### ISSUE TITLE
Support ISO 8601 timestamps

### ISSUE THREAD

**Issue by robsmith11** [plotly/plotly.js#1003]
It seems that plotly.js does not recognize an ISO 8601 timestamp with a character other than a space separating the date and time, e.g.:
`2016-10-14 18:04:52.142018000` works, but
`2016-10-14T18:04:52.142018000` is not parsed as a timestamp.

Obviously the "T" can be replaced with a space, but it would be nice to support the output of many standard JSON serializes.

**Comment by john-soklaski** [comment]
This would be helpful for us as well. We validate timestamps using JSON Schema, which requires the format described by [RFC 3339 Section 5.6](https://tools.ietf.org/html/rfc3339#section-5.6).

**Comment by alexcjohnson** [comment]
A few notes on how I'm going about this.

**One decision I'd like some feedback on:** at least for now (unless and until we build in proper timezone support), I'm leaning toward simply throwing away timezone information. That means, however, that if you have a single dataset containing dates recorded at different timezones, they will become shifted relative to each other. I think this will generally be more useful than for example shifting everything to UTC, and making some sort of smart decision about harmonizing timezones across a whole dataset is outside the scope I can tackle right now. Is this going to be a major constraint for anyone?

The formats I'm intending to support are:
- The exact syntax described in https://tools.ietf.org/html/rfc3339#section-5.6 ( 🎩 @john-soklaski ) including allowing for uppercase or lowercase T and Z, and (+/-)HH:MM timezones
- A few extensions to it, like (+/-)HHMM, and accepting the same time variants that we take for regular Plotly format dates, including fractional seconds
- But none of the extra formats described in https://en.wikipedia.org/wiki/ISO_8601 such as without the separators, or using ordinal days or week numbers

Any comments before I write this?
