### ISSUE TITLE
Line plot missing from API docs

### ISSUE THREAD

**Issue by zbjornson** [plotly/plotly.js#1005]
This page seems to be missing line charts: https://plot.ly/javascript/reference/

(although the example page exists: https://plot.ly/javascript/line-charts/)

**Comment by rreusser** [comment]
Is this the section you're looking for? https://plot.ly/javascript/reference/#scatter

I think maybe the distinction is that lines are a `mode` (in addition to markers or text) and scatter plots are the `type` of the trace.

**Comment by zbjornson** [comment]
Hrm, so it seems, thanks.

Was looking at some code I didn't write and the `type` passed to Plotly is "line". Perhaps Plotly accepts that and converts it to "scatter" type + "line" mode under the hood...

**Comment by rreusser** [comment]
Ah, that's correct. The `type` determines what sort of plot it is (scatter, contour, bar, pie, etc). _Within_ scatter plots, the `mode` may be some combination of lines, points, and text that defines what do actually _do_ with those points. I'd have to check the precise logic, but yes, but default if you pass `x`/`y` data, it's interpreted as `type: 'scatter'`.

**Comment by zbjornson** [comment]
Thanks for explaining that, makes sense. :)
