### ISSUE TITLE
restrict pan to x only or y only axis

### ISSUE THREAD

**Issue by CalvinFernandez** [plotly/plotly.js#1006]
I think it would be great if plotly allowed people to pan in the x-only direction or y only direction. This would be really nice for timeseries-like charts .

**Comment by CalvinFernandez** [comment]
also implemented here https://github.com/CalvinFernandez/plotly.js/tree/cfernandez/bindPanToAxis 

would someone mind taking a look if this is a feature that you'd be interested in?

**Comment by etpinard** [comment]
You can already do this using `fixedrange: true`: http://codepen.io/etpinard/pen/ozpERP

**Comment by CalvinFernandez** [comment]
oooo so cool!

**Comment by etpinard** [comment]
That said, some users might think your syntax is more intuitive.

Thanks for bringing this up. I guess we need better docs!
