### ISSUE TITLE
restrict scroll zoom to x or y axis 

### ISSUE THREAD

**Issue by CalvinFernandez** [plotly/plotly.js#1007]
I  think it would be useful if plotly allowed users to pin scroll zoom to the x or y axis. I think this pairs really nicely with #1006, particularly with charts like time series -- I've got a preliminary implementation here if this feature is of interest ! https://github.com/CalvinFernandez/plotly.js/tree/cfernandez/bindZoomToAxis

**Comment by etpinard** [comment]
Already possible here: http://codepen.io/etpinard/pen/kkvZKy

**Comment by CalvinFernandez** [comment]
👍

**Comment by etpinard** [comment]
Here too, thanks for bringing this up.

**Comment by jackparmer** [comment]
For folks who find this issue by Googling, this capability is possible through `layout.yaxis.fixedrange = True` (or `layout.xaxis.fixedrange = True`)

**Comment by CmpCtrl** [comment]
Is there a way to restrict the scroll zoom without affecting the ability to click and drag on the axis? I'd like the scroll to zoom in the x axis but i still want the user to be able to click and drag on the y axes to zoom or pan.

**Comment by vnadhan** [comment]
@CmpCtrl Did you manage to find a solution to your requirement?

**Comment by CmpCtrl** [comment]
I don't believe so, but its been a while. I think i mostly learned to click and drag on axes.

**Comment by alexcjohnson** [comment]
Another thing to say here: when `scrollZoom` is enabled, you can also scroll with the mouse over an axis rather than the plot area, and then you just zoom that one axis.

https://github.com/user-attachments/assets/785908da-a646-4401-8efb-4769443a7620
