### ISSUE TITLE
Custom scales or more advanced hoverinfo support

### ISSUE THREAD

**Issue by zbjornson** [plotly/plotly.js#1008]
I need to scale data with a custom function (let's say `log2`). Right now I'm doing that by:

1. Scaling my data before passing it into plotly. (easy)
2. Determining nice locations for tick marks. (sort of painful)
3. Setting `tickvals` and `ticktext` to the scaled and unscaled values, respectively. (easy enough)

This works okay, except that the hover info shows the transformed values (e.g. `log2(x)` instead of `x`). As far as I can tell, there's no way to change that. I would have to set `hoverinfo: "none"`, listen to `plotly_hover` and implement my own tooltip.

Some solutions I can think of:

1. Accept a custom scale function that would be applied to the data before plotting it, but not to the tick text or hoverinfo text. Might take some thought as far as making this work nicely with the axes code.

2. Accept a function for `hoverinfo` that is called with some data (`x`, `y`, `z`, `text`, `name` probably); return value is displayed in the hover. This goes with the workaround I listed above, but also seems like a very nice feature.

This could help with #221 and any other future requests for new scales.

**Comment by zbjornson** [comment]
Example of how my work-around falls short:

![image](https://cloud.githubusercontent.com/assets/469365/19097963/157a5f04-8a5e-11e6-93e3-2894636c7fb4.png)

**Comment by zbjornson** [comment]
Thanks for the prompt and helpful reply.

Based on the issues you linked to, it looks like I should hang on for a bit until a transform type that suits this problem is available? Or do you think it's already doable? (I don't see any docs for it yet, at least.)

(https://github.com/rreusser/plotly-basis-transform looks relevant, also!)

**Comment by etpinard** [comment]
>  it looks like I should hang on for a bit until a transform type that suits this problem is available?

We're not planning on adding a particular transform for your use case. I meant: you should start thinking about writing your own custom transform to achieve tasks of the likes.

> Or do you think it's already doable?

Yep, it's already doable. Though probably a little bit tricky. 

As you point, https://github.com/rreusser/plotly-basis-transform is probably the best example of a custom transform at the moment.

**Comment by zbjornson** [comment]
@etpinard I finally tried to use a transform to create a log2 scale, but I'm not seeing a way to solve the original problem (show `z` instead of `log2(z)` in the hover text). I made a minimal codepen working from the demo heatmap: https://codepen.io/anon/pen/mpgNwW. Is there actually a way to do this with a transform?

---

From digging, it looks like I can almost do what I want by defining a `trace._module.eventData` function, *except* for what might be a bug in fx/hover.js:

This invokes `trace._module.eventData`, which lets me define a custom `z` or `zLabel` value, cool:
https://github.com/plotly/plotly.js/blob/46483f22353d7063a59a3189648735a334d661e4/src/components/fx/hover.js#L563-L568

but then `createHoverText` is invoked with the original `hoverData`, not the data returned by `helpers.makeEventData`:
https://github.com/plotly/plotly.js/blob/46483f22353d7063a59a3189648735a334d661e4/src/components/fx/hover.js#L591

Is that intentional?

**Comment by zbjornson** [comment]
Actually, I forgot that I can make use of `text` and `hoverinfo: "text"` to define my own hover text entirely.

So, my workaround:
https://codepen.io/anon/pen/PEvYgv?editors=1010

And implemented as a transform:
https://codepen.io/anon/pen/mpgNwW?editors=1010
