### ISSUE TITLE
relayout not working in certain cases

### ISSUE THREAD

**Issue by fresheneesz** [plotly/plotly.js#1009]
I have this code that fails to relayout the width and height when an annotation is present: 

http://codepen.io/anon/pen/RGxagY?editors=102

```
<head>
  <script src="https://cdn.plot.ly/plotly-1.0.0.min.js"></script>
</head>
<body>
  <div id="graph"></div>
</body>
<script>
var x = document.createElement('div')

var layout = {annotations: [
    {text:'My Annotation', arrowcolor: 'orange', font:{color:'orange'},
     x:2, y: 2
    }
  ]
}

Plotly.newPlot(x, [{x: [1,2,3],y: [1,2,3],type: 'scatter'}], layout)

document.body.appendChild(x)

layout.width = 100
layout.height = 100

Plotly.relayout(x,layout)
</script>
```

**Comment by fresheneesz** [comment]
Tested on v1.17.1

**Comment by etpinard** [comment]
Thanks for the report

I believe this problem is related to https://github.com/plotly/plotly.js/issues/537 - but this need confirmation.

In the meantime, here's a workaround http://codepen.io/etpinard/pen/kkvEpJ

**Comment by etpinard** [comment]
Seems to be working now fine in `1.19.2`
