### ISSUE TITLE
relayout kills annotations 

### ISSUE THREAD

**Issue by fresheneesz** [plotly/plotly.js#1010]
When you have an annotation, `relayout` can destroy it in plotly v1.17.1 (since at least v1.16):

http://codepen.io/anon/pen/vXpGRV?editors=1011

```

    var layout =  {
        xaxis: {},
        yaxis: {title: "Velocity"},
        margin: {"r":0,"t":15,"b":17,"l":40},
        annotations: [
            {text:'This Month', arrowcolor: 'orange', font:{color:'orange'},
                ax: 2, ay: 2
            }
        ]
    }
    var container = document.createElement('div')

    Plotly.newPlot(container, [{x:[1,2,3],y:[1,2,3],type: 'scatter'}], layout)

    document.body.appendChild(container)
    Plotly.relayout(container,layout)
```

**Comment by etpinard** [comment]
That's the expected behavior.

The second argument to `Plotly.relayout` isn't meant to be a plotly.js `"layout"` object, but a hash-map of updates to make on the current layout.

I forked your codePen and put a few `console.log` to help you understand:

http://codepen.io/etpinard/pen/QKamkr

I hope this helps.

**Comment by fresheneesz** [comment]
"a hash-map of updates to make on the current layout"

Oh I see. That isn't very clear in the docs: https://plot.ly/javascript/plotlyjs-function-reference/#update-layout-attributes-with-plotlyrelayout

"That's the expected behavior."

I still don't understand why its expected that passing in the full layout (with the annotations) would destroy the annotation without creating a new one. It still seems like a bug to me.

**Comment by etpinard** [comment]
> That isn't very clear in the docs: 

I agree our API `Plotly` method docs aren't great at the moment.

To expand on 

> "a hash-map of updates to make on the current layout

From the example you referenced [above](https://plot.ly/javascript/plotlyjs-function-reference/#update-layout-attributes-with-plotlyrelayout):

```js
// update only values within nested objects
var update = {
    title: 'some new title',
    xaxis.range: [0, 5]
};
Plotly.relayout(graphDiv, update)
```

Here, `relayout` **updates** the graphs title to `'some new title'` and `layout.xaxis.range` value to `[0. 5]`. This syntax is (unfortunately) incompatible with `layout` object first used passed to `Plotly.plot`.

**Comment by fresheneesz** [comment]
So you can't, for example, update the entire xaxis object like this?:

```
Plotly.relayout(graphDiv, {
  xaxis = {
   range: [0,5]
  }
})
```

Are you forced to specify every individual nested property? Where can I find more information on how that format works?

**Comment by etpinard** [comment]
```js
Plotly.relayout(graphDiv, {
  xaxis: { range: [0,5] }
})
```

will indeed update the entire axis object, but in a _flat_ way. That is,

```js
Plotly.plot(gd, [ /* some data */ ], {
  xaxis: { title: 'my x axis', range: [0, 1] }
})

// and then

Plotly.relayout(gd, { xaxis: { range: [0. 5] } });

// => will clear the `layout.xaxis.title`

```

If you have more question about `Plotly.relayout`, I'd recommend taking a look at our community forums at http://community.plot.ly/

**Comment by fresheneesz** [comment]
@etpinard Could you please review my edits to the `relayout` documentation. I looked over the code and specified it as I saw it. My pull request is here: https://github.com/plotly/documentation/pull/552

"This syntax is (unfortunately) incompatible with layout object first used passed to `Plotly.plot`."

What I saw in the code, and what I documented doesn't support that statement. Even after going through the code and checking out `lib/nested_property.js`, it still seems like there's a bug somewhere. The example I wrote in my original post up there should work according to how the code is written and how it's specified. Could you please tell me what I'm missing from my spec that would cause my example up at the top to destroy the annotations?
