### ISSUE TITLE
New call signature for Plotly.plot

### ISSUE THREAD

**Issue by rreusser** [plotly/plotly.js#1014]
**Problem**: Frames cannot be passed to the initial call to `Plotly.plot`. I don't think breaking changes are required to change that fact, so this might be nice before it's integrated in a bunch of different places. You also have to unpack plotly JSON data that almost certainly has the format:

```json
{
  "data": [],
  "layout": {},
  "config": {},
  "frames": []
}
```

*(Note: config is not fully serializable)*

Currently to create a plot, you must run

```javascript
Plotly.plot(gd, d.data, d.layout, d.config).then(function() {
  return Plotly.addFrames(gd, d.frames);
});
```

### Possible solutions

It's not bad, but the extra step seems unnecessary. Alternate proposed forms that could be implemented without breaking changes by overloading `Plotly.plot`:

```javascript
Plotly.plot(gd, d.data, d.layout, d.config, d.frames);
```

Frames could simply be appended, though config seems nice as a final argument. Switching the last two arguments:

```javascript
Plotly.plot(gd, d.data, d.layout, d.frames, d.config);
```

This case could be distinguished from the current form by the presence of an Array-typed fourth argument.

Taking a different approach and passing a single object:

```javascript
Plotly.plot({
  container: gd,
  data: [],
  layout: {},
  config: {},
  frames: []
});
```

Except neither `gd` nor `config` are serializable, in general. Extracting the `gd` part, we get:

```javascript
Plotly.plot(gd, {
  data: [],
  layout: {},
  config: {},
  frames: []
});
```

I rather like this final form since with some non-serializable exceptions in `config` (specifics?), you could simply pass fetched data to`Plotly.plot` in one go, i.e.:

```javascript
fetch('path/to/my/data.json').then(function(d) {
  Plotly.plot(gd, d);
});
```

Which is nice and short, but then at the end of all of this, the conclusion is that this all exists only to save a bit of typing. I think it's still worth discussing though since it seems sub-ideal that you can't fully pass data (missing: frames) to a plot in a single command.

cc: @etpinard @chriddyp

**Comment by rreusser** [comment]
cc: @etpinard @chriddyp @alexcjohnson @bpostlethwaite

**Comment by etpinard** [comment]
> Except neither gd nor config are serializable,

I'd like to point out: it wouldn't be too hard to make `config` JSON-serializable. At the moment, only [`setBackground`](https://github.com/plotly/plotly.js/blob/dd94b9fd3bac425f3eab14ed9ffe119869fe887c/src/plot_api/plot_config.js#L87) expect a `function`. We could easily turn `setBackground` a enumerated in `v2.0.0`.

**Comment by rreusser** [comment]
Ah thanks for the clarification. I didn't know the specifics, but that doesn't sound like a show-stopper.

**Comment by etpinard** [comment]
> , but that doesn't sound like a show-stopper.

Yes, exactly.

That's why I'm voting for adding in option

```js
Plotly.plot(gd, {
  data: [],
  layout: {},
  config: {},
  frames: []
});
```

**Comment by dfcreative** [comment]
I am a bit out of context and don’t know all the details, but single argument pattern, where `container` defaults to `document.body` makes it easier to run in simple use-case, esp. for new users (who may not care or event not know about container creation, which is rather DOM thing than data-vis thing):
```js
Plotly.plot({
  data: [],
  layout: {}
});
```
Also that is common pattern for regl and other components. Though it may be not applicable here.

**Comment by rreusser** [comment]
I agree! That syntax is pretty tantalizing. The downside I see is that *all* of the other commands take the graph div as the first argument. This form might be best left for an object-oriented sort of notation that I believe was being discussed for 2.0. 

```
var plot = Plotly.plot({...})
plot.update({...})
```

**Comment by dfcreative** [comment]
Some oldschool [components](https://github.com/component/) followed the "middle way" of making first argument optional, that way not to destroy API and allow for new syntax:
```js
Plotly.plot(container?, how);
//or
Plotly.plot(how);
```
One question — why not just
```js
Plotly.plot(what, how);
//which is
Plotly.plot(data, options);
```
?

**Comment by rreusser** [comment]
Also brought up:

In [regl](https://github.com/regl-project/regl), the equivalent of `gd` is *not* required. If you don't provide a container, a div is created and expanded to fill the window. This seems rather more like plotly 2.0 syntax where `Plotly.plot` returns an object upon which you can call `.update()` etc. The usage would be:

```javascript
var plot = Ploty.plot({data: [...], layout: {}});
plot.update(...)
```

Presumably it would just make a div that fills the whole window and maintain its own reference.

**Comment by monfera** [comment]
Indeed a root is optional, e.g. a canvas or even a `gl` context can be passed (the version [here](http://bl.ocks.org/monfera/raw/85aa9627de1ae521d3ac5b26c9cd1c49/) makes a `<canvas>` directly under `<body>`). Also, for some reason, `inferno.js` gives a [warning](https://github.com/trueadm/inferno/blob/7f8ab5d2e2fa52a4131b696b809d511a053616d9/packages/inferno/dist/inferno-dom.js#L1994) when putting stuff directly into `document.body`, I'm unsure of the reasons other than perhaps [these](https://medium.com/@dan_abramov/two-weird-tricks-that-fix-react-7cf9bbdef375#.r3jt7vw7a).

**Comment by rreusser** [comment]
@monfera yeah, was at least thinking it would auto-append a `div` to `document.body` and then only operate on the *div*.

**Comment by rreusser** [comment]
@dfcreative:

> One question — why not just ...

That makes sense, but I think the short answer is to keep overloading/variadic style to a minimum. PR #1054 basically allows *two* styles: the current behavior (with parameters optionally omitted) and the new style, which is basically just the old style wrapped in an object. I think it's best to keep overloading to a minimum though, particularly in the main plot command.

**Comment by etpinard** [comment]
closed by https://github.com/plotly/plotly.js/pull/1054
