### ISSUE TITLE
Bar chart variants

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#1015]
A couple of bar chart variants will be supported by #80 but only with extra calculation and redundant data. We could express these semantically fairly easily, I would think.
- [Grouped waterfall](http://wiki.analytica.com/images/b/b3/Waterfall_chart_example.png):
  ![waterfall_chart_example](https://cloud.githubusercontent.com/assets/2678795/19140356/6794ff5e-8b5a-11e6-9baa-ae4f4c277b76.png)
  With explicit positioning this requires the user to calculate all the subtotals... can we just make this a new barmode? One complication is how to specify the total bar at the end, which ideally has _no_ data associated with it but is a trace, so that it can be styled (and named) arbitrarily.
  Would we need a separate mode for a single waterfall group? I don't think so, and keeping each component as a separate trace adds styling and labeling flexibility.
- [Grouped stacks](https://www.google.com/search?q=grouped+stacked+bar+chart&espv=2&biw=1273&bih=590&source=lnms&tbm=isch&sa=X&ved=0ahUKEwipkrCHp8XPAhXCKCYKHR0JCmoQ_AUIBigB):
  ![example-of-cluster-stacked-chart](https://cloud.githubusercontent.com/assets/2678795/19140432/2b2eacd0-8b5b-11e6-8fc8-8f914bb87b87.png)
  Seems like just another barmode plus per-trace attributes for group number or ID.

**Comment by stingh711** [comment]
Expecting grouped stack bar chart. Both echarts and highcharts support it.

**Comment by nicolaskruchten** [comment]
Another take on multiple waterfall charts: one series per waterfall.

![image](https://user-images.githubusercontent.com/203523/45898425-ef7dfe80-bda7-11e8-8585-0b27c7348d18.png)

**Comment by etpinard** [comment]
Closing. 

- Waterfalls are coming in https://github.com/plotly/plotly.js/pull/3531 and
- grouped stack setups will be possible once https://github.com/plotly/plotly.js/issues/3614 is implemented
