### ISSUE TITLE
Bar charts disappear while animating

### ISSUE THREAD

**Issue by hellochar** [plotly/plotly.js#1019]
Hey Plotly, I'm trying to animate a zoom into a bar chart (see http://codepen.io/hellochar/pen/ozEBXr), but it looks like the bar charts disappear when they're being animated? Is that something intentional or something I'm doing wrong?

Also orthogonally, it looks like many of the different layout properties aren't animated smoothly - for instance, `margin`, `width`, `height`, `bargap`, `xaxis.domain` - is this expected? 

Thanks for your time,
Xiaohan

**Comment by rreusser** [comment]
Thanks for the report, @hellochar! The short answer is that all of the animation effort so far has gone into 1) infrastructure for defining what animation means in plotly, and 2) animating scatter traces. I expected bar charts to fall back to instantaneous updates so I'm not thrilled that they simply disappear while updating.

The first step that's necessary to fix this is to work d3 element persistence into bar charts. There's some work going on with bar charts at the moment that I need to avoid conflicting with, but I'd really like to tackle them as soon as that's complete. Long story short, I think it will be about two weeks until I can get this implemented and cleaned up. Apologies for the phased implementation, but it's very helpful to hear about the interest!

**Comment by geekuillaume** [comment]
@rreusser Is there any news about it ? I'm trying to do something similar but animating the values changes. I compute every frame and call Plotly.animate on each requestAnimationFrame and I get the same behaviour (bars disappearing until the end of the animation). It works fine with scatter.

**Comment by rreusser** [comment]
One bug to fix, then I'm on it! Follow #1143 for more specific updates on bar charts.

**Comment by etpinard** [comment]
PR https://github.com/plotly/plotly.js/pull/1647 was pretty close to getting this done. :disappointed:

**Comment by parmentelat** [comment]
FWIW I could have used this feature too, animating bar charts looks like such an obvious step forward once you do bar charts in plotly
and I have to say it's a bit sad too to see these 2 previous attempts (I mean PRs) that have not been merged after all this time

So I guess it'll be native d3 instead, probably for the best btw ;)

**Comment by parmentelat** [comment]
it's not very fair to say that i'm complaining, because I'm not; I just wanted to signal that I could have used the feature if it had been available; I do feel sorry though for the chaps who wrote the PRs in question.

**Comment by woodwards** [comment]
You can do a workaround using fat lines that look like bars:

https://stackoverflow.com/questions/56623868/animate-plotly-plot-in-shiny-when-data-changes/56623991#56623991

**Comment by etpinard** [comment]
Merging into https://github.com/plotly/plotly.js/issues/3896 - which has a few recent comments.
