### ISSUE TITLE
[feature] Violin plots

### ISSUE THREAD

**Issue by deep-introspection** [plotly/plotly.js#1024]
Hi!
is there any way to render violin plots like in Python or R with Plotly?
Thanks,
Guillaume

**Comment by etpinard** [comment]
Not at the moment unfortunately.

**Comment by adrianoesch** [comment]
+1 ;)

**Comment by etpinard** [comment]
Oh I forget there was an issue about this.

Violin were implemented in https://github.com/plotly/plotly.js/pull/2116 and released in `1.32.0`
