### ISSUE TITLE
plotly.min.js overrides Promise

### ISSUE THREAD

**Issue by zllovesuki** [plotly/plotly.js#1032]
When using plotly.js with Bluebird (global scope, without Bluebird.noConflict()), loading plotly.js seems to overrides the Promise.

Bluebird 3.4.6
Plotly.js 1.17.3
Chrome 53.0.2785.143 m (64-bit)

Try this:
1. Load Bluebird
2. Load Plotly.js
3. Promise.all([]).spread()

Expected Results:
3 returns a Promise

Actual Result:
Promise.all(..).spread(..) is not a function

**Comment by zllovesuki** [comment]
maybe related to #955

**Comment by etpinard** [comment]
Yep, same problem as #955 

Importing plotly.js before Bluebird should solve the issue.

**Comment by etpinard** [comment]
https://github.com/plotly/plotly.js/pull/2994 will add a handler for `window.PlotlyConfig.MathJaxConfig` as a way to configure MathJax "on load". 

I'm thinking we could similarly add a handler e.g `window.PlotlyConfig.noPromisePolyfill` to skip over this line

https://github.com/plotly/plotly.js/blob/a070a8d2dd89f8ecbee89eecee77979298bfd886/src/core.js#L15

on load.

**Comment by archmoj** [comment]
This might be fixed by #5358.

**Comment by alexcjohnson** [comment]
This one we should explicitly test (manually, once, I don't see it as requiring a CI test) before closing.

**Comment by archmoj** [comment]
> This one we should explicitly test (manually, once, I don't see it as requiring a CI test) before closing.

Tested. It is fixed on master.
