### ISSUE TITLE
Emit relayout event on geo plot pan/zoom

### ISSUE THREAD

**Issue by yannouchou** [plotly/plotly.js#1034]
Unless I'm missing something, I'm not getting any event fired from plot.ly on rescaling the geo plots (the mapbox plots work fine though).

Thx!

**Comment by etpinard** [comment]
That's correct.

Unfortunately, `relayout` on geo subplots is pretty buggy at the moment (see https://github.com/plotly/plotly.js/issues/292) so I don't it's worth spending time on this until #292 is fixed.

I'll merge your issue with #292.

Thanks for the report.
