### ISSUE TITLE
Toggle all traces (not delete and newplot)

### ISSUE THREAD

**Issue by alok-sin** [plotly/plotly.js#1042]
I want to deselect all traces (toggle, not delete) via js/jQuery. There seems to be no function associated in the core library.

I triggered a click via : 
```
jQuery.each(jQuery.("legendtoggle"), function(){ 
  jQuery(this).jQuery.trigger("click");
});
```

But this does not show the intended purpose.

**Comment by etpinard** [comment]
You mean something like: http://codepen.io/etpinard/pen/jrpZLG

**Comment by etpinard** [comment]
Closing.

This question is better suited for http://community.plot.ly/ than here.
