### ISSUE TITLE
Scattergeo crashing on unrecognized country names in 1.18

### ISSUE THREAD

**Issue by yannouchou** [plotly/plotly.js#1043]
Just upgraded to 1.18 and my scattergeo plots are now messed up when I feed them with country names it doesn't recognize.
Bubbles are drawn fine until a country is unknown, and from there onwards they're all drawn at (0,0).
Bug reproduced at https://jsfiddle.net/115n60og/
(replacing 'Tromelin Island' with 'France' fixes it).

**Comment by etpinard** [comment]
thanks for the report.
