### ISSUE TITLE
Resize is broken in 1.18.0

### ISSUE THREAD

**Issue by sporto** [plotly/plotly.js#1051]
In 1.18.0 when you resize a chart using `Plotly.Plots.resize` only part of it resizes.

You can see this behaviour here

http://codepen.io/sporto/pen/amRzGw?editors=1010

Make the window smaller or bigger in big increments, notice how the x axis seems to resize but the chart itself stays as the same size as before.

This is not noticible when the window resize is done in small increments. This works fine in 1.17.3

**Comment by rreusser** [comment]
I think this is solved by @etpinard's PR from today, #1049. We're going to release that as `1.18.1` tomorrow, so that should fix it, I hope. Thanks for reporting!

**Comment by etpinard** [comment]
@sporto can you confirm this bug is fixed in `1.18.1`:

http://codepen.io/etpinard/pen/QKkqXr

Thank you.

**Comment by sporto** [comment]
Yes, fixed thanks
