### ISSUE TITLE
Error rendering plot with phantomjs

### ISSUE THREAD

**Issue by JordanBallew** [plotly/plotly.js#1053]
When I try to render a heatmap with phantomjs I get the following error:
```
TypeError: undefined is not a constructor (evaluating 'ArrayBuffer.isView(t)')

  https://cdn.plot.ly/plotly-latest.min.js:48 in exports
  https://cdn.plot.ly/plotly-latest.min.js:48 in i
  https://cdn.plot.ly/plotly-latest.min.js:48
  https://cdn.plot.ly/plotly-latest.min.js:48 in coerceFunction
  https://cdn.plot.ly/plotly-latest.min.js:48 in coerce
  https://cdn.plot.ly/plotly-latest.min.js:59 in u
  https://cdn.plot.ly/plotly-latest.min.js:44 in exports
  https://cdn.plot.ly/plotly-latest.min.js:59 in exports
  https://cdn.plot.ly/plotly-latest.min.js:56 in supplyTraceDefaults
  https://cdn.plot.ly/plotly-latest.min.js:56 in supplyDataDefaults
  https://cdn.plot.ly/plotly-latest.min.js:56 in supplyDefaults
  https://cdn.plot.ly/plotly-latest.min.js:50 in plot
  https://cdn.plot.ly/plotly-latest.min.js:50 in newPlot
```

This behavior seems to have started in 1.17.0. It works fine in 1.16.3. I am using [phantomjs 2.1.1](http://phantomjs.org/download.html). I have attached an example that can be run by the following command:

`./phantomjs.exe test.js`

The example assumes everything is in the current directory. It is rendering the Annotated Heatmap example from the plotly docs.

[phantomjs-test.zip](https://github.com/plotly/plotly.js/files/537304/phantomjs-test.zip)

**Comment by etpinard** [comment]
Looks like you'll need a typed array polyfill.

**Comment by JordanBallew** [comment]
Does that mean that it's likely a phantomjs ES6 support issue?

**Comment by etpinard** [comment]
> ES6 support issue?

Even worse than that. Typed arrays are a pretty old feature in most browsers 

![image](https://cloud.githubusercontent.com/assets/6675409/19496307/e503afa4-9554-11e6-80be-1ac548c24127.png)

ref: https://developer.mozilla.org/en/docs/Web/JavaScript/Typed_arrays

**Comment by rreusser** [comment]
I was curious. http://phantomjs.org/faq.html

> Q: Which WebKit version is used by PhantomJS?
>
> If you really like to get the WebKit version, find it via the user agent, run the examples/useragent.js. The actual version depends on the libraries with which PhantomJS was compiled.

**Comment by JordanBallew** [comment]
For phantomjs 2.1.1 for Windows I get
```
The default user agent is Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/538.1 
(KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1
```

**Comment by rreusser** [comment]
Is webkit for windows supported anymore? https://en.wikipedia.org/wiki/Safari_version_history

**Comment by etpinard** [comment]
@JordanBallew I'm going to close this issue.

plotly.js has been requiring an environment with typed arrays support since `v1.0.0` for the heatmap trace type, so we won't consider your report a _breaking change_.

I'd recommend taking a look at our distributed file [docs](https://github.com/plotly/plotly.js/tree/master/dist#using-distributed-files) and more specifically the typed-array [polyfill](https://github.com/plotly/plotly.js/blob/master/dist/extras/typedarray.min.js).

Thanks again very writing in.

**Comment by JordanBallew** [comment]
Yeah, it doesn't really seem like your problem at this point. We have the work around of using 1.16.3 for working with phantomjs at this point. I'll look into your suggestions when I get a chance, and I'll report back if I find a better solution. Thanks for the help.

**Comment by waTeim** [comment]
I had the same problem.  Strangely `ArrayBuffer.isView` is not implemented by many polyfills including the one referenced above. However, [this polyfill](https://github.com/inexorabletash/polyfill) does implement it.  

```
polyfill.js (minified: polyfill.min.js) has everything in web.js plus es5.js and es6.js and es2016.js
```

Include the minified polyfill before plotly and it works fine.  e.g.

    <head>
      <script src="/polyfill.min.js"></script>
      <script src="/plotly.min.js"></script>
    </head>
