### ISSUE TITLE
x-axis hover-text in a scatter graph extends below the rest of the graph

### ISSUE THREAD

**Issue by fresheneesz** [plotly/plotly.js#1056]
When you hover over a point in a scatter graph, two items of hover-text show up pointing out the specific y and x values for that point. The problems is that the x value extends below the graph such that if you size the graph so that everything is visible (including the x-axis increment labels) the hover text for the x-axis is cut off. 

Here's an example: http://codepen.io/anon/pen/ozaRQm

If you hover over any point there, you'll notice the hover text at the bottom is cut off.

**Comment by etpinard** [comment]
Thanks for the report.

Bottom margin dimensions aren't taken into consideration in the placement of the on-axis hover label at the moment.

Bumping `layout.margin.b` to about 30, fixes the issue http://codepen.io/etpinard/pen/pEQbxO

**Comment by fresheneesz** [comment]
Gotcha. Is taking margin dimensions into consideration planned on being added?

**Comment by etpinard** [comment]
> Is taking margin dimensions into consideration planned on being added?

Yep, for sure. It will be a very low priority for us for the next few months though.

**Comment by fresheneesz** [comment]
Ok. Is there any way of modifying the position of that marker?

**Comment by etpinard** [comment]
> Ok. Is there any way of modifying the position of that marker?

You mean the position of the hover label? If so, you might want to look into custom hover event handlers as displayed at https://plot.ly/javascript/hover-events/

**Comment by fresheneesz** [comment]
Thanks I'll take a look!

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
