### ISSUE TITLE
Unbind click event

### ISSUE THREAD

**Issue by caalberts** [plotly/plotly.js#107]
Hi, I have a single page application which contains a plotly chart with click event handler in it. I have another function which removes the chart and plot a new chart after certain events.
```
Plotly.newPlot(plotSpace, data, layout)
plotSpace.on('plotly_click', click => {
  listAllTransactions(town, click.points[0].data.name, click.points[0].x)
})
```

Each time the plot is replaced with a new one, the event handler from the previous chart is carried over to the new chart, so a click on the new chart will trigger `listAllTransactions` twice: first with `town` from the first chart and second with `town` from the second chart.

How can I remove the event handler from the first chart? I've tried removeEventHandler to no avail.

**Comment by caalberts** [comment]
A workaround I used was to completely remove `plotSpace` before recreating it for the new plot, thus removing the previous event listener.

Appreciate if anyone has a more elegant solution

**Comment by etpinard** [comment]
@caalberts Thanks for writing in. 

I'd vote for making `Plotly.newPlot` unbind all events for the `div` (`plotSpace` in your case).

@mdtusz @alexcjohnson @cldougl thoughts?

**Comment by mdtusz** [comment]
:+1:  `Plotly.newPlot` should be fresh.

**Comment by cldougl** [comment]
:+1: sounds like a good idea

**Comment by mdtusz** [comment]
@caalberts should be in the next release after this pr: https://github.com/plotly/plotly.js/pull/117

**Comment by caalberts** [comment]
:ok:

**Comment by mdtusz** [comment]
Fixed in https://github.com/plotly/plotly.js/pull/117

**Comment by chriddyp** [comment]
Is there any other way to remove or rebind existing handlers without calling `newPlot`?

**Comment by alexcjohnson** [comment]
I don't see that we document or test this anywhere, but we do support [removeListener and removeAllListeners](https://github.com/plotly/plotly.js/blob/master/src/lib/events.js#L55-L58) from the npm [`events`](https://nodejs.org/api/events.html#events_emitter_removealllisteners_eventname) module:

```js
function logIt(e) { console.log(e) }

gd.on('plotly_relayout', logIt)

Plotly.relayout(gd, {'xaxis.range': [-1,5]})
// here the listener is invoked
> Object {xaxis.range: Array[2]}
> Promise {[[PromiseStatus]]: "resolved", [[PromiseValue]]: div#graph.dashboard-plot.js-plotly-plot}

gd.removeListener('plotly_relayout', logIt)

Plotly.relayout(gd, {'xaxis.range': [-2,6]})
// now the listener is not invoked
> Promise {[[PromiseStatus]]: "resolved", [[PromiseValue]]: div#graph.dashboard-plot.js-plotly-plot}
```
