### ISSUE TITLE
Scatter (sometimes) draw line incorrectly through markers

### ISSUE THREAD

**Issue by eulerreich** [plotly/plotly.js#108]
If I zoom in on a scatter plot of 'markers+lines', sometimes the line isn't drawn correctly through the markers.
![image](https://cloud.githubusercontent.com/assets/4183609/11769931/442514e6-a1b8-11e5-8c2e-b801d7241f3d.png)

I've been having this issue since before 1.9.x and now I'm on 1.9.3 and it's still there.

**Comment by etpinard** [comment]
Copied from https://github.com/plotly/plotly.js/blob/master/CONTRIBUTING.md#opening-issues :

Bug reports must be accompanied with a reproducible example. We recommend using
[codepen](http://codepen.io/), [jsfiddle](https://jsfiddle.net/) or [jsbin](https://jsbin.com) to share your example.

**Comment by etpinard** [comment]
@eulerreich or in your case a reproducible python code snippet of https://plot.ly URL.

**Comment by eulerreich** [comment]
Here's an URL https://plot.ly/2766/~lincolnWSforce/

**Comment by etpinard** [comment]
@eulerreich that plot is private. Could you [share it](http://help.plot.ly/how-to-share-and-print-plotly-graphs/) with me at etienne@plot.ly. Thanks.

**Comment by etpinard** [comment]
@eulerreich Looks like you have (maybe accidentally) deleted the plot's associated grid or made it private. I can't see your graph's data.

**Comment by eulerreich** [comment]
I realized that and sent you a second copy of it? Did you get that second
one?

**Comment by etpinard** [comment]
@eulerreich Could you resend me the working copy?

**Comment by eulerreich** [comment]
I just resent it.

**Comment by etpinard** [comment]
@eulerreich Bug confirmed (in both the latest Chrome and Firefox). Thanks for this report.

Here's a minimal example showing the bug: http://codepen.io/etpinard/pen/KVNwQR?

No obvious reason why this bug could happen comes to mind.

Maybe some rounding error in the line decimation algorithm (cc @alexcjohnson ) ?

Note that hover picks out the 'correct' value when `mode: 'markers+lines'`

**Comment by etpinard** [comment]
fixed via https://github.com/plotly/plotly.js/pull/353
