### ISSUE TITLE
hovervalues for candlestick charts

### ISSUE THREAD

**Issue by VeraZab** [plotly/plotly.js#1082]
Should the choices of values shown on hover (hoverinfo) for financial charts not be: x, open, high, low, close, text?

http://codepen.io/veraz/pen/ZpPxyZ?editors=1010

![screen shot 2016-10-25 at 10 32 15 am](https://cloud.githubusercontent.com/assets/4257572/19690359/8dee3bd6-9a9e-11e6-87d8-e75d3de559fe.png)

**Comment by etpinard** [comment]
Maybe in an ideal world. But `box` (the trace type that `candlestick` depend upon) hover text isn't configurable (apart from `'name'` and `'none'`) at the moment.
