### ISSUE TITLE
Problems with addTraces and scattergl

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#1083]
http://codepen.io/cpsievert/pen/LRamoV/

This pen actually crashed my browser,  but I've also seen this error trying to do a similar thing with version 1.18.1

```
WebGL: INVALID_OPERATION: drawArrays: no buffer is bound to enabled attribute
```

**Comment by etpinard** [comment]
another potential issue for @dfcreative

**Comment by dfcreative** [comment]
Ok

**Comment by dfcreative** [comment]
Hm.
```js
let data = [{x:[...], y:[...]}];
Plotly.plot(container, data);
Plotly.addTraces(container, data); //← we pass already existing data
```
What is expected behaviour when we try to add existing data? Should we ignore it or copy it to new trace @etpinard?

**Comment by dfcreative** [comment]
https://github.com/plotly/plotly.js/pull/1136 should help with that.

**Comment by etpinard** [comment]
Oh. Actually, this has nothing to do with the gl2d code - as @dfcreative points out in #1136.

More generally, @cpsievert, what do you expect to happen here? In your codepen, you're calling `addTraces` with the same trace object as in your first `plot` call. Should `addTraces` add a second (identical) trace to the graph? Or should `addTraces` look up its uid to figure out that the user wants to update the existing trace instead?

**Comment by cpsievert** [comment]
> Should `addTraces` add a second (identical) trace to the graph? 

yea, that's what I would want/expect

**Comment by etpinard** [comment]
thanks @cpsievert :beers:
