### ISSUE TITLE
Tick label position incorrect for PDF and PNG with extra resolution

### ISSUE THREAD

**Issue by chrisjcameron** [plotly/plotly.js#109]
In the sample plot linked below, the Y axis labels have three spaces as the ticksuffix to avoid hugging the axis too closely with the larger font. This looks fine when viewed in the Jupyter notebook or online at plot.ly. If I download the figure in PNG format, it looks fine. If I select PNG with extra resolution or PDF format, the suffix spacing is ignored. This seems like a bug in the compositing. 

Standard Res PNG
![demo](https://cloud.githubusercontent.com/assets/1383080/11785912/e2c3a9de-a251-11e5-8da8-21906902ad8a.png)

High Res PNG
![demo_high_res](https://cloud.githubusercontent.com/assets/1383080/11785910/e224939e-a251-11e5-83d3-6b5ef101ad22.png)

Original file located at https://plot.ly/~chris.j.cameron/95/proportion-of-nodes-adopted-vs-time-steps/

**Comment by etpinard** [comment]
@chrisjcameron Bug confirmed. Thanks

**Comment by etpinard** [comment]
This may be related to our use of [`class="crisp"`](https://github.com/plotly/plotly.js/blob/a27d62ca9b157db473e2a3bd8b51634fff2433b5/src/css/_base.scss#L23) in the axis drawing [code](https://github.com/plotly/plotly.js/blob/a27d62ca9b157db473e2a3bd8b51634fff2433b5/src/plots/cartesian/axes.js#L1427). 

I doubt that batik understands DOM classes.

**Comment by etpinard** [comment]
Closing. This bug isn't related to plotly.js, but to our image-exporting services.
