### ISSUE TITLE
Inverted axes feature

### ISSUE THREAD

**Issue by crayxt** [plotly/plotly.js#1092]
Dear developers,

Could you please suggest whether there is any plan to implement Chart Invertion? (see highcharts' option for reference http://api.highcharts.com/highcharts/chart.inverted, demo: http://www.highcharts.com/demo/area-inverted)

Thanks,

**Comment by etpinard** [comment]
The basically what `orientation` does, correct? See [example](http://codepen.io/etpinard/pen/PGvoKx).

**Comment by crayxt** [comment]
It looks like it is not avalable for area (scatter) plots

**Comment by crayxt** [comment]
Seems like outdated.
