### ISSUE TITLE
heatmaps don't respect axis categoryarray

### ISSUE THREAD

**Issue by hellochar** [plotly/plotly.js#1097]
Hey Plotly,

It looks like you can use `axis.categoryarray` to reorder the bars in a bar chart. I'm trying to do the same thing with heatmaps (that is, reorder the heatmap columns) but it only seems to change the tick labels, not actually move the data. See http://codepen.io/hellochar/pen/WGBEow . This is concerning since the data being displayed is not longer accurate to the data that was fed in.

 Is there another way to specify the heatmap ordering, other than by modifying the x/y arrays manually?

**Comment by etpinard** [comment]
Thank very much for the report.

**Comment by rcrezende** [comment]
any plans to fix it?

**Comment by etpinard** [comment]
> any plans to fix it?

yes, that's what the `type: bug` label means.

**Comment by antoinerg** [comment]
Proof of principle in branch [`issue-1097`](https://github.com/plotly/plotly.js/compare/issue-1097)

Codepen before: https://codepen.io/antoinerg/pen/bJyOjX
Codepen after: https://codepen.io/antoinerg/pen/EJzGdv

Still need to write test and support `multicategory`

**Comment by etpinard** [comment]
Looking good @antoinerg - thanks for taking this on!

**Comment by antoinerg** [comment]
@etpinard About `multicategory` axes, it seems like `categoryorder` isn't implemented for it (https://github.com/plotly/plotly.js/issues/3723#issuecomment-479895345). I will not tackle this here.

**Comment by etpinard** [comment]
> About `multicategory` axes, it seems like `categoryorder` isn't implemented for it

Yes, that's correct. My bad!
