### ISSUE TITLE
scattergl error: Cannot read property 'drawingBufferWidth' of null

### ISSUE THREAD

**Issue by jessetabak** [plotly/plotly.js#1100]
When I create a 'scatter' graph it works fine, but when I use type 'scattergl' it will give this error.
The plotly library calls createGLPlot2D(options), options.gl is null, which gives this error.

Scatter example (which works):
http://codepen.io/anon/pen/amgRLX

Scattergl example (which does not work):
http://codepen.io/anon/pen/WGqaXE

Even on the plot.ly site I'm getting this error.

/update: It seems to be a Chrome thing, didn't have this problem 1 or 2 weeks ago, so it looks like something new. It works fine in Firefox and IE Edge.

/update2: Looks like it's just on my machine... on other machines it seems to work fine..

**Comment by etpinard** [comment]
Things are looking ok on my machine too.

What computer are you using?

We did make several changes to WebGL calls last week's `1.19.x` release. @monfera any insights on this topic?

**Comment by monfera** [comment]
@jessetabak thanks for the report!

From the error message it looks like some kind of WebGL context loss (it's used as `gl.drawingBufferWidth`). I don't have a good idea for why it happens right now as the problem doesn't appear on my device / OS / browser permutations either. 

Can you share details about your setup, e.g. vintage, type of GPU (or integrated), OS, Chrome version number etc.?

Also, could you please identify the program line where it happens? If you have the developer console open, it should break at the appropriate line.

**Comment by monfera** [comment]
@jessetabak one more thing to try: do you get a proper render if you change to this:
```
mode: 'markers+lines'
```
Or alternatively, to 
```
marker: {size: [12, 12, 12, 12]}
```

**Comment by jessetabak** [comment]
@monfera @etpinard Seems like it was just a glitch on my machine, after a reboot it worked fine.

**Comment by etpinard** [comment]
@jessetabak no worries. Thanks for writing in!
