### ISSUE TITLE
Shapes cover the traces

### ISSUE THREAD

**Issue by empet** [plotly/plotly.js#1102]
Long time ago, when I worked for the first time with shapes I realized that it would be more convenient if shapes were defined   as data traces, because a Data object is a list, and we could append the Shape trace first, and then other traces.
Being defined in layout, they are  always plotted over traces, hiding parts of them: https://plot.ly/~empet/14032
I propose to discuss this issue and if it possible to define  'shape' as  a new chart  type.

**Comment by etpinard** [comment]
Hi,

You can now draw shapes below data traces by `layer: 'below'` to each shape container.

See live example : https://plot.ly/~etpinard/7441/

and associated python code: https://plot.ly/~etpinard/7441.py

**Comment by empet** [comment]
I didn't know that there was introduced the key layer. Thank you very much!!
