### ISSUE TITLE
Plot from .json file

### ISSUE THREAD

**Issue by SimoneTosato** [plotly/plotly.js#1104]
Hi,
I'm currently developing an app based on Electron and i'm implementing real time plotting of a timeseries using plotly.js. Currently i'm using `lowdb` to create a json file in which I save my `(x,y)` points and some other infos, is it possible in plotly to use the file as a source to plot data from? I hope this is not a duplicated issue, i haven't found anything about this yet. 
If it could be useful my .json file has the following structure
```
{
    '_data_':[
        { 'series': , 'timestamp': , 'value': }
        .
        .
        .
   ],
  'other data'....
}
```

**Comment by etpinard** [comment]
plotly.js has no notion of _source plot data_. In essence, plotly.js can only plot coordinates (e.g. `x`, `y`) arrays out of the box.

So, you can either convert your json into `x` and `y` arrays as e.g. 

```js
Plotly.plot('graph', [{
  x: _data_.map((d) => d.timestamp),
  y: _data_.map((d) => d.value)
}])
```

or write + register a custom transform [plugin](https://github.com/plotly/plotly.js/pull/499). See example: http://codepen.io/etpinard/pen/mrNvbg

**Comment by etpinard** [comment]
Closing the issue.

Further questions may be asked on https://community.plot.ly/
