### ISSUE TITLE
Hover text appears at wrong position in bar charts

### ISSUE THREAD

**Issue by mkraeva-astea** [plotly/plotly.js#1105]
Using the latest plotly versions (1.19.0, 1.19.1), hover text in bar charts does not appear directly next to the selected bar; it is displayed with some offset in the next bar to the right. 
[Example: https://jsfiddle.net/tjj2wems/](https://jsfiddle.net/tjj2wems/)

The same fiddle works correctly when switching to https://cdn.plot.ly/plotly-1.18.1.min.js

**Comment by etpinard** [comment]
Yikes. Thanks very much for this bug report!

**Comment by etpinard** [comment]
This is likely a regression coming from @n-riesco's https://github.com/plotly/plotly.js/pull/1075
