### ISSUE TITLE
texttemplate for heatmaps & histogram2d traces

### ISSUE THREAD

**Issue by colinfang** [plotly/plotly.js#1116]
For a heatmap, it is not very easy to do annotations that simply show text for each grid. (One has to specify `x, xref, y, yref, ...`.

Can we borrow the idea from `scatter`, by introducing a `mode` parameter that allows to display text as well as marker/line?

**Comment by etpinard** [comment]
Interesting.

> Can we borrow the idea from scatter, by introducing a mode parameter that allows to display text as well as marker/line?

Why not use a scatter trace on top of the heatmap trace?

**Comment by colinfang** [comment]
Then I have to make nrows scatter traces, which seems worse than the existing annotations.

If we are allowed to use `mode = 'text'`, to print `z` values for heatmap can be as simple as

    Heatmap(z=z, text=z, mode='text')

**Comment by mafar** [comment]
i translated ```create_annotated_heatmap```  python plotly.py to js here as standalone.
https://github.com/plotly/plotly.js/issues/4116
 i hope it gets integrated.

**Comment by Carl-Analytix** [comment]
This should be done in my opinion. I dont like using figurefactory for subplotting heatmaps.  It is a pain extracting all the data out and making sure you have everything to be placed in the new subplot correctly. The same goes for annotations when doing a go.Heatmap.  This utility would be great, especially if you could adjust the size, family, and color of the text.  Maybe an annotation kwarg would be ideal for Heatmap types.  And something to control word wrapping?

**Comment by wiznotwiz** [comment]
Was this ever added? It's such a pain to manually create the values for annotating when they're already there in the tooltip to use.

**Comment by nicolaskruchten** [comment]
We definitely want to do this, and it would be great to get an outside contributor to help :)

**Comment by archmoj** [comment]
Instead of a text `mode`, it looks like `texttemplate` could/should be added.

**Comment by nicolaskruchten** [comment]
Yeah let's not add a mode, let's add a showtext attribute or something and trettemplate
