### ISSUE TITLE
Heatmap should look up category position when building brick data

### ISSUE THREAD

**Issue by colinfang** [plotly/plotly.js#1117]
The 2nd plot should start at `Team B`, instead of `Team A`.

```{python}
fig = make_subplots(rows=2, cols=1, shared_yaxes=True, shared_xaxes=True)

z = [[.1, .3, .5],  
     [1.0, .8, .6],
     [.6, .4, .2]]

x = ['Team A', 'Team B', 'Team C']
y = ['Game Three', 'Game Two', 'Game One']

fig.append_trace(go.Heatmap(z=z, x=x, y=y), 1, 1)

z = [[.3, .5],  
     [.8, .6],
     [.4, .2]]

x = ['Team B', 'Team C']
y = ['Game Three', 'Game Two', 'Game One']

fig.append_trace(go.Heatmap(z=z, x=x, y=y), 2, 1)
iplot(fig)
```

```
fig.data

[{'type': 'heatmap',
  'x': ['Team A', 'Team B', 'Team C'],
  'xaxis': 'x1',
  'y': ['Game Three', 'Game Two', 'Game One'],
  'z': [[.1, .3, .5],  
     [1.0, .8, .6],
     [.6, .4, .2]],
  'yaxis': 'y1'},
 {'type': 'heatmap',
  'x': ['Team B', 'Team C'],
  'xaxis': 'x1',
  'y': ['Game Three', 'Game Two', 'Game One'],
  'z': [[.3, .5],  
     [.8, .6],
     [.4, .2]],
  'yaxis': 'y2'}]

fig.layout

{'xaxis1': {'anchor': 'y2', 'domain': [0.0, 1.0]},
 'yaxis1': {'anchor': 'free', 'domain': [0.575, 1.0], 'position': 0.0},
 'yaxis2': {'anchor': 'x1', 'domain': [0.0, 0.425]}}
```
![newplot 6](https://cloud.githubusercontent.com/assets/1499555/20067835/9211efc6-a50e-11e6-9bdb-44d22b892d9a.png)

https://codepen.io/anon/pen/qqdqWq

**Comment by etpinard** [comment]
replacing

```py
x = ['Team B', 'Team C']
```

with 

```py
x = [null, 'Team B', 'Team C']
```

should do the trick.

**Comment by colinfang** [comment]
It doesn't work in JS.

I hope this is a bug instead of expected behaviour, as in Bar plot the shared axis do align on the name.

**Comment by etpinard** [comment]
Ha I see. You're expecting each `z` column to shift in accordance with `x`. 

I believe this is the result of the same underlying issue as https://github.com/plotly/plotly.js/issues/1097

Here's a way to work around the problem: https://codepen.io/etpinard/pen/QGbGNP

**Comment by etpinard** [comment]
@colinfang thanks for posting :beers: 

Next time, to make our lives a little easier, please don't make references to the plotly.py API (or any other API library) in this repo. It can make things a little confusing on how to approach the issue. A reproducible codepen suffices.

**Comment by etpinard** [comment]
**Update**: solving this problem and https://github.com/plotly/plotly.js/issues/1097 in general is a little harder than I thought. 

At the moment, the heatmap plotting routine fails when `x` and `y` are unsorted (even when `x` and `y` are numerical - see http://codepen.io/etpinard/pen/RoKGpj)

So, I think we'll need to order `x` and `y` and rearrange `z` in the calc step.  From [`heatmap/plot.js`](https://github.com/plotly/plotly.js/blob/5971c1694893fd506adec2f6d4ab03c546adedcf/src/traces/heatmap/plot.js#L64-L66) this issue isn't news.

```js

    // TODO: if there are multiple overlapping categorical heatmaps,
    // or if we allow category sorting, then the categories may not be
    // sequential... may need to reorder and/or expand z
```
