### ISSUE TITLE
Filtering Transform: Inequality + Category data bug

### ISSUE THREAD

**Issue by bpostlethwaite** [plotly/plotly.js#1119]
The > and < operations seem to be reversed. See http://codepen.io/bpostlethwaite/pen/KNpgae

One would expect the first trace with the LESS_THAN operator to contain _more_ points since we are filtering on 'c' and the other values are 'a' and 'b'.

**Comment by bpostlethwaite** [comment]
No codepen but some further testing shows that this also applies to the Range operators such as `()` and `)(`

**Comment by etpinard** [comment]
That's very possible. Here's the only test [case](https://github.com/plotly/plotly.js/blob/38aa4b3841752adaae010f28ba1647c7a7128107/test/jasmine/tests/transform_filter_test.js#L642-L647) for categorical `target: [/* */]`.
