### ISSUE TITLE
How does plotly automatically rotate the x axis label when it's too long?

### ISSUE THREAD

**Issue by cqcn1991** [plotly/plotly.js#1123]
Just curious, don't know how to search for the source code

I want to know how plotlyjs rotate the axis label so that 
![qq](https://cloud.githubusercontent.com/assets/2425141/20125967/5cce729e-a66c-11e6-8a46-daf73dac1761.png)

becomes this

![qq 2](https://cloud.githubusercontent.com/assets/2425141/20125973/6da5a038-a66c-11e6-8fe8-e24afb10674d.png)

Codepen:
http://codepen.io/plotly/pen/4f14500e8ce23a9b39cd100ccc59425d

**Comment by etpinard** [comment]
There's an attribute for called [`tickangle`](https://plot.ly/javascript/reference/#layout-xaxis-tickangle) that does just that. 

When `tickangle` is unset, plotly.js tries to be smart: it first draws the tick labels horizontally (vertically) on x (y) axis, it then detects if axis labels are overlapping, if so it rotates them to 30 degree or 90 degrees depending on their tick spacing and font size.

The relevant code is [here](https://github.com/plotly/plotly.js/blob/c883e57657673ff9860606eb30e422c0b25c3db1/src/plots/cartesian/axes.js#L1752-L1806).

---------

For questions of the likes, we recommend using our community forums at https://community.plot.ly/ that way other users can benefit for our answers.
