### ISSUE TITLE
repeated adding - removing trace in animation mode fails

### ISSUE THREAD

**Issue by Quath** [plotly/plotly.js#1129]
When you have a page where you can add to an existing plot a trace (for instance if you want to compare 2 populations), and you repeatedly (thus more than once) add and remove and add again the additional trace within animation mode => the second time you add the trace, it isn't displayed (though it is in the frame definition!!!).

Since the description is a bit "vague" I've made a fiddle which tends to reproduce this effect. 
[https://fiddle.jshell.net/Quath/fzxavfq9/](https://fiddle.jshell.net/Quath/fzxavfq9/)

You'll notice that it works fine the first time you click on the "add" button. Then, on the "delete", you come back to one trace (ok almost ... my example fails here, but I succeeded in the real code to have only one trace --using ng-if and $onDestroy, so let's not bother on that). And when you click on the "add" again ... well the data is there (see console log) but the additional trace isn't.

**Comment by rreusser** [comment]
Thanks for the report! Can you clarify the result you're after? It looks like your delete button just executes a redraw, but that the redraw function adds/removes traces, so I'm not 100% sure what it should be doing. Are you trying to fade in and out traces? If so, I made a quick codepen that might help. http://codepen.io/rsreusser/pen/BQjyvZ?editors=0010 (Unless I'm wrong, it looks like the trace opacity does not animate (it should! I'll fix asap, see: #1130), but I've used the line color to animate enter.)

**Comment by Quath** [comment]
Oh sorry if I'm unclear. What I want is that I can add and remove a trace (it's actually happening in the html template) repeatedly. The thing is that I don't know in advance what's the data of the other trace, thus I can hardly use the opacity trick (though, if nothing else works I'll try this out). 
The example in the fiddle is a very simplified version of what I have in my code: 
 - on add, you add a trace and redraw,
 - on delete, you return to the original data-set. 
Though, in the real code, it's just one button -> you activate 2 traces or you're back to one trace.

What I'd want, is that the behavior of the plot remains the same however N times I click on the button (thus alternating between adding-removing a trace). 

Was that clearer?

**Comment by rreusser** [comment]
In my example I created a trace with opacity:0 using `.addTraces` and then *immediately* faded it in with `.animate`. The same could be done for fading out (in pseudocode): `Plotly.animate(... set the opacity to zero...).then(function () { Plotly.deleteTraces(... delete the trace ...)});`

I'm not necessarily opposed to `Plotly.animate` handling this in one go, but I'd need to investigate further. In the mean time, does this solution work for you?

**Comment by etpinard** [comment]
@Quath it's probably more robust to _delete_ traces by animating them to a `visible: false` frame at the moment.

**Comment by Quath** [comment]
OK, I'll try this out. Thanks for the suggestions!!

**Comment by rreusser** [comment]
Just backing up a bit, my feedback on a higher level is: do you really need animation? The part that wasn't clear to me is precisely *which* part of the sequence you wanted animated. It sounds like either visibility or `addTrace` + `deleteTrace` might be a better fit unless you're particularly aiming for tweening/fading, in which case I think it can be accomplished, just with a bit more work.

**Comment by Quath** [comment]
hmmmm.... I may not need animation when I add/remove the trace. But afterwards, when the traces are modified, yes. 
I'll keep both suggestions in mind to try out. 

Thanks again for your quick answers and suggestions (and probably till the next "bug" ... )

**Comment by rreusser** [comment]
No problem! Again, all of this feedback helps and influences future decisions! The plotly forum would also be a good place to ask questions that may not be bugs, but glad to help!

**Comment by rreusser** [comment]
@Quath: I've submitted a PR that fixes the opacity animation issue. It's not merged yet, but hopefully it will make its way in in the next release or two. See: #1146

**Comment by Quath** [comment]
@rreusser Oh great!!
I've implemented in the end your second suggestion: avoid having animation when adding/removing a trace, and reinstalling them afterward and it works like a charm now!!! Thus: Thanks!!

**Comment by etpinard** [comment]
Looks like this issue was given a working workaround. Closing.
