### ISSUE TITLE
Scatter to-zero fills don't honored gaps in coordinates

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#1132]
See http://codepen.io/etpinard/pen/GNorWw

Where (I believe) the desired behavior would show two fill rectangles spanning from the line segments down to `y=0`.

First reported on https://community.plot.ly/t/area-chart-is-not-breaking-at-null-values/2652

**Comment by rreusser** [comment]
@etpinard This is a big right, not a regression? Something must have changed so that I didn't immediately succeed in rolling back the version to check.

**Comment by etpinard** [comment]
@rreusser it's not a regression. No stress.

**Comment by morganh35** [comment]
@etpinard is there any update on this bug? Has anyone started work on it? 
If not, if you can point me in the right direction I could give it a go. 

Thanks!

**Comment by rreusser** [comment]
@morganh35 Currently the way scatter plots work is essentially all contained in [traces/scatter/plot.js](https://github.com/plotly/plotly.js/blob/master/src/traces/scatter/plot.js). I was going to try to explain verbally how this could work, but it's gonna be way too difficult. So here's my image-based description instead. The blue arrows show the points that could accomplish this most simply. It's SVG though so there are probably five different ways to accomplish this. Open to other thoughts!

![fill](https://cloud.githubusercontent.com/assets/572717/26745695/b3c87218-47b9-11e7-9166-c13ee3c0fe65.png)

**Comment by craigdrayton** [comment]
Hi team - is this bug still being worked on? I've just come across it in my work. Many thanks

**Comment by Kolano** [comment]
I'm also interested in seeing this addressed, I've had to convert to using Bar graphs to avoid this issues.

**Comment by Kolano** [comment]
I was able to use the following map function to account for this in the current Plotly.js with the minor caveat that you'll have 1 erroneous data point indicating 1 rather than nothing beside each chunk of data.

```
//Account for "scatter" plots not honoring null data gaps
values.map(function(value, i){
   if(value == null){
   //Check for non-null values on either side
      if((typeof dataset.values[i+1] != undefined && dataset.values[i+1] != null) || (typeof dataset.values[i+1] != undefined && dataset.values[i-1] != null)){
         //Return minimal value to keep fill lines sensible
         value = 1;
      }
   }
   return value;
})
```

**Comment by supern8ent** [comment]
A workaround is to insert y=0 at each x=<desired cut>. To use rreuser's diagram as an example, you would insert y=0 immediately before and after each of the two filled blocks. 

This workaround is a bit more difficult to code than inserting Nulls so it would be great to see this bug fixed!

**Comment by jqlee85** [comment]
Has anyone figured out a solution that doesn't involve adding superfluous data? I would expect this to work like the green trace in [this example](https://codepen.io/jqlee85/pen/KKPgggj) from dygraphs.

**Comment by th0ger** [comment]
> @rreusser it's not a regression. No stress.
(7 years later.) Maybe a tiny bit of stress would help. Is this solveable?
