### ISSUE TITLE
Filtering transform Category + Range

### ISSUE THREAD

**Issue by bpostlethwaite** [plotly/plotly.js#1135]
@etpinard think I found another one for ya :)

```javascript
var INCLUSIVE = '[]';
var EXCLUSIVE = '][';

var trace1 = {
  x: [1, 2, 3],
  y: [10, 20, 30],
  mode: 'markers',
  transforms: [{
    type: 'filter',
    operation: INCLUSIVE,
    target: ['a', 'b', 'c'],
    value: ['a', 'b']
  }]
};

var trace2 = {
  x: [1, 2, 3],
  y: [30, 20, 10],
  mode: 'markers',
  transforms: [{
    type: 'filter',
    operation: EXCLUSIVE,
    target: ['a', 'b', 'c'],
    value: ['a', 'b']
  }]
};


var data = [trace1, trace2];

var layout = {
  title:'Filtering category data',
  height: 400,
  width: 480
};

Plotly.newPlot($('.js-plotly-plot')[0], data, layout);
```
gives 
![image](https://cloud.githubusercontent.com/assets/1176674/20225321/c1c3a98a-a810-11e6-89e2-daa12ed86760.png)

**Comment by etpinard** [comment]
I don't think there's a bug here.

trace 0 gets filtered to 

```js
x: [1, 2],
y: [10, 20],
transforms[0].target = ['a', 'b']
```

and all points of trace 1 pass the `][` filter condition. From the [`description`](https://github.com/plotly/plotly.js/blob/2897167dc064ef678ccaef441d83e796749844f6/src/transforms/filter.js#L54-L76), 

> `*][*` keeps items outside `value[0]` to `value[1]` and equal to both bounds

In detail,

- `'a'` is equal to `value[0]` (which passes the filter `]` part)
- `'b'` is equal to `value[1]` (which passes the filter `[` part)
- `'c'` is outside to interval

So @bpostlethwaite , in terms of inclusive / exclusive, I think you're looking for 

```js
var INCLUSIVE = '[]';
var EXCLUSIVE = ')(';  // which does not include the bounds
```

**Comment by bpostlethwaite** [comment]
ahhhh, right. Thanks for looking into it!
