### ISSUE TITLE
Double click event not fired anymore after selection

### ISSUE THREAD

**Issue by smalesys** [plotly/plotly.js#1138]
Hello !

I have an issue concerning the doubleclick event. It doesn't fire anymore after a selection of dots, in a scatter plot for instance, either with the rectangle or the lasso.

See this [CodePen](http://codepen.io/anon/pen/vyKBWG).

Thanks !

**Comment by etpinard** [comment]
Ha. That's because double-clicking on a graph with selected points triggers `plotly_deselect` instead of `plotly_doubleclick`.

You could probably make an argument that both `plotly_deselect` and `plotly_doubleclick` should be triggered in that situation. In https://github.com/plotly/plotly.js/pull/255, we chose a handler-based event namespace. What do you think?

**Comment by etpinard** [comment]
See example of `plotly_deselect` -> http://codepen.io/etpinard/pen/ObXMXe

**Comment by smalesys** [comment]
Thanks for your quick answer !

Sounds logical to me to have two distinct events here. I think maybe the names can be confusing, since "doubleclick" sounds general and "deselect" is specific, while they are actually both on the same level (im not sure if i am clear here haha).

But i admit that i have no idea for renaming the event. Maybe unzoom or resetplot but i don't think that this will englobe all the usecases of the event. I guess just mentionning it in the doc should be enough for the users.

**Comment by etpinard** [comment]
Thanks for the feedback @smalesys :tada: 

We're planning on cleaning up our event namespace and event data in [`v2.0.0`](https://github.com/plotly/plotly.js/issues/420). I'll paste your last comment in https://github.com/plotly/plotly.js/issues/145.

**Comment by smalesys** [comment]
You are welcome! Maybe the main confusing point is that "doubleclick" is an action while "deselect" is an effect. But with a doc it shouldn't be a problem, i know that naming things is a pain in the *** ;)
Good luck for V2.0 !
