### ISSUE TITLE
scattergl hover bug

### ISSUE THREAD

**Issue by jessetabak** [plotly/plotly.js#1145]
When I create a scattergl plot with multiple traces the hovering seems broken.It only highlights one color correctly. If you hover a different color it will show a tooltip for a different point.

Take a look at this codepen: http://codepen.io/anon/pen/ENyLKX
Only the blue dots get highlighted.

**Comment by etpinard** [comment]
Thanks for the report. This seems to be a regression introduced in the `1.19.x` series.

cc @monfera @dfcreative

**Comment by etpinard** [comment]
See http://codepen.io/etpinard/pen/NbrmqZ which uses `v1.18.0` and appears to be working fine.

**Comment by monfera** [comment]
@jessetabak Thanks for the report, we're working on the issue. In the meantime, a possible temporary workaround is the addition of a `{marker: {size: [10]}}` (the size value may of course be different) in the traces, see http://codepen.io/anon/pen/XNKQLZ - though this approach probably leads to slower rendering speed if there are hundreds of thousands of points.

**Comment by monfera** [comment]
@jessetabak the bugfix has been merged by @etpinard https://github.com/plotly/plotly.js/pull/1148 and will be part of an upcoming `plotly.js` bundle in a day or two; please use the above workaround or rel. 18 in the meantime.

**Comment by jessetabak** [comment]
awesome, thanks for the fast response

**Comment by monfera** [comment]
@jessetabak as @etpinard published a `plotly.js` bundle yesterday, your pen works without a change.

**Comment by jessetabak** [comment]
@monfera very nice, thanks!
