### ISSUE TITLE
exception when container is too small (uncaught ax.dtick error: NaN)

### ISSUE THREAD

**Issue by jessetabak** [plotly/plotly.js#1153]
When I set the width or height of the container very small (ie. 185px height) it will generate loads of exceptions: "Uncaught ax.dtick error: NaN"

Look at this codepen example: http://codepen.io/anon/pen/YpGYye
If you change the height to 190px it will work fine.

**Comment by etpinard** [comment]
Seems to be fixed now. No errors in the console for https://codepen.io/anon/pen/YpGYye
