### ISSUE TITLE
annotation placement for ordinal axis bugs with version 1.20

### ISSUE THREAD

**Issue by Quath** [plotly/plotly.js#1154]
Hi

I have a bar graph which had on the X axis a combination of 2 date strings ("04/2014") and text strings ("Status", "Difference", ...). On top of each bar was an annotation. The annotations were all defined the following way:
`
let annotation = {
 x: "mystring",
 y: 2354,
 text: "blabla",
 xanchor: middle,
 yanchor: top,
}
`
with `"mystring"` being either one of the date strings, or one of the text strings.

With version 1.19.x I had no trouble, the annotations where all placed nicely on top of the bars, with the upgrade to version 1.20.x, all the annotations are placed in the X middle of the graph... The code itself didn't change between the upgrade... 

Any idea?

**Comment by etpinard** [comment]
Can you share a reproducible example?

This is probably a side-effect of https://github.com/plotly/plotly.js/pull/1078

**Comment by Quath** [comment]
Almost!! I have another error when I try to use the cdn plotly-latest.min so I'm not sure if it's reproducing the bug or not...
[https://fiddle.jshell.net/Quath/8hd4p8nu/](https://fiddle.jshell.net/Quath/8hd4p8nu/)

**Comment by etpinard** [comment]
https://fiddle.jshell.net/8hd4p8nu/3/

is now showing a graph. What's wrong with it?

**Comment by Quath** [comment]
The annotations are in the center of the graph, and not on the bars... 
I expect the annotations to be at least within the bars if not on top

**Comment by etpinard** [comment]
I see. The annotation reference `x` / `y` categories. This is regression.

Thanks for posting!

**Comment by Quath** [comment]
You're welcome!!
