### ISSUE TITLE
stacked bar chart hover labels showing cumulative values since 1.20

### ISSUE THREAD

**Issue by arhang** [plotly/plotly.js#1157]
hi.

stacked bar chart hover labels used to show individual values
since 1.20 they start showing cumulative ones
could this be reverted or could an option be added to choose what is shown?
thanks

**Comment by etpinard** [comment]
Thanks for posting. 

@n-riesco looks like the fix in https://github.com/plotly/plotly.js/pull/1142 caused a regression.

**Comment by etpinard** [comment]
Reproducible example / comparison: http://codepen.io/etpinard/pen/Woopae
