### ISSUE TITLE
scattergl crashes with one marker

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#1164]
http://codepen.io/cpsievert/pen/QGGMej

I originally discovered problems re-creating updating this page to use v1.20.0 -- http://cpsievert.github.io/pedestrians/stl-tour/

I get different errors depending on whether viewing in Chrome or Firefox...

**Comment by etpinard** [comment]
part of https://github.com/plotly/plotly.js/issues/130

**Comment by cpsievert** [comment]
I assume you're saying this example falls under this category:

> cartesian + gl2d subplot on the same graph are not supported

But this is not a subplot...they are 2 different graphs on the same page

**Comment by etpinard** [comment]
What's the problem? I don't see any console errors?

**Comment by cpsievert** [comment]
Do you see errors for the second link? For the codepen, you have to uncomment this line:

//"mode": "markers",

When I do that, it freezes my browser tab in Chrome

**Comment by rreusser** [comment]
@cpsievert I'm able to get it to crash with this simplified case involving just one plot: http://codepen.io/rsreusser/pen/woorOo?editors=0010

```javascript
Plotly.plot('graph1', [{
  "x": [1],
  "y": [1],
  "mode": "markers",
  //"type": "scattergl"
}]);
```

Perhaps it's a problem with length-one traces?

**Comment by etpinard** [comment]
Interesting. Maybe @dfcreative would be interested in looking into this.

**Comment by cpsievert** [comment]
Yea, @rreusser, that is probably the real issue here...and now that second link is now rendering ok for me...I must be seeing things!!

**Comment by etpinard** [comment]
@cpsievert thanks for the report!

Sorry about that hasty close. I must be going blind.

**Comment by Phasedd** [comment]
This bug was introduced in 1.19.0.

I noticed the bug a fair few days ago, but I did not have the time to dig into why the scatterplot kept crashing when I started to receive data.

After finally getting free times after finishing my exams for the semester, I finally found out it was due to adding 1 data point. Opened up the issue tab to post a codepen with the issue to find out someone beat me to it.

**Comment by etpinard** [comment]
@monfera looks like one of your patches caused this regression. Would you mind sharing some insights on why this could be happening?

**Comment by monfera** [comment]
It seems that the simultaneous presence of these conditions cause the browser tab to hang:

1. We have a regular (SVG based) scatter plot
2. Its mode is `markers` (problem doesn't come up if it's `markers+lines`
3. There's only one data point
4. We then switch to `scattergl`

Initial thoughts: apparently, it requires a switch into the non-fancy `scattergl` version. Perhaps a domain projection gets into a degenerate case with one data point (domain high and low values are the same) - though this condition wouldn't be new. The most recent change only impacted the return value - pick index offset - of the render function, so maybe it's related to some downstream effect of that.

**Comment by monfera** [comment]
Update: it seems to be an earlier regression, working on it now.
