### ISSUE TITLE
bug with subscripts and superscripts in 3D

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#1165]
As reported by @ellecj - the problem has a couple of layers...

If I try to make this plot:
```
Plotly.newPlot(gd, [
    {
      "type": "mesh3d",
      "y": [0, 1, 2],
      "x": [1, 2, 0],
      "z": [2, 0, 1],
      "i": [0],
      "j": [1],
      "k": [2]
    }
  ],
  {
    "title": "Triangle mesh",
    "scene": {
      "zaxis": {
        "title": "Z<sup>SUPER</sup><sub>SUB</sub>"
      }
    }
  })
```
I don't see any super or subscripts:
<img width="420" alt="screen shot 2016-11-18 at 11 37 17 am" src="https://cloud.githubusercontent.com/assets/2678795/20437821/76729aae-ad83-11e6-950f-16f575cc9575.png">

And then if I do a `relayout`:
```
Plotly.relayout(gd, {'scene.zaxis.title':'ZZZ<sup>2</sup><sub>a</sub>'})
```
I see a superscript but not a subscript:
<img width="352" alt="screen shot 2016-11-18 at 11 38 47 am" src="https://cloud.githubusercontent.com/assets/2678795/20437950/d3c98b54-ad83-11e6-99ca-3809ddba3950.png">

**Comment by etpinard** [comment]
Some info on the topic: 

HTML entities are converted to unicode in [src/lib/html2unicode.js](https://github.com/plotly/plotly.js/blob/master/src/lib/html2unicode.js). In particular `<sup></sup>` are converted using [`superscript-text`](https://github.com/mikolalysenko/superscript-text) which [appears](https://github.com/mikolalysenko/superscript-text/blob/master/superscript.js) to work only for lower case strings inside the `<sup></sup>` tags. Indeed, lower case strings are working fine. This is tested in the [`gl3d_log-axis-big`](https://github.com/plotly/plotly.js/blob/master/test/image/baselines/gl3d_log-axis-big.png) mock.

Note that `html2unicode` makes no attempt at converting `<sub></sub>`.

**Comment by etpinard** [comment]
Related: https://community.plot.ly/t/scatter3d-text-formatting/4039/2

**Comment by etpinard** [comment]
cc @dfcreative

**Comment by archmoj** [comment]
The example below is related to using lower case letters and `<sup>` which works with the PR #3207 
Please note that here plus signs are used to avoid displaying the elements within `<sup>` tags to be parsed by GitHub viewer. Obviously one could omit them in the call. 
<pre>
Plotly.newPlot(gd, [
    {
      "type": "mesh3d",
      "y": [0, 1, 2],
      "x": [1, 2, 0],
      "z": [2, 0, 1],
      "i": [0],
      "j": [1],
      "k": [2]
    }
  ],
  {
    "title": "Triangle mesh",
    "scene": {
      "zaxis": {
        "title": "Z" + "<sup>" + "super script using numbers and only lower cases without" + "</sup>" + "'q'!"
      }
    }
  });<pre>

**Comment by archmoj** [comment]
Now in the PR #3207 the superscripts and subscripts could be used in webgl; and they are not limited to lower cases.
