### ISSUE TITLE
Can't layer an existing trace on top of itself

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#1167]
http://codepen.io/cpsievert/pen/zoNBMV

Possibly related to #1083. I also tried pushing traces to gd.data and calling `Plotly.redraw(gd)` with the same problem, so I think the issue needs to be resolved there.

PS. this is quite important for the R packages' newest stuff

**Comment by etpinard** [comment]
Why don't you just make a clone of that trace in question?

**Comment by cpsievert** [comment]
I suppose that would be a smart thing to do 😆 

I still find the behavior kind of surprising, but I know u have better things to work on...

PS. would u recommend cloning with `var traceClone = JSON.parse(JSON.stringify(trace));`?

**Comment by etpinard** [comment]
@cpsievert I believe a mere _flat_ extend suffice here as @dfcreative 's patch in https://github.com/plotly/plotly.js/pull/1136

`JSON.parse` + `JSON.striginify` makes a deep copy which is safer but also very slow.

**Comment by etpinard** [comment]
Should be resolved in #1136

**Comment by etpinard** [comment]
fixed in https://github.com/plotly/plotly.js/pull/1175

**Comment by etpinard** [comment]
Oh and I should mention @cpsievert both this issue and #1083 will be fixed in `1.20.3` set to be released in the next few hours.
