### ISSUE TITLE
Dropdown selects the wrong option

### ISSUE THREAD

**Issue by rreusser** [plotly/plotly.js#1169]
Select option b. It jumps to option c:

http://codepen.io/rsreusser/pen/YpNGaY?editors=0010

cc @jackparmer @etpinard

**Comment by n-riesco** [comment]
I'm already looking at adding a scrollbar to the dropdown menu. I could have a look at this issue too.

**Comment by rreusser** [comment]
Investigating this. @n-riesco's assessment is that my matching logic needs to be better, which seems correct. Adding failing test and fixing now.

**Comment by etpinard** [comment]
Closed in https://github.com/plotly/plotly.js/pull/1176
