### ISSUE TITLE
Should categorical bars / boxes always have a width of 1?

### ISSUE THREAD

**Issue by bpostlethwaite** [plotly/plotly.js#1181]
http://codepen.io/bpostlethwaite/pen/eBvMWM

All data points except two have been filtered but the plot shows the full range of axis points and they are off center. I don't know if this is related to filtering or is more general but this is a way to trigger it.

cc @etpinard @alexcjohnson

**Comment by alexcjohnson** [comment]
that's a funny one, I think it's two bugs:
- the categories are being read from the original trace, pre-filtering, which doesn't seem like what we want
- then when we make bars only at `a` and `f` they each get a width of 5 categories - also probably not what we want, category axis bars should always have width 1 (one category), right? You can also trigger this second one with two overlaid traces:
```
Plotly.newPlot(gd,[
        {x:['a','b','c','d','e'], y:[1,2,3,4,5], type: 'bar'},
        {x:['a','e'], y:[4,2], type:'bar'}
    ],
    {barmode:'overlay'})
```
![screen shot 2016-11-21 at 4 11 41 pm](https://cloud.githubusercontent.com/assets/2678795/20500855/4334e85c-b005-11e6-9aaf-1e1e1854b20f.png)

**Comment by n-riesco** [comment]
@alexcjohnson Forcing a width of 1 for category axis can be done by changing [this line](https://github.com/plotly/plotly.js/blob/48b035873b66682de512d9473c07cb7c1e331552/src/traces/bar/set_positions.js#L189) and [this line](https://github.com/plotly/plotly.js/blob/48b035873b66682de512d9473c07cb7c1e331552/src/traces/bar/set_positions.js#L233).

**Comment by etpinard** [comment]
> the categories are being read from the original trace, pre-filtering, which doesn't seem like what we want

Fixed in https://github.com/plotly/plotly.js/pull/1260

Changing issue title to reflect what's left of @bpostlethwaite 's bug report.

**Comment by alexcjohnson** [comment]
> Should categorical bars always have a width of 1?

I think so - it's misleading otherwise, as otherwise a bar would bleed into neighboring categories, which in principle have no relation to each other.

**Comment by etpinard** [comment]
A similar problem happens for box traces on categorical position axes - see https://github.com/plotly/plotly.js/issues/4510 for more details.
