### ISSUE TITLE
tickangle is wrong units in scattergl

### ISSUE THREAD

**Issue by emackey** [plotly/plotly.js#119]
The units for `tickangle` is degrees when using `scatter`:

```
Plotly.plot(Tabs.fresh(), [{x:[1,2,3], y:[2,1,2], type:'scatter'}], {yaxis:{tickangle:-10}});
```

However, it switches to radians when using `scattergl`:

```
Plotly.plot(Tabs.fresh(), [{x:[1,2,3], y:[2,1,2], type:'scattergl'}], {yaxis:{tickangle:-10}});
```

This could be a bug in the underlying `gl-plot2d` library, it doesn't seem to specify what units are expected here.

Also, there is a test `gl2d_axes_labels` that does specify `tickangle: 45`, but it turns out that 45 radians looks visually similar to 45 degrees by coincidence, approximately 58 degrees to be more precise.  It does appear that this test's baseline "correct" image does have a 58 degree slant baked into it.

**Comment by etpinard** [comment]
Bug confirmed. Thank you very much for reporting.

**Comment by etpinard** [comment]
The problem also affects the gl3d axes.

The gl-vis [gl-plot2d](https://github.com/gl-vis/gl-plot2d#ticks) and [gl-axes3d](https://github.com/gl-vis/gl-axes3d#tick-text) modules consistently use radians for `tickAngle`. 

We should convert the angle to radians in the gl3d and gl2d convert step.
