### ISSUE TITLE
Incorrect plot size calculation after legend moves over chart area

### ISSUE THREAD

**Issue by zbjornson** [plotly/plotly.js#1190]
There's a non-zero range of plot widths between the point when the legend moves on top of the chart (265 px in example below) and when the chart resizes to consume the space where the legend was (172 px). This leaves a weird blank space on the right and needlessly scrunches up the plot.

http://codepen.io/anon/pen/QGvGWY

![image](https://cloud.githubusercontent.com/assets/469365/20540775/5504149a-b0af-11e6-905e-fffefa953809.png)

**Comment by etpinard** [comment]
What _should_ here in your mind?

Looks like at  `w <= 265`, the legend would fit (given some padding) in the right margin. 

Not sure what's happening at `w >= 172`, this is what I'm seeing:

![image](https://cloud.githubusercontent.com/assets/6675409/20541068/a5a70168-b0c9-11e6-9ae3-a5babcdd3deb.png)

**Comment by zbjornson** [comment]
Thanks for the prompt reply!

Interesting, my original screen shot was from Chrome, but Firefox shows what you posted for the 2nd plot.

I would expect the plot to *resize to fill the div at the exact same point that the legend moves over the chart area*. That is, I would expect the right-margin in the 3rd plot to be 0-ish (same as in the first plot in Chrome and first and second plots in FF).

**Comment by n-riesco** [comment]
`w>=172` looks like an edge at which [autoMargin](https://github.com/plotly/plotly.js/blob/0e0928bbe55fc6d75067bdf942de30444f8e7920/src/plots/plots.js#L1209-L1212) starts accepting requests to expand margins to accommodate the legend.

The algorithm to position legends always makes a request to expand margins, and keeps the expanded margins, even if it doesn't manage to fit the legend at the requested location.

@etpinard Can you think of any cases where it wouldn't make sense for legend to revert a margin expansion request that failed?

**Comment by etpinard** [comment]
This is maybe related to @n-riesco 's observation [here](https://github.com/plotly/plotly.js/blob/c13093282e9824d7e61db4a43b4c4a8bf17368fd/src/plots/plots.js#L464-L465).

**Comment by etpinard** [comment]
This seems to have been fixed. Using 1.45.2:

![image](https://user-images.githubusercontent.com/6675409/54567762-4bb68980-49ab-11e9-9bf7-ce5a7bc7c472.png)
