### ISSUE TITLE
legend items (trace names) in horizontal legends aren't aligned nicely if all in one row

### ISSUE THREAD

**Issue by salim-b** [plotly/plotly.js#1193]
The problem occurs if `legend = list(orientation = "h")` (in `R`) or [`layout = {legend: {"orientation": "h"}};`](https://plot.ly/javascript/legend/#changing-the-orientation-of-legend) (in `JS`) is set and the frame width is large enough to place all legend items on one line.

The [logic to align the legend items in a grid](https://github.com/plotly/plotly.js/issues/769#issuecomment-235365202) (see also <https://github.com/plotly/plotly.js/pull/786>) is generally a good thing for responsiveness, but doesn't look good if the resulting grid consists of only one row as in the example below:
![example](https://cloud.githubusercontent.com/assets/20040931/20580111/d967c00c-b1d0-11e6-92af-a18460ef55c9.png)
(note the spacing between `SRG SSR`, `Schweizer Privatsender` and `Ausländische Sender`; [here](https://plot.ly/~slim-b/223) is the same chart hosted on plot.ly)

Some more information I could find:
- clearly related issue: <https://github.com/plotly/plotly.js/issues/960>
- related pull request: <https://github.com/plotly/plotly.js/pull/945>

**Comment by etpinard** [comment]
Thanks for writing.

This is in fact the same issue as https://github.com/plotly/plotly.js/issues/960#issuecomment-248790714

I'll mark this as a duplicate.
