### ISSUE TITLE
Modebar not destroyed correctly

### ISSUE THREAD

**Issue by emackey** [plotly/plotly.js#120]
Try this in the test environment:

```
Plotly.newPlot(Tabs.fresh(),    [{x:[1,2,3], y:[2,1,2]}]);
Plotly.newPlot(Tabs.getGraph(), [{x:[1,2,3], y:[2,1,2]}]);
Plotly.newPlot(Tabs.getGraph(), [{x:[1,2,3], y:[2,1,2]}]);
Plotly.newPlot(Tabs.getGraph(), [{x:[1,2,3], y:[2,1,2]}]);
Plotly.newPlot(Tabs.getGraph(), [{x:[1,2,3], y:[2,1,2]}]);
```

Now, inspect the DOM tree near the modebar(s).  Each `newPlot` has its own overlapping modebar.

**Comment by mdtusz** [comment]
Confirmed.

**Comment by etpinard** [comment]
probably a one-line fix in `Plots.purge`.

**Comment by mdtusz** [comment]
Yep. My thinking as well - just need to destroy the node.

**Comment by etpinard** [comment]
Adding:

```js
gd._fullLayout._modebar.destroy();
```

https://github.com/plotly/plotly.js/blob/master/src/components/modebar/index.js#L262

should do it.

**Comment by emackey** [comment]
This is fixed, thanks!
