### ISSUE TITLE
Opacity for 3D plots doesn't behave as expected

### ISSUE THREAD

**Issue by cldougl** [plotly/plotly.js#1206]
Originally posted in: https://github.com/plotly/plotly.py/issues/610

Hello,
When plotting a 3D surface using iplot, the opacity parameter does not behave continuously. Setting it to 1.0 will cause full opacity, and setting it to 0.999999 will cause the surface to be VERY transparent, somewhere around 0.5 opacity. It will behave relatively linearly below this point.

Expected behavior: The opacity parameter should be continuous. A tiny change in the parameter value should be imperceptible.

http://codepen.io/plotly/pen/QGqavK

**Comment by etpinard** [comment]
cc @dfcreative
