### ISSUE TITLE
Issues with local image testing

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#121]
@mdtusz @cldougl @perigee 

Please document the issue you are seeing while running the image test locally.

**Comment by mdtusz** [comment]
On OSX:

* docker version 1.8.3
* docker-compose version: 1.5.0
* docker-machine version 0.4.1

Running `npm run test-image`:

* connects to server after 5 attempts (connection refused on attempts)
* fails on multiple (*multiple*) test cases that all pass on circle
* fails saying `gm compare: Request did not return an image.` for multiple (*MULTIPLE*) test cases
* finally, exits with a status of 1 (although this may be intentional when not all tests pass)

Full logs [here](http://pastebin.com/sSSffvUm).

**Comment by cldougl** [comment]
On OSX:
* docker version 1.9.1
* docker-compose version 1.5.1
* docker-machine version 0.5.1

Today (clean branch) `npm run test-image`: 
* connecting to server after 2 attempts 
* all 236 tests are running and passing  

Yesterday:
*** After remaking the `gl3d` images with `npm run baseline -- XX.json`
* only ~130 were running/passing and ~100 were returning `gm compare: Request did not return an image.`  
* *BUT* when the failed tests were run individually, (i.e. `npm run test-image -- gl3d_nan-holes.json`) they passed.

**Comment by perigee** [comment]
Built a working around by installing the docker inside a vagrant controlled the VM. I've installed on @mdtusz 's machine, waiting for the feedback, during the mean time, @cldougl if you want, i can install on your machine also.

**Comment by mdtusz** [comment]
@perigee it works, but still has some hiccups. It tries to connect quite a few times before succeeding still, and as seen [here](https://github.com/plotly/plotly.js/pull/116), the image-test still isn't as deterministic as it should be - tests passed in the vagrant(docker(tests)) but not on circle, the image diff was *extremely* slight as well which is odd.

**Comment by cldougl** [comment]
@perigee at the moment everything is working as expected for me so I'll stay with my current set up- but I'll keep you posted if I run into trouble again. Thx!!

**Comment by etpinard** [comment]
In https://github.com/plotly/plotly.js/pull/154/commits

On commit https://github.com/plotly/plotly.js/tree/5be72dece3c69c8269e0e211b3ff165f84d5a142

the image tests failed when run in batches (after the ~6 image is generated). Individual image tests are passing.

On commit https://github.com/plotly/plotly.js/tree/7b07a2561778f477c0a69d6b79bc9dd79c1b2eba

the image tests are passing (batch & individual). At first glance, the only differences between the two trees is reorganization.

**Comment by perigee** [comment]
@etpinard  @mdtusz @cldougl 

you may need run

```
docker pull plotly/testbed:latest
```

to fetch the new docker images (replace the old local image `latest`) on your local machine for local image test.

**Comment by etpinard** [comment]
Closing for now.
