### ISSUE TITLE
Legend color turns black if specifying specific colors for each bar

### ISSUE THREAD

**Issue by sijmenvos** [plotly/plotly.js#1212]
For a project I'm using lighter bar colors to display what bars have insufficient datapoints to draw conclusions from it. Unfortunately this results in the legend color being black.

Is there a workaround to fix this problem? If not it would be a nice feature to be able to set the color of the legend manually for each series.

Example:
[https://plot.ly/~sijmen/3/](https://plot.ly/~sijmen/3/)

**Comment by etpinard** [comment]
Looks like the legend item fallback is wrong for bar traces.

Thanks for pointing this out.

**Comment by etpinard** [comment]
Reproducible codepen: http://codepen.io/etpinard/pen/JbMbXe

**Comment by sijmenvos** [comment]
Thanks for fixing this!

It seems that the color of the legend when you deselect a serie it is still black. Normally it's a fade out of the color of the serie. 

See the codepen: http://codepen.io/etpinard/pen/JbMbXe
And click on a legend item to deselect it.

Regards,
Sijmen

**Comment by aanchalvazir** [comment]
Hi @etpinard 

I am facing a similar issue. I am creating a bar chart in Dash plotly, to which I am assigning a color scale for showing diverging colors (not assigning colors per bar but a assigning a scale which can do this automatically as per a measure for reference). However, the legend for this chart appears black. 

The following is a snippet of what I am trying to achieve:

'data':[
go.bar(
 x='dates',
 y=( df['mean'] - dff['mean'] ),
 marker={'colorscale':'Greens', 'color':(dff['mean'])},
 showlegend=True,
 legendgroup='group2',
 yaxis='y3',
)
],

'layout':[
 'yaxis3':{
            'domain':[0.8, 1],
            'rangemode':'nonnegative',
            'visible':False,
            'mirror':True,
            'range':[0,250000],
            'scaleratio': 1,
 }
]

I do not want to show the continuous color scale itself as shown in : https://plotly.com/python/colorscales/    but the legend itself.
Could you suggest a work around?

Thanks in advance!

**Comment by nitramwin** [comment]
It seems, this problem is occurring again in 2020.

**Comment by archmoj** [comment]
> It seems, this problem is occurring again in 2020.

@nitramwin could you please share a minimal codepen illustrating the bug you noticed?
Thanks!

**Comment by nitramwin** [comment]
@archmoj Thanks for the response. Here it is: https://codepen.io/nitramwin/pen/mdEoxZo

**Comment by archmoj** [comment]
> @archmoj Thanks for the response. Here it is: https://codepen.io/nitramwin/pen/mdEoxZo

Thanks @nitramwin. Tracked in #5285.
