### ISSUE TITLE
Plotly hover show different text color when hover from different position.

### ISSUE THREAD

**Issue by ajay06kumar** [plotly/plotly.js#1215]
Hi Everybody,

I am using plotly.js to display line and scatter points on single plot. For some color, the tooltip attached with each point show text in black color and for some color ( e.g. pink ) it shows white as text-color. 

I am able to change all hover point text color to black using
 
`myPlot.on('plotly_hover', () => {
       angular.element('.hovertext > text')[1].setAttribute('style', 'fill: black');
});`

But for some reason, I am seeing two colors for single point when I hover from a different position. e.g. when I hover from bottom to top it uses black as text color and when I hover from top to bottom it uses white text color.

I am unable to find the source of the error. 

Any Help is appreciated.

Regards
Ajay

**Comment by etpinard** [comment]
Can you share a reproducible example?

**Comment by etpinard** [comment]
Closed due to lack of reproducible example.
