### ISSUE TITLE
Plotly hover e2e test.

### ISSUE THREAD

**Issue by ajay06kumar** [plotly/plotly.js#1216]
Hi Everybody, 

We are using plotly.js for displaying multiple scatter and line plots. In our application, we have a feature to show a custom card when user hover over plot points. Using custom card user can perform multiple operations in our application.

While writing E2E test-case for our application, I accessed the custom card by providing hovered point x-path. While debugging, I found out that plotly.js is storing same set of points in an array form. So, we can access different point displayed inside plotly by modifying the index-position at a valid location in x-path. 

Right now, I am able to hover over a particular standard point using a particular position but when I perform the same operation for a different hover point, plotly hover over a different set of points. 

I am unable to find the source of the issue.

Any Help is Appreciated.

Regards
Ajay.

**Comment by etpinard** [comment]
Closing.

Questions of the like should be asked on https://community.plot.ly/
