### ISSUE TITLE
Bar and histogram traces will not draw side-by-side

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#1219]
For example:
```
Plotly.newPlot(gd,[
    {x:[1,1,1,1,1,2,2,2,3,3],type:'histogram'},
    {x:[1,2,3],y:[-1,-2,-3],type:'bar'}
])
```
Only the first one will draw, whichever is the first (though both contribute to autorange and hover effects for both still display).
Multiple histograms or multiple bars will still show.

**Comment by etpinard** [comment]
Interesting this used to work in way back in v1.2.0

http://codepen.io/etpinard/pen/ZBxLNZ
