### ISSUE TITLE
Cast frame labels to strings everywhere they're used

### ISSUE THREAD

**Issue by rreusser** [plotly/plotly.js#1224]
Numbers keep sneaking through as valid frame labels or animate arguments, which then cause animations to totally fail. They should be cast to strings on some sort of supplydefault step, otherwise we should cast them to strings every time they're used.

Until then, a note to avoid integer labels, cc: @Kully @jp and… @empet ? is that the right callout?

**Comment by etpinard** [comment]
@rreusser was this completed in https://github.com/plotly/plotly.js/pull/1236?

**Comment by rreusser** [comment]
Ah yes, I believe so. I think it's no working fine. That PR was the day after this, so looks like a stray unclosed issue. 👍

**Comment by etpinard** [comment]
Great. Thanks. Closing.
