### ISSUE TITLE
Option to execute component commands on initialization

### ISSUE THREAD

**Issue by rreusser** [plotly/plotly.js#1225]
We talked about this briefly before and it didn't sound like a good idea, but I really think this is proving to be necessary. Syntax:

```json
"updatemenus": [{
  "active": 0,
  "executeoninitialization": true,
  "buttons": [{
    "method": "animate"
  }]
}]
```

This would trigger execution of the command if the *internally* active button/step index was previously undefined. Once that has happened, it won't automatically be executed again.

Here's situations it would help with:

1. Playing animations on load in the UI. Right now they just get played with `Plotly.animate(gd)` (I think), which is not acceptable because it's entirely unconfigured, giving a better than average chance that it will look pretty junky.

2. synchronizing the initial state. Right now you have to load a bunch of frames and also set up the initial plot state and set the slider component value and configure a command that correctly reconstructs the exact state. Long story short, the inability to execute a command that sets the state automatically means you have to do your best to make things look correct and then just cross your fingers that you got it right. Executing the command would just make it right in the first place.

2. Slider transform. cc: @bpostlethwaite. Right now when the magic workspace transform generates frames slider etc, it doesn't actually *set* that frame. This leads to a difficult initialization problem that, at best, has to be hacked around. If it actually executed the command that configured the filter, this problem would go away.

cc: @etpinard

**Comment by rreusser** [comment]
cc: @Kully @mdtusz @jp regarding autoplaying animations on page load. I can imagine autoplaying animations being a desirable feature that can be done unless the animation given proper configuration, so that we probably need *some* machinery in plotly.js that can accomplish this.

**Comment by rreusser** [comment]
Other ideas on how the animation problem might be solved.

1. see above. components can execute their command on load
2. `layout.defaultanimationconfig`. At least then we *could* just autoplay it and be done with it. Maybe add `autoplay: true | false` to the default animation options.
3. `layout.initializationcommand`. More general. You could just pass a custom command that's executed after the plot loads? I don't particularly like this idea.

**Comment by etpinard** [comment]
To me, setting whether or not an animation should start right after the first draw depends on the plot _context_ in plotly lingo (i.e. its environment).

For example on plot.ly, you can make the case that animations in shareplot and embed should start right away. But, I doubt that someone editing a graph in the workspace would want it to animate while editing.

Generally, per-context options are handled in the config object e.g. `Plotly.plot(gd, data, layout, { editable: true })`.

**Comment by dioscuroi** [comment]
Agreed with @Kombat-Batyanya. Has there been any update on the starting frame other than 0?

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
