### ISSUE TITLE
Unknown filename when exporting charts (Safari)

### ISSUE THREAD

**Issue by wallacedf** [plotly/plotly.js#1227]
Hi,

I've been using the "Export" feature to save charts as images and it's working mostly great! However, in Safari 10.0.1 (Mac OSX), the file is downloaded with the name "Unknown" without even an extension.

Here is an example: https://plot.ly/~bd_plotly/46

Could you please check this issue out?

Thank you very much!

**Comment by freshwuzhere** [comment]
ditto.  Is this in Safari only?

**Comment by meletis** [comment]
Yes, this is Safari OS X only.

**Comment by alubbock** [comment]
In plotly 1.27.1 and Safari 10.1.1, the user gets two image downloads - one with the proper filename and one with filename "Unknown". The Javascript console also shows the error:

    data:application/octet-stream;base64,<octet stream goes here>=
    Failed to load resource: Frame load interrupted

**Comment by petermattia** [comment]
I have the same issue in Safari as @alubbock. Works fine on Chrome.

**Comment by abegehr** [comment]
same problem here. downloading the image twice (Unknown.png and [name].png) on OSX 10.13.5 Safari 11.1.1 with Plotly 1.38.1

**Comment by rlreamy** [comment]
Just going to chime in with the same question as several others have asked...is this something that is going to be fixed soon, or is there a workaround for this?

**Comment by nicolaskruchten** [comment]
This issue is not on anyone's roadmap at the moment, although we certainly would be happy to review and accept a pull request that resolves it :)

**Comment by rlreamy** [comment]
I have made some local changes to the filesaver.js and tested on Safari Version 14.0.1 (16610.2.11.51.8) and was able to get a plot to download successfully. The change I made was to simply remove the special Safari handling code in that function...it appears that at least the version of Safari I am using does not need this.

I do not have other versions of Safari to try this out on, and am unsure of which versions you need supported. I also tried to create a pull request with my changes but was denied access.
 
Let me know how I can proceed with pushing this code to the repo so that others can test it and it can possibly be integrated into the next release.

**Comment by archmoj** [comment]
> I have made some local changes to the filesaver.js and tested on Safari Version 14.0.1 (16610.2.11.51.8) and was able to get a plot to download successfully. The change I made was to simply remove the special Safari handling code in that function...it appears that at least the version of Safari I am using does not need this.
> 
> I do not have other versions of Safari to try this out on, and am unsure of which versions you need supported. I also tried to create a pull request with my changes but was denied access.
> 
> Let me know how I can proceed with pushing this code to the repo so that others can test it and it can possibly be integrated into the next release.

Sounds good.
@rlreamy
Please note that in order to open a PR you need to "fork" plotly.js and push the changes to that fork.

**Comment by rlreamy** [comment]
Thanks! Will do!

**Comment by rlreamy** [comment]
Sorry if I did that wrong...feel free to close the one that is wrong.

**Comment by jneilliii** [comment]
So this appears to be the only issue related to the problem a user is experiencing with my project. Related issue can be seen [here](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/issues/448). I'm using Plotly.downloadImage in my code [here](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/blob/7183551fb8f5aa9fb2b39714539902d3e829fb3b/octoprint_bedlevelvisualizer/static/js/bedlevelvisualizer.js#L356) and the image is created but with an empty surface mesh, only legend. I'm using version 2.1.0 gl3d bundle. Any help would be greatly appreciated.
