### ISSUE TITLE
documentation: add link with an example for each item in the api

### ISSUE THREAD

**Issue by mg1075** [plotly/plotly.js#1243]
feature request:

The api documentation is sometimes hard to grasp.

The documentation could be improved if: 

(1) each item in the api had a link opening in a separate window to a codepen/jsfiddle/(whatever tool) where the api item in question was used in the online example. 

(2) child properties of an api item are ordered alphabetically instead of what seems to be random order.

**Comment by etpinard** [comment]
Best for https://github.com/plotly/documentation/issues/new
