### ISSUE TITLE
allow for horizontal colorbar

### ISSUE THREAD

**Issue by mg1075** [plotly/plotly.js#1244]
_feature request:_ **horizontal colorbar** for heatmap, 3d graphs, etc.

The api for the colorbar seems to only allow for a colorbar positioned _vertically_.
![image](https://cloud.githubusercontent.com/assets/2031435/21077994/a7571ff2-bf24-11e6-98db-aea3044165af.png)

But what if someone wants the bar displayed _horizontally_?
As far as I can tell from the api, this is not possible, but it would be nice to have.

![image](https://cloud.githubusercontent.com/assets/2031435/21078021/519a3cba-bf25-11e6-8050-82de661715a1.png)

**Comment by isokrates** [comment]
This would be great—it would make things centre on the page in a much more visually appealing way!

**Comment by cdsontag** [comment]
This would be a great benefit to the JWST ETC project.  With the colorbar vertical, any variation in the number of sig. figs shown for the colorbar numerical tick values change the width of the whole area.

**Comment by antoinerg** [comment]
@divyachandran-ds brought this issue to my attention.

I think that allowing colorbars to have an horizontal orientation would be really useful as well as tight control of their position to not waste (sometimes very precious) space.

We should aim to reproduce a figure like this one:
![screenshot_2019-03-01_14-45-00](https://user-images.githubusercontent.com/301546/53662391-c56f1900-3c30-11e9-8218-32f1000009f6.png)

**Comment by huangzhenyu** [comment]
when this issue could be solved? it have been 2years

**Comment by Z-me** [comment]
I applied CSS forcibly because this issue is not solved... 😢

Since this way has a heavy browser load, I want you to create a property that makes this horizontal ColorBar quickly. 🙇 

![image](https://user-images.githubusercontent.com/5908070/70321629-233d2b00-186b-11ea-84a1-67bb176362e8.png)

**Comment by JeroneGagliano** [comment]
Agree with @antoinerg.  This also helps when the corresponding plot changes height based on the data (eg time-series heatmap) and the vertical bar can get cut off.

**Comment by theodcr** [comment]
@JeroneGagliano for your issue you can set the layout height and yaxis domain according to the size of your data, but I agree a horizontal colorbar would be more convenient.

**Comment by rusiano** [comment]
+1

**Comment by elmargasimov** [comment]
+1

**Comment by essafik** [comment]
> 
> 
> I applied CSS forcibly because this issue is not solved... 😢
> 
> Since this way has a heavy browser load, I want you to create a property that makes this horizontal ColorBar quickly. 🙇
> 
> ![image](https://user-images.githubusercontent.com/5908070/70321629-233d2b00-186b-11ea-84a1-67bb176362e8.png)

@Z-me Is that a workaround for the heatmap? If yes, could you share how you managed to get it?

**Comment by nicolaskruchten** [comment]
This issue has been tagged with `NEEDS SPON$OR`

A [community PR](https://github.com/plotly/plotly.js/pulls?q=is%3Apr+is%3Aopen+label%3A%22type%3A+community%22) for this feature would certainly be welcome, but our experience is deeper features like this are difficult to complete without the Plotly maintainers leading the effort.

**Sponsorship range: $10k-$15k**

What Sponsorship includes:
- Completion of this feature to the Sponsor's satisfaction, in a manner coherent with the rest of the Plotly.js library and API
- Tests for this feature
- Long-term support (continued support of this feature in the latest version of Plotly.js)
- Documentation at [plotly.com/javascript](https://plotly.com/javascript/)
- Possibility of integrating this feature with Plotly Graphing Libraries (Python, R, F#, Julia, MATLAB, etc)
- Possibility of integrating this feature with Dash
- Feature announcement on [community.plotly.com](https://community.plotly.com/tag/announcements) with shout out to Sponsor (or can remain anonymous)
- Gratification of advancing the world's most downloaded, interactive scientific graphing libraries (>50M downloads across supported languages)

Please include the link to this issue when [contacting us](https://plotly.com/get-pricing/) to discuss.

**Comment by essafik** [comment]
Maybe I am missing something and I would like to understand where the difficulty resides. Can someone explain to me why implementing this feature is particularly difficult? From my perspective, it is simply a pi/2 rotation of the colorbar with a repositioning. So far, when I really need to have the colorbar horizontal, I just export my graph in svg and do the manipulation manually in Inkscape. It's not practical when having many graphs to do but it does the trick for now. From this manipulation, one can see that the colorbar is a seperate element from the graph so it should be possible to give us a way to rotate and choose the position of the colorbar.

**Comment by usser123** [comment]
+1

**Comment by michaelcraige** [comment]
I would greatly appreciate a solution for moving the color scale bar up top or horizontal below

**Comment by kingdom031** [comment]
> I would greatly appreciate a solution for moving the color scale bar up top or horizontal below

+1

**Comment by Tixierae** [comment]
One more upvote for a horizontal colorbar

**Comment by archmoj** [comment]
> One more upvote for a horizontal colorbar

We are actually working on it : )

**Comment by JeroneGagliano** [comment]
Awesome and thank you!!
Yes, one more upvote for this feature.

Jerone

Jerone Gagliano *PE, CEM*
*Founder & CEO*
brightbuilding.us

**Comment by janosh** [comment]
Thanks @archmoj! Will this be in the next release of plotly.py?

**Comment by archmoj** [comment]
> Thanks @archmoj! Will this be in the next release of plotly.py?

Yes

**Comment by arielhgl** [comment]
Thanks @archmoj! will this be available for the R Plotly distribution, wether through ggplotly or plot_ly?

**Comment by aalyousfi** [comment]
@archmoj I'm using Plotly JavaScript 1.58.5 and I'm still not able to make the colorbar horizontal in a choropleth map.

**Comment by alexcjohnson** [comment]
If you’re using 1.58.5 because it’s “latest” via CDN, please note that we did not advance the “latest” tag to v2.x, to avoid pushing breaking changes to users. Please use an explicit recent version, current is 2.24.2

**Comment by chanansh** [comment]
the issue is since 2016 and still have not solved in 2025! @archmoj
