### ISSUE TITLE
[IE] Y-axis values overlap the title

### ISSUE THREAD

**Issue by maxcopters** [plotly/plotly.js#1247]
Hello,
I have been using plot.ly to draw classical charts, but I observed an issue when my values are very little or very large. This issue only appears on Internet Explorer and Edge (on win10), as I have tested it on Firefox and Chrome.
Here is an example: https://codepen.io/anon/pen/XNPpKN

Could you check this issue?

Thanks!

**Comment by etpinard** [comment]
Thanks for the report.

**Comment by asolagmbh** [comment]
I don't know if it's the same problem or not.
In IE 11 and Edge if you use the pan function for dragging the graph the line of the graph overlap with the y axis. It seems that the line are not cropped in the correct area.
There are plan for resolve this issue? 
Thanks a lot!

**Comment by maxcopters** [comment]
Hello,
I would be very interested in the information whether this ticket could be integrated soon or not.

Regards!
