### ISSUE TITLE
Rangeslider only shows for the first x-axis in multiple subplots

### ISSUE THREAD

**Issue by hy9be** [plotly/plotly.js#1250]
For example in case here: http://codepen.io/plotly/pen/648434b7b06688fc6b00067592d616b0.

If I add ``rangeslider: {}`` to ``xaxis2``, no slider will be rendered.
If I add ``rangeslider: {}`` to both ``xaxis`` and ``xaxis2``, only the first x-axis will have the slider.

It seems the range slider will not work for some of the axes in subplots.

**Comment by hy9be** [comment]
@etpinard Is this a bug or an expected behavior. I read the spec for rangeslider here: https://github.com/plotly/plotly.js/issues/279, and did not find a clue.

Thanks!

**Comment by etpinard** [comment]
It is the expected behavior (for now). Would be a nice addition though.

**Comment by hy9be** [comment]
Thanks!. I would like to try to make a PR for this.

I see that there is a flag named ``isMainPlot`` in the drawing function for rangeslider: https://github.com/plotly/plotly.js/blob/master/src/components/rangeslider/draw.js#L334

Not sure if this is key flag for this.
