### ISSUE TITLE
can not update offline plot with jupyter

### ISSUE THREAD

**Issue by eleanor2017** [plotly/plotly.js#1262]
Hello,
I am working with jupyter offline and would like to **update a plot**, not plot another one.
The following code give me 10 plots, not one being updated 10 times : 

import time
import numpy as np
from plotly.offline import plot
from plotly.graph_objs import *
for i in range(10):
    time.sleep(1)
    iplot([Box(y = np.random.randn(50), showlegend=False) for i in range(45)], show_link=False, filename = 'myfile')

Does plotly offer the possibility to update a plot ofline ?
Thank you!

**Comment by etpinard** [comment]
Well, this has nothing to do with plotly.js.

Please open an issue at https://github.com/plotly/plotly.py/issues/new
