### ISSUE TITLE
hoverformat/tickformat overwrites separators

### ISSUE THREAD

**Issue by merlux** [plotly/plotly.js#1264]
It's not possible to set the separators of thounds and comma when also setting the tickformat or hoverformat.

Settings:
```js
data = [{x:[0],y[2323.45]]
layout={
  separators: ',.',
  yaxis: {
    hoverformat: ',.2r'
  }
}
```

Expected output:
When hover, following number should be printed: "2.323,45".

Example: [Codepen](http://codepen.io/anon/pen/zobmyW)

I want to reformat ticks and hover to not show "k" as thounds, but also keep the localized thousand separator and comma.

**Comment by Romainpetit** [comment]
Indeed, surprisingly. 

`hoverformat` and `tickformat` are using [D3 Format](https://github.com/d3/d3-format/blob/master/README.md#d3-format), which is [configurable with a custom locale](https://stackoverflow.com/a/38211635/869162).

```
var myLocale = {
  "thousands": ".",  // specify that thousands are separated with a dot
  // .. other rules
}
```

Then used like 
```
var localeFormatter = d3.locale(myLocale);
```

Which should do the job. I'll try to use it and keep you posted here

**Comment by rreitmann** [comment]
We are experiencing this as well. Is there any workaround or plan to fix this?

**Comment by rreitmann** [comment]
I have found a workaround for displaying numbers correctly with a german locale if you are using `xaxis.tickformat`:
```javascript
var germanLocale = Plotly.d3.locale({
    decimal: ',',
    thousands: '.',
    grouping: [3],
    currency: ['€', ''],
    dateTime: '%a %b %e %X %Y',
    date: '%m.%d.%Y',
    time: '%H:%M:%S',
    periods: ['AM', 'PM'],
    days: ['Sontag', 'Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag'],
    shortDays: ['So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa'],
    months: ['Januar', 'Februar', 'März', 'April', 'Mai', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember'],
    shortMonths: ['Jan', 'Feb', 'Mär', 'Apr', 'Mai', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dez']
});
Plotly.d3.format = germanLocale.numberFormat;
```

**Comment by etpinard** [comment]
cc @alexcjohnson would may or may not come across the same code paths in his i18n work.
