### ISSUE TITLE
3D hover labels don't show up with `mouse-change@1.4.0`

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#1268]
<strike>**that is 3D hover labels are broken in bundles built from a fresh `npm i`**</strike> --- fixed in `v1.21.3`

Commit https://github.com/mikolalysenko/mouse-change/commit/2aba95014765317eed59b5b58c61aaa6342ef78c and more precisely this [line]( https://github.com/mikolalysenko/mouse-change/commit/2aba95014765317eed59b5b58c61aaa6342ef78c#diff-ba527e2055a8d4c2ab96bee04318fc26R181) ensured that mouse change listeners could be detached. Unfortunately, our gl3d scene code relied on the old (`mouse-change@1.3.0`) buggy behavior [here](https://github.com/plotly/plotly.js/blob/b823573efb1cd910b6f9406502690f4de0c94f6c/src/plots/gl3d/scene.js#L204).

Removing that above line 

```js
 scene.glplot.mouseListener.enabled = false;
```

in `plots/gl3d/scene.js` appears to solve the issue. But, I afraid that it might lead to side-effects such as memory leaks. We should look into this in depth before merging a patch.

**Comment by etpinard** [comment]
cc @dfcreative @alexcjohnson

**Comment by rreusser** [comment]
Am I correct in understanding that plotly simply doesn't use `mouseListener.enabled = true` anywhere? Or if that command was broken, perhaps it *does* use it even though it requests not to. At least I'm not immediately able to find a reference to where it *is* used. It sounds like that might indeed leak a bit of memory then if listeners are attached but never detached.

This is a bit confusing.
