### ISSUE TITLE
Multiple y axes with multiple scattergl traces not working as expected

### ISSUE THREAD

**Issue by halfs13** [plotly/plotly.js#127]
As visible in this [JSFiddle](https://jsfiddle.net/halfs13/v4v86otu/), the same layout config, with two y axes and two traces, produces differing results with scatter and scattergl. With scattergl the trace using `yaxis: y` is hidden by the second axis and trace.

**Comment by mdtusz** [comment]
Confirmed. Thanks for adding the issue.

**Comment by etpinard** [comment]
The complete list of known gl2d limitations is in: https://github.com/plotly/plotly.js/issues/130

**Comment by etpinard** [comment]
> This is still affecting me. What's the ETA on this?

< 1 month away.

**Comment by BEFH** [comment]
Amazing. Thanks

**Comment by etpinard** [comment]
Will be fixed by @dfcreative 's regl-based `scattergl` work:

![image](https://user-images.githubusercontent.com/6675409/34688472-4529face-f480-11e7-9a7f-99e2983791dd.png)

**Comment by dfcreative** [comment]
Test mock 41499e8e658b1ab81f8e1b696fb9c1fd27654a18

**Comment by etpinard** [comment]
done in #2258 (sorry for the 2-year wait)
