### ISSUE TITLE
Two sets of axis and missing buttons on a surface plot

### ISSUE THREAD

**Issue by felixveysseyre** [plotly/plotly.js#1272]
Hello,

I generate several types of graphs from your _Plotly MATLAB API_.

For a given dataset, the plot generated with _PlotlyJS_ seems to present several problems:

- There is two sets of axis: 3D axis (correct) + 2D axis (not correct)
- Buttons to pan, zoom and rotate are not available

Here is a CodePen demonstrating these two problems: http://codepen.io/anon/pen/wobLda

![capture d ecran 2016-12-26 a 12 23 57](https://cloud.githubusercontent.com/assets/4909259/21481287/43b3b296-cb66-11e6-86a0-a1ddb2cc09e1.png)

Thanks for your help !

**Comment by rreusser** [comment]
It looks like there are three traces with `"type": "scatter"`. I deleted those and replotted and it seems probably like what you'd expect. I had a lot of trouble plotting it on codepen (it seems to struggle with strings this long!) so I put the result here:

http://rickyreusser.com/demos/plotly-unsupported/gh-issue-1272.html

**Comment by felixveysseyre** [comment]
Thanks Ricky ! I was able to delete as well the false traces and it is working fine now.

I need to look to the original data in order to understand if the error is related to the data itself or to the _Plotly MATLAB API_.

Thanks !
