### ISSUE TITLE
Hoverdata undefined when animating.

### ISSUE THREAD

**Issue by rreusser** [plotly/plotly.js#1274]
Investigating the cause of failure for `plotly_click` to work *sometimes* when animations are taking place. Tracing through things:

1. [`Fx.click` fires](https://github.com/plotly/plotly.js/blob/master/src/plots/cartesian/graph_interact.js#L1325)
2. [`gd._hoverdata` is `undefined`](https://github.com/plotly/plotly.js/blob/master/src/plots/cartesian/graph_interact.js#L1326) *sometimes*

Investigating the further causes…

cc @bpostlethwaite

**Comment by rreusser** [comment]
I'm having a lot of trouble coming up with a sequence of events that reproduces this 100% of the time, but the problem definitely seems to be the way `hoverdata` is set. It seems like *maybe* it's set on `mousemove` and the *used* on click. Need to investigate further. I suspect the cause is that I'm simply failing to set it 100% of the time when animation changes the hoverdata.

**Comment by etpinard** [comment]
> cc @etpinard I might need some help to get to the bottom of this (tomorrow)

I hope 8 days later is ok too :smile:

**Comment by rreusser** [comment]
Haha, yup!

**Comment by rreusser** [comment]
Hmm… I'm having just a bit of trouble reproducing this. I was mistaken and it appears though some interactions are explicitly disabled in dragbox, click animations do seem to work. It might just take a more complicated example to zero in on buggy behavior. Here's an example that animates continuously and seems to work acceptably with click events: http://rickyreusser.com/demos/plotly-unsupported/interaction-failure.html

See also: #1293

**Comment by rreusser** [comment]
Update. Have isolated a better example. Working on debugging.

**Comment by etpinard** [comment]
@rreusser does https://github.com/plotly/plotly.js/pull/1304 indeed close this issue?

**Comment by rreusser** [comment]
I'll try to do a better job of catching related issues!
