### ISSUE TITLE
scatter plot: is there any way to show multiple hovers or annotations?

### ISSUE THREAD

**Issue by gro-mit** [plotly/plotly.js#1276]
hello
there is a demand described as follow:
in a scatter plot, when the mouse is on or click a point,the information of its k nearest points will appear in the graph via hovers or annotations.

**Comment by etpinard** [comment]
See https://plot.ly/javascript/hover-events/#coupled-hover-events for an example.

In the future, please post questions of the likes on https://community.plot.ly/

Thanks.
