### ISSUE TITLE
Not able to get 3d subplots using Plotly R

### ISSUE THREAD

**Issue by tarunparmar** [plotly/plotly.js#1277]
Hi @etpinard 

I am not able to get all the plots in one picture with below code. This same code worked fine with type="box" and "histogram".
The code below only generates one plot, but if you then check "plots" variables it does have 3 plots.

I found the plotly with Python can do this but there is no R page for this. Check it out here: https://plot.ly/python/3d-subplots/1

Please help.

df <- read.csv('https://raw.githubusercontent.com/plotly/datasets/master/3d-line1.csv')
lst <- levels(factor(df$color))
plots <- list()
for(i in 1:nlevels(factor(df$color))){
subdf <- dplyr::filter(df, color == lst[i])
dens = akima::interp(subdf$x, subdf$y, subdf$z, duplicate = "mean")
p <- plot_ly(x = dens$x, y = dens$y, z = dens$z, colors = c("blue","red"), type = "surface) 
plots[[i]] <- p
}
subplot(plots, nrows = 2)

![image](https://cloud.githubusercontent.com/assets/17690950/21592433/7a1bc6aa-d0db-11e6-9c7f-3c71b55bfa1f.png)

One another note, I am doing subplots for type="contour" and it makes the plots but the legend seems to get overlapped. Can each subplot have its own legends? 

![image](https://cloud.githubusercontent.com/assets/17690950/21592535/3da893aa-d0dc-11e6-829b-73a69e8b4d85.png)

**Comment by etpinard** [comment]
> I found the plotly with Python can do this but there is no R page for this

That's probably because you're using an old version of the R library.

When you can't reproduce your issue JavaScript, please ask your questions on https://community.plot.ly/ 

Thanks

**Comment by tarunparmar** [comment]
Hi @etpinard -  Thanks for your reply.
Sorry I am a bit new to github community. 
I did ask this on community.plot.ly but due to amount to queries there I was worried it would get lost. So thought of opening it up as an issue here as well.
Here is the plotly community link: https://community.plot.ly/t/not-able-to-create-3d-subplots-in-r/3000

Can you give some more hint on what could possibly be an older version in my R library ?
All the packages are up to data that I am using in my code. My plotly is 4.5.6.

**Comment by etpinard** [comment]
You asked your question on December 31. I hope you find it _normal_ that no one has answered it yet.
