### ISSUE TITLE
Multiple axes with scattergl traces causes left axes labels to be cut off

### ISSUE THREAD

**Issue by halfs13** [plotly/plotly.js#128]
Visible in this [JSfiddle](https://jsfiddle.net/halfs13/j99hkLvn/). This may be caused by the same problem that is causing #127.

This also happens with a single x axis and multiple y axes if y is marked `side: 'left'` and y2 is `side: 'right'`

**Comment by etpinard** [comment]
Overlaid axes are not supported in gl2d graphs at the moment.

@halfs13 Thanks for bringing this up. I forgot to port over the known gl2d limitations from plotly's closed-source repo to this repo.

The complete list of known gl2d limitations is in: https://github.com/plotly/plotly.js/issues/130

**Comment by etpinard** [comment]
@halfs13 

Moreover, in all fairness, I do not recommend making gl2d graphs with multiple axes at the moment. 

The current framework creates one canvas and one gl-context per pair of axes, which can be very slow to initialize. 

In its current form, gl2d works great for big data on a single x-y plane. For other layouts, I'd would stick to svg2d.

In the future, we would like to create only one canvas and only one gl-context for all axes.

**Comment by etpinard** [comment]
Will be fixed by @dfcreative 's regl-based `scattergl` work:

![image](https://user-images.githubusercontent.com/6675409/34688320-ba319d0a-f47f-11e7-8897-8f906154f869.png)

**Comment by dfcreative** [comment]
Test mock d646e2c209dd9e306e9a7c950ccc2ed6686713d1

**Comment by etpinard** [comment]
done in #2258 (finally)
