### ISSUE TITLE
3D surface plot with sparse coordinates, or custom x-y grid values

### ISSUE THREAD

**Issue by ryan-williams** [plotly/plotly.js#1290]
I am trying to plot a surface at sparse (x,y,z) coordinates.

In particular, my surface is defined over a domain of [0, 10000] on each (x- and y-) axis, and has been downsampled upstream to just the z-values for {x,y} ∈ {0,1,2,5,10,20,50,100,200,500,1000,2000,5000,10000}², so that I can sketch the surface with ≈14² points instead of 10000².

Ideally I'd like to plot these z-values on logarithmic x- and y-axes.

I'm currently feeding plotly a proper grid – giving the z-value for every xy-pair from the above set – and the shape of the surface is correct, though the labels+hovertext are not, as I have no way to tell plotly that the 4th row (resp. column) corresponds to an x- (resp. y-) value of "5", the 5th is "10", the 6th is "20", etc. It just shows those points at corresponding to x/y values of "4", "5", "6", etc.

[Here](https://plot.ly/~ryan.blake.williams/78/normal-depth-vs-tumor-depth/?share_key=B8K3x4eKTbhoUsPevgX4tE) is an example plot with the above approach; as described above, the input data has already been log-scaled, so the shape is right but the labels are wrong.

**Comment by etpinard** [comment]
Have you tried setting the `x` and `y` fields in your `surface` trace?

For example:

```js
trace = {
  type: 'surface',
  x: [1, 10, 100],
  y: [100, 1000, 2000],
  z: [ [1,2,3], [2,3,4], [3,4,5] ]
}
```

gives:

http://codepen.io/etpinard/pen/dNGXmy

**Comment by ryan-williams** [comment]
Ah, I thought I'd tried that but apparently I'd done it wrong, this works, thanks a lot!
