### ISSUE TITLE
subscripts/superscripts result in misaligned legend text

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#1294]
Legend titles float up too high if you use a subscript or superscript - and even higher if you use both!
This was `name: 'B<sup>C</sup><sub>D</sub>`:
![screen shot 2017-01-11 at 4 07 53 pm](https://cloud.githubusercontent.com/assets/2678795/21866505/809a8e6e-d818-11e6-81a4-07fd9b04e94a.png)

**Comment by rreusser** [comment]
Though a lower priority, mathjax content also seemed slightly misaligned in a way that caused unnecessary legend scrolling: https://github.com/plotly/plotly.js/issues/966

**Comment by Braintelligence** [comment]
@alexcjohnson This was fixed already, right? I can't reproduce this.

**Comment by etpinard** [comment]
Seems to work ok now: https://codepen.io/etpinard/pen/rbBOow
