### ISSUE TITLE
Samsung android browser does not show tooltips on barcharts

### ISSUE THREAD

**Issue by bramklg** [plotly/plotly.js#1296]
Our clients using a Samsung Galaxy S7 report that they don't see hover tooltips for bar charts. We use pie charts and bar charts, the pop-up is working for pie charts. They have the same issue with https://plot.ly/javascript/bar-charts/ and report https://plot.ly/javascript/pie-charts/ is working correctly.

They use the stock (Samsung? Android?) browser, version 4.0.20-78. If they use the mobile Google Chrome browser the tooltips are working correctly. I can't reproduce this myself because I don't have a Samsung phone. I'm not sure where to look. See the attached screenshots. Both screenshots should show a popup but only the pie chart is.

![hover-barchart](https://cloud.githubusercontent.com/assets/1615690/21881685/97e29708-d8a7-11e6-8894-abfbc26be9ae.png)
![hover-piechart](https://cloud.githubusercontent.com/assets/1615690/21881686/97ef246e-d8a7-11e6-95f5-eecc10e5bbe6.png)

**Comment by etpinard** [comment]
Can someone else on a Samsung phone replicate this issue?

**Comment by apxu-devil** [comment]
Hi! 
I use Chrome mobile version 62.0.3202.84.
Os Android 7.0.0, Huawei VNS-L21, build VNS-L21C10B388.
Same problem.

**Comment by etpinard** [comment]
merging with https://github.com/plotly/plotly.js/issues/1967
