### ISSUE TITLE
[Bug] Automatic bar width with single X value too thin for range.

### ISSUE THREAD

**Issue by lewisjb** [plotly/plotly.js#1308]
The width of a bar when there is only 1 X value is too thin in some cases because it doesn't take the xaxis range into account.

Example: http://codepen.io/anon/pen/rjWoyY

As you can see, the only difference between the two plots is one has a second trace, but the thickness of the bars on them is drastically different.

**Comment by etpinard** [comment]
Thanks for the headsup. 

What is the desired behavior in your mind?

In the meantime, note that in `>v1.19.0` you can set the bar width, see example -> http://codepen.io/etpinard/pen/VPPvpM

**Comment by lewisjb** [comment]
@etpinard As I haven't looked at how it currently chooses the width, I wouldn't be able to give a desired behaviour that fits properly. I'm aware it's vague because it is an odd issue to fix, but thought I would put it here in-case somebody had a genius solution.

I did try manually setting the width, but ran into a different issue with it (which you can see in the issue referenced above)

**Comment by etpinard** [comment]
merged into https://github.com/plotly/plotly.js/issues/1346
