### ISSUE TITLE
auto bins and cumulative distribution histograms

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#1318]
We need a way to harmonize autobins across traces, and that it needs to know about cumulative. To make this example work I needed to manually extend the bin range for the red trace, otherwise its CDF ended too soon. Actually, CDFs never end, really... so perhaps the even better thing to do would be to look at the axis range and draw bins out to the edge, while still only using the real data for autoranging? We also need to make sure bin sizes and edges match, which is needed for non-cumulative histograms as well.

![hist_cum_stacked](https://cloud.githubusercontent.com/assets/2678795/22089351/8cd9e198-ddb8-11e6-8de1-fad7a2aaad2e.png)

Originally mentioned in https://github.com/plotly/plotly.js/pull/1189#discussion_r96732116

**Comment by nicolaskruchten** [comment]
Is this now closed?

**Comment by etpinard** [comment]
**Update:**

From the [`hist_cum_stacked`](https://rreusser.github.io/plotly-mock-viewer/#hist_cum_stacked) which sets `xbins: {start: 0.5, end: 10.5, size: 1}` in both traces

![image](https://user-images.githubusercontent.com/6675409/61156542-a4151800-a4c1-11e9-9388-96c966d4639a.png)

then clearing `xbins` we get:

![image](https://user-images.githubusercontent.com/6675409/61156584-bf802300-a4c1-11e9-823c-62f586f03353.png)

which computes shared bins (post https://github.com/plotly/plotly.js/pull/3044) of:

```js
gd._fullLayout._histogramBinOpts.xyx = {
  end: 13.5,
  size: 2,
  start: -0.5
}
```

That is, the default auto xbins essentially have one bin too many. So I'd leave this issue open.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
