### ISSUE TITLE
Webpage `Bar-Charts` demo misspelled attribute `gridwidth` as `grigwidth`

### ISSUE THREAD

**Issue by GramThanos** [plotly/plotly.js#1322]
In the second example "Bar Chart with Hover Text"
the attribute `gridwidth` is misspelled as `grigwidth`.
[https://plot.ly/javascript/bar-charts/](https://plot.ly/javascript/bar-charts/)

The code is also misspelled in the CodePen example
[http://codepen.io/plotly/pen/c11f764ad9de0a40f3f4989517195cf0](http://codepen.io/plotly/pen/c11f764ad9de0a40f3f4989517195cf0)

Also the link to this demo is dublicate because the id `#bar-chart-with-hover-text`
was already used on a previous demo code. So the link
[https://plot.ly/javascript/bar-charts/#bar-chart-with-hover-text](https://plot.ly/javascript/bar-charts/#bar-chart-with-hover-text)
links to the first demo.

**Comment by etpinard** [comment]
Documentation issues should be posted on https://github.com/plotly/documentation/issues/new

Thanks.
