### ISSUE TITLE
Missing certain xaxis labels

### ISSUE THREAD

**Issue by jpmunz** [plotly/plotly.js#1324]
When using ticktext it appears that with certain data sets there are missing xaxis labels. In this example the xaxis label for 'Jan 1' is missing even though the marker for that data point is drawn and the label is shown on hover:
https://jsfiddle.net/hgqhrnrj/5/

The bug only seems to occur with very specific data sets, for example if you remove or reorder one of the items from the data array then 'Jan 1' gets drawn properly.

**Comment by rpaskowitz** [comment]
Pull request against fork per guidelines is at https://github.com/rpaskowitz/plotly.js/pull/1 . Will create new PR against main project if the fix looks good.
