### ISSUE TITLE
Animating the layout of secondary axis fails

### ISSUE THREAD

**Issue by emanuelsetitinger** [plotly/plotly.js#1325]
Please find a reproducible example on CodePen: http://codepen.io/EmanuelS/pen/vgmKRm

This example shows a plot of one x-axis and two y-axes. While animating the range of the x-axis and the primary y-axis works perfectly fine, the range of the secondary y-axis doesn't change after Plotly.animate.

**Comment by rreusser** [comment]
Thanks for the report and example. I'll take a look at this later today.

**Comment by alexcjohnson** [comment]
Looks like this is https://github.com/plotly/plotly.js/blob/master/src/plots/cartesian/transition_axes.js#L18
-> matches `'x2axis'` instead of `'xaxis2'` - I'm abstracting all these regexes right now, should fix this but I'll include a test to confirm.

**Comment by rreusser** [comment]
Ah! That definitely looks like an error on my part.
