### ISSUE TITLE
Error when pan scatter with empty text

### ISSUE THREAD

**Issue by inDream** [plotly/plotly.js#1328]
Change https://github.com/plotly/plotly.js/blob/master/src/components/drawing/index.js#L54
from `if(isNumeric(x) && isNumeric(y)) {` to `if(isNumeric(x) && isNumeric(y) && sel.node()) {`
solved this problem.

Demo: https://jsfiddle.net/indream/6L8nLgr1/

**Comment by rreusser** [comment]
Thanks so much for the report and for tracking this down! That makes pretty good sense. Would you be willing to make a PR for this? This might be small and straightforward enough that it doesn't require a specific test (debatably), but it's still necessary to ensure the tests as a whole are fine. The basic process is:

1. fork the repo
2. make the fix
3. run `npm run lint-fix`, commit, and push to your branch
4. file a PR

That would be greatly appreciated but no pressure. If not I'll try to get a PR together for it.
