### ISSUE TITLE
addTrace with type: 'scattergl' does not show previous traces

### ISSUE THREAD

**Issue by Phasedd** [plotly/plotly.js#133]
I am currently implementing Scatter Plots to graph certain sensor data coming in from robots, the amount of data that comes in becomes to much for just 'scatter' and makes the web app pretty much unusable.

[scattergl (broken)](http://codepen.io/anon/pen/xZVLKx?editors=101)

[scatter (works)](http://codepen.io/anon/pen/obxevb?editors=101)

It may be similar to [#130](https://github.com/plotly/plotly.js/issues/127) but this is more really basic as you can have multiple traces working if you add them at creation, but not add them using addTrace.

**Comment by etpinard** [comment]
Bug confirmed. Thanks reporting.

**Comment by mdtusz** [comment]
Possible fix [here](https://github.com/plotly/plotly.js/pull/140).
