### ISSUE TITLE
Scatter3d: Using lines to connect one point to multiple points

### ISSUE THREAD

**Issue by jrmartin** [plotly/plotly.js#1330]
Hello Plot.ly community,

I'm using a scatter3d graph on a project I'm working on, and one of the features I need is for points to show connections between them. I read the documentation and found that using connectgaps : true shows a connection line between two points, but I need some points to have multiple lines connecting them to other points. Something similar to a network graph, which I found it's available in the python API. Is there a feature like this available in the javascript API? 

Thanks

**Comment by etpinard** [comment]
You can do this using multiple traces. 

Here's an example:

-  https://plot.ly/~chelsea_lyn/9211.embed 
- code -> https://plot.ly/~chelsea_lyn/9211.js

If you have more questions about making 3D network graphs, please use our forums at https://community.plot.ly/ 

Thanks.
