### ISSUE TITLE
choropleth hover labels can get lost

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#1333]
If you zoom into a choropleth (say for example http://localhost:3000/devtools/test_dashboard/#geo_country-names) and hover on a region that goes off the edge, the hover label can get lost. Here's one where you just see the bottom of the Russia label (and if I zoom in a little more it disappears entirely):
![screen shot 2017-01-25 at 9 14 01 am](https://cloud.githubusercontent.com/assets/2678795/22293856/37e0fc9a-e2df-11e6-8069-20c7480b5e46.png)

The label should get pushed down onto the plot, like we do with regular cartesian types:
![screen shot 2017-01-25 at 9 22 14 am](https://cloud.githubusercontent.com/assets/2678795/22294055/d8223b60-e2df-11e6-815f-232bcef9dac5.png)

One thing that may help a bit: the hover labels don't need to be clipped to the same viewport as the plot: the tip of the arrow should be constrained to that viewport, but the rest of the label can go outside (as long as the whole thing stays within`gd`)

**Comment by etpinard** [comment]
> the hover labels don't need to be clipped to the same viewport as the plot

Yeah. That would be a nice improvement to start. Choropleth hover labels should be drawn in the `<g infolayer>` node. While at it, we should :hocho: that useless `<div geo-container>`:

![image](https://cloud.githubusercontent.com/assets/6675409/22432524/223f30d4-e6e3-11e6-9242-67085beb105a.png)

and put the geo nodes in the main `<svg>`.

------------

Down the road, to better handle edge cases, we should consider extending the `hoveron: 'fill'` hover placement algo to geo polygons.
