### ISSUE TITLE
Scattergl fill tozerox/y doesn't work as expected 

### ISSUE THREAD

**Issue by cldougl** [plotly/plotly.js#1334]
`scattergl` fill `tozeroy` fills to lowest y value rather than 0 and behaves inconsistently from `scatter` fill which uses the trace as a bound (see codepen: http://codepen.io/plotly/pen/apyXpW?editors=1010 )

Additionally, we need to fix the attribute description for scattergl [`fill`](https://github.com/plotly/plotly.js/blob/43d3710bdb183f9c1681f40efe8649a7238efce5/src/traces/scattergl/attributes.js#L81) - it should be different from scatter's fill.

**Comment by etpinard** [comment]
maybe we should try to make a push for this in https://github.com/plotly/plotly.js/pull/1869

cc @dfcreative

**Comment by zhangjiang2013** [comment]
Also, the "toself" fill option doesn't work as expected. The enclosed area isn't filled.

**Comment by dfcreative** [comment]
Yes, [regl-line2d](https://github.com/dfcreative/regl-line2d) is capable of filling any shapes now, so fully svg-compatible in that sense. We can cover these cases.

**Comment by etpinard** [comment]
@dfcreative 's regl-based `scattergl` work will get us very close to parity with SVG `scatter`.

I found a few discrepancies: 

From https://rreusser.github.io/plotly-mock-viewer/#scatter_fill_no_opacity, applying `Plotly.restyle(gd, 'type', 'scattergl')` gives:

![image](https://user-images.githubusercontent.com/6675409/34689211-b9340368-f482-11e7-88c8-ced11ad8590e.png)

In https://rreusser.github.io/plotly-mock-viewer/#scatter_fill_self_next, it appears that the bounding lines coloring in gl is blended a little bit. See svg:

![image](https://user-images.githubusercontent.com/6675409/34689302-ff102d30-f482-11e7-9cdb-72797a321a3a.png)


vs gl (ignore the lack of `line.shape`)

![image](https://user-images.githubusercontent.com/6675409/34689310-05701a5a-f483-11e7-9710-5e12b358ef60.png)

**Comment by dfcreative** [comment]
@etpinard 3b08da1b00cd43dc36546b80ab3669d2d60a9e23 should fix both. Although https://rreusser.github.io/plotly-mock-viewer/#scatter_fill_no_opacity does not fail now, it requires detailed consideration.

**Comment by dfcreative** [comment]
Added mock test https://github.com/plotly/plotly.js/pull/2258/commits/d3fd7d28d881db878e2cc5c10cbb45e566718170
![image](https://user-images.githubusercontent.com/300067/35091746-7171f6b0-fc4e-11e7-8f95-fa7d1f6ce6ba.png)

**Comment by etpinard** [comment]
I'm going to close this thing as the issue title refers to to-zero fills which are fixed in https://github.com/plotly/plotly.js/pull/2258

For more fill open items, see https://github.com/plotly/plotly.js/issues/130
