### ISSUE TITLE
Custom mode bar buttons are displayed upside down 

### ISSUE THREAD

**Issue by bruno-rino** [plotly/plotly.js#1335]
The mode bar icons that ship with plotly are for some reason flipped vertically. To compensate, plotly applies transformation matrix that includes a vertical flip (the -1 in the following line):

[`path.setAttribute('transform', 'matrix(1 0 0 -1 0 ' + thisIcon.ascent + ')');`](https://github.com/plotly/plotly.js/blob/master/src/components/modebar/modebar.js#L176)

To illustrate: the following example of how to add a custom icon uses a SVG path that looks good, because it is actually an upside down image (I render the SVG inline for comparison): http://codepen.io/bruno-rino/pen/bgowQx

The `-1` in the transformation matrix should be configurable. Or else any normal SVG path has to be flipped manually (and I don't know even how to go about doing that) before it can be used as an icon in the mode bar.

**Comment by etpinard** [comment]
Ha. Good catch. 

Yes, our stock mode bar icons use bottom-to-top y axis (from [fontastic.me](http://fontastic.me/) I believe) which need to be flipped in the browser. 

We have a few options here:

### 1- reverse our icons

in [`src/fonts/ploticons/`](https://github.com/plotly/plotly.js/tree/master/src/fonts/ploticon) and remove the useless `-1` matrix transform. Problem: some users might be currently using our built icons paths by accessing them [here](https://github.com/plotly/plotly.js/blob/master/build/ploticon.js); this change might be considered _backward incompatible_.

### 2- add a general transform field

for example

```js
modeBarButtonsToAdd: [{
    name: 'my icon',
    icon: /* icon string path */,
    ascent: 100,
    transform: 'matrix(1 0 0 -1 0 100)',
    click: function(gd) { }
}]
```

This solution might be too confusing for some.

### 3- add a `flip` boolean field

or `direction: 'up' | 'down'`, ...

```js
modeBarButtonsToAdd: [{
    name: 'my icon',
    icon: /* icon string path */,
    ascent: 100,
    filp: true,
    click: function(gd) { }
}]
```
------

Personally, I prefer a type **3** solution (once we agree on the field name and values) for its simplicity. unless you think we need to cover other cases through the API.

**Comment by rreusser** [comment]
Perhaps `flipy` is more descriptive both since it's more fully descriptive and since `flipx` could conceivably be useful too (left right arrows without needing two separate icons?)

**Comment by bruno-rino** [comment]
The spikeline icon required a special matrix; so maybe option 2 would be best?

**Comment by vdh** [comment]
So did anyone actually get around to fixing this, or are we forced to always have a flip transform applied to custom icons whether we like it or not?

**Comment by etpinard** [comment]
> So did anyone actually get around to fixing this,

No.



> or are we forced to always have a flip transform applied to custom icons whether we like it or not?

Right now, yes. But we're hoping to add an option as proposed in https://github.com/plotly/plotly.js/issues/1335#issuecomment-276138485

**Comment by etpinard** [comment]
Resolved by @vdh 's https://github.com/plotly/plotly.js/pull/2762
