### ISSUE TITLE
Allow legend to use bottom margin space?

### ISSUE THREAD

**Issue by rpaskowitz** [plotly/plotly.js#1340]
Would the team accept a PR to optionally allow the legend to expand in to the bottom margin area?

![image](https://cloud.githubusercontent.com/assets/1222909/22389125/f33ba534-e498-11e6-87aa-8e3da8710796.png)

Currently this space is un-used since there will never be x-axis labels in this place, and it would allow for more legend entries to be shown before scrolling.

Visually, some people may prefer to have the legend entries align entirely with the graph area, but in my case, it would be preferable to use the space to show more.

Here is an example of the legend_scroll mock with 100% of the bottom margin used. (I'd probably preserve some margin, also maybe configurable so it doesn't go right to the bottom of the div).

![image](https://cloud.githubusercontent.com/assets/1222909/22389213/434c8002-e499-11e6-950b-426cf0eaeedf.png)

**Comment by etpinard** [comment]
Sounds like a solid idea :+1: 

I'd vote for adding a `len` attribute (short for `length`) similar to what we use current for configuring the span of colorbars and sliders. By default, its maximum value would be `1` corresponding in pixels to:

```js
// for vertical legends
layout.height - (layout.margin.t + layout.margin.b) 

// for horizontal legends
layout.width - (layout.margin.l + layout.margin.r) 
```

This `len` attribute would allow users to specify e.g.

```js
layout = {
  len: 1.2
}
```

which would make the legend span into the bottom margin.

**Comment by rpaskowitz** [comment]
To achieve the effect I showed, I had modified:
```
-        legendHeightMax = gs.h;
+        legendHeightMax = fullLayout.height - gs.t;
```

I think gs.h works out to `layout.height - (layout.margin.t + layout.margin.b) ` as you mention.

Would you recommend that (roughly):
```
x = layout.height - (layout.margin.t + layout.margin.b) 
legendHeightMax = x * opts.layout.len
```

**Comment by etpinard** [comment]
@rpaskowitz yep, that sounds about right. 

Would you mind making a PR so that we can test this solution in detail?

**Comment by etpinard** [comment]
In doing so, we should try to make `updatemenus` re-use @n-riesco 's brilliant [`scrollbox`](https://github.com/plotly/plotly.js/blob/master/src/components/updatemenus/scrollbox.js) module.

**Comment by saimaparveen** [comment]
I need this .. is there any way we can get this working in v1.26.1 ?

**Comment by etpinard** [comment]
> I need this .. is there any way we can get this working in v1.26.1 ?

@saimaparveen ... if only life was that easy.

**Comment by cpsievert** [comment]
+1 for a `len` attribute. It would also be useful to have in `ggplotly()` when trying to layout colorbar(s) with a legend (relatedly, https://github.com/plotly/plotly.js/issues/1244 would be awesome to have)
