### ISSUE TITLE
afterplot event not fired on load

### ISSUE THREAD

**Issue by tjmcewan** [plotly/plotly.js#1341]
The `afterplot` event isn't fired until the chart is interacted with in some way.  It seems like this isn't the intention?  I'd like to be able to hook to an event that is fired when the chart is finished loading for the first time.

Reproduction:

1. Go here: http://codepen.io/plotly/pen/QbZmZY
2. Open your console
3. Reload the page and observe that no event is fired.

If this is not the intention, do you have a recommended workaround?

Thanks. :)

**Comment by etpinard** [comment]
Thanks for the report.
