### ISSUE TITLE
Autorange for log plot doesn't show all the data

### ISSUE THREAD

**Issue by neilmb** [plotly/plotly.js#1352]
When using `autorange: true` with `type: "log"`, the default scaling does not show all of the data. The example is at https://jsfiddle.net/crq1tkjy

![screen shot 2017-02-03 at 14 28 42](https://cloud.githubusercontent.com/assets/443389/22607354/1aa7388e-ea1d-11e6-93c6-d12ebe1e4182.png)

I expected to be able to see both the maximum and minimum values by default, instead anything over 10k is off the top of the graph.

**Comment by etpinard** [comment]
I was able to reproduce this bug with much simpler data in http://codepen.io/etpinard/pen/jBwoOL

Looks like the problem only affects bar traces.

Pinging @alexcjohnson in case this problem rings a :bell:

**Comment by alexcjohnson** [comment]
Hah, how can we not have an autoranged log axis bar chart anywhere in our tests? 0.1 to 10^4 is the default y axis range (-1 to 4), there's a problem with the log/linear conversion. I'll sort it out.

**Comment by neilmb** [comment]
What is the timing of the release process when this change will hit the CDN?
