### ISSUE TITLE
[Feature Request] States from Brazil on geo maps

### ISSUE THREAD

**Issue by tberne** [plotly/plotly.js#1354]
Hi,
It would be really nice if there could be a Brazilian state map view (like [USA-states location mode](https://plot.ly/javascript/reference/#scattergeo-locationmode)).

Thanks!

**Comment by FlorinAndrei** [comment]
World cities would be awesome, too.

**Comment by s3630237** [comment]
Hi Guys,
I have the long and lat values for stores within Australia. I fed these values into plotly scattergeo to generate a bubble map but to no avail. I get a single bubble in the middle of Australia. Ive been using the following parameters, locations = ["Australia"], locationmode = 'country names'. After doing alot of research, is it it fair to say that plotly will only recognise US locations?

**Comment by nicolaskruchten** [comment]
You can certainly plot points anywhere on the earth. `locationmode="country names"` means that points will be placed according to the value of `locations`, which in your case you've set to Australia, so all points get located in the middle. Try not setting `locationmode` or `locations` and instead setting `lat` and `lon` and your points should render in the desired locations.

**Comment by nicolaskruchten** [comment]
More generally: we are not planning on adding new built-in geographies to this library, but we have added the `geojson` attribute to all our geo traces so develops can provide their own geographies :)

**Comment by s3630237** [comment]
Thanks a lot Nicholas, that worked seamlessly! Cheers Bill.
