### ISSUE TITLE
Contours not rendered correctly with semi-transparent colorscale

### ISSUE THREAD

**Issue by rreusser** [plotly/plotly.js#1356]
**Expected behavior**: contours with < 100% opacity render correctly

**Observed behavior**: This json:

```javascript
{
  type: 'contour',
  z: [[1, 2], [3, 4]],
  colorscale: [
    [0, 'rgba(0, 0, 0, 0.5)'],
    [1, 'rgba(0, 0, 0, 0.5)']
  ]
}
```

produces the following plot.

<img width="397" alt="screen shot 2017-02-06 at 16 45 17" src="https://cloud.githubusercontent.com/assets/572717/22667640/ad1be320-ec8b-11e6-975c-0eb4119c503c.png">

The colorscale has no variation, so I'd expect a flat region with 50% black. See: http://codepen.io/rsreusser/pen/PWBjZG

**Analysis**: The reason is that contours are drawn on top of one another vs. the region *between* successive levels. That is, the colors are assumed fully-opaque so that it makes no difference.

For carpet plots inequality ranges, I had to do some magic on the extracted paths to flip paths and render the area *between* contours levels. That would maybe work here. The downside of this approach for regular contour plots is that the SVG paths will not rasterize and antialias nicely without a small gap between them. Of course if there's any line between them, it makes no difference.

**A potential workaround**:

1. Remove any opacity and draw the overlapping contours, as we do now
2. Draw the overlapping contours once more, rendering the alpha as black-white
3. Use (2) as a `mask` of (1) (as opposed to a `clip-path`)

Since masks are opacity-aware, I *believe* this would produce the expected result without unpleasant artifacts. The downside is that the SVG has to internally rasterize and composite multiple layers, which seems to be significantly slower. It would need some testing to ensure this is viable.

ping @alexcjohnson for any details I may have missed based on previous discussion

**Comment by etpinard** [comment]
Weird. I thought that was fixed in https://github.com/plotly/plotly.js/pull/1090 ?

**Comment by rreusser** [comment]
@etpinard I believe transparent colorscales *work*, they just don't produce the expected result for contour plots since the regions are drawn on top of one another with the assumption that they're fully opaque.

**Comment by etpinard** [comment]
Ha. I see. Nice catch :eyes:

**Comment by rreusser** [comment]
Discussion with @alexcjohnson was mainly that the semi-easy fix of flipping adjacent paths to fill proper bands has the unpleasant artifact of this sort: http://graphicdesign.stackexchange.com/questions/55816/fix-gap-between-path-and-shapes-in-illustrator

<img width="379" alt="screen shot 2017-02-06 at 17 03 00" src="https://cloud.githubusercontent.com/assets/572717/22668275/21da98e4-ec8e-11e6-82a0-8ec6d318b579.png">

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
