### ISSUE TITLE
financial charts: calling relayout(gd, {'xaxis.type': '-'}), returns gd.layout.xaxis.type = 'category'

### ISSUE THREAD

**Issue by VeraZab** [plotly/plotly.js#1357]
Somehow, that newPlot call gets called with xaxis.type = 'category'.. instead of '-' as per our relayout call. 

Codepen: http://codepen.io/veraz/pen/VPBprr?editors=0010

**Comment by etpinard** [comment]
Strange. `ohlc` appears to behave fine http://codepen.io/etpinard/pen/WRKEp

@VeraZab can you confirm that `ohlc` are ok?

**Comment by VeraZab** [comment]
Yes, ohlc is ok
