### ISSUE TITLE
"Collaborate" modeBarButton not removable?

### ISSUE THREAD

**Issue by shosaco** [plotly/plotly.js#1361]
Dear team,

first of all, thanks for you great work. I want to remove the modebar button "Collaborate" using

    plot_ly(data = iris, x = ~Sepal.Length, y = ~Petal.Length) %>% layout(modeBarButtonsToRemove = "collaborate"). 

However, it is not disappearing (the other ones are working fine)

The other buttons are removable. I also can't find the Collaborate handling in https://github.com/plotly/plotly.js/blob/master/src/components/modebar/buttons.js

**Comment by etpinard** [comment]
That _collaborate_ button is a R library specific feature. Please file your report on https://github.com/ropensci/plotly/issues/new thanks.
