### ISSUE TITLE
tickvals and ticktext showing same values

### ISSUE THREAD

**Issue by suribabu39** [plotly/plotly.js#1366]
Hi, I am trying to plot charts using plotly js but when axis labels are tool long they are going out, overlapping with titles so I tried to use tickvals. After using tickvals both (on hover and while plotting axis labels it is showing ticktext). I am new to to plotly and got stuck here.
Thank you in advance
Codepen link: http://codepen.io/suribabu_95/pen/egLGgB

**Comment by etpinard** [comment]
Hmm. I'm not sure I understand your question. Looks like your `tickvals` / `ticktext` solution is working properly. What is the desired behavior in your mind?

**Comment by suribabu39** [comment]
Tickvals should be shown on hovering over the chart and ticktext should be displayed as axis labels. In my case ( http://codepen.io/suribabu_95/pen/egLGgB ) D1, D2, so on should be shown on axis while plotting(which it is showing) but on hovering over the chart also it is showing D1, D2, so on but I want to show tickvals which are Domain1, Domain2, so on on hovering over chart.
Let me know if it is still not clear.
Thank you

**Comment by rpaskowitz** [comment]
Does http://codepen.io/anon/pen/MJLvqV do what you want?

**Comment by suribabu39** [comment]
Yes that is exactly what I needed. Thank You very much
I have a small doubt though, Suppose If a had legends(whose values are long) also and I want to show them on too on hovering. Should I append them to x-axis values and put in "text" field ?
My question is If I had anything which I want to show on hovering should I add to "text" field and put in "hoverinfo" ?

**Comment by rpaskowitz** [comment]
For the `hoverinfo`, you can simply add more content to the 'text' array. `hoverinfo` itself only accepts a few specific items to control what it shows, see https://plot.ly/javascript/reference/#bar-hoverinfo

Regarding the legend, it will be the series name shown and not information related to the data points. Plotly will try to size the chart and legend to fit the series names, but if the series name grows too long, you may encounter some issues. For that reason, you may want to truncate series names ahead of time, and then toss a custom tooltip on the legend so people can get the full name.

Here's an example with more text shown on hover, and a moderately long series name in the legend. Add more text to the series name to see why you may want to truncate to a fixed length. http://codepen.io/rpaskowitz/pen/PWVLvv

**Comment by etpinard** [comment]
Closing as this issue won't directly lead to a patch.

@suribabu39 questions of the likes are better asked on https://community.plot.ly/ to let other users comment and offer solutions. Thanks for using plotly.js :+1:
