### ISSUE TITLE
scattergl plot shapes not working

### ISSUE THREAD

**Issue by ifll** [plotly/plotly.js#1372]
I don't know if it is a known issue but it seems that shapes don't work on scattergl plots.

Here there are two identical code-pens one with svg (scatter plot type) and the other with webgl (scattergl plot type) to demonstrate this issue:

  - svg: http://codepen.io/NTX11/pen/WRLYaQ
  - webgl: http://codepen.io/NTX11/pen/PWXxEg

Does anyone know if this will be fixed soon for "scattergl" plots?

I think it is a quite important feature for scatter plots... 

Thank you!

**Comment by ifll** [comment]
I've seen now it is on the known limitations already: #130 
Still, any idea when this could be solved or when those limitations will be planned to be solved?

Webgl is quite more powerful than SVG when plotting a lot of points in scatter plots, so it would be very nice to have same great features as there are in SVG plots...

Thank you!

**Comment by destradafilm** [comment]
@etpinard I forked plotly and made a branch to add more symbols to the scattergl plot. According to the PR guidelines, a maintainer needs to review changes

https://github.com/destradafilm/plotly.js/tree/scattergl-on-par-shapes

**Comment by etpinard** [comment]
Thanks for the PR @destradafilm I don't think these are the _shapes_ @ifll was referring to.

**Comment by ifll** [comment]
Nope.. by shapes I meant drawing lines and other geometrical figures... I think it is quite easy to check what I meant on the codepens I provided

But anyway, thank you very much @destradafilm for improving scattergl plots :D

**Comment by destradafilm** [comment]
Okay, now I'm trying to implement a 'line of best fit' or 'regression line' and need this feature as well

**Comment by etpinard** [comment]
worth thinking about in https://github.com/plotly/plotly.js/pull/1869

cc @dfcreative

**Comment by etpinard** [comment]
Will be fixed by @dfcreative 's regl-based `scattergl`:

![image](https://user-images.githubusercontent.com/6675409/34687715-95f9b582-f47d-11e7-853b-0fc62eeef2f2.png)

---

We should add a test mock for this thing before merging.

**Comment by dfcreative** [comment]
https://github.com/plotly/plotly.js/commit/42872138d611ecbbf4686e6c5e9a9dfa96241f38 adds shapes test mock

**Comment by etpinard** [comment]
Done in https://github.com/plotly/plotly.js/pull/2258
