### ISSUE TITLE
Uncaught (in promise) ReferenceError: MathJax is not defined

### ISSUE THREAD

**Issue by ssjunior** [plotly/plotly.js#1380]
This is a simple bar chart that I don't think that should need MathJax. 

The legends are being rendered wrong and there is nothing unconventional there. Pie charts are OK with the same data set:

Without MaxJax
http://codepen.io/ssjunior/pen/QdoygK

With MathJax
http://codepen.io/ssjunior/pen/EZMPXE

**Comment by etpinard** [comment]
Thanks for the report. 

Having two `$` in one string that appears in SVG `<text>` break plotly.js at the moment if `MathJax` isn't loaded on the page. 

We could do definitely add a better _fallback_ here :smile:

**Comment by etpinard** [comment]
This is actually a duplicate of https://github.com/plotly/plotly.js/issues/1248

Closing.
