### ISSUE TITLE
`Virgin Islands (U.S.)` overwrites `United States` in choropleth

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.js#1381]
![image](https://cloud.githubusercontent.com/assets/1280389/22960215/0a59e800-f30a-11e6-9685-a3a83da6ff94.png)

USA is getting colored in as 10 instead of 1.

Here is the example: https://plot.ly/~chris/18329.embed

**Comment by etpinard** [comment]
`Virgin Islands (U.S.)` passes the USA regex in the [countrycode](https://github.com/vincentarelbundock/countrycode) package whereas `Virgin Islands` passes the [VIR](https://countrycode.org/virginislands) regex.

@chriddyp would you mind opening an issue upstream in https://github.com/vincentarelbundock/countrycode about this?

**Comment by cjyetman** [comment]
pretty sure this has been fixed already upstream... make sure you're using the [most recent version (0.19) of countrycode](http://cran.r-project.org/web/packages/countrycode/index.html).

**Comment by etpinard** [comment]
Thanks for your help @cjyetman !
