### ISSUE TITLE
Axis equal option

### ISSUE THREAD

**Issue by geocosmite** [plotly/plotly.js#1384]
In some situations it is important that the distance for a given range in data is identical along the x and y axes (or z for 3D plots). In Matlab it is possible to use the "axis equal" constraint in such cases but I haven't yet been able to find equivalent functionality in Plotly.

I have been successful at getting the correct aspect ratio for the axes and ranges for the case depicted below left where (1) the plot width and height are identical, (2) the x-axis and y-axis ranges are identical, and (3) the plot legend is wholly within the axis boundaries.  (The two magenta "measuring sticks" on the outer axis bounds have identical lengths in the plot.)  An example of where I have failed, however, is the case below right where the plot is configured identically except that the legend now is to the right of the x-axis upper bound. Here what I would like to have happen is that the y-axis of the plot would shrink such that its upper bound (35) would move down to the position of the horizontal magenta line. In this way the data / axis aspect ratio would be identical to that of the x-axis. I know that this effect could be accomplished by reducing the plot height but I see no a priori way to know what value to use to preserve the data / aspect ratio given that I have no information on the width of the legend.

![image](https://cloud.githubusercontent.com/assets/25803192/22993026/b99cdf24-f37e-11e6-8ff7-73f5efbf0ada.png)

An additional example of where the axis equal option would be invaluable is where the 'heatmap' and 'contour' plot types are used to show map data that are plotted in UTM coordinates as illustrated below.  In this case it is difficult to ensure that the x-axis and y-axis / data aspect ratios are identical due to the presence of the color bar.

![image](https://cloud.githubusercontent.com/assets/25803192/22993081/ea928db8-f37e-11e6-821c-04e15c170d6d.png)

**Comment by rreusser** [comment]
Are you referring to setting an aspect ratio? If so, there's a bit of discussion on how this might be accomplished at: https://github.com/plotly/plotly.js/issues/272

**Comment by etpinard** [comment]
merging with #272
