### ISSUE TITLE
Allow node client to read ~/.plotly/.credentials

### ISSUE THREAD

**Issue by ryan-williams** [plotly/plotly.js#1386]
It seems that the only way to auth with the node client is to put your username and api-key (effectively password) into your source ([docs](https://plot.ly/nodejs/getting-started/)).

It would be better if there were an option to have it read credentials from `~/.plotly/.credentials`, like the python client does.

I'm trying to ship a script that users can run to generate a plot with data of their choosing; putting my own credentials into that script / my SCM is not desirable or sensible.

Perhaps I've missed a way to do this currently? As it is, I'm going to parse `~/.plotly/.credentials` myself in JS, and pass the u/p to `require('plotly')`.

**Comment by etpinard** [comment]
I believe you're looking for this repo https://github.com/plotly/plotly-nodejs
