### ISSUE TITLE
Support additional tags for Annotations

### ISSUE THREAD

**Issue by destradafilm** [plotly/plotly.js#1387]
It would be great to be able to add html tags (divs, img, svg) into the annotations. Specifically the 'scatter' and 'scattergl' plots. 

Currently seems like only basic tags like br, b, i, and span are supported but would be good to not have a limitation

I've seen this brought up in the community boards...Is this being considered at all?

**Comment by jackparmer** [comment]
@destradafilm Probably not in the near future without sponsorship from a company.

**Comment by destradafilm** [comment]
@jackparmer Thanks for your response. What exactly do you mean by sponsorship from a company?

**Comment by jackparmer** [comment]
@destradafilm companies can contact us to sponsor financially plotly.js feature development: 
https://plotly.typeform.com/to/mH1Cpb

**Comment by marcusblevin** [comment]
@jackparmer What about adding more basic formatting tags? I currently manually add the following:
strong:"font-weight:bold",
strike:"text-decoration:line-through",
h1:"font-size:2em",
h2:"font-size:1.5em",
h3:"font-size:1.17em",
h4:"font-size:1em",
h5:"font-size:0.83em",
h6:"font-size:0.67em",
p:"padding:0em 1em 0em 1em"

**Comment by jonfreedman** [comment]
I would like to be able to use [flag-icon-css](https://github.com/lipis/flag-icon-css) in an annotation which would require the ability to not strip out classes when converting from span to tspan in svg_text_utils

**Comment by alexcjohnson** [comment]
@jonfreedman we could certainly allow class to pass through from the pseudo-html to the svg, my concern (and this applies to some of the other suggested additions as well) is that referencing external content means the plot loses portability, or at least would lose that content if rendered elsewhere. That would be a first for plotly.js, at least as far as the plot's static behavior is concerned.

**Comment by jonfreedman** [comment]
I see your point, I noticed that the react wrapper exposes style and classname on the parent element, is that a similar blurring of portability?

**Comment by DaniMori** [comment]
It would be useful if this applied to tooltips as well.  I recently got stuck while trying to include an <img> inside a tooltip in a chart.

**Comment by DaniMori** [comment]
Alright! I think this improvement could be really useful, so I'll open up a new issue.

**Comment by DaniMori** [comment]
Already addressed in #6420
