### ISSUE TITLE
This bubble charts isn't working

### ISSUE THREAD

**Issue by suribabu39** [plotly/plotly.js#1397]
Hi, 
For certain range of values(x, y, size in trace) bubble chart is not plotting, Maybe it is plotting but clearly not visible. For most of range it is working but for certain range of values it is not working. Is there any constraint on the value ranges or should I maintain a ratio?
One such example where it doesn't plot any chart is here (http://codepen.io/suribabu_95/pen/egwPrG?editors=0010)

Thank You

**Comment by etpinard** [comment]
Strange.

Back in `v1.7.0`, your bubble chart would've looked like http://codepen.io/etpinard/pen/VPJVyv

At first glance, it looks like very large bubbles are throwing off the marker sizing routine.

> Is there any constraint on the value ranges or should I maintain a ratio?

Yes. Try using `marker.sizeref` as in http://codepen.io/etpinard/pen/VPJVyv

**Comment by etpinard** [comment]
This bug is a side-effect of (the very controversial) https://github.com/plotly/plotly.js/pull/353

**Comment by etpinard** [comment]
More closely, the problem lies inside the autorange [routine](https://github.com/plotly/plotly.js/blob/d8441a080aba8269ce20260a69a2bf8f68fb13ba/src/plots/cartesian/axes.js#L235-L247): where very large bubbles make

```js
dp = ax._length - minpt.pad - maxpt.pad;
```

always be negative and hence excluded from the the autorange computation. Perhaps `dp` should be constrained?

**Comment by etpinard** [comment]
Referencing https://github.com/plotly/plotly.js/issues/1352 which also highlights `getAutoRange` issues.

**Comment by etpinard** [comment]
Fixed _as best we can_ in https://github.com/plotly/plotly.js/pull/2960/commits/1f4898c7b638aa6711c6abbb6691cfe3a4024e1a
