### ISSUE TITLE
plotly conditional add trace stopped working after the new release...

### ISSUE THREAD

**Issue by eralpdogu** [plotly/plotly.js#1399]
After the release of new plotly version, we started getting errors for the traces on a run chart. Code chuck is as follows. 

p <- plot_ly(plot.data
               , x = QCno
               , y = CUSUM.poz
               , line = list(color = "dodgerblue")
               , name = "CUSUM+"
               , showlegend = FALSE
               , text = Annotations
   ) %>%
  layout(xaxis = x,yaxis = y, showlegend = FALSE) %>%
  add_trace(x=c(0, max(plot.data$QCno)),y = c(CUSUM.outrange.thld,CUSUM.outrange.thld),     marker=list(color="red" , size=4 , opacity=0.5), name = "UCL",showlegend = FALSE) %>%
  add_trace(x=c(0, max(plot.data$QCno)),y = c(-CUSUM.outrange.thld,-CUSUM.outrange.thld), marker=list(color="red" , size=4 , opacity=0.5), name = "LCL",showlegend = FALSE) %>%
  add_trace(  x = QCno
                 , y = CUSUM.poz
                 , mode = "markers"
                 , marker=list(color="blue" , size=5 , opacity=0.5)
                 , showlegend = FALSE,name=""
     ) %>%
  **add_trace(x = plot.data[CUSUM.poz <= -CUSUM.outrange.thld, ]$QCno,
               y = plot.data[CUSUM.poz <= -CUSUM.outrange.thld, ]$CUSUM.poz,
               mode = "markers",
              marker=list(color="red" , size=5 , opacity=0.5),
              showlegend = FALSE,name=""
     ) %>%
     add_trace(x = plot.data[CUSUM.poz >= CUSUM.outrange.thld, ]$QCno,
               y = plot.data[CUSUM.poz >= CUSUM.outrange.thld, ]$CUSUM.poz,
               mode = "markers",
               marker=list(color="red" , size=5 , opacity=0.5),
               showlegend = FALSE,name=""
     )%>%**
   )

We could convert the main traces by replacing "tilda"s but we still need a solution for the last two traces (in bold). Please comment if you have a quick fix or any ideas.

Thanks,
Eralp

**Comment by etpinard** [comment]
Can you reproduce this bug in JavaScript?

If not, please open your report @ https://github.com/ropensci/plotly/issues/new

Thanks.

**Comment by eralpdogu** [comment]
Thanks...I forwarded it to the other group.
