### ISSUE TITLE
UMD is broken

### ISSUE THREAD

**Issue by Hypercubed** [plotly/plotly.js#14]
The browserify generated UMD files are broken by `appendVersion` in your bundle task.  For CommonJS loading systems `Plotly` in the last line of `plotly.js` and `plotly.min.js` (`Plotly.version='1.0.0';`) is undefined.

P.S. Great work!  Thanks for making this open source.

**Comment by etpinard** [comment]
@Hypercubed thank you so much for bringing this up.

I was about to use https://github.com/webpro/versionify to add the package.json version on the exported object, but got scared off by https://github.com/webpro/versionify/issues/11 so I decided to come up with a my own ad hoc routine.

Can you recommend an other way of adding the version on the bundle's exported object?

**Comment by Hypercubed** [comment]
Sorry, I can't think of an easy way off the top of my head.  I usually don't include version numbers in dist files.  Plus doesn't this introduce an inconsistency between the CommonJS version and the dist version?

**Comment by Hypercubed** [comment]
I can confirm that UMD in the fix-umd branch (after `npm run build`) works (loading using SystemJS).
