### ISSUE TITLE
Aitoff and sinusoidal geo projections

### ISSUE THREAD

**Issue by collioud** [plotly/plotly.js#1400]
Hello,

I noticed by looking at the _plotly.js_ file that two geo projections are already included : the _aitoff_ and the _sinusoidal_ one. But these are not directly usable because they are not referenced.
This could be done by adding the two following code lines into the _plotly.js_ file :

```
// projection names to d3 function name
params.projNames = {
    // d3.geo.projection
    ...
    'aitoff': 'aitoff',           
    'sinusoidal': 'sinusoidal'   
};
```

Of course, the API reference should be also updated.

I am very pleased that these are already included since I need the aitoff projection for one project of mine. I didn't feel adding a projection "from scratch" into Plotly.js...

**Comment by etpinard** [comment]
Ha good :eye: 

The sinusoidal projection is indeed exported in our projections [bundle](https://github.com/plotly/plotly.js/blob/d8441a080aba8269ce20260a69a2bf8f68fb13ba/src/plots/geo/projections.js#L406) but currently and mistekenly not exposed.

I don't think we ever planned on exposing the Aitoff projection, but as the popular Winkel Triplet projection [depends](https://github.com/plotly/plotly.js/blob/d8441a080aba8269ce20260a69a2bf8f68fb13ba/src/plots/geo/projections.js#L428) on Aitoff, might as well expose it also.

Thanks for posting!
