### ISSUE TITLE
Lasso & box selection in scattermapbox

### ISSUE THREAD

**Issue by jackparmer** [plotly/plotly.js#1402]
It would be nice to expand the `scattermapbox` modebar to support lasso and box selection. Ideally, it would fire a `plotly_selected`event with the same data structure as cartesian plots.`scattermapbox` could be another maps option in addition to leaflet for R Shiny and linked view examples such as these.

![](https://cpsievert.github.io/plotly_book/images/plotlyLeaflet.gif)
https://cpsievert.github.io/plotly_book/linking-views-without-shiny.html#linking-with-other-htmlwidgets

![image](https://cloud.githubusercontent.com/assets/1865834/23185785/a15ea0ea-f852-11e6-96d2-524fa2c0f7a3.png)
http://cpsievert.github.io/pedestrians/tour-dendro/

**Comment by r1z1a** [comment]
Would be great too have the lasso and box select for Histogram and Bar Chart as well.
