### ISSUE TITLE
Scatter polar title issues

### ISSUE THREAD

**Issue by brian428** [plotly/plotly.js#1404]
I noticed a few issues with the titles of scatter polar plots:

- titlefont has no effect (http://codepen.io/brian428/pen/vgoqYw)
- seems to be no way to increase space between title and chart
- using HTML in title causes title text to become way off center
- There seem to be no controls for polar scatter plots (zoom, select, etc.)

**Comment by brian428** [comment]
One more: when using only one or two traces, the polar scatter shows additional non-existent traces in the legend. I'm not sure where they're coming from. http://codepen.io/brian428/pen/jBNbrB?editors=0010

**Comment by etpinard** [comment]
Thanks for writing in! 

I'm surprised those are the only bugs you noticed before giving up on polar completely :smile:

Our polar charts are due  for a complete rewrite. 

You might want to look at

https://github.com/plotly/plotly.js/milestone/2

for a complete (known)  list of polar bugs.

**Comment by brian428** [comment]
Thanks, do you have any general idea on when those might get tackled? Are we talking a month, 3 months, 6 months? Just so I have an idea. Thanks.

**Comment by etpinard** [comment]
Not in the next three months unfortunately.

**Comment by etpinard** [comment]
fixed in `scatterpolar` after #2200
