### ISSUE TITLE
isPlainObject usage blocks objects with prototype

### ISSUE THREAD

**Issue by bpostlethwaite** [plotly/plotly.js#1405]
@etpinard @alexcjohnson re: an internal conversation. 

The Plotly.js usage of `isPlainObject` appears to prevent objects with a prototype. This doesn't seem to be target behaviour of `isPlainObject` as Plotly.js seems to only care if the object behaves like an object (duck typing). Allowing prototype objects will make it easier for people to integrate Plotly.js with Typescript among other potential use cases.

@alexcjohnson made the note that it would be best to change the name of the function.

This issue has been encountered by teams actively integrating Plotly.js with a Typescript application.

**Comment by etpinard** [comment]
maybe switching to [`is-plain-obj`](https://github.com/sindresorhus/is-plain-obj) would solve this issue.

**Comment by alexcjohnson** [comment]
> maybe switching to is-plain-obj would solve this issue.

[doesn't look like it](https://github.com/sindresorhus/is-plain-obj/blob/master/index.js#L6) - `is-plain-obj` explicitly looks for prototype to be missing. I notice though that we are already including it at least via [`color-parse`](https://github.com/colorjs/color-parse/blob/master/index.js#L12) - I wonder if we will need to alter this behavior all the way down our dep tree? that could be painful...

I don't *think* there's anything wrong with omitting the prototype check - hey, it works for [`imagetest`](https://github.com/plotly/plotly.js/blob/756bd69e5908d7da414b4a444ed7a9633bdca0d6/src/lib/is_plain_object.js#L20), right? I imagine people could find a way to construct something that would cause errors, but in general it seems like simple prototyped objects work fine in our framework, and they seem to `JSON.stringify` fine for portability too. If we can write some end-to-end tests with some of the prototyped objects people really want to use I'd be OK with just loosening up the condition.

**Comment by jefshe** [comment]
Non-standard use case, but this also prevents plain javascript objects being passed into an iframe from working as well

**Comment by alexcjohnson** [comment]
Closing as #5151 is a more up-to-date duplicate
