### ISSUE TITLE
Hoverinfo with date axis in 3D broken when using Date objects

### ISSUE THREAD

**Issue by jdugge** [plotly/plotly.js#1407]
If one of the axes in a 3D plot is a date axis and the data for this axis consists of Date objects, the hoverinfo is displayed as `NaN, 0NaN, aNaN:aN`.

![image](https://cloud.githubusercontent.com/assets/2399255/23223690/02e93e36-f92c-11e6-9bab-3519fd839fc3.png)

[Codepen](http://codepen.io/anon/pen/RpbQWQ)

When the date data is provided as date strings, these strings are displayed in the hoverinfo instead, instead of being parsed and formatted as dates.

**Comment by etpinard** [comment]
Thanks for the report.
