### ISSUE TITLE
'plotly_hover' event listener does not work on Pie charts.

### ISSUE THREAD

**Issue by GauthamGoli** [plotly/plotly.js#141]

**Comment by mdtusz** [comment]
Please read our [contributing guide](https://github.com/plotly/plotly.js/blob/master/CONTRIBUTING.md) before opening issues. Bug reports must be accompanied with a reproducible example. We recommend using codepen, jsfiddle or jsbin to share your example.

That said, I am observing the same behaviour. Confirmed as a bug.

**Comment by mdtusz** [comment]
https://github.com/plotly/plotly.js/pull/150
