### ISSUE TITLE
Cant print 'None' string in x axis in Scatter plot if first value

### ISSUE THREAD

**Issue by ssjunior** [plotly/plotly.js#1413]
If the first value in x series is a string 'None' the plot is not rendered.

http://codepen.io/ssjunior/pen/qrBMNG

**Comment by etpinard** [comment]
That's intended behavior I'm afraid. On this [line](https://github.com/plotly/plotly.js/blob/9ebefd73bae4a0ed6016ed051411b5a04552c357/src/plots/cartesian/axis_autotype.js#L69) we explicitly skip string data item `'None'`. That is, `'None'` is essentially equivalent to `null` for plotly.js.

This is probably an artefact that we could :hocho: in v2. I suspect in the early days of plotly, the python API didn't convert `None` values to JSON `null`s (cc @alexcjohnson).

**Comment by ssjunior** [comment]
Understood. Thanks for explaining.

The most strange is if the None is the second value the graph is rendered normally. This only happens if None is the first value. Take a look below.

http://codepen.io/ssjunior/pen/gmbMZY

In my opinion, does not make sense to have None is this condition. If you have a valid non empty string it should be rendered. FYI the Pie Chart render it normally.
 
if(typeof ai === 'string' && ai !== '' && ai !== 'None') curvecats++;

I think this condition is not being evaluated correctly too. What happens if ai !=== "" after the first value? By the same logic it will be rendered.

Best regards. :)

**Comment by ssjunior** [comment]
If the empty string is not the first value the plot is rendered as suspected. The condition as it is now is kind os useless. :)

http://codepen.io/ssjunior/pen/BWyzXj

**Comment by alexcjohnson** [comment]
Removing from v2, as I think we can solve this in a sufficiently backward-compatible way in #3070
