### ISSUE TITLE
scattermapbox lines break with trailing null

### ISSUE THREAD

**Issue by rreusser** [plotly/plotly.js#1418]
The following trace breaks scattermapbox:

```javascript
{
  type: 'scattermapbox',
  mode: 'lines+markers',
  lat: [0, 10, null, 20, 30, null],
  lon: [10, 20, null, 30, 40, null],
  connectgaps: false
}
```

The culprit is the trailing null. The result is a generic mapbox error and no lines for that particular trace. It fails identically given more than one trailing null.

Example: http://codepen.io/rsreusser/pen/VpYjON?editors=1010

<img width="536" alt="nulls" src="https://cloud.githubusercontent.com/assets/572717/23320385/88d452f6-faa8-11e6-823c-0f86456d7a21.png">

**Comment by etpinard** [comment]
Thanks for the report!
