### ISSUE TITLE
Animation when the populating the chart with new data set.

### ISSUE THREAD

**Issue by DilipRajkumar** [plotly/plotly.js#142]
Is it possible to add animation when the data is changed.   Consider I have a bar chart, the height of the bar is 100 if if the data changes to 50 it should change with animation.(ease effect) is it possible.

**Comment by etpinard** [comment]
@DilipRajkumar thanks for the suggestion.

Animations à la `d3.ease` are far from being integrated inside plotly.js.

Animations and declarative schemas don't get along naturally and thus finding the right API (most likely on top of the current `Plotly.restyle` and `Plotly.relayout`) will be tricky.

**Comment by DilipRajkumar** [comment]
Ok, Thank you @etpinard :)

**Comment by jim-bo** [comment]
I'd like to second this request.

**Comment by rolandjitsu** [comment]
@etpinard is there a status update on this? Is there any way to achieve bar/pie chart animation when redrawing?

**Comment by rreusser** [comment]
@rolandjitsu I'm currently finishing off the animation PR. The first version tackles scatter traces only, but with the framework in place, the pieces are there to be able to animate pie/bar charts in a straightforward manner. Most of the work is refactoring current plotly code to reuse DOM elements (i.e. joins/updates instead of recreating elements).

**Comment by rolandjitsu** [comment]
@rreusser that's great, just what I wanted to hear. Looking forward to see how it works and how it could be applied to the rest of the charts.

**Comment by rreusser** [comment]
An update: It's taken quite a while to put together the infrastructure, but I've just merge #802 for an animation API. Currently only scatter traces smoothly transition (the fallback is an instantaneous update), but working D3 element persistence into the picture is not *particularly* difficult now that there's a bigger picture into which it fits. Bar/pie charts are not an immediate priority; the update is just that it's a totally different and feasible task now that the feature request actually fits cleanly into plotly.js.

**Comment by jim-bo** [comment]
awesome thanks for the support. Looking forward to playing with this soon.

**Comment by jackparmer** [comment]
Closing. See:
https://plot.ly/javascript/animations/
For the @rreusser 's plotly.js animations API 🎉

**Comment by ajeet007** [comment]
any example to achieve bar/pie chart animation
