### ISSUE TITLE
Scattermapbox hangs up Plotly API until all tiles have loaded

### ISSUE THREAD

**Issue by rreusser** [plotly/plotly.js#1429]
When scattermapbox is updated (this could just be dragging or zooming), the plot command does not complete until all of the tiles have loaded. Sometimes that's as much as 30s and in the mean time the promise queue delays any further API commands. Perhaps it could return immediately and the mapbox callback could be a separate event that's dispatched (`plotly_mapboxupdated`?) instead of hanging up plotly itself for that amount of time.

Details:

I instrumented [these lines in plots/mapbox/mapbox.js](https://github.com/plotly/plotly.js/blob/master/src/plots/mapbox/mapbox.js#L80-L82):

```javascript
promise = new Promise(function(resolve, reject) {
  self.updateMap(calcData, fullLayout, resolve, reject);
});
```

With some timing:

```javascript
promise = new Promise(function(resolve, reject) {
    var t1 = Date.now();
    self.updateMap(calcData, fullLayout, function () {
        var t2 = Date.now();
        console.log('updated map in', (t2 - t1), 'ms');
        resolve()
    }, reject);
}); 
```

The result after zooming into a town is:

```
updated map in 33211 ms
```

**Comment by etpinard** [comment]
That's the intended (and I think desired) behavior I'm afraid. Similar to all other subplot types the `.plot`, `.restyle` and `.relayout` promises are resolved after the rendering is complete.

Maybe we should execute mapbox promise in parallel to avoid any hang ups?

**Comment by rreusser** [comment]
Ah. One point of clarification. I understand what you mean, but I don't think it was a problem with chained promises. It was *one* mapbox update that took thirty seconds, not a sequence of short mapbox updates.

**Comment by rreusser** [comment]
All good. I can just leave it open for reference if you prefer, but I'm assuming it's probably just necessary to leave as-is.
