### ISSUE TITLE
Legend orientation: h autosize problem

### ISSUE THREAD

**Issue by jaboon** [plotly/plotly.js#1439]
Hi,

Sorry for not supplying example data, I'm working with sensitive data, but I think I can explain the problem pretty clearly since I have a very basic setup.
I have the plot size set to auto and set legend: { orientation: 'h' }.
Everything worked fine in v1.18.1.
Now I upgraded to v1.24.0, it still works fine in the website, but when I download png, the legend is shown vertically, and when I have data with a lot of different legends in one graph it will overlap the chart.
If I set the size manually it all works fine again, but I want the graph to use the full width of the screen.
I hope this helps.

Jeffrey

**Comment by etpinard** [comment]
I can't replicate.

Starting from http://codepen.io/etpinard/pen/VpaRRp @jaboon can you try reproducing the issue?

Thanks for report!

**Comment by jaboon** [comment]
Thank you for the quick response!
I found out that I can only replicate it in the codepen if I'm using our data. I discussed this with my manager and he allows me to send you the data I'm currently using to replicate this problem, can I send this data to you by email or something?

**Comment by etpinard** [comment]
@jaboon I doubt that your `x` and `y` data is causing the issue. This issue is most likely caused by an odd style attribute combination or HTML setup. You shouldn't need to send us you sensitive data.

**Comment by jaboon** [comment]
@etpinard The issue is reproducible by just replacing the data in the codepen with our data, no style or html changes are needed to reproduce the issue. I'm sure our data isn't the problem because it worked correctly in v1.18.1, but it might help you fix the issue.

**Comment by etpinard** [comment]
Strange. If you're ok sending me your data via email, my email address is listed on my github profile https://github.com/etpinard 

Thanks!

**Comment by etpinard** [comment]
Closing due lack of activity.
