### ISSUE TITLE
Styling a single marker

### ISSUE THREAD

**Issue by aderidder** [plotly/plotly.js#144]
Hi,

In a community post I recently enquired whether, in order to change the colour of a single marker in a 10000 marker trace, I'd have to provide the `plotly.restyle` with a complete array with colours, or whether it's possible to update just a single marker. 
Etienne's answer is that at the moment `plotly.restyle` can only be used to restyle a complete trace.

The feature I'm requesting is a more fine-grained control, e.g. the possibility to change the colour of a single marker without having to style the complete trace. 

Thanks,
Sander

**Comment by etpinard** [comment]
@aderidder Thanks for the suggestion. 

I like this idea, but I'm not 100% sure if it belongs in `Plotly.restyle`.

My main concern is coming up with an API on top of the current `Plotly.restyle` API that is intuitive, general and scalable.

The current API supports:

```js
// restyle trace 1 in red
// restyle trace 2 in blue
Plotly.restyle('graph', 'marker.color', ['red', 'blue'], [1, 2]);

// restyle trace 1 pts in red and blue in alternate manner
// restyle trace 2 pts in green and yellow " " "
Plotly.restyle('graph', 'marker.color', [['red', 'blue'], ['green', 'yellow']], [1, 2]);
```

Per-pt restyle could then look like:

```js
// restyle pt 20 of trace 1 in red & pt 21 of trace 1 in blue (and nothing else)
// restyle pt 20 of trace 2 in green & pt 21 of trace 2 in yellow (" " ")
Plotly.restyle('graph', 'marker.color', [['red', 'blue'], ['green', 'yellow']], [1, 2], [20, 21]);
```
The last argument `[20, 21]` will be used to restyle both trace 1 and trace 2. 

**Problem** there would no way to e.g. restyle pts 20 and 21 in trace 1 and 10 and 12 in trace 2 in one `Plotly.restyle` call.

Alternatively, last argument could become a 2d array:

```js
// restyle pt 20 of trace 1 in red & pt 21 of trace 1 in blue (and nothing else)
// restyle pt 10 of trace 2 in green & pt 12 of trace 2 in yellow (" " ")
Plotly.restyle('graph', 'marker.color', [['red', 'blue'], ['green', 'yellow']], [1, 2], [[20, 21], [10, 12]]);
```

but, that might be too confusing / non-intuitive. 

@cldougl @mdtusz thoughts?

**Comment by alexcjohnson** [comment]
#1338 ensures that calls like `Plotly.restyle(gd, {'marker.color[23]': 'red'}, [0]) will work. Closing this, but note that @etpinard 's concern about restyling different marker indices in different traces is still valid: you cannot change the color of point 23 in trace 0 and point 22 in trace 1 in a single `restyle` call. At that point, just use two restyle calls.

**Comment by Discmt** [comment]
@alexcjohnson I'm using `Plotly.restyle(gd, {'marker.color[23]': 'red'}, null, [0])` in my code but it also change the color of all other markers within the trace. Is there a way for me to stop that?

**Comment by alexcjohnson** [comment]
@Discmt can you post a complete code example that shows the issue you've encountered? ie a codepen or something? When I try it, as long as `marker.color` is already an array, it behaves as expected and only changes the color of one point.

**Comment by r1z1a** [comment]
Having issue in restyling bars in multiple traces, on barmode plot. when i click the bar, i need it to change the maker colour just for that bar(pointNumber) but for all the traces. 
Currently its only doing the first bar and rest gets greyed out:

Plotly.restyle(plotDiv, "marker.color", [['#C54C82']], traces, bars); 

traces is array of traces that get recorded from on click, and bars is also array of bars (in this case its same value but the length of array is same as traces)
What I wanted it to do is to update the marker color of the bar for each trace, and this seems like a extremely hard task. either i get 1st bar, or whole graph, or one trace but not the 1 bar that was clicked

**Comment by AniWar** [comment]
Any definite solution found for this issue ? Can someone please post an sample code .
