### ISSUE TITLE
plotly is using __proto__ which slows down the script?!

### ISSUE THREAD

**Issue by marcinwojciechowski** [plotly/plotly.js#1445]
Hello,
I have found that in FF browser i got a warning telling: 
"mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create"

When I search the net what does that means I have found this stackoverflow ticket: http://stackoverflow.com/questions/23807805/why-is-mutating-the-prototype-of-an-object-bad-for-performance

Can you say something about that? Does it really impact the performance?

Best regards,
Marcin

**Comment by rreusser** [comment]
It appears to be a d3 3.x issue which I would hazard to guess is aggressively worded to influence how people handle this. I'd be surprised if it actually has much of an effect except in very pathological cases. There will be [no fix for d3 3.x](https://github.com/d3/d3/issues/1805#issuecomment-183684144), so I don't think there's anything to be done about this.
