### ISSUE TITLE
API Reference page broken

### ISSUE THREAD

**Issue by zbjornson** [plotly/plotly.js#1449]
I'm not sure if this is the right place to report this as I can't tell where the source for this lives.

The reference page seems to have gotten truncated - https://plot.ly/javascript/reference/

![image](https://cloud.githubusercontent.com/assets/469365/23634437/0b229cb2-027f-11e7-852d-97ee13c38bfc.png)

**Comment by etpinard** [comment]
Hmm. Strange. It's working fine for me.

cc @cldougl

**Comment by zbjornson** [comment]
Now it's working fine for me also. Maybe the CDN had bad content for a while.

**Comment by cldougl** [comment]
hmm those weren't updated or modified today. @zbjornson feel free to ping our doc repo: https://github.com/plotly/documentation/issues if you notice an issue again!
