### ISSUE TITLE
onClick for pies slices doesn't return any trace info

### ISSUE THREAD

**Issue by andrey-zakharov** [plotly/plotly.js#1456]
Code sample:
http://codepen.io/anon/pen/ZeLdXK?editors=0011

If i click any pie other that the biggest one ( first ) no there is no any trace info in event data. neither in points[0], nor in event.trace. Actually, there is "event.points.trace = undefined".
console.log(e) gives only:
![image](https://cloud.githubusercontent.com/assets/1961993/23759861/06a7f1a0-04ff-11e7-9921-9833a98ed0f7.png)

**Comment by etpinard** [comment]
Right. Sounds like an easy PR to make.

@andrey-zakharov want to give it a shot? Adding a ref to trace in `evt` [here](https://github.com/plotly/plotly.js/blob/20a47fd6e904e52e92dc1c60b0d9d23db7a5070b/src/traces/pie/plot.js#L129) should be good enough.

**Comment by blokhin** [comment]
Unfortunately, still an issue with the **latest** (v1.30.0)

**Comment by etpinard** [comment]
> Unfortunately, still an issue with the latest (v1.30.0)

Works for me: https://codepen.io/etpinard/pen/prxrbg?editors=0010

**Comment by blokhin** [comment]
Chrome 60.0.3112, FF 54.0.1: click at green or orange area in your pen yields _undefined_ in console (blue area is OK).

**Comment by etpinard** [comment]
thanks @blokhin , reopened.

**Comment by blokhin** [comment]
Any chance the bugfix will be included in the next release?

**Comment by alexcjohnson** [comment]
Pie event data is currently very different from most other plotly event data. I'm going to clean this up as part of #2073.

**Comment by alexcjohnson** [comment]
Note that pie event data changed a fair amount with #2117 - should all be for the better but if anyone was using all the various internal-use coordinates that were being reported previously you will have to find another way to retrieve them 🙈

**Comment by blokhin** [comment]
> Works for me: https://codepen.io/etpinard/pen/prxrbg?editors=0010

Still doesn't work, click at any area in your pen yields `undefined` in console :( Chrome 64, FF 58, **plotly-latest** (1.35.2)
