### ISSUE TITLE
Text positioning - 'lines+text' vs 'lines+markers+text'

### ISSUE THREAD

**Issue by aderidder** [plotly/plotly.js#146]
Hi,

When the mode is set to lines + markers + text, there is some space between the graphics and the text:
![image](https://cloud.githubusercontent.com/assets/9414840/11992162/b55981b6-aa22-11e5-922f-d9644b302606.png)

However, when set to lines + text, this space is gone:
![image](https://cloud.githubusercontent.com/assets/9414840/11992173/e537b5ba-aa22-11e5-93da-2437e079b9ea.png)

It would be nice if this space is also there in the second case, or if the space / layout of the text would be customisable.

Thanks,
Sander

**Comment by etpinard** [comment]
@aderidder Thanks for the suggestion.

Fine tuning `textposition` would be nice.

Maybe, `textposition` could support arrays of x-y offsets e.g. `textposition: [-5, 10]` would result in text 5 px to the left and 10 px above the marker pts.

Alternatively, we could add a `textoffset` attribute accepting x/y arrays or `{x: , y: }` objects.

In the meantime, you could set `mode: 'lines+markers'` with `marker.color: 'rgba(0,0,0,0)'` drawing invisible marker pts faking a text offset.

**Comment by aderidder** [comment]
Hi,

I think I'd prefer to be able to provide the offset instead of the actual
coordinates, but maybe that's a personal preference.
Thanks for the workaround; works fine.

Sander

2015-12-29 22:17 GMT+01:00 Étienne Tétreault-Pinard <
notifications@github.com>:

> @aderidder <https://github.com/aderidder> Thanks for the suggestion.
>
> Fine tuning textposition would be nice.
>
> Maybe, textposition could support arrays of x-y offsets e.g. textposition:
> [-5, 10] would result in text 5 px to the left and 10 px above the marker
> pts.
>
> Alternatively, we could add a textoffset attribute accepting x/y arrays
> or {x: , y: } objects.
>
> In the meantime, you could set mode: 'lines+markers' with marker.color:
> 'rgba(0,0,0,0)' drawing invisible marker pts faking a text offset.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plotly/plotly.js/issues/146#issuecomment-167878838>.
>



-- 
E.   sander@thehyve.nl
T.   +31(0)30 700 9713
W.  www.thehyve.nl

the hyve

**Comment by CaseGuide** [comment]
Anyone know if it is possible to set a textposition offset here in 2021?
