### ISSUE TITLE
numbers as categories should equal their string representations

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#1460]
I would expect this to generate 3 categories (a, b, 1) but it generates 4 - two identical 1's:
```
Plotly.newPlot(gd,[{x:['a','b',1,'1'],y:[1,2,3,4]}],{xaxis:{type:'category'}})
```
<img width="303" alt="screen shot 2017-03-09 at 7 03 14 pm" src="https://cloud.githubusercontent.com/assets/2678795/23776241/138e6a74-04fb-11e7-871e-36a48b4bcc9c.png">

**Comment by rreusser** [comment]
Also a good find! Note: `['a','b',1,'1']` and `['a','b','1',1]` both fail in the same way.

**Comment by alexcjohnson** [comment]
@monfera @etpinard I missed this issue when category arrays went in, particularly [this comment](https://github.com/plotly/plotly.js/blob/master/src/plots/cartesian/ordered_categories.js#L18) - I actually think we *want* string coercion, although this may open a can of worms re: lexicographic vs natural sorting. Thoughts?

**Comment by etpinard** [comment]
Yep agreed. `1` and `'1'` should be considered the same category - similar to how `valType: 'number'` attribute can be input as number of numeric strings.

**Comment by etpinard** [comment]
... but maybe @monfera has something to say about this.

**Comment by monfera** [comment]
_Generally_ I'm not an advocate of automatic type coercions so if asked yesterday, I'd have said, expecting 4 things would seem natural. Coercing to strings will make it sort them as strings by default, e.g. "2" > "10". But based on the above discussion it looks like coercion would be the more natural fit for the library and I have no overriding argument of any kind.

**Comment by etpinard** [comment]
Found this. Will be fixed as part of https://github.com/plotly/plotly.js/pull/2489
