### ISSUE TITLE
[Enhancement] Legend and traces three-way toggling

### ISSUE THREAD

**Issue by chrisvwn** [plotly/plotly.js#1462]
May be related to #674, but on advice from @rpaskowitz setting up as a separate request. I would like to suggest a 3-way toggling so that an entry can be on, off or highlighted. Sometimes, when trying to visually analyze a subset of plots in a crowded graph it might help to either dim the rest or just make a selected few stand out? So you still want the context of the other plots for comparison just not at the same visibility level as the selected subset.

Thanks to @rpaskowitz for suggesting the following: 

> I'd recommend doing something like that with a hover interaction, for example: http://c3js.org/samples/timeseries.html

My rejoinder: 

> Almost exactly what I was thinking only with a little more persistence so that one can have multiple highlighted.

**Comment by jensb** [comment]
I would second that request. That would be quite useful.

**Comment by etpinard** [comment]
Similar to https://github.com/plotly/plotly.js/issues/674. This should be doable using `plotly_legendclick` and `plotly_legenddoubleclick` added in https://github.com/plotly/plotly.js/pull/2581

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
