### ISSUE TITLE
Events not received in polar charts

### ISSUE THREAD

**Issue by suh786** [plotly/plotly.js#1463]
I tried attaching hover and click event handlers in polar charts, but the events are not received. Am I doing something wrong or they are not yet supported? Please find a pen below:

http://codepen.io/anon/pen/yMMqqg?editors=1011

**Comment by waegen** [comment]
I have managed to add events to Polar Plots. Please check out the RP https://github.com/waegen/plotly.js/pull/1

**Comment by etpinard** [comment]
fixed in `scatterpolar` after #2200
