### ISSUE TITLE
Incorrect placement of hoverinfo with shared axes

### ISSUE THREAD

**Issue by rpaskowitz** [plotly/plotly.js#1468]
From discussion on #1461, the placement of the hoverinfo on the axis is incorrect on charts with a shared axis, for example `mocks/stacked_coupled_subplots.json`:
![image](https://cloud.githubusercontent.com/assets/1222909/23842015/d3857686-076e-11e7-85a3-54c0e6c78704.png)

It seems to be being drawn based on the bottom of the sub-charts y-axis position as opposed to being based on the position of the x-axis itself.

**Comment by etpinard** [comment]
I'm not sure _incorrect_ is the right word here. I think the current behavior could be enhanced, but by no means wrong. Take this very tall [graph](https://cloud.githubusercontent.com/assets/2789078/23756009/51501970-04b0-11e7-84cc-37de9085c75d.png) for example where all subplots are linked to the same x-axis, in this case having the  x hover label be displayed on the true x-axis (at the bottom of the graph) would essentially make it invisible for most of the graph.

So adding an attribute e.g. `layout.xaxis.showhoverlabeloncommonaxis` (or something less verbose :smile: ) would be the way to go here.

**Comment by alexcjohnson** [comment]
I don't think anyone is going to go through the thought process "this graph is super tall so I'd better change how the common axis hover labels get placed"... and anyway who's to say what's "too tall", that's different for each viewer, and depending on the context the plot may be scrolled halfway off screen anyway. So I wouldn't be in favor of making this configurable.

How about we try to detect where the bottom of the screen is, and move the label down to the bottom-most shared axis but then push it back up onto the screen if necessary? Not actually sure how to do that but given all the sites that make something happen to an element when it scrolls on screen I imagine it's possible...
