### ISSUE TITLE
can not draw specific triangle in 3d surface chart

### ISSUE THREAD

**Issue by lwlwlwlw** [plotly/plotly.js#1474]
can not draw following data( triange) in 3d surface chart,

x,y,z
-1,-1,0
1,-1,0
0,1,1

Code that I have tried:

    var x=[-1,0,1];
    var y=[-1,1];
    var z=[];
z1 = [
    [0,null,0],
    [null,1,null],
];

var data_z1 = {x:[-1,0,1],y:[-1,1],z: z1, type: 'surface'};
Plotly.newPlot('myDiv', [data_z1]);

Please help. Thanks.

**Comment by etpinard** [comment]
It's probably easier to draw a triangle using a `mesh3d` trace like in http://codepen.io/etpinard/pen/XMaqJN

I'd recommend searching through our forums @ https://community.plot.ly/ for implementation questions of the likes. Thank you.

**Comment by lwlwlwlw** [comment]
Purpose of this is not drawing a triangle using 3d surface chart, but to confirm if 3d surface chart module can not draw specific data like this. If yes, what kind of data that 3d surface chart module can not draw? If 3d surface chart is supposed to draw any data, so since this is a proof that it doesn't that is why I am posting here. Please kindly leave a comment. Thank you.
