### ISSUE TITLE
Drawing traces on top of shapes

### ISSUE THREAD

**Issue by zerweck** [plotly/plotly.js#148]
I would like to use shapes in the background to highlight areas, without resorting to opacity.
The developer of the R API states that this is not supported in plotly.js:
https://github.com/ropensci/plotly/issues/370

**Comment by etpinard** [comment]
@zerweck This would be useful addition.

Unless @alexcjohnson has a reason for always keeping shapes above traces.

Possible API:

- `layout.shape.layer: 'above' || 'below'`

**Comment by Kopite4Ever** [comment]
Another one here who is hopeful this can be implemented soon.  It will enable me to do some good stuff with the charting library.

Regards
