### ISSUE TITLE
Marker styles are not updated with Plotly.restyle in zoomed state until double-click to zoom out

### ISSUE THREAD

**Issue by kimsk** [plotly/plotly.js#1480]
When calling `Plotly.restyle` in zoomed state, the markers style are not updated in UI until I double-click to zoom out.

Codepen: https://codepen.io/karlkim/pen/OpxMxG?editors=1010#0

> Click one of the buttons to trigger `Plotly.restyle` which update style of markers

### Steps to reproduce:

0. Initially, the red marker has `opacity` = 1 and others have `opacity` = 0.3
1. Click `1`, and the blue marker should have `opacity` = 1, and the red marker should have `opacity` = 0.3
2. Zoom into the area around red marker and click `0`.

### Expected Result:

The red marker should have `opacity` = 1 and the blue marker should have `opacity` = 0.3

### Actual Result:

The blue marker still has `opacity` = 1. The marker styles are not updated until I double-click to zoom out.

**Comment by etpinard** [comment]
Thanks for writing in. As a lot of people do, you not providing the right input to `restyle`. Restyle set key-value updates - not a object meant to extend a trace. To update nested keys, use e.g. `marker.opacity: 0.4`.

See https://codepen.io/etpinard/pen/WpZJgb for a working example. And please refer to our https://community.plot.ly/ for more restyle examples.

**Comment by kimsk** [comment]
Thanks for the comment about the input. 

However, the working example does not have marker style updated when zooming in either?

**Comment by etpinard** [comment]
> the working example does not have marker style updated when zooming in either?

I don't understand. Why should the marker style update on zoom. Restyle is only called on button click if I'm not mistaken.

**Comment by kimsk** [comment]
Sorry for the confusion. I mean if I click the buttons to trigger restyle without zooming in, the marker styles are updated immediately. However, if I zoom in and click the buttons, the marker style are not updated until I double-click the graph to zoom out.

**Comment by etpinard** [comment]
No worries @kimsk !

Thanks very for the report. Something is up during restyle in versions `1.21.3` and up. I think https://github.com/plotly/plotly.js/pull/1257 is the culprit. I'll investigate.

**Comment by etpinard** [comment]
Thanks again for the report @kimsk 

This will be fixed in the next release `1.25.0`.
