### ISSUE TITLE
Pie chart textinfo specific color customization

### ISSUE THREAD

**Issue by tarikgan** [plotly/plotly.js#1483]
Hi,

I'm curious if there is any way to implement custom color in every Textinfo in Pie Chart.

I've tried outsidetextfont with custom multi color, but it seems not work.

I'll be good if we can implement this in future(if it doesn't exist yet).

Thanks.

**Comment by etpinard** [comment]
You can try something like http://codepen.io/etpinard/pen/GWORVy

**Comment by tarikgan** [comment]
Thanks, it works for me.

Sorry for not noticing that before.
