### ISSUE TITLE
(reopening) failed to render 3d surface chart on specific data.

### ISSUE THREAD

**Issue by lwlwlwlw** [plotly/plotly.js#1484]
reopening https://github.com/plotly/plotly.js/issues/1474 because I have some more questions that need your help.

I am creating a 3d surface chart based on some input data, this data could change from time to time and if by accident, data like below(a triangle) came, then the 3d surface chart can not render correctly.
x,y,z
-1,-1,0
1,-1,0
0,1,1

Code that I have tried:

var x=[-1,0,1];
var y=[-1,1];
var z=[];
z1 = [
[0,null,0],
[null,1,null],
];

var data_z1 = {x:[-1,0,1],y:[-1,1],z: z1, type: 'surface'};
Plotly.newPlot('myDiv', [data_z1]);

In the original ticket, etpinard suggested using mesh3d rather than 3d surface chart.  However 3d surface chart best fits the requirement so I have to stick to it and make it renders any data as much as possible.

Since the fact that code I wrote above failed to render the graph so any help would be highly appreciated.

Please don't rush closing this and just give the author one chance to explain himself in case of some misunderstanding. Thanks.

**Comment by etpinard** [comment]
Hi, I closed #1474 because as per our [Contributing](https://github.com/plotly/plotly.js/blob/master/.github/ISSUE_TEMPLATE.md) guidelines, GitHub issues are reserved for bug reports and feature request **only**. 

In that same ticket I pointed you our https://community.plot.ly/ which to the best place to ask questions because 1) more users can offer solutions 2) more users can benefit from it.

I hope you understand.

**Comment by lwlwlwlw** [comment]
Thank you very much etpinard, I totally understand and completely agree with you. I am sorry for any inconvenience.

Since the data I given above is a simple triangle and I guess it should can be rendered in 3d surface chart however it couldn't, it looks like a bug to me. Of source I might be wrong in my code, although the exact same logic works fine for data with more points. 

Could you please kindly take a look at it? Thank you.

**Comment by archmoj** [comment]
This is addressed in PR #3638.
@lwlwlwlw Here is a [codepen](https://codepen.io/MojtabaSamimi/pen/zbegPK) with `connectgaps` enabled.
Closing.
