### ISSUE TITLE
Add `geo.center` attribute to specify map view without rescaling

### ISSUE THREAD

**Issue by brian428** [plotly/plotly.js#1486]
When using an autosized plot, focusing on a map area by using ranges on scattergeo lat long causes the plot width and height to change. I don't think this should happen. The plot should always use all available space. 

I created a codepen to demonstrate the issue: http://codepen.io/brian428/pen/EWbKgQ

Just change the `setRange` flag to `true` to see the effect it has on the plot size.

**Comment by etpinard** [comment]
That's the intended behavior I'm afraid. Can I _why_ this shouldn't happen?

**Comment by brian428** [comment]
I assumed that the geo range would set the extent of what you SEE in the map, but I don't understand why it would change the width and height. If you don't set a range and you zoom into the plot, it doesn't alter the size. So if this is the desired behavior when setting the range, is there some way to specify the visible extent being shown on the map without changing the size of the map itself?

**Comment by etpinard** [comment]
@brian428 that's more like it! Pro tip: opening an issue saying something _should_ work a certain way without explanation is one way to make a OSS maintainer pissed off.  On that topic, you might want to read [this](https://nolanlawson.com/2017/03/05/what-it-feels-like-to-be-an-open-source-maintainer/).

------

As you point out, geo subplots are missing a few attributes to fully described the state. At first, I was convinced that `lonaxis.range` and `lataxis.range` were and should be enough, but no. 

To better explain the problem here's a little background information: in general one can't satisfy (or _fill_) both given a width and height without distorting the map. That's because a map's width and height aren't independent: they are constrained by the map projection. So, plotly fills one dimension to its maximum (in your case your map has full height) and the width is then determined by the map projection.  When setting the lon/lat ranges you essentially set the bounds for which width/height constrain is applied. If you're interested, the logic is [here](https://github.com/plotly/plotly.js/blob/master/src/plots/geo/set_scale.js).

But now, how does one show a subset of a map without rescaling it? At the moment, you can't. So I'm thinking about adding a `geo.center` attribute similar to how `mapbox` subplot are specified. Together with `geo.scale` one could then get your desired result.

It's about time I give this a shot as this will also resolved https://github.com/plotly/plotly.js/issues/292 fairly easily.

**Comment by brian428** [comment]
Thanks, Étienne. I actually do know what it feels like to be an OSS maintainer (having maintained or helped maintain a number of OSS projects). My intent wasn't to piss you off. I thought this was a genuine bug, and thought that my Codepen sufficiently showed the apparent oddness of what was going on. :-)

I was able to get a bit closer to what I was looking for by scouring the API and finding `geo.scale` and `geo.rotation`. These aren't documented (as far as I can tell), but I created a TypeScript definition (TSD) generator for Plotly and found these via the TSD. (I believe your colleague Ben Postlethwaite already forwarded it to you. I'm with the folks who were funding the scattergl fixes. Having full code completion and inline API docs for Plotly has been a big help for me!)

Setting the `rotation.lat`/`rotation.lon` seems to center the map, and `scale` will zoom it in, but the problem there is that a specific extent of min/max lat/lon is difficult to accurately translate to a `scale` value.

I get that the width and height of the map is _eventually_ limited by the map projection, but that only happens when you hit the maximum `scale` (1). It seems like anything beyond `scale:1` would should have "enough map" available to fill any width/height, right? 

I like your idea of `geo.center`, though I'm not totally sure it's needed, assuming that `geo.rotation` is basically doing the same thing? That said, it would be great if the map width/height always used the full size of it's parent container (as long as it doesn't butt up against the max width/height of the chosen projection). 

Let me know what you think. Thanks.

**Comment by brian428** [comment]
A late reply here, but just wanted to note that using geo.rotation doesn't work. It does center the map, but it does something wonky which skews the map itself in bizarre ways (probably depending on which projection is used). So I think a dedicated ability to center is needed.

This also should **really** include the ability to set an initial zoom scale or set an initial lat/lon extent to make it possible to scale (zoom) and center the map on a relevant location. I've tried setting a lat/lon extent using lataxis/lonaxis range, but that causes the map's width and height to shrink.

**Comment by brian428** [comment]
In the meantime, is there really NO way to do this, even via a hack? Some non-public function or layout value that can be set when creating the layout?

**Comment by etpinard** [comment]
> A late reply here, but just wanted to note that using geo.rotation doesn't work.

Would you mind sharing a reproducible example?

**Comment by brian428** [comment]
Here's an example that shows both problems. At the top of the JS, turn on the scale/rotate to see the map become skewed (zoom out on the map to see it). Then turn that off and turn on the use of a lat/lon range to see the size of the map shrink instead of just scaling the map to show the relevant ranges.

https://codepen.io/brian428/pen/vJZJaE?editors=0010#0

**Comment by brian428** [comment]
Étienne, did that show you what you needed? Were you able to see the scale/rotate skewing and the range causing the map to shrink?

**Comment by etpinard** [comment]
Yes I was able to see it. 

That is the intended -- albeit potentially not ideal -- behavior. You seem very vocal about how _bad_ the intended behavior is, so I didn't bother commenting.

**Comment by brian428** [comment]
To be fair, I never said it was **bad**. I just said that using scale and rotate isn't an option for specifying an initial center point for the map. 

I would probably say the way specifying a lat/lon range behaves borders on bad, though. It seems odd for Plotly to resize the entire map instead of maintaining the size and simply filling it with the specified range. Would you agree?

**Comment by etpinard** [comment]
@brian428 significant improvements are coming to geo subplot in https://github.com/plotly/plotly.js/pull/2030

**Comment by brian428** [comment]
@etpinard awesome, thanks Étienne! Do you happen to know if the geo.center will also let you set the scaling and/or range that is shown? (In particular, letting you set the range without the width-shrinking behavior I showed in my earlier Codepen?)

I'd also be curious whether this change will make the current geo scale/range accessible in the Plotly element's layout object? I had been talking with Rob, Ben and Alex about the need to capture plot range from the element so I can restore it after rebuilding a chart. We're basically trying to keep as much of the charts intact as we can, even if we have to re-create them.

For scatter, I'm able to pull the current (after zoom) range from `el.layout.{x/y}axis.range`. But we realized that the geo plot doesn't seem to update the `el.layout` with the current scale/range. 

Any idea if #2030 would make this available? If not, let me know and I can create a separate ticket for it. 

Thanks again.

**Comment by etpinard** [comment]
@brian428 see https://github.com/plotly/plotly.js/pull/2030/commits/4d9b566dbf266f01286dcfbce1149be4bfb76b10 for an example of how to position a map using `geo.center` - which is based on the codepen you posted above.

**Comment by brian428** [comment]
Étienne, is this enabled in the current release (1.30.1)? I tried this out using the example config in https://github.com/plotly/plotly.js/commit/4d9b566dbf266f01286dcfbce1149be4bfb76b10, but am not seeing the same behavior. https://codepen.io/brian428/pen/veppWq?editors=0010

Just trying to determine if this should be working in 1.30.1, or if it's coming in the next release?

**Comment by etpinard** [comment]
See https://github.com/plotly/plotly.js/releases for the most up-to-date release info. Thanks

**Comment by brian428** [comment]
Well the thing that confuses me is that your commit (https://github.com/plotly/plotly.js/commit/4d9b566dbf266f01286dcfbce1149be4bfb76b10) doesn't look like it has any Plotly changes, only the addition of the mock file. And the release notes don't mention anything about this issue. So it's not clear if this functionality is something that already existed and just needed an example provided, or if it involved changes to Plotly that aren't released yet.
