### ISSUE TITLE
Scatterplot 'Ordinal' data redraw to 'Nominal' data - bug

### ISSUE THREAD

**Issue by destradafilm** [plotly/plotly.js#1487]
If my scatterplot start with an array of of Nominal data ('strings') and I change the data to Ordinal data ('numbers') and then 'redraw' it works just fine

![nominal to ordinal](https://cloud.githubusercontent.com/assets/6043499/24014153/7c5b6112-0a49-11e7-80f0-bb54cba34641.gif)

But there's a bug

![ordinal to nominal](https://cloud.githubusercontent.com/assets/6043499/24014175/8d0bfaf8-0a49-11e7-9c61-16303b591fb4.gif)

If I draw my chart with 'Ordinal' first and change it to 'Nominal' and then redraw it doesn't display the Nominal data or any points...the y axis in my example stays as numbers and the points disappear

CODEPEN:
http://codepen.io/destrada/pen/LWORGW

**Comment by etpinard** [comment]
Very similar to https://github.com/plotly/plotly.js/issues/1231

@destradafilm you'll need to clear the `xaxis.type` before calling `redraw`.

By the way, `Plotly.redraw` is set to :hocho: in [`v2`](https://github.com/plotly/plotly.js/issues/420), so we probably start logging a deprecation warning.

**Comment by etpinard** [comment]
@destradafilm there's an opened PR https://github.com/plotly/plotly.js/pull/1285 which attempts to clear axis types on `newPlot`. I'm not particularly happy with it at the moment. That said, the issue you're pointing out is very much known, so I'll close this ticket.

**Comment by destradafilm** [comment]
Yup, that works! It's fixed on the same codepen if anyone else needs a working example:
http://codepen.io/destrada/pen/LWORGW
