### ISSUE TITLE
gl2d cursor doesn't correspond with chosen modebar tool

### ISSUE THREAD

**Issue by destradafilm** [plotly/plotly.js#1489]
On the 'scatter' plot the cursor changes to reflect the corresponding modebar tool chosen. 
It's only on the default cursor no matter which modebar chosen on 'scattergl' plot

**Comment by etpinard** [comment]
![gifrecord_2017-03-16_200656](https://cloud.githubusercontent.com/assets/6675409/24023668/2eed6eee-0a84-11e7-9f3c-d6fc6d58076f.gif)

Wow. I can't nobody noticed this yet. Thanks for posting.

**Comment by etpinard** [comment]
maybe @dfcreative might want to look at this.

**Comment by etpinard** [comment]
will be fixed in https://github.com/plotly/plotly.js/pull/1869

**Comment by dfcreative** [comment]
@etpinard how we can add a test for that?

**Comment by etpinard** [comment]
> how we can add a test for that?

No need to add a test for this, our cursor-changing logic is already well [unit-tested](https://github.com/plotly/plotly.js/blob/master/test/jasmine/tests/lib_test.js#L1182).

**Comment by etpinard** [comment]
closed by https://github.com/plotly/plotly.js/pull/2258
