### ISSUE TITLE
question: Is it possible to disable interaction with a plot?

### ISSUE THREAD

**Issue by lyschoening** [plotly/plotly.js#15]
I understand that the interactivity of Plotly is one of the things that make it so powerful, but there are a few situations when a static plot might be preferable. Are there ways to toggle (a) visibility of the modebar and (b) panning/zooming?

**Comment by etpinard** [comment]
This can be done using one of  `Plotly.plot`'s (currently poorly documented) config arguments. 

The full list is found here: https://github.com/plotly/plotly.js/blob/master/src/plot_api/plot_config.jshttps://github.com/plotly/plotly.js/blob/master/src/plot_api/plot_config.js

```js
Plotly.plot(graphDiv, data, layout, {staticPlot: true})
```

should do the trick.

Moreover, note that in svg 2d plots, individual axis can be made fixed using the `fixedrange` attribute: https://github.com/plotly/plotly.js/blob/master/src/plots/cartesian/layout_attributes.js#L84 .

**Comment by lyschoening** [comment]
Thank you for pointing me to the code for this. I can see there's also a `displayModeBar` option, so that answers all my questions.

**Comment by chriddyp** [comment]
FYI, here are some examples of most of the configuration options: https://plot.ly/javascript/configuration-options/

**Comment by fizcris** [comment]
Is this option available in python offline version?

**Comment by hadhoryth** [comment]
Yes, for python is also possible, just pass "config" dict to the plot.
```
Pyplot.plot(...., config={'displayModeBar':False, ....})
```

**Comment by PabloBotas** [comment]
Can this be done for a specific trace?

There might be a better approach for what I want:
1. as *trace0* lot of scatter points as background without interactivity or legend
2. as *trace1*, some selected subset with full interactivity

**Comment by etpinard** [comment]
@PabloBotas you can adding your own custom legend click handlers. See https://github.com/plotly/plotly.js/pull/2581

**Comment by rageycomma** [comment]
If you pass `staticPlot: true`, you can't disable it. So if you're creating a plot and want to disable it until data is received, even if you pass `staticPlot: false` afterwards, data doesn't update. So, this doesn't really resolve the issue of disabling user interaction for plots that are updated frequently.

**Comment by jaspersardonicus** [comment]
In case anyone comes looking for this feature like I did for Choropleth plots:

- The option to disable panning: `dragMode=False` in the layout property
- The option to disable scrolling: `scrollZoom=False` in the config property
- The option to disable map controls: `displayModeBar=False` in the config property

**Comment by xanderwallace85** [comment]
> In case anyone comes looking for this feature like I did for Choropleth plots:
> 
> * The option to disable panning: `dragMode=False` in the layout property
> * The option to disable scrolling: `scrollZoom=False` in the config property
> * The option to disable map controls: `displayModeBar=False` in the config property

Hi @jaspersardonicus ! Which module did you use for the Choropleth map? in the ff dragMode the throws an error when placed in the layout :(

**Comment by jaspersardonicus** [comment]
@xanderwallace85 I used `from plotly import graph_objects as go` and constructed the map with `fig = go.Choropleth()`

**Comment by xanderwallace85** [comment]
> @xanderwallace85 I used `from plotly import graph_objects as go` and constructed the map with `fig = go.Choropleth()`

@jaspersardonicus Thanks! Have you also tried to disable pan/drag with plotly.express?

**Comment by jaspersardonicus** [comment]
Not yet. I haven't even used plotly.express yet, sorry!

**Comment by marysteffin** [comment]
`fig.show(config=dict({'staticPlot':True}))`

Looks like that works for offline plots.
