### ISSUE TITLE
Automatic sorting of dates?

### ISSUE THREAD

**Issue by aft-luke** [plotly/plotly.js#151]
Hi there,

I'm trying to draw a very simple scatter chart, and it looks like plotly is sorting by x axis automatically? Is there any way to turn this off? Is this just because the x values are dates? 

```javascript
        let layout = {
            xaxis: {
                title: 'foo'
            }
            , yaxis: {
                title: 'bar'
            }
            , title: 'a graph'
        }

        let data = [{
            x: [Array of Dates]
            , y: [Array of Floats]
            , type: 'scatter'
        }]

        plotly.newPlot(div, data, layout, {
            displaylogo: false
            , showTips: false
        })
```

This is pretty inconvenient because I'm trying to implement a "sort by value" feature instead of only sorting by dates.

Default, sorted by dates:

![screen shot 2015-12-29 at 8 34 41 pm](https://cloud.githubusercontent.com/assets/13787895/12045155/dcf75b24-ae6b-11e5-89ee-ebce8786c860.png)

After sorting the x/y arrays by the y values, and recreating the plotly:
![screen shot 2015-12-29 at 8 34 54 pm](https://cloud.githubusercontent.com/assets/13787895/12045156/e3c15e82-ae6b-11e5-8127-b115de43f21e.png)

This is obviously not the correct chart, and it looks like plotly is just forcing a strict sort order on the x-axis dates. How can I prevent this?

**Comment by etpinard** [comment]
@aft-luke arrays of dates will always be shown in order by default.

To override this behavior, set the axis type to `category`. More info [here](https://github.com/plotly/plotly.js/blob/master/src/plots/cartesian/layout_attributes.js#L27-L41).

**Comment by aft-luke** [comment]
I see. Much appreciated. I could not find any clearly laid out details of this in the documentation. Maybe I just can't navigate the docs very well.

**Comment by etpinard** [comment]
@aft-luke no worries. This behavior isn't well documented in our docs at the moment. Thanks for bringing this up.
