### ISSUE TITLE
BUG: GL2D scatterplot marker size and redrawing/restyling breaks plot

### ISSUE THREAD

**Issue by destradafilm** [plotly/plotly.js#1510]
In this example, I'm using the LATEST version of plotly `https://cdn.plot.ly/plotly-latest.min.js` I change the size of the marker to an array. Some Markers should get bigger and some should get smaller. The result is that they move in x and y coordinates and get slightly smaller. Unless, I change the symbol of the marker. The 'redraw' or 'restyle' function cleans it up

EXAMPLE:
![latest version of plotly bug](https://cloud.githubusercontent.com/assets/6043499/24223135/693a32cc-0f1a-11e7-8cca-125e0740d7b3.gif)

CODEPEN:
http://codepen.io/destrada/pen/xqYJYQ

-----
When I switch to version 1.5.0 `https://cdn.plot.ly/plotly-1.5.0.min.js` of Plotly, it responds correctly to resizing the Markers and redrawing

EXAMPLE:
![version 1 5 doesn t break marker size](https://cloud.githubusercontent.com/assets/6043499/24223101/4a0299d0-0f1a-11e7-9eff-9fc2e1812f8a.gif)

CODEPEN:
http://codepen.io/destrada/pen/mWLRzZ

**Comment by etpinard** [comment]
Ok. Interesting. Have you tried using `restyle` instead of the soon to be deprecated `redraw`?

**Comment by destradafilm** [comment]
I updated the codepens by switching it to `restyle` instead of `redraw` and it has the same results

**Comment by etpinard** [comment]
Thanks for the report!

This probably a side-effect of @dfcreative 's https://github.com/plotly/plotly.js/pull/1398

**Comment by dfcreative** [comment]
Oh, yes, that might be. Gotta check in details.

**Comment by dfcreative** [comment]
[gl-scatter2d-sdf@1.3.4](https://www.npmjs.com/package/gl-scatter2d-sdf) fixes that.
