### ISSUE TITLE
layout shapes are not properly rendered in a time series graph

### ISSUE THREAD

**Issue by rolandjitsu** [plotly/plotly.js#1515]
I'm trying to highlight night time (between `20:00` on `n` date  to `07:00` on `n + 1` date) using [shapes](https://plot.ly/javascript/shapes/), but there seems to be some issues when the time is from `20:00` on date `n` to `00:00` on date `n`.

To illustrate the issue, look at [bqKQez](http://codepen.io/rolandjitsu/pen/bqKQez), on the right side of the graph there are two shapes that are overlapping and one of them highlights the wrong period (instead of going from `20:00` to `00:00` on the same date it goes from `00:00` to `20:00` on the same date):

![night](https://cloud.githubusercontent.com/assets/1479737/24305668/7a5b570e-10c6-11e7-989f-6d8e10fac4cf.png)

**Comment by etpinard** [comment]
So, if I'm understanding correctly, `"2017-03-24T00:00:00.000Z"` should be considered in March 24th? Is that the convention? Or shouldn't this be `"2017-03-25T00:00:00.000Z"`?

**Comment by rolandjitsu** [comment]
@etpinard that's a good question. I guess I expect it to be end of March 24th, thus March 25th, but now that you ask, it's obviously March 24th which leads to the behaviour I'm seeing. That's the case here, right?

Rationally, `"2017-03-24T00:00:00.000Z"` is the beginning of March 24th, so if I wanted end of 24th, I'd either use `"2017-03-24T23:59:59.999Z"` or `"2017-03-25T00:00:00.000Z"`.

**Comment by etpinard** [comment]
I think (where I come from at least) `00:00` means the start of a new day i.e. `2017-03-24T00:00:00.000Z` is the start of March 24th during the night of the 23th to the 24th. So, I believe the current behavior is correct. It would be nice to confirm though. @rolandjitsu have you ever tried plotting similar things in other graphing libraries?

**Comment by rolandjitsu** [comment]
@etpinard that's true. I haven't tried other libraries, but I'm sure you're right. I just failed to see that when I initially thought about it.
