### ISSUE TITLE
contour trace on top of heatmap redraws below heatmap trace

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#152]
Example: http://codepen.io/etpinard/pen/EPNdMg

The first `plot` call renders the graph as desired, but any zoom/pan interactions (most likely all `relayout` calls) redraws the contour trace below the heatmap trace.

**Comment by etpinard** [comment]
@alexcjohnson any reasons for not using the `d3` select/data/enter/exit pattern in the heatmap plot [step](https://github.com/plotly/plotly.js/blob/master/src/traces/heatmap/plot.js#L370-L382) ?

**Comment by alexcjohnson** [comment]
no, I don't think so. Weird, dunno why I would have written it that way.

**Comment by etpinard** [comment]
@alexcjohnson any reasons for drawing heatmap and contour trace in the same `<svg>` [layer](https://github.com/plotly/plotly.js/blob/master/src/plot_api/plot_api.js#L2654)?

Seems to me that contour traces need be above heatmaps always to allow for consistent trace toggling. See example: http://codepen.io/etpinard/pen/rxGwyZ
