### ISSUE TITLE
Plotly.deleteFrames(gd, null) should delete *all* frames

### ISSUE THREAD

**Issue by rreusser** [plotly/plotly.js#1528]
Currently, I think `Plotly.deleteFrames('graph', null);` will throw an error as it expects a *list* of frame indices to be deleted. This seems like an oversight. To match `animate(gd, null)`, it should probably delete all frames. If there's agreement, I'll make this quick fix.

will fail here: https://github.com/plotly/plotly.js/blob/master/src/plot_api/plot_api.js#L2767

**Comment by etpinard** [comment]
Hmm. What does `Plotly.deleteTraces(gd, null)` do?

**Comment by rreusser** [comment]
To be honest, I haven't actually tried it, but I believe it'll just throw an error on that line.

**Comment by rreusser** [comment]
Comparison: 

<img width="427" alt="screen shot 2017-03-29 at 16 56 10" src="https://cloud.githubusercontent.com/assets/572717/24476274/a89a3706-14a0-11e7-9a03-4de287a14b7e.png">

**Comment by rreusser** [comment]
The challenge (both for traces and frames, IMO) is that it's difficult to track what the indices actually are since there's no API for querying the state of the chart without digging into `._fullData` — which is pretty stable at this point though still private — and `.transitionData` — which always bugs me as a slight misnomer that should be `_animationData` so that I hate recommending digging into private data as a formally correct answer to how to use deleteFrames or deleteTraces.

**Comment by rreusser** [comment]
(Small addendum that unless no longer throwing an error is a breaking change, I don't see a particular problem with considering both of these an enhancement or both of these simply unsupported (in which case the frame error should be more descriptive))

**Comment by etpinard** [comment]
@rreusser this issue was closed by https://github.com/plotly/plotly.js/pull/1531, correct? Or do you want to leave this open to discuss it further?

**Comment by rreusser** [comment]
Oops. Neglected to close. 👍
