### ISSUE TITLE
scattergeo does not respect datum position in arrayOk attributes

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#1529]
For example

```js
Plotly.plot('graph', [{
  type: 'scattergeo',
  lon: [10, null, 40],
  lat: [0, null, 0],
  marker: {
    color: ['red', 'green', 'blue'],
    size: [20, 50, 10]
  }
}])
```

yields

![image](https://cloud.githubusercontent.com/assets/6675409/24476938/3210ce9e-14a3-11e7-98c0-48d5b8e69815.png)

see http://codepen.io/etpinard/pen/QpJGeq

---

This issues comes from https://github.com/plotly/plotly.js/pull/1004 where we started [skipping](https://github.com/plotly/plotly.js/pull/1004/commits/52c1b89d2f90453f259f766d7c79012e4bff1827#diff-c9c536870c5f780da73fb82c7e5f15bfR42) over items with non-numeric `lon` and/or `lat` coordinates.

Post https://github.com/plotly/plotly.js/pull/1519#discussion_r108450645, I'm having second thoughts about skipping non-numeric items in the calc step though [`mapbox/calc.js`](https://github.com/plotly/plotly.js/blob/master/src/traces/scattermapbox/calc.js) appears to get this right. Ignoring non-numeric items early makes sense for :racehorse: as we save a few `isNumeric` call in hot code paths (e.g. in `<>/plot.js`), but it does lead to some headaches elsewhere in the code (e.g. those [`placeholder`](https://github.com/plotly/plotly.js/pull/1004/commits/dd05c6ee857ff5e5e537ccf946d715e60f9924e2) flags) :confused:

**Comment by alexcjohnson** [comment]
if `isNumeric` is a concern (I'm not sure it is compared to everything else that needs to happen in `<>/plot.js`, but it wouldn't hurt to optimize this) we should be able to ensure `<>/calc.js` replaces all non-numeric points with `BADNUM` and just use `!== BADNUM` which is about as fast as can be imagined.

Right now scatter uses `false` for non-numerics but that was an ancient decision... if we standardize on something it should be `BADNUM`.
