### ISSUE TITLE
PlotSchema.findArrayAttributes doesn't list marker.borderwidth

### ISSUE THREAD

**Issue by n-riesco** [plotly/plotly.js#1534]
While using `PlotSchema.findArrayAttributes`, I noticed it doesn't list `marker.borderwidth` despite having been set to an array.

See [codepen](https://codepen.io/n-riesco/pen/oZQJWW).

**Comment by etpinard** [comment]
I didn't know `borderwidth` was a `scatter` attribute?

**Comment by etpinard** [comment]
It works with [`marker.line.width`](https://codepen.io/etpinard/pen/gmQZyZ?editors=0010).

**Comment by n-riesco** [comment]
Thanks for the quick reply!
