### ISSUE TITLE
Suboptimal performance when rendering large amount of traces

### ISSUE THREAD

**Issue by hy9be** [plotly/plotly.js#1535]
Here is the [testing script](https://jsfiddle.net/smileyhaowen/tf4bpk5w/3/)

I kept the total data points fixed, and tested different combinations of amount of traces and amount of data points per trace:

![image](https://cloud.githubusercontent.com/assets/3392907/24511265/8f45107a-1539-11e7-837c-689b2822d053.png)

You could see that 5000 traces needs 17 seconds to render even it only renders 5000 markers in total. But for the case of only 1 trace, scattergl could use that 17 seconds to render over 10 million markers!

And by looking into the code I found that for each trace we created a Scene2D and a Shader, which get the shader reference and rebuild program. Is there anything we can optimize here?

**Comment by hy9be** [comment]
And another question is since we are using Shader, why it looks all the points are plotted sequentially? Correct me if I am wrong, one of the biggest advantages of using Shader is to leverage the parallel computing paradigm of GPU.

**Comment by hy9be** [comment]
A timeline profile screenshot:

![image](https://cloud.githubusercontent.com/assets/3392907/24512465/a6986c1a-153c-11e7-8374-2c087192469c.png)

**Comment by etpinard** [comment]
Thanks for the very detailed report!

We could indeed optimize `scattergl` so that it groups traces into the least number of `gl-vis` objects (see [`gl-scatter2d`](https://github.com/gl-vis/gl-scatter2d) and [`gl-scatter2d-sdf`](https://github.com/gl-vis/gl-scatter2d-sdf)) possible, but since that can already (easily) be done by the users pre-`Plotly.plot` this is not high on our priority list at the moment.

Performance for graphs with numerous traces is probably plotly.js' Achilles heel at the moment (not just WebGL based traces).

**Comment by hy9be** [comment]
@etpinard I looked into a non-gl``scatter`` example. It looks the time consuming phases are:
- generate uid for each trace in cleanData
- supplyDataDefaults for each trace, for converting strings into objects, and processing color strings
- sort scatter layers
- apply style for each trace

May I ask the specific reason for that "Achilles heel", like the piece of leaf? Thanks!

**Comment by hy9be** [comment]
@etpinard I did some optimization to group and stacked bars when there are large amount of traces. Could any of you guys take a look? Thanks!

https://github.com/plotly/plotly.js/pull/1544

**Comment by hy9be** [comment]
@etpinard I opened another PR to optimize the performance of scatter plot, when there are large amount of traces. All tests passed. FYI: https://github.com/plotly/plotly.js/pull/1555

**Comment by etpinard** [comment]
Addressed in https://github.com/plotly/plotly.js/pull/1555

This is of course not the end of our multi-trace performance problems ...
