### ISSUE TITLE
Dragging point on a line chart

### ISSUE THREAD

**Issue by doaa-altarawy** [plotly/plotly.js#1537]
Is it possible in plotly.js to drag points to change their location (vertically) in a line chart similar to draggable points in highcharts (http://www.highcharts.com/plugin-registry/single/3/Draggable%20Points)

Thanks.

**Comment by etpinard** [comment]
You can probably do this using `plotly_click` and `restyle`. But no, we don't expose that functionality at a high-level similar to what Highcharts does at the moment.

**Comment by maxheld83** [comment]
I'm not sure how this would jive with the overall design/mission of plotly.js, but I think a drag-and-drop event for *elements* would be a fantastic addition, not just in line charts.

Use cases:
- data entry
- especially for surveys
- network plots
- ...

**Comment by etpinard** [comment]
> I'm not sure how this would jive with the overall design/mission of plotly.js,

Probably not to be honest. At least, not in the foreseeable future.

Closing this issue (for now).

**Comment by hherrada** [comment]
This feature would take plotly to a whole new level!

**Comment by niclasmattsson** [comment]
I'm late to the party here, but for anyone else who needs this functionality ...

Draggable points are certainly possibly with the current version of Plotly, you just build on `d3.behavior.drag()`. The only problem is that Plotly by default disables mouse pointer events on the SVG paths that make up the plot points, but you can override that with a line of CSS. I have a [working demo here](http://bl.ocks.org/niclasmattsson/7bceb05fba6c71c78d507adae3d29417) with a brief explanation of the CSS trick. [Full source code here](https://gist.github.com/niclasmattsson/7bceb05fba6c71c78d507adae3d29417).

**Comment by niclasmattsson** [comment]
I needed draggable points in an Electron app (i.e. Chromium only) so didn't test my code on Microsoft's browsers. But I think I found the problem. Apparently SVG attributes have comma-separated coordinates in Firefox & Chrome but Microsoft just has to do its own thing and uses space-separation.

So in the function `startDragBehavior()`, change this line:
```
var translate = transform.substring(10, transform.length-1).split(",");
```
to this:
```
var translate = transform.substring(10, transform.length-1).split(/,| /);
```
That should work with either comma or space separation.

**Comment by DarkFIxED** [comment]
@niclasmattsson, thank you very much. Yes, now it works on EDGE,  but there is performance issue with all browsers except Chrome. Especially in EDGE. Did you faced with this problem?

**Comment by denfromufa** [comment]
There are some other examples here:

https://community.plot.ly/t/moving-the-location-of-a-graph-point-interactively/7161/4

**Comment by Koushikphy** [comment]
any plans to add this feature in the future???

**Comment by DarkFIxED** [comment]
So, there was no moving in that direction for ~2 years. I'll not be sure for this =) As i remember, actually i used direct D3 invocation for d'n'd functionality
