### ISSUE TITLE
barmode stack does not group correctly

### ISSUE THREAD

**Issue by fabiangehring** [plotly/plotly.js#1541]
Hi, when checking this http://codepen.io/etpinard/pen/mPGLrY mentioned here: https://community.plot.ly/t/stacked-bar-with-positive-and-negative-values/920

I saw, that barmode "stack" does not color all the bars correctly. Couldn't find another issue adressing this?

**Comment by n-riesco** [comment]
I don't think stack mode is appropriate for chart plots with negative amounts (I'd use relative instead).

How would you expect stack mode to handle negative amounts?

**Comment by fabiangehring** [comment]
To be honest, I don't know the difference between "stack", "relative" and "overlay". I always though it's the ordering of the stacks. But a stack, where the different groups do not differ in color seemed strange to me. Is there an explanation somewhere for the difference of the 3 modes?

**Comment by etpinard** [comment]
> To be honest, I don't know the difference between "stack", "relative" and "overlay"

Probably best to ask this question on https://community.plot.ly/ so that other users can benefit from it.
