### ISSUE TITLE
Vertical Alignment for Annotations [Feature Request]

### ISSUE THREAD

**Issue by stoberblog** [plotly/plotly.js#1545]
I'm trying to add two annotations to a plot, one in top center, the other bottom center. The problem is, I'd like these to stay visible when I zoom in, so using a static y co-ordinate won't work.

I'm using a scatter plot, and the data I'm plotting is power factor in degrees, where a positive value indicates a capacitive load, and a negative angle represents an inductive load.
![plotly-powerfactor](https://cloud.githubusercontent.com/assets/25950862/24575265/99aef8c8-16ec-11e7-8692-a45b38b94cdd.PNG)

So I propose a feature request to add a parameter called valign (similar to align for the horizontal axis), which allows the text to stay in the same relative vertical location, regardless of scaling or zoom. I'd suggest values of: 'top', 'center', 'bottom', 'positive', 'negative'. The positive and negative can be used to have a label on a certain side of the y=0 line or similar.

Thanks

**Comment by etpinard** [comment]
If I understand your request correctly, you can already do this using `xref: 'paper'` see  http://codepen.io/etpinard/pen/WpmNEo for an example.

**Comment by etpinard** [comment]
@stoberblog maybe https://github.com/plotly/plotly.js/pull/1551/ will do just what you want.

**Comment by alexcjohnson** [comment]
doesn't look like #1551 to me, I'm fairly sure @etpinard 's first thought about setting `xref` and/or `yref` to `'paper'` (with appropriate `x` / `y` values) is what you're looking for. If you want to get really precise with positioning, `xanchor` and `yanchor` can also help.

I'm going to close this, but @stoberblog feel free to reopen if we've missed what you're going for.
