### ISSUE TITLE
Does Plotly support font tags in HTML graph so i can color a specific word in the Title?

### ISSUE THREAD

**Issue by tecoy82** [plotly/plotly.js#1547]
Can I wrap a portion of the Title in a font color tag so that only say one of the three words in the title is red?
  I can only find the list of tags here, http://help.plot.ly/adding-HTML-and-links-to-charts/, which appears to already answer my question but I wanted to get confirmation from anyone that may know another work around.

**Comment by etpinard** [comment]
Here's how http://codepen.io/etpinard/pen/oZVgML

As per our contributing [guidelines](https://github.com/plotly/plotly.js/blob/master/CONTRIBUTING.md), please use our community [forums](https://community.plot.ly/) for questions of the likes so that other users can benefit from the answer. Thanks.
