### ISSUE TITLE
BUG: p2c not reliable in scatter or gl2d

### ISSUE THREAD

**Issue by destradafilm** [plotly/plotly.js#1548]
Based of this example by @etpinard 
http://codepen.io/etpinard/pen/EyydEj

If you zoom or pan, the p2c conversion is unreliable
![p2c bug](https://cloud.githubusercontent.com/assets/6043499/24621877/5672fad0-1860-11e7-8128-d53c62596d4e.gif)

**Comment by etpinard** [comment]
That `p2c` and other `x2y` conversion functions aren't _official_ features by any means and aren't guaranteed to work. That codepen I wrote is grade-A hack. 

What I think we should do: is add another `plotly_` event (e.g. `plotly_mouse`) that would get fired on anytime you mouse over a graph with or without triggering `plotly_hover`.

**Comment by destradafilm** [comment]
I vote for that `ploty_mouse` event

**Comment by etpinard** [comment]
@destradafilm great. I'll close this issue then and merge it with https://github.com/plotly/plotly.js/issues/145

**Comment by therealsquidgee** [comment]
Hey @destradafilm not sure if you still need this but I slightly modified @eptinard's codepen to make the mousemove event more reliable (still a grade A hack though and it will error if the start and end of the x range are equidistant from 0 e.g. [-12, 12] or something like that).

http://codepen.io/therealsquidgee/pen/EmbOzX
