### ISSUE TITLE
plots.addLinks is still called even set { showLink: false }

### ISSUE THREAD

**Issue by hy9be** [plotly/plotly.js#1554]
Not sure if this is expected. The main concern here is performance. As some measurements and reflows occurs, this function call always add about 100ms overhead on my 2015 Macbook pro. I have not tested on other devices, but I expect more delays on some older hardwares. 

![image](https://cloud.githubusercontent.com/assets/3392907/24715195/9ae301bc-19f8-11e7-8dee-c27428f0f5dd.png)

**Comment by etpinard** [comment]
Thanks for the report! 

Your patch in #1557 will improve this for most users as `showLink: false` by default. But we should also try to find an alternative for that :turtle:  `getComputedTextLength()` call [here](https://github.com/plotly/plotly.js/blob/ce06ea9cea377c5ed87ed7baa088a14a1997dbb7/src/plots/plots.js#L291).

**Comment by etpinard** [comment]
done in https://github.com/plotly/plotly.js/pull/1557
