### ISSUE TITLE
<span>'s in text labels move during animations

### ISSUE THREAD

**Issue by n-riesco** [plotly/plotly.js#1556]
I have created a scatter plot that changes the opacity of a trace when clicked.
I have also set text labels for each point.
The text labels contain `<span>`'s and I've noticed they move during animations.

Here's a [codepen](http://codepen.io/n-riesco/pen/yMrwgO) that illustrates the issue better than I can describe.

**Comment by rreusser** [comment]
Hmm… I don't know _why_ it's happening, but here's what's happening:

![ezgif-1-c5b1134278](https://cloud.githubusercontent.com/assets/572717/24726210/88997028-1a1f-11e7-9e1c-05ab24d2deda.gif)

During the animation, the span gets offset properties. I'll need to investigate further though. I recall svg text span positioning being kinda strange and complicated the first time I encountered it.
