### ISSUE TITLE
Y-Axis ticks are not rounded for line chart

### ISSUE THREAD

**Issue by suribabu39** [plotly/plotly.js#1559]
Hi, 
Y-Axis ticks are not getting rounded up automatically if provided only one tick value. Can we do anything to round up tick values other than limiting ticks(in below case giving max ticks as 1).

Codepen Link: http://codepen.io/suribabu_95/pen/bqyRaX?editors=1010

Thank You in advance,

**Comment by etpinard** [comment]
I'm not 100% sure what your desired behavior is. 

Here's two ways to control the ticks values: http://codepen.io/etpinard/pen/LWozmR?editors=0010

**Comment by suribabu39** [comment]
I want y axis tick values to be rounded up. It should show only one tick as there is only one y axis value(1st way among those which you have mentioned). But that value should be rounded up, In this particular case it should show 5.78B rather than showing 5.77837481B. Is there any way to round up ticks to fixed decimal values ? 
Also shouldn't it show only one tick by default if there is only one y-axis value?

**Comment by etpinard** [comment]
Ok well, I think http://codepen.io/etpinard/pen/dvBXYR?editors=0010 does exactly what you're hoping.

I won't go into why one tick isn't showing _by default_ because that's very much debatable. 

If you have other question about plotly, please consider checking our community forum at https://community.plot.ly/

**Comment by suribabu39** [comment]
Hi, 
Thanks for the above solution(using tickFormat).
Formatting ticks to limited decimal values is working fine with tickFormat. However I am getting 'G' as suffix for y axis ticks if I use tickFormat, if I don't use tickFormat then it would show it with suffix 'B'. As y axis ticks are numbers I would like to show them with 'B' (with Million, Billion, Trillion formatting).
Is there a way to show that way? Should I change tickFormat?
Thanks in advance,

**Comment by suribabu39** [comment]
I have also tried using [exponentformat](https://plot.ly/javascript/reference/#layout-yaxis-exponentformat), but still I am not getting ticks in Billions format. 
[Codepen link](https://codepen.io/suribabu_95/pen/zwdQXK)
