### ISSUE TITLE
BUG: range is wrong if layout.axis.type == 'log'

### ISSUE THREAD

**Issue by destradafilm** [plotly/plotly.js#1561]
![plotlyjs_bug_range numbers in log](https://cloud.githubusercontent.com/assets/6043499/24777197/777bf424-1ae1-11e7-8c55-045e4a8299fd.gif)

As you can see, the range I'm getting for the y axis 
`min: plotlyDiv._fullLayout.yaxis.range[0]`
`max: plotlyDiv._fullLayout.yaxis.range[1]`

Is wrong when the axis.type is 'log' unless there's a conversion I'm not aware of

codepen:
http://codepen.io/destrada/pen/qrGJwq

**Comment by destradafilm** [comment]
Nevermind, I realize this is a log10 conversion of the number range

**Comment by etpinard** [comment]
@destradafilm I was just going to write that.

That `log10` conversion is unfortunate, but there's no way for us to fix it in a backward-compatible way. 

This is essentially the same issue as https://github.com/plotly/plotly.js/issues/1258 that we're planing on fixing in v2.  Thanks for posting.

**Comment by oricou** [comment]
That's quite unpleasant, it seems I use Plotly v. 2.7 and I still have it.

I tried to do in Dash for my graph which can switch from log to linear:
```python
range=(0,55000) if xaxis_type == 'linear'
                else (np.log10(50), np.log10(55000))
```
but it does not work

**Comment by alexcjohnson** [comment]
@oricou that’s v2 of `plotly.py`. `plotly.js` is still on v1.

**Comment by oricou** [comment]
ok thanks. Any date for version 2? I couldn't find any roadmap...
