### ISSUE TITLE
relayout() fails when adding array item object with constructor

### ISSUE THREAD

**Issue by fhurta** [plotly/plotly.js#1563]
I upgraded plotly.js from 1.17.1 to 1.25.2 and started facing strange behavior when adding shapes into graph programmatically (after newPlot()).

I use Typescript and the shape object I pass into relayout() function is defined as a class in Typescript. The details are not much relevant, I put together a sample to reproduce the misbehavior by simply wrapping the object with `Object.create()` (Actually it is for `images`, not `shapes`, but id does not matter). Please see here [http://codepen.io/exavier/pen/RpzRJY?editors=0011](http://codepen.io/exavier/pen/RpzRJY?editors=0011)

In `relayout()` it comes to check `manageArrays.isAddVal(vi)`, which in turn does check `isPlainObject(val)` where the failing check is `Object.getPrototypeOf(obj) === Object.prototype`.

**Comment by etpinard** [comment]
Thanks for bringing this up. 

Related to https://github.com/plotly/plotly.js/issues/1405

**Comment by fhurta** [comment]
Thanks. 
Just to choose right workaround - as #1405 status is 'discussion needed' since Feb 22, am I right thinking it is not going to be fixed anytime soon?

**Comment by etpinard** [comment]
@fhurta correct, this issue is likely not going to be resolved anytime soon.

**Comment by etpinard** [comment]
... and I'm actually going to merge this ticket with https://github.com/plotly/plotly.js/issues/1405 as it's really two reports of the same issue.
