### ISSUE TITLE
Supplying text as a string doesn't work as expected

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#1565]
http://codepen.io/cpsievert/pen/xqodgv

**Comment by etpinard** [comment]
This isn't a problem for `scatter` traces: http://codepen.io/etpinard/pen/WpVqOa?editors=1010

![peek 2017-04-10 17-15](https://cloud.githubusercontent.com/assets/6675409/24883068/58c7b012-1e11-11e7-9b64-c8e8380c2311.gif)

**Comment by etpinard** [comment]
Is (miraculously :pray: ) fixed in `1.26.0`

![peek 2017-04-26 16-29](https://cloud.githubusercontent.com/assets/6675409/25455397/a9dba8d0-2a9d-11e7-8a9f-e1a7ae254156.gif)

**Comment by etpinard** [comment]
I suspect https://github.com/plotly/plotly.js/pull/1523/commits/7b6911fcc3643878cd6e6f7ca97620c57a3fdfd6 fixed it.
