### ISSUE TITLE
feature request: when downloading plot as png using the modebar button, use the current size of the plot as the size of the png

### ISSUE THREAD

**Issue by finger563** [plotly/plotly.js#1576]
Currently it does not use the size of the plot as it has been rendered into the browser. The data ranges and such are all the same, but since the size is different the legend may overlap parts that it did not when viewed in the browser and the aspect ratio may be different.

**Comment by etpinard** [comment]
Unfortunately, that's more like a backward-incompatible change than a feature request. If we do choose to do this, we'll have to wait for [`v2`](https://github.com/plotly/plotly.js/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20v2).

In the meantime, here's a workaround: http://codepen.io/etpinard/pen/NpvYOo

**Comment by finger563** [comment]
Thanks for the feedback and adding my own options to that code snippet worked well :)

**Comment by jayanthcl** [comment]
Hi,
Thanks for suggesting the workaround

> Unfortunately, that's more like a backward-incompatible change than a feature request. If we do choose to do this, we'll have to wait for [`v2`](https://github.com/plotly/plotly.js/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20v2).
> 
> In the meantime, here's a workaround: http://codepen.io/etpinard/pen/NpvYOo

I am using Angular wrapper for Plotly (https://github.com/plotly/angular-plotly.js/)
Unfortunately, I cannot figure out the proper syntax for this workaround.
Is there a way to use Plotly module from my Angular component?

Will appreciate a lot your help!

**Comment by ijustmadethisforplotly** [comment]
Is there any progress on this feature?- It kinda seems important to be able to save your plots as an png :)

**Comment by ijustmadethisforplotly** [comment]
Bump

**Comment by nicolaskruchten** [comment]
@etpinard would this really be a "breaking" change? In what scenarios would this not be a net improvement over the current arbitrary dimensions of the downloaded PNG when no width/height are set?

**Comment by etpinard** [comment]
https://github.com/plotly/plotly.js/pull/3746 add a JSON-serializable way to do effectively what is presented in https://github.com/plotly/plotly.js/issues/1576#issuecomment-293043413

-----

Next, as @antoinerg points out in https://github.com/plotly/plotly.js/pull/3746#issuecomment-481012418, maybe we could:

> Could config options `toImageButtonOptions: {width: null, height: null}` be the default when responsive: true?

in v2, or better yet make `{width: null, height: null}` the default behavior in v2 when `Plotly.toImage` is called with an existing graph div as first argument.
