### ISSUE TITLE
Refactor recalcAttrs

### ISSUE THREAD

**Issue by rreusser** [plotly/plotly.js#1578]
Carpet is going to add a huge number of attrs to recalcAttrs. (up to 287 total or so!?) The array of attributes is recalculated on every plot *and* it looks them up with `indexOf`. It should place them in a hash (e.g. `{mode: true, visible: true, ...}`) and should be defined in a plot-api-global context since it never changes.

@alexcjohnson notes that a larger refactoring is desired, but this might be a start since, at least once carpet is merged, it shouldn't take more than five minutes and may very well be at the point of having a non-negligible impact on performance.

cc @etpinard

**Comment by etpinard** [comment]
Merging this issue with https://github.com/plotly/plotly.js/issues/648
