### ISSUE TITLE
Date() x-axis data gets incorrectly retrieved when getting the closest point in the 'plotly_click' function

### ISSUE THREAD

**Issue by finger563** [plotly/plotly.js#1583]
Appears to be offset by timezone of the computer on which it's running.

E.g. when I create a data point with a certain epoch time in milliseconds and then click on that data point and get it's x-value (after using `point.xaxis.d2l(point.x)`) I get the wrong number of ms since the epoch.

**Comment by etpinard** [comment]
I think the discussion in https://github.com/plotly/plotly.js/issues/1532 will answer your questions.

**Comment by etpinard** [comment]
Merging with #1532
