### ISSUE TITLE
Log which baselines are missing

### ISSUE THREAD

**Issue by rreusser** [plotly/plotly.js#1587]
Just a reminder. Should be easy. I get:

```
ok 351 viridis_heatmap should be pixel perfect
ok 352 yignbu_heatmap should be pixel perfect
ok 353 world-cals should be pixel perfect
ok 354 yiorrd_heatmap should be pixel perfect
ok 355 zsmooth_methods should be pixel perfect
not ok 356 plan != count
  ---
    operator: fail
    expected: 356
    actual:   355
  ...
```

But unless I'm missing it, there's no message about *which* mock wasn't found, which makes it difficult to debug.

**Comment by etpinard** [comment]
After https://github.com/plotly/plotly.js/pull/1569/commits/3ebe7976d5d54ec00372bd4a6b984ba9781bfe3f, scrolling up should give you the problematic mock name.

**Comment by etpinard** [comment]
But yeah, keeping a list of all mocks that didn't get pixel-tested and logging it at the end of the test run would be nice :+1:

**Comment by rreusser** [comment]
Cool! Yeah, that's absolutely sufficient. Current strategy was to ls + diff in my local repo.

**Comment by rreusser** [comment]
I'm content to close as long as you _can_ figure out which are missing. Feel free to reopen if desired. 👍
