### ISSUE TITLE
Outline for text layers

### ISSUE THREAD

**Issue by alanocallaghan** [plotly/plotly.js#1597]
It would be very helpful to be able to add outlines to text layers. This allows for text to be legible on any background (eg white text with black outline, or black text with white outline). 

Also, though not strictly related, there does not seem to be any documentation of the options "familysrc", "sizesrc", or "colorsrc" anywhere.
https://plot.ly/javascript/reference/#bar-textfont
https://plot.ly/r/reference/#scatter-textfont

Related: https://github.com/talgalili/heatmaply/issues/42

**Comment by etpinard** [comment]
> Also, though not strictly related, there does not seem to be any documentation of the options "familysrc", "sizesrc", or "colorsrc" anywhere.

Those shouldn't even be displayed in the docs pages. Thanks for pointing this out.

**Comment by Alanocallaghan** [comment]
No worries, fyi there are a few similar things hanging around in the documentation, eg
https://plot.ly/javascript/reference/#bar-marker-colorbar-tickvalssrc

**Comment by etpinard** [comment]
> It would be very helpful to be able to add outlines to text layers.

About this here, can you share a screenshot to help us understand what you're looking for?

**Comment by Alanocallaghan** [comment]
Google maps uses dark text with a white outline, while white text with a dark outline also works. It's the most effective way to make text readable on any background 

http://asset0.cbsistatic.com/cnwk.1d/i/bto/20081009/google_maps_taxi_ad.png
http://2.bp.blogspot.com/-TGEt81O_qaI/Uxns70ZKVEI/AAAAAAAACE4/V5v81OF9sT4/s1600/white-text-black-outline.png

**Comment by rreusser** [comment]
A note on implementation: for SVG, it requires two copies of the text element with different `stroke-width` properties (that is, it's possible but not just a simple property, which means it requires a bit more effort)

**Comment by alexcjohnson** [comment]
Our much-neglected polar charts do this with the text-shadow style:
![screen shot 2017-04-18 at 10 13 56 am](https://cloud.githubusercontent.com/assets/2678795/25135240/c839cf8e-241f-11e7-997f-0cf6910907b9.png)


```
<text dy="0" y="0" x="0" dx="0" transform="rotate(45) translate(0,15)" style="
  text-anchor: start;
  font-size: 15px;
  font-family: Tahoma, sans-serif;
  fill: gray;
  text-shadow: white -1px 0px 0px, white 1px -1px 0px, white -1px 1px 0px, white 1px 1px 0px;
">0</text>
```
Might cease to look good at a greater thickness though, as that's not going to increase the radius of curvature. But it at least avoids having to copy everything. Kind of an odd collection of offsets, I wonder if that was intentional...

I'll also note that applying this to mathjax will require a completely distinct implementation regardless, as it generates its own SVG paths.

**Comment by rreusser** [comment]
Oh wow, I stand corrected! Thanks for that. I missed that in my googling.

**Comment by etpinard** [comment]
From https://github.com/plotly/plotly.js/pull/3191#issuecomment-434676329

> Definitely an improvement! I'm just wondering if we want to go one step further and make a new attribute (`tickshadow`?) that defaults to `paper_bgcolor` but people could set it to whatever they want (including transparent).

**Comment by fgenoese** [comment]
@etpinard : After reading through this issue it is not clear to me what the solution is.

Imagine the following case: on top of a choropleth map you add a text trace to indicate a value permanently (not just through a hover). Considering that the heatmap has colors from light yellow to dark blue, it is almost impossible to choose a font color of the text trace which is visible on the map. What would you suggest?

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Comment by gvwilson** [comment]
@alanocallaghan thanks for your feedback - we're trying to sort through over 3500 open issues across more than 100 repositories and figure out which ones people do still care about. I'll reopen this one and assign it to myself for further triage.

**Comment by alanocallaghan** [comment]
By all means carry on, I imagine there's hundreds of good ideas and valid bug reports in here but dealing with a huge backlog is difficult. Probably just a grumpy Monday response from me

**Comment by alexcjohnson** [comment]
Is this already solved by the new `font.shadow` attributes? https://github.com/plotly/plotly.js/pull/6983 ?
