### ISSUE TITLE
hoverinfo: name field not included for HeatMap

### ISSUE THREAD

**Issue by jsundram** [plotly/plotly.js#1600]
## Code
*run inside of a jupyter notebook cell...*

```python
import numpy as np
import plotly  # plotly.__version__ == '2.0.6'
plotly.offline.init_notebook_mode()
import plotly.graph_objs as go

rows, cols = 3, 3 
data = np.random.rand(rows, cols)
py.iplot(go.Figure(
    data=[go.Heatmap(
        name="CUSTOM NAME",  # This SHOULD show up in the hoverinfo?
        x=range(rows + 1), 
        y=range(cols + 1), 
        z=data, 
        text=np.where(data < .5, '<.5', '>.5'),
        hoverinfo="name+text",  # Want to see "CUSTOM NAME"
        colorscale='Greens', reversescale=True, showscale=False
    )], 
    layout=go.Layout(
        title="Test", 
        xaxis=dict(title='X-Axis'),
        yaxis=dict(title='Y-Axis'),
    )
))
```

# Result 
*it's a bit small, but you can see that the hovertext lacks the CUSTOM NAME text.*

<img width="1676" alt="screenshot of result, showing tooltip without Name" src="https://cloud.githubusercontent.com/assets/150536/25076262/2476f99a-22ed-11e7-86a4-d8e81ad65e7e.png">

**Comment by etpinard** [comment]
In JS: https://codepen.io/etpinard/pen/xdwYmL

Thanks for report.

You're `hoverinfo: 'name'` doesn't work currently for heatmap.

**Comment by alexcjohnson** [comment]
@etpinard if you want to include this fix in your hover labels PR, it's as simple as removing:
`&& d.zLabelVal === undefined`
from https://github.com/plotly/plotly.js/pull/1582/files#diff-53eaf7f3ac3274b40206f89f8f87a5d6R689

I don't really recall why that condition was put in there - maybe on the idea that you're already showing lots of info about heatmap points and you don't want to show more? Probably some long-obsolete rationale. 🔪
