### ISSUE TITLE
Legend has no effect for Heatmap

### ISSUE THREAD

**Issue by jsundram** [plotly/plotly.js#1601]
You can see this by turning Legend on inside this fiddle:
[https://plot.ly/create/?fid=PythonPlotBot:823](https://plot.ly/create/?fid=PythonPlotBot:823)

### Screenshot:
<img width="1145" alt="Screenshot of Legend not displaying " src="https://cloud.githubusercontent.com/assets/150536/25076702/20c17d26-22f1-11e7-9f0f-8a5ead17f7ef.png">

**Comment by etpinard** [comment]
Sounds like you're referring to a plot.ly bug not a plotly.js bug, so I'll close this issue and report it internally. 

In the future, I recommand reporting plot.ly bugs on https://community.plot.ly/

Thank you.

**Comment by kevinwuhoo** [comment]
I'm also experiencing this issue, but _not_ in plot.ly. I thought I was doing something wrong until I found an example in the docs where it's not working: https://codepen.io/plotly/pen/WQGgbe.

It's linked from here: https://plot.ly/javascript/configuration-options/#modify-the-edit-chart-link-text. Side note, the syntax highlighting is also a little messed up in that example.
