### ISSUE TITLE
scattergl image background feature request

### ISSUE THREAD

**Issue by dirtyredz** [plotly/plotly.js#1603]
I was using scatter until my graph's data grew to over 25k points. When I transfered to scattergl for performance. The background image I was using did not appear. The image for the graph and the zooming ability is integral to the experience I'm providing. 

Ive been unable to find any info available to whether or not images are supported for scattergl. Any information or support for this would be appreciated.

**Comment by etpinard** [comment]
cc @dfcreative would be nice in `scattergl` v2

**Comment by etpinard** [comment]
Will be completed in @dfcreative 's regl-based `scattergl`:

![image](https://user-images.githubusercontent.com/6675409/34687909-3c11f93e-f47e-11e7-8e17-2b3b93d56a8a.png)

**Comment by dfcreative** [comment]
Added test mock in https://github.com/plotly/plotly.js/commit/20491b2f2838d0894c0ea7865578157873bbe175

**Comment by etpinard** [comment]
Done in https://github.com/plotly/plotly.js/pull/2258
