### ISSUE TITLE
jerky transition in plots with a date axis

### ISSUE THREAD

**Issue by n-riesco** [plotly/plotly.js#1607]
The animation of an date axis range isn't smooth nor linear.

Here's a [codepen](http://codepen.io/n-riesco/pen/GmoZEx) that shows the issue.

![peek 2017-04-19 10-49](https://cloud.githubusercontent.com/assets/6199391/25174028/0331d608-24ee-11e7-825a-69820ce5bf7c.gif)

**Comment by etpinard** [comment]
Probably related to https://github.com/plotly/plotly.js/issues/2062

**Comment by dgopsq** [comment]
Any updates on this? Is there something I can do to make Plotly.js transitions work with a date axis?

**Comment by brussee** [comment]
Here is a minimal workaround for your inspiration: https://codepen.io/pbrussee/pen/YzKaLjQ

**Comment by etpinard** [comment]
These jerky transitions here have the same underlying cause as https://github.com/plotly/plotly.js/issues/2062, so I'll close this issue.

(P.S. I'm working on a fix now)
