### ISSUE TITLE
Marker text size distorted during animations

### ISSUE THREAD

**Issue by n-riesco** [plotly/plotly.js#1608]
Taken from #1607.

Here's a [codepen](http://codepen.io/n-riesco/pen/GmoZEx) that shows the issue.

![peek 2017-04-19 10-49](https://cloud.githubusercontent.com/assets/6199391/25174028/0331d608-24ee-11e7-825a-69820ce5bf7c.gif)

**Comment by alexcjohnson** [comment]
And during zoom (by dragging an axis end or corner). @rreusser it was you who put in the inverse-distortion code for points and lines, right? Should be easy to extend to text?

**Comment by etpinard** [comment]
Closed via https://github.com/plotly/plotly.js/pull/1616 by @rreusser
