### ISSUE TITLE
tick0 not working for line charts

### ISSUE THREAD

**Issue by suribabu39** [plotly/plotly.js#1610]
Hi,
I want to show 0 as default first tick for y-axis always. According to [this](https://plot.ly/javascript-graphing-library/reference/#yaxis-tick0), assigning tick0 value to yaxis should give the desired output, but it is not working that away. Should I give any other arguments ?

[Codepen link](http://codepen.io/suribabu_95/pen/eWJqqx?editors=0010)

**Comment by alexcjohnson** [comment]
`tick0` just controls the formula that determines where to draw ticks. It doesn't affect the range of the axis, which in your case doesn't reach zero.

The setting you want is [`rangemode: 'tozero'`](https://plot.ly/javascript-graphing-library/reference/#yaxis-rangemode)
