### ISSUE TITLE
Support for editable, movable annotations on click

### ISSUE THREAD

**Issue by gunkaragoz** [plotly/plotly.js#1611]
It would be good to have built-in enhanced annotation option. 

Here is my recommendations:
- editable, movable (draggable) annotations.
- annotation color shall be available to change.
- text/ icons / lines / rectangle / circle / images can be added as annotation.

Reference: https://jsfiddle.net/BlackLabel/N6GR9/

I saw it in plotly cloud as notes, I couldn't find any related example or documentation except the one https://codepen.io/anon/pen/YVqGXb

**Comment by etpinard** [comment]
You mean like this https://codepen.io/etpinard/pen/MmybBN ?
