### ISSUE TITLE
Marker size animation disabled by axis range animation

### ISSUE THREAD

**Issue by n-riesco** [plotly/plotly.js#1622]
Here's another [codepen](http://codepen.io/n-riesco/pen/NjbLEP) adapted from #1607 .

It shows that marker size animations work smoothly if the axis ranges don't change.
But if the axis ranges change, the marker size isn't animated, it transitions immediately.

![peek 2017-04-26 09-14](https://cloud.githubusercontent.com/assets/6199391/25424684/26409850-2a61-11e7-9f17-5d4dbadbcd61.gif)

**Comment by rreusser** [comment]
I think this one will need to remain this way. The general case of transitioning data and layout at the same time resulted in a combination of interactions I was simply unable to tame. Marker sizes aren't that problematic, but there's no way to know or guarantee that it won't also be the x/y data changing.

**Comment by etpinard** [comment]
@n-riesco ok to close this one post https://github.com/plotly/plotly.js/issues/1622#issuecomment-297351665 ?
