### ISSUE TITLE
Boxplot annotations

### ISSUE THREAD

**Issue by deecay** [plotly/plotly.js#1642]
I would like to see annotations to a boxplot such as [this](http://stackoverflow.com/questions/35644665/d3-js-grouped-box-plot).

**Comment by etpinard** [comment]
I guess that would be nice, but this won't be a high priority in the short term. 

In the meantime you can use annotations to get the desired result.

**Comment by deecay** [comment]
Thanks, I understand.

I have seen box annotation with `Plotly.plot().then((gd) => {gd.calcdata....Plotly.relayout()});`. Is there a way to obtain or calculate values equivalent to box plot `calcdata` before `plot()`? I really would like to draw box and annotation in first `Plotly.plot()` call.
