### ISSUE TITLE
Http 403 Error on 1.26.1 release

### ISSUE THREAD

**Issue by hy9be** [plotly/plotly.js#1643]
The [link to 1.26.1 script](https://cdn.plot.ly/plotly-basic-1.26.1.js) returns 403 code and the XML message below:
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>5EC454953AA428AA</RequestId>
<HostId>
X+cExrH1PzwDEU7nJbTWaoF1z3oHrIOPUMPju/mT791RRZyqkKRndb+jSGNZYKX7xG3DLyQSEhA=
</HostId>
</Error>
```

**Comment by etpinard** [comment]
Thanks for the headsup. Something went wrong during the last release. The CDN links are now fixed.
