### ISSUE TITLE
plotly_click event data.points coordinates not being numbers

### ISSUE THREAD

**Issue by dzduniak** [plotly/plotly.js#1644]
Let me start with saying I'm not sure what the real issue is, here I just provide my speculation.

In my code I use click events to obtain point position on a surface plot and then I tried to put coordinates of that point inside a html number input box (here represented by `startx` and `starty` variables).
I was getting an error saying that value doesn't match required format. After some investigation I noticed that value of the points coordinates are not really numbers but strings (I suspect) where minus sign was represented by ''\u2212" unicode character instead of default minus-hyphen character. 

I suspect the problem might be that plotly is incorrectly taking values from some html element's text (which might have undergone some formatting, hence the weird "\u2212" character) instead of using actual number value from the surface.

    plot.on('plotly_click', function (data) {
        if (data.points.length === 1) {
            var point = data.points[0];
   
            console.log(point.x + " " + point.y);

            startx.value = point.x.replace("\u2212","-"); // HERE my "fix"
            starty.value = point.y.replace("\u2212","-"); // HERE my "fix"
        }
    });

**Comment by etpinard** [comment]
Can you share a fully reproducible example i.e. that contains your data to help debug? Thank you.

**Comment by dzduniak** [comment]
@etpinard 
http://codepen.io/qwertsol/pen/aWyzBM

Try clicking on surface point with negative `x` coordinate. In console (browser console, not codepen console) you will see a warning about number not matching required format.

**Comment by etpinard** [comment]
Fixed in https://github.com/plotly/plotly.js/pull/1582/commits/92de0176c26e866c3ffd18a6a1e8dc017cf4c78e

This patch will be patch of the next minor release `1.27.0`
