### ISSUE TITLE
plotly_click and plotly_select buggy on scatter/markers plot

### ISSUE THREAD

**Issue by r1z1a** [plotly/plotly.js#1648]
I made a codepen here:
[Codepen](https://codepen.io/anon/pen/rmzgda?editors=0011)

plotly_click:
So when you click on a given point, it only returns one object even when there is 10 points at each of the 3 locations. Does it not register the other points, that are also with same x and y coordinates?

plotly_selected:
As you can see when you select(box or lasso) any given point or set of points, the total number of objects always appends the NA items into the array. Also the selection does not give more than just x,y, pointNumber and curveNumber the actual data for each point is not passed into plotly_select.

**Comment by etpinard** [comment]
> So when you click on a given point, it only returns one object even when there is 10 points at each of the 3 locations. Does it not register the other points, that are also with same x and y coordinates?

That's been discussed in https://github.com/plotly/plotly.js/issues/720#issuecomment-230900670 - it is the intended behavior I'm afraid.

> As you can see when you select(box or lasso) any given point or set of points, the total number of objects always appends the NA items into the array

Oh. That's a bug. Thanks for discovering it!

> Also the selection does not give more than just x,y, pointNumber and curveNumber the actual data for each point is not passed into plotly_select.

Ok, but what else do you want it there?

**Comment by etpinard** [comment]
> As you can see when you select(box or lasso) any given point or set of points, the total number of objects always appends the NA items into the array

will be via https://github.com/plotly/plotly.js/pull/1656

**Comment by r1z1a** [comment]
> That's been discussed in #720 (comment) - it is the intended behavior I'm afraid.
Yeah I suspected that this is set in stone and would make sense since not everyone would want to return multiple click events from hitting one point. 
I saw that someone has made a topic about adding "jitter" functionality which would solve the issue since you would be able to zoom in very close and points would not be superimposed #299

> Oh. That's a bug. Thanks for discovering it!
No problem, its better that I rewrite my code once the fix is out, than other people struggling with this problem.

> Ok, but what else do you want it there?
Stemming back from first issue where _click will not allow you to hit multiple points and, and since there is no jittering I'm using the _select to pick up the points that are below the top one. It would be nice if it also returned data, like plotly_click. Although I understand you can get the data for whole graph from the div and then go though each point and get the info that way. 
Just thought it would be nice to have consistence between the 2 events since they seem similar in that way. Maybe just for me and way I use them.

Thanks for quick response

**Comment by etpinard** [comment]
> It would be nice if it also returned data, like plotly_click

Oh good point! I agree. Double-checking with @alexcjohnson before I add it in.
