### ISSUE TITLE
Is there a way to add a png/jpg image to a 3D plotly graph (in R)

### ISSUE THREAD

**Issue by renegademonkey** [plotly/plotly.js#1650]
Hi there,

This is more of a help/feature request than an issue.

I am plotting a 3D surface image (similar to your volcano data example):

`plot_ly(z = ~volcano) %>% add_surface()`

The only difference is that my data is related to geographical coordinates (on the x and y axes). What I would like to now do is overlay/underlay a real map onto this graph as an additional surface, either as map tiles or even just as a plain jpg/png file.

I've downloaded a detailed map image with the exact same co-ordinates/dimensions as my plot. I've already spent many hours trying to figure out how to add an image as a flat surface layer to the 3D plot, but have not yet succeeded.

I can see how to add additional plotted surfaces (as per [here](https://plot.ly/r/3d-surface-plots/#multiple-surfaces)) by adding:

`%>% add_surface(z = z_matrix)`

but specifying an image here doesn't work (needs a matrix).

I've also looked into trying to add it as a background image, [as you would in a 2D plot](https://plot.ly/r/logos/), but this doesn't work in 3D plots.

Is there any other way this can be achieved?

**Comment by etpinard** [comment]
Not sure why you're posting this here. It sounds like an issue for https://github.com/ropensci/plotly/issues ?

**Comment by renegademonkey** [comment]
because: [they shuttled me here](https://github.com/ropensci/plotly/issues/988)

**Comment by cpsievert** [comment]
@etpinard this seems to be a request for images in 3D plots. I was assuming that isn't yet possible in plotly.js, so I recommended posting here.

**Comment by etpinard** [comment]
My bad, I read this too quickly and didn't see it was about 3D (seeing R code in plotly.js tickets tends to do that to me). 

Now, to answer @renegademonkey's question 

> Is there a way to add a png/jpg image to a 3D plotly graph 

Paper-referenced images on 3D graphs work. Data-referenced images on 3D graphs don't - and quite frankly I'm not even sure it's feasible to implement such feature.

@renegademonkey can you share a screenshot of what you're trying to do?

**Comment by jackparmer** [comment]
@renegademonkey this may not be exactly what you're looking for, but  @empet has some nice 2d projections of 3d surfaces:

![image](https://cloud.githubusercontent.com/assets/1865834/25830319/e016c3cc-3410-11e7-8cb2-3de303d88db6.png)

https://plot.ly/~empet/14225

**Comment by renegademonkey** [comment]
Thanks for the prompt responses!

@etpinard: I'm not sure what you mean by paper-referenced images - do you mean static flat images? If so, then that is roughly what I am trying to do, just haven't found a way to do it yet. I also haven't found any examples online of exactly what I am trying to achieve. 

Basically, I have created a 3D surface plot which represents RF activity across a specific geographical area, plotted on a 3km x 3km grid with 50m resolution. It looks very similar to your [basic 3D surface plot](https://plot.ly/r/3d-surface-plots/#basic-3d-surface-plot), except that x and y a longitude and latitude.

As this data represents real geographical space, I would also like to OVERLAY an actual map onto this plot, so that someone can see where spikes of RF activity correspond to in the real world. Now, I appreciate that doing this programatically might be overly complicated (e.g. by automatically pulling relevant lat/long map tiles from mapbox of gmaps and aligning them for example). However, I have separately downloaded a map png which corresponds exactly to the same lat/lon coordinates as represented on my 3D surface plot - and now I am trying to figure out how to add this png to the 3D plot as an additional 'surface' (i.e. a flat png image). This could either be as a plot 'background image' on the x-y axis, or an additional floating flat 'surface'. 

The final image should resemble this: 
![tutorial_3dsurfacemap_05](https://cloud.githubusercontent.com/assets/23357640/25841433/ff083e82-3497-11e7-9363-488a209d5956.png)

HOWEVER, the flat 2D surface along the bottom should be an imported image, rather than a 2D representation of the same surface data.

@jackparmer: what you showed is a similar concept to what I am trying to achieve, but the 2D surface I need to plot is an imported 2D png/jpg image, rather than a 2D representation of existing data. 

Is there a way to do this in surface plots?

**Comment by jackparmer** [comment]
@renegademonkey I've never tried including an image in a 3d plot through layout.images, but you could easily map your image to a flat surface at z=-250. Here is the general approach for how that can be done in Python:
https://plot.ly/~empet/14172

**Comment by cpsievert** [comment]
@renegademonkey want to open a community post at so we can talk about implementing in R? <https://community.plot.ly/>

**Comment by renegademonkey** [comment]
@jackparmer : thanks for the tip! I'm having a look at that post now to see if I can implement something similar in R.

@cpsievert : will make a community post also to see if anyone else has ideas about an R implementation.

**Comment by etpinard** [comment]
This ticket won't lead to a PR. Closing.
