### ISSUE TITLE
IE9 JS Plotly.redraw and Plotly.addTraces both throws Invalid Argument

### ISSUE THREAD

**Issue by micwc** [plotly/plotly.js#166]
I used the recommended way to load plotly for IE9 with the typedarray
```
<script>if(typeof window.Int16Array !== 'function')document.write("<scri"+"pt src='extras/typedarray.min.js'></scr"+"ipt>");</script>

<script type="text/javascript" src="plotly.min.js"></script>
```

I am trying to do a simple "bar" chart with three traces. However, both addTraces (adding one trace at a time) and redraw (array of traces) would throw "Invalid Argument" error in IE9 and no bars on graph

IE10+ works
Chrome works

Is there a workaround for this in IE9? It is a little urgent

thanks for any help

**Comment by etpinard** [comment]
Can you screenshot where the error occurs?

(I don't have access to a machine with IE9, and I'd rather not debug using browserstack).

Thank you!

**Comment by micwc** [comment]
![image](https://cloud.githubusercontent.com/assets/16586417/12162035/f964748a-b4ca-11e5-8574-c62f1a7739f1.png)

version 1.3.1
fo.setProperty=function(t,e,r){po.call(this,t,e+"",r)}

let me know if more info is needed, thanks

**Comment by micwc** [comment]
![image](https://cloud.githubusercontent.com/assets/16586417/12162211/ae4d790e-b4cc-11e5-9ce3-5b826114370d.png)

let me know if more info is needed, thanks

**Comment by etpinard** [comment]
@micwc Could paste a screenshot of the callstack leading to the error?

Thank you very much!

**Comment by micwc** [comment]
![image](https://cloud.githubusercontent.com/assets/16586417/12162395/647f6aaa-b4cf-11e5-99cb-cb37fa5130da.png)

![image](https://cloud.githubusercontent.com/assets/16586417/12162402/86d1ae42-b4cf-11e5-9d24-98242eda2d56.png)

![image](https://cloud.githubusercontent.com/assets/16586417/12162427/f50cbae6-b4cf-11e5-930f-2ee4d0eb04c1.png)

**Comment by etpinard** [comment]
@micwc thanks!

This line https://github.com/plotly/plotly.js/blob/master/src/components/legend/index.js#L465 see a little strange.

Perhaps changing it to:

![image](https://cloud.githubusercontent.com/assets/6675409/12162534/8d73d8f4-b4d1-11e5-9f85-e227afa815c5.png)

could fix it.

**Comment by micwc** [comment]
I tried this, but it came back with the same error

**Comment by etpinard** [comment]
@micwc arrg.

I'll take your word on it and mark this as a bug.

Unfortunately, no plotly.js full-time member will have the time to work on this in the next days.

**Comment by WardLootens** [comment]
I stumbled upon the same error. Of course I'm not sure the cause is the same, but in my case the value of the _value_ parameter passed to d3_style_setProperty.call was _NaNpx_ (and _name_ was _#stroke-width_). I could fix this by explictly adding _marker.line.width_ option to my traces.
e.g.
```
marker: {
	color : 'green',
	line: {width: 0} // should be there, to make it work in IE9 :-)
}, 
```

Hope this can be of any help...

**Comment by n-riesco** [comment]
I reckon is caused by [this line](https://github.com/plotly/plotly.js/blob/master/src/components/drawing/index.js#L257). It should look like [line above](https://github.com/plotly/plotly.js/blob/master/src/components/drawing/index.js#L252).

@WardLootens I don't have access to IE9, would you be able to check if replacing `lineWidth` with `(lineWidth||1)` fixes the problem for you?

**Comment by WardLootens** [comment]
@n-riesco 
I replaced this, but this was not enough :-) Same error occured at other point in the callstack.
I got it working by additionally changing
[this line](https://github.com/plotly/plotly.js/blob/master/src/components/legend/style.js#L177) and [this line](https://github.com/plotly/plotly.js/blob/master/src/traces/bar/style.js#L60).

FYI, I'm testing IE9 with Virtual Machine images downloaded from http://modern.ie

**Comment by n-riesco** [comment]
@WardLootens Thx for the link.

Do you have a small test case I can use to reproduce the problem?
I would like to understand why `marker.line.width` hasn't been coerced to its default value.

**Comment by WardLootens** [comment]
Here you go: https://jsfiddle.net/plotlygraphs/gqdme3r2/4/

**Comment by n-riesco** [comment]
Really??? I had imagined this issue to be some corner case.

**Comment by WardLootens** [comment]
Aawch, I pasted the wrong link... I edited the above message with the [correct one](https://jsfiddle.net/wardlootens/gqdme3r2/5/)

**Comment by cliffxuan** [comment]
i can confirm that i can reproduce the same problem.

**Comment by dfcreative** [comment]
Having TypedArrays polyfilled, I don’t get any errors with the example in IE9 nor IE10.
I used [typedarray](https://github.com/substack/typedarray) to polyfill them:
```js
var typed = require('typedarray');
for (var c in typed) {
  if (!window[c]) window[c] = typed[c];
}
```
But if you are unfamiliar with browserify, [this polyfill](https://raw.githubusercontent.com/inexorabletash/polyfill/master/typedarray.js) can be used:
```html
<!--[if gte IE 9]>
    <script src="typedarray-polyfill.js"></script>
<![endif]-->
```

**Comment by alexcjohnson** [comment]
Pretty sure #1332 fixes this - but please reopen if this or related problems persist.
