### ISSUE TITLE
Sankey hover labels misaligned when the plot isn't in the corner of the page?

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#1662]
If I load a sankey diagram in the test dashboard - where plots are drawn on the left edge of the page but not at the top - I see hover labels misaligned with the links:

![screen shot 2017-05-10 at 1 09 53 pm](https://cloud.githubusercontent.com/assets/2678795/25911704/d9f8a000-3582-11e7-865c-948c8496c3dd.png)

To reproduce: `npm start` from the plotlyjs repo root, then go to eg http://localhost:3000/devtools/test_dashboard/#sankey_energy

cc @monfera

**Comment by etpinard** [comment]
Blocking or not for `1.27.0`?

**Comment by alexcjohnson** [comment]
yes, blocking `1.27.0` IMO

**Comment by etpinard** [comment]
@monfera can I help with anything?

**Comment by monfera** [comment]
@etpinard thanks a lot, done: https://github.com/plotly/plotly.js/issues/1664

**Comment by etpinard** [comment]
closed by https://github.com/plotly/plotly.js/pull/1664
