### ISSUE TITLE
hoverlabel.opacity

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#1665]
Sometimes you'd like to be able to see behind hover labels. We *could* do this by supporting `rgba` colors in hoverlabel styles, but it seems easier - and better, for the same reason that we have `marker.opacity` - to make a `hoverlabel.opacity` setting that affects the whole group as a unit.

As discussed in https://github.com/plotly/plotly.js/pull/1582#discussion_r115631554

**Comment by etpinard** [comment]
merged with https://github.com/plotly/plotly.js/issues/2342
