### ISSUE TITLE
Filter transform doesn't restore data text

### ISSUE THREAD

**Issue by n-riesco** [plotly/plotly.js#1666]
I'm using filter transforms to hide and show points in a trace. These points have a `text` and I've noticed that in some cases when I unhide a point, its `text` isn't displayed.

Here's a [codepen](http://codepen.io/n-riesco/pen/aWqXWa) reproducing the issue.

![peek 2017-05-10 18-58](https://cloud.githubusercontent.com/assets/6199391/25913526/f4f539c4-35b2-11e7-9c58-4bf65e6d102b.gif)

**Comment by etpinard** [comment]
Interesting. Thanks for the report @n-riesco !

I can replicate the problem on `master`. By inspecting `fullData` and `calcdata`, the filter transform appear to do the _right thing_. Something must be up in the `plot` routine.

**Comment by etpinard** [comment]
OK. I found the problem. When a filter transform filters out all items in data arrays the resulting `fullData` items is inconsistent with what the plot step except. More precisely, filter transforms allows for `fullData` items containing:

```js
x: [],
y: [],
visible: true
```
whereas (all) other plotly code paths force `visible: false` whenever blank coordinates are found.

In details, logging `x`, `y` and `visible` in `fullData` after `restyle(gd, 'transforms', /* */`)` call gives:

![peek 2017-05-10 17-50](https://cloud.githubusercontent.com/assets/6675409/25922930/23142ea0-35a9-11e7-9873-d7e04639458a.gif)

Luckily the marker points appear to update correctly when `x` and `y` are blank. No luck for the text point nodes though. But, we should **not** rely on the plot step knowing what to do with blank `x` / `y` arrays. Instead we should make sure the filter transform forces in `visible: false`. Perhaps we should call `Plots.supplyDefaults` after the calc transform is applied (probably an overkill)?

--- 

In brief @n-riesco , one workaround would have your toggle buttons never reach that `transform.target = [0, 0, 0]` state. In the case, the restyle command should be `restyle(gd, 'visible', false)`.

**Comment by n-riesco** [comment]
@etpinard How about `filter` transforms setting `visible` to `false` whenever they result in an empty trace? Would that fix the issue?
