### ISSUE TITLE
Hover broken if plotDiv has a css transform (other than a translation)

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#1667]
If the page transforms the `plotDiv` element with a scale, rotation, or matrix, any call to `getBoundingClientRect` on an element within that div gives us misleading results and breaks hover effects. Certain `getBoundingClientRect` calls are necessary to find text sizing, but this should always be called on elements in `gd._tester`, which we attach directly to `<body>`, far off-screen. We should get rid of all other `getBoundingClientRect` calls. This will also be better for performance.

Calling this a bug, but we could also consider it a feature ("Add support for CSS transforms on the plotDiv and its parents")

**Comment by rreusser** [comment]
Possible duplicate of #888?

**Comment by alexcjohnson** [comment]
Ah thanks @rreusser - I'll move my comment here over there.
