### ISSUE TITLE
first and last data points in area chart are partially visible

### ISSUE THREAD

**Issue by suribabu39** [plotly/plotly.js#1671]
Hi,
For area charts first and last data points(markers) of each line are not completely visible(partially visible). Is there any way to give padding and make them completely visible.
[Codepen link](https://codepen.io/suribabu_95/pen/KmoNPM)

Thanks in advance

**Comment by etpinard** [comment]
See https://community.plot.ly/t/adjust-starting-position-for-area-plot/4043/3 

Thanks
