### ISSUE TITLE
More control over tick text alignment

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#1673]
Perhaps via `layout.axisid.tickalign` & `layout.axisid.tickvalign` -- both accepting a number on a 0-1 scale? Here's an example of `tickalign=1` (the default) vs `tickalign=0`
![screen shot 2017-05-11 at 1 30 04 pm](https://cloud.githubusercontent.com/assets/1365941/25965587/0b117ee8-364e-11e7-883c-220769a2ace4.png)
![screen shot 2017-05-11 at 1 30 27 pm](https://cloud.githubusercontent.com/assets/1365941/25965598/12815cfc-364e-11e7-952e-52e98e334e9b.png)

**Comment by bpostlethwaite** [comment]
Another use case is centering labels _between_ ticks. A request has come in to replicate this type of label positioning

![image](https://user-images.githubusercontent.com/1176674/42514990-a9cfa266-8428-11e8-9638-67203a527fe2.png)

**Comment by nicolaskruchten** [comment]
Basically here we just want a new `ticksbetweenlabels` boolean.

**Comment by alexcjohnson** [comment]
@cpsievert was talking here about how to align the tick label relative to its anchor point. I see that as a very different feature from whether the ticks and labels even *have* the same anchor point - which is the subject of #2601, lets continue the latter discussion over there.

**Comment by nicolaskruchten** [comment]
Ah you're right, sorry. @bpostlethwaite had tagged this issue so I just followed suit :)

**Comment by Braintelligence** [comment]
@nicolaskruchten Does the latest release allow `ticksbetweenlabels` for other types than `category`?

**Comment by etpinard** [comment]
No, `tickson: 'boundaries'` is only available for `'category'` and `'multicategory'` axes at the moment.

**Comment by emmanuelle** [comment]
The `ticksbetweenlabels` boolean would be really useful for heatmaps and images, in order to have ticks at the boundary between pixels.

**Comment by archmoj** [comment]
This issue would be resolved by #7006.
