### ISSUE TITLE
Annotation text not getting placed correctly on relayout when page is scrolled

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#1678]
First reported in https://community.plot.ly/t/text-move-to-wrong-position-when-scrolling-update-or-relayout-graph/4209

:sos: This is a regression `1.27.0` :sos: 

From http://codepen.io/plotly/pen/Kzjamd?editors=0011 

- make the page scrollable (e.g. by opening the codePen console)
- click on a point, get an annotation (this works)
- scroll down
- click on a point, now the annotation text nodes are misplaced
- scroll up
- click on a point, now all the annotation text nodes are placed properly

![peek 2017-05-12 10-26](https://cloud.githubusercontent.com/assets/6675409/26002419/9073f728-36fd-11e7-97b9-d8c87db62d7b.gif)

----

I can't find anything suspicious in the `1.27.0` changelog. Maybe the `Drawing` optimisations of https://github.com/plotly/plotly.js/pull/1585 are to blame?

**Comment by rreusser** [comment]
Hmm.  About the textpoint class? That could possibly have an effect on the transform/x/y properties.

**Comment by etpinard** [comment]
This regression is indeed caused by https://github.com/plotly/plotly.js/pull/1585/commits/29abb5d8ec3dea92cc71f438fffa6785463d1fb1 

I'm not sure why though. I'll try to come up with a test case.
