### ISSUE TITLE
add_pie() - svg pielayer not positioned correctly

### ISSUE THREAD

**Issue by flo12392** [plotly/plotly.js#1679]
This was initially posted in the ropensci/plotly git repository, but @cpsievert suggested to move the issue to plotly.js. [Link to issue](https://github.com/ropensci/plotly/issues/1002)

It seems that since the last update, the svg layer (class="main-svg") of the pie chart is not positioned properly. whereas previously the "pielayer" was at least as big as the svg main layer, there is now always a blank space at the top. This makes the pie much smaller than it could be. See the attached image for an example (added axis to improve the example).

[http://oi65.tinypic.com/2ylpes4.jpg](http://oi65.tinypic.com/2ylpes4.jpg)
[http://oi67.tinypic.com/21e1caq.jpg](http://oi67.tinypic.com/21e1caq.jpg)

I originally included R code to create a representative example, codepen for JS made by @cpsievert attached:

[codepen](https://codepen.io/cpsievert/pen/XRqjzX)

**Comment by etpinard** [comment]
@cpsievert what version of plotly.js this is? I can't replicate / understand this report.

**Comment by flo12392** [comment]
Sorry, maybe it is confusing that I attached both the R and the codepen example. Please only look at the following codepen and images:

[codepen](https://codepen.io/cpsievert/pen/XRqjzX)
[Example images](https://drive.google.com/drive/folders/0ByGbN6t9KhP_akVfejctdVE1M28?usp=sharing)

The pie chart is not using all the available space. This seems to me as unexpected behaviour, in earlier versions of plotly.js I did not have this issue.

**Comment by etpinard** [comment]
> in earlier versions of plotly.js

Which version(s)?

**Comment by flo12392** [comment]
Apologies, I experimented further and this issue is really only caused by the installation of the new R package for plotly. I will report further in [https://github.com/ropensci/plotly/issues/1002](https://github.com/ropensci/plotly/issues/1002) with more details and this issue can be closed.
