### ISSUE TITLE
eventdata content consistency

### ISSUE THREAD

**Issue by aderidder** [plotly/plotly.js#168]
Hi,

In order to capture the points in my scatterplot, I'm currently using plotly_relayout. After playing around with this for a bit, I found that the eventdata is somewhat unpredictable, making it hard/confusing to work with:
- autoscale button clicked: Object {xaxis.autorange: true, yaxis.autorange: true}
- zoom button clicked: Object {xaxis.range: Array[2], yaxis.range: Array[2]}
- drag zoom: Object {xaxis.range[0]: <value>, xaxis.range[1]: <value>, yaxis.range[0]: <value>, yaxis.range[1]: <value>}
- drag zoom, but leave your plot at the left side: Object {xaxis.range[1]: <value>, yaxis.range[0]: <value>, yaxis.range[1]: <value>}
- pan: similar to drag zoom, but if you drag along an axis (e.g. don't change the y, only the x), the eventdata only contains information about the x

It would be very useful if the eventdata's content would be consistent, e.g. always provide Object {xaxis.range: Array[2], yaxis.range: Array[2]}

Thanks,
Sander

**Comment by etpinard** [comment]
@aderidder great suggestion. Thanks!

The `plotly_relayout` is in dire need of a redesign. Maybe the solution lies in https://github.com/plotly/plotly.js/issues/145 where *axis* each interaction would emit an event with a similar data object.

**Comment by chrisgervang** [comment]
It appears the rangeslider pan and zoom is consistently `{xaxis.range: Array[2], yaxis.range: Array[2]}`. So to handle relayout event I now do this:

```
const newSliderRange: [number, number] = e['xaxis.range']; //Plotly format for zooming with the slider
const newZoomRange: [number, number] = [e['xaxis.range[0]'], e['xaxis.range[1]']]; //Plotly format for zooming within the graph

const newRange = !!newZoomRange[0] || !!newZoomRange[1] ? newZoomRange : newSliderRange;
console.log("EVENT", e, newRange);
```

**Comment by jackparmer** [comment]
Hiya! Plotly now has improved and consolidated Plotly.js event documentation here:

https://plot.ly/javascript/plotlyjs-events/

Please feel free to suggest documentation improvements in a pull request:

https://github.com/plotly/documentation/tree/source-design-merge/_posts/plotly_js/events

**Comment by etpinard** [comment]
Pie and Sankey event data should be refactor during the v2 push to look more like the other traces.

See https://github.com/plotly/plotly.js/issues/1875

**Comment by JacobJNilsson** [comment]
Hi, not sure if this is the right place to bring this up, please feel free to remove this if this is not the propper channel.
Today the update information of plotly_relayout only contain the y and x axis.autorange: bool, but should not the axis range also be included? Such as in the case of other resizing updates.
