### ISSUE TITLE
Inconsistent axis anchoring behavior in scattergl

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#1680]
https://codepen.io/cpsievert/pen/xdjgXo

Change the trace type to "scatter" (in both traces) -- the yanchor of the xaxis changes

**Comment by etpinard** [comment]
I'm impress that anything subplot related works in gl2d.

It's definitely **not** a good idea to use subplots in gl2d at the moment.

**Comment by etpinard** [comment]
related to https://github.com/plotly/plotly.js/issues/1200

**Comment by etpinard** [comment]
Will be fixed by @dfcreative 's regl-based `scattergl` work :tada:

**Comment by dfcreative** [comment]
https://github.com/plotly/plotly.js/commit/4c22e0cc0af252820bdea147571fbe89ba3dd52f adds mock test

**Comment by etpinard** [comment]
done in #2258
