### ISSUE TITLE
Bug: histogram silently ignores data, when bin size is too small

### ISSUE THREAD

**Issue by cnowzohour** [plotly/plotly.js#1682]
When plotting histograms with very fine grained bins, some data will be ignored. See:

https://codepen.io/cnowzohour/pen/qmYmoM

vs

https://codepen.io/cnowzohour/pen/vmjmjM

Both histograms should show 10 bars, but the second one only shows 5 - the only difference being the bin size of 0.005 vs 0.001.

I realized this when visualizing timestamps over one day with a bin size of 10 seconds:

https://github.com/ropensci/plotly/issues/1001

**Comment by etpinard** [comment]
Thanks for the report. Looks like this hard-coded [5000](https://github.com/plotly/plotly.js/blob/6653e71d79313627194628e6d2e41308ac7deca8/src/traces/histogram/calc.js#L109) bin limit is the culprit. For example, bumping that number to 50000 yields:

![image](https://cloud.githubusercontent.com/assets/6675409/26017167/430b22fc-3736-11e7-8abb-893866f00403.png)

as desired.

We should come up with a better upper bound. Maybe something like `x.length / bins.size`?

**Comment by cnowzohour** [comment]
Yeah I guess 5000 can be a bit conservative in cases when the data is sparse and only a small subset of the bins are actually drawn. Also, it would be great if it was somehow visible if this limit is exceeded (and data is omitted). Maybe via a big last bin, containing all the remaining data?

**Comment by etpinard** [comment]
Update: changing the while clause from

```js
while(i < binend && pos.length < 5000) {}
```

to 

```js
while(i < binend && pos.length < (pos0.length / bins.size)) {}
```

breaks some of our tests. We'll have to dig deeper to find a solution.
