### ISSUE TITLE
vertexcolor for mesh3d plot does not seem to work

### ISSUE THREAD

**Issue by precisesimulation** [plotly/plotly.js#1684]
Experimenting with the [tetrahedron codepen](http://codepen.io/plotly/pen/xOOamN) setting the vertexcolor property does not seem to work, facecolor though works as expected.

```js
var data = [{
    type: "mesh3d",
    opacity:0.7,
    x: [0, 1, 2, 0],
    y: [0, 0, 1, 2],
    z: [0, 2, 0, 1],
    i: [0, 0, 0, 1],
    j: [1, 2, 3, 2],
    k: [2, 3, 1, 3],
    // color:'rgb(200,100,300)',
    // facecolor: [ 'rgb(255, 0, 0)', 'rgb(0, 0, 255)', 'rgb(0, 255, 0)', 'rgb(255, 255, 255)' ],
    vertexcolor: [ 'rgb(255, 0, 0)', 'rgb(0, 0, 255)', 'rgb(0, 255, 0)', 'rgb(255, 255, 255)' ],
}
           ];

Plotly.plot('myDiv', data, {});
```

**Comment by etpinard** [comment]
Thanks very much for the report. Here's the 1-letter [patch](https://github.com/plotly/plotly.js/pull/1686/commits/c28320ec3d2e8139672a07d1ff05c869c0c1aa49) that fixes this.
