### ISSUE TITLE
select / deselect events and lasso for mapboxgl maps

### ISSUE THREAD

**Issue by jackparmer** [plotly/plotly.js#1696]
Part of the [crossfilter project](https://github.com/plotly/plotly.js/issues/1316)

Plotly's mapboxgl maps (like the one below) need a lasso in the modebar and select/deselect events like Plotly's SVG scatter trace type:

![image](https://cloud.githubusercontent.com/assets/1865834/26177122/78336c52-3b26-11e7-9af2-5bee887112d0.png)

**Comment by etpinard** [comment]
duplicate of https://github.com/plotly/plotly.js/issues/1402

@jackparmer could you close whichever issue you like the least? Thanks.

**Comment by jackparmer** [comment]
Ah, whoopsee, closing this one.
