### ISSUE TITLE
Can't set longitude range between [160, -160]

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.js#1698]
Trying to center a scatter map around Fiji. I want the longitude to be between 140 and -140, like this image (I manually zoomed and panned to focus here)

![image](https://cloud.githubusercontent.com/assets/1280389/26181706/399e3f52-3b40-11e7-8ee0-ada17e7e1022.png)

Setting the longitude range to `[140, -140]` does not seem to work. I've also tried rolling over with `[140, 220]` to no avail. Here is a Codepen: https://codepen.io/chriddyp/pen/OmovzL?editors=1010. Here is a graph in the chart editor: https://plot.ly/create/?fid=chris:18383

🎩  tip to @jackparmer who originally discovered this.

**Comment by etpinard** [comment]
Looks like all custom `lonaxis` ranges that cross the antimeridian (where lon = -180 = 360) are broken.

This might be a good reason to start using d3 v4's [`d3-geo`](https://github.com/d3/d3-geo) module which ships with a [`fitExtent`](https://github.com/d3/d3-geo#projection_fitExtent) method that probably does a better [job](https://github.com/d3/d3-geo/blob/2c51b71d55eb68c4f571b06c92ea502342975849/src/projection/fit.js) than my ad hoc [attempt](https://github.com/plotly/plotly.js/blob/master/src/plots/geo/set_scale.js).

**Comment by etpinard** [comment]
@chriddyp I found a way to make this work without waiting for a patch:

- set `projection.rotation.lon` to `-180` (or `180`) - the algo which sets its default is off currently
- set `lonaxis.range` to `[140, 220]` - the `[140, -140]` does not work.
- see https://codepen.io/etpinard/pen/pWgWLv?editors=0010

**Comment by chriddyp** [comment]
cc @jackparmer in case you still need to make this example ^^
