### ISSUE TITLE
R library: Big slowdown in Firefox but not in Chrome

### ISSUE THREAD

**Issue by MarkEdmondson1234** [plotly/plotly.js#17]
Hi, when I view this page: https://beta.rstudioconnect.com/mark/digitalMarketingReportSchedule/
....in Firefox it has big slowdown problems, sometimes asking to stop an unresponsive script, other times its enough that it crashes Firefox.  Even if it does load, tooltip response time is sluggish. 

The problems only appear when using plot.ly plots, not other htmlwidget libraries like dygraph.

The plots in the page are generated using this R code in an .Rmd document:

```
gadata %>% plot_ly(x = date, y = sessions, group = medium)


plot_ly(gadata[gadata$date > as.Date(Sys.Date() - 30),], 
        x = date, 
        y = transactionRevenue, group = medium, type = "bar") %>% layout(barmode="stack")
```

However the same report in Chrome has no issues, loads quickly.

I'm on OSX Yosemite 10.10.2 running Firefox 42.0

**Comment by nsmith5** [comment]
I'm having the same issue. Chrome is fine, but Firefox is sluggish for some reason. Sometimes plots load quickly, but other times they take several seconds.

Firefox 49.0 on Fedora 24

**Comment by juliusverrel** [comment]
Same here, Firefox 50.0.2, Windows 7.

**Comment by etpinard** [comment]
FF 55 performance seemed to have caught up to Chrome's.

Can anyone else confirm?

**Comment by MarkEdmondson1234** [comment]
My example above is usable now, so good for me.

**Comment by etpinard** [comment]
Ok great. As this ticket won't directly result in a PR, I'll close it.

Thanks for checking @MarkEdmondson1234 :tada:
