### ISSUE TITLE
Label color in legend

### ISSUE THREAD

**Issue by collioud** [plotly/plotly.js#1701]
Hi,

It would be nice to have an option to automatically set the legend label to the color of the corresponding marker.

For example, amCharts is using a parameter named 'useMarkerColorForLabels' in the config object.
![capture](https://cloud.githubusercontent.com/assets/3032757/26207623/600b3980-3be8-11e7-9f61-3ec84830b37e.jpg)

Thanks in advance!

**Comment by etpinard** [comment]
That would be nice. I would prefer this being part of more general legend item style attributes then a one-off boolean, but oh well.

Here's a workaround, in the meantime: https://codepen.io/etpinard/pen/ybRyVp?editors=0010

**Comment by collioud** [comment]
Thanks!
Indeed, HTML styling can do the job failrly well.

Cheers

**Comment by rpaskowitz** [comment]
I've got a quick branch with this, currently implementing a `legend.fontColorStyle` attribute with values of `default` for current behaviour, which reads from `legend.font`, or `trace` which takes the trace color (needs a bit of work to match the same logic as in `style.js`).

On other place I thought to put this would be on the trace data itself. It could be set to `default` to use the legend's default, set to a custom color, which is ultimately flexible, in case of complicated markers/lines/fills and would let people set to whatever they like, or could use a `trace` color, for the case where they have not set trace colors themselves and plotly has assigned automatically.

A couple examples of the current work (pretty much what you'd expect):
![image](https://user-images.githubusercontent.com/1222909/31530567-4e570058-af96-11e7-8367-c7b374fc5651.png)
![image](https://user-images.githubusercontent.com/1222909/31530576-60a15a42-af96-11e7-977f-c3e68af19137.png)

**Comment by etpinard** [comment]
> currently implementing a legend.fontColorStyle attribute

That could work. But I would prefer putting these options in a trace attribute container that way it would be compatible with other legend item styling feature requests (e.g. https://github.com/plotly/plotly.js/issues/2080). For example,

```js
{
  x: [/* */],
  y: [/* */],
  legenditem: {
    textfont: {
       color: 'red'
     },
     marker: {
       size: 20 // see https://github.com/plotly/plotly.js/issues/2080
     }
  }
}
```

----

But then again, maybe this is the wrong approach altogether. @alexcjohnson thinks that legend items should be special version of annotations.

**Comment by Melmoth-the-Wanderer** [comment]
Just wanted to add one thought to the discussion. It would be nice to make it possible to change text of the labels (so it can be something different than data name), not just fonts/colors/sizes.

Maybe it's good idea to move legend options from traces to layout (?) object, something like: 
```
{
   legendItems: [{
       text: "Group name 1",
       traces: [1, 3, 4],
       style: { /* textFont, marker, etc */ }
   },{
       text: "Group name 1",
       traces: [0, 2, 5],
       style: { /* textFont, marker, etc */ }  
   }]
}
```


This would also allow us to create a 'group' of certain data items as a single item on the legend. Not just visually (like current legendgroup property on a trace), but physically displayed as one label on legend. 
I think disconnecting legend settings from trace object should also make legend more flexible and easier to maintain - no need to track group names on trace obect etc. How do you feel about that, @etpinard ?

**Comment by p2ya** [comment]
Is there any solution for this ? 
I have a chart as attached and I need to manually set the legend colors.
This is generated by using:

trace=[]
for colname, col in statusCountSorted[1:-1].iteritems():
    
    trace.append(go.Bar(x=statusCountSorted.index, y=statusCountSorted[colname][0:-1],opacity=0.6,name=colname))

layout = go.Layout(
    autosize=False,
    width=800,
    height=400,
    barmode='stack',
    title = 'Top '+str(topCommonCount)+' common issues from '+horizonStartDate+' to ' + endDate,
    margin=go.Margin(
        l=50,
        r=50,
        b=150,
        t=50,
        pad=0
    ))

![topcommonissues](https://user-images.githubusercontent.com/17534393/33354849-f6525fb8-d508-11e7-83ee-60a262b493ff.png)

**Comment by etpinard** [comment]
> Is there any solution for this ?

Yes. See https://github.com/plotly/plotly.js/issues/1701#issuecomment-302436793

**Comment by p2ya** [comment]
@etpinard how can I implement your suggestion into my code ? it looks like it is a bit different

**Comment by etpinard** [comment]
> it looks like it is a bit different

Probably best to use https://community.plot.ly/ for questions of the likes.

**Comment by etpinard** [comment]
Now in https://github.com/plotly/plotly.js/issues/3735
