### ISSUE TITLE
Parallel coordinates plot axes labels overlap

### ISSUE THREAD

**Issue by kernc** [plotly/plotly.js#1703]
On parallel coordinate plot, axes labels overlap when the text is too long, font too large, or there are too many dimensions for given canvas width.

CodePen example: https://codepen.io/anon/pen/LygNGG

A short proposed solution, please have a look at **PR** https://github.com/kernc/plotly.js/pull/1

![screenshot - 05182017 - 07 49 37 pm](https://cloud.githubusercontent.com/assets/684364/26216098/2a5f3190-3c03-11e7-8e06-fc35371b9420.png)

Slightly related: https://github.com/plotly/plotly.js/issues/511

**Comment by etpinard** [comment]
See https://github.com/plotly/plotly.js/pull/1256 for other known limitations.

**Comment by kernc** [comment]
I reviewed the thread. What do you mean by other limitations?

**Comment by etpinard** [comment]
The unchecked boxes:

![image](https://cloud.githubusercontent.com/assets/6675409/26222368/b8885602-3be7-11e7-995f-1eae8c5ec23f.png)

**Comment by kernc** [comment]
Well, the [proposed PR](https://github.com/kernc/plotly.js/pull/1) checks the first item by an _"other way of avoiding overlap"_. 😃 Would you prefer the labels slanted?

**Comment by etpinard** [comment]
> Would you prefer the labels slanted?

Whatever `parcoods` prince @monfera prefers.

**Comment by bhvbhushan** [comment]
@kernc were you able to resolve the issue, with the possible solution that @monfera mentioned [here](https://github.com/plotly/plotly.js/pull/1857#issuecomment-313492943).
If yes, could you please share here. It would be really helpful.

Thanks

**Comment by harishr1308** [comment]
Hi @bhvbhushan, has this been merged? Or, is there any other way to resolve the overlap. Perhaps, having the text on multiple lines?

Thanks

**Comment by javdev** [comment]
we had the same problem, slanting sucks a bit, cause it needs a lot of space. Wouldn't it be a simple idea, to make two lines for the labels and every second label is put in the bottom line?

**Comment by javdev** [comment]
I could do this myself, just adding a newline to half of the labels on at the end and a newline to the other half at the beginning of the labeltext, but the newline gets removed, as it seems. If it only would get trimmed, I could add a little dot, but it gets really removed

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
