### ISSUE TITLE
Data ids interfere with transforms

### ISSUE THREAD

**Issue by n-riesco** [plotly/plotly.js#1706]
[This code](http://codepen.io/n-riesco/pen/MmPJYw) shows a bad interaction between data ids and transforms. The plot is made up of three bubbles sorted by marker size.

Clicking once on the button removes the circle in the middle using a filter transform.
Clicking a second time brings the circle back.
The issue is that when circle is back is drawn on top of all the circles (despite the sort transform).

![peek 2017-05-18 22-43](https://cloud.githubusercontent.com/assets/6199391/26224760/c6bfcd48-3c1b-11e7-944e-4f7383376335.gif)

**Comment by etpinard** [comment]
This [`.order()`](https://github.com/d3/d3-3.x-api-reference/blob/master/Selections.md#order) is what we want to use I think, but looks like but doing so it does break some of our tests. :confused:

**Comment by alexcjohnson** [comment]
pinging @rreusser - just to make sure this issue (and @etpinard's fix in #1709) is on your radar re: bar animations
