### ISSUE TITLE
No shape and no marker 'cross-thin' on scattergeo plot

### ISSUE THREAD

**Issue by collioud** [plotly/plotly.js#1707]
Hi,

I noticed that points with the symbol 'cross-thin' are not displayed in scattergeo plot (see codepen below). Same issue with other symbols like 'x-thin', 'line-ew', etc.

[https://codepen.io/anon/pen/MmPXER?editors=0010](https://codepen.io/anon/pen/MmPXER?editors=0010)

BTW, I am trying to draw lines and circles on a scattergeo plot, without success. Is it even possible ?

Thank you!

**Comment by etpinard** [comment]
Oh, you scared me for a moment. 

The markers are there, they're just _very very_ small with the default `marker.line.width` value. In https://codepen.io/etpinard/pen/xdQKLb?editors=0010, `marker.line.width` is set to 2 making the markers visible :tada: . For the record, the same odd behavior happens for `scatter` traces, see https://codepen.io/etpinard/pen/qmQWjO?editors=0010

Perhaps we should set a better `marker.line.width` default value when users specify a `-thin` marker symbol? Oh well, we'll put that on the [`v2`](https://github.com/plotly/plotly.js/issues/420) shelve (cc @alexcjohnson).

--- 

As for the shapes, data-referenced shapes / annotations / images aren't supported for `geo` subplots. That is, you can't drawn a shape on a map that will drag along with the map on pan and zoom. But you can drawn paper-referenced shapes by switching  those `xref` and `yref` value to `'paper'` as in https://codepen.io/etpinard/pen/bWQbLM?editors=0010. The shapes here sit on top of the map and are static.

We're about to implement data-referenced annotations for 3D subplot in https://github.com/plotly/plotly.js/pull/1638, but the `geo` implementation isn't on our short-term priority list unfortunately.

**Comment by collioud** [comment]
Thanks for these explanations!

For the 'thin' markers, I supposed changing the marker size would make it more visible. I was not aware of the marker.line propery...

Well, it is too bad not to be able to add geo-referenced shapes or annotations. For example, I am displaying on a map data points around a given position with a specified radius of search. In this case, it would have been so useful to display the maximum extent of search by a (projected) circle.

>  ...but the geo implementation isn't on our short-term priority list unfortunately.

No problem, I know this will not an easy task to add this...

Cheers!

**Comment by emmanuelle** [comment]
This issue was again mentioned in https://community.plot.ly/t/x-thin-marker-symbol/31356/3, changing the default could be a good idea.
