### ISSUE TITLE
zmin and zmax properties not implemented for mesh3d types colorbar

### ISSUE THREAD

**Issue by precisesimulation** [plotly/plotly.js#1710]
Perhaps just a copy paste bug, but according to:

https://plot.ly/javascript/reference/#mesh3d-colorscale

the mesh3d colorbar should be able to be controlled with the zmin and zmax properties, however no such properties are available.

Also it seems the colorbar is attached to the z value which doesn't seem to be possible to change or general. Seems to me that having the colorbar correlate to the intensity field would make more sense where one could then attach any value one wants (x, y, z, or some other value).

**Comment by etpinard** [comment]
Thanks very much for pointing this out.

`gl-mesh3d` will need to patched in a similar manner to `gl-surface3d` in PR https://github.com/gl-vis/gl-surface3d/pull/7
