### ISSUE TITLE
Category-type x-axis out of order

### ISSUE THREAD

**Issue by TMiguelT** [plotly/plotly.js#1712]
Consider the following code. In the data there are 6 categorical X values, but the first series only has values for 3 of them.
```python
import plotly.offline as py
import plotly.graph_objs as go

fig = go.Figure(data=[
    go.Scatter(
        x=['a', 'b', 'f'],
        y=[3, 4,  5],
    ),
    go.Scatter(
        x=['a', 'b', 'c', 'd', 'e', 'f'],
        y=[1, 2, 3, 4, 5, 6],
    )
])

py.plot(fig, filename='plot.html')
```
This generates the following plot, where the categories are out of order, causing the lines to double back on themselves:
![image](https://cloud.githubusercontent.com/assets/5019367/26292677/42ba5ad0-3efb-11e7-924b-963dd5567ef2.png)

It seems that the order of the categories is determined from the first series, not the most complete series. Is there some way of specifying a correct order for the x-axis? Is this a bug?

**Comment by TMiguelT** [comment]
One workaround to this issue is to either re-order the series so that the most complete series is first:
```python
import plotly.offline as py
import plotly.graph_objs as go

fig = go.Figure(data=[
    go.Scatter(
        x=['a', 'b', 'c', 'd', 'e', 'f'],
        y=[1, 2, 3, 4, 5, 6],
    ),
    go.Scatter(
        x=['a', 'b', 'f'],
        y=[3, 4,  5],
    )
])

py.plot(fig, filename='plot.html')
```
![image](https://cloud.githubusercontent.com/assets/5019367/26292781/1845577c-3efc-11e7-95e9-9d773ff6f84b.png)


Another workaround is to fill in `None`/`null` values wherever a series is missing data (although this stops the `'b'` and `'f'` data points from being connected:
 ```python
import plotly.offline as py
import plotly.graph_objs as go

fig = go.Figure(data=[
    go.Scatter(
        x=['a', 'b', 'c', 'd', 'e', 'f'],
        y=[3, 4, None, None, None, 5],
    ),
    go.Scatter(
        x=['a', 'b', 'c', 'd', 'e', 'f'],
        y=[1, 2, 3, 4, 5, 6],
    )
])

py.plot(fig, filename='plot.html')
```
![image](https://cloud.githubusercontent.com/assets/5019367/26292776/0964d156-3efc-11e7-9725-bf8f78a53a45.png)

**Comment by n-riesco** [comment]
`categoryarray` lets you set the order in cat axis.

See [this codepen](http://codepen.io/etpinard/pen/NjyOXp).

**Comment by TMiguelT** [comment]
Looks like that solves it!
