### ISSUE TITLE
Wrong fullData passed `plotly_click` listeners after zoom

### ISSUE THREAD

**Issue by n-riesco** [plotly/plotly.js#1713]
The object `plotlyEvent` passed to a listener to `plotly_click` events contains amongst other the properties:
- `plotlyEvent.points[0].data` = trace before transforms
- `plotlyEvent.points[0].fullData` = trace after transforms

This [codepen](http://codepen.io/n-riesco/pen/JNwJgr) shows a chart with a `sort` transform that reorders the circles from `A, B, C` to `B, C, A`. It also defines a `plotly_click` listener that outputs the order in `data` and `fullData`.

The screencast below shows how before zooming the order in `fullData` is `B, C, A` but after zooming the order changes to `A, B, C`.

![peek 2017-05-22 21-36](https://cloud.githubusercontent.com/assets/6199391/26327307/c89e2bdc-3f36-11e7-9dba-b00268438038.gif)

**Comment by etpinard** [comment]
> plotlyEvent.points[0].data = trace before transforms
> plotlyEvent.points[0].fullData = trace after transforms

That's the intended behavior - at least to my eyes. Can you elaborate on why this is a big deal for the spotlight plugin?

**Comment by n-riesco** [comment]
Before the zoom, when I click I get:
```js
plotlyEvent.points[0].data.text = ['B', 'C', 'A']
plotlyEvent.points[0].fullData.text = ['A', 'B', 'C']
```
This is expected because of the `sort` transform.

The next time I click (after zooming) I get:
```js
plotlyEvent.points[0].data.text = ['A', 'B', 'C']
plotlyEvent.points[0].fullData.text = ['A', 'B', 'C']
```
The issue is that `plotlyEvent.points[0].data.text` isn't sorted any longer.

**Comment by etpinard** [comment]
Ah I see. Thanks for pointing this out @n-riesco !

It won't be pretty, but I'll figure something out.
