### ISSUE TITLE
Plot flashes then disappears.

### ISSUE THREAD

**Issue by razed11** [plotly/plotly.js#1716]
There are two files attached. One is the HTML/JS rendered from Python. The other is the text message that appears after the plot disappears.

When the file is loaded or reloaded the plot flashes briefly and then the text message is shown.

Mac OS: 10.12.5 (Sierra)
Chrome: Version 58.0.3029.110 (64-bit)
Python Plotly: 2.0.8
Python: 2.7.13 

[full.txt.html.zip](https://github.com/plotly/plotly.js/files/1022807/full.txt.html.zip)

Text Shown:

<img width="767" alt="message" src="https://cloud.githubusercontent.com/assets/816621/26363723/beb12baa-3f96-11e7-8f09-28e29f5b0f37.png">

**Comment by rreusser** [comment]
Hmm. I have the *exact* same specs and am able to open this file:

![screen shot 2017-05-23 at 12 21 00](https://cloud.githubusercontent.com/assets/572717/26364582/d03ca55e-3fb2-11e7-962a-6e93830e9ef8.png)

Are any errors printed in the javascript console?

**Comment by razed11** [comment]
I have Markdown Preview Plus 0.6.1 installed as an extension. When disabled the file renders just fine. Thanks for the suggestion.
