### ISSUE TITLE
shapes on category axis are redrawn incorrectly after zoom

### ISSUE THREAD

**Issue by cldougl** [plotly/plotly.js#1720]
example: https://codepen.io/plotly/pen/79661cd85e9e51054039b89d096b0c9a

after zoom/relayout the vertical line is drawn as a rectangle or if `type='line'` is specified the vertical line becomes diagonal.

**Comment by etpinard** [comment]
This is a regression from `1.24.0`. 

Here's working example with `1.23.1`:
https://codepen.io/etpinard/pen/vmqEJg?editors=0010

**Comment by etpinard** [comment]
I suspect PR https://github.com/plotly/plotly.js/pull/1403

**Comment by etpinard** [comment]
Ok, well this is a pretty big problem after all. Annotations, shapes and layout image on `type: 'category'` axes are all broken after zoom, pan or any axis-range relayout calls at the moment.

Diagnostic: in [`Axes.coercePosition`](https://github.com/plotly/plotly.js/blob/a0f833387c0c1a06b234a0b4f026e40a0f867dbc/src/plots/cartesian/axes.js#L117) we attempt to use `ax._categories` to convert string category positions to category indices. Note that, `ax._categories` isn't filled (nor relinked) at that point in [`Plots.supplyDefaults`](https://github.com/plotly/plotly.js/blob/a0f833387c0c1a06b234a0b4f026e40a0f867dbc/src/plots/plots.js#L476). To go around that, annotations, shapes and images defaults are called a second time during [`Plotly.doCalcdata`](https://github.com/plotly/plotly.js/blob/a0f833387c0c1a06b234a0b4f026e40a0f867dbc/src/plots/plots.js#L2112) if `type: 'category'` axes are detected. At this point `ax_.categories` is set, but `Plots.doCalcdata` isn't called on all updates (e.g. not on pan/zoom) whereas `Plotly.supplyDefaults` leading to bad coordinates values in `fullLayout` propagating to the `draw` methods after pan/zoom interactions.

Before PR #1403, annotations and shape [used](https://github.com/plotly/plotly.js/pull/1403/files#diff-05274991eb85aefd482f72514dbda1a5L246) to redo their defaults in their `drawOne` respective methods. We could revert to doing something like that, but we can do better I think. 

In [`component-category-axes-relayout-attempt`](https://github.com/plotly/plotly.js/compare/component-category-axes-relayout-attempt), I propose removing logic involving `ax._categories` from `Axes.coercePosition` (as `ax._categories` can't be relied upon at the defaults step) and instead redefining what `r` (short for ranges) axes conversions methods means for category axes. 

@alexcjohnson what do you think before I go any further?

**Comment by sb0007** [comment]
shapes are still broken on category axis... is this yet to be fixed?
