### ISSUE TITLE
Axis labels for scattergl do not rotate

### ISSUE THREAD

**Issue by tanz2** [plotly/plotly.js#1738]
Axis labels for scattergl type graphs do not rotate, causing them to overlap with each other.

codepen: https://codepen.io/Person21/pen/mmgjaR

Is it possible to get them to auto-rotate like how it works in the nongl version?

**Comment by etpinard** [comment]
Thanks for the report

Here's a workaround in the meantime: https://codepen.io/etpinard/pen/RVmXYZ?editors=0010

**Comment by etpinard** [comment]
will be fixed by @dfcreative 's regl-based `scattergl` work :tada: :

![image](https://user-images.githubusercontent.com/6675409/34686722-7b081942-f47a-11e7-82a6-b5ff3c6fbb3d.png)

**Comment by dfcreative** [comment]
Added axes labels mock in https://github.com/plotly/plotly.js/commit/9cfef66ba05605a8279280afcb01e94ce61e8f0d

![image](https://user-images.githubusercontent.com/300067/34991358-63caca3e-fada-11e7-840c-8adf34b561ac.png)

**Comment by etpinard** [comment]
fixed with https://github.com/plotly/plotly.js/pull/2258
