### ISSUE TITLE
Multiple groupby transforms ignores the second and unsets trace names

### ISSUE THREAD

**Issue by rreusser** [plotly/plotly.js#1742]
See: https://codepen.io/rsreusser/pen/QvXWWE?editors=0010

Either groupby independently produces the expected result, but *both* groupby transforms seems to only have the effect of unsetting the group name. Perhaps multiple groupby transforms should be explicitly forbidden and the second one ignored. It seems *logically* trivial to merge all groupby transforms but not straightforward to merge the style options, and the fact that it's not really meaningful to separate them means maybe it should just be explicitly forbidden.

**Comment by jackparmer** [comment]
👍  Explicitly forbidden from me - we never had a chained groupby use case in WS1 as far as I can recall.

**Comment by etpinard** [comment]
Thanks for pointing this out @rreusser !

**Comment by rreusser** [comment]
Cool. I can work through this since I'm already in the groupby code. Is the right answer then to set every groupby after the first to `enabled: false`?

**Comment by etpinard** [comment]
> Is the right answer then to set every groupby after the first enabled groupby to enabled: false?

Yeah, that works.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
