### ISSUE TITLE
Relative date on x-axis

### ISSUE THREAD

**Issue by Romainpetit** [plotly/plotly.js#1744]
**Problem**
I'm using plotly to display timed data, but here the exact date is of no importance, only the relative time between the values is. I'm wondering if there is any existing setting about this.

For the moment, I get this result with `tickmode: 'auto', type: 'date'`
![image](https://cloud.githubusercontent.com/assets/632197/26582417/604cd112-4541-11e7-9e70-a9b9dff9ca52.png)
![image](https://cloud.githubusercontent.com/assets/632197/26582955/5d5f5536-4543-11e7-8169-64d448f6f0a5.png)

**Wish**
I'd like to set my first point as the zero, and then have all other times relative to it. 
The tick would display the time **relatively to this first date** : 
![image](https://cloud.githubusercontent.com/assets/632197/26582618/27eb0a0e-4542-11e7-83b1-dc37fc4be718.png)
![image](https://cloud.githubusercontent.com/assets/632197/26583134/437ebd72-4544-11e7-9b86-6653b93e336f.png)

Since I'll be displaying various data of different time scales, `tickformat` is of little help. I'd need an automatic date formatter with **customizable format settings**.

This is related to this debate on the pertinence of this automatic date format:  https://github.com/plotly/plotly.js/issues/99

Any help appreciated!

**Comment by etpinard** [comment]
That's an interesting proposition. I've never came across a special _relative_ time format in other graphing library. @Romainpetit Does that exist anywhere else?

In your case (in JS at least), it would be pretty to convert your `x` coordinates to milliseconds (i.e with `new Date().getTime()`) from that base time step.

**Comment by Romainpetit** [comment]
I don't know a graphing library that offers such a relative time in its options @etpinard. 
This specific point is manageable tough: I can process my data in milliseconds by substracting the first point's timestamp to all points values, like you said.

Now with this relative timing in ms, 
- In plotly, I can display it telling `xaxis` to use `type: 'linear'`: that will display it as a quantity unit. I can have the `s` unit display with `ticksuffix: "s"` and try to have some formatting for large number with `tickformat`. But still, we're only showing seconds. 
- In an environment where I have more control, I can use a JS time formatting library like moment.js or dateformat.js to render this time in ms to time-formatted data: `ms`, `s`, `h`, `day` ...

Other option seems to be to dig in the `formatTime()`, `ms2DateTimeLocal()` or `formatTime()` functions in plotly's `dates.js` file, to get a well-formatted time output that fits my needs.

**Comment by etpinard** [comment]
> In plotly, I can display it telling xaxis to use type: 'linear': that will display it as a quantity unit. I can have the s unit display with ticksuffix: "s" and try to have some formatting for large number with tickformat. But still, we're only showing seconds.

You can also try `tickvals` / `ticktext` to customize your axis labels (see example https://codepen.io/etpinard/pen/YWEdJX?editors=0010). This might not behave as desired on zoom, but it should get you close to what you want.

**Comment by etpinard** [comment]
This ticket won't directly result in a PR, so I'll close it.

Thanks for writing in @Romainpetit
