### ISSUE TITLE
Allow users to limit x/y coordinates visible on pan/zoom

### ISSUE THREAD

**Issue by Alanocallaghan** [plotly/plotly.js#1746]
I realise this is a tricky ask, but would it be possible to set "hard" limits for the x and y axes of a plot, such that users could not pan (or zoom, though that might be trickier) to areas beyond it?

**Comment by etpinard** [comment]
duplicate of https://github.com/plotly/plotly.js/issues/887

**Comment by Alanocallaghan** [comment]
Cheers I had a quick search but couldn't find one, sorry for the duplicate

**Comment by etpinard** [comment]
@Alanocallaghan no worries. Searching for previous issues on Github can be a bit of pain. 

Thanks for writing in :beers:

**Comment by samuelnimi** [comment]
I have the same question?
