### ISSUE TITLE
plotly_clickannotation event not firing on `editable: true`

### ISSUE THREAD

**Issue by marcusblevin** [plotly/plotly.js#1750]
Has something changed with the plotly_clickannotation event? I have tried reverting back to a previous version (1.22.0) and the event is firing but on latest (1.27.0) it is not.

See [CodePen](https://codepen.io/marcusblevin/pen/KmJJEQ?editors=1011) for example using latest version

**Comment by etpinard** [comment]
We apologise if your graphs are currently broken, adding `captureevents: true` to your annotation settings should do the trick - as in https://codepen.io/etpinard/pen/PmMxZL?editors=0011

See

- https://github.com/plotly/plotly.js/pull/1573#discussion_r110697483
- https://github.com/plotly/documentation/issues/742

for more detail on the issue.

**Comment by marcusblevin** [comment]
Thank you, that fixes the issue with the event firing but is that event dependent upon the editable configuration option not being turned on? I saw you had it disabled in the Codepen. The use case I am trying to accomplish is allow the annotation to be moved and capture the click event to load the currently set properties into an editor the user can use to update the annotation. Seems like this is a one or the other solution.

**Comment by etpinard** [comment]
> but is that event dependent upon the editable configuration option not being turned on?

Yeah. I noticed that too. I'm not sure if on purpose and/or the desired behavior.

> The use case I am trying to accomplish is allow the annotation to be moved and capture the click event to load the currently set properties into an editor the user can use to update the annotation

You should listen to `plotly_relayout` instead to accomplish this task.

**Comment by marcusblevin** [comment]
To be more specific, I use the plotly_clickannotation event to load the properties into the editor and to immediately change the focus so the text in the annotation never shows as editable and the edits instead happen in the form inputs. Plotly_relayout would fire after a change to the plot occurs but I want the event to be captured before any changes are made. Granted I could use plotly_relayout to capture the info when the annotation is moved but the loading of the inputs should not be dependent upon the annotation being repositioned.

**Comment by etpinard** [comment]
> to immediately change the focus so the text in the annotation never shows as editable and the edits instead happen in the form inputs.

That's an interesting use case, probably not what we envision `plotly_clickannotation` to be for, but interesting nonetheless.

----

After some thinking a little bit longer, I'm going to call this a bug: `plotly_clickannotation` and, more generally, all `plotly_` events, should be triggered in `editable: true` mode.

Changing the issue title accordingly.

**Comment by slfan2013** [comment]
Hi @etpinard, is there any update on this?

thanks.
