### ISSUE TITLE
Memory leak in dynamically updated scatter plot.

### ISSUE THREAD

**Issue by adamshapiro0** [plotly/plotly.js#1755]
Hi,

I'm using scatter plots as part of a real-time data display where I'm updating the data set relatively frequently (large volume of data @ ~5-10Hz). I've noticed a significant growth in memory usage as the plot is updated on the order of 100s of MB over a short span of time. I made a small pen to demonstrate, just generating random data and restyling the plot:

https://codepen.io/adamshapiro0/pen/jwOWgZ

I've found a few things after a bunch of digging and googling:
1. This seems to happen in both Chrome (58.0.3029.96) and Firefox (53.0.3)
2. The tab's overall memory usage _and_ javascript memory usage as reported by Chrome's task manager grow continuously while the tab is visible
3. When another tab is selected, the memory usage drops back down to a reasonable level, but appears to maybe grow slowly (hard to tell)
4. In the Chrome inspector, the heap usage recorded by the profiler appears to drop completely to normal on each garbage collect (i.e., the task manager looks like the usage is growing without bound but the inspector profile and heap snapshots don't match that)

I can't tell if this is an issue with Plotly or a deeper HTML5/v8 issue, but since it seems to affect both browsers I'm leaning towards Plotly.

This might be related to https://github.com/plotly/plotly.js/issues/957 and https://github.com/plotly/plotly.py/issues/487, but it's not quite clear.

Any thoughts?

**Comment by etpinard** [comment]
Interesting. This is the first I head about (possible) memory leakage in an SVG-based trace type (#957 and  plotly/plotly.py#487 identify problems with the WebGL-based `surface` trace type).

I remember @alexcjohnson taking noticing some memory issues in codepen itself than couldn't be replicated in a plain HTML page. @adamshapiro0 have you noticed this leaky behavior outside of codepen?

**Comment by etpinard** [comment]
@adamshapiro0 is using `restyle` in the referenced codepen. I wonder if `extendTraces` has the same apparent leaky tendencies.

**Comment by adamshapiro0** [comment]
(Sorry for the delay - traveling.)

@etpinard, I tried copying the codepen code directly into a local HTML file and I _think_ I'm seeing slow memory growth. It's a bit hard to tell because of variation due to garbage collection, but I watched it for a while and it did at least seem to be growing on average. I can try to play some more to confirm when I have a bit more time.

**Comment by dfcreative** [comment]
If there is memory leak, it is tiny/very hard to catch. 30s memory screening:
![image](https://user-images.githubusercontent.com/300067/27877300-15bd3818-6188-11e7-84e3-1e35245dfc34.png)
![image](https://user-images.githubusercontent.com/300067/27877281-0caa2cf4-6188-11e7-8b56-461294edfb64.png)

**Comment by cstelly** [comment]
I am having the same issue with memory growing as I update my chart in plotly. I have tried a few different ways to update the chart using newPlot and deleteTraces / addTraces but I am seeing the memory usage rise in chromes task manager by 100k to 500k every time I try to update my chart with new traces. Anyone have any other suggestions on how to try rebuilding / updating the chart?

**Comment by etpinard** [comment]
Closing as I'm hoping this thing is obsolete.

**Comment by markzolotoy** [comment]
No, it's not. I am seeing memory leak. If I dont execute Plotly.react then it's not happening.

**Comment by etpinard** [comment]
> No, it's not. I am seeing memory leak. If I dont execute Plotly.react then it's not happening.

Can you share a reproducible example to help us debug? Thank you!

**Comment by markzolotoy** [comment]
I was wrong about a straight memory leak, however my confusion is based on the following scenario. I have a button that sends a data request to the server and upon data arrival processes the data and renders a chart. Let's assume that data retrieval takes 5 secs and chart rendering (Plotly.react) takes 5 secs too. If I keep clicking the button before data is processed and Plotly.react is executed then I have no memory leak, but once I click the button that will start reprocessing of the unfinished chart it creates a memory leak. That's the impression I am getting.
