### ISSUE TITLE
[Feature Request] Hideable/collapsible subplots

### ISSUE THREAD

**Issue by betteridiot** [plotly/plotly.js#1756]
It is simple enough to hide the trace by clicking on the legend...but the axes and canvas for that subplot still exists. A fun feature (mainly for data exploration) would be able to hide/collapse the subplot until selected. Since I don't really know if you can synchronize plots within different divs, such a feature would allow vertical subplots to expand upwards/downwards when opened, and horizontal subplots to expand left and right when opened. Such actions could allow currently opened plots to be re-centered into the current div.

**Comment by etpinard** [comment]
> A fun feature (mainly for data exploration) would be able to hide/collapse the subplot until selected

How? By adding a button in the mode bar?

> allow vertical subplots to expand upwards/downwards when opened, and horizontal subplots to expand left and right when opened

That's sounds painful to describe as `data/layout` attributes.

---

Quite frankly, I believe this feature would best implemented in userland (i.e. not in this library)

**Comment by betteridiot** [comment]
I figured the rescaling of the canvas would be a bit much. However, a button or check box next to the subplot legend

**Comment by etpinard** [comment]
> However, a button or check box next to the subplot legend

plotly.js does not allow _per-subplot_ legends at the moment (see https://github.com/plotly/plotly.js/issues/1668). So, it really isn't obvious to me how this would work w/o confusing long-time users.

**Comment by etpinard** [comment]
Merging this ticket with https://github.com/plotly/plotly.js/issues/1668
