### ISSUE TITLE
Adding Markers to a line plot adds additional dates

### ISSUE THREAD

**Issue by Rpgilligan85** [plotly/plotly.js#1757]
This is for version 1.8 which is the version in the working example.

I am making a line chart with markers and I want it to work exactly like this, 
[Working Example](https://codepen.io/plotly/pen/WwXEoV). When you click on 1m it takes you to the last day and it won't let you go any further and this codepen works perfectly. 

The bug is when you add mode: "markers" or mode: "lines+markers" so the line has markers it will add additional dates at the end so when you click 1m it takes you way past your data. It should work just like the example above and not like this, [Example with bug](https://codepen.io/Rpgilligan85/pen/zzYqZV).

**Comment by etpinard** [comment]
That's the desired behavior. The markers mode add some [padding](https://github.com/plotly/plotly.js/blob/bc0e06d280be748200870da28bf48180ef5f100b/src/traces/scatter/calc.js#L73-L74) to the autoranged axes.

If you're not happy with our autorange opinions, you can always set `xaxis.range` and/or `xaxis.rangeslider.range` yourself as in https://codepen.io/etpinard/pen/OgJNwQ?editors=0010

**Comment by Rpgilligan85** [comment]
Thanks! Didn't realize you had to add the range in the range slider as well. This works perfectly.
