### ISSUE TITLE
issue with adding grouping letters on the top of each bar in a histogram

### ISSUE THREAD

**Issue by jingjin0322** [plotly/plotly.js#1759]
Hi All,

I am trying to use plotly to draw a histogram using the code below. I was wondering if it is possible to place the grouping letters AB, B, B , EF (which were placed below the names in the code) on the top of each bar?

Hope someone can give me some advice. I'll really appreciate that!

Thanks,
Jing 

a<-list(title="")
b<-list(title="")
p<- plot_ly( 
  x=c("R0-G5-6<br>AB",
      "R0-G6-3<br>B",
      "R0-G2-6<br>B",
      "R0-G2-3<br>EF"
     ),
  y= c(2.55,
       2.45,
       2.22,
       0.45
       ),
  error_y=list(type="data", array = c(0.09,
                                      0.09,
                                      0.09,
                                      0.08
                                      )),
  name="",
  type = "bar"
  
)%>%
  layout(title = "", xaxis=a, yaxis=b)
p

**Comment by etpinard** [comment]
It would be best to ask this question on https://community.plot.ly/ 

Thank you.
