### ISSUE TITLE
Gridlines duplication after adding and removing trace

### ISSUE THREAD

**Issue by fhurta** [plotly/plotly.js#1760]
In a graph using overlaying on y-axis, if I add trace and remove it later, there remain vertical gridlines.

The issue can be reproduced by this [codepen](https://codepen.io/exavier/pen/EXayqX). If you add trace, then remove it and scroll on x-axis, you can see the original vertical gridlines remain there.

I originally reported this as comment to #1218 - as problem in `Plotly.redraw()` but I tried to workaround it using `addTraces`/`deleteTraces` and it still produces those duplicated gridlines.

**Comment by etpinard** [comment]
Thanks for the report.

**Comment by czellweg** [comment]
@etpinard Has there been any progress on this? Or is there a rough time-estimate when this is expected to be resolved?

**Comment by etpinard** [comment]
@czellweg We don't give out roadmap for bug or feature work, as most of the time it would give user a false impression.

**Comment by alexcjohnson** [comment]
Seems to have been solved, probably by #2227
