### ISSUE TITLE
Is there a minimum land mass for countries to be included in the Coropleth maps?

### ISSUE THREAD

**Issue by slremy** [plotly/plotly.js#1763]
It seems that there are many "smaller" islands that are can't be seen on the [map of the world ](https://plot.ly/python/choropleth-maps/#world-choropleth-map)

<img width="701" alt="image" src="https://user-images.githubusercontent.com/871503/26874440-45cdd87c-4b86-11e7-83d6-e82a4bbc3221.png">

**Comment by etpinard** [comment]
Just set `geo.resolution: '50m'` for higher resolution maps.

See https://codepen.io/etpinard/pen/vZNBYP?editors=0010 and please use https://community.plot.ly/ for questions of the likes in the future.
