### ISSUE TITLE
Syntax error inside c#' webbrowser control 

### ISSUE THREAD

**Issue by rawat123** [plotly/plotly.js#1764]
i am using plotly-latest.min.js from this link https://cdn.plot.ly/plotly-latest.min.js inside c#' webbrowser control and it gives me syntax error at line 30 col 22569 and line is `u.function&&"object"===` can i have an alternative for this. @etpinard

**Comment by rreusser** [comment]
I'm not sure what the implications of using through c# are, but for a start, can you try the unminified version and give a few lines of context? The minified version is more or less meaningless as far as debugging goes.

**Comment by etpinard** [comment]
Yes @rawat123 , please try using https://cdn.plot.ly/plotly-latest.js instead. 

Fixing this bug starting from your report would be pretty much like trying to find a needle in a haystack. Thanks.

**Comment by etpinard** [comment]
and @rawat123 please don't tag my handle (@etpinard). It's not my repo. I'm just a maintainer and your not my boss. Thanks.

**Comment by rawat123** [comment]
ok gurudev

**Comment by etpinard** [comment]
Closing. @rawat123 feel free to reopening an issue when/if you can sandbox the problem into a reproducible example.
