### ISSUE TITLE
Annotation autorange on category axes

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#1768]
Annotation autorange is broken if you position the annotation using the category names for positioning, rather than the category serial number.
```
Plotly.newPlot(gd, [{x: ['a', 'b'], y: ['c', 'd']}], {
    annotations:[{x: 1, y: 1, ax: 30, ay: -30, text: 'boo!'}],
    width: 300,
    height: 300,
    paper_bgcolor:'#ffc'
})
```
works:
![screen shot 2017-06-08 at 12 50 03 pm](https://user-images.githubusercontent.com/2678795/26940554-1a6849c4-4c49-11e7-886d-6ecdedfc1d3e.png)

but if I change to category names:
```
Plotly.newPlot(gd, [{x: ['a', 'b'], y: ['c', 'd']}], {
    annotations:[{x: 'b', y: 'd', ax: 30, ay: -30, text: 'boo!'}],
    width: 300,
    height: 300,
    paper_bgcolor:'#ffc'
})
```
it fails to include the annotation in autorange:
![screen shot 2017-06-08 at 12 51 31 pm](https://user-images.githubusercontent.com/2678795/26940600-401d3e40-4c49-11e7-9ac5-60b10fe95bb4.png)

**Comment by etpinard** [comment]
This appear to be working fine in `1.27.1`: https://codepen.io/etpinard/pen/ZypqJz?editors=1010

**Comment by etpinard** [comment]
PR https://github.com/plotly/plotly.js/pull/1748 strikes again. Not sure why `annotations.json` didn't produce a diff.

**Comment by etpinard** [comment]
Blocking for `1.28.0`

**Comment by alexcjohnson** [comment]
The mock to include this in is `annotations-autorange.json` - make one of the axes categorical and use the category names for a couple of the positions on that axis.
