### ISSUE TITLE
Annotations appear in the corner if they are zoomed off-plot

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#1771]
See eg the annotations-autorange mock - it's easiest to see with annotations that don't have arrows, but happens with all of them: zoom in on one annotation, eg "right no arrow" - the other three annotations from that plot generate junk in the upper left corner.
![screen shot 2017-06-09 at 1 43 43 am](https://user-images.githubusercontent.com/2678795/26962587-316645a6-4cb5-11e7-92aa-c7fb8d4feb8c.png)

**Comment by etpinard** [comment]
Ha. This is fine in the latest release `1.27.1` -> http://rickyreusser.com/plotly-mock-viewer/#annotations

I suspect PR https://github.com/plotly/plotly.js/pull/1748 is the culprit.
