### ISSUE TITLE
Setting different color for each part of Box Plot 

### ISSUE THREAD

**Issue by alenan2016** [plotly/plotly.js#1774]
I would like to color the top of the box and the bottom of the box in different colors, and also top of the whisker and the bottom of the whisker in different colors. Is it possible somehow? Please see my example here: (my apologize, the example is in the Highcharts, in Highcharts I only can color top and bottom of the whisker  in different colors): https://jsfiddle.net/hew8nq5u/4/ Please show me an example if it is possible. Thank you in advance,
Best regards,
alenan2016

**Comment by etpinard** [comment]
Here's what you can do now: https://codepen.io/etpinard/pen/mwVxBE?editors=0010

We're missing a few attributes:

- `whiskerthinkess`
- `whiskercolor`
- `boxmeancolor`

**Comment by alenan2016** [comment]
Thank you for your interest and help.

**Comment by slfan2013** [comment]
eagerly wanting this as well. thanks.

**Comment by Braintelligence** [comment]
@etpinard Would love to have `whiskercolor`.

**Comment by slfan2013** [comment]
@Braintelligence Maybe set `boxpoints` to `outliers` and then change the `markers`? https://plot.ly/javascript/reference/#box-boxpoints

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
