### ISSUE TITLE
Extra space gets added below and above the chart

### ISSUE THREAD

**Issue by saimaparveen** [plotly/plotly.js#1775]
Hi,

Extra space is added at the top and bottom of chart if chart height is more. Any idea how to remove it?
<img width="468" alt="screen shot 2017-06-09 at 9 56 22 pm" src="https://user-images.githubusercontent.com/9054196/26984826-8e2b9bac-4d5e-11e7-897d-fe9d9319c502.png">

https://codepen.io/saimaparveen/pen/mwVLLL

**Comment by etpinard** [comment]
Assuming you're referring to the _space_ between `y=0` and `y='test'`, you can try tweaking `yaxis.range` to fit your needs: https://codepen.io/etpinard/pen/qjbYgX?editors=0010

**Comment by etpinard** [comment]
Closing. @saimaparveen if you have any other questions on this topic, please use https://community.plot.ly/

**Comment by saimaparveen** [comment]
Hi,

 yaxis: { 
    range: [-0.5, trace1.y.length-3]
  }

This solution works only for static data .. for me the graph data is changing that is why this solution is not working .. If data is more trace1.y.length-3 still leave space on top. Is there any way i can know what value we can minus from  trace1.y.length ?

**Comment by etpinard** [comment]
> for me the graph data is changing 

How are you updating your data? You can use `Plotly.relayout` or `Plotly.update` to update the yaxis range dynamically to fit your needs

**Comment by saimaparveen** [comment]
The issue is not with the update.
The issue is occurring when there is duplicate data for y axis or xaxis 
for ex: the code which is attached above is having 2 duplicate values in categories
"ss" ,"rr"  
We are doing trace1.y.length-3 which is removing space on top,  when there are no duplicates then there is no extra space at top.

**Comment by etpinard** [comment]
> the code which is attached above is having 2 duplicate values in categories
> "ss" ,"rr"

Hmm. I doubt that's the case.

The markers mode add some [padding](https://github.com/plotly/plotly.js/blob/bc0e06d280be748200870da28bf48180ef5f100b/src/traces/scatter/calc.js#L73-L74) to the autoranged [axes](https://github.com/plotly/plotly.js/blob/ffb3791989ff97de528fc66d0f9748fa2aedec43/src/plots/cartesian/axes.js#L439). This logic is slightly opinionated, and you're not the first one complaining about it not giving the desired results. As I mentioned above, to override this behavior, you can set the axis range.

**Comment by saimaparveen** [comment]
Same issue is happening for space in left and right side. 
When the mode is "markers+lines"
when the mode is just "lines" it is working fine.
<img width="1076" alt="screen shot 2017-08-24 at 1 25 04 pm" src="https://user-images.githubusercontent.com/9054196/29655896-2143dc7c-88d0-11e7-9cc4-f2c4517e3b18.png">

Any idea how this can be fixed?

**Comment by etpinard** [comment]
> you can set the axis range.

**Comment by SB-SVM** [comment]
I already set the axis range. However, if I press "All" on the rangeselector, it is showing me the white spaces again.
Before using the rangeselector:

![before](https://user-images.githubusercontent.com/35254041/42176208-74c8d5c0-7e28-11e8-9a06-79ffb1d740e2.JPG)


After clicking the "all" button:
![after](https://user-images.githubusercontent.com/35254041/42176157-4ba19380-7e28-11e8-9465-a119e65ffe3a.JPG)

**Comment by alexcjohnson** [comment]
FYI making this whole situation more configurable is being discussed in #1876. That effort, whenever it happens, will include the ability to override this automatic padding.
