### ISSUE TITLE
Allow to choose whether to trim trace names in hover info

### ISSUE THREAD

**Issue by simoneb** [plotly/plotly.js#1777]
Because of https://github.com/plotly/plotly.js/blob/master/src/components/fx/hover.js#L703 trace names longer than 15 chars get trimmed. It would be useful to provide an option to decide whether to trim or not

**Comment by etpinard** [comment]
Yeah for sure. Thanks for writing in!

**Comment by simoneb** [comment]
@etpinard thanks for the feedback. 

To expand on this, it would also be useful to be able to specify the maximum number of chars to trim to, or not at all. If you can give me some hints about where you think this configuration should live and what shape it may have based on your coding standards I can also create a PR. My first guess would be an additional option next to `hoverinfo` in a trace configuration, but maybe there's a better, upstream location for such a configuration?

**Comment by alexcjohnson** [comment]
@simoneb definitely, making this attribute an integer seems like the way to go. I'd put it in [hoverlabel](https://github.com/plotly/plotly.js/blob/master/src/components/fx/attributes.js#L15), perhaps `hoverlabel.trimname` or `hoverlabel.namelength`? Then a value of `0` would mean "no trimming" (or perhaps `false` would be clearer? It's not an integer but we do mix types for purposes like that elsewhere) and the `dflt` would be `15`.

**Comment by etpinard** [comment]
+1 for `hoverlabel.namelength`
