### ISSUE TITLE
This data makes the surface algorithm blow up

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#179]
... and freeze the browser tab.

``` js
z =  [[9607345622458638.0, 9607345622458652.0, 9607345622458652.0, 9607345622458646.0, 9607345622458652.0, 9607345622458650.0, 9607345622458650.0, 9607345622458646.0], [9607345622458654.0, 9607345622458640.0, 9607345622458650.0, 9607345622458652.0, 9607345622458652.0, 9607345622458654.0, 9607345622458650.0, 9607345622458652.0], [9607345622458654.0, 9607345622458652.0, 9607345622458638.0, 9607345622458652.0, 9607345622458650.0, 9607345622458652.0, 9607345622458654.0, 9607345622458650.0], [9607345622458650.0, 9607345622458652.0, 9607345622458650.0, 9607345622458632.0, 9607345622458644.0, 9607345622458646.0, 9607345622458646.0, 9607345622458650.0], [9607345622458654.0, 9607345622458652.0, 9607345622458650.0, 9607345622458650.0, 9607345622458638.0, 9607345622458654.0, 9607345622458654.0, 9607345622458650.0], [9607345622458650.0, 9607345622458654.0, 9607345622458650.0, 9607345622458646.0, 9607345622458652.0, 9607345622458638.0, 9607345622458646.0, 9607345622458652.0], [9607345622458654.0, 9607345622458652.0, 9607345622458654.0, 9607345622458650.0, 9607345622458654.0, 9607345622458652.0, 9607345622458640.0, 9607345622458654.0], [9607345622458650.0, 9607345622458652.0, 9607345622458650.0, 9607345622458652.0, 9607345622458650.0, 9607345622458654.0, 9607345622458654.0, 9607345622458638.0]]
```

most likely due to unstable floating point errors.

If that's the case, we should at least warn user when this happens.

**Comment by alexcjohnson** [comment]
#1906 fixes this for SVG, but there's something strange still happening with webGL - the browser still locks up with an unending cascade of these errors:
![screen shot 2017-07-21 at 4 56 06 pm](https://user-images.githubusercontent.com/2678795/28484291-833ed8a6-6e3f-11e7-951b-0a27cc5a0cc2.png)

**Comment by archmoj** [comment]
A [demo](https://codepen.io/MojtabaSamimi/pen/vQzKBp) to illustrate the issue.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
