### ISSUE TITLE
Deselecting scattergl points via double-clicking doesn't reset their color correctly

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#1806]
See https://codepen.io/etpinard/pen/rwwOyg

![peek 2017-06-21 14-37](https://user-images.githubusercontent.com/6675409/27400785-34c33e0a-568f-11e7-92ce-270d299665b7.gif)

cc @dfcreative

**Comment by dfcreative** [comment]
@etpinard fixed in https://github.com/plotly/plotly.js/pull/1804

**Comment by etpinard** [comment]
Thanks! Can you make a separate PR with with just this fix. #1804 will part of 1.29.0 fixing this should be part of 1.28.3

**Comment by dfcreative** [comment]
@etpinard done
