### ISSUE TITLE
Issues encountered with new zoom functionality

### ISSUE THREAD

**Issue by aderidder** [plotly/plotly.js#181]
Hi,
I'm using the new 'plotly_selected' feature, which is a great improvement. Here are some issues I encountered:
1. When in Select mode, a 'click' generates undefined eventData
2. When you're zoomed in, select some points and zoom back out, the selection box does not properly scale, which causes a mismatch between the selected points and the area the selection box shows
3. When in Select mode, double click removes the selection box, whereas a single-click does not. 
This is the selection:
![image](https://cloud.githubusercontent.com/assets/9414840/12322792/a7e46a10-bab6-11e5-850e-b347ad617b32.png)

On a single click it stays the same:
![image](https://cloud.githubusercontent.com/assets/9414840/12322792/a7e46a10-bab6-11e5-850e-b347ad617b32.png)

When you double-click:
![image](https://cloud.githubusercontent.com/assets/9414840/12322811/ce2f0e64-bab6-11e5-8639-20660a0940e9.png)

In the eventData there is no way distinguish between the two, as both are undefined, whereas, if the selection box is removed, you'd also want to be able to remove the selected points to keep the plot visually consistent.

**Comment by etpinard** [comment]
@aderidder These are known limitations of our first implementation of the lasso/select-box functionality.

I'll rename the issue accordingly.

You can look at PR https://github.com/plotly/plotly.js/pull/154 to know more about what you can expect in the current plotly.js version.

**Comment by etpinard** [comment]
More info here: https://github.com/plotly/plotly.js/pull/154#issuecomment-168797572

**Comment by etpinard** [comment]
cc @dfcreative @chriddyp @jackwluo

**Comment by etpinard** [comment]
merging with #1851
