### ISSUE TITLE
Minor mention: modebar tooltip slightly protrudes

### ISSUE THREAD

**Issue by monfera** [plotly/plotly.js#1810]
Mode bar hover tooltip `Produced with Plotly` - or other button tooltip if plot is narrow enough for modebar buttons to wrap - breaches the container size of its own `graphDiv`, causing a vertical widening of what's rendered:

![image](https://user-images.githubusercontent.com/1548516/27449522-fb664d32-5788-11e7-918f-2495c34a99bf.png)

The consequence (not seen) is that an `x` scrollbar on the bottom appears, which, as it takes space, causes a `y` scrollbar too (as seen).

Ideally, there is no protrusion, so a responsive dashboard can be made to fill the screen without risk of scrollbars appearing due to a couple of pixels.

Perfectly good-looking workaround: `d3.select('body').style('overflow', 'hidden')`

![image](https://user-images.githubusercontent.com/1548516/27449724-a61f33ec-5789-11e7-93f3-46decc22feee.png)

(Issue can be closed if unimportant; just a way of mentioning)

**Comment by monfera** [comment]
Interestingly, a similar protrusion on the left side doesn't appear to trigger the same issue, still noting it as a future iteration might shift tooltips such that they're visible in their entirety. All these are only (slightly) useful on the document body edge, but I guess in some cases it's useful if the tooltip is contained by the `gd` whether or not its edge is on a document body edge or not.

![image](https://user-images.githubusercontent.com/1548516/27450084-d72be9d4-578a-11e7-8d2e-30234fcf2786.png)

Again, just a contest entry for the 'most minor issue possible' title :-)

**Comment by alexcjohnson** [comment]
Nothing's too minor @monfera 🔍 🏆 

Seems to me the simplest way to keep this from happening is to add `overflow:hidden` to `.svg-container` - which cuts off the pleasant curve on the edge of the tooltip, but that's better than overstepping our bounds! Then secondarily we can look for a way to push it back on screen, curves and all.

**Comment by ThijsBroersen** [comment]
@monfera I was looking for information on to position the modebar to the left instead of the 'default' to the right and came across this issue. In your second comment you show an example with the modebar positioned to the left, how did you do that? Is there an option for it?

**Comment by monfera** [comment]
@ThijsBroersen I'm aware of no option, it appears on the left because there are three plots horizontally aligned and it's on the leftmost plot.

**Comment by etpinard** [comment]
Looks like this one got fixed during @antoinerg 's recent modebar work.
