### ISSUE TITLE
Major memory leak in 2D WebGL plots

### ISSUE THREAD

**Issue by kevineschmidt** [plotly/plotly.js#1813]
The Plotly.purge does not fully clean up a 2D OpenGL plot.  It seems that the camera associated with the 2D scene leaves some mouse handlers attached, which then keep a reference to the pickbuffer in  GLPlot2D, and in that, some very large Uint32Arrays.  

I ran the following plnkr in Chrome under an allocation timeline.  Repeatedly click the button.
https://plnkr.co/edit/7fve7JWbJrQy6COqJdIv?p=preview

In the function purgePlot, you can see there are two lines commented out that uninstall them and get rid of that large leak.

**Comment by kevineschmidt** [comment]
Intersting, in the allocation timeline, you don't see much recovered in the summary timeline at top, but the Retained Size is quite large.

Also it seems like you can't just change the code & rerun the allocation - Chrome tools don't seem to pick up the change. Stop plnkr  , close dev tools, make the change, start plnkr, open devtools

**Comment by etpinard** [comment]
cc @dfcreative

**Comment by dfcreative** [comment]
Ok seems that [fixed](https://github.com/dfcreative/plotly.js/tree/mem-unleak).

Before:
![image](https://user-images.githubusercontent.com/300067/27553619-a01dcad8-5a79-11e7-8af3-abc063ef93af.png)

After:
![image](https://user-images.githubusercontent.com/300067/27553664-d971c2f8-5a79-11e7-895d-bc71c1ec8204.png)

**Comment by dfcreative** [comment]
[Fix for scatter3d camera](https://github.com/dfcreative/plotly.js/commit/888ee1b5be96533e446e63cdef6341d584952d38).

**Comment by etpinard** [comment]
@dfcreative amazing :tada: 

PR away :rocket:

**Comment by etpinard** [comment]
fixed in https://github.com/plotly/plotly.js/pull/1821
