### ISSUE TITLE
HTML entities no longer render in ticktext

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#1814]
Introduced in 1.28.0 release

https://codepen.io/cpsievert/pen/ZyJoPW

**Comment by etpinard** [comment]
Thanks for the report. Caused by https://github.com/plotly/plotly.js/pull/1792. I can't believe no test failed to catch this.

**Comment by etpinard** [comment]
cc @alexcjohnson

**Comment by etpinard** [comment]
Here's the list of entities we should support:

https://github.com/plotly/plotly.js/blob/master/src/constants/string_mappings.js
