### ISSUE TITLE
Automatically color individual groupby child traces

### ISSUE THREAD

**Issue by rreusser** [plotly/plotly.js#1823]
@jackparmer points out that [when you add a groupby, only the legend changes](https://github.com/plotly/streambed/pull/9566#issuecomment-311134824), which isn't particularly helpful. Is there some way to work it in so that child traces don't simply inherit the same color and need to be manually styled to be meaningful?

Otherwise this may be strictly a workspace issue, but it seems that if there's some way to accomplish this in plotly.js, that would be preferable.

It isn't entirely straightforward since they do inherit the parent styles, which is a single color. Perhaps this could be accomplished with groupby populating the `style` field with unique colors for each child trace. It's ugly to need to populate all the group style fields, but unless there's a better way to override the default color, then I'm not sure the best path.

**Comment by rreusser** [comment]
I understand this issue better after digging a bit. The problem is that `supplyTraceDefaults` is run *twice*. Once on the input and then again out the expanded traces.

On the first pass, the default color is applied.
On the second pass, unique colors are applied to each expanded trace, but because the default color was already applied, it has no effect.

Is there any way to clear the color for the second pass? Or to cause the defaultColor to definitely be applied on the second pass in any general sort of way?

**Comment by rreusser** [comment]
@etpinard @alexcjohnson what do yo think about allowing a magic color value like `"DEFER"` [here](https://github.com/plotly/plotly.js/blob/master/src/lib/coerce.js#L141) so that we can sanitize the color but then know that it must *actually* be overridden on the second pass of supplyDefaults? That's the only way I can come up with to run `supplyDefaults` twice and only use the defaultColor on the second pass.

**Comment by rreusser** [comment]
Okay, thinking through this over and over, and I'm struggling. The necessary behaviors:

1. if no color is specified, each group should get an individual color. This works, but we need some hack to make supplyDefaults work. I think that hack is a flag that denotes whether a default color was applied and then `module.clearDefaultColors` so that the second pass just works.
2. if a trace level color (e.g. `line.color`) is specified, it should just work like it does now. The only catch is that props can't be cleared in the workspace, but that's a separate UX issue.

I still think this seems more like a plotly.js issue than a workspace issue, but of course the nuclear alternative is to shift the burden to the workspace and just construct styles manually. That will cause the `clear group styles` button not to work very well though since it will reset everything to a non-default state.

**Comment by etpinard** [comment]
done in #1830
