### ISSUE TITLE
heatmapgl cursor popup can't go wider than the plot is tall

### ISSUE THREAD

**Issue by ssfrr** [plotly/plotly.js#1825]
I use heatmaps to plot spectrograms represented as matrices. In trying to improve performance I tried using `heatmapgl`, but it looks like there's an issue with the cursor popover where it stops following the cursor when the X coordinate is greater than 1023.

Example:
https://jsfiddle.net/xfj1yxyu/3/

EDIT: corrected fiddle URL

**Comment by etpinard** [comment]
cc @dfcreative

**Comment by ssfrr** [comment]
just realized that 1023 isn't special, but that's the height of my plot (well, 1025, but that's close enough). When the plot is taller than it is wide things seem to be OK.

A smaller (e.g. 50x100) `heatmapgl` shows the same behavior.
