### ISSUE TITLE
heatmapgl box-select doesn't follow cursor outside the plot bounds

### ISSUE THREAD

**Issue by ssfrr** [plotly/plotly.js#1826]
If you want to select a corner of a `heatmapgl` plot, you have to drag your cursor exactly to the corner. If you try to go down-then-left, or left-then-down, the zoom box will stop following when you go past the edge. Compare the behavior when selecting a corner of the normal `heatmap` type.

Example:
https://jsfiddle.net/xfj1yxyu/4/

**Comment by etpinard** [comment]
That's true of all gl2d traces. Merging with https://github.com/plotly/plotly.js/issues/130
