### ISSUE TITLE
FR: Stacked and grouped barplots

### ISSUE THREAD

**Issue by fabiangehring** [plotly/plotly.js#1835]
As far as I know stacked and grouped barplots (at same time) are not possible in plotly at the moment. This would be a very nice feature:

Comparable to:
[Stacked and grouped](https://www.highcharts.com/demo/column-stacked-and-grouped)

**Comment by etpinard** [comment]
Would be nice!

See related:

- https://github.com/plotly/plotly.js/issues/475
- https://github.com/plotly/plotly.js/pull/517

**Comment by mojoaxel** [comment]
Here is a screenshot to demonstrate what this e feature request is for:
![image](https://user-images.githubusercontent.com/600565/37286015-06f9ec16-2601-11e8-84cb-398bcc524e30.png)
Here are some related community entries for this topic:
* [community.plot.ly #2154](https://community.plot.ly/t/combination-of-grouped-and-stacked-bar-chart/2154)
* [community.plot.ly #117](https://community.plot.ly/t/can-plotly-create-a-grouped-stacked-bar-chart/117)

**Comment by pietersv** [comment]
It is possible to create a grouped-and-stacked bar chart in Plotly.js by creating each group as a subplot.   It's not as simple as setting a top-level feature like 'barmode: 'stacked+grouped` but because it's more elemental it offers more options.

Here each subplot references a shared common yaxis and its own xaxis.  Each xaxis gets a "domain" which here means a portion of the overall bottom axis width. Here the first group gets [0.0, 0.33], the second [0.34, 0.66] and the third [0.67, 1.0]

![image](https://user-images.githubusercontent.com/10464727/39552850-1a89ff86-4e39-11e8-8f53-a111e93337f4.png)

https://codepen.io/__proto__/pen/XqgWEq
```js
Plotly.newPlot(
  "myDiv",
  [
    {
      x: ["A", "B", "C"],
      y: [0.3, 0.35, 0.4],
      type: "bar",
      name: "series 1a", 
      xaxis: 'x1',
      barmode: 'stack', 
      marker: {color: '#448'}
    },
    {
      x: ["A", "B", "C"],
      y: [0.6, 0.50, 0.40],
      type: "bar",
      name: "series 1b", 
      xaxis: 'x1',
      barmode: 'stack', marker: {color: '#88C'}
    },
    {
      x: ["A", "B", "C"],
      y: [0.1, 0.15, 0.20],
      type: "bar",
      name: "series 1c", 
      xaxis: 'x1',
      barmode: 'stack', 
      marker: {color: '#CCF'}
    },
    {
      x: ["A", "B", "C"],
      y: [0.3, 0.35, 0.4],
      type: "bar",
      name: "series 2a",
      xaxis: 'x2',     
      barmode: 'stack', marker: {color: '#080'}
    },
    {
      x: ["A", "B", "C"],
      y: [0.25, 0.15, 0.05],
      type: "bar",
      name: "series 2b",
      xaxis: 'x2',     
      barmode: 'stack', marker: {color: '#8c8'}
    },
    {
      x: ["A", "B", "C"],
      y: [0.45, 0.50, 0.55],
      type: "bar",
      name: "series 2c", 
      xaxis: 'x2',
      barmode: 'stack', marker: {color: '#CFC'}
    },
     {
      x: ["A", "B", "C"],
      y: [0.3, 0.35, 0.4],
      type: "bar",
      name: "series 3a", 
      xaxis: 'x3',
      barmode: 'stack', marker: {color: '#880'}
    },
    {
      x: ["A", "B", "C"],
      y: [0.6, 0.50, 0.40],
      type: "bar",
      name: "series 3b", 
      xaxis: 'x3',
      barmode: 'stack', marker: {color: '#CC8'}
    },
    {
      x: ["A", "B", "C"],
      y: [0.1, 0.15, 0.20],
      type: "bar",
      name: "series 3c", 
      xaxis: 'x3',
      barmode: 'stack', marker: {color: '#FFC'}
    },
  ],
  {
    barmode: "stack",
    yaxis: {tickformat: '%'},
    xaxis: {
      domain: [0, 0.33],
      anchor: 'x1', 
      title: 'Apples'
    },
    xaxis2: {
      domain: [0.33, 0.66],
      anchor: 'x2', title: 'Pears'
    },
    xaxis3: {
      domain: [0.67, 1.0],
      anchor: 'x3', title: 'Cherries'
    }
  }
);
```

**Comment by etpinard** [comment]
Merging into https://github.com/plotly/plotly.js/issues/3614 - which will make stack+group subplots possible

**Comment by arushiS27** [comment]
I am trying to use this layout for my json data but I am unable to get the right graph... Instead of  xaxis: x1 ... I need xaxis: Code and xaxis: test but i am not getting as I think there is some link to xaxis: x1 ...  which cannot be changed .. Please help me how to make it work
