### ISSUE TITLE
bullet charts?

### ISSUE THREAD

**Issue by hrstoyanov** [plotly/plotly.js#1837]
I saw this beautiful charts made with D3:
https://bl.ocks.org/mbostock/4061961

Can this be incorporated in plotly?

**Comment by jackparmer** [comment]
@hrstoyanov there is no bullet chart trace type (yet), but users have made them out of line charts. This is the nicest one I've seen:

https://plot.ly/~riddhiman/407/

Check out the "code" tab and select "JavaScript" in the dropdown for the JavaScript code to make this chart.

This chart was originally made in R:
https://moderndata.plot.ly/bullet-charts-in-r-using-plotly/

**Comment by hrstoyanov** [comment]
Thanks, I see. Still, a dedicated chart would be nicer, especially if one needs sparklines too
