### ISSUE TITLE
Stateless toggleable frames

### ISSUE THREAD

**Issue by rreusser** [plotly/plotly.js#1841]
Togglable? Toggleable?

talked with @etpinard long ago about solving the memory management frustration around frames with togglable frames. Animation would have two modes:

1. The first is frames as changesets. This is the current behavior and is good for ephemeral animations where animate is really just used as a fast path for shortcutting lots of the plotting logic by just supplying defaults and plugging the data into a d3 update.

2. The second is frames as changes that are toggled on/off. All active frames would be merged before the supplyDefaults step. This would be potentially a bit more expensive, but it would mean the state is recomputed from scratch each time so that things would be properly stateless. Maybe the implementation wouldn't be too bad, and I think this would solve some of the frustrating memory management issues. See: #1839 

The biggest challenge for 2 is just working it into the existing animation logic. Perhaps `Plotly.animate(gd, ['frame1'])` would toggle the state on/off, though that could get irritating if it's not straightforward to just *specify* whether it's on or off.

**Comment by SillyLily0** [comment]
This issue caused me hours of questioning my redux state management (I am using slider animations in a react/redux component).  I'm happy, that I finally found out about this issue, and deep cloning solved the problem within seconds, thank you! 
So I think it would be nice, to comment on this in the animations documentation (as far as I know there's no comment, that frames[0] is mutated internally).

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
