### ISSUE TITLE
Remove toolbar

### ISSUE THREAD

**Issue by pmpbar** [plotly/plotly.js#185]
There does not seem to be a way to remove the toolbar at the top right of a graph. It is interfering with my other hover events and is not necessary in my plot. I would love a way like ```{displayLogo:false}``` that removes this. 
Thank you. I love this library so very much.

**Comment by etpinard** [comment]
[`{displayModeBar: false}`(]https://github.com/plotly/plotly.js/blob/master/src/plot_api/plot_config.js#L59) should do the trick.

Example here: https://plot.ly/javascript/configuration-options/#hide-the-modebar-with-plotly.js

**Comment by pmpbar** [comment]
Thank you! I should not have added this. I looked through the source and found that (it did not work) but adding ```{staticPlot:true}``` did work. Sorry to open this.

**Comment by etpinard** [comment]
No worries. The term *mode bar* isn't really universal. You can't blame yourself for not finding those docs.

**Comment by pmpbar** [comment]
No worries! Thank you.
