### ISSUE TITLE
Updatemenu scroll handle has the wrong size

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#1859]
(Edit: this has been fixed for legend, still an issue for updatemenus)
Look for example at the `legend_scroll` mock: there are 23 traces, and 13 are visible at a time in the legend. So the scroll handle should take up ~13/23 of the legend height. But it looks like it just has a fixed height of 20px (which might be reasonable as a *minimum* in case the legend is absurdly long relative to its viewport, unless the viewport itself is super small, then the minimum might drop to half its height?)
![screen shot 2017-07-07 at 1 37 52 am](https://user-images.githubusercontent.com/2678795/27944474-1991d3b2-62b5-11e7-88ca-01f77b5b7795.png)

I think updatemenu scroll handles do [the same thing](https://github.com/plotly/plotly.js/pull/1214/files#diff-6df5a05bf905f2429d5e0ef121f31d08R62) but have not observed it.

**Comment by n-riesco** [comment]
@alexcjohnson Both legends and updatemenus use a constant-sized scrollbars.

**Comment by alexcjohnson** [comment]
Thanks @n-riesco - It's not super high priority (I called it a bug not because it's broken, but because it's different from basically every other scrollbar out there), but do you want to take this one when you need a break from other work? Should be easy...

**Comment by n-riesco** [comment]
@alexcjohnson sure, I can look into it (as long as this isn't urgent).

**Comment by alexcjohnson** [comment]
#2426 fixed the legends part of this.
Updatemenus *do* have this problem too, so leaving this issue open.
