### ISSUE TITLE
Add `marker.opacity` to bar traces

### ISSUE THREAD

**Issue by saimaparveen** [plotly/plotly.js#1862]
Hi,

Opacity of bar chart not changing.
https://codepen.io/saimaparveen/pen/WOgKYJ

If i remove type:'bar' for scatter plot opacity is working fine.

Thanks,
Saima Parveen

**Comment by etpinard** [comment]
CodePen w/o commented-out blocks: https://codepen.io/etpinard/pen/xrayzz?editors=1010

@saimaparveen Thanks for report!

**Comment by saimaparveen** [comment]
Is there any workaround for this issue?

**Comment by etpinard** [comment]
> Is there any workaround for this issue?

Try plotting separate traces with different scalar opacity values or wait for a patch.

**Comment by etpinard** [comment]
After looking at this more closely, it appears that `marker.opacity` has never been part of `bar` trace schema in `v1.x`. So this ticket isn't a bug. Passing the `data` array from the codepen above to `Plotly.validate` correctly outputs _key marker.opacity is not part of the schema_ .

 I wouldn't be opposed to adding `marker.opacity` to `bar` traces, but this will be a low-priority ticket in the short term. Community PRs are welcomed though.

Note that trace-wide `opacity` scalar values due work for bars and setting `marker.color` as `rgba` values also works. See https://codepen.io/etpinard/pen/JJqjgy?editors=1010
