### ISSUE TITLE
Timeseries -values plotting with plotly

### ISSUE THREAD

**Issue by nikitagupta55** [plotly/plotly.js#1865]
Plotly is a really good for interactive data-visualisation.

I have a some timeseries data of this form:

```js
var data = [
               {
                    "x": "2017-06-23T23:54:10-07:00",
                    "y": 16.092212379644767,
                    "y_min": 10.14738937992582,
                    "y_max": 24.88384684136803
                },
                {
                    "x": "2017-06-23T23:54:20-07:00",
                    "y": 16.090838412070973,
                    "y_min": 10.403717849870672,
                    "y_max": 24.253709163301977
                },
                {
                    "x": "2017-06-23T23:54:30-07:00",
                    "y": 16.089464561807755,
                    "y_min": 10.356200342305344,
                    "y_max": 24.754436098179013
                },
                {
                    "x": "2017-06-23T23:54:40-07:00",
                    "y": 16.088090828845107,
                    "y_min": 10.548971084023746,
                    "y_max": 25.17303591243651
                },
                {
                    "x": "2017-06-23T23:54:50-07:00",
                    "y": 16.086717213173024,
                    "y_min": 10.117586305351361,
                    "y_max": 24.66066931822096
                },
                {
                    "x": "2017-06-23T23:55:00-07:00",
                    "y": 16.085343714781484,
                    "y_min": 10.711075236451466,
                    "y_max": 25.065592656487638
                },
                {
                    "x": "2017-06-23T23:55:10-07:00",
                    "y": 16.083970333660474,
                    "y_min": 10.542796162002471,
                    "y_max": 25.065456456643652
                },
                {
                    "x": "2017-06-23T23:55:20-07:00",
                    "y": 16.08259706979997,
                    "y_min": 10.466850541247998,
                    "y_max": 23.736521551344573
                },
                {
                    "x": "2017-06-23T23:55:30-07:00",
                    "y": 16.081223923189977,
                    "y_min": 10.405617923533082,
                    "y_max": 24.051937297627507
                }
]
```

As, it is quiet clear from the data, that on x axis I will be plotting timestamps and on y axis I need to plot the y values but I also want to plot this y_min and y_max and fill this region with some color.
Please see the image below for better understanding. Is this type of thing possible using plotly?

![screen shot 2017-07-07 at 3 04 41 pm](https://user-images.githubusercontent.com/25779041/27978726-0b3bf89e-6326-11e7-8e0e-39b61821a785.png)

As plotly is build using d3.js, and I build this graph using d3 timeseries library http://mcaule.github.io/d3-timeseries/. But I couldn't figure out how this can be done in poltly?

Also, can plotly timeseries graph can be built on react js? Can you just give a simple example to start with.
Thanks
Please let me know.

**Comment by eiymba** [comment]
I think using shapes might help? See https://plot.ly/javascript/shapes/

**Comment by etpinard** [comment]
Here's how to convert your data to something that plotly.js understands: 

https://codepen.io/etpinard/pen/QgJpVJ?editors=0010

Would might want to look at https://plot.ly/javascript/time-series/ for more examples or ask other questions in our community forums on https://community.plot.ly/

**Comment by nikitagupta55** [comment]
@etpinard  It looks good, but i need to color the region between y_min and Y_max as shown in the figure. How do i do that?
