### ISSUE TITLE
restyle marker to array of symbols doesn't work

### ISSUE THREAD

**Issue by destradafilm** [plotly/plotly.js#1866]
Here's the codepen

https://codepen.io/destrada/pen/XgPQgb

If I draw a new plot with marker.symbol as an array it works

when I restyle with an array for marker.symbol it only uses first symbol in array

**Comment by destradafilm** [comment]
nevermind, I figured it out here:
https://codepen.io/destrada/pen/GEXLyx

Although it's not intuitive because it's inconsistent with other instances of restyling.

**Comment by etpinard** [comment]
This is the intended behavior. Your `restyle` call updates the whole `marker` attribute container. Try commenting out the `size: 25` key-value pair, this leads to markers of the default size. 

Note that for single-trace graphs:

```js
  var restyleupdate = {
    'marker': { 
      symbol: ['circle','square','circle','square', 'circle', 'square'],
      size: 25
    }
  }
```

is equivalent to

```js
  var restyleupdate = {
    'marker': [{ 
      symbol: ['circle','square','circle','square', 'circle', 'square'],
      size: 25
    }]
  }
```

but not

```js
  var restyleupdate = {
    'marker.symbol': [['circle','square','circle','square', 'circle', 'square']],
    'marker.size': 25
  }
```

which only update `marker.symbol` and `marker.size` as opposed to the whole `marker` container.
