### ISSUE TITLE
Allow scatter traces with `mode: 'none'` to contribute to `tonext*` fills 

### ISSUE THREAD

**Issue by koreyou** [plotly/plotly.js#1867]
Trying to create filled plots with no lines, I used `fill` with `mode = 'none'`. This caused unexpected behavior of the first fill not showing up.

```javascript
var data = [
  {
    "x": [1, 2, 3],
    "y": [-2.0, -3.0, -4.0],
    'type': 'scatter',
    'mode': "none",
    'showlegend': false,
    "name": "1"
  },
  {
    "x": [1, 2, 3],
    "y": [-1.0, -2.0, -3.0],
    'type': 'scatter',
    'showlegend': false,
    'mode': "none",
    "name": "2",
    "fill": "tonexty",
    "fillcolor": "blue"
  },
  {
    "x": [1, 2, 3],
    "y": [0.0, 0.0, 1.0],
    'type': 'scatter',
    'showlegend': false,
    'mode': "none",
    "name": "3",
    "fill": "tonexty",
    "fillcolor": "green"
  }
];

Plotly.newPlot(
  "test", // the ID of the div
  data, {});
```

![fill_with_mode_none](https://user-images.githubusercontent.com/5196226/27982751-50fbf18e-63e6-11e7-85b3-ecb9242321ef.png)

The minimum moving example is [here](https://embed.plnkr.co/gGCSlS/)

This is the expected plots:

![expected](https://user-images.githubusercontent.com/5196226/27982752-56c8c8b2-63e6-11e7-8f2b-40e91a6b2ba0.png)

This can be achieved by passing 0 width line.

```javascript
    'mode': "lines",
    'line': {'width': 0, 'color': 'green'},
```

I believe this is not a desired behavior?
It will be great if you can fix the problem or at least document it for `fill`.

**Comment by etpinard** [comment]
Interesting. Thanks for pointing this out!

I guess we could allow for line-less fills. I don't see a problem with that. I'll change the issue title accordingly. 

In the meantime, your

```js
'mode': "lines",
'line': {'width': 0, 'color': 'green'},
```

is the best workaround I can think of.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
