### ISSUE TITLE
Add support for the "config.editable" parameter as an object

### ISSUE THREAD

**Issue by ruxeom** [plotly/plotly.js#1872]
The documentations states that the **editable** flag allows us to edit titles, move annotations, etc.
It would be nice to have the option to specify how editable my plot will be.

For example: I'd like to be able to edit annotation positions, or even their text, but I'd like my axis labels and plot title to remain fixed.

**Comment by alexcjohnson** [comment]
Good timing @ruxeom - this is actually something we're working on right now.

**Comment by ruxeom** [comment]
That's great! Thanks for the info

**Comment by etpinard** [comment]
It might be worth delaying the release of `1.29.0` (again, sorry) to get this feature in - as the next minor `1.30.0` probably won't happen until mid-August.
