### ISSUE TITLE
Tick text not in correct position in scattergl

### ISSUE THREAD

**Issue by PPPW** [plotly/plotly.js#1874]
Dear Plotly.js,
The performance of "scattergl" is really impressive, so I'd like to replace "scatter" with it. However I found if the axis consists of long strings, the tick texts are not as properly located as "scatter". E.g., in the following example, compare "scattergl" and "scatter":
https://codepen.io/anon/pen/dRwQGK?editors=1010

Thanks!

**Comment by etpinard** [comment]
Thanks for the report. 

You might want to subscribe to https://github.com/plotly/plotly.js/pull/1869 where @dfcreative is doing major improvement to `scattergl`

**Comment by etpinard** [comment]
Will be fixed by @dfcreative regl-based `scattergl` work :tada: 

![image](https://user-images.githubusercontent.com/6675409/34686647-4444e43a-f47a-11e7-93e4-a4ebe9492aa2.png)

**Comment by dfcreative** [comment]
Added mock in a61568529e90189f9ebddf00b27daf86696ebd1c.
![image](https://user-images.githubusercontent.com/300067/34987107-0bd4ad54-facb-11e7-9951-18a5f9f364d7.png)
But long ticks are not perfect in `scatter` trace too by default. @etpinard is there a way to insert a line break in tick label? I tried `<br/>`, `\n` or just newline - nothing worked. Or mb some tick width limit?

**Comment by etpinard** [comment]
> But long ticks are not perfect in scatter trace too by default

Yep, that's known issue (see https://github.com/plotly/plotly.js/pull/2243). No action required from your end.

**Comment by etpinard** [comment]
done in https://github.com/plotly/plotly.js/pull/2258
