### ISSUE TITLE
A "scattergl" trace + a "box" trace: not working

### ISSUE THREAD

**Issue by PPPW** [plotly/plotly.js#1878]
I'd like to show all points in the box plot, so that people can select the points. It seems the only way is to add a scatter trace with the box trace. "scatter" + "box" works fine:
https://codepen.io/anon/pen/LLqrmx?editors=0010

However if I change it to "scattergl", then it doesn't work. Since "scattergl" is way faster than "scatter", so it would be nice if this works. Thank you!

**Comment by etpinard** [comment]
This one is part of https://github.com/plotly/plotly.js/issues/130 

> cartesian + gl2d subplot on the same graph are not supported
