### ISSUE TITLE
The typed array polyfill we provide in dist/ does not polyfill ArrayBuffer.isView

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#1900]
First reported in https://github.com/ropensci/plotly/issues/1055

In our src code, we add a fallback to `ArrayBuffer.isView` [here](https://github.com/plotly/plotly.js/blob/master/src/lib/is_array.js), but @dfcreative 's [`color-parse`](https://github.com/colorjs/color-parse/blob/f6e9863c72870e629d9fdc4f63a65910758b1905/index.js#L164) does not. This lead to 3D and gl2d (and anything else using [`color-rgba`](https://github.com/colorjs/color-rgba)) breaking in RStudio even with typed array [polyfill](https://github.com/plotly/plotly.js/blob/master/dist/extras/typedarray.min.js) we provide in `dist/`.

So, we could of course patch `color-parse` to include an `isView` fallback, this will fix this one case. But maybe instead we could add a `ArrayBuffer.isView` polyfill to the `typedarray.min.js` we provide which will solve this problem for all our dependencies.

By the way, does anyone know where `typedarray.min.js` comes from?

cc @alexcjohnson @cpsievert @bcdunbar

**Comment by dfcreative** [comment]
@etpinard I can just check if ArrayBuffer has that method if you want

**Comment by etpinard** [comment]
> @etpinard I can just check if ArrayBuffer has that method.

Yeah, that would be great thanks :+1:

**Comment by dfcreative** [comment]
@etpinard done https://github.com/colorjs/color-parse/commit/4be59c59c9f063b71d87b0c8e8cbde11349c2530#diff-168726dbe96b3ce427e7fedce31bb0bcL164

**Comment by etpinard** [comment]
Oops. I forgot to include this in `1.29.1`. My mistake.

**Comment by etpinard** [comment]
@dfcreative would you mind publishing https://github.com/colorjs/color-parse/commit/4be59c59c9f063b71d87b0c8e8cbde11349c2530#diff-168726dbe96b3ce427e7fedce31bb0bcL164 and making a PR here bumping `color-rgba`?

**Comment by dfcreative** [comment]
@etpinard here https://github.com/plotly/plotly.js/pull/1915

**Comment by etpinard** [comment]
fixed by https://github.com/plotly/plotly.js/pull/1915 (verification made by @cpsievert )

**Comment by etpinard** [comment]
Actually, I'll reopen this issue. 

#1915 _fixed_ the issue, but _the typed array polyfill we provide in dist/ does not polyfill ArrayBuffer.isView_ still holds.

**Comment by jackparmer** [comment]
This issue has been tagged with `NEEDS SPON$OR`

A [community PR](https://github.com/plotly/plotly.js/pulls?q=is%3Apr+is%3Aopen+label%3A%22type%3A+community%22) for this feature would certainly be welcome, but our experience is deeper features like this are difficult to complete without the Plotly maintainers leading the effort.

**Sponsorship range: $5k-$10k**

What Sponsorship includes:
- Completion of this feature to the Sponsor's satisfaction, in a manner coherent with the rest of the Plotly.js library and API
- Tests for this feature
- Long-term support (continued support of this feature in the latest version of Plotly.js)
- Documentation at [plotly.com/javascript](https://plotly.com/javascript/)
- Possibility of integrating this feature with Plotly Graphing Libraries (Python, R, F#, Julia, MATLAB, etc)
- Possibility of integrating this feature with Dash
- Feature announcement on [community.plotly.com](https://community.plotly.com/tag/announcements) with shout out to Sponsor (or can remain anonymous)
- Gratification of advancing the world's most downloaded, interactive scientific graphing libraries (>50M downloads across supported languages)

Please include the link to this issue when [contacting us](https://plotly.com/get-pricing/) to discuss.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
