### ISSUE TITLE
Weird hover issue when drawing multiple graphs in a parent div with `column-count: 2`

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.js#1902]
https://codepen.io/chriddyp/pen/aweQae

![colum-count](https://user-images.githubusercontent.com/1280389/28448018-bde067f6-6da2-11e7-9df1-15444c6ffe1b.gif)

Originally posted https://github.com/plotly/dash/issues/86

**Comment by rreusser** [comment]
One small note: I think it's best to avoid `<div/><div/>`, which for whatever random reason [gets parsed](https://codepen.io/rsreusser/pen/gxYPYx) as `<div><div></div></div>`.

**Comment by rreusser** [comment]
Whoaa… check out *three* columns… that might at least hint at how this is implemented. Perhaps it rasterizes and then splits it into columns as a rendering effect? I wouldn't at all be surprised if this were browser bugginess for how this interacts with relative/absolute positioning, mouse coords (which, surprisingly, seem to work), etc.

<img width="1134" alt="screen shot 2017-07-21 at 08 00 18" src="https://user-images.githubusercontent.com/572717/28469304-b66e5ed6-6dea-11e7-833a-371233cad3bf.png">

**Comment by alexcjohnson** [comment]
We can at least apply [`break-inside: avoid`](https://css-tricks.com/almanac/properties/b/break-inside/) and its vendor variants to `gd` to prevent chopping the svg as in @rreusser 's second comment.

What this shows though is that the browser is doing something strange with `getBoundingClientRect` after the first column - see eg this [ancient bug](https://bugs.webkit.org/show_bug.cgi?id=99959) webkit seems to have ignored. I don't see where So I suspect that the complete fix is going to require getting rid of *all* invocations of `getBoundingClientRect` on elements inside `gd` and only using the off-screen tester - which is also needed for #888 and probably some un-reported issues around plotting certain trace types in hidden `<div>`s.

Also notice that the modebar jumps down below the plot momentarily when you mouse over from one plot to the next... not sure why that would happen as it's absolutely positioned wrt its parent... but might be related to all this.

**Comment by rreusser** [comment]
I also tried `page-break-inside: avoid` and `-webkit` variants but didn't have luck. Maybe I used them incorrectly.

**Comment by zmays** [comment]
Any known workarounds for this issue?

**Comment by lacerdamarcelo** [comment]
I managed to "solve" this problem by manually editing the style of the div. You can see how it is done [here](https://www.educative.io/edpresso/how-to-make-side-by-side-divs-in-html?aid=5082902844932096&utm_source=google&utm_medium=cpc&utm_campaign=edpresso-dynamic&gclid=EAIaIQobChMIvq_2usLQ6gIVhxGRCh2gjQcPEAAYASAAEgIU1_D_BwE).

This is the code I used:

```
app.layout = html.Div(children=[
    html.H1(
        children='Painel de Rating da Dívida Ativa',
        style={
            'textAlign': 'center',
        }
    ),
    
    html.Div(children=[
    dcc.Graph(
        id='example-graph',
        figure=fig
    )], style={'width': '50%', 'float': 'left'}),

    html.Div(children=[
    dcc.Graph(
        id='example-graph-2',
        figure=fig2
    )], style={'marginLeft': '50%'}),

    generate_table(df_data)
])
```

In this example, fig and fig2 will be put side by side and the hover text in fig2 will succesfully appear.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
