### ISSUE TITLE
Plotly Unified Color Scale

### ISSUE THREAD

**Issue by hiteshsahu** [plotly/plotly.js#1903]
I am using plotly.js to plot graph in HTML5 Web app. The problem is the colorbar change its color scale depending on input values. Plotly assign a color based on distribution of points

  For eg consider this colorscale:
 max value(1.0) = Blue 
 med value (0.5) = Green
 min( 0.0) = Red. 

- If data is in range of 0-100 then 100 will be Blue
- If suddenly some value bounced to 200 then the range will change to 0-200 now Green color represents 100. 

![img_20170721_144813](https://user-images.githubusercontent.com/4076925/28457942-92ccf4fc-6e25-11e7-978d-9610bb3fdfc2.jpg)

 I want 100 to be always represented by Blue color.  For this, I need to assign color to value range like
  100 - Blue,
  100- 150 Deep Blue, 
  Higher than that Black

 

>   Is there any way I can fix color for the data range?  My data range varies from 0- 6k, 2k-6k,  4k to 6k. I need 6 k to be blue all the time.

**Please refer below code pen for the issue.**

<p data-height="265" data-theme-id="light" data-slug-hash="JJgqrv" data-default-tab="js,result" data-user="hiteshsahu" data-embed-version="2" data-pen-title="Ploty Unified color scale" class="codepen">See the Pen <a href="https://codepen.io/hiteshsahu/pen/JJgqrv/">Ploty Unified color scale</a> by Hitesh  Sahu (<a href="https://codepen.io/hiteshsahu">@hiteshsahu</a>) on <a href="https://codepen.io">CodePen</a>.</p>
<script async src="https://production-assets.codepen.io/assets/embed/ei.js"></script>

**Comment by etpinard** [comment]
See:

- https://plot.ly/javascript/heatmap-and-contour-colorscales/
- https://plot.ly/javascript/reference/#heatmap-colorscale
- https://plot.ly/javascript/reference/#heatmap-zmax
- https://plot.ly/javascript/reference/#heatmap-zmin

and https://community.plot.ly/ if you have any other questions on the topic.

**Comment by hiteshsahu** [comment]
Thanks, @etpinard setting  `zauto `solved my problem. 

Adding code snippet for future reference if somebody wants similar thing.

```
  var plotData5kW = [{
                z: data5kW,
                showscale: true,
                fixedrange: true,
                hoverinfo: "z",
                colorbar: {
                  title: 'Speed(RPM)',
                  titleside: 'top',
                  titlefont: { color: 'black' }
                },
                type: 'heatmap',
               // Define color scale range in a bound
               zauto:false,
               zmin: 0,
               zmax : 6000,
              colorscale: 5kWColorScale,
                }
            ];

            Materialize.toast("Displaying 5.5kW Graph :	For Model: " + data5kW.name, 2000);
            Plotly.newPlot('compressorDiv', plotData5kW, layoutScale, { displayModeBar: false });
```

**Comment by lubianat** [comment]
@hiteshsahu this comment just saved my day!! 

ChatGPT 4o couldn't fix it in 1h30, but you did it! (it kept putting cmin in the wrong place)
