### ISSUE TITLE
df3.iplot(kind='surface') gives me a three diminsional uncolored graph

### ISSUE THREAD

**Issue by TareqAlshargabi** [plotly/plotly.js#1905]
Hi,

The command above in the title gives me a white graph.

I followed all the steps for installation and ran all commands for notebook and for offline use (please see below for commands I used and the output graph). Not sure why the graph is not colored. Could you please help?

I get this uncolored graph when I ran the command:
df3.iplot(kind='surface')

Where df3 is a dataframe.

![2017-07-20_16-27-54-d52058270b48e80117ca7637a0002bd7](https://user-images.githubusercontent.com/30349651/28477802-aa0a3780-6e23-11e7-8bfb-bf55fae68f13.png)

Any idea what may have caused this?

Many thanks,

**Comment by etpinard** [comment]
Best for https://github.com/plotly/plotly.py/issues 

I doubt this is a plotly.js issue.

**Comment by TareqAlshargabi** [comment]
I apologize for the mistake.
