### ISSUE TITLE
Coloring for markers using scattergl isn't working properly

### ISSUE THREAD

**Issue by Vampiro** [plotly/plotly.js#1909]
Coloring for markers using scattergl isn't working properly.

Example using scattergl where x values range from 0-999 and y values are random from 0-1. Coloring should be clearly defined gradients from red to green to blue as you go up in y:
https://codepen.io/anon/pen/gxOeNw

You can see that it kind of starts out alright, but later in x the colors become jumbled, they should be clearly defined based on y values. If we comment out the scattergl line, colors are as they should be:
https://codepen.io/anon/pen/vJYRoN

**Comment by etpinard** [comment]
cc @dfcreative and https://github.com/plotly/plotly.js/pull/1869

**Comment by tylertucker202** [comment]
Hello! I've noticed that if you round the color to one decimal point will sometimes clear the issue. Can you confirm this?

**Comment by etpinard** [comment]
This appears to have been fixed by @dfcreative 's awesome new regl-based `scattergl` coming in version `1.33.0`:

![image](https://user-images.githubusercontent.com/6675409/34686163-c40712ee-f478-11e7-8199-3f8b2ab8fc5d.png)

**Comment by tylertucker202** [comment]
This is fantastic news. I've been writing a web-app that uses scatter GL to view ocean data on color plots. You can see the temperatures plot, you have dark color markers showing on the surface. Switching to 'scatter' make this disappear.
http://www.argovis.com/catalog/platforms/5902386/page
I will be anxiously awaiting version 1.33.0. Thanks for the good work.

**Comment by dfcreative** [comment]
Added mock in https://github.com/plotly/plotly.js/commit/889237f9dd4c04b640229f5e0839658697e2dfa7

**Comment by etpinard** [comment]
fixed by https://github.com/plotly/plotly.js/pull/2258
