### ISSUE TITLE
"selected" event doesn't distinguish between double clicking to clear a selection and single clicking outside the selection box

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.js#1911]
In Dash, users need to know when the viewer has cleared the selection box by double clicking outside of it. Right now, single-clicking outside of the selection box doesn't clear the selection box but it emits a `selected` event with no data. Double-clicking outside of the selection box clears the selection box but it emits the same `selected` event with no data. There is no way to distinguish between these two actions right now.

![clear-unselect](https://user-images.githubusercontent.com/1280389/28541339-a3497b30-7086-11e7-9237-4e4667f5532c.gif)

**Comment by chriddyp** [comment]
Brought up in this issue https://github.com/plotly/dash/issues/97

**Comment by etpinard** [comment]
What about using [`plotly_deselect`](https://github.com/plotly/plotly.js/blob/10c3ae0f5105e6d617ede522d854112ca277f3cb/src/plots/cartesian/select.js#L209)?

**Comment by chriddyp** [comment]
that works for me! thanks :clinking_glasses:

**Comment by etpinard** [comment]
Ok. I'll close this. 

Perhaps we should revisit how `plotly_selected` is triggered when no points are selected in `v2`? (see https://github.com/plotly/plotly.js/issues/168 for more). Maybe it shouldn't be triggered at all?
