### ISSUE TITLE
Horizontal legend wrapping is broken when legendgroups are used

### ISSUE THREAD

**Issue by tripped** [plotly/plotly.js#1913]
jsfiddle repro here: https://jsfiddle.net/6oq39dpy/3/

Normally, when a horizontal legend contains many items, they get wrapped onto multiple lines.

However, if legend groups are used at all -- even if only a single item is assigned to its own legend group -- nothing is wrapped, and legend items extending beyond the width of the plot are invisible and inaccessible.

To make wrapping appear again in the jsfiddle repro, just comment out line 10, which sets a legend group for the first trace.

While searching for an already open issue for this, I found #769, which led to the original PR that added support for wrapping horizontal legends in the first place, and mentions legend groups, but only as a workaround for the original problem. I've only skimmed the related code so far so I don't know exactly what causes the bug. :-)

**Comment by healzer** [comment]
Any fix for this?

**Comment by jzthree** [comment]
https://github.com/plotly/plotly.js/blob/9a79056bb223e13995be8debd22f60c9d56cbef0/src/components/legend/draw.js#L521-L592

It looks like this is the issue, in the code structure below, if isGrouped is true, it blocks the regular horizontal legend code

if(helpers.isVertical(opts)) {
...
}
else if(isGrouped){
...
}else{
...
}

**Comment by Braintelligence** [comment]
@jzthree Could it be as easy as refactoring this bit and horiontal legend groups would work again?

**Comment by Braintelligence** [comment]
It's not perfect at all, but you can change they legend orientation on relayout depending on the window width as a workaround until this is fixed. (Only a choice between horizontal and vertical, tho. No wrapping of two items in a row possible this way.)

**Comment by Braintelligence** [comment]
Just FYI everyone: If you set `legend.traceorder = normal || reversed` (but not grouped or reversed+grouped) you won't experience problems with wrapping. This is perhaps interesting for you, if you're using legendgroups solely for the feature of simultaneous isolation of data by legendclicks but don't need the grouped positioning in the legend.

**Comment by slishak** [comment]
Extending on this issue, with multiple legend groups you end up with one vertical column in the legend for each group. Which I guess is not a bad way of representing a grouped legend, but I'd guess not intentional!
https://jsfiddle.net/by142svc/1/

**Comment by tobiasblasberg** [comment]
> Just FYI everyone: If you set `legend.traceorder = normal || reversed` (but not grouped or reversed+grouped) you won't experience problems with wrapping. This is perhaps interesting for you, if you're using legendgroups solely for the feature of simultaneous isolation of data by legendclicks but don't need the grouped positioning in the legend.

I am using rplotly with plotly version 4.8.0. Unfortunately there is no legend$traceorder variable for barplots: https://plot.ly/r/reference/#bar. I would highly appreciate any solution for the alignment/wrapping of horizontal legend of barplots in R.

**Comment by alexcjohnson** [comment]
@tobiasblasberg it's not a trace property, it's in layout https://plot.ly/r/reference/#layout-legend-traceorder

**Comment by tobiasblasberg** [comment]
Great! That works perfect - thanks a lot!

**Comment by avsdev-cw** [comment]
+1 for this

I may even make a PR if I get a chance to implement a fix using a refactored version of the mentioned draw.js file.

**Comment by etpinard** [comment]
@antoinerg could you take a look at this one?

**Comment by antoinerg** [comment]
> Extending on this issue, with multiple legend groups you end up with one vertical column in the legend for each group. Which I guess is not a bad way of representing a grouped legend, but I'd guess not intentional!
> https://jsfiddle.net/by142svc/1/

 @plotly/plotly_js is the behavior mentionned above intentional and would the following change be acceptable: https://github.com/plotly/plotly.js/commit/e84bcb9f768c96ac0873a187398e3a919d027870?short_path=3367b6a#diff-3367b6ae7c2fe5d6fbdfd3a6630f48a1 ? If so, I could submit a fix that only :hocho: suspcious code which is a win imho.
