### ISSUE TITLE
Setting mapbox center near meridian causes errors

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#1916]
Oddly enough, the errors go away without `marker.color`

https://codepen.io/cpsievert/pen/yoNVMr

**Comment by rreusser** [comment]
Can you clarify the error? I see the following plot without console errors.

<img width="525" alt="screen shot 2017-07-26 at 10 05 02" src="https://user-images.githubusercontent.com/572717/28633829-eaf9b256-71e9-11e7-8d13-d3c311efcd6d.png">

**Comment by rreusser** [comment]
What I don't see though is hover labels to the right of the meridian (> 0˚)

**Comment by cpsievert** [comment]
Ahh, sorry, you're right. The problem was due to something else that I failed to include, and it's not a plotly.js problem https://github.com/ropensci/plotly/issues/1083

**Comment by rreusser** [comment]
The lack of hover labels on the right side of the plot might be an issue though. Does that seem fishy to anyone else? @etpinard?
