### ISSUE TITLE
boxplot points hover events

### ISSUE THREAD

**Issue by joshua-gould** [plotly/plotly.js#192]
It would be nice if hover events were fired for points rendered when drawing a boxplot

**Comment by mdtusz** [comment]
Could you share an example of your code (codepen/jsbin/jsfiddle) where this isn't working for you? A graph div with a box plot will emit a `plotly_hover` event that you can bind a function to like so:

``` js
var graphDiv = document.getElementById('graph-div');

graphDiv.on('plotly_hover', function(data){
  // do something with the emitted data here
});
```

**Comment by joshua-gould** [comment]
http://codepen.io/anon/pen/mVqQyY

When you hover any of the data points (not the box and whisker itself), I would like to show a tooltip corresponding to the text array.

**Comment by mdtusz** [comment]
@etpinard perhaps can chime in with more details on this.

**Comment by etpinard** [comment]
@joshua-gould that'd be a nice feature. Thanks for the suggestion!

I suspect making this happen will be tricky. But it could be a good opportunity to split up `graph_interact.js`

**Comment by joshua-gould** [comment]
One workaround is to create an additional scatter trace.

**Comment by ifll** [comment]
Recently I was seeking for the exact same feature.

If it were possible to have it the close future that would be very nice.

**Comment by MikeRixWolfe** [comment]
+1 for separate hover tool tips for the data points, my users would like to be able to hover the points for labels associated with the numerical data being plotted

**Comment by gfairchild** [comment]
I'd love this feature.

**Comment by etpinard** [comment]
Select/lasso dragmodes are coming to box trace soon; it might be good to tackle this ticket too.

To get this done, I'm thinking about adding a `hoveron` attribute to box trace (similar to scatter and scatterternary):

```js
// (default) this would corresponding to the current behavior
hoveron: 'boxes' 

// display hover labels for the visible boxpoints only
// this would support multiple labels per box and per traces 
// for hovermode 'x' and 'y'
hoveron: 'points' 

// both modes at the same time,
// where 'boxes' would take precedence when cursor is over a box
hoveron: 'points+boxes'
```

any thoughts on this @alexcjohnson @cldougl @chriddyp ?

**Comment by chriddyp** [comment]
👍  love this! `points+boxes` will be great, `hoveron` seems right to me.
I suppose that `hovermode` options could apply here as well (think horizontally stacked box plots with points)

**Comment by alexcjohnson** [comment]
Sounds great! `hoveron` and its values sound perfect. Only question is about:
> 'boxes' would take precedence when cursor is over a box

I'd probably have gone the other way, since the box is large and has a permissive hover region, give the points small hover regions (reuse the way scatter does it) but let them take precedence within that region.

**Comment by dejanskledar** [comment]
I have difficulties producing the implemented hover effect:
https://codepen.io/anon/pen/BwerzQ

What did I miss? I used the latest 1.32.1 version...

**Comment by etpinard** [comment]
@dejanskledar #2094 hasn't been released yet.

See changelog here: https://github.com/plotly/plotly.js/releases

**Comment by dejanskledar** [comment]
Oh, I misunderstood the 62 commits to master thinking that these commits are already included. Thanks.

**Comment by dejanskledar** [comment]
@etpinard Is there any other way to get the latest lib with #2094 included before the official release?

**Comment by etpinard** [comment]
@dejanskledar please ask questions of the likes on https://community.plot.ly/

Thanks.
