### ISSUE TITLE
Inconistent numeric format on logarithmic axis labels

### ISSUE THREAD

**Issue by AndiMD** [plotly/plotly.js#1920]
Hi all,

The following example shows inconsistent x-axis labels. 
Result: 10e+21, 100e+21, 1e+24, 10e+24, 100e+24, 1e+27
Expected: 1e+22, 1e+23, 1e+24, 1e+25, 1e+26, 1e+27

Can this be improved? Thanks!

```
<html>
<head> <script src="https://cdn.plot.ly/plotly-latest.min.js"></script> </head>
<body> 
<div id="TEST" class="plotly-graph-div"></div>
<script>
    window.PLOTLYENV=window.PLOTLYENV || {};
    window.PLOTLYENV.BASE_URL="https://plot.ly";
    Plotly.newPlot('TEST', [{"mode":"lines","y":[0.0,1.0],"type":"scatter","x":[1.0e22,1.0e27]}],
               {"xaxis":{"type":"log"},"margin":{"l":50,"b":50,"r":50,"t":60}}, {showLink: false});
</script>
</body>
</html>
```
CrossRef: [https://github.com/sglyon/PlotlyJS.jl/issues/132](https://github.com/sglyon/PlotlyJS.jl/issues/132)

**Comment by etpinard** [comment]
You might want to look at the `exponentformat` attribute:

https://plot.ly/javascript/reference/#layout-xaxis-exponentformat

I think for your use case, setting `exponentformat: 'power'` seems best:

**Comment by etpinard** [comment]
@AndiMD is `exponentformat: 'power'` giving you the desired result?

**Comment by alexcjohnson** [comment]
True, `exponentformat: 'power'` can fix it in this case - @AndiMD the default is `'B'` ie SI prefixes except for billion - but I do think there's a good argument to be made that continuing to round the exponent to a factor of 3 when we're beyond the range of SI prefixes (the range we've deemed common enough to use anyway, ie femto to tera) serves no purpose and can be misleading, so we can consider this a bug.
