### ISSUE TITLE
scattergl open markers require explicit line width

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#1921]
In regular scatter, you don't need to specify a line width to get default width 1 for open symbols:
```
Plotly.newPlot(gd,[{
  y: [1, 2, 3],
  marker: {symbol: 'circle-open', size: 20},
  type: 'scatter',
  mode: 'markers'
}], {width:400, height:400})
```
![screen shot 2017-07-31 at 4 14 21 pm](https://user-images.githubusercontent.com/2678795/28796376-50292830-760b-11e7-907f-bd8df81a2dd4.png)

But change this to `type: 'scattergl'` and the markers disappear until you put an explicit `line: {width: 1}` in `marker`.

Note that this is independent of the `marker.line.width` in `gd._fullData`, which is still `0` in the `scatter` example above. This means `supplyDefaults` doesn't need to care about `marker.symbol`, and importantly, if `marker.symbol` is an array, you can use closed symbols (with no line width) alongside open symbols (with default line width 1) without explicitly saying this is what you're doing.

cc @dfcreative @VeraZab

**Comment by etpinard** [comment]
@dfcreative 

```js
Plotly.newPlot(gd,[{
  y: [1, 2, 3],
  marker: {symbol: 'circle-open', size: 20},
  type: 'scattergl',
  mode: 'markers'
}], {width:400, height:400})
```

leads to 

![image](https://user-images.githubusercontent.com/6675409/34686008-39699f76-f478-11e7-9e1d-9a37df7e71b6.png)

off https://github.com/plotly/plotly.js/tree/rescatter-squashed-2018

Would you mind taking a look this before we release `regl`?

**Comment by dfcreative** [comment]
@etpinard @alexcjohnson thanks! Fixed by https://github.com/plotly/plotly.js/pull/2230/commits/320c4c9182fe88b065cc7bbd872d916239068c4d

**Comment by dfcreative** [comment]
Added mock in https://github.com/plotly/plotly.js/commit/7cefeabe81db683767707e3ca440e58e7492da34

**Comment by etpinard** [comment]
closed by https://github.com/plotly/plotly.js/pull/2258
