### ISSUE TITLE
issue when plot png image in phantomjs!

### ISSUE THREAD

**Issue by frh10** [plotly/plotly.js#1922]
hello!
    I use plotly.js,and plot svg string in phantomjs to get the renderd html.It runs fined!But when i plot table chart,i found the svg is very large because the table chart will create a png image and when run canvas.toDataURL('image/png')  in phantomjs will get a very large string.I knows there may be a bug in phantomjs when use toDataURL, there will be fixed by changing to canvas.toDataURL('image/jpeg'),or anyone who has better solutions?Thanks!

**Comment by etpinard** [comment]
@frh10 thanks for reaching out to us.

This discussion would be best for https://community.plot.ly/
