### ISSUE TITLE
How to decrease the padding between yaxis and first axis points ?

### ISSUE THREAD

**Issue by suribabu39** [plotly/plotly.js#1927]
https://codepen.io/suribabu_95/pen/Ojbmje?editors=0010

I want xaxis ticks to start without any padding(first data point should overlap with yaxis).

**Comment by etpinard** [comment]
Just set `xaxis.range` to the desired range: https://codepen.io/etpinard/pen/wqoyVM?editors=0010

Please use our https://community.plot.ly/ for questions of the likes in the future.
