### ISSUE TITLE
Parcoords image data spills from one graph to another

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#1929]
See https://codepen.io/etpinard/pen/brBKdy?editors=0010 where the `gl2d_parcoords_1` and `gl2d_parcoords_2` mocks are plotted side-by-side. Both `newPlot` calls are followed by `toImage`. The top row displays the interactive graphs (i.e. `newPlot` output) and the bottom row displays the `toImage` outputs. Now, notice that the `gl2d_parcoords_1` image has a few strokes that spilled over from `gl2d_parcoords_2`.

Fixing this we'll important for the image exporter where multiple `parcoords` graphs might be exported on the same page at the same time.

cc @monfera

**Comment by monfera** [comment]
@etpinard thanks for the clear, reproducible case, I'm on it!
