### ISSUE TITLE
Implement `autorange: "reversed"` in 3d 

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#1940]
https://codepen.io/cpsievert/pen/BdWePv

Discovered via https://github.com/ropensci/plotly/issues/1095

See also:
- https://community.plot.ly/t/reverse-z-axis-values/1817/3

**Comment by etpinard** [comment]
That thing was never implemented. Feature.

**Comment by vonplato** [comment]
I would also like this feature (particularly in R)

**Comment by alexcjohnson** [comment]
Bumping this to `bug` since you can set a reversed axis range (`scene.xaxis.range: [6500, 500]` eg [here](https://codepen.io/alexcjohnson/pen/gKLBgR?editors=0010)) and all the data disappears 😢

**Comment by alexcjohnson** [comment]
Alternatively, we could accomplish the same thing by specifying [right-hand-rule](https://en.wikipedia.org/wiki/Right-hand_rule) or left-hand-rule for the scene.
