### ISSUE TITLE
plotly.js typescript typings not compatible with 3dscatterplot

### ISSUE THREAD

**Issue by alanpurple** [plotly/plotly.js#1942]
an example code
https://plot.ly/javascript/3d-scatter-plots/

with using types/plotly.js

emits errors because typescript typing is not compatible

**Comment by etpinard** [comment]
By types/plotly.js, you mean https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15379 ?

If so, it's probably best to open up an issue there.

**Comment by alanpurple** [comment]
@etpinard thanks I posted here since I thought that repository was a general typing repository

**Comment by etpinard** [comment]
Ok. But we like keeping issues in the repo relevant to code in this repo. 

So, I'll merge your ticket with https://github.com/plotly/plotly.js/issues/28
