### ISSUE TITLE
A parcoords test is failing when running the full jasmine suite

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#1951]
Running `npm run test-jasmine` locally currently yields;

![image](https://user-images.githubusercontent.com/6675409/29317825-b5d468e8-819b-11e7-9872-fcbd3c63e582.png)

pointing to this parcoods [test](https://github.com/plotly/plotly.js/blob/fd54beebde20fb6b6e4bfcaa8a7270f3ec5312c3/test/jasmine/tests/parcoords_test.js#L660).

Note that the parcoords suite runs successfully in isolation - with `npm run test-jasmine -- parcoords`.

I wonder if this failure is due to a gl3d or gl2d shader program not getting cleaned up correctly.

Low priority, but cc'ing @monfera @dfcreative in case they have ideas.

**Comment by monfera** [comment]
@etpinard should we reorder tests so they start with `parcoords` and see what happens?

**Comment by etpinard** [comment]
We _could_, but they _should_ just work whatever the order.

**Comment by monfera** [comment]
Glad to look at it once the more urgent items are cleared; self-assigning but equally happy if @dfcreative has time to look at it earlier so feel free to reassign

**Comment by etpinard** [comment]
FYI, this is _maybe_ related to https://github.com/gl-vis/gl-axes3d/pull/11#issuecomment-310496878

**Comment by monfera** [comment]
@etpinard I'm wondering if this may be closed, not seeing the message pertaining to `parcoords` now. Maybe the `gl2d` / `gl3d` changes, eg. @dfcreative and you unbinding VAOs etc. there solved it. I see a lot of unrelated errors on several kinds of plots though, is it expected or is something up with my local setup?

**Comment by etpinard** [comment]
I haven't seen this test fail recently either. Probably fixed by upgrading from Chrome 60.
