### ISSUE TITLE
Yarn package manager install offline support

### ISSUE THREAD

**Issue by jmeberst** [plotly/plotly.js#1957]
I'm using the yarn package manager (v0.27.5) to install my modules including plotly offline behind a corporate proxy. mapbox-gl@0.22.1 has a dependency on two packages (mapbox-gl-shaders, and mapbox-gl-specs) that have been removed on github, and yarn won't correctly package them into the tgz files it uses for the offline registry.

**Comment by etpinard** [comment]
Nothing we can do until https://github.com/plotly/plotly.js/issues/1714 is :white_check_mark: 

Closing.
