### ISSUE TITLE
`hovermode: 'vline'`, `hovermode: 'hline'`

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.js#1959]
2 separate users have requested this type of hover mode in the Dash community forum. So, I thought I'd create an issue to collect further interest. 

https://community.plot.ly/t/vertical-line-on-hover/5321/3
![](https://cdn-standard.discourse.org/uploads/plot/original/2X/e/e212355b842063861061cadb9626a867dfb9623f.png)

https://community.plot.ly/t/capturing-mouse-events-position/4616/8
![](https://cdn-standard.discourse.org/uploads/plot/original/2X/d/d3827b8cd525b5f9b5111d4b93f1e336534043c5.gif)

Perhaps could be solved as part of https://github.com/plotly/plotly.js/issues/1847 (customized hover shapes) or just as a separate `hovermode`.

**Comment by alexcjohnson** [comment]
@chriddyp have you seen [`showspikes` and `spikemode: across`](https://github.com/plotly/plotly.js/pull/1461/files#diff-0e41c2e162564438ff091d0ed6b5b455R315)? A great community PR this spring from @rpaskowitz

**Comment by chriddyp** [comment]
Ah nice, I didn't see that. Thanks @alexcjohnson and @rpaskowitz !
