### ISSUE TITLE
Lasso selection with border and area color 

### ISSUE THREAD

**Issue by unvaiso** [plotly/plotly.js#1961]
Hi,

I think it would be wonderful if the lasso selection could be as aesthetic as below

![](https://cdn-standard.discourse.org/uploads/plot/original/2X/a/a29a50a1e2444121039d716aa9124bfbef7a5cfa.png)
Screeshot from Padmapper.com.

**Comment by alexcjohnson** [comment]
related: #1847

**Comment by monfera** [comment]
I don't currently see a screenshot or anim gif, maybe it was removed, it'd be neat to have it back here.

**Comment by monfera** [comment]
Closing this issue as #1847 discusses it in detail - please follow things over there.

**Comment by unvaiso** [comment]
updated
