### ISSUE TITLE
Feature Request: Add plotly event listeners to Mapbox layers

### ISSUE THREAD

**Issue by radumas** [plotly/plotly.js#1966]
I didn't realize this before but it seems there are two ways to add a layer to a mapbox map:
1. `Scattermapbox(lat=lats, lon=lons, etc.)`  ([ref](https://plot.ly/javascript/reference/#scattermapbox))
2. `layout(mapbox=(layers={source='data.geojson', sourcetype='geojson')` ([ref](https://plot.ly/javascript/reference/#layout-mapbox-layers))

Since the first option doesn't play well with Geojson (or [lines](https://github.com/plotly/plotly.js/issues/1960)), could plotly click, hover, select events be fired for layers created by the second option? 

My motivation for this is to be able to create layers (in python) from geojson or vector tile source, but be able to attach plotly interactivity to the geometries.

**Comment by etpinard** [comment]
Essentially done by adding `choroplethmapbox` in https://github.com/plotly/plotly.js/pull/3988

Please, let us know if you missed something.
