### ISSUE TITLE
Parallel coordinates: discrete legend instead of continuous colorbar

### ISSUE THREAD

**Issue by kernc** [plotly/plotly.js#1968]
Please add a feature to Parallel Coordinates plot to mark colorbar values as discrete (i.e. nominal) so that the colorbar renders as a legend (like in scatter plot) instead of continuous colorbar.

![screenshot - 05182017 - 07 49 37 pm](https://cloud.githubusercontent.com/assets/684364/26216098/2a5f3190-3c03-11e7-8e06-fc35371b9420.png)

**Expected:** some option to make it:

![plotly-parcoords-discrete-colorbar](https://user-images.githubusercontent.com/684364/29618540-cbb14676-8818-11e7-83f0-6e8dad66a5ab.png)

**Comment by etpinard** [comment]
> Please add a feature Parallel Coordinates

Thanks for writing in, but this won't be a priority for us in the near future. So don't get your hopes up.

**Comment by kernc** [comment]
No problem, just needed an issue to track. Hope it's still a legitimate feature request. Thanks.

**Comment by alexcjohnson** [comment]
related: #1785

**Comment by renatobellotti** [comment]
I'd like to see this as well. Would be quite useful in science.

**Comment by samthiriot** [comment]
This feature would be so nice. Parallel coordinate plots are especially good precisely because they allow to mix discrete and continuous!

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
