### ISSUE TITLE
Multiple y axes with scatter traces do not work correctly

### ISSUE THREAD

**Issue by alexmon** [plotly/plotly.js#1970]
Hi, 

i am trying to render a plot consisted of multiple y axes added dynamically by the user and each trace, trace's type is scatter, is bound to a y axis. 

Seems plotly.js doesn't support 'smart' rendering of multiple y axes out of the box as it appears on this post [https://community.plot.ly/t/multiple-y-axis-overlay-issue/5508/4](https://community.plot.ly/t/multiple-y-axis-overlay-issue/5508/4). Tried as suggested to use 'position' and 'domain' configurations but i couldn't make it work as seen on this codepen post [https://codepen.io/alexmon/pen/rzrxxJ](https://codepen.io/alexmon/pen/rzrxxJ). As you can see only the last trace is rendered.

Is this a wrong usage of the API or a bug?

Thank you for your time.
Alex

**Comment by etpinard** [comment]
> As you can see only the last trace is rendered.

Hmm. This is not what I'm seeing. Can you be more specific about what's not working for you?

**Comment by alexmon** [comment]
You were right, corrected [codepen](https://codepen.io/alexmon/pen/rzrxxJ) to display multiple traces assigned to a different y axis.

Uploading this screenshot to point a strange issue with newly added y axis:
![screenshot from 2017-08-30 12-31-07](https://user-images.githubusercontent.com/666086/29865852-4d81da1a-8d7f-11e7-8e88-282001e62f42.png)

- Why both y2 and y3 axes display a secondary overlapping y axis in black color? Is this a configuration error or a bug?

Thank you and I appreciate your time.
