### ISSUE TITLE
Map plot image download does not reflect current map scale/position

### ISSUE THREAD

**Issue by brian428** [plotly/plotly.js#1971]
When using downloadImage on a Map plot, the scale/position of the downloaded image is reset, and does not reflect the scale/position of the current map being displayed.

Repro case: https://codepen.io/brian428/pen/vJzGjg?editors=0010

Just zoom in and drag the map, hit the download image button, then open the image to see that it doesn't reflect the scale and position shown on the plot.

**Comment by etpinard** [comment]
This is caused by the same problem as https://github.com/plotly/plotly.js/issues/292 

Marking this as a duplicate.

**Comment by brian428** [comment]
Sounds good. Thanks, Étienne.
