### ISSUE TITLE
`showspikes: true` doesn't work if `showticklabels: false`

### ISSUE THREAD

**Issue by shogun70** [plotly/plotly.js#1977]
See https://codepen.io/anon/pen/mMvybw

My use case for this is when tick-labels for a "category" axis are too long or too numerous I want to hide the labels and show a bootstrap tooltip at the end of the spikeline. I use `hovermode: 'closest'` so I don't get the built-in `commonLabel` on hover.

I'm currently working around this issue using `tickfont.color: 'transparent'`instead of `showticklabels: false`.

**Comment by etpinard** [comment]
Thanks for the report.

Related: https://github.com/plotly/plotly.js/pull/1604

**Comment by shogun70** [comment]
Thanks, that was fast.

**Comment by etpinard** [comment]
Thanks for 10/10 bug report @shogun70 :ok_hand:
