### ISSUE TITLE
Uncentered Scattergl yaxis

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.js#198]
originally reported by @rminnett here: https://github.com/plotly/plotly.py/issues/391

***

> See the modified example from https://plot.ly/python/webgl-vs-svg/:
> ![image](https://cloud.githubusercontent.com/assets/1182698/12443371/4a4ba76a-bf0c-11e5-85fd-5b0ce8db1d49.png)

**Comment by etpinard** [comment]
Bug confirmed.

To fix:

- pass `textAlign: 'left'` [text-cache](https://github.com/gl-vis/text-cache/blob/master/textcache.js#L48) option from [gl-plot2d](https://github.com/gl-vis/gl-plot2d/blob/master/lib/text.js#L211)
