### ISSUE TITLE
labelfont, tickfont and rangefont string property

### ISSUE THREAD

**Issue by dy** [plotly/plotly.js#1983]
Now to set custom font for an axis we have to pass an object to `labelfont` property:
```js
Plotly.plot(document.body, {
  data: {
    ...
    labelfont: {family: 'Roboto, sans-serif'}
    ...
  }
})
```
What if instead we could just use string:
```js
Plotly.plot(document.body, {
  data: {
    ...
    labelfont: 'Roboto'
    ...
  }
})
```
[Plain css `font` string](https://developer.mozilla.org/en-US/docs/Web/CSS/font) would be so intuitive!

Also I would suggest introducing an alias for `labelFont` - that is easy to miss a letter.

**Comment by dfcreative** [comment]
Ok, seems to be problematic with existing [`coerceFont` implementation](https://github.com/plotly/plotly.js/blob/master/src/lib/coerce.js#L344), since we can't check which type of value passed.

**Comment by etpinard** [comment]
> Also I would suggest introducing an alias for labelFont - that is easy to miss a letter.

That's not going to happen, all plotly.js `"data"` and `"layout"` attribute are written in smashedtogether case with a few exception like `error_y` and `error_x`.

**Comment by etpinard** [comment]
@dfcreative that's an interesting idea and I don't think it would be that hard to implement.

We could just add check for `isPlainObject(attr)` [here](https://github.com/plotly/plotly.js/blob/fc5a73ae624b843d5ae53516e51d31ed576afbbc/src/lib/coerce.js#L349) in `coerceFont` and split `family`, `size` and `color` using a regex.

Now, down the road, we're planning on adding optional outline colors for fonts (see https://github.com/plotly/plotly.js/issues/1597) which wouldn't fit within the _css font_ realm. So, I'm having doubts adding another attribute-value pathway.

**Comment by etpinard** [comment]
This one most likely won't happen. Closing.
