### ISSUE TITLE
Surface plot - colorscale min max values

### ISSUE THREAD

**Issue by b-pos465** [plotly/plotly.js#199]
Hey guys,

great work so far. I really enjoy working with this well documented framework. I have one question:

Im trying to set a min and max bound for the colorscale so that all of the values below the min value will be colored in the colorscale min color and all values above the max value will be colored in the colorscale max value. I found the `zmax` and `zmin` attributes in the docs and it changes the labels at the colorscale, but the graph still looks the same. See this for example:

![newplot](https://cloud.githubusercontent.com/assets/9197649/12452486/edd79dc6-bf8e-11e5-8ade-b355f15593b6.png)
 
I except all of the values below 0.8 to be blue. Am I overlooking anything? Or is this feature just not available yet?

**Comment by etpinard** [comment]
This issue was fixed in [v1.4.0](https://github.com/plotly/plotly.js/releases/tag/v1.4.0), so please upgrade if you haven't.

If your problem persists, please provide a reproducible example as mentioned in the contributing guidelines:

> Bug reports must be accompanied with a reproducible example. We recommend using [codepen](http://codepen.io/), [jsfiddle](https://jsfiddle.net/) or [jsbin](https://jsbin.com) to share your example.

**Comment by b-pos465** [comment]
Thx ! It works now :)

**Comment by Amal-Vincent** [comment]
Is there a way to do the same on markers mode, I am struggling with that now
