### ISSUE TITLE
parcoords `pad` property missing from schema?

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.js#1990]
As reported here: https://community.plot.ly/t/tweaking-go-parcoords/5662/3

It looks like the `pad` isn't in the chart schema, and therefore isn't in the python API:
![image](https://user-images.githubusercontent.com/1280389/30125472-7a8cda5a-9306-11e7-917b-671a29e8c5fa.png)

cc @monfera

**Comment by monfera** [comment]
@chriddyp indeed, `pad` is not in `parcoords`, it was simply an omission as it was my 1st completely new chart and I overlooked some attributes. Some other usual attribs weren't added for expediency (several of them added later) or other reasons. I'll assign it to myself but if anyone else has capacity to take it earlier, depending on priorities, that's fine too.

**Comment by etpinard** [comment]
Why do need `pad` for parcoords? Should `layout.margin` suffice?

**Comment by chriddyp** [comment]
My bad, I thought that this property existed (as it was in the mocks) but just wasn't documented in the schema. Turns out the mocks were outdated.

**Comment by etpinard** [comment]
> Turns out the mocks were outdated.

Sounds like we should test that, if anyone feels like adding a syntax test.

**Comment by monfera** [comment]
@etpinard to clarify, `pad` is not present in a `parcoords` mock in `plotly.js` - it was in one of my codepen examples during development. I can probably just change the link there to point to an official mock.

**Comment by monfera** [comment]
^^ done with `Plotly.d3.json`.
