### ISSUE TITLE
gl3d doesn't render on Windows XP + Chrome 49

### ISSUE THREAD

**Issue by MichaelMonashev** [plotly/plotly.js#1992]
On page https://plot.ly/javascript/3d-scatter-plots/ I see "Webgl is not supported by your browser - visit http://get.webgl.org for more info" . But on https://get.webgl.org/ I see "Your browser supports WebGL" and rotating cube. I use Chrome browser.

Console:
```
plotly-latest.min.js:65 Uncaught TypeError: Cannot read property 'canvas' of undefined
i @ plotly-latest.min.js:65
a @ plotly-latest.min.js:65
r.plot @ plotly-latest.min.js:65
d @ plotly-latest.min.js:60
l.syncOrAsync @ plotly-latest.min.js:58
x.plot @ plotly-latest.min.js:60
x.newPlot @ plotly-latest.min.js:60
(anonymous function) @ pen.js:42
(anonymous function) @ plotly-latest.min.js:14
e @ plotly-latest.min.js:13
i @ plotly-latest.min.js:14
```

**Comment by alexcjohnson** [comment]
I have not been able to reproduce this. @MichaelMonashev can you say more? Which OS are you on? Which Chrome version?

One thing I do see is if I open https://plot.ly/javascript/3d-scatter-plots/ with Chrome/win7 on browserstack I get an odd color bug whenever my mouse is NOT over the plot:
![screen shot 2017-09-06 at 6 40 43 pm](https://user-images.githubusercontent.com/2678795/30137820-28f97522-9333-11e7-8792-49c824ac364e.png)
vs the expected:
![screen shot 2017-09-06 at 6 42 48 pm](https://user-images.githubusercontent.com/2678795/30137836-3a2d6fba-9333-11e7-8562-1dd34a459599.png)
Can someone with a similar setup check whether this is just a failure of browserstack or a real issue with Chrome on Windows?

**Comment by MichaelMonashev** [comment]
Windows XP
Google Chrome 49.0.2623.112 m

**Comment by etpinard** [comment]
> Windows XP
> Google Chrome 49.0.2623.112

I can replicate the problem on browserstack. Strangely, Chrome 49 on other Windows versions appears to work fine.

Changing the issue title accordingly.

**Comment by alexcjohnson** [comment]
Thanks @MichaelMonashev - confirmed in Chrome on XP. It looks though as if chrome has disabled WebGL (for security?) - see https://superuser.com/questions/958238/how-to-enable-webgl-on-chrome-on-xp. Version 49 is also fairly old at this point, but is apparently the last version to support XP (as well as Mac OS Mountain Lion and below).

I'm curious how https://get.webgl.org/ gets around this for you (when I try it in Browserstack I see "Hmm. While your browser seems to support WebGL, it is disabled or unavailable.") but I can't get `canvas.getContext('webgl')` to return anything. If you can figure out what it's doing (if there's some modification of `canvas.getContext` or similar that does work, for example) we could try to support it as long as it behaves the same way as a regular context.

**Comment by MichaelMonashev** [comment]
Thank you very match! This link: https://superuser.com/questions/958238/how-to-enable-webgl-on-chrome-on-xp is very useful. Now 3d-scatter-plots works good.
