### ISSUE TITLE
geo.scope='usa' with points outside USA gives console errors on hover

### ISSUE THREAD

**Issue by jackparmer** [plotly/plotly.js#1996]
https://plot.ly/~jackp/17904/

Change `geo.scope` to `north america` and hover works again

![image](https://user-images.githubusercontent.com/1865834/30245796-f21d0e10-95b2-11e7-8f6f-b5df0da3aa77.png)

**Comment by jackparmer** [comment]
Is `usa` for `geo.scope` only meant to be used for `choropleth`?

**Comment by etpinard** [comment]
> Is usa for geo.scope only meant to be used for choropleth?

Nop. https://plot.ly/~jackp/17904/ should work.

Thanks

**Comment by etpinard** [comment]
@jackparmer found a fix for this. Is this urgent? Or can it wait 1-2 weeks? If so, I'll include it only in my upcoming geo refactor PR.
