### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by piranna** [plotly/plotly.js#20]
Add a CLI tool that allow to generate the charts from command line without needing a web browser.

**Comment by etpinard** [comment]
plotly.js will remain a browser-only app for the foreseeable future.

I'd recommend including plotly.js into a Desktop runtime like [nw.js](https://github.com/nwjs/nw.js) or [electron](https://github.com/atom/electron) to generate images.

**Comment by chriddyp** [comment]
@piranna - alternatively, https://plot.ly provides APIs for image generation and hosting of `plotly.js` graphs. 
Here's an example with the [plotly nodejs api client](https://github.com/plotly/plotly-nodejs):
```js
var plotly = require('plotly')('username','apiKey');
var fs = require('fs');

var trace1 = {
  x: [1, 2, 3, 4],
  y: [10, 15, 13, 17],
  type: "scatter"
};

var figure = { 'data': [trace1] };

var imgOpts = {
    format: 'png',
    width: 1000,
    height: 500
};

plotly.getImage(figure, imgOpts, function (error, imageStream) {
    if (error) return console.log (error);

    var fileStream = fs.createWriteStream('1.png');
    imageStream.pipe(fileStream);
});
```

and from the [python plotly client](https://plot.ly/python):
```python
import plotly.plotly as py
py.image.save_as({
    "data": [{"x": [1, 2, 3], "y": [4, 2, 5]}],
    "layout": {"title": "example image"}}, 'example.png')
```

**Comment by piranna** [comment]
What I'm interested for is to create a [GitBook](https://www.gitbook.com/) plugin to generate the graphs offline. Usage of PhantomJS is an option (it's already being used by [mermaid plugin](https://github.com/JozoVilcek/gitbook-plugin-mermaid), for example), but since Plotty.js generates SVG images (that are plain text) I don't thing a renderer is needed...
