### ISSUE TITLE
Scattergl ignoring fixedrange=False axis option

### ISSUE THREAD

**Issue by rminnett** [plotly/plotly.js#200]
Using code similar to https://github.com/plotly/plotly.js/issues/198, note the added fixedrange options and the ability to pan vertically in the Scattergl plot, but not the Scatter plot:

![image](https://cloud.githubusercontent.com/assets/1182698/12457256/6d832900-bf58-11e5-9cae-7bb2e5e94e31.png)

**Comment by etpinard** [comment]
@rminnett the plotly.js scattergl isn't quite on par with its svg counterpart.

Please read through https://github.com/plotly/plotly.js/issues/130 before opening new issues.

**Comment by rminnett** [comment]
Ah, ok, thanks! Perhaps the documentation at https://plot.ly/python/reference/#scattergl could list the known limitations (unless I missed it somewhere) or point to https://github.com/plotly/plotly.js/issues/130?
