### ISSUE TITLE
Text should contribute to autorange calculations

### ISSUE THREAD

**Issue by RedShift1** [plotly/plotly.js#2000]
When drawing a scatter plot with
`{ mode: 'lines+markers+text', fill: 'tonexty' }`
or
`{ mode: 'lines+markers+text', fill: 'tozeroy' }`

the text of the first point and the last point is cut off:

![plotly_filled](https://user-images.githubusercontent.com/3098010/30363974-8ba93368-9862-11e7-82d2-58fcebd29552.png)

JSFiddle: https://jsfiddle.net/sd7drgph/

**Comment by alexcjohnson** [comment]
[Known issue](https://github.com/plotly/plotly.js/blob/master/src/plot_api/plot_api.js#L268) but doesn't look like we have an issue for it - thanks for bringing this up @RedShift1 

I was going to suggest `cliponaxis: false` #1861 (your leftmost text item would overlap the tick labels but at least would be visible) but I notice that has problems with date axes... another bug report coming :)

**Comment by alexcjohnson** [comment]
Merging #2001 -> ensure our solution works for both scatter and bar traces.

**Comment by etpinard** [comment]
This would be a nice addition post https://github.com/plotly/plotly.js/issues/2704

**Comment by emilykl** [comment]
still an issue
