### ISSUE TITLE
sanitize all subplot attribute names

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#2007]
From @etpinard in https://github.com/plotly/plotly.js/pull/1999#discussion_r138750557 - we've added a lot of stuff and not all of it is handled equivalently in `cleanLayout` / `cleanData`. Do we want to?

> We should perhaps try to sanitize all subplots attribute names in `cleanLayout`. Looks like we only sanitize cartesian, gl2d and gl3d axes at the moment.

**Comment by etpinard** [comment]
Closing. Probably not worth adding more to `cleanData` and `cleanLayout` at this stage if we're planning on :hocho: them in v2.
