### ISSUE TITLE
`range` doesn't work on `rangeslider`

### ISSUE THREAD

**Issue by colinfang** [plotly/plotly.js#2012]
https://codepen.io/colinfang/pen/xXZVxO

I would expect the rangeslider zoom in to range `[2, 3]` by default. However it seems there is no effect

```javscript
var data =
{
  'x': [1, 2, 3, 4],
  'y': [2, 1, 3, 4],
}

var layout =
{
  'xaxis': {
    'rangeslider': {
      'range': [2, 3]
    }
  }
};

Plotly.plot('graph', [data], layout);
```

**Comment by etpinard** [comment]
Try https://codepen.io/etpinard/pen/BwjKmM?editors=0010

and please use https://community.plot.ly/ for questions of the likes in the future.

**Comment by colinfang** [comment]
Sry my bad. I was confused about the meaning of  `range` under `rangeslider`.
