### ISSUE TITLE
Legend toggles visibility of all groupby groups

### ISSUE THREAD

**Issue by rreusser** [plotly/plotly.js#2013]
Observed: clicking group toggles visibility of all groups.

Expected: clicking group in legend toggles only that group.

![28334288-b0330298-6bc8-11e7-9d1b-49fcfe7d4f83](https://user-images.githubusercontent.com/572717/30554069-7b0f286c-9c60-11e7-8b0b-68c2750da27d.gif)

**Comment by rreusser** [comment]
A simple reproducible example:

https://codepen.io/rsreusser/pen/PJZWQq

What is the desired behavior here? @cldougl says there have been some complaints about this, so seems worth addressing. Should groupby simply not set the legendgroup? Or should there be an option not to set the legendgroup? Does the legendgroup do anything apart from linking visibility? Final question: is there any existing way around this?

**Comment by alexcjohnson** [comment]
@etpinard may have more to say about this, but I don't think we have a way around this right now, and I suspect we only set `legendgroup` originally because we didn't have a way to address the groups independently. But with the generic `styles` attribute it should be doable with explicit groupby handling, similar to #1919.

**Comment by etpinard** [comment]
> Should groupby simply not set the legendgroup?

Hmm. Where is this set? 

I'm only seeing this [block](https://github.com/plotly/plotly.js/blob/master/src/components/legend/draw.js#L412-L425).

**Comment by rreusser** [comment]
My mistake regarding `legendgroup`. Upon thinking about it, that's a bit of an oversimplification. I set it aside for a moment when I got hung up on testing, but almost have a PR ready that applies the containerArray trick to set this in group-specific styles.

**Comment by rreusser** [comment]
Fixed in #2022. /cc @cldougl
