### ISSUE TITLE
Scatter text automatic colour

### ISSUE THREAD

**Issue by slishak** [plotly/plotly.js#2018]
When plotting a scatter with mode 'lines+markers' with no colour specified (i.e. automatic sequential colouring), both the lines and the markers have the same colour. When extending this to 'lines+markers+text', the markers and lines are still the same colour but the text is always black.

At the point I'm defining the scatter, I don't know what colour the line will be (as I'm relying on plotly to do this for me).

Is there any way to make the text the same colour as the lines and markers when the actual colour is not user-specified?

**Comment by alexcjohnson** [comment]
No, there's no way to do this. I can only suggest setting these colors manually. If you want to use Plotly's defaults (glad you like them!) I don't believe they're exposed anywhere normally but you can grab them from [here](https://github.com/plotly/plotly.js/blob/cb5a465ff6a17f0943b22f52c590dd07f60ee524/src/components/color/attributes.js#L13-L24).

In principle we could add this as a feature (`textfont.color: 'inherit'`?), but it strikes me as a fairly uncommon edge case - most of the time it seems to me you *need* text to have a different color so it's still legible when it overlaps other markers/lines.

**Comment by slishak** [comment]
I do like the default colours - and I think my solution might be to grab them from that link, thanks for that.

For a bit more information on my use case, I'm using Dash (my new favourite toy) to build a tool that allows the user to interactively plot families of parametric curves {x=u(t), y=v(t)}, and I'd like to annotate the parameter value at a few pre-determined points along each curve. When the curves approach and overlap it would be neater if each text label was easily associated with its line/marker by colour.

**Comment by etpinard** [comment]
Request like this one come up quite frequently.

Maybe we should output the default trace color sequence in `Plotly.PlotSchema.get()` - which would make it accessible to the python and R APIs.

**Comment by etpinard** [comment]
> Maybe we should output the default trace color sequence in Plotly.PlotSchema.get()

After the colorway PR (-> https://github.com/plotly/plotly.js/pull/2156), users can now grab the default trace color sequence with:

```
Plotly.PlotSchema.get().layout.layoutAttributes.colorway.dflt
```
