### ISSUE TITLE
Isolating a trace makes visible:false traces visible:legendonly

### ISSUE THREAD

**Issue by rreusser** [plotly/plotly.js#2019]
**Expected**: isolating a trace preserves `visible: false` status of hidden traces

**Observed**: isolating a trace changes `visible: false` traces to `legendonly`

**Version**: `plotly-latest.js`

See: https://codepen.io/rsreusser/pen/qPZNqo

![legend-isolate](https://user-images.githubusercontent.com/572717/30607954-ab6fc9dc-9d2b-11e7-8ed1-159ccf086209.gif)

I think the fix is straightforward. Seeking confirmation on expected behavior.

**Comment by etpinard** [comment]
> Expected: isolating a trace preserves visible: false status of hidden traces

I agree 100%.

**Comment by rreusser** [comment]
Thanks! Fixing that along with the groupby fixes.

**Comment by etpinard** [comment]
done in https://github.com/plotly/plotly.js/pull/2022
