### ISSUE TITLE
yaxis: { showticklabels: false } has no effect on parcoords

### ISSUE THREAD

**Issue by zax-slaughter** [plotly/plotly.js#2034]
Tick labels are present with
var layout = { yaxis: { showticklabels: false } };
Plotly.plot('graphDiv', data, layout);

https://jsfiddle.net/zk32Ln27/2/

Doesn't seem like expected behaviour to me.

**Comment by etpinard** [comment]
Parcoord trace have no `yaxis`. That's why it doesn't _work_.

See https://plot.ly/javascript/reference/#parcoords-tickfont

and please use https://community.plot.ly/ for questions of the likes in the future.
