### ISSUE TITLE
Adding suffix to values in pie chart on hovering

### ISSUE THREAD

**Issue by suribabu39** [plotly/plotly.js#2035]
I want to add a suffix(lets say '$') to all the values in pie chart while showing them on hovering. I definitely can't add it to the actual data (values attribute in data object) because it won't plot the chart. I also can't use text attribute because I am already using for something else(which is hiding percentages of values less than 1% because I don't want to show all the values as it doesn't look good). I also tried hoverformat but it's not working. Is there any away to add suffix to values on hovering?
https://codepen.io/suribabu_95/pen/yzgyae?editors=1011
Thanks in advance

**Comment by etpinard** [comment]
Here's how to do it with custom `text` and `hovertext`: https://codepen.io/etpinard/pen/QqdweG?editors=0011

Please use https://community.plot.ly/ for questions of the likes in the future, so that other users can benefit from it. Thanks.

**Comment by suribabu39** [comment]
From next time onwards I'll use  https://community.plot.ly/ 
I cannot open the codepen link (codepen website is down I think)
So can you please add that piece of code in the comments 
Thanks

**Comment by etpinard** [comment]
```js
var dataVal = [190, 260, 550,7, 5, 3, 1];
var labels = ['slice1', 'slice2', 'slice3','slice4','slice5','slice6','slice7'];
var total = 0;

var text = [];
var hoverText = [];

for(var i=0;i<dataVal.length;i++){
  total = total + dataVal[i];
}
for(var i=0;i<dataVal.length;i++){
  var percent = dataVal[i]*100/total >= 1 ? (dataVal[i]*100/total).toFixed(1).toString()+'%' : '';
  
  text.push(`${percent}`)
  
  hoverText.push(`
  ${labels[i]}<br>
  ${dataVal[i]}$<br>
  ${percent}`)
}

var data = [{
  values: dataVal,
  labels: labels,
  type: 'pie',
  textinfo: 'text',
  text: text,
  hoverinfo: 'text',
  hovertext: hoverText
}];

var layout = {
  height: 400,
  width: 500
};

Plotly.newPlot('myDiv', data, layout);
```
