### ISSUE TITLE
Could the lib provide the minified file of `plotly-geo-assets.js`?

### ISSUE THREAD

**Issue by sufuf3** [plotly/plotly.js#2036]
Hi @alexcjohnson  ,
I'm a member of [cdnjs](https://github.com/cdnjs/cdnjs/). We are going to host this library.
Could you provide the minified file of `plotly-geo-assets.js`?

If you have any suggestions, please let me know.

Thank you.
CC @maruilian11

cdnjs/cdnjs#11504

**Comment by etpinard** [comment]
It's here: https://raw.githubusercontent.com/plotly/plotly.js/master/dist/plotly-geo-assets.js

**Comment by sufuf3** [comment]
@etpinard Thanks.
Actually, I mean https://raw.githubusercontent.com/plotly/plotly.js/master/dist/plotly-geo-assets.min.js that I'd like to add it on CDNJS.
Could you provide it?
Thank you.

**Comment by etpinard** [comment]
`plotly-geo-assets.js` is already as minified as it gets. We could run it through a minifier to shave off a few dozen bytes, but that's hardly worth it in my mind.

If you absolutely need to a _minified_ version, please consider making a PR. No plotly.js dev will spend time on this. Thank you.

**Comment by sufuf3** [comment]
@etpinard thank you for your response.
I think we can do this on CDNJS.
Many thanks.
