### ISSUE TITLE
RAF loop blocks interaction in gl plots.

### ISSUE THREAD

**Issue by rreusser** [plotly/plotly.js#2039]
SVG needs interactions disabled during animation since the transforms get too difficult to manage. WebGL plots do not. Opening this issue to track progress on re-enabling. It won't be perfect since a plot context does not need to be *strictly* webgl xor svg, but we can at least improve the situation.

**Comment by rreusser** [comment]
Oh. It's not disabled at all. :/ It simply doesn't work since it continuously resets the axis range every time it draws, *unless* a mouse-up event commits it before the next frame.

**Comment by etpinard** [comment]
Moved to https://github.com/plotly/plotly.js/issues/3759
