### ISSUE TITLE
scattergeo hoverinfo breaks when it's an array

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#2044]
https://codepen.io/cpsievert/pen/NagamG

Discovered via https://github.com/ropensci/plotly/issues/1127

**Comment by etpinard** [comment]
Should be an easy fix. I'll try to include in `1.31.0`.

**Comment by etpinard** [comment]
Oh wait, you have `hoverinfo` as an array (not `hovertext` like a I was expected - I must be going blind :eyeglasses: ). That's not _supposed_ to work. 

`hoverinfo` is flaglist attribute. Setting it to `"lon+lat"` gives the desired behavior:

https://codepen.io/etpinard/pen/veZRLw?editors=0010

**Comment by cpsievert** [comment]
Why, then, would `arrayOk` be `true`?

![screen shot 2017-09-29 at 1 57 43 pm](https://user-images.githubusercontent.com/1365941/31031465-3cba5778-a51e-11e7-894e-60b42f59f9cf.png)

**Comment by etpinard** [comment]
Oh sorry, I'm not going blind, but I might have Alzheimer's disease.

I forgot about https://github.com/plotly/plotly.js/pull/1761 - which didn't bother testing any geo traces. On it.
