### ISSUE TITLE
Latest version on CDN is 1.30.0 - 1.30.1 is missing

### ISSUE THREAD

**Issue by s-m-e** [plotly/plotly.js#2047]
https://cdn.plot.ly/plotly-latest.min.js points to 1.30.0, https://cdn.plot.ly/plotly-1.30.1.min.js will give an HTTP 403. 

(I am using a script to pull the latest version from your CDN based on the latest release tag on GitHub. The above breaks it.)

**Comment by etpinard** [comment]
Fixed. Thanks for letting us know.
