### ISSUE TITLE
Custom data item aren't included in pie trace event data

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#2048]
See https://codepen.io/anon/pen/OxjXWP?editors=0011

First reported in https://community.plot.ly/t/customdata-for-pie-chart-is-undefined/6021

Bug from https://github.com/plotly/plotly.js/pull/1770

**Comment by etpinard** [comment]
Oh pie hover is a big mess (cc https://github.com/plotly/plotly.js/issues/1456). 

Unfortunately, I'll have to punt this out of my TODO list for `1.31.0` :football:

**Comment by alexcjohnson** [comment]
Fixed in #2117
