### ISSUE TITLE
Something is up with bar autorange with y minute-precision data on date axes

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#2049]
See https://codepen.io/etpinard/pen/mBMgLR

First reported in https://community.plot.ly/t/bar-chart-axis-not-showing-duration-properly-line-chart-does/5990/

**Comment by etpinard** [comment]
Back at `v1.18.1` we had:

![image](https://user-images.githubusercontent.com/6675409/31082737-b381ab68-a75d-11e7-8e06-e626f10507dd.png)




https://codepen.io/etpinard/pen/borJjL

**Comment by alexcjohnson** [comment]
Nothing to do with the precision, we're just showing the full bar now (down to the "zero" of dates ie 1970) and we weren't before. Seems like an easy fix to replace the old behavior, leaving aside the fact that this is a strange way to use a bar chart, and has some other odd side-effects - like if you set y before 1970 it'll be an upside-down bar - I guess if we want to support this we should really have the bars extend down to `-Infinity`?
