### ISSUE TITLE
Plotly resizes incorrectly

### ISSUE THREAD

**Issue by t0mm13b** [plotly/plotly.js#205]
This issue has come up with latest version of plotly.js v1.4.1

Below, is a plotly consisting of three data kinds, bar and two scatter

![plotlybefore](https://cloud.githubusercontent.com/assets/424531/12495201/4a0e4552-c086-11e5-9011-0e2336d675b4.png)

After that, more data comes in, using scatter and markers, using the in-built symbol types, 'cross' and 'circle'. 

```javascript
var graph = document.getElementById('graph');
var graphData = graph.data;
// Code to process and iterate through the bar data to position the markers
var plotDataOne = { x: xValsOne, y: yValsOne, mode: 'markers', type: 'scatter', marker: { color: markersOne, size: 12, symbol: 'circle' } };
var plotDataTwo = { x: xValsTwo, y: yValsTwo, mode: 'markers', type: 'scatter', marker: { color: markersTwo, size: 12, symbol: 'circle' } };
graphData.push(plotDataOne);
graphData.push(plotDataTwo);
Plotly.redraw(graph).then(function(){
    console.log('Additional data added to plotly!');
});
```

![plotlyafter](https://cloud.githubusercontent.com/assets/424531/12495200/4a0ae0ce-c086-11e5-9a6f-10fd984ff508.png)

The bars got resized, was expecting the bars to remain as shown in the first image, with the markers placed in the appropriate spot.

Any advice would be appreciated.

**Comment by etpinard** [comment]
I believe this the intended behaviour (although I'll have to double checked to be sure).

But in the meantime, here's an explanation and a workaround:

plotly.js -- by default -- expands the axis ranges for scatter traces with mode `'markers'`. So the fact that the range of your x-axis increased is not surprising.

If you'll like to keep the original x-axis range, you can turn off the auto-range algorithm in your `redraw` call with:

```js
graphData.layout.xaxis.autorange = false;
``` 

I hope this helps.

**Comment by t0mm13b** [comment]
Many thanks for the response. :+1: 

Had to specify it twice, in the first plotting of the data pulled in from remote end-point, `autorange: false' in the `layout` and in the second pull of the data to plot in the markers for the second plot as indicated by your one-line code in previous comment.

Thanks again :) 

Any plans to enable panning and zooming using two fingers on mobile devices which is something I have made attempts to do, it did turn out to be fiddly though using plotly modebar, for the record, using plotly.js and Ionic framework combined together to achieve a data-driven type of application.

**Comment by etpinard** [comment]
> Any plans to enable panning and zooming using two fingers on mobile devices which is something I have made attempts to do,

Not in the short term I'm afraid. plotly.js is definitely not a mobile-first graphing library.
