### ISSUE TITLE
Allow dot tick markers on the axes type: feature

### ISSUE THREAD

**Issue by ricazhang** [plotly/plotly.js#2051]
For example: 
![dot tick marks](https://user-images.githubusercontent.com/7819877/31101924-ae022be6-a784-11e7-81f4-d44fde6a08aa.PNG)

**Comment by alexcjohnson** [comment]
@ricazhang interesting, not a style I've ever seen before, what's the motivation for it?

We would happily accept a pull request adding this feature.

**Comment by alexcjohnson** [comment]
@ricazhang here's a hacky way to get the effect you want, using unicode symbols. As tick marks are supposed to guide the eye along a line to data points, and circles subvert that goal, I might be inclined to leave it at this hack.

```js
Plotly.newPlot(gd, [{x:[2010, 2013, 2016, 2019], y: [0, 5, 2, 7]}], {
    xaxis: {tickprefix: '\u25cf<br>', color: '#888'},
    yaxis: {ticksuffix: ' \u25cf', color: '#888'},
    width: 600, height: 400
})
```
![screen shot 2017-10-08 at 12 13 34 am](https://user-images.githubusercontent.com/2678795/31313866-2fd5314e-abbe-11e7-9e6f-e6c1541550ce.png)

**Comment by ricazhang** [comment]
Awesome, thanks for the suggestion!
