### ISSUE TITLE
Unification of text rendering and wrapping

### ISSUE THREAD

**Issue by monfera** [plotly/plotly.js#2053]
This issue is a spinoff of the `table` [PR](https://github.com/plotly/plotly.js/pull/2052#discussion_r142493868)

Currently, text rendering logic is not centralized - most of it is in `svgUtils.convertToTspans` but the new `table` plot type has wrapper logic, which does a few things, for example:

- wraps text to a specific width
- bypasses expensive logic (in this case, the entire `svgUtils.convertToTspans`) if there's no need

and `table` would do other things if it could, such as

- caching of resulting DOM fragments
- canceling pending asynchronous requests

This issue is the basis for a follow-up PR in which

- core: code unification is covered
- core: wrapping is made available centrally (individual plots will still need to specify constraints so it doesn't on its own turn all plots wrap-aware)
- core: avoid bypass of the heavy logic if there's no styling, markup or LaTeX
- core: take a look at KaTeX (perhaps it'd be a separate ticket on its own)
- core: optimize the number of getBoundingClientRect calls; convert to `Drawing.bBox`
- desirable: separation of code to logic (calculation) and rendering
- desirable: facilitating caching
- desirable: facilitating request cancelation

**Comment by monfera** [comment]
Self-assigning for now to keep tabs during PR review; feel free to reassign

**Comment by etpinard** [comment]
cc https://github.com/plotly/plotly.js/issues/382 and https://github.com/plotly/plotly.js/issues/1964

**Comment by luisrudge** [comment]
not sure this is the right place to ask, but would the implementation of this issue fix this glitch?

![image](https://user-images.githubusercontent.com/941075/47828457-ffeba680-dd61-11e8-8240-02ee0a311c10.png)

I'm already using `automargin:true` but the axis gets cropped anyway.

**Comment by jensb** [comment]
Is this still a relevant issue, and if so, is anything done to fix this?
I'd like to have scatter plot annotations with a fixed (set) width which autowrap text if it is too wide.
Ideally, the width should be settable by dragging the right margin of the annotation box.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
