### ISSUE TITLE
Open items for future PRs related primarily to `table`

### ISSUE THREAD

**Issue by monfera** [plotly/plotly.js#2056]
- [ ] add event callbacks to `table` https://github.com/plotly/plotly.js/pull/2052#discussion_r142450559 including plotly_hover and plotly_click events on the cells https://github.com/plotly/plotly.js/pull/2052#issuecomment-333874540
- [x] roll back `gup` utils to `parcoords`: https://github.com/plotly/plotly.js/pull/2052#discussion_r142444229
- [x] get rid of camelcased classnames (use dashed) and put all classnames into `constants.js`: https://github.com/plotly/plotly.js/pull/2052#discussion_r142415494
- [ ] discuss and plan cell editing and possibly other related functionality ([request](https://github.com/plotly/plotly.js/pull/2052#issuecomment-333874540), [reply](https://github.com/plotly/plotly.js/pull/2052#issuecomment-333992189))
- [ ] represent full `table` state via attributes (in) and callbacks (out) such that users can specify and/or receive, in logical units (row item) where we are in scrolling; similar full state representation for other interactions such as column drag&drop https://github.com/plotly/plotly.js/pull/2052#issuecomment-333949519
- [ ] put back `valign` (used to be there but needs a bit of work to handle cases of LaTeX etc.)
- [ ] do more to avoid wrapping: initial render should try to render straight away (no wrapping) and iff it breaches constraints, wrapping is invoked - this makes the current 2-step process into a 3-step process but CPU upside is big if no or few cells need wrapping (worth optimizing for the plainer case and negligible cycle loss even in the worst case)
- [ ] support individual border lines in addition to boxes; maybe border collapse?
- [x] Support for 1D header values https://github.com/plotly/plotly.js/pull/2052#discussion_r142827253
- [x] Better handling of MathJax fill color styling https://github.com/plotly/plotly.js/pull/2052#discussion_r142469257
- [ ] Support `header.format` scalar value https://github.com/plotly/plotly.js/pull/2052/files#r142410512
- [x] Reuse `plots/font_attributes.js` https://github.com/plotly/plotly.js/pull/2052/files#r142410981
- [x] Move `<clipPath>` to `fullLayout._clips` https://github.com/plotly/plotly.js/pull/2052/files#r142418318
- [ ] Jasmine tests
- [x] Checking for render glitch (high speed scrolling and then stopping) and fixing it (issue found by @rreusser )
- More `defaults.js` logic to let users make do with fewer `attributes`, for example, 
  - [x] `lines` shouldn't be needed, 
  - [ ] missing values (fewer or shorter vectors) could be filled with ""
  - [ ] cell heights should have the minimum of 2x the lowest font height in the row
- <strike>[ ] Fix scrollwheel scrolling issues in IE and FF</strike> **now in** https://github.com/plotly/plotly.js/issues/3986 
- [ ] At least one more mock
- [X] Fix `dominant-baseline` / `alignment-baseline` related issues found by @alexcjohnson 
- [ ] Look into the vertical alignment issue on CI in cells with wrapped text (looks fine in the wild; issue found by @alexcjohnson ) or await the switch to the Electron based tester by @etpinard

**Comment by etpinard** [comment]
@monfera Ok if I change the issue title to _table open items_? There's probably going to be a few other ones.

**Comment by monfera** [comment]
PR https://github.com/plotly/plotly.js/pull/2064 in for "Checking for render glitch"

**Comment by monfera** [comment]
"Better handling of MathJax fill color styling" was done in the original PR

**Comment by monfera** [comment]
PR https://github.com/plotly/plotly.js/pull/2065 for "Roll back gup utils to parcoords" (also, Sankey)

**Comment by monfera** [comment]
PR https://github.com/plotly/plotly.js/pull/2067 for "Get rid of camelcased classnames (use dashed) and put all classnames into constants.js"

**Comment by monfera** [comment]
@etpinard is there anything special to pay attention to, when putting the clippaths into `fullLayout._clips`? An aside: does it serve a technical goal, or is it more of a structuring convention?

**Comment by rreusser** [comment]
@monfera This perhaps: https://github.com/plotly/plotly.js/blob/master/src/components/drawing/index.js?utf8=%E2%9C%93#L759-L779

**Comment by monfera** [comment]
"Move <clipPath> to fullLayout._clips" - discussed that it's deferred until further discussion

**Comment by monfera** [comment]
PR #2070 covers "Reuse plots/font_attributes.js"

**Comment by monfera** [comment]
PR #2072 is for "Support for 1D header values"

**Comment by monfera** [comment]
@rreusser thanks! `setClipURL` was already in the `table` merge. There are a few distinct things re clipping:

1. Ensure that clip paths are globally unique on the page (yesterday)
2. As a matter of `plotly.js` convention, use a specific utility `setClipURL` for assigning the `clip-path` property (yesterday)
3. Use a common key function on both the `<clipPath>` id and the `setClipURL` so the key link can't get out of sync (I just made this up but also followed it)
4. Attach the clippath not to its normal place in the scenegraph, but to a distinguished node `fullLayout._clips` - it's a PR feedback item above but Étienne OKd we defer it as it'd lead to avoidable complications

**Comment by monfera** [comment]
More defaults logic PR 1: https://github.com/plotly/plotly.js/pull/2074

**Comment by monfera** [comment]
"Fix dominant-baseline / alignment-baseline related issues found by @alexcjohnson" covered in https://github.com/plotly/plotly.js/pull/2076

**Comment by etpinard** [comment]
More ideas:

- [ ]  Creating frozen columns (similar to header - but for columns) cc #3705

**Comment by jackparmer** [comment]
This issue has been tagged with `NEEDS SPON$OR`

A [community PR](https://github.com/plotly/plotly.js/pulls?q=is%3Apr+is%3Aopen+label%3A%22type%3A+community%22) for this feature would certainly be welcome, but our experience is deeper features like this are difficult to complete without the Plotly maintainers leading the effort.

**Sponsorship range: $25k-$30k**

What Sponsorship includes:
- Completion of this feature to the Sponsor's satisfaction, in a manner coherent with the rest of the Plotly.js library and API
- Tests for this feature
- Long-term support (continued support of this feature in the latest version of Plotly.js)
- Documentation at [plotly.com/javascript](https://plotly.com/javascript/)
- Possibility of integrating this feature with Plotly Graphing Libraries (Python, R, F#, Julia, MATLAB, etc)
- Possibility of integrating this feature with Dash
- Feature announcement on [community.plotly.com](https://community.plotly.com/tag/announcements) with shout out to Sponsor (or can remain anonymous)
- Gratification of advancing the world's most downloaded, interactive scientific graphing libraries (>50M downloads across supported languages)

Please include the link to this issue when [contacting us](https://plotly.com/get-pricing/) to discuss.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
