### ISSUE TITLE
Code style rework: class names; extracted utils

### ISSUE THREAD

**Issue by monfera** [plotly/plotly.js#2058]
This issue originates from the `table` PR review, requesting these items:

- roll back `gup` utils to `parcoords`: https://github.com/plotly/plotly.js/pull/2052#discussion_r142444229
-

**Comment by etpinard** [comment]
Can you merge this thing in https://github.com/plotly/plotly.js/issues/2056 ?

**Comment by monfera** [comment]
Closing it in favor of https://github.com/plotly/plotly.js/issues/2056 for less granular issue creation.
