### ISSUE TITLE
Error_x opacity not works with scatter and color defined

### ISSUE THREAD

**Issue by ricardovb** [plotly/plotly.js#2059]
If I set different colors and opacities both to the error_x and error_y on scatter plot the opacity is dismissed/omited on error_x. Also if i only apply color and opacity to error_y the error_x inherits the error_y configuration.

**Comment by etpinard** [comment]
Can you please share a reproducible example?

**Comment by ricardovb** [comment]
Hi @etpinard , as you can see in the given example, the error_x opacity -> :0.01, is ignored, also you can play setting or not the color attribute for error_x and/or error_y to see how error_x render config looks inherited from error_y.

Plotly.newPlot('graph', [{"type":"scatter",
                          "x":[0.016,0.0116,0.0195,0.019,0.0214,0.028,0.014],
                          "y":[0.9121,0.9217,0.9351,0.8814,0.8756,0.876,0.8904],
                          "mode":"markers",
                          "error_x":{"type":"data",
                                     "array":[0.005,0.0044,0.006,0.0062,0.0066,0.008,0.0054],
                                     "opacity":0.01,
                                     "color":"#00ff00"},
                          "error_y":{"type":"data",
                                     "array":[0.0136,0.0138,0.0142,0.0141,0.0139,0.0141,0.014],
                                     "opacity":0.5,
                                     "color":"#ff0000"}
                         }], 
                        {"title":"Title",
                         "xaxis":{"title":"X"},
                         "yaxis":{"title":"Y"}}
);

**Comment by etpinard** [comment]
In codePen: https://codepen.io/etpinard/pen/oGpvNN?editors=0010

Thanks for the report.

**Comment by etpinard** [comment]
Ha. Actually, we deprecated [`opacity`](https://github.com/plotly/plotly.js/blob/a1a68fb9e74d75decc27e82f5c804fe91bad4217/src/components/errorbars/attributes.js#L146) for errorbars a while a ago now. 

You'll need to combine the opacity in the set color using the `rgba` alpha channel as in https://codepen.io/etpinard/pen/rGpBao?editors=0010
