### ISSUE TITLE
Support for multiple aggregate transforms

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#2078]
In theory it should be possible to chain `aggregate` transforms together, but currently it doesn't work. As a concrete example, say you had a long series of hourly temperature measurements, and you want the monthly average of daily high temperatures. You would first find the max temperature aggregating by day, then find the average aggregating by month.

Here's what this looks like if "days" are groups of 5, and "months" are groups of 2 days:
```js
Plotly.newPlot(gd, [{
    x: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
    y: [1, 2, 3, 2, 1, 3, 4, 5, 4, 3, 0, 0, 3, 0, 0, 0, 0, 0, 0, 7],
    transforms: [{
       type: 'aggregate',
        groups: [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3],
        // expected intermediate result: x: [0, 5, 10, 15], y: [3, 5, 3, 7]
        aggregations: [{target: 'y', func: 'max'}]
    }, {
        type: 'aggregate',
        groups: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        // expected final result: x: [0, 10], y: [4, 6]
        aggregations: [{target: 'y', func: 'avg'}]
    }]
}]);
```

This fails, and the challenge in making it work is that the first transform needs to aggregate the second one (if the second one has an array for `groups` like I have above). Currently the second can see the first during `supplyDefaults` (because the first has already gone through `supplyDefaults` so it's attached to the `_fullData` trace) but the first cannot see the second. But the solution is not as simple as reversing the order of these two `supplyDefaults` steps, because the second transform may need to be able to see the *results* of the first transform, if there's a `func: 'count'` aggregation in the first, because this can *create* an array that's not present in the input trace. Probably the easiest solution will be not to actually wait for those results before doing `supplyDefaults`, but to manually add to the list of `arrayAttrs` any `func: 'count'` aggregation targets from earlier transforms.

cc @bpostlethwaite

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
