### ISSUE TITLE
Add an event for panning and zooming that show live details as the range changes

### ISSUE THREAD

**Issue by Holyphoenix** [plotly/plotly.js#2082]
It would be useful to have an event that is fired any time the range of a chart changes (not just after the pan or zoom is complete).  This event could be used to make a second chart scroll or zoom with a first chart.

I want to use it to make a chart with the x-axis scrollable on my page over my other, quite large chart, that has many subplots.  I could also see it being useful for things like a dashboard where charts are separated to a point where they cannot just be subplots, but you want live updates to the charts as other charts are changing.

**Comment by alexcjohnson** [comment]
Good idea, similar to the `selecting` vs `selected` events. I imagine it would be very easy to slow the system down unbearably this way (panning & live zooming take shortcuts to adjust the plots much faster than a normal `relayout` with a changed range) but there are cases where this would work fine, or other things you might want to do with those ranges besides updating other plots.

**Comment by etpinard** [comment]
cc https://github.com/plotly/plotly.js/issues/145

**Comment by zhihua-chen** [comment]
Would like the same for rotating 3d plots.

**Comment by zhihua-chen** [comment]
How about this PR for gl3d plots?

https://github.com/zhihua-chen/plotly.js/pull/1

**Comment by suriyaprashath** [comment]
Any update on this feature request?

**Comment by zhihua-chen** [comment]
Sorry haven’t gotten around to writing the tests yet. Busy with work...

**Comment by etpinard** [comment]
Adding to `v1.48.0`
