### ISSUE TITLE
using fill doesnt allow to autorange the Y axis

### ISSUE THREAD

**Issue by Princezhm** [plotly/plotly.js#2083]
Hello, 

I was using your library and decided to add a gradient to a line chart, it was possible to do it, but then when I tried to use it with my real data, it started to behave incorrectly (or maybe correctly, but not for me).

the current case is the following:
I tried to add the fill option and at the same time I wanted to autorange the Y-axis, for what I saw this is not possible, it is always starting from 0 to the top of the data, but my data has little changes between them, so for example an array of my Y data would be:
`[1.30140139435718, 1.301839253486102, 1.301344603988707, 1.3016157641499442, 1.301913522752397]`
so, as you can see, the changes are really small, thus my range should be between [1.30, 1.31] for example, but when using fill, the autoscale option makes everything go back to [0, max].

here I created a codepen so you can see the issue using 2 plots with the same data, the only difference will be the fill option.

[CodePen](https://codepen.io/princezhm/pen/YrjrWL)

Regards, Prince.

**Comment by alexcjohnson** [comment]
Yes, the current behavior is intentional - the idea being that if you're filling to zero, the absolute magnitude is important to represent visually, similarly to a bar chart. But I can certainly understand the interest in modifying that behavior. See also #1876

**Comment by etpinard** [comment]
I'd vote for merging it with #1876

**Comment by alexcjohnson** [comment]
> I'd vote for merging it with #1876

[sure](https://github.com/plotly/plotly.js/issues/1876#issuecomment-336255376)
