### ISSUE TITLE
variable width symbols / rectangular symbols

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.js#2089]
A client is interested in creating oncoprint charts like this:
![image](https://user-images.githubusercontent.com/1280389/31623211-bf5346a8-b26c-11e7-93d3-cf1c1e020dca.png)
http://www.cbioportal.org/index.do?session_id=5952d299498e5df2e291c27d&show_samples=false&

This graph would be easy to plot if `scatter.marker.symbol` of `|` had an adjustable width. Currently, `scatter.marker.diameter` affects the height.

I'm not sure what the attribute would be. Perhaps `height` and `width` inside `symbol`? `diameter` would override it?

**Comment by alexcjohnson** [comment]
You might be able to hack it out using `marker.line.width`, but perhaps better (in terms of zoom behavior particularly) would be overlaid `bar` charts using explicit `width`, `offset`, and `base`. Would that work?

**Comment by alexcjohnson** [comment]
(and since the `y` axis is categorical, the bar traces should be horizontal)

**Comment by chriddyp** [comment]
Nice, thanks @alexcjohnson ! This seems to work
![image](https://user-images.githubusercontent.com/1280389/31625227-4c03ec6e-b273-11e7-9bf2-d300b5fca182.png)
https://codepen.io/chriddyp/pen/mBQVEy?editors=1010
