### ISSUE TITLE
Grouped Box Plot with subplots

### ISSUE THREAD

**Issue by Melanie-M** [plotly/plotly.js#2097]
When using subplots, grouped box plot are overlapping, even though `layout.boxmode = 'group'`
![boxplot_issue](https://user-images.githubusercontent.com/19667970/31717657-1d4774ea-b40d-11e7-881a-a8d5ecb5d9c0.png)

```
var layout = {
  yaxis: {
	 domain: [0, 0.45],
    title: 'axis 1',
  },
	yaxis2: {
	  domain: [0.55, 1],
	  title: 'axis2',
	},
  boxmode: 'group'
};

```
Codepen (adapted from the documentation example for [grouped box plot](https://plot.ly/javascript/box-plots/#grouped-box-plot))
https://codepen.io/anon/pen/pWqxwZ

**Comment by alexcjohnson** [comment]
Good catch @Melanie-M - and thanks for the clear codepen.

**Comment by etpinard** [comment]
Essentially the same problem as https://github.com/plotly/plotly.js/issues/78

**Comment by majorrabbit** [comment]
+1
Box plot with 2 axes and grouping also not working.

**Comment by etpinard** [comment]
This one got fixed by https://github.com/plotly/plotly.js/pull/3445 in `v1.44.0`.

See updated codepen: https://codepen.io/etpinard/pen/pGQjNL
