### ISSUE TITLE
Color bar on `choropleth` with two traces have duplicate ticks

### ISSUE THREAD

**Issue by monfera** [plotly/plotly.js#2102]
![colorbar-glitch](https://user-images.githubusercontent.com/1548516/31742481-03e6a8e0-b458-11e7-9f8a-54335dcecd7a.gif)

`crossfilter` adds the red highlight for selected countries via including a new trace before calling `Plotly.newPlot` - initially with no elements added ie. not `visible` - and `restyle`s this trace with `locations` that need to show up (in red). After doing so, the old ticks are still present on `colorbar`.

**Comment by etpinard** [comment]
Those aren't duplicated ticks, that's two colorbars (one per trace) overlapping one another.

**Comment by monfera** [comment]
Indeed! Thanks @etpinard, closing this.
