### ISSUE TITLE
Large marker line widths render differently in Chrome than in Firefox or Edge

### ISSUE THREAD

**Issue by nicknack23** [plotly/plotly.js#2108]
I wanted a custom marker with two concentric circles, so I used a large line width. Result:

![plotly rendering](https://user-images.githubusercontent.com/25664614/31820991-c7562700-b5a3-11e7-9aa2-1bf82deea779.png)

Is there some kind of workaround I can use to get the left result on Chrome too?
[Codepen here.](https://codepen.io/anon/pen/qPvXqV)

**Comment by alexcjohnson** [comment]
Ha, strange. I guess it's not well-defined what browsers should do when the line width is greater than the diameter of the circle, and they handle it differently.

I don't think there's anything we can do to get them to behave the same way, but it will be more flexible for you anyway if you simply use two traces with the same data, one with markers and lines and one with only markers.

**Comment by alexcjohnson** [comment]
another option you might find useful is `symbol: 'circle-open-dot'` which can give a similar effect, but not with different colors like this.

**Comment by nicknack23** [comment]
Thanks, I'll try adding another trace for the markers. I just confirmed that this is a [long-standing Chromium bug ](https://bugs.chromium.org/p/chromium/issues/detail?id=239860).

**Comment by nicknack23** [comment]
Thanks again, but `symbol: 'circle-open-dot'` is not the effect I'm looking for (the Firefox rendering in my screenshot is what I want). But when I looked up `circle-open-dot` I noticed there's also `circle-dot`, which may have been interesting if I could configure the size and color of the dot. But since you can't change the dot color, does `circle-dot` ever do anything different than just `circle`?

**Comment by alexcjohnson** [comment]
`circle-dot` with `marker.color` and `marker.line.color` set differently does have a distinct appearance, but it's generally not as useful as `circle-open-dot`, I'd say.
![screen shot 2017-10-20 at 10 50 59 am](https://user-images.githubusercontent.com/2678795/31826986-a3ee1076-b584-11e7-99d0-e5c423c78ca8.png)
