### ISSUE TITLE
Hover labels and event data for cumulative histograms

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#2115]
In #2113 we're adding bin range information to histogram hover labels, and input point numbers to the event data. But CDFs were explicitly omitted from these changes because it's not so obvious how to handle them.

My comment from that PR:

> this gets at some of the same issues that led to `cumulative.currentbin` but in principle a CDF shows the sum of all the data prior to a specific point, not the data within that bin. perhaps I should shift `p0` and `p1` depending on `currentbin` so that the hover label at least gets the description "all the data prior to X" precisely correct, even though it'll be a different value than the center of the bar...
>
> And then what about `pts`? You could say it should be included and again should be "all the data prior to X" but then it would be meaningless to select a single bar and not all the bars before it. Alternatively `pts` could contain "all the data that was added in this bar" which might be more useful in terms of selecting a single bar, but it's not really what that bar means.

Response from @etpinard:

> > so that the hover label at least gets the description "all the data prior to X"
> 
> Yeah. I think something along those lines would be useful down the road. 
> 
> > You could say it should be included and again should be "all the data prior to X" but then it would be meaningless to select a single bar and not all the bars before it. Alternatively pts could contain "all the data that was added in this bar" 
> 
> Sounds to me like both _all-data-prior-to-X_ and _data-added-in-this-bar_ point lists could be useful, so we might have to emit both in the future.

**Comment by julioasotodv** [comment]
+1 for this. It just seems weird that the hover info for a cumulative histogram is not actually showing the "up to" value, and instead shows the in-the-middle value for the bin range.

**Comment by akshata-patel19** [comment]
Any updates on this? would like to see the data labels as a list when hovering over a histogram bin

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
