### ISSUE TITLE
Set marker size in data coordinates, not just pixels

### ISSUE THREAD

**Issue by molehillrocker** [plotly/plotly.js#2118]
At the moment we use symbols to display some kind of "measurement threshold" for a couple of grouped bar charts. This looks nice in the first place, since the symbols are as wide as the bars. However when the user zooms in, the bar groups are scaled but the symbols remain as wide as before, leading to the effect that is shown in the attached screenshot.

![image](https://user-images.githubusercontent.com/7221361/32003329-f72ef0fc-b99e-11e7-91f6-868c5f030609.png)

We also tried to use a separate trace that renders as line (lines+markers), but we didn't make it to draw it dashed in a way that each dash spans a single bar group and each gap between two bar groups remains empty (see next screenshot).

![image](https://user-images.githubusercontent.com/7221361/32003630-f3556a5a-b99f-11e7-8b25-b3f68b387cc1.png)

It would be nice if this could be achieved by either using symbols (a line in our case) that automatically stretches horizontally, or use lines+markers with gaps (and thus no interconnection between the markers, something like the `hvh` line shape seen [here](https://codepen.io/plotly/pen/oXmJoz) without the vertical sections.

**Comment by alexcjohnson** [comment]
If this is a numeric x axis you should be able to get what you want by adding `null` or `''` between the segments
```js
{
    x: [0.6, 1.4, null, 1.6, 2.4, null, 2.6, 3.4]
    y: [65, 65, null, 20, 20, null, 50, 50],
    mode: 'lines'
}
```

That won't extend to categorical axes though (see also https://github.com/plotly/plotly.js/issues/2004) and I can see various other uses for markers that scale with the data axes, so it's definitely a feature worth considering.

**Comment by molehillrocker** [comment]
In most charts we actually use numerical axes, so I think I'll try your approach, since it looks very promising. :)

**Comment by molehillrocker** [comment]
I got it to work with the mentioned workaround, thanks a lot. Should I close this issue or do you want to keep it open as a feature request?

**Comment by alexcjohnson** [comment]
It's an interesting idea, not one we'll be working on in the near future but worth keeping open.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
