### ISSUE TITLE
updatemenus are drawn below colorscale

### ISSUE THREAD

**Issue by gdkrmr** [plotly/plotly.js#2119]
Similar issue to here #1302

![screenshot_2017-10-25_17-33-45](https://user-images.githubusercontent.com/12512930/32007867-11ff0bf4-b9ab-11e7-8650-34cb98d88e8c.png)

**Comment by alexcjohnson** [comment]
Good catch, these should definitely go on top.

**Comment by gdkrmr** [comment]
btw: the same happens with legends.

**Comment by alexcjohnson** [comment]
> btw: the same happens with legends.

@gdkrmr Do you mean updatemenus go below legends (which, if so, will be fixed by #2121) or that legends go below colorscales (for which neither option will satisfy everyone, normally you just want to keep them from overlapping each other)?

**Comment by gdkrmr** [comment]
the drop down menu shows below the legend

![screenshot_2017-10-26_17-31-22](https://user-images.githubusercontent.com/12512930/32062055-a5324d0a-ba73-11e7-8e98-b90a0d6d349b.png)

**Comment by alexcjohnson** [comment]
> the drop down menu shows below the legend

Great, #2121 fixes that.

**Comment by alexcjohnson** [comment]
closed in #2121
