### ISSUE TITLE
More robust handling of drag/hover interplay

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#2120]
Right now we do some things to disable hover interactions during drag - `dragElement` uses `gd._dragged` for example, and `pie` looks at this to prevent hover if you drag over a pie from a cartesian subplot. But there are likely other subplot types that don't do this, and anyway this will do nothing to detect dragging over the plot from outside the plot entirely (which currently causes hover events - hence the `bug` label). Seems like we could do better by just looking at `event.buttons`.

see https://github.com/plotly/plotly.js/pull/2117#discussion_r146852464

Also from a chat with @monfera 

> I like the generalization idea, and an incredibly minor point is that how the drag is initiated feels circumstantial - now it's a mouse gesture with buttons; maybe in the future, there'd be other ways that are useful. The question is, do we want to disable receipt of certain input based on the use of affordances (e.g. mouse buttons here), or based on something ongoing in the chart? E.g. a scrollyteller or some real-time shared plot could have data driven dragging. I told you it's a minor point :smiley:
>
> Also I think we want to disable it for the specific cursor (mouse) that's doing the dragging, again in a hypothetical dystopian future, you could drag something with one finger and hover (or drag) with some others

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
