### ISSUE TITLE
setting div style with css breaks interative functionality

### ISSUE THREAD

**Issue by gdkrmr** [plotly/plotly.js#2129]
The following heatmap does not have any interactivity (e.g. zoom, pan) and greys out when I mouse over it. It can be fixed by setting style inside the `div` element. I did not try this with an external `css` file
```html
<html>
    <head>
        <meta charset="utf-8"/>
        <script src="https://cdn.plot.ly/plotly-latest.js" ></script>
        <style>
         <!--
         div {
             width: 100%;
             height: 100%;
         }
         -->
        </style>
    </head>
    <body>
        <div id="myDiv"></div>
        <script>
         var color = [[0, "#ff0000"], [1, "#00ff00"]];
         var z = [];
         for (var i = 0; i < 4; i++) {
             z.push([]);
             for(var j = 0; j < 4; j++) {
                 z[i].push(i * j);
             }
         }

         var trace = {
             x: [1, 2, 3, 4],
             y: [1, 2, 3, 4],
             z: z,
             type: "heatmap"
         };

         var data = [trace];

         Plotly.newPlot('myDiv', data);
        </script>
    </body>
</html>
```

**Comment by etpinard** [comment]
In a codepen: https://codepen.io/etpinard/pen/oovOZK?editors=1010

Related to https://github.com/plotly/plotly.js/issues/888

**Comment by alexcjohnson** [comment]
This is actually just over-broad targeting of the CSS - you've made it so every `<div>` that Plotly makes expands to 100% of its parent - and the problem that causes here is that the modebar (the buttons that usually sit in the upper right corner) are in a `<div>` so they cover up the plot. If you change your css to something more specific like:
```js
#myDiv {
    width: 100%;
    height: 100%;
}
```
then it all works fine.

I suppose we could in principle `!important` or override with high specificity every attribute of any HTML elements we make but that doesn't seem desirable either.

**Comment by gdkrmr** [comment]
ok, thanks for the clarification and sorry for reporting this, I am no web designer.

**Comment by alexcjohnson** [comment]
@gdkrmr no problem, I'd much rather have reports that turn out to be easy to solve, than have real problems go unreported!
