### ISSUE TITLE
Negative positions get ignored on horizontal wrapped legends

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#2131]
https://codepen.io/etpinard/pen/ZaEEyL?editors=0010

First reported on https://community.plot.ly/t/legend-positioning-outside-plot/6528/3

**Comment by cldougl** [comment]
I think this is the same issue:
The negative position is getting ignored and the legend won't take up margin space in a plot with a set width/set right margin
https://codepen.io/plotly/pen/gvEaRK

**Comment by etpinard** [comment]
Will be alongside https://github.com/plotly/plotly.js/issues/771, closing this ticket.
