### ISSUE TITLE
autofill header title

### ISSUE THREAD

**Issue by VeraZab** [plotly/plotly.js#2133]
It would be very useful to be able to make table headers of unequal lengths, and have plotly.js fill the gaps

ex: https://codepen.io/veraz/pen/RjNEwE

**Comment by etpinard** [comment]
cc @monfera

**Comment by alexcjohnson** [comment]
I'd vote to fill the ends of cell columns to equal length as well. This doesn't *break* (or hide data) right now, but does look a little odd:

![screen shot 2017-11-01 at 11 06 33 am](https://user-images.githubusercontent.com/2678795/32281320-e6b4331c-bef4-11e7-8d4c-93b7c4ceab61.png)
