### ISSUE TITLE
Setting default colors

### ISSUE THREAD

**Issue by cixzhang** [plotly/plotly.js#2136]
Could we have a way to override the default colors for plotlyjs?

I'm willing to work on this feature.

**Comment by etpinard** [comment]
Can you be more specific? 

You would like to make the default trace-to-trace color [sequence](https://github.com/plotly/plotly.js/blob/4b8b10df27c53390751f01e949ab3a75e912367c/src/components/color/attributes.js#L12-L24) customizable?

**Comment by cixzhang** [comment]
@etpinard Yup! Exactly! I'd like to be able to set a specific color scheme for all chart traces to use.

**Comment by etpinard** [comment]
Ok. I'm thinking this should be a config [option](https://github.com/plotly/plotly.js/blob/master/src/plot_api/plot_config.js) e.g. `traceColorDefaults`.

**Comment by cixzhang** [comment]
That sounds good to me! I'll take a stab at it tonight.

**Comment by cixzhang** [comment]
Following the PR guidelines, I made a PR here in my own fork: https://github.com/cixzhang/plotly.js/pull/1.

Please have a look when you have time!

**Comment by alexcjohnson** [comment]
@cixzhang Great PR! @etpinard and I had a discussion about this offline though, and we concluded it actually should be a [top-level layout attribute](https://github.com/plotly/plotly.js/blob/master/src/plots/layout_attributes.js), not a config option. The advantage of this is that the result is portable (on plot.ly for example `data` and `layout` get saved with the plot but `config` is context-dependent), and easier to change (via `relayout` / `update`) - which can be useful for example if you want to try out a bunch of different themes / templates for your plot (cc @bpostlethwaite )

We're thinking `layout.colorway` - sound reasonable?

**Comment by cixzhang** [comment]
Thanks for the feedback! That makes sense to me. I'll take a look at implementing it as a layout attribute this evening.

**Comment by cixzhang** [comment]
I've created a new PR with `layout.colorway` on my fork here: https://github.com/cixzhang/plotly.js/pull/2

**Comment by cixzhang** [comment]
I have updated my PR here: https://github.com/cixzhang/plotly.js/pull/2. Let me know if there's anything else I should do. :)

**Comment by bpostlethwaite** [comment]
Thanks @cixzhang we appreciate the PR and will get to it ASAP. Unfortunately that may be a few days as our core plotly.js team is either on vacation or dealing with unforeseen events. Everything should be back to normal next week. Thanks again.

**Comment by etpinard** [comment]
Done in #2156
