### ISSUE TITLE
Selection by click

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.js#2143]
In #1848 (Persistent, stateful hover, click, and selection properties), I mention that it would be helpful to have "persistent click".

We discussed this in person in MTL a few weeks ago and realized that "persistent click" is really "clicking should add points to the persistent selectedPoints state".

This way of selecting data by clicking is common in the other crossfiltering tools like Tableau. Dash users are already working on workarounds to make this possible (https://community.plot.ly/t/solution-persistent-click-events/6590)

Interactions include:
1 - Clicking on a point makes it selected
2 - Clicking on second point adds it to the selected points, keeps the previous point
3 - Clicking on an already selected point removes it
4 - Does this only work if lasso and box-select are selected or is this the default behaviour?

2 is a little different than how tableau seems to work. In tableau, if you click on a second point, it deselects the first point, only allowing you to select one point at a time. 

![click-selection-points](https://user-images.githubusercontent.com/1280389/32395439-7bb011de-c0b7-11e7-826b-8adb43eebe4f.gif)

I suppose that this could be configurable (`clickselectmode: 'single | append | exclude`) down the road.

**Comment by etpinard** [comment]
Can we merge this into https://github.com/plotly/plotly.js/issues/1848 ?

#1848 will remain open after https://github.com/plotly/plotly.js/pull/2135

**Comment by etpinard** [comment]
Merging into #1848 selection-related issues are getting a little out-of-hand at the moment.
