### ISSUE TITLE
add attribute `boxtext` to boxplots

### ISSUE THREAD

**Issue by salim-b** [plotly/plotly.js#2145]
Would be nice if we could change the 5 (6 if `boxmean=TRUE`) hoverinfo texts of Plotly's boxplots to custom values.

https://github.com/plotly/plotly.js/pull/2094 seems to introduce the `text` attribute for the individual data points in boxplots. An additional `boxtext` attribute for the aggregate summary statistics (min, lower quartile, median, mean, upper quartile, max) hoverinfo texts would be awesome.

This seems to become even more relevant when other whisker options get intoduced as proposed in https://github.com/plotly/plotly.js/issues/277. To give viewers an idea of what the values of the boxplot actually depict, the `boxtext` attribute could then be set to an adequately explanatory character vector.

Might be related: https://github.com/plotly/plotly.js/issues/1642

**Comment by etpinard** [comment]
I think you're looking for more box-centric [`hoverinfo`](https://plot.ly/javascript/reference/#box-hoverinfo) flags, not a new attribute. 

For example, `hoverinfo: 'x+q1+mean'` would only show the x, q1 and mean hover labels.

**Comment by salim-b** [comment]
> I think you're looking for more box-centric hoverinfo flags, not a new attribute.
For example, hoverinfo: 'x+q1+mean' would only show the x, q1 and mean hover labels.

That would be nice, too – but not what I meant. I want to change the actual text that is displayed in the `q1`, `mean` etc. hoverinfo labels. So instead of just displaying the bare number of the `mean` for example I wanna show something like _10.3 (mean)_ by setting `boxtext` to a corresponding character vector (1st string corresponds to `min`, 2nd to `q1`, 3rd to `median`, 4th to `q3` and 5th to `max` if `boxmean` is `false`). Of course I had to calculate the numbers myself then but since I'm using R this isn't a big deal, I can just take them from `boxplot.stats()` from `grDevices` 😬 (it would surely be more user-friendly if the values plotly calculated could be directly accessed).

Additionally it could make sense to "harcode" the ordering of the values of `boxtext` when `boxmean` is set to `true`/`"sd"`, so that the hoverinfo text for `median` always corresponds to the 3rd string and the one for the `mean` always to the 4th (only relevant if 6 strings are provided in `boxtext`; without the `mean` the actual order is always the same by definition).

**Comment by etpinard** [comment]
Ok. I can't say I'm a fan of this proposal. Sure plugging numbers would be easy from R, but then we can't guarantee the numbers will exactly match the ones on the plot.

Note that PR #2094 also adds text descriptors to the box hover labels: 

![image](https://user-images.githubusercontent.com/6675409/31783959-0d5a0cb6-b4ce-11e7-8e50-e959d4261183.gif)

**Comment by salim-b** [comment]
> Note that PR #2094 also adds text descriptors to the box hover labels:

Awesome, almost exactly what I meant. Now I wanna just be able to customize those text descriptors, e.g. to translate them into my native language 🙂

**Comment by etpinard** [comment]
> Now I wanna just be able to customize those text descriptors, e.g. to translate them into my native language

Then this will be part of https://github.com/plotly/plotly.js/issues/856

**Comment by salim-b** [comment]
> Then, this will be part of #856

Allright, that looks promising and would fully enable what I wanna accomplish, I guess 👍

**Comment by yniknafs** [comment]
@etpinard Curious if adding the box-centric hover flags had been worked on per your comment above. 

> I think you're looking for more box-centric hoverinfo flags, not a new attribute.
> For example, hoverinfo: 'x+q1+mean' would only show the x, q1 and mean hover labels.

Sorry to bombard you with a ton of comments. I love plotly. I'm relying heavily on the box plot type, and it feels a little less fleshed out than some of the other plots. Would be Nice to at least be able to turn the numbers off, and just leave the name of the trace.

**Comment by amirh357** [comment]
for the boxplot using plot_ly, Is it possible to have a "text" hoverinfo similar to what we can define for type="bar" ? For example, I just want to show the median, Q1, and Q3 in a text box when I hover over a box with some additional information that I can write in that box. For example, see the figure below:
![Box_hoverinfo](https://user-images.githubusercontent.com/40361275/57032133-9d436c80-6c17-11e9-9bae-edc656b3b19c.jpg)

**Comment by samnb** [comment]
Hi @amirh357 that's a pretty good idea. Have you any solution for it?

**Comment by nmoreaud** [comment]
Hello, here is an example where I add another hover information : (https://codepen.io/kiruahxh/pen/PoNYvWw)

However, I found no information about the boxplot tooltip customization/replacement (ex : How can I show a multiline text instead of having multiple tooltips? How can I translate 'median' and 'min' keywords ? How can I feed a tooltip with the statistics automatically computed by plotly.js ?)

**Comment by datainvestor** [comment]
@nmoreaud 
This is something I'm looking for as well. Instead of having multiple tooltips separately for each of the values I need one textbox showing all the values in one place (this is useful when the chart has space boundaries and the values are being cut off). I wonder if this is possible here.
