### ISSUE TITLE
Chart tooltips - how to always on

### ISSUE THREAD

**Issue by hkbeer** [plotly/plotly.js#2146]
I  am displaying a Bar/Bubble Chart and on mouse over a tooltips box appears.
How to config it so that this tooltips always appears without need of mouse hover?

Pls post sample code. Thanks

**Comment by etpinard** [comment]
See https://plot.ly/javascript/hover-events/#triggering-hover-events

and please use https://community.plot.ly/ for questions of the likes in the future.
