### ISSUE TITLE
Exposing (and augmenting) Plotly.Axes.list

### ISSUE THREAD

**Issue by bpostlethwaite** [plotly/plotly.js#2152]
@alexcjohnson it is possible to require Axes.list statically but without tree shaking you end up including a lot of extra plotly.js bytes in the bundle  https://github.com/plotly/plotly.js/blob/master/src/plots/cartesian/axis_ids.js#L11-L15

In the Plotly.react model we are asking the user to update gd.data and gd.layout in their application code. As such it might be useful to expose some logic that can wrap intricacies such as https://github.com/plotly/plotly.js/blob/aa67de2bb69e6de51767a3bea879a88781c3ec3e/src/plot_api/plot_api.js#L1726-L1736

I'll update this issue with suggestions once I implement some more of the Axes update code in the App I am working on.

**Comment by alexcjohnson** [comment]
The reorganization I'm doing as part of #2125 will simplify `Axes.list` substantially, so requiring it directly may become viable, but we can discuss that when I get that PR up, might not even be necessary at that point. I'm sure @etpinard would approve if we can avoid exposing innards like that!

**Comment by etpinard** [comment]
Closing (for now).
