### ISSUE TITLE
Change color of marker on hover

### ISSUE THREAD

**Issue by bhaumik55231** [plotly/plotly.js#2153]
I want to change the color of scatter plot marker on hover. Here is my code snippet. 

TESTER.on('plotly_hover', function(data){
	dragLayer.style.cursor = 'pointer'
	var yellow_label = data.points["0"].data.marker;
	yellow_label.color = "#dca303";
})

I'm not getting any errors, but this code doesn't change the color of marker.

**Comment by etpinard** [comment]
Using `Plotly.restyle` in your `plotly_hover` handler should do the trick.

Please use https://community.plot.ly/ for questions of the likes in the future - so that other users can benefit from it. Thank you.

**Comment by bhaumik55231** [comment]
Thank You@etpinard
