### ISSUE TITLE
Support SVG and PDF in the download menu

### ISSUE THREAD

**Issue by jjgao** [plotly/plotly.js#2157]
Is it possible to support downloading SVG and PDF in the menu?

We noticed on [this page](https://plot.ly/javascript/static-image-export/), you mentioned "Note: The SVG, EPS and PDF Formats are only available for Plotly Professional users. You can get more details on our pricing page." Does this apply to the Javascript library as well?

**Comment by etpinard** [comment]
This post https://community.plot.ly/t/save-as-svg-instead-of-png-in-modebar/4560 has a solution for downloading SVG via the modebar.

We aren't planning on adding _native_ PDF download in plotly.js proper for the foreseeable future.
