### ISSUE TITLE
X co-ordinate for a clicked point on a heatmap does not match the corresponding co-ordinate in the data

### ISSUE THREAD

**Issue by AndrewJohnBenjamin** [plotly/plotly.js#2166]
Hi,

I have the following code pen [here](https://codepen.io/anon/pen/jGJYEg?editors=1111)

The pen consists of a simple heatmap with data for 3 co-ordinates on the x-axis (69003.3, 69001.2, 68999.3) When hooking into the click event for the graph, the event contains a property that states the x co-ordinate of the clicked area. In the example in the pen, this value is incorrect and not present in the dataset used to construct the graph. i.e. if you click the center of the heatmap on the pen, you will be alerted that the clicked co-ordinate is 69001.25 when I would expect it to be 69001.2 as per the dataset.

Can you please provide an explanation of how this works and if this is expected behaviour.

Thanks,
Andy

**Comment by etpinard** [comment]
> this value is incorrect and not present in the dataset used to construct the graph. i.e. if you click the center of the heatmap on the pen, you will be alerted that the clicked co-ordinate is 69001.25 when I would expect it to be 69001.2 as per the dataset.

We include a formatted value in the event data corresponding to what the value that would be shown in the hover label (see for yourself by swapping `hoverinfo: 'none'` for `hoverinfo: 'all'`). 

To get the original input data, you can use the event data `pointNumber` field. I hope this helps.

**Comment by etpinard** [comment]
Closing as this ticket won't result in a PR. Please use https://community.plot.ly/ if you have any other questions on the topic.
