### ISSUE TITLE
Regression observed on errors-bars in bar plot

### ISSUE THREAD

**Issue by MarcAlx** [plotly/plotly.js#2168]
Hi,

I recently observed  a regression over `error-bars`, I can't say which version introduced the regression.

Here's a working version in **plotly-1.2.0** : [sample OK](https://codepen.io/anon/pen/vWWpoR)

Here's a sample where I observe the regression (**plotly-latest**) (only the first error-bar appear) : [sample KO](https://codepen.io/anon/pen/mqqXJj) 

Maybe I've missed something from [the doc](https://plot.ly/javascript/error-bars/).

Thanks for your time and consideration.

**Comment by etpinard** [comment]
Interesting. Thanks very much for the report.

I was able to get your graph in a working state by removing the `ids` array from your data: https://codepen.io/etpinard/pen/bYYZLq?editors=0010

Why `ids` are causing error bars to disappear isn't obvious to me.

**Comment by etpinard** [comment]
Ha, maybe this [block](https://github.com/plotly/plotly.js/blob/82326bad3490be56d9c068122e49dd7975ef4f64/src/components/errorbars/plot.js#L37-L39) (added during the animation) push is causing issues.
