### ISSUE TITLE
Line paths are not correctly computed when their points are well-beyond the axis ranges

### ISSUE THREAD

**Issue by ifll** [plotly/plotly.js#217]
When building a scatter plot with both x and y logarithmic axis there is an error when placing a line shape on the plot.

The line is sometimes well displayed but when trying to zoom it disappears or appears not well placed.

The code used for displaying the line is the following:

- inside the layout variable for the plot making place the following:

var layout2 = {
			  .
                          .
                          .
			  shapes: [
			           
					//line 45º
					
					{
					  type: 'line',
					  xref: 'x',
					  yref: 'y',
					  x0: 0.0001,
					  y0: 0.0001,
					  x1: 10000,
					  y1: 10000,
					  line: {
					    color: 'rgb(0, 0, 0)',
					    width: 1
					  }
					},
			           
			           
			           
			           ],
     
				  .
				  .
				  .
			};

there are around 1000 points to be displayed on the scatter plot

Do any of you know if this is a bug or if is is not the proper way to place a line on the plot and there is another method which could work?

Thank you.

**Comment by etpinard** [comment]
Thanks for writing in.

Can you elaborate on what you mean by *not well-placed* ?

Looks like log shapes are behavior as expected when no data is present: http://codepen.io/etpinard/pen/NxYyzL

Could you share the data you're using?

**Comment by ifll** [comment]
Unfortunately data I am using is not sharable...

Even though, within the example you have posted in your answer there appears the same problem I have been encountering on my plot, as when you zoom on the plotly plot around the line shape created it disappears (it might be that 2 or 3 zooms are required to check this problem).

Besides this, by non-well displayed I mean what I have explained in the previous paragraph of this answer. Also another effect of "non-well displayed" is that the line shape is displayed not complete but for a small range of its completion, or even that it is displayed not where it should be placed.

Hope this helps to understand the problem I have been encountering and thank you very much for your help.

**Comment by etpinard** [comment]
I can't replicate it.

Could you at least share a screenshot of the *not-well-displayed* line?

**Comment by etpinard** [comment]
Moreover, what browser are you using?

**Comment by ifll** [comment]
Here you can see some images of the problem I have reported and obtained from the link you have posted on your first answer on this chat.

This images are a followup of zooming on the plot created on the link you have posted.

As you would be able to see on the first image the line is well displayed. On the second one you can check the zoom I make, and on the 3rd image you can see the result of the zoom (which the line can still bee seen but it is not well paced, as it should be more diagonal). Finally another zoom is made in the forth image and in the last one the line is no longer visible.

Besides this, I am using mozilla firefox version 43.0.4 for Ubuntu 14.04 LTS

![screenshot1](https://cloud.githubusercontent.com/assets/16896039/12584083/198d2b00-c446-11e5-9e39-bc565feed919.png)
![screenshot2](https://cloud.githubusercontent.com/assets/16896039/12584082/198a15dc-c446-11e5-962e-44f273f95c31.png)
![screenshot3](https://cloud.githubusercontent.com/assets/16896039/12584086/19a98a02-c446-11e5-860f-909f9ba10a8e.png)
![screenshot4](https://cloud.githubusercontent.com/assets/16896039/12584084/199e001a-c446-11e5-9f0a-ae2a9521bff8.png)
![screenshot5](https://cloud.githubusercontent.com/assets/16896039/12584085/19a41f04-c446-11e5-97dd-68966ce1ebeb.png)

**Comment by etpinard** [comment]
@ifll Thank you very much.

I can replicate this bug in FF 43 also. Chrome 48 behaves as expected though.

Thank you very much for reporting!

**Comment by ifll** [comment]
Thank you very much for your attention and support on this problem.

Do you know if this bug will be solved for mozilla firefox in a close future? Besides this, do you know if this bug is also happening in other webbrowsers such as "opera", "explorer", "safari" or "edge"? (I am building a web application and would be great to know if it happens in other browsers)

Thank you very much for your help!

**Comment by etpinard** [comment]
> Do you know if this bug will be solved for mozilla firefox in a close future

In all honesty, browser-specific rendering bugs are rarely a priority for our (small) team of full-time maintainers. 

Have you tried plotting your line as a data `scatter` trace with mode `'lines'` instead? You could turn off hover text by setting [`hoverinfo`](https://plot.ly/javascript/reference/#scatter-hoverinfo) to `'none'. Data lines are of course a more robust feature than shapes.

> Besides this, do you know if this bug is also happening in other webbrowsers such as "opera", "explorer", "safari" or "edge"

I just tried in IE11 and everything works OK. I'll ask my colleagues to try it out on Safari. I'd would not recommend using on Opera.

**Comment by ifll** [comment]
Ok, thank you very much.

I already tried doing what you purpose to create a new trace variable with the lines mode and the problem was the same... then was when I tried to post it here in github.

Thank you very much for your help and support, even though the bug is there for FF I can carry on working with chrome webbrowser and add an alert on the display advising to use chrome or explorer

**Comment by etpinard** [comment]
> create a new trace variable with the lines mode and the problem was the same.

Very interesting. This bumps up the priority of this issue.

**Comment by ifll** [comment]
// 	var trace4 = {
// 			mode: 'lines+markers',
// 			x: {{ x_line45 }},
// 			y: {{ y_line45 }},
// 			line: {
// 			    color: 'rgb(0, 0, 0)',
// 			    width: 1,
// 			  }
// 			};

This is the code I have used to do it on FF. The "x_line45" and "y_line45" are variables containing identic arrays of length 1000. I have used "lines+markers" as with only "lines" there was the same problem I have reported with the "shape" option of the layout, and I wanted to check if it was a mistake that the points were not displayed.

With the "lines+markers" option the markers were displayed but when zooming in the line disapeared or was missplaced as in the answer I have posted previously with the pictures of the bug found on FF.

**Comment by etpinard** [comment]
The problem is much more generalized than originally thought. Looks like all 2d svg line paths (traces and shapes) on any type of axes are not computed correctly when the line points are *well-beyond* the axis ranges. The problem does not only occur on zoom events.

This codepen may help: http://codepen.io/etpinard/pen/NxYBNJ investigate the problem.

**Comment by ifll** [comment]
Do you have any idea about when do you think that this can be solved?

Thank you

**Comment by ifll** [comment]
I was checking the problems with the shapes and the traces again and it is true that lines are not well displayed on the axis, because sometimes when I zoom the line (no matter if it is displayed due to a line shape or a trace line) disappears or it is not well placed on the plot.

Hopefully you can find a solution as soon as possible :)

Thank you very much for your help!

**Comment by ifll** [comment]
Do you know more or less how many weeks/months/years can take until this bug is solved?

Thank you very much!

**Comment by etpinard** [comment]
@ifll hopefully this week. But I can't guarantee anything. This is hard problem to solve.

**Comment by ifll** [comment]
Thank you very much!

Whenever it is solved will you text back this conversation to close the bug?

**Comment by etpinard** [comment]
> Whenever it is solved will you text back this conversation to close the bug?

yes

**Comment by etpinard** [comment]
@ifll **Update:**

I haven't found a bullet-proof solution to the problem yet. 

The fix won't be ready for next week's release.  My apologies.

**Comment by ifll** [comment]
No worries,

You said it was a very generalized issue and I guess it can be hardwork to solve it. Btw, do you have any expectancy about when this can be solved? and, how often do you publish new releases?

Thank you very much for your effords to solve this issue!

**Comment by etpinard** [comment]
We usually publish new releases once a week.

**Comment by ifll** [comment]
Any improvement on this issue?

**Comment by ifll** [comment]
@etpinard is there any advance regarding this issue??

**Comment by ifll** [comment]
@etpinard is this still an issue which still has a bumped priority and which you are thinking to solve it soon? I would like to know if you expect to solve this in a close future or if I will have to wait some months until it is solved.

I mean this because I would like to know it for the plot I am building....

thank you very much and sorry for the inconviniences.
