### ISSUE TITLE
Zoom out button is labeled as "Zoom in" in minified js

### ISSUE THREAD

**Issue by dakotakg** [plotly/plotly.js#218]
In the following link: https://cdn.plot.ly/plotly-latest.min.js, the zoom out button is labeled as "Zoom in".

Below is the code which has the typo:
"f.zoomOutGeo={name:"zoomOutGeo",title:"Zoom in",attr:"zoom",val:"out",icon:h.zoom_minus,click:a}"

**Comment by mdtusz** [comment]
Good catch! Thanks for the report.

**Comment by etpinard** [comment]
:dancer:
