### ISSUE TITLE
Marker opacity doesn't work as an array in Scatter3D.

### ISSUE THREAD

**Issue by ksze** [plotly/plotly.js#2186]
When using Scatter3D, specifying marker opacity as an array causes the opacity to be effectively 1.0, instead of whatever values are stored in the array.

To reproduce, visit this codepen and see how all the blue markers are completely opaque instead of having opacity 0.1: https://codepen.io/k_sze/pen/gXdqrV

**Comment by etpinard** [comment]
Yep. That's a `wontfix` unfortunately. Implementing per-point _true_ marker opacity in 3D proved to be too resources-intensive. 

You can still set _blend_ opacity via rgba `marker.color` as in https://codepen.io/etpinard/pen/KVdddB?editors=1010

**Comment by etpinard** [comment]
Closing as a `wontfix`.

Thanks for posting @ksze
