### ISSUE TITLE
selected event for Contour plots doesn't populate points array

### ISSUE THREAD

**Issue by brian428** [plotly/plotly.js#2188]
When using a combined scatter plot and contour plot, the plotly_selected event does get a populated points array after selection. But if no scatter plot is included, the points array is empty. It would be useful to allow selecting data when only contour is being used.

Under the hood, I assume that the contour plot is still aware of the x/y values that were fed into it to create the contours, so it seems like populating the points array should still be possible?

**Comment by etpinard** [comment]
That's correct. Selection aren't supported for all trace types. See up-to-date list in https://github.com/plotly/plotly.js/issues/170#issuecomment-317063282

Closing in favor of https://github.com/plotly/plotly.js/issues/170
