### ISSUE TITLE
Date axis not working in 3D scatter with duplicate timestamp values

### ISSUE THREAD

**Issue by bcdunbar** [plotly/plotly.js#2190]
Date axis doesn't work in 3D scatter chart type when Hour and Month (and date) values area repeated such as, 

2001-01-01 12:01:30
2001-01-01 12:01:40

The above dates work as expected in regular scatter plot. 

Originally reported here https://codepen.io/brian428/pen/aVQeqv?editors=0010

Confirmed here https://codepen.io/bcd/pen/eebmRa?editors=1010

**Comment by etpinard** [comment]
Probably another manifestation of https://github.com/plotly/plotly.js/issues/551

**Comment by alexcjohnson** [comment]
> Probably another manifestation of #551

Yep, this is below the resolution of Float32:
```js
d1=Date.UTC(2016,11,31,16,30,10)
> 1483201810000
d2=Date.UTC(2016,11,31,16,30,20)
> 1483201820000
d2 - d1
> 10000
a=new Float32Array([d1,d2])
> Float32Array(2) [1483201839104, 1483201839104]
a[1] - a[0]
> 0
```
Looks like at the present distance from the unix epoch, 32-bit resolution is ~2 minutes (2^17 = 131072 msec). In 2001 we were closer to the epoch so the exponent floats down 1 and we get, ~1 minute resolution (2^16 = 65536 msec).
