### ISSUE TITLE
non-linear box/violin hover label quirks

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#2194]
Horizontal violins have some odd hover label behavior. Labels are horizontal, not tipped as they are for horizontal boxes and bars, and (perhaps related) they're anchored to the middle of the violin, not the edge (or off the edge) as they are for vertical violins
![screen shot 2017-12-06 at 11 59 07 am](https://user-images.githubusercontent.com/2678795/33674572-f96df4ee-da7d-11e7-8b8e-92c4dedf4339.png)

And at least in `violin_non-linear` the KDE label disappears past the max point, even though the KDE line is still there.
![screen shot 2017-12-06 at 11 59 35 am](https://user-images.githubusercontent.com/2678795/33674570-f639af7a-da7d-11e7-9222-237bcefee2b6.png)

cc @etpinard

**Comment by etpinard** [comment]
This seems to happen on _non-linear_ axes for both violin and box traces.

Mock [`box_grouped_horz`](https://rreusser.github.io/plotly-mock-viewer/#box_grouped_horz) + `Plotly.restyle(gd, 'type', 'violin')` appears to work fine. Whereas [`violin_non-linear`](https://rreusser.github.io/plotly-mock-viewer/#violin_non-linear) + `Plotly.restyle(gd, 'type', 'box')` also shows the problem.
