### ISSUE TITLE
Percentage formatter for yaxis

### ISSUE THREAD

**Issue by alexander-alvarez** [plotly/plotly.js#220]
I'm plotting rates over time, and I have an abstraction that scales all of my values input into plotly by 100, and sets the axes accordingly

Would be nice to contribute it back to Plotly, just not sure where it would go or if this is something you'd like in the core functionality

I saw in #79 that [exponentformat](https://github.com/plotly/plotly.js/blob/master/src/plots/cartesian/layout_attributes.js#L275) seems to be the place to do formatting for the axes. 

Curious on your idea for on hover, as ideally these would show formatted when you add the`y` parameter to `hoverinfo` (e.g. it would be `52%` instead of `0.52`). This is currently achieved through scaling the values and manually adding them through the annotations.

**Comment by etpinard** [comment]
> Would be nice to contribute it back to Plotly 

Fantastic! :beers: 


> an abstraction that scales all of my values input into plotly by 100, and sets the axes accordingly

This sounds to me like a axis *type*, similar to `date` and `categories` and `log` axis types.

Could you send us a link to a working example? I'd like to get a better idea of you mean better starting to think about implement it.

**Comment by alexander-alvarez** [comment]
Was going to dig through the documentation on read up on axes types, but it seems they're down ATM.

It's not anything crazy: http://codepen.io/anon/pen/YwLQLa
In the example attached I'd like to label each of the yAxis labels with a `%` after the number, similarly in the 'y' value of the tooltip.

Ideally we'd have the ability  to specify in/exclusion '%'  sign after the labels and/or in the tooltip independently. [numeral](http://numeraljs.com/) and [moment](http://momentjs.com/) have great APIs for formatting flexibility (signs, decimal places, date formats).

**Comment by etpinard** [comment]
> but it seems they're down ATM

Dang. You're right. Thanks for letting us know.

**Comment by etpinard** [comment]
> In the example attached I'd like to label each of the yAxis labels with a % after the number, similarly in the 'y' value of the tooltip.

You can already do so using `yaxis.ticksuffix`, example: http://codepen.io/etpinard/pen/pgVVqr

**Comment by alexander-alvarez** [comment]
oh interesting. `ticksuffix` affects the `hoverinfo` suffix too -- as does `tickformat` -- that's the ideal behavior.
I would have never thought  to look under the `tick...` name for something related to the way the data is represented in `hoverinfo`. But I guess it kind of makes sense since it's attached to the axis itself.
