### ISSUE TITLE
Trying to print number chart

### ISSUE THREAD

**Issue by vmagalhaes** [plotly/plotly.js#2204]
Hi,

I'm trying to print my dashboard, I'm doing a print page and when I tried to get the chart number element for something reason it doesn't founded.

In screenshot below you can see this, any suggestion? 

![screenshot from 2017-12-13 11-20-25](https://user-images.githubusercontent.com/14242447/33940819-ab5159c0-dff7-11e7-9f35-59e71b0ec2c7.png)

My code: 

```
charts.forEach((chartId: number) => {
      let chartElement: any = $(`#nboard_element_${chartId}_`);

      if (chartElement.length) {
        promises.push(
          Plotly.toImage(chartElement[0], {
            format: 'png',
            width: chartElement.width(),
            height: chartElement.height()
          })
        );
      }
    });

```

Thanks

**Comment by alexcjohnson** [comment]
@vmagalhaes I can't really tell from this description what symptoms you're encountering, but offhand it doesn't look like a *problem* with plotly.js (a bug you've found or a feature we could add) - more of a usage question. Questions like that are best asked at community.plot.ly
