### ISSUE TITLE
Hover picking over this surface is off

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#2208]
First reported on https://community.plot.ly/t/3d-contained-surface-not-in-accordance-with-the-3d-containing-space/7327

See https://codepen.io/etpinard/pen/xpwGgV?editors=0010

![peek 2017-12-15 10-48](https://user-images.githubusercontent.com/6675409/34049457-7694e726-e185-11e7-958e-04b0592d09ae.gif)

**Comment by etpinard** [comment]
cc @archmoj this may be fixed by your work in https://github.com/plotly/plotly.js/pull/3281

**Comment by archmoj** [comment]
This is a closed issue? It may not be addressed there.
@etpinard Anyway I updated your codepen to point to look at the branch [here](https://codepen.io/MojtabaSamimi/pen/RqBLLZ).

**Comment by archmoj** [comment]
Revised [Demo](https://codepen.io/MojtabaSamimi/pen/pQZdLb) with better fix on another branch.

**Comment by etpinard** [comment]
@archmoj did https://github.com/plotly/plotly.js/pull/3299 fix this one?

**Comment by archmoj** [comment]
@etpinard Yes it would. Here is the updated [demo](https://codepen.io/MojtabaSamimi/pen/xmEbLm) using latest code, in case you were interested to test.

**Comment by archmoj** [comment]
Fixed in #3281.
