### ISSUE TITLE
multiple gl2d subplots: only one is drawn at a time

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#2220]
Open `gl2d_stacked_subplots` - only one subplot is visible at a time. Whenever you hover over one, it appears and the others disappear. Seems to have come in with #2159 cc @dfcreative @etpinard 

![hiding-gl2d-subplots](https://user-images.githubusercontent.com/2678795/34301088-f6b0d492-e6f8-11e7-998b-89bcfe9c2a3d.gif)

**Comment by etpinard** [comment]
Must be a side effect of https://github.com/plotly/plotly.js/pull/2159
