### ISSUE TITLE
scatter3d.size for each data point

### ISSUE THREAD

**Issue by Tagar** [plotly/plotly.js#2223]
Would be great to make possible to set scatter3d.size for each data point.

https://github.com/plotly/plotly.js/blob/43d3710bdb183f9c1681f40efe8649a7238efce5/src/traces/scatter3d/attributes.js#L126

**Comment by etpinard** [comment]
Here's how: https://codepen.io/etpinard/pen/gogJyV?editors=0010

**Comment by Tagar** [comment]
Thank you @etpinard
