### ISSUE TITLE
Old webkit versions render the plots with a black background

### ISSUE THREAD

**Issue by Leprosy** [plotly/plotly.js#2225]
Hi...I have this plot. I'm rendering it using the latest version of chrome and the rendering is ok. However, using the webkit version packed in Qt 4.8(an old one, I think), the rendering shows a dark background and the mousewheel events fail. The rest of the tools in the modebar seems to work ok, though. 

Modern webkit:
![new](https://user-images.githubusercontent.com/851905/34392535-72539d6a-eb2b-11e7-9ce5-5c40da8d3589.png)

Old webkit:
![old](https://user-images.githubusercontent.com/851905/34392538-7abbae48-eb2b-11e7-9963-e7202779c63e.png)

Is there any workaround for this issue? I had to use these two pollyfills in order to the plotly.js library to not crash in the old webkit:

```javascript
Object.isExtensible = Object.isExtensible || function isExtensible(object) {
    if (Object(object) !== object) {
        throw new TypeError('Object.isExtensible can only be called on Objects.');
    }
    // Some definitions, then return the Boolean value of the [[Extensible]] internal property of O.
    var call = Function.call;
    var prototypeOfObject = Object.prototype;
    var owns = call.bind(prototypeOfObject.hasOwnProperty);
    var isEnumerable = call.bind(prototypeOfObject.propertyIsEnumerable);
    var toStr = call.bind(prototypeOfObject.toString);

    var name = '';
    while (owns(object, name)) {
        name += '?';
    }
    object[name] = true;
    var returnValue = owns(object, name);
    delete object[name];
    return returnValue;
};

Object.freeze = Object.freeze || function freeze(object) {
    if (Object(object) !== object) {
        throw new TypeError('Object.freeze can only be called on Objects.');
    }
    return object;
}
```

**Comment by Leprosy** [comment]
And...I think I've found a workaround. Seems to be that the `rect` elements in the `g.draglayer` have the property `fill: transparent`, which it's not supported in the old webkit version. 

This CSS did the trick for me:
```css
.draglayer rect {
￼    opacity: 0;
}
```

Mousewheel is still broken, but that can be dealed with. Hope this can be of help.

**Comment by etpinard** [comment]
Thanks for the report.

**Comment by rmoestl** [comment]
@Leprosy thanks for the suggested fix. To diagnose the broken mouse wheel, it'd be good to know the exact Webkit version bundled with your QT 4.8 distribution. [QT 4.8 documentation](http://doc.qt.io/archives/qt-4.8/qtwebkit-module.html#details) says
> This is a snapshot of the Qt port of WebKit. The exact version information can be found in the src/3rdparty/webkit/VERSION file supplied with Qt.

Could you please take a look and post the exact version?

**Comment by etpinard** [comment]
Closed due to lack of activity.
