### ISSUE TITLE
Labels wrongly displayed in bar charts with showlegend false option

### ISSUE THREAD

**Issue by nflorentin** [plotly/plotly.js#2236]
Hi,

It seems that the display of labels fails with a bar chart with the following characteristics:
- a unique value on the x axis
- option "showlegend: false" for the layout

An example here: https://jsfiddle.net/m07hszmn/8/

**Comment by alexcjohnson** [comment]
Duplicate of #2154 (and likely #865 by extension) I believe. Feel free to reopen if I'm missing something.
