### ISSUE TITLE
Title is different in plotly.min.js vs plotly-cartesian.min.js

### ISSUE THREAD

**Issue by ricazhang** [plotly/plotly.js#2237]
When I'm using the full plotly bundle, not passing in a title in the layout object means that there is no title on the chart. However, when I'm using the plotly cartesian bundle, not passing in a title in the layout object results in a "Click to enter Plot title" placeholder.

Full:
![plotly full](https://user-images.githubusercontent.com/7819877/34693991-65a9516a-f47a-11e7-99c5-dfafceea318b.PNG)

Cartesian:
![plotly cartesian](https://user-images.githubusercontent.com/7819877/34693996-68d17606-f47a-11e7-808e-d2e5670167f8.PNG)

**Comment by alexcjohnson** [comment]
@ricazhang can you post a codepen/jsfiddle showing this? I don't see that when using the latest cartesian bundle from the CDN: https://codepen.io/alexcjohnson/pen/aEqrEY.

That's normally what happens when you use config `{editable: true}`, then you can click on that title and type in a new one. It's weird that you would see this without explicitly adding that config flag.

**Comment by ricazhang** [comment]
Hi, yeah I have the editable flag set to true. (For explanation: there are some situations where I want to allow editing of the axis titles but not allow editing of the title because I made the title into a separate HTML element since I need multi-line titles and plotly doesn't support that at the moment.)

**Comment by ricazhang** [comment]
I think I must have been using a different version. I see in the CodePen with the latest versions that the behavior is consistent. 

Also I found  an alternate solution -- using the margins to crop out the title area entirely.

Thanks! I'll go ahead and close this.

**Comment by alexcjohnson** [comment]
Ah great. FWIW there may be simpler ways to manage your title too. Re:
> I need multi-line titles and plotly doesn't support that at the moment. 

In fact it does, though for the moment anyway the user needs to know how to do it. We support a subset of HTML including `<br>` among other things: https://help.plot.ly/adding-HTML-and-links-to-charts/
