### ISSUE TITLE
Mesh3d hover text not shown

### ISSUE THREAD

**Issue by Helsioufy** [plotly/plotly.js#2242]
I was trying to draw a mesh3d with customized hover text in the below example:

https://codepen.io/Elsioufy/pen/JMLEmP

Yet the hover text did not appear to be shown in the graph. it is working with scatter3d and surface though.

``` 

var gd = document.getElementById('graph');

var x = [1, 1, 2, 3, 4, 2];
var y = [2, 1, 3, 4, 5, 3];
var z = [3, 7, 4, 5, 3.5, 2];

// fill in 'text' array for hover
var text = x.map((xi, i) => `
ts: ${xi}<br>
hz: ${y[i]}<br>
ftt: ${z[i]}`)

Plotly.plot(gd, [{
  type: 'mesh3d',
  text: text,
  hoverinfo: 'text',
  x: x,
  y: y,
  z: z,
  text: text,
}], {
  scene: {
    xaxis: { title: 'x'},
    yaxis: { title: 'y'},
    zaxis: { title: 'z'},
  }
});
```
![no_text](https://user-images.githubusercontent.com/16387211/34777195-3af30aca-f622-11e7-883f-4da0c7ad1f43.png)

**Comment by alexcjohnson** [comment]
This trace also seems to suffer from misplaced hover ala #2208
