### ISSUE TITLE
'dragElement.init is not a function'

### ISSUE THREAD

**Issue by nite** [plotly/plotly.js#2245]
Hi - getting an error `dragElement.init is not a function` in an angular5 app with webpack - using the webpack config from here: https://github.com/rreusser/plotly-webpack/blob/master/webpack.config.js

```
<div #plotContainer></div>

import {Data, register} from 'plotly.js/lib/core';
import {Layout} from 'plotly.js';
import * as Plotly from 'plotly.js/lib/core';
...
@ViewChild('plotContainer') chartContainer: ElementRef;
...
const data = [{
                x: ['giraffes', 'orangutans', 'monkeys'],
                y: [20, 14, 23],
                type: 'bar',
            }];
            Plotly.newPlot(this.chartContainer.nativeElement, data);
```

plotly.js@1.31.2

Any ideas?

**Comment by etpinard** [comment]
What's `this.plotly` and `this.chartContainer` in this case? It would help if you could bundle up your use case in e.g. a [github gist](https://gist.github.com/). Thanks.

**Comment by nite** [comment]
I've updated the comment above - plotly was injected to our constructor, but it effectively was a factory providing Plotly, so the above should be the same. 

I'll endeavour to extract into a standalone angular 2 app to replicate asap, but I imagine I'm somehow not importing the bit of plotly that's needed to provide dragElement (both drag/zoom & tooltips are not working)

**Comment by nite** [comment]
Actually, I noticed that fixes it - so injecting actually breaks it - ie. 

```
import * as Plotly from 'plotly.js/lib/core';
export function PlotlyFactory(): Plotly {
    return Plotly;
}

```
`{provide: 'plotlyLib', useFactory: PlotlyFactory}`
`constructor(@Inject('plotlyLib') private plotly)`

I'll work around this somehow here using a direct import.

**Comment by nite** [comment]
This fixes it - I'm not sure why we needed the factory! 
`import * as Plotly from 'plotly.js/lib/core';
{provide: 'plotlyLib', useValue: Plotly}`
