### ISSUE TITLE
Dont allow pan past the data last data point

### ISSUE THREAD

**Issue by skunheal** [plotly/plotly.js#2248]
It would be really nice to not allow users to pan past the last data. I cant find any option for this. I also tried doing this using the on relayout event and prevent it from panning when the data is past a certain x axis point but I cant find a way to prevent the panning from happening.

**Comment by alexcjohnson** [comment]
Yes, we've discussed a mode that does this, but it's not implemented yet. See https://github.com/plotly/plotly.js/issues/1876
