### ISSUE TITLE
scatter plot in javascript: `line` width not working  

### ISSUE THREAD

**Issue by slfan2013** [plotly/plotly.js#2250]
Please see [here](https://codepen.io/slfan2013/pen/NXzQva?editors=1010).

The `line:{width:10}` does not affect the size of the line but affect the size of the markers (i.e. scatters).

**Comment by dfcreative** [comment]
Please use `line: {width: 10}` outside of the scope of `marker`
```js
var trace1 = {
  x: [1, 2, 3, 4], 
  y: [10, 15, 13, 17], 
  type: 'scatter',
  mode:"lines",  marker:{},
  line: {width:10}
};
```

https://codepen.io/dmitryf/pen/BJPJdp?editors=1010
