### ISSUE TITLE
candlestick graph hoverinfo shows strange labels for open/close/low/high

### ISSUE THREAD

**Issue by AfroMetal** [plotly/plotly.js#2253]
With update of `dash-core-components` to 0.17.0 my candlestick (Python: `plotly.graph_objs.Candlestick`) chart behaves strangely on hover. `hoverinfo` is set to `x+y` for date on x axis and open/close/high/low values on candle. It looks like an error in the underlying `plotly.js`

Before (dcc 0.15.5, based on old plotly.js) it showed only the values.

But now (dcc 0.17.0, based on new plotly.js 1.32.0) each candle value has a unwanted label `min:`, `max:`, `q1:`, `q3:` and `median:`.

First mentioned in (with example screenshots): https://community.plot.ly/t/dcc-graph-candlestick-hoverinfo-shows-strange-labels/7764

**Comment by alexcjohnson** [comment]
Thanks @AfroMetal - candlestick is showing a bit more of its box plot roots than it should. Possibly came in with localization #2195 ?
