### ISSUE TITLE
Polar 2.0 open items

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#2255]
Followup issue of https://github.com/plotly/plotly.js/pull/2200 and the on-par polar [milestone](https://github.com/plotly/plotly.js/milestone/2).

------

### Features we could easily add
- [ ] radial and angular axis `spikes`
- [ ] support for `radialaxis.side: 'center'` to display radial axis labels along invisible radial axis lines
- [x] radial axis _hole_ (similar to pie `hole`, mpl [example](https://github.com/matplotlib/matplotlib/issues/4217)) - done in https://github.com/plotly/plotly.js/pull/2977
- [x] support square grid lines for category angular axes [example](https://matplotlib.org/_images/radar_chart.png) - done in https://github.com/plotly/plotly.js/pull/2739
- [ ] some way to _snap_ to NSEW corners during angular drag
- [ ] way to activate radial (and possibly angular down the road) autorange on double click (i.e. implement `doubleClick: 'autosize'` config option
- [ ] radial (and angular?) axis zeroline
- [ ] polar (r,theta) data-referenced annotations
- [ ] trace-specified and radial-axis calendars
- [ ] make polar respect `gd._context.showAxisDragHandles`? 

### Potential features that require some thought

- [x] How to replace legacy polar's `area` trace type? I'd vote for replacing it with `polarbar` or `wedge`. Most of the `bar` logic could be reused here. **Moved to ->** https://github.com/plotly/plotly.js/issues/2810 **Done in ->** https://github.com/plotly/plotly.js/pull/2954
- How to replace legacy polar's (r,t) `bar` traces? I'd vote simply removing them, unless someone out there finds them useful.
- What to do with `r < 0` values? In #2200, they are simply dismissed, but perhaps we should add an option to plot them on the opposite side of the origin. See https://github.com/plotly/plotly.js/pull/2200#commitcomment-26416872
- Date angular axes. See examples in https://github.com/plotly/plotly.js/pull/2200#discussion_r156397924) and some considerations in the last part of https://github.com/plotly/plotly.js/commit/1e81039384ebf89de376c3ddd004d0f103278fa6#r26653662 **Moved to -->** https://github.com/plotly/plotly.js/issues/4379
- Should we allow `angularaxis.period` to be less then the number of categories on categorical angular axes? See https://github.com/plotly/plotly.js/pull/2200#discussion_r161143299
- [x] Maybe add `r0`, `dr`, `theta0` and `dtheta`. For the `theta` pair, it might be tricky to find a _correct_ default the everyone likes. **Done in ->** https://github.com/plotly/plotly.js/pull/2895
- Add another zoombox mode? Perhaps a pixel-based zoom using `polar.x`, `polar.y`, `polar.zoom` scalars to describe it? See https://github.com/plotly/plotly.js/pull/2200#issuecomment-351127938
- scatterpolar (r,theta?) error bars 
- Properly clip `scatterpolargl` line segments

**Comment by etpinard** [comment]
- [ ] make polar subplot drag tests more robust. They currently fail intermittently on CI. They are now skipped on CI as of https://github.com/plotly/plotly.js/pull/2258/commits/8bebc2e60e3fe74b2c8c67474d394c5d927443fb. Replicating the issue is hard. I wasn't able to replicate it on my laptop. Even on CI, you need to run all the suites at once to _sometime_ see those tests fail. See commits https://github.com/plotly/plotly.js/pull/2258/commits/40f60de987ed2b1460327d1840faf6475bbf09fa

**Comment by etpinard** [comment]
From @alexcjohnson 's https://github.com/plotly/plotly.js/pull/2739#discussion_r197297290

- [ ] we should have a mode in scatterpolar to join the endpoints together so you don't need to repeat the initial point when the data are meant to be periodic. trace.connectends perhaps, to mirror trace.connectgaps?

**Comment by alexcjohnson** [comment]
@etpinard a request has come in for radial axis `hole` (third checkbox above) and legacy `area` type replacement (first bullet point). `hole` is straightforward enough that I think this checkbox will suffice to track it, but I'll make a new issue for `area` so we can hash out the API without overrunning this thread.

**Comment by etpinard** [comment]
> , but I'll make a new issue for area so we can hash out the API without overrunning this thread.

Sounds good!

**Comment by etpinard** [comment]
- [ ] maybe split style attributes between inner and outer angular axes? See https://github.com/plotly/plotly.js/pull/2977#discussion_r215961253

**Comment by etpinard** [comment]
- [ ] improve `polar.hole=1` behavior, see https://github.com/plotly/plotly.js/pull/3021#issuecomment-422219082

**Comment by elben10** [comment]
Are there any timeline on when these issues is expected to be solved?

**Comment by nicolaskruchten** [comment]
@elben10 this is basically just a list of ideas at this point, no one is actively working on these that I know of, but we'd appreciate any help anyone can provide :)

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
