### ISSUE TITLE
 I want the X axis not to be in the center

### ISSUE THREAD

**Issue by lyy0808** [plotly/plotly.js#2256]
[lineplotjs.zip](https://github.com/plotly/plotly.js/files/1638045/lineplotjs.zip)
I want get a line ,but sometimes my x value is all zero (0),but this time .the x axis auto stand the center ,i holp get some help .what should i do. Thank you.
for example https://codepen.io/antsdouble/pen/NXOvGq

**Comment by alexcjohnson** [comment]
This kind of question is better asked at [community.plot.ly](https://community.plot.ly), but the easiest options are to explicitly set `xaxis.range` or if you want it to stay autoranged but always put zero on the left, perhaps `xaxis.rangemode: 'tozero'` would work for you.

**Comment by lyy0808** [comment]
Thanks ,it's work.
