### ISSUE TITLE
plotly_click doesn't fire when `fixedrange` is true

### ISSUE THREAD

**Issue by sporto** [plotly/plotly.js#2265]
Hello

When `fixedrange=true` for xaxis and yaxis
`plotly_click` events do not trigger.

Please see
https://codepen.io/sporto/pen/WdLvro?editors=0010

Thanks

**Comment by sporto** [comment]
This bug was introduced in 1.32

**Comment by alexcjohnson** [comment]
Ah yep, that probably came in with #2241 - thanks for the report.
