### ISSUE TITLE
regl ScatterGL points disappear during selection selection with large number of points

### ISSUE THREAD

**Issue by jmmease** [plotly/plotly.js#2266]
First off, the new regl-based `scattergl` is awesome. Thanks @dfcreative and @etpinard 

### Description
When I create a `scattergl` plot with 20k+ points, the points disappear during a selection operation (both lasso and box select). After double clicking to exit the selection mode the points re-appear. In the console, I see the following error.

```
4VM7119:2 Uncaught TypeError: Cannot read property '222' of undefined
    at A (eval at i (VM6265 plotly-1.33.0.min.js:7), <anonymous>:2:62)
    at Object.dispatchBsearchGE [as ge] (eval at i (VM6265 plotly-1.33.0.min.js:7), <anonymous>:2:360)
    at y (VM6265 plotly-1.33.0.min.js:7)
    at v (VM6265 plotly-1.33.0.min.js:7)
    at VM6265 plotly-1.33.0.min.js:7
    at Array.forEach (<anonymous>)
    at Function.p [as draw] (VM6265 plotly-1.33.0.min.js:7)
    at Object.e._scene.r.draw (VM6265 plotly-1.33.0.min.js:7)
    at Object.style (VM6265 plotly-1.33.0.min.js:7)
    at i (VM6265 plotly-1.33.0.min.js:7)
```
Things work fine when I test with around 10k points.

Example pen: https://codepen.io/anon/pen/WdLgWQ

### Details
 - Plotly 1.33.0 from the CDN
 - Chrome Version 63.0.3239.132 on OS X

**Comment by dfcreative** [comment]
@jmmease thank you! Will be fixed with #2267

**Comment by meganrm** [comment]
**Description**
I have this same problem, but without any error.  This is ~30,000 points. When I plotted less than 10,000. 

Example site: https://meganrm.github.io/plotting-tool/

**Details**
Plotly 1.37.1 from npm
Chrome Version 66.0.3359.139

Should I create a new issue?

**Comment by etpinard** [comment]
Thanks for reporting this.

> Should I create a new issue?

If you could isolate the problem in a codepen/jsfiddle/jsbin with just your data/layout graph - it would help us immensely.

**Comment by meganrm** [comment]
Here is a plot using my data: https://codepen.io/meganrm/pen/odKveW

Both box select and lasso select make all the points go away. I haven't tested to see if the callback still gets the points or not. And I don't see any errors.
