### ISSUE TITLE
Restyling x or y values with null values creates a ghost when filling is enabled

### ISSUE THREAD

**Issue by ChristofferHS** [plotly/plotly.js#2271]
If you restyle the x or y values of a trace that forms part of a filled area with an array of `null` values, you get a ghost in the shape of the original filled area. It shows up at any zoom level and regardless of how you pan.

[CodePen](https://codepen.io/ChristofferHS/pen/PEXgLv)

**Comment by alexcjohnson** [comment]
Thanks for the very clear report @ChristofferHS 🏆  I used it almost verbatim in testing my fix -> #2280
