### ISSUE TITLE
plotly_click not working after version 1.31.2

### ISSUE THREAD

**Issue by step42** [plotly/plotly.js#2272]
Hi,
the code below used to work with version <= 1.31.2. Now with the version 1.32 the plotly_click is no longer called. Any ideas why?

Thanks
Step

```
plot(props) {
    const plotlyChart = document.getElementById(this.handle)

    // remove all previous listeners from the div plotlyChart element
    if (plotlyChart.removeAllListeners) {
      plotlyChart.removeAllListeners()
    }

    Plotly.purge(plotlyChart)
    Plotly.newPlot(this.handle, data, layout, config)

    // before events it is needed to update the plot
    Plotly.update(this.handle, data, layout)

    plotlyChart
      .on('plotly_click', function (clickEvent) {
        this.props.onDateClick(clickEvent.points[0].x)
      })
....
}
```

**Comment by alexcjohnson** [comment]
@step42 What's on your plot? I'm aware of #2265 if you've got fixed range axes. There's also a new version 1.33 out yesterday, can you check with the latest release?

**Comment by step42** [comment]
Yes, this still happens with 1.33.0. The graph is a bar chart.

**Comment by alexcjohnson** [comment]
OK, I'm going to need a bit more information than that - generally as far as I can tell bar charts do still support `plotly_click`. Please see if you can demonstrate the issue in a codepen or some other platform where I can see it in action.

**Comment by step42** [comment]
Alex, taking the code out and put it into codepen will require some significant time. It has dependencies to react and specific data and currently it is not so easy to isolate the code (I agree this is not ideal). Is there something quick I can investigate on my end to get to the root cause quicker?

**Comment by step42** [comment]
Ok, this codepen shows the issue
https://codepen.io/step42/pen/goEZWo?editors=1111

I don't see the console log when I click a bar.
Btw, how do you select an older version in the codePen?

**Comment by alexcjohnson** [comment]
Thanks @step42 - this is indeed #2265 (`fixedrange`) as I mentioned in my first comment - click is emitted if you remove `xaxis.fixedrange` (`yaxis.fixedrange` is set `true` by default since you have a `rangeslider`)

You can load old versions from the CDN like:
`<script src="https://cdn.plot.ly/plotly-1.31.0.min.js"></script>`

**Comment by step42** [comment]
Thanks. That fixed it!
