### ISSUE TITLE
Implement per-subplot hovermode 

### ISSUE THREAD

**Issue by paulsputer** [plotly/plotly.js#2274]
It appears that when the cartesian axes are flipped (i.e change x to y, and y to x) in both layout and data the resulting chart whilst looking correct has a different UX, namely the hoverinfo.

![ycat-xlin](https://user-images.githubusercontent.com/4686906/35186591-54d38868-fe0e-11e7-88be-9c19fc942081.gif)
`{yaxis.type:'category'}`
`{xaxis.type:'linear'}`
 As expected moving the mouse from left to right displays the label cursors and values.

(_unfortunatley the screen capture doesn't capture the cursor, but it is moving_)
![xcat-ylin](https://user-images.githubusercontent.com/4686906/35186595-568d0a44-fe0e-11e7-9a1e-c894d85711c5.gif)
`{yaxis.type:'linear'}`
`{xaxis.type:'category'}`
Moving the mouse from bottom to top does not change the the hoverinfo.  Only the hoverinfo for the last element in the data array is displayed. In addition the black cursor for hoverinfo would display the y axis and the blue cursor for hoverinfo would display the x axis.

Perhaps hoverinfo flaglist should interpret order of occurrence to determine which to move, or is there a more appropriate place to handle this?

**Comment by alexcjohnson** [comment]
Is this using the default `hovermode='x'` ("Compare data on hover" in the modebar)? You may have better luck with `hovermode='closest'` ("Show closest data on hover"), which I'm starting to think should be often or always the default...

When you use horizontal *bar* traces, we turn compare into `hovermode='y'`, ie compare values with the same y value across multiple traces - which behaves as you seem to have in mind. We don't do that for scatter traces - I'm not sure we could find a robust condition indicating that we should make this switch. You can enable it explicitly with `Plotly.relayout(gd,{hovermode: 'y'})`, though if the user changes hovermode from the modebar it would revert.

**Comment by paulsputer** [comment]
Perfect, thank you, yes `hovermode=closest` works well.  On first glance it looked as though we could do with `hovermode` being settable on a per trace basis just as `hoverinfo` is.  Looking closer at the code in `hover.js` that might not be as easy it sounds when there are multiple traces, unless it defaulted to the `layout.hovermode`.

Would that be a useful feature here or is it perhaps too much of an edge case?

**Comment by alexcjohnson** [comment]
I guess `hovermode` actually controls two pieces of behavior:
- Can you get multiple labels, or at most only one? (`x/y`: multiple, `closest`: one)
- Which coordinates are used to determine distance to data points? (`x`: x, `y`: y, `closest`: both)

If we wanted this to be a per-trace attribute, we'd have to split those two apart, as the former isn't about the behavior of a single trace at all. But it strikes me as potentially confusing to have each trace behave differently in this regard.

We have discussed possible per-*subplot* control over hovermode, though we have no concrete plans to implement it. For example this plot might want `closest` in the main subplot, `x` on top, and `y` on the right:
![screen shot 2018-01-21 at 1 29 29 pm](https://user-images.githubusercontent.com/2678795/35197575-3f0246a4-feaf-11e7-8661-83b481d1dff1.png)

**Comment by paulsputer** [comment]
Yea there looked to be a fair bit of logic in there, that makes sense.  Certainly per-subplot is the way forward.

In my offline fork I've added such functionality though it's a bit hacky as I've added a `_subplotoptions` to the `newFullLayout`, perhaps the more elegant way would be using the existing `_subplot` but that looks like it contains generated string ID arrays for each coordinate space.  Turning them into fully fledged objects holding options looked like it would involve a lot changes...  

If you're happy with the addition of a `_subplotoptions` solution I can push a PR for review when I get a moment.

**Comment by etpinard** [comment]
Ok if I change the issue title to _Implement per-subplot hovermode_ ?

Referencing other per-subplot feature requests https://github.com/plotly/plotly.js/issues/977 and https://github.com/plotly/plotly.js/issues/233

**Comment by paulsputer** [comment]
Sure @etpinard

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
