### ISSUE TITLE
Bug - heatmap renders with wrong colors when using zsmooth

### ISSUE THREAD

**Issue by LarryMartell** [plotly/plotly.js#2275]
Here are 2 codepens showing the issue. They both have the same data, one with zsmooth, one without - the one without zsmooth shows the correct colors, the with shows the wrong colors. 

zsmooth, wrong colors: https://codepen.io/LarryMartell/pen/aEPxbZ?editors=0010
no zsmooth correct colors: https://codepen.io/LarryMartell/pen/GyzrGE?editors=0010

You have to zoom in to see the data points. Attached are 2 screen shots showing the correct and incorrect colors. 

I contend that no matter what, zsmooth or not, shouldn't it be that the color for a given value shows the same and 
![screen shot 2018-01-20 at 10 19 56 am](https://user-images.githubusercontent.com/1308192/35189364-008fb944-fe17-11e7-94f5-de80517e9621.png)
![screen shot 2018-01-20 at 10 20 04 am](https://user-images.githubusercontent.com/1308192/35189365-009dbcd8-fe17-11e7-829f-79da03a21a6a.png)

proper color?

**Comment by alexcjohnson** [comment]
Thanks @LarryMartell - I believe this is another manifestation of #2233 - see specifically https://github.com/plotly/plotly.js/issues/2233#issuecomment-355374410 - we're confusing the brick center and the data point, when bricks are nonuniform sizes.

**Comment by LarryMartell** [comment]
I submitted this bug report because I was asked to by Chelsea Douglas from your support group. I reported this issue to support and she said “As far as I can tell this is the expected outcome, but you're always welcome to open an issue in the plotly.js repo: https://github.com/plotly/plotly.js/issues with a reproducible example“ so that is what I did.

**Comment by alexcjohnson** [comment]
Oh sure - please don't take my closing the issue as an indication you were wrong to open it, just that it has the same cause as another issue so I combined them. This is a tricky one, so I'm glad @cldougl steered you here.
