### ISSUE TITLE
what is the difference between _fullData, and _inputData, and can we make _inputData more complete?

### ISSUE THREAD

**Issue by VeraZab** [plotly/plotly.js#2281]
So, for fin charts, the true type of a trace is found in gd._fullData[0]._fullInput.type
And I was thinking that perhaps to look for all of the 'true' values for a trace, instead of looking in _fullData as we always are, we could always by default look into the _fullInput object.

But it turns out the _fullInput object is not as complete as the _fullData one.

Here's an example with ohlc charts. You can find line.color in _fullData, but not in _fullInput.
https://codepen.io/veraz/pen/KZYRVe?editors=1010

Was wondering if it'd be hard/possible to have everything in _fullInput so as to use that as the most complete reference to a trace's attributes? @alexcjohnson @etpinard ?

thanks!

**Comment by etpinard** [comment]
`fullInput` is what we should use to build the toolpanel for finance traces. 

True `fullInput.line` is incomplete (actually I think it should be undefined :thinking: ), but I think `fullInput.increasing.line` and `fullInput.decreasing.line` are the attributes of interest here.

**Comment by etpinard** [comment]
Closing. I think the conclusion to make here is: `ohlc` and `candlestick` are a mess. We should try to rewrite them using a convention `plot` step (instead of our brutal transform trace hack). This should make everyone (toolpanel dev included) happy.
