### ISSUE TITLE
Feature request: notched box plots

### ISSUE THREAD

**Issue by krassowski** [plotly/plotly.js#2286]
I searched thoroughly for such option, but found only this unanswered post on plotly community website: [Add option notch to box plots](https://community.plot.ly/t/add-option-notch-to-box-plots/7396).

Here is some short introduction: https://sites.google.com/site/davidsstatistics/home/notched-box-plots
Here is a reference for notches from MATLAB: https://www.mathworks.com/help/symbolic/mupad_ref/notched.html,
And here is a question from stackexchange to highlight how notches should be sometimes rendered "inside-out": https://stats.stackexchange.com/questions/151580/how-to-interpret-notched-box-plots

Is such an option in-scope of plotly?

**Comment by alexcjohnson** [comment]
Yes, definitely in scope. We may not get to it for a while but we'd happily review a PR to add it!

**Comment by krassowski** [comment]
Hi there! I got some time today to implement the notches. I created a PR in my fork: https://github.com/krassowski/plotly.js/pull/1.

@alexcjohnson, @jackparmer - would you mind to have a look on my PR and let me know if I should change anything or reopen it against the upstream?

Here is an example baseline:
![](https://raw.githubusercontent.com/krassowski/plotly.js/a234668c7af2e2409052fe06817f939b931dad5f/test/image/baselines/box_notched.png)
