### ISSUE TITLE
Correct Webpack instructions in README

### ISSUE THREAD

**Issue by ngauthier** [plotly/plotly.js#2294]
Following guidelines, I've made the PR here for review before I submit the PR to this repository. First time contributor, let me know if there's anything I should do differently.

https://github.com/ngauthier/plotly.js/pull/1

**Comment by alexcjohnson** [comment]
@nicolaskruchten @dfcreative you guys have been tweaking our webpack compatibility - care to comment here?

**Comment by dfcreative** [comment]
@alexcjohnson LGTM :dancer:
