### ISSUE TITLE
Plotly Disables Latex Rendering in HTML output of Jupyter Notebook

### ISSUE THREAD

**Issue by SafwanAhmad** [plotly/plotly.js#2300]
In my limited understanding of Javascript it seems like a plotly.js or an NbConvert bug. 

Plotly is using the following configuration option for MathJax:
`MathJax.Hub.Config({messageStyle:"none",skipStartupTypeset:!0` 

Looking at the code [here](https://github.com/plotly/plotly.js/blob/5bc25b490702e5ed61265207833dbd58e8ab27f1/src/lib/svg_text_utils.js#L174)  and in light of the MathJax documentation [here](https://docs.mathjax.org/en/v1.0/typeset.html) it's more of a Plotly issue IMHO than a bug in Nbconvert.

```
 MathJax.Hub.Queue(['Typeset', MathJax.Hub, tmpDiv.node()], function() {
        var glyphDefs = d3.select('body').select('#MathJax_SVG_glyphs');

        if(tmpDiv.select('.MathJax_SVG').empty() || !tmpDiv.select('svg').node()) {
            Lib.log('There was an error in the tex syntax.', _texString);
            _callback();
        }
        else {
            var svgBBox = tmpDiv.select('svg').node().getBoundingClientRect();
            _callback(tmpDiv.select('.MathJax_SVG'), glyphDefs, svgBBox);
        }

        tmpDiv.remove();
    });

```
Only Latex inside a particular DIV element is queued for Mathjax rendering by Plotly. This makes sense but combined with the configuration above, perhaps, disables automatic rendering in the rest of the page. Nbconvert's HTML seems to rely on this document-wide auto rendering.

**Comment by alexcjohnson** [comment]
Thanks @SafwanAhmad - seems to me this is also problematic as we need MathJax to render SVG, while nbconvert wants HTML. I guess we will need to do some gymnastics to figure out whether anyone else on the page needs MathJax, and work around that. It's not obvious to me how to tell whether MathJax is configured for SVG or some other output, but I assume there's a way...

One possible short-term workaround, if you want LaTeX in your page but don't need it in your plotly plots, we could try and find a way to short-circuit Plotly's MathJax config, or at least defer it until it's actually invoked.

**Comment by alexcjohnson** [comment]
Possibly useful: https://github.com/mathjax/MathJax-docs/wiki/Using-different-mathjax-renderers-on-one-page

**Comment by akhmerov** [comment]
Following @alexcjohnson's link, and after a bit of trial and error, I was able to embed plotly plots into a website that configures its own mathjax by using the following:

```javascript
window.addEventListener('load', function() {
  MathJax.Hub.Queue(
    ["setRenderer",MathJax.Hub,"SVG"]
  );
  Plotly.d3.json('/{{plotly_url}}', function(error, fig) {
    Plotly.plot('{{div_id}}', fig.data, fig.layout);
  MathJax.Hub.Queue(
    ["setRenderer",MathJax.Hub,"HTMLCSS-output"]
  );
  });
});
```

It isn't pretty, but it is sufficient in my limited context.

**Comment by anil-ganti** [comment]
@akhmerov what is the limited context that your solution works in? I haven't been able to get this working in my context.

**Comment by akhmerov** [comment]
@anil-ganti compiling a bunch of [markdown files with inline code](https://gitlab.kwant-project.org/solidstate/lectures/blob/master/src/lecture_6.md#L177-254) into a [static website](https://solidstate.quantumtinkerer.tudelft.nl/lecture_6/#fermi-surface-using-a-nearly-free-electron-model). Business logic [here](https://gitlab.kwant-project.org/solidstate/lectures/blob/master/execute.py)

**Comment by jonmmease** [comment]
This has been addressed in plotly.js 1.42 by #2994. You'll need to set `window.PlotlyConfig = {MathJaxConfig: 'local'}` before loading plotly.js. See https://github.com/plotly/plotly.js/blob/master/dist/README.md#to-support-mathjax for more information. Thanks!
