### ISSUE TITLE
Latex does not display properly in legend

### ISSUE THREAD

**Issue by LiteracyFanatic** [plotly/plotly.js#2303]
Using Latex markup in the names of legend entries results in text which overlaps the marker. A codepen showing the problem can be found [here](https://codepen.io/anon/pen/vdBmGL) but the same problem is present in the plots used for the [documentation](https://plot.ly/javascript/LaTeX/) as well.

![image](https://user-images.githubusercontent.com/18249574/35477926-e096244c-0394-11e8-9fb8-b41b9b9a76d0.png)

**Comment by alexcjohnson** [comment]
Thanks @LiteracyFanatic - This seems to have been broken for a while, prior to v1.28 it works. Possibly broke in #1783?

**Comment by etpinard** [comment]
Related https://github.com/plotly/plotly.js/issues/966

**Comment by etpinard** [comment]
Fixed in https://github.com/plotly/plotly.js/pull/3018
