### ISSUE TITLE
console errors when calling Plotly.newPlot in tables

### ISSUE THREAD

**Issue by VeraZab** [plotly/plotly.js#2312]
See this codepen for ex:
https://codepen.io/veraz/pen/oEgRJK?editors=1010

@monfera the new (editor)[https://github.com/plotly/react-plotly.js-editor] closely relies on plotly.js.

It's failing for table traces because there's errors in the console once we're trying to gradually create a table trace. Because of the console errors, this react-plotly.js call never entirely completes and instead falls into this catch statement: https://github.com/plotly/react-plotly.js/blob/9dc4e4f8810c150c88c08c81b8432d6e9952641e/src/factory.js#L126

It should be possible to gradually create a trace without it throwing console errors.
cc @alexcjohnson

**Comment by monfera** [comment]
Thanks @VeraZab I'll take a look!
