### ISSUE TITLE
Data format Setting question

### ISSUE THREAD

**Issue by lyy0808** [plotly/plotly.js#2316]
A question hit me. I have a time axis  which show  format is month/day/year  like this:
![02](https://user-images.githubusercontent.com/12517231/35656674-9087e8b2-0733-11e8-977c-24d9d7f59945.png)
but i want the format is year /month/day .so i set the tickformat Attributes, then i get another question .very lable tick get the year/month/day ,which is'nt my want. like this
![01](https://user-images.githubusercontent.com/12517231/35656667-7cff5c4e-0733-11e8-9115-c59304257203.png)
the line example is https://codepen.io/ants-double/pen/GQJeev?editors=1010 
Can you help me ? 
I want two line axis the one is hour/minuter .The other is year/month/day .just like the default .but the format change year/month/day .Thank you.

**Comment by etpinard** [comment]
Have you tried setting `xaxis.hoverformat` instead?

-----------

Closing.

**Comment by etpinard** [comment]
... as per our contributing guidelines, questions of likes should be asked on https://community.plot.ly/

Thank you.

**Comment by lyy0808** [comment]
ok ,i add Escape and format ，Thank you.

**Comment by TomDemulierChevret** [comment]
Just a quick side note, what you are look to do will be possible when 1.34.0 is released with this : https://github.com/plotly/plotly.js/pull/2261
