### ISSUE TITLE
Bug - Hoverformat for second axis fails if axis is not visible

### ISSUE THREAD

**Issue by emanuelnastasa** [plotly/plotly.js#2317]
**Observed behavior:**
Having a chart with 2 Y axes, if you mark the second Y axis as "visible:false" the hoverformat property for that axis is ignored and the values are shown in exponential form.

**Expected behavior:**
The hoverformat is respected regardless of the visible parameter.

**Steps to reproduce:**
1.Access the JSFiddle:https://jsfiddle.net/a75dhu5z/
2. Change layout.yaxis2.visible between false and true and observe the value displayed in the hover tool-tip of the top point in the orange trace.

**Build found**
It's reproducing in all builds from 1.31 to the latest release 1.33.1

**Comment by etpinard** [comment]
Thanks for the report.
