### ISSUE TITLE
Make sure all our deps use the same glslify version

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#2321]
This is a mess:

![image](https://user-images.githubusercontent.com/6675409/35707277-2087dc36-0777-11e8-8664-06847ed94295.png)

**Comment by etpinard** [comment]
Hold on. Can you update our `package-lock.json` file before closing this?

**Comment by dfcreative** [comment]
@etpinard oh, I ignore `package-lock.json`. I can set it up though, but it will take a while.

**Comment by etpinard** [comment]
@dfcreative it might be a good idea to spend time setting node8/npm5. If you don't this might lead to headaches down the road.

**Comment by dfcreative** [comment]
@etpinard done

**Comment by etpinard** [comment]
that was fast!

**Comment by dfcreative** [comment]
@etpinard I already have that installed, it is due to [`package-lock.json` issues](https://github.com/npm/npm/issues/16866) there were no way but disabling it.
