### ISSUE TITLE
scattergl won't draw line for points having same x-value or same y-value; whereas scatter works perfectly fine!

### ISSUE THREAD

**Issue by shahyash1993** [plotly/plotly.js#2335]
The codepen I have provided is quite self explanatory. Please have a look: https://codepen.io/ypshah-13/pen/GQqyeW

**Comment by alexcjohnson** [comment]
Thanks for the report.
cc @dfcreative - overlaid scatter and scattergl is beautiful - you can't do *that* in v1.31, but you *can* have horizontal and vertical lines...
