### ISSUE TITLE
The legend loses his position on a small screen with lot of items and horizontal orientation

### ISSUE THREAD

**Issue by gilles-crealp** [plotly/plotly.js#2337]
If you add a lot of items, then set the legend horizontal (`layout.legend.orientation = 'h'`) and the width of the graphic to a small value (like a smartphone), the legend (the scrollbox) is wrongly positioned.

See the [JSFiddle](https://jsfiddle.net/6oq39dpy/6/).

**Comment by alexcjohnson** [comment]
Thanks for the report. Seems to happen as soon as the legend gets a scrollbar.

**Comment by etpinard** [comment]
Will be fixed alongside https://github.com/plotly/plotly.js/issues/771, so I'll close ticket.
