### ISSUE TITLE
Format hoverinfo

### ISSUE THREAD

**Issue by mbonaci** [plotly/plotly.js#234]
Hi,
I know that it's possible to choose which info appears when you hover over a trace, but is it possible to format the contents, e.g. a number?
I'm primarily interested in rounding numbers to two or three decimal points and showing locale-sensitive thousand separator.
E.g. like using `Number` methods `toFixed()` and `toLocaleString()` in JavaScript :)

Thanks

**Comment by cldougl** [comment]
Hey @mbonaci 
You can round x and y hover values by setting hoverformat in layout.xaxis and/or layout.yaxis
using [D3 number formatting](https://github.com/mbostock/d3/wiki/Formatting).
Here's an example of [rounding numbers in hovertext](https://plot.ly/javascript/hover-text-and-formatting/#rounding-x-and-y-hover-values)

**Comment by mbonaci** [comment]
Thanks a lot, exactly what I was after.  
I thought if I used that property then would be forcing axis tickmark values to be formatted like that. Obviously not, from the suggested example :+1:
