### ISSUE TITLE
2 trace line chart is blank with scattergl

### ISSUE THREAD

**Issue by jackparmer** [plotly/plotly.js#2344]
https://plot.ly/~jackp/18341/

![image](https://user-images.githubusercontent.com/1865834/35898007-f355b8ea-0b91-11e8-8e75-b33454eab6da.png)

**Comment by etpinard** [comment]
fixed in current `master`:

![image](https://user-images.githubusercontent.com/6675409/35898183-ff1aa482-0b92-11e8-976d-72d9c85e772a.png)
