### ISSUE TITLE
Add support for more selected/unselecter marker attributes for scattermapbox

### ISSUE THREAD

**Issue by jackparmer** [plotly/plotly.js#2346]
https://codepen.io/plotly/pen/mXrQZg?editors=0010

![image](https://user-images.githubusercontent.com/1865834/35898972-b908af70-0b97-11e8-9bb0-8adc68f2b4f0.png)

**Comment by etpinard** [comment]
This is known limitation from https://github.com/plotly/plotly.js/pull/2135/commits/f54a08a0e34b8de127ee9cae8a890a886cd58042

Changing this to `type: feature`

**Comment by jackparmer** [comment]
`selected.marker.opacity` does not seem to work either with the latest Plotly.js:

![image](https://user-images.githubusercontent.com/1865834/35899171-e8742932-0b98-11e8-8aca-a811b9070821.png)

**Comment by jackparmer** [comment]
Here's another example of this issue with `selected.marker.opacity`. Try setting the unselected opacity to 0 in this plotly.js mock:

https://codepen.io/plotly/pen/NyRedR?editors=0010

![image](https://user-images.githubusercontent.com/1865834/35899488-ba13ece2-0b9a-11e8-8f60-599905ec9c98.png)

The current behavior is basically no different than without the selections API.
