### ISSUE TITLE
Time data type and/or possible high-precision datetime data

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#2349]
Split out this discussion from #420 as it's not related to v2.

From @finger563 -
> Regarding the removal of support for specifying date as epoch time in ms, is there no desire to support plots which specify time as epoch nanoseconds? Seeing as I have just such plots I'd be very interested to know :)

To which I replied:
> The precision we have right now - 100 microseconds, one digit better than native dates support - is the best I found I was able to reliably handle using a single javascript number to specify the coordinate. I could imagine a system supporting arbitrary precision within a restricted range where the zero point of the axis linearization is allowed to float - this would be a fairly big project but could be done if someone was sufficiently interested in sponsoring it ;)

From @ancapdev -
> Is it possible to do something simpler for dateless timestamps? Time of day to nanosecond precision requires 47 bits and fits comfortably in double. It would be quite useful for financial time series on intraday tick data.

Dateless times are interesting, that's definitely a use case we would consider adding. I'm curious how we should handle some cases, like do we wrap around midnight (treat the axis as periodic like longitude) or do we accept hours outside 0-23, ie negative hours for the previous day, or 24+ for subsequent days? Most of the cases I can think of hours outside 0-23 seems to make more sense, then you can treat this as a generic "time interval" axis rather than being specifically limited to "time of day".

Then we can ask if there should be a way to add "days" to the format. I don't think it can be `DD:HH:MM:SS.sss` or it would be impossible in general to distinguish `DD:HH:MM` from `HH:MM:SS`, but perhaps something like `DDdHH:MM:SS.sss`? Not sure if there's a convention out there...

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
