### ISSUE TITLE
Better positioning of hover labels for bars in compare hovermode

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#2350]
As reported by @saimaparveen with https://codepen.io/saimaparveen/pen/zRKXge - in `layout.hovermode: 'x'|'y'` the hover labels for bars go to the edge of the "category", which in some cases is confusingly far from any bars. We should move it in to match the actual bars we found.

**Comment by etpinard** [comment]
Updated codePen with `latest`: https://codepen.io/etpinard/pen/MQbOpY
