### ISSUE TITLE
Markers become semi-transparent when using size array

### ISSUE THREAD

**Issue by swiperii** [plotly/plotly.js#2351]
The following traces are identical, except for one difference: One uses  `marker: {size: 20}`, and the other `marker: {size: [20 20 20]}`. The trace with the size array gets transparent. 

A code example can be found [here](https://codepen.io/swiperii/pen/aqBVdZ)

![image](https://user-images.githubusercontent.com/13346835/35938254-d58a76cc-0c48-11e8-8f43-94d672e6ac5b.png)

**Comment by etpinard** [comment]
Yeah, the desired behavior. 

We default the `marker.opacity` to `0.7` [here](https://github.com/plotly/plotly.js/blob/ef2bff1904b50fa6fd01655ac37a588866a0e330/src/traces/scatter/marker_defaults.js#L35) whenever `marker.size` is an array. 

You can easily override our smart (or maybe too smart) default logic by setting `marker.opacity: 1`.
