### ISSUE TITLE
histfunc does nothing

### ISSUE THREAD

**Issue by palimondo** [plotly/plotly.js#2356]
I’m trying to use `histfunc: 'sum’` to do a weighted histogram (to visualize the cumulative error, so the `sum` of all data in the bin should work for this purpose).

I have specified the `histfunc` on my histogram trace, but it still uses count. I have also tried specifying `min`, `max`, `avg` to no effect:

https://codepen.io/palimondo/pen/NydQBG

**Comment by alexcjohnson** [comment]
`histfunc` needs a second data array (provided as `y` in this case) to aggregate within each bin. Thanks for mentioning it, we should clarify this in the docs.

**Comment by etpinard** [comment]
@palimondo to see an example, go to https://rreusser.github.io/plotly-mock-viewer/#hist_summed and open the dev console.

**Comment by etpinard** [comment]
Moved to https://github.com/plotly/documentation/issues/875
