### ISSUE TITLE
Faster extendTraces

### ISSUE THREAD

**Issue by BruceSherwood** [plotly/plotly.js#2358]
I originally posted these comments to the plotly.js forum, before realizing that they apparently belong here. Recently Etienne wrote in the forum of the intent to speed up extendTraces, to make incremental "live" graphing much faster. Currently I measure no significant difference between extendTraces and handing all of the data every time to Plotly. At the risk of stating what everyone knows, in my work on VPython over the years I’ve done several things to speed up incremental plotting. Perhaps these comments will be useful to the Plotly developers.

(1) When autoscaling, whenever a new point requires changing the scale, change the scale by a few percent more than needed to include the new point, so that there’s a good chance that a few later points can fit without readjusting the scale.

(2) For a lines object with no markers, discard any point that would be placed within a few pixels of the most recently plotted point. I’m doing this with my use of Plotly, and it can make a huge difference. Even without major improvements for incremental plotting, it would be useful for there to be a parameter to tell Plotly to discard points instead of me having to do the discarding; after all, Plotly knows more than I do about the pixel positioning. (The reason not to do this if there are markers is that in general markers on lines are important indications of endpoints of line segments.)

(3) Provide an “interval=N” option for all types of objects, in which Plotly only adds to the plot the Nth point, discarding the rest.

Also, my situation is one where intensive computations are coupled with incremental graphing of results of those on-going computations, in synchrony with the computations and associated 3D visualizations (using VPython). Both the JavaScript computations and the graphing are of course run off setTimeout(), and the challenge is to use as big a fraction of the second as possible for both activities.

Just before executing extendTraces I set lock = true, and when there arrives a callback from extendTraces that Plotly has finished, I set lock = false. While Plotly does its work (apparently with many calls to setTimeout), computations also run when they can, generating additional graphing data which however cannot be sent immediately to Plotly. So during the time that lock is true, data to be sent to Plotly is pushed to a list, waiting for the lock to become false, at which time extendTraces is driven again from the accumulated data (and the list of pending output is cleared).

My suggestion is that in a revision of extendTraces it would be very helpful to the Plotly user to have this lock machinery embedded in Plotly itself. In other words, extendTraces would be callable at any time but would actually trigger graphing (and clear the task list) when ongoing Plotly updates were complete. This would free up the Plotly-using program from having to implement this lock machinery itself.

Bruce Sherwood

**Comment by etpinard** [comment]
> before realizing that they apparently belong here

What makes you say that? As per our contributing guidelines, we like to keep our Github issue tracker for bug reports and feature requests only.

This ticket _could_ be a starting point for our upcoming `extendTraces` work. But user-land discussions should remain on https://community.plot.ly/c/plotly-js

Thank you.

**Comment by BruceSherwood** [comment]
Sorry. I thought I was making a feature request. I didn't get a response to these comments in the forum and so I thought I'd written to the wrong place. I thought of fast incremental plotting as a desired feature, since it's not currently part of plotly.js.

Bruce

**Comment by etpinard** [comment]
From #4455

----

I have created the SPC chart and extending the multiple traces frequently (Every 20 ms). Here is my [code](https://codepen.io/Ram97/pen/qBEPPmy).  As you can see the console in developer mode, the time taken to extend the multiple traces increasing based on the existing x and y arrays that was already plotted. 

If we extending single trace, the performance is very good.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
