### ISSUE TITLE
Dragging Annotation causes error (with repro case)

### ISSUE THREAD

**Issue by brian428** [plotly/plotly.js#2363]
If annotation is positioned on a date axis with "showarrow: false", dragging and releasing it throws: <g> attribute transform: Trailing garbage, "rotate(0,NaN,128.59)".

Here's a repro case: http://jsfiddle.net/brian428/v4ye0f4b/

If showarrow is true, the note and the arrow can be dragged successfully.

So far it **looks** like this only happens when a date axis is used.

**Comment by etpinard** [comment]
Thanks for the very clear bug report :beers:

**Comment by brian428** [comment]
Thanks!
