### ISSUE TITLE
Issue with hover labels

### ISSUE THREAD

**Issue by Maio93** [plotly/plotly.js#2370]
Hello,
I customized the hover event to trigger it on each subplots at the same time. When Plotly creates labels, it plots them in a single group. Is it possible force Plotly to plot each labels separately?

like in this example that uses an older version of Poltly: https://jsfiddle.net/2v2qp0hy/2/
this is my example on codpen: https://codepen.io/maio93/pen/OQxoZx

Thank you

**Comment by etpinard** [comment]
Thanks for the report. 

Looks like things were working fine up until `1.32.0`. Here's a working version with `1.31.2`: https://codepen.io/etpinard/pen/RQLzwq

**Comment by Maio93** [comment]
Perfect, thank you very much
