### ISSUE TITLE
scattergl lines don't show up under select/lasso drag modes

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#2376]
See https://codepen.io/etpinard/pen/ddZxmy?editors=0010

Originally reported in https://community.plot.ly/t/data-disappears-on-box-select/8392

cc @dfcreative

**Comment by alexcjohnson** [comment]
Also the modebar icons for box & lasso select don't show up with `mode: 'lines'` regardless of whether you've set yourself in one of those modes or not.

**Comment by dfcreative** [comment]
@etpinard will be fixed in https://github.com/plotly/plotly.js/tree/regl-scatter-patch
