### ISSUE TITLE
Cannot draw a simple plot:  Uncaught TypeError: Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by gramster** [plotly/plotly.js#238]
I'm trying to draw a simple heatmap with 1.5.1, but am getting this error.

    Uncaught TypeError: Cannot read property 'style' of undefined

It seems to be coming from:

    function lsInner(gd) {
        var fullLayout = gd._fullLayout,
            gs = fullLayout._size,
            axList = Plotly.Axes.list(gd),
            i;

        // clear axis line positions, to be set in the subplot loop below
        for(i = 0; i < axList.length; i++) axList[i]._linepositions = {};

        fullLayout._paperdiv
             .style({
                width: fullLayout.width + 'px',
                height: fullLayout.height + 'px'
            })
            .selectAll('.main-svg')
                .call(Drawing.setSize, fullLayout.width, fullLayout.height);

In my case fullLayout has no property named _paperdiv.

**Comment by gramster** [comment]
Looks like the offending code was quite recent: https://github.com/plotly/plotly.js/pull/160/files

**Comment by gramster** [comment]
Repo: https://jsfiddle.net/x3srtdjg/1/

**Comment by gramster** [comment]
Ah, my bad - didn't notice data needed to be an array. Adding [] around it fixes problem.

**Comment by etpinard** [comment]
Duplicate of https://github.com/plotly/plotly.js/issues/167
