### ISSUE TITLE
Strange behaviour when hiding a trace in a plot with many filling traces

### ISSUE THREAD

**Issue by ChristofferHS** [plotly/plotly.js#2380]
If you have around 10 traces or more in a plot that fill to a neighbour, clicking the legend to hide an individual trace can lead to strange behaviour from filled areas.

It appears that, generally, clicking the legend entry for a trace (the uppermost non-filling trace in the CodePen example below) that does not fill to a neighbour and whose hiding makes the plot rescale, will make a filled area get an incorrect shape. If you zoom in or out, the filled area gets its correct shape back. If you manually adjust the zoom level before you click, the issue does not seem to occur.

Another issue, possibly unrelated: if you click filling trace 7 or 2 in the CodePen example below, the filled area that should have expanded instead becomes empty. Manually setting the zoom level does not prevent this issue from occurring. However, here as well, the plot is corrected upon zooming; and a similar amount of traces seems necessary to trigger the bug. 

[CodePen](https://codepen.io/ChristofferHS/pen/vdpeVe)

**Comment by etpinard** [comment]
Thanks for the report.

**Comment by alexcjohnson** [comment]
Possibly a variant of (solved issue) #2271?

**Comment by etpinard** [comment]
Perhaps fixed via https://github.com/plotly/plotly.js/pull/3005

**Comment by ChristofferHS** [comment]
I seem unable to reproduce the issues on the CodePen, but #3005 isn't effective already, is it? Was it fixed by some other code?

At any rate, it looks like the issue is resolved.

**Comment by alexcjohnson** [comment]
Yep, seems to have been fixed between 1.40 and 1.41. I suspect either #2978 or #2960.
