### ISSUE TITLE
Error when data is updated during selection

### ISSUE THREAD

**Issue by swiperii** [plotly/plotly.js#2382]
When trace data is updated while dragging selection box, the plot temporarily becomes empty and console logs the following error:
`Error while plotting: undefined`

See [CodePen example](https://codepen.io/swiperii/pen/wyPEBW?editors=0010) (Click Add data, then use box select, drag and hold while a new data point is added)

Since I am using plotly-react.js, I guess this might be related to the new Plotly.react method (and it not taking into account `graphDiv._dragging` perhaps?).

**Comment by etpinard** [comment]
Thanks for the report.

Would it possible to make a pure plotly.js reproducible example to help us debug?

**Comment by tropys** [comment]
A [CodePen example](https://codepen.io/steph_curried/pen/ddKRoP) using Plotly.react that exhibits similar behaviour when box selecting.

**Comment by tropys** [comment]
Looks like the behavior for this has changed for the better in the 1.37.0 release

**Comment by tropys** [comment]
Now only the drag box disappears.

**Comment by Smurf81** [comment]
Hello,
I have the same problem, someone find a bypass ?

**Comment by etpinard** [comment]
Merged into https://github.com/plotly/plotly.js/issues/3305
