### ISSUE TITLE
change mapbox tile url to a local server

### ISSUE THREAD

**Issue by rahimramezanian** [plotly/plotly.js#2383]
Is there a feature to change the default mapbox tile server and use a local tile server?

**Comment by etpinard** [comment]
This should already be possible. cc @chriddyp

**Comment by etpinard** [comment]
I don't think we have a publicly available example for you, but we do have logic in our code base that handles the Atlas case [here](https://github.com/plotly/plotly.js/blob/ce5bc971770daaf3ed60d374f23a8af1bb61fe0b/src/plot_api/plot_config.js#L135-L140) and [here](https://github.com/plotly/plotly.js/blob/ce5bc971770daaf3ed60d374f23a8af1bb61fe0b/src/plots/mapbox/index.js#L139-L140) and one test case [here](https://github.com/plotly/plotly.js/blob/ce5bc971770daaf3ed60d374f23a8af1bb61fe0b/test/jasmine/tests/mapbox_test.js#L264-L290)

So I think something like:

```js
Plotly.newPlot('graph', [{
  type: 'scattermapbox',
  // ...
}], {}, {
  mapboxAccessToken: ''
})
```

should get you close.

**Comment by etpinard** [comment]
Closing due to lack of recent activity.

**Comment by Multihuntr** [comment]
Just a tiny little bit of extra information would be useful here: where does Plotly store the Mapbox hosting URL? 

I've been looking through a bunch of code, but I don't know the codebase, so I have no idea where to look.

**Comment by tcjennings** [comment]
What you do is set the "style" layout option for mapbox to the URL of the style.json you want to use. Also set the access token to an empty string as noted by @etpinard.

```
Plotly.newPlot('graph', [{
  type: 'scattermapbox',
  // ...
}], {
// ...
mapbox: {
  // ...
 style: 'https://path.to.my/style.json'
}, {
  mapboxAccessToken: ''
})
```
