### ISSUE TITLE
potential security vulnerability when bundling via an outdated version of static-eval@0.2.4 etc.

### ISSUE THREAD

**Issue by alhugot** [plotly/plotly.js#2386]
Hi,
First, this is a great lib!
Second this is perhaps not the place to report it, please feel free to close the issue, but:

There is a quite complex dependency chain on static-eval in the package.json which is affected by this security vulnerability:
https://nodesecurity.io/advisories/548   

plotly.js@1.34.0 › ndarray-homography@1.0.0 › ndarray-warp@1.0.1 › cwise@1.0.10 › static-module@1.5.0 › static-eval@0.2.4
plotly.js@1.34.0 › gl-plot3d@1.5.5 › gl-select-static@2.0.2 › cwise@1.0.10 › static-module@1.5.0 › static-eval@0.2.4
plotly.js@1.34.0 › gl-plot2d@1.3.1 › gl-select-static@2.0.2 › cwise@1.0.10 › static-module@1.5.0 › static-eval@0.2.4
plotly.js@1.34.0 › ndarray-fill@1.0.2 › cwise@1.0.10 › static-module@1.5.0 › static-eval@0.2.4
plotly.js@1.34.0 › gl-plot3d@1.5.5 › gl-spikes3d@1.0.6 › glslify@6.1.0 › static-eval@1.1.1
plotly.js@1.34.0 › gl-plot3d@1.5.5 › gl-axes3d@1.2.7 › glslify@6.1.0 › static-eval@1.1.1
plotly.js@1.34.0 › gl-plot3d@1.5.5 › glslify@6.1.0 › static-eval@1.1.1
plotly.js@1.34.0 › gl-plot2d@1.3.1 › glslify@6.1.0 › static-eval@1.1.1
plotly.js@1.34.0 › regl-line2d@2.1.5 › glslify@6.1.0 › static-eval@1.1.1
plotly.js@1.34.0 › regl-scatter2d@2.1.17 › glslify@6.1.0 › static-eval@1.1.1
plotly.js@1.34.0 › gl-scatter3d@1.0.11 › glslify@6.1.0 › static-eval@1.1.1
plotly.js@1.34.0 › gl-surface3d@1.3.4 › glslify@6.1.0 › static-eval@1.1.1
plotly.js@1.34.0 › gl-mesh3d@1.3.2 › glslify@6.1.0 › static-eval@1.1.1
plotly.js@1.34.0 › gl-select-box@1.0.2 › glslify@6.1.0 › static-eval@1.1.1
plotly.js@1.34.0 › gl-pointcloud2d@1.0.1 › glslify@6.1.0 › static-eval@1.1.1
plotly.js@1.34.0 › gl-error3d@1.0.7 › glslify@6.1.0 › static-eval@1.1.1
plotly.js@1.34.0 › gl-line3d@1.1.2 › glslify@6.1.0 › static-eval@1.1.1
plotly.js@1.34.0 › gl-heatmap2d@1.0.4 › glslify@6.1.0 › static-eval@1.1.1
plotly.js@1.34.0 › gl-contour2d@1.1.4 › glslify@6.1.0 › static-eval@1.1.1
plotly.js@1.34.0 › glslify@6.1.0 › static-eval@1.1.1

There is already an issue entered for glslify at https://github.com/glslify/glslify/issues/106
We would then need to move up in the dependency chain to the other components

Would also be good to have a security badge with:

snyk: https://github.com/snyk/snyk#badge
or
nsp: see https://github.com/dwyl/repo-badges

Thx
Alex

**Comment by etpinard** [comment]
Thanks for the headsup!

I think it's important to stress that this potential security vulnerability **only** affects users that bundle plotly.js source files as `glslify` and `cwise` are only used while building plotly.js. 

So, folks that use the `dist/` or CDN bundles are not affected by this security bug.

**Comment by etpinard** [comment]
After https://github.com/plotly/plotly.js/pull/2377/commits/48e1124e33c41e756f842a51055ba7bf5deef0fc, we have:

![image](https://user-images.githubusercontent.com/6675409/36501487-384567c8-1715-11e8-8c7b-e0d3995390e5.png)

So fixing https://github.com/scijs/cwise/issues/19 should do it.

**Comment by k-sai-kiranmayee** [comment]
Hello,
Sorry but even after this https://github.com/plotly/plotly.js/issues/2386#issuecomment-367446217, I'm still facing a few vulnerabilities like :(
![image](https://user-images.githubusercontent.com/36036544/58887931-27de2680-8704-11e9-9162-041dc90d4800.png)
![image](https://user-images.githubusercontent.com/36036544/58887986-447a5e80-8704-11e9-9ed7-44a72b143457.png)
