### ISSUE TITLE
Deleted axes not cleaned up properly

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#2392]
See eg:

```js
Plotly.newPlot(gd,
    [{y: [1,2,3]}, {y: [10, 30, 20], yaxis: 'y2'}],
    {yaxis2: {side: 'right', overlaying: 'y'}}
);
Plotly.deleteTraces(gd, [1]);
```
![screen shot 2018-02-21 at 3 00 43 pm](https://user-images.githubusercontent.com/2678795/36502455-06ffc8a4-1718-11e8-81ee-e66ba63e03b3.png)

reported in https://github.com/plotly/react-plotly.js/issues/45

**Comment by krunomunitic** [comment]
Also experiencing this 👍
