### ISSUE TITLE
Wrong histogram for a certain data point

### ISSUE THREAD

**Issue by Pradhyo** [plotly/plotly.js#2393]
Instead of two bars, one at 4 and another at 1, there is only one single bar at 4 when I try to plot a histogram for just [4, 1]

[Bug on Codepen](https://codepen.io/Pradhyo/pen/ZrRYqB)

It plots correctly for [5, 1] and some other values I tried.

**Comment by alexcjohnson** [comment]
Thanks for the report - this seems to fail for a somewhat random set of `[x, 1]`, including 8, 9, and 15-19 (and `[1, x]` fails the reverse way for the same numbers, only showing the 1).

**Comment by Pradhyo** [comment]
Thank you!
