### ISSUE TITLE
Plotly plots in jupyter notebook error :pandoc document conversion failed with error 1

### ISSUE THREAD

**Issue by 04pallav** [plotly/plotly.js#2395]
https://plot.ly/r/using-r-in-jupyter-notebooks/

x <- rnorm(1000)
y <- rchisq(1000, df = 1, ncp = 0)
group <- sample(LETTERS[1:5], size = 1000, replace = T)
size <- sample(1:5, size = 1000, replace = T)
ds <- data.frame(x, y, group, size)
p <- plot_ly(ds, x = x, y = y, mode = "markers", split = group, size = size) %>%
  layout(title = "Scatter Plot")
embed_notebook(p)

Error: pandoc document conversion failed with error 1
Traceback:

1. embed_notebook(p)
2. embed_notebook.plotly(p)
3. htmlwidgets::saveWidget(p, tmp)
4. pandoc_self_contained_html(file, file)
5. pandoc_convert(input = input, from = "markdown", output = output, 
 .     options = c("--self-contained", "--template", template))
6. stop("pandoc document conversion failed with error ", result, 
 .     call. = FALSE)

**Comment by etpinard** [comment]
Well, this has nothing to do with this repo. Closing.

Probably best for https://community.plot.ly/c/api/r
