### ISSUE TITLE
Contour plot uncaught ax.dtick error: NaN

### ISSUE THREAD

**Issue by claudericka** [plotly/plotly.js#2398]
When I create a contour plot with my configuration with small data, the contour plot works fine however when I try it with bigger data set, it throw me an "uncaught ax.dtick error: NaN". Here are some example.
[Contour plot with Nan error](https://codepen.io/claudericka/pen/WMKXxO)
[Contour plot without error](https://codepen.io/claudericka/pen/GQBOWZ)

Thanks.

**Comment by etpinard** [comment]
Another installment of our contour bug series.

Thanks very much for the report!

**Comment by alexcjohnson** [comment]
Good catch - the issue is with `ncontours: 1`, should be an easy fix. In the meantime you may be interested in a new feature (to regular contours anyway): constraint-type contours: https://github.com/plotly/plotly.js/pull/2270
