### ISSUE TITLE
NPM modules for dists

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#2400]
Idea: we could have an NPM module called e.g. `plotly.js-dist` which contained only precompiled bundles. Or we could have an NPM module per bundle. These modules would have zero dependencies so they would never throw warnings on installation and they would download really fast and require no special Webpack loaders or Browserify transforms so they would work smoothly with create-react-app or Next.js or whatever comes next :)

**Comment by etpinard** [comment]
Great idea. 

I'll even suggest making one `npm` registry per partial bundle that is `plotly.js-basic`, `plotly.js-cartesian`, `plotly.js-geo`, `plotly.js-gl3d`, `plotly.js-gl2d`, `plotly.js-mapbox`, `plotly.js-finance` that would only include one `.js` and one `.min.js` file.

**Comment by etpinard** [comment]
Related: https://github.com/plotly/plotly.js/issues/768
