### ISSUE TITLE
Embedding interactive Plotly.js plots in Sphinx disables LaTeX rendering via MathJax

### ISSUE THREAD

**Issue by kordian2k** [plotly/plotly.js#2403]
First of all, thanks for the great set of Plotly libraries!

I would like to embed plots into a [Sphinx](http://www.sphinx-doc.org) documentation which makes use of LaTeX via its *sphinx.ext.mathjax* extension. I do not want to embed the plots as images like jpg in order to keep them interactive.

My strategy to achieve that is to
+ put plotly-latest.min.js into Sphinx' `_static` folder,
+ embed "ready to use" HTML div elements created in Python via `plotly.offline.plot` with the `include_plotlyjs` flag set to *False* using the `.. raw:: html` directive,
+ Add a `script` reference to Plotly.js into each HTML file's head element using the following code snipped in Sphinx' `_templates` folder:
```
{% extends "!layout.html" %}

{%- block extrahead %}
 <script type="text/javascript" src="_static/plotly-latest.min.js"></script>
{% endblock %}
```

With that strategy the generated html file include the following `script` tags:
+ `<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7./MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>`,
+ `<script type="text/javascript" src="_static/plotly-latest.min.js"></script>`.

While Plotly's plots are shown as expected, LaTeX embeddings using the `:math:` directive do not render anymore.

+ The reason seems to be Sphinx' usage of MathJax `TeX-AMS-MML_HTMLorMML` profile.
+ The problem also seems to be related to an issue with Jupyter notebooks #2300.

Is there any way to use the same MathJax profile in Plotly.js as in Sphinx?

**Comment by kordian2k** [comment]
Until this issue is resolved a work-around is to embed the div element into an empty HTML site
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script type="text/javascript" src="plotly-latest.min.js"></script>
    <title>Plot example</title>
</head>
<body>
<div generated by Plotly ...
</body>
</html>
```
and to include this file as an `iframe` into your documentation:
```
.. raw:: html

    <iframe src="../_static/site.html" height="500px" width="100%"></iframe>
```
This way both MathJax profiles do not interfere with each other.

**Comment by jonmmease** [comment]
This has been addressed in plotly.js 1.42 by #2994. You'll need to set `window.PlotlyConfig = {MathJaxConfig: 'local'}` before loading plotly.js.  Also, the MathJax `config` doesn't need to be set to `TeX-AMS-MML_SVG` anymore (plotly.js will internally set and restore the configuration each time it uses MathJax). It just needs to be set to some configuration that includes `TeX`, so you can use whatever config makes Sphinx happy.

See https://github.com/plotly/plotly.js/blob/master/dist/README.md#to-support-mathjax for more information. Thanks!

**Comment by kordian2k** [comment]
Works like a charm. Thanks!
