### ISSUE TITLE
pdf export paper_bgcolor turns black when using image magick to convert to jpg

### ISSUE THREAD

**Issue by cldougl** [plotly/plotly.js#2408]
Now after exporting a pdf image and using image magick to convert to a jpg the paper_bgcolor becomes black:

![image](https://user-images.githubusercontent.com/2789078/36740765-6b0f8cf6-1bb1-11e8-8a19-dc885ec225a5.png)

**Comment by rafael-andrade** [comment]
I was having the same issue using another library. I was converting it to JPEG image, the default color is black. So I changed it to PNG before export to PDF.

**Comment by etpinard** [comment]
Moved to https://github.com/plotly/orca/issues/81
