### ISSUE TITLE
scattergl doesn't work with 'showspikes'; whereas scatter works as expected!

### ISSUE THREAD

**Issue by shahyash1993** [plotly/plotly.js#2409]
Please have a look at the codepen example attached below.  It is quite easily understandable with example. Thanks.

https://codepen.io/ypshah-13/pen/MQzMJe

**Comment by alexcjohnson** [comment]
fixed in #2379 - will be in the next published version.

**Comment by shahyash1993** [comment]
I am sorry! I somehow missed that.
