### ISSUE TITLE
Display camera debug info

### ISSUE THREAD

**Issue by KonradAdamczyk** [plotly/plotly.js#2412]
Sometime its hard to select right camera configuration in source code of plot.
But its easy to select right camera view in browser. 
Please add option(maybe near camera button) to display debug information about current settings of camera view so that developer can copy these values to source code and make this camera view as default.

![obraz](https://user-images.githubusercontent.com/16255826/36747093-5716020a-1bf4-11e8-8b07-4922f9373981.png)

**Comment by etpinard** [comment]
You can add your own: https://codepen.io/etpinard/pen/YedPjy?editors=0011

**Comment by etpinard** [comment]
We aren't planning on adding official debugging modebar buttons to the library, so I'll close this ticket.

@KonradAdamczyk if you have any other question regarding custom modebar buttons, please use https://community.plot.ly/c/plotly-js

Thank you.

**Comment by KonradAdamczyk** [comment]
@etpinard can You add clear info how to add the [button line that ](https://codepen.io/etpinard/pen/YedPjy?editors=0011) in python code to this page:
[https://plot.ly/python/3d-camera-controls/](https://plot.ly/python/3d-camera-controls/)
so that developer can choose camera config in web browser then view that config and copy/paste them to his source code ?

**Comment by etpinard** [comment]
Probably best to ask the python maintainers: https://github.com/plotly/plotly.py/issues/new
