### ISSUE TITLE
Contour plot "undefined" label when z >= 10 million

### ISSUE THREAD

**Issue by ollierob** [plotly/plotly.js#2420]
When contour z-points are greater than 10 million then the tooltip value is suffixed with "undefined". 

The suffix should be B or a multiple of 10M or it should render with an exponent. It should also be implemented for even larger values (1e8+).
```
var data = [ {
    z: [
        [1e6, 5e6, 1e7, 1.5e7],
        [1.2e6, 5.6e6, 1.1e7, 1.6e7]
    ], type: 'contour'
}];
Plotly.newPlot('myDiv', data);
```
![undefined](https://user-images.githubusercontent.com/6401341/36786207-71daeb4e-1c7d-11e8-8eaf-9146104bec1f.png)

**Comment by alexcjohnson** [comment]
Thanks for the report!
