### ISSUE TITLE
Scatterpolar bug: not all theta labels showing

### ISSUE THREAD

**Issue by yanndebelgique** [plotly/plotly.js#2421]
https://codepen.io/yannbel/pen/rJoEKy
Current behavior:
Theta labels 'H','I','J' not showing. only labels 'A','B','C', 'D', 'E','F','G' showing
Expected behavior:
Example: All the theta labels should be visible on the graph i.e. ['A','B','C', 'D', 'E','F','G','H','I','J']

**Comment by etpinard** [comment]
Thanks for the report.

**Comment by yanndebelgique** [comment]
Thanks for the great work with Plotly.js! awesome library
