### ISSUE TITLE
Repeatedly calling `newPlot` with `scatter3d` causes graphs to disappear

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.js#2423]
Originally reported in https://community.plot.ly/t/webgl-context-lost-after-updating-10-times/8581/4. 
I created a reproducable example in https://codepen.io/chriddyp/pen/xYmbVQ?editors=0010. After a few plots, if I navigate away from the page and then return, the original plot is no longer visible. For the original reporter, it seems like the plot disappeared while they were viewing the app (they didn't need to navigate away).

![dash-webgl-contexts](https://user-images.githubusercontent.com/1280389/36801472-3b2036ec-1c80-11e8-87be-85a8c4dcc972.gif)

**Comment by chriddyp** [comment]
cc @dfcreative

**Comment by etpinard** [comment]
Not much we can do here I think. 

1 second is probably not enough time for browsers to garbage collect a WebGL context, so yeah inevitably the context limit will be reached.

**Comment by etpinard** [comment]
@dfcreative please don't spend time on this until April.

**Comment by chriddyp** [comment]
> Not much we can do here I think.

Is there anything _I_ can do here? 1 second is just to demonstrate the problem. In Dash, graphs update frequently and if they end up disappearing irregularly then we can't reliably use any GL plots in Dash.

**Comment by chriddyp** [comment]
i.e. are there any workarounds to this issue like calling `plot` instead of `newPlot` or something?

**Comment by etpinard** [comment]
`Plotly.react` should do the right thing here.

**Comment by chriddyp** [comment]
Added `Plotly.react` in https://github.com/plotly/dash-core-components/pull/170, so hopefully we're good here 👍

**Comment by etpinard** [comment]
Closing as we won't attempt to solve this issue with `newPlot`. Switching to `Plotly.react` should fix the problem in all cases.
