### ISSUE TITLE
Autoscale yaxis when xaxis range specified

### ISSUE THREAD

**Issue by bluprince13** [plotly/plotly.js#2432]
Using the example code below, a plot is generated (which you can see [here](https://plot.ly/~bluprince13/5/)). I have specified the xaxis range, but the yaxis doesn't autoscale in response. Is there any way to force the yaxis to autoscale?

```
import plotly.offline as py
import plotly.graph_objs as go

trace1 = go.Scatter(
    x=[0, 1, 2, 3, 4, 5, 6, 7, 8],
    y=[8, 7, 6, 5, 4, 3, 2, 1, 0]
)
trace2 = go.Scatter(
    x=[0, 1, 2, 3, 4, 5, 6, 7, 8],
    y=[0, 1, 2, 3, 4, 5, 6, 7, 8]
)
data = [trace1, trace2]
layout = go.Layout(
    xaxis=dict(
        range=[2, 5]
    ),

)
fig = go.Figure(data=data, layout=layout)
py.plot(fig, filename='axes-range-manual')
```

**Comment by alexcjohnson** [comment]
I guess what you mean is can we autoscale the y axis to the data that's *visible* given the x axis range? That's a feature we've been discussing here https://github.com/plotly/plotly.js/issues/1876#issuecomment-314913229

**Comment by etpinard** [comment]
Merging with https://github.com/plotly/plotly.js/issues/1876
