### ISSUE TITLE
Scattergl Selection Removes Points

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.js#2433]
Reported by a Dash community member: https://community.plot.ly/t/webgl-context-lost-after-updating-10-times/8581/8?u=chriddyp

In upgrading from plotly.js 1.33.1 to 1.34.0, some points are removed when selecting regions in `scattergl` traces. The selected event still fires with the correct number of points.

Here is the GIF from the forum:
![](https://discourse-cdn-sjc2.com/standard16/uploads/plot/original/2X/9/9b9c16fe87a8a21396392ef6268ef5917a8c769b.gif)

**Comment by chriddyp** [comment]
This upgrade also corresponded with a change from using `Plotly.newPlot` to using `Plotly.react`. I'm not sure whether the change is due to changing the method or due to the upgrade.

**Comment by etpinard** [comment]
Can we get access to the underlying x/y data?

**Comment by etpinard** [comment]
This might be related to https://github.com/plotly/plotly.js/issues/2298 (unfortunately)

**Comment by chriddyp** [comment]
Duplicate of https://github.com/plotly/plotly.js/issues/2298
