### ISSUE TITLE
Mirrored axes have a huge bounding box

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#2434]
setting `mirror: 'allticks'` on an axis results in a giant bounding box for the axis, which causes problems with the new `automargin` flag on axes, and the positioning of the rangeslider. You can see this problem in action by setting `automargin` on any of the axes here (once we release 1.35.0) https://codepen.io/nicolaskruchten/pen/WMWvVz

This is due to the fact that the mirrored axis is drawn with the same path as the 'main' axis where the ticklabels are. It would make some sense to draw that secondary axis in a different element, so that the bounding box of the main axis is independent of the `mirror` attribute.

**Comment by alexcjohnson** [comment]
Really what we need to do is get rid of the `getBoundingClientRect` calls there altogether. This causes all sorts of problems, see #1988
