### ISSUE TITLE
can plotly draws nested pie charts?

### ISSUE THREAD

**Issue by lx1054331851** [plotly/plotly.js#2435]
can plotly draws nested pie charts like this:
![image](https://user-images.githubusercontent.com/12423206/36945410-be1e1fd0-1fe8-11e8-937c-090605464189.png)

**Comment by etpinard** [comment]
Here's one way: https://codepen.io/etpinard/pen/EQzzVb?editors=0010

Please ask questions of the likes on https://community.plot.ly/c/plotly-js in the future. Thank you!
