### ISSUE TITLE
gl2d zoom turns background black

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#2436]
Plots using stackgl (heatmapgl, pointcloud...) get a black background when you start to zoom, and it doesn't go away after zoom. Prior to v1.32.0 it was a grey background and it *did* go away after zoom. Ideally it would turn grey only within the subplot area, but since these trace types are on the back burner I'd be happy with a return to the pre-1.32 behavior.

https://codepen.io/alexcjohnson/pen/KQLKWx

![screen shot 2018-03-04 at 8 42 00 am](https://user-images.githubusercontent.com/2678795/36946317-2e034204-1f89-11e8-9c81-302f0951a314.png)

Presumably related to #2159 or #2238?

cc @dfcreative

**Comment by jmmease** [comment]
Two more observations/bugs on 1.37.1 (in addition to the black background noted above).  I can move these to one or more new issues if you think they are sufficiently different.

## Pen
https://codepen.io/anon/pen/ZoVYay

## Pan tool performs zoom action
 - Refresh Pen
 - Click on the Pan tool
 - Drag on the plot and the zoom action is executed

## Panning smears axis ticks
 - Refresh Pen
 - Click on the Pan tool
 - Drag on the plot  (this performs a zoom as above)
 - Click on autoscale button
 - Now drag again 
 - This time pan action happens, but the axis ticks get smeared.

![screen shot 2018-05-18 at 8 34 56 am](https://user-images.githubusercontent.com/15064365/40234914-7fb00a9c-5a76-11e8-8914-bd9fb79b6afc.png)

cc @dy @etpinard

**Comment by etpinard** [comment]
thanks for the report @jmmease

**Comment by ShaneHudson** [comment]
I have been having the exact same issues (especially the black background and pan zooming) with heatmapgl. Is there any known fix/workaround?

Also seeing weird data issues (just straight lines and no actual data) when I pass through data for all axes, may be a bug in my code though as I need to test further.
