### ISSUE TITLE
Update y-axis range when x-axis rangeslider is used

### ISSUE THREAD

**Issue by IanWorthington** [plotly/plotly.js#2439]
There's some JS code over here:

https://github.com/ropensci/plotly/issues/912

to autoupdate the yaxis as the xaxis changes.

There's also some discussion around this maybe not being a better default than the current not scaling at all, but also a request to open the issue here, which I can't see was ever done, so I am.

I'm sure it's not a perfect solution to all cases but can it be added in as an option maybe?

**Comment by etpinard** [comment]
I'm not 100% sure what  you're requesting. 

You might want to look at current PR https://github.com/plotly/plotly.js/pull/2364 which is adding a few rangeslider+yaxis configuration options.

**Comment by IanWorthington** [comment]
Thanks for the link.  The code in ropensci/plotly#912 adds automatic rescaling of the y-axis as the rangeslider is adjusted, which, iiuc, I don't think is in the PR?

**Comment by alexcjohnson** [comment]
@IanWorthington Is your intent that on adjusting the range slider, the y axis autoranges to just the data that's visible in the new x range? That's a feature we've had on the list for quite some time... https://github.com/plotly/plotly.js/issues/1876#issuecomment-314913229

**Comment by IanWorthington** [comment]
@alexcjohnson Yes, that looks like it might be it.  Do I take it node of that is implemented yet?

**Comment by alexcjohnson** [comment]
Correct, that issue is to collect the behavior we want to add, and make sure that it's all mutually consistent and compatible, but it's not yet implemented.

Closing this issue, lets continue the discussion over there.
