### ISSUE TITLE
rangeslider with multiple yaxis (after v1.32.0)

### ISSUE THREAD

**Issue by PavelGolodoniuc** [plotly/plotly.js#2443]
We have a plot with multiple y axes and a rangeslider. This produces something like:

![image](https://user-images.githubusercontent.com/9332295/37017969-87ce4f3e-214d-11e8-8790-4977020ac7b4.png)

This worked perfectly up until v1.31.1. The next v1.32.0 breaks it and renders rangeslider over one of the plots:

![image](https://user-images.githubusercontent.com/9332295/37018201-73ff5d9e-214e-11e8-8ac0-e50c1cc62718.png)

Reproducible example is here: https://codepen.io/anon/pen/qxzVpW

In the HTML view replace https://cdn.plot.ly/plotly-1.31.0.min.js script with the 1.32.0 or the latest from the CDN to reproduce the issue.

May I suggest that xaxis.rangeslider layout config option has something like "domain: [ number, number ]" rather than "thickness" option to specify where exactly I want to place the slider?

**Comment by alexcjohnson** [comment]
Thanks @PavelGolodoniuc - bug confirmed.

`domain: [..., ...]` is a good idea. We should probably make a separate issue to discuss that though, and keep this issue about the bug.

**Comment by etpinard** [comment]
Thanks for the report @PavelGolodoniuc
