### ISSUE TITLE
Request to support filename config when downloading a plot as a png

### ISSUE THREAD

**Issue by danday74** [plotly/plotly.js#2444]
The plotly modebar provides a "download plot as a png" button

However, the image downloaded is always called "newplot.png"

Please provide a config point which will allow this default to be overriden - thanks

**Comment by alexcjohnson** [comment]
It's completely undocumented, but you can set `graphDiv.fn` (for filename - leave off the .png extension) and that will get used for the download. You can use that, but we should be able to do better. Perhaps `layout.filename` or something?

**Comment by etpinard** [comment]
`layout.filename` would help users affected by https://github.com/plotly/plotly.js/issues/1227

**Comment by alexcjohnson** [comment]
> `layout.filename` would help users affected by https://github.com/plotly/plotly.js/issues/1227

I doubt it - if we can't set the filename to `newplot.png` we won't be able to set it to the user's choice of name either.

**Comment by danday74** [comment]
just to confirm that using graphDiv.fn worked - many thanks

**Comment by danday74** [comment]
want to close this off?

**Comment by etpinard** [comment]
I would leave this open. That `graphDiv.fn = ""` hack is not pretty. We could do better e.g.:

```
Plotly.newPlot(gd, [], {filename: ""})

// or
Plotly.newPlot(gd, [], {}, {downloadImageFilename: ""})
```

**Comment by alexcjohnson** [comment]
👍 for a config param eg `Plotly.newPlot(gd, [], {}, {downloadImageFilename: ""})`

**Comment by Braintelligence** [comment]
Hello everyone,
so the filename config referenced for Plotly.downloadImage is wrong? It doesn't seem to really work as well...

https://plot.ly/javascript/plotlyjs-function-reference/#plotlydownloadimage

**Comment by etpinard** [comment]
This one was done in https://github.com/plotly/plotly.js/pull/2607 - released in `v1.38.0`

**Comment by fazola** [comment]
Hi, does anyone know how I can access this feature in Python?

**Comment by alexcjohnson** [comment]
@fazola see https://plotly.com/python/configuration-options/#customizing-download-plot-options
