### ISSUE TITLE
Heatmap legend can't be disabled

### ISSUE THREAD

**Issue by kevinwuhoo** [plotly/plotly.js#2448]
It seems like `showlegend: false` for heatmaps is broken. I found this codepen in the docs that should have the legend hidden, but it's still being rendered: https://codepen.io/plotly/pen/WQGgbe. That codepen is linked from this page: https://plot.ly/javascript/configuration-options/#modify-the-edit-chart-link-text.

I couldn't get it to work by placing `showlegend: false` in either the trace or the layout. I also cherry picked a few previous versions to see if this worked at some point, but couldn't find one.

Thanks for all your hard work!

**Comment by alexcjohnson** [comment]
That's because we don't call it a legend, we call it a colorscale, with corresponding `showscale` attribute.

**Comment by alexcjohnson** [comment]
(I don't know why that example has `showlegend` in it, we'll take that out... but just to be clear, `showscale` is a trace attribute, not a layout attribute)

**Comment by wincowgerDEV** [comment]
The documentation still has show legend here: https://plotly.com/r/reference/heatmap/#heatmap-showlegend

**Comment by alexcjohnson** [comment]
You _can_ use a legend with a heatmap - but by default the colorscale is shown and the legend is not. https://codepen.io/alexcjohnson/pen/qBKxvpM

**Comment by wincowgerDEV** [comment]
Thanks for the response! Ok that makes sense.
