### ISSUE TITLE
scattergl layering and errorbar issues

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#2450]
A couple of remaining scatter/scattergl differences, see https://codepen.io/alexcjohnson/pen/YemVOd
![screen shot 2018-03-06 at 6 53 21 pm](https://user-images.githubusercontent.com/2678795/37065664-b3fad89e-216f-11e8-861a-3028adc470a6.png)
- [ ] fill tozero breaks in some weird ways - here it's filling to the wrong final y value, but if you slide `trace1.y[0]` up and down a little bit you see all sorts of odd behavior.
- [x] fills are behind everything else, they should be on top of some of the lines/points/errorbars (note, I didn't include fill tonext in this example, but it makes fill layering even more complicated, see https://github.com/plotly/plotly.js/pull/2442#discussion_r172405040) - **Fixed in** -> https://github.com/plotly/plotly.js/pull/3087
- [x] x errorbars aren't supported? **done ->** #2620

Initially I thought errorbar colors were also a scattergl issue, but scatter also doesn't get the colors I would have expected. That may have to be a v2 change at this point...

cc @dfcreative @etpinard

**Comment by tgoldina** [comment]
One more issue with error bars in scattergl, "markers" mode: error bars disappear on any relayout action: try switching to box select, zooming or panning in https://codepen.io/anon/pen/WJxKpP

**Comment by etpinard** [comment]
thanks for the report @tgoldina

**Comment by etpinard** [comment]
now in https://github.com/plotly/plotly.js/issues/4017
