### ISSUE TITLE
Polar plots broken in v1.35.0 (visible on docs site)

### ISSUE THREAD

**Issue by jacobq** [plotly/plotly.js#2456]
If you go to the [Polar Charts in plotly.js](https://plot.ly/javascript/polar-chart/) section of the documentation (tested in Chrome 64) you will notice that the grid lines are plotted and the radial axis ticks & labels are present, but the angular axis labels and the traces are not. For example, [this first codepen](https://codepen.io/plotly/pen/LQepNO) does not work.

Instead, an error message like the one below appears in the console. This is either a problem with `plotly.js` or a problem with the docs, but I can't imagine this not being a problem.

```
Uncaught TypeError: node.getAttribute is not a function
    at Array.d3_selectionPrototype.classed (VM456 plotly-latest.js:754)
    at ax._transfn (VM456 plotly-latest.js:173293)
    at SVGTextElement.<anonymous> (VM456 plotly-latest.js:27849)
    at VM456 plotly-latest.js:1028
    at d3_selection_each (VM456 plotly-latest.js:1034)
    at Array.d3_selectionPrototype.each (VM456 plotly-latest.js:1027)
    at positionLabels (VM456 plotly-latest.js:27845)
    at SVGTextElement.<anonymous> (VM456 plotly-latest.js:27808)
    at VM456 plotly-latest.js:1028
    at d3_selection_each (VM456 plotly-latest.js:1034)
```

Changing the script source to [v1.34.0](https://cdnjs.cloudflare.com/ajax/libs/plotly.js/1.34.0/plotly.js) seems to fix the problem, so this could be a regression introduced in v1.35.0.

**Comment by etpinard** [comment]
Ouch. That's bad. Not sure how that happened. Thanks for the report!

**Comment by jacobq** [comment]
That was quick :)

**Comment by etpinard** [comment]
@jacobq thank you for the report! We'll try a few more things this afternoon. But we'll get our CDNs updated no later than tonight

**Comment by etpinard** [comment]
The examples are back with [`1.35.1`](https://github.com/plotly/plotly.js/releases/tag/v1.35.1)

Thanks again @jacobq !
