### ISSUE TITLE
scattergl throws console errors on safari

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#2457]
Looks like this issue was introduced in the `scattergl` rewrite (i.e. v1.32.0 doesn't throw any errors) 
https://codepen.io/cpsievert/pen/WzNvVN

![screen shot 2018-03-08 at 9 31 52 am](https://user-images.githubusercontent.com/1365941/37159555-d12fe0cc-22b3-11e8-91cb-0e2410ce2d1d.png)

Possibly related to https://github.com/ropensci/plotly/issues/1214

**Comment by alexcjohnson** [comment]
Confirmed. But it doesn't seem like this actually blocks any functionality, just litters the console with errors, is that right?

**Comment by cpsievert** [comment]
Yea, I just suspect that it might be related to https://github.com/ropensci/plotly/issues/1214, which is a much bigger problem.

**Comment by etpinard** [comment]
Maybe related to https://github.com/plotly/plotly.js/issues/2430

**Comment by cpsievert** [comment]
Interesting, this same codepen through a different error in RStudio on Windows (from https://github.com/ropensci/plotly/issues/1214#issuecomment-371550911)

![image](https://user-images.githubusercontent.com/952340/37164348-00444632-22c8-11e8-9b34-1b3d5fbca08d.png)

**Comment by cpsievert** [comment]
Huh, it looks like my comment https://github.com/plotly/plotly.js/issues/2457#issuecomment-371549750 is wrong, this *does* prevent markers from rendering on Safari and seems very much related to the errors reported in #2543

<img width="632" alt="screen shot 2018-04-17 at 2 28 35 pm" src="https://user-images.githubusercontent.com/1365941/38891997-a59f0b92-424b-11e8-8297-786cd64ef080.png">
<img width="757" alt="screen shot 2018-04-17 at 2 28 03 pm" src="https://user-images.githubusercontent.com/1365941/38892003-a941710e-424b-11e8-8402-e2bab97fb24a.png">
