### ISSUE TITLE
Regression bug: LASSOing has become significantly slower between 1.31 to 1.32

### ISSUE THREAD

**Issue by daattali** [plotly/plotly.js#2459]
Codepen with sample code: https://codepen.io/anon/pen/NYWNde

Having 10,000 points in a scatterplot, if I wanted to LASSO select some points with plotly1.31 it was fairly smooth. If I try the same thing with plotly1.32+ it becomes agonizingly slow.

![yearlyadepthornshark-max-14mb](https://user-images.githubusercontent.com/952340/37163463-d8158df8-22c5-11e8-9d84-6c98b0206f05.gif)

On Windows 7 Pro, using Chrome v64

Originally reported to @cpsievert at https://github.com/ropensci/plotly/issues/1216

**Comment by etpinard** [comment]
Thanks for the report! To be more precise, the issue is with SVG `scatter` (i.e. `scattergl` is fine).

**Comment by etpinard** [comment]
Arrg. I suspect https://github.com/plotly/plotly.js/pull/2135 is the culprit here. We'll have to speed up `_module.style`. Thanks again for the report!

**Comment by etpinard** [comment]
One more reason to start stashing points selections (cc https://github.com/plotly/plotly.js/issues/2548)

**Comment by daattali** [comment]
As the issue opener, I just want to confirm this is indeed fixed :)
