### ISSUE TITLE
For swapping between scatter and scatter3d, scaleanchor stays in layout and is no longer ignored by scatter3d plot, causing error

### ISSUE THREAD

**Issue by enddev** [plotly/plotly.js#2462]
I have a use case where users need to look at a plot in 2D sometimes, but change to a 3D view at others.  This is done via a simple toggle.  Under version 1.31.2, this worked fine, any parameters the chart did not care about were ignored, but we also only conditionally added the `xaxis: { scaleanchor: 'y' }` when the user chose to look at a 2D plot of the data.  Now, trying in both 1.34.0 and 1.35.0, this causes the 3D plot to error and not render.  

We are using react-plotlyjs to construct our plots, but that is at version 1.1.1, which still creates a new chart everytime the inputs change, so it doesn't seem to be a matter of that hanging onto something, but if it is, I'll move this issue over there instead.  Just updating plotly.js to the latest versions seems to make this behavior show up.  

This is the error that I get when I try to swap:
![image](https://user-images.githubusercontent.com/10747555/37173903-29d3c8d8-22d2-11e8-8aca-fc5d0d99d377.png)

To show the behavior I was seeing before, and expected I've put together [this codepen](https://codepen.io/enddev/pen/yKLgbg).

Now, by only changing the version of plotly.js, [this codepen](https://codepen.io/enddev/pen/wmvJbm) shows the error behavior.  Additionally, by changing the starting value of dim3d on line 16 to true, the 3D plot renders fine the first time, and switching to 2D gives a different error (see below), but switching back, the 3D plot gives the same error as above again, and the toggle gets off somehow, rendering the 2D when it's supposed to render 3D.
![image](https://user-images.githubusercontent.com/10747555/37174164-fff2a4ac-22d2-11e8-95ff-8327996b37d8.png)

Just in case it matters, and to provide more information, our project is built with webpack 3.10.0, with typescript 2.0.3, but since the codepen has the same behavior, it probably isn't related to current environment.  I've also attempted to update to the latest react-plotly (1.7.0) hoping it might change something, but I can't see any difference in behavior.

**Comment by etpinard** [comment]
Thanks for the report.
