### ISSUE TITLE
Parallel coordinates chart handle normalized data

### ISSUE THREAD

**Issue by weilixu** [plotly/plotly.js#2468]
Hi, I am working with a group of normalized data, each data range is between 0 to 1. I want to use the parallel coordinate chart to do data visualization, however, the chart did not produce the correct tick value for the y-axes.

Below is the code I am testing on the https://codepen.io/plotly/pen/ZepaxM, simply change the first dictionary in the dimension can reproduce the error.

```javascript
var trace = {
  type: 'parcoords',
  line: {
    color: 'blue'
  },
	
  dimensions: [{
    range: [0.1, 0.5],
    constraintrange: [0.1, 0.2],
    label: 'A',
    values: [0.1,0.4]
  }, {    
    range: [1,5],
    label: 'B',
    values: [3,1.5],
    tickvals: [1.5,3,4.5]
  }, {
    range: [1, 5],
    label: 'C',
    values: [2,4],
    tickvals: [1,2,4,5],
    ticktext: ['text 1','text 2','text 4','text 5']
  }, {
    range: [1, 5],
    label: 'D',
    values: [4,2]
  }]
};

var data = [trace]

Plotly.plot('graphDiv', data);
```

<img width="488" alt="screen shot 2018-03-09 at 9 07 55 pm" src="https://user-images.githubusercontent.com/8561549/37237160-f9376434-23dd-11e8-9706-f96ca8e452a3.png">
With this code, notice the y-axis for the first dimension has changed to 100s + 'm' - which easily to be misunderstood as the unit meter.

Any suggestions on solving this issue will be appreciated

**Comment by alexcjohnson** [comment]
You can use `tickformat`, as in https://codepen.io/alexcjohnson/pen/GxJyrV. Its default value `3s` is good for a lot of cases but you're right, ideally we'd use the same default as regular cartesian axes which does not behave the same as pure SI notation.

**Comment by weilixu** [comment]
Awesome, this works! Thank you for the suggestions.

**Comment by alexcjohnson** [comment]
Probably can't actually fix this until v2 -> https://github.com/plotly/plotly.js/issues/420#issuecomment-372338952
