### ISSUE TITLE
Pie chart doesnt restyle marker.colors

### ISSUE THREAD

**Issue by andrey-zakharov** [plotly/plotly.js#247]
Simple test case:

```
var trace1 = {
  labels: [1, 2, 3, 4],
  values: [10, 15, 13, 17],
  type: 'pie',
};

var update = {
	'marker.colors': ['#200', '#400', '#600', '#800']
}

Plotly.newPlot(graphDiv, [trace1], {title: "test pie"});
Plotly.restyle(graphDiv, update);
```

http://codepen.io/anon/pen/RrEPgy?editors=0010
doesn't update colors.

seems like marker.colors not included somewhere to replot flags.

**Comment by andrey-zakharov** [comment]
Also it doesnt work for "pull" attr.

**Comment by etpinard** [comment]
You have to wrap all array attributes into another array in the `restyle` call.

http://codepen.io/etpinard/pen/YwdwjN

**Comment by etpinard** [comment]
The outer array in `restyle` maps to different traces.

**Comment by etpinard** [comment]
This is a recurring issue for a lot of users. We're thinking about throwing errors when the `restyle` updates aren't formatted properly. You can following our discussion here: https://github.com/plotly/plotly.js/issues/167

**Comment by ArminTaheri** [comment]
I'd like to note that the initial `marker.colors` for colorscale is an empty array. This causes a problem in the workspace2 frontend where empty colorscales are being shifted into a components state. @chriddyp  and I think what should happen is the actual colours that appear on the plot should be reflected in `marker.colors`

http://jsbin.com/gasiruyali/edit?html,js,console,output
