### ISSUE TITLE
transforms + Plotly.react bug

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#2470]
A user encountered a problem with `Plotly.react` and transforms, changing pie aggregation & labels simultaneously. The following examples start with A/B/C and switch to X/Y/Z on clicking the button.

Works fine using `Plotly.restyle`:
https://codepen.io/alexcjohnson/pen/geaRej?editors=0010
![screen shot 2018-03-12 at 5 23 07 pm](https://user-images.githubusercontent.com/2678795/37310417-3cdb6b84-261a-11e8-8d89-ec28b6a78585.png)

But not with `Plotly.react`:
https://codepen.io/alexcjohnson/pen/xWwrXR?editors=0010
![screen shot 2018-03-12 at 5 24 20 pm](https://user-images.githubusercontent.com/2678795/37310438-45a6fecc-261a-11e8-8ab1-42d88105d021.png)

However `Plotly.react` works fine using the same aggregation that's built into pies since #2117:
https://codepen.io/alexcjohnson/pen/BroZNx?editors=0010

reported by @snazzypants in https://github.com/plotly/react-plotly.js/issues/62

**Comment by etpinard** [comment]
Possibly related: https://community.plot.ly/t/plotly-js-cannot-read-property-length-of-undefined-when-clearing-filter-transforms/8890/4
