### ISSUE TITLE
While using IE-Edge, Plotly displays nothing when 'scattergl' is used; whereas it displays perfectly when 'scatter' is used.

### ISSUE THREAD

**Issue by shahyash1993** [plotly/plotly.js#2475]
plotly.js should work in IE9+ as it says here ->
https://github.com/plotly/plotly.js/tree/master/dist#using-distributed-files

Please have a look at these images.

1>With 'scattergl'
![ie_scattergl_line_notworking_1](https://user-images.githubusercontent.com/16498941/37427013-45676cbe-2785-11e8-8d4a-9ddb270eb61d.png)

2>With 'scatter'
![ie_scattergl_line_notworking_2](https://user-images.githubusercontent.com/16498941/37427014-45834088-2785-11e8-8c1f-ec9bf67b3b4e.png)

IE Version: 11.0.9600.18920

**Comment by etpinard** [comment]
Thanks for the report. What version(s) of IE-Edge are you using?

**Comment by shahyash1993** [comment]
IE Version: 11.0.9600.18920

**Comment by etpinard** [comment]
@dfcreative can you replicate this bug?

**Comment by etpinard** [comment]
should be fixed in https://github.com/plotly/plotly.js/pull/2499

**Comment by etpinard** [comment]
@dy can you confirm that scattergl "works" in IE11 using the latest master? 

from https://github.com/plotly/plotly.js/pull/2556

**Comment by dy** [comment]
![image](https://user-images.githubusercontent.com/300067/38756511-c9ed4192-3f37-11e8-88fa-ecd15779ebce.png)

**Comment by etpinard** [comment]
Beautiful!
