### ISSUE TITLE
Changing locale does not update mode bar buttons labels

### ISSUE THREAD

**Issue by fhurta** [plotly/plotly.js#2484]
I created pen initially in German - the buttons titles and dates on X-axis appears in German. Then changed the locale to English. The date format on X-axis updated but the buttons still contain the German texts.

https://codepen.io/exavier/pen/gegOmV?editors=1010

**Comment by etpinard** [comment]
Hmm. I think I got it to work: https://codepen.io/etpinard/pen/RMKmoZ

**Comment by fhurta** [comment]
Does it work for you? I tried in Chrome and Firefox (current versions) now and it still does not work.
The names on X-axis are updated but hovering over buttons, I still see german titles (e.g. Lassoauswahl for Lasso selection).

**Comment by etpinard** [comment]
Ha, now I see it. Thanks!

**Comment by alexcjohnson** [comment]
`Plotly.plot` should not be used on a plot with existing data - its behavior is weird: it adds the new `data` to the existing traces and ignores `layout`. I guess it does update `config` but this method should be considered deprecated.

If you meant to not change the plot, `Plotly.newPlot` does work as expected. `Plotly.react` however, which is really the only other approved way to change `config`, does not work correctly - it shows the same behavior as `Plotly.plot` - so I'll take that as the item to fix here.
