### ISSUE TITLE
scatterpolar: _fullData[0].textfont not present in figure

### ISSUE THREAD

**Issue by VeraZab** [plotly/plotly.js#2486]
Hello, 
I'd expect _fullData for scatterpolar plots, to contain textfont: https://plot.ly/javascript/reference/#scatterpolar-textfont

It doesn't and the font widgets in the react-chart-editor don't show up because of that.

codepen: https://codepen.io/plotly/pen/LQepNO?q=scatterpolar&limit=all&type=type-pens

**Comment by etpinard** [comment]
That's expected. We only [coerce](https://github.com/plotly/plotly.js/blob/6e0b63a28499e9403ceadbfbe0fc5832595248c4/src/traces/scatterpolar/defaults.js#L54-L56) `textfont` when `mode` includes `'text'`.
