### ISSUE TITLE
Category order, subplots, horizontal bar charts and invisible traces don't play well together

### ISSUE THREAD

**Issue by ChristofferHS** [plotly/plotly.js#2488]
In the CodePen example below, you only need to either make the invisible trace visible or comment out the line `categoryorder : 'category descending'` in order to make the plot work. Switching to a vertical bar chart setup also does the trick.

[CodePen](https://codepen.io/ChristofferHS/pen/mxWWJb)

**Comment by etpinard** [comment]
Thanks for the report.
