### ISSUE TITLE
Plotting points on a city map

### ISSUE THREAD

**Issue by icaromedeiros** [plotly/plotly.js#249]
I'm trying to use plotly (an offline plot) to draw a map showing a scatter plot with enough detail to show urban movement in a city.

I need a "zoom in scope" like this https://www.google.com.br/maps/@-23.9686819,-46.3175511,13z?hl=en

Is it possible to do it in plotly?

I'm confused with the (110 | 50) limitation in scope https://plot.ly/python/reference/#layout-geo-resolution

Is there a way to customize it?

**Comment by icaromedeiros** [comment]
BTW, if it is possible, it would be nice to include an example in https://plot.ly/python/#maps

**Comment by etpinard** [comment]
Plotting at the city level is outside the current scope of plotly.js geographic maps.

I'd recommend using leaflet or MapBox for your use case, as plotly.js is never going to compete against their large dev teams. 

We do hope to compete against [matplotllib basemap](http://matplotlib.org/basemap/users/examples.html) at some point though.

**Comment by ispmarin** [comment]
Thanks, @etpinard. Basemap can adjust their resolution level to city scope quite easily, though. 

BTW, what would require to include city-level plotting in plotly? We may be able to contribute.

**Comment by smenon8** [comment]
@ispmarin Could you share a sample code for adjusting the resolution level to a certain geographic region using Baseman? I am specifically looking to visualization something in Nairobi National Park.

**Comment by etpinard** [comment]
Oh. I forgot about this issue.

You can plot city maps using our `scattermapbox` trace type - which uses [`mapbox-gl`](https://github.com/mapbox/mapbox-gl-js) internally.

Here's an example: http://codepen.io/etpinard/pen/oLdaXP

**Comment by smenon8** [comment]
Thank you @etpinard
