### ISSUE TITLE
Updating subplot axes breaks plot

### ISSUE THREAD

**Issue by ChristofferHS** [plotly/plotly.js#2494]
Updating the second x-axis or either y-axis in the CodePen example below leads to e.g. axes overlapping (updating the first x-axis appears to work fine).

(there is at least some superficial similarity to #2347)

[CodePen](https://codepen.io/ChristofferHS/pen/MVoLrB)

**Comment by etpinard** [comment]
That's actually the desired behavior here.

When calling `relayout(gd, {yaxis: {title: 'new title'}}` you're effectively clearing the all the other set attributes in `yaxis` (in your case that includes `yaxis.domain`).

To only update the title you should call `relayout(gd, 'yaxis.title', 'new title')`, Here's a working version: https://codepen.io/etpinard/pen/jzLOKo?editors=0010
