### ISSUE TITLE
Feature request: allow limiting dragmode 'select' to horizontal or vertical only

### ISSUE THREAD

**Issue by RedShift1** [plotly/plotly.js#2495]
As a follow-up from [this forum thread](https://community.plot.ly/t/only-allow-vertical-selection-with-dragmode-select/9157), in some datasets it doesn't make sense to be able to select both x axis values and y axis values using "dragmode: select". Perhaps dragmode can be extended to 'select', 'selectx' and 'selecty', to respectively allow the user to select only horizontally or vertically.

**Comment by etpinard** [comment]
That would be nice.

**Comment by GlennMatthys** [comment]
Discussion in PR #2498, implementation in PR #2506.

**Comment by etpinard** [comment]
Done in https://github.com/plotly/plotly.js/pull/2506
