### ISSUE TITLE
Removal of breaks for OHLC, Candlestick

### ISSUE THREAD

**Issue by anothar** [plotly/plotly.js#2496]
Good day. Thank you for awesome library.
I created this issue only because I can't post solution in [this thread](https://github.com/plotly/plotly.js/issues/1382). There is no need to download data about holidays for chart without breaks.
Here is [elegant solution](https://codepen.io/anothar/pen/MVvmMz) for daily (or any timeframe) candlestick chart without breaks. The only problem is display text on hover. Instead of date it displays index. This can be fixed when [this issue](https://github.com/plotly/plotly.js/issues/2481) will be solved.

**Comment by etpinard** [comment]
moved to https://github.com/plotly/plotly.js/issues/1382#issuecomment-376156224 

thanks.
