### ISSUE TITLE
iOS + Safari touch events

### ISSUE THREAD

**Issue by tbrennanw0rk** [plotly/plotly.js#25]
The touch events on the chart which shows the markers, do not appear on iOS/Safari 9.1.
It is visible under Android Kitkat and later.

**Comment by tbrennanw0rk** [comment]
FYI, The issue has been resolved after further digging around, as using ionic framework with plotly integration, the touch events did not work, there's http://github.com/angular/material/issues/1826 which had the comment by 'DMDc0de' highlighting the angular directive `data-tap-disabled="true"` which did the trick.

**Comment by bpostlethwaite** [comment]
thanks @tbrennanw0rk for the follow up response. Marking this issue resolved and closing.
