### ISSUE TITLE
PNG snapshots on Safari

### ISSUE THREAD

**Issue by parsonsk** [plotly/plotly.js#250]
Although PNG snapshots are now working again on FF, they still do not work on Safari (at least Version 9.0.3 (11601.4.4))

**Comment by etpinard** [comment]
Thanks for reporting. This is a known bug.

Only a small percentage of our users use Safari, so this won't be a priority for the plotly.js team in the near future.

**Comment by etpinard** [comment]
Looking over PR https://github.com/plotly/plotly.js/pull/104 could be a good place to start for this bug.

**Comment by etpinard** [comment]
Here's why downloading doesn't not work in Safari: http://caniuse.com/#feat=download

**Comment by timelyportfolio** [comment]
Should I provide an option in `downloadImage` to open the link instead of download?

**Comment by etpinard** [comment]
This is how `FileServer.js` gets it done: https://github.com/eligrey/FileSaver.js/blob/master/FileSaver.js#L110-L119

**Comment by mdtusz** [comment]
Fixed in #446, then again in #604.

**Comment by PPPW** [comment]
Dear @mdtusz and @etpinard,
I found that currently downloading works fine in Safari, however another file named "unknown" will also be downloaded. This file is actually exactly the same as the png file. I wonder is this issue easy to fix? Thanks.

**Comment by etpinard** [comment]
@PPPW please subscribe to https://github.com/plotly/plotly.js/issues/1227 for the latest development info.
