### ISSUE TITLE
mode:text for regl-scatter2d

### ISSUE THREAD

**Issue by jackparmer** [plotly/plotly.js#2501]
I have a few bio customers who need to display hundreds to thousands of single letter markers like in the below graph:

![image](https://user-images.githubusercontent.com/1865834/37943372-50436efc-3145-11e8-945a-6a7290cc3365.png)

@dfcreative already has a great example of single-letter rendering for regl-scatter2d here:
https://dfcreative.github.io/regl-scatter2d/copyrights.html

I'd like to propose that `mode: text` be enabled for `scattergl`, but only work for single letters (for now). 

Note that `mode: text` currently does not do anything for `scattergl`:  https://codepen.io/plotly/pen/dmZNjM

We've tried creating graphs like the above with SVG, but for a larger number of letters, they are too slow. Here is an SVG example with a `mode: text` `scatter` trace overlaid on a `heatmap` trace: https://plot.ly/~jackp/18395/ (Note how long it takes to update when dragging the slider).

**Comment by etpinard** [comment]
I have my doubt about the single-letter approach. If we do so, then we would stuck with that until we make breaking API changes. @dfcreative How hard would it be to support text of all lengths?

And by the way @jackparmer about https://plot.ly/~jackp/18395/ are you unhappy about the first-render performance or just the drag hangups (or both :smirk: )? Simply improvement drag performance for SVG text nodes shouldn't be too hard.

**Comment by jackparmer** [comment]
> are you unhappy about the first-render performance or just the drag hangups (or both 😏 )

Mostly the drag performance.

> How hard would it be to support text of all lengths?

Dima told me up to 2 weeks.

**Comment by dfcreative** [comment]
@etpinard depends on the requirements. There are many ways to do that, the simplest is canvas2d texture, that may take a day or two. [Font-texture](https://webglfundamentals.org/webgl/lessons/webgl-text-glyphs.html) or something with sdf would take a week or two. Same for [vector-based](http://wdobbie.com/post/gpu-text-rendering-with-vector-textures/) approach.

**Comment by jackparmer** [comment]
I think we should do the `sdf` method after `splom` if we want multi-character marker text in `scattergl`. No point in adding `mode: text` to `scattergl` if it's not going to be significantly faster than SVG `scatter`.

**Comment by etpinard** [comment]
Related: https://github.com/plotly/plotly.js/issues/1116

**Comment by etpinard** [comment]
done in https://github.com/plotly/plotly.js/pull/2737, followup in https://github.com/plotly/plotly.js/issues/2780
