### ISSUE TITLE
Can't register module scatter3d

### ISSUE THREAD

**Issue by ndabAP** [plotly/plotly.js#2502]
**Browser**: Chrome 65
**Device**: Desktop
**Plotly.js version**: 1.35.2

Problem: It's not possible to use `Plotly.register(require('plotly.js/lib/scatter3d'))` to show up 3d charts. Error message appears:

> Webgl is not supported by your browser 

And console logs

> app.bundle.js:8 Uncaught TypeError: Cannot read property 'canvas' of undefined

Using the same set-up and registering the bar components works fine. Repository for reproduction: https://github.com/ndabAP/plotly.js-scatter3d-issue/tree/master

Steps to reproduce:

1. `$ npm i`
2. Open file `dist/index.html`. You should see a bar chart
3. Comment out line 20-21 and comment in line 6-17
4. `$ npm run build`
5. Open the file `dist/index.html` again. The error appears

When I import the whole Plotly.js library instead of registering the single chart components the 3d chart works fine.

**Comment by etpinard** [comment]
What browser are you using?

**Comment by ndabAP** [comment]
Using Chrome but just tested it with Firefox: Same issue.

**Comment by etpinard** [comment]
... which version of Chrome and Firefox? This is very important. WebGL (and thus scatter3d) isn't support in all browsers. If you browser doesn't support WebGL there's not much we can do.

You can navigate to https://get.webgl.org/ to check whether your browser supports WebGL.

**Comment by ndabAP** [comment]
Newest versions (65.0.3325.181 for Chrome).

When I require the whole Plotly.js library, I can see the 3 d chart without problems.

**Comment by etpinard** [comment]
In your https://github.com/ndabAP/plotly.js-scatter3d-issue/tree/master your webpack config isn't missing the `ify-loader` rule. Please see https://github.com/plotly/plotly.js#building-plotlyjs-with-webpack for more info on custom bundling with webpack.

**Comment by ndabAP** [comment]
You're right. I added the `ify-loader` but the error still appears.

**Comment by etpinard** [comment]
Your config isn't right yet (I think, I'm no webpack expert). You do need to use `ify-loaded` on `node_modules` files. That is, that `exclude: /(node_modules|bower_components)/,` line seems off.

See full example here: https://github.com/plotly/plotly-webpack/blob/master/webpack.config.js

**Comment by ndabAP** [comment]
That did it. Sorry for bothering you. Should more rely on documentation ;) Have a nice day!
