### ISSUE TITLE
3D scatter plot not showing on Firefox

### ISSUE THREAD

**Issue by jvkersch** [plotly/plotly.js#2518]
This is on Mac OS 10.13.3 with Firefox 59.0.2. The 3D scatter plot examples show an empty scatter plot when the opacity is set to something less than 1.0. I can still interact with the data, that is, hover over the (invisible) points and see the coordinates.

These same examples work fine (i.e. show the expected scatter plot) in Chrome, on the same machine. The problem persists on Firefox even when I open the example in a private window, or when I disable my Firefox extensions. There seem to be no relevant messages printed to the console.

The example on [this page](https://plot.ly/javascript/3d-scatter-plots/) has the issue. The codepen (unaltered from the official docs) is [here](https://codepen.io/plotly/pen/XmGVdd). A screenshot of how this appears is attached.

I asked my co-workers to doublecheck, and some of these have the same issue while others don't. Despite the lack of concrete leads, I'd be happy to dig deeper if someone can offer some suggestions.

<img width="776" alt="schermafbeelding 2018-04-03 om 17 01 26" src="https://user-images.githubusercontent.com/537559/38260913-bbbbf390-3760-11e8-9380-9deb648ec4e0.png">

**Comment by alexcjohnson** [comment]
Huh, is this another GPU-hardware-dependent issue like #1368 😱? Works fine for me, Mac OS 10.13.4, both before and after updating FF 58 to 59.

**Comment by jvkersch** [comment]
Thanks for investigating! Regarding HW acceleration, that's an interesting hypothesis. @alexcjohnson Could I ask what machine you are on? Below are my specs, and I'll also ask my colleagues who helped diagnose the problem yesterday. Let's see if a pattern emerges.

![schermafbeelding 2018-04-04 om 10 55 59](https://user-images.githubusercontent.com/537559/38301342-28dfdefa-37f7-11e8-9ce3-841c84a593c5.png)

I'd be quite interested in digging a little deeper here. This could be a nice inroad to understand how plotly works under the hood, and to do some debugging in an environment that I'm unfamiliar with.

**Comment by jvkersch** [comment]
Also, one of us found that he had the same issue with Firefox Nightly, but that the issue went away when he disabled tracking protection...

**Comment by mplanchard** [comment]
I am the one for whom this was working on a Mac on Nightly, but only without tracking protection.

At home (2012 MacBook Pro Retina, Mid-Year, discrete GPU), I was seeing the following

* Developer Edition (60.0b1) - no plot, regardless of state of tracking protection state
* Nightly (61.0a1) - plot shows up only when tracking protection state is "Never"

With tracking protection enabled, I got the following console errors in Nightly:

```
An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can remove its sandboxing. XmGVdd
The resource at "https://www.google-analytics.com/analytics.js" was blocked because tracking protection is enabled.[Learn More] XmGVdd
Loading failed for the <script> with source "https://www.google-analytics.com/analytics.js". XmGVdd:82
The resource at "https://srv.buysellads.com/ads/CKYDVK7U.json?callback=CPAdsinsertAd&forcenads=1&forwardedip=66.90.152.57&callback=jQuery2110607732980988535_1522793932594&_=1522793932595" was blocked because tracking protection is enabled.[Learn More] XmGVdd
Loading failed for the <script> with source "https://srv.buysellads.com/ads/CKYDVK7U.json?callback=CPAdsinsertAd&forcenads=1&forwardedip=66.90.152.57&callback=jQuery2110607732980988535_1522793932594&_=1522793932595".
```

The only one of those that was unique when protection was turned on was the one the says "was blocked because tracking protection is enabled."

Here at work (Dell XPS 15", Ubuntu 16.04), I am seeing the following:

* Developer Edition (60.0b9) - plot shows up, regardless of tracking protection state
* Nightly (61.0a1 (2018-03-22)) - plot shows up, regardless of tracking protection state

I get the following console errors:

```
An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can remove its sandboxing.
XmGVdd
Loading failed for the <script> with source “https://srv.buysellads.com/ads/CKYDVK7U.json?callback=CPAdsinsertAd&forcenads=1&forwardedip=24.227.217.186&callback=jQuery211025601335587712626_1522847520798&_=1522847520799”.
```

weirdly, the second of those errors doesn't show up on Nightly, just on Developer Edition.

Let me know if there's any other information I can provide.

**Comment by alexcjohnson** [comment]
My macbook, on which FF 58 and 59 work fine:
<img width="245" alt="screen shot 2018-04-04 at 10 02 57 am" src="https://user-images.githubusercontent.com/2678795/38312316-709031e4-37ef-11e8-84e3-0ed12641d12c.png">
Also works on FF on my iPhone, but I'm not sure that tells us much, as that's constrained to use Apple's rendering engine.

**Comment by archmoj** [comment]
It was not reproducible. 
@jvkersch Could you please test with a more recent Firefox namely FF63 or FF65 to see if you may still notice the problem?

**Comment by jvkersch** [comment]
@archmoj Thanks for checking up on this. I can't reproduce either, but I am no longer on Mac OS (I've switched to Linux and don't own a Macbook anymore). On Ubuntu 18.04 with FF 65 the code works as expected. Please feel free to close this issue.

**Comment by ptynecki** [comment]
I can reproduce the problem with my environment and with my custom 3D scatter based on plotly.js:

* macOS 10.15.2
* Firefox 72.0.2 x64
* ploty.js v1.52.1

But what's funny thing, I see dots in examples scatter 3d plots:
https://plot.ly/python/3d-scatter-plots/
