### ISSUE TITLE
How to clear annotations

### ISSUE THREAD

**Issue by rgeos** [plotly/plotly.js#252]
When creating annotations like below
``` python
	fig['layout']['annotations'] = go.Annotations([])
	for i in list_of_dictionaries:
		fig['layout']['annotations'].append(go.Annotation(i))
```
in the first run of the script, the rendering of the annotations is correct: [correct rendering](https://plot.ly/~r.geo.s/327/ma-crossover-strategy-foramzn/)

However, on a second run, with a different list of dictionaries, the new annotations are rendered correctly but without clearing the old annotations [duplicate annotations](https://plot.ly/~r.geo.s/329/ma-crossover-strategy-foramzn/)

Isn't `go.Annotations([])` suppose to initialize with an empty list?

Am I doing something wrong?

**Comment by etpinard** [comment]
Looks like a https://github.com/plotly/plotly.py bug. Please open an issue there.
