### ISSUE TITLE
Feature Request: Sankey Node Default Order

### ISSUE THREAD

**Issue by baraaorabi** [plotly/plotly.js#2520]
I think it would be cool to be able to force an ordering on the nodes of a sankey diagram. I imagine the order in which nodes appear in the label list of a sankey data object would be a reasonable choice.

**Comment by davhin** [comment]
I would also highly value the ability to order the nodes in a sankey diagram.

**Comment by davhin** [comment]
@antoinerg I see you have assigned yourself to this issue, thank you for that! Since I have no  JS-experience and cannot help out on the coding side is there anything I can do?

**Comment by skylogic004** [comment]
I agree, this would be very useful. 

In my case, I have about 25 target nodes and plotly puts most of them in the correct order that I would like, but without fail it always has to put 2 of them in some random place, breaking the cleanliness of the plot. Manual ordering would help me fix this.

Also, in my case, the targets are unique to a source, meaning that there should never be a need for connections to overlap (which I suppose is a different issue, as whatever mechanism is used to auto-sort nodes really should be able to prevent overlap when it's not necessary).

**Comment by jwilson8767** [comment]
@antoinerg 
Possibly of use: https://stackoverflow.com/questions/33461868/ordering-nodes-in-d3-sankey-diagram
And even more recently: https://github.com/d3/d3-sankey/pull/53

**Comment by antoinerg** [comment]
Also, although we can drag nodes within a column, this isn't reflected in the state so on save/reload, export etc this info is lost. This position needs to be part of the state! Ordering should also work.

**Comment by ndeku** [comment]
Agree this would add value to the Sankey diagrams in Plotly. Without consistent node ordering the diagrams are not reliably reproducible.

**Comment by Mahdis-z** [comment]
The new feature `node.(x|y)` sets the position of nodes in [Sankey](https://plot.ly/python/sankey-diagram/#define-node-position). Please follow this [ issue](https://github.com/plotly/plotly.js/issues/4373) for `sorting` feature.
