### ISSUE TITLE
"bargroupgap" adds space between histogram "bars"

### ISSUE THREAD

**Issue by ndabAP** [plotly/plotly.js#2521]
See:

https://codepen.io/anon/pen/JLBVEp?editors=0010

Histogram shouldn't have gaps. See:

https://www.mathsisfun.com/data/images/bar-chart-vs-histogram.svg

**Comment by etpinard** [comment]
Right. Histograms don't have have `bargroupgap` set to 0 by default. So, you're arguing that `bargroupgap` should be ignored completely always for histogram traces?

**Comment by ndabAP** [comment]
Exactly, because it's continuous instead of categorical. What do you think?

**Comment by etpinard** [comment]
> because it's continuous instead of categorical

Yep, that's why be default `bargroupgap: 0`. But if the user really _really_ wants gaps in there, I'm not sure we should stop them.

At the very least what you're asking is a breaking change, so it won't happen anytime soon.

**Comment by ndabAP** [comment]
Understood :) I'm making a theme for Plotly and try to generalize as much as possible. The easiest would be to use one master layout for all charts. 

I'd add another property like `histogramgab`. That wouldn't be a breaking change.

**Comment by etpinard** [comment]
> I'd add another property like histogramgab. That wouldn't be a breaking change.

That's an idea, but still it would be a breaking change. Some users might be using `bargroupgap` on histogram right now.

**Comment by etpinard** [comment]
I vote for _not a bug_.

**Comment by etpinard** [comment]
By the way, if you're interested in _themes_, you may want to follow https://github.com/plotly/plotly.js/issues/2469

**Comment by alexcjohnson** [comment]
> I vote for _not a bug_. 

I think so too, I'm afraid. You can make a histogram on a categorical axis, for example, which is of course not continuous and therefore a gap is reasonable. And you can mix (and stack) `histogram` traces with `bar` traces for cases where *some* of your data is pre-binned, and in that case it doesn't make sense to have two different gaps, we would have to pick one of them to win and ignore the other.

**Comment by ndabAP** [comment]
Ah great and very relevant. Closing this.
