### ISSUE TITLE
Add number type to `annotations.text` chart schema

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.js#2523]
Similar to #2519 , in https://github.com/plotly/plotly.py/pull/942 we're updating plotly.py's validation logic to automatically use the plotly.js schema.

Annotations allow numbers as `text` (https://codepen.io/chriddyp/pen/WzgxwK) and it's a pretty common use case in the Python library to directly pass data into the `text` field.

Could we add `number` to the valid types in the annotations schema? It's currently:
```
                                "text": {
                                    "valType": "string",
                                    "role": "info",
                                    "editType": "calc",
                                    "description": "Sets the text associated with this annotation. Plotly uses a subset of HTML tags to do things like newline (<br>), bold (<b></b>), italics (<i></i>), hyperlinks (<a href='...'></a>). Tags <em>, <sup>, <sub> <span> are also supported."
                                },
```

**Comment by alexcjohnson** [comment]
Better: you can look at whether the attribute includes [`strict: true`](https://github.com/plotly/plotly.js/blob/3d65de3adb20ca0c75e9ecb67739c5d801cc3b24/src/plots/font_attributes.js#L35) - if it does, the value must be explicitly a string, and numbers will be rejected. If it does not, we accept numbers (and ONLY numbers - not booleans or any other types) and will coerce them to strings during `supplyDefaults`.

**Comment by chriddyp** [comment]
ah very nice, that should work. fyi @jmmease
