### ISSUE TITLE
Duplicate Key in _$colorScale_104?

### ISSUE THREAD

**Issue by ToucanBran** [plotly/plotly.js#2528]
Not sure if this is a huge deal but I was trying to compile plotly.js to ES2015 using google's closure compiler which was throwing an error of duplicate key "cool" on line 121905. I looked at all the other keys for the _$colorScale_104 dictionary and noticed that there was indeed another key called "cool" on line 121855. I was able to get it to compile by changing one of the key names but that seems kind of bad.

This is plotly v1.35.2.

**Comment by etpinard** [comment]
Looks like you're trying to compile one of our already minified bundles (those `$_???` keys come from [`browser-pack-flat`](https://github.com/goto-bus-stop/browser-pack-flat)).

It's probably best to compile un-minified code e.g. `dist/plotly.js` instead of `dist/plotly.min.js`.

**Comment by ToucanBran** [comment]
dist/plotly.js seems to show the same code (i.e. the _$colorScale_104 variable) and duplicate key.

**Comment by etpinard** [comment]
Oh right. We `browser-pack-flat` those too. My bad.

**Comment by etpinard** [comment]
@ToucanBran we just released new `dist/` bundles. Can you confirm whether this problem persists?

**Comment by etpinard** [comment]
We dropped `browser-pack-flat` in https://github.com/plotly/plotly.js/pull/2572

So this issue should be _resolved_.
