### ISSUE TITLE
Text missing if axis range is reversed and cliponaxis=false

### ISSUE THREAD

**Issue by darabos** [plotly/plotly.js#2531]
I have a pull request (https://github.com/darabos/plotly.js/pull/1) for it, but I made it against my own repo now to follow the contribution guidelines.

I committed the "before" baseline to demonstrate the issue. You can see the fix in the second commit's diff:
![cliponaxis-before-after](https://user-images.githubusercontent.com/1268018/38419569-4240aa9a-39a1-11e8-962e-459e659c8ab4.png)

This example is a bit unusual. Who uses upside-down bar charts?! In real life I hit this issue with a horizontal bar chart where I wanted the order of the groups in the chart to match the order in the legend:
![horizontal-bar-chart](https://user-images.githubusercontent.com/1268018/38419723-c54d7d14-39a1-11e8-83aa-6fc333023cbb.png)

I set `autorange: 'reverse'` and the texts disappeared:
![bars-reversed](https://user-images.githubusercontent.com/1268018/38419860-3eb42522-39a2-11e8-8106-b096c3284a9b.png)

If I remove `cliponaxis: false`, the texts are clipped:
![bars-clipped](https://user-images.githubusercontent.com/1268018/38419873-4a7fd252-39a2-11e8-8f43-81d41718d7b9.png)

I'm open to suggestions, but my PR is aimed at fixing the version with the missing texts. Thanks!

**Comment by etpinard** [comment]
Thanks very much for bringing this up!

Looks fix is looking great. I made one minor comment -> https://github.com/darabos/plotly.js/pull/1/files#r179756565

PR away :rocket:
