### ISSUE TITLE
overlapping of Lines in Scatter Plot Time series(Plotly.JS)

### ISSUE THREAD

**Issue by thrinethra99** [plotly/plotly.js#2538]
(Plotly.JS) I have created a time series scatter plot with markers , lines and text. The issue I am facing is I have multiple nodes which is connected to other nodes with trace lines.The lines drawn or trace lines drawn are overlapping each which makes it hard to find to which nodes the trace lines are connected to. 
I am attaching the code which I have used . 
The plotly graph:
![image](https://user-images.githubusercontent.com/27509341/38475005-bc628de8-3b72-11e8-932a-f4e6213536f9.png)
![image](https://user-images.githubusercontent.com/27509341/38475014-d2191166-3b72-11e8-8ded-a5ed85568273.png)

![image](https://user-images.githubusercontent.com/27509341/38474868-8575cbac-3b71-11e8-9ceb-79697e52e945.png)

The above part is the code for trace lines.

The below is the code used to draw plotlyJSscatter plot (time series)
![image](https://user-images.githubusercontent.com/27509341/38474928-0fe0fbc2-3b72-11e8-9800-808bfed270df.png)

**Comment by etpinard** [comment]
This doesn't look like a bug report nor a feature request. Closing.

As per our contributing guidelines, please ask questions of the likes on https://community.plot.ly/c/plotly-js
