### ISSUE TITLE
Investigate relayout & react + axis constraints behavior

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#2540]
In PR https://github.com/plotly/plotly.js/pull/2527, a few oddities with relayout on graphs with axis constraints (i.e. `(x|y)axis.constrain: 'range' || 'domain'`) were detected. 

From https://github.com/plotly/plotly.js/pull/2527#discussion_r180543504 and below, tests coverage was deemed inadequate to assume anything about the current behavior. The first step would be to beef up the coverage there. Next, determine whether or not graphs with axis constraints do need to go though the editType `calc` on axis range relayouts. Finally, we should lock down the limitations (if any) of editType `axrange` for graphs with axis constraints.

cc @alexcjohnson

**Comment by etpinard** [comment]
Found a bug in https://codepen.io/etpinard/pen/qYopzp 

![peek 2018-05-10 12-26](https://user-images.githubusercontent.com/6675409/39880977-5aa565be-544d-11e8-8386-f15d94eee9ad.gif)

introduced in `1.36.0` (probably from PR https://github.com/plotly/plotly.js/pull/2527) where the y-axis is getting re-position properly. This should be a good starting point for this ticket here.

**Comment by etpinard** [comment]
PR https://github.com/plotly/plotly.js/pull/2628 fixed the :beetle: reported above in https://github.com/plotly/plotly.js/issues/2540#issuecomment-388106902, but many issues remain.

Pasting https://github.com/plotly/plotly.js/pull/2628#issuecomment-388446268 here:

A few more comments on constrained axes, that should be followed up in https://github.com/plotly/plotly.js/issues/2540:

- Could making range relayout go through editType "plot" (instead of "calc") be sufficient? When replacing this line

https://github.com/plotly/plotly.js/blob/a132b85b899dd490216d12823be56ad3861f091f/src/plot_api/plot_api.js#L2039

with `flags.plot = true`, no tests are failing. 

- I think `Plotly.react` is broken with constrained axes. I'm not sure if it's always been broken or if the recently-added "axrange" edit did it :confused: 

and @alexcjohnson 's https://github.com/plotly/plotly.js/pull/2628#issuecomment-388458992

> Could making range relayout go through editType "plot" (instead of "calc") be sufficient?

Do we have a test of setting mutually-exclusive range values, as per the [comment on that line](https://github.com/plotly/plotly.js/blob/a132b85b899dd490216d12823be56ad3861f091f/src/plot_api/plot_api.js#L2034-L2038)? If we do, and the result correctly fixes them for the constraints, then go for it!

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
