### ISSUE TITLE
No click events in geo plots with dragmode=select

### ISSUE THREAD

**Issue by darabos** [plotly/plotly.js#2542]
If I add `dragmode: 'select'` to the basic choropleth example, `plotly_click` events are no longer emitted. `plotly_selected` events are emitted for clicks, but with an `undefined` data. So I cannot handle clicks in this mode.

Example: https://codepen.io/anon/pen/QmoxOP

The same events work for cartesian plots. I think this is because `dragElement` there is initialized with a [`clickFn`](https://github.com/plotly/plotly.js/blob/v1.35.2/src/plots/cartesian/dragbox.js#L183) that forwards simple clicks.  I thought I'd add `Fx.click()` to `geo.js`'s [`clickFn`](https://github.com/plotly/plotly.js/blob/v1.35.2/src/plots/geo/geo.js#L415) too. But I cannot create a repro in Jasmine. 

I tried making a copy of the [`choropleth click events`](https://github.com/plotly/plotly.js/blob/v1.35.2/test/jasmine/tests/geo_test.js#L710) test and adding `Plotly.relayout(gd, { dragmode: 'select' }, [0]).then(...)`. But it still passes. I cannot figure out why.

Thanks for any advice!

**Comment by etpinard** [comment]
Thanks for the very clear report!

Any inconsistencies across subplot types should be addressed, but come to think of it, I'm not sure the cartesian behavior is _correct_. More clearly, should `plotly_click` be emitted under `dragmode: 'select' || 'pan'`? 

Cleaning this up will be especially important when implementing selection by click (in https://github.com/plotly/plotly.js/issues/1848#issuecomment-365467584).

**Comment by etpinard** [comment]
This appears fixed in `v1.41.0`.

https://github.com/plotly/plotly.js/pull/2944 standardized the behavior across all subplots that support selections.
