### ISSUE TITLE
How to activate date laybel

### ISSUE THREAD

**Issue by leentheone** [plotly/plotly.js#2545]
Hi all. I have a stupid question. I send all data to plotly to draw "Scatter" chart. But it is not very useful. I make few buttons as "last year", "last month" and etc. What I need to do to draw full chart but make plotly 
show chart only for "last month".
I'm using python 3x.
Thanks.

**Comment by etpinard** [comment]
Looks like you didn't read our contributing guidelines. Closing.

Please ask questions of the like on https://community.plot.ly/c/plotly-js.
