### ISSUE TITLE
Speed up cartesian axes supplyDefaults

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#2549]
From https://github.com/plotly/plotly.js/pull/2527, Plots.supplyDefaults takes > 100ms at 50x50 subplots which feels like an eternity when zooming.

- Getting rid of `indexOf` into axis lists would be a good start (perhaps experimenting with ES6 `Map` and `Set` could be worthwhile)
- Perhaps we could try opening a partial `Plots.supplyDefaults` pathway, that would only update a subset of the graph's cartesian axes and their dependencies.

**Comment by etpinard** [comment]
> So I'm thinking of moving this block out of Plots.linkSubplots and into the lsInner subroutine

Done in https://github.com/plotly/plotly.js/pull/2628. 

PR https://github.com/plotly/plotly.js/pull/2628 also added set axis anchors to all sploms except the ones with `showlowerhalf: false` so that the "find main subplot" loop is skipped when we can.

**Comment by etpinard** [comment]
From https://github.com/plotly/plotly.js/pull/3070#issuecomment-426792309, 50 dims splom traces spend about 40ms in [`axis_autotype.js`](https://github.com/plotly/plotly.js/blob/master/src/plots/cartesian/axis_autotype.js). Improving perf there could be very beneficial.

**Comment by etpinard** [comment]
Referencing https://github.com/plotly/plotly.js/issues/749 - moving away from the "relink everything approach" should speed up `supplyDefaults` in some scenarios.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
