### ISSUE TITLE
How to keep axis range fixed?

### ISSUE THREAD

**Issue by AlexLuya** [plotly/plotly.js#2550]
I have set range in layout like this:
```
var poseLayout = function(width, height) {
		return {
			title : '',
			xaxis : {
				range : [ 0, 640 ]
			},
			yaxis : {
				range : [ 0, 480 ]
			},
			width : 640,
			height : 480,
			showlegend : false,
			shapes : []
		};
```
but as you can see here:
![arbeitsflache 1_165](https://user-images.githubusercontent.com/303353/38674260-6afafc58-3e86-11e8-8743-d10378769f4d.png)
both x-axis and y-axis range changes with x,y values dynamically,how to keep range fixed?

**Comment by etpinard** [comment]
This has been asked numerous times before onhttps://community.plot.ly/c/plotly-js

**Comment by krinsman** [comment]
Can you link to one of the places where this has been asked and _answered_ correctly on the forums? @etpinard I am also having difficult finding the answer to a related question via Google.

**Comment by nicolaskruchten** [comment]
setting `fixedrange: true` in `layout.xaxis` and `layout.yaxis` will do this.

**Comment by simplenotezy** [comment]
@nicolaskruchten Can you provide an example?

**Comment by nicolaskruchten** [comment]
Sure, https://codepen.io/nicolaskruchten/pen/WNGGerr?editors=0010 ... this figure has a specified x and y range and cannot be panned or zoomed.
