### ISSUE TITLE
scatter3d ticktext <br>

### ISSUE THREAD

**Issue by Kolano** [plotly/plotly.js#2551]
The `<br>` HTML tag is not honored in scatter3d ticktext. They seem to be rendered as spaces?

```
scene:{
	yaxis: {
		range: [0, 65536],
		tickmode: "array",
		ticktext: ["000<br>0000","064<br>4444","128<br>8888","192<br>BBBB","255<br>FFFF"],
		tickvals: [0, Math.pow(64,2), Math.pow(128,2), Math.pow(192,2), Math.pow(256,2)],
		title: "Interface"
	}			
}
```

I tried to provide an example in CodePen...
https://codepen.io/Kolano/pen/dmLBJK
...but it seems to fail to render tickmode:"array" text at all for some reason.

**Comment by etpinard** [comment]
Your codepen had `tickvalues` instead of the correct `tickvals`: https://codepen.io/etpinard/pen/pLBXBN?editors=0010

But `<br>` unsupported on 3D axes. Related: https://github.com/plotly/plotly.js/issues/1165 and https://github.com/plotly/plotly.js/issues/608
