### ISSUE TITLE
Logarithmic axis ticks include mysterious "2 5" between each tick.

### ISSUE THREAD

**Issue by jmckib** [plotly/plotly.js#2554]
When an axis of type log is stretched wide enough by increasing html width, the numbers "2 5" appear as smaller ticks between each larger tick. Here's a picture, look at the x-axis:
<img width="983" alt="screen shot 2018-04-13 at 11 13 37 am" src="https://user-images.githubusercontent.com/183379/38742921-be359ba0-3f0b-11e8-9a1f-5112977e022c.png">

Also here's a codepen link to produce the picture. https://codepen.io/anon/pen/VXOVyX I created it by taking the codepen link from the log documentation and increasing the div width to 1000px https://plot.ly/javascript/log-plot/

Are those "2 5" expected? If so, what do they mean, and is there a way to remove them?

**Comment by alexcjohnson** [comment]
Yes, those are expected - they're labeling 2 and 5 times the previous power of 10. Zoom in a bit more and you'll see 2, 3, 4, 5, 6, 7, 8, 9.

You can get rid of these labels, *and* the lines that they're labeling, using `xaxis: {dtick: 1}`, the downside then is it won't auto-adjust as you zoom in or out - see https://plot.ly/javascript/reference/#layout-xaxis-dtick for full details.

**Comment by jmckib** [comment]
@alexcjohnson Thanks, setting dtick to 1 got rid of the subticks.

**Comment by nite** [comment]
It'd be nice to be able to keep the gridline but remove the confusing interim tick labels - are you aware of any way of doing this @alexcjohnson ?

**Comment by alexcjohnson** [comment]
Unless you want to do something hacky with `tickvals` and `ticktext`, I don't think there's a way to get rid of these labels. Would need to be a new feature to make this happen easily and dynamically.

**Comment by nite** [comment]
Is there any way to control their style & hide them using css? (not obvious to me). Is there any way to influence the decision on how many are displayed (eg. in the codepen above, 2 & 5 appear but then they all appear when you zoom in). 

Ideally, looking for something more like this plot here: 
https://en.wikipedia.org/wiki/Logarithmic_scale#/media/File:Log-log_plot_example.svg
I'd imaging this is a standard in matplotlib / matlab?

**Comment by nite** [comment]
I've got an even hackier solution to this: 
```
text[style*="font-size: 9px"] {
  font-size: 0px!important;
}
```
https://codepen.io/nite/pen/xMapqL

**Comment by ericphanson** [comment]
I found `tickformat = "~r"` useful for this issue, to show the minor tick labels as expected
