### ISSUE TITLE
A combination of bar chart with a date x axis and width set makes bar plot disappear 

### ISSUE THREAD

**Issue by jamalmoir** [plotly/plotly.js#2559]
It seems that the combination of a bar chart, along with a date x-axis and a width set makes that plot disappear.

Having just the date x-axis or just setting a width appears to be fine, however the combination…

This can be observed in this code pen: https://codepen.io/jamalmoir/pen/BrXyVy

**Comment by etpinard** [comment]
Bar `width` on date axis must be provided in milliseconds (as described [here](https://plot.ly/javascript/reference/#bar-width). For example, setting `width` to 15 days gives: https://codepen.io/etpinard/pen/BrXJaM?editors=0010
