### ISSUE TITLE
Missing lines for scattergl

### ISSUE THREAD

**Issue by amidabucu** [plotly/plotly.js#2566]
Version: 1.35.2

Reproduction:

https://jsfiddle.net/ccbja8ow/
I tried it in Firefox and Chrome.

<img width="395" alt="screen shot 2018-04-17 at 16 04 15" src="https://user-images.githubusercontent.com/5149394/38874773-33b43508-4259-11e8-864b-16c74b337311.png">

This should generate 530 lines with 2 points. Notice the missing lines at the top.

Am I misconfiguring something?

**Comment by alexcjohnson** [comment]
Thanks @amidabucu - very clear report, even parametrized so we can play with it to debug 🏆 

cc @dy looks like regardless of # of points per trace, we're only drawing lines for the first 512 of them?
