### ISSUE TITLE
Reset axis does not elminate select box

### ISSUE THREAD

**Issue by ifll** [plotly/plotly.js#257]
When some points are selected from the plot with the cursor (either with "box select" or "lasso select") a box or contour is drawn around them.

This box disappears (as expected) under this procedures:
- Zoom cursor is selected (from the modebar) and zoom is applied [box dissappears and points appear unselected again (no opacity appears on the points)]
- Pan cursor is selected (from the modebar) and panning is applied [box dissappears and points appear unselected again (no opacity appears on the points)]
- Box select cursor is selected (from the modebar) and box selection is applied [box dissappears  from the previous position and appears in the new one]
- lasso select cursor is selected (from the modebar) and lasso selection is applied [lasso selection dissappears  from the previous position and appears in the new one]
- Pan cursor is selected (from the modebar) and panning is applied [box dissappears and points appear unselected again (no opacity appears on the points)]

This box doesn't disappear (as not expected) under this procedures:
- Zoom in button is pressed (from the modebar) [box does not dissappear from the previous position (but oppacity of the points is restored)]
- Zoom out button is pressed (from the modebar) [box does not dissappear from the previous position (but oppacity of the points is restored)]
- Autoscale button is pressed (from the modebar) [box does not dissappear from the previous position (but oppacity of the points is restored)]
- Reset axes in button is pressed (from the modebar) [box does not dissappear from the previous position (but oppacity of the points is restored)]

The box shoud dissapear as it could lead to a bad missunderstanding about the points selected. I am using the latest release from plotly (downloaded on 16.02.2016) and google chrome version 48.0.2564.109 (64-bit). I haven't checked this bug for any other browser.

Besides this, when some points are selected, and a snapshot is taken, the selection done does not appear on the final snapshot image, and I think it would be great if it appears, as the used could download the image with the selection done, and he is always capable to download the image without the selection.

I would like to remind also the issue about the image size when downloading [Snapshot routines should allow users to specify image width/height #83](https://github.com/plotly/plotly.js/issues/83). I think it would be great if a solution can be found on this opened issue as the user could also choose the resolution of the final image.

**Comment by etpinard** [comment]
Thanks for the very detailed issue. 

The points you made are all known limitation of our first lasso/select box iteration. 

Your points have some overlap with https://github.com/plotly/plotly.js/issues/181.

Refer to PR https://github.com/plotly/plotly.js/pull/154 for more info about the current implementation and more precisely https://github.com/plotly/plotly.js/pull/154#issuecomment-168797572 for what's in the plans.

**Comment by etpinard** [comment]
Merging this thing into https://github.com/plotly/plotly.js/issues/1848
