### ISSUE TITLE
Deleting groupby names via legend doesn't update correctly

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#2576]
- Create a legend with groupby items, in editable mode
- Delete one of the default labels -> after blur, it stays empty (**the default label should come back**).
- Do something else that redraws the graph (including typing in another label) -> now the default label comes back

see https://codepen.io/alexcjohnson/pen/erNPjB?editors=0010 - based on the mock at
https://github.com/plotly/plotly.js/blob/4ed586a6402073cc5c50a40cad5f652d7472fcce/test/jasmine/tests/legend_test.js#L918-L931

**Comment by etpinard** [comment]
Possibly related: https://github.com/plotly/plotly.js/issues/1742

**Comment by alexcjohnson** [comment]
Actually I think my first instinct about this was incorrect - it's not how regular non-grouped traces work, and the regular-trace behavior was chosen to optimize the GUI editing experience: if you delete a label, it stays deleted but gets replaced with 4 spaces, so that you still have something to click on to put a new name there later. I think I'd like to tweak this a little - when you delete a label, store it as `''`, but when you're in editable mode display it as 4 spaces (or perhaps even a number of spaces chosen to roughly match the size of other nearby labels?). As is, if you restyle to `name: ''` it's impossible to click and edit the name after that because it has no size to click on.

That means there's no way in the GUI to delete the name and get back to the default - to do that you need to restyle to `name: null` - but I think that's better than some hack like a total delete gives the default, but setting the name as a single space makes it look blank.
