### ISSUE TITLE
rangeslider does not work with histogram

### ISSUE THREAD

**Issue by arlowhite** [plotly/plotly.js#2578]
The range-slider feature does not work with a histogram.
https://plot.ly/javascript/range-slider/

Here's the range-slider demo, converted to a simple histogram:
https://codepen.io/arlowhite/pen/erJrML

rangeslider does not render anything.

**Comment by etpinard** [comment]
Yep, it wasn't working back in 2016. It's working now: https://codepen.io/etpinard/pen/ELPLpM?editors=1010
