### ISSUE TITLE
Support for weights in Histograms / Density plots

### ISSUE THREAD

**Issue by MaxNoe** [plotly/plotly.js#2580]
For several plots, we need histograms to support weights for each observation.

E. g. we have one signal region but 5 regions to estimate background, so in a signal over noise histogram, we need to weight every background event by 0.2.

Is this possible with plotly? If not, would you consider supporting something like

```
data = [x: [1, 2, 3], weights=[1.0, 0.2, 1.0], type='histogram']
Plotly.newPlot(mydiv, data)
```

**Comment by etpinard** [comment]
@MaxNoe I might I have misread you request. I think what you're asking can already be done using `histfunc`. See https://codepen.io/etpinard/pen/qYNxre?editors=0010

**Comment by MaxNoe** [comment]
Can I use a different histfunc for traces of the same plot?

**Comment by MaxNoe** [comment]
mmh. somehow the `xbins` argument seems to be ignored if I start using `histfunc`.

**Comment by MaxNoe** [comment]
Ok, there seems to be a bug when you have two histograms in the same plot, one using histfunc and one not.
