### ISSUE TITLE
Parallel coordinates issue (Uncaught TypeError: Cannot read property 'buffer' of null) is  introduced in Chrome Version 66.0.3359.117

### ISSUE THREAD

**Issue by webbres** [plotly/plotly.js#2582]
I am experiancing an issue with parallel coordinate plots. Issue appeared after update of chrome to 66.0.3359.117, seemed to work fine in 65, works in firefox.

My copy of chrome updated and my angular page displaying a parallel coordinates plot started to fail reporting a 'Cannot read property 'buffer' of null'. The issue is also accuring on the demo page at https://plot.ly/javascript/parallel-coordinates-plot/

Error message:

Uncaught TypeError: Cannot read property 'buffer' of null
    at plotly-latest.min.js:7
    at e.exports (plotly-latest.min.js:7)
    at HTMLCanvasElement.<anonymous> (plotly-latest.min.js:7)
    at plotly-latest.min.js:7
    at ut (plotly-latest.min.js:7)
    at Array.Y.each (plotly-latest.min.js:7)
    at e.exports (plotly-latest.min.js:7)
    at e.exports (plotly-latest.min.js:7)
    at Object.r.plot (plotly-latest.min.js:7)
    at r.drawData (plotly-latest.min.js:7)

Navigating the error a bit it seems to be caused by

                return d = t.buffer({
                    usage: "dynamic",
                    type: "uint8",
                    data: null
                }),

Cheers

Sam

**Comment by etpinard** [comment]
Thanks for the report! 

I suspect this error is fatal as in the `parcoords` trace completely fails to render. @webbres can you confirm?

I don't have access to Chrome 66 at the moment, so I can't confirm. Is anyone else noticing this in Chrome 66?

The call stack seems to point to a `regl` call - which we also use for `scattergl` and `splom` traces. @webbres (or anyone else with Chrome 66) would mind opening

- https://rreusser.github.io/plotly-mock-viewer/#gl2d_12 
- https://rreusser.github.io/plotly-mock-viewer/#splom_0

to see if the same error occurs?

**Comment by webbres** [comment]
@etpinard yes either the entire plot fails to load or the lines are missing but selections can be made on the coordinates. 

I will report back on the remaining questions when I get access to PC again. 

Cheers

Sam

**Comment by webbres** [comment]
Link 1:

Uncaught (in promise) TypeError: Cannot read property 'regl' of null
    at new Scatter (plotly-latest.js:80026)
    at module.exports (plotly-latest.js:79968)
    at Object.plot (plotly-latest.js:177605)
    at plotOne (plotly-latest.js:131617)
    at Object.exports.plot (plotly-latest.js:131585)
    at exports.drawData (plotly-latest.js:125440)
    at Object.lib.syncOrAsync (plotly-latest.js:116132)
    at Object.exports.plot (plotly-latest.js:121078)
    at (index):434


Link 2:

plotly-latest.js:80026 Uncaught (in promise) TypeError: Cannot read property 'regl' of null
    at new Scatter (plotly-latest.js:80026)
    at Scatter (plotly-latest.js:80013)
    at new SPLOM (plotly-latest.js:80941)
    at SPLOM (plotly-latest.js:80930)
    at plotOne (plotly-latest.js:180837)
    at Object.plot (plotly-latest.js:180778)
    at Object.plot (plotly-latest.js:180221)
    at exports.drawData (plotly-latest.js:125440)
    at Object.lib.syncOrAsync (plotly-latest.js:116132)
    at Object.exports.plot (plotly-latest.js:121078)
Scatter @ plotly-latest.js:80026
Scatter @ plotly-latest.js:80013
SPLOM @ plotly-latest.js:80941
SPLOM @ plotly-latest.js:80930
plotOne @ plotly-latest.js:180837
plot @ plotly-latest.js:180778
plot @ plotly-latest.js:180221
exports.drawData @ plotly-latest.js:125440
lib.syncOrAsync @ plotly-latest.js:116132
exports.plot @ plotly-latest.js:121078
(anonymous) @ (index):434
Promise.then (async)
plotMock @ (index):425
plotFromHash @ (index):441
module.exports @ (index):485
2../viewer @ (index):319
s @ (index):34
e @ (index):34
(anonymous) @ (index):34

**Comment by etpinard** [comment]
cc @dy `scattergl`, `splom` and `parcoords` appear broken in Chrome 66.

We should try to find a solution before ASAP.

**Comment by dy** [comment]
Ok that works from my chrome 66 windows 7.
Waiting for other reports.

**Comment by webbres** [comment]
I've just upgraded from one version of 66 to Version 66.0.3359.139 and the issue is resolved on windows 10.

**Comment by etpinard** [comment]
Thanks for the update @webbres 

I'll leave this issue open in case other users hit similar issues with Chrome 66.

**Comment by webbres** [comment]
I can confirm that upgrading the Chrome version on the windows 7 machines experiencing the same issue has also resolved the issue. Seems to have been specific to 66.0.3359.117.

Thanks for the quick response, glad it didn't end up being a hassle.

**Comment by webbres** [comment]
turning off hardware acceleration triggers the issue without remote desktop

**Comment by dy** [comment]
As a sidethought - would be really nice to have regl-parcoords component.

**Comment by etpinard** [comment]
Closing as this issue seem to be resolved in Chrome version released after 66.0.3359.117.

@webbres feel free to open another issue about the problems you're facing in a remote desktop.
