### ISSUE TITLE
SPLOM points not displayed with TypedArrays

### ISSUE THREAD

**Issue by jmmease** [plotly/plotly.js#2585]
I'm not sure if this is a bug report or a feature request, but it seems that the new SPLOM trace type does not support typed arrays as the `values` property of a `dimension` (on version `1.36.1`).

Codepen: https://codepen.io/anon/pen/LmbQdv

```
TESTER = document.getElementById('tester');

Plotly.plot( TESTER,
			  [{
    "type": "splom",
    "dimensions": [{
      "values": new Int32Array([1, 2, 3]),
      //"values": [1, 2, 3],
      "label": "A"
    }, {
      "values": new Int32Array([2, 5, 6]),
 	   //"values": [2, 5, 6],
      "label": "B"
    }]
  }]);
```
When I run this in Chrome (*65.0.3325.181 (Official Build) (64-bit)*) I see the axes displayed but no data points.  I also get the following warning in the chrome developer console:

```
[.Offscreen-For-WebGL-0x7fdce8449c00]GL ERROR :GL_INVALID_OPERATION : glDrawArrays: attempt to access out of range vertices in attribute 3
```

If the `Int32Array`s are replaced by standard arrays then the points display as I would expect.

**Comment by etpinard** [comment]
Waiting on a reply in https://github.com/dy/regl-splom/issues/7

**Comment by etpinard** [comment]
Fixed by https://github.com/plotly/plotly.js/pull/2593
