### ISSUE TITLE
Spike line shifted in Firefox

### ISSUE THREAD

**Issue by sunqingsong** [plotly/plotly.js#2588]
The spike lines don't work correctly in Firefox when setting to spikesnap: 'cursor'.
The example below works well in Chrome or IE, but in Firefox the spike lines are shifted.

https://codepen.io/sunqingsong/pen/RyoBjp

**Comment by alexcjohnson** [comment]
Thanks @sunqingsong - actually it looks like in Chrome there's a tiny offset sometimes too... but FF is way off.
