### ISSUE TITLE
Unnecessary clipPaths

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#2595]
Potential 🐎 issue with many-subplot graphs: seems like we’re making `clipPath.axesclip` for every possible combination of axes… even though `clipPath.plotclip` only gets the subplots we use. Dunno if maybe shapes can require other combinations? In any event we should be able to be more discriminating in which of these we make.
![screen shot 2018-05-01 at 9 23 45 am](https://user-images.githubusercontent.com/2678795/39475821-dbdf6576-4d27-11e8-97a2-1606fc094b5e.png)

**Comment by etpinard** [comment]
These "unnecessary" clip paths are added to the DOM in `Axes.makeClipPaths` 

https://github.com/plotly/plotly.js/blob/a132b85b899dd490216d12823be56ad3861f091f/src/plots/cartesian/axes.js#L1457-L1495

Some benchmarks using https://codepen.io/etpinard/pen/wjmqmO:, at 50 dimensions, `Axes.makeClipPaths` takes around ~50ms, at 20 dimensions we're down to ~8ms - which is non-negligeable but not a major perf hit. Note that `makeClipPaths` is only called during the `lsInner` subroutines which is skipped notably during "axrange" and "modebar" editTypes.

That said, as far as I can tell, these per-axes clip paths are only used for shapes and layout images. So, we could easily skip `Axes.makeClipPaths` when the `_hasOnlyLargeSplom` flag

https://github.com/plotly/plotly.js/blob/a132b85b899dd490216d12823be56ad3861f091f/src/plots/plots.js#L431-L440

is turned on. Alternatively, we could call `Axes.makeClipPaths` only when there are visible shapes or layout images on the graph. This could make some relayout logic trickier though.

**Comment by alexcjohnson** [comment]
Good to know, thanks for benchmarking it. Sounds like adding a `_hasOnlyLargeSplom` switch is a no-brainer.

Down the line though we should be able to do even better by only making the ones we need period, by building up the required list during `supplyDefaults` and using that during `makeClipPaths` instead of the maximal list we generate there now. Changing axis references for shapes is already `editType: 'calc'`, we could do that with images as well (I don't see much reason to make those operations fast, if we ever autorange images #1111 we'd probably need to do that anyway), that seems like it would solve the `relayout` concerns.

**Comment by etpinard** [comment]
> Sounds like adding a _hasOnlyLargeSplom switch is a no-brainer.

Done in https://github.com/plotly/plotly.js/pull/2628

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
