### ISSUE TITLE
'plotly_click' event only usbale via  jQuery ?

### ISSUE THREAD

**Issue by napengam** [plotly/plotly.js#26]
You say:

>>No jQuery. jQuery has been removed from plotly.js for significantly better performance and improved >>browser compatibility.

This is probably true, however it looks like the plotly_click event canonly be used using jQuery
$('idj),on() or $('id').bind().

I can't get it to work using plain obj.addEventHandler('plotly.click',func,...) .

**Comment by Vestaxis** [comment]
See #21

**Comment by napengam** [comment]
thanks

**Comment by prasadrajacse** [comment]
I am trying to use it angular 2 project but it is returning the error
Property 'on' does not exist on type 'HTMLElement'.

let myPlot = document.getElementById('donutChartHigh');
myPlot.on('plotly_click', function(data){
console.log(data.points[0].label);
});

**Comment by etpinard** [comment]
@prasadrajacse that `myPlot.on` statement must be placed **after** the first `Plotly.plot` call.

**Comment by prasadrajacse** [comment]
Hi @etpinard  thanks for the response

Here is my code block..I am calling myPlot.on after Plotly.newPlot

      this.constructPlotData();
      this.plotHeading = this.donutInput.plotHeading;
      this.plotContainerId = this.donutInput.containerId;
      setTimeout( () => {
        Plotly.newPlot(this.plotContainerId, this.plotdata, this.ploylayout,{displayModeBar: false});
        let myPlot = document.getElementById(this.plotContainerId);
        myPlot.on('plotly_click', function(data){
          console.log(data.points[0].label);
        });
      },1);

**Comment by jeyasarathi** [comment]
Think it is more of a compilation error. But your code will work. If you are concerned on the error. You can create a child class for ES6 HTMLElement class. Add the below code above in your component.

    class CustomHTMLElement extends HTMLElement {
      constructor() {
        super();
      }
      on(event_type, cb) {
      }
    }

And type cast in element selection 

`let myPlot =  <CustomHTMLElement>document.getElementById(this.plotContainerId);`

**Comment by amansatija** [comment]
@jeyasarathi 
your solution caused the compilation error to away how ever the events still didn't fire 
note i m firing events one after the other by setting setTimeout from with in a forloop
