### ISSUE TITLE
Text align when hover on scatterplot

### ISSUE THREAD

**Issue by ifll** [plotly/plotly.js#260]
When hovering on a scatter plot two options are available for the displayed box if no fixed box is defined:
- box appears on the left part of the point
- box appears on the right part of the point

When box appears on the left part of the point the text is aligned on the right part, and viceversa.

Is there any way to control this and decide which align is desired? (It is mainly to control layout and styling the plot)

**Comment by ifll** [comment]
Is there also any way to selectively style the text?

Something which make the text inside the box look like this:

[ **Infotag:** Description text ]

**Comment by alexnum** [comment]
+1

**Comment by brianstamper** [comment]
+1
Any news on this? I just found this issue after having written up an SO question here: https://stackoverflow.com/questions/50003531/r-plotly-hover-label-text-alignment

**Comment by zig1000** [comment]
+1
Having half the multi-line text in a plot be formatted incorrectly is very unaesthetic.

In fact in addition to having it be settable, I think left-align should be plotly's default for all hovertext, regardless of where the mouseover box is positioned relative to the data point.

**Comment by etpinard** [comment]
Closed by https://github.com/plotly/plotly.js/pull/3753
