### ISSUE TITLE
Categorical ticks and gridlines halfway between category labels

### ISSUE THREAD

**Issue by yangmqglobe** [plotly/plotly.js#2601]
When use categorical axis, the grid still drew in the middle of a category which you can find in [here](https://codepen.io/anon/pen/erWLjw). By the way, the [striped-rows](http://getbootstrap.com/docs/4.1/content/tables/#striped-rows) style would be great for this situation(Yes, it is a table, but it can be used in plots right?).

**Comment by alexcjohnson** [comment]
Good point, ticks and gridlines halfway between the category labels is often better than aligned with the labels, as they are for numeric or date axes. Not always, for example label-aligned may be better for scatter/bubble plots. Also I'm not sure what the right behavior is when categories get too dense and we can't show them all...

Striped rows is interesting, I see a few examples of it elsewhere, like [here](https://canvasjs.com/docs/charts/basics-of-creating-html5-chart/tick-marks-grid-lines-and-interlaced-colors/) - it's not an effect I'd use myself, I think it makes interpreting the data harder. But we'd entertain a PR to add it 😄

**Comment by yangmqglobe** [comment]
em...My idea is not striped rows but striped columns, so the two adjacent category can distinguish easily, this will highly affect the group boxplot, group violin plot, etc.

**Comment by alexcjohnson** [comment]
> striped rows but striped columns, so the two adjacent category can distinguish easily

Nice, I'd call that the same feature (just applied to the x axis instead of y) but that does seem like a more useful application of it. Note that if you zoom out in your example you can see the issue I was worried about, when categories get too dense and the stripes (and/or ticks/lines) get put in what's suddenly a weird place:
![screen shot 2018-05-03 at 10 02 50 am](https://user-images.githubusercontent.com/2678795/39581280-31ecc368-4eb9-11e8-8724-770013401d8c.png)

> Another advance would be the category region hover highlight

interesting, kind of a generalization of the idea of spikelines https://github.com/plotly/plotly.js/pull/1461 - perhaps this could fit into that framework.

**Comment by yangmqglobe** [comment]
In my opinion, for the dense data, user/developer should change their design like zoom their axis or change the plot type like this one
![image](https://user-images.githubusercontent.com/17685088/39611379-d05f2fc8-4f1c-11e8-8738-58a3630f0e31.png)
When there are too much bar, then you should use polar coordinates, so I think the stripe style should be an option weather for xaxis or yaxis, but the user/develop should consider is it fix for their work.

**Comment by nicolaskruchten** [comment]
Basically here we just want a new `ticksbetweenlabels` boolean to start right?

**Comment by nicolaskruchten** [comment]
I think what you propose makes sense but for now I would just get a flag that works for categorical axes :)

**Comment by alexcjohnson** [comment]
> for now I would just get a flag that works for categorical axes 

Hence my comment:

> which I realize we need not support now, just want to ensure our solution will extend

As I was thinking it through, I initially thought a different approach would be needed for dates, in which case for consistency we'd have wanted to change categories too. But in the end I believe ^^ (with whatever terminology we settle on) will work for both cases 🎉
