### ISSUE TITLE
Hoverformat fails to apply when showticklabels=False

### ISSUE THREAD

**Issue by yankev** [plotly/plotly.js#261]
This is in reference to the following issue in the Plotly Python API: 
[Issue 398](https://github.com/plotly/plotly.py/issues/398)

Unless `showticklabels = True` then the hoverformat is not applied. 
For example in the following code:

```
from plotly.graph_objs import Scatter, Layout, YAxis, Figure
import plotly.plotly as py

data = [Scatter(x=[1, 2, 3],
                 y=[0.12345, 0.23456, 0.34567])]
layout = Layout(yaxis=YAxis(showticklabels=False,
                            hoverformat=",.2r",))
figure = Figure(data=data, layout=layout)
py.iplot(figure)
```
[Plot generated from the code](http://codepen.io/etpinard/pen/jWRzrR)

The associated yaxis portion of the json is
```
yaxis:{
  hoverformat:",.2r",
  showticklabels:false,
  type:"linear",
  range:[
             -0.2711700793681046,
              0.7894967832778617
             ],
  autorange:false
}
```
and so it appears to have translated correctly from the python plot function call.

**Comment by mdtusz** [comment]
Confirmed (unless @etpinard knows some reason why not). Thanks for reporting it. 

Aside: For markdown links, the structure is \[name of link\]\(url\). Looks like you may have gotten it mixed up :wink:

**Comment by etpinard** [comment]
@yankev even better: use this [template](http://codepen.io/etpinard/pen/jWRzrR) to show the bug in a codepen

**Comment by yankev** [comment]
@mdtusz Haha yeah.
@etpinard Oh ok, I'll just adjust the link to the one you made this time.

**Comment by etpinard** [comment]
Here's the problematic block: https://github.com/plotly/plotly.js/blob/master/src/plots/cartesian/tick_defaults.js#L33-L54

We only coerce `hoverformat` when `showticklabels` is true --- which is a little too crude.

Arguably, the logic for `tickprefix` and `ticksuffix` is wrong too. We should coerce them even in the case where `showticklabels` is false.
