### ISSUE TITLE
Orthographic projection for 3D plots

### ISSUE THREAD

**Issue by emimoun** [plotly/plotly.js#2611]
Hello,

I would like to know if 'orthographic' projection could be added as an option to plotly 3D plots.
Indeed, this option is available in [Matlab](https://fr.mathworks.com/help/matlab/ref/camproj.html), and in [matplotlib ](https://matplotlib.org/users/prev_whats_new/whats_new_2.1.0.html#orthographic-projection-for-mplot3d) since version 2.1.

![image](https://user-images.githubusercontent.com/38953797/39583939-833dca54-4ef1-11e8-8695-dcf0773ff129.png)

As explained [here](https://fr.mathworks.com/help/matlab/visualize/understanding-view-projections.html), such a projection maintains parallelism and distances, and is therefore sometimes better suited when plotting data. For example, a camera looking along the z axis (top view) would directly give you a perfect xy plane projection, which it does not do on Plotly right now,
 as can be seen on that [example](https://plot.ly/javascript/3d-axes/#camera-controls).

**Comment by alexcjohnson** [comment]
Seems reasonable - @dy is this just a matter of exposing the [`fovy` option](https://github.com/gl-vis/gl-plot3d/blob/master/scene.js#L164) to `gl-plot3d` and setting it to what, 0, or something sufficiently tiny?

**Comment by emimoun** [comment]
Actually, I did try it just to see if it would work, and it does for the plot itself, but for some reason the axis labels were then appearing very far from the axes. I did not dig further for the reason why, and maybe I did it wrong, though.

**Comment by marcotama** [comment]
I would love to see this feature!

**Comment by jonaraphael** [comment]
Please add!

**Comment by erickee** [comment]
Can the priority of this be raised? It is a serious issue for reading certain types of technical plots.
