### ISSUE TITLE
yaxis/xaxis position attribute does not do anything when using heatmap

### ISSUE THREAD

**Issue by gajus** [plotly/plotly.js#2613]
```js
Plotly.newPlot(
  'graph',
  [
    {
      colorscale: 'YIOrRd',
      hoverinfo: 'text',
      reversescale: true,
      type: 'heatmap',
      z: [[1, 20, 30], [20, 1, 60], [30, 60, 1]]
    }
  ],
  {
    showlegend: false,
    xaxis: {
      title: 'Year',
      titlefont: {
        size: 16
      }
    },
    yaxis: {
    	anchor: 'free',
    	position: -100,
        title: 'Unemployed',
        titlefont: {
          size: 16
        }
    },
    margin: {
      l: 200,
      r: 50,
      b: 50,
      t: 50
    }
  },
  {
    displayModeBar: false,
    staticPlot: true
  }
);

```

https://jsfiddle.net/dzvx2838/

I have tried adjusting values:

```js
anchor: 'free',
position: -100,

```

but it has no effect to the position of the yaxis title.

What I would like to achieve is to make the yaxis title stick to the left-most position as I increase the left-margin.

**Comment by alexcjohnson** [comment]
Currently `position` is limited to [between 0 and 1](https://github.com/plotly/plotly.js/blob/7acca0abb3ae226c458ce29b3dabdd1c1e3c460a/src/plots/cartesian/layout_attributes.js#L709-L710). I suppose we could expand that range (some other items that use paper-referenced positioning do allow [a wider range](https://github.com/plotly/plotly.js/blob/7acca0abb3ae226c458ce29b3dabdd1c1e3c460a/src/components/legend/attributes.js#L83-L84)). Notice though that this positioning is fractional, not pixels, so if your plot size changes the position will change as well. So I'd be a little worried about axes disappearing unexpectedly if we allow this.

Can you accomplish this with `xaxis.domain` instead? https://jsfiddle.net/9wegmbsc/

**Comment by alexcjohnson** [comment]
I'm going to assume `xaxis.domain` is sufficient to cover this use case without a potentially confusing change in behavior. @gajus if I'm missing something feel free to chime back in.

**Comment by gajus** [comment]
> I'm going to assume xaxis.domain is sufficient to cover this use case without a potentially confusing change in behavior.

It is not because it moves the entire axis as well...

Either way. Since we are using Plotly just for MVP, I chose to ignore the issue.
