### ISSUE TITLE
mathjax doesn't render for firefox

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.js#2616]
![image](https://user-images.githubusercontent.com/1280389/39651988-00d64e0a-4fba-11e8-8da8-516eaebc2cac.png)

originally reported in https://github.com/plotly/streambed/issues/2674, reported again in https://github.com/plotly/dash-core-components/pull/194

**Comment by alexcjohnson** [comment]
Huh, if you open http://localhost:3000/devtools/test_dashboard/#mathjax in FF it looks like the *only* place it works is in annotations, and not even all of those. Interestingly that mock doesn't put any MathJax into the legend, can't recall why, perhaps I had a problem with it in the image server? But yeah, on Chrome it works in the legend.

This is probably a `getBoundingClientRect` issue, you can see at least one of the missing labels peeking in from the left edge, the others are probably drawn somewhere but completely clipped.

In FF:
<img width="818" alt="screen shot 2018-05-07 at 9 52 17 am" src="https://user-images.githubusercontent.com/2678795/39705429-607c5f92-51dc-11e8-88ab-f4ed859c0530.png">

In Chrome:
<img width="804" alt="screen shot 2018-05-07 at 9 55 08 am" src="https://user-images.githubusercontent.com/2678795/39705560-c87e7846-51dc-11e8-9314-666b767eb39d.png">

**Comment by ibell** [comment]
I can confirm with latest.  Here is an example that does not render properly:
``` html
<meta charset="UTF-8"> 
<head>
  <script type="text/javascript" async
    src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML">
  </script>
  <script> window.PlotlyConfig = {MathJaxConfig: 'local'} </script>
  <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
</head>
<body>
  <div id="myDiv"><!-- Plotly chart will be drawn inside this DIV --></div>
  <script>
    var trace1 = {
      x: [.01, .1, 1, 10, 100], 
      y: [1000, 500, 250, 125, 62.5], 
      type: 'scatter'
    };
    var data = [trace1];
    var layout = {
      xaxis: {
        title: '$c$',
      }, 
      yaxis: {
        title: '$a^2+b^2$',
      }
    };
    Plotly.plot('myDiv', data, layout);
  </script>
</body>
```

**Comment by antoinerg** [comment]
Updating MathJax from its `2.3.1` version to the latest `2.7.5` yields:
![Screenshot_2019-04-16_21-15-49](https://user-images.githubusercontent.com/301546/56254000-e24e9700-608c-11e9-973c-3b2f5f0e84c2.png)

We are still missing titles, but the `bar` chart is much better. I will need to investigate why exactly the titles are not displayed in FF.

To be continued!

**Comment by antoinerg** [comment]
The probl

> This is probably a `getBoundingClientRect` issue, you can see at least one of the missing labels peeking in from the left edge, the others are probably drawn somewhere but completely clipped.

As @alexcjohnson pointed, it is indeed a `getBoundingClientRect` issue. Basically, we need to patch this function:
https://github.com/plotly/plotly.js/blob/172c3e6e6691b0fff362cbe55d32124c6130ef9f/src/lib/svg_text_utils.js#L22-L24
