### ISSUE TITLE
mesh3d: handle messy data

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#2630]
Currently `mesh3d` does an [in-place modification](https://github.com/plotly/plotly.js/blob/a132b85b899dd490216d12823be56ad3861f091f/src/traces/mesh3d/defaults.js#L47) of the input data during `supplyDefaults`, noticed in the course of https://github.com/plotly/plotly.js/pull/2629. We should not be modifying the user data, rather making a new cleaned array, and we shouldn't be doing any of this in `supplyDefaults` either. Also in other places (like sankey) we reject non-integers rather than truncating, we should do that here too. This probably indicates there is other strange behavior there with messy data as well.

**Comment by etpinard** [comment]
cc @archmoj who discovered some of the same oddities during his isosurface work.
