### ISSUE TITLE
Violin Span Calculation Issue

### ISSUE THREAD

**Issue by kmui2** [plotly/plotly.js#2631]
Regarding this line of code in plotly.js: https://github.com/plotly/plotly.js/blob/9d6144304308fc3007f0facf2535d38ea3e9b26c/src/traces/violin/calc.js#L51

Why is taking the minimum (`Math.min(bandwidthDflt, bandwidth)`) needed here? Should it just not take the min and use only `bandwidth`? I can see a problem where I defined `trace.bandwidth` and don't want to use `bandwidthDflt`.

**Comment by etpinard** [comment]
See -> https://github.com/plotly/plotly.js/pull/2552#discussion_r181206232
