### ISSUE TITLE
Allow axis to be displayed under multiple linked subplots

### ISSUE THREAD

**Issue by slishak** [plotly/plotly.js#2637]
I have a long column of subplots, and I'd like to have the x axes of these linked. However, if I do this the axis is only displayed under the bottom subplot, which you sometimes have to scroll to the bottom of the plot to see. It would be nice to have an option to repeat the axis scale on each linked subplot.

**Comment by alexcjohnson** [comment]
Matching axes #1549 would be one way to address this. But it would be much more user-friendly to just provide the flexibility to display labels in several places. Maybe you want labels both on top and bottom of a tall single plot, for example.

**Comment by slishak** [comment]
Agree, there have also been cases where I've wanted to repeat an axis on the left/right and top/bottom of a plot. 

In fact I didn't see that issue, I think this one is a duplicate of https://github.com/plotly/plotly.js/issues/2539 which was referenced in #1549. No problem if you want to close this one in favour of that.
