### ISSUE TITLE
Spike lines still shown after enable/disable in modebar

### ISSUE THREAD

**Issue by slishak** [plotly/plotly.js#2640]
I have a load of Scatter subplots, with spike lines disabled by default. If I enable spike lines from the modebar, I get x and y spike lines. If I disable it again, the x spike lines go away but the y spikes can't be removed.

**Comment by alexcjohnson** [comment]
I don't see that happening - can you post a codepen showing the problem? Thanks!

**Comment by slishak** [comment]
Sorry you're right, I thought it was happening all the time for me but it's actually not. I'll work on trying to reproduce it. No idea yet...

**Comment by slishak** [comment]
Can't reproduce it unfortunately. I have a Dash app that creates a big grid of subplots. The bug happens when I click and unclick the spike lines from there, but if inside my plot callback I save the figure as an html file, when I open it outside Dash everything is fine.

I get the following message in the Chrome console when running it from Dash when I click the button, which doesn't happen from the html file:
`[Violation] 'click' handler took 178ms`

**Comment by slishak** [comment]
I have a grid of axes which have linked y axes across rows. The axes are named `xaxis, xaxis2, xaxis3, xaxis4, ...` and `yaxis, yaxis2, yaxis3, yaxis4, ...`. After enabling spike lines, the `showspikes` property is `true` on all x and y axes, and the spikes correctly appear. After disabling, `xaxis` and `yaxis` have `showspikes` set to `false` but all of the numbered axes still have it set to `true`. The behaviour of the plot matches this - the top left plot (`xaxis`, `yaxis`) has no spike lines, but the rest of the top row (`xaxis{1-4}`, `yaxis`) have vertical spike lines on the x axis, and all the remaining rows (`xaxis{5-n}`, `yaxis{2-n}`) have spike lines on both axes.

The figure was created from Python using `plotly.tools.make_subplots`.

**Comment by slishak** [comment]
OK, I'll try that out later. Do you not think it's something specific to Dash, because I couldn't reproduce by saving the figure as html?

**Comment by alexcjohnson** [comment]
It's certainly possible Dash plays a role here, yes - in which case to really debug it we'd need to get this running on some publicly accessible Dash app. I'm more than a little puzzled by how Dash could alter what's happening inside the plotly.js button click, that's why I want to be very sure it's not a pure plotly.js bug before we go that route.

**Comment by slishak** [comment]
I'm having difficulty saving the CodePen (maybe it's too big? the json is about 30000 lines), but I can confirm that the issue did not appear in the browser. So far I've only seen it inside Dash.

**Comment by alexcjohnson** [comment]
OK, thanks for testing that. Sounds like we really do have to debug this inside Dash. I'm really not sure the best way to do that, so perhaps you can open an issue over at https://github.com/plotly/dash-core-components? Feel free to @ mention me and @chriddyp and link to this issue (which I'll leave open until we figure out where the problem really is).

**Comment by etpinard** [comment]
Closed due to lack of activity.
