### ISSUE TITLE
Three-variable hover labels should adapt to supplied axis titles

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#265]
As described in http://stackoverflow.com/questions/35467316/rename-axes-in-plotly-3d-hover-text

**Comment by fixxxr** [comment]
Hi there, 

is this enhancement available for plotly.js? If yes where I can find a usage example?

thanks in advance

**Comment by ischurov** [comment]
@fixxxr, no it is not yet implemented (otherwise this bug would have status 'closed', but it's 'open').

**Comment by fixxxr** [comment]
I saw that but since the label was added 17 days ago I thought It was already implemented

thanks for the quick answer

**Comment by etpinard** [comment]
@fixxxr labels are described in the [contributing guidelines](https://github.com/plotly/plotly.js/blob/master/CONTRIBUTING.md#issue-labels).

**Comment by etpinard** [comment]
Merging into https://github.com/plotly/plotly.js/issues/2618
