### ISSUE TITLE
Line that should render on x axis rendered above it

### ISSUE THREAD

**Issue by jonwedell** [plotly/plotly.js#2664]
When plotting a line chart with several points at (x,0) the interpolated line between them renders above the X axis line for certain data sets.

You can view an example [here](https://jsfiddle.net/bh0etd08/). Zoom in such that your x window is roughly 2 to 1 and your y window is -0.04 to .06. As you continue to zoom you will see the incorrect line, even though the only points in that portion of the chart are: (-1,0) and (3.214112,0).

![newplot](https://user-images.githubusercontent.com/5184895/40513899-c7bc634e-5f6c-11e8-9deb-7fec485e914a.png)

Thanks,
Jon

**Comment by alexcjohnson** [comment]
Confirmed, thanks for the report @jonwedell !
