### ISSUE TITLE
Selection vs Pan double-click bug

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#2667]
The following sequence exposes what looks like a bug:

1. Render a plot with https://codepen.io/nicolaskruchten/pen/QrXYbJ for the color settings
2. Click on the box-select tool
3. Select a point
4. Click on the pan tool
5. Pan
6. Double-click on the plot
7. For me this resets the selection and not the pan.

**Comment by alexcjohnson** [comment]
you can even omit 5. Pan

**Comment by etpinard** [comment]
Ok. On it.

**Comment by etpinard** [comment]
Bug introduced in 1.36.0. Working fine in 1.35.2: https://codepen.io/etpinard/pen/aGgXjJ?editors=1010
