### ISSUE TITLE
Legend symbol changed to default when trace is disabled in legend

### ISSUE THREAD

**Issue by collioud** [plotly/plotly.js#2672]
Hello,

If the trace symbols are specified as an array with the same symbol (ex: 'square), when disabling the trace in the legend, the symbol changes from 'square' to the default one ('round'). 

You can see this in this [codepen](https://codepen.io/anon/pen/gKYMbd?editors=0010)

Cheers,
Arnaud

**Comment by etpinard** [comment]
Thanks for the report.
