### ISSUE TITLE
Radar Chart

### ISSUE THREAD

**Issue by amitnkukanur** [plotly/plotly.js#2673]
Hi All,

I believe this is solved long time ago, but still i am finding difficult to set color in Radar Chart.
For Example: The colors Blue and Orange are predefined, can i change colors to be more specific in nature.
Am working on Plotly Javascript.

 `data = [
  {
  type: 'scatterpolar',
  r: [39, 28, 8, 7, 28, 39],
  theta: ['A','B','C', 'D', 'E', 'A'],
  fill: 'toself',
  name: 'Group A'
  },
  {
  type: 'scatterpolar',
  r: [1.5, 10, 39, 31, 15, 1.5],
  theta: ['A','B','C', 'D', 'E', 'A'],
  fill: 'toself',
  name: 'Group B'
  }
]

layout = {
  polar: {
    radialaxis: {
      visible: true,
      range: [0, 50]
    }
  }
}

Plotly.plot("myDiv", data, layout)`

Am using the one mentioned in site, where do i get coloring option?

Please suggest.

Rgds,
Amit

**Comment by etpinard** [comment]
See https://plot.ly/javascript/reference/#scatterpolar-line-color

and please ask questions of the likes on https://community.plot.ly/c/plotly-js in the future, so that other users can benefit from our answer. Thanks.
