### ISSUE TITLE
Horizontal stacked bar chart drifting along the y axis 

### ISSUE THREAD

**Issue by baaron4** [plotly/plotly.js#2675]
Stripped down example. https://codepen.io/anon/pen/GGKYdM

*Note JS is generated with C#

The bar chart should be all at the same level on the y-axis. Like a representation of actions as time goes on. The Y axis shouldnt mean anything. All the data has y-axis set to 1.5 yet for every example Ive parsed it wants to drift from below 1.5 to above it by the same amount. Even with thousands of bars in the data. Is it intentional that setting base each time effects it on both axis?

**Comment by alexcjohnson** [comment]
@baaron4 closing as I don't see any action items here - other than potentially improving the docs to highlight the default `barmode`? Feel free to comment if I'm missing something though and we can reopen.
