### ISSUE TITLE
Option cliponaxis incompatible with axis rangemode tozero

### ISSUE THREAD

**Issue by collioud** [plotly/plotly.js#2679]
Hello,

I just noticed that the layout option 'cliponaxis' + axis option 'below traces' in incompatible with the axis option rangemode: 'tozero' or 'nonnegative'.

See [this codepen](https://codepen.io/anon/pen/gKOpbL?editors=0010)

Is this the desired behavior? How should I proceed to have the benefit of the 'tozero' option without clipping the markers?

Thanks!

**Comment by etpinard** [comment]
I think I got it to work: https://codepen.io/etpinard/pen/KeKaMj?editors=0010

`cliponaxis` is a trace attribute and accepts only booleans true/false.

**Comment by collioud** [comment]
Oohhh, I thought that was a global layout option...I got it now.
Thank you Etienne for your kind help!
