### ISSUE TITLE
Continuously zooming in starts throwing errors at some point

### ISSUE THREAD

**Issue by GlennMatthys** [plotly/plotly.js#2680]
Example: https://jsfiddle.net/0rxsx2f9/1/

When continuously zooming in, at some point this error is thrown on the console:
`plotly-latest.js:117495 Uncaught RangeError: toFixed() digits argument must be between 0 and 100`

It doesn't happen all the time. Usually between 10 to 20 zooms the error starts occurring, I haven't been able to pin down the exact conditions. Once the error occurs, zoom behavior becomes erratic until you reset the graph.

![plotly-zoom](https://user-images.githubusercontent.com/31989842/40660507-7658dada-6351-11e8-9a9d-f02c6d499af0.gif)

Full trace:
```
plotly-latest.js:117495 Uncaught RangeError: toFixed() digits argument must be between 0 and 100
    at Number.toFixed (<anonymous>)
    at formatTime (plotly-latest.js:117495)
    at Object.exports.formatDate (plotly-latest.js:117532)
    at formatDate (plotly-latest.js:130858)
    at Object.axes.tickText (plotly-latest.js:130789)
    at Object.calcTicks (plotly-latest.js:130404)
    at Object.axes.doTicksSingle (plotly-latest.js:131423)
    at plotly-latest.js:131377
    at Object.lib.syncOrAsync (plotly-latest.js:119125)
    at Object.axes.doTicks (plotly-latest.js:131373)
formatTime @ plotly-latest.js:117495
exports.formatDate @ plotly-latest.js:117532
formatDate @ plotly-latest.js:130858
axes.tickText @ plotly-latest.js:130789
calcTicks @ plotly-latest.js:130404
axes.doTicksSingle @ plotly-latest.js:131423
(anonymous) @ plotly-latest.js:131377
lib.syncOrAsync @ plotly-latest.js:119125
axes.doTicks @ plotly-latest.js:131373
exports.doTicksRelayout @ plotly-latest.js:128394
(anonymous) @ plotly-latest.js:125381
lib.syncOrAsync @ plotly-latest.js:119125
relayout @ plotly-latest.js:125400
exports.call @ plotly-latest.js:153116
(anonymous) @ plotly-latest.js:133760
lib.syncOrAsync @ plotly-latest.js:119125
dragTail @ plotly-latest.js:133758
zoomDone @ plotly-latest.js:133434
onDone @ plotly-latest.js:102144
```

**Comment by etpinard** [comment]
Thanks for the report.

To help us out a little bit more:

- could you tell us what browser you are using?
- In your fiddle, could you run

```js
const div = document.getElementById('graph');
console.log(div.layout.xaxis.range)
```

after you first start noticing the error message? This will us how small the x-axis range needs to be to notice this bug.

Thank you very much.

**Comment by GlennMatthys** [comment]
> could you tell us what browser you are using?

Google Chrome Version 66.0.3359.181 (Official Build) (64-bit) on Windows 10 1803

> In your fiddle, could you run ...

[Updated fiddle](https://jsfiddle.net/0rxsx2f9/2/): The error started occuring at this X axis range: ["1970-01-01 01:00:01.2784", "1970-01-01 01:00:01.2785"]

![image](https://user-images.githubusercontent.com/31989842/40670005-9fa4bb9a-6368-11e8-8070-9b55dc0b401e.png)

**Comment by etpinard** [comment]
Thanks very much @GlennMatthys 

There's no need to _zoom in_ to notice the bug, setting `xaxis.range` to that value gives spits an error as well: https://jsfiddle.net/0rxsx2f9/4/

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
