### ISSUE TITLE
Is there any way to add text note on plots?

### ISSUE THREAD

**Issue by yangmqglobe** [plotly/plotly.js#2690]
![image](https://user-images.githubusercontent.com/17685088/40877202-62ab56ae-6642-11e8-9574-82b7d1297f77.png)
As you can see in this picture, I want to add the things like p-value  on the plot, is there any way to achieve this?

**Comment by alexcjohnson** [comment]
You want https://plot.ly/javascript/reference/#layout-annotations

This kind of question is more appropriate for https://community.plot.ly/c/plotly-js
