### ISSUE TITLE
Add missing user aliases on Open Hub (so stats are properly compiled)

### ISSUE THREAD

**Issue by marclaporte** [plotly/plotly.js#2692]
Please see: https://www.openhub.net/p/plotly_js/aliases

I added a few obvious ones but I don't know the community well enough to do them all confidently.

The result will be accurate stats at: https://www.openhub.net/p/plotly_js

Thanks!

**Comment by alexcjohnson** [comment]
Looks like you got a good bunch (I assume these came from https://github.com/plotly/plotly.js/graphs/contributors?), there are a few more at https://github.com/plotly/plotly.js#creators

BTW if you'd like a charting library with a more *open* license to use on *Open Hub* I can recommend one 😉

**Comment by marclaporte** [comment]
I passed on the suggestion :-)

I got some but there are many others to check. Ex.:

Brent
Brent Dearth

Andrew
Andrew Seier

And some obvious ones:
BRONSOLO
bronsolo

**Comment by marclaporte** [comment]
I suggest to join: https://www.openhub.net/p/plotly_js/users

**Comment by etpinard** [comment]
This ticket appears to be resolved. Closing.
