### ISSUE TITLE
Strange scatter3d hovertext when text is a string

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#2693]
https://codepen.io/cpsievert/pen/aKZbGR

Note that this behavior is inconsistent with the `scatter`/`scattergl` equivalent

https://codepen.io/cpsievert/pen/dKXyqB

**Comment by alexcjohnson** [comment]
haha I guess we don't look for a constant `text` attribute, we just see something truthy and assume it's an array. Thanks for the report @cpsievert
