### ISSUE TITLE
Include valid config attributes with plot schema

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#2703]
It would help me throw informative errors/warnings in the R package.

**Comment by etpinard** [comment]
Good call. I tried that once (in https://github.com/plotly/plotly.js/pull/1188), but was a little too ambitious with that PR.

**Comment by etpinard** [comment]
could be a great community contribution.

**Comment by jonmmease** [comment]
This would also be helpful for plotly.py.  We've fallen behind the valid list of config options a couple of times now. e.g. https://github.com/plotly/plotly.py/issues/1290
