### ISSUE TITLE
Why there is a Empty Space is occured between class "js-plotly-plot" and "bglayer" and how to fill it?

### ISSUE THREAD

**Issue by santoshgoswami2017** [plotly/plotly.js#2708]
![plotly](https://user-images.githubusercontent.com/28086924/41094025-7469b6fc-6a6a-11e8-8abe-22fdf68b0645.png)

**Comment by etpinard** [comment]
We call that empty space a _margin_.

You can tweak the margin amount using https://plot.ly/javascript/reference/#layout-margin

Please use https://community.plot.ly/c/plotly-js for questions of the likes in the future.
