### ISSUE TITLE
Null data points on categorical axes should be ignored

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#271]
See http://codepen.io/etpinard/pen/wMLEoO

At the moment, `null` data points on numerical axes are ignored whenever `connectgaps` is set to false. But, axes with `type` set to `category` stringify the `null` values as categories.

**Comment by mdtusz** [comment]
The same behaviour is there when using `undefined` - should we only be checking for `null` to leave a category gap, or do we want `undefined` to be excluded as well?

**Comment by etpinard** [comment]
We should exclude `undefined` values as well
