### ISSUE TITLE
Surface plots do not quite follow the data

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#2713]
See https://codepen.io/alexcjohnson/pen/gKLBgR?editors=0010
![screen shot 2018-06-08 at 5 00 44 pm](https://user-images.githubusercontent.com/2678795/41180724-1f444d1c-6b3d-11e8-939e-4ff73e4ab0d9.png)

I was trying to get the contour lines to exactly match the data, but notice that the line at `y=1.3` (last black line in the red) is not quite straight (even though the data at `y=1.3` is uniformly `1.0`) and the line at `y=1.4` (first black line in the green) does not quite reach the correct value of `0.898` like its neighbors at larger `y` do. Digging in a bit deeper, it seems like the contours are following the surface very closely - perhaps not precisely, there are still a few spots where they seem to disappear behind the surface, but it's pretty close. But the surface itself seems to disagree a little bit with the data, which you can see by zooming in near one of these corners:
![screen shot 2018-06-08 at 2 47 27 pm](https://user-images.githubusercontent.com/2678795/41180914-ddea1210-6b3d-11e8-877f-5cf711c68a54.png)
It looks like either a) the surface is smoothing a little bit around these sharp corners, or b) the surface is actually creating a finer mesh than the data points, and this mesh is not aligned with the data so it misses the corners. Either way it's not doing the right thing.

cc @etpinard as mentioned in #2712

**Comment by archmoj** [comment]
Here is another [demo](https://codepen.io/MojtabaSamimi/pen/BGwdrN) to illustrate this issue.

**Comment by archmoj** [comment]
One of the best illustrations for this bug is `gl3d_surface-lighting` mock where those high points on the diagonal have z values equal to 1!

**Comment by archmoj** [comment]
Here is a simpler [demo](https://codepen.io/MojtabaSamimi/pen/XyEKqo) for debugging this issue.

**Comment by archmoj** [comment]
When this is fixed `gl3d_surface-lighting` should look something like this:
![newplot](https://user-images.githubusercontent.com/33888540/48920412-cbea3980-ee66-11e8-9965-32ab4e7793d7.png)

**Comment by alexcjohnson** [comment]
An extreme example of the problem - spiky data like  `gl3d_surface-lighting` (the data is only 0s and 1s) but very nonuniform x/y data - https://codepen.io/alexcjohnson/pen/XyBReJ?editors=1000
![screen shot 2018-11-26 at 4 02 10 pm](https://user-images.githubusercontent.com/2678795/49041939-aa55be80-f194-11e8-8100-c105d9893bef.png)
notice that the thinner spikes rarely reach 1.
