### ISSUE TITLE
Feature request: Event on range selector change

### ISSUE THREAD

**Issue by myxor** [plotly/plotly.js#2719]
It would be nice to catch some event on changes (or clicks) of existing range selector buttons.

So we could make some data fetching request to the data-backend with the new set date range and just fetch the selected data instead of all existing data.

**Comment by myxor** [comment]
Exaclty what i needed. 
I did not think about that event handling what i wanted to archive. 
Thank you!

**Comment by etpinard** [comment]
Looks like @myxor's issue is resolved. Closing.

For other requests concerning additional event, please use https://github.com/plotly/plotly.js/issues/145

**Comment by Kipngetich33** [comment]
thank you alexcjohnson that worked for me

**Comment by Rapster** [comment]
I almost need the same, `plotly_relayout` is fired when range is changing, I need a similar event but after the range has been set (meaning fired after mouseup event). Any idea?

**Comment by HarryJJ** [comment]
@Rapster Did you find a solution to this?

**Comment by Rapster** [comment]
I don't think so, I ended up using another library

**Comment by HarryJJ** [comment]
Ah dang. No worries thanks for getting back to me!

**Comment by NixTheMan** [comment]
@Rapster what library did you end up using? As I am hitting a wall with #2216 ass well

**Comment by czanbaka** [comment]
I am having the same issues still, any updates on this? What was everyone's resolution?

**Comment by MojoKingBee** [comment]
Hi,
i've found that if you act on zoom you should check for ['xaxis.range[0]'] key, if you act on rangeslider check for ['xaxis.range'][0].
at least in the version of plotly.js I'm using (an old one)
hope it helps
