### ISSUE TITLE
tickpad and labelpad-like kwargs for 3d-axis formatting? 

### ISSUE THREAD

**Issue by ryandvmartin** [plotly/plotly.js#2721]
as seen here: 
https://community.plot.ly/t/axes-tick-and-title-spacing-3d-scatter/10819

I was wondering if a pad-like argument could be added to the axis tick and axis title arguments. I dont know js, but the python code to generate the plot is: 

```
x, y, z = np.random.rand(100, 3).T
x *= 5
y *= 2
data = [go.Scatter3d(
    x=x, y=y, z=z,
    mode='markers', 
    marker=dict(color="black", size=3))]
fontdict = dict(tickfont=dict(size=10))
layout = go.Layout(
    width=500, 
    height=400, 
    showlegend=False,
    margin=dict(l=0, r=0, t=0, b=0, pad=0),
    scene=dict(aspectmode="data", 
              xaxis=fontdict, yaxis=fontdict, zaxis=fontdict)
    )
fig = go.Figure(data=data, layout=layout)
iplot(fig)
```
and the goal is to get the ticklabels and axis titles closer to the axis: 

![image](https://user-images.githubusercontent.com/14908618/41242692-70030d02-6d5d-11e8-92f4-97e106477c56.png)

like this (edited in paint.. hopefully the idea comes across..):

![image](https://user-images.githubusercontent.com/14908618/41242783-aade7196-6d5d-11e8-9ccf-717487760323.png)

Thanks!

**Comment by alexcjohnson** [comment]
related (mainly just about the attribute structure): #882

**Comment by etpinard** [comment]
Or implement `margin.pad` in 3D

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
