### ISSUE TITLE
scattermapbox.line.width is not supported but it is in `_fullData`

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.js#2727]
![image](https://user-images.githubusercontent.com/1280389/41312968-97f44ab6-6e56-11e8-856c-72ec9ee5f30b.png)

In our plotly.py 3.0.0r4 (https://github.com/plotly/plotly.py/pull/942), we can view the default properties in jupyter notebooks. Today, we noticed that `scattermapbox.line.width` appears even though it isn't a supported property. 

Codepen: https://codepen.io/chriddyp/pen/mKmaQv?editors=0011

(Previously, if properties appeared in `_fullData` that weren't in the schema the plotly.py validation would raise an exception. This was fixed in https://github.com/plotly/plotly.py/pull/942/commits/3d0460ef7a01cdcd5e14541882140423c162d7e1 so plotly.py is no longer blocked by this artifact).

**Comment by alexcjohnson** [comment]
Seems to be a hack to make legends happy. Should be easy to unwind on the legend side.

https://github.com/plotly/plotly.js/blob/1a050e85c2b901b2579af0a5e09df00197271ca9/src/traces/scattermapbox/defaults.js#L46-L47
