### ISSUE TITLE
Type should be validated instead of defaulting to scatter

### ISSUE THREAD

**Issue by tbitai** [plotly/plotly.js#2730]
Currently if a plot type is invalid, it will default to `'scatter'` instead of throwing an error. This is quite misleading if one uses a partial bundle and doesn't realize that the type they want to use is not in that partial.

Example: https://jsfiddle.net/tbitai/uahw2ycd/ This will be incorrectly rendered as a scatter plot, since the `'surface'` type is not contained in the basic bundle.

**Comment by etpinard** [comment]
We don't throw errors on _bad_ attribute value anywhere in our code. So this would be a first. You may have a point that defaulting to scatter in partial or custom bundles isn't ideal. I'd recommend using `Plotly.validate` (see https://jsfiddle.net/uahw2ycd/28/ for an example) before calling `newPlot`.

Related https://github.com/plotly/plotly.js/issues/1741

**Comment by tbitai** [comment]
Thank you! Closing this, since #1741 addresses the same issue more generally.
