### ISSUE TITLE
selection on scattergl after relayout

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.js#2731]
I'm testing @jmmease's plotly.py 3.0.0 https://github.com/plotly/plotly.py/pull/942 and seeing an issue with selection on `scattergl` with 1M points. This doesn't happen on the default graph, it only appears after I have modified the graph's width, height, and margin using `Plotly.relayout`.

![scatergl-select-box-2](https://user-images.githubusercontent.com/1280389/41358172-d2153c60-6ef5-11e8-8fc8-d34b384f5303.gif)

![scatergl-select-box](https://user-images.githubusercontent.com/1280389/41358173-d220baea-6ef5-11e8-9722-2460f99e09da.gif)

This is a pretty uncommon workflow (calling relayout after plot draw) so it's not a high priority issue at all for plotly.py.

**Comment by etpinard** [comment]
Reproduced in https://codepen.io/etpinard/pen/KevRdr?editors=1010

Thanks for the report.

@dy anything comes to mind here?
