### ISSUE TITLE
Hovers on cumulative histograms

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#2738]
In this pen: https://codepen.io/nicolaskruchten/pen/RJLMVb?editors=0010# I see that the hovers label the first bin as "1" with a value of 2 and the second as "3" with a value of 3. It seems to me that the hover labels should indicate the upper edge of the bin, not its center: there are 2 values below 2, not below 1.

**Comment by etpinard** [comment]
I can't remember what @alexcjohnson had in mind for cumulative histogram hover back in https://github.com/plotly/plotly.js/pull/2113, but yeah this seems off.

Thanks @nicolaskruchten for the report.

**Comment by etpinard** [comment]
Just found https://github.com/plotly/plotly.js/issues/2115 - which describes some potential  cumulative histogram hover content.

Merging into #2115
