### ISSUE TITLE
plotly_afterplot Event isn't triggered on pan/zoom

### ISSUE THREAD

**Issue by JOE95443** [plotly/plotly.js#2740]
In previous versions of Plotly.js (1.35.2 works) I would use the `plotly_afterplot` event to detect when a user had panned the graph, but this event is no longer being called when the user pans or zooms.

The issue can be reproduced using your plotly_afterplot [example](https://codepen.io/plotly/pen/YeGGdy) on Codepen. The event only seems to be called when the plot is first drawn and when the axes are reset. I've tested this on the latest version of both Chrome and Safari on MacOS; neither of which have events called from simply panning or zooming the plot.

**Comment by alexcjohnson** [comment]
This is likely due to our performance improvements, so axis range changes don’t require a full replot anymore. The `plotly_relayout` event is really the one you want anyway, as it also tells you what the change was.

**Comment by JOE95443** [comment]
Thank you, I can confirm `plotly_relayout` works as expected. I think the documentation for `plotly_afterplot` needs updating and then this issue is resolved.

**Comment by alexcjohnson** [comment]
Good call @JOE95443 - the example at https://plot.ly/javascript/plotlyjs-events/#afterplot-event no longer acts as described.

@etpinard I seem to recall us discussing this before and concluding we no longer even need afterplot, you can just use eg `Plotly.newPlot(...).then(...)` to accomplish its original purpose (and as this issue shows, the other times it currently fires it really shouldn't be used). So should we update the docs to describe it as deprecated and add this to #420?

**Comment by alexcjohnson** [comment]
It's true, if there were one event that always fired after any change to the plot, that could be useful. But what if in v2 this event was `plotly_react`?

**Comment by etpinard** [comment]
> But what if in v2 this event was plotly_react?

Aren't we planning on renaming `Plotly.react` -> `Plotly.plot`  in v2?

**Comment by alexcjohnson** [comment]
> Aren't we planning on renaming `Plotly.react` -> `Plotly.plot`  in v2?

sure :) Alright, fiddling a little it seems like `plotly_afterplot` was actually closer to firing after every GUI-initiated change than I thought, so perhaps it *is* worth extending it to be the one "any change of state" event and then renaming it (amid coalescing with other events) in v2.

**Comment by etpinard** [comment]
> it to be the one "any change of state" event

Sounds great :ok_hand:
