### ISSUE TITLE
mapbox zoom/pan event inconsistencies

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#2742]
Mapbox zoom/pan events don't match the corresponding API calls. Currently mapbox's `moveend` (which covers pan and wheel zoom) generates a `plotly_relayout`, as it should, but the data looks like:
```js
{
  mapbox: {
    bearing: 0,
    center: {lon: -48, lat: 7},
    pitch: 0,
    zoom: 1.23
  }
}
```
whereas the matching `Plotly.relayout` (in order to not :hocho: the rest of the `mapbox` object) should be:
```js
{
  'mapbox.bearing': 0,
  'mapbox.center': {lon: -48, lat: 7},
  'mapbox.pitch': 0,
  'mapbox.zoom': 1.23
}
```

Double-clicking on a mapbox map creates a `plotly_doubleclick` event with no data - which is fine, we do that in cartesian as well - but we should also emit a `plotly_relayout` that matches the change in view.

I suppose the first part of this could be viewed as a breaking change, but the second part is simply an omission, a view change that doesn't generate the right event to describe the new view.

**Comment by etpinard** [comment]
> I suppose the first part of this could be viewed as a breaking change

Thinking of the case with `mapbox.layers`, I'd call the first part a bug.

**Comment by etpinard** [comment]
> but the second part is simply an omission, a view change that doesn't generate the right event to describe the new view.

Hmm, I'm sure other subplots suffer from the same bug. We should check how geo, gl3d, polar and ternary behave.

**Comment by etpinard** [comment]
Thanks for the report, by the way :ok_hand:
