### ISSUE TITLE
Legend points difficult to see

### ISSUE THREAD

**Issue by joshua-gould** [plotly/plotly.js#2745]
When the marker size is small, it is difficult to read the colors in the legend-https://codepen.io/anon/pen/gKoNjN. A workaround is to scale the legend using the css:
 <style>
        .layers {
            transform: scale(5) translate(-16px, 0)
        }
    </style>

However, when saving the plot as a png, the legend is not scaled. A possible solution is to add a scale factor field to the legend: {scaleFactor:5, font:{size:10}}. What do you think? Thanks.

**Comment by etpinard** [comment]
Thanks for writing in. This ticket is similar to #2080 and personally I'd vote for solution like:

```js
{
  x: [/* */],
  y: [/* */],
  legenditem: {
    textfont: {
       color: 'red'
     },
     marker: {
       size: 20
     }
  }
}
```

similar to what was proposed in https://github.com/plotly/plotly.js/issues/1701#issuecomment-336450036

----

We should probably merge these this ticket, #1701 and #2080 together.

**Comment by nicolaskruchten** [comment]
I would favour a larger default minimum personally...

**Comment by etpinard** [comment]
Merging into #3727
