### ISSUE TITLE
Change lables on chandlestick charts

### ISSUE THREAD

**Issue by RaykPlatzek** [plotly/plotly.js#2749]
Searching for a while now but could not see any info regarding this topic.
Is it possible to change the hover labels (close, low, high, open) for candlestick charts ?

Thanks in advance

**Comment by alexcjohnson** [comment]
Two ways come to mind:
- Make a [translation](https://github.com/plotly/plotly.js/pulls?q=is%3Apr+is%3Aclosed+label%3A%22type%3A+translation%22)
- Use `hoverinfo: 'text'` and make your own completely custom `trace.text` array.

Does either of those fit your use case?

**Comment by RaykPlatzek** [comment]
@alexcjohnson got it working by using:
      
      mode: 'text',
      text: [my_new_array_of_labels],
      textposition: 'top',
      hoverinfo: "x+text",
