### ISSUE TITLE
scattergl symbols not visible in Edge browser

### ISSUE THREAD

**Issue by bcdunbar** [plotly/plotly.js#2750]
Markers not visible in Microsoft Edge browser when chart type is `scattergl` and symbol is set (see image below). 

Open in Microsoft Edge browser: https://codepen.io/bcd/pen/bKMrZe
Microsoft Edge 42.17134.1.0

![scattergl edge](https://user-images.githubusercontent.com/8393928/41759838-bd29ab8e-7633-11e8-8e58-743ea01e1b5e.png)

**Comment by alexcjohnson** [comment]
confirmed, thanks @bcdunbar - cc @dy

**Comment by etpinard** [comment]
From https://github.com/plotly/plotly.js/pull/2863#issuecomment-413564575, looks like will need a separate fix for Edge.
