### ISSUE TITLE
Config argument for baseUrl

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.js#2759]
Right now, the base url for the `/external` endpoint is taken from the window. Could we add an option to the config as well? That'd make it easier for Dash users to point to their On-Premise instances:
https://github.com/plotly/plotly.js/blob/e7896e98f2643ba2824e5c4831b9f5d63f795cd4/src/plots/plots.js#L217

something like
```
 var baseUrl = (
    (window.PLOTLYENV && window.PLOTLYENV.BASE_URL) || 
    config.plotly_server_url ||
    'https://plot.ly';
```

cc @cldougl

**Comment by etpinard** [comment]
Sure. :camel: that config option to `plotlyServerUrl` and PR away :rocket:
