### ISSUE TITLE
Legend titles

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#276]
In the past, we used layout.annotations hacks to add legend titles in https://github.com/ropensci/plotly, but it's hard to do it right...

**Comment by etpinard** [comment]
That'd be cool. But I'll have to put this in the low-priority bin I'm afraid.

**Comment by suribabu39** [comment]
Hi, I understand that we can't directly give titles for legends. But is there any other away to show legend title (as it was mentioned that it can be done using layout.annotations) ?

**Comment by ggrrll** [comment]
Hi,

was there any improvement on this direction? is it still not possible to have a legend title? 

thanks

**Comment by nicolaskruchten** [comment]
Updating this issue to say: we need `layout.legend.title` in the same shape as `layout.title`. Basically want text, font, positioning :)

**Comment by nicolaskruchten** [comment]
In terms of positioning, I would be fine with forcing the title to always be above the legend items, even in horizontal mode (similar to how `layout.title` works right now) but I would also be fine with having the title be beside the legend items in horizontal mode always, *or* with allowing the user to place the title anywhere in the legend. Whatever is easiest to implement and is future-friendly :)

**Comment by archmoj** [comment]
Should we support mathjax in the first iteration?

**Comment by nicolaskruchten** [comment]
not necessary IMO

**Comment by alexcjohnson** [comment]
> not necessary IMO

That's fine - just include it in https://github.com/plotly/plotly.js/blob/master/test/image/baselines/mathjax.png so we don't forget about it
<img width="134" alt="Screen Shot 2019-11-20 at 6 23 18 PM" src="https://user-images.githubusercontent.com/2678795/69287037-ced75180-0bc2-11ea-8dc3-00f463393d19.png">

**Comment by archmoj** [comment]
I think I was able to make mathjax work on legend titles similar to legend items.
