### ISSUE TITLE
Additional aggregation functions: range and change

### ISSUE THREAD

**Issue by bhogan-mitre** [plotly/plotly.js#2763]
I would like to use some additional, fairly simple, functions for aggregations.  Per brief exchange on the [community site](https://community.plot.ly/t/additional-aggregation-functions/11274), it seems like Plotly would be open to including more functions.

Two functions I would suggest are:
- range: max - min
- change: last - first

**Comment by alexcjohnson** [comment]
Sure, those both sound completely reasonable. Would you like to make a PR to add them? In addition to adding them as [attribute values](https://github.com/plotly/plotly.js/blob/06738233c0bd61c4c6ff6e93f946f5a61d88bd43/src/transforms/aggregate.js#L71) as you already mentioned in the community post, they just need to be added in [`getAggregateFunction`](https://github.com/plotly/plotly.js/blob/06738233c0bd61c4c6ff6e93f946f5a61d88bd43/src/transforms/aggregate.js#L286) and then included briefly in the [aggregation test suite](https://github.com/plotly/plotly.js/blob/master/test/jasmine/tests/transform_aggregate_test.js)

**Comment by bhogan-mitre** [comment]
Yes, I will try to put together a PR for this.  Thanks for links to the other touch points for these functions!

**Comment by bhogan-mitre** [comment]
PR into my own fork is linked above.  Please let me know if you have any suggestions on this, @alexcjohnson.  Thanks in advance.

**Comment by bhogan-mitre** [comment]
Thanks for the review!  Linked above is a PR into the main repo.
