### ISSUE TITLE
Filter value not updated properly for interval values

### ISSUE THREAD

**Issue by bhogan-mitre** [plotly/plotly.js#2768]
When using `Plotly.update` for transform interval values, it appears to only take the first array entry rather than both the lower and upper bounds.

Reproducible example:
https://jsfiddle.net/jy7d6rax/64/

Compare the initial filter (`[slider value - 1, slider value + 1]`) to the updated filter ( `= slider value - 1`).

**Comment by alexcjohnson** [comment]
You need to wrap the array in another array. As mentioned in the [`restyle` docs](https://plot.ly/javascript/plotlyjs-function-reference/#plotlyrestyle) (from which `update` inherits its behavior):

> In restyle, arrays are assumed to be used in conjunction with the trace indices provided. Therefore, to apply an array **as a value**, you need to wrap it in an additional array.
