### ISSUE TITLE
setPlotConfig() triggering 'WARN: Unrecognized transform type ...' for any transform type

### ISSUE THREAD

**Issue by dmt0** [plotly/plotly.js#2771]
Reproduced here: https://codepen.io/dmt0/pen/XYQRzO?editors=1010
See browser console.

**Comment by etpinard** [comment]
Ah you're using `plotly-cartesian`. 

This is the desired behavior here as we only include transforms in the ["main"](https://github.com/plotly/plotly.js/blob/f06032f040897587ef8f8ff5ea3765dc64625c08/lib/index.js#L58-L73) plotly.js bundle.

**Comment by etpinard** [comment]
@dmt0 does this makes sense? Can I close this issue?
