### ISSUE TITLE
Support MultiLineString in plotly.graph_objs.Scattermapbox

### ISSUE THREAD

**Issue by OleMussmann** [plotly/plotly.js#2778]
When plotting multiple lines on a MapBox map, there are two options:
  * Make an array of `plotly.graph_objs.Data` for every new line. Benefits: Each line has separate options for hover, compatible with NaNs in the data. Drawbacks: Does not scale, each line seems to be on a new map layer that needs to be loaded separately; thus very slow for large numbers of lines.
  * Make one entry in `plotly.graph_objs.Data`, and pepper the data with NaNs. With `connectgaps = False` (default, I think) no line will be drawn across the NaNs, thus splitting the lines. Benefit: Scales well, all lines are on one layer. Drawbacks: No option to connect NaNs that may naturally occur in the data. Shared options like coloring or hover-information for all lines.

It would be nice to be able to draw multiple lines on one map layer without resorting to hacks. Bonus for allowing separate options for lines on the same map layer.

**Comment by OleMussmann** [comment]
@alexcjohnson Thanks for the swift reply and my apologies for not explaining it better. I'm not sure how to implement it in the supplied codepen. Is a python example ok too?

The performance is only a problem when using MapBox. With shapefiles and `type = 'scattergeo'` it's going fine with a large number of lines. But then there's no pretty map anymore. :-)

Two variants of plotting two lines with MapBox in Python:

  * When using NaNs (`use_nans = True`) then the continuous data will be split at the missing values. This variant scales well for a large number of independent lines.
  * When using arrays of data (`use_nans = False`) then each line is plotted separately. This would be the more logical way of dealing with data, but it gets _very_ slow for a large number of lines.



```
import plotly.graph_objs as go
import plotly.offline as py

use_nans = True

accesstoken = "xyz"

layout = go.Layout(
    showlegend=True,
    mapbox=dict(
        accesstoken=accesstoken,
        center=dict(
            lat=45.5,
            lon=-73.57
        ),
        zoom=12,
    ),
)

if use_nans:
# fast, but clunky data handling
    lats_nan = [45.5, 45.49, 45.51, float("nan"), 45.505, 45.495, 45.515]
    longs_nan = [-73.6, -73.55, -73.57, float("nan"), -73.609, -73.559, -73.579]

    data = go.Data([
        go.Scattermapbox(
            lon=longs_nan,
            lat=lats_nan,
            mode="lines",
            line=go.Line(width=8),
        ),
    ])

else:
# intuitive data handling, but slow for a large number of lines
    lats = [[45.5, 45.49, 45.51], [45.505, 45.495, 45.515]]
    longs = [[-73.6, -73.55, -73.57], [-73.609, -73.559, -73.579]]

    data = go.Data([
        go.Scattermapbox(
            lon=longs[0],
            lat=lats[0],
            mode="lines",
            line=go.Line(width=8),
        ),
        go.Scattermapbox(
            lon=longs[1],
            lat=lats[1],
            mode="lines",
            line=go.Line(width=8),
        ),
    ])

fig = dict(data=data, layout=layout)
py.plot(fig)
```

**Comment by alexcjohnson** [comment]
Ah OK, I see what you're going for. We actually do currently use `MultiLineString` for the first case (with `NaN` in the data) and you can use arrays for `text`, `hovertext`, and `hoverinfo` in order to mimic multiple traces, but our implementation doesn't allow this to include multiple line colors, and as you say it's a bit clunky to massage your data this way.

I wasn't aware of these performance issues with many layers, but it *looks* as though it should be possible to combine all our lines into one layer, and all points into one more layer, so that you could specify it in the second form (and therefore get the associated flexibility re: line color, and line width) but with the performance of the first form.

**Comment by OleMussmann** [comment]
@alexcjohnson That would be great, thanks a lot! Please let me know if you need help testing a version, or if you need sample code with which you can experience the performance drop.

**Comment by araichev** [comment]
I would also love to see this feature implemented.

**Comment by russ-schumacher** [comment]
sorry to raise an old thread, but is there an example of a solution to this issue somewhere? I'm having the same problem, where plotting many lines using scattergeo works fine, but using mapbox is extremely slow. thanks!
