### ISSUE TITLE
Improve bandwidth calculation for single-value violins 

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#2779]
From @alexcjohnson in https://github.com/plotly/plotly.js/pull/2775

> But if we think this is a real use case we should use other violins on the same subplot to pick a bandwidth that's reasonable for the whole collection, like we do with [histograms](https://github.com/plotly/plotly.js/blob/master/src/traces/histogram/calc.js#L350)

**Comment by cpsievert** [comment]
This seems to cause a reasonable amount of confusion for folks working with real data, see

https://github.com/ropensci/plotly/issues/1476
https://github.com/ropensci/plotly/issues/1462

A minimal example

https://codepen.io/cpsievert/pen/xBdxvo 

A vertical line at the singular value seems like the right way to handle this, it's also consistent with ggplot2:

<img width="1066" alt="screen shot 2019-03-07 at 4 27 10 pm" src="https://user-images.githubusercontent.com/1365941/53993840-18941080-40f6-11e9-97f6-a2e481cd6d88.png">
