### ISSUE TITLE
Fix *all* OS / browser-dependent scattergl text oddities 

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#2780]
Follow-up of https://github.com/plotly/plotly.js/pull/2737

`scattergl` text works well on @dy's Windows laptop in both Chrome, FF and IE11 (please correct me if I'm wrong @dy), but features a few oddities in FF on MacOS and Ubuntu 16.04 and Safari. 

Copying @alexcjohnson 's report:

On Mac OS 10.13.5, retina display. For reference here's the SVG `text_chart_arrays` mock, which AFAICT looks identical on Chrome, FF, and Safari:
<img width="766" alt="chrome svg" src="https://user-images.githubusercontent.com/2678795/42315547-04e0fe46-8048-11e8-942f-3a5636c6c22d.png">
But the gl2d version looks bold and blurry (perhaps this is retina-only, related to #2756?), and there are first-load issues in FF (missing some items entirely) and Safari (wrong font).
Here's Chrome:
<img width="759" alt="chrome gl" src="https://user-images.githubusercontent.com/2678795/42315567-130d79fe-8048-11e8-8bae-b39c5b7a231b.png">
FF the first render in a given tab is missing some items:
<img width="740" alt="ff gl first" src="https://user-images.githubusercontent.com/2678795/42315599-24dee2f8-8048-11e8-9a26-d1834c3748d4.png">
But the second gets them all:
<img width="751" alt="ff gl second" src="https://user-images.githubusercontent.com/2678795/42315613-2df7dac0-8048-11e8-8d71-76759ba32e9a.png">
And Safari on first render has the wrong font for "Text G":
<img width="757" alt="safari gl" src="https://user-images.githubusercontent.com/2678795/42315631-36697650-8048-11e8-8661-767f83dab73d.png">
but it's fixed on second render:
<img width="745" alt="safari gl second" src="https://user-images.githubusercontent.com/2678795/42316190-7942bf76-8049-11e8-9314-d380051a9823.png">

**Comment by etpinard** [comment]
bug report from @chriddyp 

The latest scattergl text is not rendering for me on Firefox 61.0, MacOS 10.13.4. It renders for me in Chrome.

Chrome:
![image](https://user-images.githubusercontent.com/1280389/42916045-34ba2abe-8ad1-11e8-9308-57f4fe5fcb52.png)

Firefox:
![image](https://user-images.githubusercontent.com/1280389/42916038-240eac3a-8ad1-11e8-8b52-0881625e9a7d.png)

Firefox Console:
![image](https://user-images.githubusercontent.com/1280389/42916057-4e401962-8ad1-11e8-89c7-22d4b8782d85.png)

**Comment by etpinard** [comment]
assigning @dy

**Comment by chriddyp** [comment]
Another report: https://community.plot.ly/t/scattergl-inconsistently-supports-custom-fonts/29280
