### ISSUE TITLE
feature: let `marker.color` accept an array of categories

### ISSUE THREAD

**Issue by n-riesco** [plotly/plotly.js#2795]
For example, see [here](https://community.plot.ly/t/cant-color-based-on-column-value/11602) a user that wants to create a scatter plot of `count` vs `date` coloured by by `host`.

If `host` was a numeric variable, then, the default `cmax`, `cmin` and `colorscale` would be used.

**Comment by etpinard** [comment]
Probably a duplicate of https://github.com/plotly/plotly.js/issues/1747

**Comment by etpinard** [comment]
Merging with #1747
