### ISSUE TITLE
Scattergl box/lasso selection on broken overlaying-y-axis subplots

### ISSUE THREAD

**Issue by vincex** [plotly/plotly.js#2797]
https://codepen.io/anon/pen/BPaQOe?editors=1010

If you try to select some points with lasso or box selection only the last added trace is visible.
The "autoscale" buttons fix the visualization problem until a new selection is made.

I dont have a deep knowledge of ploty and I am not able to investigate further. But from what i was able to see seems that with the autoscale the redraw of each subplot is in sync, instead with the selection the redraw of each subplot is async and only the last one is redrawed.

Thanks for your time guys.

**Comment by etpinard** [comment]
Thanks for the report!

**Comment by etpinard** [comment]
Related to https://github.com/plotly/plotly.js/issues/2562, which might be the best way to fix this bug.

@dy what do you think?

**Comment by etpinard** [comment]
More minimal reproducible example: https://codepen.io/etpinard/pen/ajbGOx
