### ISSUE TITLE
Legend Marker Vertical Alignment

### ISSUE THREAD

**Issue by bpostlethwaite** [plotly/plotly.js#2798]
A feature request has been made for legend marker alignment relative to legend trace names. 

In the case where legend trace names are multi-line the request is to have options for marker vertical alignment. In this example the marker would align with the first legend text line when set to "top".

![image](https://user-images.githubusercontent.com/1176674/42514276-046c7908-8427-11e8-8cc6-dd0f52baeba0.png)

**Comment by etpinard** [comment]
Adding a legend-wide attribute should suffice. I'd vote for `layout.legend.align` or `layout.legend.valign` similar to what `annotations/` uses:

https://github.com/plotly/plotly.js/blob/a070a8d2dd89f8ecbee89eecee77979298bfd886/src/components/annotations/attributes.js#L87-L111

**Comment by etpinard** [comment]
cc @antoinerg
