### ISSUE TITLE
IE11: scattergl: problems with marker symbols

### ISSUE THREAD

**Issue by mojoaxel** [plotly/plotly.js#2802]
We have problems with custom marker-symbols in a `scattergl` chart. 

Chrome and Firefox are OK. 
This seems to be only a Problem in IE (11.0.9600.19002)

```
WEBGL11042: INVALID_OPERATION: useProgram: Program not linked
```

![image](https://user-images.githubusercontent.com/600565/42578521-da718318-8526-11e8-9546-7f84fb757be6.png)

Live Example: https://jsbin.com/zokekob/edit?js,output

**Comment by etpinard** [comment]
cc @dy is this the expected behavior? I remember you saying we only support of symbols in IE11?

**Comment by etpinard** [comment]
related https://github.com/plotly/plotly.js/issues/2750

**Comment by dy** [comment]
Yes, custom symbols are likely broken now in scattergl. That requires a bit of time to fix, I will give a try.

**Comment by mojoaxel** [comment]
@dy Any update on this? For now we switched from `scattergl` to `scatter` on IE. Is there a chance that this will get fixed?

**Comment by mojoaxel** [comment]
I can confirm, that this issue is solved :+1:  
but, as @etpinard mentioned there are still some warnings in the example above:

![image](https://user-images.githubusercontent.com/6675409/43597729-ee9b13a0-9650-11e8-91e6-d9cf1fbf7319.png)

**Comment by dy** [comment]
@etpinard just figured out. That error is actually just a log in console, there is no way to turn it off. That piece of code feature-detects WebGL. I can hardcode browser detection instead, to mute the log for IE11 specifically.

**Comment by someusersomeuser** [comment]
version 1.42.0 and later
marker symbols not work
error: "Path2D" is not defined
