### ISSUE TITLE
Add new plot: timeline

### ISSUE THREAD

**Issue by hofes** [plotly/plotly.js#2803]
Hello,

it would be nice if you could add a similar plot like [VisJS](http://visjs.org/timeline_examples.html) to plotly. 

Thank you.

Br,
Stephan

**Comment by etpinard** [comment]
added to https://github.com/plotly/plotly.js/issues/2221

Thanks!

**Comment by mounicanaidu** [comment]
@hofes  I too needed plotly to create timeline view but I couldn't wait and hence created this small workaround till we have one from plotly. Check it out [here](https://github.com/mounicanaidu/manyamPlotlyTimeline).
