### ISSUE TITLE
Aggregate then Filter

### ISSUE THREAD

**Issue by bhogan-mitre** [plotly/plotly.js#2804]
I would like to be able to use filters and aggregations together, and I am finding that it works in one direction but not the other.

Here is a minimal example trying to aggregate and then filter: https://jsfiddle.net/f2vo05nw/5/

If I filter first and then aggregate, the analogous example works (as also shown in the [documentation](https://plot.ly/javascript/multiple-transforms/#filter-and-aggregates)): http://jsfiddle.net/3m75zqk2/12/

Is there a reason this does not (or could not) support filtering after an aggregation?

This relates to #2078.

**Comment by alexcjohnson** [comment]
As far as I can tell, it's working as designed:
- Your input data is `x: [1, 2, 3, 4, 5, 6]`, which you aggregate with groups `[1, -1, 1, -1, 1, -1]` so it breaks into sets `1, 3, 5` and `2, 4, 6`
- No `aggregations` are defined within the `aggregate` transform, so we default to `first` - thus after aggregation you have `x: [1, 2]`
- Then you filter on `x >= 3`, which eliminates both points, so the result is an empty trace. But if you change the `3` to `2`, the second point remains (and this result is different than if you reversed the order of the transforms - in that case you get `x: [2, 3]`, or `[3, 4]` with the original filter `x >= 3`.

@bhogan-mitre can you clarify the behavior you expected?

**Comment by etpinard** [comment]
@bhogan-mitre this issue seems to be resolved, ok if I close it?

**Comment by bhogan-mitre** [comment]
Yes, fine to close.  Thank you.
