### ISSUE TITLE
the chart can not scale the X axis and Y axis by rolling the mouse wheel

### ISSUE THREAD

**Issue by JayHC** [plotly/plotly.js#2807]
like this:   ### https://plot.ly/~dtrejo.privado/4/#plot,it can scale the X axis and Y axis by rolling the mouse wheel

but I try it local and copy the Embed code,the function is disabled

please tell me how to solve it,

thanks.

**Comment by alexcjohnson** [comment]
This is a config option `scrollZoom: true` https://plot.ly/javascript/configuration-options/

"how do I" questions are better suited to community.plot.ly - thanks!
