### ISSUE TITLE
TypeScript definition uses regex string types which are not supported

### ISSUE THREAD

**Issue by jonfreedman** [plotly/plotly.js#2808]
I don't believe this feature is actually supported yet?  See: https://github.com/Microsoft/TypeScript/issues/6579

If I try and set multiple axes as per https://plot.ly/javascript/multiple-axes/ TypeScript errors on the overlaying property:
```
Types of property 'overlaying' are incompatible.
  Type '"y"' is not assignable to type '"/^x([2-9]|[1-9][0-9]+)?$/" | "/^y([2-9]|[1-9][0-9]+)?$/" | "free" | undefined'.
```

**Comment by jonfreedman** [comment]
I managed to get my chart rendering properly using this definition, which I assume was never the intention...
```javascript
yaxis2: {
    overlaying: 'y' as '/^y([2-9]|[1-9][0-9]+)?$/',
    side: 'right'
}
```

**Comment by alexcjohnson** [comment]
Is this error coming from the DefinitelyTyped definitions for plotly.js? If so the issue will probably need to be sorted out over there. The core plotly.js team has not been involved in any typescript definitions, so I really wouldn't know what to suggest to fix the issue, other than a huge list of all possible x or y axis ids... perhaps a modification of this PR is in order https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20467 ?

**Comment by jonfreedman** [comment]
Yes I think you are correct - I will look at a PR with DefinatelyTyped.  For reference do you really support an unbounded number of x/y axes?

**Comment by alexcjohnson** [comment]
We really do. It starts to bog down after a while, but for example `splom` traces have been tested up to 50 dimensions, which means 50 X axes, 50 Y axes, and 1200 to 2500 subplots.

**Comment by etpinard** [comment]
This issue seems to be destined for https://github.com/DefinitelyTyped/DefinitelyTyped. Closing.
