### ISSUE TITLE
Polar 2.0 replacement for legacy "area" type

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#2810]
A request has come in for an updated version of the old `area` type. As mentioned by @etpinard in #2255:

> How to replace legacy polar's `area` trace type? I'd vote for replacing it with `polarbar` or `wedge`. Most of the `bar` logic could be reused here.

Yes, it seems like this trace type is precisely `bar` transformed onto polar axes. For consistency with other trace type names perhaps it should be `barpolar` though?

Looks to me as though essentially all the existing `bar` trace attributes will translate to the new type straightforwardly. In fact, there's even an analog of `orientation`, though instead of `(x|y)` we'd have `(radial|angular)`. For the request at hand only `radial` (which matches the legacy `area` type) is necessary, but some day someone will want `angular` as well, like https://peltiertech.com/time-is-on-my-side/
![ring chart](https://peltiertech.com/wp-content/img200808/donut-clock-in-excel.png)

The `layout` attributes (`barmode`, `barnorm`, `bargap`, `bargroupgap`) to the extent that we want them at all, we can make into attributes of the `polar<N>` subplot. I would suggest omitting (at least initially) `barmode: 'group'` and `'relative'`, and therefore also `bargroupgap`. Probably also omit `barnorm`, that only enhances the confusion over whether it's the radius or area that encodes value.

**Comment by spicynaresh** [comment]
add Aster Plot
