### ISSUE TITLE
mapbox marker symbol not working

### ISSUE THREAD

**Issue by bcdunbar** [plotly/plotly.js#2813]
marker symbols in scattermapbox either don't show up or don't color correctly. For example, 'star' is visible but is always black; square isn't visible.

https://codepen.io/bcd/pen/EpVaxQ?editors=1010

I see there a few issue concerning symbols specific to IE or Edge. This isn't browser-specific.

**Comment by etpinard** [comment]
Scattermapbox doesn't share the same marker symbol list as our other scatter* trace type

https://github.com/plotly/plotly.js/blob/918ed9cb0673b8d3208e87fe0f01e17a2626bd29/src/traces/scattermapbox/attributes.js#L72-L84

The list in https://www.mapbox.com/maki-icons/ seems to change fairly frequently, and yes some markers can't be shown in color, but there's not much we can do about it.

**Comment by etpinard** [comment]
merging with https://github.com/plotly/plotly.js/issues/815
