### ISSUE TITLE
Bad example on website (exponentformat "All" instead of "all")

### ISSUE THREAD

**Issue by jacobq** [plotly/plotly.js#2818]
In the [Set and Style Axes Title Labels and Ticks](https://plot.ly/javascript/axes/#set-and-style-axes-title-labels-and-ticks) example, `layout.yaxis.showexponent` is set to 'All', but actually this parameter is case-sensitive and should be "all".

See [live example here](https://jsbin.com/karasol/4/edit?js,output).

**Comment by etpinard** [comment]
@cldougl would it best to move this ticket over to https://github.com/plotly/documentation/issues ?

**Comment by cldougl** [comment]
yep! closing and moving it to: https://github.com/plotly/documentation/issues/969
thanks for the report @jacobq !
