### ISSUE TITLE
Add support for Sankey charts

### ISSUE THREAD

**Issue by gramster** [plotly/plotly.js#282]
What it says

**Comment by jackparmer** [comment]
@gramster We've had a few requests for this lately. Do you mind filling out this form so I can send you an email?
https://plot.ly/products/enterprise/get-in-touch/

**Comment by jackparmer** [comment]
It probably would not be too difficult to integrate this:
https://github.com/d3/d3-plugins/tree/master/sankey

The key part would be defining the JSON spec for Sankey diagrams (http://help.plot.ly/json-chart-schema/). Here's the matplotlib API:
http://matplotlib.org/api/sankey_api.html

**Comment by sudburyrob** [comment]
@jackparmer  - yo, I am adding a note re: customer request for this in the Customer Feedback channel.

**Comment by sudburyrob** [comment]
@etpinard ^^ failed to copy u

**Comment by etpinard** [comment]
assigning @monfera :tada:

**Comment by monfera** [comment]
A summary of hard requirements toward the initial implementation:

- [ ] unidirectional DAG (no cycles initially) 
- [ ] linear layout; option for horizontal or vertical flow orientation
- [ ] works on mobile
- [ ] optionally deactivated default hover tooltip with basic data and minimal styling
- [ ] plotly_hover event raised on hover to allow custom tooltips or other interactions
- [ ] text labeling for nodes
- [ ] an SVG renderer with decent scenegraph and CSS class names to enable some styling above and beyond the plotly.js Sankey attribute options (class names and structure will be subject to implementation changes though as it's not part of the API)
- [ ] ability to filter some of the flows, i.e. not graying out or turning invisible, but to relayout by freeing up their previously occupied beam size (for example, by rerendering the plot with just the restated data as specified by the API caller via e.g. `Plotly.restyle`)

In addition, we're not currently committing to, but planning to have

- [ ] breakdown of flows (e.g. by a dimension or to flow contributor items)
- [ ] moving nodes around perpendicularly to the overall flow (e.g. up/down on a horizontal layout)
- [ ] coloring options for nodes, flows and perhaps subflows (not yet specified)

**Comment by monfera** [comment]
@etpinard now equipped with [stable sorting](https://github.com/d3/d3-sankey/pull/19) parallel links, it's important to style the currently hovered line (don't mind the temporary tooltip now) as there may be partial occlusion. I could use some guidance on the approach, e.g. should I create `.sankeyLink:hover` CSS styling, or should it be done in CSS, and should there be some configuration attributes for it? Or pls. point me to a suitable precedent.

**Comment by monfera** [comment]
![sankey hover](https://cloud.githubusercontent.com/assets/1548516/23468976/94e96aba-fea2-11e6-927b-d6aa4f5e3a9a.gif)

**Comment by etpinard** [comment]
This was completed in https://github.com/plotly/plotly.js/pull/1591 released in `1.27.0`

**Comment by jackparmer** [comment]
### Docs for Sankey diagrams:
**Python:** https://plot.ly/python/sankey-diagram/
**R:** https://plot.ly/r/sankey-diagram/
**JavaScript:** https://plot.ly/javascript/sankey-diagram/
