### ISSUE TITLE
npm audit security report: several vulnerabilities found

### ISSUE THREAD

**Issue by RosarioAleCali** [plotly/plotly.js#2822]
Running npm audit outputs the following:
![screenshot from 2018-07-17 22-15-14](https://user-images.githubusercontent.com/25593250/42855521-ea116a8a-8a0e-11e8-88b4-85b0bf7d6320.png)
It actually outputs more vulnerabilities but they are all related to static-eval.
Is this something that can be fixed for the next version?

**Comment by etpinard** [comment]
see https://github.com/plotly/plotly.js/issues/2386#issuecomment-367115725

**Comment by etpinard** [comment]
and https://github.com/scijs/cwise/pull/21 which unfortunately breaks plotly.js bundling.

**Comment by RosarioAleCali** [comment]
Okay, do you see a fix for it in the foreseeable future?

**Comment by etpinard** [comment]
As this issue only potentially affects plotly.js users that build their custom bundles that include gl3d trace types (which is a fairly low % of our users), no plotly.js team member will spend time on this in the short term.

**Comment by RosarioAleCali** [comment]
Ok, then I will close this issue.

**Comment by Queatz** [comment]
We're trying to make Plot.ly pass CI - is there a way to disable "custom bundles that include gl3d trace types" so that the vulnerabilities go away?

**Comment by antoinerg** [comment]
@Queatz it should be possible to require only what you need. Please see https://github.com/plotly/plotly.js/#modules for details
