### ISSUE TITLE
Scattergl text not rendering on Firefox

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.js#2825]
The latest scattergl text is not rendering for me on Firefox 61.0, MacOS 10.13.4. It renders for me in Chrome.

Chrome:
![image](https://user-images.githubusercontent.com/1280389/42916045-34ba2abe-8ad1-11e8-9308-57f4fe5fcb52.png)

Firefox:
![image](https://user-images.githubusercontent.com/1280389/42916038-240eac3a-8ad1-11e8-8b52-0881625e9a7d.png)

Firefox Console:
![image](https://user-images.githubusercontent.com/1280389/42916057-4e401962-8ad1-11e8-89c7-22d4b8782d85.png)

**Comment by etpinard** [comment]
merged in https://github.com/plotly/plotly.js/issues/2780
