### ISSUE TITLE
Plotly.react secondary axis draw error

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#2828]
This Pen https://codepen.io/nicolaskruchten/pen/VBmWLN?editors=0010 shows a `Plotly.react` call which should move the secondary x-axis but results in the old x-axis to remain in the plot.

**Comment by etpinard** [comment]
Ok. Thanks for the report

```js
Plotly.newPlot(gd, steps[0]())
Plotly.relayout(gd, {
  'xaxis2.overlaying': 'free',
  'xaxis2.domain': [0.37, 1]
})
```

is enough to reproduce the bug also.
