### ISSUE TITLE
Pan draw error in scattergl + rangeslider and multiple yaxis

### ISSUE THREAD

**Issue by vincex** [plotly/plotly.js#2830]
https://codepen.io/anon/pen/NBbZEg

Actually im using a scattergl plot in a sort of "mixed mode":
- Drawing one trace with scatter in order to enable rangeslider preview
- Drawing all other traces with scattergl in order to have a boost in FPS and CPU usage
Using this configuration if the user tries to pan, all the scatterlg traces are painted erroneously:

![image](https://user-images.githubusercontent.com/43019/43002830-7b7ebadc-8c2a-11e8-8c04-e1192992fb52.png)

This seems related to the fact that rangeslider is rendered as last.
When rendered the rangeslider sets the viewport and remains unchanged while panning.

This seems fix the problem:
https://github.com/vincex/plotly.js/pull/2

**Comment by etpinard** [comment]
Thanks for writing in.

This is what I'm seeing off your vincex#2:

![image](https://user-images.githubusercontent.com/6675409/43005462-ec6990fc-8c00-11e8-946e-0a89522253b2.png)

which doesn't seem to solve the double drawing problem. 

Moreover, I would be reluctant to merge your patch as it could potentially slow down a hot code patch.

I think we should instead dedicate our efforts towards https://github.com/plotly/plotly.js/issues/2627

**Comment by vincex** [comment]
Ok, we will wait for #2627.
The strange thing is that in my environment the double line bug is not visible instead in a pen with the exact same layout/traces configuration copied from my environment the double line is visible. Thats weird.

**Comment by etpinard** [comment]
> my environment the double line bug is not visible

Are you using a different plotly.js version?

**Comment by vincex** [comment]
node_modules\plotly.js\dist\plotly.js from 1.39.2 available in npm.

**Comment by vincex** [comment]
Here a pen with the full flow, but in the doubletrace bug is still there. 
https://codepen.io/anon/pen/NBbZEg

Here a shoot of what I have in my environment
![image](https://user-images.githubusercontent.com/43019/43009619-7444f272-8c3e-11e8-8d74-aa94db69c500.png)

**Comment by vincex** [comment]
That is perfectly fine #2627 share the same goal.

**Comment by etpinard** [comment]
Thanks for your help @vincex !

Merging with https://github.com/plotly/plotly.js/issues/2627
