### ISSUE TITLE
Hover events not firing with hoverinfo none on traces and layout hovermode closest

### ISSUE THREAD

**Issue by swaincreates** [plotly/plotly.js#2832]
The documentation says `hoverinfo: 'none'` on the traces will still allow the hover event to fire but its not working for me. You can see the issue here in codepen https://codepen.io/swaincreates/pen/oMBaEo?editors=1010

**Comment by etpinard** [comment]
It seems to work correctly with v1.39.2 (aka latest) https://codepen.io/etpinard/pen/PBpLbg

Your pen uses v1.5.0 more than two years old.
