### ISSUE TITLE
Mapbox Marker On Click not working in Chrome

### ISSUE THREAD

**Issue by idodin** [plotly/plotly.js#2835]
Hi there!

Reporting a potential issue in the Mapbox Marker 'plotly_click' event on Chrome Browsers. I've tested my implementation on Firefox and Edge with no issues. 
**Browser**: Chrome 67.0.3396.99
**Plotly Library Version**: Plotly CDN Latest-Min

```javascript
var _data = [{
  type: 'scattermapbox',
  mode: 'markers+text',
  marker: {
    size: 14
  },
  textposition: "bottom center",
  hovertext: _me.names, // ['University', 'Station_place_des_arts']
  text: _me.names, // ['University', 'Station_place_des_arts']
  lon: _me.lon, // ['-73.573484', '-73.568279']
  lat: _me.lat, // ['45.50483', '45.508018']
}];

var _layout = {
  autosize: true,
  hovermode: 'closest',
  mapbox: {
    bearing: 0,
    center: {
      lat: 45.50483,
      lon: -73.573484
    },
    pitch: 0, 
    zoom: 14
  },
  height: 700
};

Plotly.setPlotConfig({
    mapboxAccessToken: 'pk.eyJ1IjoibmVzY2FmZWgiLCJhIjoiY2pqc3ZvdWpuOGhidjNrcjV1eWF0dTBiayJ9.g6I1HHzDHNoGdtSKk0MISg'
});

Plotly.newPlot('statContainer', _data, _layout);

$('#statContainer').get(0).on('plotly_click', function (data) {
  console.log(data)
  var pts = '';
  for (var i = 0; i < data.points.length; i++) {
    pts = data.points[i].text
  }
  requestOverview(pts);
})
```
**More information**: Clicking on markers does not execute the `requestOverview` function nor does it log the `data` information to the browser console. This issue only occurs on Chrome.

**Comment by etpinard** [comment]
I got it to work using here: https://codepen.io/etpinard/pen/BPWgra?editors=1010

I suspect something is up with your `$()` statement. That thing might not be standard across browsers.

**Comment by idodin** [comment]
@etpinard Thanks for the response!
For whatever reason, the issue resolved itself after restarting my desktop 🤔 . The `$().get(0)` was not the problem since it was correctly returning the DOM node associated with the selected JQuery element. Confused, but its fixed so will close this. My apologies for the false alarm!

As a side note: I was not aware that the `newPlot` function returned a Promise, nice to know! :)

**Comment by dangelsaurus** [comment]
weird, neither the OPs code or the link @etpinard posted are working for me
