### ISSUE TITLE
feature: expose reset/autosize functions

### ISSUE THREAD

**Issue by druvisc** [plotly/plotly.js#2838]
Would be useful if the reset/autosize functions (https://github.com/plotly/plotly.js/blob/master/src/plot_api/plot_config.js#L73) were exposed like the `Plotly.relayout(graphDiv)`.

**Comment by etpinard** [comment]
Axis autosize (which should really be called _autorange_) can be easily achieved already using 

```js
Plotly.relayout(gd, {
  'xaxis.autorange': true,
  'yaxis.autorange': true
})
```

Axis reset is a little trickier for users, you make a valid point that we should perhaps expose it. Internally we stash the axis `range` values on first render and then call relayout as such:

https://github.com/plotly/plotly.js/blob/180b6b9225173e834ff92245b6f3620bfcfd14a8/src/plots/cartesian/dragbox.js#L674-L689

So feel free to grab those `_rangeInitial` values in your app.

Now perhaps, we could make this easier with something like:

```js
Plotly.relayout(gd, {
  'xaxis.range': 'reset',
  'yaxis.range': 'reset'
})
```

but this we go against some of our recent work of making `relayout` and `restyle` less stateful. Moreover, there's open discussion in #420 about perhaps replacing them with `Plotly.react` to reduce our API surface area.

Oh well, I'll tag this with `discussion needed` and see what happens.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
