### ISSUE TITLE
Multi-line legend items are positioned incorrectly

### ISSUE THREAD

**Issue by john-soklaski** [plotly/plotly.js#284]
Multi-line legend items are positioned as if they were single-lined:
http://codepen.io/john-soklaski/pen/MygKjM

Debugging through, I found that this happened because the bounding box for the text element was calculated as if the text was all in one line.

I've fixed this in my fork by forcing a recalculation of the legend text's bounding box (though I'm not sure if it is the correct solution):
https://github.com/john-soklaski/plotly.js/commit/855d25cdbbcb58682a5d4d87f1518dfa4541d1c8

**Comment by etpinard** [comment]
Thanks for the report.

Could you test your case against `master` ?

@mdtusz made a few modifs in https://github.com/plotly/plotly.js/pull/243 that may have already fixed this issue.

**Comment by mdtusz** [comment]
Correct. This appears to be fixed in the master branch and will be solved in the next release.

**Comment by etpinard** [comment]
Fixed in `v1.6.0`: http://codepen.io/etpinard/pen/ONPNXo

**Comment by john-soklaski** [comment]
This is fantastic, thank you :)
It works great for me, and I'm liking the scroll-able legend as well.
