### ISSUE TITLE
Ability to hide trace name in legend

### ISSUE THREAD

**Issue by meganrm** [plotly/plotly.js#2841]
I am plotting more than one trace (scatterplot plus histograms) and with a groupby transform for the scatter plot, and there doesn't seem to be any way to get rid of the name of the plot in parenthesis after the name of the group. Even if I set the name to an empty string it shows the empty parentheses.

https://codepen.io/meganrm/pen/odKveW
<img width="251" alt="screenshot 2018-07-24 11 55 29" src="https://user-images.githubusercontent.com/5170636/43159886-7da217ee-8f38-11e8-9286-3eeb964f40f1.png">

I think in the case of a groupby legend, the repeated name of the plot is more annoying than informative. It seems like a `includeplotname` defaulting to `true` setting on the legend would really helpful.

**Comment by coop72** [comment]
Dawn Cooper
