### ISSUE TITLE
feature: timing diagram

### ISSUE THREAD

**Issue by mojoaxel** [plotly/plotly.js#2842]
This is a feature Request for a new chart type "Timing Diagram".

> "A digital timing diagram is a representation of a set of signals in the time domain. A timing diagram can contain many rows, usually one of them being the clock. It is a tool that is commonly used in digital electronics, hardware debugging, and digital communications." - _via [wikipedia](https://en.wikipedia.org/wiki/Digital_timing_diagram)_

![image](https://user-images.githubusercontent.com/600565/43193425-419e0afa-9000-11e8-97dc-6de0f4fa50f6.png)
_image [CC-BY-SA-3.0](https://creativecommons.org/licenses/by-sa/3.0/) based on image by [garrett-mcclure](https://electronics.stackexchange.com/users/164646/garrett-mcclure) via [electronics.stackexchange.com](https://electronics.stackexchange.com/questions/339597/drawing-a-timing-diagram-for-a-circuit-showing-x-y-and-z-what-is-z-doing)_

This chart type should support the following features:
* x-axes: normal number but also timing-series.
* y-axes can only have values `false/true` or `0/1`.
* The area underneath each "1" signal can be [filled with a color](https://plot.ly/javascript/filled-area-plots/) (in red above).
* every signal (y-axes) has a baseline (same as "0") (in green above).
* It should be possible to use this chart-type as a subplot.
* series can have different names, colors ...

**Comment by mojoaxel** [comment]
@jackparmer Could you please add this chart-type to #2221

**Comment by alexcjohnson** [comment]
I’ve seen plenty of charts like this with some of the signals analog. Wouldn’t need to be included from the outset but we shouldn’t preclude it.

This could of course be created already using one subplot and one trace for each signal, but I can see the argument for making it a single trace: it would have better performance, much cleaner API, and the interactions could be tailored to this use case.

**Comment by etpinard** [comment]
Now listed under: [`type: new trace type`](https://github.com/plotly/plotly.js/labels/type%3A%20new%20trace%20type)

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
