### ISSUE TITLE
Scattergl toself fill problem

### ISSUE THREAD

**Issue by llnns** [plotly/plotly.js#2845]
Using `scattergl` with `toself` fill option results in a "ghost"/wrong/extra fill among the first points of each object. A minimal example creating three rectangles:

[https://codepen.io/anon/pen/NBvbbv](https://codepen.io/anon/pen/NBvbbv)

Results in:

![newplot](https://user-images.githubusercontent.com/11335099/43237624-05e16154-9061-11e8-8fa9-9cfd4ecfb258.png)

Also, using the same data with `scatter` type has the expected output:

![newplot 1](https://user-images.githubusercontent.com/11335099/43237641-19b71886-9061-11e8-93a7-b85f714f439a.png)

**Comment by alexcjohnson** [comment]
Thanks for the nice simple reproduction @llnns - merging into #2291.
