### ISSUE TITLE
PlotlyJS is not redrawing seconds with a proper tickFormat that includes seconds

### ISSUE THREAD

**Issue by Talador12** [plotly/plotly.js#2848]
If I use a proper `tickformat: '%H:%M:%S'`
I would expect plotly to map out the seconds field.

If I feed the code new data with `Plotly.relayout` it should update the value of the seconds field.

In multiple instances in our application and on CodePen, we are seeing that the Hours and Minutes will update, but the seconds will not. Why is this?

CodePen:
https://codepen.io/talador12/pen/PBKgdo

**Comment by alexcjohnson** [comment]
@Talador12 not sure I understand your concern. I don't see anything that looks wrong in that codepen, but then I don't see a step that updates the data either. For example if I amend your code to:
```js
Plotly.newPlot('graph', [{
  y: input.map(sec2dt)
}], {
 yaxis: {
   tickformat: '%H:%M:%S'
 }
}).then(function() {
  Plotly.restyle('graph','y', [[2002, 5008, 9007].map(sec2dt)]);
});
```
it appears to update as expected, including the displayed seconds field.

Can you elaborate?

**Comment by Talador12** [comment]
I should elaborate that our issue was with the axis labels not displaying updates to the time in seconds. I couldn't share my code directly as it is proprietary, but the example is the closest we had.

We did actually get it working with minimal changes, however, there are some states where the labels display and the data doesn't, as well as the inverse of that. Not sure what would cause that.
