### ISSUE TITLE
feature request: increase the number of colors evolved in the color cycle

### ISSUE THREAD

**Issue by HaoyangFan96** [plotly/plotly.js#2851]
I am make a plotting in which I want to assign each category a unique color. However, with number of categories increase, I found that the color actually repeats in a cycle

![image](https://user-images.githubusercontent.com/28957687/43295160-13701026-90f8-11e8-9404-e32b705d8237.png)

Right now I think Plotly by defaults only cycle through 10 unique colors, which makes sense according to the [source](https://github.com/plotly/plotly.js/blob/master/src/components/color/attributes.js#L13)

I am wondering if there is way to let user increase amount of colors evolved in the cycle or simply let user add their customized colors to the cycle?

Thanks

**Comment by etpinard** [comment]
> I am wondering if there is way to let user increase amount of colors evolved in the cycle or simply let user add their customized colors to the cycle?

I think you're looking `layout.colorway` see example:

https://github.com/plotly/plotly.js/blob/master/test/image/mocks/layout-colorway.json

**Comment by HaoyangFan96** [comment]
@etpinard thanks for the help. Right now to me it seems like that the I need to first find a larger number of distinct and human-friendly colors and then supply to Plotly via `colorway` option. I wonder if there is way for me to get more possible colors from Plotly itself, so I won't have to import color values from third-party library etc

**Comment by alexcjohnson** [comment]
Interesting idea - I could imagine adding some named colorways... kind of like we do with colorscales where you can either specify `[[fraction, color], [fraction, color], ...]` or one of the [predefined names](https://github.com/plotly/plotly.js/blob/master/src/components/colorscale/scales.js). Would be a nice complement to plot templates.

@jackparmer this seems right up your alley 🎳

**Comment by HaoyangFan96** [comment]
@alexcjohnson I do some research on this subject and find some JS library like [this](https://github.com/davidmerfield/randomColor) which generates random distinct colors. However, this is one problem with those libraries: although the generated colors are indeed distinct to each other, but there is no guarantee that they are distinct to each other in the maximum extent. In other words, it is possible for generate some "indeed" distinct colors which are hard for human-eyes to distinguish the difference. Also, a large portion of generated colors do not look nice to the user.

Can you take this two factors into the account while developing this new feature?

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
