### ISSUE TITLE
Too many active WebGL contexts. Oldest context will be lost

### ISSUE THREAD

**Issue by bytesnz** [plotly/plotly.js#2852]
It looks like purging a scattergl graph does not destroy the webgl context. I have a page with 4 scattergl plots on it that are redrawn (`purge` and `newPlot`) when zooming in on data (as it downloads higher resolution data). Once the graphs are redrawn a couple of times, you start getting the WebGL warning messages. Was wondering if the GL context wasn't being "removed completely" on `purge` (related issues https://github.com/pixijs/pixi.js/issues/2233#issuecomment-181650433)?

Hack of an example https://codepen.io/bytesnz/pen/XBaoee

**Comment by etpinard** [comment]
`Plotly.purge` should destroy the associated webgl context. If it doesn't, it's a bug.

But in your example, my guess is that browsers take a little bit of time garbage collection old contexts. Have you tried adding a `setTimeout` in between `purge` and `newPlot`?

**Comment by etpinard** [comment]
... and I should add: I don't see any WebGL warnings in codepen on Chrome 67.

What browser are you using?

**Comment by bytesnz** [comment]
I have seen it in both Chromium and Firefox (Linux). If you duplicate the purge newPlot more, you can get Chromium to do it. Changing the demo to an `setInterval` of 500ms, firefox (62) still does it, but Chromium does not. Changing to interval to 3000ms and, waiting for it to trigger and then running a garbage collection followed by a cycle collection (from about:memory) clears the error for a number of iterations before it starts happening again, though after the 3rd go of this (using the "Minimize memory usage" button), the problem seemed to go away. So could probably be put down to a browser issue. 

The annoyance comes from when it clears the "oldest context" it doesn't discriminate between ones that have been purged and ones that haven't, which leads to an erasing when hovering over contexts that were removed. In the images below, the three coloured marker graphs are updated (zoomed, panned etc) until the error, then the other graph is moused over (excuse the redacting). The erasing happens in firefox whereas in chrome, the graph contents disappears but it still works (last image)
![image](https://user-images.githubusercontent.com/1755886/43356844-15d6e758-9270-11e8-93a8-0039b3e30319.png)
![image](https://user-images.githubusercontent.com/1755886/43356847-22e77084-9270-11e8-80d5-26af4ef16930.png)
![image](https://user-images.githubusercontent.com/1755886/43357262-a52afb8c-9276-11e8-83e3-2b3a5a18e7a5.png)


I guess this is probably one for browsers (to wipe unreferenced contexts before others)?

**Comment by bytesnz** [comment]
I was using purge/newPlot to avoid other issues we were getting. What exactly they were, I will have to test again using just react and let you know. Will close and approach browsers.

**Comment by alexcjohnson** [comment]
OK great - I think it's fair to say that any difference in outcome between `newPlot` and `react` is a bug, so please open a new issue if you encounter such a difference!

**Comment by etpinard** [comment]
> I think it's fair to say that any difference in outcome between newPlot and react is a bug,

Hmm, not quite. `react` _should recycle WebGL contexts, `newPlot` won't.

**Comment by gnestor** [comment]
Replacing Plotly.newPlot with Plotly.react also worked for us 👍: https://github.com/stencila/stencila/issues/687

**Comment by Delong-Yang** [comment]
Hi, 
I am with plotly.js 1.48.3, change to Plotly.react alleviate the issue, but after moving mouse over 40-50 times, the chart still disappears.

**Comment by bidva** [comment]
have a similar issue but I'm using React component and get this warning, I have a page that renders about 20 plots and old ones break after rendering new ones
