### ISSUE TITLE
plotly can't display negative bars from matlotlib figures

### ISSUE THREAD

**Issue by windflower715** [plotly/plotly.js#2853]
I ran into a an issue with tls.mpl_to_plotly(matplotlib_figure) The matplotlib figure has negative value, and it plots fine.

However, when I convert it to using tls.mpl_to_plotly, the negative bars will become positive, and I really don't know how to solve it.

I have tried to set ['layout']['barmode'] ='relative', which didn't help. Could any provide any suggestions on how to fix this?

Your help is greatly appreciated!

**Comment by etpinard** [comment]
Please port `mpl_to_plotly` questions on https://community.plot.ly/c/api/python
