### ISSUE TITLE
Bug: overlays not defined (1.39.3)

### ISSUE THREAD

**Issue by rwinston** [plotly/plotly.js#2855]
Hi 

I believe I have found a regression between 1.39.2 and 1.39.3. When running a plot with a secondary y-axis, makeSubplotData() throws an error as overlays is not defined for mainplotinfo

```
if(mainplot !== id && mainplotinfo) {
            // link 'main plot' ref in overlaying plotinfo
            plotinfo.mainplot = mainplot;
            plotinfo.mainplotinfo = mainplotinfo;
            // fill in list of overlaying subplots in 'main plot'
            mainplotinfo.overlays.push(plotinfo); // <- error here
        } 
```

I have a reproducible CodePen below -- if you change the plotly version to 1.39.2 it will work

[https://codepen.io/roryw/pen/oMpNwX](https://codepen.io/roryw/pen/oMpNwX)

I believe this is due to the cleanup in pull request #2831 (https://github.com/plotly/plotly.js/pull/2831), I am not overly familiar with the code - but it looks to me as if an initial assignment of overlays may now be missing in the cartesian object init code somwehere...

Cheers
-- Rory

**Comment by etpinard** [comment]
Ha. Thanks for the report.

I didn't know you could overlay a `yaxis` over a `yaxis2`.
