### ISSUE TITLE
Add zoom buttons to Mapbox plots

### ISSUE THREAD

**Issue by maxwell8888** [plotly/plotly.js#2856]
Is it possible to add zoom controls to the hoverbar for Mapbox plots? I have had complaints from users that they couldn't work out how to zoom in and out of my Mapbox charts.
Regular Plotly maps have + - zoom buttons in the hoverbar - see screenshot from https://plot.ly/javascript/scatter-plots-on-maps/:
![image](https://user-images.githubusercontent.com/28952593/43389984-0ad256dc-93e5-11e8-89f3-433bf231f0f3.png)
However, these buttons don't seem to be available in Mapbox plots - see screenshot from https://plot.ly/javascript/scattermapbox/:
![image](https://user-images.githubusercontent.com/28952593/43390144-66154536-93e5-11e8-80c0-5012a50a823a.png)

**Comment by zoohair** [comment]
any ETA on this :) ?

**Comment by johnWilshire** [comment]
This would be really useful feature.

**Comment by etpinard** [comment]
done in https://github.com/plotly/plotly.js/pull/4398
