### ISSUE TITLE
Sankey separator

### ISSUE THREAD

**Issue by simonerubiu** [plotly/plotly.js#2859]
Hi there,
I need to set the decimal and thousands separators in sankey chart, I found out the layout.separators option that works for other kind of charts, but when I use this options in sankey nothing happen.
I think this is a bug, can you explain me how to fix this issue?? or if there is a branch where this issue is just resolved.

Thanks in advance ;)

**Comment by alexcjohnson** [comment]
Thanks @simonerubiu - You're correct that our Sankey diagrams don't currently support `layout.separators`, and you're correct that this is a bug :)

Unfortunately our number formatting code is a bit chaotic at the moment, and ripe for refactoring... There's [`Lib.numSeparate`](https://github.com/plotly/plotly.js/blob/0c1d6d5ebbd2334f712aede2a32236fb451838b7/src/lib/index.js#L902) that handles separators for simple floating-point representations, [`axes->numFormat`](https://github.com/plotly/plotly.js/blob/0c1d6d5ebbd2334f712aede2a32236fb451838b7/src/plots/cartesian/axes.js#L1242) that handles rounding and exponents along with separators but is tightly coupled to cartesian axes, and [`fullLayout._d3locale.numberFormat`](https://github.com/plotly/plotly.js/blob/0c1d6d5ebbd2334f712aede2a32236fb451838b7/src/plots/plots.js#L371) for using d3 format strings (including localization and override by `layout.separators`)

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
