### ISSUE TITLE
`visible: true` ignored if x, y data arrays are empty

### ISSUE THREAD

**Issue by seansfkelley** [plotly/plotly.js#2861]
When rending a trace with no data, it can be desirable to always show a legend item even if there are no data points. (Example: user-editable data; if the user deletes all the data it would be nice to stay consistent and just show an empty trace with a legend entry.)

I thought this was possible with `visible: true`, but that appears to not be the case. See [this example](https://codepen.io/anon/pen/LBQqpj?editors=0010#0) for more (add values to `x` and `y` and note that the legend pops in along with the data, i.e., it is not present if the data is not present).

https://github.com/plotly/plotly.js/issues/1310#issuecomment-273496652 suggests this would be desirable behavior, but I see no other issues mentioning it.

**Comment by etpinard** [comment]
Thanks for writing in! I think what https://github.com/plotly/plotly.js/issues/1310#issuecomment-273496652 is suggesting should be considered a breaking change and should probably be added to our v2 wishlist in #420. 

In the meantime, I think setting `x` and `y` to `[null]` as in https://codepen.io/etpinard/pen/MBVorO?editors=0010#0 is the simplest workaround available (unfortunately).

**Comment by seansfkelley** [comment]
Alright, I'll do that for now. I'll leave this issue open so you can move/close at your discretion.

**Comment by sorenwacker** [comment]
I think I have that same problem. Trying do create an animation frame where dates are inconsistently distributed.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
