### ISSUE TITLE
scatter3d.line.showscale doesn't show a colorscale

### ISSUE THREAD

**Issue by jonmmease** [plotly/plotly.js#2862]
This report is a translation of https://github.com/plotly/plotly.py/issues/1085

It seems that the `scatter3d.line.color` and `scatter3d.line.colorscale` properties can be used to specify a line with a variable color along it's path (which is awesome!).  There is also as `scatter3d.line.showscale` property in the schema, but setting this to `true` does not show a colorscale.

Not sure if the bug is the scale not showing, or the presence of the `showscale` property. Thanks!

Codepen: https://codepen.io/anon/pen/vaRLgy

```javascript
x = [0, 0, 0]
y = [1, 1, 1]
z = [1, 2, 3]
c = [0, 1, 2]
var trace1 = {
    type: 'scatter3d',
    x: x,
    y: y,
    z: z,
    mode: "lines",
    line: {
        color: c,
        showscale: true,
        width: 10
    }
}


var data = [ trace1 ];

var layout = {};

Plotly.newPlot('myDiv', data, layout);
```

![screen shot 2018-08-01 at 5 28 15 am](https://user-images.githubusercontent.com/15064365/43513446-bbc146a8-954b-11e8-8548-149f6ff7a0ec.png)

**Comment by etpinard** [comment]
Good catch @jonmmease !

`line.showscale` was added in the scatter3d attributes since the first scatter3d `line.colorscale` PR (-> https://github.com/plotly/plotly.js/pull/617), but never got implemented.
