### ISSUE TITLE
Issue in Sankey Plot: Error in proposed[["hoveron"]]

### ISSUE THREAD

**Issue by KoningD** [plotly/plotly.js#2864]
The first ever issue I propose!

While trying to make my own Sankey Plot, I got an error. Tried the code with the example mentioned on the plotly website: https://plot.ly/r/sankey-diagram/#basic-sankey-diagram under Add Links. It gives me the same error:

Error in proposed[["hoveron"]] : subscript out of bounds

I tried it with the following versions: 
r version 3.5.1, plotly_4.8.0
r version 3.4.2, plotly_4.8.0

I hope this is all the information you need and it provides a reproducible example! 

Thank you so much for taking this issue into account!

**Comment by etpinard** [comment]
That looks like an issue for https://github.com/ropensci/plotly/issues/new

**Comment by cpsievert** [comment]
Thanks @KoningD! Ported to https://github.com/ropensci/plotly/issues/1315
