### ISSUE TITLE
Incorrect Mesh3d trace intensity updating with Plotly.restyle

### ISSUE THREAD

**Issue by timmclennan** [plotly/plotly.js#2866]
I was attempting to change the displayed values of a _mesh3d_ trace using _updatemenus_ with the _intensity_ attribute.

When the button is clicked the color of the mesh switches to black.

Looking into it in a bit more detail, the same thing occurs with a direct _Plotly.restyle_ call. _Plotly.react_ on the other hand does update the color values as intented.

An example of this can be seen in the following codepen:
https://codepen.io/anon/pen/WKzqzo

A similar effect happens with the _surfacecolor_ attribute of _surface_ traces but rather than going to black they end up displaying as the minimum color on the colormap.

**Comment by etpinard** [comment]
Here's a working version https://codepen.io/etpinard/pen/WKyoyP?editors=1010

You need to wrap update arrays into another array of len corresponding to the number of traces. See https://plot.ly/javascript/plotlyjs-function-reference/#plotlyrestyle for more info.
