### ISSUE TITLE
Implement arrayOk textposition for scatter3d traces

### ISSUE THREAD

**Issue by jonmmease** [plotly/plotly.js#2872]
Second issue reported in https://github.com/plotly/plotly.py/issues/1055

CodePen: https://codepen.io/anon/pen/EpRrVq

When the `textposition` property of the `scatter3d` trace is set to "middle left", the text position responds as expected:

`textposition: "middle left"`

![screen shot 2018-08-04 at 7 17 23 am](https://user-images.githubusercontent.com/15064365/43675952-a1ad772e-97b6-11e8-9a91-54ce559f33c7.png)

However, when the `textposition` property is set to an array of valid strings, the positions are ignored:

`textposition: ['top center', 'middle left', 'bottom center', 'middle right']`

![screen shot 2018-08-04 at 7 17 36 am](https://user-images.githubusercontent.com/15064365/43675966-dcc43c76-97b6-11e8-98b8-eef4dd65b614.png)

I checked the schema and the `arrayOk` property is set to true for this property. Also, this array of `textposition` values works as expected for the 2d `scatter` trace.

**Comment by etpinard** [comment]
Looks like `arrayOk` support for `textposition` in `scatter3d` trace never got implemented:

https://github.com/plotly/plotly.js/blob/41d870bca6049c7f7d102d5290e2425aa32fd8cf/src/traces/scatter3d/convert.js#L236-L240

I'll make a quick PR to update the attributes accordingly, but I'll tag this ticket as a feature request.
