### ISSUE TITLE
Display value or text inside bubble

### ISSUE THREAD

**Issue by GopalakrishnanKandasamy** [plotly/plotly.js#2875]
Hi, I'm working on a project where i need to display the text or a value inside a bubble like the image given below. Anyone has done this before? 
![screenshot from 2018-08-06 18-33-53](https://user-images.githubusercontent.com/20788836/43718200-8dddbb4e-99a7-11e8-9a83-a01093f4e703.png)

**Comment by alexcjohnson** [comment]
See https://plot.ly/javascript/line-and-scatter/#data-labels-on-the-plot
Omit `textposition` to leave the text centered.
