### ISSUE TITLE
Localizing modeBarButtons?

### ISSUE THREAD

**Issue by booleanbetrayal** [plotly/plotly.js#288]
Is there a recommended way of doing this? Note that I don't want to change any functionality of the buttons, just update the `title` values.

**Comment by nbrustein** [comment]
+1

**Comment by barillax** [comment]
+1

**Comment by booleanbetrayal** [comment]
looks like maybe the simplest solution is to have the `modeBarButtons` config option support hashes, merging those hashes with the default options when assembling in [`fillCustomButton`](https://github.com/plotly/plotly.js/blob/34438d713f9eb806f8e3afafbc89b561bbd52529/src/components/modebar/manage.js#L211-L213)?

**Comment by mattblang** [comment]
+1

**Comment by booleanbetrayal** [comment]
Also ran into some more localization issues revolving d3 time / number formatting. See also: 58049fa59ad6227f155128e428322d2a89d7d0d3 . Seems like we need a more robust general solution.

**Comment by jackparmer** [comment]
I just sent an email to some of you folks since it looks like you all work at Pedago.
Feel free to fill out this form: 
https://plot.ly/products/enterprise/get-in-touch/
If this is blocking your work and you would like to talk more seriously about adding this. Its not in our near-term roadmap otherwise.

**Comment by keodime** [comment]
I investigate and I arrive to the same conclusion than booleanbetrayal.  

For a real fix, it looks like maybe the simplest solution is to have the modeBarButtons config option support hashes, merging those hashes with the default options when assembling in fillCustomButton

or else simply export modebarButtons like Icons. that way we could do something like that :

modeBarButtons: [[{
                        name: Plotly.modeBarButtons.toImage.name,
                        title: 'max was here',
                        click: Plotly.modeBarButtons.toImage.click,
                        icon: Plotly.modeBarButtons.toImage.icon
                }]]

That way we would be free to localize by our own.

**Comment by etpinard** [comment]
moved to https://github.com/plotly/plotly.js/issues/856
