### ISSUE TITLE
scatter3d error bars not displayed unless `error_z` is defined

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#2881]
If you look at this Pen https://codepen.io/nicolaskruchten/pen/QBZaYE you'll see two problems:

1. Error bars don't display unless `error_z` is there (i.e. just `x` or `y` or both gives broken output)
2. `thickness` doesn't seem to do anything

This seems to be true for the latest version as well as 1.38.0, which I randomly tested.

**Comment by etpinard** [comment]
cc @antoinerg

**Comment by antoinerg** [comment]
PR #3011 doesn't fix the problem with thickness. The problem lies with `gl-error3d` so I opened an issue over there: https://github.com/gl-vis/gl-error3d/issues/5

**Comment by antoinerg** [comment]
The issue with scatter3d `thickness` parameter now has its own separate issue #3014.
