### ISSUE TITLE
scatterpolargl in 'lines' mode smears on axis rotation

### ISSUE THREAD

**Issue by jonmmease** [plotly/plotly.js#2888]
For a `scatterpolargl` trace in `lines` `mode`, when the axes are rotated by clicking and dragging on an axis label, the lines smear across the plot. The smearing is removed on release:

CodePen: https://codepen.io/anon/pen/MBzLKp

Rotation example:
![scatterpolargl_smearing](https://user-images.githubusercontent.com/15064365/43892568-4b3381d0-9b9a-11e8-9a4c-0eeecea013b0.gif)

FWIW, this doesn't occur in `markers` `mode`.

**Comment by alexcjohnson** [comment]
But it's so pretty :)

Confirmed - in fact, doesn't seem to happen in `lines+markers` mode, only in `lines` with or without `fill`

**Comment by etpinard** [comment]
Thanks for the report @jonmmease !
