### ISSUE TITLE
`tick0` in geo axes is broken

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#2896]
This pen https://codepen.io/nicolaskruchten/pen/MBxaNq?editors=0010 shows that setting `tick0` for latitude/longitude axes doesn't seem to do much.

**Comment by etpinard** [comment]
Playing around with [`d3.geo.graticule`](https://github.com/d3/d3-3.x-api-reference/blob/master/Geo-Paths.md#_graticule) settings that we're currently using here:

https://github.com/plotly/plotly.js/blob/e545415463730291201e0adadb876874680c4361/src/plots/geo/geo.js#L659-L673

does not seem to do anything.

We should instead try to :hocho: that `d3.geo.graticule` call and build our own set GeoJSON line datum for this purpose.
