### ISSUE TITLE
Running tests on windows

### ISSUE THREAD

**Issue by Hypercubed** [plotly/plotly.js#29]
Anyone else having issues running the karma tests?  First issue I had was the `tasks\util\shortcut_paths.js` transform (invalid directory delimiter for windows).  That was easy to fix.  But even after this `npm test` produces the error `ReferenceError: Can't find variable: require`.  Looks like `karma-browserify` is not working as expected.

**Comment by Hypercubed** [comment]
I am confident that this is an issue with karma-browserify on windows.  I'll reopen if I find otherwise.

**Comment by Hypercubed** [comment]
There were two issues preventing `npm run test-jasmine` on windows:

1) karma-browserify had a bug (Fixed in https://github.com/nikku/karma-browserify/pull/154).
2) On windows (or cygwin) paths generated by the `requireTransform` browserify transform contain platform-specific file separators (patch is coming).

**Comment by etpinard** [comment]
fixed in https://github.com/plotly/plotly.js/pull/46
