### ISSUE TITLE
scattergl errorbars sometimes don't appear

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#2900]
There are a number of path-dependent issues with changes to `mode` and errorbars in `scattergl` traces. All of these investigations start from the [`gl2d_error_bars`](https://rreusser.github.io/plotly-mock-viewer/#gl2d_error_bars) mock. Regular `scatter` traces can show errorbars even if `mode='none'` ie everything else is hidden:
![scatter-none](https://user-images.githubusercontent.com/2678795/44064291-3cf1db12-9f32-11e8-81cf-08891e2e8fa3.png)

If I just load that mock and `restyle(gd, 'mode', 'none')` everything disappears:
![scattergl-none](https://user-images.githubusercontent.com/2678795/44064411-d7243806-9f32-11e8-9387-ed20f3103ffc.png)

But if I first change to `type: 'scatter', mode: 'none'` and then go back to `scattergl` the errorbars are still there:
![scattergl-none-from-scatter](https://user-images.githubusercontent.com/2678795/44064352-9bf60980-9f32-11e8-9a5e-bacf3273e53e.png)

Other mode changes can create all sorts of oddities (including different behavior for orphan points):
![scattergl-lines](https://user-images.githubusercontent.com/2678795/44064470-1b53f4b2-9f33-11e8-991f-01479a612e55.png)
![scattergl-markers](https://user-images.githubusercontent.com/2678795/44064474-2122b982-9f33-11e8-88db-c6deaf9d6e03.png)
![scattergl-markers-2](https://user-images.githubusercontent.com/2678795/44064478-24611670-9f33-11e8-841f-4363925d91ec.png)

cc @etpinard @dy

**Comment by nicolaskruchten** [comment]
see also #2882 and #2881 in case they're related :)

**Comment by alexcjohnson** [comment]
Huh, I don't see the error messages @etpinard mentioned in #2882 (either here or in your codepen) though I do see the bug. Very likely related. #2881 I suspect is independent.

**Comment by archmoj** [comment]
[codepen](https://codepen.io/MojtabaSamimi/pen/bGGYQKG?editors=0010) to illustrate the bug.

**Comment by archmoj** [comment]
:tada: Fixed by in [v1.54.2](https://github.com/plotly/plotly.js/releases/tag/v1.54.2) via https://github.com/plotly/plotly.js/pull/4881.
