### ISSUE TITLE
Aster Plot Feature

### ISSUE THREAD

**Issue by Buttars** [plotly/plotly.js#2901]
Hi all,

Have you considered implementing an Aster plot to your list of charts?

Aster plots are criminally underused.

They can show the proportion each section is comprised of while showing progress in each section.

![image](https://user-images.githubusercontent.com/17345308/44067980-32b15850-9f35-11e8-8c3c-2d5ab1396640.png)

An example of the popular math learning website Aleks. The thickness of a given slice is proportional to the number of "topics" in a category relative to the total number of topics. The radius of a slice is the number of topics that a user has completed proportional to the number of topics in that category. 

It's a really easy way to display a lot of data at a glance.

**Comment by Buttars** [comment]
@dwoodard

**Comment by alexcjohnson** [comment]
Interesting, kind of a mix of pie and the upcoming `barpolar` #2810. No, I hadn't seen this before, thanks for bringing it up.

It suffers from the same ambiguity as `barpolar` will, about whether data is encoded in radius (to be precise, radial thickness) or in area (or perhaps area fraction). In contrast the [Marimekko chart](https://www.contextures.com/excelmarimekkochart.html) is unambiguous in this regard, for displaying the same kinds of data. But people like circles, whatcha gonna do. Anyway Marimekko is also [not yet implemented here](https://github.com/plotly/plotly.js/issues/2221).

**Comment by spicynaresh** [comment]
is it implemented Aster Plot feature

**Comment by Buttars** [comment]
Here's some docs for an aster plot implemented in D3 http://bl.ocks.org/bbest/2de0e25d4840c68f2db1

**Comment by spicynaresh** [comment]
Hi thanks for informing me
Im not able to implement this graph with all arcs of "same width"
Based on input data outer radius of each arc is resulting in asterplot
graph, but widths of all arcs should be same

**Comment by spicynaresh** [comment]
perfect aster plot graph in d3.js https://d00d3.codesandbox.io/

**Comment by Buttars** [comment]
@spicynaresh Super sweet implementation! The aster plot I am requesting would also have the ability to make each section's width proportionate respectively.

**Comment by spicynaresh** [comment]
https://codesandbox.io/s/github/spicynaresh/React-d3-asterplot 
hear is the updated graph with hover effect,we expect this aster plot graph implementation in plotly

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
