### ISSUE TITLE
Multiple issues with transforms

### ISSUE THREAD

**Issue by dmt0** [plotly/plotly.js#2908]
I’ve been trying to add transforms to multiple trace types with varying degrees of success. Documentation doesn’t make it clear which trace types support transforms. All I know from discussion with @etpinard, is that anything that takes 2d arrays as input doesn’t support them.
`react-chart-editor` as of now does not prepopulate target/targetsrc:

```
      "transforms": [
        {
          "type": "filter",
          "target": [],
          "targetsrc": null
        }
      ]
```

**Results:**

scatter3d: 
- filter: many warnings: `[.Offscreen-For-WebGL-0x7fef4b0d6800]RENDER WARNING: Render count or primcount is 0.`

-> https://codepen.io/etpinard/pen/dgWJZg

scatter3d + marker:’line’
- filter: `Uncaught (in promise) TypeError: Cannot read property 'slice' of undefined
    at LinePlot.proto.update`

-> https://codepen.io/etpinard/pen/Edmobo

cone, streamtube, scattergeo, table, heatmap (with 1d array input), contour (with 1d array input)
- any transforms: as I add them to `data`, they never get added to `fullData`

choropleth, scatterternary, scatterpolar, pie:
- aggregate: `Error while plotting: TypeError: Cannot set property 'type' of undefined at Object.plots.supplyTransformDefaults`

pie:
- filter: `Error: <path> attribute d: Expected number, "MNaN,NaNa189.5,18…".`

-> https://codepen.io/etpinard/pen/wYdppB

2d contour histogram:
- filter: `Error while plotting: TypeError: Cannot read property 'length' of undefined
    at makeCrossings (plotly-with-meta.js?ab3a:146042)`

**Edit:**
Add this one to the list:
- When defining a `scatter` with just Y defined, and than add an aggregate:
`Uncaught TypeError: Cannot set property 'type' of undefined
    at Object.plots.supplyTransformDefaults`
https://codepen.io/dmt0/pen/xJoWoY

This one got **fixed in:** #3093

**Comment by etpinard** [comment]
Ok. Thanks for the report!

What does `targetsrc: null` which isn't a plotly.js attribute) do?. I suspect it injects `target: []` in the user data, but I would like to confirm

**Comment by etpinard** [comment]
But yeah, we could do better than declaring `transforms` in the schema for all trace types  (including the ones that don't support them yet):

https://github.com/plotly/plotly.js/blob/7bba2661c70cf7c83d72262b43c744f2ebd30b2e/src/plots/attributes.js#L160-L167

**Comment by dmt0** [comment]
yes, in fullData I see `target: Array[0]`

**Comment by etpinard** [comment]
`scatterpolar` now looks like:

https://codepen.io/etpinard/pen/YJVYYd
