### ISSUE TITLE
[Feature] Show name of a Pie/Donut in Multi Pie.

### ISSUE THREAD

**Issue by ebellumat** [plotly/plotly.js#2915]
I use `annotations` to put the name of a Pie inside the hole of a donut. But, with a variable number of Pie's, it's very difficult to calculate coordinates. Eventually they get misaligned. You will could include some option to display the name of the pie chart on top, or in the center, rather than just display it on the hover.

![image](https://user-images.githubusercontent.com/26942680/44231066-483bf500-a173-11e8-9456-50ce6ed03e1a.png)

**Comment by alexcjohnson** [comment]
Absolutely, this has come up before, would be very useful!

**Comment by etpinard** [comment]
Done in https://github.com/plotly/plotly.js/pull/2987
