### ISSUE TITLE
`exponentformat` of 'E' does not work with log scaling

### ISSUE THREAD

**Issue by jacobq** [plotly/plotly.js#2919]
When using `layout.yaxis.type = 'log'` the `layout.yaxis.exponentformat` parameter works with `SI`, `power`,  and `none`, but setting to `e` or `E` triggers the `power` behavior. 

See [example here](https://jsbin.com/vopevam)

**Comment by alexcjohnson** [comment]
Ha, we're explicit in the code about treating these the same:
https://github.com/plotly/plotly.js/blob/f9964468d77e6738e9ff88e20f767c52c0c58dce/src/plots/cartesian/axes.js#L1103
But you're right, that's weird. Should be an easy add.

**Comment by jacobq** [comment]
Thanks for investigating (I probably ought to have at least grepped for `exponentformat`). It's not a huge deal (and I personally think the `power` format looks nice), but my client specifically requested that I show these values in `xE+x` format :man_shrugging: .
