### ISSUE TITLE
Updating a geo subplot shouldn't reset its view

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#292]
At the moment, this [block](https://github.com/plotly/plotly.js/blob/a72c6ee0e2ee7b509d9e7785f97c36768e411089/src/plot_api/plot_api.js#L1628-L1630) in `restyle` and this [one](https://github.com/plotly/plotly.js/blob/a72c6ee0e2ee7b509d9e7785f97c36768e411089/src/plot_api/plot_api.js#L2263)  in `relayout` forces a full redraw whenever we update a geo subplot.

We may need to expose a _translation_ projection attribute to secure the view from update to update.

**Comment by etpinard** [comment]
When fixing this, make sure that `plotly_relayout` is fired on pan / zoom etc.

**Comment by brian428** [comment]
Just leaving a +1. Specifically, if the user has zoomed/panned, this seems to be lost after a restyle().
