### ISSUE TITLE
[Performance] Plotly D3 `onAdd` support to Passive Events.

### ISSUE THREAD

**Issue by ebellumat** [plotly/plotly.js#2920]
When i use a lot of Plotly charts on my report page, the Scroll Freezes when the charts are rendering. In my analysis, to improve the performance, it is required to turn on passive events on D3 lib.

Explanation: [Passive event listeners](https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md)
[Passive events comparison before/after](https://developers.google.com/web/updates/2016/06/passive-event-listeners) 

But, the version of D3 what does he use in Plotly JS are v3.5.17, and i don't find the repository to create a Pull request to improve this.

Here the original method used By D3 to create the event
```javascript
function onAdd() {
  var l = wrap(listener, d3_array(arguments));
  onRemove.call(this);
  this.addEventListener(type, this[name] = l, l.$ = capture);
  l._ = listener;
}
```

And here, my improvement.
```javascript
function onAdd() {
  var supportsPassive = false;
  try {
    var opts = Object.defineProperty({}, 'passive', {
      get: function() {
        supportsPassive = true;
      }
    });
    window.addEventListener("testPassive", null, opts);
    window.removeEventListener("testPassive", null, opts);
  } catch (e) {}
  var l = wrap(listener, d3_array(arguments));
  onRemove.call(this);
  this.addEventListener(type, this[name] = l, l.$ = { passive: supportsPassive, capture });
  l._ = listener;
}
```

How can i solve this? This improve performance a lot, but i don't find the repo of D3 at this version.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
