### ISSUE TITLE
Points are deselected on zoom in scattergl

### ISSUE THREAD

**Issue by deto** [plotly/plotly.js#2926]
If you select points on a scattergl, then deselect with a double-click, and then zoom, the styling on the points reverts back to 'unselected'.

To reproduce:  on the scattergl example with 100k points (https://plot.ly/python/webgl-vs-svg/)

1.  Box select some points
2.  Double-click to deselect
3.  Zoom in or out (note point style changes)

Doesn't appear to happen on a type: 'scatter' plot, only 'scattergl'.

**Comment by etpinard** [comment]
This was fixed in https://github.com/plotly/plotly.js/pull/2815 and released in `v1.40.0`. 

The example on https://plot.ly/python/webgl-vs-svg/ will be fixed once the 1.40.0 propagates to our API libraries and cloud services
