### ISSUE TITLE
How to place a shape onto a second domain area?

### ISSUE THREAD

**Issue by ProgrammingLife** [plotly/plotly.js#2928]
I have two domain areas. If I define a shape it places on the first domain but I wanna place it on the second one. How to do it?

**Comment by etpinard** [comment]
Our github issue tracker is reserved for bug reports and feature requests only.

I invite to read https://plot.ly/javascript/reference/#layout-shapes-xref or use https://community.plot.ly/c/plotly-js for questions of the likes.
