### ISSUE TITLE
[Help] How can i change the outside text color of a Pie/Donut?

### ISSUE THREAD

**Issue by ebellumat** [plotly/plotly.js#2937]
Hi! I use an layout with Dark Mode. When i show a Pie Chart With a Small size, the info is shown outside of a Pie Chart. How can i change these colors?

![image](https://user-images.githubusercontent.com/26942680/44465566-587d2580-a5f4-11e8-836b-d7476ef88393.png)

**Comment by alexcjohnson** [comment]
Check out https://plot.ly/javascript/reference/#pie-outsidetextfont
Please direct "how to" questions to https://community.plot.ly/c/plotly-js so we can reserve github for feature requests and bug reports. Thanks!
