### ISSUE TITLE
request: special representation for null values

### ISSUE THREAD

**Issue by RichardNeill** [plotly/plotly.js#2941]
Consider a bar chart, there is currently no way to distinguish between "this bar is zero height", and "there is no bar here". Currently, plotly does the most sensible thing it can:  e.g. x=4,y=0 will be plotted (except for a bar chart where the height is invisible), whereas x=4,y=null will be ignored.

I'd like to propose an additional idea for null-handling, as a new option for the layout:
   shownullmarker:  true
   nullmarker { symbol: 'triangle-up' }

If this is set, then
 - regardless of chart type (bar,line,bubble etc), a null value will be plotted as if it had y=0, but with the different markersymbol
 - connectgaps should still ignore nulls  (this is one of the problems with casting null to zero!)
 - the tooltip should label it as "[Null]" rather than "0".
 - the symbol should default to a different color (I suggest f8f8f8 with 222222 border).
 - null points are excluded from spikelines.

Thanks very much.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Comment by RichardNeill** [comment]
Hello. Yes, this issue is still relevant. Please re-open.

As a workaround, I add a text label "zero" just above the axis for the "zero-height" bars, and then I am happy to leave the "null" bars as not plotted.

i.e. i
f (y === 0){ textposition = "outside"; text="zero"; textcolor="#88888" }
