### ISSUE TITLE
Getting an error when running npm install plotly.js

### ISSUE THREAD

**Issue by Michaelzvu** [plotly/plotly.js#2952]
It happens to 1.39.0 and above..
npm ERR! code E404
npm ERR! 404 Not Found: @etpinard/gl-text@^1.1.6

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zvulun/.npm/_logs/2018-08-29T16_49_32_780Z-debug.log

**Comment by etpinard** [comment]
Could you please specify what version of npm you're using? Thank you.

**Comment by Michaelzvu** [comment]
Sure, I am using npm 6.4.0 right now
Tnx

**Comment by etpinard** [comment]
Ok thanks. I can't replicate this unfortunately. 


When you say

> It happens to 1.39.0 and above..

are you running e.g. `npm i plotly.js@1.39.0`? Are you doing so in a fresh directory or one with an existing `node_modules/`?

**Comment by alexcjohnson** [comment]
@Michaelzvu are you behind a proxy by any chance?
https://stackoverflow.com/a/44729575/9188800
> Found out this was caused by my Company's proxy.
>
> The redirection causes the escaped '/' to become un-escaped, so it was hitting https://registry.npmjs.org/@angular/core rather than https://registry.npmjs.org/@angular%2fcore

@etpinard @dy do we still need to be pointing at `@etpinard/gl-text` or can we put it back to `gl-text`?

**Comment by etpinard** [comment]
> do we still need to be pointing at @etpinard/gl-text or can we put it back to gl-text?

I can switch back `@etpinard/gl-text` to `gl-text`, but I'm afraid it won't be enough to solve the problem. `@etpinard/gl-text/` isn't the only scoped npm package in our deps:

![image](https://user-images.githubusercontent.com/6675409/44855535-45dc9f00-ac39-11e8-9352-ef63d7943a12.png)

**Comment by alexcjohnson** [comment]
> I can switch back `@etpinard/gl-text` to `gl-text`, but I'm afraid it won't be enough to solve the problem.

Ah right. Well, we should get back on the main trunk of `gl-text` anyway.

**Comment by Michaelzvu** [comment]
@etpinard @alexcjohnson 
> are you running e.g. npm i plotly.js@1.39.0?
Yes

> Are you doing so in a fresh directory or one with an existing node_modules/?
existing node_modules

> @Michaelzvu are you behind a proxy by any chance?
yep, so I guess this was the issue? and when you are going to switch back to gl-text insead of  @etpinard/gl-text?

Thanks!

**Comment by alexcjohnson** [comment]
#2956 will move us back to `gl-text`, presumably will get finished up next week... but as @etpinard points out there are other scoped packages in our dependencies (and we can't commit to keeping them out since they're becoming more widely used in the community), so it's not clear this will really solve your issue. Lots of people have encountered issues like this, and the only robust solutions I see seem to be at the proxy/network level, eg https://github.com/angular/angular/issues/8422

**Comment by etpinard** [comment]
@Michaelzvu can you try running `npm i plotly.js@1.41.0`?

**Comment by Michaelzvu** [comment]
Yes, it worked thank you very much!
