### ISSUE TITLE
Seemingly cleared selection after drag mode change reappears again

### ISSUE THREAD

**Issue by rmoestl** [plotly/plotly.js#2955]
This is a issue discovered while implementing feature #1852 in PR #2944.

The problem: when creating a selection in lasso / select drag mode, switching to pan or zoom would clean up the visual outlines of the selection. When moving back to lasso / select without a zoom / pan operation and *adding to a selection* by holding Shift lets those seemingly cleared selections reappear.

#2944 has an example attached in a [this comment](https://github.com/plotly/plotly.js/pull/2944#discussion_r213745492). Please also note the `TODO` comments in the code.

**Comment by etpinard** [comment]
Pasting the contents of https://github.com/plotly/plotly.js/pull/2944#discussion_r213745492 for clarity:

-------

![peek 2018-08-29 12-18](https://user-images.githubusercontent.com/6675409/44800973-ca6de580-ab85-11e8-9b85-3d65b334fa99.gif)

Note that the go from select -> pan -> select w/o actually panning. 

Personally, I wouldn't consider this a bug as the "cached" selection outlines are still "correct" (i.e. they are drawn at the correct x/y coordinates). Now, is this the "ideal" behavior, I'm not so sure.

-----------

I like the behavior that we don't clear the selection itself until the last possible moment... but it would certainly be nice if the outline were redrawn when you switch back to a select mode. It's a sufficiently uncommon edge case though that I'd rather not hold up the PR for it - just leave it as is for now and make a new issue to follow up on this later.

**Comment by etpinard** [comment]
cc https://github.com/plotly/plotly.js/issues/1848

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
