### ISSUE TITLE
full default contents of hoverlabel not appearing in _fullData or _fullLayout

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#2964]
If I just create any random figure without specifying anything to do with `hoverlabel` and look at `_fullData[0].hoverlabel` or `_fullLayout.hoverlabel`, I see `font.family`, `font.size` and `namelength` but none of the default values for the color keys like `bgcolor` or `bordercolor` or `font.color`. This makes it hard to add these fields to the `react-chart-editor`.

I expect that the colours for the `_fullLayout` variant should be `null` by default, which would mean "delegate to the individual traces" right? That'll be hard to manage in the editor but we'll find a way :)

While testing this I also found some cases where the hoverlabel text doesn't automatically contrast with the `bgcolor` in a sufficient way ... setting `layout.hoverlabel.bgcolor = "white"` gives this, where issue 1 is that the bottom overlabel doesn't have black text and issue 2 is that the trace-name portion of the label doesn't have black text. Setting `layout.hoverlabel.font.color = "black"` only corrects issue 1.

![image](https://user-images.githubusercontent.com/203523/44963084-d6470800-aef5-11e8-87fe-e4744cf49d6a.png)

**Comment by etpinard** [comment]
In general, we can _just_ punch the "computed" hoverlabel colors during the defaults (and hence in `fullData` w/o hacks). One case that comes to mind: a scatter trace with array `marker.color` will have hover labels that match the `marker.color` values.

**Comment by etpinard** [comment]
Split into https://github.com/plotly/plotly.js/issues/2834#issuecomment-419448118 and https://github.com/plotly/plotly.js/issues/2981

Closing.
