### ISSUE TITLE
Remove `Aa` in legends with text?

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.js#2967]
I've worked on a few client projects with Dash where the client asked that the `Aa` in the legend be removed. To do so, I had to create a set of new traces on top of the existing traces without the `text` key, and then remove the legend item from the original traces, i.e.:

```javascript
[
    {x: [1, 2, 3], y: [3, 1, 2], text: ['a', 'b', 'c'], 'showlegend': false, 'legendgroup': 'trace-1', marker: {color: 'blue'}},
    {x: [1], y: [3], 'showlegend': true, 'legendgroup': 'trace-1', marker: {color: 'blue'}},
]
```

And in the community, some users don't understand why or how the `Aa` appears (https://community.plot.ly/t/dash-legend-label-extrange-behavoiur-scatterplot/13255).

- Could we just remove it by default? I feel like the number of folks that want it removed outweighs the number of folks that see the benefit of having it, although I only have anecdotal evidence. 
- If not, could we make a new key to remove it?

**Comment by eunaka** [comment]
I solved adding to the global style:

g.pointtext {
  display: none;
}

**Comment by etpinard** [comment]
Now in https://github.com/plotly/plotly.js/issues/2967

**Comment by pdfabbro** [comment]
Why would anybody ever want "Aa" to show up in the legend??  Having it blank or configurable should be the default behaviour.

**Comment by z7ye** [comment]
is it issue ever fixed?

**Comment by pdfabbro** [comment]
Nope.

**Comment by z7ye** [comment]
Thanks. 

import plotly.graph_objects as go

fig = go.Figure()
thresh=25
for each in total_vacancy_unit.UnitTypeDescription.sort_values().unique():
    data = total_vacancy_unit.loc[total_vacancy_unit.UnitTypeDescription==each, :].sort_values('DaysVacant%')
    text_list = data.apply(lambda x: x['UnitCode'] if x['DaysVacant%']>=thresh else '' ,axis=1).values
    fig.add_trace(go.Scatter(
        
        x = data['UnitCode'],
        y = data['DaysVacant%'],
        name = each,
        mode='markers+text',
        text=text_list,
        showlegend =True,
#         legendgroup = 'trace-1',
    ))
    fig.update_layout(showlegend=True)

fig.show()

How do I modify my code to remove the 'Aa' please?

**Comment by nicolaskruchten** [comment]
Please note that in the upcoming v2 of the library, this Aa text will no longer appear in the legend: https://github.com/plotly/plotly.js/pull/5682

**Comment by jaimeMontea** [comment]
> Please note that in the upcoming v2 of the library, this Aa text will no longer appear in the legend: #5682

I'm interested. Do you know when it is going to be released? Thanks.

**Comment by nicolaskruchten** [comment]
Working on the release now, should be a week or so
