### ISSUE TITLE
Add support for responsive charts

### ISSUE THREAD

**Issue by antoinerg** [plotly/plotly.js#2969]
In order for charts to look great on any devices/orientation, I suggest that we add the option to resize charts whenever the window's size changes.

For example, it is common for a user to switch his phone from landscape to portrait mode which results in the following unaesthetic/broken result:

![before](https://user-images.githubusercontent.com/301546/45044626-a0616b00-b03e-11e8-9179-786769ca3489.gif)

**Comment by etpinard** [comment]
Good call!

This would probably work best as new [config](https://github.com/plotly/plotly.js/blob/master/src/plot_api/plot_config.js) option (i.e. I don't think this should be a layout attribute).

**Comment by bpostlethwaite** [comment]
This could have interesting implications (I think positively so!) for Plotly's own embed and react-plotly.js 

cc @nicolaskruchten

**Comment by etpinard** [comment]
> basically baking in https://plot.ly/javascript/responsive-fluid-layout/ via a config option?

We could even shoot for moving all the [embedplot](https://github.com/plotly/streambed/tree/master/shelly/embedplot/static/embedplot) logic in plotly.js.

**Comment by antoinerg** [comment]
> even though the window doesn't change size, the containing element does (via a resize operation or a CSS reflow

`ResizeObserver` is a proposal to react to any events that resize a element. However, only Chrome implements it thus far ([caniuse#ResizeOberserver](https://caniuse.com/#search=ResizeObserver)) so we would need to resorts to a polyfill.

In the meantime, I will submit a PR doing what most (if not all) other plotting libraries claiming to be responsive do: simply react to window resize events.

**Comment by antoinerg** [comment]
Closed by PR https://github.com/plotly/plotly.js/pull/2974

**Comment by nicolaskruchten** [comment]
Let's make sure we get this in the documentation as well! :) /cc @cldougl what's the process for doing this?

**Comment by cldougl** [comment]
Yep- you can open an issue in the documentation repo: https://github.com/plotly/documentation/issues
If you have a link to a test or codepen example that exhibits the new feature that would be super helpful to include in the issue.
