### ISSUE TITLE
ScatterGL line flat-lining (with autorange: 'reversed')

### ISSUE THREAD

**Issue by bytesnz** [plotly/plotly.js#2976]
One of the graphs that is being produced in an app I am working on is producing a flat line for one trace  that contains non-flat data using `scattergl` for the graph type. I have placed an example at https://codepen.io/bytesnz/pen/bxNwbj. Having played round with it a little, if I change the graph type to `scatter` it is fine and if I remove the `autorange: 'reversed'` option on the yaxis config, it renders the line correctly. The trace also shares the yaxis with another variable, which renders correctly. Removing the second variable from the axis makes no difference.

Rendered with scattergl
![image](https://user-images.githubusercontent.com/1755886/45161062-df302600-b1e2-11e8-817c-f863a0d49cc0.png)

Rendered with scatter
![image](https://user-images.githubusercontent.com/1755886/45161127-08e94d00-b1e3-11e8-8d37-9f1da3180a82.png)

**Comment by etpinard** [comment]
Thanks for the detailed report.

Merging this ticket with https://github.com/plotly/plotly.js/issues/2904

**Comment by bytesnz** [comment]
Dah. Apologies for the duplicate

**Comment by etpinard** [comment]
> Dah. Apologies for the duplicate

No worries. Issue searching on GH isn't great.
