### ISSUE TITLE
Click event handler not working after a re-plot

### ISSUE THREAD

**Issue by Caesar90** [plotly/plotly.js#2980]
I have a click event handler for the data points on my graph, and they work initially.
However, I have some some controls on top of the graph (as seen in the picture below) that alter the graph by replotting the graph based on the selection made; and the click event handler doesn't work once any of the controls get selected (i.e. once the the graph gets re-plotted).

I need the click event handler to work at all times and I'd appreciate any help on this matter.
![plotly](https://user-images.githubusercontent.com/6764846/45223243-a52c5600-b2ae-11e8-8e3d-b4595cd218cf.PNG)

**Comment by Caesar90** [comment]
The issue was fixed by kinda re-declaring the event handler after every re-plot

**Comment by xanderwallace85** [comment]
> The issue was fixed by kinda re-declaring the event handler after every re-plot

Hi @Caesar90 ,
Did you find a better way to solve this problem?
