### ISSUE TITLE
Hoverlabel custom color bugs

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#2981]
From @nicolaskruchten :

While testing this I also found some cases where the hoverlabel text doesn't automatically contrast with the `bgcolor` in a sufficient way ... setting `layout.hoverlabel.bgcolor = "white"` gives this, where issue 1 is that the bottom overlabel doesn't have black text and issue 2 is that the trace-name portion of the label doesn't have black text. Setting `layout.hoverlabel.font.color = "black"` only corrects issue 1.

![image](https://user-images.githubusercontent.com/203523/44963084-d6470800-aef5-11e8-87fe-e4744cf49d6a.png)

**Comment by nicolaskruchten** [comment]
Pen to show this easily: https://codepen.io/nicolaskruchten/pen/pOdRbo
