### ISSUE TITLE
Implementing the direct use of WMS layer as background data of maps

### ISSUE THREAD

**Issue by TomGeoDK** [plotly/plotly.js#2988]
I tried recently to use WMS (WebMapService) data in plotly. This type of data is pretty much standard when it comes to the use of third party data or pre-processed data (GEO/GIS data).

Pre-processed in this context can mean that original data (usually GTIFF) are tiled at specific zoom levels and stored (usually PNG or JPEG) to be delivered on request of the service user.
I assume mapbox is using this sort of data, and thereby a limited number of background layer is available, but I am missing the opportunity to invoke other background layer than the one offered by mapbox.

There are many WMS services out there, one of them I would like to use is [this one](https://www.kortforsyningen.dk/indhold/webtjenesteliste#) (requires some credentials, but access is free of charge).

**Comment by vpipkt** [comment]
Agree this would be very powerful and add a lot of possibilities to customize.

Related. Documentation on how to add a WMS layer to a mapbox map: https://www.mapbox.com/mapbox-gl-js/example/wms/

**Comment by etpinard** [comment]
Merging into https://github.com/plotly/plotly.js/issues/3592

WMS layers will be available once we make our mapbox `style` API less restrictive.

**Comment by BlackChamberGroup** [comment]
Has this been done?
