### ISSUE TITLE
Giving stroke / border on one specific marker in Pie Chart

### ISSUE THREAD

**Issue by rmdwirizki** [plotly/plotly.js#2989]
I read the doc at [https://plot.ly/javascript/reference/#pie](https://plot.ly/javascript/reference/#pie), it is said that we can provide an array of number (stroke's width) to give on a specific marker in pie chart.
![image](https://user-images.githubusercontent.com/13674295/45299900-29910a00-b537-11e8-8782-aa5eb49c0936.png)
But if we provide an array in "**width**" field like this:
```javascript
var data = [{
  values: [20, 26, 55],
  labels: ['Residential', 'Non-Residential', 'Utility'],
  type: 'pie',
  pull: [0.1, 0, 0],
  marker: {
    colors: ['rebeccapurple', 'purple', 'mediumpurple'],
    line: {
      // WORKS
      // width: 3
      // ERROR
      width: [3, 0, 0]
    }
  }
}];

Plotly.newPlot('myDiv', data);
```
It will produce such an error:
![image](https://user-images.githubusercontent.com/13674295/45300351-4bd75780-b538-11e8-88df-9f0294b3e31b.png)

What i'm trying to achieve is something like this: (harcoded in inspection tools)
![image](https://user-images.githubusercontent.com/13674295/45299967-52190400-b537-11e8-8f98-52d322ea55c5.png)

Codepen Link: https://codepen.io/rmdwirizki/pen/vzdNjp

**Comment by etpinard** [comment]
Interesting. Array `marker.line.width` does seem to work in some case (e.g. in one of our test mock https://rreusser.github.io/plotly-mock-viewer/#pie_style_arrays), but not here.

Thanks very much for the report @rmdwirizki

**Comment by etpinard** [comment]
Ah and this was working in `v1.31.0`: https://codepen.io/etpinard/pen/YOeNer

**Comment by etpinard** [comment]
PR https://github.com/plotly/plotly.js/pull/2117 is most likely the culprit.
