### ISSUE TITLE
Add Jitter to Scatterplot-Points

### ISSUE THREAD

**Issue by jdittrich** [plotly/plotly.js#299]
**Usecase:** Several data points can have the same coordinates – due to chance, measurement resolution or because the data is actually ordinal. Because the points conceal each other, the plot can be misleading as these values are not visualized and thus don't get the visual weight they actually should get. 

**Solution:** Allow jittering the values. (For boxplots, there is already [a jittering option](https://plot.ly/javascript/reference/#box-jitter), however, its jitter is only along an additional, non-measured dimension)

**Comment by mattjvincent** [comment]
Greatly needed!

**Comment by weatherwax** [comment]
I would appreciate this feature too.

**Comment by destradafilm** [comment]
Any updates on this feature? I would also like this feature for scatterplots 'scatter' and 'scattergl'. Thanks!

**Comment by diegollarrull** [comment]
+1 here. 
I would greatly appreciate the option to add jitter to **scatter3d** plots. Right now I'm using **ggplotly** and _geom_jitter()_ for 2D plots, with no analogous in 3D unfortunately.

**Comment by rand5** [comment]
+1 as well

**Comment by HVGupta** [comment]
+1 here, it'd be a very useful feature

**Comment by jackparmer** [comment]
Jitter issue in MPL https://github.com/matplotlib/matplotlib/issues/2750/
Jitter geom in ggplot2: http://docs.ggplot2.org/current/geom_jitter.html
Jitter flag in MATLAB: http://undocumentedmatlab.com/blog/undocumented-scatter-plot-jitter

Any companies out there interested in sponsoring a rigorous look at this for plotly.js and its interface libraries? 
https://plot.ly/products/consulting-and-oem/

**Comment by mshokoohi** [comment]
I would also love this feature too! why isn't it happening?!

**Comment by cristhomas** [comment]
+1

**Comment by r1z1a** [comment]
+1

**Comment by Shians** [comment]
Would love this feature, further than that I'd love a quasi-random implementation that approximates violin plots. https://github.com/sherrillmix/vipor seems like a short and sweet implementation with plenty of flexibility.

**Comment by PPPW** [comment]
+1. Any comments or updates on this issue? Thanks

**Comment by jackparmer** [comment]
@PPPW Looking for a [sponsor](https://plot.ly/products/consulting-and-oem/)

**Comment by eric-czech** [comment]
+1

**Comment by jayleww** [comment]
Also looking for this feature.

Quick fix I used where my x data column was being pulled from a dataframe is below. Adds a random number -0.5 to 0.5 to each x value. Main issue is that it then displays a changed x-coordinate, so if your data is very sensitive at that scale then it would potentially ruin the data.

import np.random

x.apply(lambda n: n+(np.random.random_sample()-0.5)

**Comment by tedstrauss** [comment]
+1

**Comment by return-of-the-mack** [comment]
Please do this!

**Comment by JCGTech** [comment]
+1

**Comment by etpinard** [comment]
Deleting all the +1s.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
