### ISSUE TITLE
scatter3d zooms on scroll even if zoomScroll is false

### ISSUE THREAD

**Issue by antoinerg** [plotly/plotly.js#2998]
See codepen example: https://codepen.io/antoinerg/pen/YOaaaZ

**Comment by etpinard** [comment]
Old news, but true.

related: https://github.com/plotly/plotly.js/issues/143

**Comment by etpinard** [comment]
I don't think we should _fix_ this bug (in v1.x at least), but instead we add a new a config option for 3D scroll zoom (and another for geo scroll zoom). 

Why?

- 3D and geo subplots don't offer another way to zoom into subplot other than scrolling. In other words, scroll zoom isn't as "optional" as for cartesian graphs
- the [`scrollZoom`](https://github.com/plotly/plotly.js/blob/ed39d82a9aa809f1de06f0050572a6d55fb524f8/src/plot_api/plot_config.js#L73) default is currently `false`, so enforcing that `scrollZoom` default in 3D and geo subplots would be a breaking change (unless we add some fancy hacky logic to override the `scrollZoom` default whenever 3D and geo subplots are present on the graph, but this sounds like a nigthmare).

**Comment by etpinard** [comment]
done in https://github.com/plotly/plotly.js/pull/3422
