### ISSUE TITLE
How to create a perfect cube without the triangles as seen in documentation

### ISSUE THREAD

**Issue by mohammedzamakhan** [plotly/plotly.js#3000]
https://plot.ly/javascript/3d-mesh/
<img width="329" alt="screen shot 2018-09-12 at 11 52 53 am" src="https://user-images.githubusercontent.com/2327532/45440631-6c132d80-b682-11e8-946e-74eb8a20db6f.png">

I was trying to create a cube using the example in the documentation, but I do not want the triangles like in the example side which uses i, j, k

I want it to look like a cube but just without the sides having two differentiated triangles

**Comment by mohammedzamakhan** [comment]
@etpinard

**Comment by etpinard** [comment]
Here's perhaps an example better suited for your needs: https://rreusser.github.io/plotly-mock-viewer/#gl3d_cube using `scatter3d` and `surfaceaxis`.

Pro tip: please use https://community.plot.ly/c/plotly-js for questions of the likes in the future so that other users can benefits for them. Thank you

**Comment by jayhaluska** [comment]
Had the some problem. My guess was that it had something to do with the orientation of the triangles.

I played around with the indices of the triangles and now they are gone. My new index values:
```
    i: [7, 0, 0, 0, 4, 4, 6, 1, 4, 0, 3, 6],
    j: [3, 4, 1, 2, 5, 6, 5, 2, 0, 1, 6, 3],
    k: [0, 7, 2, 3, 6, 7, 1, 6, 5, 5, 7, 2],
```

Maybe they example in the documentation can be changed to use these indices? I think most users expect a cube without artifacts.

**Comment by archmoj** [comment]
Please refer to this [demo](https://codepen.io/MojtabaSamimi/pen/xxxBEVL?editors=0010).
cc: @emmanuelle it would be nice to have something similar in our python documentation.

**Comment by rben01** [comment]
This seems like a bug. Surely, by default, the luminosity of a triangle shouldn't depend on the orientation its vertices are specified in?

**Comment by archmoj** [comment]
> This seems like a bug. Surely, by default, the luminosity of a triangle shouldn't depend on the orientation its vertices are specified in?

@rben01 Have you seen `flatshading: true` and `lighting.facenormalsepsilon: 0` options (both should be set) as illustrated in this [demo](https://codepen.io/MojtabaSamimi/pen/xxxBEVL?editors=0010)?

**Comment by astroboylrx** [comment]
@archmoj the demo you mentioned is a single-color cube. Even with that settings in your comment, a cube with a non-uniform intensity still displays triangles.
