### ISSUE TITLE
Issue with fill in stackgroups

### ISSUE THREAD

**Issue by dmt0** [plotly/plotly.js#3003]
`fill: 'tonexty'` (the default when you stack) fills to the other trace even though they’re in different `stackgroups`. Should fill the first *of each stack* to zero.

https://codepen.io/dmt0/pen/dqemWo?editors=0010 newPlot @ 0

**Comment by alexcjohnson** [comment]
Whew, I can make all sorts of fun stuff happen with multiple stackgroups... this example has them out of order in `gd.data`:
<img width="449" alt="screen shot 2018-09-12 at 4 36 31 pm" src="https://user-images.githubusercontent.com/2678795/45451796-29fde200-b6aa-11e8-9432-46907ae3610d.png">
But even if they're in the right order (ie all 'a' group together, then all 'b' group together, then all unstacked) there are still problems right now. Thanks for the report @dmt0!
