### ISSUE TITLE
Template strings in hover data

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.js#3007]
This could include both attributes that exist in the `trace`
```
trace.hovertemplate = '{text}<br>{marker.size} Items<br>{y} Dollars'
```

But also data that is computed on-the-fly by plotly.js, like the bin widths:
```
trace.hovertemplate = 'The number of people between the age of {binleft} and {binright} is {bintotal}.'
```

This means you could express the existing box and violin text with some type of `hovertemplate`

This could span across traces, like the hover data on stacked bars
```
trace.template = 'This represents {trace.y} out of {data.total}'
```

Or one day, perhaps even trace level computations, like the sum of the area
```
texttemplate = 'The sum of the money is {trace.sum}'
```

**Comment by etpinard** [comment]
Very related to https://github.com/plotly/plotly.js/pull/1919 (more precisely https://github.com/plotly/plotly.js/pull/1919/files#r130172295), where Ricky added `nameformat` to allow groupby trace to be names via templates. 

The syntax uses `%{}` to denote values, so we would have:

```
trace.hovertemplate = '%{text}<br>%{marker.size} Items<br>%{y} Dollars'
```

**Comment by nicolaskruchten** [comment]
In terms of the types of output that would be permitted by this, here's an example:

![image](https://user-images.githubusercontent.com/203523/45523748-d6b68d00-b798-11e8-8560-3b034ddf866b.png)

**Comment by nicolaskruchten** [comment]
Note that we'll likely need to bake in some kind of `printf`-style number formatting here as well to control precision, separators etc.

**Comment by nicolaskruchten** [comment]
Here's how Highcharts does it: 

```
tooltip: {
        pointFormat: '<b>${point.y:,.2f}</b> USD'
    },
```

**Comment by nicolaskruchten** [comment]
;) I was mostly pointing at the way they encode separators and precision

**Comment by alexcjohnson** [comment]
> the way they encode separators and precision

Right, that's essentially the same `sprintf` model that python uses, and that we pulled from d3 and already use for various other contexts

https://github.com/plotly/plotly.js/blob/2a3dc2656d3c832ceb24b3c22c9155aa02fd7c7a/src/plots/cartesian/layout_attributes.js#L510-L517

**Comment by antoinerg** [comment]
Should I go ahead and do as Highcharts does: if a variable name is followed by a semicolon, use the remainder as the d3 format string?

${_variable_name_:_d3_format_string_}

@nicolaskruchten @etpinard @chriddyp @alexcjohnson

**Comment by nicolaskruchten** [comment]
...  but the idea of `:` then formatting-language sounds fine to me :)

**Comment by nicolaskruchten** [comment]
Re the syntax of the variable names, the original issue description contains both `y` and `trace.y` ... should we always use `trace.<whatever>` for all trace values, so that we can leave the door open to computed values namespaced under `data.total` or `computed.binleft` or whatever?

**Comment by etpinard** [comment]
I'd vote staying "in-trace" e.g. using `y` not `trace.y`. If users want to compute cross-trace total or other statistics, they could fill those in `customdata` combined with a template string of e.g `%{customdata.total}`

**Comment by etpinard** [comment]
> . like binleft/binright/total (for stacked bars) etc

That would imply exposing some our internal API (mostly from `gd.calcdata`) to users, which probably isn't a bad idea, but making that robust will require a pretty big effort.

Other example of "computed" values, box `q1`, `median`, `q3`, histogram "heights". Violin `kde` is a funny one, as its hover value, isn't even stored in `gd.calcdata`, it is [computed on hover](https://github.com/plotly/plotly.js/blob/97cb217c6588c2246b41983f47c822463e52b59a/src/traces/violin/hover.js#L57-L58).

**Comment by nicolaskruchten** [comment]
right, but right now those make their way into hovertext, so it would be nice to be able to replicate the current hovertext using the new language... i.e. if you like the 'median' but you want to change the way that number is displayed?

**Comment by alexcjohnson** [comment]
Lets just insert these values - per trace type - into the same namespace as the regular trace attributes, and deal with combining the two in the respective hover routines. We don't want to use the same clipped names as in `calcdata` and anyway, as @etpinard points out, that's not even complete. We can describe these options in `attributes.hovertemplate.description` for each type, like "You can refer to any trace attribute, and if that attribute is an array we pick out the value being hovered on. In addition, box traces support calculated attributes *min*, *lowerfence*, *q1*, *median*, *mean*, *stddev*, *q3*, *upperfence*, and *max*"

Box and violin have an extra challenge though: this syntax assumes there's only one *kind* of hover label for a trace. When you have separate labels for each level of the box, each one could in principle get its own formatting. What if you think min and max are obvious so you want only the numbers there, and for quartiles you want `%{q1} (25%)` and `%{q3} (75%)`? Do we need to make a separate template attribute for each of these (`hovertemplates: {q1: '...', q3: '...', ...}`?)
Also an issue for finance types using https://github.com/plotly/plotly.js/pull/2959, and scatter types with `hoveron: 'points+fills'`.

And one more question: currently the hover label formatting can depend on hover mode and occasionally on other traces that also generate hover data. So in "compare" mode normally you only get y data in each trace hover label, and x data sits in the "common label" on the x axis. But in "closest" mode both x and y are in the trace hover label and there is no common label. Occasionally other traces influence this, like if in compare mode if you make two hover labels but they don't quite share the same x, you may get a common label, and only y data in labels for traces that match the common label, but traces that don't match (but are still close enough to generate a hover label) will get both x and y in their labels. So do we just ignore this distinction when there's an explicit `hovertemplate`? Or do we accept two variants of the template somehow? I guess I'm leaning toward ignore but we should be clear about it.
