### ISSUE TITLE
scattergl & fill 

### ISSUE THREAD

**Issue by ErwanMAS** [plotly/plotly.js#3025]
Please look .

https://codepen.io/erwanmas/pen/dqQrbR

The issue is generated by  https://github.com/mapbox/earcut in    https://github.com/a-vis/regl-line2d . AND  **earcut doesn't guarantee correctness** 

https://github.com/mapbox/earcut/blob/master/README.md

a simple **console.log** here https://github.com/a-vis/regl-line2d/blob/b9d56d51e1598c4ee7a9a5e0a733e920daf63c2d/index.js#L520 will output only 1 triangle , instead of 2 triangles

**Comment by etpinard** [comment]
Thanks for the very clear example :microscope: 

I merged your ticket into https://github.com/plotly/plotly.js/issues/2291#issuecomment-422815810, which also discusses scattergl fill `toself` issues.

**Comment by ErwanMAS** [comment]
This not specific to **fill:toself** , you have the same issue with **fill:tozerox** and for **fill:tozeroy**

**Comment by etpinard** [comment]
cc https://github.com/plotly/plotly.js/issues/2284
