### ISSUE TITLE
Double click zoom out behaviour

### ISSUE THREAD

**Issue by pfbuxton** [plotly/plotly.js#3026]
**Moved from plotly.py**

Hello,

Here is a movie of the problem behaviour (taken from https://plot.ly/python/zoom-events/; but it's the same using any plotly):
![temp1](https://user-images.githubusercontent.com/4923588/45748960-24e8e780-bc02-11e8-9a0d-1b5fb09131c7.gif)

1. Zoom in by selecting a region.
2. Zoom out by double clicking.
3. Zoom in by horizontal selection.

The problem is that stage 3 also changes the vertical zoom back to that in stage 1.

**Comment by alexcjohnson** [comment]
Confirmed - thanks for the report @pfbuxton!

**Comment by etpinard** [comment]
Hmm. That's bad. I guess I should try to fix this thing ASAP.

Assigned.

**Comment by etpinard** [comment]
This is a regression that split in 1.40.0, most likely from https://github.com/plotly/plotly.js/pull/2823
