### ISSUE TITLE
Template: options seem not to work (and/or missing documentation)

### ISSUE THREAD

**Issue by IMM0rtalis** [plotly/plotly.js#3032]
**Bug** or **missbehaviour** or **missing documentation**:

When working with the new template property which got introduced with #2761 it looks like some options are not working.

So far I could identify to options which are not working in the template:
```javascript
{
  layout: {
    xaxis: {
      range: [0, 10],
      autotick: false
    }
  }
}
```
But when I put them directly into the layout without template they work as expected:

Not working: https://codepen.io/anon/pen/VGgBRr
Working: https://codepen.io/anon/pen/qMgywj

At least those both are not working, maybe even more. 

For the templates there is no documentation at all (or I am blind) except of the snipped i found here: https://github.com/plotly/plotly.js/pull/2761/files#diff-e08811dc2d34fabaf8eee6ba73afaa01R198
But i can not find a description in https://plot.ly/javascript/reference

Related to: #2469
Maybe @alexcjohnson can tell more

Hope I did not forget anything,
all the best from Berlin

**Comment by etpinard** [comment]
Here's a working version: https://codepen.io/etpinard/pen/ReVgXB?editors=1010

The problem here is: `axis.autotick` is a deprecated attribute (try calling `Plotly.validate([], {xaxis: {autotick: false}})`) which template don't support.

Someone could argue that deprecated attributes should be allowed in templates, but I'd vote :-1: here.

**Comment by etpinard** [comment]
Closing.

If someone puts forward an argument for accepting deprecated attributes in templates, we'll open another issue about then.

**Comment by IMM0rtalis** [comment]
@etpinard Yes, should not be there if it is deprecated anyway! 
Is there an issue for marking it deprecated in the docu yet? Have not seen this notice in the reference yet. 

Also: what about `range`, also deprecated?
