### ISSUE TITLE
Boolean data is autotyped like a number

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#3039]
```js
> Plotly.newPlot(gd,[{y:[true,false,true]}])
> gd._fullLayout.yaxis.type
< "linear"
```
![screen shot 2018-09-21 at 4 31 27 pm](https://user-images.githubusercontent.com/2678795/45904713-d3845800-bdbb-11e8-8c89-1a0b93c7a683.png)

It should be treated as categories instead:
```js
Plotly.newPlot(gd,[{y:[true,false,true]}],{yaxis:{type:'category'}})
```
![screen shot 2018-09-21 at 4 30 09 pm](https://user-images.githubusercontent.com/2678795/45904661-b3549900-bdbb-11e8-96c9-37188b7664d1.png)

**Comment by etpinard** [comment]
Interesting. Quickly bisecting all our releases, this doesn't appear like a regression.

Luckily `Plotly.newPlot(gd,[{y:[true,false,true]}])` gives a blank graph, so we can be confident that no one is "using" the broken behavior in an intended way.
