### ISSUE TITLE
Custom point name issue [scatter3d]

### ISSUE THREAD

**Issue by marcus1812** [plotly/plotly.js#3046]
Hello. As due to my inactivity issue https://github.com/plotly/plotly.js/issues/2884 was closed so i opened a new one.
Here is plotly example: https://plot.ly/~marcus1812/1/
My goal is to see only PointName as name of points of trace: "Overbooking & no shows".

> what with mode: 'markers' you set hoverinfo: 'text+name'?

Its not working

_Originally posted by @marcus1812 in https://github.com/plotly/plotly.js/issues/2884#issuecomment-424293787_

**Comment by etpinard** [comment]
Can you clarify what you mean by "PointName"?

**Comment by marcus1812** [comment]
@etpinard PointName is "MaxPrice", "LastPrice" and etc. You can see that with default hover (x: .. , y:.., z:..) i can set custom name for point, but with custom hover (Day:..,,Cap:...) i cant set custom point name, it copied all text. How can i get both custom PointName and PointHoverText?

**Comment by etpinard** [comment]
... and what do you mean by "name for point"?

I think I know what you're looking for. In plotly.js lingo, you want:

- per-point on-graph text
- hover text that differs from the on-graph text

and here's an example of that: https://codepen.io/etpinard/pen/eLwaaW

**Comment by marcus1812** [comment]
@etpinard it is working now! the problem was in "hovertext" property, i did not set it. Thank you :)

**Comment by etpinard** [comment]
Great. 

Please use https://community.plot.ly/c/plotly-js for questions of the likes in the future.

Thank you.
