### ISSUE TITLE
plot_ly (R) - scatterpolar: plot_bgcolor no effect 

### ISSUE THREAD

**Issue by riccardo92** [plotly/plotly.js#3047]
When using scatterpolar (in the plot_ly R library), plot_bgcolor has zero effect. It simply gives a white plot background Example:

library(plotly)

```
p <- plot_ly(
  plotly::hobbs, r = ~r, t = ~t, color = ~nms, alpha = 0.5, type = "scatterpolar"
)
p <- layout(p, title = "Hobbs-Pearson Trials", plot_bgcolor = toRGB("grey90"))
p
```

with the "scatter" type, this does work. Example:

```
p <- plot_ly(
  plotly::hobbs, r = ~r, t = ~t, color = ~nms, alpha = 0.5, type = "scatter"
)
p <- layout(p, title = "Hobbs-Pearson Trials", plot_bgcolor = toRGB("grey90"))
p
```

I'm using the following version of the lib: plotly_4.8.0.9000.

**Comment by etpinard** [comment]
`plot_bgcolor` only has an effect on cartesian subplots.

You should use https://plot.ly/javascript/reference/#layout-polar-bgcolor

**Comment by alexcjohnson** [comment]
That said it might be nice for polar (and ternary) to inherit `plot_bgcolor` as the default `bgcolor`. Could be nice when you're making a lot of subplots that all want the same background.
