### ISSUE TITLE
Modebar aesthetic configurability

### ISSUE THREAD

**Issue by jackparmer** [plotly/plotly.js#3063]
Would like the modebar to have a few more programmatic options, especially for extremely styled Dash apps:

1. Programmatic ability to set the modebar in a vertical orientation. Bokeh does a nice job with this:
![modebar_vertical](https://user-images.githubusercontent.com/1865834/46306319-f06e1780-c581-11e8-9305-c6e39aed56ee.png)

2. Programmatic ability to set the background bar color, background bar opacity, and icon colors:
![modebar_plotly](https://user-images.githubusercontent.com/1865834/46306345-ff54ca00-c581-11e8-9496-b3b1db390e38.png)

3. While we're at it, update the plotly logo in the modebar

Related: 
https://github.com/plotly/plotly.js/issues/2171 
https://github.com/plotly/streambed/issues/9699
(Perhaps we should create a plotly/plotly.js "modebar" label?)

**Comment by antoinerg** [comment]
Good idea @jackparmer 

I suggest we add the following config key:
```javascript
    // mode bar style
    modeBarStyle: {
        orientation: 'h',
        backgroundColor: 'rgba(255 ,255 ,255 ,0.7)',
        iconColor: 'rgba(0, 31, 95, 0.3);'
    },
```
We should probably turn the icons into a font: it'll then be straightforward to change their color and opacity with CSS.

@etpinard, @alexcjohnson  What do you think?

**Comment by alexcjohnson** [comment]
> ```js
>     modeBarStyle: {
>         orientation: 'h',
>         backgroundColor: 'rgba(255 ,255 ,255 ,0.7)',
>         iconColor: 'rgba(0, 31, 95, 0.3);'
>     },
> ```

I like it. I'd probably go for `bgcolor` just to match our usage in the regular schema. And there are two colors to consider: the logo and all other icons. So `logoColor` and `iconColor`? Also perhaps `position: (top|middle|bottom) (left|center|right)` like `textposition`, though that can be omitted for at least the first round, and added in later if someone is interested in it.

> We should probably turn the icons into a font: it'll then be straightforward to change their color and opacity with CSS.

They *were* a font a long time ago... and in fact that's still how they're given to us when someone designs a new one. but we ditched that and instead just draw them as straight SVG (with a [script](https://github.com/plotly/plotly.js/blob/master/tasks/util/pull_font_svg.js) to pull that out into js) so we have everything encapsulated in the one js bundle. Anyway this is still styled by [css](https://github.com/plotly/plotly.js/blob/master/src/css/_modebar.scss), we'll just need to make some pieces of that dynamic.

**Comment by antoinerg** [comment]
Thanks @alexcjohnson ! So I will go with the following for now:
```javascript  
  modeBarStyle: {
        orientation: 'h',
        bgColor: 'rgba(255 ,255 ,255 ,0.7)',
        iconColor: 'rgba(0, 31, 95, 0.3)',
        logoColor: 'rgba(0, 31, 95, 0.3)',
        position: 'right'
    },
```

Let's keep the pipeline for icons the same for now. I guess I just need to crush the logo into a single path. A tool like this may do the job: https://www.enigmeta.com/svgcrush/ . Can you point me to the most up-to-date plot.ly logo in SVG?

Thank you again for the all the details :)

**Comment by jackparmer** [comment]
@antoinerg This one
https://raw.githubusercontent.com/plotly/design-assets/master/logos/plotly/images/plotly-logomark.svg?token=ABx4ao8iUW7_hNZPRwWUjwgmzVgjGRKgks5bvBthwA%3D%3D

**Comment by nicolaskruchten** [comment]
Just wanting to chime in here a bit and request that these be `layout` options and not `config` options if at all possible... :)

My rationale is that users will often want to control these settings alongside other layout options like the plot background colour and will likely want to drag along these settings in templates etc. If we make these options `config`-only then people will not be able to e.g. use the editor to style the modebar, and will not be able to make "dark theme" templates that can be reused within Chart Studio. Baking these in to `layout` will also likely make things easier for DDK...

/cc @chriddyp @wbrgss

**Comment by jackparmer** [comment]
+1 layout

**Comment by alexcjohnson** [comment]
Thanks @nicolaskruchten, `layout` makes sense. I think we originally put these in `config` as that's where all the other modebar options go, but those are all about altering the functionality of the modebar, which may need to call out to other code on the page or something... whereas the new items are all about appearance and that's not something that depends on the display context so `layout` is better.

**Comment by antoinerg** [comment]
Thank you for your input @nicolaskruchten!

**Comment by nicolaskruchten** [comment]
Nice, thanks for the flexibility, sorry to give this feedback so late :)

Next ask: any way to make some of the behaviour automatic? especially with respect to the figure background? would be great to have the modebar either transparent or match the plot background by default, and to have the icon colours somehow maintain contrast... Even if that's hidden behind a flag I think it would be a nice option that would be turned on by default in the editor :)

**Comment by antoinerg** [comment]
I decided to wait before implementing the automatic behavior described above by @nicolaskruchten and @alexcjohnson. I definitely love the idea though. It could be applied to every bit of text on a figure: title, axes and so on. For example, as of right now, choosing `"paper_bgcolor": "#444"` makes all the text invisible! This sounds like a new feature to me and probably deserves its own issue.

**Comment by nicolaskruchten** [comment]
@antoinerg I'd really like this default behaviour for the modebar background at least... Just because we can't do it everywhere doesn't mean we shouldn't do it in some places: we already do handle automatic contrasting text in places like hovertext, where the foreground color is automatically set based on the background :)

**Comment by antoinerg** [comment]
Sure thing! I didn't know we already had the logic to do that in the codebase :)

**Comment by antoinerg** [comment]
Thanks @etpinard ! @nicolaskruchten's request was super easy to implement with this 😊

Sorry @nicolaskruchten for not realizing how easy this was to do! I'm still learning 😄

**Comment by nicolaskruchten** [comment]
There's never any need to apologize for learning :) Happy that it turned out to be easy!

**Comment by antoinerg** [comment]
> For example, as of right now, choosing "paper_bgcolor": "#444" makes all the text invisible!

@nicolaskruchten Do you think we should now do the same for the title, axes and so on?

**Comment by etpinard** [comment]
> Do you think we should now do the same for the title, axes and so on ie

I'd call that a breaking change.

**Comment by zoohair** [comment]
Should I expect this to work with Dash ? I've tried passing it in the plotly config but doesn't seem to have an effect.

**Comment by antoinerg** [comment]
@zoohair It should work with Dash if you are using plotly.js version `v.1.42.0` or newer!

**Comment by zoohair** [comment]
@antoinerg : I'm on Dash 0.39 which seems to be using plotly-1.45.0.min.js

But still no effect when passing modeBarStyle parameters (e.g. ``` 'modeBarStyle':{'bgcolor': 'red', 'color':'rgba(0,0,0,1)'}```) as part of the config to a `dcc.Graph` element in my layout.

Is there a codepen / minimum example somewhere that illustrates the proper use of modeBarStyle in conjunction with Dash?

**Comment by antoinerg** [comment]
@zoohair The style of the modebar is controlled by attribute `layout.modebar`. The following work has been tested to work properly
```python
    dcc.Graph(
        id='example-graph',
        figure={
            'data': [
                {'x': [1, 2, 3], 'y': [4, 1, 2], 'type': 'bar', 'name': 'SF'},
                {'x': [1, 2, 3], 'y': [2, 4, 5], 'type': 'bar', 'name': u'Montréal'},
            ],
            'layout': {
                'title': 'Dash Data Visualization',
                'modebar': {
                    'orientation': 'v',
                    'bgcolor': 'rgba(0,0,0,0.5)'
                }
            }
        }
    )
```

**Comment by zoohair** [comment]
Thanks @antoinerg : it is a bit confusing since this github issue mentions modeBarStyle, and other modebar configuration (visible icons, hover) is done through the dcc.Graph(config=...) not the layout.


I'm struggling though to find which setting makes it possible for the modebar to be transparent (both my `paper_bgcolor` and `plot_bgcolor` are set to `rgba(0,0,0,0)`). There is a gray background color (that I can't change despite setting modebar's bgcolor, color, or activecolor).

This issue only appeared in more recent Dash updates (likely due to an update to plotly.js - it worked on 1.42.2 but not working on 1.45.0). I remember seeing this reported as an issue in github somewhere but for the life of me I can't find it again 😞 

<img width="224" alt="screenshot" src="https://user-images.githubusercontent.com/430175/53957298-ff925c00-4103-11e9-9cd5-f5f891fdcc68.png">

**Comment by nicolaskruchten** [comment]
@antoinerg have we checked in the latest version of Dash that it's possible to set the modebar background to 100% transparent? I've been seeing a lot of semi-transparent modebar backgrounds in various Dash apps recently.

**Comment by antoinerg** [comment]
@nicolaskruchten I confirm that it is possible to set the modebar background to 100% transparent by setting `layout.modebar.bgcolor` to `rgba(0, 0, 0, 0)`. 

@zoohair the fourth number in a rgba color is the opacity so setting it to 0 should make the modebar transparent. Can you send me the list of layout attributes you're using so I can assist you further?

**Comment by zoohair** [comment]
@antoinerg : my apologies ; As I tried to put together a minimum working example I traced down the issue to a css that was included that was overriding the bgcolor using `.js-plotly-plot .plotly .modebar { background-color: #f2f2f2 } `

It's odd because I've had that there for a while, but things worked as expected (i.e. the background-color did not appear until the mdoebar was hovered on) but not in the new version of plotly.js.

**Comment by tcados** [comment]
I'm still confused similarly to zoohair....
I am able to make the background transparent, but how and where do I change the color of the icons? and how about when I hover over the icons?

Thanks.

**Comment by etpinard** [comment]
@tcados commenting on closed issues isn't the best way to ask for help for this project.

Please use https://community.plot.ly/c/plotly-js - that other plotly.js users will be able to help out or be helped from your questions.

Thank you!

**Comment by kroim** [comment]
How can I put watermark in plotly graph?

**Comment by kroim** [comment]
![image](https://user-images.githubusercontent.com/33049672/74796076-8d119080-5302-11ea-8ae9-410d612466ef.png)

**Comment by luggie** [comment]
Any new thoughts on :
`
'layout': {'modebar': {
                    'position': 'center'
                    }
`
