### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by brubbel** [plotly/plotly.js#3079]
**Description:**
Background updates using `Plotly.redraw()`, while zooming on a plot produce the following error:
`Uncaught TypeError: Cannot read property 'length' of undefined`

![image](https://user-images.githubusercontent.com/5667690/46527736-57494480-c892-11e8-93de-714cfe7ed9e3.png)

**Test case** 
[http://jsfiddle.net/gq9zrhd4/](http://jsfiddle.net/gq9zrhd4/)
The plot is updated every second, so start a box zoom and the errors appear.

(It is possible that this way of updating is not allowed, so is there a correct way to zoom into a (big) plot which is still loading in the background?)

Browser: Chrome Version 68.0.3440.106 (Official Build) (64-bit)

**Comment by etpinard** [comment]
Probably a duplicate of https://github.com/plotly/plotly.js/issues/2687

**Comment by etpinard** [comment]
Merging with #2687
