### ISSUE TITLE
Implement 'intensity' parameter in Surface as in Mesh3D

### ISSUE THREAD

**Issue by gevero** [plotly/plotly.js#308]
**Usercase:** when performing a 3D parametric plot as in [these examples](https://plot.ly/python/3d-parametric-plots/), surface coloring is performed as a function of `z` coordinate. It could instead be useful to add the possibility to perform the surface coloring as a function of a scalar field defined on the surface. An example could be performing the coloring as a function of the distance from the origin `r=sqrt(x^2+y^2+z^2)`.

**Solution:** add an `intensity` parameter, as already present in Mesh3D, also analogous to the `scalars` parameters found in the [mlab **mesh** function](http://docs.enthought.com/mayavi/mayavi/auto/mlab_helper_functions.html#mayavi.mlab.mesh).

**Comment by etpinard** [comment]
@gevero Thanks for writing. 

We've been planning on adding this feature for a while now. It should come online this spring.

**Comment by gevero** [comment]
@etpinard Thanks a lot.
