### ISSUE TITLE
Please publish locales on NPM

### ISSUE THREAD

**Issue by brylie** [plotly/plotly.js#3083]
The Plotly.js locales are not included in the primary NPM package, probably to keep the package size small. This makes it difficult to include the locales in projects that import Plotly.js from NPM. Please publish the Plotly.js locales as one or more packages on NPM, so they can easily be included in packages that use NPM to manage the Plotly.js dependency.

**Comment by etpinard** [comment]
By "primary", I suspect you mean https://www.npmjs.com/package/plotly.js-dist ?

**Comment by brylie** [comment]
Jep. There is a fork on NPM that includes locales, but it hasn't been updated in a year. It might be worth separating locales into their own packages, so they can be selectively included in projects where only a few languages are needed.

**Comment by etpinard** [comment]
Interesting idea @brylie , I thought about adding a `plotly.js-topojson` during https://github.com/plotly/plotly.js/pull/2670, but yeah locale could benefit from having their own npm packages as well.

Locales files aren't that big, so I'm thinking of publishing a single `plotly.js-locales` package and then ask users to require the correct file e.g. `require('plotly.js-locales/fr.js')`.

**Comment by brylie** [comment]
What might it look like using `import`?
