### ISSUE TITLE
[Question/Feature Request] Hide filtered legend items OR provide filtered data/layout for download plots

### ISSUE THREAD

**Issue by Braintelligence** [plotly/plotly.js#3089]
Hello everyone.
So my use-case is removing legend items from a hidden layout of a plot to prepare it for a download. This way people can create plots with a real subset of the original data (without greyed out legend items).

This works for bar and scatter charts, because every trace is its own legend item and you can set `showlegend: false/true` for the trace assigned to the `curveNumber` with the appropriate toggling `visible: true/"legendonly"` state. 

With pie-charts this doesn't work because here every label is a legend item. Even the way to find out which legend item was clicked is completely different because instead of `curveNumber` you now have to watch out for `hiddenlabels`. Not only do these not work with unique identifiers, so filtering equally labeled values is not possible, they leave no way for you to hide their legend entry in an atomic way. All you can do is hide the complete legend of the trace or remove the whole data from the plot by carrying a duplicate data object, which you synchronize to the real plot and then remove hiddenlabels and corresponding values on each legend click. (Which brings me to another problem https://community.plot.ly/t/question-about-click-event-data-for-legends/14428 )

So if plotly would provide a hidden (unused) duplicate filtered data and layout object based on what's filtered **OR** if there would be a layout option like `hideFiltered: true/false` that would remove hidden legend items from the plot entirely (which you naturally would only set for a specific download layout object), I could follow-up with my use-case without creating extra-routines to remove legend items for downloads of the plot.

I'm sorry if there's an easy way out that I missed here and hope it's a legit feature request.

**Comment by nitramwin** [comment]
Hello - I too would find the ability to hide filtered items from the legend as exceptionally useful.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
