### ISSUE TITLE
Full <a><href></a> links in header of Python Dashboard API

### ISSUE THREAD

**Issue by tim-sauchuk** [plotly/plotly.js#3102]
I see there is a "links" feature for the header of a dashboard, but a specific URL is needed. It would be very useful to be able to include entire HTML anchor tags to allow for uses such as mailto links.

**Comment by antoinerg** [comment]
Hello @tim-sauchuk is this a problem related to Dash? If so, you should open issue over [there](https://github.com/plotly/dash)!

**Comment by etpinard** [comment]
Probably not related to this repo. Closing.
