### ISSUE TITLE
Cannot log errors from Plotly into error tracking service

### ISSUE THREAD

**Issue by sporto** [plotly/plotly.js#3105]
Plotly logs some errors using its own logger:

https://github.com/plotly/plotly.js/blob/master/src/lib/loggers.js

This uses `console.error`. I understand that the console has its own exception handling that is not part of the page.

So an error tracking service like rollbar doesn't catch this and thus the error is not logged.

We would like to see those errors in Rollbar so we can investigate them.
Thanks

**Comment by antoinerg** [comment]
Hello @sporto and thank you for your interest in plotly.js!

Is my understanding correct that Rollbar would work if an `ErrorEvent` was fired in the following function (https://github.com/plotly/plotly.js/blob/c922c61234977756d04598a29d448dd7efb74c63/src/lib/loggers.js#L47)?

**Comment by sporto** [comment]
I'm unsure. I tried something like this in the console

```
var error = new ErrorEvent('Oh no', {
    error : new Error('ERROR'),
    message : 'Some message',
    lineno : 402,
    filename : 'index.html'
});

var target = document.getElementsByTagName("body")[0]

target.dispatchEvent(error)
```

Nothing was logged in Rollbar

**Comment by etpinard** [comment]
> I understand that the console has its own exception handling that is not part of the page.

Console errors should be _part of the page_ if you call `Plotly.setPlotConfig({logging: 2})` somewhere before your plot call.

**Comment by etpinard** [comment]
.... which is info our doc pages probably lack at the moment. Thanks for writing in.

**Comment by sporto** [comment]
We added `Plotly.setPlotConfig({logging: 2})` a few days ago. I'm still seeing the error in the console e.g.

```
ERROR: TypeError: Cannot read property 'fillcolor' of undefined
    at SVGPathElement.<anonymous> (plotly-basic.js:19501)
```

But we can't see anything in rollbar yet. So unfortunatelly `logging: 2` hasn't done any difference.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
