### ISSUE TITLE
ENH: Add support for heatmap MapBox layers

### ISSUE THREAD

**Issue by jonmmease** [plotly/plotly.js#3110]
In a [forum post](https://community.plot.ly/t/anything-in-python-plotly-can-create-guardian-heat-map-on-maps/14544) a user asked if there is a way to create heatmap-style plots on a map. e.g.

![55b748a71faa544cd6478eb9aa0c0af59e7adf4d](https://user-images.githubusercontent.com/15064365/47007631-a864fe00-d106-11e8-9410-e529b6316221.jpeg)

It looks like MapBox supports a `heatmap` layer that would support this (See https://www.mapbox.com/mapbox-gl-js/example/heatmap-layer/), so it would be nice to add support for this layer type in the future.

**Comment by nk9** [comment]
Seconded!

**Comment by SterlingButters** [comment]
Thirded

**Comment by inon-peled** [comment]
Definitely useful.

**Comment by etpinard** [comment]
done in https://github.com/plotly/plotly.js/pull/3993 - merged in master via https://github.com/plotly/plotly.js/pull/3987
