### ISSUE TITLE
Inside Bar Text Automatically Rotates

### ISSUE THREAD

**Issue by tim-sauchuk** [plotly/plotly.js#3117]
With a stacked bar chart, when a part of the stack becomes too small, inside positioned text automatically rotates 90 degrees. It would be useful to be able to control whether or not the text rotates.

**Comment by alexcjohnson** [comment]
good idea. Presumably a `textangle` attribute... that at least for outside text could be [anything](https://help.syncfusion.com/dashboard-platform/dashboard-designer/compose-dashboard/configuring-and-formatting-dashboard-widgets/bar-chart):
<img width="418" alt="barchart_showlabelrotation" src="https://user-images.githubusercontent.com/2678795/47099140-a4b6a180-d202-11e8-817e-173c1d88322d.png">
inside text might only support multiples of 90 degrees. Would default to `'auto'` to use the current behavior.

**Comment by etpinard** [comment]
would be useful in upcoming funnel traces too (cc https://github.com/plotly/plotly.js/issues/3504)

**Comment by etpinard** [comment]
@archmoj no _need_ to do this for 1.48.0, but if you find the time ... go for it :ok_hand:
