### ISSUE TITLE
carpet axes with all decreasing data put the axis labels in the wrong place

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#3127]
See https://codepen.io/alexcjohnson/pen/VExvjr?editors=1010
![screen shot 2018-10-18 at 5 31 42 pm](https://user-images.githubusercontent.com/2678795/47185549-b334b400-d2fb-11e8-9e97-c3d18a7c8913.png)
whereas if I reverse all three arrays we get the correct result:
![screen shot 2018-10-18 at 5 32 22 pm](https://user-images.githubusercontent.com/2678795/47185596-d7909080-d2fb-11e8-8b05-8b36658bb776.png)

**Comment by etpinard** [comment]
Other case: https://codepen.io/etpinard/pen/xNmKZp?editors=1010
