### ISSUE TITLE
axis line has different z-index than grid line

### ISSUE THREAD

**Issue by luisrudge** [plotly/plotly.js#3134]
https://codepen.io/anon/pen/ReBLNz?editors=0010

![image](https://user-images.githubusercontent.com/941075/47281696-a8f00f80-d5b2-11e8-8120-6ad3e32cf37c.png)

**Comment by antoinerg** [comment]
Thank you @luisrudge for pointing this out!

In SVG, the rendering order is based on the document order so to change this we would simply need to put the plot after the axis. 

@alexcjohnson Should we change the behavior or was it intended to be this way?

**Comment by alexcjohnson** [comment]
you want [`xaxis.layer: 'below traces'`](https://github.com/plotly/plotly.js/blob/6de004240acfba04987ded259c3511d2526d5240/test/image/mocks/cliponaxis_false.json#L67)
https://github.com/plotly/plotly.js/blob/master/test/image/baselines/cliponaxis_false.png
![screen shot 2018-10-22 at 3 03 24 pm](https://user-images.githubusercontent.com/2678795/47312933-a53ca700-d60b-11e8-9893-abbc2d8cb7ff.png)

**Comment by luisrudge** [comment]
Ops, I guess I missed that option. Thanks! 🎉
