### ISSUE TITLE
Support marker.opacity arrays in scatter3d

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#3138]
So we can get rid of [multiOpacityTransform](https://github.com/plotly/phoenix-integration/blob/d97def8cf21325f1b94b8b4c45cb5d9a8578c715/src/multi-opacity-transform.js#L57)
`scatter3d` traces already support a single-valued `marker.opacity`, and they support opacity as part of a `marker.color` array (which is what this transform makes use of) so it should be pretty easy to add this capability.

**Comment by etpinard** [comment]
> so it should be pretty easy to add this capability.

Not so fast. Mikola wasn't able to this to work. The "opacity" in that multiOpacityTransform hack isn't "true" opacity.  I don't remember the exact details, there should some info in old streambed issues.

**Comment by etpinard** [comment]
Related: https://github.com/plotly/plotly.js/issues/1267

**Comment by alexcjohnson** [comment]
I had an idea about 3D opacity... curious if something like this has been tried before:

We oversample 3D scenes, right? This idea depends on oversampling, and may work better if we increase it. What if instead of trying to model the opacity independently within each pixel, we fill pixels pseudorandomly - ie at 50% opacity we just fill 50% of the pixels at full opacity. Then a point at a different Z value and still 50% opacity fills some different 50% of the pixels, and the depth buffer sorts out ordering just like it does with fully opaque items normally.

The result would be a bit speckled... but averaged over some area (hence the oversampling) it seems like it would look just like real partial opacity. The pseudorandom generator should be a pure function of screen position (x,y,z), but we may want to do something to give it greater uniformity in (x,y) than a real random distribution, to reduce speckle.

@archmoj do you think this sounds plausible?

**Comment by archmoj** [comment]
Seems like a good idea @alexcjohnson 
Let me think about it.

**Comment by archmoj** [comment]
> So we can get rid of [multiOpacityTransform](https://github.com/plotly/phoenix-integration/blob/d97def8cf21325f1b94b8b4c45cb5d9a8578c715/src/multi-opacity-transform.js#L57)
> `scatter3d` traces already support a single-valued `marker.opacity`, and they support opacity as part of a `marker.color` array (which is what this transform makes use of) so it should be pretty easy to add this capability.

@alexcjohnson I wanted to test this with those merged PRs. Then noticed the link provided above is pointing to `phoenix-integration` source code not `plotly.js`.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
