### ISSUE TITLE
hoverinfo:x ignores xaxis

### ISSUE THREAD

**Issue by mojoaxel** [plotly/plotly.js#3144]
I'm not sure if this is a bug or the intended behavior...but if a trace uses the `xaxis` of another series also the x-hoverinfo should be displayed on this common axes!?

![image](https://user-images.githubusercontent.com/600565/47393840-f8544e00-d720-11e8-85a1-195acc68b273.png)

Here is a example:
https://jsbin.com/davagaz/24/edit?js,output

**Comment by etpinard** [comment]
Hmm, interesting. This simple couple subplot layout seem to behave correctly:

https://rreusser.github.io/plotly-mock-viewer/#stacked_coupled_subplots

At first glance, it's not obvious to me what went wrong in you codepen. We'll need to spend some time trying to isolate the problem.

**Comment by alexcjohnson** [comment]
@etpinard they're both behaving the same way - we're displaying the common label at the bottom of the subplot you're hovering on, but what @mojoaxel would prefer is that we display the common label where the tick labels are, which is the bottom of the upper subplot.

Seems like a reasonable desire, though I can see arguments either way. Our current behavior has the advantage of keeping the common label closer to the data point you're actually hovering on, the proposed way keeps the common label consistent across all subplots and aligned with the tick labels.

**Comment by mojoaxel** [comment]
> Seems like a reasonable desire, though I can see arguments either way. Our current behavior has the advantage of keeping the common label closer to the data point you're actually hovering on, the proposed way keeps the common label consistent across all subplots and aligned with the tick labels.

There is no "right" way of doing this by default. As mentioned in #3145 I think the placement of the x-hover element is not very consistent at the moment. That's why I think it should be configurable.

I'll try to think of possible configurations, that make sense..

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
