### ISSUE TITLE
configurable hoverinfo-x placement

### ISSUE THREAD

**Issue by mojoaxel** [plotly/plotly.js#3145]
It would be nice if it would be configurable if the x-value of the hoverinfo is shown as a seperated hover or as part of the data-hover.

### current behavior
![image](https://user-images.githubusercontent.com/600565/47394875-c8a74500-d724-11e8-9735-0d7d8a270c13.png)

### future behavior
![image](https://user-images.githubusercontent.com/600565/47395614-a8c55080-d727-11e8-990b-24710b0d8018.png)

**Comment by etpinard** [comment]
@mojoaxel I think setting `layout.hovermode: 'closest'` will give you the desired result.

**Comment by etpinard** [comment]
> (btw: Why are y-values not also realized as a y-axis bound hover?).

Could you clarify what you mean here? A screenshot should suffice. Thanks!

**Comment by mojoaxel** [comment]
> Could you clarify what you mean here? A screenshot should suffice. Thanks!

![image](https://user-images.githubusercontent.com/600565/47739539-dc4b3200-dc75-11e8-9069-416156a82268.png)

**Comment by etpinard** [comment]
Ok, and would you call the behavior with `hovermode: 'y'` consistent with `hovermode: 'x'` (the default):

https://codepen.io/etpinard/pen/bmyJQE ?
