### ISSUE TITLE
restyle contour

### ISSUE THREAD

**Issue by corrodis** [plotly/plotly.js#3146]
Contour plots can be created from non-grid data x : [1, 1, 2], y : [1, 2, 1], z: [1, 2, 3], 
I guess this is internaly coverted to grid data x : [1, 2], y: [1,2], z: [[1, 2],[3, ?]]
In the case where the contour is initialized with int he firtst scheme (non-grit like) it would be very usefull to be able to use restyle in  the same scheme. (restyle(z:[4,5,6])).

**Comment by alexcjohnson** [comment]
AFAICT this is working correctly. Note that in any `restyle` if you're providing an array you need to wrap it in another array, due to our multi-trace syntax.
```js
Plotly.newPlot(gd,[{type:'contour',x:[1,1,2],y:[1,2,1],z:[1,2,3]}])
Plotly.restyle(gd,{z:[[4,5,6]]})
```

**Comment by etpinard** [comment]
Hmm. Looks like it's working for me: https://codepen.io/etpinard/pen/NOEGpp

**Comment by corrodis** [comment]
I have to apologize, we were using an old version
https://cdn.plot.ly/plotly-1.27.1.min.js
