### ISSUE TITLE
Plotly IE9 error

### ISSUE THREAD

**Issue by fixxxr** [plotly/plotly.js#315]
Hi there, 

I need to run a heatmap chart on a machine using IE9 so I used the tag to obtain IE9 compatibility 
`	<script>if(typeof window.Int16Array !== 'function')document.write("<scri"+"pt src=typedarray.js'></scr"+"ipt>");</script>
`
but I get the following error in run-time:

![plotly_ie9](https://cloud.githubusercontent.com/assets/16917589/13521338/feeb0d02-e1e7-11e5-8134-6b887dc340fd.PNG)
 

What I am doing wrong?
Thanks

**Comment by etpinard** [comment]
I haven't tried. But this issue may be solved by adding `charset="UTF-8"` to your typedarray.js `<script>` tag.

**Comment by fixxxr** [comment]
Hello there, 

thanks for your response. I added `charset="UTF-8` to my script tag and the error now is the following:
![plotly](https://cloud.githubusercontent.com/assets/16917589/13565375/fb486f7c-e44f-11e5-8359-a315c0a11ef5.PNG)

now seems that typedarray.js is free of errors but Plotly.js is not loaded correctly.

Any thoughts?

Thanks in advance

**Comment by etpinard** [comment]
Could you provide the HTML file you're using?

**Comment by fixxxr** [comment]
please find attached the html that I am using

thanks in advance

[index.zip](https://github.com/plotly/plotly.js/files/161395/index.zip)

**Comment by etpinard** [comment]
Looks like your importing the unminified version of plotly.js, You should then import with:

```html
<script type="text/javascript" src="plotly.js" charset="utf-8"></script>
``` 

More info [here](https://github.com/plotly/plotly.js#non-ascii-characters).

**Comment by fixxxr** [comment]
I've tried that too but nothing changed. 

I tried importing the minified of both plotly and typedarrays but nothing changed.

**Comment by etpinard** [comment]
@fixxxr can you open https://jsfiddle.net/plotlygraphs/gqdme3r2/4/

and confirm whether the graph is showing or not?

**Comment by fixxxr** [comment]
@etpinard yes I can see the graph.

**Comment by fixxxr** [comment]
@etpinard I just tested your fiddle on a machine running IE9 and everything is OK. Apparently it was just the syntax...

Thank you very much for your effort.
