### ISSUE TITLE
[Feature-Request] Add xshift/yshift to legend

### ISSUE THREAD

**Issue by Braintelligence** [plotly/plotly.js#3151]
Hello everyone!
I'd wish for the legend to have xshift and yshift attributes, so I could position it more easily where I want it to be.

Currently I solved most of my positioning problems by using xshift/yshift with annotations and shapes but for some elements (for example "hacked" x axis titles via annotations) that are above where I want the legend to be I have huge problems of positioning for responsive layouts. (Especially with differing heights of the plot div when altering it for narrow displays.)

I can't tell how much work it would mean to implement this for the legend, but since other objects do have these attributes I hope it wouldn't create too much work. It would have an immense impact on how I could layout responsively, though, and would fix a myriad of problems that I have with layouting.

**Comment by alexcjohnson** [comment]
Makes sense, probably a fairly easy add. Feel like making a PR?? 😁

**Comment by Braintelligence** [comment]
@alexcjohnson If cargo-culting away at the commit which added annotation xshift/yshift will do, I might take a shot in about 3-4 weeks. But I bet my code wouldn't be up to snuff regarding best practices :D

**Comment by etpinard** [comment]
So `legend.xshift` and `legend.yshift` would be in pixels?

**Comment by Braintelligence** [comment]
@etpinard correct

**Comment by Braintelligence** [comment]
@alexcjohnson Would I have to create tests as well?

**Comment by Braintelligence** [comment]
As we're at it anyway: Would it be too hard to also include something like `legend.rows` where you can force the legend to distribute given legend items on so many rows?

Use-case: You set filtered legends invisible when downloading the PNG and if you have a lot of legend items in `orientation = 'h'` the will break into several rows. Now if you filter enough legend items it will reduce to one row but keep the positioning and thus a margin is created.

An alternative way would be to somehow access something like `legend.height` that is a read-only attribute which you can access while layouting (is there something like a layout-hook?) or after layouting and relayout the positioning of everything that relies on the height/margin of the legend.
If you can force a number of rows you can emulate the legend height by knowing the font size and finding a magic number that you can multiply with legend rows combined with the legend margin itself.

**Comment by Braintelligence** [comment]
So basically I found a workaround for my use-case by checking out `fullDataLayout` on a new plot. I created an invisible plot off the visible area and draw my stuff on there; I take the `legend._height` and only then draw the image that shall be downloaded.

I'm not in need of this feature anymore, so you may close it if you want or keep it for someone to work on 😸.

**Comment by brian428** [comment]
I think this would also address #1594, at least partially. It'll still probably require manually increasing the margin and then applying the shift to the legend, but at least it would provide some options for dealing with legend/axis overlaps.

**Comment by Braintelligence** [comment]
Hello everyone, is there any progress on this? 😸

**Comment by Braintelligence** [comment]
I don't know if it was a shift in versions but `legend._height` returns wrong heights for me in some cases which results in broken code functionality for me now 😢 . It basically says that the legend has less height than is actually displayed.

This seems to be another problem with usage of `<br>` tags as far as I can tell. If I remove all `<br>` tags from trace names I can't reproduce it anymore.

**Comment by jackparmer** [comment]
This issue has been tagged with `NEEDS SPON$OR`

A [community PR](https://github.com/plotly/plotly.js/pulls?q=is%3Apr+is%3Aopen+label%3A%22type%3A+community%22) for this feature would certainly be welcome, but our experience is deeper features like this are difficult to complete without the Plotly maintainers leading the effort.

**Sponsorship range: $5k-$10k**

What Sponsorship includes:
- Completion of this feature to the Sponsor's satisfaction, in a manner coherent with the rest of the Plotly.js library and API
- Tests for this feature
- Long-term support (continued support of this feature in the latest version of Plotly.js)
- Documentation at [plotly.com/javascript](https://plotly.com/javascript/)
- Possibility of integrating this feature with Plotly Graphing Libraries (Python, R, F#, Julia, MATLAB, etc)
- Possibility of integrating this feature with Dash
- Feature announcement on [community.plotly.com](https://community.plotly.com/tag/announcements) with shout out to Sponsor (or can remain anonymous)
- Gratification of advancing the world's most downloaded, interactive scientific graphing libraries (>50M downloads across supported languages)

Please include the link to this issue when [contacting us](https://plotly.com/get-pricing/) to discuss.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
