### ISSUE TITLE
[Bug] Invalid XML when downloading SVG for specific versions of IE 11

### ISSUE THREAD

**Issue by Braintelligence** [plotly/plotly.js#3152]
As requested here https://github.com/plotly/plotly.js/pull/2068#issuecomment-431331048 I'm repeating what I encountered with a specific version of IE 11 concerning this PR: https://github.com/plotly/plotly.js/pull/2068 .

Repeating my earlier comment:
> @alexcjohnson I'm not sure if this is the right place to mention this, but I think I encountered a bug for IE SVG export. If you download an SVG with Internet Explorer Version 11.0.9600.19137 that renders via trident engine (Edge) you get this:
> `<g class='plot' clip-path='url('https://www.domain.tld#clip00a1b1xyplot')' transform='translate(110 30)'>`
> instead of this:
> `<g class="plot" transform="translate(110, 30)" clip-path="url(https://www.domain.tld#clip189888xyplot)">`
> which results in a wrongly formatted XML (see the `'` that shouldn't be there).
> 
> I'm not sure how to fix this. Is this a very specific problem with this browser running on trident?

Additional information was requested:
> Can you open one, include the information you just posted - plus a description of how one ends up running this particular browser version - and link to this PR? Thanks!

Sadly, due to NDA-reasons, I can't tell you how a number of users end up using such a particular version of IE. My best shot at a possible way of being able to use such an IE version would be spinning up Windows 7, I guess.

I wouldn't say that this issue is anywhere close to high-priority. I strongly believe that there's some bug within IE 11 and how it handles generation of XML, or else most current versions of IE 11 would also have this bug, which they don't. (Tested on current Win10.)

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
