### ISSUE TITLE
[Feature-Request] Add ability not to show small text 

### ISSUE THREAD

**Issue by cooperok** [plotly/plotly.js#3153]
By default if set textposition=‘inside’ to Pie text will be scaled according to group size. And if group size is very small it does not look good.
![1](https://user-images.githubusercontent.com/1409914/47493104-2b98f900-d857-11e8-8ab2-f6bca33a027b.png)
Would be much better if text for small groups will be hidden
![2](https://user-images.githubusercontent.com/1409914/47493115-33589d80-d857-11e8-8df9-d1f395a58b16.png)
There is option 'insidetextfont' or 'textfont' which contains family, color and size. In my opinion would be usefull to set minimum font size and don't show text if scaled size is less then that value. Or maybe just turn off text scaling, for example set font size to 14 and if there is need to scale text don't show it at all.

Same for stacked bar charts
![2018-10-25 10-13-26](https://user-images.githubusercontent.com/1409914/47493260-8a5e7280-d857-11e8-86fb-c2f1f16a8b82.png)

**Comment by alexcjohnson** [comment]
Great idea, thanks for posting! The very small text is definitely useless... we might even make this parameter a fraction, like `mintextscale` - and give it a default of something like 0.5 or even larger, but if you want to disable scaling altogether just set it to 1.

**Comment by archmoj** [comment]
Resolved by #4420 using `uniformtext` with `mode: 'hide'`.
