### ISSUE TITLE
displayModeBar: hover not working in Chrome

### ISSUE THREAD

**Issue by nite** [plotly/plotly.js#3154]
Setting config=`{displayModeBar: 'hover'}` in chrome 70, Plotly 1.41.3 shows the modebar permanently, ie. as if `displayModeBar: true`. Hover mode works fine in firefox still. Have noticed this since chrome 69 or so. No javascript exceptions. Tested in incognito - ie without any extensions to interfere. 
To replicate, simply set config=`{displayModeBar: 'hover'}` in any plotly plot (or dont set it, as displayModeBar: 'hover' is actually default - hovermode works in firefox without).
eg.: 
```
var data = [
  {
    z: [[1, 20, 30], [20, 1, 60], [30, 60, 1]],
    type: 'heatmap'
  }
];
Plotly.newPlot('myDiv', data, {}, {displayModeBar: 'hover'});
```

**Comment by alexcjohnson** [comment]
Huh, works fine for me... what hardware & OS are you seeing this on? And is this new in 1.41.3 or do you see it in previous versions? (you can use a codepen like https://codepen.io/alexcjohnson/pen/ePbdbq and change `plotly-latest.min.js` in the HTML section to a specific version like `plotly-1.39.4.min.js`)

**Comment by nite** [comment]
Just realised, this is only on ubuntu (work machine) for me - working fine on OSX. So, dont think it's a plotly version thing but I'll test out some other versions.

**Comment by nite** [comment]
Closing as dupe of #2222
