### ISSUE TITLE
Cumulative scatter plots

### ISSUE THREAD

**Issue by mwouts** [plotly/plotly.js#3165]
Thanks for the beautiful and so helpful library!

I often plot cumulative returns, and would find it very helpful if the running sum was computed by plotly itself. 

Below are a few pseudo examples with my expectations:
* `go.Scatter(x=[0,1,2,3], y=[1,2,3,4], accumulate=True)` produces the same plot as `go.Scatter(x=[0,1,2,3], y=[1,3,6,10])` (accumulated left to right, starting at first value)
* `go.Scatter(x=[0,1,2,3], y=[1,2,3,4], accumulate=True)`, when zoomed on `x=[2,3]` produces the same plot as `go.Scatter(x=[2,3], y=[3,7])`

Ideally, I would also like to be able to specify
- the reference `x` coordinate for starting the accumulation: either a fixed `x` (clipped to the viewing window), left (minus infinity?) or right, the `x` center of the viewing window, etc...
- an x/y series for the reference y level (was zero above). That would be useful to superimpose cumulative plots onto classical scatter lines.

I also found a similar [question](https://community.plot.ly/t/cumulative-plots-that-rebase-when-zoomed/2333) on the community site, but it does not seem to have led to an implementation.

**Comment by antoinerg** [comment]
Thank you @mwouts! I hope the solution you found works great for you. If it does, please close this issue!

**Comment by alexcjohnson** [comment]
@antoinerg I read @mwouts comment to mean "we already have this for histograms, but I want it for scatter." Seems reasonable, either as a new mode to histogram or a `cumulative` extension to `scatter`. Seems to me @chriddyp was already asking for this at some point...

**Comment by mwouts** [comment]
Hi everyone, sure I was only citing the histogram example as a related implementation, not as a solution. I would recommend a `cumulative` extension to `scatter` rather than a new mode in histogram, as the histogram mode is very specific to probability distributions (and, naturally, `cumulative` values there do not change when we zoom).

**Comment by antoinerg** [comment]
@alexcjohnson Oh my bad! Not enough :coffee: for me today. Let's keep this open then!

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
