### ISSUE TITLE
Incorrect table cell font color

### ISSUE THREAD

**Issue by jonmmease** [plotly/plotly.js#3167]
Plotlyjs translation of https://github.com/plotly/plotly.py/issues/1241

It seems that something goes wrong when using a color array to specify the font color of table cells.

In this example, the topmost table cell should have both font and fill colored red, and all subsequent cells should have font and fill colored green.  The fill color matches this expectation, but the font color shows up as red in both the first and 7th table cell. (you have to scroll down to see it)

CodePen: https://codepen.io/etpinard/pen/GYzEYK

```JavaScritp
var colors = [
  "red",
  "green",
  "green",
  "green",
  "green",
  "green",
  "green",
  "green",
  "green",
]

var fig = {
  "data": [
    {
      "cells": {
        "fill": {
          "color": [colors]
        },
        "font": {
          "color": [colors]
        },
        "values": [
          colors
        ]
      },
      "type": "table"
    }
  ],
  "layout": {
    "height": 300,
    "width": 400
  }
}

Plotly.newPlot('myDiv', fig);
```

After playing with the layout size, it looks like the problem only happens when scrolling is needed, and it's always with the topmost cell that is not initially visible.

**Comment by etpinard** [comment]
Thanks for the report!

**Comment by 7anushetty** [comment]
Hi team, is there any workaround or update on fixing this **bug**?

> Plotlyjs translation of [plotly/plotly.py#1241](https://github.com/plotly/plotly.py/issues/1241)
> 
> It seems that something goes wrong when using a color array to specify the font color of table cells.
> 
> In this example, the topmost table cell should have both font and fill colored red, and all subsequent cells should have font and fill colored green. The fill color matches this expectation, but the font color shows up as red in both the first and 7th table cell. (you have to scroll down to see it)
> 
> CodePen: https://codepen.io/etpinard/pen/GYzEYK
> 
> ```
> var colors = [
>   "red",
>   "green",
>   "green",
>   "green",
>   "green",
>   "green",
>   "green",
>   "green",
>   "green",
> ]
> 
> var fig = {
>   "data": [
>     {
>       "cells": {
>         "fill": {
>           "color": [colors]
>         },
>         "font": {
>           "color": [colors]
>         },
>         "values": [
>           colors
>         ]
>       },
>       "type": "table"
>     }
>   ],
>   "layout": {
>     "height": 300,
>     "width": 400
>   }
> }
> 
> Plotly.newPlot('myDiv', fig);
> ```
> 
> After playing with the layout size, it looks like the problem only happens when scrolling is needed, and it's always with the topmost cell that is not initially visible.



> Plotlyjs translation of [plotly/plotly.py#1241](https://github.com/plotly/plotly.py/issues/1241)
> 
> It seems that something goes wrong when using a color array to specify the font color of table cells.
> 
> In this example, the topmost table cell should have both font and fill colored red, and all subsequent cells should have font and fill colored green. The fill color matches this expectation, but the font color shows up as red in both the first and 7th table cell. (you have to scroll down to see it)
> 
> CodePen: https://codepen.io/etpinard/pen/GYzEYK
> 
> ```
> var colors = [
>   "red",
>   "green",
>   "green",
>   "green",
>   "green",
>   "green",
>   "green",
>   "green",
>   "green",
> ]
> 
> var fig = {
>   "data": [
>     {
>       "cells": {
>         "fill": {
>           "color": [colors]
>         },
>         "font": {
>           "color": [colors]
>         },
>         "values": [
>           colors
>         ]
>       },
>       "type": "table"
>     }
>   ],
>   "layout": {
>     "height": 300,
>     "width": 400
>   }
> }
> 
> Plotly.newPlot('myDiv', fig);
> ```
> 
> After playing with the layout size, it looks like the problem only happens when scrolling is needed, and it's always with the topmost cell that is not initially visible.

**Comment by 7anushetty** [comment]
Hi team, is there any workaround or update on fixing this **bug**?

**Comment by ruliana** [comment]
Any update on this?

**Comment by julienraffaud** [comment]
Hey Friends. Any luck with this problem? Seems a pretty basic functionality, would be great if it could actually work

**Comment by julienraffaud** [comment]
Gang... can we get this one fixed, seriously?? How is it so hard to correct???

**Comment by nicolaskruchten** [comment]
We would welcome a pull request :)

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
