### ISSUE TITLE
Autorange 'reversed' doesn't allow specifying range

### ISSUE THREAD

**Issue by slishak** [plotly/plotly.js#3176]
The yaxis range isn't respected in this example:
https://codepen.io/anon/pen/yRrKpN

Potentially related to #3075 and #553 . Could potentially just be an error in the documentation, and the answer is just not to use both options at the same time the way it's done here: 
https://plot.ly/python/axes/#reversed-axes-with-range--minmax--specified

**Comment by alexcjohnson** [comment]
Thanks - your guess is right, it's a documentation issue. If you know the range you want, just specify it as `[max, min]` and omit `autorange` entirely https://codepen.io/alexcjohnson/pen/WaWJLj

**Comment by alexcjohnson** [comment]
Closing - moved to https://github.com/plotly/documentation/issues/338
