### ISSUE TITLE
D3 Scatter plot chart increasing browser memory size

### ISSUE THREAD

**Issue by aasiyak** [plotly/plotly.js#3182]
Hi,

We have huge data being received in chunks to the page and the scatter plot in the page gets updated with each chunk.  With the data size increase, browser's memory size is getting increased (up to 3 GB) and the browser is getting crashed.  Data size is not an issue, because when the chart is disassociated with the data, browser is memory is normal, it is only increasing when scatter plot is rendered with that data.

Could you please help?

 Here is the sample code :

Code to create the chart on page load :
--------------------------------------

        var ndx = crossfilter([]);
        var cpdim = ndx.dimension(function(d) {return [d.sdate,+d.CP]; });
        var cpgrp = cpowerdim.group().reduceSum(function(d) {return +d.CP;});

       var shrsdim = ndx.dimension(function(d) {return [d.sdate,+d.SHOURS]; });
       var shrsgrp = sourcehoursdim.group().reduceSum(function(d) {return +d.SHOURS;});	

      var divWidth = document.getElementById("Summary_div").offsetWidth;
      var divHeight = document.getElementById("Summary_div").offsetHeight;

      spchart = dc.compositeChart(chartDiv("Summary_div"));      

      spchart 
                  .width(divWidth)
                  .height(divHeight)
                  .x(d3.time.scale().domain([minDate,maxDate]))
                  .xUnits(d3.time.minutes)
                  .elasticX(true)
                  .elasticY(true)
                  .clipPadding(10)
                  .legend(dc.legend().x(20).y(0).itemHeight(10).gap(2))
                  .brushOn(false)
                  .yAxisLabel("CP")
        	  .rightYAxisLabel("SHours")
                  .compose([
                            dc.scatterPlot(spchart )
                            .dimension(shrsdim )
                            .group(shrsgrp , "SHours")
                            .colors('orange')                          
                            .symbolSize(4).useRightYAxis(true),

                            dc.scatterPlot(spchart )
                            .dimension(cpdim)
                            .group(cpgrp, "CP")
                            .symbolSize(4)
                        
                  ]);
        spchart .render();

On receiving each chunk of data :  

ndx.add(chunkdata);
dc.redrawAll();

**Comment by alexcjohnson** [comment]
This is the repository for plotly.js - looks like this issue is with dc.js, perhaps you want to post it at https://github.com/dc-js/dc.js/issues ? We can make scatter plots too, but we can't help with dc.js issues 😄

**Comment by alexcjohnson** [comment]
OP did post it over there - closing.
