### ISSUE TITLE
Looking for how to register hover or click events on axis and tick labels 

### ISSUE THREAD

**Issue by contactsandygo** [plotly/plotly.js#3183]
I have custom requirement to capture events on axis and tick labels . In example codepen I am able to get events and subsequent data excluding these two i.e area which has data traces.   

 https://codepen.io/contactsandygo/pen/VEOBaP 

How can I register hover event on both axis labels and tick labels of both scale with latest plotly version.

**Comment by etpinard** [comment]
Thanks for writing in! We like to keep questions of the likes on https://community.plot.ly/c/plotly-js

Closing.
