### ISSUE TITLE
Need for a jasmine test to check the context layer remains after a restyle call on parcoords

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#3185]
[PR 3178](https://github.com/plotly/plotly.js/pull/3178) resolved two restyle issues with parcoords as reported [here](https://github.com/plotly/plotly.js/issues/3101). 
It also contained a jasmine test which checks if the restyle changes the colours on the focus layer.
However in order to lock the second issue we need another jasmine test to check the context layer remains unchanged after a restyle call. This [demo](https://codepen.io/MojtabaSamimi/pen/GYagEb) used to display this issue using an older release v.1.41.3.

![47727714-4b536700-dc33-11e8-845f-52c29f41c206](https://user-images.githubusercontent.com/33888540/47729249-33c9ad80-dc36-11e8-8e80-7e178f65455b.gif)

**Comment by etpinard** [comment]
fixed in https://github.com/plotly/plotly.js/pull/3195
