### ISSUE TITLE
plots in plotly.js tutorial docs not displaying in Internet Explorer 11

### ISSUE THREAD

**Issue by priyatharsan** [plotly/plotly.js#3186]
This issue is specific only to the plots in `CodePen`.

![codepen](https://user-images.githubusercontent.com/25846124/47735601-367ecf80-dc43-11e8-87d7-932ca49cd38c.gif)

**Comment by etpinard** [comment]
Can you try opening https://codepen.io/ and any other example codepen in IE11 to help us out? Thanks.

**Comment by Braintelligence** [comment]
@etpinard Current release https://github.com/plotly/plotly.js/releases/tag/v1.42.0 doesn't work for me in IE 11 anymore. Something about `The object doesn't support the attribute or method "remove"`
The release before works fine...

**Comment by priyatharsan** [comment]
Yeah I get this message when opening https://codepen.io/ ,
![capture](https://user-images.githubusercontent.com/25846124/47739122-0c311000-dc4b-11e8-9fcf-6988576ef4b5.PNG)

like I doubted it's related to codepen and not plotly but maybe I could be wrong. 
Also, the full page view is working fine in IE11 
![capture1](https://user-images.githubusercontent.com/25846124/47739392-a6915380-dc4b-11e8-8a0a-8dcbf2438fde.PNG)

But not the pen view: 
![capture3](https://user-images.githubusercontent.com/25846124/47739404-adb86180-dc4b-11e8-98e1-6434ee1f0a63.PNG)

**Comment by Braintelligence** [comment]
IE 11 doesn't support childNode.remove() https://caniuse.com/#search=remove

**Comment by Braintelligence** [comment]
Providing this polyfill before triggering Plotly works: https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/remove#Polyfill

**Comment by etpinard** [comment]
@Braintelligence which example are you looking at?

**Comment by alexcjohnson** [comment]
This seems to be the offender:
https://github.com/plotly/plotly.js/blob/0124828f061cc1483bf09781c81c12050971bc62/src/lib/index.js#L716

**Comment by Braintelligence** [comment]
@etpinard I hope alex hit the spot. Sadly I'm not looking at any example, I'm looking at a website in the work that is still under NDA 🙈.

**Comment by priyatharsan** [comment]
I also figured that some plots are displaying. For instance, these two examples https://plot.ly/javascript/line-charts/#connect-gaps-between-data and https://plot.ly/javascript/line-charts/#labelling-lines-with-annotations are displaying but not the rest of the plots in the doc. The only common difference I can find is these two plots has `showlegend: false`

**Comment by alexcjohnson** [comment]
(BTW thanks @Braintelligence for tracking down the broken feature)
Modify that polyfill to *always* overwrite, and trace its calls, and you can see whenever `node.remove` is called in any browser:
```js
(function (arr) {
  arr.forEach(function (item) {
    Object.defineProperty(item, 'remove', {
      configurable: true,
      enumerable: true,
      writable: true,
      value: function remove() {
        console.trace(this);
        if (this.parentNode !== null)
          this.parentNode.removeChild(this);
      }
    });
  });
})([Element.prototype, CharacterData.prototype, DocumentType.prototype]);
```
Perhaps we can build that into our tests, with a `throw` instead of a `console.trace`, to ensure we never use `node.remove`?

**Comment by Braintelligence** [comment]
@alexcjohnson Good catch. I combined it with a bowser.msie check to not call the polyfill for anything but IE.

I just did a dirty combination with bowser.msie check to incorporate the linked polyfill. Should I change the polyfill portion anyway?

**Comment by alexcjohnson** [comment]
@Braintelligence my comment was just for our own debugging. Hopefully we'll have a patch release out shortly that fixes this so you won't need to polyfill at all, but as written in that MDN link it's great even without an IE check, since it'll only fill if the method is initially absent.

**Comment by Braintelligence** [comment]
@alexcjohnson Yeah, your comment still makes sense for me if you check that you use IE 11 beforehand 😸. The if-block was for skipping every element that has .remove() naturally, right? So if I just check once if I'm looking at IE 11 I can skip the whole iteration beforehand. 😼

**Comment by antoinerg** [comment]
@Braintelligence Can you try the latest patched plotly.js (https://17351-45646037-gh.circle-artifacts.com/0/plotly.min.js) built from PR #3187 and confirm over there that it works!

**Comment by Braintelligence** [comment]
@antoinerg Sorry I'm off work now. Will try tomorrow :(

**Comment by Braintelligence** [comment]
@antoinerg I can confirm that your linked plotly.min.js works without providing the polyfill yourself.
