### ISSUE TITLE
vertical modebar is a pixel outside the parent container

### ISSUE THREAD

**Issue by antoinerg** [plotly/plotly.js#3189]
This can be seen in this screenshot:
![modebar-not-pixel-perfect](https://user-images.githubusercontent.com/301546/47747840-a69b4e80-dc5f-11e8-8e8d-69ce3570e355.png)

In order for the Plotly logo to be always positioned at the same location (whether the orientation is vertical or horizontal), the following CSS rule was added:
https://github.com/plotly/plotly.js/blob/0124828f061cc1483bf09781c81c12050971bc62/src/css/_modebar.scss#L47-L48

We have to remove this line after which we can decide to:
1. To leave everything else unchanged but then horizontal and vertical modebar have the logo offset by 1px
2. Or we shift the horizontal modebar down 1px to make sure we have equal space to the right and above the logo.

What would you prefer @plotly/plotly_js ?

**Comment by etpinard** [comment]
> 2\. Or we shift the horizontal modebar down 1px to make sure we have equal space to the right and above the logo.

This one sounds better to me. I don't have a strong opinion though.

**Comment by alexcjohnson** [comment]
I imagine there's a way to have it both ways, but (2) sounds fine to me.

But there's another issue I notice: vertical modebars occupy the whole side of the plot:
![screen shot 2018-10-31 at 9 19 01 am](https://user-images.githubusercontent.com/2678795/47791358-e3af2180-dcef-11e8-88dc-b9221b72bc97.png)
unlike horizontal, which just occupy the required space:
![screen shot 2018-10-31 at 9 19 22 am](https://user-images.githubusercontent.com/2678795/47791384-f4f82e00-dcef-11e8-810c-804f393bfb8a.png)
Aside from looking odd when you give the modebar a non-matching color, it means if you put the plot itself all the way out to the edge (ie very small margins) you can't interact with points under there.

**Comment by antoinerg** [comment]
Thanks @alexcjohnson for reporting this other issue.

> I imagine there's a way to have it both ways, but (2) sounds fine to me.

I agree: another way would be to reduce the `padding-top` for the vertical modebar.

**Comment by etpinard** [comment]
This one got fixed in #3193, correct?

**Comment by antoinerg** [comment]
Absolutely! Closed via #3193!
