### ISSUE TITLE
Plotly 1.42.1 goes unresponsive

### ISSUE THREAD

**Issue by rfriedma** [plotly/plotly.js#3197]
I recently updated from plotly 1.41 to 1.42.1 in order to get some bug fixes. With the same data, plotting is now going unresponsive. I have two links below showing the same data in two versions of plotly where one hangs.
I'm using Chrome 70.0.3538.67 (Official Build) (64-bit)

Here's 1.42.1:
https://codepen.io/rfried/pen/VEJOJL

Here's 1.41.0:
https://codepen.io/rfried/pen/dgBxEg

Can anyone determine something wrong with my data or explain why plotly is hanging?

Thanks

**Comment by alexcjohnson** [comment]
there's a runaway `while` loop here:
![screen shot 2018-10-31 at 2 27 42 pm](https://user-images.githubusercontent.com/2678795/47810261-423cc580-dd19-11e8-804f-d8225ae668ae.png)
https://github.com/plotly/plotly.js/blob/6fda5955d97436534f786f5dbff7f2e121273bb7/src/traces/scattergl/index.js#L401-L407
Came in with #3087 
@archmoj want to take this?

**Comment by etpinard** [comment]
@archmoj I'm on it. We'll have a PR out shortly.

**Comment by rfriedma** [comment]
Thanks for the quick response and fix :)

**Comment by etpinard** [comment]
@rfriedma thank **you** for the report!
