### ISSUE TITLE
More control over hoverformat when supplying ticktext/tickvals

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#320]
As I mention in https://github.com/ropensci/plotly/pull/480, for our ggplot2 converter, a huge number of issues are resolved by using linear axes and supplying `ticktext`/`tickvals` for all data types. Here's a mini example of how I implement date/datetime axes -- http://codepen.io/cpsievert/pen/mPVGEg

It'd be awesome if I had more control over the hoverformat. Would it be easy/possible to add the ability to convert types just for hoverformatting purposes? Maybe this could be a new property, say `layout.axisid.hoverType = "-" | "linear" | "log" | "date" | "category" `?

**Comment by etpinard** [comment]
Why not use `hoverinfo` in the traces?

I guess, that would imply setting a custom `hoverinfo` for all traces on a given axis.

**Comment by cpsievert** [comment]
Yea, I'll probably end up using `hovermode="text"` and creating custom text for each trace. Not ideal since I have to send more data, and lose the axis hovertext, but I can make it work.

**Comment by etpinard** [comment]
We will be resolved using a templating mini-language in trace `text` fields.
