### ISSUE TITLE
geom_line becomes invisible when color aesthetic applied

### ISSUE THREAD

**Issue by wolfeclw** [plotly/plotly.js#3205]
I am attempting to apply a gradient color scale to a line in a `ggplot` object.  When I create the `plotly` chart, the plotted line is not visible.  Hovering over the plot area shows the values of the variables if the cursor is where the line is located, even though the line is not visible.

If I do not apply a color aesthetic, the line is visible.

I have download the most recent `plotly` package from Github.

Here is some example code of the issue:

library(tidyverse)

df <- tibble(
    x = rnorm(100, 7, 1),
    y = rnorm(100, 4, 1),
    z = rnorm(100, 5, 1))

plot <- ggplot(df) +
    geom_line(aes(x, y, color = z),
              lwd = 1.5) +
    scale_color_gradient(low = "red",
                          high = "blue")

plot
![ggplot_ex](https://user-images.githubusercontent.com/18602544/47876801-936bb880-ddf0-11e8-8e83-17d6c1400587.jpeg)

plotly::plotly_build(plot) 

![plotly_ex](https://user-images.githubusercontent.com/18602544/47876812-9b2b5d00-ddf0-11e8-97ae-6dfef170ec34.png)

**Comment by cpsievert** [comment]
Ohhh, yea, if you can transfer that'd be great -- super stoked to see this in `scattergl`!

**Comment by wolfeclw** [comment]
Yes, I had meant to post this over there.  Thanks for the tip!
