### ISSUE TITLE
Make sure TypedArrays are supported everywhere

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#3215]
Discussion from #3210:

> > (@alexcjohnson) I'll fix (and test) this specific bug, but @etpinard I'm not sure what would make a good generic test of typed array support - in principle we could rerun the entire image test suite, combing through `data` (and `layout` for numeric arrays and converting them to typed arrays first... that seems pretty heavy but how else could we catch silent bugs like this?
>
> (@etpinard) That does seems pretty heavy, unless we can add two more CircleCI test containers 💰
> 
> But maybe we could _try_ to run all our mocks with typed arrays once locally and then lock failing cases (if any 😏 ) with jasmine tests.

And how do we catch these problems in new features then? I guess if there's a simple command to run all of our mocks with TypedArrays, we could make this part of the pre-publish checklist?

**Comment by jonmmease** [comment]
I just opened #3339, and by my count this is the 6th bug so far that would have been caught if all of the mocks were run with typed arrays.

Full list:
 - #3210
 - #3179
 - #2585
 - #2591
 - #3142
 - #3339

So it seems to me that time/resources spent on preventing this class of issues in testing would be pretty worthwhile.

**Comment by jonmmease** [comment]
And https://github.com/plotly/plotly.js/issues/3595

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
