### ISSUE TITLE
Configurable parallel coordinates brush

### ISSUE THREAD

**Issue by mg1075** [plotly/plotly.js#3221]
Can the brush in parallel coordinates be made to follow convention seen in other non-plotly parallel coordinates and be a transparent bar rather than a super-thin pink line?

Plotly's brush is thin and gives the user a small hit target to activate the brush and drag the brush. End result is a less than user-friendly brush.
https://plot.ly/javascript/parallel-coordinates-plot/

Compare with the brush selection in this d3-based parallel coordinates plot. It is much easier to activate a brush and drag it.
http://syntagmatic.github.io/parallel-coordinates/

**Comment by etpinard** [comment]
Thanks for the feedback.
