### ISSUE TITLE
Equivalent of colSpan and rowSpan for table trace type

### ISSUE THREAD

**Issue by jackparmer** [plotly/plotly.js#3225]
rowSpan example:

![image](https://user-images.githubusercontent.com/1865834/48161487-ac6ce180-e2a8-11e8-9dff-4d43bf5cc2f9.png)

colSpan example:

![image](https://user-images.githubusercontent.com/1865834/48161524-c0b0de80-e2a8-11e8-962c-16d28d754a01.png)

**Comment by AbdealiJK** [comment]
Is there an workaround or possibility of implementing this ?
I'd be interested in contributing it if someone could guide me in what direction I need to go to solve it.

**Comment by AbdealiJK** [comment]
Was looking through the code related to this, and was thinking of the following:
In `attributes.js`, add two new attrs. `cells.rowspan` and `header.rowspan`. These can be a numeric value, an array value or an array of arrays.
    - If numeric value, it doesn't have much meaning. As the ratios are important
    - If array of numbers: The columns for headers and rows are taken in that ratio
    - If array of array of numbers: The cell value is taken into account for the width of that column.
And modifying the `cells.colspan` and `header.colspan` to allow for 2D arrays with the same behavior.

Note, the implementation of these is ratio based (similar to the current `columnwidth`) - so, giving values like 1.5 etc are allowed. These attributes would take higher priority over columnwidth. i.e. only if these are not provided will `columnwidth` be taken into account for the calculations.

This way, by setting the `header.rowspan: [[1], [2, 1], [0,1], [2,1], [0,1]]` and `cells.rowspan: 1` we could allow a table like:
<img width="273" alt="Screen Shot 2019-04-01 at 11 35 25 AM" src="https://user-images.githubusercontent.com/2200743/55306549-43ae1d80-5472-11e9-8b35-82cd38085911.png">

By setting the `cells.colspan: [[2,0], 1, 1]` we could allow a table like:
<img width="206" alt="Screen Shot 2019-04-01 at 11 41 24 AM" src="https://user-images.githubusercontent.com/2200743/55306813-1ada5800-5473-11e9-99ec-2f7d7e3b4fe9.png">

The math for this in `data_preparation_helper.js` would be something like:
```js
    var headerWidths = trace.header.width ? trace.header.width : columnWidths;
    var cellsWidths = trace.cells.width ? trace.cells.width : columnWidths;
    headerValues.forEach(function(col, icol) {
        col.forEach(function(row, irow) {
            // If header.width is a scalar value
            var value = trace.header.width;
            // If header.width is a 1D Array, get the value from that
            value = Array.isArray(value) ? value[Math.min(icol, value.length - 1)] : value;
            // If header.width is a 2D Array, get the value from the 2D indexing
            value = Array.isArray(value) ? value[Math.min(irow, value.length - 1)] : value;
            // Ensure the value is numeric
            value = isNumeric(value) ? Number(value) : 1;
            headerWidths[icol][irow] = value;
        });
    });
    // Similar for cellsWidths
```

After which the `headerWidths` and `cellsWidths` would be added to `calcdata`.
I still need to figure out how the math for plotting the cells works.

Any feedback on this is appreciated before I move on ...

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
