### ISSUE TITLE
scattergl lines trace fails with 100k points in plotly.js 1.42

### ISSUE THREAD

**Issue by jonmmease** [plotly/plotly.js#3226]
There seems to be a regression in 1.42 for `scattegl` traces with `mode='lines'` and >100k points.

Originally discussed  in https://community.plot.ly/t/trouble-with-scattergl-lines-with-lots-of-points/15408/2

CodePen: https://codepen.io/jonmmease/pen/qQZWXB

```javascript
function gaussianRand() {
  var rand = 0;
  for (var i = 0; i < 6; i += 1) {
    rand += Math.random();
  }
  return (rand / 6)-0.5;
}

// 100,000 fails
var point_num = 100000;

// 99,999 is fine
// var point_num = 99999;

var Y = [];
for (var i = 0; i < point_num; i++) {
	Y.push((gaussianRand()*8));
}

var data = [{
	type: "scattergl",
	mode: "line",
	y: Y
}]

var layout = {showlegend: false}
Plotly.plot('graph', data = data, layout = layout)
```

with <= 99,999 points the plot works as expected
![newplot](https://user-images.githubusercontent.com/15064365/48193778-4c625380-e319-11e8-8be9-21a7416f0176.png)

but with >= 100,000 points the plot doesn't render and the following JavaScript error is raised
```
TypeError: opts.marker is undefined.          plotly-1.42.4.js:168110:1
```

version 1.41.3 doesn't have this error. Thanks!

**Comment by qballed** [comment]
Additional data for seemingly same issue:

[https://github.com/plotly/plotly.py/issues/1271](url)
