### ISSUE TITLE
Plotly react performance plummets with large number of traces

### ISSUE THREAD

**Issue by rhamner** [plotly/plotly.js#3227]
I found one conversation about this in issue [1535](https://github.com/plotly/plotly.js/issues/1535) and it was referenced as the achilles heell in plotly in the comments but that was over a year ago so I wanted to include a new example to see if anything can be done.

A contrived, reproducing example is here:

[example](https://codepen.io/rhamner/pen/bQpgZy?editors=1010)

On my machine in chrome and plotly 1.42.4, I'm getting the following results for rendering 10k total points:

- 1 trace: ~80 ms/call
- 10 traces: ~90 ms/call
- 100 traces: ~140 ms/call
- 1000 traces: ~650 ms/call

The real-life example that made me notice this is 15k points going from <200 ms/call to ~15 seconds/call over the range of trace numbers. This is really impactful in our use case. We are already trying to minimize the total number of traces so I'm not sure if there's anything we can do to improve this on our end.

**Comment by Shmew** [comment]
Any progress on this? Having this issue when adapting the python version's gantt component.

**Comment by lokeshmajji** [comment]
I see this issue when plotting more than 500 traces, Python Plotly doesn't have this issue though.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
