### ISSUE TITLE
[Bug] &ndash; / &ensp; in annotation causes malformed SVG download

### ISSUE THREAD

**Issue by Braintelligence** [plotly/plotly.js#3238]
Hi everyone.
So if you use `&ndash;` in `annotations: [{ text: "&ndash;}]"` you get a malformed SVG. Why does `&nbsp;` work, though?

EDIT: `&ensp;` also doesn't work...

Here an example: https://codepen.io/anon/pen/MzJoOG

**Comment by alexcjohnson** [comment]
Ah thanks - definitely a bug that the SVG is malformed, but we don't currently plan to support arbitrary named HTML entities (so I'd say the "correct result" here would be to display "`&ndash;`" literally. The latest status of that is #2932 in which we added support for all *numbered* HTML entities (simplified example for `&ndash;` = `&#8211;`: https://codepen.io/alexcjohnson/pen/NMdMbE?editors=1010) but in that PR we noted:

> Note that this would make it feasible, performance-wise, to include ALL named html entities, but the full list is over 2000 items, and there are other options (unicode literals, or numbered entities if you want your code/JSON to be pure ASCII) so I suggest we keep it at just the existing set.

The "existing set" is a few entities we've supported for a very long time:
https://github.com/plotly/plotly.js/blob/427fd14020382f950063b61dc855e4b85d91627a/src/lib/svg_text_utils.js#L339-L348

**Comment by Braintelligence** [comment]
Ah I see!
Well I've helped myself with unicode now 😹. Will switch to numbered HTML entities due to code-readability. Thanks for pointing it out! 👍

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
