### ISSUE TITLE
Column/dimension order + redraw/uirevision

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#3241]
Following up on https://github.com/plotly/plotly.js/pull/3236 (so this issue should either wait until that's merged or should be incorporated into that PR) two things I noticed about reordering `table` columns and `parcoords` dimensions. Both of these work correctly in the immediate use, but on redraw, especially when we try to consider `uirevision`, they would break - hence they've been omitted from #3236 

---

Re `table` traces `columnorder` attribute:
https://github.com/plotly/plotly.js/blob/a11ec44f388741dd21046d08a782e4e76fc8ba22/src/traces/table/plot.js#L591-L593

This looks close to working, and its model with the `columnorder` attribute seems like the right solution for GUI edits. Just needs to have the changes the user made persisted back to `gd.data` and `fullData`, emitted in the event, and supported by `applyUIRevisions`. Currently a redraw (for example, change the plot width) will reset the columns to their original order.

---

Re `parcoords` traces reordering `dimensions`:
https://github.com/plotly/plotly.js/blob/a11ec44f388741dd21046d08a782e4e76fc8ba22/src/traces/parcoords/plot.js#L122-L130

This one is currently reshuffling the entire `dimensions` array - so all the data and other attributes in that array will look like they're GUI edits, so if anything else changed there (like adding more data points in `Plotly.react`) it would get all mixed up if we try to reapply the other changes in `applyUIRevisions`. The better solution would be to create a `dimensionorder` attribute.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
