### ISSUE TITLE
Interrupt (null values) as gap mode for stacked scatter charts

### ISSUE THREAD

**Issue by Bjodol** [plotly/plotly.js#3244]
Hi!

We have been evaluating a lot of charting frameworks and found that plotly is the one that fit our needs the best. However we have one major issue with it on the stacked scatter charts. Currently the only two supported gapModes is "infer zero" and "interpolate" which hinders us from fully commit to Plotly. In our application a null value signifies a data loss and replacing it with 0 provides a wrong picture as the 0 indicates that we have data and the value is 0 not that we actually in fact have a data loss.

I pulled down the code and saw that `src/traces/scatter/plot.js:407` suggests interrupt as a future new mode. Is this covering null values not being shown in the area charts and is there an ETA for when this will arrive? If interrupt is something else, I would like to propose having a gap mode where null values aren't drawn in the stacked group.

**Comment by alexcjohnson** [comment]
Thanks @Bjodol, there definitely should be an issue open for this. That's right, we had discussed from the beginning that a third option to `stackgaps` making it clearer that a gap is really "missing" would be useful. There's also this commented-out portion in the attribute description:

https://github.com/plotly/plotly.js/blob/2ceb5c3e7981cc850727f7406f6677c4d74be044/src/traces/scatter/attributes.js#L138-L143

which, as mentioned when we were [originally discussing this feature](https://github.com/plotly/plotly.js/issues/1217#issuecomment-394826415) would look something like:

![screen shot 2018-06-04 at 9 43 50 am](https://user-images.githubusercontent.com/2678795/40920890-e8e855d8-67db-11e8-8861-2ad511ee7152.png)

Is that the kind of behavior you had in mind?

We don't have an ETA for this currently, but it's useful to know folks are interested. But the best way to get it to happen quickly would be either to submit a PR or to sponsor the project https://plot.ly/products/consulting-and-oem/

**Comment by warren-oneill** [comment]
Hi @Bjodol and @alexcjohnson, I just sent in a request to sponsor this issue getting done here https://plotly.com/get-pricing/.
I have a similar issue with intermittent timeseries data. As you can see in the plot below I'm getting a lot of zeros in the hover that I don't want to see.
![Uploading Screenshot 2020-10-15 at 13.29.35.png…]()

**Comment by warren-oneill** [comment]
However, I was able to remove all the zeroes from the plot by setting `mode='none'`. It's only the issues with the hover I am having.

**Comment by warren-oneill** [comment]
I ended up getting around the issues by using a stacked bar plot with no gaps or borders.
```
fig = go.Figure()
fig.add_trace(go.Bar(x=x, y=y, name=u, opacity=0.5, 
                                    marker=dict(line=dict(width=0))))
fig.update_layout(barmode='stack', bargap=0)
```

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
