### ISSUE TITLE
noChange flag for react event

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#3245]
From a `react-plotly.js` perspective it would be really helpful if the `plotly_react` event (and possibly `restyle` and friends) contained information about whether or not the call that triggered it caused any changes to the figure: did plotly update `data` or `layout` or `frames` as a result of this call? 

If we had this information, it would be a lot easier to prevent infinite loops with `react-plotly.js` :)

**Comment by alexcjohnson** [comment]
Sounds reasonable for `Plotly.react` - so in addition to `{data, layout}` (hmm, should `config` and `frames` be in there too?) the event data could include `changed` - do you see any uses for describing what pieces changed? It would be easy to make this into a `flaglist` like `'data+config+frames'` so you could choose to only care about events where `data` or `layout` changed and ignore `frames` and `config`.

While we're here I notice it doesn't look like `frames` are considered on first plot, ie when we just drop back to `newPlot`.

**Comment by nicolaskruchten** [comment]
I've noticed that the `frames` array *always* changes identity, which led to a brutal hack in `react-plotly.js` such that we only look at its length :(

**Comment by nicolaskruchten** [comment]
Interestingly, `react-plotly.js` doesn't actually listen for `react` events, just this list: https://github.com/plotly/react-plotly.js/blob/master/src/factory.js#L37

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
