### ISSUE TITLE
'plotly_selected' fires `undefined` when plot is clicked subsequent to previous 'plotly_selected'

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#3248]
Not sure if this is intentional, but I find it surprising, especially considering 'plotly_deselect' could be used to 'clear' a selection

https://codepen.io/cpsievert/pen/BGZQRx

![weird](https://user-images.githubusercontent.com/1365941/48588909-a4432080-e8fe-11e8-9959-6fa9f6009172.gif)

**Comment by etpinard** [comment]
Yep, it's intended (for now):

https://github.com/plotly/plotly.js/blob/3a32ac00cf5e8619932f874960f11b4daf7ceb40/src/plots/cartesian/select.js#L258-L262

Ok, if I move this to the v2 checklist in #420 ?

**Comment by cpsievert** [comment]
Sounds good to me, thanks!

**Comment by etpinard** [comment]
Moved to https://github.com/plotly/plotly.js/issues/420#issuecomment-439442318
