### ISSUE TITLE
Plotly table hijacks page scrolling

### ISSUE THREAD

**Issue by anikets43** [plotly/plotly.js#3249]
I implemented as per https://plot.ly/javascript/table/ 

Issue: When we have full width table, page scrolling doesn't work even the table scrolls end. This completely creates confusion and looks like page is hanged.

**Comment by AbdealiJK** [comment]
![untitled](https://user-images.githubusercontent.com/2200743/48613468-cc3f8c00-e9b1-11e8-8a39-9c4f2431eecd.gif)
I've faced the same issue and can reproduce in the examples on that page too.

**Comment by alexcjohnson** [comment]
Thanks @anikets43 - agreed, this is a bug.

**Comment by alexcjohnson** [comment]
FWIW scrollable legends do not have this issue: when you reach the end of a legend, the page does start scrolling.

**Comment by AbdealiJK** [comment]
@alexcjohnson by any chance is there a workaround for this? 
I have a few pages which need to predominantly render tables and if I go to that section of my webpage I'm basically stuck and unable to do anything. Need to find some margin at the extreme corner. 

Got a few bug reports from users that the webpage is stuck and hanging their browser =P

**Comment by alexcjohnson** [comment]
@etpinard let's try to address this for 1.43 - even `staticPlot` doesn't avoid it.

**Comment by AbdealiJK** [comment]
Do let me know if I can help in any way. I'm not adept in js (I use plotly.py ...) otherwise would have attempted a PR...
If I can help by providing debug info or testing or something else pleas feel free to ping me

**Comment by anikets43** [comment]
@alexcjohnson 
In my aplication too this is a major blocker as we have a huge full page table and can't scroll on that page.
Is there a way for me to comment out this event blocking in my server where I am using plotly ? Could you point me to where this event bubbling chain stops ? I'd like to try commenting out the `e.preventDefault()` or whatever is causing this scroll hijack and see whether it fixes it for my table.

**Comment by alexcjohnson** [comment]
This looks like the relevant handler:
https://github.com/plotly/plotly.js/blob/7bb5daaaa118537ca01464d12cdbcef6f9cc764a/src/traces/table/plot.js#L59-L66

**Comment by anikets43** [comment]
Thanks @alexcjohnson 
This would work for now :)
