### ISSUE TITLE
check for jQuery by looking for $ might cause conflicts

### ISSUE THREAD

**Issue by timelyportfolio** [plotly/plotly.js#325]
I discovered this as I explored #83.  In [lines](https://github.com/plotly/plotly.js/blob/master/src/lib/events.js#L56) and [lines](https://github.com/plotly/plotly.js/blob/master/src/lib/events.js#L79) of `events`, there is a check to see if `jQuery` is present by looking for `$`.  I learned that the Chrome command-line API also defines a `$` which causes `$` to not be `undefined` when running from the console and the subsequent `$(plotObj)` to fail.  I am aware of some other libraries that hijack the `$`.  Would `if( typeof jQuery !== undefined)` be a more robust test?  Or should `$(plotObj)` be wrapped in a `try`?

If nothing else, filing (and closing) this issue might help someone else in the future who might be trying to debug this problem.

**Comment by etpinard** [comment]
Interesting. `if( typeof jQuery !== undefined)` does sound more robust.

Filling this as a bug.
