### ISSUE TITLE
Annotations position bug

### ISSUE THREAD

**Issue by tim-sauchuk** [plotly/plotly.js#3253]
I have found that about 60-70% of the time when I load up a plot via Plotly Python Online, an annotation is positioned to the left of the x-position I set. However, if I reload the page enough times, the annotation will eventually move to the correct position.

**Comment by alexcjohnson** [comment]
@tim-sauchuk can you share an example of a plot where this happens?

**Comment by alexcjohnson** [comment]
Here it is in a codepen: https://codepen.io/alexcjohnson/pen/mQXpKK?editors=1000
On first load of the page, the alignment is usually - but not always - incorrect. If you then click "run" up top to rerun the code *without* reloading the page, it will look correct. Thanks for the report @tim-sauchuk! We will at least be able to solve it for your case; finding a solution when you have a background or border may be a little harder.

**Comment by alexcjohnson** [comment]
Ooh maybe this will do it: https://github.com/bramstein/fontfaceobserver
I'm thinking the ideal would be to keep track of requested fonts during `supplyDefaults`, then before actually drawing anything wait for all of these fonts to be available. If they're not available in a reasonable amount of time, continue drawing but then redraw when they *are* all available.

**Comment by archmoj** [comment]
Good idea @alexcjohnson. The sooner we could set up fonts the better. I am curious to know what is the initial font size used to computed the width of the the text?

**Comment by alexcjohnson** [comment]
> I am curious to know what is the initial font size used to computed the width of the the text?

I'm assuming it's whatever fallback font the system uses before the requested font is available.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
