### ISSUE TITLE
Plotly.react problems when switching traces from 'linear' scatter -> 'category' scatterpolar

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#3255]
See https://codepen.io/etpinard/pen/vQJKLd from https://community.plot.ly/t/swapping-from-bubble-to-scatterpolar/15602/10

**Comment by alexcjohnson** [comment]
Wow, that's crazy. I should ask what the heck this line (which is resulting in a whole attempted "re"plot without any associated `calc`) is doing in `supplyDefaults`:

https://github.com/plotly/plotly.js/blob/3a32ac00cf5e8619932f874960f11b4daf7ceb40/src/plots/plots.js#L482-L483

But I'm afraid I'd have to ask myself from 4 years ago 🙄 
Hopefully we can just move this (and the `ax.setScale` loop below it) out of `supplyDefaults` and later in the process, and deal with any consequences in a more rational way!

Kind of amazed this is the first we've seen of this bug... oh well, no time like the present!
