### ISSUE TITLE
scatter3d always selects point 0 on mouse hover

### ISSUE THREAD

**Issue by DirkToewe** [plotly/plotly.js#3258]
From version 1.34.0 and onward, mouse hover on `scatter3d` always picks point number 0. Version 1.33.1 works fine. The problem exists in both Chrome and Firefox on Ubuntu 16.04 and Ubuntu 18.04. Here is a small example:

```js
'use strict';
{
  async function main(){
    const data = [
      {
        type: 'scatter3d',
        mode: 'markers',
        x: Array.from( { length: 25 }, () => Math.random() ),
        y: Array.from( { length: 25 }, () => Math.random() ),
        z: Array.from( { length: 25 }, () => Math.random() )
      }
    ];
    const layout = {};

    const plot = document.createElement('div')
    plot.style = 'width: 90vw; height: 90vh'
    document.body.appendChild(plot)

    await Plotly.plot(plot, data, layout)
    plot.on('plotly_hover', event => console.log(event) )
  }
  main()
}
```

And here is a screenshot of the bug (notice where the mouse is pointing):
![plotly_scatter3d_hover_bug](https://user-images.githubusercontent.com/8115342/48672517-1ef68080-eb37-11e8-95e3-178de1b71d9e.png)

**Comment by alexcjohnson** [comment]
@etpinard @archmoj are you able to reproduce this? It looks fine to me on all browsers on my mac, and on browserstack it seems fine on Windows (wonder when they're going to add Ubuntu???)

**Comment by archmoj** [comment]
@alexcjohnson I was able to reproduce the issue (visible on Ubuntu). Here is a codepen [demo](https://codepen.io/MojtabaSamimi/pen/gQGRPv).

**Comment by Shimwell** [comment]
Also came across this using Ubuntu with Firefox and Chrome.

Hovertext appears to show only the first item from the list of markers

[temp-plot.zip](https://github.com/plotly/plotly.js/files/2594564/temp-plot.zip)

**Comment by etpinard** [comment]
Some potential culprits:

- https://github.com/plotly/plotly.js/pull/2296
- https://github.com/plotly/plotly.js/pull/2293
- https://github.com/plotly/plotly.js/pull/2306
- https://github.com/plotly/plotly.js/pull/2326

**Comment by archmoj** [comment]
I tested this on another laptop running Windows 7, and it works well. So it looks the issue might only be related to Ubuntu. Wondering @bpostlethwaite could you please test this [demo](https://codepen.io/MojtabaSamimi/pen/gQGRPv) on Arch-Linux?

**Comment by bpostlethwaite** [comment]
I can see the same bug - hover shows up on the same point:
Arch-Linux 
Chrome Version 71.0.3578.44 (Official Build) beta (64-bit)

**Comment by Shimwell** [comment]
No sure if this helps narrow down the problem but I just uninstalled plotly (python) version 3.4.1 and installed the newest one 3.4.2 and it fixed this problem for me.
pip uninstall plotly
pip install plotly

**Comment by DirkToewe** [comment]
Thank You so much. Looking forward to the next release.
