### ISSUE TITLE
Bubble pie chart in Plotly.js

### ISSUE THREAD

**Issue by AbhiAbhi21** [plotly/plotly.js#3259]
Hi is there any way to create bubble pie chart in Plotly.js like [this](https://blog.zingchart.com/2015/12/02/bubble-pie-chart-new-js-chart-type/)

**Comment by etpinard** [comment]
merged into https://github.com/plotly/plotly.js/issues/2221

**Comment by cherepanovic** [comment]
@AbhiAbhi21 @etpinard 

is there a solution for this issue?
