### ISSUE TITLE
Create choropleth map based on GeoJSON file

### ISSUE THREAD

**Issue by TheLeonKing** [plotly/plotly.js#326]
I've found a [GeoJSON file][1] containing all cities in The Netherlands. I'm now trying to plot this map using Plotly, but I can't seem to figure out how to do this. I know it's possible to set the scope on a specific country, but Plotly's default map doesn't seem to contain the individual cities for each country.

I'm working based on [this JSFiddle][2] I would elsewhere on Stackoverflow. I know the data is not relevant for The Netherlands, but that doesn't matter at this moment: all I want is a map that looks somewhat like [this][3] (but I like to do it in Plotly, since Plotly's supported in Python).

Any help is greatly appreciated!

  [1]: http://code.highcharts.com/mapdata/countries/nl/nl-all-all.geo.json
  [2]: http://codepen.io/plotly/pen/EVrRxR
  [3]: http://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/nl/nl-all-all

**Comment by etpinard** [comment]
plotly.js maps don't support GeoJSON data nor city-level basemaps at the moment. 

Supporting the above features is in our plans. But, don't expect them to come online in the short-term.

For your purposes, I'd recommend using the [folium](https://github.com/python-visualization/folium) library.
