### ISSUE TITLE
Broken rendering with flat surface and scatter3d traces

### ISSUE THREAD

**Issue by slishak** [plotly/plotly.js#3262]
https://codepen.io/anon/pen/KrXrgJ

In the above codepen, the 3D axis appears to have been corrupted. This only appears to occur when there are both a surface and scatter3d, all the z coordinates are identical, and the z coordinate can not be expressed as `2^n` where n is an integer.

With `z = Math.pow(2, -1)`:
![image](https://user-images.githubusercontent.com/12515343/48703236-5f1b3900-ebf3-11e8-87c3-390b28b15abc.png)

With `z = Math.pow(2, -1) + 0.1`:
![image](https://user-images.githubusercontent.com/12515343/48703217-5460a400-ebf3-11e8-8dc9-aa578ea48024.png)

**Comment by etpinard** [comment]
Thanks for the report.

**Comment by archmoj** [comment]
This [demo](https://codepen.io/MojtabaSamimi/pen/bQZEJZ?editors=0010) illustrates a similar issue when having a `mesh3d` with a surface. So it is not related to `scatter3d` and the bug is likely on the `surface3d` side.
