### ISSUE TITLE
watermark config key

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#3268]
Per https://github.com/plotly/streambed/issues/10708 I'd like to add a default-false boolean key to `config` called `watermark` (or similar) which, when true, would cause the modebar logo to always be visible, even if the modebar is not.

**Comment by antoinerg** [comment]
> when true, would cause the modebar logo to always be visible, even if the modebar is not.

@nicolaskruchten I noticed that the mock @jackparmer made in https://github.com/plotly/streambed/issues/10708 shows a watermark that is much bigger than the modebar logo and it also has the company's name beside it. Should I copy that mock instead? I personally don't any strong preferences but I want to make sure we'll all be happy with how it looks :) 

cc @plotly/plotly_js

**Comment by alexcjohnson** [comment]
Good call, I think we need the company name. I don't think the logo needs to be any bigger than the current one, just have the rest of the modebar fade out and the name fade in in its place (being careful with its color so we know it'll be visible)

**Comment by nicolaskruchten** [comment]
Yeah, ok, let's have the "Produced with Plotly" text appear/disappear also

**Comment by nicolaskruchten** [comment]
I’m unsure actually about the text... I think the logo might be enough for now. When you mouse over it it already says “produced with” or something. Let’s make this a lighter touch for now. Can always change it later

**Comment by alexcjohnson** [comment]
I was thinking just “plotly” - as in @jackparmer’s original mock. Semitransparent, like the modebar itself, would be fine. But the real goal here is when the general viewing public sees these plots they associate our name with them, not just when they mouse over the logo. That’s how they’ll know where to come to make their own plots!

**Comment by antoinerg** [comment]
I agree with @alexcjohnson: the general viewing public needs a keyword to do a search and quickly find us. It's also impossible, obviously, to mouse over on printed figures or PNG.

I'll put "plotly" in my first draft and we can discuss about it again once I submit a PR!

**Comment by nicolaskruchten** [comment]
let's follow up on this in the original issue :)
