### ISSUE TITLE
implement `hovertemplate` for Sankey traces

### ISSUE THREAD

**Issue by OliBravo** [plotly/plotly.js#3269]
Custom HTML code for both links and nodes.

**Comment by antoinerg** [comment]
By adding support for `hovertemplate` to Sankey traces, we would have support for formatting with HTML pseudo-code and access to the different variables of interest to completely control the content of hover boxes.

See PR https://github.com/plotly/plotly.js/pull/3126 for details on `hovertemplate`

**Comment by alexcjohnson** [comment]
There's also #1663

BTW I notice pseudo-HTML is currently honored (in its current limited way) in sankey hover labels but not the node labels:
![screen shot 2018-11-20 at 7 04 38 pm](https://user-images.githubusercontent.com/2678795/48810441-688dc980-ecf7-11e8-9c09-94bcf3679e88.png)

**Comment by antoinerg** [comment]
Nice catch @alexcjohnson ! 

Actually the pseudo-html works in hover labels but not on the node labels that are always displayed.
