### ISSUE TITLE
More than one color to the marker of bubble chart

### ISSUE THREAD

**Issue by AbhiAbhi21** [plotly/plotly.js#3270]
I want to make Bubble Pie chart like [this](https://blog.zingchart.com/2015/12/02/bubble-pie-chart-new-js-chart-type/).

For this I have to assign different colours to the chords of circular marker of this [bubble chart](https://codepen.io/plotly/pen/2aaf878cd2743e2a069fcd32a0dd9c32).
How can more than one color (chord wise) be assigned to a single marker in bubble chart?

**Comment by etpinard** [comment]
Merged into https://github.com/plotly/plotly.js/issues/2221
