### ISSUE TITLE
changing `autocolorscale` via Plotly.restyle only works on first try

### ISSUE THREAD

**Issue by antoinerg** [plotly/plotly.js#3273]
As shown in the following Codepen: https://codepen.io/anon/pen/VVybMO?editors=1000

**Comment by etpinard** [comment]
This one is a side effect from mutating `gd.data[0].colorscale`

In the codepen above, the graph starts out with `gd.data[0].colorscale: 'Viridis'`, after the first `restyle(gd, 'autocolorscale', false)`, line

https://github.com/plotly/plotly.js/blob/11bec79d010a44694bf70b357bd11e11ae874ccb/src/components/colorscale/calc.js#L92

sets `gd.data[0].colorscale: [[0,"rgb(220,220,220)"],[0.2,"rgb(245,195,157)"],[0.4,"rgb(245,160,105)"],[1,"rgb(178,10,28)"]]` and the original `Viridis` is gone.

I wonder if there's a way to make colorscale attributes behave like autobin attributes post https://github.com/plotly/plotly.js/pull/3044 ?
