### ISSUE TITLE
Problems with bar-chart hover labels

### ISSUE THREAD

**Issue by mojoaxel** [plotly/plotly.js#3283]
I just noticed a minor issue in the bar-chart labels.
Here is an example: https://jsbin.com/bulaxix/6/edit?js,output
As you can see on this screenshot the "arrows" behave strange if it gets too crowded:

![image](https://user-images.githubusercontent.com/600565/48957773-2ebcfd00-ef5b-11e8-8fcd-7b0833019acc.png)

By the way: I would like to change the angel of these hover-labels. Is this possible at the moment?

**Comment by etpinard** [comment]
> , it's currently not possible to change this angle, but it's a good idea.

Related: https://github.com/plotly/plotly.js/issues/2170

**Comment by mojoaxel** [comment]
closing as duplicate of #3050
