### ISSUE TITLE
Can't log in to https://community.plot.ly/

### ISSUE THREAD

**Issue by lobachevzky** [plotly/plotly.js#3288]
I apologize for posting website related issues on the Github page, but I did not see a link to website technical support on https://community.plot.ly/.

I am trying to post an issue on that website, and after signing up, I keep getting this message:

> Log In
> You can't log in yet. We previously sent an activation email to you at ethanbro@umich.edu. Please follow the instructions in that email to activate your account.

I have already received the activation email, clicked on the link, and clicked "Click here to activate your account" (numerous times), but I keep receiving the same message (above).

Thank you for helping me with this issue.

Ethan

**Comment by etpinard** [comment]
Ok, I sent you the activation email again to your ethanbro@umich.edu address.

**Comment by lobachevzky** [comment]
Thanks!
