### ISSUE TITLE
MathJax doesn't work in FF

### ISSUE THREAD

**Issue by screeper** [plotly/plotly.js#3290]
Hey,
It seems like MathJax isn't working for Axis Labels. In annotations it works fine. Example can be found here:
[http://jsfiddle.net/x571bzom/](http://jsfiddle.net/x571bzom/)

**Comment by etpinard** [comment]
This is what I'm seeing in Chrome 70:

![image](https://user-images.githubusercontent.com/6675409/49044553-2d2e4780-f19c-11e8-8cd3-d5867aeda381.png)


Could you tells what browser you are using and share a screenshot of what you're seeing. Thank you!

**Comment by screeper** [comment]
This is my view in FF 63.0.3:
![grafik](https://user-images.githubusercontent.com/7382498/49112389-deafa480-f292-11e8-92c0-d1533833b0cd.png)
The $\chi$ (x axis label) is somewhere on the top left

**Comment by etpinard** [comment]
Merging into https://github.com/plotly/plotly.js/issues/2616
