### ISSUE TITLE
Create a "stick-inside" mode for ticks labels

### ISSUE THREAD

**Issue by EBoisseauSierra** [plotly/plotly.js#3292]
Context
---

Say we have a first quadrant chart:

![ticks1](https://user-images.githubusercontent.com/37387755/48778153-606c6480-eccc-11e8-8e38-a753b94c2ab2.png)

One can notice that ticks' labels are horizontally/vertically centred (compared to the ticks themselves) on the horizontal/vertical axis, respectively. 

This makes that  first and last ticks value "stick out" from the graph; what can be a bit ungainly — especially if one shows one axis only:

![ticks3](https://user-images.githubusercontent.com/37387755/48778261-990c3e00-eccc-11e8-8f88-38aeb4c5e998.png)

This is also inconvenient when you want to precisely align you axes with elements surrounding your picture (e.g., in the example above, if you want the `0%` tick mark to be the most-left point of the picture).

Question
---

**➥ Could it be possible to have a "stick inside" mode for ticks values?**

The idea is to change the vertical/horizontal alignment of the first and last ticks values: 

- left and right aligned, respectively, for the horizontal axis: 
![ticks3](https://user-images.githubusercontent.com/37387755/48778172-66fadc00-eccc-11e8-9f8c-37352c798ff3.png)

- bottom and top aligned, respectively, for the vertical axis:
![ticks4](https://user-images.githubusercontent.com/37387755/48778176-69f5cc80-eccc-11e8-8217-8066f84197ce.png)

Our first example would then look like this:
![ticks5](https://user-images.githubusercontent.com/37387755/48777835-92c99200-eccb-11e8-94f9-6f87ab6ef98f.png)

Variant
---
An even more super-duper mode would enable us to choose which end on the axis to "stick inside", so that one could make such graph:
![ticks6](https://user-images.githubusercontent.com/37387755/48777839-965d1900-eccb-11e8-8f39-0d385ff8e5cf.png)

**Comment by etpinard** [comment]
Thanks for writing in.

This request seems very related to https://github.com/plotly/plotly.js/issues/1673

**Comment by EBoisseauSierra** [comment]
@etpinard Indeed! (The catch is here to provide a separate `tickalign` value for each tick).

**Comment by etpinard** [comment]
.. or do something like https://plot.ly/javascript/reference/#layout-xaxis-showexponent with values ` "all" | "first" | "last" | "none"`

**Comment by EBoisseauSierra** [comment]
that could be a solution.

My initial thoughts were to be able to:
- either set `tickalign` as a [0,1] float, and apply this value to all tick,
- or set `tickalign` as a list of [0,1] floats, with a length equal the number of ticks displayed, and apply each `tickalign` respectively. (This might not be the best way to go, though, as it might be difficult to know in advance the number of ticks. Plus it's not efficient if you want to customise the last tick only… A workaroud — yet limiting the "customisability" — would be to provide a list of length 3, for [first, middles, last]…)

**Comment by walter9388** [comment]
any update on this?

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
