### ISSUE TITLE
Fill tonexty fails with missing values

### ISSUE THREAD

**Issue by jonmmease** [plotly/plotly.js#3296]
Originally reported in the plotly.py forums: https://community.plot.ly/t/filled-area-plots-with-na-in-between-points-not-working-as-expected/16024

Pen: https://codepen.io/jonmmease/pen/LXgZxW?editors=1010
```javascript
var fig = {
  "data": [
    {
      "mode": "lines",
      "name": "high",
      "type": "scatter",
      "x": [
        "W01",
        "W02",
        "W03",
        "W04",
        "W05",
        "W06"
      ],
      "y": [
        1.5,
        1.6,
        1.8,
        null,
        2,
        2.4
      ]
    },
    {
      "fill": "tonexty",
      "mode": "lines",
      "name": "low",
      "type": "scatter",
      "x": [
        "W01",
        "W02",
        "W03",
        "W04",
        "W05",
        "W06"
      ],
      "y": [
        1.4,
        1.3,
        1.2,
        null,
        2,
        2.1
      ]
    }
  ],
  "layout": {}
}

Plotly.newPlot('myDiv', fig);
```
![newplot-1](https://user-images.githubusercontent.com/15064365/49148860-8e5a3600-f2d6-11e8-876a-87c2b4113125.png)

expected resut: something like 
![newplot-2](https://user-images.githubusercontent.com/15064365/49149058-180a0380-f2d7-11e8-8664-1f861b5cf5e7.png)
with the region between `W03` and `W05` empty.

**Comment by etpinard** [comment]
Similar to https://github.com/plotly/plotly.js/issues/2736

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
