### ISSUE TITLE
Candlestick treats null values differently from other charts when using Fx.hover

### ISSUE THREAD

**Issue by jakubkottnauer** [plotly/plotly.js#3298]
For simplicity, let's say two charts (a candlestick chart and a bar chart) have the same data for the `x` axis. When there are `null`/`undefined` values in the y axis data and hover state is shared between charts using `Fx.hover`, the `pointNumber` value taken from the `plotly_hover` event doesn't correspond to the correct element in the candlestick chart - the position is offset exactly by the number of `null` values preceding the hovered element - while the bar charts treats `null` values correctly and the correct value is hovered.

See the codepan example demonstrating the described behavior: https://codepen.io/jakubkottnauer/pen/xQQYje

**Comment by etpinard** [comment]
Thanks for the report!
