### ISSUE TITLE
Allow replot during drag interactions

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#3305]
Combining issues https://github.com/plotly/plotly.js/issues/2438, https://github.com/plotly/plotly.js/issues/2687, https://github.com/plotly/plotly.js/issues/2644 and https://github.com/plotly/plotly.js/issues/2643 into a single ticket - as all these issues are likely to be fixed once we implement @alexcjohnson 's https://github.com/plotly/plotly.js/issues/2644#issuecomment-391152782 :

> I could do various simple things to avoid the particular error seen here (recalc before bailing out of `Plotly.plot`, or use some other signal besides deleting `gd.calcdata`, or just check if `gd.calcdata` exists before trying to relink it) but all of those have problems of various severity with the plot data being out of sync with the displayed plot, which are going to bite us down the line in obvious or subtle ways.

> I think the solution is to make something like [`gd._hoverData` and `Plots.rehover`](https://github.com/plotly/plotly.js/blob/master/src/plots/plots.js#L2420) but for dragging, so we can get rid of that `gd._dragging` bail out, actually do the replot, then re-establish the partial drag (be it a pan, a zoom, a select...). Obviously this has the potential to be a bit of a project, given all the different `dragmode` settings; but it would also address the use case of streaming (or otherwise changing independent of user interaction) data.

**N.B.** the promise rejections comes from:

https://github.com/plotly/plotly.js/blob/7bb5daaaa118537ca01464d12cdbcef6f9cc764a/src/plot_api/plot_api.js#L139-L149

---

Note that this same problem affect panning on graphs with `axis.automargin: true`: https://codepen.io/etpinard/pen/BGEjwY?editors=0010

**Comment by etpinard** [comment]
Examples from previous issues:

- https://codepen.io/skyandrd/pen/oERddp `Plotly.update` during zoombox drag
- https://codepen.io/watashiku/pen/pKJJNW?editors=1010 `Plotly.update` during pan
- https://github.com/plotly/plotly.js-crossfilter.js/tree/react `Plotly.react` in `plotly_selecting` handler
- https://codepen.io/galuha/pen/ywMmPZ?editors=1111 `Plotly.extendTraces` during zoombox drag
- https://codepen.io/plotly/pen/dRaawR `Plotly.extendTraces` during zoombox drag
- https://codepen.io/swiperii/pen/wyPEBW?editors=0010 `Plotly.react` during zoombox drag
- https://codepen.io/TMS8503/pen/wqxLYL `Plotly.restyle` during zoombox drag
- https://dash-bio.plotly.host/dash-alignment-viewer/ (not exactly sure what's happening in that one, yet)

**Comment by brian428** [comment]
I'll add that if you click to edit an annotation, then click the annotation again while the text field is showing, Plotly throws "Uncaught (in promise): [object Undefined]" during the relayout. I assume it's related to this issue.

**Comment by etpinard** [comment]
@brian428 

> I'll add that if you click to edit an annotation, then click the annotation again while the text field is showing

This deserves a separate issue. Would you mind opening one and/or sharing a reproducible codepen. Thank you!

**Comment by etpinard** [comment]
Closing (but might re-open later) as https://github.com/plotly/plotly.js/pull/3716 is now merged.

Starting in 1.47.0, all the bug reports listed in this ticket should be fixed.
