### ISSUE TITLE
an idea for eliminating datetime gaps of time series

### ISSUE THREAD

**Issue by gzadigo** [plotly/plotly.js#3314]
when I display stock price series on minutes basis, you know, in a day there are many minutes without trading, so we see discontinous price on the chart. I think this could be done like this (in python):

        ts = pd.Series(index=datetime_list, value=stock_price_list)
        params = {
            'title':title,
            'xaxis':dict(title=xaxis, x=range(len(ts)), mark=datetime_list)
            'yaxis':dict(title=yaxis),
        }
        layout = go.Layout(**params)

this is a straigforward way and easy to implement, please consider it. thanks a lot!!!

**Comment by gzadigo** [comment]
why no one replay on this topic? I hope to know whether I am wrong or not?

**Comment by etpinard** [comment]
Your solution looks a lot like the existing `tickvals` and `ticktext`:

https://plot.ly/javascript/axes/#enumerated-ticks-with-tickvals-and-ticktext

---

We already have https://github.com/plotly/plotly.js/issues/1382 for discussing this topic, so I'll close this ticket. Thanks for writing in.
