### ISSUE TITLE
Support for raster graphics

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#332]
To support something like [`annotation_raster()`](http://docs.ggplot2.org/current/annotation_raster.html) in our R package, which would lead to awesomeness such as conversion of [ggmap](https://journal.r-project.org/archive/2013-1/kahle-wickham.pdf) (people have been [asking for this](https://github.com/ropensci/plotly/issues/13) for a _long_ time), I need support for displaying a matrix of arbitrary color codes. Using a heatmap seems out of the question since we can't generate a sensible colorscale, and drawing a marker for each cell seems inefficient.  Any thoughts on how to approach this?

**Comment by mdtusz** [comment]
As far as I can tell, this would be fairly straightforward as far as the actual graphics part goes. The interface and having things play nicely with axes, ranges etc. might be trickier just because of the structure and codepaths that exist as of now. 

Adding a canvas layer for images or raw raster data would be a fairly efficient draw provided the data doesn't require much processing, but I can't really think of any _intensive_ processing that would slow down a draw.

**Comment by jackparmer** [comment]
Seems like this would be a great way to make geographic contour maps like this too:

![image](https://cloud.githubusercontent.com/assets/1865834/15788270/ab3d0936-2994-11e6-83f1-1c848f86b693.png)
(via PlanetOS, http://data.planetos.com/datasets/noaa_gfs_global_sflux_0.12d:gfs-global-weather-forecast-by-ncep-near-surface-parameters)

Plotly user `ToniBois` has been making some incredible geographic contour maps / weather maps in Plotly:

![image](https://cloud.githubusercontent.com/assets/1865834/15788325/0b59b792-2995-11e6-8c7b-e9d002535ded.png)

https://plot.ly/~ToniBois/

But they would be unpractically slow to load for most users compared to the PlanetOS ones. It would be awesome to provide fast, interactive weather maps to Plotly's users, but I don't know whether this or the `contourgl`/`heatmapgl` projects are better bets. @etpinard @monfera ?

**Comment by jackparmer** [comment]
Another great weather map example from NREL. Could be incredible as an interactive:

![image](https://cloud.githubusercontent.com/assets/1865834/15788798/413e7422-2997-11e6-8eb1-38b27fe52cdc.png)

**Comment by mdtusz** [comment]
Not sure if things like :arrow_up: fit in best with a raster type - they're much more applicable as contours/heatmaps in my mind. 

For raster data however (that is, values consistent/regular in their distribution across a width and height) we should be able to handle up to ~4 megapixels before it becomes _too_ slow. 

http://jsbin.com/reqazezagi/edit?js,output

**Comment by monfera** [comment]
Yes as both of you guys say a contour plot would be a first candidate.

**Comment by garyfeng** [comment]
I see "raster image support coming up soon" referenced in the current code. Wonder if how soon and how to contribute. 

I need a transparent background image for a heatmap plot. Have been hacking the SVG output to insert an image layer, see
https://gist.github.com/garyfeng/9516714839c84a1982dda74dd5f14a6c. Unless there is a master plan, I will probably go into the heatmap code and add a background parameter to the SVG output. Would like to know who else might be working on this and whether there is a better way.

**Comment by mdtusz** [comment]
The raster type will likely be used more for _raw raster data_ rather than images - you can add images however using [`layout.images`](https://github.com/plotly/plotly.js/blob/master/test/image/mocks/layout_image.json) and setting the `xref` and `yref` to”” the respective axes. Note however that the image will be distorted when the plot bounds are changed (i.e. when zoomed).

**Comment by ssfrr** [comment]
I just wanted to plug my use-case for visualizing matrices as raster plots. I do audio DSP research using Jupyter and spend a lot of time looking at spectrograms like this:

![image](https://cloud.githubusercontent.com/assets/734386/20955399/04a3f73c-bc11-11e6-95f5-a366fc712555.png)

I've been using `heatmap`, but they really slow down my notebooks compared to something like matplotlib that generates and displays a png.

**Comment by cpsievert** [comment]
I think this can be closed now? Thanks to `layout.images` we can fully support `annotation_raster()` in the R package.

https://cpsievert.github.io/plotcon17/workshop/day1/#45

**Comment by ssfrr** [comment]
I'm still hoping for support for raw raster data, e.g. if I have a 2D matrix of floats I want to visualize them as a colorscaled grid with axes. Most of my data are not huge (~1000x1000) but visualizing them as a heatmap slows down my notebooks quite a bit. Is there a better way to do this? (using the javascript API)

**Comment by jackparmer** [comment]
@ssfr have you tried using `heatmapgl` (the webgl version of plotly heatmaps)? Here's an example in Python:
https://plot.ly/python/heatmap-webgl/

**Comment by ssfrr** [comment]
@jackparmer strangely the GL versions seems to perform about the same, maybe worse. I'm going to a little digging to see where the issues are.

**Comment by jackparmer** [comment]
Thanks @ssfrr . If you have a link to a chart (both an SVG and GL version), that would help to debug. Here's a link to a GL audio spectrogram for example: https://plot.ly/~PythonPlotBot/829
