### ISSUE TITLE
Zoom not always triggered

### ISSUE THREAD

**Issue by Jodana** [plotly/plotly.js#333]
When you try to zoom-in, sometimes Plotly does not react accordingly even if the UI reflects the selection (as shown below): it simply hangs in this state until the user makes another action.

![image](https://cloud.githubusercontent.com/assets/17881065/13814885/7955620a-eb88-11e5-93a6-2cc5f1a4aab2.png)

How to reproduce:
1) Go to: https://plot.ly/javascript/time-series/
2) Zoom on a point
3) De-zoom and start to zoom (resulting in a triple-click), but do not release the mouse button
4) Release the button to trigger the zoom event : nothing happens

**Comment by etpinard** [comment]
> Plotly does not react accordingly even if the UI reflects the selection

Does that happen on **every** zoom drag movements? I remember experiencing that on sporadic occasions.

**Comment by etpinard** [comment]
> De-zoom and start to zoom (resulting in a triple-click), but do not release the mouse button

Haha. Bingo. I can reproduce it now.

Thank you very much for this bug report.

**Comment by mdtusz** [comment]
To expand on this, it appears to be an issue present whenever the mouse actions occur within the doubleclick delay.
