### ISSUE TITLE
update `vertextcolor` description to note the range of the values

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.js#3348]
I was just reading through a community member's notebook (https://plot.ly/~empet/15040/plotly-mesh3d-from-a-wavefront-obj-f/#/) and came across this comment:
![image](https://user-images.githubusercontent.com/1280389/50180636-306aae00-02d8-11e9-9892-20424cb79697.png)

Indeed, looks like the `vertexcolor` description is a little terse, could mention that this color needs to be normalized between `0` and `1`, unlike other color mappings:
https://github.com/plotly/plotly.js/blob/83fd6512178a0881ed9a960ab88a4c2393e88b04/src/traces/mesh3d/attributes.js#L150-L158

**Comment by etpinard** [comment]
Hmm. RGB colors seem to work ok:

https://codepen.io/etpinard/pen/GPNwYX?editors=0010

**Comment by archmoj** [comment]
@etpinard I think the point is that when users have 3-D models in OBJ format (where the alpha is written in the range of 0 to 255), they need to map it to fit in [0,1]. So they can't use their raw alpha values [such as 127 in this example](https://codepen.io/MojtabaSamimi/pen/qLqQvP?editors=0010).
