### ISSUE TITLE
'Layout options' section has disappeared from online documentation

### ISSUE THREAD

**Issue by gramster** [plotly/plotly.js#335]

**Comment by etpinard** [comment]
duplicate of https://github.com/plotly/documentation/issues/202

**Comment by gramster** [comment]
Is it a dup? I don't really understand what that other bug is about. Mine is about the fact that on the documentation page in the left hand nav list under 'Examples' there is a final item 'Layout Options' which links to https://plot.ly/javascript/#layout-options but that does not exist.

**Comment by etpinard** [comment]
You're right. This is a separate issue. My mistake.

That said, please open docs-related issue in our [documentation repo](https://github.com/plotly/documentation/issues/new) in the future.
