### ISSUE TITLE
[Bug] <sup> for trace.name is not respected in hoverlabel

### ISSUE THREAD

**Issue by Braintelligence** [plotly/plotly.js#3357]
Hello everyone.
If you provide a name for your trace containing `<sup>` it doesn't work for hoverlabels with hoverinfo containing name.

https://codepen.io/anon/pen/aPpmzw

As you can see, the legend is correct but the hoverlabel shows the number as if `<sup>` was never provided.

**Comment by Braintelligence** [comment]
Just to make sure: This bug is still true for 1.43.0.

**Comment by etpinard** [comment]
Thanks for the report

**Comment by Braintelligence** [comment]
@etpinard Did someone look at this bug yet? 😸 Need to know if this will be fixed within this quarter, so I can refactor some of the plots before we publish them with this bug.

**Comment by etpinard** [comment]
We currently strip out all pseudo-html tags for `trace.name` here:

https://github.com/plotly/plotly.js/blob/51b5c25bcc81109575d77f0eddc8510147ca5172/src/components/fx/hover.js#L927-L937

I don't remember why we do this. Maybe @alexcjohnson remembers?

**Comment by alexcjohnson** [comment]
I suspect we hadn't bothered figuring out vertical sizing of the name field, also we're often truncating the name and it could be weird to truncate in the middle of some pseudo-html. Probably wouldn't be too hard to resolve these issues and allow pseudo-html there though. I'm a bit concerned about color there though: it would be pretty easy to have colored text in the legend - either part or all of `name` - that would be ugly or even invisible in the hover label.

**Comment by Braintelligence** [comment]
Would it be viable to just allow <sup> for now?
