### ISSUE TITLE
how can i bind event to g.layer-above > g.shapelayer?

### ISSUE THREAD

**Issue by merturl** [plotly/plotly.js#3358]
i use shapes for vertical dash-line 
like this
![image](https://user-images.githubusercontent.com/23473356/50270220-372e2800-0474-11e9-97b5-d9c660d7a68f.png)

but.. i heard shapes is not supported mouse hover tooltip.
so i try to custom event for tooltip in shapes use jquery
```
const divs = document.querySelectorAll('svg:nth-child(3)');
or
const divs = document.querySelectorAll(''g.layer-above > g.shapelayer');
      divs.forEach(function(div) {
        console.log(div);
        div.addEventListener('mouseover', function(event) {
          console.log(event);
        });
      });
```

but I didn't get the results I wanted.
so Is there any other way?

**Comment by etpinard** [comment]
Best for https://community.plot.ly/c/plotly-js

Thank you.
