### ISSUE TITLE
Bug with latest version, opts.dflt is undefined

### ISSUE THREAD

**Issue by ShaneHudson** [plotly/plotly.js#3359]
Unfortunately upgrading to the latest version (v1.43) has not been possible for me. I particularly want it due to the fix of #3306.

I am unsure how to replicate the bug (it may be due to have a large amount of null data) but can show a screenshot of the issue. It happened once I upgraded to 1.43 and going back to 1.42.5 fixed the issue.

<img width="962" alt="screenshot 2018-12-20 10 46 35" src="https://user-images.githubusercontent.com/487005/50283882-2c14d100-044f-11e9-8367-9d5450e1e443.png">

**Comment by etpinard** [comment]
Thanks very much for the report!

> I am unsure how to replicate the bug

Could you just share the "data" and "layout" you used to generate your graph?

**Comment by ShaneHudson** [comment]
[data.txt](https://github.com/plotly/plotly.js/files/2699613/data.txt)
[layout.txt](https://github.com/plotly/plotly.js/files/2699614/layout.txt)

Here you are, they are large amounts of data but primarily null. Please advise me if there are better ways of achieving this but previously the data would autofill when we need to see the blank space.

**Comment by archmoj** [comment]
OK. @etpinard Let me test this...

**Comment by etpinard** [comment]
My gut feeling: this appears like a bug coming from the new multicategory logic that propagated to 3D erroneously.

Thanks for your help @archmoj !

**Comment by archmoj** [comment]
Here is a simplified [demo](https://codepen.io/MojtabaSamimi/pen/rojPwK) that could be used (by changing the version to v.1.43.0) to illustrate the regression coming from the new multi-category logic as @etpinard mentioned which happens when one has both heatmap and surface traces.

**Comment by archmoj** [comment]
@etpinard here is another observation: 
Not only `surface` plot that has this issue. It is not possible to add another trace e.g. `scatter3d` after `heatmap` set the axis type to `multicategory`. Here is a [demo](https://codepen.io/MojtabaSamimi/pen/JwEVMM?editors=1010).

**Comment by ShaneHudson** [comment]
> @ShaneHudson Until this regression is addressed you could test the changes with v.1.43.0; however, you would need to move your `surface` plot data to the top of the file. Please refer to the attachment below!

Thank you, this fixed the issue.

> Also as described on #3306, you may consider changing the times on the ticks from dates to minutes until #3306 fixed.

Hmm yes, that is possible but would rather not as I also have minutes/hours/days too.
