### ISSUE TITLE
data missing when multiple parcoords traces

### ISSUE THREAD

**Issue by jonmmease** [plotly/plotly.js#3361]
Originally reported in https://github.com/plotly/plotly.py/issues/1372

When multiple `parcoords` traces are placed in the same figure, the data lines only show up for the first trace.  Subsequent traces display their axes, but no data lines.

CodePen: https://codepen.io/jonmmease/pen/xmqqJP

Code:

```JavaScript
var fig = {
  "data": [
    {
      "dimensions": [
        {
          "constraintrange": [
            1,
            2
          ],
          "label": "A",
          "range": [
            1,
            5
          ],
          "values": [
            1,
            4
          ]
        },
        {
          "label": "B",
          "range": [
            1.5,
            5
          ],
          "tickvals": [
            1.5,
            3,
            4.5
          ],
          "values": [
            3,
            1.5
          ]
        }
      ],
      "domain": {
        "x": [
          0,
          0.45
        ],
        "y": [
          0,
          1
        ]
      },
      "line": {
        "color": "blue"
      },
      "type": "parcoords"
    },
    {
      "dimensions": [
        {
          "constraintrange": [
            1,
            2
          ],
          "label": "C",
          "range": [
            1,
            5
          ],
          "values": [
            1,
            4
          ]
        },
        {
          "label": "D",
          "range": [
            1.5,
            5
          ],
          "tickvals": [
            1.5,
            3,
            4.5
          ],
          "values": [
            3,
            1.5
          ]
        }
      ],
      "domain": {
        "x": [
          0.55,
          1
        ],
        "y": [
          0,
          1
        ]
      },
      "line": {
        "color": "blue"
      },
      "type": "parcoords"
    }
  ],
  "layout": {
    "title": "Multi-Parcoords Diagram"
  }
}

Plotly.plot('plotly-div', fig);
```
![newplot-5](https://user-images.githubusercontent.com/15064365/50341405-a5aecc80-04ec-11e9-97cd-4feb6a7eb1d0.png)

This worked fine in 1.31.0, seems to have broken in 1.32.0, and remains broken in 1.33.0.

**Comment by archmoj** [comment]
[Codepen](https://codepen.io/MojtabaSamimi/pen/PvymZq?editors=0010)

**Comment by archmoj** [comment]
Likely related to https://github.com/plotly/plotly.js/pull/2159.

**Comment by archmoj** [comment]
This is the result of this commit: https://github.com/plotly/plotly.js/pull/2159/commits/e6fcbf51de4b41db470b7194835b20f57f06098f
![Screenshot from 2019-05-30 14-48-49](https://user-images.githubusercontent.com/33888540/58656356-24086980-82ea-11e9-9b2c-fcc13ef0291e.png)

**Comment by emmanuelle** [comment]
Also mentioned here in the forum https://community.plot.ly/t/subplots-with-parallel-coordinates-not-showing-second-subplot/35239/2

**Comment by heroldn** [comment]
And here https://stackoverflow.com/questions/60393815/plotly-parallel-coordinates-charts-dont-display-correctly-in-subplots

**Comment by tzhang-lilly** [comment]
Hi, I think the bug is not related to the constraints on the graph. I had the same issue with the stackoverflow post. With multiple subplots, only the first graph would show up...

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
