### ISSUE TITLE
Adapt jasmine tests for jasmine-core@3

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#3368]
```
npm i jasmine-core@3.3.0 karma.jasmine@2.0.1
npm run test-jasmine -- --nowatch
```

make numerous tests fail, spits out deprecation warnings:

![image](https://user-images.githubusercontent.com/6675409/50366272-c3a91b00-0546-11e9-8588-58d625cc9eae.png)

and doesn't get along with our `negateIf` custom matcher

https://github.com/plotly/plotly.js/blob/cbaae9a41e95161a839d2084ac984863f427f10d/test/jasmine/assets/custom_matchers.js#L212-L215

![image](https://user-images.githubusercontent.com/6675409/50366306-e76c6100-0546-11e9-9bc5-a23db251ef5f.png)

----

More info about jasmine@3:

https://github.com/jasmine/jasmine/blob/master/release_notes/3.0.md

More info about karma-jasmine@2:

https://github.com/karma-runner/karma-jasmine/blob/master/CHANGELOG.md#200-2018-11-15

**Comment by etpinard** [comment]
... and note that `karma-jasmine-spec-tags@1.1.0` is only compatible with `karma-jasmine@2x`

https://github.com/mnasyrov/karma-jasmine-spec-tags

**Comment by etpinard** [comment]
See https://github.com/plotly/plotly.js/tree/bump-jasmine for the current state of affairs.

**Comment by etpinard** [comment]
It seems that the new `jasmine-core` version shuffle the tests by default. We'll need to rewrite the tests have a [`@noCIdep` tag](https://github.com/plotly/plotly.js/blob/24deba631094ba326be5fb2dafa5e50a2031fd49/test/jasmine/tests/plot_api_react_test.js#L21).

**Comment by etpinard** [comment]
their docs look more thorough than before too:

https://jasmine.github.io/api/3.4/global

**Comment by etpinard** [comment]
Things are looking up!

By setting `random: false` thus making our test running in order (like they are currently) make `npm run test-jasmine` run smooth :boat: 

https://github.com/plotly/plotly.js/compare/bump-jasmine

Now, the main "blocker" is `negateIf`. We either:

- convert its declaration to something that `jasmine-core@v3` is ok with (see [src](https://github.com/jasmine/jasmine/blob/b4cbe9850fbe192eaffeae450669f96e79a574ed/src/core/Expectation.js) for inspiration), or 
- :hocho: it and adapt the tests currently using `negateIf` . 

As adding stuff to the `jasmine.Expectation` prototype isn't recommended in jasmine [docs](https://jasmine.github.io/api/3.4/global), I'll vote for the :hocho: . Does anyone oppose?

**Comment by etpinard** [comment]
`jasmine-core@3.3.0` added `expect(...).withContext('extra message').toEqual(...)` to (finally) make `toEqual(...)` log extra info in failure messages.

https://github.com/jasmine/jasmine/blob/master/release_notes/3.3.0.md

**Comment by alexcjohnson** [comment]
🔪 `negateIf` is fine - it's just a convenience. If it becomes cumbersome without it, could always turn it into a plain function... just doesn't read quite as well as the method.
```js
function negateIf(expectation, condition) {
   return condition ? expectation.not : expectation
}
```
