### ISSUE TITLE
Too many active WebGL contexts. Oldest context will be lost

### ISSUE THREAD

**Issue by xzmagic** [plotly/plotly.js#337]
I hava a proplem while use plot_ly 10 times to create 10 surface plots. I get waring:Too many active WebGL contexts. Oldest context will be lost, so plot not show but the first 9 plot can show normally. warning details： plotly-latest.min.js:19 WARNING: Too many active WebGL contexts. Oldest context will be lost. plotly-latest.min.js:36 lost context

plot_ly is a R function that warp plotly.js function
Is there a way workaround this proplem?

**Comment by etpinard** [comment]
> 10 times to create 10 surface plots

Wo. Are you plotting 10 separate surface plots? Or are you redrawing the same graph 10 times?

If the later, this is a bug on our part.

If the former, then you're hitting the limitation of our current implementation. We make one WebGL context per graph meaning that pages with multiple plotly WebGL graphs are exposed to the browser's context cap.  I'm afraid that there's no workaround at the moment.

**Comment by xzmagic** [comment]
Thank you !This is very helpful info for me.

**Comment by bytesnz** [comment]
I am also seeing the same issue. I have a page with 4 scatter-gl plots on it that are redrawn (`purge` and `newPlot`) when zooming in on data (as it downloads higher resolution data). Once the graphs are redrawn a couple of times, you start getting the WebGL warning messages. Was wondering if the GL context wasn't being "removed completely" on `purge` (related issues https://github.com/pixijs/pixi.js/issues/2233#issuecomment-181650433)?

Hack of an example https://codepen.io/bytesnz/pen/XBaoee

**Comment by gnestor** [comment]
Replacing Plotly.newPlot with Plotly.react also worked for us 👍: https://github.com/stencila/stencila/issues/687
