### ISSUE TITLE
Inside texts in stacked bar charts are cut off for log scale

### ISSUE THREAD

**Issue by Ejdamm** [plotly/plotly.js#3373]
If the inside text for the bottom bar in a stacked bar chart does not fit it will be cut off, instead of shrinking. This only happens for log scale.

Look at this codepen example and compare how "giraffes in LA zoo" text is shrunk while "orangutangs in SF zoo" text is cut off. 
https://codepen.io/Ejdamm/pen/ebRJMN

**Comment by etpinard** [comment]
You'll need to set `cliponaxis: false`. We currently clip text nodes around the subplot limit by default at the moment. Here's an example: https://codepen.io/etpinard/pen/BvdxvV (I made the text red, to see the unclipped text better).

**Comment by Ejdamm** [comment]
Okay that helps but what I really want and think would be default behavior is that the text shrinks like in the rest of the bars.

You see in the orange giraffe bar, the text doesn't fit so it have shrunk instead of overflowing.

**Comment by Ejdamm** [comment]
Yes the behavior for linear scales is consistent and what I am looking for in the log scale. My actual data are sometimes 100 for one bar and 1M on another so linear scale is not an option. Also the chart is made automatically every week so i can't set the fontsize manually. Thanks for the tips though!
