### ISSUE TITLE
Error bar trace ordering

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#338]
Discovered via https://github.com/ropensci/plotly/issues/513 

Here is a MRE http://codepen.io/cpsievert/pen/NNddEa

**Comment by etpinard** [comment]
A side effect from our per-trace type `<svg>` layer [ordering](https://github.com/plotly/plotly.js/blob/a27d62ca9b157db473e2a3bd8b51634fff2433b5/src/plot_api/plot_api.js#L2671-L2678). 

Error bar `<g>`s should really be part of their corresponding  `<g class="scatterlayer">` and/or `<g class="barlayer">` to avoid this effect.
