### ISSUE TITLE
Parcoords colorscales not showing up on FF64 on mac

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.js#3385]
It looks like the parcoords colorscales aren't showing up. 
- originally posted in the dash community forum: https://community.plot.ly/t/parallel-coordinates-lost-color/17412
- I see the issue in the docs as well: https://plot.ly/python/parallel-coordinates-plot/

![image](https://user-images.githubusercontent.com/1280389/50611553-e02d4780-0ea4-11e9-8819-d67116dca7e5.png)

**Comment by etpinard** [comment]
Looks like fine for me:

![image](https://user-images.githubusercontent.com/6675409/50611713-621d7080-0ea5-11e9-8586-8ab665aab68e.png)

Can anyone else give https://plot.ly/~bdun9/1149.embed a :eye: ?

**Comment by chriddyp** [comment]
Ah, looks OK for me on chrome. Doesn't work for me on Firefox 64.0

**Comment by etpinard** [comment]
Weird.

![image](https://user-images.githubusercontent.com/6675409/50611872-00a9d180-0ea6-11e9-8f2f-d7ef6c1af4f5.png)

looks also good for me on FF64 (on a t450s thinkpad running Ubuntu 18.04).

**Comment by alexcjohnson** [comment]
Worked for me with FF 63 on mac, but then FF updated to 64 and the colors disappeared

**Comment by etpinard** [comment]
Thanks for checking @alexcjohnson !

Have you spotted any console errors?

**Comment by alexcjohnson** [comment]
no console messages.

**Comment by archmoj** [comment]
I upgraded to FF64; but I don't see the bug. So the browserstack option is better. Thanks you @etpinard in advance.

**Comment by etpinard** [comment]
> but I don't see the bug.

Yes, it appears to only be visible on Macs.

**Comment by etpinard** [comment]
@archmoj can you think of any way to fix this?

**Comment by archmoj** [comment]
It works well on FireFox 66, 65 & 63.
Closing.
