### ISSUE TITLE
3D graph axis rendering in FF64 + mac

### ISSUE THREAD

**Issue by ShaneHudson** [plotly/plotly.js#3387]
I've noticed graphs that look perfectly fine in Chrome look "dodgy" in Firefox. I'm not sure if it is to do with antialiasing or what but the labels and axis look many times better in Chrome.

Take the documentation's 3D surface graph for example: https://codepen.io/plotly/pen/MaxrwW

Firefox:
![screenshot 2019-01-03 10 31 06](https://user-images.githubusercontent.com/487005/50633400-0f929180-0f43-11e9-923d-a74bbcdb9ba0.png)

Chrome:
![screenshot 2019-01-03 10 31 31](https://user-images.githubusercontent.com/487005/50633401-0f929180-0f43-11e9-8f11-369c365c5405.png)

Is there anything that can be done to improve this? Firefox definitely gets a less polished result. While it looks "ok" in the screenshots, if you actually interact with the graphs Firefox is even worse.

**Comment by etpinard** [comment]
Thanks for the report.

Can you tell us which Firefox version you're using and which OS you're on. Some info about your hardware might be nice also.

Thank again.

**Comment by ShaneHudson** [comment]
Firefox 64.0 (64-bit)
MacBook Pro (15-inch, 2016)
High Sierra 10.13.6
2.7 GHz Intel Core i7
16 GB 2133 MHz LPDDR3
Radeon Pro 455 2048 MB
Intel HD Graphics 530 1536 MB

Hope that helps :)

**Comment by ShaneHudson** [comment]
On my project I've got the axis and text as white on grey and it flickers badly on interaction in Firefox (as it does in the demo but more obvious if you change colours).

**Comment by ShaneHudson** [comment]
Chrome Version 71.0.3578.98 (Official Build) (64-bit) works fine

**Comment by etpinard** [comment]
Thanks @ShaneHudson 

Looks like we have another FF64 + mac bug (cc https://github.com/plotly/plotly.js/issues/3385)

**Comment by etpinard** [comment]
@archmoj any hints on why this is happening?

**Comment by archmoj** [comment]
@ShaneHudson thanks for the report.
Could you please download the graphs `as png` using the Plotly.js modebar (at initial camera position) on Chrome and Firefox, and them upload them here?

**Comment by ShaneHudson** [comment]
Chrome: ![chrome_plotly](https://user-images.githubusercontent.com/487005/53108868-ae913e00-352f-11e9-8c8d-6d8c30aae82d.png)
Firefox: ![firefox_plotly](https://user-images.githubusercontent.com/487005/53108869-ae913e00-352f-11e9-9ee0-34abf083c641.png)

The issue doesn't seem to exist when downloading as png.

**Comment by ShaneHudson** [comment]
It's slightly worse in Firefox but not as bad as viewing in browser (without even interacting).

**Comment by ShaneHudson** [comment]
![screenshot 2019-02-20 16 52 16](https://user-images.githubusercontent.com/487005/53108985-e5675400-352f-11e9-8c73-7edf6323d859.png)
Here's another example of Firefox in browser

**Comment by archmoj** [comment]
@ShaneHudson thanks for the feedback. 
Could you please try increasing the `width` and `height` of you graph for example to 1000 to see if it is not desirable?

**Comment by archmoj** [comment]
This issue is basically related to a limitation that some browsers (not Chrome) don't apply `antialias: true` webgl flag. 
In the [first codepen](https://codepen.io/MojtabaSamimi/pen/LqoMOX?editors=1000) the `antialias` is set to `false` to illustrate similar undesirable performance may happen in Chrome when it is disabled by default.
This [second codepen](https://codepen.io/MojtabaSamimi/pen/YBbdmz?editors=1000) which imports Plotly at 1.44.4 could also be handy for a comparison (again using Chrome) .
@etpinard @alexcjohnson To improve this behaviour for FF & iOS users one idea could be to increase line widths e.g. in `gl-axes3d` vertex shader program. What do you think of that?

**Comment by etpinard** [comment]
> To improve this behaviour for FF & iOS users one idea could be to increase line widths e.g. in `gl-axes3d` vertex shader program. What do you think of that?

Yep, let's try that out!

**Comment by etpinard** [comment]
... and generate all the gl3d baselines up on a branch.

**Comment by archmoj** [comment]
@ShaneHudson now on iOS and FireFox would you mind checking this [third codepen](https://codepen.io/MojtabaSamimi/pen/JxQdKq?editors=0010), and also comparing [this one](https://codepen.io/MojtabaSamimi/pen/RvzaGr) which is based on your example; and possibly confirm the improvements?

**Comment by ShaneHudson** [comment]
<img width="651" alt="screenshot 2019-02-22 09 40 10" src="https://user-images.githubusercontent.com/487005/53233778-178aca00-3686-11e9-81ff-34db3ea5ead5.png">
<img width="486" alt="screenshot 2019-02-22 09 41 30" src="https://user-images.githubusercontent.com/487005/53233779-178aca00-3686-11e9-9c7b-8b751cb1020a.png">


That seems to have done the job! Possibly not identical to Chrome but big improvement on what Firefox is currently.

iOS looks fine too :+1:

**Comment by archmoj** [comment]
@ShaneHudson Thanks for the feedback. Would you mind testing [this revised example](https://codepen.io/MojtabaSamimi/pen/WmeRwd) as well?
