### ISSUE TITLE
the toolbar's background is always visible, not just on hover

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.js#3388]
It looks like the toolbar's background is always visible, not just when you hover. In the image below, see how the toolbar's background is visible.
![image](https://user-images.githubusercontent.com/1280389/50647233-0ce56b80-0f46-11e9-999c-64a3af20c335.png)

I'm on Firefox 64.0 and plotly.js 1.43.1

**Comment by etpinard** [comment]
In a codepen: https://codepen.io/etpinard/pen/gZepKm?editors=1010

**Comment by etpinard** [comment]
The culprit is https://github.com/plotly/plotly.js/pull/3280
