### ISSUE TITLE
Undefined zoom event data

### ISSUE THREAD

**Issue by Jodana** [plotly/plotly.js#339]
When you zoom, sometimes the data returned by 'plotly_relayout' callback is undefined for either x-axis start or x-axis end.

It happens every time you release the mouse button (to proceed zoom action) outside of the plot div.

How to reproduce:
1) https://plot.ly/javascript/zoom-events/
2) Zoom anywhere in the middle of the plot
3) Zoom, starting from anywhere, but head left till you are out of the plot (release the mouse button on the plot left side)

Result: zoom did proceed, but you are not informed about the new range (atm I'm trying to bypass this issue by retrieving this information directly from the plot instead of the event data). I would have expected either for the data to be returned, or zoom canceled.

EDIT: retrieving chartDiv.layout.xaxis.range did the trick !

**Comment by etpinard** [comment]
Thanks for the report.

I'd argue that this is the correct behaviour.

The `plotly_relayout` event intends to inform the listeners about the update object passed to `Plotly.relayout`. In the case where the mouse cursor goes off-plot-area to the left, `'xaxis.range[0]'` does not need to be updated and is `undefined` in the update object.

Your report seem to asking for a more general `on-change` event. Or, more generally, an easier way to grab to current state of a plotly graph.

I'll reference: 

- https://github.com/plotly/plotly.js/issues/168
- https://github.com/plotly/plotly.js/issues/145

for completeness.
