### ISSUE TITLE
Error bars not inheriting color

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#3392]
Here I'm only setting the marker color per trace, but the error bars are getting their color seemingly from colorway:

![image](https://user-images.githubusercontent.com/203523/50655208-6c02aa80-0f5d-11e9-8887-df3103d3f6ef.png)

**Comment by nicolaskruchten** [comment]
Huh, that's unexpected. So I guess my question is: is this reasonable? error bars iterate through colorway on their own, independently of the markers they're attached to??

(BTW in future, a CodePen is easier for me to look at than just code, as otherwise I have to go find an environment to run it in!)

**Comment by alexcjohnson** [comment]
Sounds UNreasonable to me. Unless error bar color is going to be some other color, like black error bars on bar charts, it should be inherited from an explicit color in the trace. Might be some annoying logic considering all the different possible attributes to inherit from - marker color, line color (especially if there IS no marker), marker line color - but I believe it should be clear what the desired outcome is in any given case. Surprised we didn’t already do it this way, but better late than never!

**Comment by nicolaskruchten** [comment]
OK so we should upgrade this issue to fix this in both 2d and 3d. I think in bars it's tricky because if they were the same color as the bars the lower one would be invisible...
