### ISSUE TITLE
WebJar Support

### ISSUE THREAD

**Issue by JordanBallew** [plotly/plotly.js#341]
Are there any plans to push the new versions of plotly in to webjars?

http://www.webjars.org/

**Comment by etpinard** [comment]
If you get more than 50 :+1:s (using reactions, not comments), sure.

**Comment by mdtusz** [comment]
It appears that someone already has created a plotly.js webjar on that website for v1.6.3 (unless I misunderstand what that site is!)

**Comment by JordanBallew** [comment]
Yes, it turns out that anyone can import anything deployed to bower or nmp, so I did. It does, however, take several hours for the index in maven central to get updated for it to be used. It would be nice if doing this was part of your release process, but it isn't super critical. Do you have a way to sign up for notifications for new releases?

**Comment by mdtusz** [comment]
We don't have any notification on releases, but github has [atom feeds](https://github.com/plotly/plotly.js/releases.atom) for releases that *somebody* could use to have an automatic script run. Could be a nice PR into the Webjars system actually to auto-update them.

**Comment by jamesward** [comment]
I've filed an issue to discuss auto-updating NPM & Bower WebJars: https://github.com/webjars/webjars/issues/1358

**Comment by JordanBallew** [comment]
Awesome. Thanks @jamesward .
