### ISSUE TITLE
Performance issues with multiple charts on one page

### ISSUE THREAD

**Issue by pschiphouwer** [plotly/plotly.js#3416]
Hello,

I am developing an electron application with Vue.js and Plotly as chart library. The application receives data from sensors with 25hz (25 times a second). The data from the sensors needs to bee shown in the charts.

I want to have 4 charts on one page with 8 traces in each chart. The data is shown with 4hz because of the range of the x-axis. More data is not useful. But when I have more than 1 chart on the page, the application gets slow because of the CPU usage and nothing works smooth. Even hovering over a link does not work smooth. 

Server side rendering is not available because the application is not always connected to the internet. The data from the sensors comes from the local network.

I tried multiple solutions but nothings works fine. I tried using the react function, the update function and the extendTraces function. 

The extendTraces function looks likes to be the best bet.
I have added a smooth scrolling function to scroll the chart with 60fps.
When I receive data, the data is drawn outside the view of the chart so with the scrolling it becomes visible. There is about 1 second with data outside of the view. The scrolling function also removes the data from the traces when the data is out of the range of the chart. So a trace does not have more than 300 data points. 

Do you have a suggestion to improve the performance of the application?

**Comment by etpinard** [comment]
This ticket will probably not directly result in a PR, so it would be best to ask questions of the likes on https://community.plot.ly/c/plotly-js

Sorry for not replying sooner.

**Comment by arsh09** [comment]
@pschiphouwer 

Hi, I am stuck at a similar problem and my use-case is very similar to yours. I have 3 PlotlyJS charts on a single single on VueJS, the sensors are sending data at 50 - 100 Hz. and the react functions performance is so bad when using 2 or 3 graphs on a single page. 

It works REALLY well for one graph though. 

Can you please share what worked for you in the end? 

Thank you
