### ISSUE TITLE
Saving 3D figures to PNG results in a different rotation

### ISSUE THREAD

**Issue by antoinerg** [plotly/plotly.js#3425]
Looking at this mock: https://rreusser.github.io/plotly-mock-viewer/#gl3d_snowden_altered
![gl3d_snowden_altered](https://user-images.githubusercontent.com/301546/50986533-11290000-14d5-11e9-9aca-887460502c7d.png)

Saving to PNG gives:
![newplot 5](https://user-images.githubusercontent.com/301546/50986480-f0f94100-14d4-11e9-96c1-55c470cdb99c.png)

As one can see, the orientation was changed.

**Comment by antoinerg** [comment]
Note that I can't reproduce the issue with other mocks. It may be that the issue is limited to 
 [gl3d_snowden_altered.json](https://github.com/plotly/plotly.js/blob/master/test/image/mocks/gl3d_snowden_altered.json).

**Comment by archmoj** [comment]
It could be related to particular camera position.

**Comment by etpinard** [comment]
It's a regression for 1.43.x:

latest: https://codepen.io/etpinard/pen/GPYrLp
1.42.5: https://codepen.io/etpinard/pen/zymNeJ

most likely from https://github.com/plotly/plotly.js/pull/3256

**Comment by etpinard** [comment]
@archmoj wanna take a shot at fixing this at some point this week?
