### ISSUE TITLE
layout.metatext

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#3427]
For Chart Studio we would need:

* A new data-array key in layout called `metatext`, intended to contain strings
* The ability to use `%{metatext[<x>]}` in string keys like `layout.title`, `layout.*axis.title`, `layout.annotations[*].text` (and possibly one or two other places TBD)

**Comment by etpinard** [comment]
Just to confirm, we want something like:

```js
Plotly.newPlot(gd, [{
  y: [1,2,1]
}], {
   metatext: ['a', 'b'],
   title: 'my title %{metatext[0]} - %{metatext[1]}'
})
```

yielding:

![image](https://user-images.githubusercontent.com/6675409/51040979-d7b0cd00-1586-11e9-900a-384ddd31cb36.png)

?

**Comment by nicolaskruchten** [comment]
yes indeed!
