### ISSUE TITLE
Plots.supplyDeffaults subplot type cache doesn't allow dynamic trace module imports

### ISSUE THREAD

**Issue by dan8f** [plotly/plotly.js#3428]
Hi team,

collectableSubplotTypes gets cached and this leads to inaccurate  subplot lists if new traces are registered dynamically:

https://github.com/plotly/plotly.js/blob/51b5c25bcc81109575d77f0eddc8510147ca5172/src/plots/plots.js#L582-L614

For example if we load Plotly, plot a graph and later dynamically register mapbox and plot a mapbox it will error since coorect subplotTypes are not passed to handleSubplotDefaults.

Could we simply not cache subplotTypes or reset when we register new traces?

Regards

![image](https://user-images.githubusercontent.com/46603853/51058304-42422700-15e0-11e9-8c4b-68ad36ef64c2.png)

**Comment by etpinard** [comment]
Thanks for the report!

> if new traces are registered dynamically

Could you share a code snippet to help us understand what you're trying to achieve? Thank you very much.

**Comment by dan8f** [comment]
Hi @etpinard 

Imagine we have component Timeseries.js as:

`import Plotly from 'plotly.js/lib/core';
export default function() {
	Plotly.plot(...);
}`

And component Mapbox.js as:

`import Plotly from 'plotly.js/lib/core';
import Mapbox from 'plotly.js/lib/scattermapbox';
Plotly.register(Mapbox);
export default function() {
	Plotly.plot(...);
}`

And then in our main index.js we dynamically import Timeseries and plot a graph and later on import Mapbox and plot a map. 

`import("Timeseries").default();
and later...>>
import("Mapbox").default();`


This will produce an error in handleSubplotDefaults. The subplot types for Mapbox component should include 'Mapbox' but since we have cached subplot types when first rendering the timeseries, then chart we will miss them.

Let me know if this doesn't help to visualize it.

Regards

**Comment by etpinard** [comment]
That makes perfect sense. Thanks. We'll fix that!
