### ISSUE TITLE
react() + layout.grid

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#3430]
This pen shows some difficulties with `react()`ing across different grid layouts: https://codepen.io/nicolaskruchten/pen/GPwzrM?editors=0010

Seems like a standard figure-mutation issue: `domain` gets written back to the figure so future updates don't work as one might expect.

**Comment by etpinard** [comment]
Ha, looks like this is actually a `scaleanchor` problem

https://codepen.io/etpinard/pen/VqgMQa?editors=0010 appears to work fine where I commented out the `scaleanchor` settings.

**Comment by nicolaskruchten** [comment]
Huh, interesting! I'll be honest, what I really want here is matching axes, not scaleanchor per se... I'm just using scaleanchor in the meantime. All this to say: let's make sure we test this case and/or just fix this while implementing #1549 :D
