### ISSUE TITLE
"legend.valign" doesn't work for pie charts

### ISSUE THREAD

**Issue by michaelbabyn** [plotly/plotly.js#3432]
If I set `valign='top'` in a pie chart, multi-line legend items will still be centered around the legend marker. 

[codepen for pie chart with issue](https://codepen.io/michaelbabyn/pen/jXQJME)
[codepen for scatter chart demonstrating the desired behavior](https://codepen.io/michaelbabyn/pen/VqVRKx)

**Comment by etpinard** [comment]
Thanks for the report!
