### ISSUE TITLE
Implement `hovertemplate` for all traces that support hover

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#3437]
Building on top of https://github.com/plotly/plotly.js/pull/3126, https://github.com/plotly/plotly.js/pull/3284, https://github.com/plotly/plotly.js/pull/3398 and https://github.com/plotly/plotly.js/pull/3436 `hovertemplate` is now supported for trace types: `scatter`, `bar`, `pie`, `histogram`, `scattergl`, `sankey`, `scatterpolar`, `barpolar`, `scatterternary`, `scatterpolargl`, `choropleth`, `scattergeo` and `scattermapbox`.

The "missing" trace types are:

- [x] `contour`, `heatmap`, `histogram2d`, `histogram2dcontour`
- [x] `box` and `violin` (for points done in https://github.com/plotly/plotly.js/pull/3685 | otherwise not implemented)
- [x] all the gl3d trace types: `scatter3d`, `surface`, `mesh3d`, `stremtubes`, `cone`, `isosurface`
- [x] `scattercarpet`
- [ ] `ohlc` and `candlestick`
- [x] `splom`
- [x] `parcats`
- [ ] `pointcloud`, `heatmapgl` and `contourgl` (are we deprecating those trace types in v2?)

cc @nicolaskruchten

**Comment by nicolaskruchten** [comment]
Yup! I would say that scatter3d is the most important remaining one, followed by parcats and splom, then contour/heatmap/surface then the the histogram2d ones

**Comment by mpf82** [comment]
Personally, I would find it helpful and intuitive if for ``box`` the ``hovertemplate`` would be applied to single points *only*, not affecting the other hover texts (such as median, min, lower fence, ...).

There could be a separate property to handle these.

I would also find it helpful if you could update the [documentation](https://plot.ly/javascript/reference/#scatter-hovertemplate), mentioning what types are supporting ``hovertemplate``, as I spent quite some time wondering why my box traces were not affectd by this setting.

**Comment by etpinard** [comment]
> scatter3d is the most important remaining one, followed by parcats and splom

Cool, we'll try to fit these in `v1.45.0`. Thanks for the info!

**Comment by nicolaskruchten** [comment]
If I can revise my original priority list, I might put @mpf82's suggestion above `parcats` ... It's pretty useful to be able to mouse over an outlier to know which one it is!

**Comment by etpinard** [comment]
> I might put @mpf82's suggestion above `parcats`

> I would find it helpful and intuitive if for `box` the `hovertemplate` would be applied to single points _only_, not affecting the other hover texts (such as median, min, lower fence, ...).

Hmm. We haven't figured out the api for that one yet. See https://github.com/plotly/plotly.js/pull/3126#issuecomment-434458408

We can't just make `hovertemplate` just work on box points, because at some point we'll want to implement hovertemplates on all box hover labels.

**Comment by nicolaskruchten** [comment]
> We can't just make `hovertemplate` just work on box points, because at some point we'll want to implement hovertemplates on all box hover labels.

I actually would find this to be most natural, and then we'd add `boxhovertemplate` or similar for the non-single-point ones.

**Comment by etpinard** [comment]
> we'd add `boxhovertemplate`

I really dislike three-word attribute names, but I guess that would be one way to solve the problem.

In a similar way, we'll need to declare multiple `*hovertemplate` attributes for `parcats`: one when hovering over links, and one when hovering over nodes.

Sankey does a good job at this: it declares two `hovetemplate` attributes: one in `link.hovertemplate` and one in `node.hovertemplate`. Unfortunately, for `parcats` and `box`/`violin` we don't have "nice" attribute containers like these to work with.

Hmm well, I guess for `parcats` we could use the `line` container and then maybe coerce a `hovertemplate` inside each `dimensions` item? Or maybe have the root `hovertemplate` apply to all the dimensions/nodes and be ignored when hovering on links?

**Comment by etpinard** [comment]
After https://github.com/plotly/plotly.js/pull/3530, only `box`, `violin`, `ohlc`, `candlestick` and the old gl2d traces will be missing `hovertemplate` support.

**Comment by etpinard** [comment]
hovertemplate support for `box` and `violin` **points** is implemented in https://github.com/plotly/plotly.js/pull/3685

**Comment by jackparmer** [comment]
This issue has been tagged with `NEEDS SPON$OR`

A [community PR](https://github.com/plotly/plotly.js/pulls?q=is%3Apr+is%3Aopen+label%3A%22type%3A+community%22) for this feature would certainly be welcome, but our experience is deeper features like this are difficult to complete without the Plotly maintainers leading the effort.

**Sponsorship range: $5k-$10k**

What Sponsorship includes:
- Completion of this feature to the Sponsor's satisfaction, in a manner coherent with the rest of the Plotly.js library and API
- Tests for this feature
- Long-term support (continued support of this feature in the latest version of Plotly.js)
- Documentation at [plotly.com/javascript](https://plotly.com/javascript/)
- Possibility of integrating this feature with Plotly Graphing Libraries (Python, R, F#, Julia, MATLAB, etc)
- Possibility of integrating this feature with Dash
- Feature announcement on [community.plotly.com](https://community.plotly.com/tag/announcements) with shout out to Sponsor (or can remain anonymous)
- Gratification of advancing the world's most downloaded, interactive scientific graphing libraries (>50M downloads across supported languages)

Please include the link to this issue when [contacting us](https://plotly.com/get-pricing/) to discuss.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Comment by emilykl** [comment]
Reopening because still relevant
