### ISSUE TITLE
Box plot: hover position of points is off

### ISSUE THREAD

**Issue by aaronpries** [plotly/plotly.js#3440]
In a box plot with boxpoints='all', the hover position of the boxes shows the correct position of the data points. The boxpoints are shifted to the left and the hoverinfo shows their x-position in the figure, which is not the same as the x-position of the data points, see the attached figure (created with plotly.py: [FigureWidget.txt](https://github.com/plotly/plotly.js/files/2768130/FigureWidget.txt)).
![boxplot_hover](https://user-images.githubusercontent.com/9529130/51311227-b8afb080-1a48-11e9-824a-dca040ad0412.png)

Is this desired? I would have expected to see the x-value of the data points, not the position in the figure. If a jitter is added, this may be even more confusing.

**Comment by alexcjohnson** [comment]
Thanks @aaronpries, that’s most definitely not correct, it should show the data value as you say.

**Comment by etpinard** [comment]
Thanks for the report @aaronpries !

**Comment by etpinard** [comment]
In a codepen: https://codepen.io/etpinard/pen/NeVaYR?editors=1010
