### ISSUE TITLE
Multi-line "extra" hover label alignment is off

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#3442]
Pulled out of @Braintelligence's https://github.com/plotly/plotly.js/issues/3175#issuecomment-448565062

![grafik](https://user-images.githubusercontent.com/6761196/50218117-14741480-038b-11e9-98e1-d13c342eb574.png)

or simply in https://codepen.io/etpinard/pen/QzRzBe

**Comment by etpinard** [comment]
Would something like:

![peek 2019-01-18 10-57](https://user-images.githubusercontent.com/6675409/51397773-ef043300-1b0f-11e9-9034-264e3065c1ed.gif)

look good enough?

**Comment by Braintelligence** [comment]
Maybe valign the value? :p

**Comment by etpinard** [comment]
Example of a more extreme case:

```js
Plotly.newPlot('graph', [{
  y: [1, 2, 1],
  name: 'Multi<br>line<br>trace<br>name',
  hoverlabel: {namelength: -1},
  hoverinfo: 'x+y+name'
}, {
  y: [1, 2, 1],
  name: 'Multi<br>line<br>trace<br>name',
  hoverinfo: 'x+y+name',
  hoverlabel: {namelength: -1}
}], {
  showlegend: true
})
```

![peek 2019-01-18 11-01](https://user-images.githubusercontent.com/6675409/51397970-6afe7b00-1b10-11e9-9477-5c5baf9e8756.gif)

**Comment by etpinard** [comment]
> Maybe valign the value? :p

That could work. @plotly/plotly_js any thoughts on this?

**Comment by Braintelligence** [comment]
Otherwise it looks OK! :) Thanks a bunch

**Comment by alexcjohnson** [comment]
Currently multiline primary text with a single-line name leaves the name top-aligned with the text box, which makes me think the default with more lines in the name than in the primary text should be the same, top-aligned. But an attribute to switch that to middle-aligned or bottom-aligned would be great to add at some point.

**Comment by etpinard** [comment]
> makes me think the default with more lines in the name than in the primary text should be the same

Pushed to https://github.com/plotly/plotly.js/pull/3443

> But an attribute to switch that to middle-aligned or bottom-aligned would be great to add at some point.

Now in https://github.com/plotly/plotly.js/issues/3010
