### ISSUE TITLE
Deprecated `text` / use `hovertext` for traces that don't support on-graph text

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#3450]
Attribute `hovertext` got added (first in https://github.com/plotly/plotly.js/pull/1523) for traces that support on-graph `text`. There are all the `scatter*` traces, `pie` and `bar`. Traces that support hover but do not support on-graph text currently use `text` to set the "hover" text. As @nicolaskruchten points out, this is a little confusing. 

So, should we deprecate `text` (while renaming `hovetext`) in traces that do not support on-graph text?

**Comment by nicolaskruchten** [comment]
We could start by just adding `hovertext` in the relevant places... that increases consistency and breaks nothing :)
