### ISSUE TITLE
Scatter plot hover text is of wrong point

### ISSUE THREAD

**Issue by orenbenkiki** [plotly/plotly.js#3451]
Example(s): https://plot.ly/python/webgl-vs-svg/

Try hovering on a point in the graph, you will see a hover text of a different point.

The core issue seems to be that plotly picks the point to show the text for based on only the X coordinate. This is nice for line graphs etc. but is very much the wrong thing in the case of scatter plots.

I thought I could work around the issue by box-zooming so that only very few points are visible. No such luck; plotly still considers all the points as candidates for the hover text, even points that are currently not visible within the zoom area. This is technically an unrelated bug, but the combination basically eliminates the usefulness of hover text for non-trivial scatter plots.

As the above link shows, this will happen in any dense scatter plot, including the examples in the documentation.

**Comment by orenbenkiki** [comment]
Turns out this is just a matter of a bad default. Add `hovermode='closest'` to the `layout` dictionary and it will behave as expected.

That raises the issue of how difficult it is to find anything in the documentation. I discovered `plot-schema.json` in the sources - you can see it here: https://github.com/plotly/plotly.js/blob/master/dist/plot-schema.json and you can easily search it with any text editor/viewer.

**Comment by torenunez** [comment]
That worked for me. Thanks @orenbenkiki!
