### ISSUE TITLE
Is complex multi-layered stacked/overlay/tracing bar-graph possible?

### ISSUE THREAD

**Issue by drduker** [plotly/plotly.js#3457]
My code:
https://codepen.io/drduker/pen/rPNRJw

This is less a bug and rather checking out plotly to see if what I'm trying to do is even possible.

Three things:
1. Highlighting sections of each bar trace (is this an overlay?).
I want to overlay all "verses" or numbers with custom mappings across the trace chapters.  So lets say I want to highlight Genesis 4-10 with another "trace" on top of what you already see.  Before I do these traces on the bar graphs that are here, I will have to make all the currently colorful chapters be the same color and maybe have a thin boarder line between the chapter traces.
I couldn't figure out a way to visualize this data other than using 150 traces which represent chapters in the Bible.  I will eventually hide these traces in the legend (which there was a way that I could export and import json for mass editing with a text editor like atom/sublime/etc..)
So essentially I think i'm asking to map/trace things to traces.  Is this possible?  Could you point me to an example?  If this isn't possible, I would write out a detailed feature request.

2. There are 1533 verses mapped out in the book of Genesis.  For each highlighting of a section that could go across multiple chapters, I would like to have hover text over the specific section and an option to click on a url within the text.  Is this possible?  Could you point me to an example?

3. Is is possible to have a mouse-auto-zoomin-without-click where the mouse hovers?

**Comment by alexcjohnson** [comment]
@drduker apologies for the slow reply. Questions like "can plotly do this" are a better fit for community.plot.ly, we like to reserve github for bug reports and feature requests, once it's known that the desired functionality is indeed not supported.

There are a number of issues where we're discussing extensions to bar stacking/grouping: #78, #1835, #3402... but it's better to use community.plot.ly to help figure out what's already possible, either directly or via workarounds.

**Comment by etpinard** [comment]
Closing. @drduker feel free to open a ticket on https://community.plot.ly/c/plotly-js if you need more info on this subject.
