### ISSUE TITLE
Zoom glitch when restyling

### ISSUE THREAD

**Issue by Jodana** [plotly/plotly.js#346]
Whenever you use restyle() to update a trace (affecting x or y points) in a zoomed state, plotly keeps track of the zoomed view. Then, whenever you double-click in order to unzoom, it will either unzoom or return to that zoomed state.

If a second restyle() happens in the same conditions, you can never unzoom completly (it switch between the first recorded zoomed state, and the last one).

Here is how to reproduce:
1) Zoom wherever you want
2) Click on the "Restyle" button in order to update the trace
3) Unzoom
4) Double-click to switch between global view and zoomed view

Codepen: http://codepen.io/etpinard/pen/eZvKag

**Comment by etpinard** [comment]
> (sorry didn't find a way to enable a more convenient sharing)

Next time you should save you codepen and paste its URL in your bug report.

**Comment by etpinard** [comment]
Bug confirmed. Thank you very much.
