### ISSUE TITLE
Splom zoom bug in doc example

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#3466]
Box-zooming on a splom doesn't give the expected output... I was zooming in on the blue but once it zoomed that subplot was empty.

https://codepen.io/plotly/pen/GdaBBo

![splom](https://user-images.githubusercontent.com/203523/51622419-91535a80-1f04-11e9-9d2d-48bd7b63b91e.gif)

**Comment by etpinard** [comment]
That's crazy. Thanks for the report.

Can you confirm that zooming works ok on: https://rreusser.github.io/plotly-mock-viewer/#splom_iris

**Comment by nicolaskruchten** [comment]
Yep that one works. Note that the pen starts out in drag select mode by default so maybe that’s part of the difference?

**Comment by nicolaskruchten** [comment]
The pen behaves the same way on osx/chrome as it does on iOS/safari. Does the bug in the pen not replicate for you?

**Comment by nicolaskruchten** [comment]
It looks like the range for sepal width is getting assigned to petal width also, look at the bottom ticks

**Comment by etpinard** [comment]
Found it. All the axis attribute containers are linked to the same object (`axis` in the codepen). Making them different objects as in https://codepen.io/etpinard/pen/BMNmBV?editors=1010 seems to make things work.

**Comment by nicolaskruchten** [comment]
Closing in favour of https://github.com/plotly/documentation/issues/1246 which is where that Pen is from
