### ISSUE TITLE
Categorical choropleths with legends

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#3468]
Right now it doesn't seem like we can make a categorical choropleth by adding multiple traces with the same color and having legend items appear for them: https://codepen.io/nicolaskruchten/pen/MLwyOZ?editors=0010

Ideally I'd want to be able to:

1. set the color directly, like with `marker.color`, instead of doing a dance with `z` and `colorscale`
2. have legend entries appear

So that I could easily switch between `choropleth` and `scattergeo` like with this one: https://codepen.io/nicolaskruchten/pen/QYbNax?editors=0010

**Comment by etpinard** [comment]
That's correct. `choropleth` don't support legend items.

**Comment by etpinard** [comment]
You _can_ shrink down the colorbar (one for each trace) to do something like:

![image](https://user-images.githubusercontent.com/6675409/51645131-d85f4100-1f40-11e9-8efa-8f396fd64fce.png)

from https://nbviewer.jupyter.org/github/etpinard/plotly-misc-nbs/blob/master/geo-maps/discrete-choropleths.ipynb#Suggestion-2:-split-data-into-several-choropleth-traces

**Comment by etpinard** [comment]
> 1. set the color directly, like with `marker.color`, instead of doing a dance with `z` and `colorscale`

So, you want `z` (that should have been called `value`, by the way) and `marker.color` to do the exact same thing? I can't say I'm a fan. It would be weird (to me) to have a "primary" data array (i.e. you need it to see stuff) stuck insider `marker`. 

> So that I could easily switch between `choropleth` and `scattergeo` like with this one:

By a similar argument, should we rename the `pie` data arrays `x` and `y` so that we can easily switch from `bar` <--> `pie`? I doubt it.

Now, I'm not saying we shouldn't try to make trace-to-trace correspondences easier. This has been discussed during previous work on `relayout`. The last item of https://github.com/plotly/plotly.js/issues/2025 is:

> add a way to declare correspondence between attributes of different name across trace types (e.g. to generalize type edits involving pie traces, scattergeo lon/lat should correspond to x/y, ...)

Maybe we can find a way to declare those correspondence in the plot-schema. Thoughts?

**Comment by etpinard** [comment]
> Maybe we can find a way to declare those correspondence in the plot-schema.

So this :arrow_double_up: isn't good enough?

**Comment by nicolaskruchten** [comment]
My main goal is to be able to specify the color of the country directly like we can specify the color of a marker in scatterX. Z doesn’t permit this atm, so no, declaring a correspondence doesn’t help :) 

Conversely, allowing CSS color names in an array called Z seems awkward.

**Comment by nicolaskruchten** [comment]
We could, yes. And we could allow traces to be added to the legend. That would indeed allow me to make the figures I want.

**Comment by etpinard** [comment]
Thinking about this again maybe `marker.color` for color names + legend items would be best. 

That way, user that inputs `z` gets a colorscale and a colorbar, user that inputs `marker.color` gets a legend item. There wouldn't be any `marker.colorscale` and `marker.color` items couldn't be numeric (now a true "data" array, that makes me :smile: ). It will be `arrayOk` though.

**Comment by nicolaskruchten** [comment]
Heh ok that might work also. OTOH I could also see an argument that a true choropleth by definition expresses continuous values and that we should have a new trace type called indicatormap or something that accepts only categorical colors.

Also: choropleth has a “showlegend” attribute atm that doesn’t do anything, which initially led me down this path ;)

**Comment by etpinard** [comment]
Right, all traces have a `showlegend` attribute even though some (or most?) of them don't support them

Related:

- https://github.com/plotly/plotly.js/issues/2642
- https://github.com/plotly/plotly.js/issues/3058

**Comment by nicolaskruchten** [comment]
For reference, BTW, this is the kind of figure I'm aiming at:

![image](https://user-images.githubusercontent.com/203523/51650908-056b1e00-1f58-11e9-962d-2bf0c75e3888.png)

![image](https://user-images.githubusercontent.com/203523/51650931-1d42a200-1f58-11e9-9ede-ed63f95aeaa1.png)

![image](https://user-images.githubusercontent.com/203523/51650964-321f3580-1f58-11e9-999b-e8bb77581af1.png)

**Comment by nicolaskruchten** [comment]
Just to drill in a bit on the `z` vs `marker.color` thing... @etpinard you said 

> It would be weird (to me) to have a "primary" data array (i.e. you need it to see stuff) stuck insider marker.

OK, but how is this different from something like `scattergeo`? If you omit `marker.color` then all the markers are the same default color. We could do the same thing for `choropleth` such that if you only pass in `location` then all the countries (or whatever) are the same color. That's not a useless thing: as an indicator map, it's like "here are all the places where X".

I think it would be quite weird to have `choropleth` be the one trace where `marker.color` accepts only colors and not continuous values.

**Comment by etpinard** [comment]
> but how is this different from something like `scattergeo`?

I'd say the "primary" data arrays for `scattergeo` are `lon` and `lat`. `locations` (which is what I suspect you're using) is just a shortcut for `lon` and `lat`.

> I think it would be quite weird to have `choropleth` be the one trace where `marker.color` accepts only colors and not continuous values.

True, but it would also be _weird_ to have `z` and `marker.color` do the EXACT same thing.

**Comment by nicolaskruchten** [comment]
Like I said, `z` would be a backwards-compatible way to set `marker.color`'s default value, and would be ignored if `marker.color` was set. So yeah, a bit odd, but there for legacy reasons.

**Comment by nicolaskruchten** [comment]
> I'd say the "primary" data arrays for scattergeo are lon and lat. locations (which is what I suspect you're using) is just a shortcut for lon and lat.

OK, so then the primary data array for `choropleth` is `locations`. I'm not sure why `z` has to be primary.

**Comment by etpinard** [comment]
Voting for keeping `z`!

**Comment by nicolaskruchten** [comment]
I'm not advocating for getting rid of `z`... I would just like to also have `marker.color` that behaves the same way as the other traces for both absent, continuous and CSS-valued data :)

**Comment by etpinard** [comment]
OK, then should `heatmap` also have a `marker.color`?

**Comment by etpinard** [comment]
All in all, this whole debate comes down to:

Is choropleth more like a heatmap or more like a scattergeo trace? I think it's more like a heatmap, @nicolaskruchten probably thinks it's more like scattergeo. Not sure who will win out :racehorse:

**Comment by nicolaskruchten** [comment]
> OK, then should heatmap also have a marker.color?

I would not oppose this. I think `z` is a sub-optimal choice of name for something which controls only color and not something in a spatial dimension like the `z` we have in 3d which does.

> All in all, this whole debate comes down to: Is choropleth more like a heatmap or more like a scattergeo trace?

Not really: I think attributes which control color should be called `color` no matter where they are :)

**Comment by etpinard** [comment]
> I think attributes which control color should be called `color`

I'd argue that `z` for choropleth is more than just _color_, it's a primary data array. A choropleth trace w/o a `z` doesn't show anything. A scattergeo trace w/o `marker.color` still shows points.

**Comment by nicolaskruchten** [comment]
As I said above re choropleth traces without `z`:

> OK, but how is this different from something like scattergeo? If you omit marker.color then all the markers are the same default color. We could do the same thing for choropleth such that if you only pass in location then all the countries (or whatever) are the same color. That's not a useless thing: as an indicator map, it's like "here are all the places where X".

**Comment by TJ-Tubi** [comment]
It looks like px.choropleth z field still does not support categorical legend items? I'm not sure where this discussion ended, but at present setting z to a categorical series simply produces a blank map. Thanks!

**Comment by nicolaskruchten** [comment]
That’s right, z still supports only continuous color but you can now add multiple single-color choropleth traces with legend items to get the same effect. See https://plot.ly/python/choropleth-maps/ for an example with Plotly Express in Python.

**Comment by TJ-Tubi** [comment]
Hi! Thanks for getting back to me. Which section should I be looking at? The figure under "Discrete Colors" is essentially what I am aiming to create. However, the example code provided no longer runs.

**Comment by nicolaskruchten** [comment]
It definitely runs but it requires version 4.5.0 of Plotly.py which came out a couple of weeks ago.

**Comment by secsilm** [comment]
> That’s right, z still supports only continuous color but you can now add multiple single-color choropleth traces with legend items to get the same effect. See https://plot.ly/python/choropleth-maps/ for an example with Plotly Express in Python.

Hi, I want to know how to reorder the legeng items. Because sometimes these legends may have order meaning, for example bins, 1-10, 1-20, 21-30...

**Comment by nicolaskruchten** [comment]
Legend order depends on trace order in the `data` array.

**Comment by ahertel** [comment]
@nicolaskruchten I saw that this topic was closed and included in #4386 but I still don't understand from the instructions how to achieve a categorical choropleth. My data is a Pandas DataFrame with two columns: the country name and the cluster it belongs in. I want to color the world map based on the cluster of each country. I had tried coloring a map by cluster in the past and [this](https://alanbalugu.github.io/DataScience/Project_3/usamap_merged_clustering/) as close as I was able to get using plotly.graph_objects.
This is example in the Plotly documentation is the [closest](https://plotly.com/python/mapbox-county-choropleth/#discrete-colors) to what I'm trying to achieve but my data is not in geojson format. Would appreciate any advice. Thank you!

**Comment by nicolaskruchten** [comment]
@ahertel if you're looking for information on how to do this in Python I would recommend opening an issue in the Plotly.py repo, but for completeness, here's a PX example without GeoJSON for categorically-coloring statewise choropleths... it's basically the same as the one here https://plotly.com/python/choropleth-maps/#using-builtin-country-and-state-geometries but with categorical instead of continuous color:

```python
import plotly.express as px

fig = px.choropleth(locations=["CA", "TX", "NY", "AK"], 
                    color=["yes", "no", "yes", "no"],
                    scope="usa", locationmode="USA-states")
fig.show()
```

**Comment by ahertel** [comment]
@nicolaskruchten Ah right, I forgot this was the JS page. Thank you so much for responding so quickly and taking the time to write the example code! It worked and it's so much simpler than all the stuff I was playing around with. Here's the [result](https://ahertel.github.io/playground/choropleth/).
