### ISSUE TITLE
Table: Applying colors to diagonal cells

### ISSUE THREAD

**Issue by AbdealiJK** [plotly/plotly.js#3472]
We were using the Table trace type and we wanted to try giving the diagonal cells a color so it was easy to distinguish them and see data on either sides. (I think that is a common usecase to show matrices and so on)

I looked at the documentation and saw that the `fill` attribute in `cells` but it only supports an array i.e. a specific color can be applied to a column.
Was wondering how I could achieve this using plotly tables ? Cell level color fills

**Comment by etpinard** [comment]
Thanks for writing in! 

This should be possible using `cells.fill.color`.

See https://codepen.io/etpinard/pen/bzVENX?editors=1010, is that what you're looking for?

**Comment by AbdealiJK** [comment]
@etpinard Thanks a lot. That is what I need.

I did not realize I could provide a 2D array in that and did not try :/
Should I close the issue or keep it for documentation improvement maybe ?

Currently it says:
> Sets the cell fill color. It accepts either a specific color or an array of colors.

**Comment by etpinard** [comment]
> Should I close the issue or keep it for documentation improvement maybe ?

That will be done in https://github.com/plotly/plotly.js/pull/3481

Thanks again for the report!
