### ISSUE TITLE
scrolling legend height not recalculated on resize

### ISSUE THREAD

**Issue by timelyportfolio** [plotly/plotly.js#348]
Initially reported in https://github.com/ropensci/plotly/issues/525, I was able to isolate to a non-R JavaScript only example in [codepen](http://codepen.io/timelyportfolio/pen/dMvgqd).  I had hoped `v1.7.0` would solve this, but unfortunately I just updated, and the problem persists.

![plotly_legend_resize](https://cloud.githubusercontent.com/assets/837910/13959365/d614c40c-f021-11e5-99ee-7323b62aece7.gif)

I am happy to attempt to tackle this if desired.  I see on [line](https://github.com/plotly/plotly.js/blob/master/src/components/legend/draw.js#L223) where it checks for `firstRender` to draw the legend.  I'm wondering if we can handle by just removing this `firstRender` check.

**Comment by etpinard** [comment]
@timelyportfolio thanks for the report!

> I am happy to attempt to tackle this if desired.

That would be great. Go for it!

**Comment by timelyportfolio** [comment]
So, this became far thornier than I initially expected.  We have a scope problem with `scrollheight` defined in the `scrollHandler` eventListener callback defined on initial draw that does not update on `relayout`.  Also, the pattern `data([0]).enter().append(...)....` means legend items such as `clippath` will not be updated on `relayout`.  I have almost convinced myself that the legend should partially or completely redraw each `relayout` but then we might lose legend selections.  @etpinard, any thoughts before I assemble a pull, since this will be my first?

**Comment by etpinard** [comment]
Moving block [1](https://github.com/plotly/plotly.js/blob/master/src/components/legend/draw.js#L224-L230) and [2](https://github.com/plotly/plotly.js/blob/master/src/components/legend/draw.js#L255-L262) above the `gd.firstRender` clause should suffice for this PR.

It is important to attach event listeners to the legend only once per graph (hence that `gd.firstRender` block), but re-layout calls should reset the clip paths and bounding rectangle dimensions, 

@mdtusz Any other insights?

**Comment by mdtusz** [comment]
That should solve the sizing issue. 

So long as the existing eventListeners are removed, I see no problem with re-setting them. It may take a bit of fiddling to get the order of operations right and will require a check to see that you aren't adding a listener to a non-existent scroll, but it would ensure the correct value in the `scrollHandler`.

**Comment by etpinard** [comment]
For the record, `data([0]).enter().append(...)....` does **not** mean that the legend items aren't updated on `relayout`. It indicates that there will one **and only** one of these node on the graph at all times.

More thoroughly,

```js
// select all clippath nodes with id 'clipId' => 0 node on first pass, 1 node afterwards
var clipPath = fullLayout._topdefs.selectAll('#' + clipId);
      // bind an array of length 1 to selection 
        .data([0])
      // grabs the enter selection => has 1 node in first pass, 0 node afterwards
      .enter()
     // from enter selection => append <clipPath> with id 'clipId'
    .append('clipPath')
        .attr('id', clipId)
    //  and append a <rect> inside <clipPath>
        .append('rect');
```

**Comment by timelyportfolio** [comment]
Thanks for the clarification.  I understand what you are saying, and I'll attempt to demonstrate what is happening in this instance with a narrow CodePen.

**Comment by timelyportfolio** [comment]
@etpinard, I think this [CodePen](http://codepen.io/timelyportfolio/pen/bpWrQa) might explain my statement.  Notice how only the second `p` updates.  The same thing is happening with `clippath`.  If we look at the original [codepen demo of problem](http://codepen.io/timelyportfolio/pen/dMvgqd) after we push the resize button,

![image](https://cloud.githubusercontent.com/assets/837910/13992390/ece56f42-f0e9-11e5-9603-72d403ed9166.png)

**Comment by etpinard** [comment]
@timelyportfolio nice catch.

This [block](https://github.com/plotly/plotly.js/blob/master/src/components/legend/draw.js#L58-L62) should be

```js
var clipPath = fullLayout._topdefs.selectAll('#' + clipId)
        .data([0]);

clipPath.enter().append('clipPath')
        .attr('id', clipId)
        .append('rect')
```

my mistake.

**Comment by timelyportfolio** [comment]
So, I think the only thing left is we need to somehow pass the new `scrollheight` to `scrollHandler`.  Any suggestions here besides remove and add back?

**Comment by etpinard** [comment]
> Any suggestions here besides remove and add back the eventListeners

I don't. I'd would simply remove/add the handlers.
