### ISSUE TITLE
Vertical modebars break plots on IE11

### ISSUE THREAD

**Issue by wbrgss** [plotly/plotly.js#3489]
On IE11, setting the `layout` parameter `modebar: {'orientation': 'v'}` will break plots on IE11, with the following error:
```javascript
Unhandled promise rejection TypeError: Object doesn't support property or method 'prepend'
```

This is likely related to [this](https://github.com/plotly/plotly.js/pull/3068/files#diff-979486c8ea6cdf2d004e24d69d537f3cR85) line in #3068  using `element.prepend()`. The bug can likely be easily fixed by using [this](https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/prepend#Polyfill) polyfill suggested by MDN.

"Plunker" pen demonstrating the issue (graph does not display on IE11):
https://plnkr.co/edit/mnQV4RWKhAQOLUX225IL?p=preview

![image 5](https://user-images.githubusercontent.com/9068290/51853117-8712d100-22f5-11e9-886d-c14b298fb730.png)

I had to use Plunker as CodePen et al is not compatible with IE11.

**Comment by wbrgss** [comment]
Related issue: #3186

I can fix this one myself; however, it might have to wait till next week as I'm on my own tight release schedule.

**Comment by etpinard** [comment]
@antoinerg wanna have a :eye: at this bug?

**Comment by etpinard** [comment]
... or use `d3`:

https://stackoverflow.com/questions/26234636/d3-js-prepend-similar-to-jquery-prepend

which would be my solution of choice.
