### ISSUE TITLE
parcoords interactive filtering not working in this example?

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.js#3490]
Taken from https://nbviewer.jupyter.org/github/plotly/px/blob/master/gallery.ipynb

The bottom part of the chart doesn't update when filtering with the draggable axis handle:

![parcoords-filtering](https://user-images.githubusercontent.com/1280389/51855612-a7458e80-22fb-11e9-907d-28e8a8c1a14e.gif)

Mac
Firefox 64.0.2

**Comment by etpinard** [comment]
Duplicate of https://github.com/plotly/plotly.js/issues/3385
