### ISSUE TITLE
3D Scatter transparency not activated by marker.color or marker.line.color as well as line.color and errorbars alpha channel

### ISSUE THREAD

**Issue by jonmmease** [plotly/plotly.js#3492]
Originally reported in https://github.com/plotly/plotly.py/issues/1416.

The alpha channel of rgba colors seems to be respected by `scatter3d`, but only if the `opacity` property is set to something less than 1.

CodePen: https://codepen.io/jonmmease/pen/OdRbdL

```javascript
var trace1 = {
  x: [0, 1.1, 2.2], 
  y: [0, 1, 2], 
  z: [0, 1, 2], 
  mode: 'markers',
  marker: {
    size: 20,
    color: ['rgba(255, 0, 0, 0.9)',
            'rgba(255, 0, 0, 0.5)',
            'rgba(217, 0, 0, 0.1)'],
    line: {
    },
    opacity: 1.0
    // opacity: 0.99
  },
  type: 'scatter3d'
};

var data = [trace1];
var layout = {
      margin: {
        l: 0,
        r: 0,
        b: 0,
        t: 0
  }};
Plotly.newPlot('myDiv', data, layout, {showSendToCloud: true});
```
With `trace1.opacity: 1.0`
![newplot-3](https://user-images.githubusercontent.com/15064365/51903892-4a91b480-238b-11e9-9989-0d8ff392f602.png)

With `trace1.opacity: 0.99`
![newplot-4](https://user-images.githubusercontent.com/15064365/51903953-7319ae80-238b-11e9-8df1-e01f38b8fd62.png)

Could the `opacity<1` logic be activated automatically if `marker.color` includes rgba colors with alpha < 255?  Or maybe just if there are any colors specified as rgba period.

**Comment by etpinard** [comment]
I guess we could activate it for scalar values, but for array `marker.color` that's whole other story -> https://github.com/plotly/plotly.js/issues/3138
