### ISSUE TITLE
3D grid lines and tick labels colored by rgba color with full transparency

### ISSUE THREAD

**Issue by jonmmease** [plotly/plotly.js#3493]
Uncovered by report https://github.com/plotly/plotly.py/issues/1416

 When a scatter3d marker has opacity set < 1, and the marker color is specified by an RGBA color with alpha < 1, the grid lines and tick labels take on the color of the marker.  This leads to an odd appearance when the markers are mostly of fully transparent.

CodePen: https://codepen.io/jonmmease/pen/aXmpGX

```javascript
var trace1 = {
  x: [0], 
  y: [0], 
  z: [0], 
  mode: 'markers',
  marker: {
    size: 200,
    color: 'rgb(255, 0, 0, 0)',
    line: {
    },
    // opacity: 1.0
    opacity: 0.999
  },
  type: 'scatter3d'
};

var data = [trace1];
var layout = {
      margin: {
        l: 0,
        r: 0,
        b: 0,
        t: 0
  }};
Plotly.newPlot('myDiv', data, layout, {showSendToCloud: true});
```
![screen shot 2019-01-29 at 6 15 03 am](https://user-images.githubusercontent.com/15064365/51904691-4797c380-238d-11e9-90c4-27beb28a6edd.png)

When the marker color is set as an RGB value, and the `marker.opacity` is set close to zero, the coloring of the grid lines and tick labels does not occur.

**Comment by archmoj** [comment]
Not only `markers` but also `lines` and `errorbars` have this issue. Here is a [demo](https://codepen.io/MojtabaSamimi/pen/ZwpjNM).
