### ISSUE TITLE
Integration tests for plotly.js

### ISSUE THREAD

**Issue by GoNeeti** [plotly/plotly.js#3497]
Need to test the line chart, scatter chart, spider chart etc created using plotly.js using any automation framework/tools. Following are few of the targeted verifications:

- Get data points (markers) count
- Get each data point (marker) value
- Get data points css
- Get legends css
- Handling out of the box action header items
- Zoom in/out

Have tried with java-selenium but can’t find data points (markers) in DOM to get the required styling and values.

Can anyone please help in this aspect to how to perform integration testing for these charts here?

**Comment by etpinard** [comment]
You might want to look at https://github.com/plotly/plotly.js/tree/master/test/jasmine where we use the `karma` runner and the `jasmine` test framework. 

I'll close this issue as this isn't a bug report nor a feature request. Please open a https://community.plot.ly/c/plotly-js ticket if you have any other questions on the subject.
