### ISSUE TITLE
Vertical modebars with wrapped buttons don't honor `modebar.bgcolor`

### ISSUE THREAD

**Issue by antoinerg** [plotly/plotly.js#3499]
As shown in this Codepen: https://codepen.io/anon/pen/KJawXR

**Comment by antoinerg** [comment]
The reason we hit this issue is that all modern browsers do not respect the spec and [do not grow the width of flex containers that wrap in column mode](https://stackoverflow.com/questions/33891709/when-flexbox-items-wrap-in-column-mode-container-does-not-grow-its-width).

**Comment by etpinard** [comment]
@antoinerg this one got fixed in https://github.com/plotly/plotly.js/pull/3500 too, right?

**Comment by antoinerg** [comment]
Yes it did! In #3500 we now style the background color of the button groups instead of the parent container which does not grow its width.
