### ISSUE TITLE
plotly.js breaks when jQuery is imported with no-conflict flag

### ISSUE THREAD

**Issue by nemchik** [plotly/plotly.js#350]
https://cdn.plot.ly/plotly-latest.min.js line 31
Seems to be broken right now.

**Comment by etpinard** [comment]
Can you help us out a little more?

**Comment by nemchik** [comment]
I can sure try!

I noticed my plotly JS was not working and it started sometime this morning (it was working early morning and then stopped sometime just before lunch). I used the Chrome developer tools on the Console tab to see that error message.

Some quick digging lead me to https://github.com/plotly/plotly.js/blob/master/dist/plotly.js line 58543. I'm thinking just by looking at the way it got minified that there is an issue with the syntax of calling jQuery in this location.

Not sure how helpful this is, but I un-minified the script directly from the CDN and this is the function Chrome points to
```
                triggerHandler: function(t, e, r) {
                    var n, i;
                    "undefined" != typeof jQuery && (n = $(t).triggerHandler(e, r));
                    var o = t._ev;
                    if (!o) return n;
                    var a = o._events[e];
                    if (!a) return n;
                    "function" == typeof a && (a = [a]);
                    for (var s = a.pop(), l = 0; l < a.length; l++) a[l](r);
                    return i = s(r), void 0 !== n ? n : i
                },
```
Specifically the 3rd line with the `$`.

I hope this helps narrow it down, unfortunately I don't know how to fix the issue :(

**Comment by etpinard** [comment]
Are you including `jQuery` by any chance on your page?

**Comment by etpinard** [comment]
Looks like `jQuery` in defined in the window scope, but `$` isn't, resulting in this error.

**Comment by etpinard** [comment]
In the meantime, I'd recommend importing `v1.6.3` from our cdn:

```html
<script type="text/javascript" src="https://cdn.plot.ly/plotly-1.6.3.min.js"></script>
```

**Comment by timelyportfolio** [comment]
Very likely `jQuery` with no conflict https://api.jquery.com/jquery.noconflict/ so https://github.com/plotly/plotly.js/pull/328 does not work since mixing `jQuery` and `$`.

**Comment by nemchik** [comment]
I am including jQuery in my page yes. Using the 1.6.3 version seems to be fine.

**Comment by etpinard** [comment]
@nemchik Ok. Looks like we found what's causing this issue. Thanks for the report!
