### ISSUE TITLE
box/violin vs bar positioning inconsistency

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#3502]
Not sure we can fix it in the context of the fix for #3402, but logging for reference:

Violin/box auto-populates x-axis categories here:

```javascript
Plotly.newPlot(
  document.getElementById("gd"),
  {
    data: [{
      type: "violin",
      y: [1]
    },{
      type: "violin",
      y: [1]
    }],
  }
)
```

![image](https://user-images.githubusercontent.com/6675409/52486666-bba24a80-2b89-11e9-8830-8c3588f3af4f.png)

But bar does not:

```javascript
Plotly.newPlot(
  document.getElementById("gd"),
  {
    data: [{
      type: "bar",
      y: [1]
    },{
      type: "bar",
      y: [1]
    }],
  }
)
```

![image](https://user-images.githubusercontent.com/203523/52139536-682a7c80-261e-11e9-8887-4535edc9c2f9.png)

**Comment by etpinard** [comment]
Here's the block in question:

https://github.com/plotly/plotly.js/blob/02e51d8f5ba5601f53ee3dc839ba05fb12c7f8a2/src/traces/box/calc.js#L158-L191

I guess we could add another attribute to make optionally make things consistent between bar and box/violin traces and perhaps change the default in v2 (or v3 :smirk: ).

**Comment by nicolaskruchten** [comment]
I think we will need an attribute to disable this behaviour for 1.45.0 otherwise PX will likely have trouble using `offsetgroup` and `alignmentgroup` correctly.

**Comment by etpinard** [comment]
It shouldn't any problems if `x` and `y` are set.

**Comment by etpinard** [comment]
or `x0` / `y0`

**Comment by nicolaskruchten** [comment]
Yes, but PX doesn't require both to be set and I don't want to change that...

**Comment by etpinard** [comment]
or, but then setting `x0` or `y0` will solve the issue? How is that different from adding a new box/violin attribute?

**Comment by nicolaskruchten** [comment]
OK, fair enough.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
