### ISSUE TITLE
layout.grid enhancements for plotly.py to replace make_subplots

### ISSUE THREAD

**Issue by jonmmease** [plotly/plotly.js#3507]
### Background
plotly.py has a system for building figures with subplots that predates the plotly.js `layout.grid` system for subplots.  I would like to replace this custom subplot system with `layout.grid` to reduce complexity inside plotly.py and add support for all trace types (plotly.py's system only supports Cartesian subplot types).  This transition will also make the integration of `px` into plotly.py much smoother.

### Needs
As far as I can tell, there are two features that are implemented in plotly.py's `make_subplots` function that are not supported by layout.grid.  

The first two are both demonstrated in this example https://plot.ly/python/subplots/#custom-sized-subplot-with-subplot-titles.

 1) Spanned subplots:  `make_subplots` allows individual axes to span multiple subplot grid entries
 2) Subplot titles: `make_subplots` has a system for positioning text annotations as titles for individual subplots
 3) column/row widths: `make_subplots` supports `column_width` and `row_width` arrays to support non-uniform widths of the rows and columns in the grid.
 4) insets: `make_subplots` supports the specification of insets.  TBH I'm not really sure how this works and I don't know if there are any examples of this outside of the docstring.  And this might not be something that makes sense to support in `layout.grid`.  Here's the docstring

```
    insets (kwarg, list of dictionaries):
        Inset specifications.

        - Each item in 'insets' is a dictionary.
            The available keys are:

            * cell (tuple, default=(1,1)): (row, col) index of the
                subplot cell to overlay inset axes onto.
            * is_3d (boolean, default=False): flag for 3d scenes
            * l (float, default=0.0): padding left of inset
                  in fraction of cell width
            * w (float or 'to_end', default='to_end') inset width
                  in fraction of cell width ('to_end': to cell right edge)
            * b (float, default=0.0): padding bottom of inset
                  in fraction of cell height
            * h (float or 'to_end', default='to_end') inset height
                  in fraction of cell height ('to_end': to cell top edge)
```

### API ideas
To kick things off, here's a idea for a potential plotly.js API

 1) We could add `layout.grid.rowspan` and `layout.grid.colspan` properties that may optionally be set to 2D arrays of integers.  So the example above would have a a `colspan` property of

```
[[1, 1],
 [2, 0]]
```
which would imply a `grid.subplots` property of 
```
[['xy'  , 'x2y2'],
 ['x3y3', null]]
```

2) We could add a `grid.titles` property that is a 2D array of title strings.  So the example above would have a `grid.titles` property of
```
[['First Subplot', 'Second Subplot'],
 ['Third Subplot' , null]]
```

3) We could add `grid.widths` and `grid.heights` properties that would be 1D arrays of numbers.  We could internally normalize each array and use the elements to determine the width/height of each column/row.

cc @nicolaskruchten

**Comment by nicolaskruchten** [comment]
Yup, I agree this would be great! Subplot titles would be really handy, especially if they could be used for facet labelling somehow i.e. placed on the side as well as the top and if a subplot could have two titles, for the corner one ;)

Barring that, they would still be very handy for wrapped-facet labelling

**Comment by etpinard** [comment]
### rowspan / colspan

> But seems to me yours has a clear advantage in referencing spanned grid cells in `subplot.domain`,
> do you refer to the column and row number before the cells were merged, or to the indices in the grid spec arrays? With your version the two are identical,

That's the winning argument for me. I'm voting for

```js
colspan: [[2, 0, 1],
          [0, 0, 1], // <- last one: row 1, col 2
          [1, 2, 0]]
rowspan: [[2, 0, 1],
          [0, 0, 1],
          [1, 1, 0]]
subplots: [['xy'  , null  , 'x2y2'],
           [null  , null  , 'x3y3'],
           ['x4y4', 'x5y5', null  ]]
```

### Subplot tItles 

First referencing https://github.com/plotly/plotly.js/issues/2746

> The most flexible solution of all would be annotations with `(x|y)ref: 'grid'` and `(col|row)[span]` attrs. Shapes and images could also easily support such positioning.

I think I'd vote for keeping subplot title out of gird. `(x|y)ref: 'grid'` sounds like a general enough solution. I might make it slightly for plotly.py to retain parity with the current `make_subplots` where it would need to "add" annotations behind the scenes. @jonmmease please let's us know if that's a big deal.


### Column/row widths

:+1: 

### Insets

I looked through https://github.com/plotly/plotly.py/pull/170 to try to find why `insets` were added to `make_subplots` ... to no avail. Yeah :hocho: sounds ok!

**Comment by jonmmease** [comment]
> I think I'd vote for keeping subplot title out of `layout.grid`. `(x|y)ref: 'grid'` sounds like a general enough solution. It might make it slightly tricky for plotly.py to retain parity with the current `make_subplots`: it would need to "add" annotations behind the scenes. @jonmmease please let us know if that's a big deal.

I like this solution a lot, and it should be easy enough to support from plotly.py.  Thanks @etpinard  and @alexcjohnson for improving on my suggestion!

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
