### ISSUE TITLE
Box plot with log axis results in log-scaled box widths

### ISSUE THREAD

**Issue by jonmmease** [plotly/plotly.js#3508]
Originally reported in https://github.com/plotly/plotly.py/issues/1415

When plotting a box plot on a log axis, the box widths seem to follow the log pattern.

CodePen: https://github.com/plotly/plotly.py/issues/1415
```JavaScript
var y0=[],y1=[]
for ( i = 0; i < 50; i ++) 
{
	y0[i] = Math.random();
	y1[i] = Math.random();
}

var trace1 = {
	x: y0.map(v => 1),
   y: y0,
  type: 'box'
};

var trace2 = {
  x: y0.map(v => 10),
  y: y1,
  type: 'box'
};

var trace3 = {
  x: y0.map(v => 100),
  y: y1,
  type: 'box'
};

var data = [trace1, trace2, trace3];
var layout = {xaxis: {type: 'log'}}

Plotly.newPlot('myDiv', data, layout, {showSendToCloud: true});
```
![newplot](https://user-images.githubusercontent.com/15064365/52203972-c5057d00-2840-11e9-99d7-3da526cf0971.png)

Since the width of the boxes is not a value in data coordinates, it seems to me that we shouldn't scale it according to the log axis transform.  What do you think?

**Comment by KonradTUM** [comment]
It would be really useful to input a box width in pixel. So it would be possible to output plots with different axis scales but same look. Don't know how to achieve this at the moment.

**Comment by etpinard** [comment]
> It would be really useful to input a box width in pixel.

Maybe try the new box `width` attribute added in https://github.com/plotly/plotly.js/pull/3234

**Comment by etpinard** [comment]
Thanks @jonmmease I never tried plotting a `box` trace on a log position axis. Good to know!

**Comment by s417-lama** [comment]
I fixed this issue in https://github.com/s417-lama/plotly.js/pull/1 .
Would you review the PR? @etpinard
