### ISSUE TITLE
Boxplot: set custom percentile or explicit values

### ISSUE THREAD

**Issue by jeffersonsung** [plotly/plotly.js#3519]
It there a way to customize the box plots instead of max, q3, median, q1, min? I'd like to see the 99.5% and 0.5% so the whiskers and box would size to max, 99.5%, median, 0.5%, min or 99.5%, 1sd, median, -1sd, 0.5%. Basically a customizable percentiles would be nice. Or alternatively just let me submit the 5 values top to bottom and display that.

**Comment by etpinard** [comment]
Related: https://github.com/plotly/plotly.js/issues/1059

**Comment by etpinard** [comment]
Merging into https://github.com/plotly/plotly.js/issues/1059
