### ISSUE TITLE
export util function used to parse metasrc index

### ISSUE THREAD

**Issue by VeraZab** [plotly/plotly.js#3520]

**Comment by etpinard** [comment]
You mean

https://github.com/plotly/plotly.js/blob/02e51d8f5ba5601f53ee3dc839ba05fb12c7f8a2/src/lib/index.js#L1012-L1024

that should be already available on `Plotly.Lib` in streambed.

**Comment by etpinard** [comment]
Cool. Wanna try to make a PR?

**Comment by VeraZab** [comment]
sure.. we can ship for the current deadline without this, but when I have a moment, I'll make a pr.
thanks!

**Comment by VeraZab** [comment]
aww I wish this had been in the v1.44.4 release..
