### ISSUE TITLE
Space between bars (bargap) not working on type: 'bar'

### ISSUE THREAD

**Issue by jorgemonte** [plotly/plotly.js#3523]
Hello Everyone,

I'm quite new on using Plotly.js and I cannot understand why the code isn't working as desired.
I have a type: 'bar' graphic to build, quite simple, and I need to be able to adjust the bar width (thickness) but also the gap between them.

When I change the width, they start overlaping each other and the bargap parameter inside layout isn't being applied.

Here's the problem: 
https://codepen.io/A8-XPs/pen/XOVjpv

Here's my code:

```
var xValue = ['Product A', 'Product B'];

var yValue = [20, 14];

var trace1 = {
  x: xValue, 
  y: yValue,
  type: 'bar',
  text: yValue,
  textposition: 'auto',
  hoverinfo: 'none',
  width: 12,
  marker: {
    color: 'rgb(158,202,225)',
    opacity: 0.6,
    line: {
      color: 'rbg(8,48,107)',
    }
  }
  
};

var data = [trace1];

var layout = {
  title: 'January 2013 Sales Report',
  bargap: 0.8
};

Plotly.newPlot('myDiv', data, layout, {showSendToCloud:true});
});
```

**Comment by etpinard** [comment]
That's the expected behavior (unfortunately). `bargap` is ignored whenever `width` is set. 

I'm not sure what your desired results is, but you might want to try to tweak `offset` for example:

https://codepen.io/etpinard/pen/ompYMM

**Comment by jorgemonte** [comment]
Hello my friend,

It is exactly the visual result that I need, however I just realiezed that the text below are togheter. I will need them on each bar and also the bars must have different colors. I guess I will need to have trace 1 and trace 2 to reach that result, right?

The offset solution is awesome!

**Comment by etpinard** [comment]
> It is exactly the visual result that I need, however I just realiezed that the text below are togheter. I will need them on each bar and also the bars must have different colors. I guess I will need to have trace 1 and trace 2 to reach that result, right?

Closing this issue as this ticket won't result in any work on our end.

@jorgemonte please ask your other implementation questions over at https://community.plot.ly/c/plotly-js so that other users can help you and/or be helped. Thank you for using plotly.js!

**Comment by jorgemonte** [comment]
Thank you! it was very helpful
