### ISSUE TITLE
react + legendonly bug

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#3525]
Calling `Plotly.react` from a state with all traces `visible: 'legendonly'` to a new normal state breaks the plot until a fresh `newPlot` call.
https://codepen.io/alexcjohnson/pen/RvxLNy?editors=1010

Originally reported in https://github.com/plotly/dash/issues/595

Separate note: why can't I click the legend lines/symbols to show/hide traces? I have to click the name or the space immediately above or below the legend line, but the lines/symbols themselves don't do it.

**Comment by alexcjohnson** [comment]
This is something to do with `uirevision` - simply setting all traces `visible: 'legendonly'` in the initial figure does not trigger this bug.

**Comment by etpinard** [comment]
Hmm, very strange. Using `restyle(gd, 'visible', 'legendonly')` instead of clicking on the legend items gives the correct result -> https://codepen.io/etpinard/pen/pGpdJP?editors=1010

So yeah, this is consistent with something being up with `uirevision`.
