### ISSUE TITLE
scattergl does not display points in Firefox

### ISSUE THREAD

**Issue by antoinerg** [plotly/plotly.js#3533]
I don't have a reproducible example of this but a user showed me a `scattergl` trace with lots of datapoints not displaying markers in Firefox (although Chrome was fine). This was inside a Dash app running `dash-core v0.43.0` so plotly.js' version was `v.1.44.1`. Although the points were invisible, the hoverlabels were properly rendered.

Maybe related to https://github.com/plotly/plotly.js/issues/3413

@plotly/plotly_js

**Comment by etpinard** [comment]
Let's merge this in #3413, until we have a reproducible example.
