### ISSUE TITLE
showLink: false not working

### ISSUE THREAD

**Issue by amellnik** [plotly/plotly.js#354]
The example in the docs is 
```html
<head>
  <!-- Plotly.js -->
   <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
</head>

<body>
  <div id="myDiv" style="width: 480px; height: 400px;"><!-- Plotly chart will be drawn inside this DIV --></div>
  <script>
var trace1 = {
  x: [0, 1, 2, 3, 4, 5, 6],
  y: [1, 9, 4, 7, 5, 2, 4],
  mode: 'lines+markers',
  type: 'scatter'
};

var data = [trace1];
var layout = {
	title: 'Hide the Edit Chart Link',
	showlegend: false};
Plotly.newPlot('myDiv', data, layout, {showLink: false});
  </script>
</body>
```

which produces the following:

![image](https://cloud.githubusercontent.com/assets/7132414/14003408/9d7b5d2e-f10f-11e5-809b-a9c64d9c20fb.png)

However, it does appear to be working in the codepen [here](https://plot.ly/javascript/configuration-options/).  Can anyone tell what's going on?

**Comment by etpinard** [comment]
Are you talking about the camera button ![image](https://cloud.githubusercontent.com/assets/6675409/14005655/8f01cbf8-f13b-11e5-8e1e-6b204d316abf.png) in the mode bar at the top right corner of the graph or the *Edit chart* link text which appears at the bottom right corner?

If the former, then you need to call:

```js
Plotly.newPlot('myDiv', data, layout, { modeBarButtonsToRemove: ['sendDataToCloud'] });
```

more info [here](https://github.com/plotly/plotly.js/blob/bbb8205903cdd34ae019d5cd6a2c197e9a2550e7/src/components/modebar/buttons.js#L98) and [here](https://github.com/plotly/plotly.js/blob/bbb8205903cdd34ae019d5cd6a2c197e9a2550e7/src/plot_api/plot_config.js#L63).

**Comment by amellnik** [comment]
This answers my question, thanks!  Apparently it's a coincidence that the disk icon was also disabled in that codepen.

**Comment by etpinard** [comment]
Correct. All graphs on plot.ly are displayed without the `sentDataToCloud` button.

I hope you agreed: there's no need to send data to plot.ly when the graph already resides on it.
