### ISSUE TITLE
Candlestick chart broken with null values at the end of trace

### ISSUE THREAD

**Issue by jakubkottnauer** [plotly/plotly.js#3542]
Candlestick chart is broken when there are `null` `y` values at the the end of the trace. Interestingly enough, it works as expected if there are `null`s at the beginning of the trace as well or when the trace is rendered together with with e.g. a bar chart.

There are four different examples available here showing different stages of broken-ness: https://codepen.io/jakubkottnauer/pen/LqJzZq

**Comment by etpinard** [comment]
Thanks for the report!

**Comment by etpinard** [comment]
The problem is with the auto-range. Things appears ok when setting the `xaxis.range`:

https://codepen.io/etpinard/pen/bzxXYP
