### ISSUE TITLE
scattergl & gap between points : strange behavior

### ISSUE THREAD

**Issue by Smurf81** [plotly/plotly.js#3551]
Hello,

i find an interesting bug when using scattergl et gap between point.

I made an exemple with 2 traces :
- first trace have a gap with data in Y as [1,null,1,2]. The data is not the same for all point. It works as expected.
- second trace have a gap with data in Y as [3,null,3,3]. The data is the same for all points except the null.
It doesn't works because there is a line between the first & the third point.

An exemple is visible here : https://codepen.io/anon/pen/KJbEoX

No problem with scatter.

**Comment by etpinard** [comment]
Thanks for the report!

**Comment by etpinard** [comment]
This is `regl-line2d` bug (see -> https://github.com/gl-vis/regl-line2d/issues/43)
