### ISSUE TITLE
Scatter3D errors on modebar interaction

### ISSUE THREAD

**Issue by jermainezhimin** [plotly/plotly.js#3552]
**Info**
There seems to be a feature regression in plotly.js version 1.44.0. Interacting with `zoom` or `pan` of the modebar in a plot (`type='scatter3d` with markers based on a colorscale), causes a console error and a visual error(markers turn black and colourscale turns white).

```js
[Error] Error: Invalid value for <rect> attribute height="NaN"
	attrConstant (plotly-1.44.0.js:18832)
	(anonymous function) (plotly-1.44.0.js:19131)
	d3_selection_each (plotly-1.44.0.js:19137)
	each (plotly-1.44.0.js:19130)
	attr (plotly-1.44.0.js:18818)
	(anonymous function) (plotly-1.44.0.js:80052)
	(anonymous function) (plotly-1.44.0.js:19131)
	d3_selection_each (plotly-1.44.0.js:19137)
	each (plotly-1.44.0.js:19130)
	drawAxis (plotly-1.44.0.js:80036)
	syncOrAsync (plotly-1.44.0.js:99295)
	component (plotly-1.44.0.js:80263)
	connectColorbar (plotly-1.44.0.js:79564)
	marginPushers (plotly-1.44.0.js:104597)
	syncOrAsync (plotly-1.44.0.js:99295)
	plot (plotly-1.44.0.js:104678)
	syncOrAsync (plotly-1.44.0.js:99295)
	relayout (plotly-1.44.0.js:106212)
	wrappedEdit (plotly-1.44.0.js:106740)
	handleDrag3d (plotly-1.44.0.js:89353)
	(anonymous function) (plotly-1.44.0.js:90097)
```

**Reproduction Steps**

1. Create a `scattet3d` chart with a color scale using the latest version of plotly.
2. Click on the modebar. 

**Repro Codepen**
https://codepen.io/jermainezhimin/pen/pGGbeP?editors=1000#0

**Repro Gif**
![hqyazmfp3v](https://user-images.githubusercontent.com/14270200/52973970-cec8cd80-3374-11e9-896b-5a1075505cce.gif)

**Comment by etpinard** [comment]
Thanks for the report!

**Comment by etpinard** [comment]
The culprit is https://github.com/plotly/plotly.js/pull/3384

Thanks again for the very clear report @jermainezhimin ! We'll have a patch out soon.
