### ISSUE TITLE
Using matches when opposite axis is categorical causes error

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#3560]
This pen shows the problem: https://codepen.io/nicolaskruchten/pen/gqyyVL?editors=0010

**Comment by nicolaskruchten** [comment]
Note that this only happens with the `x` axis AFAICT... doing the same trick with `x` doesn't fail.

**Comment by nicolaskruchten** [comment]
Hmm doesn't even seem related to grid per se.

**Comment by nicolaskruchten** [comment]
Here's the same problem with scatter, no grid, on Y: https://codepen.io/nicolaskruchten/pen/LqvoNV?editors=0010

**Comment by nicolaskruchten** [comment]
OK so actually it's not just `y` ... same thing happens on `x` if I swap everything! Basically if the non-shared axis is categorical it doesn't work, but if both are linear it does, in both permutations! See https://codepen.io/nicolaskruchten/pen/LqvoNV?editors=0010

**Comment by etpinard** [comment]
That's the expected behaviour. Matching axes only work on axes of the same type.

**Comment by nicolaskruchten** [comment]
No... in this case I'm matching continuous to continuous, but the OTHER axis is categorical.

**Comment by nicolaskruchten** [comment]
i.e. both `y`s are continuous, and the `x` is categorical, and I'm trying to match `y2` to `y`.

**Comment by etpinard** [comment]
Ah I see. On it!
