### ISSUE TITLE
Sankey nodes jump on dragging

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#3563]
When you drag a sankey node, on first mouse move it jumps vertically (or horizontally if the diagram is horizontal). Bug exists on master but not in the latest release 1.44.4
![sankey-drag-jump](https://user-images.githubusercontent.com/2678795/53183247-f4e6ab80-35c8-11e9-9924-e17e391efd3c.gif)
cc @antoinerg

**Comment by antoinerg** [comment]
Thank you @alexcjohnson for reporting this issue. It has to do with a change of coordinates that is done prior to running the force simulation.

However, I think I resolved this issue at some point. Did you run `npm i` before starting your devtools?
