### ISSUE TITLE
Change chart color based on value

### ISSUE THREAD

**Issue by ValerioCasini** [plotly/plotly.js#3567]

**Comment by ValerioCasini** [comment]
i want to change the color of my chart when the value of y axis overtake 1000,how can i do?

**Comment by blozano824** [comment]
You can probably split your data into sections. When your data crosses the threshold, create a new section of data until the values crosses the threshold again. You would end up with sections above and below and you may apply a specific colors to those traces accordingly.

For example,
```
data = [0, 200, 400, 600, 800, 1000, 1200, 1400, 1200, 1000, 800, 600] 
```
would be split into:
```
above = [[1000, 1200, 1400, 1200, 1000]]
below = [[0, 200, 400, 600, 800], [800, 600]]
```

Then `below` could be plotted as green traces and the `above` array could be plotted as red traces.

**Comment by etpinard** [comment]
Best for https://community.plot.ly/c/plotly-js
