### ISSUE TITLE
Use hoverdistance with hovermode closest

### ISSUE THREAD

**Issue by mmustala** [plotly/plotly.js#3569]
Hi.

My chart shows a lot of scatter lines and using the default hovermode became very verbose. Changing to hovermode 'closest' helped with it a lot. But now it is rather difficulty to hit some data points (candlesticks next to a scatter point especially) to see the hover box. I tried to set hoverdistance to 100 but it doesn't seem to have effect with this hovermode. But it would be really nice if it would show all hover items within the range defined with hoverdistance. But maybe just one item per data set, the one that is closest in the x axis. 

Another way to reach this would be to have separate setting for x and y hoverdistance. Then I could use the default hovermode but define y hoverdistance to something like 10. Then it would show the hover items that are within the rectangle defined by the x and y hoverdistances.

**Comment by etpinard** [comment]
Thanks for writing in.

Could you share a reproducible (ideally in a codepen) of the situation you're describing? `hoverdistance` appears to be working ok on graphs with `hovermode: 'closest'`, example:

https://codepen.io/etpinard/pen/modbWY

**Comment by mmustala** [comment]
What I meant is that it would show all points that are within the `hoverdistance`. The code in this pen demonstrates that it shows only one point even though two points from different data sets are within the range.

https://codepen.io/anon/pen/qvNobN

I think this kind of feature would require a new hovermode. Maybe `in-range`?

**Comment by etpinard** [comment]
Related: https://github.com/plotly/plotly.js/issues/720

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
