### ISSUE TITLE
Line drawn at x axis with more data samples

### ISSUE THREAD

**Issue by shrau94** [plotly/plotly.js#3574]
Hi,

The plotly line chart shows the extra line on x axis while the same is not shown when there is less samples of data.

example with 5000 samples of data.
[Link](https://codepen.io/anon/pen/drbgVa)

![image](https://user-images.githubusercontent.com/10210384/53334782-bf6ef480-391f-11e9-885f-66cc0afba10b.png)

example with 14 samples of data
[Link](https://codepen.io/anon/pen/zbOMVx)

![image](https://user-images.githubusercontent.com/10210384/53334809-ddd4f000-391f-11e9-9e8f-ed51e8aededc.png)

In the first case with 5000 samples, a black line is drawn at x axis where as in the later case it is not drawn.
The configs for both are same. Can you please let me know if I should be giving a property to remove that line?

Plotly version: 1.36.1

**Comment by inaw-tihor** [comment]
i am also facing the same issue. is there any limit on number of samples that needs to be passed to plotly chart.

**Comment by etpinard** [comment]
I think you're referring to

https://plot.ly/javascript/reference/#layout-yaxis-zeroline

Setting `yaxis.zeroline: false` as in https://codepen.io/etpinard/pen/OqJLzP makes it disappear.

You might want to lookup https://community.plot.ly/c/plotly-js in the future for questions of the likes.

**Comment by shrau94** [comment]
Thanks for the help @etpinard 
My concern was why this is not happening with the lesser data samples and is happening only in the case of large data set.

**Comment by etpinard** [comment]
It has nothing to do with the size of your data. That zeroline shows up by default when your data has value near zero.

**Comment by etpinard** [comment]
Closing. @shrau94 please use https://community.plot.ly/c/plotly-js if you have any other questions on the topic. Thanks!
