### ISSUE TITLE
Undesirable camera reposition just after plot and first left/middle/right click

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#3576]
Undesirable camera rotations sometimes happen right after plots and before modebar shows up if clicking on the white space! 
Please try the example below "multiple times". It is also reproducible with old versions.
[Codepen](https://codepen.io/MojtabaSamimi/pen/RdwPZO?editors=1010).

**Comment by etpinard** [comment]
Fixed by @archmoj in https://github.com/plotly/plotly.js/pull/3585 :tada:
