### ISSUE TITLE
hovertemplate d3-format numbers ignoring locale

### ISSUE THREAD

**Issue by jwmann** [plotly/plotly.js#3580]
When I set the locale, the dates are formatted correctly. But the numbers using the d3-format ignores that locale and instead follows the `en-us` default format and not the defined format from Plotly.

As per the built-in locales. => https://github.com/plotly/plotly.js/blob/master/lib/locales/fr.js#L86-L87
For FR, the separator should be a space " " and the decimal should be a comma ",".

Here is a sandbox of my implementation.
[![Edit react-plotly.js DOM element is null or undefined -- fixed](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/381790o4rm?codemirror=1&fontsize=14)

Hover over the bars on the chart.

The $000,000.00 should look like this $000 000,00 in FR

Maybe I'm missing something obvious though.

**Comment by antoinerg** [comment]
Thank you @jwmann for reporting this issue. I don't think you're missing anything obvious: the problem probably lies in our current implementation of `hovertemplate`. We will work on a fix as soon as possible.

Thanks again :)
