### ISSUE TITLE
Cannot zoom when the new orthographic projection mode is used

### ISSUE THREAD

**Issue by emimoun** [plotly/plotly.js#3588]
Hello,

I jumped on the new orthographic projection feature as I needed it, and saw a several problem rigth away : one cannot zoom anymore, instead the plot is hidden partly when one scrolls, for example. This is actually already visible on the [demo](https://codepen.io/MojtabaSamimi/pen/zeyEGK?editors=0010) shown in the original [pull request](https://github.com/plotly/plotly.js/pull/3550). I thought the bug would go away in the final release but it is still there. When one goes back to standard projection, zoom works.

Could you help fixing this?
Thanks.

**Comment by archmoj** [comment]
Hello @emimoun,
Thanks for testing the `orthographic` feature. 
The `zoom` on this projection is working similar to `perspective` projection i.e. panning in z direction (webgl Y axis). So if you continue zooming you may notice that the near clip could slice the data cube which is in fact very useful for exploring the 3-D data.
Here is an example you could quickly test this behaviour: https://rreusser.github.io/plotly-mock-viewer/#gl3d_isosurface_9more-surfaces_between-ranges_orthographic.
And here is another [codepen](https://codepen.io/MojtabaSamimi/pen/MxaMrJ) that may be of interest.
As another note if you would like to `scale` the graph in the viewport, it is possible to simply use the `aspectratio` attribute on the `layout.scene`. 
Hope this info may be helpful.

**Comment by alexcjohnson** [comment]
As useful as slicing may be, I think I'm with @emimoun on this one - the zoom interaction should make the scene bigger or smaller, whether we're using perspective or orthographic projection. If we were to design a slicing feature, we would want it to work differently: somehow tied to visual indicators of where you're slicing - at an axis value, for example - and keeping that slice as you rotate. Using zoom to create a slice is unintuitive and limited to slicing orthogonal to the depth direction.

**Comment by alexcjohnson** [comment]
It's also not helpful that the axes and labels get sliced off along with the data in the existing implementation!
