### ISSUE TITLE
[Feature Request] use own style.json instead of mapbox access token 

### ISSUE THREAD

**Issue by anderl80** [plotly/plotly.js#3592]
For plotly scatter mal plots:

I'd wish the package also offered the possibility to use a self defined style.json like when you use Mapbox natively in JS. Using this specification (and using OSM tiles) makes the mapbox_access_token obsolete.

https://github.com/plotly/plotly.py/issues/1431

**Comment by etpinard** [comment]
Thanks for posting. We'll make that simpler this spring.

In the meantime you can get this to work by providing a dummy mapbox access token: https://codepen.io/etpinard/pen/KbxgXb

**Comment by etpinard** [comment]
Related https://github.com/plotly/plotly.js/issues/3173, https://github.com/plotly/plotly.js/issues/2988
