### ISSUE TITLE
Variable bin sizes for histograms

### ISSUE THREAD

**Issue by pollackscience** [plotly/plotly.js#360]
It would be useful to allow for variable-sized bins for histogram plotting.  User should be able to give a list of bin edges to xbins or ybins (or some similar attribute), similar to functionality available in matplotlib.

**Comment by naodell** [comment]
I would also like to see this feature implemented.

**Comment by dschouten** [comment]
I second this request!

**Comment by ndawe** [comment]
Would love to have ability to specify the bin edges manually now after wanting to show bins with visually the same width on a histogram with a logarithmic x-axis.

**Comment by ndawe** [comment]
The race is on with Bokeh: https://github.com/bokeh/bokeh/issues/3398 :wink:

**Comment by rajsahae** [comment]
+1
Could we get an estimate of when this could go in? Otherwise I would need to switch to use a different charting library.

**Comment by sweatyrichard** [comment]
Agreed, this is a standard configuration attribute for histograms.

**Comment by elv1s42** [comment]
Any updates on this one?
Would be very useful.

**Comment by chriddyp** [comment]
Any companies out there interested in sponsoring this item?
https://plot.ly/products/consulting-and-oem/

**Comment by ice-ctrl** [comment]
2022. Still hoping for this feature.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
