### ISSUE TITLE
size of marker in legend

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#3602]
When I map size to a scatter, the resulting legend item is far too small. I literally can't tell the top marker apart from the nearby spec of dust on my screen :)

![image](https://user-images.githubusercontent.com/203523/53746396-14a28d00-3e6f-11e9-903b-8aefb46c79b7.png)

**Comment by etpinard** [comment]
Duplicate of https://github.com/plotly/plotly.js/issues/2745

**Comment by nicolaskruchten** [comment]
OK.
