### ISSUE TITLE
Hover Labels Overlap in 2d scatter plot

### ISSUE THREAD

**Issue by tfg250** [plotly/plotly.js#3603]
In my 2D scatter plot, the hover labels for closely spaced traces overlap when I think they should be stacked. It appears to be related to the level of zoom. Is the intended behavior for the labels to overlap when zoomed out?

A quick example is here:
[https://plot.ly/~tfg250/141](https://plot.ly/~tfg250/141)

In this plot, the initial view shows this:
![image](https://user-images.githubusercontent.com/15915420/53747764-fc803d00-3e71-11e9-83d0-2815745e6c2d.png)

Zooming in a bit and it changes to the expected view:
![image](https://user-images.githubusercontent.com/15915420/53747818-1a4da200-3e72-11e9-9a03-b402c5b2da53.png)

python code used to generate this plot:
```python
traces=[]
for i in range(10):
    x=[i,i+1]
    y=[i,i+1]
    traces.append(go.Scatter(x=x,y=y))

for i in range(10):
    x=[i,i+1]
    y=[i+1,i+2]
    traces.append(go.Scatter(x=x,y=y))

layout = go.Layout(xaxis=dict(range=[0, 100]),yaxis=dict(range=[0, 100]))

fig = go.Figure(data=traces,layout=layout)
py.plot(fig, filename='test.html')
```

**Comment by antoinerg** [comment]
Thank you @tfg250 for reporting this issue!

**Comment by antoinerg** [comment]
Codepen for this issue: https://codepen.io/antoinerg/pen/MxEjeo
