### ISSUE TITLE
[wip] - issues encountered working with small margins

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.js#3607]
This is a work-in-progress issue to contain screenshots and examples of issues that I'm running into with using extremely small margins with dash-design-kit.

In ddk, most graphs are inside other containers ("cards") and we're trying to keep the graph as large as possible within the container, ideally flush with the card. In order to do so, we set the margins really small and use automargin.

Most of the time this works great. There are some cases that I notice here and there where things get cut off. I'd like to collect those screenshots in this issue & then recategorize, isolate, create repro examples, and prioritize them later.

**Comment by chriddyp** [comment]
- Rightmost label cut off
![image](https://user-images.githubusercontent.com/1280389/53780918-8e209680-3ed4-11e9-83df-0bd6c2bf0e0b.png)

- Rightmost hover label cut off
![image](https://user-images.githubusercontent.com/1280389/53780943-ac869200-3ed4-11e9-883e-5e4abcd4eb98.png)
![image](https://user-images.githubusercontent.com/1280389/53780993-e0fa4e00-3ed4-11e9-87a2-0be83a20b032.png)

- It'd be nice to be able to expand the graph's height rather than shrink it's bottom margin. In Dash apps, we frequently have variable or unspecified chart height

- It'd be nice if I could specify a "minimum padding between label & axis title". with automargin, they end up looking a little too tight:
![image](https://user-images.githubusercontent.com/1280389/53780974-cfb14180-3ed4-11e9-87bd-3e232d097546.png)

**Comment by etpinard** [comment]
> * Rightmost label cut off

That will be fixed in https://github.com/plotly/plotly.js/pull/3605 (assuming you have `xaxis.automargin: true`)

**Comment by etpinard** [comment]
> * It'd be nice if I could specify a "minimum padding between label & axis title". with automargin, they end up looking a little too tight:

That one is related (but distinct, I think) to: https://github.com/plotly/plotly.js/issues/2575

**Comment by nicolaskruchten** [comment]
OK, I've just created a batch of issues capturing the various cases and we'll work them during 1.51

**Comment by etpinard** [comment]
Can we close this one?

All the issues pointed out here have been addressed (most of them released in `v1.51.0`) except for https://github.com/plotly/plotly.js/issues/4222

**Comment by chriddyp** [comment]
🥇 🥇 🥇 Nice work!
