### ISSUE TITLE
Draw y axis in different ticks 

### ISSUE THREAD

**Issue by eromoe** [plotly/plotly.js#3608]
I don't see this feature in docs, so ask here. 

For example, I create a scratter to show the percentage difference between real sale_count and my model predicted sale_count of some products :

![image](https://user-images.githubusercontent.com/3938751/53862691-14e38980-4023-11e9-9ba4-da151523158f.png)

--

    percentage_difference = (predict_value - real_value)/real_value

Most of points mainly locate in 0 ~ 1 . (percentage 0% ~ 100% )
As we know, there are always some outliers in the data, some of them may exceed 10 .

So I want to display the plot y axis in : `[-10, -5, -1, 0, 1, 5, 10]`

    500% ~ 1000% with length 1
    100% ~ 500% with length 2
    0% ~ 100% with length 3
    0% ~ -100% with length 3
    -100% ~ -500% with length 2
    -500% ~ -1000% with length 1

I think this is an usual requirement.

**Comment by alexcjohnson** [comment]
Sounds like what you're interested in is a symlog / asinh transform as discussed in #221 
Other arbitrary transformations (as well as symlog unless and until we add it to plotly.js) can be handled with custom tick labels - you can do something like:
- set the `trace.y` values to the transformed data
- provide the original data as part of `trace.hovertext` (or `hovertemplate` with the original data in `customdata` perhaps)
- use `yaxis.tickvals/ticktext` to label the axis according to the transformation

**Comment by etpinard** [comment]
Merging into #221

**Comment by zxdawn** [comment]
@eromoe I want the similar setting as yours: control the length for specific space. How did you deal with it at the end?
