### ISSUE TITLE
Fast scroll zoom results in out of memory error

### ISSUE THREAD

**Issue by arnog** [plotly/plotly.js#3615]
See https://codepen.io/arnog/pen/YgZdEZ

1. Create a heatmap plot with about 500 x 500 elements
2. Configure the plot with `scrollZoom = true` and `zsmooth = 'fast'`
3. Use the mouse wheel to zoom in rapidly into the plot

Result:
- the plot is not zoomed in and the console displays "Uncaught RangeError: Invalid array length"

The array being created is the pixel array in which to draw the interpolated heatmap at traces/heatmap/plot.js:238

The problem seems to be that `imageWidth` and `imageHeight` are used here and later in the function, perhaps instead of `canvasW` and `canvasH`.

**Comment by antoinerg** [comment]
@arnog I could not replicate the particular error message you received. What operating system and web browser were you using?

@archmoj Can you reproduce this issue?

**Comment by antoinerg** [comment]
While investigating the issue reported by @arnog, I uncovered the following bug in `heatmapgl`: https://github.com/plotly/plotly.js/issues/3624

**Comment by alexcjohnson** [comment]
I managed to crash the browser tab zooming in on this plot. It got slower and slower as I zoomed in, eventually crashing. But I also see a bug when you zoom out, an increasingly small fraction of the total trace is shown.
![heatmap scroll sm](https://user-images.githubusercontent.com/2678795/54150863-e6ddbb00-440f-11e9-9826-ba63bad29980.gif)
Mac OS 10.14, Chrome 72.

**Comment by antoinerg** [comment]
I could reproduce the issue as well. When zooming in, the memory usage skyrockets from ~200M to a whopping 1500M.

Thanks @arnog

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Comment by arnog** [comment]
The issue still happens. I will open a new issue: #7021

**Comment by gvwilson** [comment]
thank you @arnog
