### ISSUE TITLE
Uncaught TypeError while zooming during extendTraces 

### ISSUE THREAD

**Issue by galuha** [plotly/plotly.js#3616]
Hello.
The problem is, when zooming with the mouse selection while Plotly is doing extendTraces, it throws this "Uncaught TypeError: Cannot read property 'length' of undefined".
To reproduce, try to zoom the chart, i.e. select some area and hold the selection for a while. The error will be visible in the browser console

https://codepen.io/galuha/pen/ywMmPZ?editors=1111

**Comment by archmoj** [comment]
@galuha Thanks for the report as well as clear codepen.

**Comment by etpinard** [comment]
Essentially a duplicate of https://github.com/plotly/plotly.js/issues/3305
