### ISSUE TITLE
exception when panning / zooming an updating plot

### ISSUE THREAD

**Issue by patrislav1** [plotly/plotly.js#3617]
Hi,

this bug is reproducible in the official plot-updating ("streaming") example that uses the extendTraces() API to update the plot.
https://plot.ly/javascript/streaming/
https://codepen.io/plotly/pen/dRaawR

when a mouse click happens inside the graph for a pan/zoom operation while extendTraces() is running, there is a `uncaught exception: undefined` error.
and upon mouse button release it says
~~~
TypeError: calcdata is undefined[Learn More] plotly-latest.js:113938:16

drawData https://cdn.plot.ly/plotly-latest.js:113938 
syncOrAsync https://cdn.plot.ly/plotly-latest.js:103128 
relayout https://cdn.plot.ly/plotly-latest.js:110061 
wrappedEdit https://cdn.plot.ly/plotly-latest.js:110618 
call https://cdn.plot.ly/plotly-latest.js:142243 
dragTail https://cdn.plot.ly/plotly-latest.js:120870 
syncOrAsync https://cdn.plot.ly/plotly-latest.js:103128 
dragTail https://cdn.plot.ly/plotly-latest.js:120866 
onDone https://cdn.plot.ly/plotly-latest.js:85342 
~~~

when it's a pan operation, then the plot jumps back and forth before eventually showing up at the position to where it's supposed to move.

**Comment by etpinard** [comment]
Thanks for reporting! Merging with https://github.com/plotly/plotly.js/issues/3305
