### ISSUE TITLE
Plotly_unhover not triggered following restyle in plotly_hover in Pie Charts

### ISSUE THREAD

**Issue by PaulRCooper** [plotly/plotly.js#3618]
Hi,

I found a issue with restyling the chart in plotly_hover events stops the triggering of plotly_unhover event and also stops the hover text from disappearing. Please note it works in other chart types.

I have created an example showing the issue with the first chart showing the issue, a second chart without restyling and a third showing it working with restyling in a Bar Chart. In all cases I have added code to write "hover" or "unhover" to the console in the appropriate event.

Example web-page can be found here: [https://jsbin.com/pavopaq](https://jsbin.com/pavopaq)

**Comment by PaulRCooper** [comment]
No love for this one? Is more information required?

**Comment by antoinerg** [comment]
Thank you @PaulRCooper for clearly reporting this issue!
