### ISSUE TITLE
Compare Mode Bar button is for 'x' axis not 'y'axis when all Scatter Chart traces are Horizontal

### ISSUE THREAD

**Issue by PaulRCooper** [plotly/plotly.js#3619]
The compare mode bar button behaviour is for 'x' axis rather than even when you set all the traces to horizontal (orientation of 'h'). 

If you set the traces as horizontal the Mode Bar and set the hovermode to 'y' the button is unselected (so is the closest button) even though the expected 'y' hovermode behaviour occurs when hovering.

See example at [https://jsbin.com/wibivof](https://jsbin.com/wibivof). Here I have 3 charts: 

1.  The first is a horizontal bar chart showing the correct and expected behaviour in both the chart and the button. 

1. The second chart shows a horizontal scatter chart (all traces are horizontal) with hovermode set to 'y' and you get the correct behaviour on hovering but the button is unselected. If you click on the compare button you get 'x' axis compare behaviour instead. To get 'y' mode behaviour requires a refresh of the page.

1. The third chart is a copy of the second chart but includes a workaround to force the correct behaviour using the plotly_afterplot event to update the hovermode and the button state.

Possibly relates to issue [#778](https://github.com/plotly/plotly.js/issues/778)

**Comment by etpinard** [comment]
The second chart shows a horizontal scatter chart (all traces are horizontal) with hovermode set to 'y' and you get the correct behaviour on hovering but the button is unselected. If you click on the compare button you get 'x' axis compare behaviour instead. To get 'y' mode behaviour requires a refresh of the page.

Behavior w/o setting `hovermode` to `'y'` is in: https://codepen.io/etpinard/pen/eXWXyy

Thanks for the report!
