### ISSUE TITLE
Using plotly.js offline via nw.js error

### ISSUE THREAD

**Issue by eugenesvk** [plotly/plotly.js#362]
I'm trying to use plotly in [nw.js](http://nwjs.io/) per suggestion from https://github.com/plotly/plotly.js/issues/20 as I'd like to be able to generate images locally.
However, a simple chart wouldn't work if I use `var Plotly = require('plotly.js');` in my script instead of just using the CDN version. I just get a blank screen when I launch `nw` from the app folder. 

My **index.hml** is as follows
```
<!DOCTYPE html>
<html>
<head>
	<script type="text/javascript" src="https://cdn.plot.ly/plotly-latest.min.js"></script>
  <meta charset="utf-8">
  <title>Plotly | Simple bar chart</title>
</head>
<body>
  <div id="myDiv" style="width: 480px; height: 400px;"><!-- Plotly chart will be drawn inside this DIV --></div>
	<script id="javascript">
		// var Plotly = require('plotly.js');  // if I comment this out, it works, if I require local module, it doesn't :(
		var data = [{
		  x: ['giraffes', 'orangutans', 'monkeys'],
		  y: [20, 14, 23],
		  type: 'bar'
		}];

		var config = {
		   modeBarButtonsToRemove: ['toImage', 'sendDataToCloud'],
		   displaylogo: false
		};
		Plotly.newPlot('myDiv', data, {}, config);
	</script>
</body>
</html>
```
and my **package.json** is
```
{
  "name": "Plotly",
  "version": "1.0.0",
  "main": "index.html"
}
```

When I try to require plotly.js from node REPL I get the following:
```
> var Plotly = require('plotly.js');
ReferenceError: document is not defined
    at Object.lib.addStyleRule (C:\app\node_modules\plotly.js\src\lib\index.js:416:21)
    at Object.<anonymous> (C:\app\node_modules\plotly.js\build\plotcss.js:61:16)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\app\node_modules\plotly.js\src\plotly.js:30:1)
    at Module._compile (module.js:413:34)
```

Not really sure what this means and how I can use plotly locally. Any ideas? Would be great to have a simple guide in the docs describing a way to set this up as I understand that "plotly.js will remain a browser-only library for the foreseeable future" (https://github.com/plotly/plotly.js/issues/20)

npm v. 3.5.2
Win 10
node v.5.9.1

**Comment by etpinard** [comment]
> a simple chart wouldn't work if I use `var Plotly = require('plotly.js');`

As far as I know, nw.js packages that are imported using `require` are supposed to work inside a node.js context - which is currently not the case for plotly.js. Whereas, packages that are impoted in `<script>` tags don't have that restriction. More info [here](https://github.com/nwjs/nw.js/wiki/Differences-of-JavaScript-contexts#determining-thecontext-ofascript).

Here's a working example of plotly.js inside the nw.js environment: https://gist.github.com/etpinard/d27a44bd5dbee5490f20

You may also be interested in using plotly.js with the karma runner: https://gist.github.com/etpinard/ac6402406afcd1ce38a4 

And our current work-in-progress plotly.js in node using `jsdom`: https://gist.github.com/etpinard/bee7d62b43b6bb286950

**Comment by eugenesvk** [comment]
Thank you
Your first gist re. nw.js is using `src="https://cdn.plot.ly/plotly-latest.min.js">`. Do you have an example using locally installed version of plotly.js module?

Second example is working if I install all the modules locally, which is a bit inconvenient as I have charts in different folders and wouldn't want to pollute each folder with duplicate modules. Would you have an idea how to tweak your gist to make it work with globally installed modules? (there maybe a limitation on the karma side, also trying to test that as I get `[reporter]: Can not load "custom", it is not registered!` error when all modules are global + your karma-custom-reporter/report.js is symlinked globally as well).

Will check out the 3rd a bit later.

**Comment by eugenesvk** [comment]
The 3rd option gives the following error (after cloning gist and running `npm i` to install modules locally)
```
...\node_modules\jsdom\lib\jsdom\living\document.js:130
      throw new TypeError("First argument to importNode must be a Node");
      ^

TypeError: First argument to importNode must be a Node
    at HTMLDocument.core.Document.importNode (...\node_modules\jsdom\lib\jsdom\living\document.js:130:13)
    at Array.d3.selection.appendSVG (about:blank:60545:59)
    at showText (about:blank:60607:27)
    at Array.util.convertToTspans (about:blank:60690:10)
    at Array.d3_selectionPrototype.call (about:blank:7409:14)
    at drawTitle (about:blank:57095:10)
    at Object.lib.syncOrAsync (about:blank:59180:15)
    at Array.titleLayout (about:blank:57078:13)
    at Array.d3_selectionPrototype.call (about:blank:7409:14)
    at Object.Titles.draw (about:blank:57167:10)
```

**Comment by etpinard** [comment]
> Do you have an example using locally installed version of plotly.js module?

replacing `"https://cdn.plot.ly/plotly-latest.min.js"` with the path to your local plotly.js bundle should do the trick.


> it there an easy way to configure it to output svg file locally without having to symlink report.js file

Configuring this [line](https://gist.github.com/etpinard/ac6402406afcd1ce38a4#file-report-js-L7) should do the trick

> The 3rd option gives the following error

As mentioned above, that option is a work in progress. We'll need to mock a few more things outside the realm of `jsdom` in order to get plotly.js working in the node.js runtime.

**Comment by eugenesvk** [comment]
2. Thank you! I've replaced it with `var outPath = path.join('.', 'out.svg');` and it outputs to the folder I've run my `npm start` even though the `report.js` file is now in the global `karma-custom-reporter` fake module. You might even make it a real module so you don't even need any symlinks ;)))
