### ISSUE TITLE
hovertemplate displays unwanted trace information

### ISSUE THREAD

**Issue by mbejda** [plotly/plotly.js#3621]
Here is a [codesandbox](https://codesandbox.io/s/8xqw51zr18) demonstrating this issue. 
https://codesandbox.io/s/8xqw51zr18
If `hovertemplate` is set to `%{y:,.2f}"` the chart display unwanted trace information on hover. 
<img width="311" alt="Screen Shot 2019-03-10 at 12 07 24 PM" src="https://user-images.githubusercontent.com/5429780/54087783-1667c700-432d-11e9-8b0b-c8be38484b35.png">

To get around that bug I need to append additional information to the `hovertemplate`.
`"%{y:,.2f}<extra></extra>"` so that the hover renders correctly. 

<img width="229" alt="Screen Shot 2019-03-10 at 12 09 46 PM" src="https://user-images.githubusercontent.com/5429780/54087841-c3dada80-432d-11e9-894a-8f3796249a82.png">

**Comment by antoinerg** [comment]
Thank you @mbejda for pointing this out. Appending an empty `extra` tag as you did is exactly how to get rid of the default hover information. I will update the documentation of the `hovertemplate` to mention this as it may not be obvious at all.

**Comment by mbejda** [comment]
I see.. @antoinerg are you sure that is the right approach? If it is go ahead and close this ticket

**Comment by antoinerg** [comment]
@mbejda if you don't mind, I will keep this issue open until we merge PR #3623! The documentation should be updated.
