### ISSUE TITLE
axis labels duplicated in `heatmapgl` with `scrollZoom`

### ISSUE THREAD

**Issue by antoinerg** [plotly/plotly.js#3624]
As shown in this [Codepen](https://codepen.io/antoinerg/pen/Ygryod?editors=111), zooming in and out using the mouse wheel redraws axis labels on top of existing ones:
![Screenshot_2019-03-11_14-56-08](https://user-images.githubusercontent.com/301546/54149999-d6c4dc00-440d-11e9-8fd7-9aa57daaf98b.png)

**Comment by etpinard** [comment]
Related https://github.com/plotly/plotly.js/issues/2436

**Comment by etpinard** [comment]
Worked ok in 1.31.2: https://codepen.io/etpinard/pen/zbLqor?editors=111

**Comment by etpinard** [comment]
Fixed in https://github.com/plotly/plotly.js/pull/3647
