### ISSUE TITLE
Multi traces: Inconsistency between Plotly.plot() and Plotly.extendTraces()

### ISSUE THREAD

**Issue by jlecoeur** [plotly/plotly.js#363]
When working with multiple traces, I can create a plot with two traces like this:
```js
// SAMPLE 1
var data = [
  {
  	x: [ 0, 1, 2 ],
  	y: [ 0, 0, 0 ]
  },
  {
  	x: [ 0, 1, 2 ],
  	y: [ 1, 1, 1 ]
  }];

Plotly.plot(plotDiv, data, { title: 'Multiple traces'});

```

To add three data points to each trace using `Plotly.extendTraces`, the syntax is different:
```js
// SAMPLE 2
var update = {
   x: [[ 3, 4, 5 ],
       [ 3, 4, 5 ]],
   y: [[ 0, 0, 0 ],
       [ 1, 1, 1 ]]
   };

Plotly.extendTraces(plotDiv, update, [0, 1], 50);
```

Instead, I would have expected the following to work, but it does not:
```js
// SAMPLE 3
var update = [
  {
  	x: [ 3, 4, 5 ],
  	y: [ 0, 0, 0 ]
  },
  {
  	x: [ 3, 4, 5 ],
  	y: [ 1, 1, 1 ]
  }];

Plotly.extendTraces(plotDiv, update, [0, 1], 50);  // does not work
```

I think the syntax used in SAMPLE 3 is much more intuitive and consistent with the syntax of SAMPLE 1.
Am I missing something? And if not, would it be possible to allow both syntax for `Plotly.extendTraces`?

**Comment by etpinard** [comment]
The `extendTraces` syntax is consistent with `restyle` where the outer array maps to different traces. 

Although I agree this syntax is cumbersome for updating two data arrays at once, it is unlikely to change any time soon.
