### ISSUE TITLE
bargap in barmode=relative

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#3649]
If I make a multi-trace histogram with `barmode` set to `"relative"`, I would expect the bargap to stay 0, like it does in `"stack"`.

Per @alexcjohnson:

> We should really coerce barmode first, then invoke this logic only for `barmode !== 'group'`. And of course update it when bar `stackgroup` becomes a thing…

**Comment by etpinard** [comment]
@antoinerg would you be interested in taking this one at some point this week?

**Comment by nicolaskruchten** [comment]
This was the link @etpinard dropped into Slack about where in the code it's happening: https://github.com/plotly/plotly.js/blob/05884832cb59c9ec159141b791a4645d09b2d7c3/src/traces/bar/layout_defaults.js#L52
