### ISSUE TITLE
same-position/within-trace bar placement when barmode=group

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#3651]
Consider the following pen: https://codepen.io/nicolaskruchten/pen/RdYWdz?editors=0010

The red and cyan bars aren't being shown because within each trace at the same position, the bars are behaving as if the barmode was "overlay". I believe that the default behaviour should be "relative" instead because it's the only one that always shows all the data!). 

If we can't agree that the current behaviour is a bug, then we should create a new attr that defaults to "overlay" but allows us to set it to "relative" or "stack" as required.

**Comment by etpinard** [comment]
Interestingly under `barmode: 'relative'`, we appear to do the right thing already: https://codepen.io/etpinard/pen/GeeXmQ?editors=0010

This might just be an issue with `barmode: 'group'`.

**Comment by nicolaskruchten** [comment]
Yes, this is exclusively a problem with barmode=group.

**Comment by etpinard** [comment]
@nicolaskruchten I'm starting to think we could merge a "fix" for this bug w/o adding a new attribute.

Here's my first attempt: https://github.com/plotly/plotly.js/compare/unhide-grouped-bars-within-trace - which doesn't break any existing test.

Your codepen now looks like: https://codepen.io/etpinard/pen/YggmQx?editors=0010

![image](https://user-images.githubusercontent.com/6675409/54950357-7ce90980-4f17-11e9-8e26-f13ac10cd7b3.png)


and note that the new logic only has an effect when `barmode: 'group'`, so under `barmode: 'overlay'` we (still) get:

![image](https://user-images.githubusercontent.com/6675409/54950395-8e321600-4f17-11e9-9d79-0f510869285b.png)

**Comment by nicolaskruchten** [comment]
This is pretty much my ideal fix I think, without looking at the implementation
