### ISSUE TITLE
Feature request: Add tickHovertext layout attribute 

### ISSUE THREAD

**Issue by ford04** [plotly/plotly.js#3655]
Hello,

see [this codepen](https://codepen.io/anon/pen/PLdgMp) for some illustration.

Usecase: 
I would like to draw a scatter plot with multiple traces, each trace based on some dates (x-axis) together with their measures (y-axis). Dates are the same for all traces, the measure are divergent. In the graph,  the dates are displayed in form of a chronological ascending number, but there should some possibility to show the date for a particular x-axis number.

Suggestion:
When hovering over some position in the graph, it would be nice, if the `y` values of all traces would be shown with the hovered `x` coordinate and some additional dynamic suffix for `x` (in my case: the date string).  `ticksuffix` doesn't work here since its one static string. If the graph is not hovered, just x axis tick labels (numbers) should be shown. 

There is the `hoverinfo` attribute to add custom text to a coordinate on hover. But I do not want to show the same `x` value for every trace. Therefore, I think some custom x axis `tickHovertext` or similar  attribute in the layout options would be ideal.

// Edit: Added usecase

**Comment by etpinard** [comment]
Thanks for writing in!

That's something I suspect one can do with `hovertemplate` ([example](https://codepen.io/nicolaskruchten/pen/QJgbxo?editors=0010)).

In all fairness, I'm not sure it would be worth adding a new attribute for this.

**Comment by ford04** [comment]
Hmm thats sad. I cannot really estimate, if its a niche thing - just missed something analogous to the traces' `hovertext` and `text` attributes for the x and y axes. `hoverTemplate` seems to be very similar to setting the attribute `hovertext` (?) - my date would have to be repeated and displayed for each trace on hover.

Thanks anyway, I guess, I'll use my workaround then

(by the way, your posted example graph looks neat)

**Comment by etpinard** [comment]
> Hmm thats sad.

So, you're not a fan of `hovertemplate`? Could you tell us why? We're currently thinking about moving all things hover-label-content related to the `hovertemplate` api and potentially dropping `hoverinfo` and `hoverformat` entirely. We would appreciate your feedback.

Thank you!

**Comment by ford04** [comment]
Not that easy to find some documentation about `hovertemplate` up to now ;) .
Having had a look at your example, its seems to be really a promising `hoverinfo` alternative with templating placeholder syntax.
Is it completely scoped to one data point in a trace? Is there something like a positioning/ layout parameter for it? Concerning my feature request, I would like to set a custom position of an hover label scoped to an axis (instead of an x,y point). For example: Show a label at the bottom of the x-axis when hovering over any data point with x=2

**Comment by etpinard** [comment]
This ticket won't directly lead to a PR, so I'll close it.

Thanks very much @ford04 for writing in. Your input will be considered in future development efforts.
