### ISSUE TITLE
scattergl with xaxis date doesn't work on ios

### ISSUE THREAD

**Issue by manthey** [plotly/plotly.js#3660]
If you create a scatter plot with markers and use `scattergl`, set the xaxis to `type: 'date'`, and the markers specify a symbol, the plot is not drawn correctly on iOS.  This happens on an iPad running iOS 12.1.4 (16D57), iPad Pro (2016 - 9.7"), both in Safari and Firefox.

If you don't specify `marker: {symbol: <number>}`, it works.  It works for `scatter` traces, but not `scattergl`.

It works properly on a Windows desktop running Chrome or Firefox.

See here: https://codepen.io/manthey/pen/gEBpQv

```
var data = [{
  x: [2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009],
  y: [5, 4, 3, 2, 1, 0.5, 1, 2, 3, 4],
  mode: 'markers',
  marker: {
    symbol: 2,
    size: 10
  },
	type: 'scattergl'
}, {
  x: [2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009],
  y: [0.5, 1, 2, 3, 4, 5, 4, 3, 2, 1],
  mode: 'markers',
  marker: {
    symbol: 3,
    size: 10
  },
	type: 'scatter'
}];
var layout = {
  width: 1000,
  xaxis: {type: 'date'}
};

Plotly.newPlot('graph', data, layout);
```
Screenshot of the problem (note that diamond symbols are all at the far left of the plot):

![IMG_0001](https://user-images.githubusercontent.com/8781639/54785813-8b74af80-4bfd-11e9-9b2b-4a4f4871b472.PNG)

**Comment by archmoj** [comment]
Thanks for the report @manthey.
It could be replicated only on `iPad` and `iPhone`. 
But on OS X it works OK.
