### ISSUE TITLE
Scatter with animation_frame is plotted out of order

### ISSUE THREAD

**Issue by dvduvix** [plotly/plotly.js#3663]
I tried to plot a scatter with plotly express and I got a very weird behavior
 
![Screenshot from 2019-03-22 19:05:05](https://user-images.githubusercontent.com/1087463/54843761-81be7b00-4cd5-11e9-9d39-f6f5141a38bd.png)
Any thoughts?

**Comment by etpinard** [comment]
I suspect this might be more of a problem for https://github.com/plotly/plotly_express/issues, but maybe I'm wrong. 

Could something try to replicate in JS to help us debug?

**Comment by dvduvix** [comment]
@etpinard Oh, good point, I posted it there, thank you!

**Comment by etpinard** [comment]
Closing (for now, will reopen if this turns out to be a plotly.js bug).
