### ISSUE TITLE
Plotly.restyle causes mapbox to reset center

### ISSUE THREAD

**Issue by zoohair** [plotly/plotly.js#3683]
If a user pans/zooms a mapbox map, and Plotly.restyle is invoked, the map resets the initial origin and zoom.

This behaviour doesn't seem to happen with other graphs (barcharts or scatter)

**Comment by etpinard** [comment]
Could you please share a reproducible codepen/jsFiddle/jsBin to help us debug?

Thanks for reporting!

**Comment by zoohair** [comment]
Here is one case of it happening and how it affects mapbox.flyTo()

https://codepen.io/anon/pen/jJooVo

My understanding of plotly.js is limited, but I've narrowed it to plots.supplydefaults being invoked which resets the mapbox.center and mapbox.zoom. I've managed to fix it in some cases by setting
`plot._fullLayout._skipDefaults = true` , but that sometimes breaks other things

Thanks for looking into it :)

**Comment by etpinard** [comment]
Ha I see, you're combining plotly.js function calls with mapbox-gl function calls. Nice! 

In brief, plotly.js looks into `plot.layout.mapbox` for its mapbox state. As `flyBy` doesn't know anything about `plot.layout.mapbox`, you'll have to update `plot.layout.mapbox` yourself to get your example to work correctly like in https://codepen.io/etpinard/pen/pBzwaj

**Comment by zoohair** [comment]
Thanks, that fixes the issue. I managed to make it work with your suggestion.

I think the only other problem I have is that double clicking resets the state to the original center/zoom, but I think that's already captured in another issue: https://github.com/plotly/plotly.js/issues/2718
