### ISSUE TITLE
Exponentformat SI and type log with ticksuffix results in wrong minor tick markings

### ISSUE THREAD

**Issue by dries007** [plotly/plotly.js#3689]
I'm plotting a benchmark frequency graph, where the Y axis is (normally) a log scale in the 100M to 1G range.
I'm doing this by using the following options:
```json
{
  "yaxis": {
    "exponentformat": "SI",
    "ticksuffix": "Hz",
    "type": "log",
  },
}
```

**Example: https://jsfiddle.net/sk5v0gx6/**

This results when there is at least 1 "major" tick:
![image](https://user-images.githubusercontent.com/1346725/55148646-e4d26680-5148-11e9-8afd-86eb57fa2347.png)

If there is only "minor" ticks, this is the results: (What I'd consider the correct behaviour.)
![image](https://user-images.githubusercontent.com/1346725/55148709-07647f80-5149-11e9-9e5f-294d5f4c03a0.png)

As you can see the first example omits the 'exponent format', but it does put in the suffix. I think this results in a confusing graph.

I think there are a number of possible fixes for this:

1. Put the SI prefix in the minor tick, along with actual number (not just the 1-9) (My personal preference.)
2. Allow an option to only specify suffixes on major ticks. Maybe via `showticksuffix`. This would still make the graph less readable IMO, but it would at least make it clear the graph doesn't jump from 1GHz to 9Hz.

If this is something that would get accepted as a PR, I'm willing to try and implement it.

**Comment by etpinard** [comment]
Hi @dries007 - thanks for writing in and sorry for the belated reply.

A lot of users have been noticing less-than-ideal behavior in our minor ticks on log axes, for example: https://github.com/plotly/plotly.js/issues/3679, As we don't currently support minor tick settings (cc https://github.com/plotly/plotly.js/issues/903), it's still not obvious to me how we can make everyone happy and stay consistent with our other tick settings at the moment.

I _think_ both your "possible fixes" items could be solved issue up-coming (tracked in https://github.com/plotly/plotly.js/issues/903) minor ticks settings:

- For 1., I'm thinking `minortick.mode` with values `'step'` (like log axes currently) and `'actual'` (which would correspond to what you're suggesting)

- For 2., adding something like `showminorticksuffix` (similar to `showticksuffix`) should be sufficient.

**Comment by etpinard** [comment]
But I have to say, you're making a good point that on your https://jsfiddle.net/sk5v0gx6/, we probably shouldn't be showing the `Hz` ticksuffix on those minor ticks. 

I found https://github.com/plotly/plotly.js/issues/3250 which appears equivalent to your item 1. and called it a bug (when `ticksuffix` is set, assuming `ticksuffix` corresponds to a unit, I guess :thinking: ).

**Comment by archmoj** [comment]
Closing via #4064.
