### ISSUE TITLE
Disabling draggable columns in tables

### ISSUE THREAD

**Issue by AbdealiJK** [plotly/plotly.js#3695]
I have a table in plotly and I am trying to disable the drag and drop - because if a user by mistake reorders the columns - it doesn't make sense.
We're trying to show top 10 correlated features in order - so our headers are "Item 1", "Item 2", "item 3", and if people can reorder the columns - it gets very confusing :D

I tried setting [staticplot=True](https://github.com/plotly/plotly.js/blob/bed30cd0b242a8552d6d29f57a6a6bc206f16b2c/src/plot_api/plot_config.js#L24) / [editable=False](https://github.com/plotly/plotly.js/blob/bed30cd0b242a8552d6d29f57a6a6bc206f16b2c/src/plot_api/plot_config.js#L42) / [responsive=False](https://github.com/plotly/plotly.js/blob/bed30cd0b242a8552d6d29f57a6a6bc206f16b2c/src/plot_api/plot_config.js#L120) / [showAxisDragHandles=False](https://github.com/plotly/plotly.js/blob/bed30cd0b242a8552d6d29f57a6a6bc206f16b2c/src/plot_api/plot_config.js#L176) in the configs, but that didnt remove the dragging.

**Comment by etpinard** [comment]
`staticPlot: true` is what you're looking for, and it seems to work ok: https://codepen.io/etpinard/pen/EJYjRj

**Comment by AbdealiJK** [comment]
@etpinard Thanks, seems like I tested it in a hurry.
When I hover on the columns' header it still gives the move cursor.
Should I close the issue or keep it to fix that cursor ?
