### ISSUE TITLE
Is 3-D scatter plot supported in streaming?

### ISSUE THREAD

**Issue by mfkenson** [plotly/plotly.js#370]
I tried the regular scatter plot. (python version)
[https://plot.ly/python/streaming-tutorial/](url)

When I modify 
`
trace1 = Scatter(
        x=[],
        y=[],
        stream=dict(token='my_stream_id')
    )
`

to
`
trace1 = Scatter3d(
        x=[],
        y=[],
        z=[],
        stream=dict(token='my_stream_id')
    )
`

and 

`s.write(dict(x=1, y=2))`

to

`s.write(dict(x=1, y=2, z=3))`

There is an error saying scatter only accepts x and y..

**Comment by etpinard** [comment]
I think you're `write` call should be:

```py
s.write(dict(type='scatter3d', x=1, y=2, z=3))
```

If that doesn't work, please ask fill in a bug report on https://github.com/plotly/plotly.py
