### ISSUE TITLE
Table: Creating frozen columns (similar to header - but for columns)

### ISSUE THREAD

**Issue by AbdealiJK** [plotly/plotly.js#3705]
While Plotly has the ability to create a "header", it would be nice to also create "frozen-columns" or something similar:
<img width="659" alt="Screen Shot 2019-04-01 at 10 16 12 AM" src="https://user-images.githubusercontent.com/2200743/55304087-5c650600-5467-11e9-88ae-31843e7b0de7.png">

Excel has the concept of frozen columns. Pandas (in python) uses indexes.

Note that while a very similar thing could be done by applying `<b>` for every `cells.values` which needs this, it gets difficult to manage the empty cells in the first row, and also the background gets a bit difficult to manage.

Example comparing a HTML version and plotly version:
https://codepen.io/AbdealiJK/pen/OGJooV

**Comment by etpinard** [comment]
Merged into https://github.com/plotly/plotly.js/issues/2056
