### ISSUE TITLE
Add sunburst and isosurface to partial bundle info

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#3718]
I don't see either listed on https://github.com/plotly/plotly.js/tree/master/dist#partial-bundles

**Comment by etpinard** [comment]
That's because they're not part of any partial bundles.

- `isosurface` should be part of `gl3d` (oops, we'll fix that in `1.47.0`)
- about `sunburst`, I'm not sure that one should be part of a partial bundle. What do you think?

**Comment by cpsievert** [comment]
I guess cartesian might be nice (pie is already in there)? No strong preference though, just want to make sure I have the right list.

**Comment by etpinard** [comment]
Yeah, you could argue `pie` shouldn't really be part of `cartesian`.

**Comment by alexcjohnson** [comment]
I'm guessing `pie` is there because all the other bundles should be "basic plus something"

Perhaps we should have an `svg` bundle, that includes all svg types and omits all gl?

**Comment by etpinard** [comment]
Can I close this one? Or does anyone really _really_ wants `sunburst` as part of `plotly-cartesian`?

**Comment by cpsievert** [comment]
No strong feelings, feel free to close.

**Comment by alainaa** [comment]
Hello there, bonjour!
I'm just looking for the sunburst trace in the partial bundles but I can't find it in any of them. Would it be possible to include it in plotly-cartesian, as you were discussing above? That would be perfect for me, as the dashboard I'm buiding is based on scatter + heatmap + sunburst.
By the way, congrats for the last update 4.9.2, with brilliant improvements in the sunburst trace, which were key in the final decision of including it!
Best regards,
Alain.
