### ISSUE TITLE
Bar plots are drawn incorrectly when null values are present

### ISSUE THREAD

**Issue by aburato** [plotly/plotly.js#372]
Hi guys, when using bar plots it seems that the bar width gets calculated based on the number of non-null Y values in the data set, while all the x values are added to the axis. This leads to a messed up display.

See: http://codepen.io/aleburato/pen/yOomYa?editors=0010

Ciao!

**Comment by aburato** [comment]
After further investigation, the problem only shows up when the second value of the dataset is null.

Pen updated.

**Comment by mdtusz** [comment]
Sorry we haven't triaged this until now! Definitely a bug (and a somewhat strange one as well)!

**Comment by etpinard** [comment]
fixed in https://github.com/seibs/plotly.js/commit/dd2251d7f1e61a62e10cd1107c107c3a0fea23ae
