### ISSUE TITLE
Hoverlabel contents alignment

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#3726]
We should add an attr to control hoverlabel contents alignment, mostly to be able to force right-alignment even when the hoverlabel is on the left.

**Comment by etpinard** [comment]
Related: https://github.com/plotly/plotly.js/issues/3010

**Comment by nicolaskruchten** [comment]
Well, what I'm proposing is much narrower than #3010 but yes that would be nice too :)

Can we get this attr slotted in for 1.47 ? with default = `auto` encompassing the current behaviour ?

**Comment by etpinard** [comment]
By _alignment_ here, you mean:

- the alignment of the text content inside the hover label with respect the hover label container? or
- the alignment of the hover label with respect to its corresponding data point(s)?

**Comment by nicolaskruchten** [comment]
Text within box

**Comment by nicolaskruchten** [comment]
related #260
