### ISSUE TITLE
legend.marker.sizemode

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#3727]
We should add `legend.marker.sizemode = data (default) | constant`

related: #3602

**Comment by nicolaskruchten** [comment]
related: #2745 and #2080

**Comment by etpinard** [comment]
Full list of related issues:

- https://github.com/plotly/plotly.js/issues/2745
- https://github.com/plotly/plotly.js/issues/2967
- https://github.com/plotly/plotly.js/issues/2744
- https://github.com/plotly/plotly.js/issues/2080
- https://github.com/plotly/plotly.js/issues/1701
- https://github.com/plotly/plotly.js/issues/1560
- https://github.com/plotly/plotly.js/issues/98
