### ISSUE TITLE
scrollZoom is laggy with automargin+nTicks+title

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#3729]
https://codepen.io/cpsievert/pen/ROaVEE

Discovered in https://github.com/ropensci/plotly/issues/1509

**Comment by etpinard** [comment]
Probably not worth tackling before we take a stab at https://github.com/plotly/plotly.js/issues/2704

**Comment by etpinard** [comment]
Merging into https://github.com/plotly/plotly.js/issues/2704

**Comment by hpeiyan** [comment]
@etpinard Hi, etpinard. I have same issues in scrollZoom after setting `fig.update_layout(margin=dict(l=0, r=0, t=0, b=0))
`. Help me. Thank you veru much.
