### ISSUE TITLE
Stricter valType of some config attrs

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#3731]
Many config attributes (e.g., `modeBarButtonsToRemove`, `modeBarButtonsToAdd`, etc) have `valType` of `'any'`, but they don't seem to accept strings. Are they `'any'` because they accept arrays and objects? If that's the case, maybe the config could add some more information, like `stringOK = FALSE`?

**Comment by etpinard** [comment]
Hmm, making `modeBarButtonsToRemove` and `modeBarButtonsToAdd` have a more strict `valType` in the schema won't do anything for plotly.js as we don't [coerce](https://github.com/plotly/plotly.js/blob/master/src/lib/coerce.js) config options (unlike data/layout attributes). 

I'd recommend handling `modeBarButtonsToRemove` and `modeBarButtonsToAdd` as special cases in the R api.

**Comment by etpinard** [comment]
@cpsievert ok if I close this one? I doubt this issue will translate into any plotly.js work.

**Comment by cpsievert** [comment]
yep, no prob
