### ISSUE TITLE
Bar attributes shouldn't have anim:true in the schema

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#3737]
Perhaps this is expected, but I found it surprising since `bar`'s y atttribute has a `anim: true` flag in this config (this means it should work with the react transitioning API, right?)

https://codepen.io/cpsievert/pen/axZZeP

**Comment by etpinard** [comment]
Duplicate of https://github.com/plotly/plotly.js/issues/1019

**Comment by etpinard** [comment]
Ha oops. Sorry @cpsievert I misread the issue. I thought we were asking whether bar traces can be smoothly transitioned. The answer is no.

But you're right, `anim: true` for `x`, `y` etc should be there in the `bar` trace schema. Have you noticed `anim: true` showing up anywhere else?

**Comment by cpsievert** [comment]
No, but I haven't really been playing around with `Plotly.react()` much at all yet
