### ISSUE TITLE
Mapbox doesn't immediately respond to scrollZoom: false

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#3738]
https://codepen.io/alexcjohnson/pen/mgERKb?editors=0010

On `newPlot` with `config: {scrollZoom: false}` a mapbox plot still responds to scroll zoom.
After `react` with the same config, it no longer responds.

This changed with v1.44.0, presumably due to #3422 

@nicolaskruchten @michaelbabyn there's a separate issue in DCC, that the default `config` duplicates plotly.js's defaults - or tries to, but it's not up to date. I'll make an issue over there as well.

**Comment by etpinard** [comment]
Thanks for the report. I'll get this fixed before releasing 1.47.0
