### ISSUE TITLE
Is the plotly js cdn gzipped?

### ISSUE THREAD

**Issue by bxlxux** [plotly/plotly.js#374]
It doesn't seem as though the cdn has gzip enabled for the plotly-latest.min.js file. It comes through at the full 1.1Mb versus 460Kb when I host it on a staging server with gzip enabled.

I posted this on the forum as well:
[http://community.plot.ly/t/is-the-plotly-js-cdn-gzipped/729](url)

**Comment by etpinard** [comment]
Thanks. I deployed a fix to our CDN provider.

No need to duplicate the forum post.

**Comment by uok** [comment]
It seems that https://cdn.plot.ly/plotly-latest.min.js is currently not using gzip!

**Comment by etpinard** [comment]
@uok what makes you say that?

![image](https://user-images.githubusercontent.com/6675409/27441108-91313e7a-573a-11e7-9133-b82d4bad385a.png)

**Comment by uok** [comment]
sorry about that, all ok, I deleted my comment

**Comment by uok** [comment]
@etpinard sorry about that, all ok, I deleted my comment - you can delete your screenshot

**Comment by uok** [comment]
@etpinard sorry about that, all ok, I deleted my comment - you can delete your screenshot
