### ISSUE TITLE
box/violin hoverinfo breaks when another trace is layered on top

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#3747]
https://codepen.io/cpsievert/pen/YMpYyg

**Comment by etpinard** [comment]
What's the desired behavior here?

**Comment by cpsievert** [comment]
When the box hover is triggered it should show the 5-number summary as opposed to just the median 

(I realize this is a pretty weird corner-case)

**Comment by etpinard** [comment]
Right, when there's a scatter trace alongside a `box` trace we no longer consider the graph to be _horizontal_, to the default `layout.hovermode` is `'x'`.

Setting `hovermode: 'y'` gives: https://codepen.io/etpinard/pen/MRbrEO which I think is what you're looking for.

**Comment by etpinard** [comment]
@cpsievert ok if I close this?

Note that we're planning on switching the `hovermode` default to `'closest'` in v2, so stuff this and [this](https://github.com/plotly/plotly.js/issues/778) won't happen.

**Comment by cpsievert** [comment]
ok yea
