### ISSUE TITLE
Add way to configure trace module ordering within subplot

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#3748]
For example, although the scatter trace appears first, it is drawn on top of the box-plot https://codepen.io/cpsievert/pen/yrVpeb

Needed for `ggplotly()` parity https://github.com/ropensci/plotly/issues/866

**Comment by etpinard** [comment]
Yep, that's how things work unfortunately for now.

Here's our ordering:

https://github.com/plotly/plotly.js/blob/e11130076a5888aa69ac6289277d856238dc85f5/src/plots/cartesian/constants.js#L65-L74

I guess we could add a list-like attribute to configure the module ordering, or better yet honor the ordering found in `gd.data` (but that would be a breaking change).

**Comment by cpsievert** [comment]
> or better yet honor the ordering found in `gd.data`

That'd be awesome 👍 

Perhaps worth adding to #420?

**Comment by alexcjohnson** [comment]
> or better yet honor the ordering found in `gd.data`

Not sure this is a good idea. For one there are cross-trace interactions that sometimes make this impossible (or at least nonsensical) - mostly involving filled `scatter*` but stacked bar would also do weird things in certain cases.

I also worry people would accidentally lose point-like traces behind area-like traces, and that in some contexts like chart studio it could be hard to get the order you want. 

So I'd prefer we keep the current behavior but add a way to stack it as desired. Can we just add something like a `zindex` attribute - where any matching values keep the current behavior but different values (within a subplot) stack by index?

**Comment by cpsievert** [comment]
> Can we just add something like a zindex attribute 

I could likely manage with that

**Comment by emilykl** [comment]
Addressed by #6918
