### ISSUE TITLE
Scattergl markers are not rendered but you can hover over them

### ISSUE THREAD

**Issue by rhamner** [plotly/plotly.js#3751]
The behavior here is similar to a previous bug I hit ([issue 2999](https://github.com/plotly/plotly.js/issues/2999)) but that bug's reproducing case no longer reproduces for me so I think this might be the same behavior from a different issue.

If I plot a large number of markers with scattergl, it works fine. If I then plot a subset, it does not. The transition point seems to be ~100k markers. That is, once I plot more than ~100k, plotting below ~100k shows the issue.

Here is a really simple reproducing example:

[https://codepen.io/rhamner/pen/XQpRbx](https://codepen.io/rhamner/pen/XQpRbx)

If I use 'scatter' instead of 'scattergl' it works fine, but our actual use case is much larger than 100k points so scatter doesn't work.

The browser generates hundreds of these warnings:

[.WebGL-00000080DCBEE1F0]GL ERROR :GL_INVALID_OPERATION : glDrawArrays: attempt to access out of range vertices in attribute 0

I'm using chrome Version 73.0.3683.103 (Official Build) (64-bit). This specific sample code does not show the issue in firefox, but I do hit the issue in firefox with our actual code and I'm not sure why.

**Comment by wweitzel** [comment]
I am having an issue similar to this. The points simply do not show up when using scattergl, but show up just fine when using scatter.

Here is a simple codepen demonstrating this. https://codepen.io/wweitzel/pen/MRJVYd

The first plot is with scattergl and the second is with just scatter.

**Comment by etpinard** [comment]
@wweitzel that sounds like a very different problem. I'm seeing 

![image](https://user-images.githubusercontent.com/6675409/55824921-d97d2480-5ad2-11e9-8fc4-0bfda3fda66b.png)

from your https://codepen.io/wweitzel/pen/MRJVYd

----

Something must be up with your WebGL support. Can you try to answer the following questions:

- do you see any errors in your browser console?
- which browser are you using?
- which OS are you on?

thank you.

**Comment by wweitzel** [comment]
![image](https://user-images.githubusercontent.com/17417149/55825080-c7ac7900-5af4-11e9-8835-ca769019b433.png)

Above image is the console error

This is on Chrome version 73.0.3683.103 (Official Build) (64-bit) on windows 10, 64 bit

**Comment by etpinard** [comment]
That's what I thought. This isn't at all related to this issue. 

See if you're setup supports WebGL by going on https://get.webgl.org/ . If you see

![image](https://user-images.githubusercontent.com/6675409/55825434-fd8d3580-5ad3-11e9-9ebd-bc04133827e7.png)

than please open a new ticket. Thanks for reporting.

**Comment by wweitzel** [comment]
You are right. Seems my setup does not support WebGL. Sorry for the misunderstanding.

**Comment by etpinard** [comment]
cc https://github.com/plotly/plotly.js/issues/2334

**Comment by etpinard** [comment]
cc https://github.com/plotly/plotly.js/issues/3405

**Comment by archmoj** [comment]
This issue appears to be (going to be) fixed (in the next release v.1.49.0) after bumping `regl-scatter@3.1.5` which uses `point-cluster@3.1.5` in https://github.com/plotly/plotly.js/pull/3904.
[Codepen](https://codepen.io/MojtabaSamimi/pen/VJddPx)

**Comment by etpinard** [comment]
> after bumping `regl-scatter@3.1.5` which uses `point-cluster@3.1.5` in #3904.

I doubt it. We shouldn't be calling `point-cluster` from `regl-scatter`. Our call to `point-cluster` is here:

https://github.com/plotly/plotly.js/blob/d75e956db2fffe23bcf818c3ca9eb8952f68eab2/src/traces/scattergl/calc.js#L67

**Comment by archmoj** [comment]
But that line is not called in the codepen demonstrating the issue.

**Comment by etpinard** [comment]
> But that line is not called in the codepen demonstrating the issue.

Right, because your https://codepen.io/MojtabaSamimi/pen/VJddPx has (only) 1e4 points. See https://codepen.io/etpinard/pen/EBRpqz which has 1e5 points - and appear buggy still.

**Comment by archmoj** [comment]
@rhamner 
A candidate fix illustrated in this [demo](https://codepen.io/MojtabaSamimi/pen/jOOGjyb).

**Comment by archmoj** [comment]
Closed by #4323 .

**Comment by rhamner** [comment]
Thanks
