### ISSUE TITLE
Hoverboxes get splitted when hovering on gl3d on qtwebengine since 1.45

### ISSUE THREAD

**Issue by emimoun** [plotly/plotly.js#3752]
Hi all, I am developing a GUI using Pyside2 and plotly inside a qtwebengine widget. Up to 1.45 it was fine but starting this version the hover plots are sometimes showing some weird behaviour, getting split in several parts. This is transient and comes and goes when the mouse is moved.
I must say I was not able to reproduce on a standard browser like Chrome, but I attach this simple basic example of browser in python which demonstrates the issue. I also attach picture of the issue as seen on my screen. I understand this is not a bug per say as it is not universal, but it used to work before 1.45 so I thought it might ring a bell for someone regarding the reason such a thing could happen. Thanks.
[test.zip](https://github.com/plotly/plotly.js/files/3059745/test.zip)

![test1](https://user-images.githubusercontent.com/38953797/55813045-65e81100-5aec-11e9-9313-056eb5b51af7.png)
![test2](https://user-images.githubusercontent.com/38953797/55813048-65e81100-5aec-11e9-83ef-85613b15e5f4.png)

**Comment by archmoj** [comment]
@emimoun what about other 3d traces? Does that happen if you use `scatter3d` instead of `mesh3d`?

**Comment by emimoun** [comment]
Thank you for your answer. I just checked and it does the exact same thing.
![test3](https://user-images.githubusercontent.com/38953797/55877410-37287400-5b9a-11e9-8d1d-7469ac2a2030.png)

**Comment by archmoj** [comment]
@emimoun Could you please force `config.plotGlPixelRatio` to equal 1 and see if that may help?

**Comment by emimoun** [comment]
It seems to work, thank you so much! Out of curiosity, how does this parameter relates to the issue?

**Comment by archmoj** [comment]
I am wondering that could be related to your browser not down-scaling the webgl render after rendering with higher `pixelRatio` resolution.
@emimoun Could you please compare the graph width/height & image quality before and after 1.45 with/without tweaking the config?
Thank you in advance.

**Comment by emimoun** [comment]
For all 4 cases (1.44/1.47, and with/without setting the pixelRatio) I obtain no distinguishable difference on my example (except for the initial problem, of course). Same size and quality. The 1.47 version without the option seems noticeably slower to load, though.

**Comment by archmoj** [comment]
@emimoun Could you please try replicating the issue on a codepen like [this one](https://codepen.io/MojtabaSamimi/pen/yrMxEV?editors=0010) or using its data?
Also if possible give more info about the operating system.
Thanks.

**Comment by emimoun** [comment]
You can try [this](https://codepen.io/anon/pen/VNbPMm), but the problem does not show on Chrome for example, only on QtWebEngine based browser such as this one named [Falkon](https://www.falkon.org/). I can perfectly understand if you feel it is a bug from QtWebEngine and not Plotly. I am on Windows 10.

**Comment by archmoj** [comment]
@emimoun do you use `"config":{plotGlPixelRatio:8}` in your app similar to the example you provided?

**Comment by emimoun** [comment]
Sorry no that was to emphasize the issue, which does happen already when no plotGLPixelRatio option is specified, but for less frequent mouse positions. Only setting it to 1 makes it go away completely.

**Comment by archmoj** [comment]
And what about using `plotGlPixelRatio:2`?

**Comment by archmoj** [comment]
@emimoun I was not able to replicate this on Ubuntu+Falkon.
@antoinerg would you mind testing [this codepen](https://codepen.io/MojtabaSamimi/pen/YMQgLq) on Windows+[Falkon](https://www.falkon.org/)?
Thanks!

**Comment by etpinard** [comment]
> @antoinerg would you mind testing [this codepen](https://codepen.io/MojtabaSamimi/pen/YMQgLq) on Windows+[Falkon](https://www.falkon.org/)?

@antoinerg no longer devs on Windows. We have (at least we used to) a Windows laptop at the office. Ask Ben, if you can't find it.

**Comment by archmoj** [comment]
@emimoun Not 100% sure if this may help fix the issue in your app.
Anyway would you mind trying [this codepen](https://codepen.io/MojtabaSamimi/pen/jRLqbE) or one these two: 
https://33061-45646037-gh.circle-artifacts.com/0/dist/plotly.min.js
https://33061-45646037-gh.circle-artifacts.com/0/dist/plotly.js

**Comment by emimoun** [comment]
@archmoj Thank you, however, it does not help. It is worth noting that the problem is very subtle at `plotGlPixelRatio:2`, with only few and very transient glitches. It is made more visible and problematic by increasing to 4 or more. Honestly, setting `plotGlPixelRatio:1` works for me, it worth investigating only if you fear this is sign of some underlying issue which can cause trouble in the future.
