### ISSUE TITLE
Uncaught (in promise) TypeError: doneFnCompleted is not a function

### ISSUE THREAD

**Issue by lavor** [plotly/plotly.js#3754]
Hi, the release version 1.47.0 adds call of method `doneFnCompleted`:
https://github.com/plotly/plotly.js/commit/627fd74d07bdcfb4407c9241e5f00d92e09ab293#diff-8c5d8f688f2bb41a18d35397e5f58864R290

This method is initialized only in sankey's base_plot.js:
https://github.com/plotly/plotly.js/commit/627fd74d07bdcfb4407c9241e5f00d92e09ab293#diff-2d7d5b2875d00ef73d8c35008560ea17R90

Otherwise  `doneFnCompleted` it is not initialized and a browser reports an error whenever the Box select or the Lasso select from toolbar is used:
Uncaught (in promise) TypeError: doneFnCompleted is not a function

**Comment by etpinard** [comment]
Thanks very much for the report :+1:
