### ISSUE TITLE
`textposition: auto` not used for log axis

### ISSUE THREAD

**Issue by drkane** [plotly/plotly.js#3767]
I've found an issue with `textposition: auto` when creating a horizontal bar chart. 

When a linear axis is used, the text is correctly adjusted to fit into the available bar (see the first "monkeys" bar):
![image](https://user-images.githubusercontent.com/1049910/56099822-f453fc80-5f09-11e9-8100-6030c709ea24.png)

But for a log axis the text is not adjusted:
![image](https://user-images.githubusercontent.com/1049910/56099833-1fd6e700-5f0a-11e9-814f-09cebb9d94db.png)

[JSFiddle example](https://jsfiddle.net/drkane/dc4ptxwb/3/)

```javascript
var data = [
  {
    y: ['giraffes', 'orangutans', 'monkeys'],
    text: ['giraffes', 'orangutans', 'monkeys'],
    x: [20, 14, 1],
    type: 'bar',
    orientation: 'h',
    textposition: 'auto',
  }
];

Plotly.newPlot('myDiv', data);
Plotly.newPlot('myDivLog', data, {
	xaxis: {
    type: 'log'
  }
});
```

**Comment by etpinard** [comment]
Thanks for the report!

This issue appears similar to https://github.com/plotly/plotly.js/issues/3373 

Looks like https://github.com/plotly/plotly.js/pull/3762 fixed the behavior (on master, not released yet) for vertical bars:

```js
var data = [
  {
    x: ['giraffes', 'orangutans', 'monkeys'],
    text: ['giraffes', 'orangutans', 'monkeys'],
    y: [20, 14, 1],
    type: 'bar',
    textposition: 'auto',
  }
];

Plotly.newPlot('graph', data, {
	yaxis: { type: 'log' }
});
```

now renders as:

![image](https://user-images.githubusercontent.com/6675409/56136342-98689280-5f60-11e9-8825-954377bb78a7.png)

but something is still up for horizontal bars.

**Comment by drkane** [comment]
@etpinard - thanks for looking at this and fixing so quickly! 👍
