### ISSUE TITLE
Matching date axes don't autoscale correctly

### ISSUE THREAD

**Issue by Toumetis** [plotly/plotly.js#3770]
doAutoRangeAndConstraints attempts to take the min/max of the string representation, breaking autorange / reset axis.

https://codepen.io/Toumetis/pen/eoGogx

My fix is here, please review. https://github.com/Toumetis/plotly.js/commit/dc9b25ef80e988e3d6111fb6ddb28583f28f73b9

**Comment by etpinard** [comment]
Thanks very much for the report!

At first glance, your commit looks right. Would you mind making a PR? For bonus point, you could try adding a data/layout mock to lock down the behavior (see https://github.com/plotly/plotly.js/tree/master/test/image#c-generate-or-update-existing-baseline-image for more info)
