### ISSUE TITLE
Scatter.hoverlabel.align = "left" overflows text for labels that would otherwise have been center-aligned

### ISSUE THREAD

**Issue by zig1000** [plotly/plotly.js#3774]
When a scatterplot with multiline hovertexts is left without alignment set, the auto-alignment will set some nodes to have center-aligned text, as expected.

However, when `"hoverlabel": {"align": "left"}` is added, those same nodes will have the text overflowing to the left of the hoverbox. A couple such sample nodes are highlighted in pink in the attached example. Unbugged example without hoverlabel.align set is also included.

Bugged (with align): https://jsfiddle.net/81zjvhxa/
Unbugged (without align): https://jsfiddle.net/meor6qjg/

**Comment by etpinard** [comment]
Thanks for reporting!
