### ISSUE TITLE
Waterfall textinfo

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#3777]
I think we'll need some `textinfo` for waterfalls, so as to be able to show the total value as text.

**Comment by archmoj** [comment]
Here is [a prototype](https://codepen.io/MojtabaSamimi/pen/pBpZry?editors=0010) by reusing some of the logic in `pie`.

**Comment by nicolaskruchten** [comment]
Pretty cool! What are the available flags? Can I show value+initial or something? If so, what does that end up looking like?

**Comment by archmoj** [comment]
@nicolaskruchten the early prototype used to apply the options identical to `pie`.
However as @etpinard pointed out https://github.com/plotly/plotly.js/pull/3782#issuecomment-484089320 we may have different set of flags for waterfalls.
What about this list? 
[`label`, `text`, `sum value`, `diff value`, `diff percent`, `sum percent`]

**Comment by nicolaskruchten** [comment]
what would those look like? one per line?

**Comment by nicolaskruchten** [comment]
I would do:

* `value` (the delta value!), `initial`, `final`, and `text` (which is whatever was provided in the `text` attr)
* I would display these one-per-line

**Comment by archmoj** [comment]
I like `delta` over `value`. Value is a bit confusing considering base, etc. 
Here is an updated [codepen](https://codepen.io/MojtabaSamimi/pen/WWMmEq?editors=0010).
