### ISSUE TITLE
USA-states incorrectly drawn as foreign regions in high resolution choropleth

### ISSUE THREAD

**Issue by Thlayli** [plotly/plotly.js#3779]
I’ve been working on a choropleth (through plotly.py originally) and things had been going fine at 110 resolution, but I decided to switch to 50 and things got weird. The problem I’m seeing is that I’m providing a list of ‘USA-states’ and it’s deciding to map some of them to similarly named world states, e.g. WA (Washington) is mapped on Western Australia and PA (Pennsylvania) is mapped on Pará, Brazil. This problem does not occur at all at the lower 110 resolution where WA is correctly mapped to the USA state as requested.

I’d actually like to take advantage of this hidden feature for other projects but I can only get it to happen through this glitch, not through choice. I’ve tried various other formats like "WA, AUS" or "AUS-WA" and both "USA-states" and "countries" formats. The only thing that causes Western Australia to be drawn is putting “WA” and “USA-states” and resolution=50.

https://jsfiddle.net/Thlayli/3jza9sov/
or
https://plot.ly/~thlayli/22/number-of-artists-by-country-or-region/#/ 1

**Comment by etpinard** [comment]
Thanks for reporting.

**Comment by etpinard** [comment]
Ha, that's a shame 

```
var gd = document.querySelector('.js-plotly-plot')
gd._fullLayout.geo._subplot.topojson.objects.subunits.geometries.map(g => g.id)
```

has duplicate ids in it:

![image](https://user-images.githubusercontent.com/6675409/56251808-e4abf380-6082-11e9-997e-518e6e782d98.png)

Looks like we'll have to patch: https://github.com/etpinard/sane-topojson

-----

That said, I wonder if some users out there are using `locationmode: 'USA-states` to show (incorrectly) Brazil, Australia and Canada sub-divisions?

**Comment by Thlayli** [comment]
I'd do it if it was predictable. :D

**Comment by etpinard** [comment]
> I'd do it if it was predictable.

Do _what_ exactly? You mean you would use `locationmode: 'USA-states'` to draw e.g. Brazil sub-division choropleths? That's sounds odd. We should probably add a new `locationmode` value (e.g. `'subdivisons'`) for choropleths of the likes.

**Comment by Thlayli** [comment]
Yeah, I meant I would plot non-USA regions on a world map if I could specify both country and region code.
