### ISSUE TITLE
use require to plot in order not to harm other require modules.

### ISSUE THREAD

**Issue by cailiang9** [plotly/plotly.js#379]
So we can write code this way: require(['plotly.js'], (Plotly)-> ...)

**Comment by etpinard** [comment]
can you elaborate?

**Comment by cailiang9** [comment]
When using with jupyter notebook (offline mode), it will cause `require/define not defined' issue. `require/define' is commonly used in js to import a module.

**Comment by cailiang9** [comment]
Sorry. It seems I was using plotly.py with plotly.js 1.5.0. The issue seems resolved after 1.8.0.
