### ISSUE TITLE
Inconsistent parcoords behaviour when data is outside range

### ISSUE THREAD

**Issue by slishak** [plotly/plotly.js#3794]
Example codepen: https://codepen.io/anon/pen/xejYmv?editors=1010

In this example, dimension `C` has an out-of-range point at `C=4`. On page load, this line is shown in grey (I'm not sure if this should be the case, as it should be selectable in dimensions `A` and `B`):
![image](https://user-images.githubusercontent.com/12515343/56428087-6dfb3a00-62be-11e9-9136-7d594af68d4d.png)

Attempting to select the line on dimension `B` confirms that it is not selectable:
![image](https://user-images.githubusercontent.com/12515343/56428125-92efad00-62be-11e9-9514-c5b503b63e0f.png)

However, when clearing the constraint range by clicking on the `B` axis, the line disappears completely:
![image](https://user-images.githubusercontent.com/12515343/56428148-a69b1380-62be-11e9-9c5d-40df45d467a6.png)

And from that point onwards, it reappears whenever a constraint range is applied, and disappears again when they are cleared.

In my opinion, the default behaviour should be for lines going out of the range of one of the coordinates to not have any special treatment. This is because you might have a large number of coordinates, and points can have invalid data for one dimension while still being valid for all of the rest of the dimensions (and the status of this point as an outlier compared to the expected range could even make this point more interesting to the user, so shouldn't be hidden).

**Comment by etpinard** [comment]
Thanks for reporting!
