### ISSUE TITLE
Rangeslider and dragmode selection not in sync

### ISSUE THREAD

**Issue by mbkupfer** [plotly/plotly.js#3795]
Bug: Dragmode selections are offset when interacting with the rangeslider. See below screenshot for an example of what I'm referring to. 

![image](https://user-images.githubusercontent.com/6313008/56463528-124ab280-638b-11e9-9418-b6d9464c67c1.png)

Reproducible example: https://codepen.io/mbkupfer/pen/JVZJzR

**Comment by etpinard** [comment]
I'm not I understand what you mean by _offset_. You mean you'd like the selection styles to propagate the range-slider panel?

**Comment by mbkupfer** [comment]
@etpinard what I mean is that the selection I make by dragging does not correspond with the visually selected points.

**Comment by mbkupfer** [comment]
Great, thanks for the quick fix. On a related note, is there a setting that increases sensitivity for the select to capture a point? It seems like currently, the trace box must hover roughly half the bar before it becomes selected. Could this be configured to be more sensitive, say, select right when it is touched by the select box.  And for groups, could it be set to select all bars in a group together as opposed to individually?
