### ISSUE TITLE
Plotly mobile: Legend cannot be scrolled

### ISSUE THREAD

**Issue by avsdev-cw** [plotly/plotly.js#3801]
Initially I thought this issue was the same as #2844, however I think it is different in one key point.

When displaying a plotly graph on a mobile device (particularly where the page has it's own scrollbar) and a large number of traces, the legend does not capture the press+drag event in the same way as the main plot.  This means that the legend cannot be scrolled up or down on these devices.

Plotly.js version: v1.47.3

Example:
https://codepen.io/anon/pen/MRqOgE

**Comment by etpinard** [comment]
Thanks for reporting.

**Comment by etpinard** [comment]
Related: https://github.com/plotly/plotly.js/issues/2844

**Comment by andrewbaldock** [comment]
Here's a PR you might consider for this issue: https://github.com/plotly/plotly.js/pull/3873
