### ISSUE TITLE
layout.spikedistance = -1 causes missing spike lines over non-scatter traces.

### ISSUE THREAD

**Issue by pope1ni** [plotly/plotly.js#3805]
When using [`layout.spikedistance`](https://plot.ly/python/reference/#layout-spikedistance) with a value of `-1`, which is supposed to mean "no cutoff", and [`layout.xaxis.spikesnap`](https://plot.ly/python/reference/#layout-xaxis-spikesnap) with a value of `'cursor'`, I expected the spike line to be always visible in the plot area when moving the cursor across it. Indeed, when looking at my [codepen](https://codepen.io/anon/pen/eoPXJE), this is the case for the first scatter chart.

When I have other types of traces, the `-1` value doesn't seem to work in the same way and the spike line isn't rendered or can occasionally be seen between the traces. Changing to a value of `9999` then works, but only over the traces and not between.

Interestingly, combining scatter and bar partially works, but results in some flickering when hovering the mouse back and forth.

**Comment by pope1ni** [comment]
Annoyingly it looks as though my codepen didn't save everything, but I have partially fixed it to show enough of the problem.

**Comment by etpinard** [comment]
Thanks for the report!

**Comment by pope1ni** [comment]
Fixed by #4637.
