### ISSUE TITLE
When resizing the webpage, the modebar disappears for all plots except the last one.

### ISSUE THREAD

**Issue by jmonticolo** [plotly/plotly.js#3809]
After generating html + JS div for web output for two or more plots (in my case with Python but I don't think this is the source of the issue), from the `1.46.0` of plotly.min.js, when the webpage is resized, the modebar disappears for all plots except the last one.

Here is an example. Run the code and resize the browser or move the vertical splitter :
https://jsfiddle.net/be1s2wur/

Navigator used : firefox 66.0.3

The issue doesn't appear in the version `1.45.3`.
The issue is still present in the `1.47.3` (current) version.

**Comment by etpinard** [comment]
Thanks very much for reporting.

This is probably a side-effect of https://github.com/plotly/plotly.js/pull/3589

**Comment by antoinerg** [comment]
@jmonticolo in your example, you are loading `plotly.js` twice. By removing the second `<script>` tag, the issue seems to go away: https://jsfiddle.net/p0c83yzq/

@etpinard Should I investigate this further?

**Comment by etpinard** [comment]
> Should I investigate this further?

Let's wait until we can get more info from @jmonticolo before investigating further.

**Comment by jmonticolo** [comment]
Indeed, it works ! I have now to play more with the `include_plotlyjs` (plotly.offline.plot) parameter.
