### ISSUE TITLE
Pattern filled bar plots

### ISSUE THREAD

**Issue by jonmmease** [plotly/plotly.js#3815]
Originally requested in https://github.com/plotly/plotly.py/issues/1538

> Feature request: pattern filled bar plots - mainly for grey scale printing.
E.g. https://matplotlib.org/examples/pylab_examples/hatch_demo.html

This is something that's come up before as a publication requirement.  Could this be done with SVG pattern fills? https://iros.github.io/patternfills/sample_svg.html

**Comment by alexcjohnson** [comment]
Heh, there are still places that publish in black and white? I suppose so.

Sure, pattern fills seem like the way to go. We should make our own though, rather than using a package like `patternfills`. They're pretty easy to generate on the fly, similar to how we generate gradients, and AFAICT you need to fully specify colors and everything, so there are going to be far too many possibilities to preload them. Ideally it seems like we'd allow you to specify at least three attributes: shape, orientation, and solidity, and combine these with the fill color to make a pattern.

**Comment by lucgiffon** [comment]
Even if the original paper isn't in black and white, the printed version might be. This is also an important feature for colorblind people :) . Note that up to 10% of men are red-green color blind.

**Comment by harisbal** [comment]
Patterns can be used to represent relationships between traces also.
For instance, if one trace is depicted with diagonal stripes and another one with dots, a third trace resulting from their addition could be represented with a dotted-diagonal-stripe pattern.
Thanks a lot!

**Comment by w0L-g0R** [comment]
I agree - pattern filled bar and area charts would be great!

**Comment by kudhru** [comment]
Will this be implemented anytime soon?

**Comment by zelenkastiot** [comment]
I am also trying to reproduce a figure from a paper that needs this feature. 
We are interested in using this with Python 3, Plotly.

Hope this is still been worked on, thanks!

**Comment by Tominapa** [comment]
I would really appreciate having access to this feature as well; sometimes pattern fills are useful for distinguishing between closely-related items in plots, so those items can have a similar colour but a different pattern. This feature isn't available (yet) through other Julia plotting tools. Thank you.

**Comment by nicolaskruchten** [comment]
It's a good feature and we'd love to have it in the library but it's not on anyone's roadmap at the moment as far as I know. That said, we as maintainers would be happy to [help someone from the community to implement it in Plotly.js](https://github.com/plotly/plotly.js/blob/master/CONTRIBUTING.md), or to [accept sponsorship](https://plot.ly/products/consulting-and-oem/) to get it on to our short-term roadmap :)

**Comment by nicolaskruchten** [comment]
This issue has been tagged with `NEEDS SPON$OR`

A [community PR](https://github.com/plotly/plotly.js/pulls?q=is%3Apr+is%3Aopen+label%3A%22type%3A+community%22) for this feature would certainly be welcome, but our experience is deeper features like this are difficult to complete without the Plotly maintainers leading the effort.

**Sponsorship range: $10k-$15k**

What Sponsorship includes:
- Completion of this feature to the Sponsor's satisfaction, in a manner coherent with the rest of the Plotly.js library and API
- Tests for this feature
- Long-term support (continued support of this feature in the latest version of Plotly.js)
- Documentation at [plotly.com/javascript](https://plotly.com/javascript/)
- Possibility of integrating this feature with Plotly Graphing Libraries (Python, R, F#, Julia, MATLAB, etc)
- Possibility of integrating this feature with Dash
- Feature announcement on [community.plotly.com](https://community.plotly.com/tag/announcements) with shout out to Sponsor (or can remain anonymous)
- Gratification of advancing the world's most downloaded, interactive scientific graphing libraries (>50M downloads across supported languages)

Please include the link to this issue when [contacting us](https://plotly.com/get-pricing/) to discuss.

**Comment by gmichaeljaison** [comment]
Which release is expected to have this feature?

**Comment by nicolaskruchten** [comment]
The upcoming 2.0 release.

**Comment by nicolaskruchten** [comment]
2.0 was released this morning :)

**Comment by lucgiffon** [comment]
I don't find any documentation regarding the use of this feature. Is it available for all graphing libraries already (python?). Thank you :)

**Comment by nicolaskruchten** [comment]
This feature isn't released in Plotly.py just yet... stay tuned, it should be available in a week or so.

**Comment by swafsarl** [comment]
Any link to the documentation of this feature on plotlyjs ?
