### ISSUE TITLE
Using rgba colors in colorscales for parcoords plots results in all black lines.

### ISSUE THREAD

**Issue by SaschaJust** [plotly/plotly.js#3820]
## Observed 

The `parcoords` plot behaves differently for `rgba` color strings than others (`rgb`, `hex`, `string`) when used in a colorscale. When using `rgba` all lines are rendered black. When using a different color string type in the colorscale, lines are drawn in their respective colors.

## Expected

The type of the color string should not impact the functionality of the colors in the trace.

## Reproduction

This is the definition of the colorscale used in the example.

### Broken

Codepen: https://codepen.io/SaschaJust/pen/JVqoaL

```js
"colorscale": [
            [
                0,
                "rgba(255,0,0,1)"
            ],
            [
                1,
                "rgba(0,0,255,1)"
            ]
        ]
```

![parcoords_rgba](https://user-images.githubusercontent.com/29222831/56952067-a6f6a280-6b39-11e9-8bf6-a11607b977b2.png)

### Working

If you replace the `rgba` strings by their `rgb` counterparts, the plot renders as expected.

https://codepen.io/SaschaJust/pen/xeNGOy

```js
"colorscale": [
            [
                0,
                "rgb(255,0,0)"
            ],
            [
                1,
                "rgb(0,0,255)"
            ]
        ]
```

![parcoords_rgb](https://user-images.githubusercontent.com/29222831/56952066-a6f6a280-6b39-11e9-93ee-b4855355f99f.png)

Notice that the colorbar works fine in both cases.

**Comment by etpinard** [comment]
Thanks for the report!

Related: https://github.com/plotly/plotly.js/issues/1356
