### ISSUE TITLE
Plotly Offline 3D Surface Plots: Customize the x & y tickvals/ticktext AND ensure readability of the axis labels

### ISSUE THREAD

**Issue by jhthompson12** [plotly/plotly.js#3822]
Hello Plotly People, I am moving this from plotly.py in response to @jonmmease 's request.

Firstly, thank you very much for developing this incredible tool. You are all amazing. And apologies in advance if I did not submit this properly, this is my first time ever submitting a feature request. 

This post is in response to a question I recently asked in detail on the Plotly forum [found here](https://github.com/plotly/plotly.py/blob/master/CHANGELOG.md). 

In essence, when creating a surface plot, I would like to specify the values that are presented on the x and y axes AND set the maximum number of my custom axis tick mark values that will be displayed. At the moment, I can set the custom values with tickvals/ticktext, but the axis shows all of the ticktext that I provide. The nticks parameter almost provides the functionality that I'm looking for, but it doesn't seem to work with custom axis markers (nticks can only be used when tickmode = ‘auto’)

The following image shows how with a lot of tickvals/ticktext, the axis becomes unreadable. 

![](https://discourse-cdn-sjc2.com/standard17/uploads/plot/original/2X/4/4d38caeb3889e73328a9281277539c0db5615c1b.png)

Thank you for looking into this and please let me know if I need to provide any more information. 

-Joe

**Comment by archmoj** [comment]
@jhthompson12 have you tried increasing `layout.scene.yaxis.aspectratio`?
It maybe helpful to improve the example you provided.
https://plot.ly/python/3d-axes/

**Comment by etpinard** [comment]
Thanks for writing in @jhthompson12 

Your request is very similar to the one in https://github.com/plotly/plotly.js/issues/1812 most particularly from https://github.com/plotly/plotly.js/issues/1812#issuecomment-335348104, so I'll merge your ticket into https://github.com/plotly/plotly.js/issues/1812
