### ISSUE TITLE
Using "update" method in button created using updatemenus removes the modebar

### ISSUE THREAD

**Issue by hashimmoosavi** [plotly/plotly.js#3824]
The issue can be reproduced on the Plotly website itself. Navigate to https://plot.ly/javascript/custom-buttons/#update-button

When you hover over the chart, you can view the modebar. 

<img width="773" alt="Screen Shot 2019-05-01 at 11 57 30 AM" src="https://user-images.githubusercontent.com/3678012/57011067-83e6f400-6c08-11e9-9930-eee87e681463.png">

When you click on any button, the modebar disappears.

<img width="817" alt="Screen Shot 2019-05-01 at 11 57 40 AM" src="https://user-images.githubusercontent.com/3678012/57011080-8d705c00-6c08-11e9-8112-a60355b5b8aa.png">

**Comment by etpinard** [comment]
Thanks for reporting!

**Comment by etpinard** [comment]
The report feels similar to https://github.com/plotly/plotly.js/issues/3809

This is probably a side-effect of #3589

**Comment by sermeor** [comment]
I know the issue is closed, but it happens the same when using restyle method, which can be seen in the demos online (https://plotly.com/javascript/custom-buttons/). I was wondering if that can also be fixed?
