### ISSUE TITLE
Feature request: Add 'showlegend' to Carpet plots

### ISSUE THREAD

**Issue by pfbuxton** [plotly/plotly.js#3828]
It would be very useful to be able to switch a carpet plot on/off using the legend.

To do this `showlegend` and `legendgroup` could be added to the `Carpet` plot.

A discussion and example code showing how the feature could work can be found here:
https://github.com/plotly/plotly.py/issues/1540

**Comment by etpinard** [comment]
Merged into https://github.com/plotly/plotly.js/issues/2642
