### ISSUE TITLE
Colorscale extends beyond `cmin` and `cmax`

### ISSUE THREAD

**Issue by mdtusz** [plotly/plotly.js#383]
When `cmin` and `cmax` values are set with a colorscale, if their values lie *within* the range of the `color` data values, they will behave unexpectedly (i.e. continue beyond the colorscale bounds)

![screen shot 2016-04-01 at 12 28 15](https://cloud.githubusercontent.com/assets/6494463/14213346/806fb7b4-f805-11e5-93bb-f39ca706051a.png)

```
Plotly.plot(Tabs.fresh(), [{ 
  y: [1,2,3,4,3,2,1], 
  x: [1,2,3,4,5,6,7],
  marker: {
    color: [0,5,10,15,20,25,30],
    cmin: 23,
    cmax: 24,
    showscale: true
  }
}], { 
  plot_bgcolor: '#444', 
  xaxis: { gridcolor: '#444' }, 
  yaxis: { gridcolor: '#444' } 
});
```

**Comment by dannycodes** [comment]
IMO this is not the correct behavior. This behavior erroneous attributes data points that lie outside the bounds of the color-range to the boundary of the color-range. Ideally, a separate color option should be presented that sets the out-of-bounds color (black, for non-gray-scale colorscale, etc). Without accounting for the out of bounds data points and presenting them at the boundary, the plot is misleading the user into believing their bounds are heavily populated.

As is out-of-bounds is non-functional for the most common use cases.

**Comment by etpinard** [comment]
> As is out-of-bounds is non-functional for the most common use cases.

Would you mind sharing examples of those _common use cases_?
