### ISSUE TITLE
Choropleth maps don't reset accurately when layout.geo.scope is changed

### ISSUE THREAD

**Issue by mbkupfer** [plotly/plotly.js#3831]
First and foremost, I thought I would mention that this issue is only occurring with `Plotly.react` as I was able to implement a correct alternative by using `Plotly.newPlot` but unfortunately means that I won't be able to use react-plotly for this component. 

With that out of the way, the bug occurs when the layout scope is changed and either 1. a double click event is triggered or 2. reset is pressed in the mode bar. When the plot is changed through the dropdown though, there is no issue. All examples below can be reproduced in [this code pen](https://codepen.io/mbkupfer/pen/BEXONJ?editors=0010). 

In cases where scope is not 'usa', the reset changed the lon/lat values to whatever the initial plot's geo scope was set at. This is very pronounced when switching from 'world' to 'north america', thus I chose that for the example, but this occurs in any situation. If the initial plot is set to 'north america', then it would be the reverse.

In cases where the plot is changed to 'usa' though, the js actually throws an error! The error is: 
`TypeError: centerPx is null`. 

So this is actually two errors, but they both seem to have the same root cause. 

Let me know if I can provide any more clarity.

**Comment by mbkupfer** [comment]
Here is a gif that illustrates what I'm talking about.
![Plotly choropleth bug](https://user-images.githubusercontent.com/6313008/57120068-838f4b80-6d23-11e9-913f-2f748ea3619e.gif)

**Comment by etpinard** [comment]
Thanks very much for the report!

Something must be up with 

https://github.com/plotly/plotly.js/blob/03b7e09fa4fc6c842a28d8ba02547658cd43b6fe/src/plots/geo/geo.js#L515-L540

where we should probably clear the thing on update call involving `geo.scope`

**Comment by mbkupfer** [comment]
@etpinard, I'm not sure how far along you are in this, but I spent some time inspecting `geo.js` and it seems like we can mitigate by resetting `viewInitial` in the conditional below. 

I've also been trying to level up my js, so I wouldn't mind submitting a PR if this hasn't made it down your pipeline yet. Let me know. 

https://github.com/plotly/plotly.js/blob/03b7e09fa4fc6c842a28d8ba02547658cd43b6fe/src/plots/geo/geo.js#L76

**Comment by etpinard** [comment]
@mbkupfer We'll have a fix for this bug merged before we release 1.48.0

Here's your codepen demo using a "fixed" bundle: https://codepen.io/etpinard/pen/XwXqrN?editors=1010

Thanks again for using (and potentially contributing to :smirk: ) plotly.js!

**Comment by mbkupfer** [comment]
Awesome, thanks for fixing this so quickly! 

Thanks for making plotly such a great library.

**Comment by etpinard** [comment]
No problem! Thanks for the very clear bug report!
