### ISSUE TITLE
Box legend marker with invisible box but visible points

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#3836]
If I set the box fill and line to 0 opacity but have visible points, the legend entry is invisible. In this case it would be nice to have the legend entry look like the points.

**Comment by nicolaskruchten** [comment]
For context, I'm trying to add strip plots to `px`:

![image](https://user-images.githubusercontent.com/203523/57203810-1a0c7880-6f81-11e9-90c9-e549c7fd0403.png)

**Comment by etpinard** [comment]
Should we add "type: 'strip'" traces to plotly.js?

**Comment by nicolaskruchten** [comment]
could do, but it's really really easy to emulate with `box` (or even `violin`) for now so it's really not a priority, so long as we can slide in a fix for the legend :)

**Comment by alexcjohnson** [comment]
Sure, get a quick legend fix in, but `type: 'strip'` would be nice at some point - feels awfully hacky to do it via box or violin (instructions: make a box with no box, or a violin with no violin. Take your pick!) and there may be some extra functionality that doesn't make sense in the existing types.

**Comment by etpinard** [comment]
> , but `type: 'strip'` would be nice at some point -

That or adding `jitter` to scatter traces (cc https://github.com/plotly/plotly.js/issues/299), Personally, I prefer adding a `type: 'strip'` trace type.

**Comment by alexcjohnson** [comment]
Right, `scatter.jitter` is related, but not a replacement for `type: 'strip'` - especially grouping & offsets on the position axis, but also it's not clear to me if we can (or even if we want to) adjust scatter jitter for the local density of points like we do for box/violin jitter.

**Comment by nicolaskruchten** [comment]
Glad you guys are into it! I'm not opposed to a `strip` type, but I'd still like a fix for the legend in the meantime :)

**Comment by etpinard** [comment]
> but I'd still like a fix for the legend in the meantime :)

Yep, that fix we'll be in 1.48.0

**Comment by nicolaskruchten** [comment]
> ... adjust scatter jitter for the local density of points like we do for box/violin jitter.

I didn't realize we did that but looking at the screenshot above we clearly do, which is cool. It's sort of halfway to "swarm plots"

Seaborn has both but they're quite distinct: https://seaborn.pydata.org/generated/seaborn.swarmplot.html and https://seaborn.pydata.org/generated/seaborn.stripplot.html

**Comment by nicolaskruchten** [comment]
Could we imagine an attr that would emulate swarm plots more directly?

**Comment by antoinerg** [comment]
@nicolaskruchten maybe you can open a separate issue to discuss strip and/or swarm plots

**Comment by nicolaskruchten** [comment]
What we have is already pretty cool as a hybrid... no rush on a new trace type just for this. Next trace type is... drumroll... indicator!

**Comment by etpinard** [comment]
> maybe you can open a separate issue to discuss strip and/or swarm plots

> What we have is already pretty cool as a hybrid... no rush on a new trace type just for this.

I added it to https://github.com/plotly/plotly.js/issues/2221 in the meantime.
