### ISSUE TITLE
Negative y value for legend causes error and invisible legend

### ISSUE THREAD

**Issue by ChristinaTech** [plotly/plotly.js#384]
If you take the code given in one of the examples (https://plot.ly/javascript/legend/#positioning-the-legend-outside-the-plot) and make the y value for the legend negative, the legend will disappear and errors will appear in the console. This makes it impossible to position the legend below the graph.

Here is a codepen with the stated modification already made:
http://codepen.io/anon/pen/eZGWXo

**Comment by mdtusz** [comment]
Confirmed as a bug. Thanks for opening the issue.
