### ISSUE TITLE
Zero numbers are neither plotted nor included in hover on sunburst and pie text

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#3843]
[Codepen](https://codepen.io/MojtabaSamimi/pen/JqYyRZ?editors=0010).

**Comment by etpinard** [comment]
Could you check `sunburst` too?

**Comment by archmoj** [comment]
Confirmed `sunburst` has the same issue. It looks like we may have similar issue in hover.
And what about the case of `true`? Should `true` be displayed? If so why not `false`?
Please refer to [this codepen](https://codepen.io/MojtabaSamimi/pen/BeoVZZ?editors=0010) as an example.

**Comment by etpinard** [comment]
> Should `true` be displayed? 

yes

> If so why not `false`?

The only falsy value we should (and currently do) display is `0`.
