### ISSUE TITLE
Usage of error_y with custom buttons - Array error

### ISSUE THREAD

**Issue by hashimmoosavi** [plotly/plotly.js#3857]
When error_y is used as one of the args when defining the custom buttons using updatemenus, the "array" value of error_y is being reset to 10% of the y-value. 

The issue is reproduced here:

https://codepen.io/hashimmoosavi/pen/QREreb

Click on button "Error invisible". Then, click on button "Error visible". The array values of error_y are re-set to some default value which seems to be 10% of the y-value. The error-y seems to be losing its state after a custom button is clicked. Also, the args are applied to all lines by default, unable to set args for a single line.

**Comment by etpinard** [comment]
Here's a working version: https://codepen.io/etpinard/pen/VOKQmB?editors=1010

In brief, you need your `update` call settings in your updatemenu buttons are equivalent to:

```js
Plotly.update('graph', {
  error_y: {visible: true}
})
```

which sets the entire `error_y` attribute container to `{visible: true}` for **both** traces. To tweak only the `visible` part of the first trace, you should call:

```js
Plotly.update('graph', 
 {' error_y.visible': true},
 {/* n.b. nothing to update in layout */},
 [0]  // just update the first trace
)
```

----

I'll close the issue, but if you have any other questions about our update signature feel free to use https://community.plot.ly/c/plotly-js

thanks for using plotly.js
