### ISSUE TITLE
feature: function profiling graphs

### ISSUE THREAD

**Issue by ukos-git** [plotly/plotly.js#3878]
I have seen graphs in plot.ly for hierarchical data extracted from (former) google+ to display dependencies.

In programming, call graphs and caller graphs with highlighting of path usages is extremely useful to analyze linear independent paths within code and show the coverage graphically.

Doxygen is making a great job here using dot to visualize the data. Unfortunately the graphs produced by dot are very static.

http://www.doxygen.nl/manual/diagrams.html

Is there already an implementation for function profiling / code analysis that uses plot.ly or would that be a feature request that will not likely to happen in the scope of plot.ly?

**Comment by etpinard** [comment]
Thanks for writing in.

Merging your ticket into https://github.com/plotly/plotly.js/issues/2221
