### ISSUE TITLE
Implement of force-directed-graph of d3

### ISSUE THREAD

**Issue by 444thLiao** [plotly/plotly.js#3883]
I just want to ask if any plan to implement a **force-directed-graph** of d3 inside the plotly??

If I want to implement it by myself, I want to know where and how to find js code at python library of plotly.

Here is the **force-directed-graph** of d3.
https://observablehq.com/@d3/force-directed-graph

The main purpose of this implement is to improve the network layout _when too many point_ was shown...

**Comment by etpinard** [comment]
Thanks for writing in.

Merging your ticket into #2221
