### ISSUE TITLE
Better legend items visual for pie-like traces with same labels / different colors

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#3885]
See https://codepen.io/etpinard/pen/arVVpg

![image](https://user-images.githubusercontent.com/6675409/58117277-338e0100-7bcc-11e9-9096-e7c4b8601115.png)

for `pie` traces, `funnelarea` traces behave similarly.

Potential solution:

- split the legend item square into two halves (in general into N parts), one half with the pie color, the other with funnelarea color

More info: https://github.com/plotly/plotly.js/pull/3876#discussion_r286097769

**Comment by archmoj** [comment]
cc https://github.com/plotly/plotly.js/issues/2858.

**Comment by etpinard** [comment]
Thanks for spotting #2858 @archmoj - I'll merge this ticket in #2858
