### ISSUE TITLE
staticPlot: inconsistent behaviour with bar and pie

### ISSUE THREAD

**Issue by lingtalfi** [plotly/plotly.js#3887]
I basically have the same problem as https://github.com/plotly/plotly.js/issues/15: I just want to display plots without the user interaction. 
I found the staticPlot option, but the problem is that it also disable the tips for the bar plot I'm working on (see code and screenshot below).  However, when I apply the staticPlot: true to a pie bar, I still have those popup tips. 
So is there a way to have staticPlot: true AND the hover tips for bar plot?

The screenshot below shows the project I'm working on, with the bar plot on the left, and the pie plot on the right.
We can see the tips I'm talking about on the left plot (where it says male 26, and female 42).
Those are important things to show, even with staticPlot: true, because otherwise there is no way to get the precise value foreach bar of the plot.

My js code for those bars is below:

```js
<img width="1072" alt="Screenshot 2019-05-22 at 13 35 16" src="https://user-images.githubusercontent.com/223667/58172081-dbbccc00-7c97-11e9-8b31-0bc8c7784bff.png">

    //----------------------------------------
    // WEEK DAY MALE FEMALE DISTRIBUTION
    //----------------------------------------
    var trace1 = {
        x: [20, 14, 23, 26, 13, 61, 51],
        y: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', "Sunday"],
        name: 'Male',
        orientation: 'h',
        marker: {
            color: '#36acec',
            width: 1
        },
        type: 'bar'
    };

    var trace2 = {
        x: [12, 18, 29, 42, 20, 75, 64],
        y: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', "Sunday"],
        name: 'Female',
        orientation: 'h',
        type: 'bar',
        marker: {
            color: '#d74747',
            width: 1
        }
    };

    var data2 = [trace1, trace2];

    var layout2 = {
        title: 'Daily Traffic',
        showlegend: true
    };

    var config2 = {
        responsive: true,
        displayModeBar: false,
        // staticPlot: true,
    };
    Plotly.newPlot('plot-2', data2, layout2, config2);


    //----------------------------------------
    // MOBILE DISTRIBUTION
    //----------------------------------------
    var data3 = [{
        values: [34.2, 20, 15, 14, 16.8],
        labels: ['IOS', 'Android', 'Blackberry', 'Symbian', "Others"],
        type: 'pie'
    }];

    var layout3 = {
        title: "Mobile Traffic"
    };

    var config3 = {
        responsive: true,
        displayModeBar: false,
        staticPlot: true,
    };
    Plotly.newPlot('plot-mobile-traffic', data3, layout3, config3);
```

<img width="1072" alt="Screenshot 2019-05-22 at 13 35 16" src="https://user-images.githubusercontent.com/223667/58172144-0444c600-7c98-11e9-9c92-a0d53a064f4b.png">

**Comment by etpinard** [comment]
Hi @lingtalfi - thanks for writing in.

> I just want to display plots without the user interaction.
> So is there a way to have staticPlot: true AND the hover tips for bar plot?

By _use interaction_, I suspect you're referring to zoom/pan on drag motion. It sounds like you still want hover to be enable. If so, try setting `fixedrange: true` in the axes, see -> https://codepen.io/etpinard/pen/qGpXLj

> However, when I apply the staticPlot: true to a pie bar, I still have those popup tips.

Thanks for spotting that. That's a bug `staticPlot: true` should disable hover. Codepen: https://codepen.io/etpinard/pen/PvEKLx

**Comment by lingtalfi** [comment]
Yes, fixedrange: true did it for me, thanks.
