### ISSUE TITLE
Plot shows up empty in GWT app

### ISSUE THREAD

**Issue by sebastian-raubach** [plotly/plotly.js#3893]
I'm trying to integrate Plotly.js into my GWT application.
I can generate the charts I need in a standalone HTML file and everything works just fine.
If I then try and include them in the GWT application, the chart shows up empty.

I then went back and used one of the example charts (https://plot.ly/javascript/splom/) and just pasted that into my code and it still shows up empty.
![2019-05-23 09_25_42-Germinate 3 Demo Database](https://user-images.githubusercontent.com/12698452/58237386-e2514f00-7d3c-11e9-8d07-08a804c49e8b.png)

There are no errors in the console.
Unfortunately, I cannot provide a reproducible example, because I'm using GWT. The code I'm using though is here:

	private native void jsni(String id) /*-{
		$wnd.Plotly.d3.csv('https://raw.githubusercontent.com/plotly/datasets/master/iris-data.csv', function(err, rows){

			function unpack(rows, key) {
				return rows.map(function(row) { return row[key.replace('.',' ')]; });
			}

			colors = [];
			for (i=0; i < unpack(rows, 'class').length; i++) {
				if (unpack(rows, 'class')[i] === "Iris-setosa") {
					colors.push(0)
				} else if (unpack(rows, 'class')[i] === "Iris-versicolor") {
					colors.push(0.5)
				} else if (unpack(rows, 'class')[i] === "Iris-virginica") {
					colors.push(1)
				}
			}

			var pl_colorscale=[
				[0.0, '#19d3f3'],
				[0.333, '#19d3f3'],
				[0.333, '#e763fa'],
				[0.666, '#e763fa'],
				[0.666, '#636efa'],
				[1, '#636efa']
			];

			function axis() {
				return {
					showline: false,
					zeroline: false,
					gridcolor: '#ffff',
					ticklen: 4
				}
			}

			var data = [{
				type: 'splom',
				dimensions: [
					{label:'sepal length', values:unpack(rows,'sepal length')},
					{label:'sepal width', values:unpack(rows,'sepal width')},
					{label:'petal length', values:unpack(rows,'petal length')},
					{label:'petal width', values:unpack(rows,'petal width')}
				],
				text: unpack(rows, 'class'),
				marker: {
					color: colors,
					colorscale:pl_colorscale,
					size: 7,
					line: {
						color: 'white',
						width: 0.5
					}
				}
			}];

			var layout = {
				title:'Iris Data set',
				height: 800,
				width: 800,
				autosize: false,
				hovermode:'closest',
				dragmode:'select',
				plot_bgcolor:'rgba(240,240,240, 0.95)',
				xaxis:axis(),
				yaxis:axis(),
				xaxis2:axis(),
				xaxis3:axis(),
				xaxis4:axis(),
				yaxis2:axis(),
				yaxis3:axis(),
				yaxis4:axis()
			};

			$wnd.Plotly.react(id, data, layout)

		});
	}-*/;

Note that the `$wnd.` is a GWT requirement for accessing globally defined variables.

The chart is fully functional (zoom, pan, etc), but there just isn't any data. Interestingly, since this is the SPLOM example, there's also only a single set of axis and not the whole grid. It's almost like the layout and data are ignored, which also seemed to be the case in the custom charts that I tried to integrate originally.

**Comment by etpinard** [comment]
Hi @sebastian-raubach 

I have a few questions for you:

- Does anything show up in console?
- Which plotly.js version are you using?
- Could you paste the contents of one of your `unpack` calls e.g. `unpack(rows,'sepal length')`

**Comment by sebastian-raubach** [comment]
Nothing shows in the console and I'm using plotly.latest.
Here's the requested output:
```
[ "5.1", "4.9", "4.7", "4.6", "5.0", "5.4", "4.6", "5.0", "4.4", "4.9", "5.4", "4.8", "4.8", "4.3", "5.8", "5.7", "5.4", "5.1", "5.7", "5.1", "5.4", "5.1", "4.6", "5.1", "4.8", "5.0", "5.0", "5.2", "5.2", "4.7", "4.8", "5.4", "5.2", "5.5", "4.9", "5.0", "5.5", "4.9", "4.4", "5.1", "5.0", "4.5", "4.4", "5.0", "5.1", "4.8", "5.1", "4.6", "5.3", "5.0", "7.0", "6.4", "6.9", "5.5", "6.5", "5.7", "6.3", "4.9", "6.6", "5.2", "5.0", "5.9", "6.0", "6.1", "5.6", "6.7", "5.6", "5.8", "6.2", "5.6", "5.9", "6.1", "6.3", "6.1", "6.4", "6.6", "6.8", "6.7", "6.0", "5.7", "5.5", "5.5", "5.8", "6.0", "5.4", "6.0", "6.7", "6.3", "5.6", "5.5", "5.5", "6.1", "5.8", "5.0", "5.6", "5.7", "5.7", "6.2", "5.1", "5.7", "6.3", "5.8", "7.1", "6.3", "6.5", "7.6", "4.9", "7.3", "6.7", "7.2", "6.5", "6.4", "6.8", "5.7", "5.8", "6.4", "6.5", "7.7", "7.7", "6.0", "6.9", "5.6", "7.7", "6.3", "6.7", "7.2", "6.2", "6.1", "6.4", "7.2", "7.4", "7.9", "6.4", "6.3", "6.1", "7.7", "6.3", "6.4", "6.0", "6.9", "6.7", "6.9", "5.8", "6.8", "6.7", "6.7", "6.3", "6.5", "6.2", "5.9"]
```

**Comment by etpinard** [comment]
Thanks for writing back @sebastian-raubach 

I can't detect anything suspicious in your code snippet.

You may want to ask your question on https://community.plot.ly/c/plotly-js where other users, potentially other GWT (I don't even know what that is) users, could help you out.

**Comment by etpinard** [comment]
This ticket will likely not result in a PR in this repo, so I'll close it.
