### ISSUE TITLE
Feature request: categorical heatmap

### ISSUE THREAD

**Issue by Batalex** [plotly/plotly.js#3897]
Hi,

it would be quite handy to have a categorical mode for heatmaps.
As of today heatmaps are rendered with a gradient colorbar (which can be hidden).

The closest thing to a categorical heatmap with Plotly is the [annotated heatmap figure factory](https://plot.ly/python/annotated_heatmap/) periodic table example, but it is still a bit tedious to use since:
- we need to specify the colorscale by hand (and it needs to match the number of different values or the wrong colors are picked) 
- we need to hardcode the legend directly in the trace.

**Comment by etpinard** [comment]
Thanks for writing in! 

Your request will be part of bigger project, tracked in https://github.com/plotly/plotly.js/issues/1747
