### ISSUE TITLE
Unexpected token ILLEGAL 

### ISSUE THREAD

**Issue by robz** [plotly/plotly.js#39]
It seems like there are a lot of greek unicode characters in `d3.js` and `projections.js`. 

https://github.com/plotly/plotly.js/blob/master/src/plots/geo/projections.js#L355

These characters are causing an "Unexpected token ILLEGAL" error in Chrome 46, and likely most browsers.

**Comment by etpinard** [comment]
You should import unminified `plotly.js` code with `charset="utf-8"`. 

For example, like the [test dashboard index](https://github.com/plotly/plotly.js/blob/master/devtools/test_dashboard/index.html#L15):

```js
<script type="text/javascript" src="plotly.js" charset="utf-8"></script>
```

Note that the minified version (under `dist/plotly.min.js`) has all non-ascii characters removed thanks to uglify-js.
