### ISSUE TITLE
Problems with shared autobins on single-sample-point histogram2d

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#3909]
One of these facets has misaligned bins: https://codepen.io/nicolaskruchten/pen/MdVdGw

**Comment by nicolaskruchten** [comment]
Note also: that misaligned one has x:NaN, y:NaN in the hover for some reason

**Comment by etpinard** [comment]
They are misaligned, but are they _incompatible_? It's not obvious to me by looking at it quickly. I'll take deep dive tomorrow.

**Comment by etpinard** [comment]
Thanks for reporting. Something is up with `histogram2d` traces that have 1 `x` and `y` sample point. I can't replicate the problem with other samples with 2 or more points (example adding one pt to `gd.data[2]` https://codepen.io/etpinard/pen/byjbbr?editors=1010)

Is this blocking for 1.48.0?

**Comment by etpinard** [comment]
Similar to https://github.com/plotly/plotly.js/issues/3881

**Comment by nicolaskruchten** [comment]
agreed that it is "compatible" and that it shouldn't block 1.48, but it does seem like a bug to me.

**Comment by etpinard** [comment]
> but it does seem like a bug to me.

Yep, no doubt it's a bug.

**Comment by etpinard** [comment]
In fact, even non-shared single-sample-point histogram2d traces do not respect xbins / ybins settings:

https://codepen.io/etpinard/pen/eajory?editors=1010

**Comment by etpinard** [comment]
Ha, looks like things were working ok back in 1.42.x: https://codepen.io/etpinard/pen/eajory?editors=1010

Commit https://github.com/plotly/plotly.js/commit/e0116cbd98b0018331fdc15677d8746031de7597#diff-98b2c1750afe8f855914e1647f72dbfe didn't work for `histogram2d` traces
