### ISSUE TITLE
Unevenly spaced ticks.

### ISSUE THREAD

**Issue by abalter** [plotly/plotly.js#392]
Allow something like this:

```
var trace1 = {x:[1, 5, 13], y:[2, 7, 4]}

layout = {
    xaxis:
        {
          ticks:
          {
             tickvalues: [1, 5, 13],
             ticklabels: ["initial", "max", "final"]
          }
          tickfont:
          {
            color:"rgb(107, 107, 107)",
            size:11
          },
          showticklabels:true,
          type:"scatter",
        },
...
```

**Comment by etpinard** [comment]
@abalter this community forum [post](http://community.plot.ly/t/dates-on-x-axis-not-spaced-appropriately/767) should answer your question.

Axis attributes [`tickvals`](https://plot.ly/javascript/reference/#layout-xaxis-tickvals) and [`ticktext`](https://plot.ly/javascript/reference/#layout-xaxis-ticktext) do exactly what you're asking, unless I'm misinterpreting this issue.

**Comment by abalter** [comment]
Absolutely! I cross-posted to Stackoverflow, and someone who maintains a table of supported/unsupported ggplot equivalents posted that it is not supported. I raised the issue and posted the link as a comment. They saw your comment, and are going to update their table. So this is basically closed. Thanks for your help.

**Comment by abalter** [comment]
Oh, and if you know of any others, maybe pass them a comment. https://github.com/ropensci/plotly/wiki/Unsupported-plotly.js-features.

**Comment by cpsievert** [comment]
@abalter that page was woefully out of date -- it's updated now
