### ISSUE TITLE
scattergeo is not working well with Plotly.react

### ISSUE THREAD

**Issue by rhamner** [plotly/plotly.js#3920]
If I update a scattergeo plot using Plotly.newPlot, it works fine. If I do it with Plotly.react, the update is ignored.

Here is a codepen showing this with both calls updating separate divs with the exact same traces and layouts. For me, react updates once while newPlot updates every call.

https://codepen.io/rhamner/pen/RmYGKv

Plotly 1.47.4
Chrome Version 74.0.3729.169 (Official Build) (64-bit)
Windows 10 (64-bit)

**Comment by etpinard** [comment]
@rhamner thanks for writing in.

Looks like you're trying to update data arrays (`lon` and `lat`) by mutating them. To do so, you'll need update `layout.datarevision` before every `Plotly.react` to tell plotly.js that the content of the data arrays have changed. Here's an example: https://codepen.io/etpinard/pen/PvyooK

**Comment by rhamner** [comment]
Augh...I knew that existed and just didn't make the connection that it different between newPlot and react. Thanks @etpinard

**Comment by etpinard** [comment]
No problem @rhamner - thanks for using plotly.js!
