### ISSUE TITLE
SVG paths with elliptical arcs don't appear to render in the plot

### ISSUE THREAD

**Issue by joseph-long** [plotly/plotly.js#3926]
I'm trying to specify a shape that's a perfect fit for [elliptical arc curves](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/d#Elliptical_Arc_Curve) in SVG. However, supplying shapes that use the `A` path minilanguage command does not produce an elliptical arc.

I took [this example of SVG paths](https://codepen.io/plotly/pen/EjGMez) from the Plotly.js docs, added in a path from [this MDN example](https://codepen.io/anon/pen/RmqQVm) and adjusted the axes limits to get [this new Codepen](https://codepen.io/anon/pen/ROydgg). As you can see, the elliptical curve is nowhere to be found.

Any ideas what's going on?

**Comment by etpinard** [comment]
From  

https://github.com/plotly/plotly.js/blob/5c658326ef62618e879a6fad3fffc42cc8d35e29/src/components/shapes/attributes.js#L189-L213

We currently don't allow arcs in `path`.

**Comment by alexcjohnson** [comment]
FWIW this would be easy to add for some axis types (linear and category), hard and/or new syntax for the others (log and date). The options we allow right now are the ones that work with a straightforward syntax on all axes.

**Comment by joseph-long** [comment]
Ah, I see. That makes sense.

(... was there a way to find this out without reading the source? There’s a lot of useful documentation in the linked description)

**Comment by etpinard** [comment]
Here -> https://plot.ly/javascript/reference/#layout-shapes-items-shape-path

**Comment by joseph-long** [comment]
Cheers, thanks!
