### ISSUE TITLE
How to register parcoords module

### ISSUE THREAD

**Issue by Kiiiwiii** [plotly/plotly.js#3936]
I'm trying to customize the bundles myself and have trouble to import `parcoords` module
I'm right now use `"plotly.js": "^1.48.1"` + `"react-plotly.js": "2.3.0"` and I customize the bundles as follows:
```typescript
import Plotly from 'plotly.js/lib/core';
import createPlotlyComponent from 'react-plotly.js/factory';

// import the necessary trace type
Plotly.register([
  require('plotly.js/lib/scatter'),
  require('plotly.js/lib/bar'),
  require('plotly.js/lib/parcoords'),
]);

export default createPlotlyComponent(Plotly);
```

Bar chart and scatter chart work fine, but I have an error with `Parcoords`:
```
Error: (regl) Error compiling fragment shader, at Function.raise (regl.js:39)
    at Function.checkShaderError [as shaderError] (regl.js:325)
    at Object.getShader [as shader] (regl.js:4592)
    at regl.js:5642
    at Function.checkOptional [as optional] (regl.js:403)
    at parseShader (regl.js:5641)
    at parseProgram (regl.js:5664)
    at parseArguments (regl.js:6468)
    at Object.compileCommand [as compile] (regl.js:7694)
    at compileProcedure (regl.js:8208)
    at push../node_modules/plotly.js/src/traces/parcoords/lines.js.module.exports (lines.js:202)
```

Because the trace type is `parcoords`, so I only registered the `parcoords` from `plotly.js/lib`.

My questions are:
* is it a bug?
* Shall I register some other pre-requisite modules? 
* What is the right way to import the parcoords module?

Thank you very much!

**Comment by etpinard** [comment]
Thanks for writing in.

Could you tell us how you're bundling your custom plotly.js bundle? You might want to look at https://github.com/plotly/plotly.js/blob/master/BUILDING.md for more info.

**Comment by Kiiiwiii** [comment]
@etpinard , thanks for your reply. I let the react to handle the bundle for me. I didn't `npm eject` my project, which means I can't see the `webpack.config.json` file. But if I understand correctly from the https://github.com/plotly/plotly.js/blob/master/BUILDING.md , I need to add `ify-loader@v1.1.0+` and add some config to the webpack. Otherwise some dependencies might fail to load. I will try it and report the results here

**Comment by Kiiiwiii** [comment]
It works with `ify-loader@v1.1.0+`. Thanks @etpinard
