### ISSUE TITLE
Add option to set parcoords context line color and opacity

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#3939]
The deselected lines in all `parcoords` plots now use a constant color (i.e. `#777` and auto opacity logic (i.e. depending on the number of overlaid lines).
In some scenarios it may be useful to let the user override the default.

**Comment by chriddyp** [comment]
If we could set the opacity to zero, then the user could have the unselected lines completely removed when filtering. This would be very nice for cluttered plots. for inspiration, see how hiplot does this in their parcoords tool (https://facebookresearch.github.io/hiplot/_static/demo/ml1.csv.html?hip.color_by=%22valid+ppl%22&hip.PARALLEL_PLOT.order=%5B%22dropout%22%2C%22embedding_size%22%2C%22epoch%22%2C%22lr%22%2C%22train+f1%22%2C%22valid+ppl%22%5D)
![image](https://user-images.githubusercontent.com/1280389/74690830-81ad5080-51ae-11ea-8d2a-7d6371e22b2b.png)

**Comment by mahannya** [comment]
Hi ! Is there any attribute available now that solves this issue in Python . I want to change the unselected line colour from the default grey to another colour. Please let me know .
Thanks.

**Comment by alexcjohnson** [comment]
This will be in the next release, hopefully out this week. It will be plotly.js 2.13 and plotly.py 5.10

**Comment by RamenJamen** [comment]
Hi!
I can’t quite figure out if this is issue (parcoords and unselected lines) has been fixed in plotly.py? Since I can’t change the opacity of the unselected lines in my plotly.py (5.15.0) plot with flask.
