### ISSUE TITLE
Legend order reversed when switching from stack to group bar mode

### ISSUE THREAD

**Issue by aburato** [plotly/plotly.js#394]
Hi all,

as the title says: http://codepen.io/aleburato/pen/ZWaaLZ

I don't know if this was made on purpose, as if (and only if) the y values are positive, the "reverse" behavior makes the legend match the stacked bars ordering. But this falls apart when the Y values are negative (see the codepen), so...

**Comment by etpinard** [comment]
Yep, that's on [purpose](https://github.com/plotly/plotly.js/blob/fb874424d5b89c021ef6e5ebe0326433389d02ee/src/components/legend/defaults.js#L35-l39).

You can always override that behavior by setting [`layout.legend.traceorder`](https://plot.ly/javascript/reference/#layout-legend-traceorder) to `'normal'`.

I'd vote against adding a check that loops through the traces data array looking for negative values - as it would most likely be a performance hit.

Regardless, thanks for pointing out this *less-than-perfect* behavior to us.

**Comment by aburato** [comment]
Am I being too nit-picky? :laughing:

**Comment by etpinard** [comment]
Nop. You're making a valid point. :beers: 

We are just reluctant to add logic to our attribute defaults based on values in data arrays, for performance reasons.

**Comment by aburato** [comment]
No, no, I wasn't suggesting to "fix" the negative values case, I agree with you that wouldn't be worth (and, say, the chart updates so that now there are positive values again, or worse, MIXED values :D... legend would flip at each update, and that's NOT good)

So, maybe, make the auto-reverse choice more obvious (or make "normal" the default value, I don't know). Anyways, my problem is solved now. Thanks!
