### ISSUE TITLE
Bug in simple zoom in

### ISSUE THREAD

**Issue by michalwoz** [plotly/plotly.js#3943]
There is little bug in zooming in. When you click and release in parallel point to axis you can see two vertical or horizontal lines: A
![image](https://user-images.githubusercontent.com/31922455/59121932-aa135880-8959-11e9-8598-f5edf3a87f70.png)
and zoom in "range mode" on x or y axis.

When you click not in parallel you can go to "rectangle zoom mode": B
![image](https://user-images.githubusercontent.com/31922455/59121974-c7482700-8959-11e9-8781-199a77d43c89.png)

The problem is that when your mouse move during click and release is not almost perfectly parallel to axis you see parallel lines(picture A), but in effect you get zoom in rectangle mode. I experience it in simplest plotly configuration.

you can easily recreate this on
https://plot.ly/~demos/1414

by releasing mouse click zoom at this point:
![image](https://user-images.githubusercontent.com/31922455/59122525-42f6a380-895b-11e9-9633-64f29c62d064.png)

**Comment by etpinard** [comment]
Got it:

![Peek 2019-06-10 10-15](https://user-images.githubusercontent.com/6675409/59201603-c6d1ab00-8b68-11e9-8d21-7d5e427edbdb.gif)

Thanks for letting us know @michalwoz !!
