### ISSUE TITLE
Scatter3d should support axis scales

### ISSUE THREAD

**Issue by deliciouslytyped** [plotly/plotly.js#3953]
It looks to me like scatter3d plots don't support different types of axes, like log axe. I've attempted to search through documentation and examples, and couldn't find anything suggesting this should work.

I'm actually using plotly with R, but this seems to be a core library issue. The snippet I'm trying is `layout(xaxis=list(type="log"))`.

For the sake of maybe saving some people pain later, are there any other plot types missing functionality like this?

**Comment by deliciouslytyped** [comment]
With that in mind, it's not clear to me what functionality I should use to implement this for my own plot.

**Comment by archmoj** [comment]
@deliciouslytyped please note that the 3D axes attributes are accessible within `layout.scene` not `layout` itself.
So `type` of `xaxis` could be accessed via `layout.scene.xaxis.type`.

**Comment by etpinard** [comment]
@deliciouslytyped please see https://plot.ly/javascript/3d-axes/ for examples

You might be interested in using https://community.plot.ly/c/plotly-js for questions of the likes in the future. Thank you!

**Comment by deliciouslytyped** [comment]
@archmoj Wait, why though? Wouldn't it be more consistent if users could still access them through the usual layout things?
