### ISSUE TITLE
Forcing layouts

### ISSUE THREAD

**Issue by schoifetj** [plotly/plotly.js#3956]
Hello!  I am trying to improve the speed at which my plotly graph loads on a webpage, this webpage has 3 seperate graphs. I used chrome dev tools to look closer at the issue, I noticed that olotly constantly forces Recalculate Style and Layout over and over again, slowing down my code considerably. Both of these are forced and I have found no other mentions of this problem on the internet. I am not looking for a specific solution, but more general guidance on how to fix this so it goes quicker. SInce I think it has to do with the layout, I've included a snippet of the layout code below, I am using scattergl type points because there are a lot of them. Any tips for a good way to approach debugging the issue? I have attatched a snippet of the dev tool analysis on runtime, the small purple bars are a bunch of these instances where it is flagged for bottlenecking. 

![Screen Shot 2019-06-12 at 1 33 42 PM](https://user-images.githubusercontent.com/51413195/59382163-0d6f0300-8d2b-11e9-91aa-1f69cf4cf7a4.png)

 var layout = {
        height: $chart.height(),
        width: $chart.width(),
        margin: { l: 50, r: 30, b: 50, t: 30, pad: 10 }
    };

**Comment by etpinard** [comment]
Hi @schoifetj - let's discuss this over in https://community.plot.ly/t/having-some-forced-bottlenecking-problems-with-plotly-js/24478

thanks!
