### ISSUE TITLE
Rangeslider selection display not updating

### ISSUE THREAD

**Issue by mbkupfer** [plotly/plotly.js#3957]
@etpinard, I know it has been sometime, but turning back to merge #3806 and the original bug #3795, I noticed that there is another issue with the rangeslider and selections not being in sync. In this case, the issue is regarding the selection in the rangeslider window not updating when the selection in the graph changes.

I've created a reproducible example on codepen here: https://codepen.io/mbkupfer/pen/zVGwoZ

I also demonstrated this bug in a gif to help clarify. Take note how the selected bars will only update in the rangeslider window only when the rangelisder has a click event.

![2019-06-12 16-06-40 2019-06-12 16_09_23](https://user-images.githubusercontent.com/6313008/59392434-802cae00-8d2c-11e9-8b32-810a1f8b754f.gif)

**Comment by etpinard** [comment]
Thanks very much for the report!
