### ISSUE TITLE
all textinfo/hoverinfo flags should be available to hovertemplate

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#3960]
Following on from #3954 ... I'm not sure if this is or isn't the case for `pie` already, but it should be 🔒'ed down please :)

**Comment by archmoj** [comment]
Thanks for the report.
The `percent` flag seem to be not available in `hoverinfo` of `pie` & `funnelarea`.

**Comment by archmoj** [comment]
<b>Correction</b>: there is no issue found with `pie` and `funnelarea` with `percent` flag.

**Comment by etpinard** [comment]
@archmoj how's our test coverage for `funnelarea` + `hoverinfo` and `hovertemplate` ?

**Comment by archmoj** [comment]
> @archmoj how's our test coverage for `funnelarea` + `hoverinfo` and `hovertemplate` ?

I <i>think</i> that is pretty good.

For `hovertemplate` we have:
https://github.com/plotly/plotly.js/blob/d7d2bdd66e1afaff222eb4e5dc76e7b21db1069a/test/jasmine/tests/funnelarea_test.js#L965-L993

And for `hoverinfo` we have:
https://github.com/plotly/plotly.js/blob/d7d2bdd66e1afaff222eb4e5dc76e7b21db1069a/test/jasmine/tests/funnelarea_test.js#L877-L892

**Comment by etpinard** [comment]
Yep, good enough.

I think you can close this issue @archmoj
