### ISSUE TITLE
Parcoords - rgba not reflecting alpha

### ISSUE THREAD

**Issue by MrHejtmar** [plotly/plotly.js#3964]
<h2>Issue</h2>

Currently when setting the line colors for parcoords, it is impossible to modify the line transparency using RGBA colorscale and set alpha to zero. It is reflected in the colorbar, but not with lines themselves.

As seen in the example, lines should change color from red - fully opaque, to red - fully transparent, according to alpha. However, the line color only reflects RGB properties and lines are red - fully opaque, yet the colorbar scale is shown correctly.

<h2>Example</h2>
https://codepen.io/anon/pen/ydYxbx

**Comment by etpinard** [comment]
That's correct we don't support the alpha channel in parcoords colorscales at the moment.

related https://github.com/plotly/plotly.js/pull/3917
