### ISSUE TITLE
Hoverinfo for histogram not coloring name (JS)

### ISSUE THREAD

**Issue by pmpbar** [plotly/plotly.js#397]
I am not sure if this is my fault or not but the hoverinfo for histograms is not coloring all of the info. Example:
![screenshot - 04052016 - 01 55 21 pm](https://cloud.githubusercontent.com/assets/3513897/14296251/70093d26-fb36-11e5-8aa3-97beb8ebc676.png)

The setting is eddyBar.hoverinfo = 'text+name';

**Comment by etpinard** [comment]
This is the indented behavior. No just for histograms, but for all trace types.

If `'name'` is present in `hoverinfo` and if `name` is set in the trace objects, name shows up in the secondary (transparent) label.

One work around, would be to append `name` value to `text` field (with a `<br>` to show up on two lines) and set `hoverinfo` to `text`. Example: http://codepen.io/etpinard/pen/eZewBX
