### ISSUE TITLE
Some categoryorder creates invisible extra series for boxplot

### ISSUE THREAD

**Issue by deecay** [plotly/plotly.js#3970]
Hi,

For boxplot, I've found that `categoryorder` of (total|min|max|sum|mean|median) in boxplot generates invisible data to the plot.

[Original baseline with no categoryorder](https://codepen.io/etpinard/pen/OOZMqW)
[with categoryorder of 'median descending'](https://codepen.io/anon/pen/LKZXRy)

Screenshot. Second plot is the trace with categoryorder.
![image](https://user-images.githubusercontent.com/1698635/59666372-a7352500-91ef-11e9-8946-cefbd8a05bf0.png)

**Comment by antoinerg** [comment]
Thank you for reporting this issue @deecay !

**Comment by antoinerg** [comment]
This problem also occurs with `violin`. Prior to running `calc`, we reset the following counters:
https://github.com/plotly/plotly.js/blob/795220f815afcf79c73885715379b606afc1b4a1/src/plots/plots.js#L2750-L2752

Upon sorting the categories, we need to run `calc` again which doubles the values of those counters which shift all the boxes/violins by a half.
