### ISSUE TITLE
hoverlabel overlapping with x axis hover info

### ISSUE THREAD

**Issue by ankuradhey** [plotly/plotly.js#3973]
Hi,

I found an issue of overlap between hoverlabels closer to xaxis with x axis hover info displayed in black box. 

Here is the snapshot of issue.
![image](https://user-images.githubusercontent.com/9452047/59769045-fc8e3680-92c2-11e9-8442-99b6d7f1cdfb.png)

Created codepen for much better understanding.
https://codepen.io/ankuradhey/pen/Wqoxvy

**Comment by etpinard** [comment]
Thanks for posting!

I'm not entirely sure what the best way of fixing this problem is though. I think moving the trace label "up" when the overlap with the axis label could work, but maybe moving the axis label "down" would be best.
