### ISSUE TITLE
Meta using a object not working

### ISSUE THREAD

**Issue by anikets43** [plotly/plotly.js#3980]
In v0.48 I saw that meta can now be objects as per documentation:
https://github.com/plotly/plotly.js/blob/v1.48.3/src/plots/layout_attributes.js#L424

I tried using that and it did not seem to work:
https://codepen.io/anikets43/pen/QXvXvp

When using array like `meta: ['x', 'y']` or string `meta: 'xyz'` - it works.

Code:
```js
var gd = document.getElementById('graphDiv');
var data = [{
  y: [2, 1, 2],
  // name: '%{meta["a"]}',
  name: '%{meta[a]}',
}]
var layout = {
  meta: {
    a: "x",
    b: "y"
  },
  // title: '%{meta["b"]}'
  title: '%{meta[b]}'
}

Plotly.newPlot(gd, data, layout);
```

**Comment by etpinard** [comment]
Using `%{meta.a}` and `%{meta.b}` seems to work ok.

Something must off in the regex we use. Thanks for letting us know!

**Comment by etpinard** [comment]
Upon further inspection, [`Lib.nestedProperty`](https://github.com/plotly/plotly.js/blob/master/src/lib/nested_property.js) (which `meta` makes use of internally) was never intended to work with object keys inside `[]`. 

We could of course extend `Lib.nestedProperty` attribute strings like `meta["b"]`, but we would have to be careful to not slow down performance - as `Lib.nestedProperty` is use in a lot of place including some fairly hot codepaths.

----

Closing this issue (for now), but please don't hesitate to comment if you'd like us to generalise `Lib.nestedProperty`.
