### ISSUE TITLE
keybinding, shortcuts for zoom and pan

### ISSUE THREAD

**Issue by mzechmeister** [plotly/plotly.js#3989]
Is it possible to have shortcuts for interactions with the graph?

E.g. I would like to have
* panning with the arrow keys `left`, `right`, `up`, `down`
* zooming with `+` and `-`
* horizontal zooming with `ctrl+left` and `ctrl+right`
* vertical zooming with `ctrl+up` and `ctrl+down`
* unzoom both `u`, horizontal unzoom `alt+x`, vertical unzoom `alt+y`
* previous zoom `p`
* toggle grid `g`
* snapshot (copy as png to clibboard) `ctrl+c`

 (partly taken from gnuplot).

**Comment by etpinard** [comment]
Merging with https://github.com/plotly/plotly.js/issues/562

Thanks for posting.
