### ISSUE TITLE
Scatter plotting much slower than line plotting with huge dataset

### ISSUE THREAD

**Issue by sfchen** [plotly/plotly.js#3990]
Hi, I am plotting a dataset with about 1M points.

When I used line plotting, plotly worked well and the browser was responsive.

But when I used scatter plotting, plotly used a lot of RAM and the browser became very slow.

Why? Is there a way to make scatter plotting faster?

**Comment by etpinard** [comment]
Please refer to https://plot.ly/javascript/webgl-vs-svg/ or ask your implementation questions on https://community.plot.ly/c/plotly-js

Thank you.
