### ISSUE TITLE
Clickable hidden text in Funnel

### ISSUE THREAD

**Issue by AbdealiJK** [plotly/plotly.js#3996]
I'm not sure if this is an issue with all trace types or Funnel. But in the funnel there is hidden text in the background that is clickable and highlight-able.

Double click in the region I show in the video to see it.

Code: https://codepen.io/AbdealiJK/pen/mZpLKZ
Video:
![untitled](https://user-images.githubusercontent.com/2200743/60366231-8e571b80-9a08-11e9-946b-990024899ecc.gif)

**Comment by etpinard** [comment]
You can use

https://github.com/plotly/plotly.js/blob/d096307aabb0dd7c52c974d0401948553b35c9d6/src/plot_api/plot_config.js#L183-L190

to disable it.

https://codepen.io/etpinard/pen/MMrGMO
