### ISSUE TITLE
Custom bundle not working with surface plot

### ISSUE THREAD

**Issue by cadeo111** [plotly/plotly.js#3997]
When using a custom bundle per [this](https://github.com/plotly/plotly.js/#modules), including only the surface package, it gives a WebGL not supported error but if I use the [plotlyjs-gl3d module](https://github.com/plotly/plotly.js/blob/master/dist/README.md#plotlyjs-gl3d) it works fine

using Chrome Version 75.0.3770.100 (Official Build) (64-bit)

### [Code Here](https://gist.github.com/cadeo111/b47aa7483b92dbe2cf0ad1a572501b4a)
<img width="1680" alt="Screen Shot 2019-06-29 at 13 42 30" src="https://user-images.githubusercontent.com/20238857/60389298-06a6f680-9a74-11e9-9fae-0245da9937e1.png">

**Comment by etpinard** [comment]
Please see solution in https://github.com/plotly/plotly.js/issues/3936
