### ISSUE TITLE
0.20.1 demo-chromajs broken

### ISSUE THREAD

**Issue by xuyang2** [plotly/plotly.js#40]
http://docs.handsontable.com/0.20.1/demo-chromajs.html

Uncaught TypeError: Cannot read property '1' of undefined
at `demo-chromajs.html:2088`

```
function updateHeatmap(change, source) { 
  // arguments: [true, undefined, undefined, undefined, undefined, undefined]
  if (change) {
	heatmap[change[0][1]] = generateHeatmapData.call(this, change[0][1]);
  } else {
```

**Comment by etpinard** [comment]
@xuyang2 could you provide more information?

Looks like this *bug* has nothing to do with plotly.js.

**Comment by xuyang2** [comment]
My bad. It's an issue of handsontable.js.
