### ISSUE TITLE
Setting only min or max values for axis and not a range.

### ISSUE THREAD

**Issue by shimwell** [plotly/plotly.js#400]
Dear all

Many thanks for all your wonderful efforts with Plotly

I just wanted to ask if it might be possible to tweak the range function a little

currently an axis range can be set in the layout like this ...
```
layout = go.Layout(
xaxis=dict(
range=[2, 5]
),
```
in some cases it would be desirable to only specify a min value.
Plotly can then work out the max value automatically.

Or perhaps a user would want to set a max value and have a plotly work out the min value

Either-way it would be nice (for me at least) to only specify one of the range limits and not both. However I can see why this might not be a highly required function and I'm sure there are lots of other things to do first

matplotlib offers this function ...
```
plt.xlim(2,5) #sets a range
plt.gca().set_xlim(xmin=2) # sets only the lower x value and allows computer to work out upper value
plt.gca().set_ylim(ymax=50) # sets only the lower y value and allows computer to work out upper value
```

**Comment by etpinard** [comment]
Thanks for submitting the issue. You're making some valid points.

**Comment by Kaitensatsuma** [comment]
I'd like to add comments to this: it is especially desirable when displaying bar charts that are meant to represent performance against a maximum, otherwise the automatic sizing creates visually misleading results.

since tickmode has an attached option to explicitly name tick points, perhaps adding another option to make them fixed would be a viable feature?

**Comment by cinkie** [comment]
This feature would also be very useful when using subplots. The upper limit can be the same in axis so we could compare more easily.

**Comment by beeblebrox** [comment]
+1.

I am using extendPlots on a larger data set in which I only want to show up to the last two days (xaxis) and using extendTraces. I do not want to limit the points as extendTraces can (it doesn't know dates and it drops points completely).  If range took null for one side I can envision extendTraces auto scrolling the xaxis as points are added always leaving the new points showing.

**Comment by rneuhausler** [comment]
Not sure if people are already doing this, but what's worked for me is using "[]" in place on the value I don't want to specify. Say I only want to set the lower limit to zero, I use **range = [0,[]]**. I'm using plotly in jupyter notebook, written in python 3.

**Comment by SaturnTeam** [comment]
I need this feature too! Sometimes I have only zero values and auto axis sets up to -1 to 1, but negative values are impossible for my data.

**Comment by etpinard** [comment]
> have only zero values and auto axis sets up to -1 to 1

Have you tried setting [`rangemode: 'nonnegative'`](https://plot.ly/javascript/reference/#layout-yaxis-rangemode)?

**Comment by SaturnTeam** [comment]
@etpinard Thanks. It's working

**Comment by bld2104** [comment]
Has anyone found another solution to this? I am using [custom controls with the update button](https://plot.ly/python/custom-buttons/#update-button) on a chart, so the y axis scale changes every time a user clicks a different control. Plotly's default maximum value for each of them is fine but I'd like the minimum to be lower so the plot is easier to see. I tried setting axes in the layout and assigning them to each trace, but instead of the axes swapping out when a user clicks the buttons, they just all show up at once on top of one another. 

```
layout_boxplots = go.Layout(margin=dict(t=50, b=50, l=150, r=50),    width=500,
    height=300,
    font=dict(family='Open Sans', size=14, color='#176db6'),
    showlegend=False,
    yaxis=dict(range=[-5, max(data1)]),
    yaxis2 = dict(range=[-5,max(data2)]),
    yaxis3 = dict(range=[-5,max(data3)]),
    updatemenus=updatemenus_boxplots
)
```

**Comment by phoenixlike** [comment]
Is there any updated way to achieve axis starting at 0?

**Comment by SaturnTeam** [comment]
@phoenixlike https://github.com/plotly/plotly.js/issues/400#issuecomment-353510549

**Comment by terrycojones** [comment]
+1 on adding this. Thanks!

**Comment by oliverbrace** [comment]
Did anything ever get done about this?

**Comment by MCM-Math** [comment]
Has there been any progress on this?

**Comment by thatneat** [comment]
@ravitshrivastav: this is stale, but as @etpinard pointed out, `rangemode: 'nonnegative'` seems to do the trick.

This covers the main use case for me.

**Comment by dylanhenson** [comment]
For anyone still wondering how to set the x or y axis's minimum value to zero, add the following to the `layout` object: 
`yaxis = list(rangemode = 'tozero')` or
`xaxis = list(rangemode = 'tozero')`

**Comment by terrycojones** [comment]
Thanks @dylanhenson! That's great. (I think you mean `dict` not `list` though.)

**Comment by dylanhenson** [comment]
> Thanks @dylanhenson! That's great. (I think you mean `dict` not `list` though.)

Sorry about that, I was writing this code in R, I just realized this thread is all javascript. Hopefully `rangemode = 'tozero'` still works!

**Comment by 19leunam93** [comment]
I would like to set a min range for axis. In order that the axis at least shows a range of the given value, also with enabled autorange (axis is shifting foreward, if new datapointa are inserted).

**Comment by acai-stripe** [comment]
Any updates on this? not setting specific upperbound/lowerbound would be great.
e.g. [0, largest data point) --> for specifying dates
set a minimum, auto stop at max data point

**Comment by aanchalvazir** [comment]
> 
> 
> @ravitshrivastav: this is stale, but as @etpinard pointed out, `rangemode: 'nonnegative'` seems to do the trick.
> 
> This covers the main use case for me.

Is there a way to restrict the y-axis to only negative values? I tried 'rangemode':'nonpositive' and 'rangemode':'negative' but these don't seem to work.
Thanks!

**Comment by nicolaskruchten** [comment]
@aanchalvazir can you provide a codepen or jsfiddle reproducing the issue you're seeing with `rangemode: 'nonnegative'` please in order for us to help you or to determine of this is a bug?

**Comment by alexcjohnson** [comment]
Sounds like @aanchalvazir is asking for the opposite of `'nonnegative'`: ONLY negative values.

**Comment by aanchalvazir** [comment]
> 
> 
> Sounds like @aanchalvazir is asking for the opposite of `'nonnegative'`: ONLY negative values.

Yes, correct. I don't mean to report a bug. I meant to ask if there is a similar approach for ONLY NEGATIVE values for y-axis in Plotly. I am unable to find a solution to that. On the contrary, a work around could be to fix the 'range' property for y-axis to something like : [-100,0] but what about cases where the lower limit (-100 in this case) is unknown?

**Comment by jackparmer** [comment]
This issue has been tagged with `NEEDS SPON$OR`

A [community PR](https://github.com/plotly/plotly.js/pulls?q=is%3Apr+is%3Aopen+label%3A%22type%3A+community%22) for this feature would certainly be welcome, but our experience is deeper features like this are difficult to complete without the Plotly maintainers leading the effort.

**Sponsorship range: $10k-$15k**

What Sponsorship includes:
- Completion of this feature to the Sponsor's satisfaction, in a manner coherent with the rest of the Plotly.js library and API
- Tests for this feature
- Long-term support (continued support of this feature in the latest version of Plotly.js)
- Documentation at [plotly.com/javascript](https://plotly.com/javascript/)
- Possibility of integrating this feature with Plotly Graphing Libraries (Python, R, F#, Julia, MATLAB, etc)
- Possibility of integrating this feature with Dash
- Feature announcement on [community.plotly.com](https://community.plotly.com/tag/announcements) with shout out to Sponsor (or can remain anonymous)
- Gratification of advancing the world's most downloaded, interactive scientific graphing libraries (>50M downloads across supported languages)

Please include the link to this issue when [contacting us](https://plotly.com/get-pricing/) to discuss.

**Comment by ievgennaida** [comment]
Same request to set axes separately from python backend

https://github.com/plotly/plotly.py/issues/3634

Proposal is to allow pass None if value should be automatically determined:
range=[2, None]

**Comment by fzyzcjy** [comment]
Hi is there any updates?

**Comment by shalvichirmade** [comment]
I found a way to set one side of the y axis by adding a transparent horizontal line. For example,
```
fig.add_hline(y=-0.3,
                       line_color="rgba(0,0,0,0)")
```
Hope this helps!
