### ISSUE TITLE
Print the running test names on CI

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#4001]
Currently the tests that are skipped are logged in blue lines; whereas for the actual running tests only a dot is printed out. 
As a result it looks almost impossible to figure out which tests are actually failing on the CI.

Why not logging the names of the tests that we run instead of those that are skipped?

![Screenshot from 2019-06-30 19-46-30](https://user-images.githubusercontent.com/33888540/60403814-f70cd800-9b6f-11e9-9429-33d68fc80683.png)

**Comment by etpinard** [comment]
You can try running the tests with `--verbose` 

https://github.com/plotly/plotly.js/blob/master/CONTRIBUTING.md#jasmine-tests

**Comment by etpinard** [comment]
We could also turned off 

https://github.com/plotly/plotly.js/blob/44633a13a3e022a4565d7b230b9db3e1e1ac83aa/test/jasmine/karma.conf.js#L265-L266

on CI if you prefer.

**Comment by etpinard** [comment]
@archmoj @antoinerg let me know if you prefer the test report off:

https://circleci.com/gh/plotly/plotly.js/43636#tests/containers/1

using commit https://github.com/plotly/plotly.js/commit/51b60fbe9d658019f49449e80f9250ee56e659b6

**Comment by antoinerg** [comment]
> @archmoj @antoinerg let me know if you prefer the test report off:
> 
> https://circleci.com/gh/plotly/plotly.js/43636#tests/containers/1
> 
> using commit [51b60fb](https://github.com/plotly/plotly.js/commit/51b60fbe9d658019f49449e80f9250ee56e659b6)

I don't mind it :)

**Comment by archmoj** [comment]
Love it!
