### ISSUE TITLE
sliders + addTraces bug

### ISSUE THREAD

**Issue by DaanyWaay** [plotly/plotly.js#4002]
If I add the traces manually the slider.steps[0] looses its arguments: https://codepen.io/anon/pen/ydMLyK

**Comment by etpinard** [comment]
Hi @DaanyWaay 

Using

```js
graph.on('plotly_sliderchange', (event) => {
  console.log(event.step.args);
})
```

as in https://codepen.io/etpinard/pen/PreaRY?editors=1010 seems to always give the correct `args` list.

**Comment by etpinard** [comment]
Related: https://github.com/plotly/plotly.js/issues/1704

**Comment by DaanyWaay** [comment]
Please notice that
`console.log(event.step.args);`
returns array of args as declared in sliders.steps but:
- the first item is always "visible" string - PASS
- the 2nd item is the array of values for step 2 and 3 - PASS
- the 2nd item is empty array for step 1 - FAILED
**It is not possible to show the red line.**

**Comment by etpinard** [comment]
> * the 2nd item is empty array for step 1 - FAILED
>   **It is not possible to show the red line.**

I don't understand what you're referring to here. Can I ask: what are you trying to accomplish with the slider event data?

**Comment by DaanyWaay** [comment]
What I want to accomplish is exactly what you see in that code pen. This new pen is a slightly modified version of the previous one:
https://codepen.io/anon/pen/ydMLyK
I appreciate if you could explain why I can not display the red line while scrolling the slider. The traces have to be added by `addTraces`.
Please check the console log while scrolling the slider:
- green: ["visible", Array(6)]
- blue: ["visible", Array(6)]
- **red: ["visible", Array(0)]**

This plot has exactly the same configuration and data and works OK: https://codepen.io/anon/pen/XLBGqq but I don't use addTraces there.

**Comment by etpinard** [comment]
Ah now I see it. Thanks for posting!
