### ISSUE TITLE
Legend and scatter sizes and positions when the plot is 'small'

### ISSUE THREAD

**Issue by Nauss** [plotly/plotly.js#4018]
Hi,

I use plotly with the user able to change the size of the plot with the mouse.
Doing this and playing with the graph options I came up with some probably wrong behavior.

When the plot is big enough, I get this [perfectly fine graph](https://codepen.io/Nauss/pen/gNjNOy)

When the plot gets smaller, I get [this](https://codepen.io/Nauss/pen/MMBdrw)

It seems the draw area size is computed with the legend **outside** but then the legend is display **inside**.

Any thought ?

**Comment by etpinard** [comment]
Essentially a duplicate of https://github.com/plotly/plotly.js/issues/771

Thanks for reporting!
