### ISSUE TITLE
Marimekko aka Mekko plot

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4019]
Placeholder issue for discussing the addition of this kind of trace. See also #2901 for a circular variant, #4020 for the more-than-two-level variant and #1038 for the general-purpose treemap variant.

Here's a representative example of what this could look like:

![image](https://user-images.githubusercontent.com/203523/60721500-2a4ac080-9efc-11e9-8976-ab93065d915a.png)

Note that this is quite bar-like with two continuous axes, but also has non-linear category labels above.

This one doesn't have a (visible) continuous x-axis: 

![image](https://user-images.githubusercontent.com/203523/60721583-6aaa3e80-9efc-11e9-947d-2a8e27c0205c.png)

**Comment by eddy-geek** [comment]
Here is an implementation based on @nicolaskruchten work on #4461 :

```python
def stacked_bar_width_plot(df, value_cols, width_col, **subplot):
    '''A stacked column plot with variable bar width.
       :param value_cols: columns of `df`, already normalized (sum=1 for every line).
       :param width_col: column of `df`, unbounded, used (i) as label (ii) to compute width.
       :param subplot: optional figure/row/col
    '''
    categories = df.index.to_list()
    width = df[width_col]
    htmpl = width_col + ': %{customdata}, %{y}'
    x = np.cumsum([0] + list(width[:-1]))
    
    figure = subplot.pop('figure', go.Figure())
    for col in value_cols:
        figure.add_trace(go.Bar(name=col, x=x, y=df[col], width=width, hovertemplate=htmpl, customdata=width, offset=0), **subplot)
    return figure.update_xaxes(
                tickvals=x+np.array(width)/2,
                ticktext=categories,
                range=[0, np.sum(width)], **subplot
            )\
            .update_yaxes(tickformat= ',.0%', range=[0,1], row=subplot.get('row'), col=subplot.get('col'))\
            .update_layout(barmode='stack', bargap=0) #, hovermode='x unified')


def mekko_plot(df, unit_name, **subplot):
    '''A mekko plot is a normalized stacked column plot with variable bar width.
       
       Assumptions:
       * `df` is already indexed by category: there will be one stacked-bar per line, labeled after the index.
       * total is the sum of `value_cols`.
       unit_name is visual only (e.g. "flight/s" or "bookings"). The rest (title..) is easily customized afterwards.
    '''
    # Normalize then defer to stacked_bar_width_plot plot.
    value_cols = df.columns
    w = pd.DataFrame({unit_name: df.sum(axis='columns')})
    w[value_cols] = df.div(w[unit_name], axis='index')
    
    return stacked_bar_width_plot(w, value_cols, width_col=unit_name, **subplot)

# Example
df = pd.DataFrame(dict(category=['a','a', 'b',  'b', 'a','a', 'b',  'b'],
                       var1=[9,2,5,3,2,4,6,0],
                       var2=[1,2,3,4,2,6,7,8])).set_index('category')
display(df)
mekko_plot(df, unit_name='some_label')
```

Display:
![image](https://user-images.githubusercontent.com/2772505/78920966-7f6fc000-7a94-11ea-82af-9fb8c396b79d.png)

**Comment by prodigeek** [comment]
Is there a way to assign a single color to a column in this code? I have a large mekko with many individual stacks - I'd rather have each column have a single color. Any suggestions?
Thanks!

**Comment by vpobleteacustica** [comment]
Many thanks, great job!

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
