### ISSUE TITLE
UI is extremely slow when using 'dot' or 'dashed' lines

### ISSUE THREAD

**Issue by ofirbit** [plotly/plotly.js#4025]
### Bug
I have a simple plot with one line and 500 points. Everything works perfect when the `dash` property of the line is not set (solid line). But, when setting the line type to `dot` or `dash` - UI performance becomes extremely slow. Just click 5 times on "zoom-in" the then try panning the chart, you'll notice how slow the line moves and how UI becomes much less responsive. This becomes extremely painful with larger charts and more than one line on the screen. I believe that's a major bug.

I really need the dashed/dotted lines feature. Is there any workaround until this will be fixed?

### CodePen example

https://codepen.io/anon/pen/EBeead
(just zoom in 5 times and then click pan and try moving the right/left/up/down)

### GIF demo

![slow_plotly_gif](https://user-images.githubusercontent.com/45560972/60754132-5a21c300-9fe5-11e9-82d2-7fd1d8b49e3c.gif)

Thanks.

**Comment by antoinerg** [comment]
Thank you @ofirbit for reporting this performance issue. I am not sure why this is happening but in the meantime, switching the trace type from `scatter` to `scattergl` will help.
