### ISSUE TITLE
Support for Atom download

### ISSUE THREAD

**Issue by wadethestealth** [plotly/plotly.js#4026]
Inside of Hydrogen (Atom Package), we use plotly.js to display plotly responses from a kernel. However inside atom, clicking links does not work the same as a normal browser. Therefore the download plot as png button does not behave as expected (it returns a success message and says the plot is downloaded, but it never actually is). I have code that could do the intended result, but that would require downloading your library modifying it and publishing the modified version. I would then have to continue to update as you guys update. So I prefer if I could have a way to support it natively.

```
const electron = require('electron');
electron.remote.getCurrentWebContents().downloadURL(insertCreatedUrlFromPlotly);
```

See nteract/hydrogen#1653 for example and original issue

**Comment by etpinard** [comment]
Hi @wadethestealth , thanks for writing in.

Have you tried using `Plotly.toImage`?

**Comment by wadethestealth** [comment]
Yes, but I still can't override the button event though because of the anonymous function

**Comment by etpinard** [comment]
You can try using our `modeBar` config options:

https://github.com/plotly/plotly.js/blob/46f4cfc663f067dfa164c2637ace6069b154b9ee/src/plot_api/plot_config.js#L260-L285

Here's one example: https://codepen.io/etpinard/pen/xoQGrb

**Comment by wadethestealth** [comment]
This looks very promising I'll try it out

**Comment by wadethestealth** [comment]
Works like a charm @etpinard. Thanks for the help 😄
