### ISSUE TITLE
zeroline is not visible when axis has no gridlines

### ISSUE THREAD

**Issue by DaanyWaay** [plotly/plotly.js#4027]
https://codepen.io/anon/pen/pXxqeW
zeroline is not visible if these conditions are met:
```
rangemode: 'tozero',
nticks: 1 (or 2)
```
If you change nticks to: 0 | 3 | 3+ it is shown again.
Unfortunately I need to hide all the ticks except tick0 as this configuration will be used for subplots.

The solution with mirror axis works better, but:
- line between subplots has 2px
- the tick is not directly under zeroline
https://codepen.io/anon/pen/OeBGjN

**Comment by etpinard** [comment]
Thanks for writing in!

At present, we don't draw the `ax.zeroline` line on axes that don't have any visible grid lines associated with them e.g. as in the `nticks: 1` or `nticks: 2` cases you pointed out (note also that `0` isn't a valid `nticks` values, so you get the default ticks in that case).

The logic is here:

https://github.com/plotly/plotly.js/blob/323e79a7f016c43ff7482c9751ff2ea24b60021e/src/plots/cartesian/axes.js#L2732-L2745

---

I can't remember exactly why the `ax._gridVals.length` condition exists. We may consider changing it and honouring `ax.zeroline: true` no matter what, but that would have to be part of a major version update (e.g. in our v2 release).

**Comment by etpinard** [comment]
On second thoughts, I'm starting to think this report should be considered a bug (thanks @alexcjohnson )

Removing

https://github.com/plotly/plotly.js/blob/323e79a7f016c43ff7482c9751ff2ea24b60021e/src/plots/cartesian/axes.js#L2738

does not make any of our tests fail.

The only problem I see is: as some axes `coerce('zeroline', true)`, according to the logic below

https://github.com/plotly/plotly.js/blob/674f0b0714190411006d6e16abb25752036a0e5e/src/plots/cartesian/line_grid_defaults.js#L56

a "new" zeroline will appear on some graphs. Now I agree that:

```js
xaxis: {
  zeroline: true,
  nticks: 1
}
```

should show the zeroline, even when it's on one of the plot area edges.

Would anyone be opposed to adding a `ax._input.zeroline` condition in here:

```js
 axes.shouldShowZeroLine = function(gd, ax, counterAxis) { 
     var rng = Lib.simpleMap(ax.range, ax.r2l); 
     return ( 
         (rng[0] * rng[1] <= 0) && 
         ax.zeroline && 
         (ax.type === 'linear' || ax.type === '-') && 
         (ax._gridVals.length || ax._input.zeroline) &&
         ( 
             clipEnds(ax, 0) || 
             !anyCounterAxLineAtZero(gd, ax, counterAxis, rng) || 
             hasBarsOrFill(gd, ax) 
         ) 
     ); 
 }; 
````

**Comment by alexcjohnson** [comment]
My gut reaction is if `zeroline` gets coerced true, we should show it in these edge cases too, not just when it’s explicitly set true. Is there a case where that would look wrong?

**Comment by etpinard** [comment]
I'm going to slip in a fix for this bug i.e. by simply removing

https://github.com/plotly/plotly.js/blob/323e79a7f016c43ff7482c9751ff2ea24b60021e/src/plots/cartesian/axes.js#L2738

in 1.50.0.
