### ISSUE TITLE
Lines disappear when displaying small numbers and large numbers are off screen

### ISSUE THREAD

**Issue by KenCoder** [plotly/plotly.js#403]
Can see this clearly here: https://plot.ly/~KenCoder/11/percent-vs-date/

Move your mouse in the middle of the chart  - the hover displays the data, but the line isn't visible. The cause seems to be a large value on 10/1/1924. Even though that value is off screen, it's messing up the rest of the points. Pressing auto-scale shows the large point (and the rest of the line) but reset axes reverts the error.

I believe this was introduced in the last few months, as these charts worked for us in a prior version of plotly.js

**Comment by etpinard** [comment]
Thanks for the bug report.

You are correct. This bug was introduced in [`v1.7.1`](https://github.com/plotly/plotly.js/releases/tag/v1.7.1) most likely in PR https://github.com/plotly/plotly.js/pull/353

Reproductible codepen: http://codepen.io/etpinard/pen/QNadEQ

**Comment by etpinard** [comment]
Converting the `x` values to JS dates does not solve the problem: http://codepen.io/etpinard/pen/vGpgJy

**Comment by myw** [comment]
I believe I have found a temporary workaround, mentioned in ginkgobioworks/plotly-plot#1: when using the javascript library and adding new traces, use `addTraces` instead of just setting `.data` and calling `Plotly.redraw`.

The use case in ginkgobioworks/plotly-plot#1 was for a 3D scatter plot, but the behavior was similar: the data that was much larger was entirely off-screen, and the plot did not adjust.

The difference seems to be that `Plotly.addTraces` calls a private method named `cleanData` before redrawing, but `Plotly.redraw` does not. Adding a call to `cleanData` before every redraw may fix the issue.

**Comment by etpinard** [comment]
@myw Hmm. I think you discovered a separate issue.

This issue here seems to be related to an overflow error somewhere. 

Would you mind filing a new issue that includes a reproducible example?

**Comment by myw** [comment]
@etpinard no problem

**Comment by myw** [comment]
@etpinard Seems like I am now unable to reproduce the behavior I was seeing earlier; maybe this has already been resolved recently? 

I have this [JSFiddle](https://jsfiddle.net/myw01/us5kq46f/) up just in case.

**Comment by etpinard** [comment]
@myw maybe ...

But this bug is still present in this codepen http://codepen.io/etpinard/pen/QNadEQ in the latest release.

**Comment by myw** [comment]
@etpinard Sorry, I was unclear. I meant that, per your suggestion that I discovered a separate issue, I opened a JSFiddle to try to reproduce the behavior _I_ was seeing. That behavior no longer seems to apply. As to the original issue, I didn't look into it, but yes, it does seem to still exist.

**Comment by mdfederici** [comment]
@etpinard is this still being looked at? I'm getting this as well and its reasonably painful.

**Comment by etpinard** [comment]
Not locked. But not actively develop either as far as I know. 

It has proven very hard to fix this bug while maintaining the specs added in https://github.com/plotly/plotly.js/pull/353

Maybe attempt to set a hard zoom limit (related to https://github.com/plotly/plotly.js/issues/887) on cartesian graphs instead?
