### ISSUE TITLE
BUG : scatterbar url not updated after newPlot/react on other url.

### ISSUE THREAD

**Issue by wandri** [plotly/plotly.js#4033]
When I have a Graph with a scatterbar in page `/test_1`  and after I go in page `/test_2` without reloading the whole page (Angular app) but I use newPlot or react for updating the graph, then the scatterbar isn't display correctly because the `<rect>` inside has a reference for `fill` to the url `/test_1`.

![graphs](https://user-images.githubusercontent.com/15016833/61042006-a26d2680-a3d3-11e9-93da-d001aa41450a.png)

Step : 

1. I'm in my url : `http://localhost:4200/modelling/e6e0cbe7-1719-47d3-af8e-e2061f247ccb`, The graph **1** is displayed correctly. The url in the fill is set correctly.

![work_url](https://user-images.githubusercontent.com/15016833/61042597-cda44580-a3d4-11e9-9594-4878208e3fc5.PNG)

2. I change the url to `http://localhost:4200/modelling/803e7203-dbdb-4c3e-bed3-8c00738ec3e4`, And I update the plotly graph with `react` method (when I use `newPlot`method, it doesn't work either) the graph **2** is displayed with a **wrong colorbar**. The url uses the **last url** and not the new one.

![no-work_url](https://user-images.githubusercontent.com/15016833/61042731-0e9c5a00-a3d5-11e9-9bed-ab49aa99fb21.PNG)

To help the contributors, 
`cbfill` is referenced [here](https://github.com/plotly/plotly.js/blob/b6edba5db568cda2ff246a12aa1552281c988fc8/src/snapshot/tosvg.js#L118) and [here](https://github.com/plotly/plotly.js/blob/66b2f400e62b70ef5e0b2fc3d21a549168caf2b0/src/components/colorbar/draw.js#L53)

EDIT : It's was done with : `"plotly.js-basic-dist": "^1.48.3"`

**Comment by etpinard** [comment]
Thanks for reporting.

Can someone try to replicate the problem in a control environment? For angular apps, sounds like https://stackblitz.com/ is working quite well.

**Comment by etpinard** [comment]
related: https://github.com/plotly/plotly.js/issues/3700

**Comment by wandri** [comment]
Here is an [example with stackblitz](https://stackblitz.com/edit/angular-4ckhyk).

The problem can be seen when we click on the buttons to change the route.

![error](https://user-images.githubusercontent.com/15016833/61058912-67c9b500-a3f8-11e9-845a-9bbf7dac6646.PNG)

**Comment by etpinard** [comment]
@wandri Looks like your app doesn't redraw the graph (e.g. it doesn't call `Plotly.newPlot()`) when switching URL. Can you confirm?

**Comment by etpinard** [comment]
`_baseUrl` (that we use to set the clippath urls) is set here:

https://github.com/plotly/plotly.js/blob/323e79a7f016c43ff7482c9751ff2ea24b60021e/src/plot_api/plot_api.js#L412-L416

should get updated on redraw.

**Comment by wandri** [comment]
@etpinard The function to redraw the graph is called in the htlm correctly. (see picture)

![called](https://user-images.githubusercontent.com/15016833/61103791-cb44f880-a473-11e9-8ddc-6376fe637513.PNG)

**Comment by wandri** [comment]
@etpinard You are right! If I instanciate my graph at the beginning and THEN I use react (which call the change url function), it works.

The deal here is to always gives a `config` with react to update the url.

**Comment by George35mk** [comment]
A quick workaround that fixed this issue on my angular 10 app.

```ts
public applyMacOsColorScaleFix() {
    if (this.data?.length >= 1 && this.data[0]?.type === 'heatmap') {
      const gradientsId = document.querySelector('.gradients linearGradient');
      const colorScaleRect: HTMLElement = document.querySelector('.cbfill');
      if (colorScaleRect) {
        colorScaleRect.setAttribute('style', `fill: url('${window.location.href}#${gradientsId.id}')`);
      }
    }
  }
```


```ts
public initPlot(data: Data[], layout: Layout) {
    if (this.data && Array.isArray(this.data) && this.layout) {

      this.plotly.newPlot(this.plotContainer.nativeElement, data, layout, {
        staticPlot: this.static
      });

      // Mac OS heatmap plot fix.
      this.applyMacOsColorScaleFix();

    } else {
      console.warn('Plot data or layout is invalid');
    }
  }
```
