### ISSUE TITLE
More modeBarButtons customization options

### ISSUE THREAD

**Issue by wadethestealth** [plotly/plotly.js#4036]
I am able to create, add, and remove a button on the `modebar`, however, I am unable to assign which group the button belongs to. Say my button was only meant for 3d plots, I would have no way of distinguishing that my button belongs to that group. I also have no way of ordering the button inside of that group without listing out every button that is shown.

I essentially want to replace a button, without changing the default ordering, but still make sure it only shows with the right plot types.

In my specific case I just want to exactly replace the function `toImage` button, not the location, the name, when it shows, the icon nothing

You can see #4026 where I was able to remove and create, but not order back to normal (camera button is added to the end of the bar rather than where it used to be)

**Comment by etpinard** [comment]
Thanks @wadethestealth for writing back - I had a feeling my answer in https://github.com/plotly/plotly.js/issues/4026#issuecomment-509231245 wouldn't be completely satisfactory. 

---

> I am unable to assign which group the button belongs to
> I essentially want to replace a button, without changing the default ordering

You're 100% correct. At present, plotly.js allows users:

- to appends buttons (in a new group between the rightmost button and the plotly logo)
- remove buttons (referencing the button names as found in [`components/modebar/buttons.js`](https://github.com/plotly/plotly.js/blob/master/src/components/modebar/buttons.js))
- create a button list from scratch

So, to "replace' one could create a new list in the `modeBarButtons` config options (see example: https://codepen.io/etpinard/pen/BgErvm), but then by creating this new list, we lose the per-subplot logic:

https://github.com/plotly/plotly.js/blob/14133af4fc205a7d00b158bb91e4afec845fd1d3/src/components/modebar/manage.js#L117-L173

that the default modebar goes through.

This is fare from ideal.

So, perhaps we could add a new config options called `modeBarButtonsToReplace` such that:

```js
{
  modeBarButtonsToReplace: [
    ['toImage' /* i.e. the name of the button to replace */, {
      click: function() { /* */ }
      // leaving 'icon' and 'title' intact
    }], 
   ['select2d', {
      title: 'Start rectangular selection'
      // just changing the icon title here
   }],
   // ...
  ]
}
```

**Comment by wadethestealth** [comment]
I think even without the replace you should be able to assign buttons and groups to plot types too. Like some features may only work with 2d plots or 3d but not vice versa

**Comment by jakublala** [comment]
I agree that this would indeed be helpful.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
