### ISSUE TITLE
How to Rotate Labels in a Sunburst Chart

### ISSUE THREAD

**Issue by parthhhh** [plotly/plotly.js#4039]
There seems to be no way of rotating the text inside of the sunburst chart. Is there a way of fixing all the text orientation for the labels radially? So it would look like this:

![Capture](https://user-images.githubusercontent.com/20375380/61086591-17e2f200-a3e8-11e9-8402-2d8415d26e8d.PNG)

**Comment by etpinard** [comment]
merged into https://github.com/plotly/plotly.js/issues/3590

pie and sunburst use the same code here, so that'll get this feature at the same time.
