### ISSUE TITLE
%V in tickformat is not formated as described in docs 

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#4040]
https://codepen.io/cpsievert/pen/qzvgVQ

Originated from https://github.com/ropensci/plotly/issues/1549

**Comment by etpinard** [comment]
Yeah that the wrong link in the schema.

`%V` was added in after the `d3@v4` module split ([ref](https://github.com/d3/d3-time-format/releases/tag/v2.1.0)). We're (still, unfortunately) using `d3@v3`.

This issue will get solved in https://github.com/plotly/plotly.js/issues/3052, closing. Thanks!
