### ISSUE TITLE
Stacked BarChart: Legend Click Event & Stacked Bar-Item Click Event

### ISSUE THREAD

**Issue by AdnanBoota** [plotly/plotly.js#4043]
Hi Team Plotly,
 
I want to develop some scenarios using stacked-histogram, but I am unable to achieve expected results. My scenarios are as follows:
 
1. legend-selection:  I need a legend-click event so that I can send an HTTP request based on what the user selected. Currently, this feature is available in PieChart, where I can use the Relayout event to identify what the user clicked. But, I cannot get the same information with stacked-histograms. I also looked into the legend-click event for stacked-histogram, but I did not succeed.
 
2. stacked-bar-click-event: If the user clicks on some stacked bar, I would like to identify which stacked element the user clicked on. For example, if I have 3 items stacked in a single bar, and the user clicks on the top-most element, I would like to get this information via the click-event, so that I can send an HTTP request.
 
I'm using this library in ReactJS, will the Plotly.js also update the ReactJS package, any suggestion on this?
 
Thank you very much for your help and the wonderful library!

Regards,
Adnan
![stacked-1](https://user-images.githubusercontent.com/14972616/61138768-4fc16680-a4c8-11e9-89c2-746577277d05.png)
![stacked-2](https://user-images.githubusercontent.com/14972616/61138769-5059fd00-a4c8-11e9-8e26-e4629f9c2b0d.png)

**Comment by etpinard** [comment]
Hi again @AdnanBoota 

> 1. legend-selection:

You can try using `plotly_legendclick`, see example https://plot.ly/javascript/plotlyjs-events/#legend-click-events


> 2\. stacked-bar-click-event:

We don't offer an easy way to do this at the moment, but you can read up https://github.com/plotly/plotly.js/issues/965 where some workaround have been proposed.

---

If you need help integration these feature in `react-plotly.js`, please use https://community.plot.ly/

Thank you.

**Comment by AdnanBoota** [comment]
Hi @etpinard ,

Thanks for your quick response!

`1. legend-selection` -> yes right i can capture this event, but still not able to get the clicked-item, is there any default way to get the click-item?

`2. stacked-bar-click-event`, i think if i can receive the clicked-item, this can solve my problem. Will try #965, but still it's like adding a new attribute (freetext)

Regards,
Adnan

**Comment by etpinard** [comment]
> is there any default way to get the click-item?

Here's how: https://codepen.io/etpinard/pen/gVYewZ?editors=1010

-----

As this ticket won't result in a PR, I'll close it. Please use https://community.plot.ly/c/plotly-js if you have any other implementation questions. That way others could benefit from it. Thanks again for writing in!
