### ISSUE TITLE
Countries missing in scope=africa

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4046]
In this plot  https://plot.ly/~nicolaskruchten/364 countries like Congo are white/missing but are highlighted in scope=world mode.

**Comment by nicolaskruchten** [comment]
Ah I found the problem: it's lakes! https://codepen.io/nicolaskruchten/pen/orRBKb?editors=0010

**Comment by etpinard** [comment]
Thanks for spotting that!

There must be a broken polygon in https://cdn.plot.ly/africa_110m.json and even in https://cdn.plot.ly/africa_50m.json (example https://codepen.io/etpinard/pen/YooNEm?editors=0010)

**Comment by nicolaskruchten** [comment]
This normally wouldn't show up so obviously but the new default Plotly template sets the lake color to white :)

**Comment by nicolaskruchten** [comment]
I would suggest adding a mock which contains one of each `scope` we have, with the various `show* = true` and `*color=<unique>`, so that we can more easily track regressions, and/or spot check for other such issues in the current set of polygons.
