### ISSUE TITLE
new simple shortcut for layout.mapbox.style: white-bg

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4051]
I propose another new shortcut value for `layout.mapbox.style` called `"white-bg"` with the following definition:

```
{
        "id": "white-bg",
        "version": 8,
        "sources": {},
        "layers": [
          {
            "id": "white-bg",
            "type": "background",
            "paint": {"background-color": "#FFFFFF"}
          }
        ]
      }
```

This would be useful in conjunction with #4050 when a user wants a very simple way to provide a layer to go under their data. They would provide `layout.mapbox.style: "white-bg"` and then some `data` and then something in `layout.mapbox.layers` with `below: traces`. If their layer is fully opaque (i.e. some raster tile-server) then the white background won't be visible, but it also won't make any API calls to any server.

**Comment by antoinerg** [comment]
Closed by https://github.com/plotly/plotly.js/pull/4068
