### ISSUE TITLE
Colorscale documentation typo

### ISSUE THREAD

**Issue by jonmmease** [plotly/plotly.js#4054]
Originally reported in https://github.com/plotly/plotly.py/pull/1657 by @jkaluzka.  There is a missing `]` character after the first element of the example colorscale description at

https://github.com/plotly/plotly.js/blob/adf9bee14a8badcb5b2f49065fd594623421c82e/src/components/colorscale/attributes.js#L197

**Comment by etpinard** [comment]
Good :eye: Thanks!
