### ISSUE TITLE
Problem with marker.line.width arrays containing scientific number strings

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#4057]
Scientific numbers in marker.line.width arrays may cause `bar` plot to fill the rest of plot in black!
[Codepen](https://codepen.io/MojtabaSamimi/pen/zgOXdJ?editors=0010).

**Comment by etpinard** [comment]
Good eye. Replacing `"1e1"` with `1e1` gives the correct result: https://codepen.io/etpinard/pen/KOPYJo?editors=0010

I wonder what we do elsewhere with exponent-notation inside strings (e.g. `"1e1"`). Do they even pass `isNumeric`?

**Comment by archmoj** [comment]
It is pretty strange. Only happens with `bar` and not with `histogram`, `funnel` or `waterfall`.
This might be a better [codepen](https://codepen.io/MojtabaSamimi/pen/oKvOOg?editors=0010) to illustrate the issue.

**Comment by archmoj** [comment]
A regression may be involved here since 1.29.0:
[Codepen](https://codepen.io/MojtabaSamimi/pen/dxbEpX?editors=1000).

**Comment by etpinard** [comment]
@archmoj wanna close this one too?

**Comment by archmoj** [comment]
No. In respect to https://github.com/plotly/plotly.js/pull/4056#discussion_r305034311 let's keep that open until we apply similar fixes (already applied for bars) for other traces.
