### ISSUE TITLE
mapbox token error message

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4059]
(Pulling https://github.com/plotly/plotly.js/pull/4035#discussion_r303095139 out into its own issue)

In the case when the `layout.mapbox.style` key is not set, and a mapbox token is not provided, I don't think the error message should say "you need a token". It should say "you need to provide a style". And then if the style is known to require a token, we can say "you need a token".

If a token is provided and no style is provided, then we should do the same thing we do right now: use "basic" as the default style.

**Comment by etpinard** [comment]
Here's the current state of affairs:

https://github.com/plotly/plotly.js/blob/218a9195832aab94b1d8bd0ca4653c159d2f25ce/test/jasmine/tests/mapbox_test.js#L242-L449

In brief,

- we log "Uses Mapbox map style, but did not set an access token" when trying to plot a mapbox base style w/o having set a token, and throw an error
- we throw an error, when a set access token is invalid
- We log "Listed mapbox access token(s) MAPBOX_ACCESS_TOKEN but did not use a Mapbox map style, ignoring token(s)." when a token is set for a non-Mapbox-server-style map.

**Comment by etpinard** [comment]
@nicolaskruchten I assume you want this for 1.49.0?

**Comment by nicolaskruchten** [comment]
yes for 1.49 unless the LOE is huge.

**Comment by etpinard** [comment]
OK, I'll push as part of https://github.com/plotly/plotly.js/pull/4035
