### ISSUE TITLE
Does plotly Scatter Plots on Mapbox support configuring map layer location name in Chinese

### ISSUE THREAD

**Issue by JashonHuang** [plotly/plotly.js#4065]
As i know , mapbox can support Chinese label of location in map layer.
As shown below
![image](https://user-images.githubusercontent.com/19502693/61348764-63881680-a894-11e9-9c45-f00846a14bba.png)

But when i read the plotly api documentation , it seems i can't find any configuration 
to configure map layer label in Chinese.

So, i wanna ask  if i can configure it via plotly ?

___________
Sincerely,
Jason Huang

**Comment by jonmmease** [comment]
Hi @JashonHuang, I transferred this issue to the plotly.js project as this is something that would need to be enabled in the JavaScript layer.

**Comment by JashonHuang** [comment]
> Hi @JashonHuang, I transferred this issue to the plotly.js project as this is something that would need to be enabled in the JavaScript layer.

Thanks, jonmmease. I have solved out this problem by passing a customized style url created in  Mapbox Studio  to the style parameter that plotly layout.mapbox needed. Finally , i can see what i wanted.
  

So,  maybe this issue can be closed.
