### ISSUE TITLE
Cannot read property 'hasOwnProperty' of undefined

### ISSUE THREAD

**Issue by fylworker** [plotly/plotly.js#4066]
I want to customize the contents of the variable in hovertemplate, but I am having a problem, this is to reproduce the link:

https://codepen.io/fylworker/pen/eqpvBZ

I am using it in the project. For me, this question is very urgent, I hope to get answers, thank you very much.

**Comment by etpinard** [comment]
Here's a working version: https://codepen.io/etpinard/pen/ymYjzN?editors=1010

`customdata` must have the same dimension as `z` for 2d-traces in order to be indexed into.

**Comment by fylworker** [comment]
@etpinard Cool! thank you very much.
