### ISSUE TITLE
Cone trace doesn't show any if double-up

### ISSUE THREAD

**Issue by lewisjb** [plotly/plotly.js#4072]
I found that if I have two cones at the same location, then no cones show up, and no error appears.

This also happens if they are just in close proximity, like 0.01 off

Reproducible example: https://codepen.io/anon/pen/KOVwYd?editors=0010

**Comment by etpinard** [comment]
Thanks for reporting!

That's probably our auto-size algorithm that's blowing up here. 

Trace coordinates like you have in https://codepen.io/anon/pen/KOVwYd?editors=0010, would be a good candidate for an `absolute` sizing mode as requested in https://github.com/plotly/plotly.js/issues/3613

**Comment by etpinard** [comment]
Assigning @archmoj

**Comment by archmoj** [comment]
@lewisjb would you mind testing this [codepen](https://codepen.io/MojtabaSamimi/pen/Poomedy?editors=0010) and with other input data?
Thanks!

**Comment by archmoj** [comment]
@etpinard FYI - here is my patch https://github.com/gl-vis/gl-cone3d/commit/3c7188f392a2a906ac8b6e52c1de7d78c0b45b3f, 
if that looks OK I can move forward and make a PR.

**Comment by etpinard** [comment]
Yeah, that looks ok to me. Does it cause any changes to the cone baselines?

**Comment by archmoj** [comment]
No change. The image test passed.

**Comment by etpinard** [comment]
Ok PR away :rocket:
