### ISSUE TITLE
Chart defaults to system font when exported

### ISSUE THREAD

**Issue by nibnob** [plotly/plotly.js#4077]
**Description**
It appears that exported charts do not respect the font family set in their layout. The SVG visual to the user _and_ the copy that the `convert` function passes to `svgToImg` both display the font correctly, but it appears the final canvas, from which the image is generated using `HTMLCanvasElement.toDataURL()`, does not.

**Minimal example**
Depending on the OS on which the export takes place, the canvas font will default to a system font. In the case of Open Sans, this is Times New Roman on Windows machines. Here's a CodePen that illustrates the problem using a very iconic font:

https://codepen.io/anon/pen/KOzRMr

Click the camera icon and you'll see that the titlefont of the exported image is different.

**What I've tried so far**

- Testing on multiple OSes and browsers: macOS, iOS, Linux Mint, Windows 7/8/10, Chrome, Safari, Firefox - they are all affected, but the font that is defaulted to differs between OSes.
- Serving the font from the same server to see if this is a CORS issue - no dice.
- Explicitly specifying the layout _again_  in the call to `toImage` - no dice.

Does anyone have a clue why this happens? Am I overlooking something, perhaps a workaround?

**Comment by etpinard** [comment]
Thanks for writing in.

Your observations seem to correspond to ours back in https://github.com/plotly/orca/issues/11

As far as I know, there's nothing plotly.js or users can do to workaround this problem in the front-end. That said, the last time we took a serious look at this issue was 2 years ago. Perhaps there's a way now.

**Comment by etpinard** [comment]
This ticket will likely not result in a PR in this repo, so I'll close it.

If someone has any potential workarounds or has ideas on how we should approach the problem, please comment in https://github.com/plotly/orca/issues/11
