### ISSUE TITLE
Parcoords plot causes out of memory error or browser hang if data is all zeroes

### ISSUE THREAD

**Issue by jonathonw** [plotly/plotly.js#4080]
Parallel coordinates plots cause browser out of memory errors (on Chrome) or browser hangs (on Firefox) if a dimension's values are all zeroes and the dimension's range is not specified or also set to `[0, 0]`.

Minimal example:  https://jsfiddle.net/JonathonW/p5rj2uv4/8/

This issue is not reproducible if the range is explicitly set (to something other than `[0, 0]`), or if the dimension's values are non-zero (even if they are the same--  `value: [1, 1]` does not cause the same problem).

**Comment by archmoj** [comment]
@jonathonw thanks for the report. 
This is a 1.49.0 regression as your example works with previous versions [codepen](https://codepen.io/MojtabaSamimi/pen/WVGRyo?editors=1000).
The browser stops here: https://github.com/plotly/plotly.js/blob/76f7652fe8d5369869f60e968f00a4a383d392ff/src/plots/cartesian/axes.js#L1373 possibly to avoid an infinite loop.
