### ISSUE TITLE
plotly_unhover not triggered in scattergeo

### ISSUE THREAD

**Issue by sieste** [plotly/plotly.js#409]
The `plotly_unhover` event is not triggered with `type:'scattergeo'`. I created a reproducible example here: [https://jsfiddle.net/sieste/ae3f624q/](https://jsfiddle.net/sieste/ae3f624q/)

**Comment by etpinard** [comment]
Oops. Looks like I forget to add `plotly_unhover` in https://github.com/plotly/plotly.js/pull/215.

Thanks!
