### ISSUE TITLE
Use surfacecolor, if defined, instead of z to color the contour lines

### ISSUE THREAD

**Issue by kapraran** [plotly/plotly.js#4097]
I suggest that when [usecolormap](https://plot.ly/javascript/reference/#surface-contours-x-usecolormap) in `surface.contours` is true, the lines should be colored using the `surfacecolor`, if defined, otherwise it will use the `colorscale` as a fallback.

[Demo](https://codepen.io/anon/pen/zgzzJx?editors=0010)

As you can see in the demo, i'd like the countours in the second scene to use the `surfacecolor` as a source for coloring instead of the default `colorscale` that they currently use.

Thanks in advance!

**Comment by etpinard** [comment]
I'd call that a bug. Thanks for reporting!

**Comment by etpinard** [comment]
Assigning @archmoj

**Comment by archmoj** [comment]
Not sure if this is a bug.
What is the issue [here](https://codepen.io/MojtabaSamimi/pen/poowYdd?editors=0010)?

**Comment by gpdonnarumma** [comment]
If is possible to get similar result on a surface in 3D space. As you can see in the image the contours are based on the color area (surfacecolor) not axes data
![IMG-20191126-WA0007](https://user-images.githubusercontent.com/25745069/70923602-698f4880-2028-11ea-9365-d9e28d603218.jpg)

**Comment by gpdonnarumma** [comment]
Hi,
sorry for disturbing you.

Is there any news about this feature?
Is possible to use "surfacecolor" data and not axis value to calculate contour line?

**Comment by archmoj** [comment]
> If is possible to get similar result on a surface in 3D space. As you can see in the image the contours are based on the color area (surfacecolor) not axes data
> ![IMG-20191126-WA0007](https://user-images.githubusercontent.com/25745069/70923602-698f4880-2028-11ea-9365-d9e28d603218.jpg)

@gpdonnarumma 
Is the image posted above relevant to this ticket?

**Comment by gpdonnarumma** [comment]
> > If is possible to get similar result on a surface in 3D space. As you can see in the image the contours are based on the color area (surfacecolor) not axes data
> > ![IMG-20191126-WA0007](https://user-images.githubusercontent.com/25745069/70923602-698f4880-2028-11ea-9365-d9e28d603218.jpg)
> 
> @gpdonnarumma
> Is the image posted above relevant to this ticket?

Yes, I hope.
It's an example of the result I want to obtain.
If I generate a Surface3D, is possible, using contour setting, draw the contour lines (as you can see in the image) taking as source the surfacecolor values and not the x/y/z values?

**Comment by archmoj** [comment]
@gpdonnarumma 
GitHub today had some down times. And I am not sure if you noticed my previous message.
Anyway I post it here again:
Until the bug is fixed one may consider using `opacityscale` feature as illustrated in this [demo](https://codepen.io/MojtabaSamimi/pen/QWjYRVV?editors=0010).

**Comment by gpdonnarumma** [comment]
Hi,
thank you for your help.
Opacityscale is not what I need... but I think that is a great feature.
I'll use it in other functions.

So I'm working on how to realize something like a contour series over a
surface3D serie.

@gpdonnarumma@gmail.com

**Comment by jackparmer** [comment]
This issue has been tagged with `NEEDS SPON$OR`

A [community PR](https://github.com/plotly/plotly.js/pulls?q=is%3Apr+is%3Aopen+label%3A%22type%3A+community%22) for this feature would certainly be welcome, but our experience is deeper features like this are difficult to complete without the Plotly maintainers leading the effort.

**Sponsorship range: $5k-$10k**

What Sponsorship includes:
- Completion of this feature to the Sponsor's satisfaction, in a manner coherent with the rest of the Plotly.js library and API
- Tests for this feature
- Long-term support (continued support of this feature in the latest version of Plotly.js)
- Documentation at [plotly.com/javascript](https://plotly.com/javascript/)
- Possibility of integrating this feature with Plotly Graphing Libraries (Python, R, F#, Julia, MATLAB, etc)
- Possibility of integrating this feature with Dash
- Feature announcement on [community.plotly.com](https://community.plotly.com/tag/announcements) with shout out to Sponsor (or can remain anonymous)
- Gratification of advancing the world's most downloaded, interactive scientific graphing libraries (>50M downloads across supported languages)

Please include the link to this issue when [contacting us](https://plotly.com/get-pricing/) to discuss.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
