### ISSUE TITLE
Warnings using scattergl in plotly.js

### ISSUE THREAD

**Issue by chickendinosaur** [plotly/plotly.js#411]
Fired up plotly.js and trying to use the webgl render types with some simple examples but when I do I get a stack limit of these warnings:

[.CommandBufferContext]RENDER WARNING: Render count or primcount is 0.

Any suggestions?

Here is the code:

'use strict';

var TESTER = document.getElementById('tester');

var trace1 = {
    x: ["2001-06-11 11:00", "2001-06-11 11:10", "2001-06-11 11:20", "2001-06-11 11:30", "2001-06-11 11:40", "2001-06-11 11:50", "2001-06-11 12:00", "2001-06-11 12:10", "2001-06-11 12:20", "2001-06-11 12:30", "2001-06-11 12:40", "2001-06-11 12:50", "2001-06-11 13:00", "2001-06-11 13:10", "2001-06-11 13:20", "2001-06-11 13:30", "2001-06-11 13:40", "2001-06-11 13:50", "2001-06-11 14:00", "2001-06-11 14:10", "2001-06-11 14:20", "2001-06-11 14:30", "2001-06-11 14:40", "2001-06-11 14:50", "2001-06-11 15:00", "2001-06-11 15:10", "2001-06-11 15:20", "2001-06-11 15:30", "2001-06-11 15:40", "2001-06-11 15:50", "2001-06-11 16:00", "2001-06-11 16:10", "2001-06-11 16:20", "2001-06-11 16:30", "2001-06-11 16:40", "2001-06-11 16:50", "2001-06-11 17:00", "2001-06-11 17:10", "2001-06-11 17:20", "2001-06-11 17:30", "2001-06-11 17:40", "2001-06-11 17:50", "2001-06-11 18:00", "2001-06-11 18:10", "2001-06-11 18:20", "2001-06-11 18:30", "2001-06-11 18:40", "2001-06-11 18:50", "2001-06-11 19:00", "2001-06-11 19:10", "2001-06-11 19:20", "2001-06-11 19:30", "2001-06-11 19:40", "2001-06-11 19:50", "2001-06-11 20:00", "2001-06-11 20:10", "2001-06-11 20:20", "2001-06-11 20:30", "2001-06-11 20:40", "2001-06-11 20:50", "2001-06-11 21:00", "2001-06-11 21:10", "2001-06-11 21:20", "2001-06-11 21:30", "2001-06-11 21:40", "2001-06-11 21:50", "2001-06-11 22:00", "2001-06-11 22:10", "2001-06-11 22:20", "2001-06-11 22:30", "2001-06-11 22:40", "2001-06-11 22:50", "2001-06-11 23:00", "2001-06-11 23:10", "2001-06-11 23:20", "2001-06-11 23:30", "2001-06-11 23:40", "2001-06-11 23:50", "2001-06-12 00:00", "2001-06-12 00:10", "2001-06-12 00:20", "2001-06-12 00:30", "2001-06-12 00:40", "2001-06-12 00:50", "2001-06-12 01:00", "2001-06-12 01:10", "2001-06-12 01:20", "2001-06-12 01:30", "2001-06-12 01:40", "2001-06-12 01:50", "2001-06-12 02:00", "2001-06-12 02:10", "2001-06-12 02:20", "2001-06-12 02:30", "2001-06-12 02:40", "2001-06-12 02:50", "2001-06-12 03:00", "2001-06-12 03:10", "2001-06-12 03:20", "2001-06-12 03:30", "2001-06-12 03:40", "2001-06-12 03:50", "2001-06-12 04:00", "2001-06-12 04:10", "2001-06-12 04:20", "2001-06-12 04:30", "2001-06-12 04:40", "2001-06-12 04:50", "2001-06-12 05:00", "2001-06-12 05:10", "2001-06-12 05:20", "2001-06-12 05:30", "2001-06-12 05:40", "2001-06-12 05:50", "2001-06-12 06:00", "2001-06-12 06:10", "2001-06-12 06:20", "2001-06-12 06:30", "2001-06-12 06:40", "2001-06-12 06:50", "2001-06-12 07:00", "2001-06-12 07:10", "2001-06-12 07:20", "2001-06-12 07:30", "2001-06-12 07:40", "2001-06-12 07:50", "2001-06-12 08:00", "2001-06-12 08:10", "2001-06-12 08:20", "2001-06-12 08:30", "2001-06-12 08:40", "2001-06-12 08:50", "2001-06-12 09:00", "2001-06-12 09:10", "2001-06-12 09:20", "2001-06-12 09:30", "2001-06-12 09:40", "2001-06-12 09:50", "2001-06-12 10:00", "2001-06-12 10:10", "2001-06-12 10:20", "2001-06-12 10:30", "2001-06-12 10:40", "2001-06-12 10:50", "2001-06-12 11:00", "2001-06-12 11:10", "2001-06-12 11:20", "2001-06-12 11:30", "2001-06-12 11:40", "2001-06-12 11:50", "2001-06-12 12:00", "2001-06-12 12:10", "2001-06-12 12:20", "2001-06-12 12:30", "2001-06-12 12:40", "2001-06-12 12:50", "2001-06-12 13:00", "2001-06-12 13:10", "2001-06-12 13:20", "2001-06-12 13:30", "2001-06-12 13:40", "2001-06-12 13:50", "2001-06-12 14:00", "2001-06-12 14:10", "2001-06-12 14:20", "2001-06-12 14:30", "2001-06-12 14:40", "2001-06-12 14:50", "2001-06-12 15:00", "2001-06-12 15:10", "2001-06-12 15:20", "2001-06-12 15:30", "2001-06-12 15:40", "2001-06-12 15:50", "2001-06-12 16:00", "2001-06-12 16:10", "2001-06-12 16:20", "2001-06-12 16:30", "2001-06-12 16:40", "2001-06-12 16:50", "2001-06-12 17:00", "2001-06-12 17:10", "2001-06-12 17:20", "2001-06-12 17:30", "2001-06-12 17:40", "2001-06-12 17:50", "2001-06-12 18:00", "2001-06-12 18:10", "2001-06-12 18:20", "2001-06-12 18:30", "2001-06-12 18:40", "2001-06-12 18:50", "2001-06-12 19:00", "2001-06-12 19:10", "2001-06-12 19:20", "2001-06-12 19:30", "2001-06-12 19:40", "2001-06-12 19:50", "2001-06-12 20:00", "2001-06-12 20:10", "2001-06-12 20:20", "2001-06-12 20:30", "2001-06-12 20:40", "2001-06-12 20:50", "2001-06-12 21:00", "2001-06-12 21:10", "2001-06-12 21:20", "2001-06-12 21:30", "2001-06-12 21:40", "2001-06-12 21:50", "2001-06-12 22:00", "2001-06-12 22:10", "2001-06-12 22:20", "2001-06-12 22:30", "2001-06-12 22:40", "2001-06-12 22:50", "2001-06-12 23:00", "2001-06-12 23:10", "2001-06-12 23:20", "2001-06-12 23:30", "2001-06-12 23:40"],
    y: [25.03, 24.98, 25.17, 24.03, 23.6, 27.5, 27.26, 25.87, 24.61, 19.66, 22.17, 23.16, 23.39, 22.9, 22.74, 26.09, 28.18, 28.04, 28.17, 28.27, 26.25, 27.37, 28.76, 29.63, 31.19, 27.72, 23.38, 22.46, 20.06, 18.92, 19.9, 18.68, 13.7, 19.22, 18.4, 18.09, 19.51, 19.39, 19.72, 19.74, 19.65, 20.12, 19.19, 20.63, 20.43, 17.73, 18.19, 18.64, 21.11, 19.32, 17.0, 15.69, 18.89, 18.63, 18.34, 20.16, 18.34, 17.77, 17.59, 20.65, 20.51, 21.82, 19.8, 17.92, 17.04, 17.38, 16.25, 17.37, 19.81, 16.51, 15.82, 15.25, 17.0, 16.18, 17.25, 16.49, 16.68, 17.99, 19.79, 18.13, 17.33, 16.96, 16.68, 18.04, 16.89, 17.23, 16.42, 17.19, 17.12, 17.49, 17.23, 16.99, 17.75, 17.28, 16.05, 17.95, 16.82, 15.92, 13.22, 13.46, 13.7, 14.12, 13.9, 13.96, 13.46, 11.01, 9.98, 10.52, 10.56, 8.11, 9.34, 8.92, 6.78, 5.97, 10.13, 9.83, 13.49, 16.87, 15.83, 16.88, 17.93, 22.86, 28.16, 22.89, 25.76, 16.44, 23.3, 31.12, 33.16, 34.22, 31.76, 29.42, 27.34, 22.21, 21.33, 14.02, 17.68, 16.69, 15.71, 13.53, 13.27, 21.97, 19.35, 20.44, 13.12, 19.15, 11.32, 28.03, 14.01, 18.39, 11.5, 17.93, 17.58, 15.31, 11.04, 14.26, 17.53, 20.88, 21.56, 22.75, 21.76, 24.13, 24.97, 25.59, 24.15, 27.2, 24.89, 25.95, 27.86, 27.05, 28.64, 30.59, 32.09, 30.84, 27.61, 28.89, 32.65, 32.32, 31.12, 31.03, 27.84, 30.64, 29.07, 30.56, 28.73, 32.56, 37.47, 36.98, 32.77, 33.9, 27.89, 28.64, 27.33, 27.65, 30.44, 29.05, 30.55, 31.09, 28.66, 29.42, 29.48, 29.21, 27.85, 27.86, 27.63, 27.71, 31.06, 29.51, 29.26, 30.22, 29.54, 29.13, 29.56, 27.64, 25.19, 24.19, 24.03, 23.34, 25.25, 23.58, 24.39],
    mode: "lines",
    name: "Upper Bound",
    type: "scattergl"
};

var data = [trace1];

var layout = {
    showlegend: false,
    title: "Continuous, variable value error bars. Notice the hover text!",
    yaxis: { title: "Wind speed (m/s)" }
};

Plotly.plot(TESTER, data, layout);

**Comment by etpinard** [comment]
What browser and which OS are you using?

**Comment by chickendinosaur** [comment]
This was using the latest Chrome browser and Windows 10.

**Comment by etpinard** [comment]
Problem fixed in [`gl-error2d`](https://www.npmjs.com/package/gl-error2d).
