### ISSUE TITLE
scattermapbox: text not displayed when using non-mapbox predefined styles

### ISSUE THREAD

**Issue by antoinerg** [plotly/plotly.js#4110]
In `scattermapbox`, when changing the style to a non-mapbox one, markers are still shown but not the text. Example Codepen: https://codepen.io/antoinerg/pen/ZgrYPw?editors=0010

Is that the expected behavior? Am I missing something?

**Comment by etpinard** [comment]
Thanks for spotting that. We get

![image](https://user-images.githubusercontent.com/6675409/62560981-2d630480-b84c-11e9-9c92-35f8ac24e439.png)

in the console, I'm not sure what we can do about it.

**Comment by etpinard** [comment]
cc @Mahdis-z

**Comment by emmanuelle** [comment]
Also reported on the forum https://community.plot.ly/t/scattermapbox-doesnt-work-with-marker-mode-as-text/35065/3

**Comment by wico-jourdan** [comment]
Same issue here
