### ISSUE TITLE
Support custom colorscales with rgba on surface traces

### ISSUE THREAD

**Issue by kapraran** [plotly/plotly.js#4120]
[Demo](https://codepen.io/iamnikosk93/pen/JgwyqG?editors=0010)

As you can see on the colorbar next to the plot, most of the surface should be transparent. Instead, it's colorized according to the rgb values of the rgba colorscale (completely ignoring the alpha).

I don't know if this is the expected behavior, but i guess that it's a bug.

Thanks

**Comment by archmoj** [comment]
@nikosk93 instead of `surface` have you ever tried using `mesh3d` trace?

**Comment by nikosk93** [comment]
No, i haven't. It seems a bit more complex than the surface one, but i'll give it a try.

**Comment by archmoj** [comment]
@nikosk93 here is a [codepen](https://codepen.io/MojtabaSamimi/pen/qeGdME?editors=0010) to give you an idea!

**Comment by nikosk93** [comment]
@archmoj  wow thanks for your help. 

I replicated it a bit by myself [here ](https://codepen.io/iamnikosk93/pen/rXgVmq?editors=0010) but i had trouble setting the colors. I'll check your pen!
