### ISSUE TITLE
scattergl: text arrays shorter than data arrays throws error

### ISSUE THREAD

**Issue by antoinerg** [plotly/plotly.js#4124]
Plotting the following gives an error:
```javascript
Plotly.newPlot(gd,[{
        "type": "scattergl",
        "mode": "markers+text",
        "x": [3, 2, 1, 0],
        "y": [0, 1, 4, 9],
        "text": ["1", "2", "3"],
        "textposition": "top center"
    }])
```
![Screenshot_2019-08-13_14-10-16](https://user-images.githubusercontent.com/301546/62968766-b7c1e000-bdd9-11e9-86f6-5e0c034b557c.png)

**Comment by etpinard** [comment]
See `scatter` version -> https://codepen.io/etpinard/pen/ZEzQRYR
