### ISSUE TITLE
Can't control yaxis rangemode, when there is no data

### ISSUE THREAD

**Issue by lifeparticle** [plotly/plotly.js#4129]
Hi,

I've noticed that if there is no data, you can not control the Y-Axis rangemode attribute, so it shows the negative portion.

Here is an example, where I've demonstrated both examples with data and without.
https://codepen.io/mahbubzaman/pen/LYPNbzP

Here is the link for the official documentation.
https://plot.ly/javascript/reference/#layout-yaxis-rangemode

Thanks.

Kind regards,
Zaman

**Comment by etpinard** [comment]
merged into https://github.com/plotly/plotly.js/issues/4137
