### ISSUE TITLE
Getting Cannot read property 'document' of undefined error

### ISSUE THREAD

**Issue by Arjun-Shinojiya** [plotly/plotly.js#4130]
I am trying to integrate plotly.js in my Angular 8 project. I successfully integrated it and tested it in local ,that time it is working fine without any error. But when I check it in live server ,that time I am **getting cannot read property 'document ' of undefined error.**.   I also similar issue blog in this [repository.`](https://github.com/plotly/plotly.js/issues/3518).I wanted to try this hack 
**changing line 27724 from }(); to }.apply(self); but this is just a hack :)**
But I dont know in which module file I can get this line.Currently none of the plotly.js file have 27724 lines

**Comment by etpinard** [comment]
Merged in https://github.com/plotly/plotly.js/issues/3518#issuecomment-521684610
