### ISSUE TITLE
mirror: "all" - all axis lines and ticks are mirrored

### ISSUE THREAD

**Issue by DaanyWaay** [plotly/plotly.js#4136]
Ticks should be mirrored only if "allticks" is selected.
https://codepen.io/pen/ZEzpYWY

**Comment by etpinard** [comment]
essential the bug part of https://github.com/plotly/plotly.js/issues/2539 - thanks very much for posting!

**Comment by thchr** [comment]
I noted this over in #4140 but realized it might make more sense to note it in this issue instead:

> This seems to still be be broken on v2.2.1: https://codepen.io/thchr/pen/eYWGjQM
> I.e., the tick marks are on both y-axes of the first subplot.
