### ISSUE TITLE
Annotations are not getting clipped when panning

### ISSUE THREAD

**Issue by marfoldi** [plotly/plotly.js#4141]
When panning the plot (using the 'Pan' tool or by dragging the axes) the annotations are not getting clipped until the action is finished.

https://codepen.io/plotly/pen/oXRjRJ

Under Windows on latest FF and Chrome.

**Comment by etpinard** [comment]
Looks like this is regression coming from https://github.com/plotly/plotly.js/commit/a8fb653ddca6dd00407b4362131ba2ceb3e6d511 part of `v1.40.0`

Things were working fine back in `v1.39.0`: https://codepen.io/etpinard/pen/NWKXEQL
