### ISSUE TITLE
Missing translation for "Download plot" in localization files

### ISSUE THREAD

**Issue by Batalex** [plotly/plotly.js#4142]
Hi,
I noticed that the localization files do not have the translation key "Download plot" (they have the legacy "Download plot as png"). I checked three of them (**fr**, **de**, & **es**), but maybe some of them do have this key.

I do not know how they were generated, but  if needed I would be glad to contribute on the french ones.

**Comment by etpinard** [comment]
This one got fixed in https://github.com/plotly/plotly.js/pull/4148
