### ISSUE TITLE
SVG Heatmaps

### ISSUE THREAD

**Issue by zbjornson** [plotly/plotly.js#4149]
Currently the color brick area of heatmaps is rendered using `data:` URLs. This makes it harder to produce high-quality exported images (especially for print) unless you're careful with how the image is resampled after exporting (difficult to do given that it's a PNG embedded in an SVG).

Would you consider using SVG instead, at least for `zsmooth=false`?

I made a quick patch to try this out. With a 50 x 200 brick heatmap, performance seems pretty close. I could turn this into a PR if it would be accepted.

**Comment by alyst** [comment]
I wanted a heatmap with a clearly visible grid. But enabling gaps between the tiles produces antialiasing artifacts, and the resulting grid doesn't look publication-ready, unfortunately.
Also the PDF version produced with Orca looks like vector-based interpretation of antialiasing.

I guess "rects" mode for the heatmap trace would have solved that.
The normal grid lines drawn on top of the gapless heatmap would have solved it even better, but I learned that it's not possible.

@zbjornson Can you publish your patch, please? That would be really helpful, at least for me!

**Comment by alyst** [comment]
An additional consideration why "rects" would be very useful: it's not possible to edit the pixel-based heatmap. E.g. if we want to manually introduce bigger gaps between the groups of X or Y axis categories in AdobeIllustrator.

**Comment by zbjornson** [comment]
@alyst my patch was a super rough one just for benchmarking and is far from usable, sorry. I'll be revisiting it within the next few months and will post or PR it if I can.

Using SVG rects might fix #888 as well, if the mouse event listeners are placed on the rects directly.
