### ISSUE TITLE
Axis animation with subplots leaks to other axis

### ISSUE THREAD

**Issue by EmanueI** [plotly/plotly.js#4153]
Every button here should only animate a single axis:
https://jsfiddle.net/9onwtvgu/

But clicking the first button also animates the second and third axis and clicking the second button also animates the third axis.

The problem seems to be that `editX` and `editY` are not initialised to `null` here:
https://github.com/plotly/plotly.js/blob/fbbcd20f65d1b61373d6625973a8885382816e82/src/plots/plots.js#L2424-L2436

The same problem might be found here as well (but not related to animations, I assume):
https://github.com/plotly/plotly.js/blob/fbbcd20f65d1b61373d6625973a8885382816e82/src/plots/plots.js#L2521-L2533

**Comment by etpinard** [comment]
Thanks for reporting!
