### ISSUE TITLE
Add new choroplethmapbox locationmode for geojson `properties.id`

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#4154]
It [seems like](https://github.com/plotly/plotly.js/pull/3988) choroplethmapbox traces support MultiPolygons geometry types, but this example fails without error/warning:

https://codepen.io/cpsievert/pen/KKPqgje

Perhaps I am missing something?

**Comment by cpsievert** [comment]
Interestingly, this same geojson file works as a `layout.mapbox.layers` -- https://codepen.io/cpsievert/pen/NWKgpzg

**Comment by etpinard** [comment]
Looks like that geojson 

https://gist.githubusercontent.com/cpsievert/66a06baaed96aa47e21ac02fd1d57efb/raw/8ee5ef67ac363910056f0c2aec896381c67a4d64/huh.json

doesn't set any feature `id` fields. It does set `properties.id`, but we unfortunately don't support extracting data for `properties.id` yet. It would be a nice addition to the library though.

**Comment by cpsievert** [comment]
Ahh, thanks for catching that!

**Comment by etpinard** [comment]
No problem @cpsievert - ok if I turned this into a `type: feature` ticket?

**Comment by cpsievert** [comment]
👍
