### ISSUE TITLE
Graph jumping left and right on double-click

### ISSUE THREAD

**Issue by TheJavaGuy** [plotly/plotly.js#4159]
If there's data of certain range in trace and we set range of X axis so that some data is outside this range, then on double-click graph will consecutively jump left and right. In other words, when the page is first loaded graph will show data only within X axis range as expected. Then, on first double-click it will show data in trace range (so, broader than X axis range). Then, on second double-click it will show data in X axis range again. Then, on third double-click it will show data in trace range again etc. ad infinitum. This creates jumping effect.

I think that expected behaviour is double-click should make the graph always show values in X axis range. If a user wants to see more data he should pan. Other possibility is that this is configurable in `layout` or `config` objects.

Demonstration of bug:
![plotly_doubleclick_jumping_bug](https://user-images.githubusercontent.com/11942401/64017848-e86c7e00-cb2a-11e9-93ef-d4b3922d77e2.gif)

Code is at https://codepen.io/thejavaguy/pen/xxKLxvY

**Comment by etpinard** [comment]
There's a config option for that 

https://github.com/plotly/plotly.js/blob/37e80cbc10ef8bf93b4dee1c1e7de043745da676/src/plot_api/plot_config.js#L160-L174

For example: https://codepen.io/etpinard/pen/BaBdKvx

**Comment by TheJavaGuy** [comment]
Wow, great! This solved my problem. Thank you @etpinard!
