### ISSUE TITLE
unhandled exception when using plotly-cartesian.js  with scatterternary

### ISSUE THREAD

**Issue by greg9504** [plotly/plotly.js#4164]
Hello,

When the "Toggle show closest data on hover" button is clicked there is an exception triggered in function getNextHover3d, approximately line 395.  sceneIds is undefined.

If I switch to the full dist, the exception does not occur. 
I noticed this in our app using Plotly version 1.48.3 of npm installed plotly.js-cartesian-dist, however it seems to be there with 1.49.4 as well.

Attached in the zip file is a simple html file with ternary plot that demonstrates the problem.  Open dev tools and you'll see the exception.

[Three.zip](https://github.com/plotly/plotly.js/files/3571976/Three.zip)

if you change the dist to point to https://cdnjs.cloudflare.com/ajax/libs/plotly.js/1.49.4/plotly.js the error does not occur.

**Comment by etpinard** [comment]
Thanks for the reports.

Looks like this

https://github.com/plotly/plotly.js/blob/b45304597ff639c7b9e38adf6a6b48efc47455af/src/components/modebar/buttons.js#L383

should have

```js
sceneIds = fullLayout._subplots.gl3d || [];
```

---------

Moreover, I wonder what `scatterternary` is doing in the cartesian bundle, maybe we take it out of there in v2.

**Comment by etpinard** [comment]
In a codepen: https://codepen.io/etpinard/pen/XWrEwrm
