### ISSUE TITLE
Blank text is not placed by texttemplate

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#4173]
[Codepen](https://codepen.io/MojtabaSamimi/pen/KKPQELB)

cc: @antoinerg

**Comment by archmoj** [comment]
I <i>think</i> this line 
https://github.com/plotly/plotly.js/blob/b5f0316f5c90e466a2a9009eeb876bee627e39c2/src/lib/index.js#L1159
should be 
```js
return v || v === '' || v === 0;
```

**Comment by etpinard** [comment]
OR this line:

https://github.com/plotly/plotly.js/blob/b5f0316f5c90e466a2a9009eeb876bee627e39c2/src/lib/index.js#L1051

**Comment by antoinerg** [comment]
@etpinard The function `templateFormatString` actually consider empty string a valid value:
https://github.com/plotly/plotly.js/blob/b5f0316f5c90e466a2a9009eeb876bee627e39c2/src/lib/index.js#L1044-L1047

The change proposed by @archmoj in https://github.com/plotly/plotly.js/issues/4173#issuecomment-529525001 fixes the issue. Hopefully, it doesn't break anything else. PR on the way

**Comment by etpinard** [comment]
Ok, but I would prefer not rendering `<text>` elements associated with `''` strings.

**Comment by antoinerg** [comment]
@archmoj It doesn't seem like the issue lies with the texttemplate routine itself but rather in how `sunburst` calls it.

Did you encounter this error with other traces than `sunburst`?

**Comment by antoinerg** [comment]
Ok so here are the traces affected:
- [ ] pie
- [ ] funnelarea
- [ ] sunburst
