### ISSUE TITLE
Display counted number of leaves/branches on sunburst/treemap using textinfo, texttemplate, hoverinfo and hovertemplate

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#4174]
[Codepen](https://codepen.io/MojtabaSamimi/pen/qBWxGGJ)

**Comment by etpinard** [comment]
I think the current behaviour makes sense when `value` isn't set.

**Comment by etpinard** [comment]
I'm not sure why anyone would want to show `1` in all the sectors

**Comment by archmoj** [comment]
I agree the ones (on leaves) may not be that useful; but the totals on branches are.
So, if you think the current behaviour is correct; we may possibly add another flag e.g. `count`?

**Comment by etpinard** [comment]
Adding `count` would be fine, yes.

**Comment by etpinard** [comment]
Will be part of https://github.com/plotly/plotly.js/pull/4185 - so adding this to the `1.50.0` milestone.

**Comment by archmoj** [comment]
So we should add a new key called `count`? Or using `value` key is fine?

**Comment by etpinard** [comment]
![image](https://user-images.githubusercontent.com/6675409/65447829-6576d480-de05-11e9-8038-7a7edacabf6d.png)

isn't it already there?

**Comment by archmoj** [comment]
Just modified the description.
