### ISSUE TITLE
Newest version of Plotly is not showing custom contour lines

### ISSUE THREAD

**Issue by Pman6543** [plotly/plotly.js#4175]
In the previous version of plotly the values of the contour lines on the plot would correspond to my colorbar levels tickvals, and in the most recent update it now displays them directly from z. 

How do I change it so that I can display custom contour lines or have my colorbar tickvals correspond to my contour line values.

**Comment by etpinard** [comment]
Hmm, I'm not sure what could have changed the behavior.

Would you mind sharing a reproducible example to help us debug?

**Comment by Pman6543** [comment]
var data = [ {
		  z: [[10, 10.625, 12.5, 15.625, 20],
			  [5.625, 6.25, 8.125, 11.25, 15.625],
			  [2.5, 3.125, 5.0, 8.125, 12.5],
			  [0.625, 1.25, 3.125, 6.25, 10.625],
			  [0, 0.625, 2.5, 5.625, 10]],
		  type: 'contour',
		  contours: {
			coloring: 'heatmap',
			showlabels: true,
			labelfont: {
			  family: 'Raleway',
			  size: 12,
			  color: 'white',
			}
		  }, 
		  colorbar: {
			tickvals: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
			ticktext: [1, 22, 34, 5, 6,77, 88, 99, 10101]
		  },
		}];

		var layout = {
		  title: 'Contour with Labels'
		}

		Plotly.newPlot('myDiv', data, layout);

This example will not display the ticktext as the contour line values with the current version of plotly, but it will on a version that I have dated from back in February 2019.

**Comment by Pman6543** [comment]
![test](https://user-images.githubusercontent.com/22284591/64541930-aee8ff00-d2f0-11e9-8bea-86d8b1437298.PNG)
^Old version of plotly

![test](https://user-images.githubusercontent.com/22284591/64542044-da6be980-d2f0-11e9-965c-56f43116907f.PNG)
^Newest version of plotly

Same code

**Comment by etpinard** [comment]
In codepens,

current: https://codepen.io/etpinard/pen/oNvqgGY
v1.47.4 (last working version): https://codepen.io/etpinard/pen/MWgVYEd

Thanks very much for reporting!

Something must have gone wrong during the shard coloraxis push https://github.com/plotly/plotly.js/pull/3786 / https://github.com/plotly/plotly.js/pull/3803
