### ISSUE TITLE
Plotly with vue and API

### ISSUE THREAD

**Issue by ddiegommachado** [plotly/plotly.js#4183]
Hi everyone,

I need mount a graph with data of the a API. I'm using https://github.com/statnett/vue-plotly
My code is:
```
<vue-plotly :data="data" :layout="layout" :options="options" />
<script>
import axios from "axios";
import VuePlotly from "@statnett/vue-plotly";

export default {
  components: {
    VuePlotly
  },
  data() {
    return {
      fields: [],
      data: [{ x: [], y: [] }],
      layout: {},
      options: {},
      responsive: true
    };
  },
  mounted() {
    var url = "http://www.mocky.io/v2/5d77aa2f3200005b00923f71";

    axios.get(url).then(r => {
      this.fields = r.data.fields;
    });
  }
};
</script>
```

How make this?

**Comment by etpinard** [comment]
Closing.

No plotly.js team member has experience with Vue.js, so we won't attempt to answer your question here.

Maybe try reaching to https://github.com/statnett/vue-plotly or to the folks that have shown interest in https://github.com/plotly/plotly.js/issues/2691

Cheers!
