### ISSUE TITLE
t.split issue with choroplethmapbox on hover

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.js#4194]
- `geojson` - https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json
- dataset: https://gist.github.com/chriddyp/c1ef87321f4efc567bb9f59fba8e9544
- `locations` - the "ZIP Code" column
- `z` - the 'Complaint ID' column

It renders fine, but the hover info isn't appearing.

![image](https://user-images.githubusercontent.com/1280389/65001659-7207a400-d8be-11e9-8f05-572767ef466c.png)

Traceback: 
![image](https://user-images.githubusercontent.com/1280389/65001688-91063600-d8be-11e9-8e3b-b1219ddcd6f1.png)

**Comment by chriddyp** [comment]
plotly.js 1.49.4

**Comment by etpinard** [comment]
Reproducible codepen: https://codepen.io/etpinard/pen/pozOKjL?editors=1010

Thanks for reporting!

**Comment by chriddyp** [comment]
thanks @etpinard! :raised_hands:
