### ISSUE TITLE
Problem adding/removing mapbox layers via Plotly.react

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#4196]
From https://codepen.io/nicolaskruchten/pen/pOVLop

Couple ways to hit the problem:

- step 0 -> step 1 -> step 2 -> step 3 fails
- step 0 -> step 1 -> step 0 fails

**Comment by etpinard** [comment]
@nicolaskruchten 

Looks like `Plotly.react` doesn't clear the rejected promises before plotting.

Adding 

```js
        var gd = document.getElementById('gd')
        gd._promises = [];
```

before the `Plotly.react` call to the above codepen (see https://codepen.io/etpinard/pen/oNvPRGX?editors=1010) appears to fix the "figure getting wedged" problem. Note that the console errors are still there.

This is a general `Plotly.react` bug. `restyle`, `relayout` and `update` all call 

https://github.com/plotly/plotly.js/blob/832590bb9f2c837058e96c2777d27e5f504921a0/src/plot_api/helpers.js#L24-L31

before attempting a redraw. 

---

Now we could also do a better job at identifying bad mapbox layout layer inputs like

```js
Plotly.newPlot(gd, [{type: 'scattermapbox'}], {
  mapbox: {
    layers: [{
      sourcetype: 'raster',
      source: ['']
    }]
  }
})
```

which will of course fail at fetch time.

----

Moreover, 

```js
Plotly.newPlot(gd, [{type: 'scattermapbox'}], {
  mapbox: {
    layers: [{}]
  }
})
.then(gd => {
  Plotly.react(gd, [{type: 'scattermapbox'}], {
    mapbox: {
      layers: []
    }
  })
})
```

should not fail.

**Comment by nicolaskruchten** [comment]
Ah ok, that's helpful, thanks very much!

**Comment by etpinard** [comment]
-> https://codepen.io/etpinard/pen/qBWMzoj is now error and "wedge" free.
