### ISSUE TITLE
[BUG] data[type=contour].autocontour not working with restyle

### ISSUE THREAD

**Issue by mafar** [plotly/plotly.js#4201]
**CodePen:**  https://codepen.io/mafar/pen/XWrxarp?editors=0010
This pen is bare minimum for bug reproduction

**Explaination:** https://plot.ly/javascript/reference/#contour
**Initial data** see below
1. Define data with ```autocontour:true``` 
1. Define ```contours``` start,end and size option even they will be ignored because of ```autocontour:true``` 

Once plot is drawn , restlye it with 
```js
var update = {
  autocontour: false,
  "contours.start": 3 
};
Plotly.restyle("myDiv", update, 0);
```
**But plot does not update !!! as expected** where it should have used contours.start end and size values

**Code:**
```js
var data = [
  {
    z: [
      [10, 10.625, 12.5, 15.625, 20],
      [5.625, 6.25, 8.125, 11.25, 15.625],
      [2.5, 3.125, 5, 8.125, 12.5],
      [0.625, 1.25, 3.125, 6.25, 10.625],
      [0, 0.625, 2.5, 5.625, 10]
    ],
    type: "contour",
    ncontours: 15,
    autocontour: true,
    contours: {
      start: 1,
      end: 5,
      size: 1
    }
  }
];
var layout = {
  title: Contours"
};
Plotly.newPlot("myDiv", data, layout);
var update = {
  autocontour: false,
  "contours.start": 3 
};
Plotly.restyle("myDiv", update, 0);

```

**Comment by etpinard** [comment]
Writing down a similar play-by-play as in https://github.com/plotly/plotly.js/issues/4199#issuecomment-532745501 for this report:

```js
Plotly.newPlot(gd, [
  {
    z: [
      [10, 10.625, 12.5, 15.625, 20],
      [5.625, 6.25, 8.125, 11.25, 15.625],
      [2.5, 3.125, 5, 8.125, 12.5],
      [0.625, 1.25, 3.125, 6.25, 10.625],
      [0, 0.625, 2.5, 5.625, 10]
    ],
    type: "contour",
    ncontours: 15,
    autocontour: true,
    contours: {
      start: 1,
      end: 5,
      size: 1
    }
  }
])

// gives (the auto contours)
gd.data[0].contours // => {start: 2, end: 18, size: 2}

// then
Plotly.restyle(gd, { autocontour: false, "contours.start": 3 })
// gives
gd.data[0].contours // => {start: 3, end: 18, size: 2}
// ... keeping the previous auto contours value and 
//     ignoring the starting {start: 1, end: 5, size: 1} settings
```

**Comment by etpinard** [comment]
As this bug has the same cause and will be solved at the same time as https://github.com/plotly/plotly.js/issues/4199 - I'll merge the two tickets together.

Thanks again @mafar for the very clear bug reports! Cheers

**Comment by mafar** [comment]
One additional comment:
Toggle of ``` autocontour``` should work ,which it currently does not

Turn on manual contour settings
```js Plotly.restyle(gd, { autocontour: false })```

Turn on autocontour which will consume```ncontours``` value (default is 15 anyway)
```js Plotly.restyle(gd, { autocontour: true})```
