### ISSUE TITLE
[Bug] data[type=contour].line width documentation typo

### ISSUE THREAD

**Issue by mafar** [plotly/plotly.js#4203]
As per my tests , it seems that 
for ```data[type=contour].line.width```
default value is ```0.5``` instead of documented ```2```

 https://plot.ly/javascript/reference/#contour-line-width

**Comment by etpinard** [comment]
Thanks for reporting!

Here are the relevant lines in case someone would like to make a PR:

https://github.com/plotly/plotly.js/blob/56f6983360febe9d5b3bf7427ada9863c372561a/src/traces/contour/attributes.js#L242-L244

https://github.com/plotly/plotly.js/blob/56f6983360febe9d5b3bf7427ada9863c372561a/src/traces/contour/style_defaults.js#L25
