### ISSUE TITLE
streamtube coloring and positions depend on data order

### ISSUE THREAD

**Issue by emmanuelle** [plotly/plotly.js#4206]
````
var gd = document.getElementById('graphDiv');

var type = 'streamtube';

var allX = [];
var allY = [];
var allZ = [];
var allU = [];
var allV = [];
var allW = [];

var res = 10;
var ni = res;
var nj = res;
var nk = res;
var i, j, k;

for(var k = 0; k < nk; k++) {
    for(var j = 0; j < nj; j++) {
      for(var i = 0; i < ni; i++) {
            var x = i;
            var y = j;
            var z = k;

            allX.push(x);
            allY.push(y);
            allZ.push(z);

            var u = 0;
            var v = 0;
            var w = z;

            allU.push(u);
            allV.push(v);
            allW.push(w);

        }
    }
}

var allX2 = [];
var allY2 = [];
var allZ2 = [];
var allU2 = [];
var allV2 = [];
var allW2 = [];

for(var k = 0; k < nk; k++) {
    for(var j = 0; j < nj; j++) {
      for(var i = 0; i < ni; i++) {
            var x = k;
            var y = j;
            var z = i;

            allX2.push(x);
            allY2.push(y);
            allZ2.push(z);

            var u = 0;
            var v = 0;
            var w = z;

            allU2.push(u);
            allV2.push(v);
            allW2.push(w);

        }
    }
}

Plotly.newPlot(gd, {
  data:  [{
    type: type,
    x: allX,
    y: allY,
    z: allZ,
    u: allU,
    v: allV,
    w: allW,
    scene: 'scene1'
  },
  {
    type: type,
    x: allX2,
    y: allY2,
    z: allZ2,
    u: allU2,
    v: allV2,
    w: allW2,
    scene: 'scene2'
  },
],
  layout: {
    width: 1200,
    height: 600,
    scene1: {
      domain: {
        x: [0, 0.45]
      }
    },
    scene2: {
      domain: {
        x: [0.5, 0.95]
      }
    },
  }
}
);
````

![newplot(2)](https://user-images.githubusercontent.com/263366/65256210-29720580-dacd-11e9-869a-c4fe81b7c60c.png)

A codepen is available on https://codepen.io/emmanuelle-plotly/pen/PoYxZQv?editors=0010

I would not expect the viz to depend on whether `x` or `z` is the fastest varying variable.

**Comment by archmoj** [comment]
In addition to `color` it looks there is a bug in the positions!
In your codepen if I change the trace type from `streamtube` to `cone`, it displays the full correct data.
[Demo](https://codepen.io/MojtabaSamimi/pen/RwbqGxE?editors=0010)

**Comment by archmoj** [comment]
Not sure about the `cone` plot sizes even: [codepen](https://codepen.io/MojtabaSamimi/pen/abbzprd?editors=0010)

**Comment by etpinard** [comment]
> Not sure about the `cone` plot sizes even: [codepen](https://codepen.io/MojtabaSamimi/pen/abbzprd?editors=0010)

See https://github.com/plotly/plotly.js/issues/3613 for that.

**Comment by archmoj** [comment]
It appears that `gl-streamtube3d` module makes false assumption about the order of data!
https://github.com/gl-vis/gl-streamtube3d/blob/533bf21665b8849542756402ffc0800b932cffec/streamtube.js#L242-L249

**Comment by etpinard** [comment]
Nice find @archmoj !

**Comment by archmoj** [comment]
@emmanuelle what do you think of this fix?
[codepen](https://codepen.io/MojtabaSamimi/pen/rNNOJwj?editors=0010)
Do the normals make sense e.g. when compared with `cone`.

**Comment by archmoj** [comment]
Here is another example to help test changes.
[codepen](https://codepen.io/MojtabaSamimi/pen/mddeXqa?editors=0010)

**Comment by emmanuelle** [comment]
Thank you @archmoj it looks good now :-)
