### ISSUE TITLE
Missing dependency in package.json

### ISSUE THREAD

**Issue by wolfd** [plotly/plotly.js#4207]
`color-rgba` should be included in dependencies:

https://github.com/plotly/plotly.js/blob/56f6983360febe9d5b3bf7427ada9863c372561a/src/traces/parcoords/parcoords.js#L12

I suspect this is a [phantom dependency](https://rushjs.io/pages/advanced/phantom_deps/), as it almost certainly exists in a dependency of plotly.js.

**Comment by alexcjohnson** [comment]
Oh parcoords... you're quite right:
```
plotly.js@1.49.4 /Users/alex/plotly/plotly.js
├─┬ color-normalize@1.5.0
│ └── color-rgba@2.1.1 
└─┬ regl-scatter2d@3.1.5
  └── color-rgba@2.1.1  deduped
```
Now, add it to `package.json`, or switch the usage to `tinycolor2` like we use everywhere else?
