### ISSUE TITLE
Radar Chart in a Partial Bundle (React)

### ISSUE THREAD

**Issue by peterwiebe** [plotly/plotly.js#4217]
Is there a way to use Radar Charts with partial bundles? I don't see any of the smaller bundles supporting `scatterpolar` as a type. If not, is there something that I can do to get it supported?

I created a demo of what I am experiencing here:
https://codesandbox.io/embed/plotly-partial-bundle-radar-chart-demo-s8etb

One of things that I tried doing was importing the _scatterpolar_ chart from `plotly.js/lib/scatterpolar` but that gives me the error:
`TypeError: Plotly.react is not a function`

when I then do:
```js
const Plot = createPlotlyComponent(scatterpolarPlot)
```

**Comment by etpinard** [comment]
https://github.com/plotly/plotly.js#modules has some info on the topic. If you see have questions about making custom bundles, please use https://community.plot.ly/c/plotly-js
