### ISSUE TITLE
Box plot boundary calculations

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4220]
a) An option to choose the calculation method for quartiles from one of the following
algorithms. The algorithms can also be found on the [Wikipedia Page on quartiles](https://en.wikipedia.org/wiki/Quartile)

  * Excel QUARTILE.EXC() Function / Wikipedia method 1
    Use the median to divide the ordered data set into two halves.
    o If there is an odd number of data points in the original ordered data set, do not
    include the median (the central value in the ordered list) in either half.
    o If there is an even number of data points in the original ordered data set, split this
    data set exactly in half.
    The lower quartile value is the median of the lower half of the data. The upper quartile
    value is the median of the upper half of the data.

  * Excel QUARTILE.INC() Function / Wikipedia method 2
    Use the median to divide the ordered data set into two halves.
    o If there are an odd number of data points in the original ordered data set, include the
    median (the central value in the ordered list) in both halves.
    o If there are an even number of data points in the original ordered data set, split this data
    set exactly in half.
    The lower quartile value is the median of the lower half of the data. The upper quartile value
    is the median of the upper half of the data.

  * Matlab algorithm / Wikipedia method 3:
    i. If there are even numbers of data points, then Method 3 is the same as either method
    above
    ii. If there are (4n+1) data points, then the lower quartile is 25% of the nth data value plus
    75% of the (n+1)th data value; the upper quartile is 75% of the (3n+1)th data point plus
    25% of the (3n+2)th data point.
    iii. If there are (4n+3) data points, then the lower quartile is 75% of the (n+1)th data value
    plus 25% of the (n+2)th data value; the upper quartile is 25% of the (3n+2)th data point
    plus 75% of the (3n+3)th data point.

~b) Plotly should offer an option to manually provide the minimum, median and maximum value as well as the quartiles for the Box plot.~ ->  #1059

**Comment by etpinard** [comment]
> b) Plotly should offer an option to manually provide the minimum, median and maximum value as well as
> the quartiles for the Box plot.

This piece got requested in https://github.com/plotly/plotly.js/issues/1059 - I'll leave them as separate issues.

**Comment by etpinard** [comment]
I'm thinking of adding a new enumerated attribute to `box` traces called `quartilemethod`. 

Now, does anyone have a strong opinion on how to call each of the three new methods as well as the our current (default) method?

Using as reference:

- http://jse.amstat.org/v14n3/langford.html
- https://en.wikipedia.org/wiki/Quartile

We could say:

- method 1 -> `'inclusive'`
- method 2 -> `'exclusive'`
- method 3 -> this one seems to be a combination of the "Vining" and “J&F”  method listed on http://jse.amstat.org/v14n3/langford.html
- our current method  -> `'m&s'` (from http://jse.amstat.org/v14n3/langford.html - I think)

**Comment by etpinard** [comment]
Note that also the computed Q1 and Q3 are also used in violin traces to compute the Inter-Quartile-Range then used to compute (1) the default bandwidth using [Silverman's Rule](https://github.com/plotly/plotly.js/blob/75d007e71c6d04ddb2caf54ac05622cc3ce74717/src/traces/violin/calc.js#L103-L106) and (2) determine with sample points are outliers.

I don't think exposing `quartilemethod` to violin traces is necessary nor very useful, but please let me know if you disagree.

**Comment by alexcjohnson** [comment]
`'inclusive'` and `'exclusive'` seem fine as names - they do seem to be the accepted names, despite the somewhat counterintuitive result that "inclusive" has a smaller IQR (ie it includes fewer data points between Q1 and Q3) than "exclusive".

The third method I'd propose we name `'linear'`.

AFAICT our method *is* Wikipedia method 3, which is also Langford # 10, `'H&L-2'` - anyway if I replicate the data sets from Langford Table 2 `[1,2,3,4]` through `[1,2,3,4,5,6,7]` in our box plot it matches row 10.

If I look at Matlab's [quantile reference page](https://www.mathworks.com/help/stats/quantile.html#btf91zm) I believe that *also* describes exactly our algorithm, generalized to arbitrary fractions:

> 1. The sorted elements in X are taken as the (0.5/n), (1.5/n), ..., ([n – 0.5]/n) quantiles
> 2. quantile uses Linear Interpolation to compute quantiles for probabilities between (0.5/n) and ([n – 0.5]/n)

I can't see specifically what they do for boxplot quartiles but I'd tend to assume it should match their quantile function.

I also see this [Matlab dataviz toolbox quartile function](https://in.mathworks.com/matlabcentral/mlc-downloads/downloads/submissions/53789/versions/5/previews/dataviz_toolbox/dvt/html/quartile.html) showing `[0,10,20,30,40]` having quartiles 10, 20, 30 - which would correspond to Langford methods 1 (inclusive),3,4,5,7 or 12... but that looks like a 3rd-party thing.

BTW according to Langford "Excel" is method 12, which in the language of the Matlab description would be:

> 1. The sorted elements of X are taken as the 0, 1/(n-1), 2/(n-1), ...(n-1)/(n-1)==1 quantiles

(which I'll note gives a consistently smaller IQR than any other method) But as Excel apparently [can only fake box plots](https://support.office.com/en-us/article/create-a-box-plot-10204530-8cdf-40fe-a711-2eb9785e510f) I guess Langford is describing obsolete versions of Excel.

**Comment by etpinard** [comment]
from @alexcjohnson 

> test datasets for box plot algorithms - seems to me the collection used in the langford paper is ideal: [1,2,3,4], [1,2,3,4,5], [1,2,3,4,5,6], and [1,2,3,4,5,6,7] - this gives all the degrees of freedom necessary to distinguish all of the algorithms anyone uses, with data that’s extremely easy to wrap your head around and verify the calculations manually.

**Comment by etpinard** [comment]
> AFAICT our method _is_ Wikipedia method 3, which is also Langford # 10, `'H&L-2'`

I can confirm this is correct.

So, looks like we only need two new methods and the new `quartilemethod` attribute would be declared as:

```js
    quartilemethod: {
        valType: 'enumerated',
        values: ['linear', 'exclusive', 'inclusive'],
        dflt: 'linear',
        role: 'info',
        editType: 'calc',
        description: [
            'Sets the method used to compute the sample\'s Q1 and Q3 quartiles.',

            'The *linear* method uses the 25th percentile for Q1 and 75th percentile for Q3',
            'as computed using method #10 listed on http://www.amstat.org/publications/jse/v14n3/langford.html).',

            'The *exclusive* method uses the median to divide the ordered dataset into two halves',
            'if the sample is odd, it does not includes the median in either half -',
            'Q1 is then the median of the lower half and', 
            'Q3 is the median of the upper half.',

            'The *inclusive* method also uses the median to divide the ordered dataset into two halves',
            'but if the sample is odd, it includes the median in both halves -',
            'Q1 is then the median of the lower half and',
            'Q3 the median of the upper half.'
        ].join(' ')
    },
```
