### ISSUE TITLE
Pie label clipping on tight margins

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4223]
Right now it's possible for various plot elements to clip when `margin` is set to 0, for example the pie labels when they break out of the slices

![image](https://user-images.githubusercontent.com/203523/65695598-cee52600-e045-11e9-85a1-b310bb908c79.png)

**Comment by nicolaskruchten** [comment]
Related #3607

**Comment by etpinard** [comment]
Similar to cartesian axes, I'm thinking of adding an `automargin` attribute to pie traces.
