### ISSUE TITLE
tight margins: rightmost label cutoff

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4225]
This shouldn't happen:

![image](https://user-images.githubusercontent.com/203523/65696322-07393400-e047-11e9-82db-846f7de3c81b.png)

![image](https://user-images.githubusercontent.com/203523/65696337-0dc7ab80-e047-11e9-8dd3-540549587948.png)

**Comment by nicolaskruchten** [comment]
Related https://github.com/plotly/plotly.js/issues/3607

**Comment by etpinard** [comment]
That one should be already fixed.

Can I get a reproducible example?

**Comment by nicolaskruchten** [comment]
I'll try, or close it if I can't :)

**Comment by etpinard** [comment]
Here are my attempt at reproducing the above graphs:

- https://codepen.io/etpinard/pen/eYYRZYZ?editors=1010
- https://codepen.io/etpinard/pen/LYYLNYz?editors=1010

As you can see the problems appear fixed in `v1.50.1`, most likely from https://github.com/plotly/plotly.js/pull/4216

**Comment by etpinard** [comment]
Can I remove this ticket from the 1.51.0 milestone? Better yet, can we close this issue?

**Comment by nicolaskruchten** [comment]
Works for me!
