### ISSUE TITLE
Heatmap suppress hovers on missing data

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4226]
A trace-by-trace flag to disable hovers on heatmaps when the z value is null/NaN

**Comment by etpinard** [comment]
We'll need a new attribute for this - exposed in all 2d-z trace types (heatmap, contour, contourcarpet, histogram2d*, surface).

Anyone want to take a shot at naming this new attribute? e.g. `hovernanvalue` or `hovernan`?

----

In relation to https://github.com/plotly/plotly.js/issues/3035 and https://github.com/plotly/plotly.js/issues/975, maybe this new attribute could be a `valType: 'string'`. For example,

```js
hovernan: 'blank'
// would show `z: blank` in the hover label

hovernan: ''
// or maybe handle
hovernan: null 
// to omit the `z: ` line in the hover label.
```

----

Moveover, should this new attribute only affect hover labels generated via `hoverinfo` or should it also affect the `%{z}` values in `hovertemplate` strings. For example,

```js
// should
hovernan: '',
hovertemplate: 'f(%{x},%{y}) = %{z}'

// show: `f(1,1) = NaN`
// OR: `f(1,1) = ''` ?
```

**Comment by etpinard** [comment]
Or wait, looks like this ticket actually want to suppress the **entire** hover label (not just the `z: ` line) when hovering over a NaN `z` value.

Perhaps, in this case a boolean makes more sense: For example: `hoveronnan`, but maybe that's a little too hard to make up in smashtogethercase.

**Comment by archmoj** [comment]
What about `hovermissing`?

**Comment by archmoj** [comment]
Or `hoverignore`?

**Comment by nicolaskruchten** [comment]
can we reuse `hoveron` ?

**Comment by nicolaskruchten** [comment]
like `hoveron = "all" | "nonnan"`

**Comment by archmoj** [comment]
I like it. And I see `hoveron` is used at least with `box`, `parcats`, `scatter`, `scattergl`, `scattercarpet`, `scatterternary` and `violin`.
Is there any conflict with the traces mentioned in https://github.com/plotly/plotly.js/issues/4226#issuecomment-538423027?

**Comment by archmoj** [comment]
@emmanuelle would you mind testing the hover behaviour on missing points using this [codepen](https://codepen.io/MojtabaSamimi/pen/BaaQaVM?editors=0010)?
