### ISSUE TITLE
Decent treemap in plotly

### ISSUE THREAD

**Issue by KangboLu** [plotly/plotly.js#4229]
Can Plotly have it's own decent treemap function to plot treemap? Using Squarify is very inconvenient when designing treemap with Dash dashbaord.

And there is only 1 example in the documentation showing how to map super ugly treemap. More examples please.

**Comment by archmoj** [comment]
It would be available in the next minor version of plotly.js v.1.50.0.
Please refer to https://github.com/plotly/plotly.js/pull/4185 for more info.

**Comment by KangboLu** [comment]
When will the team release V1.50.0? 
And will there be documentation ready for v1.50.0?

**Comment by archmoj** [comment]
The 1.50.0 release may be this/next week
The API is pretty similar to `sunburst`. So chances are that a `js` documentation would be prepared soon after. cc: @nicolaskruchten @Mahdis-z 

@KangboLu Anyway please let us know if you were interested to help test it before the release or provide some examples?
Thank you!

**Comment by KangboLu** [comment]
I see. It will be similar to sunburst in plotly. 
I have edited the sunburst example page in markdown and made a pull request. 
https://github.com/plotly/plotly.py-docs/pull/132
It's not really clear for sunburst because there is no explanation for the basic example at all.
I felt many plotly examples are like this.

I was confused about sunburst's branchvalues attribute in the beginning. Why not make 'total' as default? It's more intuitive to think as 'total' for the ring percentage.
