### ISSUE TITLE
Axis lines disappearing  on 3d plot

### ISSUE THREAD

**Issue by CarlCui** [plotly/plotly.js#423]
Latest chrome, plotly 1.9.0

screenshot: 

![axis](https://cloud.githubusercontent.com/assets/16545211/14508519/ac6635b6-017c-11e6-884c-8eb230b8046c.png)

**Comment by etpinard** [comment]
Could you share a reproducible example on codepen, jsFiddle, jsBin, etc ... ?

**Comment by CarlCui** [comment]
I'm sorry, but it's really a rare case. My supervisor had this issue on his chrome, and worked on IE 11. So I'm not even sure it's related to this library. Could you think of anything that might cause this thing to happen? Greatly appreciated! :+1:

**Comment by etpinard** [comment]
Our 3D plots are not immune to Browser, OS, or driver issues as they rely on some fairly new browser technologies. So any bug report is much appreciated.

Unfortunately, without a reproducible example, there's nothing much we can do to fix the issue.

**Comment by CarlCui** [comment]
I understand. Thanks anyway!
