### ISSUE TITLE
Problem with sunburst plot with total values

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#4232]
This `sunburst` [codepen](https://codepen.io/MojtabaSamimi/pen/ZEzNbQL?editors=0010) does not show up and throws error in the console.
Also to mention - the `treemap` variation works fine on master.

**Comment by etpinard** [comment]
Nice catch. The same happens when generating an "implied root":

```js
Plotly.newPlot(gd, { 
    data: [{
        type: 'sunburst',
        branchvalues: 'total',
        labels: [ 'A', 'B', 'b'],
        parents: ['Root', 'Root', 'B'],
        values: [1, 2, 1]
    }]
});
```

https://codepen.io/etpinard/pen/mddbBdy?editors=0010
