### ISSUE TITLE
3D plots broken in Chrome 77 on GNU/Linux and Android

### ISSUE THREAD

**Issue by dpq** [plotly/plotly.js#4233]
### Summary
In Chrome@Linux v.77, 3D plots are broken.

### Steps to reproduce
For example, visit the [docs](https://plot.ly/python/3d-scatter-plots/). Other 3D plots used in production are similarly broken in Chrome 77. 

### What is observed
In error console, ```WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost```. In the browser:
![image](https://user-images.githubusercontent.com/64569/65834424-569b9080-e2e3-11e9-973b-b3b17affd814.png)

### What is expected
Normally functioning 3D plots.

### Additional information
WebGL is enabled; get.webgl.org shows a spinning cube; Chrome WebGL experiments such as Aquarium work properly.

**Comment by etpinard** [comment]
Thanks very much reporting.

We've had some reports already in https://github.com/plotly/plotly.js/issues/3640, could you tell which Linux flavor/version you're using and some info about the hardware you're on. Thank you!

**Comment by archmoj** [comment]
With Chrome 77 on Ubuntu the very first graph displays the error and then a combination of working and non-working veiwports like the one below:
![Screenshot from 2019-09-30 10-35-01](https://user-images.githubusercontent.com/33888540/65888820-2947f480-e36e-11e9-9944-bbfbef82138a.png)

**Comment by longwei66** [comment]
Same here, not working with Version 77.0.3865.90 (Build officiel) (64 bits) - Ubuntu 18.04

WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost

See example here : https://datapleth.io/blog/2019/08/28/2019-08-28_the_french_yield_curve_problem/
![image](https://user-images.githubusercontent.com/1811577/65969313-da30bb00-e464-11e9-9f8c-9e4af0bdb0fb.png)

No problem on firefox 69.0.1 (64 bits) and chromium v. 76 on another computer (wayland).

The example was generated by plotly on R :+1: 
https://cloud.r-project.org/src/contrib/plotly_4.9.0.tar.gz

Source code here : 
https://github.com/longwei66/datapleth/blob/master/content/blog/2019-08-28_the_french_yield_curve_problem.Rmd

**Comment by archmoj** [comment]
@dpq @longwei66 
Could you please test [this codepen](https://codepen.io/MojtabaSamimi/pen/pozMRaJ?editors=0010) in Chrome 77 browser?
Thanks.

**Comment by longwei66** [comment]
@archmoj this works, I can see the vector in 3D with axis, initial issue on my example above persists.

**Comment by dpq** [comment]
@etpinard 
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 5500 (rev 09)
Debian GNU/Linux 10 (Stretch)

I can provide more info on hardware if you tell me what exactly do you need.

**Comment by dpq** [comment]
@archmoj I also observe the codepen working.

Update: due to unknown reasons (maybe another Chrome/system package update, or maybe I didn't notice it initially) on the docs page linked in the bug report I observe the following behavior:

* First plot (iris data): same as before, WebGL not supported
* Second plot (with color dimension), third (styled 3D scatter plot), fourth (basic scatter plot with go.scatter3d) are invisible except for the legend, but then appear when I hover the mouse over them:

Before:

![image](https://user-images.githubusercontent.com/64569/66252205-42331a00-e761-11e9-928e-7c5aa579f76e.png)

After:

![image](https://user-images.githubusercontent.com/64569/66252210-4c551880-e761-11e9-8bf4-587bcab9301f.png)

* 3D Scatter Plot with Colorscaling and Marker Styling appears to work correctly
* Dash App shows the "WebGL not supported" error message

**Comment by etpinard** [comment]
A first attempt at fixing this problem got merged in https://github.com/plotly/plotly.js/pull/4256 and will be released in today's `v1.50.0`

We'll keep this issue open until we find a better solution.

**Comment by archmoj** [comment]
`heatmapgl` is also shows a webgl problem when using Chrome77 on Ubuntu:
https://rreusser.github.io/plotly-mock-viewer/#gl2d_heatmapgl

**Comment by antoinerg** [comment]
> `heatmapgl` is also shows a webgl problem when using Chrome77 on Ubuntu:
> https://rreusser.github.io/plotly-mock-viewer/#gl2d_heatmapgl

This example actually works fine for me on `Chromium Version 77.0.3865.90 (Developer Build) (64-bit)` on NixOS 19.03 (Linux). Now maybe the bug only affects Chrome and not Chromium?

**Comment by antoinerg** [comment]
> `heatmapgl` also shows a webgl problem when using Chrome77 on Ubuntu:
> https://rreusser.github.io/plotly-mock-viewer/#gl2d_heatmapgl
> 
> ![Screenshot from 2019-10-17 15-33-34](https://user-images.githubusercontent.com/33888540/67041406-9b9d3080-f0f3-11e9-999f-42566e701aaf.png)

It also works for me on `Chrome Version 77.0.3865.120 (Official Build) (64-bit)` on NixOS 19.03 (Linux). @archmoj exactly what version of Chrome are you running?

**Comment by archmoj** [comment]
Chrome Version 77.0.3865.120 and .90 both displayed the error.

**Comment by antoinerg** [comment]
> Chrome Version 77.0.3865.120 and .90 both displayed the error.

Ok so I imagine there is an incompatibility with the graphics library shipped with Ubuntu since this exact Chrome version works for me over here. :thinking:

**Comment by archmoj** [comment]
This issue appears to be fixed in Chrome 78 and we already have a work around for v77.
Closing.
