### ISSUE TITLE
Newest plotly.min.js doesn't have fix #4177 

### ISSUE THREAD

**Issue by Pman6543** [plotly/plotly.js#4235]
I downloaded the most recent minified version of plotly from 12 days ago, and it doesn't have the fix detailed in: https://github.com/plotly/plotly.js/pull/4177. Right now I'm using two separate versions of plotly.min.js for my code, and I'd like to only use one. 

When is this fix planned on being added? Also, is there a way I could build a version of plotly myself based on the source code in the repository? 

Thanks!

**Comment by etpinard** [comment]
That's correct. 1.49.5 didn't include the fix for https://github.com/plotly/plotly.js/pull/4177. This one will be released in 1.50.0 - which should be out by week's end.

You can see the release notes here: https://github.com/plotly/plotly.js/releases/tag/v1.49.5

Thanks.

**Comment by Pman6543** [comment]
Ah okay, thank you!
