### ISSUE TITLE
Bad webgl alpha config for 3-D scenes

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#4236]
Noticed blending issues (see the yellow areas on the image below) with Ubuntu + FireFox. 
This could be related to `premultipliedAlpha: true` instead of `false`.
See `gl-plot3d` at https://github.com/gl-vis/gl-plot3d/blob/ccfc4318ec9d382900f7b80b17b1630092fe3953/scene.js#L84.

![blendingFireFoxUbuntu](https://user-images.githubusercontent.com/33888540/65897072-716e1380-e37c-11e9-9483-ea37880e6acb.png)

**Comment by archmoj** [comment]
Also this mock renders:
![Screenshot from 2019-09-30 12-30-06](https://user-images.githubusercontent.com/33888540/65897842-353bb280-e37e-11e9-9c70-26c63f0892cd.png)

**Comment by archmoj** [comment]
Also observed on 
Windows 10 + Firefox 64 - 69.
Windows 7 + Firefox 69.
So the proposed fix may help!
But because the quality of rendering won't be great on other browsers namely Chrome (see the bottom image) it looks we should spend more time on this before making a PR.
![Screenshot from 2019-09-30 17-21-44](https://user-images.githubusercontent.com/33888540/65918325-6381b800-e3a7-11e9-82ee-a0e596e28281.png)

**Comment by archmoj** [comment]
By the way here is the [codepen](https://codepen.io/MojtabaSamimi/full/JjPQyyx) used to test the bug as well as possible impacts of the fix.

**Comment by archmoj** [comment]
See https://github.com/plotly/plotly.js/issues/4334#issuecomment-549976027 which illustrate a similar issue on `Chrome`.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
