### ISSUE TITLE
Clicking "Autoscale" in menu-bar also graphically toggles spikemode

### ISSUE THREAD

**Issue by mscotch1** [plotly/plotly.js#4237]
Steps to reproduce:
1. Open [example](https://codepen.io/plotly/pen/LVMRMO)
1. Click "Autoscale" menu bar option
1. Spike mode is now showing as active, but the spikes don't show up on hover. Clicking spike mode button turns the feature "off," and clicking it again turns spike mode on with the spikes actually showing up.

**Comment by etpinard** [comment]
Thanks for spotting that!

The "Toggle Spike Lines" should not turn on when clicking on the "Autoscale" button.
