### ISSUE TITLE
[feature request] - facet / trellis plot option

### ISSUE THREAD

**Issue by destradafilm** [plotly/plotly.js#4248]
They python library has trellis / facet plot option with built-in facet_row and facet_col arguments

It would be great to have this in Plotly JS as well :)

**Comment by etpinard** [comment]
Moved to https://github.com/plotly/plotly.js/issues/2221#issuecomment-537669624

**Comment by tomhamiltonlambda** [comment]
Commenting as this issue was closed as "Completed" - and routed to another thread #2221 - however that thread has now also been closed without this issue really being discussed / anything being implemented. Can we please keep an issue around this open?

**Comment by tomhamiltonlambda** [comment]
Correction - this feature does exist - but it's called "Subplots" in PlotlyJS. See: https://plotly.com/javascript/subplots/
