### ISSUE TITLE
xaxis labels position and at specific intervals

### ISSUE THREAD

**Issue by SirCameron** [plotly/plotly.js#4257]
Hello

Is it possible to specify the positions of the xaxis labels?
I have a composite graph with 3 yaxis graphs plotting on one xaxis and the xaxis labels are showing up in the middle of the graphs and not at the bottom of all of them.

Can I also specify the intervals? so this is a frequency graph and I'd like the markers/labels to be at specific frequencies. I have looked through the docs and tried a few settings, but none have worked.

<img width="586" alt="Screenshot 2019-10-07 at 20 02 58" src="https://user-images.githubusercontent.com/74608/66336511-7ebb6d00-e93d-11e9-9a77-c3008f2ef1ec.png">

**Comment by etpinard** [comment]
Hi, please ask questions of the likes on https://community.plot.ly/c/plotly-js so that other users can help and/or benefit from the answer. You may also want to use the https://community.plot.ly/c/plotly-js search function.
