### ISSUE TITLE
customdata not working in x/y/z heatmap

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#4260]
in both `hovertemplate` and hover data.

See https://codepen.io/etpinard/pen/bGGNXoz?editors=1010

**Comment by etpinard** [comment]
Even worse: `pointNumber` is 2D: https://codepen.io/etpinard/pen/jOOPqmr?editors=1010 

This is obviously wrong for x/y/z heatmaps.

**Comment by etpinard** [comment]
We should probably build a 2d-indices-to-1d-index map somewhere in [`convert_column_xyz.js`](https://github.com/plotly/plotly.js/blob/master/src/traces/heatmap/convert_column_xyz.js) instead of building 2d version of the `arrayOk` attributes e.g. for `text` and `hovertext`:

https://github.com/plotly/plotly.js/blob/bead43ff7d5cbcedfd2bf29c25cf01b1b4074df9/src/traces/heatmap/convert_column_xyz.js#L37-L42

https://github.com/plotly/plotly.js/blob/bead43ff7d5cbcedfd2bf29c25cf01b1b4074df9/src/traces/heatmap/convert_column_xyz.js#L56-L57

**Comment by brian428** [comment]
Just ran into this and was wondering a fix is planned soon? I'm looking at trying to look up the custom data value "manually", but the pointNumber 2D array doesn't seem to correspond with anything I can use to locate an object in the customdata array. It also doesn't look like there's a way to pass anything else through to the hover event handler (I tried using text, hovertext, etc. to try and pass some lookup value through).

**Comment by nicolaskruchten** [comment]
As far as I can tell, customdata is working in heatmap, but it must have the same shape as `z`: https://codepen.io/nicolaskruchten/pen/yLYLMRX?editors=0010

**Comment by brian428** [comment]
Even in that case, the pointNumber, pointIndex, etc. are 2D arrays rather than an integer. https://codepen.io/brian428/pen/RwWwgRL?editors=0010

Is this actually the intended behavior?

**Comment by Wes-Kuegler** [comment]
@brian428 I've found the same, but I'm running into an issue where I have large 2D data for 'z', but only a 1D array for 'customdata' labels. I want to apply 'customdata' strings to entire "rows" in 'z', not each element. For example, I have 'customdata=["a", "b," "c"]` and I want to apply 'b' to each of 'z[2][x]'. The workaround I'm using is to create a new array of the same length as 'z[x].length' for each index in 'customdata', and copy the desired string 'z[x].length' times into it. It works, but it's not performant at all.

**Comment by naten7k** [comment]
I know this issue is closed, but I have the same issue as @Wes-Kuegler -- I have a 1,000 x 100,000 matrix and a length-1000 customdata that i'd like to apply row-wise. If I use @Wes-Kuegler's workaround, my filesizes and load times become really unmanageable. Is this issue (perhaps more of a feature request?) tracked anywhere else? I would be greatly appreciative if there was been (or could be) any work on this!

**Comment by alexcjohnson** [comment]
@naten7k this is getting to a level of granularity that's pretty tough to envision adding declaratively (though if you have a proposal we'd be happy to consider it), but straightforward to manage imperatively by responding to hover events. If you're doing this in `dash`, there's a whole component dedicated to this use case: https://dash.plotly.com/dash-core-components/tooltip

**Comment by naten7k** [comment]
@alexcjohnson yeah, I sort of figured that would be the case. It's tough to imagine how you'd the correspondence when the shape of `customdata` isn't the same as (or a stack of) `z`. (Just the same, if anyone smarter than me could figure out how to do it in a not-terribly-confusing manner, it'd be useful!)

For future users dealing with similar issues, my solution was very hacky but seems to work well for my use-case. It was to (1) turn off hovertext for the heatmap, (2) set `hovermode='y'` (3) draw invisible horizontal lines on top of the heatmap, and (4) associate the appropriate hovertext with each horizontal line.
