### ISSUE TITLE
Horizontal legend overlaps x-axis label

### ISSUE THREAD

**Issue by cameronwaterman** [plotly/plotly.js#4261]
When there are a large number of traces in a horizontal legend, they begin to overlap to x-axis label as the legend grows in size. It would be great if the horizontal legend added a scrollbar if there are >3-4 rows of legend items, or if this could be configurable.

This seems somewhat related to this issue: https://github.com/plotly/plotly.js/issues/960

![image](https://user-images.githubusercontent.com/25089669/66416948-9853c780-e9c4-11e9-815f-21dfd0bed11e.png)

**Comment by etpinard** [comment]
This seems very related to https://github.com/plotly/plotly.js/issues/1199

@cameronwaterman ok if I merge your issue into #1199 ?

**Comment by cameronwaterman** [comment]
Seems relevant, so yeah that's fine.

It seems that there has been a lot of activity on the issue for close to 2 years now but no changes submitted to address this issue. Is there plans to address it any time soon?

**Comment by etpinard** [comment]
Merged into https://github.com/plotly/plotly.js/issues/1199 - thanks!
