### ISSUE TITLE
struggle with dropdown menu for seleting specific points in timeseries graph

### ISSUE THREAD

**Issue by Gibby90** [plotly/plotly.js#4266]
Hello,

I use plotly.js template for plotting time series like this:
https://www.youtube.com/watch?v=xnJ2TNrGYik

how can I add a search field  and type "01.10.2019" and then all the datapoints which were created on "01.10.2019" are filtered in the graph, means you can only see the data Points of 01.10.2019?  
I Need a good solution, Google for almost 1 week and dont find the correct solution.
thanks

**Comment by etpinard** [comment]
Please use our community forums https://community.plot.ly/c/plotly-js or https://community.plot.ly/c/api/python for questions of the likes. Thank you!
