### ISSUE TITLE
[Bug] data[type=isosurface].surface show option not working as expected

### ISSUE THREAD

**Issue by mafar** [plotly/plotly.js#4270]
For this bug , 
CodePen: https://codepen.io/mafar/pen/WNNQYVd?editors=0010

**Issue:** 

1. I dont define  ```surface``` key at all in trace option, output is solid
1. I define ```surface.show = false``` ,output is not solid which is wrong IMO
```surface.show = false``` should be treated same as ```surface = false```

**Expected:**
1. ```surface.show = true``` turns on surface (no solid anymore)
1. ```surface.show = false``` turns off surface , now should be solid

**Caveat:**
Currently if surface key is defined, there is no way to turn it off

**Suggestion:** 
It should work like ```contour``` option where 

1. ```contour.show = true``` turns on contouring
1. ```contour.show = false``` turns off contouring
1. ```contour= false``` turns off contouring same as ```contour.show = false```

and 
```js
{
        type: "isosurface",
        contour {show:false}, 
        surface : {show:false}, // not working currently
 }
```

**Comment by archmoj** [comment]
@mafar thanks for writting in.
It is working as expected.
See [codepen](https://codepen.io/MojtabaSamimi/pen/dyyYaVm?editors=0010).

**Comment by mafar** [comment]
@archmoj  No it is not .I think I was not clear.

See 
Plotly single iso-surface  - with surface key 
https://codepen.io/mafar/pen/PooPrWq?editors=0010
vs 
Plotly single iso-surface  - without surface key
https://codepen.io/mafar/pen/KKKdjam

Just by adding 
```
surface: {show:false},
``` 
result varies which is definitely not same. One is surface , one is solid

**Comment by mafar** [comment]
@archmoj is it clear now ?

**Comment by archmoj** [comment]
The `surface` refers to `isosurface` i.e. 3d contours at iso-min/max levels which are turned off by the command.
 If you are interested in displaying only iso-surfaces and not the `caps` you could disable them using 
```js caps: { x: { show: false} , y: { show: false} , z: { show: false} }```.
Hope it helps.
