### ISSUE TITLE
select2d and lasso2d not working in Rstudio's Plotly Sankey diagram

### ISSUE THREAD

**Issue by edriclee** [plotly/plotly.js#4272]
library(plotly)

p <- plot_ly(
  type = "sankey",
  orientation = "h",
  
  node = list(
    label = c("A1", "A2", "B1", "B2", "C1", "C2"),
    color = c("blue", "blue", "blue", "blue", "blue", "blue"),
    pad = 15,
    thickness = 20,
    line = list(
      color = "black",
      width = 0.5
    )
  ),
  
  link = list(
    source = c(0,1,0,2,3,3),
    target = c(2,3,3,4,4,5),
    value =  c(8,4,2,8,4,2)
  )
) %>% 
  layout(
    title = "Basic Sankey Diagram",
    font = list(
      size = 10
    )
  ) %>%
  config(modeBarButtons = list(list("select2d"), list("lasso2d")))
p

**Comment by etpinard** [comment]
Here's the JS version of your code:

https://codepen.io/etpinard/pen/zYYrvwj?editors=0010

Box and lasso selection seem to be working as expected. Perhaps you're R installation is using an old version of plotly.js. Sankey node grouping via selection first got released as part of `plotly.js@v1.47.0`.

**Comment by edriclee** [comment]
Thanks for the quick response. I deleted the Plotly package ver 4.9.0 downloaded from CRAN, and installed the Github version via devtools::install_github("ropensci/plotly") to get the ver 4.9.0.9000 which brought back the Box Select, Lasso Select etc.
