### ISSUE TITLE
When mouse-zooming with 3d orthographic projection, no exposed property is updated

### ISSUE THREAD

**Issue by emmanuelle** [plotly/plotly.js#4274]
See the codepen https://codepen.io/emmanuelle-plotly/pen/QWWyjxg?editors=0011 and try to zoom using the mouse wheel. One would expect one property of the figure to be updated, such as `scene.camera.eye` or `scene.aspectratio`, but none of them changes. 

In `perspective` projection, the `scene.camera.eye` is updated when wheel-zooming. 

At the moment it is not possible to dump to JSON a figure which has been zoomed and then to reproduce it because the information about the zoom is not included.

**Comment by archmoj** [comment]
@emmanuelle the codepen now works with the wheel zoom: [demo](https://codepen.io/MojtabaSamimi/pen/mddOywY?editors=0011).

Wondering is we should apply those changes to `_fullLayout.scene.aspectratio`?

**Comment by alexcjohnson** [comment]
Yes, it’s a good idea to keep fullLayout in sync with layout, for the sake of Plotly.react

**Comment by emmanuelle** [comment]
Thank you @archmoj ! At the moment is there any way to retrieve this property in Dash? Using a clientside callbck in Javascript maybe? (I'm not familiar with this, just asking)

**Comment by etpinard** [comment]
> At the moment is there any way to retrieve this property in Dash?

We should add this as part of a `plotly_relayout` event data object.

Here's what happens currently with the default (perspective) projection: https://codepen.io/etpinard/pen/MWWJoQM (open the console and start scrolling)

**Comment by archmoj** [comment]
`orthographic` [demo](https://codepen.io/MojtabaSamimi/pen/BaaWGpZ?editors=1000)
