### ISSUE TITLE
Google Fonts are not rendering on Google Chrome

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#428]
This seems to be a [wide spread issue](http://stackoverflow.com/questions/22011139/google-fonts-are-not-rendering-on-google-chrome)...it'd be awesome if we had a workaround!

http://codepen.io/cpsievert/pen/jqzoWj

**Comment by etpinard** [comment]
Hmm. Which Chrome version are you using?

On `Google Chrome 49.0.2623.112`, I'm getting:

![image](https://cloud.githubusercontent.com/assets/6675409/14563457/18cbc530-02f0-11e6-8ff3-c484eb24213e.png)

which looks ok? Or is it the wrong font?

For the record, on `Mozilla Firefox 45.0.1`, I'm getting:

![image](https://cloud.githubusercontent.com/assets/6675409/14563528/63b8d1dc-02f0-11e6-88c4-f303ae06f07d.png)

**Comment by mdtusz** [comment]
No issues here on `50.0.2661.75` or `52.0.2708.0 canary`.

**Comment by timelyportfolio** [comment]
Is plotly responsible for loading/importing the Google Font?  When I inspect the elements, the `font-family` is correctly set to 'Circular Air Medium'.  See http://codepen.io/timelyportfolio/pen/QNrLOL for an example of what happens when I import the Google Font with CSS settings in CodePen.

![image](https://cloud.githubusercontent.com/assets/837910/14564411/136cbe86-02ec-11e6-96b6-e907bbae73d6.png)

**Comment by etpinard** [comment]
> Is plotly responsible for loading/importing the Google Font?

No. plotly.js doesn't ship with any fonts. We just fill the `font-family` style value in the corresponding `<text>` nodes.

Maybe CodePen has a few defaults fonts available to all pens by default?

**Comment by ricardo-bion** [comment]
These are the Circular Air Fonts that I am having a hard time with:

[Circular Air Medium](https://dl.dropboxusercontent.com/u/2364714/airbnb_ttf_fonts/Circular%20Air-Medium%203.46.45%20PM.ttf) and [Circular Air Bold](https://dl.dropboxusercontent.com/u/2364714/airbnb_ttf_fonts/Circular%20Air-Bold%203.46.45%20PM.ttf", "/Library/Fonts/Circular Air-Bold 3.46.45 PM.ttf)

*Plot in Safari:*
<img width="1017" alt="screen shot 2016-04-14 at 10 40 10 pm" src="https://cloud.githubusercontent.com/assets/9888486/14568776/e6bc348a-02ef-11e6-8df4-3d59eea7bb8e.png">

*Plot in Firefox:*
<img width="981" alt="screen shot 2016-04-15 at 9 55 07 am" src="https://cloud.githubusercontent.com/assets/9888486/14568839/30a53fa6-02f0-11e6-8e5d-3b7c05c2731e.png">

*Plot on Chrome:*
<img width="998" alt="screen shot 2016-04-14 at 10 39 27 pm" src="https://cloud.githubusercontent.com/assets/9888486/14568795/f75f17bc-02ef-11e6-80f1-9b978f17b552.png">

The fonts do not show up in Chrome for some reason. I reproduced this pattern in a few different Mac computers.

**Comment by mdtusz** [comment]
Hi @ricardo-bion. Could you confirm what version of Chrome this was happening with and if possible, share the code you are plotting this with (the data can be omitted if necessary)?

**Comment by cpsievert** [comment]
@etpinard I don't think either of those are right. It should look like this (taken on `Safari 9.0.3 (11601.4.4)`)

<img width="1145" alt="screen shot 2016-04-16 at 9 55 12 am" src="https://cloud.githubusercontent.com/assets/1365941/14577651/e255c4a4-03b9-11e6-81f5-6e3a8758e58c.png">


I get the same result as you on `Chrome 49.0.2623.112` and `Firefox 45.0.2`

**Comment by ricardo-bion** [comment]
`Chrome 50.0.2661.75`. 

It works when I specify the path for the fonts on the CSS. That is good enough for our purposes now.


If you want to reproduce the original issue, this is some example R code. 

It renders well in RStudio, but not when I open the html in Chrome.

```
library(plotly)
library(extrafont)
library(ggplot2)
library(dplyr)

download.file("https://dl.dropboxusercontent.com/u/2364714/airbnb_ttf_fonts/Circular%20Air-Medium%203.46.45%20PM.ttf", "/Library/Fonts/Circular Air-Medium 3.46.45 PM.ttf", method="curl")
download.file("https://dl.dropboxusercontent.com/u/2364714/airbnb_ttf_fonts/Circular%20Air-Bold%203.46.45%20PM.ttf", "/Library/Fonts/Circular Air-Bold 3.46.45 PM.ttf", method="curl")

font_import(pattern = 'Circular', prompt=FALSE)

ggplotly(qplot(1) + 
  theme(text=element_text(family="Circular Air")))
```
