### ISSUE TITLE
Scatter line doesn't get drawn if points are too close

### ISSUE THREAD

**Issue by NRiedinger** [plotly/plotly.js#4282]
Hello,

I'm implementing a timeline-chart by using a scatter type plot with lines.

Working example:
![timeline](https://user-images.githubusercontent.com/20442047/67009195-612f9580-f0eb-11e9-9629-964d94833eb7.png)

In the screenshot above, each coloured tile is a trace with it's own start- and end-timestamp and value.

However, if the delta between start and end of a single trace is too small compared to the timerange of the x-axis, the trace won't get drawn and leaves a gap. If multiple of those small traces are in a row, there's even a bigger gap visible, even though the raw data has no gaps between the timestamps:
![timeline_gaps](https://user-images.githubusercontent.com/20442047/67009602-4ad60980-f0ec-11e9-85b6-13f44c26830d.PNG)

I made a small codepen-example for this:
https://codepen.io/nriedinger/pen/BaaLyLo
If you zoom in on the white gaps, you can see that those should be dark-blue traces.

When inspecting the codepen site we can see, that those traces are even in the DOM, but without the path-children
![timeline_dom](https://user-images.githubusercontent.com/20442047/67010532-1c592e00-f0ee-11e9-8e67-b46b933ad3d0.PNG)

So my questions are:
* Is there a way to still draw those traces? 
* Is this a bug or intended?
* Am I missing something here?

**Comment by etpinard** [comment]
Hi @NRiedinger - thanks for writing in.

Could you share a codepen of the "working example" from which you took your first screenshot? That should help us debug.

**Comment by NRiedinger** [comment]
Hey @etpinard thanks for the quick answer!

You can get the "working example" by zooming in in my codepen example.
It really only happens when I have a big timerange on the x-axis compared to the timerange of the trace I want to draw.

My codepen example is basically the same like in our product, where I took the screenshot from.

**Comment by alexcjohnson** [comment]
Here's an example with numeric axes, here the orange trace is just below the threshold and disappears, the green is just above and appears. Seems to happen at any angle and just be related to pixel length as a fraction of line width https://codepen.io/alexcjohnson/pen/GRRjZrW?editors=1010

**Comment by etpinard** [comment]
By setting `line.simplify: false`, look likes we get the correct results:

- https://codepen.io/etpinard/pen/zYYKKaJ?editors=1010
- https://codepen.io/etpinard/pen/MWWjjXQ?editors=1010

---

Maybe adapting some of the tolerance values in [`line_points.js`](https://github.com/plotly/plotly.js/blob/master/src/traces/scatter/line_points.js) in function of the pixel range of the graph would be help solve this problem?

**Comment by etpinard** [comment]
... which could also help with transitions of "simple" line traces cc https://github.com/plotly/plotly.js/issues/4250

**Comment by alexcjohnson** [comment]
I don't think we should be adding more magic numbers. I feel like the solution here is simplification should never remove the first or last point in any contiguous section (ie a sub-array with no nulls). I'm guessing what's happening here is it's adding the first point, skipping the second because it's too close to the first, then realizing it only has a 1-point line and deleting the whole thing.

**Comment by NRiedinger** [comment]
> By setting `line.simplify: false`, look likes we get the correct results:
> 
> * https://codepen.io/etpinard/pen/zYYKKaJ?editors=1010
> * https://codepen.io/etpinard/pen/MWWjjXQ?editors=1010
> 
> Maybe adapting some of the tolerance values in [`line_points.js`](https://github.com/plotly/plotly.js/blob/master/src/traces/scatter/line_points.js) in function of the pixel range of the graph would be help solve this problem?

That worked, thanks!
I must have somehow overlooked in the docs :D

**Comment by nicolaskruchten** [comment]
> I don't think we should be adding more magic numbers.  

in principle yes but the current behaviour is causing a fair number of problems... I think https://github.com/plotly/plotly.py/issues/1843 is related also

**Comment by alexcjohnson** [comment]
> the current behaviour is causing a fair number of problems

Let's address the animation-related pieces of this in #4250, and address the static-display bug on its own per my earlier https://github.com/plotly/plotly.js/issues/4282#issuecomment-543267004

**Comment by ldd** [comment]
Hey guys! 

So, let me just say that plotly.js is awesome. I saw this issue and went and read `line_points.js`. A quick hacky and non-ideal fix is changing `minTolerance` in [constants.js](https://github.com/plotly/plotly.js/blob/master/src/traces/scatter/constants.js) to something smaller, like `0.1`

The actual code that seems to end up giving you this behaviour is [this check](https://github.com/plotly/plotly.js/blob/master/src/traces/scatter/line_points.js#L385-L386) that you do in `line_points.js`:

>             if(!(fill && (pti === 0 || pti === len - 1)) &&
>                clusterRefDist < getTolerance(clusterHighPt, nextPt) * minTolerance) continue;

which basically is

`sqrt(x**2 + y**2) < max(3/20, width/20)` and that ends up being problematic for certain widths, I'd guess.

Now, I went ahead and found a cute algorithm to decimate lines: [Douglas Peucker Algorithm](https://en.wikipedia.org/wiki/Ramer%E2%80%93Douglas%E2%80%93Peucker_algorithm)

But I guess that ideally, you'd let the user use their own decimators. 

Now, I could maybe work on a pull request like this, but first I wanted to get your feedback here.

Perhaps it's best to tackle other more pressing issues? I just really really wanna help.

Thanks for working on plotly and hopefully I can be helpful somehow.

**Comment by jackparmer** [comment]
This issue has been tagged with `NEEDS SPON$OR`

A [community PR](https://github.com/plotly/plotly.js/pulls?q=is%3Apr+is%3Aopen+label%3A%22type%3A+community%22) for this feature would certainly be welcome, but our experience is deeper features like this are difficult to complete without the Plotly maintainers leading the effort.

**Sponsorship range: $5k-$10k**

What Sponsorship includes:
- Completion of this feature to the Sponsor's satisfaction, in a manner coherent with the rest of the Plotly.js library and API
- Tests for this feature
- Long-term support (continued support of this feature in the latest version of Plotly.js)
- Documentation at [plotly.com/javascript](https://plotly.com/javascript/)
- Possibility of integrating this feature with Plotly Graphing Libraries (Python, R, F#, Julia, MATLAB, etc)
- Possibility of integrating this feature with Dash
- Feature announcement on [community.plotly.com](https://community.plotly.com/tag/announcements) with shout out to Sponsor (or can remain anonymous)
- Gratification of advancing the world's most downloaded, interactive scientific graphing libraries (>50M downloads across supported languages)

Please include the link to this issue when [contacting us](https://plotly.com/get-pricing/) to discuss.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
