### ISSUE TITLE
Heatmapgl better handle missing data

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#4287]
It appears that `heatmapgl` replaces the missing data with the minimum value.
[codepen](https://codepen.io/MojtabaSamimi/pen/abbmxwG?editors=0010)

**Comment by archmoj** [comment]
`surface` variation would set `visible` to false in that case: [codepen](https://codepen.io/MojtabaSamimi/pen/VwwKoKV?editors=0010)
`heatmap` does not draw the missing point(s): [codepen](https://codepen.io/MojtabaSamimi/pen/dyypxNQ?editors=0010)

**Comment by etpinard** [comment]
See https://codepen.io/etpinard/pen/xxxgOZb?editors=0010 for a better 1:1 comparison. Note that `heatmapgl` does not support `connectgaps:false` and always smooths the rendered pixels (similar to `zsmooth:'best'` in the `heatmap` case).
