### ISSUE TITLE
Rotating Ellipse (Circle Shape)

### ISSUE THREAD

**Issue by jmethfe** [plotly/plotly.js#4296]
Hi,

Adding the ability to create an ellipse with arguments similar to what can be found in matplotlib Python package would be very useful. I am creating ellipses using the shape of type 'circle'. This works mostly, however I need to provide an angle for the ellipse. 

P.S Does anyone know of a workaround to accomplish this?

Best Regards

**Comment by dougollerenshaw** [comment]
I want to second this. I found this comment while trying to work this out myself. No luck yet. Here's the matplotlib syntax, for reference:

```
fig,ax=plt.subplots()
e = Ellipse(
        xy=(X,Y),
        width=W, 
        height=H,
        angle=THETA,
    )
ax.add_artist(e)
```

**Comment by ped59430** [comment]
For reference too, there has been this thread in the community: https://community.plot.ly/t/2d-scatter-plot-with-ellipse/8825.

An in R, the [ellipse function](https://www.rdocumentation.org/packages/mixtools/versions/1.0.4/topics/ellipse).

On my side, I might try an SVG path like described in the [docs](https://plot.ly/javascript/reference/#layout-shapes). Something built with Bezier curves maybe.

**Comment by ped59430** [comment]
I have never contributed but we have done an implementation using ellipse parameters.

The code is in the form of some Vue methods. The idea is to compute dots for some angles and then draw.

One dot coordinates:
```
computeEllipsePoint(averages, parameterMatrix, constError, t) {
      const [lambda_1, lambda_2, theta] = parameterMatrix
      return [
        averages[0] +
         (Math.sqrt(lambda_1) * Math.cos(theta) * Math.cos(t) - Math.sqrt(lambda_2) * Math.sin(theta) * Math.sin(t)) * constError,
        averages[1] +
          (Math.sqrt(lambda_1) * Math.sin(theta) * Math.cos(t) - Math.sqrt(lambda_2) * Math.cos(theta) * Math.sin(t)) * constError
      ]
    }
```

All dots:
```
    computeEllipseQuarter(averages, parameterMatrix, constError) {
      var output = { x: [], y: [] }
      for (var angle = 0; angle < 720; angle++) {
        const tmp = this.computeEllipsePoint(
          averages,
          parameterMatrix,
          constError,
          angle * 2 * (Math.PI / 720)
        )
        output.x.push(tmp[0])
        output.y.push(tmp[1])
      }
      return output
    }
```

Call (sorry the code is not refactored... quarter has no meaning here):
```
          const quarter = this.computeEllipseQuarter(averages, parameterMatrix, 1.96)
          this.data.push(
            ellipse(quarter.x, quarter.y, elem, this.groupColor[elem])
          )
```
where ellipse is:
```
export const ellipse = (x, y, name, color) => {
  const ellipse = line(x, y, name, color)
  ellipse.name = ellipse.name + ' (CI 95%)'
  ellipse.hoveron = 'points'
  ellipse.hovertemplate = '<b>%{fullData.name}</b><extra> <b><i>%{yaxis.title.text}</i> %{y:.0f} <i>%{xaxis.title.text}</i> %{x:.0f}</b></extra>'
  ellipse.fill = 'toself'
  ellipse.line = {
    color: convertHex(color, 0.9),
    width: 1,
    dash: 'dot'
  }
  ellipse.fillcolor = convertHex(color, 0.1)
  return ellipse
}
```

How to compute the parameters (from this article: https://www.xarg.org/2018/04/how-to-plot-a-covariance-error-ellipse/): 
:warning: I recall that we moved the computation of ellipse parameters to Python, so if anyone use this JS implementation, might be better to check again the xarg article and results.
```
    /**
     * @vuese
     *
     * @arg _averages_ - from the compute API <br>
     * @arg _covariance_ - from the compute API <br>
     * @arg _integer_ - integer between 0 and 1 for the confidence level <br>
     */
    computeEllipseParameter(averages, cov_error, level) {
      level = level || 0.95
      // get the chisquare value for the log level
      var s = -2 * Math.log(1 - level)
      // get the cov_error
      var a = cov_error[0][0]
      var b = cov_error[0][1]
      var c = cov_error[1][0]
      var d = cov_error[1][1]
      // get the eigenvectors
      var tmp = Math.sqrt((a - d) * (a - d) + 4 * b * c)
      var V = [
        [-(tmp - a + d) / (2 * c), (tmp + a - d) / (2 * c)],
        [1, 1]
      ]
      // get the scaled eigenvalues (scale according to
      // confidence level)
      var sqrtD = [
        Math.sqrt((s * (a + d - tmp)) / 2),
        Math.sqrt((s * (a + d + tmp)) / 2)
      ]
      // normalize the eigenvectors
      var norm1 = Math.hypot(V[0][0], 1)
      var norm2 = Math.hypot(V[0][1], 1)
      V[0][0] /= norm1
      V[1][0] /= norm1
      V[0][1] /= norm2
      V[1][1] /= norm2
      // choose the major axis by selected the highest
      // eigenvalues
      var ndx = sqrtD[0] < sqrtD[1] ? 1 : 0
      // make a matrix woth the ellipse parameters
      const parameterMatrix = [
        [V[0][ndx] * sqrtD[ndx], V[0][1 - ndx] * sqrtD[1 - ndx]],
        [V[1][ndx] * sqrtD[ndx], V[1][1 - ndx] * sqrtD[1 - ndx]]
      ]
      return parameterMatrix
    }
```

**Comment by janosh** [comment]
Would be a great feature!

Besides the links from @ped59430 above for JS and R ellipse functions, there's also [this community thread](https://community.plotly.com/t/36576) with a plotly.py ellipse function.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
