### ISSUE TITLE
Colorbar fill method

### ISSUE THREAD

**Issue by mdtusz** [plotly/plotly.js#430]
The colorbar component is currently drawn using many overlapping svg rectangles with colors set according to their _value_ on the color gradient.

While this works with fully opaque colorbars, it can't work with transparencies because the `rect`s overlap in order to avoid aliasing and as a result, we'll see darker sections of "combined opacity". I.e.:

```
Imagine these are all shmushed into one column.

************
*          *
*          *  ************  
************  * overlap  *
              *          *  ************
              ************  * overlap  *
                            *          *
                            ************

Where there is overlap, opacities are combined.
0.5 + 0.5 -> something more opaque than 0.5
```

We can use native `<svg>` `<linearGradient>`'s without any issue and using multiple stops of any color or opacity, but this will require a few things:
- [ ] refactor module to have access to the `colorscale` array of the trace in context
- [ ] add a `<linearGradient>` `<def>` adding `<stop>`'s as specified by `colorscale`
- [ ] replace old `.cbfills` element with a `<rect fill="url(#idOfGradientDef)">`

The second two are pretty much trivial - the big thing will be rearranging the colorbar module so we can access the correct `colorscale`.

**Comment by etpinard** [comment]
This ticket is obsolete.
