### ISSUE TITLE
pie - problem with reversed domain ranges

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#4300]
In this [codepen](https://codepen.io/MojtabaSamimi/pen/LYYyzwa?editors=0010) the first `pie` graph (i.e. on the left) does not look right! 
The graphs reversed and the text is presented `outside` as a result of bad input data where `domain.x`[1] is not greater than `domain.x`[0].

We shouldn't allow that here: https://github.com/plotly/plotly.js/blob/99fc02f50cb7e10a616b1c4928e5f7e16809c57c/src/plots/domain.js#L111-L132

**Comment by etpinard** [comment]
Thanks for spotting. Presumably this bugs affects other traces that use `plots/domain.js`.
