### ISSUE TITLE
Setting layout.xaxis.tickmode to 'array' explicitly does not work on date and log axes

### ISSUE THREAD

**Issue by ark-ark** [plotly/plotly.js#4302]
Setting _layout.xaxis.tickmode_ to _array_ explicitly does not work at all. If set to _array_ all settings regarding _tickvals_ and _ticktext_ will be ignored.  _tickvals_ and _ticktext_ only have an effect if _tickmode_ is not set.

See https://jsfiddle.net/xt6udrkh/2/

**Comment by etpinard** [comment]
Thanks for reporting.

The current logic is pretty clear:

https://github.com/plotly/plotly.js/blob/c8a9f8ae8a8389e357c2afbada1ec0b7a2c4259a/src/plots/cartesian/tick_value_defaults.js#L16-L24

I'm not sure why `tickmode` is set to `'auto'` here. Maybe `tickvals` / `ticktext` used to not work on date and log axes.

**Comment by etpinard** [comment]
Commit https://github.com/plotly/plotly.js/commit/355fb09126ff692bfa2025aa6f4fb52f51220194 changed a few things and may be the culprit.

**Comment by etpinard** [comment]
and then there's this test:

https://github.com/plotly/plotly.js/blob/c8a9f8ae8a8389e357c2afbada1ec0b7a2c4259a/test/jasmine/tests/axes_test.js#L1538-L1542


clear :lock: ing down the reported behavior :thinking:

**Comment by archmoj** [comment]
Fixed via #4851.
