### ISSUE TITLE
Custom error hover text

### ISSUE THREAD

**Issue by Carnageous** [plotly/plotly.js#4309]
It would be nice to be able to customize the "error text". This would allow users not only to make it more clear what data is the negative/positive error but would enable to give them custom names.

For example: I created a graph to show data for min, aim and max concentrations but as far as I know there is no way to describe it. (see this [example](https://plot.ly/~Janis.Jansen/1/))

When hovering the error bars at the moment you only get a couple of values without any more explaination about what the data actually represents. I know in other charting libraries like fusioncharts there is a template-like syntax, so you could use min and max values inside a customized hover text.

I hope you see a value in this feature. I see this as the only solution for my problem and I think it would generally be a good addition to plotly.

**Comment by etpinard** [comment]
You should be able to get pretty close to your desired result using `hovertemplate`.

See example: https://codepen.io/etpinard/pen/zYYdpMY?editors=1010

**Comment by Carnageous** [comment]
Wow, I never knew this feature existet. This issue is redundant then.
I'll figure out how this works in angular, thank you!
