### ISSUE TITLE
Use AppVeyor for karma/jasmine CI testing on IE11

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#431]
_... and maybe on MS Edge too, [down the road](https://github.com/nicolasmccurdy/karma-edge-launcher/issues/12)._

I've made some prelim. work on the [`appveyor`](https://github.com/plotly/plotly.js/compare/appveyor) branch where [`karma-ie-launcher`](https://github.com/karma-runner/karma-ie-launcher) is used to boot up IE.
### Issues that I've ran into
- all our tests that use our [mouseEvent wrapper](https://github.com/plotly/plotly.js/blob/master/test/jasmine/assets/mouse_event.js) are failing (because `window.mouseEvent` does not work in IE11, see prelim attempt for writing a wrapper [here](http://codepen.io/etpinard/pen/reYWaJ))
- I had to use `npm install --force` so that `node-sass` installs properly run after run. This has the side effect of making our AppVeyor test runs > 10 minutes long. We have to find a better way of caching packages.

Full CI outputs: https://ci.appveyor.com/project/etpinard/plotly-js/build/7

Any help from anyone with access to a Windows machine and/or with AppVeyor expertise would be greatly appreciated.

**Comment by mdtusz** [comment]
Interesting. Why was/is the node-sass installation failing?

We should probably add

``` yml
cache:
  - $PATH_TO_PLOTLYJS/node_modules     # or maybe it would be a backslash...
```

to the `appveyor.yml` though.

**Comment by etpinard** [comment]
> Interesting. Why was/is the node-sass installation failing?

I got some `Error: EPERM: operation not permitted` off this [build](https://ci.appveyor.com/project/etpinard/plotly-js/build/3). This error apparently has happened to other folks (e.g. [here](http://help.appveyor.com/discussions/problems/3147-error-eperm-operation-not-permitted-rename-on-npm-install)).

**Comment by etpinard** [comment]
Note, we don't have to run all our jasmine tests there. Most of our pixel-based-assertions will probably fail, getting those up-to-speed for IE will be too much of a pain for little gain. We could either tag a few existing tests with a new `@IE` tag or add a seperate suite.
