### ISSUE TITLE
imagemapbox trace type

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4330]
Let's build a way to put raster data on a mapbox subplot (broken off of https://github.com/plotly/plotly.js/issues/3898#issuecomment-519515769)

I.e. to be able to make maps like the tilemap here https://examples.pyviz.org/gerrymandering/gerrymandering.html or like this:

![image](https://user-images.githubusercontent.com/203523/68037980-49d1da00-fc9f-11e9-9958-508710f21d59.png)

**Comment by Charlesfox1** [comment]
Hey @nicolaskruchten - did this get built in / included? Raster support would be fantastic.

**Comment by archmoj** [comment]
Closing in view of the note by @jonmmease:
<i>It's possible now using a mapbox image layer and a base64 encoded png.  Not sure if there's value in making an easier JavaScript API for it, but plotly express could provide a px.imagemapbox function based on what's already available.</i>
