### ISSUE TITLE
ScatterGL : Cannot show tooltip value when two point in same trace have the same x value

### ISSUE THREAD

**Issue by Smurf81** [plotly/plotly.js#4333]
Hello,

when i make a trace with scattergl, if this trace make a circle and two point have the same x value but different y value, i can't see the tooltip of the second value.

An example is visible here :  : https://codepen.io/smurf81/pen/WNNMXzW

**Comment by archmoj** [comment]
Using `hovermode: 'closest'` can help. Plese refer to this [demo](https://codepen.io/MojtabaSamimi/pen/bGGLYOJ?editors=0010).

**Comment by Smurf81** [comment]
Thx you
