### ISSUE TITLE
coloraxis range not react()ing

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4337]
As raised in https://github.com/plotly/react-plotly.js/issues/167 and at least one Dash-related report somewhere that I can't find just now, it seems like `layout.coloraxis` isn't `react()`ing completely... codepen: https://codepen.io/nicolaskruchten/pen/YzzLXmy?editors=0010

**Comment by nicolaskruchten** [comment]
Basically the range grows but doesn't shrink :)

**Comment by alexcjohnson** [comment]
Another example, from https://github.com/plotly/dash-core-components/issues/702: https://codepen.io/alexcjohnson/pen/JjjwBKE?editors=0010
