### ISSUE TITLE
plotly_click event doesn't fire when clicking non-root/leaf nodes of sunburst trace

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#4338]
Originally reported in https://github.com/ropensci/plotly/issues/1648

Minimal example (note how clicking on the middle ring doesn't trigger `plotly_click`) https://codepen.io/cpsievert/pen/OJJZyrZ

**Comment by archmoj** [comment]
`plotly_sunburstclick` is the event you may looking for. 
Here is a [demo](https://codepen.io/MojtabaSamimi/pen/NWWMNbr?editors=0010).

**Comment by cpsievert** [comment]
Oh, interesting; thanks, is there a good reason why a new event is needed? It'd be nice if the event was mentioned in the release notes.

**Comment by alexcjohnson** [comment]
@archmoj @etpinard can we please dredge up a clear answer as to *why* this odd behavior exists with `plotly_click` (for `treemap` as well) and whether it would be feasible to make `plotly_click` behave the way users would expect, before we go to the trouble of documenting these trace-specific variants, adding them to dash, etc etc.

**Comment by archmoj** [comment]
For reference `plotly_sunburstclick` is added to `sunburst/plot.js` within this commit: https://github.com/plotly/plotly.js/commit/a7e7e65ed6

**Comment by etpinard** [comment]
First off, the current behaviour is very much intended (see the logic [here](https://github.com/plotly/plotly.js/blob/513491e6a8f20e247881609eefa74ffdb6c7c319/src/traces/sunburst/fx.js#L220-L239)). So the discussion here should be about _is the current behaviour correct_.

Here's some background: for most traces (maybe all, but I'd have to double-check) `plotly_click` means "give me the `plotly_hover` event data" on click without doing anything else. For sunburst (and now treemap) traces, click does a lot more (it triggers a transitions). Most importantly, sunburst and treemap allow users to override the "click" behaviour with:

```js
gd.on('plotly_sunburstclick', () => {
  /* new logic e.g. make a request to a database */

  return false; // cancel the default handler
})
```

This was one of the original requirements for sunburst traces. Note that returning `false` to in a custom `plotly_click` event handler does nothing.

---

So, is this ticket asking to:

1) rename `plotly_sunburstclick` and `plotly_treemapclick` --> `plotly_click`, that is no longer make a distinction between clicks that trigger transitions and other clicks, or
1) trigger `plotly_click` (which just returns the `plotly_hover` event data) on all nodes, not just root and leaf nodes?

**Comment by etpinard** [comment]
Personally, I'm very (very) much in favour of 2).

**Comment by cpsievert** [comment]
Thanks @etpinard! I think the behavior you describe in 2 is more intuitive for most users.

**Comment by alexcjohnson** [comment]
Thanks for clarifying, @etpinard - we were missing that context. It does make sense to keep the transition-canceling property only in the `plotly_*click` events, so essentially option 2 sounds great to me as well.

But according to the existing logic, you get a `plotly_click` event in sunburst or treemap traces precisely when there's no transition - either because you clicked on a node that doesn't support transitions, OR because the `plotly_*click` handler canceled the transition. That seems weird to me - I'd say if `plotly_*click` canceled the transition, it should cancel the `plotly_click` event too. But otherwise `plotly_click` should alway be triggered, transition or no. It could be useful to know whether there was a transition triggered by the click or not, so perhaps we can find a way to add that to the event handler?

**Comment by etpinard** [comment]
> That seems weird to me - I'd say if `plotly_*click` canceled the transition, it should cancel the `plotly_click` event too.

So, there are three scenarios:

1) user clicks on the root node OR a leaf node:
  + current: fires `plotly_click`
  + wanted: same
2) user clicks on an inner node:
  + current: executes `plotly_sunburstclick` handler, triggers transition
  + wanted: executes `plotly_sunburstclick` handler, fires `plotly_click`, triggers transition
3) user clicks on an inner node AND sets up a `plotly_sunburstclick` handler that returns `false`:
  + current: executes `plotly_sunburstclick` handler, fires `plotly_click`
  + wanted (by AJ :smirk: ): executes `plotly_sunburstclick` hander 

Is that correct?

---

> It could be useful to know whether there was a transition triggered by the click or not, so perhaps we can find a way to add that to the event handler?

Yeah, that's a good idea. The sunburst/treemap event data currently looks like:

![image](https://user-images.githubusercontent.com/6675409/69193969-fca29480-0af5-11ea-8553-5aa2eacc3639.png)

I can't really imagine placing the transition info inside the `points` array, so maybe the event data could have three subcontainers:

```js
{
  event: { /* instanceof MouseEvent */ }
  points: [{ /* */ }],
  transition: {
     duration: /* value from the constant file */,
     easing: /* value from the constant file */
  }
}
```

or maybe a just a boolean would suffice :thinking: 

---

Moreover, theses changes are borderline breaking, so at the very least they would have to be released in a minor.

**Comment by alexcjohnson** [comment]
> 1. user clicks on the root node OR a leaf node:
> 
> * current: fires `plotly_click`
> * wanted: same
> 
> 2. user clicks on an inner node:
> 
> * current: executes `plotly_sunburstclick` handler, triggers transition
> * wanted: executes `plotly_sunburstclick` handler, fires `plotly_click`, triggers transition
> 
> 3. user clicks on an inner node AND had set up a `plotly_sunburstclick` handler that returns `false`:
> 
> * current: executes `plotly_sunburstclick` handler, fires `plotly_click`
> * wanted (by AJ 😏 ): executes `plotly_sunburstclick` hander
> 
> Is that correct?

yep, that's what I had in mind! 🍻 

> I can't really imagine placing the transition info inside the `points` array, so maybe the event data could have three subcontainers when a transition is triggered:
> 
> ```js
> {
>   event: { /* instanceof MouseEvent */ }
>   points: [{ /* */ }],
>   transition: {
>      duration: /* value from the constant file */,
>      easing: /* value from the constant file */
>   }
> }
> ```
> 
> or maybe a just a boolean would suffice 🤔

As a user what I would want to know is not the transition parameters, but: did the root node of the view change, and if so to which node?

> Moreover, theses changes are borderline breaking, so at the very least they would have to be released in a minor.

For sure, minor.
