### ISSUE TITLE
Traces shift Y position with svg size > 16380px

### ISSUE THREAD

**Issue by mjordan84** [plotly/plotly.js#4339]
Hi,
There seems to be a max height plotly can handle. Over this value (16380px) traces start shifting up in relation to the y axis.
As you can see in the example below if you change layout height to 16380, markers are correctly positioned.Over this value they start drifting up.  
![Untitled](https://user-images.githubusercontent.com/55309143/68345108-b0924000-0144-11ea-97f8-8ea64966f2e2.png)

https://codepen.io/mjordan84/pen/vYYjLvQ

**Comment by alexcjohnson** [comment]
Thanks @mjordan84 - looks like the limit is 2^14 = 16384. But only in Chrome - Both FF and Safari (on my mac anyway) appear to fail past 2^13 = 8192 - and FF does so in much more dramatic fashion! Also to note: this seems to only be a problem for webgl - convert these to `'scatter'` traces and it looks fine.

Given the browser-dependent nature of this, I'm not sure there's anything we can do. Indeed, these numbers line up with what I see described as webgl limits elsewhere, like https://tech.shutterstock.com/2019/04/30/canvas-webgl-filtering-concepts
https://webglstats.com/webgl/parameter/MAX_RENDERBUFFER_SIZE (some sizable fraction are still limited to 4096)

**Comment by mjordan84** [comment]
Thanks @alexcjohnson - I will move away from WebGL when hitting these limits. As you said not much you can do about it.
