### ISSUE TITLE
Automargins in narrow spaces

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4350]
From @chriddyp:

I’m seeing this issue in 1.51.1 - I’m assuming that the axes labels are longer than the width of the chart itself. maybe we can introduce some kind of minwidth property for the layout where the chart would shrink up to minwidth and display cut off tick labels (e.g. shrink the chart up to 100px wide)

![image](https://user-images.githubusercontent.com/203523/68822930-473c9080-0660-11ea-9c8b-c5e9d4be2e2a.png)

a min width on one end or the other might be nice. either say - if there isn’t enough room, make the graph at least 100px wide (layout.minwidth or something) or e.g. set the min width in the tick labels - display at least 40px of tick labels
or maybe there is a more elegant solution to display the tick labels in a nicer way for compact layouts. like on top of the bars or something. or at least get the hover labels to show up on top of the bars

**Comment by etpinard** [comment]
> I’m assuming that the axes labels are longer than the width of the chart itself.

Actually, longer than half the width of the chart is enough to trigger the problem:

https://github.com/plotly/plotly.js/blob/513491e6a8f20e247881609eefa74ffdb6c7c319/src/plots/plots.js#L1842-L1851

**Comment by etpinard** [comment]
... and I should add the lines pasted in the above comment are very old, so I doubt the current `v1.51.x` behaviour is any different than in previous versions.

**Comment by archmoj** [comment]
How does this problem look like after [v1.58.0](https://github.com/plotly/plotly.js/releases/tag/v1.58.0)?
cc: #5237

**Comment by nicolaskruchten** [comment]
What would you expect the change to be? I thought that to fix this we would need https://github.com/plotly/plotly.js/issues/5246 ?

**Comment by archmoj** [comment]
Confirmed by @wbrgss that this issue is now now fixed after [v1.58.0](https://github.com/plotly/plotly.js/releases/tag/v1.58.0) by #5237.
