### ISSUE TITLE
*Dynamic* styling of a single marker

### ISSUE THREAD

**Issue by ccamero8** [plotly/plotly.js#4352]
Related to [issue#144](https://github.com/plotly/plotly.js/issues/144).

In the linked issue above, a solution was provided to style a single marker on a line. However, the identifier for the marker seems to be hardcoded. 

To be more specific, the solution is to use restyle like this: 
`Plotly.restyle(gd, {'marker.color[23]': 'red'}, null, [0])`

This does in fact work, and changes the 23rd index marker to red. However, if I change the code to something like this:
`let dynamicallyFoundIndex = 14;`
`let str = "marker.color[" + dynamicallyFoundIndex + "]";`
`Plotly.restyle(gd, {str: 'red'}, null, [0])`

Nothing happens. No errors in the console, and no markers' styling changes.

Hopefully I'm overlooking something simple here, but I haven't been able to get this to work. Any help is appreciated. Thanks!

**Comment by alexcjohnson** [comment]
That will attempt to restyle the attribute `str`
If you're using es6:
```js
Plotly.restyle(gd, {[str]: 'red'}, null, [0])
```
Or with es5:
```js
var dynamicallyFoundIndex = 14;
var str = "marker.color[" + dynamicallyFoundIndex + "]";
var editObj = {};
editObj[str] = 'red';
Plotly.restyle(gd, editObj, null, [0]);
```

**Comment by etpinard** [comment]
Closing.
