### ISSUE TITLE
Apply reversescale in contour and histogram2dcontour legends

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#4354]
Expecting `contour` legend to flip fill direction when `reversescale` is set.
[demo](https://codepen.io/MojtabaSamimi/pen/ExxdBJR?editors=0010)

**Comment by archmoj** [comment]
Similar bug in `histogram2dcontour`: [demo](https://codepen.io/MojtabaSamimi/pen/GRRwQvO?editors=0010)
cc: @alexcjohnson

**Comment by etpinard** [comment]
Nice catch @archmoj !

We could release this in a patch, so no need to pin this to the `v1.52.0` milestone.
