### ISSUE TITLE
Problem drawing legends of contour and histogram2dcontour when using coloraxis

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#4355]
See console error.
[contour demo](https://codepen.io/MojtabaSamimi/pen/abbQqxB?editors=0010)
[histogram2dcontour demo](https://codepen.io/MojtabaSamimi/pen/oNNQEre?editors=0010)

**Comment by etpinard** [comment]
Very nice catch @archmoj !

Have you started work on this? If not I'll assign myself.

**Comment by archmoj** [comment]
Fixed in https://github.com/plotly/plotly.js/pull/4356
