### ISSUE TITLE
How to format dates on point hover with streaming graph

### ISSUE THREAD

**Issue by ccamero8** [plotly/plotly.js#4367]
I have a timeline very similar to this example from the PlotyJS Streaming page: https://codepen.io/plotly/pen/YQBBbE

When I hover on a point in my timeline, it shows the X-Axis value (date) as a full date/time string. Something like this: 'Nov 19, 2019, 16:35:14.345'

Is there anyway to show that as JUST the time part of the string on point hover? I looked at the hovertemplate JS examples, but I the only formatting I saw was with float datapoints and static graphs.

Also tried to set hoverTemplate in my call to Plotly.extendTraces(), but that didn't work.

Thank you!

**Comment by etpinard** [comment]
Here's how using `xaxis.tickformat`

https://codepen.io/etpinard/pen/rNNPZbd

----

If ever you have any other questions about plotly.js, please https://community.plot.ly/c/plotly-js so that other users can benefit from the answer. Thank you!

**Comment by ccamero8** [comment]
Thanks! I'll be sure to use that forum next time :)
