### ISSUE TITLE
[Typescript] type for text is not complete

### ISSUE THREAD

**Issue by z4m0** [plotly/plotly.js#4370]
Line
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/plotly.js/index.d.ts#L513

should be:
``` typescript
text: string | string[] | string[][];
```
instead of:
```ts
text: string | string[];
```
It is necessary for heatmap for example.

**Comment by etpinard** [comment]
Hi @z4m0 - we do not officially maintain the typescript definitions, so I'll close this issue.

I'd recommend opening an issue over at https://github.com/DefinitelyTyped/DefinitelyTyped

Thank you!
