### ISSUE TITLE
Bug fix - plotly won't shrink beyond its initial height...

### ISSUE THREAD

**Issue by vicn1222** [plotly/plotly.js#4383]
I finally found the bug.

My plot won't shrink in height. It can grow in height when browser grows, just won't shrink when browser shrinks. It always sticks to the initial height when it was created. I have autosize=true and responsive=true.

The width can grow and shrink without problem.

After digging into the plotly.js, I found problem is in function lsInner, line 116030. I comment out that line, and everything works. I don't know why though...

I have tested in the following browsers:
  CenterOS 7: Chrome, Firefox
  Windows 10: Chrome, Firefox, IE
  iPad: Chrome, Firefox, IE, Safari (by rotating the screen and dragging my splitter that emit window resize event)
  iPhone: Same tests as iPad.

Can someone verify the change? If it is alright, please include the fix in the next release.

Thank you.

**Comment by vicn1222** [comment]
I changed both width and height to 'auto', and they still work:

lines 116029 & 116030
    fullLayout._paperdiv.style({
        //width: (gd._context.responsive && fullLayout.autosize && !gd._context._hasZeroWidth && !gd.layout.width) ? '100%' : fullLayout.width + 'px',
        //height: (gd._context.responsive && fullLayout.autosize && !gd._context._hasZeroHeight && !gd.layout.height) ? '100%' : fullLayout.height + 'px'
        width: 'auto',
        height: 'auto' 
    })

**Comment by etpinard** [comment]
Hi @vicn1222 - are you able to replicate this problem inside a controlled environment e.g. a codepen / jsFiddle / jsBin?

**Comment by vicn1222** [comment]
I don't know how to do codepen or jsFiddle...

However, I just switch back to use https://cdn.plot.ly/plotly-latest.min.js, the chrome no longer has the problem. This is very bizarre, as the bug was initially seen in Chrome. However, Microsoft Edge and IE 11 still have the same problem. 

Using "auto" for both width and height, all browsers work. 

I suspect in Microsoft, 100% is calculated based on the height of the browser, not its direct parent, that is why I see a scroll window and can't be turn off. while 'auto' is based on direct parent so it fills in the container without scroll window...just my guess...

**Comment by vicn1222** [comment]
I test this morning again. The bug comes back on Chrome, Microsoft Edge, and IE11 again. Using width='auto', height='auto', everything works as expected.

Is it because the session expires and the javascript gets completely reloaded?

**Comment by etpinard** [comment]
From the current bug report, I can't imagine any plotly.js dev spending time trying to pinpoint this underlying problems described in this issue, so I'll close this ticket.

@vicn1222 feel free to reopen another issue if you're able to reproduce the problem in inside a controlled environment (e.g. Codepen / jsFiddle / jsBin). Thank you!
