### ISSUE TITLE
Grouped horizontal legend are displayed vertically

### ISSUE THREAD

**Issue by gilles-crealp** [plotly/plotly.js#4394]
I do not know if this is the expected behavior but when you set legends horizontally and you group some legends, the grouped legends are displayed vertically.

See traces 0 to 4 in the screen capture.

![2019-12-02 08_51_39-plotly](https://user-images.githubusercontent.com/29562925/69940221-01961980-14e2-11ea-8d80-c57bffe9014a.png)

https://jsfiddle.net/0zct6ao8/

**Comment by etpinard** [comment]
Yes, this is exactly the expected behavior (unfortunately). 

I have discussed a few potential ways to improved things in https://github.com/plotly/plotly.js/issues/960

**Comment by etpinard** [comment]
Merged into https://github.com/plotly/plotly.js/issues/960#issuecomment-571777593
