### ISSUE TITLE
More exclusive regex for ify-loader

### ISSUE THREAD

**Issue by thatsmeta** [plotly/plotly.js#4395]
Hi, I'm using plotly.js with Angular 8 and followed the instructions in this as of yet open PR: https://github.com/plotly/plotly.js/pull/4182.
Could you help me find a more exclusive regex to put in the `test` section of the ify-loader rule?
```
module.exports = {
    module: {
        rules: [
            {
                test: /\.js$/,
                loader: 'ify-loader'
            }
        ]
    }
};
```
I have a rather large project and would like to avoid running all js files through the loader.
I'd like to limit the use of the loader to plotly / webgl files.

**Comment by etpinard** [comment]
Hi @thatsmeta 

Could you repost your question over on https://community.plot.ly/c/api/plotly-js? - This way, other users can help and benefit from the answer(s). Thanks!

**Comment by thatsmeta** [comment]
https://community.plot.ly/t/more-exclusive-regex-for-ify-loader/32098
