### ISSUE TITLE
Feature: allow typed arrays to be used for the data.transforms.groups value

### ISSUE THREAD

**Issue by danieljblinick** [plotly/plotly.js#4397]
I have a very high cardinality data set that I am trying to store only in typed arrays. Plotly already accepts typed arrays for the `data.x` and `data.y` values, which is great. However, I want to color the points based on the groups they belong to, and I would like to store those groups in a typed array as well. So instead of:
```
{
      type: 'scattergl',
      mode: 'markers',
      transforms: [{
        type: 'groupby',
        groups: [1, 2, 3]
      }]
}
```
it would be 
```
{
      type: 'scattergl',
      mode: 'markers',
      transforms: [{
        type: 'groupby',
        groups: new Uint8Array([1, 2, 3])
      }]
}
```
I looked at the code, and it seems to be as easy as changing the line 175 in [groupby.js](https://github.com/plotly/plotly.js/blob/master/src/transforms/groupby.js) from:
`if(!(Array.isArray(groups)) || groups.length === 0) {`
to something like:
`if(!(Array.isArray(groups) || groups.constructor === Uint8Array) || groups.length === 0) {`

would this be doable? Thanks!

**Comment by etpinard** [comment]
Yes that would be doable. Thanks for pointing this out.

I would personally vote for accepting all typed arrays using [`Lib.isArrayOrTypedArray`](https://github.com/plotly/plotly.js/blob/dbf02f1b47f2b0e17a1b78fabee815e3cde18715/src/lib/array.js#L28-L30) for consistency with the other array-typed-array logic in this library.

@danieljblinick would you be interested in making a PR for us?

**Comment by danieljblinick** [comment]
@etpinard okay great! yeah ill give it a shot, thanks 👍

**Comment by etpinard** [comment]
This one got done in https://github.com/plotly/plotly.js/pull/4410
