### ISSUE TITLE
How to find all config options for a plot attribute ?

### ISSUE THREAD

**Issue by ahetawal** [plotly/plotly.js#440]
Hi,
I am trying to find what all config options I can use for lets say the xaxis: {} object.
Where can I can find all the config options for this as such. Even in the source code its fine, but just need a place where I can look this up.
Currently, I am finding samples from python examples and try to port over to javascript configs.
Ex : Found this for python https://plot.ly/python/axes/#enumerated-ticks-with-tickvals-and-ticktext
but cant seem to find any for javascript ?

I am fine searching through source code, but need to understanding how to traverse the source for such things.

**Comment by cldougl** [comment]
You can check out attributes for the xaxis on the reference page: https://plot.ly/javascript/reference/#layout-xaxis

**Comment by ahetawal** [comment]
Wow, I was looking for this from a while now. Thank you !!
How do i land on to this page from the plot.ly website. Cant seem to find a direct link for this ?

**Comment by cldougl** [comment]
No problem!
Our js docs are here: https://plot.ly/javascript/ and you'll want to select Chart Attributes from the left side bar to get the reference page. 

To navigate from [plot.ly](https://plot.ly/) you can select Help in the header and from the [help page](http://help.plot.ly/) select [API Clients](https://plot.ly/api/) and select JS.

**Comment by ahetawal** [comment]
Thanks a lot !!
