### ISSUE TITLE
Chart not updating on dropdown event

### ISSUE THREAD

**Issue by shrutiwebgeek** [plotly/plotly.js#4400]
I am trying to create a line chart that changes according to a dropdown event using plotly.js. Consider the following bit of code, where "myDiv" is the id of div in HTML code and "dataBtn" is the id of the dropdown box. I am unable to show the line chart on the screen but if I print in console "dataRow" or "axisValue" I can see the values inside them. But when I change the dropdown second time then an error is shown "Uncaught TypeError: Cannot read property 'map' of undefined". I looked for reasons for the error and also solutions but nothing seems to work.

What does it mean can you help me here!

     var myPlot = document.getElementById('myDiv');
     var allRow = null

    Plotly.d3.csv(sample.csv), function(err, data){

    allRow = data
    var data = [];
    var layout = {'xaxis': {'title': 'Number of rows'}, 'yaxis':{'title': 'Data'} };
    Plotly.plot(myPlot, data, layout);

    $('#dataBtn').change( function selectedY(){
     var axisValue = $("#dataBtn :selected").val();
     var x_row = [], y_data = [];

     for(var i=0; i<allRow.length; i++){
       xrow = i;
       row = allRow[i];
       x_row.push(xrow);
       y_data.push(+row[axisValue]);

      var dataRow = {
       x: x_row,
       y: y_data,
       mode: 'line+markers',
       type: 'scatter',
       line: {
          color: '#000',
           width: 2
        }
      };
    }

    Plotly.restyle(myPlot, 'y', [[]]);
    Plotly.newPlot(myPlot, data[dataRow]);
    });
    });

**Comment by etpinard** [comment]
Replacing 

```js
Plotly.newPlot(myPlot, data[dataRow]);
```

with 

```js
Plotly.newPlot(myPlot, [dataRow]);
```

should do the trick.

-------------


I recommend using https://community.plot.ly/c/api/plotly-js for implementation questions of the likes in the future. Thank you.

**Comment by shrutiwebgeek** [comment]
Thank you, I initially contacted on the community platform but couldn't get any answer there, but I will keep that in mind.
