### ISSUE TITLE
Sankey tooltip position when orientation is set to vertical "v" 

### ISSUE THREAD

**Issue by holmesma** [plotly/plotly.js#4402]
Hi I found when Sankey orientation is set to "v" the tooltip is rendered in the wrong position is some cases.

[https://codepen.io/Marvalo/pen/YzPzoVv](https://codepen.io/Marvalo/pen/YzPzoVv)

<img width="821" alt="Screenshot 2019-12-03 at 11 16 36" src="https://user-images.githubusercontent.com/634290/70042155-af76f600-15be-11ea-88b7-e459ce7a23c0.png">

**Comment by antoinerg** [comment]
Thanks for reporting this @holmesma. This is a very bad regression :open_mouth:
