### ISSUE TITLE
Sankey node labels when orientation is set to vertical "v"

### ISSUE THREAD

**Issue by holmesma** [plotly/plotly.js#4403]
Hi I found that node labels are truncated when orientation is set to vertical "v" which is problematic for printing or exporting.

If there were an option for node labels to render diagonally as seen in some bar charts this would help.

[https://codepen.io/Marvalo/pen/YzPzoVv](url)

<img width="821" alt="Screenshot 2019-12-03 at 11 17 03" src="https://user-images.githubusercontent.com/634290/70043315-8bb4af80-15c0-11ea-8c71-eab14151c490.png">

**Comment by antoinerg** [comment]
Thanks for pointing this out @holmesma !

Because of the limited horizontal space between nodes, it's not clear what should be done. The easiest thing to do would be to rotate the labels to make them vertical. Does anyone have a better idea?

cc @nicolaskruchten @etpinard

**Comment by holmesma** [comment]
An option to be able to rotate them to a certain degree would be great.

**Comment by mallikkommaraju** [comment]
Hi @holmesma I also face the same issue. I wish there was a flag to allow the label to be trimmed or not. How did you solve your issue? Did you rotate the label...if so how?

I moved back to using horizontal orientation but it is not the best visualization in my case...

Thank you,
Mallik
