### ISSUE TITLE
Feature: add a way to 'extend' a plot in a sorted way

### ISSUE THREAD

**Issue by bearsh** [plotly/plotly.js#4408]
using Plotly,extendTraces() appends the data to the end. What about a way to 'insert' new data in a sorted way?

**How should it work?**
if I have the following plot with
`x: [t, t+10, t+20]`
`y: [1,2,3]`

a call to Plotly.extendTraceSorted() with
`x: [t+5, t+15], y: [5, 5]`

should insert the pair in a sorted way based on x:
`x: [t, t+5, t+10, t+15, t+20]`
`y: [1, 5, 2, 5, 3]`

**Why**
This allows to first render a graph with much less datapoints (e.g. scatter plot, sensor data, every 10min). later either by user request or timed add more and more datapoints until all data is plotted. or only add points for a timespan the user zooms in.

what do you think?

**Comment by etpinard** [comment]
I think you can get the desired behaviour using a `sort` transform:

https://codepen.io/etpinard/pen/WNbpmzV?editors=1010

**Comment by etpinard** [comment]
Closing to due lack of activity.
