### ISSUE TITLE
Missing wedges / sectors in sunburst and treemap

### ISSUE THREAD

**Issue by emmanuelle** [plotly/plotly.js#4422]
See https://codepen.io/emmanuelle-plotly/pen/yLyaOjJ?&editable=true (sunburst)
and https://codepen.io/emmanuelle-plotly/pen/dyPpMmK?&editable=true (treemap).

The issue is that some sectors of the lowest level are not represented (maxdepth is None), but they appear when going down in the hierarchy. This is more visible in the sunburst example with the missing wedges (the outer ring should be full), which appear when you click on intermediate levels. But the same happens in the treemap chart (there should be a sector labelled by a number in each box).

I can try to make a smaller example if this one is hard to debug as it is.

**Comment by archmoj** [comment]
The `ids` are not identical. Right?

**Comment by emmanuelle** [comment]
Oh you're right there are identitical ids, which is bound to cause problems. OK, most likely that the problem is on my side. Thank you @archmoj , I'll investigate and (probably) close the issue.

**Comment by etpinard** [comment]
Related: https://github.com/plotly/plotly.js/issues/4335

**Comment by emmanuelle** [comment]
Thank you to both! At least in the `plotly.express` function we should be able to detect duplicated ids.
