### ISSUE TITLE
Wrong bar layout on the horizontal axis when using 'histogram' in plotly-cartesian

### ISSUE THREAD

**Issue by cebamps** [plotly/plotly.js#4429]
When using the `plotly-cartesian` in place of the `plotly` distribution in the latest version (1.51.3, also reproducible in 1.51.1), for some inputs the histogram bars are incoherently laid out on the horizontal axis.

Some other inputs do not seem cause that issue.

The problem does not appear when substituting `https://cdn.plot.ly/plotly-1.51.3.js`.

### Minimal reproduction of the issue
https://jsfiddle.net/c8gfb6rp/2/
```js
var x1 = [1,3];
var x2 = [1,20];

var trace1 = {
  x: x1,
  type: "histogram",
};
var trace2 = {
  x: x2,
  type: "histogram",
};
var data = [trace1, trace2];
var layout = {barmode: "stack", height: 200, width: 400, margin: {t:30, b:30}};

Plotly.plot("plot", data, layout);
```

### Screenshots
Here is what it looks like in the jsfiddle above.

Using `plotly-cartesian` (bug):
![hist-plotly-cartesian](https://user-images.githubusercontent.com/12797742/70982809-efa6a000-20b7-11ea-938c-e1a3392058c0.png)

Using `plotly` (expected behavior):
![hist-plotly](https://user-images.githubusercontent.com/12797742/70982808-efa6a000-20b7-11ea-8834-eeb0a915232e.png)

**Comment by etpinard** [comment]
Thanks for reporting!
