### ISSUE TITLE
reversescale doesn't reverse colorbar on contour plot with coloring='heatmap'

### ISSUE THREAD

**Issue by harupy** [plotly/plotly.js#4430]
### Bug

`reversescale: True` doesn't reverse the colorbar on a contour plot with `{contours: {coloring: 'heatmap'}}`.

In the plot below, the colorbar indicates the red region has larger values, but it actually has smaller values.

![plotly-issue](https://user-images.githubusercontent.com/17039389/71063572-498a9100-21b0-11ea-9f96-b4fffa88227a.gif)

### Code

```javascript
var data = [{
  z: [[10, 10.625, 12.5, 15.625, 20],
      [5.625, 6.25, 8.125, 11.25, 15.625],
      [2.5, 3.125, 5., 8.125, 12.5],
      [0.625, 1.25, 3.125, 6.25, 10.625],
      [0, 0.625, 2.5, 5.625, 10]],
  x: [-9, -6, -5 , -3, -1],
  y: [0, 1, 4, 5, 7],
  type: 'contour',
  contours: {
    coloring: 'heatmap'
  },
  reversescale: true,
}];

var layout = {
  title: 'Setting the X and Y Coordinates in a Contour Plot'
};

Plotly.newPlot('myDiv', data, layout);
```
 
### Codepen
https://codepen.io/harupy/pen/bGNgBOz

**Comment by harupy** [comment]
Without `{contours: {coloring: 'heatmap'}}`, it works.

![plotly-issue-2](https://user-images.githubusercontent.com/17039389/71064532-a8510a00-21b2-11ea-944a-444014dbc0f6.gif)


### Code

```javascript
var data = [{
  z: [[10, 10.625, 12.5, 15.625, 20],
       [5.625, 6.25, 8.125, 11.25, 15.625],
       [2.5, 3.125, 5., 8.125, 12.5],
       [0.625, 1.25, 3.125, 6.25, 10.625],
       [0, 0.625, 2.5, 5.625, 10]],
  x: [-9, -6, -5 , -3, -1],
  y: [0, 1, 4, 5, 7],
  type: 'contour',
  reversescale: true,
}];

var layout = {
  title: 'Setting the X and Y Coordinates in a Contour Plot'
};

Plotly.newPlot('myDiv', data, layout);
```

### Codepen
https://codepen.io/harupy/pen/NWPddqQ

**Comment by harupy** [comment]
Do we need to flip the colorscale here?
https://github.com/plotly/plotly.js/blob/adf9bee14a8badcb5b2f49065fd594623421c82e/src/traces/contour/colorbar.js#L22-L28

**Comment by etpinard** [comment]
Thanks for reporting!

**Comment by harupy** [comment]
@etpinard Thanks!
