### ISSUE TITLE
Some jasmine tests fail depending on the screen resolution of the computer running the test

### ISSUE THREAD

**Issue by monfera** [plotly/plotly.js#444]
When running tests in the Default resolution of a 13" MacBook, all of `click_test.js` passed; however, four failures were reported after increasing the resolution to the maximum in System Preferences. After much fiddling on my part, @etpinard suggested it may be to do with the browser window size. Indeed, the browser window was of a different size, depending on the resolution:

- Default resolution: 1035 x 617
- Highest resolution: 792 x 867

Manually resizing the already existing Chrome window and rerunning the test made it pass, confirming the suspicion that failure is due to less than expected viewport width.

**Comment by mdtusz** [comment]
Interesting. Is this because of the viewport width (and plots are being rendered at a different pixel-width?) or because of how OSX/Chrome handles pixel scaling when using the increased resolution mode?

In any case, it would probably be a good idea if we make sure all our tests have explicitly set widths and heights.

**Comment by monfera** [comment]
@mdtusz For this specific issue, it's the former. The devicePixelRatio is the same in both resolutions, the width was different (and Chrome even gave a different aspect ratio for the higher resolution mode). But in general it's true that there are multiple variables to consider, e.g.

- The devicePixelRatio is important for Canvas and WebGL, because, without scaling up with it, the output will be pixelated (aliased). On a multimonitor setup, it can be different per monitor.
- The browser zooming level is another variable. Maybe it's possible for it to get stuck at a non-100% level, failing a bunch of test cases.
- Minimum font size might also impact pixel based comparisons, and potentially even jasmine tests.

I haven't tried to address these other variations in this little PR. 

My $.02 is it's useful to set the screen size in test cases, e.g. to test window size responsiveness. It's also useful to have a basic window size for those type of tests that are not width/height sensitive or haven't (yet?) been sized explicitly. My immediate motivation was to be able to run the test suite without errors so it's but a small step.
