### ISSUE TITLE
coloraxes with values for sunburst and treemap 

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#4443]
Shared `coloraxes` should be implemented for `sunburst` and `treemap`.

**Comment by etpinard** [comment]
Hmm. They seem to work fine already:

https://codepen.io/etpinard/pen/zYxdKRw

**Comment by archmoj** [comment]
Interesting. So the user have to provide a color array and cannot use values, right?

**Comment by etpinard** [comment]
> Interesting. So the user have to provide a color array and cannot use values, right?

Well, too late for that. You handle the `values` w/o `marker.colors` case here:

https://github.com/plotly/plotly.js/blob/e778644e1182e13126db6b801af6dd0a386372ba/src/traces/sunburst/calc.js#L203-L205

**Comment by nicolaskruchten** [comment]
Does this really belong in the 1.52 milestone?

**Comment by etpinard** [comment]
It's done in https://github.com/plotly/plotly.js/pull/4444 - which we'll merge at some point today
