### ISSUE TITLE
Performance delay for extending multiple traces frequently

### ISSUE THREAD

**Issue by Ram-97** [plotly/plotly.js#4455]
Hello,
I have created the SPC chart and extending the multiple traces frequently (Every 20 ms). Here is my [code](https://codepen.io/Ram97/pen/qBEPPmy).  As you can see the console in developer mode, the time taken to extend the multiple traces increasing based on the existing x and y arrays that was already plotted. 

If we extending single trace, the performance is very good.

**Comment by etpinard** [comment]
Thanks for posting. 

I'll merge your report into https://github.com/plotly/plotly.js/issues/2358
