### ISSUE TITLE
Handle symbol numbers in string format

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#4460]
[Demo](https://codepen.io/MojtabaSamimi/pen/eYmyBJJ?editors=0010)

**Comment by alexcjohnson** [comment]
I suspect this line:
https://github.com/plotly/plotly.js/blob/29b456eafdfb9bc3b949918df557b200d9790486/src/components/drawing/index.js#L253

Just needs to be changed to `if (!isNumeric(v)) {`
