### ISSUE TITLE
Can't set 'colorbar' parameters in layout.template.data.{trace}[i].{line|marker}

### ISSUE THREAD

**Issue by wbrgss** [plotly/plotly.js#4467]
Setting `colorbar` parameters doesn't appear to work in `layout.template.data.{trace_type}[i].{line|marker}`.

Related: https://github.com/plotly/plotly.js/issues/3100#issuecomment-429374392, to quote @etpinard:

> As for the colorbar part, the problem comes from the colorbar defaults call:
> 
> https://github.com/plotly/plotly.js/blob/d34015066c8d339f041c9ac5ae68762a342d5d86/src/components/colorscale/defaults.js#L62
> 
> where `containerOut` is `fullData[i]` for heatmap, but is `fullData[i].marker` for scatter and other marker colorscales. Colorbar templates propagate correctly (using [`Template.newContainer`](https://github.com/plotly/plotly.js/blob/d34015066c8d339f041c9ac5ae68762a342d5d86/src/components/colorbar/defaults.js#L23))  from `fullData[i]`, but **not** from marker containers. Adding
> 
> ![image](https://user-images.githubusercontent.com/6675409/46880073-b3254780-ce15-11e8-9c0f-9d3aa6738c56.png)
> 
> should be enough to fix this, but we should look for other situations where supply-defaults subroutines are called with trace sub-containers.

-----

I'm not sure the above suggested fix was ever implemented.

This codepen demonstrates the issue with `ypad`:
https://codepen.io/wbrgss/pen/NWPXEPG

I logged a separate issue related to #3100 in #4466

**Comment by wbrgss** [comment]
To be more specific, I've noticed this for `line` as well as `marker` colorscales, including `scatter` but also `parcats` and `splom`.

**Comment by etpinard** [comment]
Thanks for pointing this out. 

I botched https://github.com/plotly/plotly.js/commit/6a47d6611e8ed3400f93d3c572eb17943bd1eadd for `colorbar` containers. 

----

Please note that `line` colorscales are not supported in scatter lines (they are in `marker.line`) and that `splom` traces only support markers.
