### ISSUE TITLE
modeBarButtons name changing

### ISSUE THREAD

**Issue by cerencimer** [plotly/plotly.js#4468]
Hi, I want to change modeBarButtons names. We are developing Turkish languages application. I am using ['zoomIn2d', 'zoomOut2d', 'resetScale2d', 'pan2d', 'zoom2d'] buttons.  How can I change?

**Comment by etpinard** [comment]
Hi,

I'm assuming you're referring to the button names as listed in [`modebar/buttons.js`](https://github.com/plotly/plotly.js/blob/master/src/components/modebar/buttons.js). These are meant to be internal, so they're not covered in the our locale translations. Maybe you could share a bit more details about your application?

If you're looking to translate on-hover description of the buttons (e.g ["Zoom"](https://github.com/plotly/plotly.js/blob/9fc2c82ed77b7f1884a9ecc8dcdb337ce9c2fb91/src/components/modebar/buttons.js#L103)) in Turkish, I suggest filling up the Turkish locale translations in [`locales/tr.js`](https://github.com/plotly/plotly.js/blob/master/lib/locales/tr.js). You can look past translation PRs [here](https://github.com/plotly/plotly.js/pulls?q=is%3Apr+translation+label%3A%22type%3A+translation%22+is%3Aclosed) for inspiration.

**Comment by cerencimer** [comment]
Thank you, I looked locales/tr.js but, dictionary is empty, 

I want to add some translation here, what should I do?

        'Autoscale': 'Oto-ölçekleme',
        'Download plot': 'Grafiği indir',
        'Pan': 'Kaydır'
        'Reset axes': 'Başa Döndür',
        'Zoom': 'Yakınlaştır/Uzaklaştır',
        'Zoom in': 'Yakınlaştır',
        'Zoom out': 'Uzaklaştır'

**Comment by etpinard** [comment]
https://github.com/plotly/plotly.js/blob/master/.github/PULL_REQUEST_TEMPLATE.md#translations has some info on how to get started on making a translation PR.

Let us know if you more details.

**Comment by etpinard** [comment]
Closing. 

Filling in the Turkish locale translations in `locales/tr.js` will be enough to fix the problems described in this ticket. As we don't need an open ticket for all missing translations, I'll close this issue.
