### ISSUE TITLE
add more locales: `pl`, `ar`, `az` and more

### ISSUE THREAD

**Issue by mine-this-piece-of-floor-is** [plotly/plotly.js#4471]
Hi,
Is there a possibility to fix Polish (pl) locale in plotly because it does not work? When chosen in config only english subtitles appear. I have checked some other locales and also do not work: af, am, ar-dz, ar-eg, ar, az. For example "ja" works so my code is ok. My code:
p <- p %>% config(locale = "pl").

Please :)

Best regards,

Kris

**Comment by etpinard** [comment]
Nobody has filled in the polish translation keys yet (see [`lib/locales/pl.js`](https://github.com/plotly/plotly.js/blob/master/lib/locales/pl.js)), same `ar` and `az` and many other locales. We rely on native speakers submitting the translations in pull requests.

If you're interesting in filling in translation keys for languages you know, please refer to https://github.com/plotly/plotly.js/blob/master/.github/PULL_REQUEST_TEMPLATE.md#translations on how to get started. You may want to look at [past translation PRs](https://github.com/plotly/plotly.js/pulls?q=is%3Apr+is%3Aclosed+label%3A%22type%3A+translation%22) for inspiration.

**Comment by etpinard** [comment]
As locale translations are done by community devs, we don't need an open ticket listing all the locales that didn't get filled in yet. 

We <strike>could</strike> should however add a way to find missing translations in a locale as described in https://github.com/plotly/plotly.js/issues/2269 to help us keep things up-to-date better.
