### ISSUE TITLE
unified hoverlabels

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4477]
We need a new `hovermode` like `xunified`/`yunified` that would produce a single hoverlabel that would contain info about all the points at a given `x`/`y` ... similar to `hovermode=x` but with a single hover. Like this:

![image](https://user-images.githubusercontent.com/203523/72090974-1d5cbe80-32dd-11ea-9326-9933aba4fead.png)

Other libraries which implement this include eCharts (ignore the "follow-me" aspect here, it's not in-scope for this issue and it's discussed here #3899 ) https://www.echartsjs.com/examples/en/editor.html?c=line-stack and https://www.fusioncharts.com/ (scroll down a bit)

**Comment by nicolaskruchten** [comment]
In terms of what goes into the hoverlabel, i'm partial to the idea of having it be essentially the legend, with another column of values to the right.

**Comment by nicolaskruchten** [comment]
C3 also does this with vertical follow-me only https://c3js.org/samples/chart_bar.html

**Comment by antoinerg** [comment]
In echartjs, the order of the items is always the same (ie. it is ordered by trace index). In C3.js, it is ordered by the value of the hovered data point. I think we want the latter as a default. However, do you see a use case for supporting items ordered by trace index?

cc @nicolaskruchten

**Comment by antoinerg** [comment]
Also, I can't remember what decision was made about the positioning of the unified hover label. Where should it be positioned?

cc @nicolaskruchten

**Comment by antoinerg** [comment]
Also, I can't remember what decision was made about the positioning of the unified hover label. Where should it be positioned?

cc @nicolaskruchten

**Comment by nicolaskruchten** [comment]
Ordering: let's make that a parameter, default to legend order. Positioning: median of the range in the Y dimension, and same X position as our current ones (in "unified x" mode)
