### ISSUE TITLE
Scatter 3D - Support selectedpoints, selected, unselected

### ISSUE THREAD

**Issue by joshua-gould** [plotly/plotly.js#4479]
I have a 3d and 2d plot of the same data. Users can select points in the 2d plot. It would be nice if they were styled the same way in the 3d plot (I can set marker size, opacity myself on the 3d plot, but this would make it easier. It would also be a first step in supporting a lasso tool for 3d plots). Thanks.

**Comment by etpinard** [comment]
Merging with https://github.com/plotly/plotly.js/issues/3511
