### ISSUE TITLE
geo.visible vs template...showland

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4482]
Right now, `layout.geo.visible=false` doesn't override `layout.template.layout.geo.showland=true` but it should.

**Comment by archmoj** [comment]
Bug [demo](https://codepen.io/MojtabaSamimi/pen/ZEYobOQ?editors=0010)

**Comment by alexcjohnson** [comment]
Hmm this is a bit of a tricky case but I think you're right to consider it a bug.  We have two inheritance pathways: the more-specific value from the template and the more-general value set explicitly, and normally the template wins but here we want the explicit-but-general value to win. I'm wondering if there are other cases like this - for example, should `layout.xaxis.color` beat out `layout.template.layout.xaxis.linecolor` to determine final `fullLayout.xaxis.linecolor`?

An additional wrinkle though: what if you set BOTH in the template and NEITHER in the main layout? ie `layout.template.layout.geo.showland=true` and `layout.template.layout.geo.visible=false` and you don't set `layout.geo.visible` or `layout.geo.showland`? We need to ensure that in this case `showland` will end up `true`, so we can't even trust the coerced value of `fullLayout.geo.visible`

**Comment by nicolaskruchten** [comment]
Yes, agreed that it's tricky.

Agreed that `layout.template.layout.geo.visible=false` and `layout.template.layout.geo.showland=true` and `layout.geo.visible=null` and `layout.geo.showland=null` should result in land showing only IMO, so you can't use the "normal" machinery.

**Comment by archmoj** [comment]
Should we override all these? Or only 'showland'?
```
'lonaxis.showgrid',
'lataxis.showgrid',
'showcoastlines',
'showocean',
'showland',
'showlakes',
'showrivers',
'showcountries',
'showsubunits',
'showframe'
```

**Comment by nicolaskruchten** [comment]
all of the above except for `*axis.showgrid` I would think.

**Comment by archmoj** [comment]
Why should we skip `*axis.showgrid`?

**Comment by nicolaskruchten** [comment]
Ah I see that `geo.visible` currently impacts `showgrid` per https://github.com/plotly/plotly.js/commit/0909f339c0e481b2ba882491b3e544d5cc5eb47d  so... OK for `showgrid` too.

**Comment by etpinard** [comment]
> I'm wondering if there are other cases like this - for example, should `layout.xaxis.color` beat out `layout.template.layout.xaxis.linecolor` to determine final `fullLayout.xaxis.linecolor`?

Did anyone look into `axis.color` and `axis.visible` behave in and out of templates?
