### ISSUE TITLE
top line (border) not visible when grid is used in candlestick chart

### ISSUE THREAD

**Issue by pavitrakumar78** [plotly/plotly.js#4484]
Hi,

I'm trying to add a border to my candlestick chart which uses a grid. The issue here is that the top border or the line that is supposed to also be on the top (using `linewidth`) of the chart is not visible.   

Here is the demo: https://jsfiddle.net/pavitrakumar/8dtu4oyz

If I set the grid parameter `roworder` to `bottom to top` from `top to bottom`, then I see the top border, but only a portion of the bottom border. Why does this happen?

I'm not sure if this has been raised as an issue here - I tried searching, but I wasn't able to find anything very specific like this.

**Comment by etpinard** [comment]
Note that by default the `grid` settings generate linked subplots. Switching `xaxis.mirror: true` for `xaxis.mirror: 'all'` in https://jsfiddle.net/qhym06fL/ seems to give the behaviour you're looking for,

More info:

- https://plot.ly/javascript/reference/#layout-grid-pattern
- https://plot.ly/javascript/reference/#layout-xaxis-mirror
