### ISSUE TITLE
Add opacity effect to mapbox layers sourcetype "image"

### ISSUE THREAD

**Issue by meteoDaniel** [plotly/plotly.js#4490]
Dear all would be great to have this feature. 

I asked why it is not working in the plotly.py project: https://github.com/plotly/plotly.py/issues/2077

```
import plotly.graph_objects as go

fig = go.Figure(go.Scattermapbox(), layout=dict(width=600, height=450))
mapbox = dict(zoom= 4.5,
              style='open-street-map',
              center=dict(
                        lat=42,
                        lon=-74.5),
              layers=[
                  dict(
                  below ='',
                      opacity=0.6,
                  source = "https://docs.mapbox.com/mapbox-gl-js/assets/radar.gif",
                  sourcetype= "image",
                  coordinates =  [
                          [-80.425, 46.437], [-71.516, 46.437], [-71.516, 37.936], [-80.425, 37.93]
                                 ])
                     ])
fig.update_layout(mapbox=mapbox)
fig.show()
```

**Comment by etpinard** [comment]
Thanks for reporting. I'll call this a bug as `opacity` is part of the mapbox layout layer attributes.

Fixing this bug should be as easy as adding `'raster-opacity': opts.opacity` to

https://github.com/plotly/plotly.js/blob/8122c2127c12b50cb20207d676aa24e3a786f305/src/plots/mapbox/layers.js#L248-L250

similar to https://docs.mapbox.com/mapbox-gl-js/example/adjust-layer-opacity/

**Comment by meteoDaniel** [comment]
Great for this fast support guys !
