### ISSUE TITLE
Group By example produces schema error

### ISSUE THREAD

**Issue by tboerstad** [plotly/plotly.js#4496]
The Group By example, https://plot.ly/javascript/group-by/, produces a Schema Error for each of the three groups if you call `Plotly.validate()`. See the developer console in this example:
https://codepen.io/tboerstad/pen/povxLGq

The error message is `"In data trace 0, key transforms[0].styles[1].value.marker is not part of the schema"`.

The functionality seems to be working as intended

**Comment by etpinard** [comment]
Thanks for reporting!
