### ISSUE TITLE
Group By legend item missing for TypedArray if target == 0

### ISSUE THREAD

**Issue by tboerstad** [plotly/plotly.js#4497]
I am using a typed array as the `groups` variable to a Group By transform. 
This works as intended, except for the label text disappearing if the target value is `0`. 
Other target values work fine. 

See example, where the `0` target has an empty trace name:
https://codepen.io/tboerstad/pen/NWPOMde

I'm not aware if there is anyway to specify the trace name when using typed arrays, if it is, it would 
be possible to use that as a work around.

**Comment by etpinard** [comment]
> See example, where the `0` target has an empty trace name:

Found it:

![image](https://user-images.githubusercontent.com/6675409/73213167-bb45eb00-411d-11ea-8818-e9343dfbd056.png)

Thanks for reporting!
