### ISSUE TITLE
Is it possible to change the DEFAULT date format of the tickformat from MMM DD, YYYY to MM/DD/YYYY ?(Only for the values where date is changing, and not of all ticks)

### ISSUE THREAD

**Issue by achaturv** [plotly/plotly.js#4498]
When I plot a graph with date type with default tickformat, it always get the first date in MMM DD, YYYY. This is how I am currently getting.
![image](https://user-images.githubusercontent.com/590043/72704532-0771b800-3b7f-11ea-9120-9054c48ac5a5.png)

Is it possible to change this default tickformat to dd/mm/yyyy only for the first legend on the x-axis.

**Comment by archmoj** [comment]
Please use https://community.plot.ly/ for questions like this.
