### ISSUE TITLE
Null values show up as thin bars in Bar chart if you set an axis range including 0.

### ISSUE THREAD

**Issue by kei51e** [plotly/plotly.js#4499]
If you have null values in y, those show up as thin bars in Bar chart if you set an axis range that includes 0.

![image](https://user-images.githubusercontent.com/68080/72707387-25a2ce00-3b15-11ea-9949-b8d2920adb35.png)

Here is a pen. 

https://codepen.io/kei51/pen/KKwraMX

It doesn't happen on an older version of Plotly like 1.47.4.

https://codepen.io/kei51/pen/XWJypEO

**Comment by etpinard** [comment]
Thanks for reporting!

This should have been fixed as part of https://github.com/plotly/plotly.js/pull/4056 unless I'm missing something. @archmoj can you comment?

**Comment by archmoj** [comment]
Hmm... this [demo](https://codepen.io/MojtabaSamimi/pen/BayExay) using #4056 renders OK.
The problem should be caused by another PR in [1.48.0](https://github.com/plotly/plotly.js/releases/tag/v1.48.0)
Investigating...

**Comment by archmoj** [comment]
Improved [bug demo](https://codepen.io/MojtabaSamimi/pen/rNabvjJ?editors=1000).
This is only a problem in interactive mode. Download PNG works OK (does not show empty bars).
Related to this block: https://github.com/plotly/plotly.js/blob/8122c2127c12b50cb20207d676aa24e3a786f305/src/traces/bar/plot.js#L193-L201

**Comment by kei51e** [comment]
Thank you very much for the fix!
