### ISSUE TITLE
Is it possible to make Rounded edges to the Bar Charts?

### ISSUE THREAD

**Issue by dinmaduraimani** [plotly/plotly.js#4500]
When I plot a Bar Charts, i would expect the rounded corner for each bars, sample screenshot for your reference.

![image](https://user-images.githubusercontent.com/45810749/72718931-e0c27a00-3b9c-11ea-993e-30271dc28380.png)

**Comment by antoinerg** [comment]
@dinmaduraimani, unfortunately, this is not yet implemented. There is already an issue for this feature so I will close this one.

Closing in favor of https://github.com/plotly/plotly.js/issues/2196

**Comment by RevathiSekar** [comment]
Any update on this?

**Comment by nicolaskruchten** [comment]
See #2196 :)
