### ISSUE TITLE
add line width to parcoords

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#4504]
From https://community.plot.ly/t/how-to-change-line-width-of-parallel-coordinates-parcoords/9758/5

**Comment by etpinard** [comment]
Essentially a duplicate of https://github.com/plotly/plotly.js/issues/2573

@archmoj ok if we merge this ticket into https://github.com/plotly/plotly.js/issues/2573 ?

**Comment by archmoj** [comment]
Merging with #2573
