### ISSUE TITLE
Legend formatting

### ISSUE THREAD

**Issue by DMconduit** [plotly/plotly.js#4507]
Having an issue with legend formatting. Featuring Plotly in R within a flexdashboard running a Shiny app. The right side of the legend is cut off. This happens mostly in Chrome, less so in Safari. Image attached.
<img width="1150" alt="plotly legend cut off" src="https://user-images.githubusercontent.com/12718105/72949359-0e065800-3d56-11ea-8a0c-a78b1c8adffb.png">

The ui code looks like this:
ui <- fillPage(
  fillRow(flex = c(1.5,4),
        fillCol(
          radioButtons(...),
          selectInput(...),
          checkboxInput(..)
),
      plotlyOutput("plot", height = "100%")
    )
  )

**Comment by emmanuelle** [comment]
Hi @DMconduit I've transferred your issue to the javascript repository because you were not using Python.

**Comment by nicolaskruchten** [comment]
I actually think that the Plotly.R repo at https://github.com/ropensci/plotly might be a better fit for this issue if you're encountering it within a Shiny context... Sorry for the bounce-around!
