### ISSUE TITLE
Calling Plotly.restyle fires a plotly_click event

### ISSUE THREAD

**Issue by Luthaf** [plotly/plotly.js#4513]
See https://codepen.io/luthaf/pen/mdyvGLR for a reproduction. Clicking on one of the points fire the event in a loop and the script ends up killed by the browser (too much recursion on firefox).

I find it strange that calling Plotly.restyle would send a plotly_click event, hence this issue!

**Comment by etpinard** [comment]
Thanks for the report. Your codepen describes (in a nice minimal way, I might add) the exact same problem as in https://github.com/plotly/plotly.js/issues/1025.

Merging into https://github.com/plotly/plotly.js/issues/1025
