### ISSUE TITLE
Orthographic projection + zoom breaks hover and Plotly.restyle

### ISSUE THREAD

**Issue by Luthaf** [plotly/plotly.js#4514]
See https://codepen.io/luthaf/pen/oNgmavz

After zooming, the hover label no longer correspond to the mouse cursor position:
![Capture du 2020-01-23 17-34-35](https://user-images.githubusercontent.com/6141587/73003940-be339980-3e06-11ea-9294-9438e92f55ee.png)

Additionally, if I try to call Plotly.restyle after zooming, the camera resets to the default position. I don't know if this is intended or accidental.

---

Maybe related to #4239

**Comment by etpinard** [comment]
@Luthaf please confirm that this gif

![Peek 2020-01-27 15-53](https://user-images.githubusercontent.com/6675409/73212938-41156680-411d-11ea-8d0f-cc1a511037ee.gif)

corresponds to the problem you're describing.

**Comment by etpinard** [comment]
... and thanks very much for reporting, something wrong is indeed happening when hovering after zoom

**Comment by Luthaf** [comment]
> corresponds to the problem you're describing.

For the hover part, yes. There is also the issue with Plotly.restyle resetting the camera, which you can trigger by clicking on a point.

**Comment by archmoj** [comment]
All gl3d traces are affected by this bug.

**Comment by Luthaf** [comment]
Thanks for the fix, the hover issue seems to be fixed =)

> Additionally, if I try to call Plotly.restyle after zooming, the camera resets to the default position. I don't know if this is intended or accidental.

The zoom reset on Restyle seems to still be here on the updated version: https://codepen.io/MojtabaSamimi/pen/WNvbzZp?editors=1000

To trigger it, zoom and then click on a point. The camera resets to the default view.

**Comment by Luthaf** [comment]
Thanks a lot @archmoj !
