### ISSUE TITLE
Click events for waterfall charts not aligned

### ISSUE THREAD

**Issue by mtadams007** [plotly/plotly.js#4524]
I've been working with waterfall charts and added a click event. If the waterfall bar is negative, then the area where the click is ends up being misaligned. Sometimes one has to click far above the bar to trigger the click, while other times one cannot trigger the click at all.

See https://codepen.io/mtadams007/pen/KKwLpzR?editors=0010 for a working example. 

Thanks

**Comment by etpinard** [comment]
Thanks very much for posting!

The hover labels are also not working as intended under `hovermode: 'closest'`

![Peek 2020-01-29 11-48](https://user-images.githubusercontent.com/6675409/73377647-5a3d2500-428d-11ea-956c-c28091526ea5.gif)

(they worked fine under `hovermode: 'x'`)

**Comment by mtadams007** [comment]
Great! Thanks!
