### ISSUE TITLE
Mesh3d: false information displayed on hover when hovertemplate gives cell intensities or facecolor

### ISSUE THREAD

**Issue by empet** [plotly/plotly.js#4527]
When `intensitymode='cell'` and  the hovertemplate is defined like this:

`hovertemplate = "cell intensity":  %{intensity: .3f}"`

or if I define as `customdata`   the array of face center coordinates
and a hovertemplate of the form:

`hovertemplate ="fx: %{customdata[0]:.3f}<br>fy: %{customdata[1]:.3f}"+\
                                 "<br>fz: %{customdata[2]:.3f}<br>intensity: %{intensity:.3f}<extra></extra>"`
                            
the hoverbox that displays data related to the k<sup>th</sup> face is anchored at  the k<sup>th</sup> vertex, i.e. plotly.js associates face attributes to vertices and so hovering  is confusing and non-informative.  

It would be nice to provide hoverbox pointing to the face centers when a hovertemplate contains information related to faces.  
      
 This is a simplest example to illustrate the bug: [https://plot.ly/~empet/15474](https://plot.ly/~empet/15474).   It has 6 vertices and 8 faces. Plotly makes pairs `(vertex[k], intensity_face[k]), k 0,1,2,...5`. Hence the face intensity for the faces 6 and 7 are not even displayed.

In the right plot from this example  [https://plot.ly/~empet/15467](https://plot.ly/~empet/15467) if you are hovering the darkest face, you'll see the non-concordance between the associated color and the displayed intensity.

**Comment by archmoj** [comment]
@empet 
Thanks very much for reporting.
It turned out that there is a similar bug when using `facecolor`!
Here is a [demo](https://codepen.io/MojtabaSamimi/pen/yLyWEJj?editors=0010).

**Comment by empet** [comment]
@archmoj  I don't remember ever using facecolor, because for a mesh with a big number o faces it's difficult to find and write explicitly so many  color codes.

**Comment by archmoj** [comment]
This issue might be linked to #4533.

**Comment by empet** [comment]
Thanks @archmoj!

**Comment by archmoj** [comment]
@empet thank you for reporting!
