### ISSUE TITLE
Customizing style (dashed, dotted) of grid lines

### ISSUE THREAD

**Issue by emmanuelle** [plotly/plotly.js#4530]
There have been several requests in the past for changing the style of grid lines to dashed or dotted, see https://community.plot.ly/t/how-to-customize-grid-lisne-to-dotted-lines/2981 or https://community.plot.ly/t/dashed-or-dotted-grid-lines/34296. Probably not high priority, but just opening this issue as a placeholder to log the request.

**Comment by Willtl** [comment]
It would be nice to have an option to turn on dotted lines.

**Comment by archmoj** [comment]
+1

**Comment by Lvulis** [comment]
This issue was opened previously to address ggplotly converting dashed lines to solid lines: https://github.com/plotly/plotly.js/issues/4045

**Comment by DimaDDM** [comment]
+1

**Comment by etiennecelery** [comment]
+1

**Comment by Jace-Yang** [comment]
+1

**Comment by bliitzkrieg** [comment]
+1

**Comment by sladewang95** [comment]
+1

**Comment by ben-j-barlow** [comment]
+1

**Comment by njwhite** [comment]
I've tried to fix this with my  #6144

**Comment by artdreamer** [comment]
+1

**Comment by ua-chjb** [comment]
+1
