### ISSUE TITLE
splom customization

### ISSUE THREAD

**Issue by m--c** [plotly/plotly.js#4531]
Hi! This is a question, i'm new to this library. 
I'm currently working on a graph with type : 'splom'. It works as expected but I wonder itf it is possible to replace certain plots in the matrix with some other type of visualization. 
What I'm looking for can be seen here: https://plotly-r.com/interactives/ggpairs.html 
It is built with plotly-r. How could I achieve something like this with plotly js?

thanks

**Comment by etpinard** [comment]
We don't allow that unfortunately at the moment.

As this potential addition is already listed in https://github.com/plotly/plotly.js/issues/2555, I'll close this issue. I'd recommend subscribing to https://github.com/plotly/plotly.js/issues/2555 for the most up-to-date development info. Thanks!
