### ISSUE TITLE
Updatemenus: the update set by  {'yaxis2': {'visible': false}} is ineffective

### ISSUE THREAD

**Issue by empet** [plotly/plotly.js#4532]
In a fig with two buttons [https://plot.ly/~empet/15485](https://plot.ly/~empet/15485), the updatemenus is defined such that when the first button is clicked to be displayed three traces. Two of them are referenced  to the xaxis and a secondary yaxis. Clicking the second button only the trace referenced to xaxis, yaxis is set to be displayed, and this setting works, but  any attempt to make the  `'yaxis2'` invisible failed.
The arg
 `{ "yaxis2": { "visible": false } }`
 is innefective. However, it works when it is set directly via layout update.
Here: [https://gist.github.com/empet/9367eebc544b94937f026367c808ba94](https://gist.github.com/empet/9367eebc544b94937f026367c808ba94) is the json file to reproduce this bug.

**Comment by etpinard** [comment]
Here's a working version: https://codepen.io/etpinard/pen/NWPZqRg (in JS, but please let us know if you're having a hard time converting it to python code). In brief, you need to set

```js
layout.updatemenus[0].buttons[0].args = [
  { "visible": [true, true, true] },
  { "yaxis.ticksuffix": null,  "yaxis2.visible": true }
]

// and
layout.updatemenus[0].buttons[1].args = [
  { "visible": [false, false, true] },
  { "yaxis.ticksuffix": "%",  "yaxis2.visible": false }
]
```

-----

The updatemenu `args` syntax matches the arguments our [plotly.js top-level methods](https://plot.ly/javascript/plotlyjs-function-reference/). So, when setting `method: 'update'`, we expect:

```js
args: [ traces_update, layout_update, [, traceIndices] ]
```

which on-click is equivalent to calling

```js
Plotly.update(graphDiv, traces_update, layout_update, [, traceIndices] ]
```

Note also that setting something like

```js
layout.updatemenus[0].buttons[1].args = [
  { /* traces update */ },
  { "yaxis2": {"visible": false} }
]
```

means: _replace everything in `yaxis2` by `{"visible": false}`_ - which in your case leads to some unexpected results as you set

```js
        "yaxis2": {
            "side": "right",
            "anchor": "x",
            "overlaying": "y"
        },
```

on first draw.

**Comment by empet** [comment]
Thanks @etpinard   for working on my question. Here is the Python version with suggested updates: [https://chart-studio.plot.ly/~empet/15494](https://chart-studio.plot.ly/~empet/15494).
I think that there is a python bug related to the issue I opened, because with this Python code it works only partially when for Button B I set `{'visible': [false, false, true]}` (like in your plot) or `[false, true, false]` (this plot [https://plot.ly/~empet/15487](https://plot.ly/~empet/15487)).
It works  partially because at the first click on Button B all it's it's OK, but clicking the Button A again the bar plot is no more displayed.

My initial question was however related to the case `[true, false, false]` for Button B, because by definition, the Bar is referenced to (x,y), an the scatter traces to (x, y2). When I click B, I want to be displayed only the bar, and to remove yaxis2 ticklabels. With the updates suggested by you this case  works worse: [https://plot.ly/~empet/15489](https://plot.ly/~empet/15489), because a click on Button B leads to an empty plot.  The ticklabels for y2 are removed though.

**Comment by etpinard** [comment]
> Here is the Python version with suggested updates: https://chart-studio.plot.ly/~empet/15494.

Hmm, this version has 

```py
            args=[{"visible": [True, True, True] },
                                { "yaxis": {"ticksuffix": None}, 
                                  "yaxis2": {"visible": True } }],

# and
     args=  [{"visible": [True, False, False] },
                                  { "yaxis": {"ticksuffix": "%"}, 
                                    "yaxis2": {"visible": False } }],
```

which won't give the desired results as here you're asking `update` to replace the entire `yaxis` and `yaxis2` specifications. Try setting

**Comment by etpinard** [comment]
....

            args=[{"visible": [True, True, True] },
                                { "yaxis.ticksuffix": None, 
                                  "yaxis2.visible": True }],

# and
     args=  [{"visible": [True, False, False] },
                                  { "yaxis.ticksuffix": "%", 
                                    "yaxis2.visible": False }],
```

instead.

**Comment by empet** [comment]
Nice!!!!   Thanks!!

**Comment by etpinard** [comment]
No problem!
