### ISSUE TITLE
Mesh3d unable to hover on points positioned on the right side of the scene

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#4533]
In this [demo](https://codepen.io/MojtabaSamimi/pen/zYxVBVN?editors=0010) hover only shows up for the very first point! 
To hover on the other points one has to rotate the graph so that the point displays on the left side of the scene.

**Comment by archmoj** [comment]
[Working demo using v1.44.4](https://codepen.io/MojtabaSamimi/pen/qBEzaax?editors=1000)
This is a regression since v1.45.0.

**Comment by empet** [comment]
@archmoj  It seems that this issues manifests only for meshes wih big faces. In this case [https://plot.ly/~empet/15482](https://plot.ly/~empet/15482) the hoverboxes are displayed no matter where is the vertices position.

**Comment by archmoj** [comment]
@empet thanks for the feedback.
The issue is related to wrong write to/read from `mesh3d` pick layer i.e. impacted by `config.plotGlPixelRatio`.
By setting to 1 it works fine: [demo](https://codepen.io/MojtabaSamimi/pen/MWYMbEB?editors=0010).
I am trying to fix this in v1.52.2.
