### ISSUE TITLE
BarPolar with Overlay - Disable zoom feature

### ISSUE THREAD

**Issue by dinmaduraimani** [plotly/plotly.js#4544]
I have few questions on BarPolar chart type with overlay barmode.

* How to disable zoom feature, in normal bar chart we used to add fixedrange: true to the xaxis and yaxis to disable the zoom and cursor will change to pointer from crosshair
* How to differentiate the label color of each trace based on the value of the trace
* Need to display textoutside the bar

**Comment by etpinard** [comment]
Hi @dinmaduraimani - have you tried using our community forums (link: https://community.plot.ly/c/api/plotly-js) ? 

We like to keep our GitHub tracker for bug reports and feature requests only. Thank you!
