### ISSUE TITLE
update data corrupts bar plot

### ISSUE THREAD

**Issue by bhogan-mitre** [plotly/plotly.js#4545]
I have noticed some weird behavior when trying to `update` the data in a trace.  Is this to be expected, or is there a better way of doing this?

Suppose there is a basic bar plot:
![newplot](https://user-images.githubusercontent.com/32336739/73675141-e7162300-467f-11ea-8ef1-f281ce1faf37.png)

Updating the y values somehow wipes out the data to just an index of the entries, and flips it to a horizontal bar plot:
![newplot (1)](https://user-images.githubusercontent.com/32336739/73675479-791e2b80-4680-11ea-97c6-7b6c52cc9722.png)

Updating the x values seems to work better, although the axis tick labels are reset to just an index of the entries.
![newplot (3)](https://user-images.githubusercontent.com/32336739/73675658-d87c3b80-4680-11ea-8828-9be6bd4e1055.png)

Trying to update both the x and y values leads to an empty plot.
![newplot (4)](https://user-images.githubusercontent.com/32336739/73675689-e631c100-4680-11ea-8e5f-023facd9324a.png)

Reproducible example here:
https://jsfiddle.net/bhogan_mitre/12pmyL0q/

Note that I am trying to refresh the data in a plot, but hopefully without the "blink" that occurs with a `newPlot`.  The new data is not necessarily at the beginning or end of the existing data so `extendTraces` or `prependTraces` are not appropriate here.  Calling `react` appears to have the same behavior of wiping out the plot when I tried to update data, although I may not have had the syntax correct there.

**Comment by etpinard** [comment]
Here's a working version: https://jsfiddle.net/m3zhc59v/1/

The traces argument in a `Plotly.update` works the same way as in `Plotly.restyle`. You may want to review its different available call signatures here: https://plot.ly/javascript/plotlyjs-function-reference/#plotlyrestyle

In brief, the outer array in restyle/update calls maps to trace indices and the inner array maps to data indices.

**Comment by bhogan-mitre** [comment]
Great, thank you @etpinard!  I appreciate the pointers.
