### ISSUE TITLE
Gl3d hover not working on mobile and tablet since v1.34.0

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#4550]
Since [v1.34.0](https://github.com/plotly/plotly.js/releases/tag/v1.34.0) the gl3d hover not working on mobile and tablet devices 
[working demo using 1.33.x](https://codepen.io/MojtabaSamimi/pen/ZEGzrXJ)

**Comment by archmoj** [comment]
Possibly related to #2296.

**Comment by jdpaterson** [comment]
I would like to get this fixed. I think the commit where this stopped working is this one: https://github.com/plotly/plotly.js/commit/7221cd009ca9cb2eec02e1e4e602c03e9e07b1ef 

In camera.js if I change the 3 lines that say: 
`supportsPassive ? {passive: false} : false` 
to be 
`supportsPassive ? {passive: true} : false` 
then it works again.

**Comment by archmoj** [comment]
> I would like to get this fixed. I think the commit where this stopped working is this one: [7221cd0](https://github.com/plotly/plotly.js/commit/7221cd009ca9cb2eec02e1e4e602c03e9e07b1ef)
> 
> In camera.js if I change the 3 lines that say:
> `supportsPassive ? {passive: false} : false`
> to be
> `supportsPassive ? {passive: true} : false`
> then it works again.

@jdpaterson Would you interested to submit a PR?

**Comment by jdpaterson** [comment]
@archmoj I am would like to, but the file I mentioned above, "plots/gl3d/camera.js" doesn't exist anymore, it seems the logic has been moved elsewhere. Do we know where that logic might have been moved to? I'll keep looking

**Comment by archmoj** [comment]
> @archmoj I am would like to, but the file I mentioned above, "plots/gl3d/camera.js" doesn't exist anymore, it seems the logic has been moved elsewhere. Do we know where that logic might have been moved to? I'll keep looking

It is in `gl-plot3d` dependency: https://github.com/gl-vis/gl-plot3d/blob/master/camera.js

**Comment by jdpaterson** [comment]
Ok I'll make a PR there.
