### ISSUE TITLE
Wrong scaling on ggplotly facet_wrap within shiny

### ISSUE THREAD

**Issue by abbatidanilo** [plotly/plotly.js#4552]
Hello,

I met an issue on the plot result when using the ggplotly on ggplot with facet_wrap. This happens when there is a lot of *antigens* that is a lot of different plots to wrap together with *facet_wrap* 

This is the code generating the wrong scaling plots:
```
p <- ggplot(ggdf, aes(x = expression, color = sample_id, group = sample_id)) +
    geom_freqpoly(stat = "density") + 
    facet_wrap(~ antigen, scales = "free", ncol = colonne, nrow = righe) +
    scale_color_manual(values = sample_color)
  
  p <- ggplotly(p = p, originalData = TRUE)
```
Here colonne = 2 and righe = 12 so we have  24 plots wrapped together.

The same problem happens (but less often) outside shiny implementation and with both *originalData* parameter setting (FALSE or TRUE) 

As you can see below, only the first and the latest row are plotted correctly while all the plots in between are kind of compressed...

![newplot](https://user-images.githubusercontent.com/20769604/73833685-a72f7700-480a-11ea-9c60-efa91d5e1cee.png)

**Comment by etpinard** [comment]
Hi, I highly doubt the problem has to do with plotly.js code here, so it would be to open an issue over at https://github.com/ropensci/plotly/issues/new

Thank you!

**Comment by cpsievert** [comment]
Looks like you probably want to pass the size of the container to `ggplotly()`, like this:

https://github.com/ropensci/plotly/blob/master/inst/examples/shiny/ggplotly_sizing/app.R

Please file an issue here if you're still having issues -- https://github.com/ropensci/plotly/issues/new

**Comment by cpsievert** [comment]
(feel free to close @etpinard)

**Comment by abbatidanilo** [comment]
Thank you very much Sievert,
now it works perfectly, but now I have a doubt concerning the whole UI process with the *session$clientData*. The first time I run the routine and I try to pass the *session$clientData$output_pid_width* into the *ggplotly* function I only have the session$clientData$$output_pid_hidden available (the  *session$clientData$output_pid_width* and the *session$clientData$output_pid_height* are still *NULL*)
Is this normal (that is you have to output before to switch from hidden to active) or am I missing anything?
