### ISSUE TITLE
Browser lacks typed array (Uint8Array) support error in phantomjs

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#4556]
Possibly related to https://github.com/plotly/plotly.js/issues/895, but this specific error thrown by phantomjs 2.1.1 was introduced by plotly.js 1.50.0. For a minimal reproducible example, see https://gist.github.com/cpsievert/a6015fd914d1b4b7ac201e99a4234bd1

**Comment by etpinard** [comment]
Ok, and what happens when you add the [`typedarray.js`](https://github.com/plotly/plotly.js/blob/master/dist/extras/typedarray.min.js) polyfill **before** the plotly.js `<script>` ?

See https://github.com/plotly/plotly.js/tree/master/dist#to-support-ie9 for an example.

**Comment by cpsievert** [comment]
Same error (I updated the gist to include the polyfill)

**Comment by etpinard** [comment]
Here's a working version of your `plot.html` file:

```html
<head>
  <script>
    Object.setPrototypeOf = Object.setPrototypeOf || ({ __proto__: [] } instanceof Array ? setProtoOf : mixinProperties)

    function setProtoOf (obj, proto) {
      obj.__proto__ = proto
      return obj
    }

    function mixinProperties (obj, proto) {
      for (var prop in proto) {
        if (!Object.prototype.hasOwnProperty.call(obj, prop)) {
          obj[prop] = proto[prop]
        }
      }
      return obj
    }
  </script>
  <script src="https://cdn.plot.ly/plotly-1.50.0.min.js"></script>
</head>

<body>
  <div id="graph"></div>

  <script>
    var dat = [{
      "x": [1,2],
      "y": [1,2]
    }];

    var gd = document.getElementById("graph");

    Plotly.plot(gd, dat);
  </script>
</body>
```

-----

It turns our that `Uint8Array` is supported in phantomjs, but that `Object.setPrototypeOf` is not. That method is used in the `buffer` module to determine whether or not the environment supports typed arrays (see [logic](https://github.com/feross/buffer/blob/b172571deaa88be23d4f5bf9faebf4fbd7ce1749/index.js#L49-L60)).

Taking the polyfill definition from https://github.com/wesleytodd/setprototypeof/blob/master/index.js - things appear to work ok.

**Comment by cpsievert** [comment]
Awesome, thank you @etpinard! 🍻

**Comment by etpinard** [comment]
Can I close this one @cpsievert ?

**Comment by cpsievert** [comment]
Yea ok with me, thanks again!
