### ISSUE TITLE
Plotly.Fx.hover does not work with 'scattergl'

### ISSUE THREAD

**Issue by Queatz** [plotly/plotly.js#4557]
Codepen: https://codepen.io/queatz/pen/wvavmqJ

The example from https://plot.ly/javascript/hover-events/#triggering-hover-events only works for non-GL.  It should work the same with 'scattergl'

**Comment by etpinard** [comment]
Duplicate of https://github.com/plotly/plotly.js/issues/1963

Thanks for posting!
