### ISSUE TITLE
import latency

### ISSUE THREAD

**Issue by Phillip-M-Feldman** [plotly/plotly.js#4564]
When I import `plotly`, using Anaconda 2019.10 with Python 3.7, there is a latency of roughly 3 seconds.  (For comparison, on the same computer, it takes roughly half a second to import `matplotlib`).  Is there anything that can be done to reduce the `plotly` import latency?

**Comment by alexcjohnson** [comment]
duplicate of https://github.com/plotly/plotly.py/issues/740
