### ISSUE TITLE
Regression of bar plot axis scaling between 1.51.1 and 1.51.2

### ISSUE THREAD

**Issue by brubbel** [plotly/plotly.js#4567]
@archmoj 

https://github.com/plotly/plotly.js/commit/96ef28a76de609ca11adf475adba59a574ce3e59#diff-41fd60f1e6a06a5340748d3f4b3754e6R218-R225

This commit broke (my) bar plots which are **updated in chunks**. Horizontal axis of the bar plot stopped rescaling correctly between 1.51.1 and 1.51.2.
This has been working for years so this should be considered as a regression.

By removing this if statement it starts working again: https://github.com/plotly/plotly.js/blob/acc9c21c0239b4500b9787ab92203327b3abd033/src/traces/bar/plot.js#L218

**New behaviour:**
![image](https://user-images.githubusercontent.com/5667690/74196823-639b9980-4c5e-11ea-9173-ac335274af24.png)

**Version <= 1.51.1 (or above if-statement removed in 1.51.2):**
![image](https://user-images.githubusercontent.com/5667690/74196943-abbabc00-4c5e-11ea-847f-5d5a69c740f0.png)

If required, I'll try to construct a simple example to reproduce.

**Comment by archmoj** [comment]
@brubbel thanks for reporting.
Does this [demo](https://codepen.io/MojtabaSamimi/pen/xxGGPay?editors=0010) illustrate the bug?

**Comment by brubbel** [comment]
It seems so, at first sight.

**Comment by archmoj** [comment]
Related: #4522.

**Comment by brubbel** [comment]
Confirmed: I've Tested the demo with and without the if-statement, and it illustrates the same issue.

**Comment by archmoj** [comment]
I would like to possibly add another test to lock the behaviour.
@brubbel would you mind sharing the data and layout of your figure?
Thanks.

**Comment by archmoj** [comment]
In addition to #4522, I also think this could be related to #4180 as well.

**Comment by archmoj** [comment]
> In addition to #4522, I also think this could be related to #4180 as well.
Correction: regression is not related to #4180.

**Comment by brubbel** [comment]
@archmoj 
With the latest version (https://cdn.plot.ly/plotly-latest.min.js), and using your above [demo](https://codepen.io/MojtabaSamimi/pen/xxGGPay?editors=0010), the problem is solved.
However, it persists when the plot is downloaded using the png button:

![image](https://user-images.githubusercontent.com/5667690/83968764-b19e7200-a8cb-11ea-9dc9-fe9c02e361a2.png)

**Comment by alexcjohnson** [comment]
@brubbel the png behavior is not a regression - going back to v1.51.1 or earlier we see this same behavior that the bars disappear in the png output. We might consider it a bug, but this is a little tricky. Normally for a plot downloaded as an image we disable both rounding positions and `shape-rendering: crispEdges`, because the same machinery can produce vector output (eps, pdf, svg) and even for raster output it can scale up to higher resolution. In all of those cases this rounding and disabled antialiasing would degrade the output.

But for the default output of the download button - 1:1 scaled raster - it would make sense to carve out an exception and retain the behavior used on interactive plots.

**Comment by jackparmer** [comment]
This issue has been tagged with `NEEDS SPON$OR`

A [community PR](https://github.com/plotly/plotly.js/pulls?q=is%3Apr+is%3Aopen+label%3A%22type%3A+community%22) for this feature would certainly be welcome, but our experience is deeper features like this are difficult to complete without the Plotly maintainers leading the effort.

**Sponsorship range: $5k-$10k**

What Sponsorship includes:
- Completion of this feature to the Sponsor's satisfaction, in a manner coherent with the rest of the Plotly.js library and API
- Tests for this feature
- Long-term support (continued support of this feature in the latest version of Plotly.js)
- Documentation at [plotly.com/javascript](https://plotly.com/javascript/)
- Possibility of integrating this feature with Plotly Graphing Libraries (Python, R, F#, Julia, MATLAB, etc)
- Possibility of integrating this feature with Dash
- Feature announcement on [community.plotly.com](https://community.plotly.com/tag/announcements) with shout out to Sponsor (or can remain anonymous)
- Gratification of advancing the world's most downloaded, interactive scientific graphing libraries (>50M downloads across supported languages)

Please include the link to this issue when [contacting us](https://plotly.com/get-pricing/) to discuss.
