### ISSUE TITLE
sunburst text does not fit inside for 0-valued sectors

### ISSUE THREAD

**Issue by emmanuelle** [plotly/plotly.js#4569]
See https://codepen.io/emmanuelle-plotly/pen/JjdYPBN?editable=true, for the sector with 0 value the text label is still displayed even when setting `uniformtext` parameters. Changing the value to a very small number (e.g. 1.e-7) fixes the issue. Raised by https://community.plot.ly/t/help-with-sunburst-using-plotly-express-and-path/34823/

**Comment by emmanuelle** [comment]
I'm not sure whether this is fixed by https://github.com/plotly/plotly.js/pull/4519

**Comment by archmoj** [comment]
> I'm not sure whether this is fixed by #4519

@emmanuelle No #4519 is not related/helpful in this regard.

**Comment by archmoj** [comment]
[Minimal demo](https://codepen.io/MojtabaSamimi/pen/MWwaxpe?editors=0010)

**Comment by archmoj** [comment]
This in not related `uniformtext`.
Basically the text should not be displayed over the sector.
[Demo without uniformtext](https://codepen.io/MojtabaSamimi/pen/ZEGbPXL?editors=0010).

**Comment by archmoj** [comment]
Not a regression.
