### ISSUE TITLE
Yarn install fails

### ISSUE THREAD

**Issue by ulrich06** [plotly/plotly.js#4576]
Hi,

I'm facing an issue with plotly.js and yarn.

yarn add plotly.js

yarn add v1.12.3
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
warning plotly.js > regl-splom > left-pad@1.3.0: use String.prototype.padStart()
warning plotly.js > ndarray-fill > cwise > static-module > through2 > xtend > object-keys@0.4.0: 
warning plotly.js > point-cluster > bubleify > buble > os-homedir@2.0.0: This is not needed anymore. Use `require('os').homedir()` instead.
error Couldn't find package "3d-view@^2.0.0" required by "gl-plot3d@^2.4.2" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

Any hint to solve it?

Many thanks

**Comment by ieglonew01f** [comment]
Yes I'm facing this issue too since yesterday

**Comment by pareshbbb** [comment]
Even I am facing the same with npm

**Comment by ieglonew01f** [comment]
I suspect this commit https://github.com/plotly/plotly.js/commit/4a4bdea15a5e204f373303a1c81ee32ddc66da09

**Comment by jbbpatel94** [comment]
Try to install manually

` npm i git://github.com/mikolalysenko/3d-view`

and then run `npm install`

**Comment by archmoj** [comment]
> I suspect this commit [4a4bdea](https://github.com/plotly/plotly.js/commit/4a4bdea15a5e204f373303a1c81ee32ddc66da09)

Could you please explain why?

**Comment by archmoj** [comment]
> Even I am facing the same with npm

@pareshbbb to help debug, would you mind posting `npm` error logs?

**Comment by ieglonew01f** [comment]
https://status.npmjs.org/incidents/lvgmcrfvrvsh there are some incidents with npm hmm

**Comment by ieglonew01f** [comment]
https://status.npmjs.org/incidents/lvgmcrfvrvsh 
> We are currently investigating issues with installing certain packages.
> 
> Some of the packages known to be affected are: 3d-view, error-ex ,42-cent-base, 8base-cli.

**Comment by tximpa91** [comment]
Yes i am facing the same issue trying to install plotly 1.49.0

**Comment by etpinard** [comment]
Update:

![image](https://user-images.githubusercontent.com/6675409/74359816-f25d0300-4d91-11ea-9c97-656ccbddb708.png)

**Comment by ieglonew01f** [comment]
there is a workaround for this which worked for me, in your package.json
set the following

```            
"resolutions": {
                "3d-view": "git://github.com/mikolalysenko/3d-view.git#017651d48ac7b42e81447adb1a2e06a4972b3293"
            }

**Comment by etpinard** [comment]
Another update:

![image](https://user-images.githubusercontent.com/6675409/74364762-c8f4a500-4d9a-11ea-9149-9eba15fbf163.png)

**Comment by etpinard** [comment]
![image](https://user-images.githubusercontent.com/6675409/74370077-7a4c0880-4da4-11ea-864d-6f384c636679.png)

The issue now appears fixed. I was able to get a fresh `yarn add plotly.js` to work. Closing.
