### ISSUE TITLE
WebGL/scattergl issue in Brave browser

### ISSUE THREAD

**Issue by jackparmer** [plotly/plotly.js#4577]
`Cannot read property length of null`

![image](https://user-images.githubusercontent.com/1865834/74369310-28ef4980-4da3-11ea-92e8-c63ffd7ff836.png)

My figure object looks like this:
```
Figure({
    'data': [{'hoverlabel': {'namelength': 0},
              'hovertemplate': 'index=%{x}<br>0=%{y}',
              'legendgroup': '',
              'line': {'color': '#636efa', 'dash': 'solid'},
              'mode': 'lines',
              'name': '',
              'showlegend': False,
              'type': 'scattergl',
              'x': array([     0,      1,      2, ..., 440997, 440998, 440999]),
              'xaxis': 'x',
              'y': array([   0,    0,    0, ..., -302, -301, -301], dtype=int16),
              'yaxis': 'y'}],
    'layout': {'height': 250,
               'legend': {'tracegroupgap': 0},
               'margin': {'l': 0, 'r': 0, 't': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'index'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'fixedrange': True, 'title': {'text': ''}}}
})
```

And the graph itself looks like this on Safari and Chrome:
![image](https://user-images.githubusercontent.com/1865834/74369395-4f14e980-4da3-11ea-9ad8-8d785bf88727.png)

Since the `scattergl` graph works on Safari and Chrome (but not Brave), I'm assuming this is Brave x WebGL issue. Hopefully this is useful to someone else using Brave.

**Comment by archmoj** [comment]
`Scattergl` appears to be working on Brave on my machine.
Any chance using a non-minified version to help us debug?

**Comment by Batalex** [comment]
I use Brave as my main browser and I often encounter issue with WebGL plots. I usually solve them by turning off the Brave Shields
