### ISSUE TITLE
Attribute to control inside-text-anchor in pie and sunburst

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#4607]
When setting `insidetextorientation` to `horizontal`, `radial` or `tangential`, by default the text is positioned at 3, 6, 9, 12 hours if it fits within the sector. And if not, the text would be positioned in the middle of the arc (i.e .similar to `auto` option).
However, some users (see https://community.plot.ly/t/sunburst-chart-edit-text/35509) prefer to force the text to stay in the middle. 
This could be achieved by adding a new attribute called `insidetextanchor` which defaults to `center` with `auto` `insidetextorientation` and defaults `auto` with other `insidetextorientation` options.

**Comment by domgomez** [comment]
I have my data like this:

`   var data = [
     {
       "type": "sunburst",
       "maxdepth": 2,
       "ids": unpack(rows, 'ids'),
       "labels": unpack(rows, 'labels'),
       "parents": unpack(rows, 'parents'),
       "values":  unpack(rows, 'values'),
       //"leaf": {"opacity": 0.4},
       //"marker": {"line": {"width": 2}},
       "branchvalues": 'total',
       //"textposition": 'inside',
       "insidetextorientation": 'radial',
       "insidetextanchor": 'middle',
       "textfont": {"color": "white"}
     }]`

It's still not on the "middle" or "center" am I missing something?

Thanks,
Dom

**Comment by archmoj** [comment]
@domgomez no you are not missing something.
There is no attribute to control that at the moment. 
And that's the reason why this is a feature request.

**Comment by domgomez** [comment]
Ah I see, thanks for clarifying! :)

**Comment by ameenmi** [comment]
We do have simialr problem. Any fix released?

**Comment by harsh201** [comment]
Hi,
We are also looking for functionality. Is there any update?

**Comment by nicolaskruchten** [comment]
No one is working on this at the moment as far as I know, but we would welcome a pull-request :)

**Comment by harsh201** [comment]
@nicolaskruchten Thanks for quick response. I will try and raise a PR for same.
Can you help me with pointers for #5561?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
