### ISSUE TITLE
I want to lazy load plotly in my application.

### ISSUE THREAD

**Issue by pragyagarg642** [plotly/plotly.js#4609]
My application bundle size is increasing while I am using plotly-with-meta.

On further analysing it, I could see the size of plotly with meta is 6.2MB, which is increasing my vendors bundle size. To reduce the vendors bundle size, I want to load it based on user action. I explored the possibility of dynamic imports using webpack. but it is anyway getting bundled with the vendors bundle. Is there any other method that can be tried? Any help would be appreciated :)

**Comment by AhmedThahir** [comment]
How to achieve this?
