### ISSUE TITLE
locale fi download plot as a png button translate not work

### ISSUE THREAD

**Issue by njake** [plotly/plotly.js#4612]
Locale fi "Download plot as a png" translate not work in button title.
Other languages work example sv.

Example code. Move mouse to download button(camera) to see wrong title.
https://codepen.io/njake/pen/rNVzWeg

**Comment by alexcjohnson** [comment]
Thanks @njake - looks like we just have the wrong translation key:

https://github.com/plotly/plotly.js/blob/80262b5194d625d750260b1dc64cb952cd1fb1cd/lib/locales/fi.js#L29

should be `Download plot as a png` (missing `a`)

https://github.com/plotly/plotly.js/issues/2269 talked about adding a check for missing keys in translations - this issue brings up the need for a check of *wrong* keys, which is something we can fix without knowing the language in question, either by adjusting the key if it's obvious like this case, or by deleting the key and waiting for a native speaker to provide the right thing.

**Comment by archmoj** [comment]
Fixed by #6723.
