### ISSUE TITLE
YIOrRd heatmap restyle defaults back to RdBU

### ISSUE THREAD

**Issue by mmebsout** [plotly/plotly.js#4613]
I am trying to switch the [colorscale](https://plot.ly/javascript/colorscales/) of my heatmap by using the [restyle](https://plot.ly/javascript/plotlyjs-function-reference/#plotlyrestyle) function.
It works pretty well with colorscales like "Greens" or "Jet" but when I use "YIOrRd" or "YIGnBu" it defaults back to "RdBU".

see : https://codepen.io/mmebsout/pen/KKpvvOR

It looks like Issue #3829 might be related to this.
I couldn't fix my problem using `autoscale:true` or `false`. Sorry if I have misunderstood something but I'd be delighted to be corrected. Thanks in advance for your time.

**Comment by alexcjohnson** [comment]
You have an uppercase `I` in `"YIOrRd" or "YIGnBu"` - should be a lowercase L for yellow: `"YlOrRd" or "YlGnBu"`

**Comment by alexcjohnson** [comment]
Ah I see, our docs have the uppercase `I` as well! Will get this fixed...

**Comment by alexcjohnson** [comment]
We at one point had this typo in the colorscales, and there's a "cleaning" step that ensures the wrong spellings get fixed when a new figure is supplied, but that cleaning doesn't happen on `restyle` or `relayout`

**Comment by mmebsout** [comment]
Thank you very much :)

**Comment by alexcjohnson** [comment]
Thanks for reporting @mmebsout - closing, will be addressed by https://github.com/plotly/graphing-library-docs/issues/14
