### ISSUE TITLE
Violin attributes/values missing from plot-schema.json

### ISSUE THREAD

**Issue by hmf** [plotly/plotly.js#4617]
Posted a related question in [here](https://community.plot.ly/t/plolty-example-data-attribute-value-not-found-in-json-schema/35871) but I think it may be an error because I found another issue. Hence this report here. Describing two missing elements. 

Background: I am using the schema to auto-generate Scala code to read and generate the Plotly JSON documents. I have started with the [Violin](https://plot.ly/javascript/violin/) trace examples for preliminary tests. I have found that:

* The attribute:  `points: 'none'` does not exist in the schema. The schema `points` is an `enumerated` that only has the following values:
  *   `“all”`
  *   `“outliers”`
  *   `“suspectedoutliers”`
  *   `false`
* The element `"boxpoints": false` does not appear in the Violin trace. The only place I find this is in the `box` trace.  

So am I correct in assuming that these are missing from the schema? Can I use this schema to generate the intended code?

**Comment by nicolaskruchten** [comment]
You can use the schema to generate code, this is what we do in Plotly.py. It's normal that `boxpoints` isn't available in `violin` and I don't believe that `'none'` is an accepted value for `violin.points`, indeed. 

I suspect the documentation is wrong rather than the schema ;)

**Comment by hmf** [comment]
Ok, I will assume these are schema errors then. Thanks.

**Comment by nicolaskruchten** [comment]
(You mean documentation errors, right? The schema is automatically derived from the internal data structures used by Plotly.js, so it's very unlikely that the schema is wrong :)

**Comment by hmf** [comment]
oops. I confess I am Plotly _illiterate_. Ok then I will open a new issue for a documentation error. Thanks for the explanation.
