### ISSUE TITLE
Possible value error in schema for a `dflt` field in the `indicator` trace

### ISSUE THREAD

**Issue by hmf** [plotly/plotly.js#4625]
I am developing Scala code to automatically generate a Scala API based in the schema (akin to Python). Got nearly all schema coded. However the following element:
```
value<-threshold<-gauge<-attributes<-indicator<-traces<-schema<-*
```
has:

```
valtype: "number"
dflt: false
```

Am I correct in assuming that the `dflt` value should only be numeric? 

TIA

**Comment by archmoj** [comment]
@hmf thanks for writting in.
`dlft` could contain a values outside the `valType`.
https://github.com/plotly/plotly.js/blob/8f049fddbac0ca0382816984b8526857e9714fe6/src/lib/coerce.js#L359-L401

That's pretty exciting to use Scala!
Curious to know if you noticed this page?
https://plot.ly/scala/getting-started/

**Comment by alexcjohnson** [comment]
@archmoj is right that we sometimes have a default of a different type - basically in cases where omitting a value disables that feature. And I imagine it could be useful to have client libraries explicitly allow that default to be set without flagging it as an incorrect type, for example if you've enabled the feature previously and later want to remove it. @nicolaskruchten @jonmmease how is that case handled on the Python side?

**Comment by hmf** [comment]
@archmoj Thanks for the feedback. Yes, I considered using that Scala API first. I also looked into [plotly-scala](http://plotly-scala.org). The latter is not complete. It requires manually generating case classes (conversion based on Argonaut), which requires a lot of effort. It also tests against the examples, which may be misleading. In regards to the [former](https://github.com/facultyai/scala-plotly-client), it uses remote access to to Plotly's server for plot generation. It also seems to be complete (I may be wrong about this).

I have opted for (semi) automatic generation (all traces but this case can be generated), no use of macros for JSON conversion and local plot generation via Java's WebKit (no SVG at this point). I want to take advantage of Scala's static typing and the IDE's code completion capabilities. Hence the question on default types. 

I was planning to allow users to *activate* the default by setting it. This is problematic if we have a numeric type and one has a Boolean value. Scala typing fails. I have yet to encounter this issue elsewhere (layout can also be generated). To make this work I would have to add a hack on per trace case. Not easy seeing as the same code parsers all JSON data (traces, layout).

**Comment by hmf** [comment]
@alexcjohnson I understand the *activate/deactivate a feature*, but won't setting a numeric feature to a Boolean value cause an error? Cannot understand this. My knowledge of JS and Plotly coding/design is very limited. Sorry. Note that for valType "Any", I accept any type. Maybe this is what was intended assuming a Boolean value is acceptable?

As for the Python API, I am also curious - however I am assuming that Python typing is not an issue here.
