### ISSUE TITLE
Bars with NaNs as positions lead to console errors

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#4631]
Go to https://codepen.io/etpinard/pen/YzXeooZ?editors=0010 open the console, you should see:

```
Error: <path> attribute d: Expected number, "MNaN,620V620HNaNV…".
```

As detected in https://github.com/plotly/plotly.js/pull/4614#issuecomment-597253006 (but this happens w/o setting axis breaks!)

----

From @archmoj https://github.com/plotly/plotly.js/pull/4614#issuecomment-597263534 :

Something went wrong in [v1.50.0](https://github.com/plotly/plotly.js/releases/tag/v1.50.0) | [demo-console-error](https://codepen.io/MojtabaSamimi/pen/abOEerE?editors=1000).
Possibly a side effect of `Add transition support to bar trace length, width, on-graph text positioning,
marker style and error bars` [#4180, #4186]

https://github.com/plotly/plotly.js/pull/4614#issuecomment-597266796 - It could be related to 

![Screenshot from 2020-03-10 15-18-07](https://user-images.githubusercontent.com/33888540/76350621-7ac3ba80-62e2-11ea-893e-ac90e9fa8399.png)

in https://github.com/plotly/plotly.js/pull/4180/commits/f49828a05fdf593097083842b31cbc2f8f777c11

**Comment by archmoj** [comment]
This problem also exits with `funnel` and `waterfall` which would be fixed in #4663.
