### ISSUE TITLE
Allow custom sizes for treemap nodes

### ISSUE THREAD

**Issue by justin-sleep** [plotly/plotly.js#4636]
This would be useful for quickly visualizing the relative weight of nodes.

**Comment by archmoj** [comment]
Thanks for writing in.
Could you provide an example?

**Comment by justin-sleep** [comment]
Sure! [Here](https://finviz.com/map.ashx)'s an example; the size of the node depends on the market cap of the stock.

**Comment by archmoj** [comment]
Did you try `values` attribute? https://plot.ly/javascript/reference/#treemap-values
Here is an example with/without values: https://rreusser.github.io/plotly-mock-viewer/#treemap_with-without_values

**Comment by justin-sleep** [comment]
Ah, that's exactly what I wanted. I had tried using `values` earlier, but kept getting `Multiple implied roots, cannot build treemap hierarchy` back. I've tracked that down to being caused by pushing null entries to `values`.

Sorry for the confusion. Thanks!
