### ISSUE TITLE
Shapes not deleted when clearing all shapes

### ISSUE THREAD

**Issue by aaliddell** [plotly/plotly.js#464]
Hi,

I've come across an issue in the recent version whereby calling Plotly.relayout to remove all shapes (i.e shapes: []) does not remove the shape svg elements. Is there a check somewhere that is bailing out when shapes.length == 0, without first checking if there are elements to remove?

In this example, the red shape should be removed by the call to relayout with an empty shapes array: http://codepen.io/anon/pen/pyZPxX

In this example, using a non-empty shapes array in relayout results in the expected behavior (red removed, blue added): http://codepen.io/anon/pen/XdBRym

This worked in prior versions, so has there been a change in the advised method of removing all shapes? The current workaround I'm having to use is to add a tiny invisible shape when I want to remove all other shapes, which is a bit of a bodge.

Edit: As as addition: shapes that are present when calling Plotly.relayout with shapes: [] appear to be orphaned and never cleaned up in subsequent calls to relayout, even when the shapes array is non-empty. Meaning the chart ends up covered in old shapes.

**Comment by n-riesco** [comment]
I can reproduce it in v1.9.0, but it isn't present in v1.8.0. I'm now bisecting the commits.

**Comment by n-riesco** [comment]
And the guilty commit is ... f67ff4d1dcbd4a0a9e5d460ed10020861a8abcae 

That's my bad. I will revert the commit, add a comment in the code, and test to prevent this from happening again.

**Comment by aaliddell** [comment]
Excellent! 

Do you have any vague estimate of when this would be in a release? Basically, is it worth applying your patch myself to a local copy, or will it be pushed in the next few days anyway?

**Comment by etpinard** [comment]
> Do you have any vague estimate of when this would be in a release

should be early next week.
