### ISSUE TITLE
texttemplate for histogram traces

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4645]
And the associated `textposition` etc.

**Comment by singharx** [comment]
is this done for python version as well ? @nicolaskruchten

**Comment by nicolaskruchten** [comment]
Plotly.py uses Plotly.js to do rendering, so the flow is that this has to be implemented here in Javascript first, then released, and then the next version of Plotly.py to come out will have access to this functionality.

**Comment by singharx** [comment]
Thanks Nicolas 💯

**Comment by archmoj** [comment]
> @archmoj can I get an estimate on this please? In principle it's a lot of code reuse from other bar-like traces so I'm hoping it's not too long

A week or so.

**Comment by nicolaskruchten** [comment]
See also https://github.com/plotly/plotly.js/issues/1116
