### ISSUE TITLE
text weight

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4646]
It would be great to be able to specify that various titles and labels should be bold, without needing to use inline HTML.

**Comment by alexcjohnson** [comment]
Ideally it would be great to allow ALL font attributes to take several extra pieces, not just `family`, `size`, and `color`. Easiest would be to just pass more CSS attributes through:
- `weight` -> [`font-weight`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight) for bold etc
- `style` -> [`font-style`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-style) for italic

and maybe if we want to be (more) complete:
- `variant` -> [`font-variant`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant) for small caps and ligature control
- `stretch` -> [`font-stretch`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-stretch)

There's more... but we're already awfully deep in the weeds if we add these 4!
