### ISSUE TITLE
stacked histograms have different start/end values on hover 

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4648]
https://codepen.io/nicolaskruchten/pen/BaNxYzM

This is weird:

![image](https://user-images.githubusercontent.com/203523/76764985-1c785b00-676c-11ea-8601-542a62927cb2.png)

**Comment by alexcjohnson** [comment]
FWIW this happens with regular split hover as well - 
<img width="747" alt="Screen Shot 2020-03-16 at 9 56 51 AM" src="https://user-images.githubusercontent.com/2678795/76765335-9ad4fd00-676c-11ea-9103-19ba45567505.png">

**Comment by alexcjohnson** [comment]
we are just doing the calculation of number of digits to show in these labels independently for each trace even when they're stacked or grouped so the coordinates should match.
<img width="376" alt="Screen Shot 2020-03-16 at 10 04 17 AM" src="https://user-images.githubusercontent.com/2678795/76765885-847b7100-676d-11ea-8576-8dcad67d19ce.png">

**Comment by archmoj** [comment]
@alexcjohnson is this a bug?

**Comment by alexcjohnson** [comment]
Yes, bug. I forget how that calculation works but whatever it does should be shared by all traces in a group or stack.

**Comment by antoinerg** [comment]
The test added in https://github.com/plotly/plotly.js/commit/ee1a6ba4f8797332301eec4d6c64c130324c55b5 showcases the problem at hand.

The problem comes from the fact that each trace has its own rounding function `roundFn` which is determined by their trace specific `leftGap` and `rightGap`:
https://github.com/plotly/plotly.js/blob/9a75ef0bf6e3c49a96c321c86e3ac4abff9b1697/src/traces/histogram/calc.js#L112-L131

**Comment by antoinerg** [comment]
One possible solution is to defer the evaluation of `ph0` and `ph1` to after we're done with the `calc` phase of all traces. This is what is implemented in [branch `fix-4648`](https://github.com/plotly/plotly.js/compare/fix-4648). It's rather hacky but it seems to solve the issue at hand. 

cc @alexcjohnson @archmoj can you have a look at it?

**Comment by alexcjohnson** [comment]
Ideally things like this belong in `crossTraceCalc`, though that could also be hacky since `histogram` shares that with `bar`. Your solution looks good, it's just better to minimize the work in `hover` when possible.

**Comment by antoinerg** [comment]
> Ideally things like this belong in crossTraceCalc, though that could also be hacky since histogram shares that with bar.

I forgot that `crossTraceCalc` is executed after the `calc` steps of each trace. I could definitely do the work of computing `ph0` and `ph1` over there. The only downside is that we will have to loop over all the bars again.

> Your solution looks good, it's just better to minimize the work in `hover` when possible.

I understand that we may not want to add latency to something interactive. Computing everything in advance is probably a better approach considering we don't usually have a lot of bars.

Thanks for the review @alexcjohnson

**Comment by antoinerg** [comment]
Another solution using `crossTraceCalc` can be found in [branch `fix-4648-cross`](https://github.com/plotly/plotly.js/compare/fix-4648-cross). Please let me know what you think and how to improve on it!

cc @alexcjohnson @archmoj

**Comment by archmoj** [comment]
The https://codepen.io/nicolaskruchten/pen/BaNxYzM is fixed in your [branch `fix-4648`](https://github.com/plotly/plotly.js/compare/fix-4648). But it is not fixed by [branch `fix-4648-cross`](https://github.com/plotly/plotly.js/compare/fix-4648-cross) .

**Comment by antoinerg** [comment]
> The https://codepen.io/nicolaskruchten/pen/BaNxYzM is fixed in your [branch `fix-4648`](https://github.com/plotly/plotly.js/compare/fix-4648). But it is not fixed by [branch `fix-4648-cross`](https://github.com/plotly/plotly.js/compare/fix-4648-cross) .

Actually using the bundle from `fix-4648-cross`, we only get one item when using the hover compare mode. I'm a bit puzzled as to why. Investigating now. Let me know if you have any hint!

**Comment by alexcjohnson** [comment]
@antoinerg the approach in `fix-4648-cross` looks great, though somehow it's getting a mismatch of bin positions - looks like maybe `fullTrace._binEdges` is for all traces but each trace may start at a different bin? Only Africa, which has the left-most bin, looks correct. Not sure why that would cause problems for getting all the other items but perhaps fixing that will resolve both?
Here the box says 40-something but the box is at 50-something... and if you switch to `closest` mode you can look at all the traces.
<img width="159" alt="Screen Shot 2020-03-17 at 9 42 29 PM" src="https://user-images.githubusercontent.com/2678795/76916917-5d6d8e00-6898-11ea-98da-0323d8b93362.png">

**Comment by antoinerg** [comment]
> looks like maybe `fullTrace._binEdges` is for all traces but each trace may start at a different bin?

You were exactly right @alexcjohnson! Fixed in https://github.com/plotly/plotly.js/commit/374941be778ad4442eac26f3fa69fea267bb83cb

**Comment by alexcjohnson** [comment]
That'll work! I believe the index is simply offset between traces, so it might be more efficient just to store  it once, something like `cd[0].t.i0` but that's not a big deal.

**Comment by antoinerg** [comment]
> That'll work! I believe the index is simply offset between traces, so it might be more efficient just to store it once, something like `cd[0].t.i0` but that's not a big deal.

Sounds good. In the end, I think I will use my first approach of preparing functions in `histogram/calc.js` and defer their evaluation until later. However, instead of doing the evaluation in `hover`, I would do it in the `crossTraceCalc` step. I think it results in cleaner code.

**Comment by antoinerg** [comment]
When deferring the evaluation of `ph0` and `ph1`, I encounter an edge case: both `leftGap` and `rightGap` can be zero and the rounding function then returns `NaN`. 

@alexcjohnson I think you wrote `getBinSpanLabelRound`. Is it easy to account for this edge case?
