### ISSUE TITLE
Updatemenus: traces of the same type are similarly updated, despite settings

### ISSUE THREAD

**Issue by empet** [plotly/plotly.js#4651]
Defined    subplots with two heatmaps and a bar chart. In an attempt to  use a dropdown menu
to update only the second heatmap, by  setting  `traces =[1]` in button's `args` definition,  it  can be noticed that the first heatmap is also updated, with the same data like the second one, i.e. after each update both heatmaps exhibit identical patterns.

Examples to reproduce this bug: [https://chart-studio.plot.ly/~empet/15569](https://chart-studio.plot.ly/~empet/15569)

**Comment by emmanuelle** [comment]
Thank you @empet, https://github.com/plotly/plotly.py/issues/2328 might be related to this issue.

**Comment by emmanuelle** [comment]
https://codepen.io/emmanuelle-plotly/pen/VwLqyQB?editors=1010 reproduces the issue

**Comment by emmanuelle** [comment]
As mentioned in the Python issue, if you remove the layout part from the update then everything works well.

**Comment by emmanuelle** [comment]
Curiously, the corresponding Javascript example of the doc works well
https://plotly.com/javascript/custom-buttons/#update-button
but the Python one does not
https://plotly.com/python/custom-buttons/#update-button

**Comment by emmanuelle** [comment]
@empet could you please tell us which navigator you are using? I hope I didn't hijack too much your issue and that the problems are indeed related, but I can only observe the problem in Firefox, in Chrome it's ok. The error in the console is NS_ERROR_FAILURE, which seems (from a rapid google search) to be associated mostly with Firefox.

**Comment by empet** [comment]
@emmanuelle   I'm sorry, I didn't  notice your question. Meantime I realized that I had to invoque the `restyle` method, not  the `update` ,  because only data are updated, not some layout attributes.

With this updatemenu buttons  definition: 
```
buttons = [dict(method='restyle',
                args=[{"z": [ z1]}, [1]],
                label="z1"),
          dict(method='restyle',
               args=[{"z": [ np.array(np.logical_not(z1), int)]}, [1]],
               label="Not z1")]
```
it works:

**Comment by gilbertovilarunc** [comment]
Still, it should work with update method, if we want to do both data and layout updates in a button. It is not working properly.
