### ISSUE TITLE
compare/unified hover should include all points at same coordinate

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4656]
In x-unified and x-compare modes, it should never be possible for there to be two data with the same x-coordinate and only one of them is displayed in a hoverlabel. I know compare mode doesn't currently behave this way but I consider it a bug.

The solution proposed by @alexcjohnson seems good to me:

* Step 1: find hover points the way we do now
* Step 2: loop back over traces not in the set of hover points we already found, and see if any of them have a point with position-axis value exactly matching what we found for the other point(s)

**Comment by antoinerg** [comment]
Demonstration of the issue:
![unified](https://user-images.githubusercontent.com/301546/76888803-f087d300-685a-11ea-978e-21f80429e3b4.gif)

**Comment by antoinerg** [comment]
The approach suggested to @alexcjohnson seem to work fine for the simple case demonstrated above: https://codepen.io/antoinerg/pen/gOpKwPg

Now, I wonder if there are cases for which this may lead to undesirable behavior. WIP on [branch `fix-4656`](https://github.com/plotly/plotly.js/compare/fix-4656).

**Comment by antoinerg** [comment]
> Now, I wonder if there are cases for which this may lead to undesirable behavior. WIP on [branch `fix-4656`](https://github.com/plotly/plotly.js/compare/fix-4656).

For one, categorical axis are not working ATM. Working on a fix.

**Comment by antoinerg** [comment]
My [branch `fix-4656`](https://github.com/plotly/plotly.js/compare/fix-4656) now has fixes for date and categorical axes: https://codepen.io/antoinerg/pen/gOpKwPg

cc @nicolaskruchten

**Comment by nicolaskruchten** [comment]
Looks good! Here's an oddity that I don't think we can easily fix, with two points above a bar, one at a slightly different x-coordinate:

![unified](https://user-images.githubusercontent.com/203523/77020559-92421980-695a-11ea-9e0c-4437bcf09359.gif)

**Comment by antoinerg** [comment]
> Looks good! Here's an oddity that I don't think we can easily fix, with two points above a bar, one at a slightly different x-coordinate:
> 
> ![unified](https://user-images.githubusercontent.com/203523/77020559-92421980-695a-11ea-9e0c-4437bcf09359.gif)

I'm curious, what behavior would you rather have in that case?

**Comment by alexcjohnson** [comment]
> two points above a bar, one at a slightly different x-coordinate

There's a reason the title of this issue says "should include all points at same coordinate" 😏

**Comment by nicolaskruchten** [comment]
Indeed :) I was just noticing while testing that as I sweep in an increasing-x direction, I get the hover at 1, then 1.1, then 1 again even though my mouse is now at 1.2 or so. C'est la vie: the bar picks it up and then adds the point from 1. It's more correct than anything else I can think of right now :)

**Comment by antoinerg** [comment]
Some tests are failing with the changes made in [branch `fix-4656`](https://github.com/plotly/plotly.js/compare/fix-4656): multiple boxes/violins sharing a category with offsets. See second figure in https://codepen.io/antoinerg/pen/gOpKwPg . It used to hover on 1 box, now it hovers 2 boxes. I imagine we'd rather hover on all of them right?

@alexcjohnson when you have a chance, can you take a look at [branch `fix-4656`](https://github.com/plotly/plotly.js/compare/fix-4656) and let me know what you think of this approach (and potential pitfalls).

**Comment by nicolaskruchten** [comment]
For boxes and violins, the 1.52 behaviour for compare was good IMO.
