### ISSUE TITLE
spike/hover congruence

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4657]
It should be possible to configure things (and in unified hover mode this should be the default coerced configuration) such that whenever a hoverlabel appears, a spikeline appears and vice-versa: you should not see a spikeline without a hoverlabel.

This should hold true for mixes of bars and scatters, and work with #4656

**Comment by antoinerg** [comment]
@nicolaskruchten I am aware that this behavior can happen at the moment and can reproduce. Do you by any chance have an example where this is particularly egregious?

**Comment by antoinerg** [comment]
Never mind: mock `24` is a good example of the problem at hand.

**Comment by antoinerg** [comment]
@nicolaskruchten here's a simple (perhaps the simplest) solution that prevents drawing spike lines if no points are hovered on: https://github.com/plotly/plotly.js/commit/7c036abaf097fdcbb50e15832b28346c3855727c .

cc @alexcjohnson

**Comment by nicolaskruchten** [comment]
Hehe yes indeed. Could we make that an attribute that is coerced to true in unified hovermode? that way it can be turned off in unified mode and also optionally turned on it compare mode?

**Comment by antoinerg** [comment]
> Hehe yes indeed. Could we make that an attribute that is coerced to true in unified hovermode? that way it can be turned off in unified mode and also optionally turned on it compare mode?

Sure! Let's decide on a name for that attribute at the meeting tomorrow :)

**Comment by nicolaskruchten** [comment]
Conclusion: `hovered data` as a possible value for the existing `spikesnap` attribute :)
