### ISSUE TITLE
circleci: publish dashboard

### ISSUE THREAD

**Issue by antoinerg** [plotly/plotly.js#4659]
I think it may be worthwhile to publish/host the dashboard (which is only made of static files) on CircleCI to make it easy to try out the build associated with a particular commit AND be able to browse all the mocks. This way, we wouldn't have to create Codepens each time we want to showcase a particular plotly.js bundle and mock.

**Comment by archmoj** [comment]
Fantastic idea!

**Comment by antoinerg** [comment]
Glad you like the idea @archmoj! I'm wasting too much time preparing Codepen.

**Comment by archmoj** [comment]
I am sure you know how to make this happen.
If so, let's ask to be added to a milestone @nicolaskruchten.

**Comment by archmoj** [comment]
Should you install devDeps on the CI and run into problems with `ecstatic` missing versions, then we may recover #4553 and merge it.
