### ISSUE TITLE
New rangebreaks and unified hover should work from templates

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4667]
I should be able to set `rangebreaks` and `hovermode="x unified"` inside `layout.template.layout` instead of `layout` and have things work identically.

As an aside: this is an invariant which should be the case for all attributes! I just QA'ed these two by chance but we should probably look into previous recently-added attributes to ensure that they work.

**Comment by nicolaskruchten** [comment]
Possibly see https://github.com/plotly/plotly.js/pull/4620/files#diff-1602f9e66d27cf60c7469f31f03b8053

**Comment by archmoj** [comment]
Closed via #4669 and #4670.
