### ISSUE TITLE
Incorrect text position with ScatterGL plots

### ISSUE THREAD

**Issue by Dive576** [plotly/plotly.js#4682]
NOTE: I am using Plotly.js v1.52.3.

In a ScatterGL plot, text will move away from its associated point if the user pans the plot while the axes range is small. For an axis with date data, this starts becoming noticeable when the range is small enough for hours to be shown on the ticks and is very noticeable when seconds start being displayed. A simple example of this:

```
data = {mode: "markers+text",
        text: ["a", "b", "c"],
        textposition: "right",
        type: "scattergl",
        x: ["2020-03-25 08:00:00", "2020-03-25 08:01:00", "2020-03-25 08:02:00"],
        y: [1, 2, 3]};
Plotly.newPlot("myDiv", [data], {width: 600, height: 400, xaxis: {range: ["2020-03-25 07:55:00", "2020-03-25 08:05:00"]}});
```

This produces the output:

![time_axis](https://user-images.githubusercontent.com/62649460/77544647-a8326b80-6e7f-11ea-8640-b63e1b349e91.png)

Another example showing this for an axis with numeric data:

```
data = {mode: "markers+text",
        text: ["a", "b", "c"],
        textposition: "right",
        type: "scattergl",
        x: [1.9999999, 2, 2.0000001],
        y: [1.95, 2, 2.05]};
Plotly.newPlot("myDiv", [data], {width: 600, height: 400, xaxis: {range: [1.9999998, 2.0000002]}});
```

This produces the output:

![linear_axis](https://user-images.githubusercontent.com/62649460/77544683-b41e2d80-6e7f-11ea-83d5-6e5b0b9fb11d.png)

**Comment by archmoj** [comment]
Thanks for the report @Dive576.
Unlike other `regl-*` modules used in `scattergl` trace, the [gl-text](https://github.com/a-vis/gl-text) module appears not to use @dy's [to-float32](https://www.npmjs.com/package/to-float32) module.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
