### ISSUE TITLE
rangebreaks hovermode=closest offset

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4693]
Try hovering over points here: https://codepen.io/nicolaskruchten/pen/oNXQmLR?editors=1010

**Comment by archmoj** [comment]
@nicolaskruchten thanks for the codepen.
As a side note:
It is working OK with reversed y-axis | [demo](https://codepen.io/MojtabaSamimi/pen/JjdeVGr?editors=1010).

**Comment by alexcjohnson** [comment]
> It is working OK with reversed y-axis

Does that mean it's also _broken_ for a reversed _x_ axis?

**Comment by archmoj** [comment]
> > It is working OK with reversed y-axis
> 
> Does that mean it's also _broken_ for a reversed _x_ axis?

Positive.

**Comment by nicolaskruchten** [comment]
Let's leave this aside for the 1.53 release...
