### ISSUE TITLE
autorange should not display zero line for certain bars with positive base and negative value

### ISSUE THREAD

**Issue by emmanuelle** [plotly/plotly.js#4701]
See for example https://codepen.io/emmanuelle-plotly/pen/bGdOLmR?editable=true, the axis starts at 0 and therefore a large part of the domain is not used to represent data. For other sets of data the automatic range works well. 

Triggered by https://github.com/plotly/plotly.py/issues/2327

**Comment by archmoj** [comment]
Something possibly went wrong in autorange when using `base` and the sum (without `base`) goes below the initial value.

**Comment by archmoj** [comment]
[Minimal demo](https://codepen.io/MojtabaSamimi/pen/zYGeKWZ?editors=0010).

**Comment by archmoj** [comment]
It works well if we force `tozero` to be `false` e.g. here:
https://github.com/plotly/plotly.js/blob/ebab12b4ebf6ebdfed54d1f7b53cbb094b813aa5/src/plots/cartesian/autorange.js#L335

**Comment by archmoj** [comment]
Not sure if we should have tag this as a bug.
[Demo using bar](https://codepen.io/MojtabaSamimi/pen/xxGMEJX?editors=0010).

**Comment by alexcjohnson** [comment]
Definitely a bug - and we have logic that appears intended to address exactly this, but somehow isn't working.

https://github.com/plotly/plotly.js/blob/b8a452c1bd63aac05afbca1bf74baba6b4ac4066/src/traces/bar/cross_trace_calc.js#L521

**Comment by archmoj** [comment]
[minimal demo](https://codepen.io/MojtabaSamimi/pen/bGdzMRz?editors=0010) in regards with the new title.

**Comment by alexcjohnson** [comment]
Ah, nice sleuthing @archmoj! In fact, to dive into the details of `tozero` a bit: if an axis is autoranged `tozero` it means two things: (1) zero is always included in the autorange, and (2) if the lowest (or highest) point on the axis is *exactly* zero, no padding is added past zero. This is an interesting effect: it says that for a normal bar chart or filled area chart, the size axis starts exactly at zero, but we get the normal 5% padding at the other end.

I wonder if the correct `tozero` logic  is as simple as "true if *any* bar has zero base"? I don't think it matters whether the base is positive or negative, or anything about the bar size.

**Comment by archmoj** [comment]
@alexcjohnson I think we still want to display the zero line when the values are negative.
So [this codepen](https://codepen.io/MojtabaSamimi/pen/Jjdxamr?editors=0010) is OK.

**Comment by archmoj** [comment]
> See for example https://codepen.io/emmanuelle-plotly/pen/bGdOLmR?editable=true, the axis starts at 0 and therefore a large part of the domain is not used to represent data. For other sets of data the automatic range works well.

@emmanuelle thanks very much for the report. In your codepen, would you mind set plotly.js version to 1.52.3 and <b>not</b> use the latest?

**Comment by alexcjohnson** [comment]
> I think we still want to display the zero line when the values are negative.
> So this codepen is OK.

Why? What makes that case different from its positive twin?

**Comment by archmoj** [comment]
I don't have strong opinion on that. Perhaps as a result of this bug, I always thought we wanted to display zerolines for bars with negative values.

**Comment by alexcjohnson** [comment]
For historical context, I think before we had a `base` attribute we didn't even put the bottoms of the bars into the autorange calculations - and I think we still do that when there's no base at all, for performance purpose. So in that case the "extend to include zero" part of `tozero` is required or you wouldn't see the full bars at all.

But yeah, when there are no bars with a `base` at zero, there's nothing special about the value zero anymore and `tozero` is inappropriate.

**Comment by nicolaskruchten** [comment]
> Why? What makes that case different from its positive twin?

My feeling is that we should behave symmetrically, and not arbitrarily try to include the zero line for either positive or negative bars. This has caused issues in the past actually, so I would consider the current behaviour a bug, unless it exists to support some specific use-case.
