### ISSUE TITLE
Test mock with no trace "type"

### ISSUE THREAD

**Issue by hmf** [plotly/plotly.js#4703]
I am trying to test a Scala wrapper on the Plotly.JS tests. I have found that some mocks do not have the trace `type`. One example is [overlaying-axis-lines.json](https://github.com/plotly/plotly.js/blob/master/test/image/mocks/overlaying-axis-lines.json).

Is this intended? Does this imply a default trace type (these mocks do have a base plot)? I tried to find this in the documentation but did not succeed. 

TIA

**Comment by archmoj** [comment]
If an attribute has a `dflt` property, then the value of `dflt` would be used when that is not defined in inputs or valid.
In the case of trace.`type` there is a `dflt` and the default is `scatter`.
https://github.com/plotly/plotly.js/blob/0e01a5ad0dc4ace99d02a9fbd21d72428be87537/src/plots/attributes.js#L14-L21

**Comment by hmf** [comment]
I see. Just to confirm: this information is not available in the schema, correct? I did a search on the raw text and found nothing. If so, I will have to figure out a way to _hard-code_ this and close this issue.

TIA

**Comment by alexcjohnson** [comment]
Oh interesting - yes, the way we construct the schema (separately for each trace type), this particular attribute's default value gets lost. But as @archmoj says, its default is in fact `'scatter'`.

**Comment by hmf** [comment]
OK. I will hard code this then. Thanks.
