### ISSUE TITLE
Test mock with unexpected "barnorm" value 

### ISSUE THREAD

**Issue by hmf** [plotly/plotly.js#4704]
The mock [bar_attrs_overlay.json](https://github.com/plotly/plotly.js/blob/master/test/image/mocks/bar_attrs_overlay.json) has the following layout:
```json
    "layout":{
        "xaxis": {"showgrid":true},
        "height":400,
        "width":400,
        "barmode":"overlay",
        "barnorm":false
    }
```

Testing based on the schema resulted in a parsing error of  `"barnorm"`. The schema has: 

```json
"barnorm": {
                    "valType": "enumerated",
                    "values": [
                        "",
                        "fraction",
                        "percent"
                    ],
                    "dflt": "",
                    "role": "info",
                    "editType": "calc",
                    "description": "Sets the normalization for bar traces on the graph. With *fraction*, the value of each bar is divided by the sum of all values at that location coordinate. *percent* is the same but multiplied by 100 to show percentages."
                },
```
Is that an error or can we have false values?

TIA

**Comment by archmoj** [comment]
Some attributes could be set to `false`.
But in this case `false` is not among those valid options for `barnorm`.
So the `dflt` value would be used which is blank string ( "" ).

**Comment by hmf** [comment]
So I can consider this value _incorrect_? The reason I ask is explained in this
https://github.com/plotly/plotly.js/issues/4705#issuecomment-605613185.

Apologies for insisting so much but auto-generating code from the schema is not trivial for me.

**Comment by alexcjohnson** [comment]
That's an error, good catch! In fact, `layout.barnorm` isn't even used in that mock, because it has `barmode: 'overlay'`

https://github.com/plotly/plotly.js/blob/0e01a5ad0dc4ace99d02a9fbd21d72428be87537/src/traces/bar/layout_defaults.js#L54

So we should just remove that line from the mock.

**Comment by hmf** [comment]
Ok. I will set it to "" in my tests and update the mock to latest changes when available. Thanks.
