### ISSUE TITLE
Test mock bar_attrs_relative.json with unexpected "barnorm" value

### ISSUE THREAD

**Issue by hmf** [plotly/plotly.js#4710]
This may be the same issue described in this https://github.com/plotly/plotly.js/issues/4704
Mock is [bar_attrs_relative.json](https://github.com/plotly/plotly.js/blob/master/test/image/mocks/bar_attrs_relative.json)
For reference here is the snippet:

```json
    "layout":{
        "xaxis": {"showgrid":true},
        "yaxis": {"range":[-6,6]},
        "height":400,
        "width":400,
        "barmode":"relative",
        "barnorm":false
    }
```

**Comment by alexcjohnson** [comment]
Solved already by @archmoj in #4708 - thanks for bringing this up in #4704 🎉

**Comment by hmf** [comment]
@alexcjohnson Small note: The change you referre to is for the file test/image/mocks/bar_attrs_group.json. This is another [bar_attrs_relative.json](https://github.com/plotly/plotly.js/blob/master/test/image/mocks/bar_attrs_relative.json). Don't know if you realized that or if the change was made to all files.

**Comment by alexcjohnson** [comment]
`bar_attrs_relative.json` is included in that PR https://github.com/plotly/plotly.js/pull/4708/files#diff-d04eaf77addda33da276b8baa5db23b8 - the link you posted now says:
https://github.com/plotly/plotly.js/blob/b8a452c1bd63aac05afbca1bf74baba6b4ac4066/test/image/mocks/bar_attrs_relative.json#L39
