### ISSUE TITLE
Invalid rangebreaks should be ignored instead of resulting in a bad render

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4715]
i.e. `rangebreaks: [{bounds: ["not a", "valid bound"]}]`

**Comment by archmoj** [comment]
Unable to replicate! See [demo](https://codepen.io/MojtabaSamimi/pen/OJVdaoO?editors=0010).
cc: @emmanuelle

**Comment by archmoj** [comment]
Do you switch to `scattergl` by default in python with those many points?

**Comment by emmanuelle** [comment]
the error in the console is 
`TypeError: x is undefined`

**Comment by emmanuelle** [comment]
let me share a codepen

**Comment by emmanuelle** [comment]
oh wow it works in the codepen but not in my notebook. Past my bedtime here but let me share here the codepen https://codepen.io/emmanuelle-plotly/pen/PoqVxvE?editors=1010 and the Python code
```
import plotly.express as px

import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/finance-charts-apple.csv')

fig = px.line(df[100:120], x='Date', y='AAPL.High')
fig.update_layout(xaxis_rangebreaks = [dict(bounds=["foo", "bar"])])

fig.show()
```
if Nic wants to take a look.

**Comment by emmanuelle** [comment]
Maybe something wrong with the Python codegen / validators then??

**Comment by nicolaskruchten** [comment]
Unable to replicate in Python using a 5-minute-fresh build, either. I think I gave Emma a bad or outdated build yesterday, sorry.

**Comment by emmanuelle** [comment]
must have been an old build indeed, closing.
