### ISSUE TITLE
Spike position in unified hover mode

### ISSUE THREAD

**Issue by emmanuelle** [plotly/plotly.js#4716]
https://codepen.io/emmanuelle-plotly/pen/eYNxQba?editable=true (hover on the scatter point at x=0, the spike line stays at the middle of the bar)
![image](https://user-images.githubusercontent.com/263366/77963099-1098a700-72dd-11ea-976f-20a53f392365.png)

**Comment by archmoj** [comment]
Is this really a bug?

**Comment by alexcjohnson** [comment]
If there's a hover label, the spikeline should get its position from something within that label. In this case the bar is setting the spikeline position, but only the scatter point is in the hover label.

**Comment by nicolaskruchten** [comment]
Definitely a bug, because it doesn't happen if the cursor or point is above the bar rather than within it.

**Comment by nicolaskruchten** [comment]
Compare hovering over the scatter points within the two bars' ranges here: https://codepen.io/nicolaskruchten/pen/abZrYJO?editors=0010

**Comment by nicolaskruchten** [comment]
Note that the behaviour in `hovermode: "x"` with `xaxis.showspikes: true` is also pretty bad: https://codepen.io/nicolaskruchten/pen/yLVQXYy?editors=0010

**Comment by nicolaskruchten** [comment]
Can I see a pen with just this PR please so I can approve this one's behaviour separately from the other one? (it was nice to see them together as well, but now I'd like to see just this one broken out please :)

**Comment by archmoj** [comment]
> Can I see a pen with just this PR please so I can approve this one's behaviour separately from the other one? (it was nice to see them together as well, but now I'd like to see just this one broken out please :)

Here is a [before vs after codepen](https://codepen.io/MojtabaSamimi/pen/mdOooGB?editors=1000).

**Comment by nicolaskruchten** [comment]
✨ for the behaviour! just need a dancer from @alexcjohnson and then we can tackle #5292 on its own

**Comment by archmoj** [comment]
#5542 is merged.
@nicolaskruchten you may close this.
