### ISSUE TITLE
Data order is not applied by React when using matching axes

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#4718]
Originally reported in https://github.com/plotly/dash/issues/1163.
[MINIMAL DEMO](https://codepen.io/MojtabaSamimi/pen/GRJeVwd?editors=0010)

**Comment by archmoj** [comment]
Not clear how we could bypass `_categories` here?
https://github.com/plotly/plotly.js/blob/d37895bd64227433229f2b3f91c9e14fd6ec7b89/src/lib/relink_private.js#L30

**Comment by archmoj** [comment]
It may be best to use re-direct to `newPlot` from `react` when there are `category` axes `matches` one another.

**Comment by alexcjohnson** [comment]
We can't do `newPlot` - both for performance reasons and for `uirevision`

Normally it looks like we clear `_categories` in `ax.clearCalc`, and there's even logic in there that looks like it's supposed to apply to linked axes... why isn't that working?
