### ISSUE TITLE
Minified version of plotly.js-dist

### ISSUE THREAD

**Issue by aaomidi** [plotly/plotly.js#4726]
It would be a great if we could have a minified version of this library. Doing some quick tests it would reduce the file size by over 2 MB.

https://www.npmjs.com/package/plotly.js-dist

**Comment by antoinerg** [comment]
Hello @aaomidi and thank you for your interest in plotly.js! I think this is what you are looking for:

**Comment by aaomidi** [comment]
Thanks that solves my problems haha!
