### ISSUE TITLE
asia_110m.json and asia_50m.json has some deformations

### ISSUE THREAD

**Issue by reza1615** [plotly/plotly.js#4730]
In the https://github.com/plotly/plotly.js/tree/master/dist/topojson 
* asia_110m.json 
* asia_50m.json 
* world_50m.json
* world_110m.json
has deformations. Open them in GitHub or http://geojson.io/  you will see.

**Comment by archmoj** [comment]
@reza1615 thanks for the report.
Could you please open an issue with screenshots on https://github.com/etpinard/sane-topojson repo?

**Comment by archmoj** [comment]
Closing in respect to https://github.com/etpinard/sane-topojson/issues/19.
