### ISSUE TITLE
How to import data from local csv file

### ISSUE THREAD

**Issue by rikuliku** [plotly/plotly.js#4732]
when use plotly.js to import data from a local csv file, it shows error for reading data. is there any way to solve that?

**Comment by alexcjohnson** [comment]
Hi @rikuliku! This kind of question is out of scope for the plotly.js repo - this library doesn't directly interact with data files at all. But it would be a great question to ask on our community forum https://community.plotly.com/c/api/plotly-js/ - particularly if you can show the code you're executing along with the exact error message you see.
