### ISSUE TITLE
Candlestick body width bug with range breaks

### ISSUE THREAD

**Issue by matdecac** [plotly/plotly.js#4742]
Hello everyone,

I am using plotly with python and found a bug with the new (very useful) rangebreaks feature.

When using candlestick graphs it generates some kind of *yaxis size reduction* on the body of every candles, resulting in what look likes **vertical lines** for **each candles**.

I created a codepen with and without rangebreaks as the only difference.

Thanks a lot for this great library,

[codepen link](https://codepen.io/matdecac/pen/JjYPwRv)

Mathias

**Comment by archmoj** [comment]
Hi @matdecac,
Thanks for using potly.
I am afraid you applied an old bundle in your codepen!
Here is what your [demo](https://codepen.io/MojtabaSamimi/pen/WNQeLWj) looks like using `v1.53.0`.

**Comment by matdecac** [comment]
Thanks @archmoj, I am using plotly.py, and by reading the release page it is not yet released with `v1.53.0`. So I will wait :).

Thanks for the support, I am closing the issue.

Mathias

**Comment by archmoj** [comment]
@matdecac 
I think latest plotly.py uses `v1.53.0`; but let me confirm.

**Comment by matdecac** [comment]
@archmoj, According to the [PR](https://github.com/plotly/plotly.py/pull/2340) : it was merged 8 days ago.
Release [4.6.0](https://github.com/plotly/plotly.py/releases/tag/v4.6.0) of plotly.py was released 7 days ago

**Comment by archmoj** [comment]
@matdecac Are you still experiencing this issue using upgraded `plotly.py`?

**Comment by matdecac** [comment]
@archmoj Yes I was already using 4.6.0.

**Comment by matdecac** [comment]
@archmoj,

- I reviewed in detail your codepen, it seems like the range breaks is not applied : there is data after 17:30 which is the limit of the range breaks
- I built the same exemple in Python :
```
 
fig = go.Figure(
    data=[{
      "x": [
        "2020-01-02 17:00", "2020-01-02 17:10",
        "2020-01-02 17:20", "2020-01-02 17:30",
        "2020-01-02 17:40", "2020-01-02 17:50",
        "2020-01-02 18:00", "2020-01-02 18:10"
      ],
      "open": [
        10, 10,
        10, 10,
        10, 10,
        10, 10
      ],
      'high': [
        12, 12,
        12, 12,
        12, 12,
        12, 14
      ],
      'low': [
        8, 8,
        8, 8,
        8, 8,
        3, 8
      ],
      'close': [
        12, 7,
        11, 10.5,
        9, 8.5,
        3, 14
      ],
      'type': 'candlestick',
    }],
    layout={
        'title': 'Bug example',
        'template': "plotly_dark", 
        'xaxis_rangeslider_visible': False,
        'showlegend': False, 
        'hovermode': 'x',
        'xaxis': {
            'rangebreaks': [
                dict(bounds=["sat", "mon"]), #hide weekends
                dict(pattern='hour', bounds=[17.5, 9]),
            ]
        },
    },
)
fig.show()
```

**Comment by archmoj** [comment]
OK. There are more API changes that should be applied in that pen e.g. `breaks` to `rangebreaks` and `%H` to `hour`.
So I think this [new demo](https://codepen.io/MojtabaSamimi/pen/oNjvOBa?editors=0010) now illustrates the bug you are referring to.

**Comment by matdecac** [comment]
Ok, sorry I used a codepen from another bug which must have been a bit old.

But thanks for reopenning !

Mathias

**Comment by rbi13** [comment]
I am having the same issue with plotly.js v1.53.0 using values/dvalues. 
The breaks are displayed correctly, however the candles are displayed as vertical lines and none of the hover functionality is working.
