### ISSUE TITLE
Mock bar_multiline_labels has unexpected layout  "legend" value "none"

### ISSUE THREAD

**Issue by hmf** [plotly/plotly.js#4745]
My Scala scanner/parser failed on the [bar_multiline_labels.json](https://github.com/plotly/plotly.js/blob/master/test/image/mocks/bar_multiline_labels.json). The "legend" attribute in the following [snippet](https://github.com/plotly/plotly.js/blob/master/test/image/mocks/bar_multiline_labels.json#L157) (removed the other axis) is the _culprit_: 

```json
    "layout":{
        "showlegend": false,
        "xaxis": {
            "ticks": "outside",
            "domain": [0, 0.4]
        },
        "legend": "none",
        "height":800,
        "width":800
    }
```
According to the schema, it seems that the value should always be a JSON object. I am also assuming that `"none"` may have been used to remove/hide the legend but now we have a `"showlegend"` (set to false above).

Is this an error? Does removing the `"lengend"` correct this issue? If so, should I make PR with this element removed? 

TIA

**Comment by archmoj** [comment]
@hmf thans for reporting. 
This is fixed by https://github.com/plotly/plotly.js/commit/647673159eb21b5db0769d1166f7a9a5958a73ae.
