### ISSUE TITLE
How to get selected data in parcoords?

### ISSUE THREAD

**Issue by AndreHermanto** [plotly/plotly.js#4756]
Hi Plotly Team,

How do you actually get the list of data selected in parcoords? The only event I tried that could trigger something is `plotly_restyle`, but this only returns the constraint range. 

```
[
  {
    "dimensions[2].constraintrange": [
      [
        3.75,
        4.25
      ]
    ]
  },
  [0]
]
```

Based on the documentation, isn't `plotly_selected` supposed to be the event that I'm looking for? But using `plotly_selected` doesn't return me anything when selecting on parcoords.

How to retrieve the selected data on parcoords? 

Cheers,
Andre

**Comment by Di-o-go** [comment]
Hi,

Have you managed to retrieve the selected data from Parcoords?
