### ISSUE TITLE
[Bug] data[type=scattergl ]  gives error if webGL is not supported

### ISSUE THREAD

**Issue by mafar** [plotly/plotly.js#4765]
When browser does not have webGL enabled, ```type=scattergl``` gives error on console.
See error below
![image](https://user-images.githubusercontent.com/4101480/79355979-d0315e00-7f57-11ea-9cca-331428e06d48.png)

**Steps To Reproduce:**
I used firefox => ```about:config ```  =>  ```webgl.disabled: true  ``` to disable webGL to reproduce this issue.
![image](https://user-images.githubusercontent.com/4101480/79356266-2acaba00-7f58-11ea-9237-bdeffb295908.png)

**Expected Behaviour:** 
Instead of error , plotly should display following message just like ```type=scatter3d``` or ```type=isosurface```

> WebGL is not supported by your browser - visit https://get.webgl.org for more info

(disable webGL first) (Correct Behaviour scatter3d)
 https://codepen.io/mafar/pen/ZEbQLZm?editors=1010

**Incorrect Behaviour: scattergl**
(disable webGL first)
https://codepen.io/mafar/pen/XWmXpoO?editors=1010

**Comparison:**

![image](https://user-images.githubusercontent.com/4101480/79357864-fe17a200-7f59-11ea-8654-374f775d1e66.png)

**Comment by mafar** [comment]
can anyone point , in which js file i should be looking to make a fix. plotly has really long code

**Comment by archmoj** [comment]
Closed via #4777.
