### ISSUE TITLE
Wrong order for bar chart sorting with null values

### ISSUE THREAD

**Issue by oshikryu** [plotly/plotly.js#4784]
When data has null values, sort them to the end (if descending) and beginning (if ascending)

Example of improper sorting.
<img width="1824" alt="Screen Shot 2020-04-22 at 12 26 16 PM" src="https://user-images.githubusercontent.com/1293288/80024822-7ddec880-8494-11ea-8583-17e3c8efd32e.png">
https://codepen.io/oshikryu/pen/MWaJgLx

This is the simple case where there is no bar grouping value. 
The issue with the bar grouping value is here: https://github.com/plotly/plotly.js/issues/4749

**Comment by alexcjohnson** [comment]
Fixed by #4783 🎉
