### ISSUE TITLE
Security warnings in static-module and minimist

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4796]
We need to resolve https://github.com/plotly/plotly.py/issues/2385 and https://github.com/plotly/jupyterlab-chart-editor/issues/47 by avoiding https://www.npmjs.com/advisories/758 and https://www.npmjs.com/advisories/1179

**Comment by nicolaskruchten** [comment]
Current strategy detailed in https://github.com/scijs/cwise/pull/25#issuecomment-642972416

**Comment by nicolaskruchten** [comment]
@archmoj what's our strategy for https://www.npmjs.com/advisories/1179 ?

**Comment by archmoj** [comment]
> @archmoj what's our strategy for https://www.npmjs.com/advisories/1179 ?

@nicolaskruchten Thanks for the question. That would be fixed as part of `cwise` patch.
