### ISSUE TITLE
(x|y)axis.hovertemplate

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4798]
Today with hovermode='x' or 'x unified' the x-value is shown either in its own little axis-attached hoverlabel, or at the top of the unified hoverlabel, but there is no way to control its formatting:

![image](https://user-images.githubusercontent.com/203523/80804144-494cca00-8b82-11ea-8563-e768cbcf0112.png)

![image](https://user-images.githubusercontent.com/203523/80804163-59fd4000-8b82-11ea-8332-c94c3d9650f0.png)

This is especially problematic for date axes, where people might have strong opinions about how dates should be formatted.

The proposed solution is to add `layout.xaxis.hovertemplate` which could be set to something like `%{x:<d3 number format>}` or `%{x|<d3 date format}` or even something more fanciful like `The date here is %{x}.` etc. We would implement the same thing for the y axis when hovermode is 'y' or 'y unified', naturally.

**Comment by nicolaskruchten** [comment]
In fact, we already have `xaxis.hoverformat` which addresses most of this.

**Comment by nicolaskruchten** [comment]
OK, no more work required here.

**Comment by ironfist95** [comment]
Hi, I would like the power of hovertemplate, hoverformat is not capable of very much.
