### ISSUE TITLE
Category-axis bar chart has incorrect width if category label equals endpoint of autocomputed range

### ISSUE THREAD

**Issue by airtable-MartinMichelsen** [plotly/plotly.js#4812]
For bar charts with category-labeled x axes, Plotly automatically computes an x-axis range based on the number of bars in the chart, which seems to be [-0.5, numBars - 0.5]. The chart doesn't render properly if one of the range endpoints happens to be equal to a category name. In the following example, the graph is cut off with the bar labeled '2.5' being partially out of frame and the bar labeled '3.0' not rendering at all:
https://codepen.io/mmichelsen/pen/LYpebKj

If you change '2.5' to anything other than '-0.5' or '2.5', the graph renders properly.

**Comment by claraPag** [comment]
Hi, i am having exactly the same issue describe above.. Is there any action taken on your side to resolve this very annoying issue ? Thank you in advance for your help

**Comment by airtable-MartinMichelsen** [comment]
Appending a zero (e.g. changing "2.5" to "2.50" works around the issue.

**Comment by LoganWlv** [comment]
@nicolaskruchten this one relates to https://github.com/plotly/plotly.js/issues/5200 which is fixed

**Comment by nicolaskruchten** [comment]
Indeed, your fix in https://github.com/plotly/plotly.js/pull/5211 seems to have resolved this one, thank you :)
