### ISSUE TITLE
Let the first sector of a pie chart unfold counterclockwise

### ISSUE THREAD

**Issue by DaniMori** [plotly/plotly.js#4817]
When I create a pie chart, and I set attribute `direction = "counterclockwise"`, I would like that the first sector can be configured to unfold counterclockwise as well.

Although I could "manually" compute the angular width of the sector and subtract it from the desired value in the `rotation` argument, that would still fix the first edge (in clockwise order) when I turn on/off categories in the legend, and thus the last edge would not be aligned with the desired rotation.  The desired behavior would be that the last edge is fixed so that the `rotation` argument fixes the rotation of the first sector shown, no matter which one it is.

In this example, the first sector "a" unfolds clockwise, while the categories are plot counterclockwise
from the reference direction (12 o'clock):

![](https://i.imgur.com/Mk73IOV.png)

As a workaround, I can subtract the width of first category from the desired value for
`rotation`; this is ok as long as all traces are active, but not when they are clicked on/off on legend:

![](https://i.imgur.com/pSOz5kE.png)

**Comment by mdouchin** [comment]
+1 for the ability to let the 1st slice go "the right way", ie from right (angle 0) to the left (ex angle -20) when going anticlockwise.

**Comment by DaniMori** [comment]
Yes, I created that issue in the `ropensci` repo myself. The problem is that the behavior is not as expected when I turn traces off.

**Comment by nicolaskruchten** [comment]
This makes sense and we'd certainly accept a pull request that added a new attribute to `pie` traces to control the placement of the first slice to make it work more similarly to something like Excel :) 

This attribute could be called e.g. `firstslicedirection` with accepted values `forward` and `reverse` (defaulting to `reverse` to preserve the current behaviour for existing users).

**Comment by DaniMori** [comment]
Would this affect also a "clockwise" pie chart? If so, defaulting to `reverse` would imply that the first slice would go "counterclockwise", instead of "clockwise" (i.e. forward) as it is now.

If it helps clarifying it, please consider the accepted values `clockwise` and `counterclockwise` instead.

**Comment by nicolaskruchten** [comment]
I think that it's more flexible/orthogonal to support forward/reverse with respect to the existing `direction` attribute, so if `direction` is `clockwise` then the `reverse` `firstslicedirection` means "counterclockwise" and vice-versa.

**Comment by DaniMori** [comment]
Ok, I think I missunderstood, it's clear now. I'd also like to ask, is there any reason for not using a boolean (e.g. `reversefirstslice = false/true`) instead?

**Comment by nicolaskruchten** [comment]
That would be fairly equivalent, yes.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
