### ISSUE TITLE
Incorrect automatic date labels on X axis

### ISSUE THREAD

**Issue by meglio** [plotly/plotly.js#482]
Data is provided from Apr 7 to Apr 22:

![image](https://cloud.githubusercontent.com/assets/282177/14876852/6f40ac34-0d57-11e6-859f-381381322de3.png)

The very first X-label says Apr 8.
Expected: Apr 9 (3rd day starting from Apr 7).

The conflict also can be clearly seen when mouse-hovering the corresponding data point:

![image](https://cloud.githubusercontent.com/assets/282177/14876885/a9ff69fa-0d57-11e6-990a-50163a3554a2.png)

---
# Data for bug reproduction

Days (X axis):

``` json
["2016-04-07","2016-04-08","2016-04-09","2016-04-10","2016-04-11","2016-04-12","2016-04-13","2016-04-14","2016-04-15","2016-04-16","2016-04-17","2016-04-18","2016-04-19","2016-04-20","2016-04-21","2016-04-22"]
```

Number of responses (Y axis):

``` json
[1,0,0,0,0,0,0,0,1,0,0,2,0,0,0,6]
```

**Comment by etpinard** [comment]
@meglio I can't reproduce this.

Here's what I tried: http://codepen.io/etpinard/pen/ONBmrx

**Comment by meglio** [comment]
What you are showing in codepen demonstrates the bug.
Mouse hover where the x-axis label says "Apr 8" and it will show a black popup saying "Apr 9":

![image](https://cloud.githubusercontent.com/assets/282177/14890290/28b7bbd2-0da1-11e6-9b1b-ab02a7ef7a36.png)

**Comment by etpinard** [comment]
Ah it must be a timezone-related issue. 

Here's what I'm getting:

![image](https://cloud.githubusercontent.com/assets/6675409/14890484/d7dda9b2-0d30-11e6-8707-d08b26ec2964.png)

This issue is possible a duplicated of https://github.com/plotly/plotly.js/issues/171

**Comment by meglio** [comment]
The dates I'm feeding to Plotly.js are in format `YYYY-MM-DD` - it contains no timezone information at all. Still can be a timezone issue?

**Comment by etpinard** [comment]
@meglio https://github.com/plotly/plotly.js/blob/master/src/lib/dates.js

**Comment by meglio** [comment]
If this is a timezone issue, how can it be that static labels are incorrect while the hover labels are correct?

**Comment by etpinard** [comment]
If you zoom in on that point, you'll see that the label and data point aren't exactly at the same location. They should be a few hours apart, one on April 8, one on April 9.

**Comment by alexcjohnson** [comment]
This seems to have been fixed - probably by #1194. Feel free to reopen if you still see the problem.

**Comment by analytics-bootcamp** [comment]
Hi,

It seems that I run into the same issue again, but now it's on month level. This is not a timezone issue, is it?

https://plot.ly/~olavl/6/#plot

The hover date is correct, the x-axis label date not.

**Comment by alexcjohnson** [comment]
@analytics-bootcamp you're right, that's not a timezone issue. The issue there is that we automatically put the label "Aug 2018" at August 1, which is essentially at your bar for July 31. The ticks are not labeling the bars, though in this case they're very close to the bars, they're labeling axis positions.

You can force the behavior you want with eg:
```js
Plotly.relayout(gd,{
    'xaxis.tick0':'2000-01-31', // canonical tick on the last day of the month
                                // (which automatically sets tickmode: 'linear')
    'xaxis.dtick':'M1', // can't use auto ticks with tick0, so you have to specify 1-month ticks
    'xaxis.tickformat':'%b %Y' // eg 'Jul 2018', otherwise we'll show 'Jul 31'
                               // (and year when necessary)
})
```

I'm not really sure how we could figure out automatically that this is what you want though.
