### ISSUE TITLE
faceting react() bug

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4826]
Sorry this isn't a more minimal codepen but there's something seriously wrong with the category orders here: https://codepen.io/nicolaskruchten/pen/rNOKjpE

Note: the JSON here is basically what you'd get from PX in a Dash app when changing some filters.

**Comment by archmoj** [comment]
Here is a slightly more minimal [demo](https://codepen.io/MojtabaSamimi/pen/xxwzqmp?editors=0010).

**Comment by archmoj** [comment]
Seems like there is no problem with `vertical` bars: [demo 1](https://codepen.io/MojtabaSamimi/pen/WNQyjer?editors=0010).

**Comment by archmoj** [comment]
[demo 2](https://codepen.io/MojtabaSamimi/pen/ExVRmyE?editors=0010) illustrate that ther is no bug with `vertical` bars. So the issue appear to be only with `horizontal` ones.

**Comment by nicolaskruchten** [comment]
Note that in the initial pen, there is no `xaxis2.matches` but there is `yaxis2.matches` ... if I add `xaxis2.matches="x"` to both in your vertical codepen the issue returns. So this is maybe related to `matches` with categories and react?

**Comment by alexcjohnson** [comment]
Possibly related: #4718
