### ISSUE TITLE
problem with the time-zone on making baselines

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#4828]
If I `npm run baseline` on the figure in this [demo](https://codepen.io/MojtabaSamimi/pen/qBOKwWa),
I get an strange image:
![make-baseline](https://user-images.githubusercontent.com/33888540/81701304-d243eb00-9437-11ea-99d0-b4be3f687abb.png)

which depends on time-zone? and is different from what is displayed as well as download-image one:
![download-image](https://user-images.githubusercontent.com/33888540/81701483-120ad280-9438-11ea-9792-b9186044ad85.png)

**Comment by archmoj** [comment]
@antoinerg curious to know what you get with `orca`?

**Comment by alexcjohnson** [comment]
@archmoj I think this is to be expected when you provide dates as milliseconds:
```js
    "xbins": {
        "start": 1578002100000,
        "end": 1578063300000,
        "size": 600000
    }
```

Presumably `xbins.start/end` can be strings and then everything is self-consistent?

**Comment by archmoj** [comment]
@alexcjohnson thanks for the hint.
Yeah we could only generate a desired baseline if we use date strings:
```
"xbins": {
        "start": "2020-01-02 16:55",
        "end": "2020-01-03 09:55",
        "size": 600000
},
```
