### ISSUE TITLE
Axis labels on very tall graph don't reach end of axis

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#484]
Originally posted on https://github.com/plotly/plotly.py/issues/450

See codepen: http://codepen.io/etpinard/pen/WwajEX

I was able to reproduce the issue with a `scatter` trace as well.

Something must up in the axes code.

**Comment by alexcjohnson** [comment]
Oh that's just a failsafe against [infinite loops](https://github.com/plotly/plotly.js/blob/master/src/plots/cartesian/axes.js#L810-L811) - we could be smarter about that, perhaps just check to see that each label is closer to the end than the previous one was, though I do think we need *some* sort of upper bound to prevent locking the browser - this can happen easily for example if you specify an explicit tick spacing and then zoom out a lot.

**Comment by etpinard** [comment]
Thanks for the clarification @alexcjohnson :books:
