### ISSUE TITLE
Allow layout.(x|y)axis.tickformat to be assigned a user supplied function too

### ISSUE THREAD

**Issue by jaromir-benes** [plotly/plotly.js#4840]
Hi

First off, many thanks for all you effort you've put into developing Plotly. Greatly appreciated.

My issue/feature request is motivated by the fact that you still haven't upgraded to d3 v5. For me personally, the biggest pain is the impossibility to use all the v5 date formatting options. Perhaps, an easier workaround to implement (which would also enhance the flexibility of your package) could be to allow the user to pass their own formatting function (not only string) into `layout.(x|y)axis.tickformat` (hence, I could then load the latest d3-time-format separately, and compose my own formatting functions).

Best
Jaromir

**Comment by alexcjohnson** [comment]
This is ancient, sorry - but see #1464

**Comment by sergei3000** [comment]
hi @alexcjohnson , what do you mean it's ancient? The issue you referenced is closed.
Does all this mean the desired feature will not be implemented?

**Comment by alexcjohnson** [comment]
By ancient I meant my response came 3 years after the question, so was probably not much use to the original poster. But that’s correct, we do not intend to implement this.
