### ISSUE TITLE
Optimized rendering for image traces

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4842]
Breaking this off of https://github.com/plotly/plotly.js/issues/4301

Let's carefully think about whether or not this would be a breaking change and if we need a new attribute, but clearly this is needed, as right now we're avoiding using `image` traces in favour of `layout.image` for performance reasons.

Note that this rendering concern is distinct from the input specification in base64-encoded PNG or via URL, which will be tracked in https://github.com/plotly/plotly.js/issues/4841

cc @emmanuelle @nicholas-esterer

**Comment by nicolaskruchten** [comment]
In principle, this should address https://github.com/plotly/plotly.js/issues/4377 on supported browsers, right @antoinerg ?

also cc @jonmmease

**Comment by antoinerg** [comment]
> In principle, this should address #4377 on supported browsers, right @antoinerg ?
> 
> also cc @jonmmease

It should definitely get rid of the flashing but it probably won't help with the tooltip issue (https://github.com/plotly/plotly.js/issues/4570).

**Comment by archmoj** [comment]
Could we close this issue now that #5075 merged?
