### ISSUE TITLE
Relaxed versions

### ISSUE THREAD

**Issue by daveisfera** [plotly/plotly.js#4843]
Currently, a few specific versions are used (here's an example: https://github.com/plotly/plotly.js/commit/ecff28e5c465a08b08d8eb001bb50e3cdb8f4a0a ), but this can cause multiple versions to be installed by users, so could `^` or `~` be sure to allow more flexibility in what's installed?

**Comment by archmoj** [comment]
For some modules we needed specific versions. What's wrong with (not globally) installing multiple versions?

**Comment by daveisfera** [comment]
It takes up more space and makes the `yarn install`/`npm install` take longer, and can occasionally result in security vulnerabilities hanging around

**Comment by archmoj** [comment]
There is e.g. [this issue](https://github.com/plotly/plotly.js/issues/4926) with latest version of `mapbox-gl` so I don't think we could relax its version.
