### ISSUE TITLE
Empty array axis anchor leads to fatal id.match is not a function error

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#4844]
Minimal example https://codepen.io/cpsievert/pen/QWjzGgJ

Initially reported in https://github.com/ropensci/plotly/issues/1768

**Comment by archmoj** [comment]
Seems to work if one sets `yaaxis2.anchor` to `free` instead of an empty array.
Am I missing something?

**Comment by cpsievert** [comment]
Ohh, yes, thanks, and sorry for the noise :)

**Comment by archmoj** [comment]
@cpsievert no worries. Please feel free to re-open if you think we should better handle that case of empty array?

**Comment by alexcjohnson** [comment]
Low priority, but a thrown error preventing rendering is a bug even if it resulted from garbage input.
