### ISSUE TITLE
Explicitly setting tickmode to array disables tickvals in date axis

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4848]
Initially reported in https://github.com/plotly/plotly.py/issues/2478

This codepen is a bit puzzling: https://codepen.io/nicolaskruchten/pen/MWaZBwa ... I'm explicitly setting `tickmode` to `array` and seeing the default tick labels. But if I comment out that `tickmode` line it does the right thing, even though the schema docs say that this configuration should imply `tickmode=array`!

**Comment by archmoj** [comment]
Not sure if this should be labeled as a bug; whereas we have this logic:
https://github.com/plotly/plotly.js/blob/0b54b3f02dfee76a2250a1155b581b5079bba145/src/plots/cartesian/tick_value_defaults.js#L27-L29

**Comment by nicolaskruchten** [comment]
And yet we say: `"(*array* is the default value if `tickvals` is provided)"` in  https://github.com/plotly/plotly.js/blob/master/src/plots/cartesian/layout_attributes.js#L378

So what is the actual value of `tickmode` for date axes when `tickvals` is provided and `tickmode` is not provided? Because that does display the desired behaviour :)

**Comment by archmoj** [comment]
> So what is the actual value of `tickmode` for date axes when `tickvals` is provided and `tickmode` is not provided? Because that does display the desired behaviour :)

`tickmode` would be set to `array` in that case.

**Comment by archmoj** [comment]
The logic was present since v1.0:
![Screenshot from 2020-05-20 13-27-57](https://user-images.githubusercontent.com/33888540/82477723-dad29c00-9a9d-11ea-9856-d2563a35a066.png)

It looks like a bug to me.

**Comment by nicolaskruchten** [comment]
Weird! So if I don't set it, it gets set to array but it skips this check?

**Comment by archmoj** [comment]
> Weird! So if I don't set it, it gets set to array but it skips this check?

Positive. I think we could/shoud fix this for `log` as well.
I am close to open a PR for this.
