### ISSUE TITLE
Make surface contour levels configurable

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#485]
... with `autocontours`, `ncontours`, `contour.start`, `contour.end` and `contour.size`.

Looks like [`gl-surface3d`](https://github.com/gl-vis/gl-surface3d/blob/master/surface.js#L124) already has that feature; it would just a matter of exposing the contour calc [step](https://github.com/plotly/plotly.js/blob/1f406e5bf7c4396f3371699c4f61cb406f61b2e6/src/traces/contour/calc.js#L24-L48) so that the surface convert step can reuse it to fill the `contourLevels` gl-surface3d property.

**Comment by Koushikphy** [comment]
This is a nice way to plot wireframe plot using plotly.js by providing hidesurface:true. But the only problem is I can't make the last/end line visible even though I'm giving all the tickvals. Anyway to show that last line?

**Comment by archmoj** [comment]
@Koushikphy Thanks for reporting this. 
@etpinard I don't know if this was mentioned before? If so we may open a new issue and I would try to address that in the PR related to `gl-surface3d` module.
Here is a [demo](https://codepen.io/MojtabaSamimi/pen/eQQMYX) in respect to that.

**Comment by yaozhewei** [comment]
Has there been any updates? This would be a very good feature to have

**Comment by etpinard** [comment]
@archmoj wanna close this thing?

**Comment by archmoj** [comment]
Hmm... 
The surface contours are quite configurable.
So yes let's close this for now.

**Comment by Koushikphy** [comment]
I still can't get the last contour line. If my data is upto say `xMax` then providing `end:xMax`  doesn't draw the contour line corresponding contour line.
