### ISSUE TITLE
[IE11] Zoom using scroll doesn't work

### ISSUE THREAD

**Issue by Xerotico** [plotly/plotly.js#4853]
Hi, team!
Using the latest version of the plotly.js, we are faced with the following issue:
When we set the flag `scrollZoom: true`, zoom using the mouse scroll does not work.

Live example: https://liveweave.com/zHvu2p
Environment: Windows 10 x64, Internet explorer 11.

P.S: in chrome everything works fine.

**Comment by archmoj** [comment]
@Xerotico I can replicate this.
Which version of `plotly.js` you were using before?

**Comment by Xerotico** [comment]
Seems that https://github.com/plotly/plotly.js/pull/4385 should fix the issue

**Comment by Xerotico** [comment]
@archmoj We have used `v1.50.0` but I cannot approve that in this version zoom works fine in IE11. According to Pull Request that I have mentioned above, it seems that the issue is actual at least since Nov 25, 2019.

**Comment by sgorchichko** [comment]
@archmoj any updates on this?

**Comment by archmoj** [comment]
Fixed via #4385.

**Comment by sgorchichko** [comment]
@archmoj when could we expect 1.54.2 to be released?

**Comment by archmoj** [comment]
@sgorchichko possibly today or sometime this week, I hope.

**Comment by archmoj** [comment]
@sgorchichko update: start of next week.

**Comment by sgorchichko** [comment]
@archmoj Looking forward and thanks for the update!
