### ISSUE TITLE
Parcoords - lines disappear, categorical axis with single tick

### ISSUE THREAD

**Issue by MrHejtmar** [plotly/plotly.js#4876]
In parcoords, unexpected behavior happens when applying brush to a categorical dimension with single tickval and ticktext. When brush is applied to this dimension (to the single tick,  then applied brush has no meaning), all lines disappear. After clicking on the (hidden) dimension and removing brush, lines appear again.

Also, I noticed when there are applied brushes to other dimensions (so far the chart behaves properly), it is impossible to apply the brush to this single tickval / ticktext dimension .

See below:

https://codepen.io/martin-hejtm-nek/pen/mdeYGYv

**Comment by alexcjohnson** [comment]
Good catch @MrHejtmar - we should probably just disable brushing entirely on any single-valued dimension.
