### ISSUE TITLE
Plotly.relayout doesn't update the subplot clip paths 

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#488]
a pretty high priority bug.

http://codepen.io/etpinard/pen/grBRao

**Comment by etpinard** [comment]
Introduced in `v1.10.0`

**Comment by n-riesco** [comment]
[One of my commits](https://github.com/plotly/plotly.js/commit/8fce07c19cda9dda8a10264e63baa5173376db37) is causing this bug.
