### ISSUE TITLE
no calendar on partial bundles

### ISSUE THREAD

**Issue by mattcorner** [plotly/plotly.js#4883]
I am trying to get the connectgaps property to work in a React app where I use a custom plotly.js bundle to reduce the build size. 

With this custom bundle which imports only Surface, connectgaps does not work.

If I use the full plotly.js bundle, the plot works properly. 

See attached github repo for a simple reproduction showing the two plots side-by-side. 
![image](https://user-images.githubusercontent.com/27866636/83103055-44cfee80-a0f9-11ea-857a-f2dd6feadbd4.png)
[Github repo for reproduction](https://github.com/mattcorner/plotly-surface-connectgaps-error)

I presume that I either need to import something extra in the custom bundle, or that lib/Surface is missing a dependency?

**Comment by archmoj** [comment]
Thanks for reporting. Here is a [codepen](https://codepen.io/MojtabaSamimi/pen/pojXNBW?editors=0010) illustrating the bug.
That's possibly related to `surface` trace using a function from `heatmap` trace.

**Comment by archmoj** [comment]
@alexcjohnson strangely there is no calendar attached to axes when using partial gl3d bundle: [demo](https://codepen.io/MojtabaSamimi/pen/oNbNgrY?editors=1000).

**Comment by archmoj** [comment]
To clarify how `calendar` issue is linked to `surface.connectgaps` issue, 
`calendar` is undefined here when using partial bundle:
https://github.com/plotly/plotly.js/blob/5b8b1db1386b82db747cbad239fed754e624a18f/src/traces/surface/convert.js#L444

**Comment by jendrikw** [comment]
Is it possible to fix the root cause? I don't need calendars (not even gregorian), and it's blowing up my bundle size.
