### ISSUE TITLE
Automatic axis detection incorrectly selects linear when data contains some numbers as a string

### ISSUE THREAD

**Issue by mofojed** [plotly/plotly.js#4889]
I have a CodePen here illustrating the issue: https://codepen.io/mofojed/pen/MWKWaOv?editable=true%3Dhttps%3A%2F%2Fplotly.com%2Fjavascript%2Fbar-charts%2F

If the x-axis data contains all strings, but some of those values are just numbers converted to strings, then the layout appears to resolve to the `linear` type, and only the numeric values are displayed. This is unexpected, as the data is provided as a string and there are also other entirely string values that should be shown. In my example, the x-axis data is just: `["Ace","2","3","4","5","6","7","8","9","10","Jack","Queen","King"]`

If you explicitly set the layout type to `category`, then it is displayed correctly. Automatic type selection should resolve to `category` instead of `linear` if there are non numeric values in the data.

**Comment by alexcjohnson** [comment]
This is a tricky one - there are also lots of data sets for which interpreting the data as numbers _is_ the desired outcome that are mostly numbers but have some non-numeric values like `"n/a"` or similar - and more often than you'd like these aren't clean, there are several varieties of non-numeric entry.

The fact that we treat numeric strings identically to numbers is at this point mostly a historical artifact (largely driven by [Chart Studio](https://chart-studio.plotly.com/)) but I don't think that's something we would want to alter without a major version bump.

So unless we can come up with a very robust heuristic to identify certain sets of mixed numbers and strings as definitively category data, I don't think we can change this behavior.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
