### ISSUE TITLE
How to reduce bundle size of Plotly.js for 3D surface chart?

### ISSUE THREAD

**Issue by Rezakarimi66** [plotly/plotly.js#4891]
Hi, Could someone please answer my question [here](https://stackoverflow.com/questions/62094091/how-to-reduce-bundle-size-of-plotly-js-for-3d-surface-chart). I have asked it everywhere and no one cares :(

**Comment by Rezakarimi66** [comment]
I just double checked the size of latest gl3d bundle. The minimized version which currently I am using [(look here)](https://cdn.plot.ly/plotly-gl3d-latest.min.js) has a size of 465kB. How did you create that file? I have used webpack and also browserify to create such bundle but not successful.
![bundle size](https://user-images.githubusercontent.com/5058070/83666754-bb735d00-a5cd-11ea-85e1-529611fd1c6c.png)
Please take a loot at my code [here](https://github.com/Rezakarimi66/plotly-webpack)

**Comment by archmoj** [comment]
@alexcjohnson this is interesting in terms of using `webpack` instead of `browserify`.

**Comment by Rezakarimi66** [comment]
> @alexcjohnson this is interesting in terms of using `webpack` instead of `browserify`.

Size of bundle is also big with browserify for me. It's 1.4MB. You could see it with running my script "borwserify-prod" [(here).](https://github.com/Rezakarimi66/plotly-webpack) Webpack or browseriy or any other tool doesn't matter for me. Just trying to get the same size as yours.

**Comment by archmoj** [comment]
@Rezakarimi66 your fork is rather behind latest changes made to plotly.js including various module upgrades. Could you pull these changes (or on a separate repo) and then try applying your commit on top of that?

**Comment by Rezakarimi66** [comment]
@archmoj I updated my package.json file to the latest version ( [1.54.4](https://github.com/Rezakarimi66/plotly-webpack/commit/aae8981f2a8483d79e5bac6fe100d757948eaebc) ) Nothing changed :( 
Could you please share the code that you are using for generating your minified file (https://cdn.plot.ly/plotly-gl3d-latest.min.js)?

**Comment by archmoj** [comment]
@Rezakarimi66 
Here is what `npm run build` does: https://github.com/plotly/plotly.js/blob/b4a40046b05ff8b6b27e33f07206980f16ea70f2/package.json#L29.
Namely this file could be of interest: https://github.com/plotly/plotly.js/blob/master/tasks/bundle.js

**Comment by Rezakarimi66** [comment]
@archmoj Thanks for your helps. I cloned and changed your code to generate my custom bundle and the result was the same. The only possible way to reduce the size is to compress with gzip.

**Comment by archmoj** [comment]
@Rezakarimi66 Please see #5301.
