### ISSUE TITLE
Events and callbacks in Plotly

### ISSUE THREAD

**Issue by prog8** [plotly/plotly.js#49]
I am currently using C3 which is now not developing fast. I decided to evaluate Plotly. I see that Plotly is complex library comparing to C3 so it is much heavier. I think C3.js is designed in JS-fashion: emitting events and using callbacks. From what I can see Plotly is designed to be used in JS, Python, Matlab and R so I guess it works differently. Maybe I spent too little time to learn Plotly and I missed a few important things about it. What I would expect from Plotly is to emit events when one hovers a chart or use callbacks to format data which is shown in tooltips. Am I just missing how to use it? I haven't looked into source code of Plotly - only looked at examples and documentation.

**Comment by mdtusz** [comment]
For hover events, you can use the `plotly_hover` event. The DOM element for the graph will emit events, and you can bind event handlers like so:

```
var chart = document.getElementById('my-chart-element');

chart.on('plotly_hover', function(data){
  // do something with the data
});
```

The data returned varies by event, but for `plotly_hover`, you will have access to `points`, `xaxes`, `yaxes`, and `yvals` - all within the `data` that is passed to your callback. 

Here's an [example](http://jsfiddle.net/Largrgsw/2/) with some tooltips.

**Comment by otisg** [comment]
Thanks for the info, @mdtusz .  Do you know if this is documented somewhere?  We couldn't find this anywhere in the docs.

**Comment by mdtusz** [comment]
Unfortunately, It's not very well documented at the moment, but we are working on it. [This page](https://plot.ly/javascript/hover-events/) and [this page](https://plot.ly/javascript/click-events/) show some basic usage of hover and click events, but we will hopefully update the page with more detailed documentation and examples soon.

**Comment by chriddyp** [comment]
Updated documentation here: https://plot.ly/javascript/plotlyjs-events/
