### ISSUE TITLE
Documentation incorrectly states tickmode *must* be "array" for tickvals/ticktext to work

### ISSUE THREAD

**Issue by stringfellow** [plotly/plotly.js#4908]
The [documentation for ticktext and tickvals](https://plotly.com/javascript/reference/#layout-xaxis-tickvals) states that "Only has an effect if `tickmode` is set to "array"." 

The **opposite** of this is true, if the X axis is datetime type (or detected to be such). In this case, by adding `tickmode: "array"` to the `xaxis` options, the `ticktext` and `tickmode` values are totally ignored. Removing the `tickmode` setting produces the desired behaviour but is completely counter to what the documentation says. 

Here is an example **without** `tickmode` being set, and the X axis tick labels are as wanted, adding in `tickmode: "array"` to the xaxis options will cause it to revert to automatic date labels: https://codepen.io/etpinard/pen/YWEdJX

Fixing the code would be best (although will create breaking changes for users of this quirk) but fixing the documentation would be a good start...

**Comment by archmoj** [comment]
Thanks for the report. The bug is fixed in #4851 and would be reflected in `v1.54.2` release.
