### ISSUE TITLE
period positioning

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4912]
This issue is intended to apply in principle to `scatter` (not `scattergl`), `bar`, `funnel`, `waterfall`, `ohlc` and `candlestick` traces, and only applies in the context of `(x|y)axis.type=date`.

We need to be able to position marks along date axes not at a particular instant in time, but at the start/midpoint/end of a well-defined period (see related https://github.com/plotly/plotly.js/issues/4911). 

Proposed new trace-level attributes:

* (x|y)period: Standard duration notation like ‘<N>m’ or millis
* (x|y)period0: A specific boundary point timestamp which is used to compute all boundaries. This will allow us to define e.g. "quarters that start on Feb 1" or "weeks that start on Wednesdays" etc
* (x|y)periodalignment: start/middle/end

Proposed backwards-compatible changes to traces with `width` parameter:

* Start accepting period lengths
* Defaults to (x|y)period if orientation=(v|h)
* If specified as a period, then the bar widths are variable and the gaps are computed as a percentage of the local bar width

Note: the hoverlabel here will need some thought.

**Comment by nicolaskruchten** [comment]
Re the hover-label, let's not do anything special for now: the user can do whatever they like in the `hovertemplate`.

Re the `xperiod0` concept, I'll note that setting the default value to `1950-01-01 00:00`  conveniently anchors seconds, minutes, hours at 0, the day of week on a Sunday, the 1st of the month at 1, the first month of the year at January, the first quarter at Jan/Feb/Mar and the first year of a decade at a multiple of 10.

If someone wants quarters like Q1=Feb/Mar/Apr then could set `xperiod0` to something like `2020-02-01` or any other February 1, and if they want weeks that start on Mondays then they could set `xperiod0` to something like `2020-08-31` or any other Monday

**Comment by alexcjohnson** [comment]
FYI the default tick0 behavior already shifts to Sunday when using week ticks:

https://github.com/plotly/plotly.js/blob/2737bf26019e059f3da63c70545364bc3593474b/src/lib/dates.js#L45-L58

**Comment by nicolaskruchten** [comment]
Given Alex's comment above, let's just do the same thing with xperiod0 then, no need to force it to 1950 :)
