### ISSUE TITLE
Hovermode 'closest' should ignore hoverinfo 'none' pts 

### ISSUE THREAD

**Issue by empet** [plotly/plotly.js#493]
Hover text is not displayed in  plots generated with Plotly 1.9.10:
https://plot.ly/~empet/13758/network-centrality-measures/

**Comment by etpinard** [comment]
Thanks for the bug report.

Here's a minimal reproducible example: http://codepen.io/etpinard/pen/aNQmaq

This bug was introduced in `v1.10.0`.

I'm working on a fix starting now.

**Comment by empet** [comment]
Fine, thanks!!
