### ISSUE TITLE
Misalignment of candlestick, ohlc and box plots when using rangebreaks 

### ISSUE THREAD

**Issue by pavitrakumar78** [plotly/plotly.js#4933]
Hi,

The candlesticks in my plot are not aligned (the sticks are misaligned with the candle) when I use the rangebreak option when generating the plot.

Here's a sample: https://codepen.io/pkmar78/pen/oNbZwmQ

This issue does not occur for all charts, the above is just one example of where it occurred when I was testing this. I also looked at previous issues when rangebreak where just sticks were displayed instead of candlesticks (#4742) but I'm not sure if this is also a similar bug.

This issue does not occur if I remove the rangebreak settings from the plot parameters. 

Here's a pic of the misalignment:

![image](https://user-images.githubusercontent.com/5354407/85226040-e85ba880-b3f2-11ea-9a3f-df1212070285.png)

Could this be due to non-uniform dates? or is there any other param that I should be using, but missing from my code?

Plotly version used: 1.54.3
Source: https://cdn.plot.ly/plotly-1.54.3.min.js

**Comment by archmoj** [comment]
@pavitrakumar78 
Thanks for the report.

**Comment by archmoj** [comment]
Not only `candlestick` but also `ohlc` and `box` are affected.
Here is a [demo](https://codepen.io/MojtabaSamimi/pen/VwebLxp?editors=0010).

**Comment by pavitrakumar78** [comment]
@archmoj Thank you for the fix!
