### ISSUE TITLE
3D scatter plot not working in Firefox

### ISSUE THREAD

**Issue by mddr** [plotly/plotly.js#4943]
Hello,

I noticed that markers on 3D Scatter Plot are not visible at all in using Firefox, while it works perfectly in Chrome. I attached screenshots straight from the [docs](https://plotly.com/javascript/3d-scatter-plots/), but the issue persists also outside of them.

Firefox (tried it in private window with all extensions disabled, too):
![firefox_Screenshot_2020-06-23_10-15-09](https://user-images.githubusercontent.com/20992825/85378214-8c9c3700-b53a-11ea-868e-9a0736420338.png)

Chrome:
![chrome_Screenshot_2020-06-23_10-15-52](https://user-images.githubusercontent.com/20992825/85378218-8e65fa80-b53a-11ea-9515-0732965f50f0.png)

Additional info:
Firefox 77.0.1
Chrome 83.0.4103.116
OS: Linux Mint 19.3

**Comment by archmoj** [comment]
I was not able to replicate this on Firefox 77.0.1, Windows, Mac & Ubuntu.

**Comment by alexcjohnson** [comment]
Seems to me we've seen issues like this that are also dependent on specific graphics hardware - @mddr what can you tell us about your physical system?

**Comment by mddr** [comment]
Seems like the issue here is related to some Firefox Preferences. I tried the fresh install (both, 77.0.1 and Developer Edition 78.0b9) and it works until I log in into my Firefox account and sync the settings. I'll try to pinpoint the setting responsible for that

**Comment by mddr** [comment]
Okay, seems like I found the culprit: inside _about:config_ there is a setting called _privacy.resistFingerprinting_, which defaults to _false_. Setting its value to _true_ causes the behaviour I described above.

**Comment by alexcjohnson** [comment]
Nice detective work @mddr - I see the same on my Mac. It's only `about:config -> privacy.resistFingerprinting` that does this, if I go to `about:preferences#privacy` and set `strict` (which also claims to block fingerprinting) I still see the markers.

I somewhat doubt this is going to be something we can fix - and anyway keeping up with "advanced" experimental features like this seems like a bit of an arms race. If it becomes part of standard FF behavior though we would definitely want to take a closer look.

**Comment by kurtlawrence** [comment]
Thanks @mddr, I ran into this issue the other day as well and your problem-solving saved me heaps of time. It seems hit-and-miss whether it blocks the content or not, but turning _off_ the blocker does seem to fix it.

**Comment by xgsa** [comment]
The issue seems to be actual for Firefox 127.0.2 (64-bit) on Ubuntu 22.04.4 with privacy.resistFingerprinting=false. See details in https://github.com/ArduPilot/WebTools/issues/172

**Comment by aberja** [comment]
plotly still will not work in Firefox with privacy.resistFingerprinting=true.  

Firefox just announced that they are blocking more fingerpriting ( see: https://www.howtogeek.com/firefox-is-blocking-more-fingerprinting-methods-to-improve-privacy/ )

Considering how bad fingerprinting can be, I don't think it is fair to users that they have to allow fingerprinting to use plotly.

Therefore, would it be possible that this issue be reopened (or a new one created) to find a resoultion that will allow users to use plotly with  privacy.resistFingerprinting=true ?
