### ISSUE TITLE
text/texttemplate on heatmap/histogram2d traces

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4955]
It would be great to be able to deprecate the `create_annotated_heatmap` figure factory in Python :)

**Comment by archmoj** [comment]
What 'text' attribute does on heatmap right now?

**Comment by nicolaskruchten** [comment]
If it's there now then it just appears in the hover label if `hoverinfo` contains `text` I would assume.

**Comment by archmoj** [comment]
> If it's there now then it just appears in the hover label if `hoverinfo` contains `text` I would assume.

That does not seem to be working. Tracked in #4956.

**Comment by archmoj** [comment]
duplicate of #1116
