### ISSUE TITLE
heatmap & surface text not showing up in hover

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#4956]
[surface codepen](https://codepen.io/MojtabaSamimi/pen/YzwQLgm?editors=0010)
[heatmap codepen](https://codepen.io/MojtabaSamimi/pen/zYrzaqM?editors=0010)

**Comment by alexcjohnson** [comment]
`text` needs the same shape as `z` https://codepen.io/alexcjohnson/pen/MWKoXOq?editors=0010
