### ISSUE TITLE
xref="x2 domain" type options for shape/annotation/image

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4958]
If we could specify `x` and `y` in terms of an axis domain rather than paper coordinates, this would greatly facilitate positioning of horizontal/vertical lines and annotations thereof. See https://github.com/plotly/plotly.py/issues/2590 for more information.

**Comment by nicholas-esterer** [comment]
So this is progressing nicely: shapes, annotations and images can be placed relative to axes and will update their position relative to axis length and offset.
I'm just posting to get some feedback, to see what more needs to be done:
 - these new objects are still not draggable, looking into this
Is there a list of specs that the new objects should have? Right now I'm looking through `test/jasmine/tests/shapes_test.js` to see what tests should be adapted for this new behaviour.

**Comment by nicolaskruchten** [comment]
@alexcjohnson can you help orient Nick here plz?

@nicholas-esterer I don't think these shapes need to be draggable unless they've been created via the new shape-drawing system... can you elaborate about which objects are not draggable that you feel should be?

**Comment by nicholas-esterer** [comment]
If you put shapes on the plot referring to axis domains and set `config: { editable: true }` then when you would drag these shapes, they move to strange locations. I have fixed this though now. I would just need to add it for annotations.
But my question is more: is there a list of specs that the shapes / annotations / images need to fulfill? Because I discovered the dragging just by playing around with some test plots I made, and probably my playing around will not discover all intended use cases :)

**Comment by alexcjohnson** [comment]
> is there a list of specs that the shapes / annotations / images need to fulfill?

That's a good question - no, I don't think there is. But for shapes I can't think of anything besides the `editable: true` behavior that isn't visible in the original [shapes mock](https://github.com/plotly/plotly.js/blob/master/test/image/baselines/shapes.png) or in the [attributes](https://github.com/plotly/plotly.js/blob/master/src/components/shapes/attributes.js) for shapes. The same should be true of annotations and images, as long as each of the attributes they support do the expected thing (and annotations have `editable: true` dragging too) then we should be good.

**Comment by nicholas-esterer** [comment]
Dragging shapes and annotations while referencing an axis domain is mostly working. My goal is to have them behave like paper shapes but just react when the domain changes. I mostly have this working, however, I can't figure out how to keep them from "clipping" when they move outside of the subplot area. For comparison, paper shapes are not clipped at all, but shapes that reference data coordinates are.  However, the axis domain referenced shapes clip in a strange way, and the annotations disappear, see the video:
![clipping](https://user-images.githubusercontent.com/64649603/87209661-b0080580-c2e0-11ea-930f-a6dbe1d8e17b.gif)
