### ISSUE TITLE
Unexpected error when validating schema: In layout grid is not part of the schema

### ISSUE THREAD

**Issue by acse-fk4517** [plotly/plotly.js#4959]
Hi,

I am running plotly on the node for unit tests using jsdom. There is some inconsistent behaviour depending on whether I run the code on Node or in codepen.

*I should add I do not care about "unused" errors, only "schema" and "value" errors.

The full example below can be run using the command `node example.js`. Now if you do, you will get an error in validate:

`{"code":"schema","container":"layout","trace":null,"path":["grid"],"astr":"grid","msg":"In layout, key grid is not part of the schema"}`

Why does this happen?

```
const fs = require('fs');
const path = require("path");

const jsdom = require("jsdom");
const { JSDOM } = jsdom

// get current path
const currentPath = process.cwd();

// get path to the local javascript file
const scriptPath = path.resolve("../../../main/resources/plotly.min.js");

// this succesfully reads in the javascript file
const plotlyJs = fs.readFileSync(scriptPath, "utf8");

// a function that takes in json and validates both the data and layout objects
function validate(traces, layout) {

  // run some function based on the local library
  const dom = new JSDOM(`<body>
  <script>
  window.addEventListener('load', 
    function() {
       window.test = Plotly.validate(${JSON.stringify(traces)}, ${JSON.stringify(layout)})
    }, false);
  </script>

  </body>`, { runScripts: "dangerously" });

  // inject the local js script onto the page
  const script = dom.window.document.createElement('script');
  script.type = "text/javascript";
  script.textContent = plotlyJs;
  dom.window.document.head.appendChild(script);

  dom.window.onload = () => {
    console.log(JSON.stringify(dom.window.test));
  };
}

const raw = {"traces":[{"name":"test","type":"scatter","mode":"markers+lines","xaxis":"x","yaxis":"y","x":[1,2,3],"y":[1,2,3],"marker":{}}],"layout":{"title":"XY.Scatter.Int","legend":{"x":0,"y":1,"orientation":"v"},"height":500,"width":800,"grid":{"rows":1,"columns":1,"pattern":"independent"},"xaxis":{"title":"x","side":"","overlaying":"","showgrid":true,"zeroline":false,"showline":false},"yaxis":{"title":"y","side":"","overlaying":"","showgrid":true,"zeroline":false,"showline":false}},"config":{"responsive":false,"scrollZoom":true,"displaylogo":false}}
const chart = JSON.parse(JSON.stringify(raw))

validate([], chart.layout)
```

It seems to give a different error "unused" in the codepen below. This is the expected behaviour.  Any guidance would be appreciated on whether this is a library issue, or something wrong with my code.

<p class="codepen" data-height="265" data-theme-id="light" data-default-tab="js,result" data-user="fkE3" data-slug-hash="XWXgOpy" style="height: 265px; box-sizing: border-box; display: flex; align-items: center; justify-content: center; border: 2px solid; margin: 1em 0; padding: 1em;" data-pen-title="Plotly.js Simple Subplot">
  <span>See the Pen <a href="https://codepen.io/fkE3/pen/XWXgOpy">
  Plotly.js Simple Subplot</a> by fuzzy (<a href="https://codepen.io/fkE3">@fkE3</a>)
  on <a href="https://codepen.io">CodePen</a>.</span>
</p>
<script async src="https://static.codepen.io/assets/embed/ei.js"></script>

**Comment by archmoj** [comment]
@acse-fk4517 
Which versions of `jsdom`, `plotly.js` and `node` are you using?

**Comment by acse-fk4517** [comment]
> @acse-fk4517
> Which versions of `jsdom`, `plotly.js` and `node` are you using?

So I updated all the versions to the following after your comment to make sure. I download the plotly.min.js file from the cdn url to the relevant location on my drive:

```
- Node.js v12.18.0. 
- "canvas": "^2.6.1",
- "jsdom": "^16.2.2",
- "requirejs": "^2.3.6"
- https://cdnjs.cloudflare.com/ajax/libs/plotly.js/1.54.5/plotly.min.js
```

Once I make the update I get a new error:

`Error: Uncaught [TypeError: window.URL.createObjectURL is not a function]
`
No idea what is going on now.

**Comment by acse-fk4517** [comment]
Ok seem to got it working now thank you for your help!:

`  dom.window.URL.createObjectURL = function() {};
`
