### ISSUE TITLE
Images for logos, diagramming, etc.

### ISSUE THREAD

**Issue by mdtusz** [plotly/plotly.js#496]
@etpinard @cldougl 

For adding logos or other visual elements to plots that are not specifically data. A proposed interface is to add an `images` layout attribute:

```
{
  images: [{
    source: 'http://www.placekitten.com/450/450', // always kittens
    opacity: 0.8,
    layer: 'above',
    xanchor: 'center',
    yanchor: 'top',
    x: 0.5,
    y: 0,
    xref: 'paper', // default to use paper ref?
    yref: 'paper',
    width: 0.2 // smart aspect ratio preservation unless both dimensions given?
  }]
}
```

**Comment by etpinard** [comment]
maybe also `borderwidth` and `bordercolor` ?

**Comment by mdtusz** [comment]
Yep those can be added as well.

Regarding where to place the images - currently shapes can be in `shapelayer-below` or `shapelayer-above`. Do we create additional `images-above` and `images-below` or simply add them to the existing `shapelayer`s? I'm hesitant to add yet more layers to the plot, but at the same time, it's nice to keep things clearly defined. Thoughts?

**Comment by etpinard** [comment]
> Do we create additional images-above and images-below or simply add them to the existing shapelayers?

I'd for for no. Let's put `images` in the same layer(s) as shapes.

**Comment by etpinard** [comment]
One thing to take into consideration would be the _ordering_ of shapes and images in those `<g>` layer.

I'd vote for always placing images below the shapes in a given `<g>` layer using d3 [`selection.order`](http://bl.ocks.org/mbostock/1440766).
