### ISSUE TITLE
Any support for contourgl?

### ISSUE THREAD

**Issue by kennyhuynh125** [plotly/plotly.js#4962]
I have a feature on my app that could display up to 10+ different contour plots. Once it hits about 10+, the performance is affected. I know that there is a `contourgl` plot option, but after looking through some of the other issues, it seems that it is not very supported and has many bugs.

I have tried to use it as well and ran into some issues (think it was something to do with the shader). I'm wondering if there has been any improvements to `contourgl` or if there is another solution to getting faster performance while using `contour` (maybe via canvas instead of svg)?

**Comment by alexcjohnson** [comment]
I'm afraid that's right - `contourgl` is known to be buggy and we haven't seen enough interest in it to justify improving it. If you're interested in helping out we'd happily accept a PR, or [we would accept sponsorship](https://plot.ly/products/consulting-and-oem/) to accelerate it.
