### ISSUE TITLE
Plotly Transform Aggretation: median calculation appears wrong

### ISSUE THREAD

**Issue by mwills** [plotly/plotly.js#4966]
I have an application that can show the data in box format or aggregate into a scatter.  I noticed that some groups were showing different 'median' values.

here is a simple example using the numbers of 6, 28, 33, 37, 49 which is resulting in a median of 37...
<p class="codepen" data-height="265" data-theme-id="light" data-default-tab="html,result" data-user="mattrwills" data-slug-hash="LYGzXVP" style="height: 265px; box-sizing: border-box; display: flex; align-items: center; justify-content: center; border: 2px solid; margin: 1em 0; padding: 1em;" data-pen-title="Plotly.js Transforms median error?">
  <span>See the Pen <a href="https://codepen.io/mattrwills/pen/LYGzXVP">
  Plotly.js Transforms median error?</a> </span>
</p>

**Comment by archmoj** [comment]
@mwills thanks very much for the report and a minimal example.
It appears there is a sorting problem when numbers have different digits!
And if I add 100 to that list I get the correct answer | [demo](https://codepen.io/MojtabaSamimi/pen/abdVbWe?editors=0010).

**Comment by alexcjohnson** [comment]
Heh we’re probably falling into the trap of assuming the default sort function is numeric, but it’s actually string-based. I never did understand that choice...
