### ISSUE TITLE
Element.querySelector error when deleting a trace whose uid contains complex characters

### ISSUE THREAD

**Issue by theodcr** [plotly/plotly.js#4967]
Hi and thank you for the awesome work!

I am using Dash to build a graph whose traces depend on user input and external data. I set the various traces `uid` to be able to track UI changes with `uirevision`, and Plotly.js throws this kind of error when deleting certain traces: `Element.querySelector: '.cb<buggy uid>' is not a valid selector`. It causes the graph to stop responding.

I have understood it happens when the uid contains whitespace or special characters. However this error is only thrown when deleting traces. When traces are not deleted, Plotly and Dash are able to track UI change and trace visibility perfectly even with these complex uids. So this could either be considered as a bug in trace deletion, or a lack of clarification on what is a valid uid.

I can give you this working example using Dash, the app creates and deletes traces based on user input. I am using Dash v1.13.4 which uses Plotly.js v1.54.3.

```python
import dash
import dash_core_components as dcc
import dash_html_components as html
import plotly.graph_objects as go
import numpy as np
from dash.dependencies import Input, Output


app = dash.Dash(__name__)

app.layout = html.Div([
    dcc.Graph(id='graph', figure=go.Figure()),
    dcc.Dropdown(
        id='dropdown', clearable=False, value=1,
        options=[
            {'label': str(i), 'value': i} for i in range(1, 10)
        ]
    )
])


@app.callback(
    Output('graph', 'figure'),
    [Input("dropdown", "value")]
)
def update_figure(nb_traces):
    fig = go.Figure()
    for i in range(nb_traces):
        fig.add_trace(
            go.Scatter(
                x=np.random.rand(10),
                y=np.random.rand(10),
                mode='markers',
                name=i,
                uid=f"uid with whitespace / special characters {i}",
            )
        )
    return fig


if __name__ == '__main__':
    app.run_server(debug=True)
```

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
