### ISSUE TITLE
Inconsistence for Gaps in scatterGL with NaN

### ISSUE THREAD

**Issue by wandri** [plotly/plotly.js#4968]
Plotly version: v1.54.5

Hello.

I have found, what I believe is an inconsistence: [https://codepen.io/wandri/pen/pogdJYd](https://codepen.io/wandri/pen/pogdJYd)

For a **ScatterGL plot**, 

- If my Y values are not a constant and with some NaN, then I have gaps in my plot.
- If my Y values **are a constant** and with some NaN, then I have no gap in my plot, and my points are connected.

<img width="1535" alt="Screenshot 2020-06-30 at 17 07 33" src="https://user-images.githubusercontent.com/15016833/86143092-47f13c80-baf4-11ea-8fc3-b1d99398165f.png">

(For Scatter, the gap is displayed correctly in the both case)

**Comment by archmoj** [comment]
Unable to replicate.
I get this using Chrome 78 (or Firefox) on Ubuntu 19.
![NaN](https://user-images.githubusercontent.com/33888540/86154360-f6838600-bad0-11ea-93df-7fe49d367cc6.png)

@wandri Could you please mention your OS + browser?

**Comment by alexcjohnson** [comment]
Looks fine to me too - Chrome 83 or FF 77 on Mac. Interestingly enough we had (and fixed) a similar problem last year https://github.com/plotly/plotly.js/pull/4316

**Comment by wandri** [comment]
Thanks,
I'm working with 
macOs Catalina 10.15.5.
Chrome: Version 83.0.4103.116 (Official Build) (64-bit)

I have tried my example: https://codepen.io/wandri/pen/pogdJYd, 

- On Firefox 78 (macOs Catalina 10.15.5)

<img width="1247" alt="Screenshot 2020-07-01 at 09 04 28" src="https://user-images.githubusercontent.com/15016833/86213527-1b800380-bb7a-11ea-84f7-52643124b735.png">

- On the app Chrome (v 83.0.4103.106) with my Samsung S 10
![Screenshot_20200701-090848_Chrome](https://user-images.githubusercontent.com/15016833/86214005-ddcfaa80-bb7a-11ea-8137-9d767191610c.jpg)

**Comment by wandri** [comment]
I try again today on my MAC with this example. It works.
I close the topic

**Comment by alexcjohnson** [comment]
OK thanks @wandri - seems like there still may be something funny going on here, so if this comes back and anyone can pin down exactly the conditions when it's happening, please reopen.
