### ISSUE TITLE
hoverlabel not working properly with subplots when resizing window

### ISSUE THREAD

**Issue by mbkupfer** [plotly/plotly.js#4971]
There is something buggy going on with my subplots using x unified

When creating the plot on its own, the hoverlabel is fine, but when I put it inside a dash app via dcc.Graph component, the labels don’t show. I created two versions in chart studio, one that is exported from the dash app and the second created using the `chart_studio` module.

The latter works fine, but the former works initially, but then all but the last plot’s hover labels no longer work when the window is resized.

Any idea what is going on here?

Created using dash app via dcc.Graph: https://chart-studio.plotly.com/~mbkupfer/72/#/

Created using chart_studio (works good): https://chart-studio.plotly.com/~mbkupfer/70/#plot

Dependencies:

```
dash                      1.13.3
dash-core-components      1.10.1
dash-html-components      1.0.3
dash-renderer             1.5.0
dash-table                4.8.1
plotly                    4.8.2
```
**[Update]**
It actually looks like this issue occurs in both created plots.

**Comment by nicolaskruchten** [comment]
@archmoj @antoinerg can you take a look at this plz?

**Comment by archmoj** [comment]
@mbkupfer do you think it is a regression?

**Comment by archmoj** [comment]
> **[Update]**
> It actually looks like this issue occurs in both created plots.

Looks like the expected behaviour to me.
Should we remove the bug tag and add a feature request tag?

**Comment by mbkupfer** [comment]
> do you think it is a regression?

@archmoj couldn't say, this is my first time using this feature

> Looks like the expected behaviour to me.

For the hover data to not show?

FWIW, this issue only comes up when I used `shared_xaxes`. I have been able to get a workaround by not using shared and making the other axes invisible.

**Comment by archmoj** [comment]
> > Looks like the expected behaviour to me.
> 
> For the hover data to not show?

For the hover not to show across subplots.

> FWIW, this issue only comes up when I used `shared_xaxes`. I have been able to get a workaround by not using shared and making the other axes invisible.

Am curious to see how the results look like.

**Comment by mbkupfer** [comment]
> Looks like the expected behaviour to me.
>> For the hover data to not show?
>>> For the hover not to show across subplots.

Oh, no...what I meant was that it simply didn't show. For example, in first screenshot, I get a unified hoverlabel on the first plot, but when I resize the window it no longer shows...all I get are the pipelines. The only subplot that shows overlaps at this point is the last one.

![image](https://user-images.githubusercontent.com/6313008/86183662-5f75f880-bae7-11ea-9ba2-c2ffbaf211a9.png)

![image](https://user-images.githubusercontent.com/6313008/86183678-67ce3380-bae7-11ea-9cb0-9083bf8a93eb.png)

**Comment by archmoj** [comment]
@mbkupfer now could you please modify the issue title to better reflect the problem you observed?
Thanks in advance,

**Comment by archmoj** [comment]
Here is a [codepen](https://codepen.io/MojtabaSamimi/pen/NWxwdYY?editors=0010) to help illustrate the problem.
Not only `unified hover` but also other modes have this problem.

**Comment by archmoj** [comment]
And this is a regression since [v1.54.2](https://github.com/plotly/plotly.js/releases/tag/v1.54.2).

**Comment by archmoj** [comment]
Side effect of #4832
