### ISSUE TITLE
Template quirk

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#4980]
A strange effect of #4904:
- If you want to use the template to override default colors for axis lines that are hidden by default, now you need to explicitly hide those lines.
- We decided in that PR that this behavior is more self-consistent, because that's how the regular figure attributes work: if you provide a color, it makes the line visible by default. So the template should do that too, otherwise it has a strange difference vs a regular figure.
- EXCEPT that templates are often used just to provide new defaults but the intent is not to override other parts of the logic. In the case of axis lines this has two undesirable effects:
  - Sometimes the data itself causes the lines to show. For example bar charts by default turn on the zero line. But now if you have a template that recolors the zero line and then turns it back off, bar charts won't be able to automatically turn it back on.
  - If the user provides a new color for the line in the main figure, it won't cause the line to turn on, as it would without the template present.

Both of these are demonstrated in https://codepen.io/alexcjohnson/pen/VweyRJe?editors=1010 - without the template, both the xaxis line and the x=0 line show:
<img width="414" alt="Screen Shot 2020-07-03 at 3 03 07 PM" src="https://user-images.githubusercontent.com/2678795/86493136-5d59a700-bd3e-11ea-97d6-810461a737df.png">
But with the template they both disappear:
<img width="385" alt="Screen Shot 2020-07-03 at 3 03 23 PM" src="https://user-images.githubusercontent.com/2678795/86493149-65b1e200-bd3e-11ea-9dfa-64b6731842be.png">

Since there *is* a clear use case for both variants, I kind of think we need a new concept in the template, of a "new default" value, that doesn't count as having provided a value, so can't affect any other logic.

@archmoj @nicolaskruchten @wbrgss thoughts?

**Comment by nicolaskruchten** [comment]
Tangentially related to https://github.com/plotly/plotly.js/issues/4482 I feel?

**Comment by archmoj** [comment]
> Tangentially related to #4482 I feel?

Good call. It seems so.

**Comment by wbrgss** [comment]
I initially understood this issue as affecting the `zerolinecolor` and `linecolor`, but I realize now it affects `gridcolor` as well in a Dash Enterprise product, and this is harder to work around AFAIK.

In a template, we set both the `xaxis` and `yaxis` default `gridcolor`. Before #4904 (`v1.54.4`), axis grid colors were displayed depending on the trace type. For example, scatter plots have both x and y gridlines displayed — but `orientation: 'h'` (horizontal) bar charts only had gridlines displayed on the x-axis, and `orientation: 'v'` (vertical) bar charts only displayed grid lines on the y-axis, etc. This logic applies to many other trace types as well. The advantage is that you can have a universal template, but keep the conditional logic (based on trace type and, in some cases, orientation) for displaying grid lines. I'm not too familiar with where this logic is in the code base  or which traces it applies to.

Here are forks of @alexcjohnson's Codepen above to demonstrate this:

With plotly.js `v1.54.3` — `gridcolor` is specified for both axes in the template
  - https://codepen.io/wbrgss/pen/GRozJza
![image](https://user-images.githubusercontent.com/9068290/88107063-7b177080-cb74-11ea-8906-7d92f519b8f3.png)

With `plotly-latest` (`v1.54.6` at the time of this writing)
  - https://codepen.io/wbrgss/pen/rNxPOVp
![image](https://user-images.githubusercontent.com/9068290/88107291-d9dcea00-cb74-11ea-9c08-6047a1862438.png)

**Comment by nicolaskruchten** [comment]
I'm increasingly thinking that we should revert to the previous behaviour.

**Comment by alexcjohnson** [comment]
I agree - let's revert #4904 and reopen the issues it closed, then we can come back to this when we have more time to develop a full solution for both flavors. I still consider those issues bugs, in as far as there are certain things you can't do with templates and other things that do not behave the same way in the template as they do in layout, but in the short term this fix - that turns out to be incomplete - causes more problems than it solves.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
