### ISSUE TITLE
Horizontal legend disappears depending on length of series names

### ISSUE THREAD

**Issue by fredrikw** [plotly/plotly.js#4986]
I have a graph with a horizontally oriented legend that shows a strange problem. When the total length of the legend is "exactly right" the clip path in the resulting svg gets distorted so that most of the legend is clipped of. See the following CodePen where the first plot is the problematic one. Adding or removing one character in the series names make the legend show correctly as seen in plots two and three. 

https://codepen.io/fredrikwa/pen/NWxYXba

**Comment by fredrikw** [comment]
I created a PR in my fork as per above. Please review and see if it is acceptable.

**Comment by fredrikw** [comment]
Maybe @alexcjohnson or @archmoj would like to look at it?

**Comment by archmoj** [comment]
Looks good. Could you open a PR to plotly.js repo?

**Comment by fredrikw** [comment]
Sure, should I merge in the upstream master first?

**Comment by archmoj** [comment]
No it doesn't look necessary.

**Comment by archmoj** [comment]
@fredrikw 
I didn't notice any difference between the [Before](https://codepen.io/MojtabaSamimi/pen/OJNvZNw) vs [After](https://codepen.io/MojtabaSamimi/pen/rNedveV) codepens using the build from #5139.
Do you see any changes?
If so please mention which operating system and browser you use. 
Thanks!

**Comment by fredrikw** [comment]
Yes, I see a difference, see attachments:
![image](https://user-images.githubusercontent.com/86855/92925531-ee35b880-f43a-11ea-9b3f-a305dfef6678.png)
![image](https://user-images.githubusercontent.com/86855/92925583-fee62e80-f43a-11ea-889d-34472cafce28.png)

I'm using Chrome 85.0.4183.83 on Windows 10

**Comment by archmoj** [comment]
Thanks @fredrikw. 
I confirm the difference is notable using Chrome 85 on Windows 10.

**Comment by archmoj** [comment]
Closed via #5139.
