### ISSUE TITLE
webgl not supported

### ISSUE THREAD

**Issue by danielfrunza** [plotly/plotly.js#4989]
WARN: webgl setup failed possibly due to enabling preserveDrawingBuffer config. The device may not be supported by is-mobile module! Inverting preserveDrawingBuffer option in second attempt to create webgl scene.

The above message is displayed despite that my browser supports WebGL as [here](https://get.webgl.org/)

The environment:
Angular: 9.0.7
PlotlyJS: 1.54.5
Chrome: Version 83.0.4103.116 (Official Build) (64-bit)

Steps to reproduce:
1. create an angular 9 project
2. npm install plotly.js
3. add plotly.min.js in scripts in angular.json:
           `"scripts": [
              "node_modules/plotly.js/dist/plotly.min.js"
            ]`
4. create an angular component and add a [3D surface plot](https://plotly.com/javascript/3d-surface-plots/#surface-plot-with-contours) from docs
5. ng serve --prod

When using the --prod from angular compiler, I think that the already minified plotly.min.js gets bundled and minified in a wrong way. If the angular app is served or build without the '--prod' option everything works as expected.

PS: The last version of Plotly that is still working with --prod flag is 1.41.3

SS without --prod
![plotly2](https://user-images.githubusercontent.com/14039720/86948531-ef561b00-c155-11ea-9141-2aeb0506ed7a.png)

SS with --prod
![plotly1](https://user-images.githubusercontent.com/14039720/86948529-eebd8480-c155-11ea-8c5f-4d9a336f4eb9.png)
![plotly3](https://user-images.githubusercontent.com/14039720/86948532-efeeb180-c155-11ea-9610-cb2de8346b17.png)

**Comment by archmoj** [comment]
@danielfrunza Which browser & OS are you using?

It may be related to https://github.com/gl-vis/gl-plot3d/pull/11 of [v1.42.0](https://github.com/plotly/plotly.js/releases/tag/v1.42.0).

To investigate, you could use `dist/plotly.js` and add 
```js
console.log({
  opts: opts.glOptions, 
  glplot: scene.glplot
});
```
here: https://github.com/plotly/plotly.js/blob/7a274edcf3f4926db69a004899c9181a5d1a0f6c/src/plots/gl3d/scene.js#L153

**Comment by danielfrunza** [comment]
> 
> 
> @danielfrunza Which browser & OS are you using?
> 

Chrome: Version 83.0.4103.116 (Official Build) (64-bit)
Windows 10

**Comment by archmoj** [comment]
> > @danielfrunza Which browser & OS are you using?
> 
> Chrome: Version 83.0.4103.116 (Official Build) (64-bit)
> Windows 10

@danielfrunza and this [demo](https://codepen.io/MojtabaSamimi/pen/yrMxEV?editors=0010) works?

**Comment by danielfrunza** [comment]
if I replace:
angular.json:
"scripts": [ "node_modules/plotly.js/dist/plotly.min.js" ]

with: 
angular.json:
"scripts": [ "node_modules/plotly.js/dist/plotly.js" ]

It works fine! Thanks for advice

**Comment by archmoj** [comment]
> if I replace:
> angular.json:
> "scripts": [ "node_modules/plotly.js/dist/plotly.min.js" ]
> 
> with:
> angular.json:
> "scripts": [ "node_modules/plotly.js/dist/plotly.js" ]
> 
> It works fine! Thanks for advice

@danielfrunza wanna close this issue?
