### ISSUE TITLE
FeatureRequest Trim traces per multiple maxpoints

### ISSUE THREAD

**Issue by ghost** [plotly/plotly.js#4991]
Could you please extend the function to **different** trim length per trace, should be a charm.

https://plotly.com/javascript/plotlyjs-function-reference/#plotlyextendtraces

propose: 
`Plotly.extendTraces(graphDiv, {y: [[rand()], [rand()]]}, [0, 1], 10)`  
to `Plotly.extendTraces(graphDiv, {y: [[rand()], [rand()]]}, [0, 1], [10,3]) ` with first trace maxpoints 10 the latter 3. 

Suggestions?

**Comment by alexcjohnson** [comment]
Seems reasonable. This probably won't be worked on by Plotly folks in the foreseeable future, but we'd happily accept a PR to support this syntax.
