### ISSUE TITLE
Confusion about config.edits.shapePosition vs shapes[].editable

### ISSUE THREAD

**Issue by pfbuxton** [plotly/plotly.js#5006]
Hi,

This example has two shape lines: one red and one blue.

In the dcc.Graph the shapePosition is designated as editable.

The red shape has `editable=True`, but the blue shape has `editable=False`.

I would have expected to be able to only edit the blue shape, but both shapes are editable.

Is this a bug?

```python
import dash
import dash_html_components as html
import dash_core_components as dcc

app = dash.Dash(__name__)

app.layout = html.Div(
    children = [
        dcc.Graph(
            config = dict(edits=dict(shapePosition=True)),
            figure = dict(
                layout = dict(
                    shapes = [
                        dict(  # red shape
                            type = 'line',
                            x0 = 0,
                            y0 = 1,
                            x1 = 1,
                            y1 = 0,
                            xref = 'paper',
                            yref = 'paper',
                            line = dict(color='rgb(255, 0, 0)'),  # red
                            editable = True
                        ),
                        dict(  # blue shape
                            type = 'line',
                            x0 = 0,
                            y0 = 0,
                            x1 = 1,
                            y1 = 1,
                            xref = 'paper',
                            yref = 'paper',
                            line = dict(color='rgb(0, 0, 255)'),  # blue
                            editable = False  # @@@@ This option seems to be ignored @@@@
                        )
                    ]
                )
            )
            
        )
    ]
)

if __name__ == '__main__':
    app.run_server(debug=True)
```

**Comment by alexcjohnson** [comment]
(moved to the plotly.js repo and renamed - thanks for the report @pfbuxton!)

The new `shapes[].editable` attribute is independent of the old `config.edits.shapePosition`, and for backward-compatibility the `config` one still applies to all shapes regardless of `shapes[].editable`. If you remove `config`, only the red shape is editable. @nicolaskruchten we should clarify this in the docs for `config.edits`.

The two modes work rather differently as well - with `config` the shapes are immediately edited by dragging them. But with `shapes[].editable` you need to click a shape to select it first, then you see its anchor points and you can drag them or the whole shape. However two issues to highlight @archmoj:
- With the settings you have here I find it quite difficult to select the shape - the region you have to click is tiny. Can we make both the anchor point selection region and the line selection region bigger?
- If I just try to drag the shape without first selecting it, I instead select all the tick label text. Not a useful behavior. Can we have a drag function as selecting the shape?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
