### ISSUE TITLE
distplot in plotly.js

### ISSUE THREAD

**Issue by CarlosAmaral** [plotly/plotly.js#5007]
I would like to understand if it's possible to plot a dist curve on plotly.js such as in plotly.py https://plotly.com/python/distplot/#plot-only-curve-and-rug since I haven't found anything similar to it on plotly.js.

Thank you for the support!

**Comment by djejaquino** [comment]
@CarlosAmaral have you found a way to achieve that?

**Comment by nhoktenz** [comment]
> I would like to understand if it's possible to plot a dist curve on plotly.js such as in plotly.py https://plotly.com/python/distplot/#plot-only-curve-and-rug since I haven't found anything similar to it on plotly.js.
> 
> Thank you for the support!

Have you found the solution to your question yet? I am looking for this also.
