### ISSUE TITLE
Type definition Plotly.Layout -> modebar 

### ISSUE THREAD

**Issue by pacocom** [plotly/plotly.js#5008]
`"plotly.js": "1.54.6",`

![image](https://user-images.githubusercontent.com/7735329/88169640-9047da00-cc1c-11ea-9bec-6e3c3acd2588.png)

Object literal may only specify known properties, and 'modebar' does not exist in type 'Partial\<Layout\>'.

See https://plotly.com/javascript/reference/#layout-modebar

Thank you for the support!

**Comment by dmyronuk** [comment]
TS definition was fixed here:
[[[Typescript definitions ](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62258/files).](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62258)](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62258)
