### ISSUE TITLE
xaxis for shapes doesn't support Date objects

### ISSUE THREAD

**Issue by cambridgemike** [plotly/plotly.js#501]
even if the xaxis is specified as 'date' type, your shapes must have x-values of millisecond integers, not date objects (unlike plots).

**Comment by etpinard** [comment]
That's correct. 

If I remember correctly, `xaxis.range` and `yaxis.range` need millisecond integers too, That is, they need to be converted with `(new Date(yyyy, mm, dd)).getTime()`.

I agree, this is far from ideal. Thanks for bringing this up.

**Comment by cambridgemike** [comment]
At the least an update to the documentation would have been really helpful
and saved some time debugging.

**Comment by etpinard** [comment]
Agreed.

We should copy some of the info about [axis.range](https://github.com/plotly/plotly.js/blob/d8e27dd33270aa7e4bb01a612cc99c51fa3cb68a/src/components/rangeslider/attributes.js#L41-L46) to the shape [attributes](https://github.com/plotly/plotly.js/blob/d8e27dd33270aa7e4bb01a612cc99c51fa3cb68a/src/components/shapes/attributes.js).

This would be a good oppurtunity for a first-time contributor.

**Comment by cambridgemike** [comment]
haha, fine fine :) I'll send a pull request later today
