### ISSUE TITLE
Disable text selection

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#5021]
It always bugs me that dragging sometimes selects text on our figures in a way that makes it hard to unselect... Should we use https://css-tricks.com/almanac/properties/u/user-select/ for stuff like ticklabels and legends and such? Maybe not annotations or trace data text.

**Comment by Acmion** [comment]
Agree. This should be the default behavior. 

Fortunately, it is easy to add, even if not yet provided by Plotly.
