### ISSUE TITLE
3D Surface Plot - X.Y axis starting from top left

### ISSUE THREAD

**Issue by angieto** [plotly/plotly.js#5024]
Hi,

I wonder if there is a way to show the surface plot in a direction where the x and the y axis start from the top left position.

Attached is my code for the layout setting:
![image](https://user-images.githubusercontent.com/42507452/88604295-0472eb00-d02c-11ea-928d-1f0eb79a9944.png)

A screenshot for current graph's x,y starting position (start from bottom right):
![image](https://user-images.githubusercontent.com/42507452/88604414-32f0c600-d02c-11ea-89b9-c33a45358359.png)

What I want it to be after the change (start from top left):
![image](https://user-images.githubusercontent.com/42507452/88604467-4ef46780-d02c-11ea-897c-941bb8d6407d.png)

Thanks,
Angie

**Comment by mithi** [comment]
It might be nice if you linked to a code pen :)

I played around a bit with a different surface plot.

# Before

<img width="861" alt="Screen Shot 2020-07-30 at 11 36 05 PM" src="https://user-images.githubusercontent.com/1670421/88943388-fa681b00-d2bd-11ea-892f-95f7961bc7b9.png">

# After
<img width="784" alt="Screen Shot 2020-07-30 at 11 36 52 PM" src="https://user-images.githubusercontent.com/1670421/88943414-048a1980-d2be-11ea-958a-c7a00cca6150.png">

**Comment by angieto** [comment]
Hi Mithi,

Thank you for showing me the examples. I got that figured and changed the camera.eye's x and y to 0. It worked!
