### ISSUE TITLE
Plotly runs out of memory while trying to plot

### ISSUE THREAD

**Issue by omerkaramanli** [plotly/plotly.js#5030]
I made a GUI that does some statistical analysis on phylogenetic trees. When 2 nodes selected, it plots a some graphs using Plotly. It was working good until our last tree. When using this tree, it runs out of memory trying to plot the graphs needed.

Here, how it normally works:

![](https://aws1.discourse-cdn.com/business7/uploads/plot/original/2X/4/48b22b334ca1c3f0af62ff7b1624df8dc49521f6.png)

But when we use the tree we want to use, it just gets stuck and after a while, browser warns me that it ran out of memory. The picture shows the stuck screen. Normally, after clicking “select as second node” it automatically does the statistical analysis and plots the graphs.

![](https://aws1.discourse-cdn.com/business7/uploads/plot/original/2X/1/18dbf7d75a3ce9e1af4981a27196ac57cf83d521.png)

In the second tree, as you can see, leaves have a length of 0 from their parents. I thought it might be an issue with them having 0 length but when i checked the testing, we actually selected common ancestor of the nodes as a distance point so the data is not 0 but they are all the same for same node’s leaves. I thought this may be the reason so i made a codepen using my code that plots the charts and used same values to plot. Then it worked. As expected, it just plots a line.
Here is the codepen that works: https://codepen.io/omerkaramanli/pen/MWKBEKX 1

Then i tried using the data that my GUI using to plot the charts. It didn’t work. I made a separate codepen for that.
Here is the codepen that doesn’t work(the actual data that GUI using to plot): https://codepen.io/omerkaramanli/pen/VweBzoZ

Both data have equal amount of points to plot for each part. But difference is, one of them is float and other one is integer. However, the data in the first picture also have only floats and i don’t think that is a problem. However, i couldn’t figure out what is the problem. Can you help me figure out the problem?

**Comment by dheeraj-murali** [comment]
We are also facing a similar issue while trying to render a violin plot with a large decimal value just like the example(https://codepen.io/omerkaramanli/pen/VweBzoZ) you have provided. As a workaround, changing the inputs to integer seems to be working, but it impacts our data accuracy.

@omerkaramanli have you found any solution to your issue?

**Comment by kurtlawrence** [comment]
I am also running into a similar issue as @dheeraj-murali.
The plot does not work with decimal inputs, but if I truncate the numbers, the plots would display.
I was plotting 15 traces of 300 observations.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
