### ISSUE TITLE
Custom Partial Bundle - Scatter3d - Not working.

### ISSUE THREAD

**Issue by mithi** [plotly/plotly.js#5031]
I'm trying to load my own custom partial bundle, because I only need the Scatter3d but was not successful. There might be a bug which might be related to issue https://github.com/plotly/plotly.js/issues/4891

Here's the code sandbox link and screenshot.
- https://codesandbox.io/s/proud-dawn-i907r?file=/src/App.js:183-206

<img width="1280" alt="Screen Shot 2020-07-30 at 7 37 51 PM" src="https://user-images.githubusercontent.com/1670421/88920351-43f53d80-d29f-11ea-89ff-8371ee125566.png">

I found these related issues to help me with this
- https://github.com/plotly/plotly.js/issues/4883 (How to reduce bundle size of Plotly.js for 3D surface chart?)
- https://github.com/plotly/plotly.js/issues/4891 (no calendar on partial bundles)

# Here's the sandbox of my actual project which is working fine currently because i'm using the partial bundle made by plotly (OK):
- https://codesandbox.io/s/nervous-water-7rwhh?file=/src/components/HexapodPlot.js
<img width="1280" alt="Screen Shot 2020-07-30 at 9 15 26 PM" src="https://user-images.githubusercontent.com/1670421/88927373-e2869c00-d2a9-11ea-8168-7c8e95cb441e.png">

# Here's the sandbox where I'm using a custom partial bundle (NOT OK)
- https://codesandbox.io/s/patient-rgb-knowb?file=/src/components/CustomPlot.js

<img width="1280" alt="Screen Shot 2020-07-30 at 9 21 25 PM" src="https://user-images.githubusercontent.com/1670421/88927867-a7d13380-d2aa-11ea-8588-2cce13faed40.png">

#  This is the only difference between the two:
- https://github.com/mithi/hexapod/blob/custom-plotly-bundle-error/src/components/CustomPlot.js
- https://github.com/mithi/hexapod/blob/custom-plotly-bundle-error/src/components/HexapodPlot.js
```js
import Plotly from "plotly.js/lib/core";
import Scatter3d from "plotly.js/lib/scatter3d"
import createPlotlyComponent from "react-plotly.js/factory";
Plotly.register([Scatter3d]);

const CustomPlotly = createPlotlyComponent(Plotly);
export default CustomPlotly;
```

# Console log errors when running on local

```
react_devtools_backend.js:2273 WARN: webgl setup failed possibly due to enabling preserveDrawingBuffer config. 
The device may not be supported by is-mobile module! 
Inverting preserveDrawingBuffer option in second attempt to create webgl scene.
```

On  Chrome `Version 84.0.4147.89 (Official Build) (64-bit)`, MacBook Pro (Retina, 13-inch, Mid 2014)
MacOs Catalina 10.15.5
<img width="1276" alt="Screen Shot 2020-07-30 at 8 38 59 PM" src="https://user-images.githubusercontent.com/1670421/88924007-2f1ba880-d2a5-11ea-8d61-e024ae49c6b5.png">

Also happens on firefox 78.0.2 (64-bit)

<img width="1277" alt="Screen Shot 2020-07-30 at 8 41 42 PM" src="https://user-images.githubusercontent.com/1670421/88924107-5c685680-d2a5-11ea-926b-c3f74268dc2e.png">

# Additional info # 1
I experimented with  https://github.com/mithi/plotly-webpack 
and was somewhat successful (but wasn't able to load the paper background)... the paper background wasnt working...
I found out that I can reproduce my plot having only a gzipped bundle size of `~410kb`, which is significantly lower than when using `plotly.js-gl3d-dist-min` which has a gzipped bundle size of `~450kb`

<img width="1280" alt="Screen Shot 2020-07-30 at 8 13 47 PM" src="https://user-images.githubusercontent.com/1670421/88921552-53758600-d2a1-11ea-9216-c340f8eebd75.png">

# Additional info # 2

Importing all the requirements here https://github.com/plotly/plotly.js/blob/master/lib/index-gl3d.js

```
    require('./scatter3d'),
    require('./surface'),
    require('./mesh3d'),
    require('./isosurface'),
    require('./volume'),
    require('./cone'),
    require('./streamtube')
```
produces the same error discussed above ... while Commenting out `Plotly.register([Scatter3d]);` Will remove the error and  produce the following

<img width="1280" alt="Screen Shot 2020-07-30 at 8 21 02 PM" src="https://user-images.githubusercontent.com/1670421/88922156-502eca00-d2a2-11ea-95aa-88467a35fcc1.png">

I also saw this issue which might be related https://github.com/plotly/plotly.js/issues/4989
But i don't know how to fix it in my case. 

Any help is appreciated! Thanks!

**Comment by mithi** [comment]
Need to add ify
- https://github.com/mattcorner/plotly-surface-connectgaps-error/blob/master/config-overrides.js
- https://github.com/plotly/plotly.js/issues/2502

Still isnt 100 percent okay, background still doesn't show up.

<img width="967" alt="Screen Shot 2020-07-31 at 12 19 59 AM" src="https://user-images.githubusercontent.com/1670421/88947857-be37b900-d2c3-11ea-9451-1edd031bedcb.png">

**Comment by mithi** [comment]
Background is now showing, I just needed to include `mesh3d` for the paper background to show


```
import Plotly from "plotly.js/lib/core";
import Scatter3d from "plotly.js/lib/scatter3d"
import Mesh3d from "plotly.js/lib/mesh3d"

import createPlotlyComponent from "react-plotly.js/factory";
Plotly.register([Scatter3d, Mesh3d]);

const CustomPlotly = createPlotlyComponent(Plotly);
export default CustomPlotly;
```

<img width="966" alt="Screen Shot 2020-07-31 at 12 37 27 AM" src="https://user-images.githubusercontent.com/1670421/88949869-6b133580-d2c6-11ea-9e51-c070463e3994.png">

**Comment by archmoj** [comment]
Thanks very much @mithi for the updates.
Also please consider submitting a PR here or to https://github.com/plotly/plotly-webpack,
if you think it should be updated considering latest dependency changes.
