### ISSUE TITLE
Features for financial analysis: Add opacity (transparency) to hover box / Allow it to be outside the plot / Increase its gap / hover information solely on the x and y axes 

### ISSUE THREAD

**Issue by GitHunter0** [plotly/plotly.js#5036]
Plotly hover box has no transparency to it, which causes it to cover other data points, compromising the visual analysis of the data. Example:
![git1](https://user-images.githubusercontent.com/26294221/89054094-9fbad780-d32e-11ea-8583-5cfb83991334.png)

Ideally it would allow box transparency like these one from dygraphs, which displays the hover text but does not cover/hide the region beneath it (http://dygraphs.com/tests/legend-values.html)
![git_dy1](https://user-images.githubusercontent.com/26294221/89054126-afd2b700-d32e-11ea-8e78-f92bcecfa088.png)

Same with Highcharts (https://www.highcharts.com/demo/line-time-series/sand-signika):
![Highcharts](https://user-images.githubusercontent.com/26294221/89054200-cf69df80-d32e-11ea-87e5-032d8a954a41.png)

Additionaly, it would be great to have the possibility to show the tooltip/hover box information outside the plot, again to not cover any part of the plot and enable clear visual inspection. Another example from dygraphs:
![image](https://user-images.githubusercontent.com/26294221/88964998-7f344400-d280-11ea-8e3c-90fa3536108e.png)

Lastly, adding more horizontal gap space between the point and its hover box would also facilitate the visual inspection.
C3 example (https://cran.r-project.org/web/packages/c3/vignettes/examples.html):
![image](https://user-images.githubusercontent.com/26294221/89054370-0e983080-d32f-11ea-9854-81264717cbef.png)

Highcharts, dygraphs and C3 have those options as default. 

Related discussions/requests: 
https://community.plotly.com/t/custom-hovertext-obstructs-plot-view-opacity-bottom-of-plot/9065
This one addresses another related common request for finance, which is to display hover information solely on the x and y axes (like https://www.tradingview.com/chart Chart tool)
https://stackoverflow.com/questions/61794582/plotly-how-to-only-show-vertical-and-horizontal-line-crosshair-as-hoverinfo
![oaF1I](https://user-images.githubusercontent.com/26294221/89080232-b0834180-d35e-11ea-8e3a-1a7628efa224.gif)

Changes like these would allow Plotly to be an excellent tool for financial plots and to be adopted by many more analysts from finance field.

Plotly is the best graphing tool in my opinion and I would like to stick to it, so I really appreciate if you can consider this request. 
Thank you for the awesome work.

**Comment by nicolaskruchten** [comment]
These are good ideas in general, and we'd be happy to work with someone who wants to implement these changes :)

**Comment by GitHunter0** [comment]
Thank you @nicolaskruchten , I really don't have the knowledge at the moment to implement those ideas. But I hope in the future I have, because those features are the ones that I most miss in plotly. With them, I believe plotly should no doubt be the go to choice tool for graphing.

**Comment by nicolaskruchten** [comment]
I'll merge this into https://github.com/plotly/plotly.js/issues/2342 and close.
