### ISSUE TITLE
layout.transition.duration prevents layout.title.text changes

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#5037]
in this pen: https://codepen.io/nicolaskruchten/pen/gOPVgRe?editors=0010

newPlot@0, react@1 ... the title does not change but should. comment out layout.transition.duration and it works.

**Comment by nicolaskruchten** [comment]
This may or may not be a separate issue but it looks related... In this pen, I would expect the category order to change, but it doesn't: https://codepen.io/nicolaskruchten/pen/wvMVgrE?editors=0010

**Comment by archmoj** [comment]
Thanks for the report.
It is also a problem for axis titles | [demo](https://codepen.io/MojtabaSamimi/pen/JjXjPjv?editors=0010)
