### ISSUE TITLE
"nearly linear" lines in scattergl plot appear transparent if there are more than 50000 points

### ISSUE THREAD

**Issue by michaelbabyn** [plotly/plotly.js#5046]
See [this codepen](https://codepen.io/plotly/pen/xxVxwQw) for an example.
![nearly-linear-scattergl](https://user-images.githubusercontent.com/41019918/89344182-7aea9b00-d673-11ea-9ddf-359cc617fde0.png)

**Comment by archmoj** [comment]
Thanks for the report.
While your example does not have any markers and point clustering is enabled over 50K points,
wondering if adding markers similar to this [demo](https://codepen.io/MojtabaSamimi/pen/dyMyGGR) may help?

**Comment by michaelbabyn** [comment]
thanks @archmoj , I think that makes sense for this use-case. I'll close this issue
