### ISSUE TITLE
Rotating group names in grouped bar chart

### ISSUE THREAD

**Issue by appukuttan-shailesh** [plotly/plotly.js#5054]
I am using a grouped bar chart. A simplified example is shown here:
https://codepen.io/Shailesh2020/pen/WNwbyGN

The number of entries varies, and often can be large.
This causes the group headings (e.g. "Model1", "Model2") to overlap as they are all being displayed horizontally.
The tick labels seem to auto-rotate when there are many entries, but this does not rotate the group titles.

I have tried using 'tickangle' and 'textangle', but they don't affect the group titles.
I have checked the docs and forms and there doesn't seem to be any discussion related to this.

Is this possible to do in plotly.js?

**Comment by appukuttan-shailesh** [comment]
p.s. I had posted this on https://community.plotly.com/, and got no responses.
Is rotating group names in a grouped bar chart a non-trivial thing to do with Plotly?

**Comment by nicolaskruchten** [comment]
Unfortunately, the second level of tick labels cannot be rotated at this time. The best workaround I can offer you at the moment would be to use a horizontal bar chart.

**Comment by appukuttan-shailesh** [comment]
Thanks for your reply @nicolaskruchten . 
Would it be possible for you to guide me where in the source files I might be able to change things around to alter this (if at all possible).

**Comment by appukuttan-shailesh** [comment]
I was wondering if there is some work around to my original problem?

Is it possible to have ellipsis to shorten the text? The problem with trying to do this manually (cropping the length) is that the cropping can result in different labels being converted to identical representations (e.g. [LongText_Model_A, LongText_Model_B] -> [LongText_Mo, LongText_Mo] based on the cropping length. As it has to serve a large variety of inputs, it is difficult to hard code such a value.
