### ISSUE TITLE
Base attribute bug 

### ISSUE THREAD

**Issue by skrobec** [plotly/plotly.js#5057]
I have tried to make simple timeline with the help of base attribute. Run into problem with low x values. If x is lower than 10000 ms, plot breaks as seen in example. With values higher than 10s, plot works as expected.  Possible bug, thanks for help or maybe explanation if i am doing something wrong. 

Codepen - https://codepen.io/kristi-n-krob-nek/pen/dyMoKNJ

Also tried to look for similar issue before posting, but found nothing close to this problem.

**Comment by nicolaskruchten** [comment]
This has been reported in Plotly.py as well, https://github.com/plotly/plotly.py/issues/2658

Indeed this seems like a bug.

**Comment by archmoj** [comment]
The problem appears within the range of positive and negative 10000 ms. 
@skrobec Could you please confirm?

**Comment by archmoj** [comment]
After some investigation, the issue appears not to be related to bars and bases.
Instead the way the dates are handled is rather confusing.
Please see this [demo](https://codepen.io/MojtabaSamimi/pen/ZEWGgrZ).
Should we handle case of `2000` as 2000 years or 2000 milliseconds?

**Comment by skrobec** [comment]
> The problem appears within the range of positive and negative 10000 ms.
> @skrobec Could you please confirm?

Yes, so it seems.

> After some investigation, the issue appears not to be related to bars and bases.
> Instead the way the dates are handled is rather confusing.
> Please see this [demo](https://codepen.io/MojtabaSamimi/pen/ZEWGgrZ).
> Should we handle case of `2000` as 2000 years or 2000 milliseconds?

It would make sense that number type should be taken as milliseconds. Years and other types should be specified as string in my opinion.
