### ISSUE TITLE
bar widths on categorical axes when barmode=overlay

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#5058]
In this pen https://codepen.io/nicolaskruchten/pen/yLONGKZ the orange bars should be the same width as the blue ones.

Ref https://github.com/plotly/plotly.py/issues/2684

**Comment by alexcjohnson** [comment]
Related: #1181

**Comment by nicolaskruchten** [comment]
Indeed @alexcjohnson ... I believe this is a bug and doesn't need to wait until 2.0.
