### ISSUE TITLE
negative sign on zero percent

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#5069]
This pen https://codepen.io/nicolaskruchten/pen/GRZoRxV?editors=0010 shows the issue raised in https://community.plotly.com/t/yaxis-labeling-0-as-negative/32227 ... couldn't find an existing duplicate. Seems distinct from https://github.com/plotly/plotly.js/issues/3814 which actually looks far worse (set `tickformat: "p"` for a laugh)

**Comment by archmoj** [comment]
It could be fixed if we try upgrading d3-format | [Demo](https://codepen.io/MojtabaSamimi/pen/XWdXWOq?editors=0010).

**Comment by nicolaskruchten** [comment]
yeah that's what I figured.
