### ISSUE TITLE
Clean unneeded and deprecated dependencies

### ISSUE THREAD

**Issue by Lectem** [plotly/plotly.js#5077]
Due to some packages such as regl/splom, plotly.js makes us download/use uneeded and deprecated dependencies such as `left-pad` while they are not even needed. (See https://github.com/gl-vis/regl-splom/pull/18)

When installing through npm I get the following warnings:

> npm WARN deprecated os-homedir@2.0.0: This is not needed anymore. Use `require('os').homedir()` instead.
> npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()

I think it would do good to the project to clean such dependencies.

**Comment by archmoj** [comment]
Addressed by https://github.com/plotly/plotly.js/pull/5084.
