### ISSUE TITLE
Read attributes.js info from NodeJs app

### ISSUE THREAD

**Issue by bartbutenaers** [plotly/plotly.js#5087]
Hi all,
Thanks for sharing this amazing library!
We need the information from the _**attributes.js**_ file (e.g. [this ](https://github.com/plotly/plotly.js/blob/master/src/traces/scatter/attributes.js)one for the scatter trace), to use it via autocomplete in our open-source application.

Do you have any advice on how to do this?
We have tried this:
1. We do `npm install plotly.js` because the other plotly npm packages seem not to have the attributes information.
2. We then call `require("C:\Users\admin\.node-red\node_modules\plotly.js\src\traces\scatter\attributes.js");` as a simple test.
3. But then we get _**Uncaught ReferenceError: window is not defined**_ because we are in NodeJs (instead of in a browser):

   ![image](https://user-images.githubusercontent.com/14224149/90604067-92da2700-e1fc-11ea-8343-52f707333254.png)

Does anybody knows a better way to achieve this?
Thanks a lot !!
Bart

**Comment by nicolaskruchten** [comment]
Your best bet would be to load the static JSON file that captures all that information, actually: https://github.com/plotly/plotly.js/blob/master/dist/plot-schema.json

Would that meet your needs?

**Comment by bartbutenaers** [comment]
Hi Nicolas,
that is perfect for my use case.  Thanks!!
Bart
