### ISSUE TITLE
Multiple legends: trace.legend and layout.legend<N>

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#5098]
Breaking off of https://github.com/plotly/plotly.js/issues/1668 ...

Multiple users have requested what amounts to the ability to have multiple legends, **within the current concept** of "each trace has a single legend item which appears in a single legend". This could be implemented by adding a `legend` attribute to each trace that would operate similarly to the `xaxis` attribute, and a corresponding `legend2`, `legend3` series of attributes in the `layout`. This is **distinct from** the idea of [having a legend for size and one for symbol etc](https://github.com/plotly/plotly.js/issues/5099), as in that case each item would refer to multiple traces, and each trace would be represented by multiple items.

The major challenge here is the default positioning of `legend2` if present... we could do something really ugly like just having it default to the position of the first legend and forcing users to position them manually, but having it "stick to the bottom" is probably a much more graceful solution, if more complex to implement.

**Comment by nicolaskruchten** [comment]
It's a good feature and we'd love to have it in the library but it's not on anyone's roadmap at the moment as far as I know. That said, we as maintainers would be happy to [help someone from the community to implement it in Plotly.js](https://github.com/plotly/plotly.js/blob/master/CONTRIBUTING.md), or to [accept sponsorship](https://plot.ly/products/consulting-and-oem/) to get it on to our short-term roadmap :)

**Comment by nicolaskruchten** [comment]
This issue has been tagged with `NEEDS SPON$OR`

A [community PR](https://github.com/plotly/plotly.js/pulls?q=is%3Apr+is%3Aopen+label%3A%22type%3A+community%22) for this feature would certainly be welcome, but our experience is deeper features like this are difficult to complete without the Plotly maintainers leading the effort.

**Sponsorship range: $10k-$15k**

What Sponsorship includes:
- Completion of this feature to the Sponsor's satisfaction, in a manner coherent with the rest of the Plotly.js library and API
- Tests for this feature
- Long-term support (continued support of this feature in the latest version of Plotly.js)
- Documentation at [plotly.com/javascript](https://plotly.com/javascript/)
- Possibility of integrating this feature with Plotly Graphing Libraries (Python, R, F#, Julia, MATLAB, etc)
- Possibility of integrating this feature with Dash
- Feature announcement on [community.plotly.com](https://community.plotly.com/tag/announcements) with shout out to Sponsor (or can remain anonymous)
- Gratification of advancing the world's most downloaded, interactive scientific graphing libraries (>50M downloads across supported languages)

Please include the link to this issue when [contacting us](https://plotly.com/get-pricing/) to discuss.

**Comment by Episkiliski** [comment]
Any plan to work on this issue?

**Comment by nicolaskruchten** [comment]
We'd love to, given a sponsor :)

**Comment by seungy0** [comment]
Is this going on right now?

**Comment by nicolaskruchten** [comment]
We're still looking for a sponsor, and will update this issue when we find one :)
