### ISSUE TITLE
Step chart

### ISSUE THREAD

**Issue by ni-hil** [plotly/plotly.js#51]
Any thoughts on implementing a "step mode" for the scatter trace? 

I thinks the need to display stepped data is quite frequent (to display error count over time for example). Doing it by programatically adding fake points at the bottom of the step is the only workaround I thought about and it doesn't sound like a great way to do it.

Here is what I mean by step chart:
![step chart](https://cloud.githubusercontent.com/assets/2896648/11484930/dbc67b08-977e-11e5-8b34-cbaa27a1e689.png)

(Source: http://www.highcharts.com/stock/demo/step-line)
Sorry about linking them here, but in fact quite a lot of others charting library also support this.

**Comment by etpinard** [comment]
Try https://plot.ly/~chelsea_lyn/8766.js

![image](https://plot.ly/~chelsea_lyn/8766.png)

**Comment by ni-hil** [comment]
Oh, I missed this parameter in the doc. And since I couldn't find any example of this...

 Thanks, that's exactly what I needed!
