### ISSUE TITLE
Margins not updating correctly with rangeslider and changed tick angle

### ISSUE THREAD

**Issue by penguindustin** [plotly/plotly.js#5102]
With large `tickangle` value the range slider gets obscured/not drawn even if you have `automargin` set to `true`. 

https://codepen.io/penguindustin/pen/QWNpObv
<img width="1633" alt="Screen Shot 2020-08-25 at 11 44 06 AM" src="https://user-images.githubusercontent.com/1649836/91214707-5446df80-e6c8-11ea-8b47-90021cfaaeac.png">

https://codepen.io/penguindustin/pen/GRZWOpJ
<img width="1645" alt="Screen Shot 2020-08-25 at 11 44 12 AM" src="https://user-images.githubusercontent.com/1649836/91214939-a38d1000-e6c8-11ea-8e85-89db92c0cf28.png">

I think the margins aren't considering both the tick angle and the added rangeslider but i'm not an expert at formatting the plot area in plotly.

**Comment by archmoj** [comment]
Thanks this is now fixed in [v1.58.0](https://github.com/plotly/plotly.js/releases/tag/v1.58.0) by #5237.
