### ISSUE TITLE
Sankey: need a way to set the values (sizes) of initial nodes

### ISSUE THREAD

**Issue by codekitchen** [plotly/plotly.js#5105]
See codepen: https://codepen.io/codekitchen/pen/yLObERa

Because values are only defined on links, not nodes, there's no way to describe the sizes of initial nodes -- they always have the same size as the total of their outputs. On subsequent nodes this isn't a problem, and you can have nodes where some of their value gets "dropped" and don't progress to further nodes. This is really a visual issue, since of course you can still hover over the nodes and links and see the "correct" values, but we've had problems with our users finding it misleading.

We can get around this by defining a "start" state so that your initial nodes have incoming links from that start state, but in our actual application graph that has 4-5 layers of 4-5 nodes each, adding another big "start" layer really makes it look too busy.

It'd be really nice if you could either (a) define links from some null "source" node to the initial nodes so that their size can be different than the sum of their outputs or (b) directly define the size of these initial nodes (and probably all nodes just for consistency).

**Comment by ese-jdm418** [comment]
Hi there,

Has this been sorted as I am wanting to represent some stocks and flows data and would really like to be able to either change the size of nodes(maybe width as height represents the flow input/output) to represent the size of a stock and add a label to the node to put the actual stock value on it without having to hover over the top.

John.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson

**Comment by ink-github** [comment]
Hi, 

I'm using Plotly version 4.10.4 in R, and the only way (that I've found) to adjust node height is to modify the width of links. An additional argument to set node height and width manually would be much appreciated.
