### ISSUE TITLE
Overlapping 3D axes labels

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#511]
reposted from http://community.plot.ly/t/axes-labels-overlapping-on-3d-surface-plot/859

> I was wondering if there is a way to offset axis labels for 3D plots so that they don't overlap the ticks? This seems to be because the text is set to centre justification and the centre point is too close to the axis when the label is not parallel with its axis. Maybe there's a way to get the text to always remain parallel with its axis? [This](Example Project6) is the project where this is an issue.

**Comment by mraxilus** [comment]
I too would like this behaviour. It seems rather cluttered to have them crossing over. For me, if the axis label is any longer than about 9 characters they cross in nearly all orientations.

**Comment by alexcjohnson** [comment]
merging into #3077
