### ISSUE TITLE
X-Axis spacing is different when having one extra line+marker in bar chart.

### ISSUE THREAD

**Issue by SAnbumannan** [plotly/plotly.js#5120]
When I have two traces the x-axis margin is proper.
https://codepen.io/anbumannan-s/pen/WNwZVRG

For the same plotData, with an extra trace; the x-axis margins are weird.
https://codepen.io/anbumannan-s/pen/LYNxQmM

Because of this when I render charts using plotly in my app, the space taken by x-axis is different.
Note: The x-axis tick labels are same all the times, but the spacing is different.

**Comment by alexcjohnson** [comment]
We add some padding around scatter markers, and in this case that padding extends the x axis range past zero. You can fix this with `rangemode: 'nonnegative'` or `rangemode: 'tozero'` (which are only different if you ever add *data values* that go past zero)

https://codepen.io/alexcjohnson/pen/eYZeJQK?editors=0010

This kind of question is a better fit for https://community.plotly.com/ - we try to reserve github for bug reports and feature requests.
