### ISSUE TITLE
Pie show incorrect value (in scientific format) when hovered over

### ISSUE THREAD

**Issue by chiehrosswang** [plotly/plotly.js#5122]
I am working with some large numbers in pie charts.  I came across some incorrect values in scientific format.  The value of L1 should be 3.31E+10 but it's showing 3.31E+1.  Same error is seen in L2.

![image](https://user-images.githubusercontent.com/15328803/92141829-fa899800-ede0-11ea-9cec-1346ac5c961c.png)

Below is a snip of the code and here is a working example: [http://jsfiddle.net/3u05bo89/12/](http://jsfiddle.net/3u05bo89/12/).  
```
var data = [{
  values: [33103474584, 58115093734, 123036969165],
  labels: ['L1', 'L2', 'L3'],
  type: 'pie',
  hoverinfo: 'label+value+percent'
}];

var data = [{
  values: [33103474584, 58115093734, 123036969165],
  labels: ['L1', 'L2', 'L3'],
  type: 'pie',
  hoverinfo: 'label+value+percent'
}];

var layout = {
  height: 400,
  width: 400,
	title:"Test Piechart"
};

Plotly.newPlot('myDiv1', data, layout);
```

**Comment by alexcjohnson** [comment]
Nice catch @chiehrosswang! Looks to me as though we're stripping trailing zeros - on the assumption that they're coming after a decimal point, but in this case the zero is in the exponent instead 🤦

**Comment by chiehrosswang** [comment]
Thanks @alexcjohnson that makes sense 😄
