### ISSUE TITLE
Unable to set xaxis/yaxis titles (or pre-set defaults if editable)

### ISSUE THREAD

**Issue by esternin** [plotly/plotly.js#5130]
Please, help! Not sure if this is a bug or my own stupidity.

I am trying to implement control of the axes' labels from the web page input fields, but allow the user to override them directly on the graph.  The layout object seems to be created properly, like this:

```
var layout = {
    autosize: true,
    type: 'scatter',
    xaxis: {title: {text: document.getElementById('xaxislabel').value, font: {size: 18}} },
    yaxis: {title: {text: document.getElementById('yaxislabel').value, font: {size: 18}} },
    title: {text: document.getElementById('titletext').value, font: {size: 24}, xref: 'paper', x: 0.05} 
    };

console.log(Plotly.version);
console.log(layout.xaxis,layout.title);

Plotly.newPlot( g, [{  // trace 0
        x: xvalues,
        y: yvalues,
        name: 'data',
        mode: 'markers',
        }], layout, {editable: true, responsive: true, scrollZoom: true}
   );
```
The console shows that the layout settings seem to have been recognised, for both the title and the xaxis.title:
```
1.55.1
{text: "X-axis label", font: {…}}
     autorange: true
   > font: {size: 18}
   > range: (2) [-0.44220100045475225, 7.242201000454752]
     text: "X-axis label"
     type: "linear"
   > __proto__: Object 

{text: "Graph Title", font: {…}, xref: "paper", x: 0.05}
   > font: {size: 24}
     text: "Graph Title"
     x: 0.05
     xref: "paper"
   > __proto__: Object
```
The title string works as it should, but the axes' titles always show the gray "Click to enter X[orY] axis title".  If I set `editable: false` the axes' titles are blank.  They always show up as blank in any of the snapshot formats (.png, .jpeg, .svg).

You can see this in action [here](https://www.physics.brocku.ca/Labs/ioLab/), just press "load example".  One can control the strings under "Settings", but only Title is working.  I include a snapshot.

![newplot](https://user-images.githubusercontent.com/29458452/92318295-09866b00-efd8-11ea-9bd4-ea0203a53447.png)

**Comment by esternin** [comment]
Figured it out.  Turns out, at a later point I was issuing this call
```
if (document.getElementById('SET_XLOG').checked)  // log axes?
   Plotly.relayout( g, { xaxis: {type: 'log'} } );
else
   Plotly.relayout( g, { xaxis: {type: 'linear'} } );
```
adjusting the axis type.  I assumed that this setting will be **appended** to the previously-made layout controls, i.e. will change just this setting, but is **replaced** them, which meant that all layout values not specified in this re-layout call were re-set to defaults.

Not sure if this is a bug or a design feature, so will leave this open for a while.  If this is by design, feel free to close this issue.

**Comment by esternin** [comment]
Interesting, if I change the format of the re-layout structure in the second call to this: 
```
if (document.getElementById('SET_XLOG').checked)  // log axes?
   Plotly.relayout( g, { 'xaxis.type': 'log' } );
else
   Plotly.relayout( g, { 'xaxis.type': 'linear' } );
```
everything works as expected.  Would have never guessed.

If this is not a bug, it's a misfeature, IMHO.

**Comment by alexcjohnson** [comment]
Good or bad design, you're correct in your interpretation and this is as designed: if you just want to modify a small part, make an attribute path `'xaxis.type': 'log'` rather than a nested object `xaxis: {type: 'log'}`. If we had made nested objects append, it would be very difficult to delete items from a container.

I'd encourage you to explore `Plotly.react` instead of `Plotly.relayout` - this form requires passing in the entire graph spec again - which you can get by pulling out `g.data` and `g.layout` and then modifying them to your liking. This avoids a lot of the confusion generated by `Plotly.relayout` and `Plotly.restyle` all while enabling much more flexible modifications to the graph.
