### ISSUE TITLE
[Feature request] Add `x` and `y` attributes to the `Image` trace

### ISSUE THREAD

**Issue by emmanuelle** [plotly/plotly.js#5137]
This would be convenient in particular when passing xarrays (data arrays with coordinates) to `px.imshow` in Python.

One can probably reuse some of the `Heatmap` code since the `Heatmap` trace has `x` and `y` attributes.

**Comment by antoinerg** [comment]
If I remember correctly, we decided at some point that an image would always be a rectangle. This rectangle can then be positioned on the Cartesian coordinate system via a combination of `x0` and `y0` (to set the position of a corner) as well as `dx` and `dy` to set the size of a pixel in data units. This is essentially equivalent to defining `x` and `y` as arrays that are linearly increasing.

> Add `x` and `y` attributes to the `Image` trace
> This would be convenient in particular when passing xarrays (data arrays with coordinates) to px.imshow in Python.

@emmanuelle can you confirm that what you are trying to achieve cannot be done via `x0`, `y0`, `dx` and `dy`? Also, why not simply use `heatmap`?

**Comment by emmanuelle** [comment]
@antoinerg hum I had forgotten once again about `x0`, `y0` and `dx` and `dy`. Let me check, thanks!

**Comment by emmanuelle** [comment]
It works, thanks @antoinerg ! Closing the issue.

**Comment by emmanuelle** [comment]
Just one thing @antoinerg : is there any way to use `x0` and `dx` to pass dates? It works with dates converted to seconds but if the other axis is not a date this results in a very flat image...

**Comment by archmoj** [comment]
@emmanuelle 
Is that a bug? If so Could you provide a codepen?

**Comment by nicolaskruchten** [comment]
Not a bug, just a known limitation :)

**Comment by emmanuelle** [comment]
Closing in favor of #5141.
