### ISSUE TITLE
annotations for mapbox subplots

### ISSUE THREAD

**Issue by ougx** [plotly/plotly.js#5142]
When it is regular layout it works (see code below).

```
dcc.Graph(
    id='map',
    figure=dict(
        data=[
            go.Scatter( ... )
        ],
        layout=dict(
            # mapbox=dict(
            #     style='white-bg',
            #     center={'lat':42, 'lon':-97},
            #     zoom=6
            # ),
            annotations=[
                dict(
                    x=-96,
                    y=43,
                    xref='x',
                    yref='y',
                    ax=30,
                    ay=30,
                    text='here',
                    showarrow=True,
                )
            ]
        )
    )
)
```
But if you uncomment the `mapbox` section and change `go.Scatter` to `go.Scattermapbox` it will always add the annotation to the center of the view and is stagnant even when you move the map.

-  replace the result of `pip list | grep dash` below
```
dash                          1.14.0
dash-bootstrap-components     0.10.5
dash-core-components          1.10.2
dash-defer-js-import          0.0.2
dash-html-components          1.0.3
dash-renderer                 1.6.0
dash-split-pane               1.0.0
dash-table                    4.9.0
django-plotly-dash            1.4.2
```

**Expected behavior**

Mapbox annotations act the same as for regular layouts.

**Comment by nicolaskruchten** [comment]
This is more of a known scope limitation/feature-request than a bug... `layout.annotations` only work in `paper` or 2d-cartesian coordinates today. We would need to add something like `mapxbox1` to the possible accepted values of `xref` and `yref` to make this work, and it would need to be deeply integrated into our Mapbox code, which is a bit of a project :)

**Comment by Ture2019** [comment]
Very well its a feature not a bug. Where is the upvote button. How many years does the python community need to wait for an easy to use python library to be able to easily draw on a map? Plotly is our best shot. And annotations are essential!

**Comment by nicolaskruchten** [comment]
We'd be happy to work with anyone who wants to help contribute such a feature instead of "waiting" :)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson

**Comment by CmpCtrl** [comment]
yea jeesh, i spent a ton of time arguing with claude before realizing this just doesn't work. it seems so obvious that it should and that it would be extremely useful for anyone who uses maps. i was testing with plotly 6.1.1 and the `scattermap`.
