### ISSUE TITLE
Indicator: Show both, relative and absolute difference

### ISSUE THREAD

**Issue by nlichtenberg** [plotly/plotly.js#5148]
Is it possible to show both, relative and absolute difference in an indicator's delta tag?
For the moment, I have a local solution, but it is not backwards compatible:

I went into plotly-finance.js and before the line

```
return (value > 0 ? trace.delta.increasing.symbol : trace.delta.decreasing.symbol) + numberFmt(value); //(inside the `drawDelta()`-function)
```

I added
```
if(trace.delta.deltatag == 'both')
 return (value > 0 ? trace.delta.increasing.symbol : trace.delta.decreasing.symbol) + deltaFmtRel(cd[0].relativeDelta) + " / " + deltaFmtAbs(cd[0].delta);
```
with additional functions
```        
var deltaFmtAbs = function(v) { 
		    var tmpAx = deltaAx;
			tmpAx.tickformat = '';
			return Axes.tickText(tmpAx, v).text;
		};

var deltaFmtRel = function(v) { 
		    var tmpAx = deltaAx;
			tmpAx.tickformat = '2%';
			return Axes.tickText(tmpAx, v).text;
		};
```

In the `module.exports` I replaced the `delta.relative `property with
```
delta: {
...
        deltatag: {
          valType: 'enumerated',
          values: ['absolute', 'relative', 'both'],
          editType: 'plot',

          dflt: 'absolute',
...
}
```
Occurences of `trace.delta.relative ?` have been replaced by `trace.delta.deltatag == 'relative' ?`

The result looks like this:
![image](https://user-images.githubusercontent.com/2855519/93099361-39a0ce80-f6a8-11ea-8600-4e334447fcc8.png)

I do not know how to do this backwards-compatible, because the "relative" property is a boolean and the relative+absolute difference tag would be a third option. Also, I'm not sure how to get the format correct (see the functions `deltaFmtRel` and `deltaFmtAbs`.

Regards
Nils

**Comment by archmoj** [comment]
You could start by changing the `valType` of `relative` attribute from `boolean` to `enumerated`.
And provide the third option something like:
```js
valType: 'enumerated',
values: [true, false, 'both'],
```

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
