### ISSUE TITLE
Typescript - Uniform Text

### ISSUE THREAD

**Issue by jbest84** [plotly/plotly.js#5149]
It appears the uniformtext layout property is not included in the typings. I was able to work around this by extending the type as such:

```typescript
  type ExtLayout = Partial<Plotly.Layout> & {
    uniformtext?: {
      mode?: false | 'hide' | 'show',
      minsize?: number,
    }
  };

  type ExtPlotParams = PlotParams & { 
    layout: ExtLayout,
  };

  type ExtPlot = React.ComponentType<ExtPlotParams>
```

Versions:
"@types/plotly.js": "^1.50.18"
"@types/react-plotly.js": "^2.2.4"
"plotly.js": "^1.55.2"

**Comment by nicolaskruchten** [comment]
Thanks for letting us know! You'll probably want to make a PR for this to the `types` project, as this is not something the Plotly.js maintainers do on a regular basis.
