### ISSUE TITLE
Drawing module error when MathJax is present

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#515]
See http://codepen.io/etpinard/pen/YqdRWy

**Comment by alexcjohnson** [comment]
@etpinard I'm not seeing errors in that codepen - can we close this?

**Comment by etpinard** [comment]
Yep, probably fixed by your https://github.com/plotly/plotly.js/pull/1788 or https://github.com/plotly/plotly.js/pull/1991

I'll let you the honors of closing this thing.
