### ISSUE TITLE
Bug in purge function

### ISSUE THREAD

**Issue by Rezakarimi66** [plotly/plotly.js#5159]
Reproducable link: [Bug](https://codepen.io/rezakarimi66/pen/PoNxWqa)

Hi all, please take a look at the following code: 

The error is 

```
plotly-latest.min.js:61 Uncaught (in promise) TypeError: Cannot read property '_redrawFromAutoMarginCount' of undefined
    at E (plotly-latest.min.js:61)
    at plotly-latest.min.js:61
E @ plotly-latest.min.js:61
(anonymous) @ plotly-latest.min.js:61
Promise.then (async)
r.plot @ plotly-latest.min.js:61
r.newPlot @ plotly-latest.min.js:61
(anonymous) @ pen.js:19
```

and that only happens if you remove plot container in DOM after purge function.

**Comment by archmoj** [comment]
I think all you need to wrap those after plot steps in a `then`.
Please see [codepen](https://codepen.io/MojtabaSamimi/pen/XWKMVee?editors=0010).
