### ISSUE TITLE
Lowest colormap color is set to white when chart type is changed to contour

### ISSUE THREAD

**Issue by Fredx87** [plotly/plotly.js#5161]
When updating chart data and setting type to "contour", the lowest color in the colormap is always set to white instead of the right color.

This is a reproduction on codepen: https://codepen.io/fredx87/pen/YzqdJZz

If I use `Plotly.react` the colorbar is wrong, if I redraw the chart using `Plotly.newPlot` the colorbar is correct.

**Comment by archmoj** [comment]
Thanks for the report and clear demo.

**Comment by anaplian** [comment]
I've had a go at this in #5217 
Let me know if that's OK :smile: 

Happy Hacktoberfest! :jack_o_lantern:
