### ISSUE TITLE
x are dates converted to strings, Plotly cannot sort those dates increasingly

### ISSUE THREAD

**Issue by HillelR** [plotly/plotly.js#5173]
Hi - I don't know js, so reporting as explained in the opening message. 

events:
dates = [Timestamp(‘2018-01-14 00:00:00’), Timestamp(‘2018-10-24 00:00:00’), Timestamp(‘2018-11-07 00:00:00’)]
descriptions = [‘Kytruda’, ‘Video assisted thoracoscopy lobectomy’, ‘Kytruda’]
types = [‘Drug Therapy’, ‘Surgery’, ‘Drug Therapy’]

and the main trace:
dates = [Timestamp(‘2020-01-19 00:00:00’), Timestamp(‘2019-12-09 00:00:00’), Timestamp(‘2019-11-20 00:00:00’), Timestamp(‘2019-10-30 00:00:00’), Timestamp(‘2019-10-10 00:00:00’), Timestamp(‘2019-09-18 00:00:00’), Timestamp(‘2019-08-28 00:00:00’), Timestamp(‘2019-08-06 00:00:00’), Timestamp(‘2019-07-10 00:00:00’), Timestamp(‘2019-06-19 00:00:00’), Timestamp(‘2019-05-29 00:00:00’), Timestamp(‘2019-05-07 00:00:00’), Timestamp(‘2019-04-17 00:00:00’), Timestamp(‘2019-03-27 00:00:00’), Timestamp(‘2019-03-06 00:00:00’), Timestamp(‘2019-02-13 00:00:00’), Timestamp(‘2019-01-23 00:00:00’), Timestamp(‘2019-01-06 00:00:00’), Timestamp(‘2018-12-26 00:00:00’), Timestamp(‘2018-12-05 00:00:00’), Timestamp(‘2018-11-25 00:00:00’), Timestamp(‘2018-11-14 00:00:00’), Timestamp(‘2018-10-26 00:00:00’), Timestamp(‘2018-10-25 00:00:00’), Timestamp(‘2018-10-24 00:00:00’), Timestamp(‘2018-10-23 00:00:00’), Timestamp(‘2018-10-21 00:00:00’), Timestamp(‘2018-10-03 00:00:00’), Timestamp(‘2018-09-20 00:00:00’), Timestamp(‘2018-09-12 00:00:00’), Timestamp(‘2018-09-03 00:00:00’), Timestamp(‘2018-08-27 00:00:00’), Timestamp(‘2018-08-19 00:00:00’), Timestamp(‘2018-08-12 00:00:00’), Timestamp(‘2018-08-05 00:00:00’), Timestamp(‘2018-07-29 00:00:00’), Timestamp(‘2018-07-23 00:00:00’), Timestamp(‘2018-07-16 00:00:00’), Timestamp(‘2018-07-09 00:00:00’), Timestamp(‘2018-07-04 00:00:00’), Timestamp(‘2018-07-01 00:00:00’), Timestamp(‘2018-06-25 00:00:00’), Timestamp(‘2018-06-24 00:00:00’), Timestamp(‘2018-06-10 00:00:00’), Timestamp(‘2018-05-06 00:00:00’), Timestamp(‘2018-04-29 00:00:00’), Timestamp(‘2018-03-25 00:00:00’), Timestamp(‘2018-03-18 00:00:00’), Timestamp(‘2018-03-04 00:00:00’), Timestamp(‘2018-02-25 00:00:00’), Timestamp(‘2018-02-04 00:00:00’), Timestamp(‘2018-01-21 00:00:00’), Timestamp(‘2018-01-14 00:00:00’), Timestamp(‘2017-12-24 00:00:00’), Timestamp(‘2017-12-10 00:00:00’), Timestamp(‘2017-12-03 00:00:00’), Timestamp(‘2017-11-24 00:00:00’), Timestamp(‘2017-09-13 00:00:00’)]
values = [ 2.6 3.5 3.9 3.8 3.5 3.5 4.6 4.7 3. 3.3 3.7 4.8
3.8 3.1 3.4 3.1 5.8 4.4 3.8 5.4 3.8 4.5 3.81 5.74
13.1 4.81 4.1 3.4 3.1 3.8 3.1 3.3 3.5 3.8 3.8 3.9
3.7 4. 3.3 2.5 1.4 1. 0.9 6.8 0.6 2.9 1.9 3.8
2.2 3.6 4.3 2.5 2.1 10.9 2.8 10.7 10.9 10.6 ]

when x are dates converted to strings, Plotly cannot sort those dates increasingly.
With pure datetimes the bars are not plotted either.  

All is summarized in the following thread: 
https://community.plotly.com/t/adding-event-annotations-to-time-series-plots-as-vertical-bars/34571/8

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
