### ISSUE TITLE
3D surface plot: Interactive rotation, zooming, panning not working on touch devices

### ISSUE THREAD

**Issue by bg23** [plotly/plotly.js#518]
A 3D surface plot displays a toolbar at the upper right with icons to enable interactive rotation or zooming or panning. When a mode is enabled, dragging the mouse would interactively zoom etc.
On touch devices (e.g. tablets) one would expect that moving a finger would perform the respective operation. Instead:
Under Chrome/Android, the 3D surface plot is shown, the toolbar appears after double tapping, but zooming etc. is not supported.
Under Safari/iOS, the 3D surface plot is not shown at all, conforming with issue #280.

**Comment by etpinard** [comment]
duplicate of https://github.com/plotly/plotly.js/issues/480
