### ISSUE TITLE
flag to disable parsing textual numbers as numbers in axis auto-typing

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#5195]
I would really love a flag like `layout.parsenumericalstrings` which I could force to `false` from Python, so that axis auto-typing would treat `"1"` the same way as `"a"` :)

**Comment by archmoj** [comment]
Should it only be applied in axes autoType?
For example if one used numbers as string in colors and symbols we should still cast them. Right?

**Comment by nicolaskruchten** [comment]
just for auto-typing, yes. we can rename the attribute as needed 👍
