### ISSUE TITLE
tickformat don't work for Reactjs

### ISSUE THREAD

**Issue by yankeeguyu** [plotly/plotly.js#5214]
When i set tickformat to y axis layout, it is only valid for the y-axis scale, but the y-axis data  still maintains the original value and will not change with tickformat. Like this:
![image](https://user-images.githubusercontent.com/46274612/96233369-d073ea00-0fca-11eb-91b5-d62449d6c75a.png)

So how to fix this problem? Thank you very much!

**Comment by archmoj** [comment]
Have you tried using texttemplate?

**Comment by yankeeguyu** [comment]
> Have you tried using texttemplate?

Hi @archmoj , i tried texttemplate, but it also didn't work for me!

**Comment by archmoj** [comment]
Could you please share a minimal data and layout  of your figure?

**Comment by yankeeguyu** [comment]
x: [2020-10-01, ...., 2020-10-15]
y: [0.11, ... 0.20]

xaxis layout is %Y-%m-%d, yaxis layout is .3%

**Comment by archmoj** [comment]
Like this [demo](https://codepen.io/MojtabaSamimi/pen/NWrNpKy?editors=0010)?

**Comment by alexcjohnson** [comment]
Also [hoverformat](https://plotly.com/javascript/reference/layout/yaxis/#layout-yaxis-hoverformat)

**Comment by yankeeguyu** [comment]
> Like this [demo](https://codepen.io/MojtabaSamimi/pen/NWrNpKy?editors=0010)?

Yep, in codepen it works, but in reactjs don't work!

**Comment by yankeeguyu** [comment]
I fixed it, thank you!
