### ISSUE TITLE
Disable Rotation Drag on Polar when dragmode = false

### ISSUE THREAD

**Issue by Phil-DS** [plotly/plotly.js#5219]
When I set dragmode to false, I'm expecting all drag events to be halted. On polar, the zoom event was halted, but you are still able to click and drag the outer edge of the polar chart, and rotate the chart, which is seemingly impossible to disable without going deep into the halting of events, or making it a static chart (Which means that you lose any sort of interactivity that is enabled by Plotly)

**Comment by Peque** [comment]
@Phil-DS Did you find any workaround for this?

**Comment by TheLogan** [comment]
I could also use a fix for this, been trying a multitude of things, but dragmode is the one that makes most sense, but it doesn't seem there is a way to do it :(

**Comment by nicolaskruchten** [comment]
We'd accept a PR for this if someone is interested :)

**Comment by TheLogan** [comment]
Had a look at the source code, it's beyond me I'm afraid =/

**Comment by Phil-DS** [comment]
Sadly, I never found a fix for it. While I could have lived without removing the drag rotation, it had another aspect that it disabled click events, which were pivotal to the use case I had. I did update to the latest today to see if the click events were still disabled by it, and they were. In the end, I ignored the issue.

I did have a deeper look into the source code at the time, and unless I did some major overriding, I wouldn't be able to get the click events working with disabling the rotation and zoom.

**Comment by speti05** [comment]
It's quite hacky, but when **cursor-move** class has been deleted from the element, drag on angular axis works no more

<path class="angulardrag drag cursor-move"....>

**Comment by miketwo** [comment]
I have a workaround if you're using `react-plotly`, but it's ugly...

```jsx
// Add the following state
const [rotation, setRotation] = useState(90);
const [revision, setRevision] = useState(1);

// Add a callback that we will use whenever the layout is updated.
  const onLayoutCallbacks = data => {
    if (data['polar.angularaxis.rotation']) {
      setRotation(90);
      setRevision(revision + 1);
    }
  };

// Add the callback to the component. 
// And be sure the layout is based on state
<Plot
  onRelayout={onLayoutCallbacks}
  onRelayouting={onLayoutCallbacks}
  ...
  layout={{
    angularaxis: {
      rotation,
      ...
```

It should make it so that callback is executed on/during layout changes, and it specifically resets the angular rotation if that's the data being changed. The result is that you get a gazillion refreshes if someone drags the axis, but it shouldn't change what it looks like. YMMV.

**Comment by sup3rcow** [comment]
This will turn off drag event on element that is responsible for drag/rotate action.
 .angulardrag {
  pointer-events: none !important;
}
