### ISSUE TITLE
Stange Plotly.js click annotation behavior with two y axes

### ISSUE THREAD

**Issue by abalter** [plotly/plotly.js#523]
I'm using code based off the plotly [click event example](https://plot.ly/javascript/text-and-annotations/#styling-and-formatting-annotations), but with two y axes. I define the left axis first, and the right axis second.

1. When I click on a point associated with the "first" (left) axis, I get the proper annotation box, however, if there isn't room above, plotly shoves down the grid ONLY for the left axis points which looks very strange. 

1. **FIXED** (added `hovermode` to the y axes) When I click on a point associated with the "second" (right) axis, but with an x-value shared by the left axis, the annotation box appears for the WRONG axis, i.e. is the "first".

1. When I click on a point associated with the "second" (right) axis (at a non-shared x value), the annotation box appears on the x-axis, not at the selected point.

1. When I click on a point associated with the "second" (right) axis (at a non-shared x value), if there isn't room the axis again get mushed around.

**NOTE**: In my opinion and experience with Matlab, the grid is the grid. The numbers on the left and right axes may be different representing different scales. But there are not two separate, superimposed grids as there appears to be in Plotly.

[![enter image description here][1]][1]
[![enter image description here][2]][2]
[![enter image description here][3]][3]

https://jsfiddle.net/abalter/4vy2ea5b/

Javascript:

    // start out with empty plot
    Plotly.newPlot("graph",[],{title: "Multiple Y-Axis Plot"});
    
    var trace1 =
    {
      x: [1, 2, 3],
      y: [40, 50, 60],
      name: 'yaxis data',
      type: 'scatter'
    };
    
    var trace2 =
    {
      x: [2, 3, 4],
      y: [4, 5, 6],
      name: 'yaxis2 data',
      yaxis: 'y2',
      type: 'scatter'
    };
    
    var yaxis1 =
    {
    	title: 'yaxis1',
      //position: 0,
      side: "left",
      anchor: 'x'
    };
    
    var layout1 =
    {
    	yaxis1: yaxis1,
    };
    
    var yaxis2 =
    {
      title: 'yaxis2 title',
      titlefont: {color: 'rgb(148, 103, 189)'},
      tickfont: {color: 'rgb(148, 103, 189)'},
      overlaying: 'y1',
      side: 'right',
      anchor: 'x'
      //position: 1,
    };
    
    var layout2 =
    {
    	yaxis2: yaxis2
    };
    
    Plotly.relayout("graph", layout1);
    Plotly.addTraces("graph", [trace1]);
    
    Plotly.relayout("graph", layout2);
    Plotly.addTraces("graph", [trace2]);
    
      myPlot = document.getElementById('graph');
    
      myPlot.on('plotly_click', function(data)
      {
        //console.log(data);
        
        var point = data.points[0];
        
        console.log("point.pointNumber: " + point.pointNumber);
        console.log("point.x " + point.x);
        console.log("point.y " + point.y);
        var name = point.fullData.name;
        console.log("name " + point.fullData.name);
    
        x_datetime = new Date(point.x);
        console.log("x_datetime: " + x_datetime);
        x_datestring = x_datetime.toLocaleDateString('en-US');
        console.log("x_datestring: " + x_datestring);
    
        var newAnnotation =
        {
            x: point.x,
            y: point.y,
            arrowhead: 8,
            ax: 0,
            ay: -80,
            bgcolor: 'rgba(255, 255, 255, 0.9)',
            arrowcolor: point.fullData.marker.color,
            font:
            {
                size: 12
            },
            bordercolor: point.fullData.marker.color,
            borderwidth: 3,
            borderpad: 4,
            text: '<b>Date: </b>' + x_datestring + '<br>' + '<b>' + name + ': </b>' + point.y + '<br>'
        };
    
        var divid = document.getElementById('graph');
        var newIndex = (divid.layout.annotations || []).length;
    
        // delete instead if clicked twice
        if (newIndex)
        {
            var foundCopy = false;
            divid.layout.annotations.forEach(function(ann, sameIndex)
            {
                if (ann.text === newAnnotation.text)
                {
                    Plotly.relayout(
                        'graph',
                        'annotations[' + sameIndex + ']',
                        'remove'
                    );
    
                    foundCopy = true;
    
                }
            });
    
            if (foundCopy)
            {
                return;
            }
    
        }
            
        Plotly.relayout
        (
            'graph',
            'annotations[' + newIndex + ']',
            newAnnotation
        );
        
      })
      .on('plotly_clickannotation',function(event, data)
      {
          Plotly.relayout(
              'graph',
              'annotations[' + newIndex + ']',
              newAnnotation
          );
      });

  [1]: http://i.stack.imgur.com/qprfol.png
  [2]: http://i.stack.imgur.com/823cDl.png
  [3]: http://i.stack.imgur.com/kPCDv.png

**Comment by mdtusz** [comment]
I'm not sure that this is a bug per-se, but @etpinard will need to chime in. 

Regarding the annotation "flags" being placed incorrectly - this is also not a bug - you must specify which axis the position should reference when placing it by adding (for example) `yref: 'y2'`.

Plotly.js is not built in the exact same manner as plots with Matlab and _our_ grid _is_ intrinsic to the data - it is possible to just turn it off if you wish, but the positioning still remains in code. There is no easy or clear way to display two axes with differing scales and a shared grid, so we leave it to the user to decide what is preferred. Some users may find having a single grid that is not in line with a second axis to be misleading. You can turn off an axis grid with `showgrid: false` in the axis layout settings.

**Comment by abalter** [comment]
@mdtusz:

Thanks for referring me to the `yref` attribute. I hadn't seen that one before. It is a bit awkward accessing it from within the `plotly-click` callback:

    var yref = point.yaxis._id;

But it does do the trick.

Seems to me that the default behavior should be to assume I'm referring to the axis I'm clicking on. Do you agree?

I'll comment on the 2nd issue in the issue I opened specifically for it #524.

**Comment by mdtusz** [comment]
Correct, that _would_ be a smart default, but without any context of _which axis you want_, it's impossible to know (we can't really gather an axis context on a custom event handler...).

**Comment by abalter** [comment]
Couldn't you just assume it is `point.yaxis._id`?

**Comment by mdtusz** [comment]
When creating the annotation, there is no notion of an associated `point` - the annotation is not bound to any points and it's position, axis layer etc. are all set independent of any plot-data.
