### ISSUE TITLE
SVG NaN errors when shapes and bgcolor are specified

### ISSUE THREAD

**Issue by zbjornson** [plotly/plotly.js#5235]
https://jsfiddle.net/hnqe98uv/

This example generates a handful of errors like `Unexpected value NaN parsing x attribute` because some of the background attributes (`_offset`, `_length`) are not set. This only occurs with `paper_bgcolor`.

**Comment by archmoj** [comment]
Strangely enough, if one hides `heatmap` `colorbar` using `showscale: false`, the error goes away!

**Comment by archmoj** [comment]
Here is [a minimal codepen](https://codepen.io/MojtabaSamimi/pen/XWKRLob?editors=0010).

**Comment by archmoj** [comment]
This is in fact a regression since [v1.43.0](https://github.com/plotly/plotly.js/releases/tag/v1.43.0).

**Comment by archmoj** [comment]
Side effect of #3510.

**Comment by zbjornson** [comment]
Thank you for the fast fix!

**Comment by archmoj** [comment]
> Thank you for the fast fix!

Thanks for your report.
Please note that the official fix won't be available until next patch/minor release.
