### ISSUE TITLE
Graphs should have a single grid regardless of how many y axes.

### ISSUE THREAD

**Issue by abalter** [plotly/plotly.js#524]
Specific aspect of #523.

Currently, graphs with multiple y axes appear to be separate plots superimposed upon each other, each with their own grid. Sometimes the grids are not synced up and you get oddly placed grid lines. Annotations relating to one y axis will distort only those grid lines, doing very weird things to the plot.

To prevent these inconsistencies, the grid could belong to the paper, not the axes. The values of the tick marks and tick values can be different on the various y axes. They can line up with the grid lines or not. The grids help guide the eye. They are not data.

This causes a conundrum: since it makes sense for a single y axis to have the ticks on that axis define the grid, when there are multiple y axes, what defines the grid spacing?

**Proposal:**

The grid is a visual element, not a data element. So the grid should by in the layout section. However, you can anchor it to a y axis of your choice, or the paper.

```
var layout =
{
  grid:
  {
    anchor: ["yaxis#" | "paper"], // if y axis, grid lines at tick values
    scale: ["linear" | "log" | "auto"],
    num_lines: [int],  // if anchored to y axis, choose best n ticks. if paper, space according to scale
    divisions: [int], // if anchored to y axis, number of grid lines between ticks
  }
}
```

**Comment by abalter** [comment]
From #523:

>There is no easy or clear way to display two axes with differing scales and a shared grid, so we leave it to the user to decide what is preferred. Some users may find having a single grid that is not in line with a second axis to be misleading. You can turn off an axis grid with showgrid: false in the axis layout settings.

But, the user really has only two choices in this case, left axis or right axis. In my proposal, the user has three options, left axis, right axis, or independent. It makes sense in most cases to have the grid align with tick marks, but not all, and my proposal does allow more freedom.

**Comment by mdtusz** [comment]
I'm not sure that I agree. Yes, grids are visual cues and not data, but they should still align with sensible intervals so you can easily comprehend the scales of axes. I agree that when axes gridlines become "out of sync", it can be confusing, but I think that having a static grid that is locked to the paper would be even more misleading when resizing the plot.

As mentioned in the other issue, grids can be turned on or off so I would suggest as a fix for your situation to simply turn off one of the axes grids - this is essentially the same result as having an `anchor` attribute for the grid.

**Comment by abalter** [comment]
Fair enough. I suppose I could always get exactly the behavior I want by writing a function that creates a grid out of vertical and horizontal lines. Wouldn't be too bad I don't think.

**Comment by ginna-baker** [comment]
I have this same issue and think it should work as @mdtusz suggests.  Here you can see that I have the same number of tics on each side, but they are not aligned.  
![screen shot 2017-08-22 at 3 41 48 pm](https://user-images.githubusercontent.com/6732956/29585358-d8ca2b08-8754-11e7-992f-f9d28732df50.png)

I turned the grid off for one side, but really if there are the same number of tics, the grid lines should be evenly spaced on both sides.
