### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by silviubogan** [plotly/plotly.js#5243]
This dependency makes it impossible to use plotly.js in the browser because image-size uses fs module which is not available in browsers. I do not know how does react-plotly.js adapt to this dependency but I guess they have this issue too.

Related to: https://github.com/plotly/plotly.js/pull/5119.

# Reproducible example
1. Create an app with `create-react-app`.
2. Install dependencies from the screenshot below (you might need to change the React and ReactDOM packages' versions too), including `plotly.js@1.57.1` and use it as a dynamic import with `@loadable/component`.
3. Run `yarn start` in the project directory.

## Screenshot
![image](https://user-images.githubusercontent.com/198924/98013057-89775880-1e02-11eb-8ebc-890f8d0c2982.png)

## Expected output
The app runs well without terminal or browser errors.

## Actual output
Error inside browser window:

![image](https://user-images.githubusercontent.com/198924/98012831-38fffb00-1e02-11eb-9f56-2b74bd56ab85.png)

# Update
The essence of this issue is here: https://github.com/plotly/plotly.js/issues/5243#issuecomment-724028727

**Comment by silviubogan** [comment]
Sorry, I think it is a configuration problem on my side. It seems to work with create-react-app. I am closing this because of this.

**Comment by silviubogan** [comment]
I get the same error again and in a similar situation, so I think it is real. This time I have more information. We use `plotly.js 1.57.0` and `react-plotly.js 2.5.0`. The code [is here](https://github.com/eea/volto-bise/blob/41b4dbfd83ac7f4718cd9fdd45c4c30870f71954/src/components/theme/datablocks/ConnectedChart/ConnectedChart.jsx) and the situation in images is:

## Browser window contents
![image](https://user-images.githubusercontent.com/198924/98540614-e5286280-2296-11eb-83d4-ce5a36682737.png)

## DevTools console
### react-plotly.js errors
![image](https://user-images.githubusercontent.com/198924/98540793-21f45980-2297-11eb-8786-8f6370bf55c1.png)

### Our code's errors
![image](https://user-images.githubusercontent.com/198924/98540988-697ae580-2297-11eb-9831-54d1c5671d54.png)
![image](https://user-images.githubusercontent.com/198924/98541070-87484a80-2297-11eb-9c6f-8abb5d32f4ce.png)

### plotly.js errors
![image](https://user-images.githubusercontent.com/198924/98541601-5c122b00-2298-11eb-9287-0e85d3194c18.png)

I will try to reproduce this issue in a `create-react-app` project and come with an update.

Thank you.

**Comment by silviubogan** [comment]
I think that the following error might be related to the same issue:
![image](https://user-images.githubusercontent.com/198924/98549853-09d70700-22a4-11eb-9642-5620be453e40.png)

**Comment by silviubogan** [comment]
I have tested and the screenshot in my message above is the root cause of this issue.

In chronological order:

1. I start the server.
2. I open the browser with the web app URL.
3. The error in my previous message appears in the terminal and approximatively at the same time in the browser I get this:
![image](https://user-images.githubusercontent.com/198924/98550463-cd57db00-22a4-11eb-803b-cead4636ecd4.png)
4. Refreshing the page in the browser makes the server skip the error and in the browser I see the first errors in this issue.

**Comment by archmoj** [comment]
@silviubogan could you investigate if [probe-image-size](https://www.npmjs.com/package/probe-image-size) depends on `fs`? And if it does not, can we replace it with `image-size` here?
https://github.com/plotly/plotly.js/blob/e62219a57e1024082d221e9e460d986bc057b8ec/src/traces/image/helpers.js#L11

**Comment by silviubogan** [comment]
In our code, the issue is that these instructions (just them, as I verified), when not commented out, produce the error related to the `fs` module, although I was thinking this is impossible since I tested them in a context where they are not used anywhere:

```js
const LoadableBasicPlotly = loadable.lib(() =>
  import('plotly.js/lib/index-basic'),
);
const LoadableCartesianPlotly = loadable.lib(() =>
  import('plotly.js/lib/index-cartesian'),
);
const LoadableGeoPlotly = loadable.lib(() => import('plotly.js/lib/index-geo'));
const LoadableGl3dPlotly = loadable.lib(() =>
  import('plotly.js/lib/index-gl3d'),
);
const LoadableGl2dPlotly = loadable.lib(() =>
  import('plotly.js/lib/index-gl2d'),
);
const LoadableMapboxPlotly = loadable.lib(() =>
  import('plotly.js/lib/index-mapbox'),
);
const LoadableFinancePlotly = loadable.lib(() =>
  import('plotly.js/lib/index-finance'),
);
```

I still do not understand how `loadable.lib` works. I thought it lazy loads the libraries, so if none of the `const`s above are used, as I tested, the error related to `fs` is not justified.

I start investigating the probe-image-size library now, if nothing else more important intervenes.

Thank you!

**Comment by silviubogan** [comment]
The `probe-image-size` library does not require `fs` and, they say, finds the length only through HTTP. An example usage is this:

```js
  it('should return content-length', async function () {
    responder = function (req, res) {
      res.writeHead(200, { 'Content-Length': 1234 });
      res.end(GIF1x1);
    };


    let size = await probe(url);


    assert.strictEqual(size.width, 1);
    assert.strictEqual(size.height, 1);
    assert.strictEqual(size.length, 1234);
    assert.strictEqual(size.mime, 'image/gif');
  });
```

(via [this link](https://github.com/nodeca/probe-image-size/blob/c16972265caba1e3caa636d37a23f42eb2dc878f/test/test_http.js#L49-L61))

But its internal functions are easy to use and extend. If time allows me to do this, I can try to use it for your use cases.

**Comment by nicolaskruchten** [comment]
I could be way off the mark here but the `document is not defined` error suggests to me that you're trying to use this module in a NodeJS context rather than a browser context, which is not really a supported use-case at all... Is that indeed what you're trying to do?

**Comment by silviubogan** [comment]
> I could be way off the mark here but the `document is not defined` error suggests to me that you're trying to use this module in a NodeJS context rather than a browser context, which is not really a supported use-case at all... Is that indeed what you're trying to do?

Yes, more precisely we use razzle with SSR. I hope that SSR is supported.

Thank you.

**Comment by nicolaskruchten** [comment]
Unfortunately, pure-Javascript SSR is not officially supported at this time and I'm not aware of anyone having successfully done it unofficially, due to this exact issue. Plotly.js relies extensively on browser APIs which are generally not available or hard to emulate on the server short of running a full in memory browser like we do in the Kaleido project.

**Comment by silviubogan** [comment]
PTAL and help me solve this issue. Is it an issue in `@loadable/component`?

> In our code, the issue is that these instructions (just them, as I verified), when not commented out, produce the error related to the `fs` module, although I was thinking this is impossible since I tested them in a context where they are not used anywhere:
> 
> ```js
> const LoadableBasicPlotly = loadable.lib(() =>
>   import('plotly.js/lib/index-basic'),
> );
> const LoadableCartesianPlotly = loadable.lib(() =>
>   import('plotly.js/lib/index-cartesian'),
> );
> const LoadableGeoPlotly = loadable.lib(() => import('plotly.js/lib/index-geo'));
> const LoadableGl3dPlotly = loadable.lib(() =>
>   import('plotly.js/lib/index-gl3d'),
> );
> const LoadableGl2dPlotly = loadable.lib(() =>
>   import('plotly.js/lib/index-gl2d'),
> );
> const LoadableMapboxPlotly = loadable.lib(() =>
>   import('plotly.js/lib/index-mapbox'),
> );
> const LoadableFinancePlotly = loadable.lib(() =>
>   import('plotly.js/lib/index-finance'),
> );
> ```
> 
> I still do not understand how `loadable.lib` works. I thought it lazy loads the libraries, so if none of the `const`s above are used, as I tested, the error related to `fs` is not justified.
> 
> I start investigating the probe-image-size library now, if nothing else more important intervenes.
> 
> Thank you!

**Comment by silviubogan** [comment]
It seems that after commenting all the other loadable.lib calls in the message above, from these remaining two:

```js
const LoadableBasicPlotly = loadable.lib(() =>
  import('plotly.js/lib/index-basic'),
);
const LoadableCartesianPlotly = loadable.lib(() =>
  import('plotly.js/lib/index-cartesian'),
);
```

The first one alone does not produce the error with `fs`, but when uncommenting the second one, the error is there. What could be the issue? Is it a Loadable issue?

Thank you.

**Comment by archmoj** [comment]
@silviubogan would you mind testing if the issue was resolved after #5388?

**Comment by silviubogan** [comment]
@archmoj Thank you for the notification. I am pleased to know you have worked on this. I will try to find time in the following week.

**Comment by archmoj** [comment]
See https://github.com/plotly/plotly.js/issues/5377#issuecomment-757363843

**Comment by silviubogan** [comment]
@archmoj  The error related to the module `image-size` is gone (with the latest commit in `plotly.js#master`) in the project I work on, although I did not test inside CodeSandbox. Is it possible to tell when will the change be included in a GitHub release? Thank you!

**Comment by archmoj** [comment]
> @archmoj The error related to the module `image-size` is gone (with the latest commit in `plotly.js#master`) in the project I work on, although I did not test inside CodeSandbox. Is it possible to tell when will the change be included in a GitHub release? Thank you!

Thanks for testing this out.
We are working on a major release now that involves days of QA.
So v2 might be out around Jan 25, I hope.
