### ISSUE TITLE
dragmode [Intervention] Ignored attempt to cancel a touchstart event

### ISSUE THREAD

**Issue by aldomart** [plotly/plotly.js#5251]
hi, I'm having an issue:

Using a Node server with Chrome on Windows in mobile mode I'm getting: 
    **plotly.js:90457 [Intervention] Ignored attempt to cancel a touchstart event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.**

tried with plotyly version 1.54.7 and version 1.57.1, same...

looking at plotly code I found it's failing on e.preventDefault in:

if(options.dragmode !== false) {
    e.preventDefault();
    document.addEventListener('mousemove', onMove);
    document.addEventListener('touchmove', onMove, {passive: false});
}

if tested in a plain html, not getting the error, but click does nothing, sample code:

`<script
  src="https://cdn.jsdelivr.net/gh/plotly/plotly.js@1.54.7/dist/plotly.js"
  type="text/javascript"
></script>

<div id="myDiv"></div>
<script>
  var myPlot = document.getElementById("myDiv"),
    d3 = Plotly.d3,
    N = 16,
    x = d3.range(N),
    y = d3.range(N).map(d3.random.normal()),
    data = [
      { x: x, y: y, type: "scatter", mode: "markers", marker: { size: 16 } },
    ],
    layout = {
      hovermode: "drawclosedpath",
      title: "Click on Points",
      dragmode: "select",
    };

  Plotly.newPlot("myDiv", data, layout);

  myPlot.on("plotly_click", function (data) {
    var pts = "";
    for (var i = 0; i < data.points.length; i++) {
      pts =
        "x = " +
        data.points[i].x +
        "\ny = " +
        data.points[i].y.toPrecision(4) +
        "\n\n";
    }
    alert("Closest point clicked:\n\n" + pts);
  });
</script>`

with dragmode "zoom" | "pan" works, with "select" | "lasso" | "drawclosedpath" not

if I disable mobile mode it works, any idea?

Thanks!

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
