### ISSUE TITLE
How to handle discontinuity in data

### ISSUE THREAD

**Issue by vinerich** [plotly/plotly.js#5261]
Hey folks,
at first thanks for the hard work.

### Problem/Question
For certain applications we have data that should come in at a `regular interval`, suppose something like `2 seconds`. If this data is not coming in (**there are no datapoints at all (!)**) it should be considered a discontinuity.

I'm trying to achieve an interpolate display of data which is continous and a disconnected display of data which has a discontinuity.

### Existing solution
I read through https://github.com/plotly/plotly.js/issues/1454 and the corresponding community thread at [4234](https://community.plotly.com/t/how-to-graph-time-series-data-with-a-discontinuous-x-axis/423/4).

This points me to using `connectgaps = false` and to insert a timestamp with `null` values for each dataset I want to plot. This should be doable without problems.

However I'm not sure if inserting artificial data into raw datasets "just to achieve a certain plotting of that data" is a good solution.

### Proposal
As a first draft I thought of a parameter like `gapwidth = 3 seconds` which in conjunction with `connectgaps = false` would result in a `value gap (no data)` of 3 seconds or more not being interpolated.

There is probably more to think of before bringing this to a solution. Just wanted to check with the ones familiar with the code and existing solutions if there is a possibility to implement such a feature, or if it would lead to much bigger problems and headaches than it is trying to solve.

Thanks for your time.

**Edit:** The `rangebreak` feature is also not usable since the breaks should be visible to the user in my case.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
