### ISSUE TITLE
should clip inside ticks

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#5263]
[codepen](https://codepen.io/MojtabaSamimi/pen/LYZMPYb?editors=0010)

**Comment by nicolaskruchten** [comment]
probably pretty marginal/unlikely to happen in the wild, I would not put work into this.

**Comment by alexcjohnson** [comment]
I don't consider this a bug. Yes in extreme cases like this the overflowing tick looks odd, but in more realistic cases you want the tick to either be entirely visible (when the label is visible) or entirely gone along with the label. A partially-visible tick would look wrong.
