### ISSUE TITLE
should increase autorange pad for long inside ticks

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#5264]
[codepen](https://codepen.io/MojtabaSamimi/pen/JjKwPGR?editors=0010)

**Comment by nicolaskruchten** [comment]
We can log a bug here but I'm OK not working on this just now.

**Comment by alexcjohnson** [comment]
I don't think this should be the default behavior. When we give folks the ability to customize the padding they can do it manually. cc #1876

**Comment by archmoj** [comment]
This conflicts with #5186. Namely when both `ticks` and `ticklabelposition` are set to `inside`.

**Comment by alexcjohnson** [comment]
I don't see that as a conflict - labels should by default not overlap the data, so when those are inside the padding should increase enough for the labels and any space between the labels and the axis (ie where the ticks are). But if you've asked for inside ticks without inside labels, there are plenty of cases where the ticks overlapping the data is what you want - heatmaps, lines going to the edge, etc.

**Comment by archmoj** [comment]
Thanks for the clarification. So I'll only address this for the case of "inside" `ticklabelposition` without touching the default behaviour for other "inside" `ticks`.
