### ISSUE TITLE
mapox layers reordered after updating figure with Plotly.react

### ISSUE THREAD

**Issue by jonmmease** [plotly/plotly.js#5266]
### Overview

I would like to overlay a mapbox `image` layer on top of a mapbox `raster` layer and update the `image` layer's `coordinates` and/or `source` properties in response to zoom/pan events using `Plotly.react`

On initial render, everything works fine and the z-order of the two layers matches the order in the `layout.mapbox.layers` array. However, after updating the image layer's `coordinates` in a `plotly_relayout` callback, the image layer is pushed behind the raster layer.

Here's an example, where the opacity of the raster layer is set to 0.5 so that you can see the image behind it.

Codepen: https://codepen.io/jonmmease/pen/vYKvxwx?editors=1010

![mapbox_layer_order](https://user-images.githubusercontent.com/15064365/98930449-a834b980-24aa-11eb-84f3-e3255407cdec.gif)

Unless anyone has an idea of what might be going on here, I'll start poking around in https://github.com/plotly/plotly.js/blob/master/src/plots/mapbox/layers.js.

**Comment by archmoj** [comment]
It is an update bug here: 
https://github.com/plotly/plotly.js/blob/98dfdb836e56296361e537f15d885b3916bebbdb/src/plots/mapbox/layers.js#L37-L56

It seems to work if I replace the function with something like:

```js
proto.update = function update(opts) {
    if(!this.visible) {
        // IMPORTANT: must create source before layer to not cause errors
        this.updateSource(opts);
        this.updateLayer(opts);
    } else {
        if(this.needsNewSource(opts)) {
            // IMPORTANT: must delete layer before source to not cause errors
            this.removeLayer();
            this.updateSource(opts);
            this.updateLayer(opts);
        }

        if(this.needsNewImage(opts)) {
            this.updateImage(opts);
        }

        if(this.needsNewLayer(opts)) {
            this.updateLayer(opts);
        } else {
            this.updateStyle(opts);
        }
    }

    this.visible = isVisible(opts);
};
```

**Comment by jonmmease** [comment]
Thanks, I'm playing with it now.
