### ISSUE TITLE
category order bug

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#5267]
This pen https://codepen.io/nicolaskruchten/pen/OJXrOLG shows (on my machine anyway) the categories being out of order:

![image](https://user-images.githubusercontent.com/203523/98951227-fc01cb80-24c7-11eb-9366-0d5ae6ed0afc.png)

reported in https://github.com/plotly/plotly.py/issues/2350 but oddly not always reproducible.

**Comment by archmoj** [comment]
Here is a [minimal codepen](https://codepen.io/MojtabaSamimi/pen/yLJGPYJ?editors=0010).
