### ISSUE TITLE
Small domain causing hovers to not appear

### ISSUE THREAD

**Issue by abalter** [plotly/plotly.js#527]
Ok, maybe "sensible" and "nonsensical" are not really true, I'm just thinking domain should be `[0,1]`, but maybe that is not necessary.

This bug was discovered via this SO post. http://stackoverflow.com/questions/37178664/plotly-hover-text-not-displaying/37180688#37180688

[This fiddle](https://jsfiddle.net/abalter/0cjprqgy/) has the following code, and hover text is not working. If I make the single change of `domain` from `[0.85, 0.9]` to `[0.85, 1.9]`, the hovers show. But the whole point is to have the line of markers above other plots as in http://plnkr.co/edit/vvStyutowlwubUdddY37

``` javascript
var data =
{
    "x":["2014-02-10 00:00:00.0","2014-02-18 00:00:00.0","2014-02-24 00:00:00.0"],
  "y":[0,0,0],
  "text":["gemcitabine","gemcitabine + Abraxane","Xeloda"],
    "hoverinfo": "all",
  "name":"Treatment",
  "type":"scatter",
  "mode":"markers",
  "marker":
  {
    "size":9,
    "color":"#800000"
    },
  "uid":"c2e171"
};

var layout = 
{
    "title":"Treatments",
  "height":600,
  "width":655,
  "autosize":true,
  "yaxis":
  {
    "titlefont":
    {
        "size":12,
      "color":"#800000"
    },
    "domain":[0.85,0.9],
    "showgrid":false,
    "showline":false,
    "showticklabels":false,
    "zeroline":true,
    "type":"linear",
    "range":[0,0],
    "autorange":true
  },
  "hovermode":"closest",
  "xaxis":
  {
    "type":"date",
    "range":[1389215256994.8186,1434909143005.1814],
    "autorange":true
  }
};

Plotly.plot('graph', [data], layout);
```

**Comment by etpinard** [comment]
Bug confirmed. Thanks for bringing this up.

Reproducible codepen: http://codepen.io/etpinard/pen/BKEpgW

Hover labels visibility should not be affected by the axis domains.

**Comment by etpinard** [comment]
>  If I make the single change of domain from [0.85, 0.9] to [0.85, 1.9], the hovers show

By the way, domain values beyond `[0,1]` (e.g `[0.85, 1.9]`) are constrained to the `[0,1]` interval. That is, `[0.85, 1.9]` is really the same as `[0.85, 1]` for plotly.js.

**Comment by abalter** [comment]
Good to know! Incidentally, maybe if I add another element that goes from `[0.9,1]` it would fix it. Worth a try...

**Comment by abalter** [comment]
Hi @etpinard. I was hoping that if I had domains going all the way to 1.0 it would help the situation. But as you can see here:

http://plnkr.co/edit/h0N4p0BAdg1yzP7qz2iR?p=preview

No such luck. There are some scientists who would be really happy if this plot worked as expected!

Thanks, Ariel

**Comment by abalter** [comment]
Here is a little playground that might help with debugging:

https://jsfiddle.net/abalter/kehgovq9/

**Comment by jdugge** [comment]
I believe this happens because plot.ly wants to constrain labels strictly to the height of current y axis ([`pmax`](https://github.com/plotly/plotly.js/blob/bc5726c420b20b300827173e39d42cc5a2bef510/src/components/fx/hover.js#L865) is basically the [length of the current axis](https://github.com/plotly/plotly.js/blob/bc5726c420b20b300827173e39d42cc5a2bef510/src/components/fx/hover.js#L846)).

One way to solve this could be to allow labels to spill out of the current axis, at least into the associated x-axis, but possibly also into other subplots or even into the margins of the plot.
