### ISSUE TITLE
Plotly.js is not height responsive

### ISSUE THREAD

**Issue by MarcSkovMadsen** [plotly/plotly.js#5270]
I'm using Plotly.js via Python. I'm also a user of other plotting libraries like Bokeh, Vega/ Altair and Echarts. And I can see that the responsiveness functionality of plotly.js is just not as robust, fast and seamless as the others.

The one thing where I can point to a reproducible example right now is height responsiveness. 

If you take the example at https://plotly.com/javascript/responsive-fluid-layout/ you can see its not height responsive.

This is a major problem if you want to make responsive layouts. For example for mobile. But also if you want to put Plotly inside resizable divs and similar.

![plotly-not-resizable](https://user-images.githubusercontent.com/42288570/99026729-ee058680-256b-11eb-8408-846804f03119.gif)

**Comment by MarcSkovMadsen** [comment]
#### Additional Context

You can experiment with the behavior of Plotly vs other plotting libraries here. 

App: https://awesome-panel.org/streaming-plots
Code: https://github.com/MarcSkovMadsen/awesome-panel/blob/master/application/pages/streaming_plots/streaming_plots.py

![plot-not-responsive-streaming](https://user-images.githubusercontent.com/42288570/99027525-bd265100-256d-11eb-890c-5a30ab535c8d.gif)

Echarts also have a problems. But those where on Panels side and have been solved in the Panel Master branch.

**Comment by MarcSkovMadsen** [comment]
## Additional Context 2

Another reproducible example can be found here https://github.com/holoviz/panel/issues/1770#issue-740981139

![98850094-87da1000-2454-11eb-9c74-be10e8e5914c](https://user-images.githubusercontent.com/42288570/99028761-edbbba00-2570-11eb-80af-81621cfae0dd.gif)

**Comment by Erhannis** [comment]
I think the problem is that the `div`'s height wraps to its contents.  If I open the debugger and set `height` to `100%` on the plot div, and every element above it (back up to and including `<html>`), the plot does resize height.

**Comment by MarcSkovMadsen** [comment]
Thanks. I can see adding height 100% is the solution. Thanks
