### ISSUE TITLE
Question: Will Plotly.js get Plotly Express?

### ISSUE THREAD

**Issue by Alex-Monahan** [plotly/plotly.js#5271]
Hi All!

We are just getting started using Plotly.js and it is great so far! We are building a self-service analytics platform with it, so we are trying to keep things as simple as we can for our users.

I looked through the issues and couldn't find an answer to this. Are there plans or a way to use the power of plotly express in plotly.js? It would greatly simplify things for is, as we are intending to build a wrapper around plotly that does a similar (but not nearly as full featured) abstraction.

Thanks!
-Alex

**Comment by nicolaskruchten** [comment]
Hi Alex! I'm glad you like Plotly Express :) 

There are no plans to port this to Javascript at the moment, no... PX relies heavily on stuff that exists mostly in Python only like Pandas dataframes etc, which just aren't available or mature in JS.

**Comment by sebastianvitterso** [comment]
Just a follow-up - does that mean that plots such as TreeMap just aren't (and won't be) available to in the JavaScript library?

**Comment by gvwilson** [comment]
Hi @sebastianvitterso - it isn't on our roadmap. If someone from the community can contribute a PR, we'd be happy to review. thanks - @gvwilson
