### ISSUE TITLE
Missing colors in bar legend having a colorscale

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#5285]
Originally reported in https://github.com/plotly/plotly.js/pull/1289#issuecomment-728275102 by @nitramwin
[Minimal codepen](https://codepen.io/MojtabaSamimi/pen/MWexGwp?editors=0010)

**Comment by nicolaskruchten** [comment]
So the problem here is that the legend item is black instead of whatever the middle of the color scale is.
