### ISSUE TITLE
Mapbox Max/Min Zoom and bounds

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#5296]
For many applications it would be good to be able to set bounds on where the user can pan and zoom mapbox maps: https://docs.mapbox.com/mapbox-gl-js/example/restrict-bounds/ and  https://docs.mapbox.com/mapbox-gl-js/api/map/#map#setmaxzoom

**Comment by nicolaskruchten** [comment]
See also https://github.com/plotly/plotly.js/issues/3434 and the related cartesian #1876

**Comment by beautah** [comment]
I've come up with this as a python workaround, could be easily adaptable to js. 

lats and longs are lists of all the coordinates.

`

    zoom_lat = abs(abs(max(lats)) - abs(min(lats)))  

    zoom_long = abs(abs(max(longs)) - abs(min(longs)))

    zoom_factor = max([zoom_lat,zoom_long])

    if zoom_factor < 0.002:

        zoom_factor = 0.002

    auto_zoom = -1.35 * math.log(float(zoom_factor)) + 7

`

**Comment by jacksongoode** [comment]
@archmoj I'm not sure if the bounds provide the same effect min/max zoom. Mapbox mention that there are some performance benefits by setting min/max zoom levels https://docs.mapbox.com/help/troubleshooting/mapbox-gl-js-performance/#filter-by-zoom-levels.
