### ISSUE TITLE
Horizontal Legend below the chart

### ISSUE THREAD

**Issue by prog8** [plotly/plotly.js#53]
I couldn't find any way to configure legend to be placed under the chart in a single line. It would be nice if Plotly makes it possible to move the legend below the chart.

**Comment by etpinard** [comment]
@prog8 correct. plotly.js legends don't offer much in terms of customization. 

You can move the legend using `layout.legend.x` and `layout.legend.y`, but there's no way to place the items horizontally at the moment.

**Comment by prog8** [comment]
Is it planned to make legends more customizable in nearest future? If yes do you know any estimates?

**Comment by czellweg** [comment]
For anybody wanting to place the legend under the chart, one way to achieve this would be like so:

    layout: {
    ....
      legend:{
        xanchor:"center",
        yanchor:"top",
        y:-0.3, // play with it
        x:0.5   // play with it
      }
    }

You can also check out the effects of the x/yanchor and x/y values on https://plot.ly/plot: plot a graph, then change Layout -> Horz Position, Vert Position, Horz anchor, Vert anchor.

**Comment by prog8** [comment]
Yes but this doesn't change the legend layout. Legend entries are always one below another. They are never in the same line.

**Comment by buremba** [comment]
+1

**Comment by mbonaci** [comment]
Yes, this one is crucial when working in tight places :)
:+1:

**Comment by otisg** [comment]
Another +1

**Comment by mikehenken** [comment]
+1

**Comment by vcbin** [comment]
+1

**Comment by jackgolding** [comment]
+1 Overlap with twin y-axis is my main gripe atm with Plot.ly

**Comment by Wramberg** [comment]
+1

**Comment by n-riesco** [comment]
@etpinard I'm thinking of the following API for this feature:

```json
layout: {
    legend : {
        orientation: 'horizontal' | 'vertical'
    }
}
```

**Comment by etpinard** [comment]
@n-riesco I'd vote for 

layout: {
    legend : {
        orientation: 'h' | 'v'
    }
}
```

similar to bar [`orientation`](https://github.com/plotly/plotly.js/blob/d117e92409d8d25c59295bc3288b813f7c22b4e6/src/traces/bar/attributes.js#L27).

**Comment by mdtusz** [comment]
:arrow_up: agreed, but only for the sake of consistency with the existing style.

**Comment by ptoche** [comment]
I came here after receiving the following message: 

    Warning message:
    plotly.js does not (yet) support horizontal legend items 
    You can track progress here: 
    https://github.com/plotly/plotly.js/issues/53

I do not usually receive this warning message. In a ``ggplot2`` object processed by ``plotly`` I set ``guides(colour = guide_legend(ncol=1))``, clearly requesting a vertical legend (not a single-line horizontal legend), which works as expected.  I came to this issue as directed by the warning message and see this issue is now closed: Is this warning still relevant? Thanks.

**Comment by alexcjohnson** [comment]
@cpsievert ^^ ?

**Comment by mikkokotila** [comment]
Is there any update on this?

**Comment by marwin1991** [comment]
![image](https://user-images.githubusercontent.com/25181517/51075354-88ec5b80-168a-11e9-979c-7f5b3d84e6c4.png)

legend is coverd by x-axies label

**Comment by mikkokotila** [comment]
@marwin1991 Try something like this > `{legend: {x: 0.35, y: 5, orientation: 'h'},`

**Comment by marwin1991** [comment]
legend : {
                            orientation: 'h',
                            y:-0.15
                        },

this helps

**Comment by usser123** [comment]
Horizontal legend is not working for me. Is this a bug ?

**Comment by MikkoHaavisto** [comment]
When I set the legend to 'h', but it only moves the legend title to the side, the variable legends are still vertically aligned. I couldn't get one below the other.

Is this feature working for someone?

**Comment by nicolaskruchten** [comment]
Yes, this works for me: https://codepen.io/nicolaskruchten/pen/JjENwZZ?editors=0010 ... it looks like this:

![newplot](https://user-images.githubusercontent.com/203523/113495878-80c6a380-94c2-11eb-8c42-6c9192ecae7f.png)
