### ISSUE TITLE
Heatmap zsmooth=fast bug

### ISSUE THREAD

**Issue by lomereiter** [plotly/plotly.js#530]
Seems that [this](https://github.com/plotly/plotly.js/blob/v1.10.2/src/traces/heatmap/plot.js#L328) line is the offending one, `n` instead of `imageWidth` should solve the problem, though I'm too lazy to check that.

Compare zmooth='fast' vs 'best'/false here: https://jsfiddle.net/hnbyn502/

**Comment by etpinard** [comment]
This indeed looks like a bug. Thanks for the report!

Moreover, I've just noticed that we don't have any image test mocks for `zsmooth: 'fast'`:

![image](https://cloud.githubusercontent.com/assets/6675409/15296748/c3fb70ae-1b64-11e6-8b50-2869aaae53c2.png)
