### ISSUE TITLE
Uncaught TypeError: Cannot read property 'match' of null when clicking any options in the ModeBar

### ISSUE THREAD

**Issue by SnowNooDLe** [plotly/plotly.js#5304]
```json
"plotly.js": "^1.55.2"
"react": "^16.13.1"
"react-plotly.js": ^"2.5.0"
```

I am using react-plotly.js for our project. (in React)

I haven't modified much on this ModeBar (image below)

![image](https://user-images.githubusercontent.com/7849113/100391239-b7fdf180-3097-11eb-9e08-80a02099c51a.png)

Added only two configs to the ModeBar

```javascript
config={{
          displayModeBar: true,
          toImageButtonOptions: {
            filename: "something",
          },
        }}
```
It doesn't always happen but time to time, by clicking one of the options from the ModeBar, it still does the job without crashing the app but in console, it prints the following errors.

![image](https://user-images.githubusercontent.com/7849113/100391407-33f83980-3098-11eb-9d94-9b9639fa0f7f.png)

Right after I created this issue, just refreshed the app and went over exact same steps but no warning message this time.

I am quite new to React and this error message only comes from ModeBar buttons so I am assuming it's something to do with plotly.js library?

**Comment by archmoj** [comment]
Thanks for the report.
@SnowNooDLe could you provide a minimal demo please? 
You may simply start by forking [this codepen](https://codepen.io/MojtabaSamimi/pen/yrMxEV?editors=0010).

**Comment by SnowNooDLe** [comment]
@archmoj Hey, thanks for the comment and I briefly created one
[Plotly Demo](https://codepen.io/SnowNooDLe/pen/OJRPPqQ)

Pretty much structure is same, except less data as we pull data from API
And it doesn't happen here so perhaps I could link the video if it's okay?
(The video will probably show only part of the screen, E.g. plotly.js and console and show what happens when I click the options in modebar?)

**Comment by SnowNooDLe** [comment]
@archmoj Hey, in case you want to watch it.
[YouTube - Video Demo](https://youtu.be/2-4mXoaiTBY)

**Comment by archmoj** [comment]
> @archmoj Hey, thanks for the comment and I briefly created one
> [Plotly Demo](https://codepen.io/SnowNooDLe/pen/OJRPPqQ)
> 
> And it doesn't happen here so perhaps I could link the video if it's okay?

If it could not be replicated in codepen, then maybe it's not a `plotly.js` bug.

**Comment by SnowNooDLe** [comment]
> > @archmoj Hey, thanks for the comment and I briefly created one
> > [Plotly Demo](https://codepen.io/SnowNooDLe/pen/OJRPPqQ)
> > And it doesn't happen here so perhaps I could link the video if it's okay?
> 
> If it could not be replicated in codepen, then maybe it's not a `plotly.js` bug.

Thanks for checking it tho, I will keep an eye on this and see how this goes.
