### ISSUE TITLE
Plot sizing issue in 1.58.0 release

### ISSUE THREAD

**Issue by dmbarry86** [plotly/plotly.js#5314]
The 1.58.0 release yesterday has changed (broken) some sizing behaviour we have in bullet charts. It appears that heights are not correct.

In releases prior to 1.58.0 we had a plot which looked like this:
![image](https://user-images.githubusercontent.com/8976377/101156279-44705d00-3620-11eb-999a-983589c0b576.png)

When updating to 1.58.0 the same plot code now looks like this:
![image](https://user-images.githubusercontent.com/8976377/101156315-54883c80-3620-11eb-8f2e-630533a54858.png)

We are specifying widths and heights in the layout but it seems like they are not being adhered to in 1.58.0.

I have created a codepen which demonstrates the issue. In the codepen, if you change the plotly import version from 1.58.0 to a prior version, e.g. 1.57.0 then you will see the expected behaviour.
https://codepen.io/dmbarry86/pen/qBabyNa

**Comment by archmoj** [comment]
Thanks for the report and clear codepen.
It could be also replicated even without `react`.
So here is [the minimal codepen](https://codepen.io/MojtabaSamimi/pen/zYKrJba?editors=1010).

**Comment by dmbarry86** [comment]
Thanks for the quick fix @archmoj. I have just tested 1.58.1 release and can confirm the issue is now resolved 👌

**Comment by archmoj** [comment]
> Thanks for the quick fix @archmoj. I have just tested 1.58.1 release and can confirm the issue is now resolved

dmbarry86
Thanks for your report and clear codepen!
AS a side note I noticed you added `axis` to the trace but it is not used as it should  be in `gauge` object similar to https://github.com/plotly/plotly.js/blob/master/test/image/mocks/automargin-narrow-indicator.json

**Comment by dmbarry86** [comment]
> > Thanks for the quick fix @archmoj. I have just tested 1.58.1 release and can confirm the issue is now resolved
> 
> dmbarry86
> Thanks for your report and clear codepen!
> AS a side note I noticed you added `axis` to the trace but it is not used as it should be in `gauge` object similar to https://github.com/plotly/plotly.js/blob/master/test/image/mocks/automargin-narrow-indicator.json

Thanks for pointing that out. I have just double checked our actual component code and axis is correctly part of the gauge object. Whilst stripping down our component code in to a codepen example I think axis got misplaced.
