### ISSUE TITLE
strange ticklabelposition behaviour

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#5321]
In this pen: https://codepen.io/nicolaskruchten/pen/PoGzzbK

1. the x range doesn't leave room for the y labels so they overlap the data
2. the y range expands seemingly more than necessary for the x labels

**Comment by nicolaskruchten** [comment]
Looks like for the y labels / x range, we don't leave any space when `mode="lines"`

**Comment by nicolaskruchten** [comment]
the two-line labels here should be top-aligned with each other so the months all read straight across

**Comment by archmoj** [comment]
> the two-line labels here should be top-aligned with each other so the months all read straight across

Only on the x-axis when `side` is *bottom*?

**Comment by alexcjohnson** [comment]
> Only on the x-axis when `side` is bottom?

Good point - same thing happens when `ticklabelposition` is the default `outside` and `side` is `'top'`. I'd consider it a bug in both cases.
![Screen Shot 2020-12-07 at 11 21 21 AM](https://user-images.githubusercontent.com/2678795/101376252-5a7b5900-387e-11eb-8bed-b307d81196e1.png)
