### ISSUE TITLE
tick / ticklabel mismatch with period positioning

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#5337]
In this pen, you see that the tick and tick label are positioned oddly with respect to each other: https://codepen.io/nicolaskruchten/pen/yLaVVXa

**Comment by alexcjohnson** [comment]
That's as intended - the label has precision of 1 month so the offset is 1/2 month. dtick is 3 months, so the offset is 1/6 of the tick spacing.

**Comment by nicolaskruchten** [comment]
Ah I see. Another way to look at it is that in this case the ticklabel is correctly centered but wider than the period it represents.
