### ISSUE TITLE
[Feature Requested]: Sunburst direction

### ISSUE THREAD

**Issue by DaniMori** [plotly/plotly.js#5341]
Similarly to the [Rotation or starting point](https://github.com/plotly/plotly.js/issues/4728), a `direction` argument (with values `"clockwise"` (by default) and `"counterclockwise"`) would be desirable.

**Comment by thierryVergult** [comment]
Please note that a _sort_ (boolean) parameter was added recently to Sunburst trace. By setting that parameter to false, you can order the data at your end, in the direction desired.

> [sunburst sort](https://github.com/plotly/plotly.js/pull/5164)

**Comment by usser123** [comment]
In relation to this issue, I tried to add the line 'sort': False in the trace of a Plotly sunburst chart. However, it does not seem to work. The order of labels in the chart was not the order in the dataframe. The order seemed to be changed by Plotly.

Is there any ETA for this issue ?

**Comment by xeladsn** [comment]
Did you try to build your figure with `graph_objects` and not `plotly express` ?

It seems that Plotly applies an unwanted sort on `path` columns when using `px.sunburst`.

**Comment by usser123** [comment]
@xeladsn, I am using the Plotly Express generated meta data but creating the sunburst by using that meta data in graph_objects. Based on this link:

[https://stackoverflow.com/questions/61241172/plotly-how-to-create-sunburst-subplot-using-graph-objects/61245407#61245407](url)

Any idea, how to get the sort disabled ?

**Comment by xeladsn** [comment]
@usser123 I would recommend using the graphs_objects and not Plotly Express to create your sunburst trace if you want to keep the data order. Here is a simple example why with the image below (data order is ['a', **'c', 'b'**, 'd']) : 

![sunburst_order](https://user-images.githubusercontent.com/19688493/125654795-70770fdc-43de-492b-90b0-05135a051325.png)

Plotly Express appears to reorder the data fore the column named `cat`.

As this odd behavior does not relate to the current topic let's create a new issue if you confirm that `sort=False` works well for your use case if you use graph_objects.

**Comment by usser123** [comment]
@xeladsn, I am using Plotly Express generated labels and parents in my graph_objects chart. It is quite laborious to specify labels and parents in graph_objects directly.  So the issue does exist for me.

The issue for this already exists in github:
https://github.com/plotly/plotly.js/pull/5164

**Comment by xeladsn** [comment]
The issue you mentions (https://github.com/plotly/plotly.js/pull/5164) was related to the order for the sunburst trace. It is already fixed and merged. The re-ordering that appears for your use case is related to Plotly Express only, and not to the sunburst trace `sort` attribute (see image attached in my last message).

I think you can't disable that custom ordering when using Plotly Express. This is an issue, but should be addressed separately as it seems to be unrelated to the sunburst trace `sort` attribute.

**Comment by usser123** [comment]
Ok, I did not realize that re-ordering and sort are different things. In that case, yes this is a separate issue.

**Comment by nickriches** [comment]
Really interested in getting the sorting to work properly on this.

**Comment by Skrattoune** [comment]
Is there any advance there?

This is extremely annoying that the default displaying order is counterclockwise ... as most people on earth are used to ... clockwise as the default functioning for about everything (starting with clocks)

This is definitively a very different topic than "sorting"
The easily visible issue is that when sorting is enabled, data are sorted counterclockwise ... instead of the cross-industry standard which is  ... clockwise !

**Comment by nicolaskruchten** [comment]
There is no "advance" to be reported here, no. Things advance when people step up to work on them and no one has done so to date. Expressing your annoyance at the status quo does not particularly encourage anyone to do so either.

**Comment by nicolaskruchten** [comment]
I'll note that it kind of seems like the issue being reported here is with Plotly Express' behaviour, not Plotly.js' ... this might be a better fit for a Plotly.py issue: https://github.com/plotly/plotly.py/

**Comment by Skrattoune** [comment]
> There is no "advance" to be reported here, no. Things advance when people step up to work on them and no one has done so to date. Expressing your annoyance at the status quo does not particularly encourage anyone to do so either.

No annoyance ;-) I'm new to Plotly and find it super cool.
Just want to know the status because I had spent a lot of time on understanding what was my problem ... until I finally made it here.

Happy to help solve the problem if I can as I have a real need there.



> 'll note that it kind of seems like the issue being reported here is with Plotly Express' behaviour, not Plotly.js' ... this might be a better fit for a Plotly.py issue: [plotly/plotly.py](https://github.com/plotly/plotly.py/)

I'll have a look, thanks

**Comment by nicolaskruchten** [comment]
OK. Here is where Plotly Express converts between the input data frame and the structure which `go.Sunburst` requires. Any changes to how things are sorted would need to be made here. https://github.com/plotly/plotly.py/blob/master/packages/python/plotly/plotly/express/_core.py#L1543

**Comment by DaniMori** [comment]
> I'll note that it kind of seems like the issue being reported here is with Plotly Express' behaviour, not Plotly.js' ... this might be a better fit for a Plotly.py issue: https://github.com/plotly/plotly.py/

Actually I opened this issue because I was working with the R plotly package; I understood this behavior affected the whole plotly.js library, but maybe I got confused with the R package interface... Is that so?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
