### ISSUE TITLE
Time Actions Bar Plot

### ISSUE THREAD

**Issue by CarlosAmaral** [plotly/plotly.js#5343]
Hi,

I was trying, without success, to plot a 24 hours (Y axis) time series plot that would display the time of actions in minutes (x axis - 0 to 60 min). Also if the action exceeded 1 hour (e.g. started at 01:00 and ended at 02:15, the data point would carry to the next X axis and consequently be connected. Please check the example below. I'd greatly appreciate help regarding this. Thank you.  
 
![Screen Shot 2020-12-15 at 9 42 08 AM](https://user-images.githubusercontent.com/12385793/102176911-d4819280-3ebb-11eb-93a3-65ccc9920c05.png)

**Comment by nicolaskruchten** [comment]
This sort of "wrapping" is not a feature of Plotly.js at the moment, so your upstream code will have to explicitly split the bars and model the wrapping.
