### ISSUE TITLE
plotly_legenddoubleclick never fires if plotly_legendclick return false

### ISSUE THREAD

**Issue by mmakrzem** [plotly/plotly.js#5350]
I would like to wire my own event handling when the legend is single clicked or double clicked.

I created the following demo: https://codepen.io/mmakrzem/pen/wvzdVaM

Notice that only the plotly_legendclick event triggers when I single or double click in the legend.  The plotly_legenddoubleclick event never fires (because the plotly_legendclick is returning false).

If I double click I also wouldn't expect the plotly_legendclick event to fire.

**Comment by ttrinidad** [comment]
There is a timer there that tries to debounce it, here: https://github.com/plotly/plotly.js/blob/master/src/components/legend/draw.js#L371

 It seems the default should be 300ms (https://github.com/plotly/plotly.js/blob/master/src/plot_api/plot_config.js#L171), but you can try changing it through `config.doubleClickDelay`

**Comment by mollybsmith-noaa** [comment]
I'm also experiencing this behavior (plotly_legenddoubleclick never fires if there's a custom handler for plotly_legendclick), and I don't think it's related to the double click delay, as I set that to 5 seconds and the problem persisted.

**Comment by archmoj** [comment]
Fixed by #6727.

**Comment by vedvalsangkar** [comment]
As of Plotly.js v3.0.1, I am facing this issue again. If I do not write a function for `plotly_legendclick` I have a successful trigger for `plotly_legenddoubleclick`. But I cannot handle double click if single click callback is declared.
