### ISSUE TITLE
[Feature Request] Allow ordering items by value for unified x hovermode

### ISSUE THREAD

**Issue by mayeut** [plotly/plotly.js#5362]
At the moment, it seems that order of items is hardcoded in the following line:
https://github.com/plotly/plotly.js/blob/4ce0c8bff1d80c0d17a91233883f883696ad8836/src/components/fx/hover.js#L1043

It would be great to allow ordering items by value for `unified x` `hovermode` as mentioned in comments https://github.com/plotly/plotly.js/issues/4477#issuecomment-590945637 and https://github.com/plotly/plotly.js/issues/4477#issuecomment-590995134.

Current behavior sample:
<img width="585" alt="Capture d’écran 2020-12-26 à 17 35 32" src="https://user-images.githubusercontent.com/9768336/103155728-9e3cf080-47a2-11eb-81f2-bec4181171d3.png">

Desired behavior sample:
<img width="583" alt="Capture d’écran 2020-12-26 à 17 32 42" src="https://user-images.githubusercontent.com/9768336/103155736-ba409200-47a2-11eb-9a0d-26b629f4e8c6.png">

**Comment by mayeut** [comment]
Might mitigate #4786 in some cases (like the one showed above).

**Comment by miranda-luna-db** [comment]
Hi @nicolaskruchten @chriddyp @ndrezn - Any plans to take a look here soon? Right now we're stuck between a choice of (a) covering up the x-axis value on hover but having data nicely sorted and (b) displaying x-axis value but losing data sort.

**Comment by nicolaskruchten** [comment]
It's not a bad idea, we could add a flag that would control this behaviour but no one on our team is looking at this at the moment, no. We'd accept a pull request for someone who wanted to implement it though!

**Comment by nlyle01** [comment]
Chiming in to agree with @mayeut; Ordering tooltip by trace value rather than legend order would be super cool

**Comment by vicn1222** [comment]
I am also looking for this feature and stumble on this thread. Has this been implemented yet? Thanks.

**Comment by JeromeC-B** [comment]
For me, with plotly js, in the plot config, with hovermode = "x", it works.

**Comment by KacemKhaled** [comment]
plotly==5.24.1 the functionality is still not there
Can you please re-open this issue?

**Comment by gvwilson** [comment]
@KacemKhaled reopened, but we have no plans to implement this - we'd be happy to prioritize review of a PR from the community. thanks - @gvwilson
