### ISSUE TITLE
Icicle / Flame charts

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#5369]
We could use a new trace type for [`icicle` charts](https://observablehq.com/@d3/icicle), basically sunbursts that aren't circular but instead grow either up (flame chart) or down (like physical icicles) or sideways (good for text!).

We'd want the API and capabilities (animation, uniformtext etc) to be very similar to `sunburst` and we might even want to grab the `pathbar` from `treemap`. We'll want a `direction` attribute to control the orientation.

**Comment by pgkirsch** [comment]
Sibling issue in the plotly.py repo: plotly/plotly.py#2878 :)

**Comment by nicolaskruchten** [comment]
This issue has been tagged with `NEEDS SPON$OR`

A [community PR](https://github.com/plotly/plotly.js/pulls?q=is%3Apr+is%3Aopen+label%3A%22type%3A+community%22) for this feature would certainly be welcome, but our experience is deeper features like this are difficult to complete without the Plotly maintainers leading the effort.

**Sponsorship range: $12k-$17k**

What Sponsorship includes:
- Completion of this feature to the Sponsor's satisfaction, in a manner coherent with the rest of the Plotly.js library and API
- Tests for this feature
- Long-term support (continued support of this feature in the latest version of Plotly.js)
- Documentation at [plotly.com/javascript](https://plotly.com/javascript/)
- Possibility of integrating this feature with Plotly Graphing Libraries (Python, R, F#, Julia, MATLAB, etc)
- Possibility of integrating this feature with Dash
- Feature announcement on [community.plotly.com](https://community.plotly.com/tag/announcements) with shout out to Sponsor (or can remain anonymous)
- Gratification of advancing the world's most downloaded, interactive scientific graphing libraries (>50M downloads across supported languages)

Please include the link to this issue when [contacting us](https://plotly.com/get-pricing/) to discuss.
