### ISSUE TITLE
2d and 3d subplots overlap

### ISSUE THREAD

**Issue by kcf-jackson** [plotly/plotly.js#538]
It seems 'scatter3d' doesn't respect the 'domain' specification and result in overlapping with another plot.

2d-2d plots work fine: http://codepen.io/cfkwok/pen/ONGaNL
2d-3d plots overlap partially: http://codepen.io/cfkwok/pen/QNPJNN
3d-3d plots overlap completely: http://codepen.io/cfkwok/pen/QNPJKN

Thanks.

**Comment by etpinard** [comment]
To specify the domain of 3d scene, you need to set the `layout.scene.domain.x` and `layout.scene.domain.y` attributes. 

See http://codepen.io/etpinard/pen/KzLwZe
