### ISSUE TITLE
plot type histogram2dcontour with heatmap contours renders slow

### ISSUE THREAD

**Issue by alexcastillo** [plotly/plotly.js#541]
Hi,

I've created a `histogram2dcontour` plot and when using the heatmap contours settings, it renders very slowly compared to when used without said settings:

``` js
contours: {
      coloring: 'heatmap'
}
```

I'm currently updating the plot data around 30 times per second. Any ideas?

Alex

**Comment by etpinard** [comment]
This ticket is due vague (no reproducible example, no sample data given) to remain open. 

Improving performance is always a priority for us. Hopefully the upcoming `extendTraces` perf work (planned in https://github.com/plotly/plotly.js/issues/2358) will help out this particular use case.
