### ISSUE TITLE
Need to remove the transparency in radar chart bg color

### ISSUE THREAD

**Issue by naresh-FD** [plotly/plotly.js#5418]
![image](https://user-images.githubusercontent.com/50324374/104916035-82022d00-59b7-11eb-95fd-0931f15ae9d9.png)

Is there any option to removing remove the opacity of the green highlighted portion in the radar chart ??

**Comment by alexcjohnson** [comment]
You can set an explicit `fillcolor`

**Comment by naresh-FD** [comment]
no am giving the Hexa and also tried with RGBA color code only but on load am getting the same.
![image](https://user-images.githubusercontent.com/50324374/105125253-f0eb9d00-5b01-11eb-989a-90520316ce59.png)

**Comment by alexcjohnson** [comment]
Not inside `marker` - you're not using markers here at all, only lines and fill. Your trace should look something like:
```
{
  r: [...],
  theta: [...],
  mode: 'lines',
  fill: 'toself',
  line: {color: '#006600'},
  fillcolor: '#006600'}
}
```
https://plotly.com/javascript/reference/scatterpolar/#scatterpolar-fillcolor
