### ISSUE TITLE
[bug] cannot show gauge threshold when value is 0

### ISSUE THREAD

**Issue by kenchan13** [plotly/plotly.js#5428]
Hi! I want to set the threshold value in gauge. There is no problem with positive and negative number except '0'.
I checked plotly.js issues and stackoverflow and there is no solution right now. 

https://codepen.io/kenchan13/pen/mdrgPBK?editors=1010

Thanks

**Comment by antoinerg** [comment]
Thanks @kenchan13 for the very clear bug report!
