### ISSUE TITLE
Relayout of range on y axis removes left and right borders of plot

### ISSUE THREAD

**Issue by jneilliii** [plotly/plotly.js#5442]
After generating a line plot, if you use relayout to add a range to y axis and set autorange: false the left and right borders of the plot get removed. Here's an example jsfiddle.

https://jsfiddle.net/pkbgvjmL/

Relevant layout options and line traces in link above; based on the `Styling a Line Plot` example from the docs. 

```
var layout = {
	autosize: true,
	showlegend: false,
	xaxis: { type:"linear", automargin: true, title: {standoff: 0},linecolor: 'black', linewidth: 2, mirror: true},
	yaxis: { type:"linear", automargin: true, title: {standoff: 0}, linecolor: 'black', linewidth: 2, mirror: true },
	margin: { l:35, r:30, b:0, t:20, pad:5}
};
```
relayout command used
```
Plotly.relayout('myDiv',{yaxis: {autorange: false, range: [0, 300]}
```

**Comment by alexcjohnson** [comment]
When you use `relayout` that way you're replacing the entire `yaxis` object with the new one that only contains `{autorange: false, range: [0, 300]}`, deleting all the other values you started with. What you want instead is:

```js
Plotly.relayout('myDiv',{'yaxis.range': [0, 300]})
``` 
The `autorange: false` will be inferred from this, but if you prefer you can also do:
```js
Plotly.relayout('myDiv',{'yaxis.range': [0, 300], 'yaxis.autorange': false})
```

This behavior is described in https://plotly.com/javascript/plotlyjs-function-reference/#plotlyrestyle - specifically the section about "attribute strings"

**Comment by jneilliii** [comment]
Thank you so much, that worked as expected.
