### ISSUE TITLE
Investigate upgrading mathjax in v2

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#5452]
We can certainly upgrade to 2.7.9 and drop 2.3, especially if we can get this into our v2 release. In fact in a perfect world we'd upgrade to MathJax v3 in plotly.js v2, but I assume that'll be more than a one-afternoon change, so not something we can do right now.

_Originally posted by @alexcjohnson in https://github.com/plotly/plotly.js/issues/5374#issuecomment-770001225_

**Comment by archmoj** [comment]
cc: #5395 
@antoinerg could you please explore the possibility?

**Comment by nicolaskruchten** [comment]
@archmoj could you please explore this? @antoinerg is busy on other projects ATM :)
