### ISSUE TITLE
radar name overlapping in names (theta )

### ISSUE THREAD

**Issue by naresh-FD** [plotly/plotly.js#5454]
![image](https://user-images.githubusercontent.com/50324374/106426645-fe9f0c00-648b-11eb-96d2-72651ac82cc4.png)
tried to add margin and padding but no luck

**Comment by nicolaskruchten** [comment]
This is a real problem for which we don't have a good solution beyond adding `<br>`s in your tick label names and possibly tweaking the font sizes.
