### ISSUE TITLE
Closure Compiler fails with duplicate member "cool" error

### ISSUE THREAD

**Issue by taschukMax** [plotly/plotly.js#5457]
When trying to use Closure Compiler it fails with the following error:

`Class or object literal contains duplicate member "cool". In non-strict code, the last duplicate will overwrite the others.
  16739| 	"cool":[{"index":0,"rgb":[0,255,255]},{"index":1,"rgb":[255,0,255]}]`

When reviewing non minified version of plotly it does contain 2 "cool" keys

**Comment by archmoj** [comment]
Nice catch!
Reported in https://github.com/bpostlethwaite/colormap/issues/27

**Comment by taschukMax** [comment]
@archmoj thanks for picking this up!
