### ISSUE TITLE
Individual negative values discarded in pie chart

### ISSUE THREAD

**Issue by justin-sleep** [plotly/plotly.js#5481]
It looks like negative values are dropped when constructing pie charts, probably to prevent negative sums ([example](https://codepen.io/justin-sleep/pen/dyOXJmx?editors=1010)). I think [this](https://github.com/plotly/plotly.js/blob/dc3c342f346bd6effad210414f377345fe3e2d47/src/traces/pie/calc.js#L42) is the line responsible for this behavior, and that it could be fixed by checking for negative values in the sums rather than checking the individual points.

**Comment by alexcjohnson** [comment]
Good call @justin-sleep - the negative exclusion predates automatic aggregation, and was never updated to be done after the sums are complete.
