### ISSUE TITLE
A new "npm run" target for building custom bundles

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#5484]
I'd like a straightforward set of instructions that a user can use to:

1. Create `my-custom-bundle.js` based on something like `lib/index-basic.js`
2. Run `npm run build-custom-bundle my-custom-bundle.js` and it would produce `my-custom-bundle.min.js` or whatever

This is needed so as to be able to provide clear instructions to Dash developers that want to make their own bundles :)

**Comment by nicolaskruchten** [comment]
The custom-bundle build instructions should be documented in https://github.com/plotly/plotly.js/blob/master/BUILDING.md, as this is what I'm linking to from dash-docs for "custom-built bundle".

**Comment by archmoj** [comment]
Right now `scatter` trace (puls `cartesian` subplots) are added to every bundle by default.
Do you think it should not be added by default for custom bundles?

**Comment by alexcjohnson** [comment]
If a bundle without scatter works, then yes. But I think it was put in core originally because otherwise something or other would break.
