### ISSUE TITLE
Legendrank attribute in traces

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#5501]
A new attribute in all traces called `legendrank` which defaults to the index of the trace in the `data` array. The legend items will then be sorted by `legendrank` (ties broken by index in the `data` array) before being laid out.

As an example for:

```
data = [
{name: "A", legendrank: 2}
{name: "D", legendrank: 4, legendgroup: "G2"}
{name: "E", legendrank: 4, legendgroup: "G2"}
{name: "B", legendrank: 1, legendgroup: "G1"}
{name: "C", legendrank: 3, legendgroup: "G1"}
]
```

then I would expect the legend order to be: `G1(B,C), A, G2(D,E)`.

Note that the group order matters in the example above, when this will be coupled with #5260 and/or `legendgroupgap`.

**Comment by nicolaskruchten** [comment]
Notes:
* should be a number (floats and negatives OK)
* default should be 1000
* tie breaker is trace order as modulated by `legend.traceorder` i.e. 'reverse' reverses the tie-break

**Comment by ryan-williams** [comment]
For future searchers: I couldn't get legendrank to work; turns out I was inadvertently using plotly.js 1.x. This feature landed somewhere in the 2.x line.

**Comment by gonthalo** [comment]
> For future searchers: I couldn't get legendrank to work; turns out I was inadvertently using plotly.js 1.x. This feature landed somewhere in the 2.x line.

This worked for me, thanks!
