### ISSUE TITLE
Gridlines which would intersect inside tick labels should not be drawn

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#5502]
As discussed in the meeting, let's just call this a bug, and suppress any gridlines/ticks/ticklabels whose position is within the bounding box of any inside tick labels. Resolving this should resolve some cases of https://github.com/plotly/plotly.js/issues/5404

**Comment by nicolaskruchten** [comment]
Some additional context for this issue:
* the core idea is that nothing should occlude or interfere with the inside tick labels, so that means gridlines *and* zerolines. Note that axis base lines don't interfere with the labels or ticks, so they can stay
* the secondary idea is that nothing distracting should be drawn within the same extent even if it doesn't intersect, so no tick labels or ticks should appear on the X axis if they would appear below the inside tick labels on the Y axis. This is pretty straightforward in non-period-positioned cases: hide the gridlines and their ticks and labels
* One tricky edge case would be with Y labels on the inside *right* with X labels in period-positioning mode: it would be quite possible to get a gridline that does *not* intersect the inside labels but its ticklabel would be drawn underneath them. In this case we should *keep* the gridline but *drop* the label.

**Comment by nicolaskruchten** [comment]
Addendum: for that final case, we should drop the label only if its *centerline* will intersect the y tick labels. That's more in keeping with the style guide in question.

**Comment by archmoj** [comment]
I noticed showing data without *zerolines* could be misleading in most cases.

**Comment by nicolaskruchten** [comment]
can you provide an example plz?

**Comment by archmoj** [comment]
> can you provide an example plz?

For example:

![hideZeroLines](https://user-images.githubusercontent.com/33888540/111502140-f4735d00-871b-11eb-9215-4b9a920f6224.png)

**Comment by nicolaskruchten** [comment]
fair enough. That seems unlikely-enough to be the developer's intent that I'm OK with this behaviour.

**Comment by nicolaskruchten** [comment]
I used the artifact from this branch in this pen https://codepen.io/nicolaskruchten/pen/BaLGYeW?editors=0010 (couldn't save because the URL is too long) and it seemed like the right-most ticklabel didn't disappear early enough as I panned. It seemed like it disappeared when its centerline hit the edge of the plot rather than the left edge of the inside ticklabel bounding boxes.

**Comment by archmoj** [comment]
This is fixed by #5550.

**Comment by archmoj** [comment]
> This is fixed by #5550.

Here is a [codepen using master](https://codepen.io/MojtabaSamimi/pen/WNRZELq?editors=1000).

**Comment by nicolaskruchten** [comment]
Thanks! Do you have a pen that demonstrates this one?

> * One tricky edge case would be with Y labels on the inside right with X labels in period-positioning mode: it would be quite possible to get a gridline that does not intersect the inside labels but its ticklabel would be drawn underneath them. In this case we should keep the gridline but drop the label.

**Comment by archmoj** [comment]
> Thanks! Do you have a pen that demonstrates this one?
> 
> > * One tricky edge case would be with Y labels on the inside right with X labels in period-positioning mode: it would be quite possible to get a gridline that does not intersect the inside labels but its ticklabel would be drawn underneath them. In this case we should keep the gridline but drop the label.

Good call.
Here is [the codepen for the case of period](https://codepen.io/MojtabaSamimi/pen/WNRZELq?editors=0010).
So it looks we need another PR to handle that period edge case.
