### ISSUE TITLE
No option for tickformat with '(' (parentheses) sign

### ISSUE THREAD

**Issue by OmriAroesti** [plotly/plotly.js#5511]
As specified [here](https://plotly.com/javascript/tick-formatting/#using-tickformat), the formatting is described as the same as d3's formatting language. 

However, the [d3 documentation this points to](https://github.com/d3/d3-format/blob/master/README.md#locale_format) mentions that "the sign can be... **( - nothing for zero or positive and parentheses for negative**.".

This option, however, is not available to plotly.js. 
I see that the `d3_format_re` is in fact `/(?:([^{])?([<>=^]))?([+\- ])?([$#])?(0)?(\d+)?(,)?(\.-?\d+)?([a-z%])?/i`, and does not include the "`)`" along with "`+`", "`-`" and "` `"(space), so it defaults back to `-`.

**Comment by nicolaskruchten** [comment]
This is likely because Plotly.js uses an older (v3) version of `d3_format`. We will be able to upgrade to the latest formatter soon :)

**Comment by alexcjohnson** [comment]
Right - until we manage to upgrade `d3-format`, the docs should really be pointing to the d3v3 version of the package, as we do in some of the attribute docstrings:

https://github.com/plotly/plotly.js/blob/cfa7720cafb61ff71b8991e37e5b248230624091/src/constants/docs.js#L4

**Comment by nicolaskruchten** [comment]
@archmoj we can close this one right?

**Comment by archmoj** [comment]
Resolved by #5125.
