### ISSUE TITLE
CLI details for custom bundle script

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#5521]
My feeling is that we need the following kinds of flags:

* `--traces` for the trace list
* `--out` for the target file
* `--sourcemaps=false` (boolean, default false)

This will allow us to eventually add in other flags like `--calendars=false` or `--include-scatter=false` or whatever

**Comment by archmoj** [comment]
Thanks! 
Do you think we could & should rely on [minimist](https://www.npmjs.com/package/minimist) when handling the input arguments, or not?

**Comment by nicolaskruchten** [comment]
Your call, I'm not that stressed about it. There are many arg parsers out there in the world. It's nice to have something that generates `-h` help text automatically but it's not a hard requirement for me

**Comment by archmoj** [comment]
> Do you think we could & should rely on [minimist](https://www.npmjs.com/package/minimist) when handling the input arguments, or not?

@alexcjohnson any suggestion?
