### ISSUE TITLE
Performance of Plotly.js when plotting 180k+ datapoints

### ISSUE THREAD

**Issue by saadbinabid786** [plotly/plotly.js#553]
Dear Plotly.js committers,
I am very new to plotting time-series graphs and currently working on a dashboard that is totaly relying on Plotly.js. I have csv files that are having data poins (timestamps, values) around 180k+ to be rendenred using plotly.js line graph. I am using Plotly.plot() function to render the graphs. It takes around 18 seconds to plot the data points 23k+ at the moment which is kind of slow. In between the browser stops responding as well. I want to know is there are way through which I can make it fast. I look forward to your kind response.
Many thanks in advance,
Saad

**Comment by mdtusz** [comment]
The best you can do without bringing your data size down will be to make sure you are using the GL variants of plots (e.g. `scattergl`).

Beyond that, the best optimization you can make is to simply use a more coarse granularity of your data - for example if you have time series data, reduce the effective sampling rate that you are plotting.
