### ISSUE TITLE
add_trace for dotplot not working

### ISSUE THREAD

**Issue by diggydetroit** [plotly/plotly.js#555]
I tried reproducing the dot plot example on plotly website here, https://plot.ly/r/dot-plots/

This is what I got

![test2](https://cloud.githubusercontent.com/assets/19480442/15412651/f2a66c88-1dee-11e6-9998-fa5821bd8ee6.png)

Looks like add_trace function is not working like its supposed to.

**Comment by cpsievert** [comment]
Thanks @diggydetroit. That code is assuming an old version of the R package. The problem is explained here, and we'll be updating the docs soon -- https://github.com/plotly/documentation/issues/387

**Comment by diggydetroit** [comment]
Thanks
