### ISSUE TITLE
(x|y)hoverformat

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#5552]
All traces that support `(x|y)period` should also support `(x|y)hoverformat` which is the formatting that will be applied to the x or y value when it appears in any hoverlabel: unified, compare (both point and axis, thereby overriding `(x|y)axis.hoverformat`) and closest.

**Comment by archmoj** [comment]
It looks we shouldn't apply this format on `date` axes.
What are the other cases?

**Comment by archmoj** [comment]
Also to mention the `zhoverformat` is used in `heatmap` and `contour` for numbers:
https://github.com/plotly/plotly.js/blob/623fcd1fea9d9bfb86e5e0d44d8047cd8636881c/src/traces/heatmap/attributes.js#L114-L123

**Comment by archmoj** [comment]
> It looks we shouldn't apply this format on `date` axes.
> What are the other cases?

Nevermind. That will works for `date` axes.

**Comment by nicolaskruchten** [comment]
Yes, date axes are most of the reason for this, so it will work with periods :)

**Comment by archmoj** [comment]
In addition to traces covered by #5563, it is possible to add this option for `heatmapgl`, as well as `gl3d` traces.

**Comment by jxu** [comment]
Is this what changed in v2.0.0 the marker text in scatterplot to show (x,y) instead of just y?

**Comment by nicolaskruchten** [comment]
In v2 we did change the default hover mode from "x" to "closest" yes. The feature described in this issue works with all hover modes.

**Comment by archmoj** [comment]
> Is this what changed in v2.0.0 the marker text in scatterplot to show (x,y) instead of just y?

@jxu No please see #5647. Alternatively you can set `hovermode: 'x'` with v2.
