### ISSUE TITLE
Rename "in progress" labels to "has TODOs"

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#5557]
Looking at pull requests https://github.com/plotly/plotly.js/pulls IMO the `in progress` PRs should really be labeled as something like `has TODOs` simply because they are not necessarily in progress but have some TODOs.

![inProgress](https://user-images.githubusercontent.com/33888540/111639376-94d78900-87d1-11eb-818e-e1e18a0d2002.png)

**Comment by nicolaskruchten** [comment]
I'd be fine with dropping that label altogether. Any open PR is by definition "in progress" :)
