### ISSUE TITLE
Zoom In causes ticks overlap axis label even with automargin

### ISSUE THREAD

**Issue by quantum-noise** [plotly/plotly.js#5567]
Example: https://codepen.io/quantum_noise/pen/GRrpGPq
Steps to reproduce:
- Zoom a chart somehow.

xaxis label is visible:
![Screen Shot 2021-03-26 at 10 50 20](https://user-images.githubusercontent.com/9678185/112439574-55251a00-8d5a-11eb-9f31-7ed68147faf6.png)
After zoom xaxis label is overlapped:
![Screen Shot 2021-03-26 at 10 50 51](https://user-images.githubusercontent.com/9678185/112439568-548c8380-8d5a-11eb-82e4-170545f7bdf6.png)

**Comment by hannahker** [comment]
I've tested this out a bit further and it does seem to be present in other cases when the axis has a title. Even before zooming (in the first screenshot) this doesn't seem to be working properly: 

![Screen Shot 2022-09-06 at 3 49 25 PM](https://user-images.githubusercontent.com/25990216/188726024-83dd1b86-fa67-4d21-b3a9-e9e76035d6dc.png)

And then after zooming it's still buggy:

![Screen Shot 2022-09-06 at 3 49 52 PM](https://user-images.githubusercontent.com/25990216/188726073-6b564839-cb6c-4921-a012-cedc96e251a4.png)
