### ISSUE TITLE
rangeslider doesn't update if range is changed using array

### ISSUE THREAD

**Issue by jdugge** [plotly/plotly.js#557]
If the range of a plot with a rangeslider is changed using `Plotly.relayout(gd, {'xaxis.range': [3,9]});` or `Plotly.relayout(gd, 'xaxis.range', [3,9]);`, the rangeslider doesn't update to reflect the changed range.

However, when using `Plotly.relayout(gd, {'xaxis.range[0]': 3, 'xaxis.range[1]': 9});`, both the main plot and the rangeslider get updated correctly.

[Reproducible example on codepen](http://codepen.io/anon/pen/BKXyqQ?editors=1010)

**Comment by mdtusz** [comment]
Interesting bug. This is very likely to do with the way relayout updates are handled - the attribute strings are deconstructed and the updates are "flagged" based on the attributes (in a less-than-perfect way).

Thanks for reporting - we'll likely have a fix this week and in the next release.

**Comment by mdtusz** [comment]
Interesting bug. This is likely to do with [this section](https://github.com/plotly/plotly.js/blob/master/src/plot_api/plot_api.js#L2440) - the way updates are handled as strings is very imperfect at the moment and could benefit from some work to make it more robust and generalized (hopefully using [`Lib.objectFromPath`](https://github.com/plotly/plotly.js/blob/master/src/lib/index.js#L506).

Thanks for reporting though and we'll likely have a fix later this week for the next release.
