### ISSUE TITLE
Heatmap ignores zmin/zmax when using shared coloraxis object?

### ISSUE THREAD

**Issue by JobLeonard** [plotly/plotly.js#5576]
I have a somewhat complicated use-case that results in having these two requirements for the same plot:

- I need to be able to construct multiple heatmaps using a shared coloraxis, to ensure they are on the same color scale
- I need to be able to override the domain of the z-values these heatmaps, regardless of the domain of the input data

On a simple heatmap I would typically use `zmin` and `zmax` for the second requirement:

![image](https://user-images.githubusercontent.com/259840/113302475-60e78200-9300-11eb-9d14-c40ce1fc366c.png)

https://codepen.io/JobLeonard/pen/oNBZNWp

However, if I use a shared coloraxis the `zmin` and `zmax` configurations are ignored:

![image](https://user-images.githubusercontent.com/259840/113302508-6a70ea00-9300-11eb-8a44-2f3df67ac6f1.png)

https://codepen.io/JobLeonard/pen/jOyBNjR

Now, I can understand that if I add three different traces with different `zmin`/`zmax` properties then that would directly conflict with the idea of a shared coloraxis. But shouldn't it be possible somehow to add a zmin/zmax to the `coloraxis` object instead? I don't see any documentation suggesting how to do this.

(I do have a workaround in mind for this, which would be manually clipping all `z` values to the `zmin`/`zmax` domain, and providing a `text` array with the unclipped values so that the hover values are still correct. But if there is a less "hacky" way of doing this that I'm missing I'd like to know)

**Comment by nicolaskruchten** [comment]
Yes, you can configure the min/max of the coloraxis with `layout.coloraxis.(cmin|cmax)`: https://plotly.com/javascript/reference/layout/coloraxis/

**Comment by JobLeonard** [comment]
So I tried that yesterday, and it didn't work, but looking at the commit it appears that I added a `coloraxis.colorbar.cmin` instead of `coloraxis.cmin` (and equivalent `cmax`), which explains why it didn't do anything. It works now, thanks!
