### ISSUE TITLE
Bug: npm package for plotly.js-strict-dist is gone

### ISSUE THREAD

**Issue by stevenhao** [plotly/plotly.js#5577]
This link is broken: https://www.npmjs.com/package/plotly.js-strict-dist

It is linked to from https://github.com/plotly/plotly.js/blob/master/dist/README.md

![image](https://user-images.githubusercontent.com/1988030/113459435-5691ba80-93ca-11eb-99c2-a07ce7f8f172.png)

**Comment by stevenhao** [comment]
Seems https://cdn.plot.ly/plotly-strict-latest-v2.min.js is down to (Access Denied)

**Comment by nicolaskruchten** [comment]
Sorry about this... the `strict` bundle isn't released yet, although the readme-generation code did include it in the readme. the `strict` bundle will be released in a few weeks along with v2.0 of the library. See https://community.plotly.com/t/plotly-js-2-0-is-coming-soon/50055/5 for details.

**Comment by stevenhao** [comment]
Understood, thanks!

**Comment by archmoj** [comment]
Fixed by `v2.0.0-rc.1`.
