### ISSUE TITLE
Bug: Rogue Line in scatterplot in some environments

### ISSUE THREAD

**Issue by alexander-alvarez** [plotly/plotly.js#558]
it seems there's a regression:

v1.9.0:

![image](https://cloud.githubusercontent.com/assets/11779993/15451439/6f589862-1f90-11e6-94a9-2602dfeca329.png)

v.1.10.0-v1.11.0
![image](https://cloud.githubusercontent.com/assets/11779993/15451427/004afbea-1f90-11e6-9e82-80c55eea9d20.png)

using `git bisect` I narrowed it down to: https://github.com/plotly/plotly.js/commit/b6d993006264a6f5e66b9f8d519f7eb44a2e46ea

not sure what information I can provide to better help out, but just let me know so I can help out.

**Comment by mdtusz** [comment]
That commit was part of a branch that removed the remaining nested `<svg>` tags for compatibility with Illustrator, so the structure of plots needed to be changed a bit, so it's very possible I missed something in the logic that creates the `clipPath` for the plot. Could you provide the sample data/layout you used to produce this and I'll look into it ASAP.

**Comment by mdtusz** [comment]
That commit was part of a branch that was removing the remaining nested `<svg>` tags for compatibility with Adobe Illustrator. It required changing from a `<svg>` tag that was constrained by it's `viewBox` to a `<g>` tag that has an associated clip - it's most likely that the clip is being miscalculated in the scenario provided.

Could you share the data and layout you have used for this example so we could reproduce? I can't seem to make a (not) working example myself.

**Comment by alexander-alvarez** [comment]
so trying to reproduce it in a fresh environment and no luck...
http://codepen.io/anon/pen/reXdVV

After the `Plotly.relayout()` it seems things go AWOL

would styling/position not captured here affect this?

**Comment by mdtusz** [comment]
It's _possible_, but unlikely. Are you on the most recent release for your local environment? It looks as if the clip is not being properly set on the plot `<g>` element. Which browser are you using? I didn't see any significant inconsistencies when implementing the clip, but it's very possible I may have overlooked something - any extra info will be helpful to debug.

**Comment by alexander-alvarez** [comment]
Running: Chrome 49.0.2623.110 under Linux and Mac

seems like it might be a clip issue:
when [this](https://github.com/plotly/plotly.js/blob/master/src/traces/scatter/line_points.js#L53) gets called during relayout, I get negative x values for the points that render to the left of the axes: 

what attributes on objects / functions should i be looking at pertaining to the 'clip'
I see this, but not sure if it's what i want.
https://github.com/plotly/plotly.js/blob/716a621d70616d9fdd8ae565bbcebc3a60eaa6ce/src/plot_api/plot_api.js#L2916

**Comment by mdtusz** [comment]
That is the correct plot clip - unfortunately they're a bit tricky to debug because you can't just add a border to them 😛  

I still haven't been able to reproduce this, so any more information you come across will be helpful.

**Comment by alexander-alvarez** [comment]
Sorry for the radio silence... just not much I know how to do.
Where would I look for to debug the clip / what sort of values would I expect to give me radically 'off the charts' lines?

We're pinned to 1.9.0 indefinitely until we figure this out or it magically goes away. :(

**Comment by dev-oups** [comment]
I am facing this problem using Plotly in an Angular 2 application.
I am using the # anchor in the URL to manage client routing.

The element g with class="plot" has a wrong clip-path property.
It contains the full page URL: "url(http://127.0.0.1:43422/#/workspace/studies#clip8a724bxyplot)".
Replacing it with "url(#clip8a724bxyplot)" will solve the problem.

Please let me know if it can be fixed, thanks.

**Comment by etpinard** [comment]
> I am facing this problem using Plotly in an Angular 2 application.

Interesting. Can you share a reproducible example in a codepen / jsFiddle / jsBin to help us debug?

**Comment by dev-oups** [comment]
Here it is:
- open a hero details view
- move on the x axis to see traces moving outside the plot

http://plnkr.co/edit/KzOqZY2MYBPX7MmHIZ6V?p=preview

**Comment by etpinard** [comment]
@dev-oups Thanks very much for that example!

Here's the problematic [block](https://github.com/plotly/plotly.js/blob/0fc99c6f7cc29cb037ed270f8afa5474a1bb2784/src/components/drawing/index.js#L557-L573) which I believe was put in the support Angular 1 (cc @alexcjohnson ) a few years ago.

Obviously, this solution isn't working for all environments. So, instead of determining whether or not to prefix the clip paths URLs with `window.location.href` based on `<base>`, maybe we should make this a config option e.g. `clipPathPrefix`?

**Comment by etpinard** [comment]
Oh I think I know what's the problem. For your page 

```js
window.location.href === 'http://127.0.0.1:43422/#/workspace/studies'
```

which contains a `#`, which (must, right?) conflicts with the `#` that precedes the clip path id.

So perhaps replacing `window.location.href` with

```js
window.location.origin + window.location.pathname
```

would do the trick.

Copying a few colleagues that might know more about this subject @bpostlethwaite @mdtusz

**Comment by etpinard** [comment]
A potential fix has been merged in https://github.com/plotly/plotly.js/pull/1203 hence closing this issue.

Once plotly.js `v1.21.0` is out, please let us know if it indeed resolved your issues.

**Comment by dev-oups** [comment]
OK thanks.

However this code brings a big limitation as mentioned in the comment the chart is not portable no more.
I just wonder why the document location is used when a base element is found and there is no comment on this specific line of code which cause the limitation.
(the base href value is "/" in most of Angular2 applications)
