### ISSUE TITLE
Invalid text on the logarithmic axis

### ISSUE THREAD

**Issue by nikita-zamaraev-loginom** [plotly/plotly.js#5585]
Plotly config:

```js
var data = [{
  type: "scatter",
  y: [2, 5, 3, 2.5],
  mode: 'text+lines+markers',
  texttemplate: "%{y}"
}];

var layout = {
    yaxis: {
        type: 'log'
    }
};
```

Example on codepen - https://codepen.io/x-base/pen/LYxOwBR

Expected text - `2`, `5`, `3`, `2.5`,  
but I see `Math.pow(y)` - `100`, `100k`, `1000`, `316.2278`.

**Comment by nicolaskruchten** [comment]
Yikes, thanks for the bug report!
