### ISSUE TITLE
SSL certificate expired for JSON editor

### ISSUE THREAD

**Issue by bbkane** [plotly/plotly.js#5587]
https://plotly-json-editor.getforge.io/ is linked to from https://plotly.com/chart-studio-help/json-chart-schema/ , so I figured it's official. It looks like the SSL certificate expired Wed, 31 Mar 2021 06:48:07 GMT

**Comment by nicolaskruchten** [comment]
Thanks for letting us know! We should update those docs :)

**Comment by bbkane** [comment]
🤷
