### ISSUE TITLE
commit plot-schema like a baseline?

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#5588]
What if we treated the final plot schema like a baseline? You'd have to generate it and commit it in any PR that changes it, otherwise the build would fail, and then the review process would explicitly review the changes to the schema. This would catch situations where we add something to e.g. axes and it impacts axes in indicator, color bars etc etc.

@alexcjohnson thoughts? cam from a chat with @archmoj ... can discuss at the next meeting

**Comment by alexcjohnson** [comment]
Great idea! In our call today @archmoj and I discussed having the dev build process (`npm start`) generate a copy of the schema in the `build` folder, and committing that one, so that the version in `dist` stays in sync with the rest of the published files.

**Comment by nicolaskruchten** [comment]
Oh yes the version in `dist` should stay in sync! `build` is still a bit nebulous for me, but it sure seems like a reasonable place for this :)
