### ISSUE TITLE
Legend title in horizontal mode is misaligned and ambiguously sized

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#5595]
![image](https://user-images.githubusercontent.com/203523/115421714-2e77c900-a1ca-11eb-99f6-008c2dbfde1f.png)

Maybe we need new values for `legend.title.side` like "middle left" and "top center"?

We also have a typography-hierarchy problem where the legend title by default is the same size as the legend items, and is smaller than e.g. the axis title size. So maybe we need to make the legend title (and colorbar title!) size the same as xaxis.title.size as well to avoid ambiguity. And/or implement #4646 and just make all the titles bold, like the way Vega does it.

**Comment by nicolaskruchten** [comment]
To be honest, even just setting the default legend/colorbar title font size to 14 improves things a lot IMO:

![image](https://user-images.githubusercontent.com/203523/115464001-70206800-a1fa-11eb-9e48-bfd8cdf1e923.png)

**Comment by nicolaskruchten** [comment]
@alexcjohnson we played with various permutations of increasing the font size as in this PR and bolding it and bolding with no change to font size or a smaller change to font size and all things considered, I still favour bumping the font size defaults for legend and colorbar titles (all orientations) to exactly match the logic we have for axis titles.

**Comment by nicolaskruchten** [comment]
Here are three variants we looked at. I favour "big"

![newplot (1)](https://user-images.githubusercontent.com/203523/116633013-6d262580-a926-11eb-8906-7b0d5f569b1d.png)
![newplot (2)](https://user-images.githubusercontent.com/203523/116633016-6e575280-a926-11eb-8bad-2d0f1db8fcae.png)
![newplot (3)](https://user-images.githubusercontent.com/203523/116633020-6eefe900-a926-11eb-9ae5-7261d2611f39.png)

**Comment by alexcjohnson** [comment]
OK, "big" is fine. I still somewhat prefer "small and bold" I think, as a way to better disambiguate the title from the trace names, but that would be a pretty big visual change to push on people as a new default. The vertical misalignment I still think should be treated simply as a bug, having font size "fix" it seems awfully fragile - does the "fix" still work if you make `layout.font.size` bigger or smaller?

**Comment by nicolaskruchten** [comment]
OK re "big" for now.

> does the "fix" still work if you make layout.font.size bigger or smaller?

First thing I checked, and no. I think we should merge a version of https://github.com/plotly/plotly.js/pull/5611 that implements the size changes, and then actually tackle this alignment problem for real. We do need to have a conversation about what we want this alignment to be, though, and it's pretty tricky to spec out given various permutations of "legend title could be multiple lines", "there could be multiple rows of legend items" and "trace names could be multiple lines". Input needed!
