### ISSUE TITLE
Upgrade to modern JS like es6 or es7

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#5596]
I don't even know what the right name is any more, but basically modernize our codebase to enable folks who never learned ES5 to contribute :)

My main question now is: is such an upgrade so mechanical that it's zero-risk and we can just do i in a patch or minor? Or are we sufficiently worried that we *should* do it in the 2.0 cycle just in case it shakes something loose?

**Comment by nicolaskruchten** [comment]
We could even just start using a transpiler... we don't **need** to change much of our code so long as we accept the new idioms :)

**Comment by alexcjohnson** [comment]
The only concern I have about doing this in a minor is if it will break the build of someone downstream who imports plotly.js from source. If we're worried about that it could be worthwhile doing a minimal version of this in v2.0 including a transpiler and at least one change somewhere in the core that depends on transpiling.

**Comment by nicolaskruchten** [comment]
That's a thought!

**Comment by archmoj** [comment]
Adressed by #6909.
