### ISSUE TITLE
modebar can't be hidden with multiple traces

### ISSUE THREAD

**Issue by mheilman** [plotly/plotly.js#56]
It looks like the mode bar can't be hidden in line charts with more than one trace (though it works fine for single trace charts).

Here's a minimal example:

```
<html>
<body>
  <div id="plotly-div"></div>
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
<script>

var trace1 = { x: [0, 1], y: [4, 5], type: "scatter"};
var trace2 = { x: [0, 1], y: [4, 5], type: "scatter"};
//var data = [trace1];  // This works: the mode bar gets removed.
var data = [trace1, trace2];  // This doesn't work: the mode bar remains.
Plotly.plot('plotly-div', data, {}, { displayModeBar: false });

</script>
</body>
</html>
```

I looked through the code a bit and thought that perhaps this has something to do with [this comment](https://github.com/plotly/plotly.js/blob/216599856f6757333c34c29fb2f3786f8f02cf9b/src/plot_api/plot_api.js#L2466).

**Comment by etpinard** [comment]
Bug confirmed. Thanks for reporting.

The problem is in the modebar manager. The logic [here](https://github.com/plotly/plotly.js/blob/master/src/components/modebar/manage.js#L30) isn't quite right.

Working on a fix now.

**Comment by mheilman** [comment]
Amazing.  Thanks!.
