### ISSUE TITLE
explicit axes ranges don't work with log scales

### ISSUE THREAD

**Issue by rhamner** [plotly/plotly.js#5606]
Here is a reproducing example:

https://codepen.io/rhamner/pen/NWdeRXz

They work fine with autorange. Weird also...if you just manually edit the axes, it works fine so it doesn't only work for autorange.

Plotly version is https://cdnjs.cloudflare.com/ajax/libs/plotly.js/1.58.4/plotly.min.js, and tested on current chrome.

**Comment by nicolaskruchten** [comment]
Indeed, for log axes the range is expected to be the exponent, meaning 10 for the upper end maps to 10 billion = 10^10.

**Comment by rhamner** [comment]
@nicolaskruchten that works. Thanks.
