### ISSUE TITLE
mutating the [[Prototype]]

### ISSUE THREAD

**Issue by GuestXY** [plotly/plotly.js#561]
I have the current version (v1.11.0) of plotly.js from dist folder.
In the Firefox console is the following output:

mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create plotly.js:3419:3

Looks like the buffer module from node.js fault.

3418: 
```
if (Buffer.TYPED_ARRAY_SUPPORT) {
  Buffer.prototype.__proto__ = Uint8Array.prototype
  Buffer.__proto__ = Uint8Array
  if (typeof Symbol !== 'undefined' && Symbol.species &&
      Buffer[Symbol.species] === Buffer) {
    // Fix subarray() in ES2016. See: https://github.com/feross/buffer/pull/97
    Object.defineProperty(Buffer, Symbol.species, {
      value: null,
      configurable: true
    })
  }
} else {
  // pre-set for values that may exist in the future
  Buffer.prototype.length = undefined
  Buffer.prototype.parent = undefined
}
```

![unbenannt](https://cloud.githubusercontent.com/assets/19550595/15501647/e7d55b5c-21ae-11e6-8653-f2f56386d440.PNG)

**Comment by etpinard** [comment]
As you pointed out, this is an issue with browserify browserifying `buffer` using the npm `buffer` [module](https://github.com/feross/buffer).
