### ISSUE TITLE
ScrollZoom behavior as 1:1 ratio for both axis 

### ISSUE THREAD

**Issue by wchen85** [plotly/plotly.js#5621]
Is there anyway we can add a configuration for scrollzoom: true to scroll 1:1 ratio when mouse is on xaxis/yaxis like scrolling in the middle of the chart?
I know we can scroll in the middle of the chart and get the behavior, but some user wants to be able to do 1:1 ration when mouse is on xaxis or yaxis 
Maybe we can add some property like scrollzoomXaxis: false which means when mouse is on xaxis it scroll like the mouse is in the middle of the chart?

Thank you
https://codepen.io/pen/

**Comment by alexcjohnson** [comment]
If you know the aspect ratio you want for the chart ahead of time, you can use `scaleanchor` (and `scaleratio` if the aspect ratio is not 1:1) https://codepen.io/alexcjohnson/pen/mdRNYBN

**Comment by wchen85** [comment]
If aspect ratio is 1:1, do I just simply add s scaleanchor?

> If you know the aspect ratio you want for the chart ahead of time, you can use `scaleanchor` (and `scaleratio` if the aspect ratio is not 1:1) https://codepen.io/alexcjohnson/pen/mdRNYBN

**Comment by wchen85** [comment]
> If you know the aspect ratio you want for the chart ahead of time, you can use `scaleanchor` (and `scaleratio` if the aspect ratio is not 1:1) https://codepen.io/alexcjohnson/pen/mdRNYBN

Doesxaxis: {scaleanchor: 'y', scaleratio: 2} means 1 (x) : 2 (y)?

**Comment by alexcjohnson** [comment]
Yes, when you set `scaleanchor`, `scaleratio` defaults to 1 - see https://plotly.com/javascript/reference/layout/xaxis/#layout-xaxis-scaleanchor (and `scaleratio` below it)

**Comment by wchen85** [comment]
> Yes, when you set `scaleanchor`, `scaleratio` defaults to 1 - see https://plotly.com/javascript/reference/layout/xaxis/#layout-xaxis-scaleanchor (and `scaleratio` below it)

Thank you very much sir

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
