### ISSUE TITLE
Add modebar buttons control into layout

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#5623]
Let's add a `layout.modebar.buttons = {add: [...], remove: [...] }` attribute to make it easier for folks to force certain buttons (like the to-be-removed hovermode buttons per #5642 or the drawing controls)

**Comment by nicolaskruchten** [comment]
and change hovermode to closest

**Comment by nicolaskruchten** [comment]
So to crisp up a bit what I think should happen in layout... We should add a new key `modebarbuttons` which accepts an object with keys `add` and `remove`, which should in turn accept arrays of strings. These attributes should behave the same way as the existing `config` keys `modebarButtonsToAdd` (in array-of-strings mode only!) and `modebarButtonsToRemove` (i.e. they should follow the same precedence rules we have right now in `config`, whatever they are).

The config should take precedence over whatever is set in the layout, so if the layout adds a button and the config removes it, it should be removed.

**Comment by nicolaskruchten** [comment]
(updated above to reflect the fact that we already have `layout.modebar` ... should this be `layout.modebar.buttons.(add|remove)` or `layout.modebar.(buttonstoadd|buttonstoremove)` ?

**Comment by nicolaskruchten** [comment]
No, config should still win IMO

**Comment by alexcjohnson** [comment]
At some point we may want to expose an equivalent of `config.modebarButtons`, which would be most natural as `layout.modebar.buttons = ["zoom", "pan", ...]`

`layout.modebar.buttons.(add|remove)` is incompatible with that, unless we do something like `buttons.(add|remove|all)`.

`layout.modebar.(buttonstoadd|buttonstoremove)` feels a bit long though. Would it be ambiguous to just use `layout.modebar.(add|remove)`?

**Comment by nicolaskruchten** [comment]
OK for `layout.modebar.(add|remove)`. I don't want to go down the road of `.buttons=[...]` right now because I that's a very static view of things: you have to know all the current defaults to recreate "defaults+add-remove".
