### ISSUE TITLE
Scatter line breaks when xaxis is in millions, while scattergl markers produce ok output on the same dataset

### ISSUE THREAD

**Issue by antonio-piha** [plotly/plotly.js#5629]
Hi all. Thank you for this amazing library. 

I searched through all the issues but couldn't find anything similar. Is this down below a known issue/bug?

Scatter + lines breaks:
![plotly js-scatter-lines](https://user-images.githubusercontent.com/3170126/117087503-904a3e00-ad47-11eb-91aa-8fc975bd911f.PNG)

**Codepen**
https://codepen.io/antonio-piha-the-vuer/pen/NWpKBQz

Scattergl + markers looks ok:

![plotly js-scattergl-markers](https://user-images.githubusercontent.com/3170126/117087519-9dffc380-ad47-11eb-866d-2b42de6fc6a2.PNG)

**Codepen**
https://codepen.io/antonio-piha-the-vuer/pen/WNpegNg

Different output on the same dataset:
Y range [-6000, 6000]
X range [800000, 4099846]

Please help 😃  thank you

**Comment by nicolaskruchten** [comment]
Is your input sorted by the x-value? (Cant load codepen on my phone :)

**Comment by antonio-piha** [comment]
Yup, correct, it was simple sorting issue. Didn't notice on large dataset.
Thank you for your time and help 😄
