### ISSUE TITLE
poor performance of chart layout when data includes rangebreaks

### ISSUE THREAD

**Issue by spasovski** [plotly/plotly.js#5630]
My team detected a significant performance issue with charts when rangebreaks are involved. Example chart at https://codepen.io/spasovski/pen/wvgVRNV and is even better demonstrated at https://jsbench.me/zpko8zmpic/1

This makes the charts quite slow to generate and more specifically update (as would be the case in a ticking chart). The main thread tends to lock up when lots of data points are involved and affects the overall usability of the rest of the page. 

A team member first found the likely culprit at https://github.com/plotly/plotly.js/blob/623fcd1fea9d9bfb86e5e0d44d8047cd8636881c/src/plots/cartesian/set_convert.js#L834 since this then kicks off ax.maskBreaks(), and this only multiplies as the the number of rangebreaks increases.

Please let me know if a performance recording/screenshot would also be of benefit.

**Comment by dsmmcken** [comment]
https://jsbench.me/zpko8zmpic/2

5000 points with 300 range breaks is 99% slower at plotting than with no breaks.

The biggest slow down seems to be doing the dateTime2ms for every point * every range break, so in this case 1,509,346 times for the 5000 points.

**Comment by nicolaskruchten** [comment]
Thanks for flagging this! We'd love a PR if someone wants to take on this optimization work :)
