### ISSUE TITLE
x-unified hover skips a level for data with different lengths

### ISSUE THREAD

**Issue by xenatisch** [plotly/plotly.js#5643]
## Synopsis 
This is rather difficult to describe, but I'll give it a go and use visual aids to convey it. 

Given the following:

- `hovermode: "x unified"`
- There are many data points on the graph - roughly >100. 
- There are two sets of data - i.e. one visualised as bar and one as line - and one of the two ends before the other. 

As you approach the end of the x-axis, the hover jumps one level as the shorter dataset ends.

## Examples 
You can see an example of the issue on our [live service](https://coronavirus.data.gov.uk/details/vaccinations#card-people_who_have_received_1st_dose_vaccinations_by_report_date). There is also an alternative description of the issue in [our repository](https://github.com/publichealthengland/coronavirus-dashboard/issues/332).

The issue basically boils down to this:

In the animation, you can see that when hovering from 3 May to the right, the next point is skipped and then the successive point for 5 May is then displayed. This happens even if you manage to hover exactly over the bar for 4 May.

![screengrab](https://user-images.githubusercontent.com/13240654/117516295-a0a12980-af90-11eb-8599-f2ab5e88a6cd.gif)

## Exceptions
The issue resolves itself if you zoom into the data (x-axis zoom).

## Expected behaviour
The tooltip should be displayed for all successive points and jump one step at a time.

## Additional info
In case it helps, the code for the visualisation can be found [here](https://github.com/publichealthengland/coronavirus-dashboard/blob/v3-development/src/components/Plotter/BasePlot.js).

**Comment by nicolaskruchten** [comment]
I believe that we may have fixed this recently and the fix will be out in v2 (in a week or two). If you could try out the Release Candidate and let me know if it still happens, that'd be great :) A build can be found here: https://cdn.plot.ly/plotly-2.0.0-rc.1.min.js

PS: I'm a big fan of your work and would be happy to chat with you about any other feedback you might have for us :)

**Comment by nicolaskruchten** [comment]
Does our RC fix it? We should have another RC out shortly that might do it if it doesn't :)

**Comment by xenatisch** [comment]
So I tried this locally, and it did work. But to use it in context, I'll need to integrate it into React. That's where things get more complicated when dealing with stand-alone packages... so I left that for when the release is finalised. 

Will let you know how it turns out.

**Comment by nicolaskruchten** [comment]
Great! We're not anticipating any particular challenges or changes with how we interact with React, so 🤞

**Comment by archmoj** [comment]
This is likely fixed or improved by [v2.0.0-rc.2](https://github.com/plotly/plotly.js/releases/tag/v2.0.0-rc.2).

**Comment by nicolaskruchten** [comment]
We just released 2.0 (no longer an RC) if you want to try upgrading :) Let us know if this resolves your particular issue!

**Comment by xenatisch** [comment]
Just integrated v2 in the source code and tested it. Doesn't seem to have made any difference, I'm afraid... unless I'm doing something wrong, which is not impossible given that it's past midnight. 

Here's what I've done:

Updated the version in `package.json` to `"plotly.js": "^2.0.0"` alongside `"react-plotly.js": "^2.5.1"` and ran `yarn install`.

Changed the implementation of the base component for plots to:

```
import Plotly from "plotly.js";
import createPlotlyComponent from 'react-plotly.js/factory';

console.log(Plotly.version)

const Plot = createPlotlyComponent(Plotly);
```
The version is logged as `2.0.0` in the console, and the result is as follows:

https://user-images.githubusercontent.com/13240654/121099821-7e4d3680-c7f0-11eb-896e-92b7ac991701.mov

**Comment by nicolaskruchten** [comment]
Ah that's disappointing. Are you able to extract a minimal test case i.e. a single figure JSON object for us to test against, without needing to boot the rest of your app?

**Comment by xenatisch** [comment]
Sure thing... will do that tomorrow morning.

**Comment by xenatisch** [comment]
Right, I've created a new React project, which only includes the part of our code needed to do visualisation of simple charts. This is really as abstract as I could make it. It is fully self-contained and doesn't rely on external resources - including our API. 

Here's the link to repo: https://github.com/xenatisch/plotly-sample

Hope it helps. Please let me know if I can do anything else.

**Comment by nicolaskruchten** [comment]
OK, I see what's happening. I think the behaviour is very slightly improved in 2.0 but it's still not doing what you'd like. Internally, the scatter trace is taking precedence and because the default `layout.hoverdistance` is 20, there's some radius beyond which it's overriding the bars. I'll think about a better default behaviour a little bit, but in the meatime, for your specific charts which have a fully-dense coverage using bars, I think that setting `layout.hoverdistance=1` or some other small number will get you what you need.

**Comment by xenatisch** [comment]
Thank you. I'll implement that as soon as I can. Will let you know how it goes.

I also agree that the behaviour has marginally improved. It's no longer snappy... if that makes any sense :))

**Comment by nicolaskruchten** [comment]
"no longer snappy" doesn't really sound great, but if you're happier with the behaviour I'll take it ;)

happy to help, and happy to chat with you 1-1 if there's anything else I or anyone on the Plotly team can do to support your important work 💪

**Comment by xenatisch** [comment]
Thank you.
