### ISSUE TITLE
Don't output `console.log`s in production (don't use console.log directly)

### ISSUE THREAD

**Issue by coopy** [plotly/plotly.js#565]
Plotly.js uses raw `console.log` statements to print info, warning, and error messages. Instead, it should use an abstract logger so we can silence warnings in production. Something like https://github.com/FormidableLabs/abstract-log that lets us configure a `null` transport in production for anything but errors.

As an example of this happening, try typing some HTML into the rich annotations editor. Before you've closed the opening tag, [`svg_text_utils.js`](https://github.com/plotly/plotly.js/blob/7774903b8e1fd4690817aed834220c34c5dcb1c7/src/lib/svg_text_utils.js#L39) spews errors for every update.

![open-tag](https://cloud.githubusercontent.com/assets/794843/15519516/b1ec6528-21b6-11e6-9b77-f6ee4d09f32f.gif)

**Comment by etpinard** [comment]
And we should probably add the [`no-console`](http://eslint.org/docs/rules/no-console) eslint rule to the src [`.eslintrc`](https://github.com/plotly/plotly.js/blob/master/src/.eslintrc).

**Comment by n-riesco** [comment]
I was thinking of submitting a PR to replace all the occurrences of `console.log` under `src/` with `lib.log`. Would that be OK?

**Comment by etpinard** [comment]
@n-riesco I think we should at least expose a config [argument](https://github.com/plotly/plotly.js/blob/master/src/plot_api/plot_config.js) so that users that want to see the logs can see them using:

```js
Plotly.plot('graph', data, layout, { verbose: true }):
```

**Comment by mdtusz** [comment]
Agreed on this - probably would be good to swap most `console.log` statements to `Lib.log`, but I still think there are _some_ true errors/warnings that should remain (e.g. things like calling `Plotly.plot` with invalid arguments).

**Comment by etpinard** [comment]
> but I still think there are some true errors/warnings that should remain

maybe throwing errors would be better.

**Comment by mdtusz** [comment]
😑 ... 

Yep.
