### ISSUE TITLE
Deprecate transforms in v2

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#5652]
We should remove `transforms` from the bundles but keep a way to re-include them.

**Comment by nicolaskruchten** [comment]
I think we should not change anything, because we have not been advertising them as "deprecated" but we can start in v2. so I'll remove them from docs and we can mark those attributes as "deprecated" in the schema, but keep them in all the same places they are now bundle-wise

**Comment by archmoj** [comment]
The `transforms` are a registered method (function) on the plotly API.
It appears we cannot "deprecate" `transforms` similar to other data attributes by putting it in a `_deprecated` container.
So I am wondering what is the expected behaviour for deprecating `transforms`?
Just changing the description similar to what we did for `heatmapgl` is enough?
Should `Plotly.validate` pass or it does not matter while there is #4759 bug?!

**Comment by nicolaskruchten** [comment]
Yes, including some deprecation text in the schema attributes is enough for me.

**Comment by Domino987** [comment]
@nicolaskruchten Hello, i was wondering why the transformers were deprecated and if there is a way to include a similar function (filtering data above a threshold) nativly with plotly?

There is of course the possibility to filter the data outside of plotly, but I would assume it could be faster to do it within the lib?

**Comment by chadamski** [comment]
> @nicolaskruchten Hello, i was wondering why the transformers were deprecated and if there is a way to include a similar function (filtering data above a threshold) nativly with plotly?
> 
> There is of course the possibility to filter the data outside of plotly, but I would assume it could be faster to do it within the lib?

I'm also looking for some guidance on why transforms are being deprecated and what the recommended alternate method of handling will be.

**Comment by andoks** [comment]
I would also like to know what alternatives there are to the transform functionality

Also this relates to the deprecation notices change in the docs https://github.com/plotly/graphing-library-docs/commit/8b334a91285ae98717a2f0c499b52c6f873c3298
