### ISSUE TITLE
hover edge cases on period positioned points

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#5656]
Clear improvement. There are three funny cases I want to point out, though we may choose not to do anything about them:

(1) the only place I can put the mouse and NOT get a label for any bar is slightly to the left of a first-of-month scatter point:
![Screen Shot 2021-05-12 at 11 27 01 AM](https://user-images.githubusercontent.com/2678795/118127975-507afa80-b3c8-11eb-97fb-8526d7e5c376.png)
If I put the mouse to the right of this point I do get a bar hover:
![Screen Shot 2021-05-12 at 11 27 09 AM](https://user-images.githubusercontent.com/2678795/118131027-03008c80-b3cc-11eb-9a9b-e2ab885a2d37.png)
This is presumably because the mouse is not over the range of the bar that matches the winning scatter point - so we include the previous bar in our original set of hovered points but then disqualify it because it's inconsistent with the scatter point.
This happens at all month boundaries in `x` mode, but if I switch to `x unified` mode, I see this behavior on the Dec/Jan boundary:
![Screen Shot 2021-05-13 at 8 57 09 AM](https://user-images.githubusercontent.com/2678795/118128925-87054500-b3c9-11eb-9a6e-5ad702bc9930.png)
but not on the Jan/Feb boundary, there I always get the Feb bar no matter where my mouse is:
![Screen Shot 2021-05-13 at 8 57 24 AM](https://user-images.githubusercontent.com/2678795/118128943-8cfb2600-b3c9-11eb-8ea5-41571e988716.png)

(2) When I zoom in enough, there are gaps between scatter points so that none of them are hovered, and only a bar is shown in the hover info. But if I set `xperiod` to 5 days on the scatter trace, I would have expected that no matter how much I zoom in there would be a winning scatter point, because I'm always over the period of one of them. That doesn't happen, in either `x` or `x unified` hovermode. In both modes there's still a gap where I only see the bar's hover.

(3) Except in a very narrow set of conditions, when no matter which scatter gap my mouse is in, the middle scatter point is included in hover data with the bar. I only see this with an `xperiod` on the scatter and in `x` hovermode - not with instant-positioned scatter points and not with `x unified`, and at least in the codepen given there's a very narrow zoom range where this happens, immediately after gaps in the scatter have opened up but before they get too big. Here my mouse is on about Jan 27:
![Screen Shot 2021-05-13 at 8 48 02 AM](https://user-images.githubusercontent.com/2678795/118130818-ca60b300-b3cb-11eb-88f5-5de9fad1d383.png)
(This third point may become moot if we choose to address the second point)

_Originally posted by @alexcjohnson in https://github.com/plotly/plotly.js/pull/5618#issuecomment-840558084_

**Comment by alexcjohnson** [comment]
Closed by #5683
