### ISSUE TITLE
SVG Image Trace Doesn't Show Correctly

### ISSUE THREAD

**Issue by RossSmyth** [plotly/plotly.js#5661]
Hello,
I am attempting to plot an SVG image trace as stated. But when attempted to be plotted, it shows a bizarre looking plot. It looks either much too far zoomed in or out. When the zoom button is hit the axis sets to near the origin and the image is not seen.
[CodePen here](https://codepen.io/rosssmyth/pen/QWpKvEG)
[SVG that is supposed to show (an example with same response)](https://upload.wikimedia.org/wikipedia/commons/1/1a/SVG_example_markup_grid.svg)

**Comment by archmoj** [comment]
@antoinerg if I recall `image` trace only works with image formats e.g. `png`, `jpg`, `gif`, `bmp` and not `SVG`. Correct?

**Comment by antoinerg** [comment]
> @antoinerg if I recall `image` trace only works with image formats e.g. `png`, `jpg`, `gif`, `bmp` and not `SVG`. Correct?

You are right @archmoj! The image trace is meant to display bitmaps (or raster graphics). We should probably add this information to the description of the attribute `image`.

@RossSmyth if you want to draw vector graphics, you can look at https://plotly.com/javascript/images/ (this one is `layout.images` which is not the same thing as the image trace) and https://plotly.com/javascript/shapes/.

**Comment by RossSmyth** [comment]
Cool, thanks for the help.
