### ISSUE TITLE
Slow performance when using minified version while by zooming.

### ISSUE THREAD

**Issue by ramaUptimeAI** [plotly/plotly.js#5667]
The Scatter graph is very crystal clear in points while using the min version but have noticed a performance slowness while zooming or resetting a scatter graph compare to a full-size library.

Min version:  "plotly.js-cartesian-dist-min": "^1.58.4"
Full Size Library Version: "plotly.js": "^1.57.1"

The layout and how we are updating graph

```
layout: {
    title: 'Something',
    hovermode: 'closest',
    showlegend: true,
    legend: { "orientation": "h", x: 0, y: 1.15 },
    annotations: [],
    datarevision: 0,
    height: 400,
    margin: {
      t: 75,
      b: 60
    },
    autosize: true,
    xaxis: {
      //title: 'Time',
      ticks: false,
      autorange: false,
      // range: ['0', '10']
    },
    yaxis: {
      title: 'Something',
      rangemode: 'nonnegative'
      //showticklabels: false
    },
    shapes: []
  }
```
```
 Plotly.newPlot(
      e,
      data,
      layout
    )

```

While zooming or updating the graph by using Plotly.update
```
 Plotly.update(a, data, layout);
```

Min Version Graph
![Screenshot 2021-05-19 at 2 29 52 PM](https://user-images.githubusercontent.com/82371227/118795923-b845af80-b8b8-11eb-8989-11b16005ab29.jpeg)

Full-Size Library Graph: Points are not clear as compare to the min version.
<img width="1368" alt="Screenshot 2021-05-19 at 3 38 09 PM" src="https://user-images.githubusercontent.com/82371227/118796158-f642d380-b8b8-11eb-9e2a-224c323033d9.png">

**Comment by alexcjohnson** [comment]
Any chance you're using the `scattergl` trace type? The `cartesian` bundle doesn't include that, so will fall back on `scatter`, which renders with SVG so will look a little different and has worse performance with lots of points.

The `gl2d` bundle includes `scattergl`.

**Comment by ramaUptimeAI** [comment]
Thanks 👍 . Scatter-gl is working fine with this library "plotly.js-gl2d-dist-min" but heatmap got changed. Do I need to change anything ?.

Layout and Data of Heatmap:
```
export const HeatmapGraphJSON: any = {
    data: [{
        colorbar: { x: 1, thickness: 10 },
        z: [],
        x: [],
        y: [],
        zmin: 0,
        zmax: 0,
        colorscale: [[0, 'rgba(170,255,255, 0.7)'], [0.0000001, '#0a11af'], [0.5, '#c1bcb9'], [1, '#b30d1d']],
        type: 'heatmap',
        connectgaps: false
    }],
    layout: {
        title: 'Heatmap',
        datarevision: 0,
        annotations: [],
        hovermode: 'closest',
        bgcolor: 'rgb(0,0,0)',
        height: 400,
        margin: {
            t: 75,
            b: 60
        },
        autosize: true,
        xaxis: {
            ticks: '',
            side: 'bottom',
            autosize: false
        },
        yaxis: {
            showticklabels: false,
            //automargin: true,
            title: 'Tags',
            ticks: '',
            side: 'left',
            ticksuffix: ' ',
            autosize: false
        }
    }
}
```
Heatmap After using gl2D:
<img width="1351" alt="Screenshot 2021-05-20 at 10 26 40 AM" src="https://user-images.githubusercontent.com/82371227/118921856-8c790700-b956-11eb-9bd8-25d7cde6613c.png">

Heatmap Before:
<img width="1344" alt="Screenshot 2021-05-20 at 10 30 20 AM" src="https://user-images.githubusercontent.com/82371227/118921907-a74b7b80-b956-11eb-814b-53c3c9cb1b79.png">

**Comment by alexcjohnson** [comment]
This file: https://github.com/plotly/plotly.js/blob/master/dist/README.md describes which traces are included in which bundles. Any trace type not included will fall back on `scatter` (which obviously makes no sense for heatmaps!)

Note there's also a complete minified dist package https://www.npmjs.com/package/plotly.js-dist-min

**Comment by ramaUptimeAI** [comment]
Thanks for your response. In gl2d have a heatmapgl type and I've changed the type to heatmapgl from heatmap but getting blur heatmapgl. Is there anything should I need to change in the layout.

Heatmapgl:
<img width="1324" alt="Screenshot 2021-05-21 at 11 43 43 AM" src="https://user-images.githubusercontent.com/82371227/119093164-f82da380-ba2c-11eb-83f5-fd7cc71dff9f.png">

**Comment by ramaUptimeAI** [comment]
@alexcjohnson Is there any update on heatmapgl blured graph?

**Comment by nicolaskruchten** [comment]
Please note that we are deprecating the heatmapgl in the upcoming v2 release.

**Comment by alexcjohnson** [comment]
You can try `zsmooth: false` (which is the default `zsmooth` for regular `heatmap` traces) but as @nicolaskruchten mentions, we're deprecating `heatmapgl` in v2 because it has a number of problems; instead we will work to improve the performance of `heatmap` traces.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
