### ISSUE TITLE
A double click jasmine test fails intermittently on CircleCI

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#567]
This [test](https://github.com/plotly/plotly.js/blob/b5331e391957278059eac89a77e2d7a74575f181/test/jasmine/tests/click_test.js#L633) fails intermittently on CircleCI (see [1](https://circleci.com/gh/plotly/plotly.js/1511), [2](https://circleci.com/gh/plotly/plotly.js/1498)). That's not right.

**Comment by n-riesco** [comment]
I fixed a similar failure not long ago.
I could give a go to fixing this one too.

**Comment by etpinard** [comment]
I haven't seen this test fail on CircleCI in a long time. 

Closing for now.
