### ISSUE TITLE
OpennStreetMap credit

### ISSUE THREAD

**Issue by marado** [plotly/plotly.js#5675]
Hi,

With the introduction of 09343ae841d33c8e5a6c29445730af5db2f19aeb , Plotly maps can use the cartodb-dark style (now carto-darkmatter), and they get credit with "© CARTO", linking to https://carto.com/ .

I am under the impression that attribution is wrong. If I understand correctly, the maps used are stilll OSM's, and to fulfill OSM's credit criteria, credits shoud still be given to the OSM contributors: https://www.openstreetmap.org/copyright .

If I'm reading it right, CARTO seems to agree, as you can see in their own examples: https://carto.com/help/working-with-data/attribution/ .

This should be easilly fixed, with something like:
```
-                attribution: '<a href="https://carto.com/" target="_blank">© CARTO</a>',
+                attribution: '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank">OpenStreetMap</a> contributors, <a href="https://carto.com/" target="_blank">© CARTO</a>',
```

**Comment by nicolaskruchten** [comment]
Thanks for bringing this to our attention!

@archmoj can you please change these defaults for 2.0?
