### ISSUE TITLE
Incorrect hover invariant in period mode

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#5681]
In this pen https://codepen.io/nicolaskruchten/pen/qBrjNLJ?editors=0010 which is based on this morning's master, hovering over the April scatter point pulls in the wrong value for the bar trace (April 1 is not in Q1).

This is a v2 blocker.

**Comment by archmoj** [comment]
This appears to be related to `hovermode: -1` and `period` positions.
Most likely the infinity confuses distance sort.
Simplified [codepen](https://codepen.io/MojtabaSamimi/pen/wvJegGL?editors=1000)
Investigating...
