### ISSUE TITLE
Overflowing the graph in the distribution minified library (plotly-dist-min)

### ISSUE THREAD

**Issue by ramaUptimeAI** [plotly/plotly.js#5687]
I've been facing the issue of graph overflowing when I scroll or zoom.

I'm using: scatter-gl
Library: 'plotly.js-dist-min';

```
layout: {
    title: 'Something',
    hovermode: 'closest',
    showlegend: true,
    legend: { "orientation": "h", x: 0, y: 1.15 },
    annotations: [],
    datarevision: 0,
    height: 400,
    margin: {
      t: 75,
      b: 60
    },
    autosize: true,
    xaxis: {
      //title: 'Time',
      ticks: false,
      autorange: false,
      // range: ['0', '10']
    },
    yaxis: {
      title: 'Something Y',
      rangemode: 'nonnegative'
      //showticklabels: false
    },
    shapes: []
  }
```

![MicrosoftTeams-image](https://user-images.githubusercontent.com/82371227/119773015-afb72f80-bedd-11eb-9c7b-4250e0f7420d.png)

And also is there any difference between ''plotly.js-dist-min' and 'plotly.js-dist' ?

**Comment by nicolaskruchten** [comment]
I'm not sure what you mean by "graph overflowing when I scroll or zoom"... can you elaborate or share an executable example like on CodePen please?

**Comment by ramaUptimeAI** [comment]
Hello @nicolaskruchten, graph overflowing means it's coming out of the boundary. Not only at scroll or zoom even for the first time rendering graph is rendering out of the place.

Without Overflow:
<img width="1312" alt="Screenshot 2021-05-28 at 9 50 04 AM" src="https://user-images.githubusercontent.com/82371227/119928983-45b09000-bf9a-11eb-8898-b402698d2575.png">

With Overflow:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/82371227/119929033-59f48d00-bf9a-11eb-8831-b7242d1afb89.png)

**Comment by nicolaskruchten** [comment]
I'm really sorry, but I'm not understanding the issue here... what part of your screenshot is overflowing? We would need to be able to run an example to be able to help you here :)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
