### ISSUE TITLE
Some readme improvements

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#5710]
* let's rework the headers so that instead of "install from NPM" it's "load via `import` or `require`" and "install from CDN" it's "load via `<script>` tag" which I think is more helpful.
* let's move the MathJax section up out of the Documentation section into the script-tag/CDN section and separately document how to use it with import/require
* let's create a separate LOCALIZATION.md (i.e. move it out of the dist readme) which explains how localization works, and includes information about how to load them via import/require as well as script tags

**Comment by archmoj** [comment]
> * let's rework the headers so that instead of "install from NPM" it's "load via `import` or `require`" and "install from CDN" it's "load via `<script>` tag" which I think is more helpful.

One could use native ES6 `import` in `<script>` now, so those proposed headers may be little confusing.

**Comment by nicolaskruchten** [comment]
show me an example? I think it's pretty clear: "script tag" means "load the specific file via script src="

**Comment by archmoj** [comment]
> show me an example? I think it's pretty clear: "script tag" means "load the specific file via script src="

```html
<script type="module">import "https://cdn.plot.ly/plotly-2.0.0-rc.3.min.js"</script>
```
as well as the example in [this codepen](https://codepen.io/MojtabaSamimi/pen/BaWrdKY?editors=0010)

**Comment by nicolaskruchten** [comment]
OK, but I still think in the context of "import vs script" it's clear... @alexcjohnson thoughts?

**Comment by archmoj** [comment]
> OK, but I still think in the context of "import vs script" it's clear... @alexcjohnson thoughts?

I could be OK with "require vs script" or "npm import vs html import"

On another note the following link is no longer working:
```
Fastly supports Plotly.js with free CDN service. Read more at https://www.fastly.com/open-source.
```
So perhaps we could drop it?

**Comment by alexcjohnson** [comment]
The fastly link still works for me - temporary outage?

**Comment by archmoj** [comment]
> The fastly link still works for me - temporary outage?

It works for me now. Thanks!

**Comment by alexcjohnson** [comment]
The key distinction is whether it's an independent `<script>` tag or part of your build pipeline. So how about "Load via `<script>` tag" vs "Load as a node module"? I think users that don't know what a node module is will recognize that they should use the script tag, and those that have a build pipeline will understand both.

**Comment by archmoj** [comment]
> The key distinction is whether it's an independent `<script>` tag or part of your build pipeline. So how about "Load via `<script>` tag" vs "Load as a node module"? I think users that don't know what a node module is will recognize that they should use the script tag, and those that have a build pipeline will understand both.

Applied in #5713.
