### ISSUE TITLE
x-unified hover tooltips overflow

### ISSUE THREAD

**Issue by xenatisch** [plotly/plotly.js#5721]
## Synopsis

The hover tooltips in x-unified mode exceed max-width and therefore overflow. This happens when:

- the chart is small and close to the sides 
- the chart is large (near width size) on a small screen - e.g. mobile
- the tooltip is displayed for a point on the chart that falls near the mid-point of the x-axis

The issue persists in Plotly v2.0.0.

## Example

You can see an example of the issue on our [live service](https://coronavirus.data.gov.uk/details/vaccinations#card-people_who_have_received_1st_dose_vaccinations_by_report_date), provided that your browser width is smaller than ~580px.

<img width="477" alt="Screenshot 2021-06-08 at 14 52 22" src="https://user-images.githubusercontent.com/13240654/121197442-36b6c100-c869-11eb-8c7c-021c05944a7f.png">

## Expected behaviour

The hover tooltip x-extrema must always fall between x-extrema of the browser. An even better outcome would be for the tooltip to not spill out of the cartesian axes. 

I don't think there's an easy / immediate solution to this, primarily because the tooltip position moves based on cursor position. I suppose one way to address it is to do what folks at Google Charts have done - i.e. move the tooltip until it hits one side, then stop moving horizontally. 

Here's an example, which you've probably seen before:

![google-sample](https://user-images.githubusercontent.com/13240654/121204866-1be74b00-c86f-11eb-86e1-dfa04c625d3d.gif)
[Credit: Google]

Thanks again for all your efforts.

**Comment by nicolaskruchten** [comment]
I actually think this is "just a bug" where the hoverlabel should be on the left-hand side if there is room there. If there not enough room on either side then yes, we will need some new behaviour.

**Comment by nicolaskruchten** [comment]
The hoverlabel looks like it's much more than 1px beyond the edge, though, no?

**Comment by nicolaskruchten** [comment]
Ah I see, this is just a really wide hoverlabel and there is a zone where there is no room on either the left or the right :(

In this case @xenatisch I would recommend using newlines i.e. `<br>` in the hovertemplate if you can on narrow screens? Like before "daily" or something?

**Comment by alexcjohnson** [comment]
Ah right, x unified doesn't seem to have the centered fallback for when there isn't room on either side like closest and x modes have. We should add that. But I was definitely able to get a situation where there was plenty of room on the left for the whole label, yet it was shown on the right side with just 1px border cut off. So I think we should pad it 1px as well.

**Comment by xenatisch** [comment]
So, there are two issues here - one is ours, the other is yours:
- Some of our labels are just too long, and that needs to be fixed. This is something for our content team to think about as the labels are set dynamically. 
- Where the labels aren't toooo long, some of the tooltips still overflow, and that's the topic of this issue. 

In the latter case, as you highlighted eloquently, there is indeed enough space on one side, but the tooltip still overflows *without* using the space that's available. This, however, tends to happen when we're near the mid-point. How close to the mid-point? That would depend on the width of the tooltip itself. 

This clip shows the problem more clearly (I think / hope):

Here's [the link](https://coronavirus.data.gov.uk/details/testing#card-lab-based_testing_and_capacity_by_test_type) to the graph in the clip in case you want to experiment with it yourself.

https://user-images.githubusercontent.com/13240654/121237336-daff2e80-c88e-11eb-999a-9d024969ce39.mov

**Comment by xenatisch** [comment]
Hallelujah. Thanks @nicolaskruchten, @archmoj, and @alexcjohnson. Looking forward to 2.3.0.
