### ISSUE TITLE
`tickformat` doesn't work when `showticklabels` is set to false 

### ISSUE THREAD

**Issue by CKanishka** [plotly/plotly.js#5727]
#### Description
I was trying to format the y-axis ticks to two decimal places using - `tickformat:'0.2f'` but the formatting doesn't seem to work when `showticklabels` property is set to false.
`var layout = {
    "yaxis": {
        "showticklabels": false,
        "tickformat": "0.2f" 
    }
}`

#### Steps to reproduce
Codepen link: [https://codepen.io/ckanishka/pen/bGqQQNL](https://codepen.io/ckanishka/pen/bGqQQNL)

#### Expected Behaviour
The formatting should work irrespective of `showticklabels` property's value

**Comment by nicolaskruchten** [comment]
I'm confused about what you're expecting here... you've hidden the tick labels so there's nothing to format, right?

**Comment by CKanishka** [comment]
> I'm confused about what you're expecting here... you've hidden the tick labels so there's nothing to format, right?

Yeah I got your point but what I was trying to achieve with `showticklabels:false` was to just hide the y-axis labels and with `tickformat:0.2f` I was trying to make the value shown on the tooltip on hovering over a point to be formatted as per the specified format.
![image](https://user-images.githubusercontent.com/30779692/121912426-337e7200-cd4e-11eb-8cb0-1c79f8ce7e49.png)

**Comment by nicolaskruchten** [comment]
Gotcha. For that we have `<trace>.yhoverformat`, which is more explicit than relying on the tick formatting, especially if you're then hiding the ticks :)

**Comment by CKanishka** [comment]
> Gotcha. For that we have `<trace>.yhoverformat`, which is more explicit than relying on the tick formatting, especially if you're then hiding the ticks :)

Thanks a lot, this was exactly what I was looking for. Highly appreciate your help.
