### ISSUE TITLE
pattern bgcolor & fgcolor as well as overlay fillmode

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#5728]
Right now patterns basically replace fills, and I want to introduce a second mode where they overlay them instead:

* new attribute `marker.pattern.fillmode= enum(default=replace, overlay)`
* new attribute `marker.pattern.fgcolor`
* `replace` fillmode is the current behaviour:
    * `marker.pattern.bgcolor` is transparent
    * `marker.pattern.fgcolor` = `marker.color`
*  `overlay` fillmode will be:
    * `marker.pattern.bgcolor` = `marker.color`
    * `marker.pattern.fgcolor` will be set to to contrast the `bgcolor` using the same algo we use to contrast text on bars

**Comment by alexcjohnson** [comment]
I like the behavior. Maybe change the value from `fill` to `mask` though? I like the value `overlay`, but `fill` doesn't seem like its opposite for this purpose.

**Comment by nicolaskruchten** [comment]
I guess I meant it as "the pattern takes the place of the fill"... what's the case for "mask" ?

**Comment by alexcjohnson** [comment]
"fill" sounds to me like "the pattern fills the bar", which isn't any more true for this mode than for overlay mode. By "mask" I meant "the pattern masks the bar fill" which feels more directly opposed to "the pattern overlays the bar fill" - I grant though that this is fairly technical / esoteric usage of the word "mask" so if there's a better word I'm all ears :)

**Comment by nicolaskruchten** [comment]
How about `marker.pattern.fillmode = replace | overlay` ... the pattern either replaces the fill or overlays it.

**Comment by alexcjohnson** [comment]
`marker.pattern.fillmode = replace | overlay` Sold 🎉
