### ISSUE TITLE
Recommended way of using a custom bundle?

### ISSUE THREAD

**Issue by invokermain** [plotly/plotly.js#5734]
Hi,

The custom bundle feature looks really useful, and the instructions to build a custom bundle were clear and helpful.

I was wondering if there was a recommended way of using this custom bundle in a Vue/Webpack application?

Would we for example do: `import Plotly from 'plotly.js/dist/plotly-custom.min.js'`? As suggested by this guide: https://github.com/plotly/plotly-webpack

Also is there any automated way of building a bundle? i.e. if someone clones the repo do they have to manually run the `npm run custom-bundle ...` command?

Apologies if this question is solely due to my lack of understanding of node/webpack.

**Comment by nicolaskruchten** [comment]
Once you build your custom bundle using the instructions here https://github.com/plotly/plotly.js/blob/master/CUSTOM_BUNDLE.md it will be placed in `path/to/plotly.js/dist/` and you should copy it out of there into your source tree, where you can load from it using `require` or `import`.

> if someone clones the repo do they have to manually run the npm run custom-bundle ... command?

Yes :)

**Comment by wehnerl** [comment]
Regarding this topic:

To improve web-performance I switched from the npm-package **plotly.js-basic-dist-min** to a custom bundle. I followed the instructions and created the file **plotly-custom.min.js** via the command `npm run custom-bundle --traces scatter --transforms none`. I copied that file, as @nicolaskruchten stated, into my source-tree. At the point, I'm a bit lost. 

 I tried to access Plotly and its methods via the following import commands, but nothing worked out
```
import * as Plotly from "path/to/plotly-custom.min.js";
import Plotly from "path/to/plotly-custom.min.js";
import { Plotly } from "path/to/plotly-custom.min.js";
```


Calling Methods like Plotly.react(…) or Plotly.newPlot(…) will result in `Uncaught TypeError: Plotly.<Method> is not a function`

What fundamental thing am I missing here? Help is highly appreciated! 😄

**Comment by mattharbord** [comment]
@wehnerl - I was having this problem, no idea if this will help but I needed to include `/* eslint-disable */ ` at the head of my plotly-custom-min.js to get it to run. Worked after that with just `import Plotly from "../util/plotly-custom-min"`

**Comment by CallumNZ** [comment]
I think I have a similar problem. In a Create React App, I had:

```
import PlotlyStrict from "../plotly-scattergl.min.js" // My custom bundle in `src` folder.
import createPlotlyComponent from "react-plotly.js/factory";
const Plot = createPlotlyComponent(PlotlyStrict);
```

This worked. I had /* eslint-disable */ at the top of the custom bundle file.

Then I moved to Vite (no other changes), and I get the error:
`Uncaught SyntaxError: The requested module '/src/plotly-scattergl.js' does not provide an export named 'default'`

The custom bundle file is copied out of Plotly.js in the `node_modules` folder. If I change the first line to point to that original file:
```import Plotly from "plotly.js/dist/plotly-scattergl.js"```

It works. I'm guessing it's a Vite configuration somewhere that needs to change, but I have no idea what. @wehnerl Would be interesting to know if you're using Vite as well?

**Comment by wehnerl** [comment]
> It works. I'm guessing it's a Vite configuration somewhere that needs to change, but I have no idea what. @wehnerl Would be interesting to know if you're using Vite as well?

Sorry, for the late response. No i used Vue3 with Webpack.

**Comment by Lexachoc** [comment]
I also have the same issue! I cannot import the custom plotly bundle in vite:

The distribution version works:
`import Plotly from 'plotly.js-dist';`

But the custom bundle doesn't:

`import Plotly from '@lib/plotly/2.34.0/plotly-custom-bundle.min.js';`

I will got error:

> Uncaught SyntaxError: The requested module '/src/lib/plotly/2.33.0/plotly-custom-bundle.min.js' does not provide an export named 'default'

Is this still an issue for Plotly v3.0.0? If yes, could we reopen this?

**Comment by CallumNZ** [comment]
@Lexachoc 

Hi, I got it working with Vite by copying the custom bundle into my project's `src` folder and importing like this:

```js
import "./my-plotly-bundles/my-custom-bundle.min.js"
```

And if you're using `react-plotly`, you can then do this:

```js
import createPlotlyComponent from "react-plotly.js/factory";
const Plot = createPlotlyComponent(Plotly);
```

**Comment by Lexachoc** [comment]
@CallumNZ Thank you so much! It works!
