### ISSUE TITLE
Boxplot points not drawn in some cases

### ISSUE THREAD

**Issue by Jeff-Clark** [plotly/plotly.js#574]
See https://jsfiddle.net/cf4j5vxz/

Traced it into code line
newJitter = trace.jitter * 2 / maxJitterFactor;
maxJitterFactor is zero in some cases when lots of data points are zero.

**Comment by etpinard** [comment]
Bug confirmed. Thanks for reporting.

Looks like you found the root of the problem. This would a great opportunity for a first contributor to make his/her first PR.

**Comment by alexcjohnson** [comment]
closed by #915
