### ISSUE TITLE
Error fetching geojson when ES6 import is used

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#5753]
[codepen](https://codepen.io/MojtabaSamimi/pen/PopvWqr?editors=0010)
See console error.

**Comment by archmoj** [comment]
Replacing `this.XDomainRequest` with `self.XDomainRequest` in d3-v3 fork appears to fix the problem.

**Comment by nicolaskruchten** [comment]
Is this to do with the changes we made to make things ES6-importable? Maybe there's a binding problem now?

**Comment by archmoj** [comment]
It does not look like a regression.
Only that right now everything is not E6 importable.

**Comment by archmoj** [comment]
I only see the error in `choropleth` when using `test_dashboard` that uses `es6-import`.
