### ISSUE TITLE
Bar text performance regression from plotlyjs 1.58.4 to 2.1

### ISSUE THREAD

**Issue by darintay** [plotly/plotly.js#5764]
Bar charts with text appear to be several times slower to render in plotlyjs 2.1 than they were in 1.58.4.

Simple example here:

1.58.4: https://jsbin.com/winiqazavu/edit?html,output
2.1.0:  https://jsbin.com/fahedevopo/edit?html,output

The 1.58.4 version runs in a couple of seconds for me, where the 2.1.0 takes over a minute.  I've tried on Chrome and Firefox.

If you remove the text, everything renders quickly on either version.

**Comment by sean-mcl** [comment]
Hey, we found some performance issues too.

 [Here](https://codepen.io/seanmcl030/pen/GRmgdGz) is an example with 100k datapoints. When we use the 2.2.0, the whole plot freezes and has a very bad performance. When we use the plotly-1.58.4.min.js, everything works fine.

LayTec-AG/Plotly.Blazor#99

**Comment by sean-mcl** [comment]
@archmoj should i create another issue for the other performance issue?

**Comment by sean-mcl** [comment]
@archmoj Can you please check the example above regarding the performance of the scallergl plot.

**Comment by archmoj** [comment]
> @archmoj Can you please check the example above regarding the performance of the scallergl plot.

Please open a separate issue for the scattergl case.
Thanks.

**Comment by DarinTayTwoXAR** [comment]
Ah, it was suddenly trying to render the text inside all the bars?  Makes sense why that would take a while.

Confirmed that textposition none fixes issues here, thanks!
