### ISSUE TITLE
Clickable legend group title

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#5765]
_Originally posted by @rithwikjc in https://github.com/plotly/plotly.js/issues/5260#issuecomment-860032962_

I'd like to request that the additional functionality of the `legendgrouptitle` having the clickable behavior of toggling the whole group, be added along with this feature introduction.

**Comment by Braintelligence** [comment]
Quick question: Is it possible to simultaneously define legendgroupclick with `toggleitem` but be able to click the legend group title to hide the group? Did you implement a new event handler for legend group titles or do we have to use `.on("plotly_legendclick",` to find out if someone clicked a legend group title?

**Comment by endursa** [comment]
Is the idea of having single trace toggle within a group still persued? or was this forgotten after the group legend toggle was implemented?
