### ISSUE TITLE
Legend scroll position resets after toggle

### ISSUE THREAD

**Issue by john-soklaski** [plotly/plotly.js#578]
On a legend that has enough entries to require a scroll bar, scroll to the bottom and toggle an entry. The result is that the scroll bar jumps back up to the top.

See http://codepen.io/john-soklaski/pen/GqRZxq

I think a better behavior would be to maintain the current scroll position so that the user can see the entry that they toggled.

**Comment by etpinard** [comment]
Yep that's a bug. Thanks for reporting.
