### ISSUE TITLE
Missing executeAPICommand in `exports.Plots`

### ISSUE THREAD

**Issue by cid8600** [plotly/plotly.js#5794]
Bug: I Upgraded Plotly to `v2.2.0` and noticed the `Plotly.Plots.executeAPICommand` handler was no longer in the latest version.

As a User I'd like to see `executeAPICommand` returned to `exports.Plots`. This allows one to control multiple plots via a single Event. 

File: `dist/plotly.js`
Line:  `155701`

Is: 
```
exports.Plots = {
    resize: Plots.resize,
    graphJson: Plots.graphJson,
    sendDataToCloud: Plots.sendDataToCloud,
};
```

Fix:
```
exports.Plots = {
    resize: Plots.resize,
    graphJson: Plots.graphJson,
    sendDataToCloud: Plots.sendDataToCloud,
    executeAPICommand: Plots.executeAPICommand
};
```

Example: try to execute `Plotly.Plots.executeAPICommand(gd, method, args)` to control a sibling Plot and notice the function is missing from the `exports.Plots` Object.

**Comment by alexcjohnson** [comment]
@cid8600 Can you give a full example of how you use this function? We intentionally removed a lot from `Plotly.Plots`, to minimize the surface area we need to maintain - see https://github.com/plotly/plotly.js/blob/master/CHANGELOG.md#removed, specifically:

> Reduce the number of exported methods from Plotly.Fx and Plotly.Plots in the API [[#5420](https://github.com/plotly/plotly.js/pull/5420)]

I'm not inherently opposed to bringing this one back, just want to understand the use cases better before we do.

**Comment by cid8600** [comment]
@alexcjohnson, Indeed:

Let say I have two contour plots rendered on a page. Each Plot has a slider to stream through 3D data. The plot steps are synced. If I move the slider from Plot1, I expect the slider from Plot2 to follow and display the same frame. 

React Pseudo code would look like: 
```
const [startingSlice, setstartingSlice] = useState(1)
const Plot1 = useRef()
const Plot2 = useRef()

 const onSliderChange = (event) => {
    if (Plot1.current && Plot2.current) {
      const { slider, step } = event;
      if (slider._gd === Plot1.current.el) {
        // if from Plot1, update Plot2
        Plotly.Plots.executeAPICommand(Plot2.current.el, step.method, step.args);
      } else if (slider._gd === Plot2.current.el) {
        // if from Plot2, update Plot1
        Plotly.Plots.executeAPICommand(Plot1.current.el, step.method, step.args);
      }
      setstartingSlice(slider.active);
    }
  };

<Plot ref={Plot1} onSliderChange={onSliderChange}>
<Plot ref={Plot2} onSliderChange={onSliderChange}>
```

**Comment by cid8600** [comment]
![image](https://user-images.githubusercontent.com/771471/124184977-2dd39c80-da6f-11eb-87ca-ea93a78107b9.png)

**Comment by alexcjohnson** [comment]
I see. If you're explicitly calling `executeAPICommand` like that, can you call the method directly? ie change:
```js
Plotly.Plots.executeAPICommand(Plot2.current.el, step.method, step.args);
```
to:
```js
Plotly[step.method](Plot2.current.el, ...step.args);
```

**Comment by cid8600** [comment]
Great call. That works the same. I appreciate you looking into it.
