### ISSUE TITLE
SVG paths (i.e. shapes) on ternary plots

### ISSUE THREAD

**Issue by blokhin** [plotly/plotly.js#580]
Hi there : D

it seems that shapes of the "path" type are not supported on ternary plots. Is this indeed so?

Thanks a lot!

**Comment by etpinard** [comment]
Axis-referenced paths are not supported on ternary plots. 

Paper-referenced paths should work are desired though: see http://codepen.io/etpinard/pen/MeWLWo

Assuming that you're interested in axis-referenced paths, can I ask what are you trying to plot?

**Comment by blokhin** [comment]
Thx for the kind response and for the codepen!

I now see, that the paper-referenced paths work.

Concerning axis-referenced ones, I think, one can convert them to the paper-referenced ones. Math shouldn't be complicated.
