### ISSUE TITLE
2.0^ version can't be used in Angular

### ISSUE THREAD

**Issue by aanilyildiz** [plotly/plotly.js#5810]
Version 1.58 was working fine in Angular with a couple of modifications. But the addition of new dependencies which use the stream package makes it impossible to use the newer versions in Angular. I've searched for a workaround but found nothing.  I tried using it with angular-plotly.js but it gave me a error saying wrong import of ploty.js. Any help would be appreciated regarding this situation

**Comment by alexcjohnson** [comment]
@aanilyildiz I assume you closed this because you found a solution - anything you can say about the required changes, to help others in your situation? Thanks!

**Comment by aanilyildiz** [comment]
I've switched back to using version 1.58 after giving up. angular-plotly.js doesn't see the newer versions of the plotly.js. I think an update to that package would be better since newer versions of plotly.js use many packages that can't be used in browsers.
