### ISSUE TITLE
Tip: to change Hover Text font properties

### ISSUE THREAD

**Issue by dineshu07** [plotly/plotly.js#582]
using css we can change text color, font, size.. etc .
use this code 

 .hovertext text{
            font-family: Helvetica !important;
            font-size:13px !important;
  } 

Thanks 
Dinesh

**Comment by etpinard** [comment]
Thanks!

As per our [contributing guidelines](https://github.com/plotly/plotly.js/blob/master/CONTRIBUTING.md), github issues are reserved for bug reports and feature requests only. So I'll have to close your ticket.

Please use our community forums at [community.plot.ly](http://community.plot.ly/) for posts of the likes.

**Comment by dineshu07** [comment]
Thanks.
