### ISSUE TITLE
hover misplaced with period positioning

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#5822]
In this pen the hover labels positioning is quite broken: https://codepen.io/nicolaskruchten/pen/gOWgpEx?editors=0010

when I hover directly on some of the points it's correct, but in general it's too far to the left. This doesn't happen when I use just the first trace, and when I set `xperiod` to e.g. M1.

**Comment by Djeramon** [comment]
I don't think this has been fixed. I took the original code pen and updated it to 2.3.0:

https://codepen.io/Djeramon/pen/XWRVzwz

The behavior is not yet right. Two things are going wrong:

- For the last data point only the hover label of a single trace is shown. (Yen)
- The values for all other traces are shifted and are not shown correctly. (e.g. the third data point for US Dollar should be the value 6, but instead the hover label shows the value 8)

**Comment by alexcjohnson** [comment]
Discussing this in another channel, @Djeramon and others with similar setups are seeing this problem on Windows 10 using either Chrome or Edge. But my own testing, whether on Windows or Mac and regardless of browser, is behaving correctly. So there's some aspect of the environment affecting this, but we haven't yet figured out what it is. If anyone else is seeing this and can shed more light on its cause, please do!
