### ISSUE TITLE
Cannot read property 'select' of undefined

### ISSUE THREAD

**Issue by slutske22** [plotly/plotly.js#5824]
I am updating a codebase that had been using `plotly.js-basic-dist@^1.58.4`.  The code uses the call to 

```js
Plotly.d3.select()
```  

This works fine.  [Here is a working sandbox](https://codesandbox.io/s/plotly-working-g7w8l)

I upgraded to the latest version, 2.2.1,  and I get the error `Cannot read property 'select' of undefined` when using the same code.  [Here is a codesandbox showing that issue](https://codesandbox.io/s/plotly-not-working-3k2bg).

Did I miss something in the changelog?  I can't find documentation on the `.select` or `.selectAll` methods anywhere.  Where did this get broken?  What is the replacement?

**Comment by nicolaskruchten** [comment]
Yes, in v2 we stopped exporting `Plotly.d3`.

**Comment by slutske22** [comment]
So is the assumption here that I should be installing d3 separately (`npm i d3`), and doing `import d3 from 'd3'`, and `const thing = d3.select('something')`?

**Comment by nicolaskruchten** [comment]
That's right! We want to be able to change our internal version of D3 without worrying about documenting these changes externally, and I think it makes more sense for folks to load up the specific version of D3 they need without being coupled to whatever internal choices we make :)
