### ISSUE TITLE
Missing Dosis font for image test

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#5830]
We used to get `Dosis` from the address below for the image test.
https://github.com/eliheuer/dosis-vf/blob/master/fonts/static-fonts/

But it is now missing causing these baselines to fail:
`gl3d_indicator_scatter3d`,
`indicator_bignumber`,
`indicator_scatter`

**Comment by alexcjohnson** [comment]
Let's just take Dosis out. There's nothing special about it, we have plenty of other fonts represented in our tests.

**Comment by archmoj** [comment]
Side effect of https://github.com/eliheuer/dosis-vf/pull/15
