### ISSUE TITLE
scattergl lines don't respect top-level opacity attribute

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#585]
Perhaps this should be added to the list in https://github.com/plotly/plotly.js/issues/130

http://codepen.io/cpsievert/pen/oLNRRN

**Comment by etpinard** [comment]
Thanks for reporting. 

This bug only affect scattergl lines. Markers respect the trace opacity field (see [here](http://codepen.io/etpinard/pen/aZzvJo)).
