### ISSUE TITLE
connectgaps in scattergl only works when mode is explicitly set to 'lines'

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#586]
Couldn't find this listed in #130, perhaps it should go there.

http://codepen.io/cpsievert/pen/YWPKvz

**Comment by etpinard** [comment]
scattergl `connectgaps` was added in https://github.com/plotly/plotly.js/pull/449

There's a bug in it though: it only worked when `mode` is explicitly set to `lines` (see [here](http://codepen.io/etpinard/pen/NrPGby)). Thanks for reporting.

**Comment by etpinard** [comment]
done in https://github.com/plotly/plotly.js/pull/589
