### ISSUE TITLE
Renaming 3d axes 

### ISSUE THREAD

**Issue by arogozhnikov** [plotly/plotly.js#587]
HI, 
is there a (maybe hacky) way to rename axes in 3d?

Passed layout options:
```
        xaxis: {title: 'x1'},
        yaxis: {title: 'x2'},
```
seem to be ignored.

**Comment by etpinard** [comment]
Here's how: http://codepen.io/etpinard/pen/YWPwNa

You may want to look at our community [forum](http://community.plot.ly/) for questions of the likes in the future.

**Comment by arogozhnikov** [comment]
This works! Thanks a lot.
