### ISSUE TITLE
[feature] Candlestick explicit position and width: add ‘offset’ & ‘width’ attributes to graph type 'candlestick'

### ISSUE THREAD

**Issue by chuckinho** [plotly/plotly.js#5877]
# Introduction 
I have a request for a feature that could be very useful and allow for more control over [candlestick graphs](https://plotly.com/javascript/candlestick-charts/).

I was wondering if the [```offset```](https://plotly.com/javascript/reference/bar/#bar-offset) and [```width```](https://plotly.com/javascript/reference/bar/#bar-width) attributes could be added to the type [```candlestick```](https://plotly.com/javascript/reference/candlestick/).

I have an example where it works for type [```bar```](https://plotly.com/javascript/reference/bar/) but not for candlestick as this isn’t supported yet. My example puts a trace of candles and volume into one subplot, there are 3 subplots.

For my volume trace, I have these attributes:
```javascript
{
  ...
  type: ‘bar’
  offset: 0,
  width: width * stepsize // width differs for stepsizes 1,2,3
}
```

I would like to also have this for my candlestick trace:
```javascript
{
  ...
  type: ‘candlestick’
  offset: 0,
  width: width * stepsize // width differs for stepsizes 1,2,3
}
```

However, the attributes ```offset``` and ```width``` are not supported for the type ```candlestick```. This would be greatly appreciated and be very useful! 

# Visuals

![plotly-candlestick-feature](https://user-images.githubusercontent.com/74075783/128251549-af74be32-e688-4121-94b8-b554996beaab.png)
In this picture, you can see how the candlestick remains with the default offset and width, whereas the bar uses my defined offset and widths.

![plotly-candlestick-example](https://user-images.githubusercontent.com/74075783/128251667-da5b3e7c-96bb-44a6-a59f-dba7fc9b08c9.png)
In this picture, you can get an idea of what I’d like the candles to be like.

-----

Please let me know if you need any more information. Here is the github repo of this example plot (written in react): https://github.com/chuckinho/Plotly-Subplots-Candles-Example

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
