### ISSUE TITLE
posibility of a 2.3.2 release with less strict d3-interpolate version dependency 

### ISSUE THREAD

**Issue by evansrobert** [plotly/plotly.js#5886]
Hi, @archmoj,
### Issue Description

   I noticed that a vulnerability is introduced in **_plotly.js@2.3.1_**:
     Vulnerability **SNYK-JS-D3COLOR-1076592** affects package **_d3-color_** (versions:<3.0.0):  [https://snyk.io/vuln/SNYK-JS-D3COLOR-1076592](https://snyk.io/vuln/SNYK-JS-D3COLOR-1076592)
  The above vulnerable package is referenced by **_plotly.js@2.3.1_** via:
`plotly.js@2.3.1 ➔ d3-interpolate@1.4.0 ➔ d3-color@1.4.1`

Since **_plotly.js@2.3.1_** ([10,096 downloads per week](https://www.npmjs.com/package/plotly.js/v/2.3.1?activeTab=versions)) is referenced by **38** downstream projects (e.g., [jupyterlab-plotly 5.1.0](https://www.npmjs.com/package/jupyterlab-plotly) (latest version), [@interpretml/interpret-inline 0.2.6](https://www.npmjs.com/package/@interpretml/interpret-inline) (latest version), [@deephaven/code-studio 0.2.1](https://www.npmjs.com/package/@deephaven/code-studio) (latest version), [@intermix-dashboard/victory 0.7.0](https://www.npmjs.com/package/@intermix-dashboard/victory) (latest version), [@deephaven/chart 0.2.1](https://www.npmjs.com/package/@deephaven/chart) (latest version)), the vulnerability [**SNYK-JS-D3COLOR-1076592**](https://snyk.io/vuln/SNYK-JS-D3COLOR-1076592) can be propagated into these downstream projects and expose security threats to them via the following package dependency paths:
 (1)`jupyterlab-plotly@5.1.0 ➔ plotly.js@2.3.1 ➔ d3-interpolate@1.4.0 ➔ d3-color@1.4.1`
(2)`@interpretml/interpret-inline@0.2.6 ➔ plotly.js@2.3.1 ➔ d3-interpolate@1.4.0 ➔ d3-color@1.4.1`
  **......**

If **_plotly.js@2.3.\*_** removes the vulnerable package from the above version, then its fixed version can help downstream users decrease their pain.

**Given the large number of downstream users, could you help update your package to remove the vulnerability from plotly.js@2.3.1 ?**

### Fixing suggestions

In **_plotly.js@2.3.2_**, maybe you can kindly try to perform the following upgrade :
`d3-interpolate ^1.4.0 ➔ ^3.0.0`; 

**Note:**
_**d3-interpolate@3.0.0**(>=3.0.0) directly depends on **d3-color@3.0.1** which has fixed the vulnerability [**SNYK-JS-D3COLOR-1076592**](https://snyk.io/vuln/SNYK-JS-D3COLOR-1076592)._
Of course, you are welcome to share other ways to resolve the issue.

Thank you for your attention to this issue.

Best regards,
^_^

**Comment by archmoj** [comment]
Please note that there was no version change in the following packages between plotly.js v1.58.4 and plotly.js v2.3.1:
```
└─┬ d3-interpolate@1.4.0
  └── d3-color@1.4.1 
```
Also noting that `d3-interpolat@v2` [dropped support for IE](https://github.com/d3/d3-interpolate/releases/tag/v2.0.1), upgrading may not be a feasible choice at this point.
What about fixing the issue in `d3-interpolate v1`?

**Comment by archmoj** [comment]
Addressed in #6463.
