### ISSUE TITLE
Axis-unified hover tooltips overlay data points

### ISSUE THREAD

**Issue by xenatisch** [plotly/plotly.js#5889]
## Synopsis

Axis-unified hover tooltips overlay data points, making it impossible to see graph content.

### Current behaviour 

When hovering over data points, specially in data that fluctuate, the tooltip is drawn over the visualisation, making it impossible to see the content. This is best deomonstrated as follows:
![E8ifXpcWYAI0gFp](https://user-images.githubusercontent.com/13240654/129278009-762b2f1a-cf26-4169-a60b-94f7c35f9988.jpeg)

### Expected behaviour
The expected behaviour would be something along these lines - albeit within the boundaries of the graph:
<img width="476" alt="Screenshot 2021-08-12 at 23 28 34" src="https://user-images.githubusercontent.com/13240654/129278047-1175d65e-1599-4f51-b3ff-772f7e9af8fe.png">

Alternatively, it might be feasible to consider having a fixed location - e.g. midpoint of the axis - for the tooltip and get it to move around if the cursor position along the same axis is within the boundaries of the tooltip. 

## Reproduce 

You can get data to reproduce this behaviour from the [UK Coronavirus dashboard](https://coronavirus.data.gov.uk/).

---

Plotly version: 2.3.1

**Comment by suhasthegame** [comment]
Hi,
I would love to  work on this issue, but I'm new to open-source. Can you please guide me?
