### ISSUE TITLE
 Sometimes scatter graph is showing out of the range

### ISSUE THREAD

**Issue by ramaUptimeAI** [plotly/plotly.js#5890]
Hello Plotly,

My issue is when first time the scatter graph is rendering out of the range even though ranges are correct, but when I refresh the browser it's working fine. Please check the below images and my configuration of Plotly.

Out of the Range Images:
<img width="1406" alt="Screenshot 2021-08-13 at 9 43 09 AM" src="https://user-images.githubusercontent.com/82371227/129304603-3d4e86da-70b2-4d1a-aae7-813507b5d822.png">

Here: the right side x-axis is out of the range.

![image](https://user-images.githubusercontent.com/82371227/129304640-b289012e-a6fd-4e6c-a718-52dd4b4b2775.jpeg)

Here: sometimes the left x-axis is out of the range.

When I refresh the browser, it's working perfectly fine.
<img width="1403" alt="Screenshot 2021-08-13 at 9 44 39 AM" src="https://user-images.githubusercontent.com/82371227/129304711-d0cbedb4-1997-463a-bede-caa6064e75bd.png">

My configuration of Plotly is:
```
  
  systemAnomalyScore: any = {
    data: [{
      name: 'Normal',
      x: [],
      y: [],
      mode: 'markers',
      marker: {
        size: 2
      },
      type: 'scattergl',
    },
    {
      name: 'Shutdown',
      x: [],
      y: [],
      hovertext: [],
      hoverinfo: 'text',
      mode: 'markers',
      marker: {
        size: 2
      },
      type: 'scattergl',
    },
    {
      name: 'Maintenance',
      x: [],
      y: [],
      hovertext: [],
      hoverinfo: 'text',
      mode: 'markers',
      marker: {
        size: 16
      },
      type: 'scatter',
    },
    {
      name: 'Alerts',
      x: [],
      y: [],
      mode: 'markers',
      marker: {
        size: 16
      },
      type: 'scatter',
    }
    ],
    layout: {
      title: 'Anomaly Score',
      hovermode: 'closest',
      showlegend: true,
      legend: { "orientation": "h", x: 0, y: 1.15 },
      annotations: [],
      datarevision: 0,
      height: 400,
      margin: {
        t: 75,
        b: 60
      },
      autosize: true,
      xaxis: {
        ticks: false,
        autorange: false,
      },
      yaxis: {
        title: 'Anomaly Score',
        rangemode: 'nonnegative'
      },
      shapes: []
    }
  };
```

Please let me know if I'm doing anything wrong with my configuration or some other thing.

**Comment by ramaUptimeAI** [comment]
@archmoj can you help with this ?

**Comment by archmoj** [comment]
Please fork [this codepen](https://codepen.io/MojtabaSamimi/pen/KKqVgwK?editors=0010) and provide some data so that it could be replicated. Thanks!

**Comment by ramaUptimeAI** [comment]
@archmoj please check this codepen link https://codepen.io/ramauptimeai/pen/XWgXqZR. Thanks!

**Comment by mahammadSyed** [comment]
@archmoj  Any update about the issue ?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
