### ISSUE TITLE
Disabling zooming and panning

### ISSUE THREAD

**Issue by buremba** [plotly/plotly.js#59]
I'm aware that there is `staticPlot` option for disabling these features but it actually disables all interactive operations including tooltips and legends.

For charts that don't have much data points, these features unnecessary so it would be great if you guys add an option to disable zooming, panning and dragging.

**Comment by etpinard** [comment]
In svg 2d plots, you can set `layout.xaxis.fixedrange: true` to disable zooming/panning along x and similarly using `layout.yaxis.fixedrange: true` in the y direction. More info on the reference [page](https://plot.ly/javascript/reference/#layout-xaxis-fixedrange).

That said, this option hasn't been implemented for the webgl and maps plot types yet.

**Comment by buremba** [comment]
Oh, I missed them. Thanks for the fast response!

**Comment by etpinard** [comment]
@buremba All good :beers: It is a pretty hidden feature.

**Comment by ankitgoel888** [comment]
How to do this for tables created via figure factory viz. 
ff.create_table(df).
There seems to be no attribute called fixedrange in the output generated via ff.

**Comment by etpinard** [comment]
> How to do this for tables created via figure factory viz.

Please ask your questions on https://community.plot.ly/

**Comment by sriram15690** [comment]
@etpinard Thanks :)

**Comment by sriram15690** [comment]
I did not find “staticPlot: true” in the attribute reference. It should be added to the documentation.

**Comment by sriram15690** [comment]
> In svg 2d plots, you can set `layout.xaxis.fixedrange: true` to disable zooming/panning along x and similarly using `layout.yaxis.fixedrange: true` in the y direction. More info on the reference [page](https://plot.ly/javascript/reference/#layout-xaxis-fixedrange).
> 
> That said, this option hasn't been implemented for the webgl and maps plot types yet.

This option disables browser-page optical zoom on tablets when a user tries to zoom the page by placing his fingers on the graph.

**Comment by DaveSimmons1234** [comment]
Why does putting xaxis.fixedrange: true, yaxis.fixedrange: true on the graph change the mouse cursor to pointer, as if the whole graph is clickable?

**Comment by jaspersardonicus** [comment]
In case anyone comes looking for this feature like I did for Choropleth plots:

- The option to disable panning: `dragMode=False` in the layout property
- The option to disable scrolling: `scrollZoom=False` in the config property
- The option to disable map controls: `displayModeBar=False` in the config property

**Comment by surya-factly** [comment]
@jaspersardonicus 

That was helpful. As far as I understand, in python, we can provide those configuration options to 

`
config = dict({'scrollZoom': False})
fig.show(config` = config)
`

I am using streamlit to show a plotly chart and cannot use the show() function, which opens the choropleth map in new window. Is there any other way we can set these config options.

Any help is appreciated. Thanks

**Comment by adrian-gralak95** [comment]
For people stumbling, here from the internet - https://github.com/plotly/plotly.js/blob/master/src/plot_api/plot_config.js has the reference for all the config options, if you set `{'showAxisDragHandles': False}` it should do exactly what was asked in the question
