### ISSUE TITLE
This contour trace blows up on zoom

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#591]
The x/y limits are fine, but the coloring breaks on any zoom event, perhaps a rounding issue?

http://codepen.io/cpsievert/pen/qNEXKV

**Comment by jackparmer** [comment]
I'm seeing the same issue with these contour traces by @empet 

https://plot.ly/dashboard/jackp:16964/present

![image](https://cloud.githubusercontent.com/assets/1865834/19754054/c942258c-9bbe-11e6-84c7-14d0eeb9bd3c.png)
