### ISSUE TITLE
angularaxis with one trace

### ISSUE THREAD

**Issue by romain-fontugne** [plotly/plotly.js#592]
There is undesired points and labels appearing when ploting a polar chart with a single trace.
Example with one trace containing only one point: http://codepen.io/romain-fontugne/pen/NrPvoW

**Comment by etpinard** [comment]
Thanks for reporting. Sorry to hear that you're having issue with our polar chart types.

Our polar code is in dire needs of a complete rewrite. We hope to start working on it this summer.

**Comment by etpinard** [comment]
fixed in `scatterpolar` after #2200
