### ISSUE TITLE
[Feature request] Set font size for legendgroup titles in layout 

### ISSUE THREAD

**Issue by Djeramon** [plotly/plotly.js#5920]
It would be great, if we could set the font size for all legendgroup titles in the layout, similar to the font size for the overall legend title. Currently, the font size of the legendgroup title has to be set for each trace individually.

**Comment by archmoj** [comment]
How about `legendgrouptitlefont` and `hovergrouptitlefont` (for the case of unified hover) as the attribute names?

**Comment by Djeramon** [comment]
Both sound good to me. Thanks!
