### ISSUE TITLE
The same marker color is displayed differently, depending on marker size 

### ISSUE THREAD

**Issue by empet** [plotly/plotly.js#5946]
The first plot has all markers of constant size, size=10, and `marker_color='rgb(255,200, 0)'.
![constant_size](https://user-images.githubusercontent.com/3627253/134508553-c8a1c85f-2f5b-45fe-88c6-e5828361aab3.png)

Updating size to an array, the color looks differently (it has a lower saturation):
![variable_size](https://user-images.githubusercontent.com/3627253/134508579-314520df-0792-4203-85ab-36ffea66b329.png)

**Comment by nicolaskruchten** [comment]
Yes, when you scale markers by size, the engine automatically lowers the opacity for some historical reason. You can force it back up to 1 to avoid this.

**Comment by empet** [comment]
Historical reason?!!!  :)

**Comment by nicolaskruchten** [comment]
My way of saying "I don't really love this design decision but we're stuck with it now for backwards-compatibility" :)
