### ISSUE TITLE
Can't import plotly.js in nodejs because of one slash

### ISSUE THREAD

**Issue by delfick** [plotly/plotly.js#595]
Hi,

https://github.com/plotly/plotly.js/commit/8c4721b365fcec428412430420c74d1bac4507d0#diff-dacb67ab63b7ad6769ed4c2ec64af4e7R14

In this line, require has a trailing slash next to "constants" which prevents it from being imported from nodejs.

Can the trailing slash be removed please?

Thank you :)

**Comment by etpinard** [comment]
Thanks. The trailing slash problem is fixed https://github.com/plotly/plotly.js/pull/597 

But, that would be enough for plotly.js to work in node.js.

See discussion in https://github.com/plotly/plotly.js/issues/437#issuecomment-211386133

**Comment by delfick** [comment]
Awesome thanks.

I don't mind that it won't work, I just want it to import :)
