### ISSUE TITLE
Tufte Axis

### ISSUE THREAD

**Issue by ncammarata** [plotly/plotly.js#596]
Is it possible to add padding to the axis similar to how Edward Tufte suggests structuring it in Edward Tufte's The Visual Display of Quantitative Information (shown on the right)?

![image](https://cloud.githubusercontent.com/assets/204989/15737045/96762312-2858-11e6-886b-a613fe258e80.png)

**Comment by etpinard** [comment]
> Is it possible to add padding to the axis similar to how Edward Tufte

I think so. Here's what I came up with: http://codepen.io/etpinard/pen/LZpzNO?

**Comment by etpinard** [comment]
Closing for now.
