### ISSUE TITLE
[Bug] Legend 'xanchor' setting plot's x position rather than legend's

### ISSUE THREAD

**Issue by wunderBarr7** [plotly/plotly.js#5983]
When using horizontal legend orientation, using the 'xanchor' property sets the plot's x position rather than the legend's x position.

[Link to Example Code](https://codepen.io/wunderbarr/pen/dyzGMrZ)

**Comment by OpportunityLiu** [comment]
You'd set `x: 0.5` with `xanchor: 'center'` to center the legend.
```
legend: {
    orientation: 'h',
    xanchor: 'center',
    x: 0.5,
  }
```

The default value of `x` is `0`, with `xanchor: 'center'`, the legend will be aligned with 0 at its center.
