### ISSUE TITLE
highlight a series and fade the rest series like dygraph

### ISSUE THREAD

**Issue by cailiang9** [plotly/plotly.js#60]
Highlighting a series like dygraph is important and useful when there are many series in a plot.
So we don't need to click to toggle out all other series.
It is not hard to implement.

**Comment by etpinard** [comment]
Could you be more specific? Do you have an example of a graph with this feature?

**Comment by ni-hil** [comment]
Something like this I guess: http://dygraphs.com/gallery/#g/highlighted-series

**Comment by alexcjohnson** [comment]
:+1: that can be very useful, in fact we've implemented this exact feature for clients by using hover/unhover events.

Perhaps this even deserves a button in the mode bar? It would be nice to give viewers the option to turn it on and off while they're looking at the plot - for instance, I can imagine wanting it on while I'm getting an overview of all the traces, then wanting it off while I'm drawing a box to zoom in, or while focusing on two traces simultaneously to study their correlation.

**Comment by cailiang9** [comment]
:+1: If it is not easy to be added to mode bar, can we make it default on when plotting?

**Comment by etpinard** [comment]
Old issue. Merging with https://github.com/plotly/plotly.js/issues/1847
