### ISSUE TITLE
Plotly.toImage and Plotly.downloadImage not working correctly

### ISSUE THREAD

**Issue by mdtusz** [plotly/plotly.js#600]
It appears to work on the most recent Ubuntu version of Chrome, but on  OSX `Google Chrome v51.0.2704.79`, things are no bueno.

cc @timelyportfolio

**Comment by mdtusz** [comment]
It appears that `downloadImage` is broken as well with `format: 'svg'`.

**Comment by mdtusz** [comment]
cc @yankev

**Comment by timelyportfolio** [comment]
Strange, I wonder what happened.  I'll check on my Windows machine.

**Comment by timelyportfolio** [comment]
So this does not work http://codepen.io/timelyportfolio/pen/MyzGWY?

**Comment by mdtusz** [comment]
All three work in Firefox, but none are working in Chrome. Additionally, `downloadImage` seems to be broken in Firefox when using `format: svg`.
