### ISSUE TITLE
Support trendline annotations

### ISSUE THREAD

**Issue by mdfederici** [plotly/plotly.js#601]
I would like to be able to leverage annotations to specify a trendline like so:
![image](https://cloud.githubusercontent.com/assets/1938515/15778433/37327a1a-2964-11e6-9416-7631935fa06e.png)
I can do this with the current annotation code leveraging 'ax' and 'ay' but it is a bit clunky (as i need to  convert a point on the graph to pixels outside of plotly) and does not work correctly when the plot is zoomed.

How I imagine this working is a flag in the options which when set to true tells the annotation code to interpret 'ax' and 'ay' not as an offset in pixels but rather an absolute point in the coordinate system which indicates the position of the tail (while x,y continues to represent the head as usual). This would make it easier to draw the trendline and the trendline would correctly scale with zoom like so:
![image](https://cloud.githubusercontent.com/assets/1938515/15778551/ee31999e-2964-11e6-900c-5b9e9d5980f8.png)

I've never contributed to plot.ly before but I've implemented this in my plotly fork and have [a pull request](https://github.com/mdfederici/plotly.js/pull/1) there (in accordance with the [contributing guidelines](https://github.com/plotly/plotly.js/blob/master/CONTRIBUTING.md)).

**Comment by mdfederici** [comment]
[pull request to plotly/plotly.js](https://github.com/plotly/plotly.js/pull/610)

**Comment by mdfederici** [comment]
@etpinard @mdtusz any chance we can get this one in for this week's release to npm? thanks guys
MFed

**Comment by etpinard** [comment]
@mdfederici My bad. I have to wrap up an important PR today. I'll review yours on Monday. Sorry for the wait.

**Comment by mdfederici** [comment]
@etpinard no worries. finishing important things is good :)

**Comment by etpinard** [comment]
done in https://github.com/plotly/plotly.js/pull/610
