### ISSUE TITLE
feature request: flip the rotation of overlapping labels

### ISSUE THREAD

**Issue by mbork** [plotly/plotly.js#6025]
When the labels would overlap, Plotly.js rotates them by 30 degrees. I'd like to be able to specify some option to have them rotated by -30 degrees instead, so that instead of [this](https://codepen.io/mbork/pen/vYJvvYj) I would get [that](https://codepen.io/mbork/pen/BadvvyM) (without specifying the -30 angle manually). This way the labels would still be horizontal if short enough (which cannot be attained by just saying `tickangle: -30`), but go upwards instead of downwards if longer (which everyone I asked actually prefers).
I can make a PR if you point me to the right direction. I found [this page](https://github.com/plotly/plotly.js/issues/1123) and so I know about the `fixLabelOverlaps` function, but I don't know how to define a new layout key. Also, I'm not sure what the best name for that key could be.

**Comment by archmoj** [comment]
FYI - The logic is over here: 
https://github.com/plotly/plotly.js/blob/0408836bd860df010b26872cbb3bcd5bd1ee7212/src/plots/cartesian/axes.js#L3272-L3285

**Comment by mbork** [comment]
Yes, I know that. The question is, how do I define a new layout key.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson

**Comment by Konstiman** [comment]
Hi @gvwilson, I believe this is a regional thing - same as the text orientation on book spines. While countries like USA, UK, northern Europe prefer the top-to-bottom direction, countries like Germany and France prefer the bottom-to-top direction. I currently develop software for the German market, so I would really appreciate if this was customizable in Plotly.js. 

Is it possible to add a new parameter for that into the layout.xaxis, e.g. `tickdirection` (possible values `top2bottom` and `bottom2top`) that would modify the behavior of the "smart" tickangle and would reverse the angle?

I can help create the PR, could you just point me to some contribution guidelines?

**Comment by alexcjohnson** [comment]
I believe what you’re looking for is `autotickangles` https://plotly.com/python/reference/layout/xaxis/#layout-xaxis-autotickangles - implemented about 6 months ago by @my-tien 😄

**Comment by Konstiman** [comment]
@alexcjohnson thank you so much, this is exactly what I needed!! 😊 Looks like the `autotickangles` parameter isn't included in the npm's `@types/react-plotly.js` library - do you know by any chance how to contribute this parameter to there?

**Comment by alexcjohnson** [comment]
Great! I’m afraid I don’t know much about `@types/react-plotly.js` though, that’s not made by Plotly.
