### ISSUE TITLE
  showLink: false - does not work ;(

### ISSUE THREAD

**Issue by mrok** [plotly/plotly.js#603]
`Plotly.plot(gd, [trace], {
   showLink: false
});`

the code above should result in chart without "save and edit plot" option.
Unfortunately is does not work.

Please take a look here
[https://plnkr.co/edit/T3CuM8YN2wHN1QLW3icA?p=preview](https://plnkr.co/edit/T3CuM8YN2wHN1QLW3icA?p=preview)

**Comment by etpinard** [comment]
`showLink` is a [configuration](https://plot.ly/javascript/configuration-options/) option, not a layout attribute. 

To remove the link, you show call `Plotly.plot` as:

```js
Plotly.plot(gd, [trace], {}, { showLink: false });
```

**Comment by mrok** [comment]
I corrected it and upgraded Plotly version, but error still occurs ;(

https://plnkr.co/edit/z471XNN0QfUHGKkHGxqO?p=preview

**Comment by etpinard** [comment]
You mean the disk icon:

![image](https://cloud.githubusercontent.com/assets/6675409/16743968/c8b5bf02-477c-11e6-9d34-e286a96a6c56.png)

?

If so, then please read through http://community.plot.ly/t/how-to-hide-save-and-edit-link-in-modebar/360

**Comment by mrok** [comment]
Yes. I got it, thanks a lot.
