### ISSUE TITLE
Selecting bars with text impacts bar positions

### ISSUE THREAD

**Issue by junjiewu-mtl** [plotly/plotly.js#6041]
In a horizontal stacked bar chart with `text` attribute and `even+select` clickmode, a group will shift up after clicking, but won't reset after deselecting.  

![image003](https://user-images.githubusercontent.com/53387300/143300427-6fb06cb5-a713-49e6-a47b-78f568891bbf.png)
![image004](https://user-images.githubusercontent.com/53387300/143300436-77c1e01b-bda6-4cbe-9434-197838402552.png)
![image005](https://user-images.githubusercontent.com/53387300/143300441-8083dc82-b195-4dcf-b289-3f80de8cd582.png)

If remove the text attribute, the shifting won't happen

<img width="1773" alt="Screen Shot 2021-11-23 at 3 27 45 PM (1)" src="https://user-images.githubusercontent.com/53387300/143300873-6da38296-7fb2-4ddf-a00a-dce5ff84782c.png">
<img width="1773" alt="Screen Shot 2021-11-23 at 3 27 41 PM (1)" src="https://user-images.githubusercontent.com/53387300/143300875-358dee41-482d-49b7-87ff-ea81eef0b4c9.png">

**Comment by nicolaskruchten** [comment]
@archmoj here's a codepen: https://codepen.io/nicolaskruchten/pen/vYJqjLO?editors=1010

**Comment by archmoj** [comment]
It's not clear to me what the bug is.
Could you please provide an animate GIF?

**Comment by nicolaskruchten** [comment]
this video has some audio  :)

https://user-images.githubusercontent.com/203523/143304677-2b9b3c5a-1fa8-414c-b40c-1046af9b7576.mov

**Comment by archmoj** [comment]
Need to find additional software to be able to open that extension on ubuntu :(
BTW, here is [the "minimal" codepen](https://codepen.io/MojtabaSamimi/pen/RwZzyMo?editors=0011).

**Comment by archmoj** [comment]
Also happens on vertical bars: [codepen](https://codepen.io/MojtabaSamimi/pen/bGrPMQv?editors=0011).

**Comment by archmoj** [comment]
And that's not related to stack bars only: [codepen](https://codepen.io/MojtabaSamimi/pen/JjyQvwd?editors=0011).

**Comment by archmoj** [comment]
Not a regression but using v1.41.0 we have a slightly different "jump" | [codepen](https://codepen.io/MojtabaSamimi/pen/xxLvVRV?editors=1001).
