### ISSUE TITLE
[Bug] Mapbox with custom mapbox style object - access token not found

### ISSUE THREAD

**Issue by LoganWlv** [plotly/plotly.js#6042]
Following the [plotly mapbox-layers doc](https://plotly.com/javascript/mapbox-layers/), I am trying to change the `layout.mapbox.style` attribute from **'light'** (default Light mapbox) to a custom mapbox style object (cf. [spec](https://docs.mapbox.com/mapbox-gl-js/style-spec/))

Both require an access token, which I have. 

When setting the style to 'light' the access token is well found, can be tested in the following [codepen](https://codepen.io/loganwlv/pen/MWvNgwd).
But when using a custom style object it seems we lose track of the `mapboxAccessToken` config attribute. (cf. this [codepen](https://codepen.io/loganwlv/pen/eYEwqaa)). 

I also tried to pass the access token as a query parameter as I saw in some mapbox methods we would parse it that way: 
[normalizeTileURL](https://github.com/mapbox/mapbox-gl-js/blob/304a8297ba0f846166059af3d15e69501b347d76/src/util/mapbox.js#L96)

We could do a PR on the mapbox repository to add the same logic in: 
[normalizeSpriteUrl](https://github.com/mapbox/mapbox-gl-js/blob/304a8297ba0f846166059af3d15e69501b347d76/src/util/mapbox.js#L96)

but I feel like it's more a matter of Plotly correctly passing the access token to the mapbox API. 

I think we could fix that by adding the access token to the options passed to the Map constructor, [here](https://github.com/plotly/plotly.js/blob/2b01f3cd8277fc49f235507d5f2685009ba4a00f/src/plots/mapbox/mapbox.js#L96)

I'll test that.

**Comment by LoganWlv** [comment]
It seems it works, I'll create a PR

**Comment by LoganWlv** [comment]
@alexcjohnson Sorry to push on that, but do you mind pointing me out what's missing to merge that PR?

**Comment by casotto** [comment]
Hi @alexcjohnson,
thank you for the awesome work that you and your team are doing at plotly. 
I am a colleague to @LoganWlv and I am wondering on how can we help you to make the validation for this PR easier.

The code can allow for better map visualisations in Plotly by adopting different mapbox styles than the default one, so please let us know how we can make your work easier to add this feature :)

**Comment by alexcjohnson** [comment]
@LoganWlv @casotto my apologies for missing this issue and your PR earlier! Your fix looks excellent, please open a PR against the main repo.

The only additional thing we'd like to see is an image test that depends on this fix - ie would fail currently but succeeds with your fix. This can either be a new [mock](https://github.com/plotly/plotly.js/tree/master/test/image/mocks) or a change to one of the existing Mapbox mocks, so long as the changed mock still serves its original purpose but also tests the custom style. If you have trouble generating the corresponding [baseline image](https://github.com/plotly/plotly.js/tree/master/test/image/baselines), just create the desired mock and @archmoj can turn the crank to generate the appropriate image.

**Comment by LoganWlv** [comment]
I tested it again, and could not reproduce the issue. 
I guess I did a mistake when reading Codepen logs, I'm very for the waste of time, thank you.

I'm closing this issue. (Tested my Codepens & the `mapbox_custom-style.json` test)
