### ISSUE TITLE
Polygons with holes doesn't work with scattergeo, fill: 'toself' seems to be ignored.

### ISSUE THREAD

**Issue by awulkiew** [plotly/plotly.js#6044]
If polygon is defined as multiple rings in one trace, with `scattergeo` the relation of the rings seems to be ignored even if `fill` is set to `toself`. Such polygon is treated as multipolygon and each ring is drawn WRT the whole globe. Projection type is irrelevant. The behavior is different and correct in the case of `scatter` plot.

Polygon without hole:
![polygon without hole](https://user-images.githubusercontent.com/1226951/143596325-1b671f96-af24-4f1c-a325-b9d0f1d76407.png)

Polygon with hole:
![polygon with hole](https://user-images.githubusercontent.com/1226951/143596398-30109f1c-fd8a-482b-823c-c85f04c1831d.png)

Polygon with hole 2:
![polygon with hole 2](https://user-images.githubusercontent.com/1226951/143596755-a3202c85-b795-4761-a54f-b7eac99cf47d.png)

To reproduce:
```
<http>
<head>
    <script src="https://cdn.plot.ly/plotly-latest.js"></script>
</head>
<body>
    <div id="plot"></div>
    <script>
        var plot = document.getElementById('plot');

        var layout = {
            geo: {
                bgcolor: '#fff',
                projection: {
                    type: 'orthographic',
                    rotation: {
                        lon: 45,
                        lat: 10
                    },
                },
                showocean: true,
                oceancolor: '#fff',
                showland: true,
                landcolor: '#fff',
                showlakes: false,
                lakecolor: '#fff',
                showcountries: true,
                lonaxis: {
                    showgrid: true,
                    gridcolor: '#555'
                },
                lataxis: {
                    showgrid: true,
                    gridcolor: '#555'
                }
            }
        };

        var traces = [{
            lon: [1,1,90,90,1,null,10,20,20,10,10],
            lat: [1,27,27,1,1,null,10,10,20,20,10],
            mode: 'lines+markers',
            type: 'scattergeo',
            fill: 'toself',
            fillcolor: '#f555',
            marker: {color: '#f55a'},
            line: {color: '#f55a'}
        }];

        Plotly.newPlot(plot, traces, layout);
    </script>
</body>
</http>
```

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
