### ISSUE TITLE
Heatmap crashes with d3 errors when plotting with x-axis and y-axis traces of single element arrays

### ISSUE THREAD

**Issue by ArminTaheri** [plotly/plotly.js#605]
http://codepen.io/armintaheri/pen/JKYGrK?editors=1010

If a given axis of a heatmap only has one element in the trace, the plot crashes and the console is filled with d3.js exceptions:

```
attribute height: Expected length, "NaN".
attribute width: Expected length, "NaN".
attribute x: Expected length, "NaN".
attribute y: Expected length, "NaN".
```

**Comment by etpinard** [comment]
Yikes. Thanks for the report!
