### ISSUE TITLE
Multiple yaxis identifier inconsistency, why is 'y0' invalid?

### ISSUE THREAD

**Issue by CmpCtrl** [plotly/plotly.js#6053]
Why is `yaxis: 'y0'` an invalid axis identifier in a plot trace (I'm specifically working with scattergl)? This requires a special case when generating plots with multiple axes, ie: `'y', 'y1', 'y2', ...` instead of a consistent `'y0', 'y1', 'y2', ...`. I believe the same inconsistency is present in the `xaxis` identifiers as well.

I haven't looked into the source code, but I presume this is inconsistent to allow `'y'` to be a valid identifier for plots that don't have multiple axes. Is there any reason that `'y0'` can't also be valid? Obviously this isn't a major issue, but as a user, any inconsistencies or special cases are frustrating to keep track of.

To be clear, I am working in python, but I believe this is not specific to python.

**Comment by alexcjohnson** [comment]
You can use `'y1', 'y2', 'y3', ...` if you really want - `y1` is treated as an alias for `y`, and will be converted to `y` when the figure is rendered. Or in fact if you don't want anything to be changed you can use `'y2', 'y3', 'y4', ...`, I don't believe there's any requirement to start at the lowest index.

Your presumption is correct, this behavior is meant to simplify the great majority of graphs that only have one x and one y axis.

**Comment by alexcjohnson** [comment]
Axes show up in two ways: you create axis objects (`layout.yaxisN`) and you reference them (`trace.yref='yN'` and similar).

For the axis objects, if both `layout.yaxis` and `layout.yaxis1` exist, `layout.yaxis1` will simply be dropped. If only `layout.yaxis1` exists, it will be moved to `layout.yaxis`.

For the references, `trace.yref='y1'` and `trace.yref='y'` are equivalent: both traces will be displayed on `layout.yaxis`.

**Comment by CmpCtrl** [comment]
Copy that. Thanks for the clarification.
