### ISSUE TITLE
Incorrect hover label position after resize

### ISSUE THREAD

**Issue by john-soklaski** [plotly/plotly.js#606]
This doesn't repro with 1.12.0, but does with master.
I have this pointed to a custom bundle of Plotly I have, is there a bundled version of master I can point to? 

Resize the browser window and the labels will be incorrectly offset upon hovering.
https://codepen.io/john-soklaski/pen/beVpLN

**Comment by etpinard** [comment]
Confirmed. Thank you very much!

> is there a bundled version of master I can point to?

Unfortunately. We don't upload a _master_ bundle to our cdn. Using rawgit, like you did, is probably the easiest way to report a bug on the `master` branch.

**Comment by satotake** [comment]
Hi all,
I suspect #575 Pull request might cause this bug

**Comment by etpinard** [comment]
@satotake yes it is. I'll fix it before the next release.

**Comment by john-soklaski** [comment]
@etpinard Thanks! The fix works well for me.

**Comment by etpinard** [comment]
> Thanks! The fix works well for me.

and thank you for reporting the issue :beers:
