### ISSUE TITLE
Plotly JS 3D plotting performance significantly dropped in the recent version

### ISSUE THREAD

**Issue by Koushikphy** [plotly/plotly.js#6063]
I have been using Plotly JS quite extensively for the last few years. I'm using it to make 2D as well as 3D interactive plots. I started using it from version ~ `1.30`, and currently, it's in version `2.8.1`. And one thing I noticed was that the 3D plots, in recent versions, got very slow and laggy. Panning/Moving/Zooming in 3D plots are pretty annoying now. So, for comparison, I made this quick code https://gist.github.com/Koushikphy/36090debffcfc456724c8fccb5ab62e1 that plots the same 3D plot with current and an older version. Indeed, the older version performs better than the latest version for 3D plots.

Is there any reason for this performance degradation? Is there any bug? Were the use case/settings/options changed in some intermediate versions, and do I have to use other options for better performance? 

Please look into this, as this made the 3D plotting experience with Plotly JS pretty poor.

**Comment by archmoj** [comment]
Thanks for the report.
Your code is long and truncated.
Could you please create a minimal codepen e.g. based on [this example](https://codepen.io/MojtabaSamimi/pen/dyVWddB?editors=1000)?

**Comment by Koushikphy** [comment]
Sorry for that. I made this GitHub page https://koushikphy.github.io/PlotlyJS-3D-Performance/ for quickly checking it. Also in the meantime, I noticed something, this problem only happens when I'm working in Linux (Ubuntu 20.04 desktop, checked in Firefox and Chrome). Windows machines doesn't show this problem, both the  versions works equally.

**Comment by Koushikphy** [comment]
Also noticed this performance problem starts from version `1.45.0`

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
