### ISSUE TITLE
trigger hover text on surface possible?

### ISSUE THREAD

**Issue by jneilliii** [plotly/plotly.js#6100]
When attempting to display hovertext in surface plot get error "WARN: Unrecognized subplot: xy". Example codepen: https://codepen.io/jneilliii/pen/podjLdo Made from combining the two examples for [surface plot demo](https://plotly.com/javascript/3d-surface-plots/#topographical-3d-surface-plot) and [triggering hover events](https://plotly.com/javascript/hover-events/#triggering-hover-events) so I'm sure I'm missing something. I've searched the community forum and previous issues and can't seem to find anything related.

**Comment by GnaneshKunal** [comment]
Pass the subplots as the third argument to `Plotly.Fx.hover` func.

Here's what worked for me:
```javascript
chartContainer.current.on('plotly_hover', function (eventdata) {
  var points = eventdata.points[0]
  var pointNum = points.pointNumber
  Plotly.Fx.hover(
    chartContainer.current,
    props.data.map((_, i) => ({
      curveNumber: i,
      pointNumber: pointNum
    })),
    Object.keys((chartContainer.current)._fullLayout._plots))
})
```


`chartContainer.current` is the `div` and `Object.keys((chartContainer.current)._fullLayout._plots)` will return all the existing plots, i.e., `["xy", "xy2", ...]`

**Comment by jneilliii** [comment]
Thanks for the pointer. I've attempted to tweak the button click event but unfortunately still get the same error. I assume there is some magic to the plotly_hover event your hooking into that's not available. I've updated the codepen with the changes. It seems that `(document.getElementById('myDiv'))._fullLayout._plots` is returning an empty object `{}`.

**Comment by gvwilson** [comment]
Hi - we are tidying up issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. For tech support and "how-to" questions, please post in our community forum https://community.plotly.com/. Thank you - @gvwilson
