### ISSUE TITLE
Improper surfacecolor data interpolation in the context of texture mapping onto a surface

### ISSUE THREAD

**Issue by empet** [plotly/plotly.js#6103]
As I pointed out in [https://community.plotly.com/t/applying-full-color-image-texture-to-create-an-interactive-earth-globe/60166/5](https://community.plotly.com/t/applying-full-color-image-texture-to-create-an-interactive-earth-globe/60166/5)
an attempt to map a color image as  a texture onto a surface failed, because of the actual implementation of surface corner data interpolation and mapping  to a colorscale (equivalent to heatmap zsmooth="best", by @alexcjohnson; see [https://community.plotly.com/t/applying-full-color-image-texture-to-create-an-interactive-earth-globe/60166/7](https://community.plotly.com/t/applying-full-color-image-texture-to-create-an-interactive-earth-globe/60166/7). That's why I open this issue  to ask  plotly.js team to find  an alternative to  the actual drawback.
Thank you all!!

**Comment by alexcjohnson** [comment]
To be clear, the current behavior is not a bug, it’s just improper in the context of creating a custom colorscale that is not intended to be interpolated as a colorscale but rather a color lookup table. 

The ideal solution would be to add support for `zsmooth`, and either `false` or `'fast'` would work for the use case @empet is describing. `'fast'` would be a misnomer in this case, as it would be no faster than the other options, it would just mean “interpolate in color space, not in data space,” but if we do implement this I imagine we’d keep this name for consistency.

**Comment by empet** [comment]
Here is the current alternative, using Mesh3d with `intensitymode="cell"`:  [https://chart-studio.plotly.com/~empet/16132](https://chart-studio.plotly.com/~empet/16132).
Since the intensity values returned by color quantization method  are in a one-to-one correspondence with the triangulation vertices, and their number is  less than the number of triangular cells, I  performed the trick illustrated in the attached image. Even with this color approximation the result is surprinsingly good (see both plots from the above notebook).  
![intensity-vertex-to-cell](https://user-images.githubusercontent.com/3627253/152341833-c3e09029-1837-4d70-83da-baeb87a01eb7.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
