### ISSUE TITLE
Empty plot for mesh3d with alphahull>0

### ISSUE THREAD

**Issue by empet** [plotly/plotly.js#6131]
As it is pointed in [https://github.com/plotly/plotly.py/issues/3615](https://github.com/plotly/plotly.py/issues/3615), the mesh3d with alphahull>0 doesn't work. I checked it with Plotly 5.6 and got an empty plot. But for alphahull=-1 and 0,  it displays the Delaunay triangulation, respectively the convex hull of the data set.

**Comment by archmoj** [comment]
Thanks for the report.
Regression introduced in [v2.6.0](https://github.com/plotly/plotly.js/releases/tag/v2.6.0) and possibly related to #6004.
Here is a [codepen](https://codepen.io/MojtabaSamimi/pen/wvPZyBj).
