### ISSUE TITLE
Histograms nbinsx and nbinsy descriptions are wrong 

### ISSUE THREAD

**Issue by yankev** [plotly/plotly.js#614]
Example:
After setting the [`nbinsx`](https://plot.ly/javascript/reference/#histogram2d-nbinsx) parameter to 20, the number of bins showing is 15. Also tried with other values for `nbinsx`, and results vary. 

https://jsfiddle.net/2k0q2yg8/

**Comment by etpinard** [comment]
Ha. That's a description bug.

`nbinx` doesn't directly set the number of bins but the **maximum** number of bins allowed by the [autobin](https://github.com/plotly/plotly.js/blob/27503920d1d3e98a002f7cb87a0eed1033f7eda7/src/plots/cartesian/axes.js#L367-L467) algorithm. The autobin algorithm attempts to keep the bin size _nice_.

The old plot.ly workspace got this right:

![image](https://cloud.githubusercontent.com/assets/6675409/15898088/e1221d06-2d64-11e6-9e0b-31673f0d77d1.png)

i.e. that _Max # X bin_ row.

For fully custom bin sizes, you should use `xbins.start`, `xbins.end`, `xbins.size`.

Changing the issue accordingly.

**Comment by etpinard** [comment]
@yankev wanna try to make PR for this?
