### ISSUE TITLE
Contour throws exceptions when trying to infer x and y axis types after switching from numerical to category.

### ISSUE THREAD

**Issue by ArminTaheri** [plotly/plotly.js#615]
http://codepen.io/armintaheri/pen/NrGLxY

When plotting a contour plot with x-axis set to a numerical array, then calling restyle with a categorical array, then calling relayout with `{'xaxis.type': '-'}`, The following exceptions are thrown:

```
Error: <path> attribute d: Expected number, "M,0L,0L,270L,270Z".
Uncaught TypeError: Cannot read property '0' of undefined
```

And the plot does not change its axis type.

**Comment by etpinard** [comment]
Strange.  Restyling a categorical `x` to a linear type works fine.

Thanks for reporting.

**Comment by etpinard** [comment]
This bug is still present in `1.20.x`, but at least now a workaround : replacing `restyle` + `relayout` by `Plotly.update` works as desired.

**Comment by etpinard** [comment]
Potentially fixed in https://github.com/plotly/plotly.js/pull/1999 cc @alexcjohnson
