### ISSUE TITLE
issue with Plotly.react() graph update when using cdn.plot.ly/plotly-latest.min.js

### ISSUE THREAD

**Issue by lorcat** [plotly/plotly.js#6164]
Hi!
I have not found a similar bug in the list of the current issues, I am also not sure where it should be posted.

The bug reproduction can be found in [codepen](https://codepen.io/lorcat-the-sasster/pen/XWVZjNR).
The idea is simple - to add dynamically point by point to the graph through _Plotly.react('myDiv', data, layout);_ and using _setInterval()_ functionality.

The code shows that while the title is updated, the graph is not updated at all. I can only trigger a graph update through a manual switching off/on the graph using the legend. Tried chrome, firefox, same result. Any advice would be appreciated.

**Comment by alexcjohnson** [comment]
You're updating the data arrays in place, which we explicitly don't check for. But you can _tell_ us that the arrays have updated by using `layout.datarevision` that changes every time the data changes. See https://codepen.io/alexcjohnson/pen/gOovgBj where I set `layout.datarevision = d.toLocaleTimeString();`

Another point (that I updated in my fork of your codepen): `plotly-latest` is no longer updating, it's stuck at the end of the 1.x series. Use a specific version on the 2.x series.

**Comment by lorcat** [comment]
Many thanks! I guess it resolves it.
