### ISSUE TITLE
Re: Scatter3d zoom options for detail zooming

### ISSUE THREAD

**Issue by adeelibr** [plotly/plotly.js#6175]
I am not sure if this should be labeled as a feature or maybe missing documentation if the feature already exists;

I am looking for detail zoom options similar to https://plotly.com/javascript/zoom-events/ but for `scatter3d` chart, where I have multiple traces and on zooming I get a beginning of x-axis range and end of x-axis range.

But the `plotly` event (plotly_relayout) or the reactjs alternate `onRelayout`, do not return me the event as shown in the example above i.,e here https://plotly.com/javascript/zoom-events/ ;

With scatter3d the object `plotly_relayout` event throws is

```js
{
    "up": {
        "x": 0,
        "y": 0,
        "z": 1
    },
    "center": {
        "x": 0,
        "y": 0,
        "z": 0
    },
    "eye": {
        "x": 0.2451076909967036,
        "y": 0.24510769099670354,
        "z": 0.24510769099670354
    },
    "projection": {
        "type": "perspective"
    }
}
```

This information does not help in identifying the x-axis range begin/end. To make a detail zoom request with a respective BE.

Is there another event that would give me this information? If no, then is it possible to add this feature with scatter3d. I can help. But I would need some guidance in navigating through the code base.

**Things I did before creating the issue**

- [x] searched github issues
- [x] searched plotly docs
- [x] searched stackoverflow for similar issues

**Comment by alexcjohnson** [comment]
Thanks @adeelibr - the challenge is we're not actually restricting the axis ranges upon zoom / pan / rotate events for 3D scenes. The visible region does get clipped as you zoom in, but the clipping planes aren't aligned with the axes.

I suppose we could try to calculate and return these planes with the event data, maybe as a set of four vectors `v_i` (or five? I think perhaps we clip points too close to the eye? I don't know if that's a plane though), I guess from the `center` point... then you could retrieve the set of visible points by filtering on something like `dot(dataPoint - center, v_i) < dot(v_i, v_i)` for each `v_i`.

Would that be useful? It seems like a cumbersome effort for the user, but I don't see a simpler way to do it.

**Comment by adeelibr** [comment]
I see that python version has range slider availability, but there is no option to do that in javascript version of 3d chart. If that possible, maybe I can use that range slider and integrate that with a BE api. 

Is something like that possible with plotly javascript scatter3d range slider?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
