### ISSUE TITLE
set defaults on mesh3d lighting

### ISSUE THREAD

**Issue by VeraZab** [plotly/plotly.js#618]
Hey, 
would you mind setting default values on these:
'mesh3d.lighting.facenormalsepsilon'
'mesh3d.lighting.vertexnormalsepsilon'

thanks!

**Comment by etpinard** [comment]
Hmm.

Looks like that's already done [here](https://github.com/plotly/plotly.js/blob/9ee53c9af2c516d4c5fd4e80d1cba6e7bab95e48/src/traces/mesh3d/attributes.js#L181) and [here](https://github.com/plotly/plotly.js/blob/9ee53c9af2c516d4c5fd4e80d1cba6e7bab95e48/src/traces/mesh3d/attributes.js#L190).

I was afraid that `1e-12` wasn't JSON serializable, but looks like that's not the case:

![image](https://cloud.githubusercontent.com/assets/6675409/15908218/8a4de116-2d8e-11e6-9c6f-8fe1a71867dc.png)
