### ISSUE TITLE
Default tickformat in yaxis now shows too many decimal places

### ISSUE THREAD

**Issue by pietersv** [plotly/plotly.js#6184]
Somewhere between version 2.2.0 and version 2.3.0 the behavior of Plotly changed such that simple d3-style entries for `tickformat` such as `,f` and `%` now show lots of extra zeros after the decimal places, whereas they used to neatly snap to round numbers before.

Below is current compared to previous:

<img width="239" alt="image" src="https://user-images.githubusercontent.com/10464727/167662973-901201b5-24f4-4f88-8d6c-20650cd499d3.png">  <img width="222" alt="image" src="https://user-images.githubusercontent.com/10464727/167662855-81349196-6984-4b1e-b16d-a0f559652397.png">

- v2.3.0 (https://codepen.io/__proto__/pen/MWQegpy)
- v2.2.0 (https://codepen.io/__proto__/pen/xxYOKXP)

**Comment by nicolaskruchten** [comment]
@archmoj did you guys look into this one?

**Comment by alexcjohnson** [comment]
I wasn't able to reproduce - those codepens always looked identical to me. @pietersv did you close this because the issue resolved itself for you? Perhaps there's some browser out there that has a problem here?
