### ISSUE TITLE
Feature Request: Make plotly_click events in 3d plots consistent with 2d

### ISSUE THREAD

**Issue by CmpCtrl** [plotly/plotly.js#6185]
There are some issues/limitations with the 3d plot events, particularly the click event, that aren't present in the equivalent 2d plots. It would really help their functionality to be consistent with the 2d events. 

I've been working specifically with `scatter3d` (or `surface`) plots and the `plotly_click` event. 

My biggest issue is that the `plotly_click` event is fired on `mousedown` (in a 2d `scatter` it is fired on `mouseup`). That makes it impossible to tell if the user is intending to select a point, or to click and drag to rotate/pan/zoom, etc. That is an issue since typically a callback related to selecting a point conflicts with a drag to rotate operation. Again, the 2d scatter behaves as intended. 

Here is a simple demo, the click events are logged to the console, you'll note that in the 2d `scatter`, click and drag (to zoom) does not fire a `plotly_click` event, but doing the same thing in the 3d surface plot does fire the `ploty_click` before the drag functionality. 
[https://codepen.io/cmpctrl/pen/rNJLNLd](https://codepen.io/cmpctrl/pen/rNJLNLd)

One thing i hoped to use to workaround this issue was to detect if the user right clicked on the plot. Unfotunately, the DOM `MouseEvent` data that is, very usefully, included in the 2d `click_data` is missing in the 3d plots. 

Similarly, there is no `plotly_doubleclick` event for 3d. 

Some related issues, there may be more. 
#2565
#3266 
#5590

**Comment by CmpCtrl** [comment]
I did a little more digging and it seems like it won't be easy to add the DOM `MouseEvent` data to the `eventData` but it should be relatively easy to add some more data to it, which at least would help with detecting which button is clicked.. 

I think the relevant section is here:
[https://github.com/plotly/plotly.js/blob/12a49c0f225dea785c98bd36f6820091d98d2d85/src/plots/gl3d/scene.js#L403-L420](https://github.com/plotly/plotly.js/blob/12a49c0f225dea785c98bd36f6820091d98d2d85/src/plots/gl3d/scene.js#L403-L420)

What about adding something like the following? Any other useful tidbits we could include here?
``` js
var eventData = {
    points: [pointData],
    buttons: selection.buttons,
    distance: selection.distance,
};
```

Then it seems like the `plotly_click` event could be moved from here, which happens at the start of a click and drag. 

[https://github.com/plotly/plotly.js/blob/12a49c0f225dea785c98bd36f6820091d98d2d85/src/plots/gl3d/scene.js#L450-L465](https://github.com/plotly/plotly.js/blob/12a49c0f225dea785c98bd36f6820091d98d2d85/src/plots/gl3d/scene.js#L450-L465)

While i was looking at this, i also noticed that the `plotly_unhover` fires at every step of a click or drag, which doesn't seem helpful. Perhaps that could be addressed at the same time. 

Something like the following? This is completely untested... 
``` js

        if (!selection.buttons && !selection.distance < 5) {
            gd.emit('plotly_hover', eventData);
            this.oldHoverState = true;
        }

        this.oldEventData = eventData;
    } else {
        Fx.loneUnhover(svgContainer);
        if (this.oldHoverState) {
            gd.emit('plotly_unhover', this.oldEventData);
        }
        this.oldHover = undefined;
        if (this.oldEventData && this.oldEventData.buttons && this.oldEventData.distance < 5) {
            gd.emit('plotly_click', this.oldEventData);
        }
        this.oldEventData = undefined;
    }

    scene.drawAnnotations(scene);
};
```

I hesitate to try to make a pr for this since i have almost no experience with js and dont feel like i understand it well enough to make a reliable change. Can i just add `this.oldHoverState` like that? or does that need to be defined elsewhere?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
