### ISSUE TITLE
In polar layout the griddash attribute for  radialaxis/angularaxis (listed in reference) is not accepted/active

### ISSUE THREAD

**Issue by empet** [plotly/plotly.js#6186]
By javascript and python reference for plotly.js, respectively plotly.py, there is a radialaxis  attribute, `griddash`:
[https://plotly.com/javascript/reference/layout/polar/#layout-polar-radialaxis-griddash](https://plotly.com/javascript/reference/layout/polar/#layout-polar-radialaxis-griddash),
[https://plotly.com/python/reference/layout/polar/#layout-polar-radialaxis-griddash](https://plotly.com/python/reference/layout/polar/#layout-polar-radialaxis-griddash)
    
But plotly.py throws the error    

```
ValueError: Invalid property specified for object of type plotly.graph_objs.layout.polar.RadialAxis: 'griddash'
``` 
when in polar layout is set  `radialxis_griddash="dash"`, while PlotlyJS.jl displays the   radialaxis with the default `"solid"`
style.  
It seems that  plotly.js replaces the griddash read from  the figure json version (created by PlotlyJS.jl) with `gridash="solid"`.
Is this the intended behaviour?  I ask because on plotly community has been asked a question on how to plot a dashed radialaxis      https://community.plotly.com/t/barpolar-is-it-possible-to-change-radialaxis-line-style/63872

**Comment by archmoj** [comment]
Here is a [demo](https://codepen.io/MojtabaSamimi/pen/RwQRdWO?editors=0010).

**Comment by nicolaskruchten** [comment]
You'll have to upgrade to `plotly==5.8` (released last night) for these to work :)

<img width="937" alt="image" src="https://user-images.githubusercontent.com/203523/167916902-e53b16d3-a779-4e8d-ad47-282079f448d0.png">

**Comment by empet** [comment]
Wow! But I don't understand  why plotly.py says that there is no such attribute for radialaxis, and PlotlyJS.jl displays ii as a solid line.
This is my code:
```
fig = go.Figure(go.Barpolar(
                    r=[3.5, 1.5, 2.5, 4.5, 4.5, 4, 3],
                    theta=[65, 15, 210, 110, 312.5, 180, 270],
                    width=[20,15,10,20,15,30,15,],
                    marker_color="#ff8c00",
                    marker_line_color="black",
                    marker_line_width=1))

fig.update_layout(
    template=None,
    polar = dict(
        radialaxis = dict(range=[0, 5], showticklabels=False, ticks='', griddash='dash'),
        angularaxis = dict(showticklabels=False, ticks='')
    )
)

fig.show()
```
I install just now the last Plotly version and check again. I have 5.7.0

**Comment by empet** [comment]
OK, it works with Plotly 5.8.0.

**Comment by nicolaskruchten** [comment]
The `graph_objects` module provides python-level validation and error messages for the Plotly.js schema whereas PlotlyJS.jl doesn't... it's just a different design. We prefer the Python module this way so there is less confusion about which version of Plotly.js is baked in. V5.7 came with Plotly.js 2.11 which didn't have grid dash support so it would have been weird for it to accept this attribute without complaining.

As of Plotly.js 2.9 you can mouse over the Plotly logo in the modebar to check which version of Plotly.js you have.

**Comment by empet** [comment]
PlotlyJS.jl has not been updated since october 5, 2021.   Hence it is backed with an older plotly.js version.
