### ISSUE TITLE
Problem with setting axis titles in 3D surface plot

### ISSUE THREAD

**Issue by pranabdas** [plotly/plotly.js#6196]
I want to set axes titles in 3D surface plot. However, it always shows default "x", "y", and "z".

### Steps to reproduce:
1. Open one of the 3D surface plot examples in CodePen <https://plotly.com/javascript/3d-surface-plots/>
2. Pass custom axis titles in the layout, e.g., 
```
var layout = {
  xaxis: {title: "x-title"},
  yaxis: {title: "y-title"},
  zaxis: {title: "z-title"},
  title: 'Mt Bruno Elevation With Projected Contours',
  scene: {camera: {eye: {x: 1.87, y: 0.88, z: -0.64}}},
  autosize: false,
  width: 500,
  height: 500,
  margin: {
    l: 65,
    r: 50,
    b: 65,
    t: 90,
  },
};
```
3. But it still shows "x", "y", "z" instead of "x-title", and so on.

Thank you.

**Comment by archmoj** [comment]
In your code you need to put axis inside `scene`.
Also I suggest you set `title.text` instead of `title` to the string.
Here is a working [demo](https://codepen.io/MojtabaSamimi/pen/rNJwyZw?editors=0010).
