### ISSUE TITLE
Filled Lines example should use fill:'toself' instead of  fill:'tozerox'

### ISSUE THREAD

**Issue by john-soklaski** [plotly/plotly.js#620]
This is regarding https://plot.ly/javascript/continuous-error-bars/#filled-lines
If you click on "Autoscale" the confidence traces extend left, to x=0. 

Adjusted version:
http://codepen.io/john-soklaski/pen/YWwXGe

**Comment by etpinard** [comment]
moved to https://github.com/plotly/documentation/issues/423
