### ISSUE TITLE
How can i make only integer for Y / X lines? 

### ISSUE THREAD

**Issue by StasSpawn** [plotly/plotly.js#6210]
I want only 1, 2, 3, 4, 5 ...

![2022-06-06_131232](https://user-images.githubusercontent.com/56681850/172141722-803aacc9-2ee2-4e2a-b6dd-730bbce4f6b2.png)

**Comment by alexcjohnson** [comment]
This kind of question is better suited to https://community.plotly.com/, but you can use [`xaxis.dtick=1`](https://plotly.com/python/tick-formatting/) to force the tick spacing you want.
