### ISSUE TITLE
[Bug] Hoverable Control Labels Misaligned

### ISSUE THREAD

**Issue by OscarPinchen01** [plotly/plotly.js#6211]
Hello there, ☺️

We've been having some issues with the hoverable control labels on Plotly graphs and charts. In some instances they simply don't quite line up with the icons that they're meant to represent and, in other more severe instances, the constituent components of the labels actually come apart. The instances of the latter seem to happen on Safari only, although it could be worth investigating these on multiple different browsers as there's every possibility that they behave differently.

<img width="202" alt="Screenshot 2022-05-10 at 10 52 10" src="https://user-images.githubusercontent.com/104358534/172328475-c8fdb99d-33c2-4a96-b96a-df5948867600.png">

![image-20220504-092356](https://user-images.githubusercontent.com/104358534/172328828-86d8f900-2851-4952-985c-e9e1b81417de.png)

**Comment by alexcjohnson** [comment]
Thanks @OscarPinchen01 - The first screenshot looks reasonable to me, can you say more about what's incorrect there?

The second one is obviously wrong but I can't reproduce the issue. Would you be able to create a codepen that shows this behavior?

**Comment by OscarPinchen01** [comment]
Hi @alexcjohnson,
Thanks so much for taking the time to get back tome regarding my issue post and apologies for being so slow at getting back to you.
I started putting together a codeSandbox to demonstrate my issue but, in the process, actually identified the error in our codebase that was causing the alignment issues.
For anyone who stumbles upon this in the future, be wary of applying 'display: block;' universally to svg's as this'll do strange things with label alignment.
I'm not sure what the process is from here, but I suspect this issue can be closed. Many thanks again for considering my issue. 🙌

**Comment by alexcjohnson** [comment]
Excellent! Yes, we create a lot of elements inside our plots and it’s frustratingly easy for your CSS to leak in there. Glad you figured it out!
