### ISSUE TITLE
Missing `libnss3_3.42.1-1+deb10u3_amd64.deb` at `security.debian.org/debian-security/pool/updates/main/n/nss/`

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#6214]
The `export-test` on `master` branch is not passing on CircleCI at the moment with the following error:
https://app.circleci.com/pipelines/github/plotly/plotly.js/6754/workflows/26a33f7f-f5bf-44d5-866e-3372002d1023/jobs/154658

![Screenshot from 2022-06-09 12-02-47](https://user-images.githubusercontent.com/33888540/172893510-b7f520fb-a331-4703-9aa1-f63d720d986a.png)

It looks like the file to install `poppler-utils` for exporting to `eps` format is removed from their website.

**Comment by antoinerg** [comment]
We should run this first: `sudo apt-get update --allow-releaseinfo-change`

Reference: https://www.linuxtutorials.org/This-must-be-accepted-explicitly-before-updates-for-this-repository-can-be-applied-See-apt-secure-8-manpage-for-details/
