### ISSUE TITLE
Contour ignores request to hide legend

### ISSUE THREAD

**Issue by scottstanfield** [plotly/plotly.js#622]
Code:

`plot_ly(x = runif(5), y=runif(8), z=runif(5), type="contour", showlegend=F)`

Expected:
The vertical legend (labeled `runif,5`) to be hidden/missing.

Results:
http://cl.ly/gPR6

![contour-with-showlegend-false](https://s3.amazonaws.com/f.cl.ly/items/0R1q2S2f3s0d0X1n0U1T/Image%202016-06-09%20at%2012.45.08%20PM.png)

**Comment by etpinard** [comment]
You mean the colorscale?

Try setting `showscale` to `false` (or whatever that is in R).

**Comment by cpsievert** [comment]
@scottstanfield this is what you're looking for:

```r
plot_ly(x = runif(5), y=runif(8), z=runif(5), type="contour", showscale=F)
```

**Comment by scottstanfield** [comment]
That totally worked; thanks. More of a documentation thing then. Conflated scale with legend. Thanks!
