### ISSUE TITLE
Move image separetly from other plot (js)

### ISSUE THREAD

**Issue by StasSpawn** [plotly/plotly.js#6229]
Can i move **image** separatly from **markers, grid and all other stuff**? 

Here i have an image (Python logo) and a lot of info, 

And i need to move image regardless to anything other. So image is moving, but markers staying on their initial position. 

![2022-06-15_122605](https://user-images.githubusercontent.com/56681850/173794217-e2c82b44-2dcb-4cee-9f9d-462e4a1751ca.png)

**Comment by alexcjohnson** [comment]
This kind of question is better suited to https://community.plotly.com/, but to get you started I'd suggest using a second set of x and y axes, set to overlay the first set, and put either the image or the markers onto that second set. Then mark the axes that the markers are on as `fixedrange: true`

**Comment by StasSpawn** [comment]
Hi @alexcjohnson 
Thank you for the answer. 

No one is giving replies here https://community.plotly.com/
So, i'm trying other ways:)
