### ISSUE TITLE
is there is any way to change tooltip position and size and align text to center in tooltip ?

### ISSUE THREAD

**Issue by viramjain13** [plotly/plotly.js#6241]
Hi Need help in customizing a tooltip in plotly.js. I want to make a tooltip like this  
![tooltip](https://user-images.githubusercontent.com/86965162/174868057-fe5a281c-ca7a-4277-9849-b2c158ee4bc4.png)

 There is any way to customize a tooltip? Please help .thanks in advance

**Comment by alexcjohnson** [comment]
There's a little bit of customization you can do within plotly.js itself https://plotly.com/python/hover-text-and-formatting/#customizing-hover-label-appearance but more substantial customization requires breaking out of this, for example the Dash `dcc.Tooltip` component https://dash.plotly.com/dash-core-components/tooltip

**Comment by rezam7596** [comment]
This issue is mention on JS forum. the links you provided are for python. as far as I investigate we cannot use `dcc.Tooltip` in JS. There should be a way to customize the tooltip fully, like providing a component to the plotly.

**Comment by gvwilson** [comment]
https://www.rainbowrailroad.org/
