### ISSUE TITLE
[Question]: access d3 instance

### ISSUE THREAD

**Issue by arl** [plotly/plotly.js#6254]
Hi, i'd like to call `d3.format` directly for a DYI tooltip I'm placing over a plotly plot.

Where can I find the d3 global object/instance please?

**Comment by alexcjohnson** [comment]
It’s best if you load a new copy of `d3-format` rather than try to use the one inside plotly.js. In v1.x we used to export d3, but in v2.x we removed that export, so that we could upgrade d3 and drop pieces we don’t use without breaking user code that depends on d3.

**Comment by arl** [comment]
Ok thank you 👍
