### ISSUE TITLE
Discord server?

### ISSUE THREAD

**Issue by WhiteBlackGoose** [plotly/plotly.js#6255]
Hey, community!

I suggest creating a discord server for plotly.js. I already [suggested](https://github.com/plotly/plotly.py/issues/3808) it in `plotly.py`, however, now I came to an idea that maybe it's better if we create *one* server for both libraries. Or even for the whole `plotly`. What do you think?

**IF YOU'RE INTERESTED, SEE [ISSUE BELOW](https://github.com/plotly/plotly.js/issues/6255#issuecomment-1194433983)**

**Comment by WhiteBlackGoose** [comment]
Yeah, there definitely is!

I've been a member of a whole bunch of community discord servers, such as that of C#, F#, Java, as well as a couple of particular projects. So I'm willing to tell more about it (and if needed, administrate).

### Discord is a chat
Not a forum. It means, the threshold for questions is much lower. You can come, quickly ask how to pass a parameter somewhere, and get an answer.

Of course, the maintainers of plotly.js don't have to answer - the whole point of community server is that anyone can help.

### It's universal
One problem with forums - you have to register there all the time. It's not hard of course, but it's yet another time you leave your "digital trace" somewhere.

Discord, of course, is not as popular as telegram or whatsapp or facebook. But it's still *very* popular among developers (again, mentioning those servers, hugest and most active communities of their kinds. C# server is 30k+, the Python one is over 200k).

### Not just chat
You can add a lot of channels, manage roles, add some automatic management and moderation (e. g. banning scammers, or remove messages containing executables).

### Screenshot from the C# server
![image](https://user-images.githubusercontent.com/31178401/178741418-eb031ee3-8ada-4bb2-8d28-a1dc0dd45405.png)

Oh, and it's also free, as a bonus.

**Comment by WhiteBlackGoose** [comment]
@Coding-with-Adam in case you didn't receive it, I responded to your email the same day.
If someone else wants to discuss details about moving plotly to discord with me, I'm Oryp4ik#0120 on discord and the @WhiteBlackGoose on telegram.

**Comment by Coding-with-Adam** [comment]
Thank you for alerting me @WhiteBlackGoose . I just checked my Spam and saw your two emails there. I'm answering you right now.

**Comment by WhiteBlackGoose** [comment]
## Conversation notes

I suggested using Discord as a medium of talking about plotly and asking/answering users' questions about it.

### Why

In my opinion, there are many people who would prefer Discord over forums. Chats in general are more beginner-friendly, when properly moderated. Plus, we can always keep channels for beginners and "advanced" channels separated, if we want.

So, with a beginner-friendly support, we may get more people getting started with plotly. Especially those, who already use Discord and do not want to use other online platforms.

Let's go over why I think discord could be a good change:
- Live chatting. When a community is active, you get responses for easy questions within a minute.
- Relaxed requirements for people who're trying to help. You don't have to spend a while writing a whole post like you'd have to on StackOverflow or other forums. If the user has a question regarding your solution, they ask and get help live.
- Relaxed community. E.g. we can have an #off-topic channels and things. It never hurts. Plus we can have a "gallery" where we'd have people posting their projects - you could even use it for readme or showcase.
- No need to create an account if you already have a Discord account (unlike Slack and forums). I personally am part of a whole bunch of both community and official discord servers. Joining one as simple as clicking the invitation link.

### Things to think about

Adam said that he likes the idea of offering discord-only community users a place to learn Plotly; however, Forum questions and answers are searchable by Google, which means people that need help could easily find the answers on Google because it leads them to the question on the Plotly Forum. Questions and answers are not discoverable on Discord. In addition, Adam's time and resources are focused on making the Forum an even better place for users to find answers and share their Plotly success stories. Therefore, creating a new Discord Plotly server, maintained by Adam, is not an option right now. 

If the community decided to create a Plotly server on Discord, they should ask themselves: How do we ensure to overcome the threshold, where people within the Discord community-driven server start helping each other out?

I recommended having maintainers and active contributors on the server so that people who come would get help. Theoretically, we eventually get to the point where active members start helping newcomers. But will it actually happen? I also said that maintaining this server would mean a lot of initial effort from community maintainers/contributors/moderators. That's why we have to understand if it's gonna be worth it.

### Suggestion

I'll keep this issue open for a while.

- Please, vote with :+1: if you'd like to have a Discord server to *ask* questions there.
- Please, vote with :rocket: if you'd like to *help others* with plotly on this server.

Also feel free to add other suggestions, pros, cons, or other things to think about.

**Comment by renegoretzka** [comment]
You have my vote. If you need Moderator/Admins, let me know. I am experienced with bigger Discord Communities :)

**Comment by h-connor** [comment]
Bump. Discord would be great! I've had some questions that didn't receive responses on the forums, a live-chat can have many benefits.

**Comment by evbo** [comment]
one problem with the Plotly forum is it requires separate login, whereas Discord offers federated login through Github.

Honestly... too many web accounts is enough of a hurdle to prevent me from signing up for the forum. Please consider offering a discord

**Comment by bhargavkakadiya** [comment]
@WhiteBlackGoose Thanks for pushing on the discord Server; Is there any unofficial community on discord for Plolty?

**Comment by Coding-with-Adam** [comment]
hi @WhiteBlackGoose and All,
We are in the planning phase of creating an official Plotly Discord server. We would need a few volunteers to help moderate the server, especially in the first 6 months. 

Would anyone here be interested in volunteering? 

@evbo @h-connor @renegoretzka @WhiteBlackGoose

**Comment by WhiteBlackGoose** [comment]
Haha that took a while. But while you haven't created it yet, I'd recommend going with matrix space instead. Discord is proprietary and who knows what happens to it when some Elon Musk buys it.

**Comment by TimChinye** [comment]
Did this ever come into fruition? It's been almost 2 years since the ETA*

**Comment by Coding-with-Adam** [comment]
hi @TimChinye ,
yes, thanks for asking. Here's the Discord server: https://discord.gg/Pa8scsgepB
