### ISSUE TITLE
Impossible to disable triangular selection (zooming) on ternary plots

### ISSUE THREAD

**Issue by blokhin** [plotly/plotly.js#628]
Mouse selection is supposed to be disabled here, but it is not so: http://codepen.io/anon/pen/ZOQNmO

**Comment by mdtusz** [comment]
Thanks for reporting this!

**Comment by etpinard** [comment]
To clarify a little bit: `ternary.?axis.fixedrange` was never intended to work in `ternary` subplot.

**BUT** the `staticPlot` config should be honoured. Thanks for reporting.
