### ISSUE TITLE
Node hover effect not working correctly in Sankey plots

### ISSUE THREAD

**Issue by esiivola** [plotly/plotly.js#6328]
There seems to be an issue with Sankey plots' nodes' hover effect. When hovering over a node, not all traces entering and exiting that node are fully highlighted.

reproducible example: https://codepen.io/esiivola/pen/ZEovKvN
Instructions: Place your mouse over the node with the title "D". "trace 1" is now highlighted and "trace 2" is highlighted from "H" to "D" and from "D" to "F", but not from "F" to "B". 

Correct behavior should be that either traces 1 & 2 are fully highlighted OR only the segments from "H" to "D" and from "D" to "F" 

This issue has been discussed here (https://community.plotly.com/t/sankey-node-hover-issue/28324) as well but I didn't find a solution or bug ticket.

**Comment by archmoj** [comment]
Thanks for the report.
