### ISSUE TITLE
[BUG] Series plot hover only shows first line

### ISSUE THREAD

**Issue by fsantiago99** [plotly/plotly.js#6331]
Hi all. I've updated to plotly v2 and all the plots with series only shows the first line in the hover box.

If I revert to version 1.58.5 it works perfectly.

Codepen: https://codepen.io/fsantiago99/pen/jOxZVmz
(You can change the plotly version in the scripts)

Expected behaviour:
![image](https://user-images.githubusercontent.com/33151376/192997795-98081ab4-3c5c-43b1-8d78-4c8c165f1ac9.png)

Current Plotly v2 behaviour:
![image](https://user-images.githubusercontent.com/33151376/192998013-b493d678-0718-4585-a793-60f1bc55fa05.png)

Thanks in advance

**Comment by archmoj** [comment]
Thanks for the report. It looks like a bug with `multicategory` axis type to me. @alexcjohnson no?

**Comment by alexcjohnson** [comment]
@archmoj I think you're right, if I replace the x data in that codepen with just the integers on a normal numeric or category axis we see all the data on hover. Thanks for the report @fsantiago99!
