### ISSUE TITLE
Github version does not match NPM Version

### ISSUE THREAD

**Issue by radicodes** [plotly/plotly.js#6340]
Github's latest version for this package is 2.15.0, however NPM's latest version is 2.14.0.  We are facing an issue where one of our dependencies is expecting 2.15.0, but is failing to get that from NPM and it has broken our build.

**Comment by radicodes** [comment]
https://www.npmjs.com/package/plotly.js/v/1.47.4 NPM versions

**Comment by radicodes** [comment]
Thank you!  Best of luck 😄

**Comment by archmoj** [comment]
Both `2.15.0` and `2.15.1` are now available on the npm.

**Comment by radicodes** [comment]
Thank you everyone for your fast turnaround on this!
