### ISSUE TITLE
Is it possible to remove the root element of a treemap ?

### ISSUE THREAD

**Issue by GeorgeFlorian** [plotly/plotly.js#6343]
I don't need the root element in the treemap chart that I am using.

I have set `hovertemplate: '%{label}<br />%{value}% <extra></extra>'` and since the root doesn't have any labels or values I get warnings in the console 
```
console.trace() WARN: Variable 'label' in hovertemplate could not be found!
console.trace() WARN: Variable 'value' in hovertemplate could not be found!
console.trace() WARN: Too many hovertemplate warnings - additional warnings will be suppressed
```

Also when I hover over the root element it shows the hovertemplate as `%{label} %{value}%` which is not wanted.

**Comment by hieuvts** [comment]
I think you could use event 'plotly_hover' and Plotly.react to update the hovertemplate.
