### ISSUE TITLE
Improve on Mesh3d colorscale documentation

### ISSUE THREAD

**Issue by VeraZab** [plotly/plotly.js#636]
This should not be an attribute of mesh3d: https://plot.ly/javascript/reference/#mesh3d-colorscale

**Comment by mdtusz** [comment]
As discussed earlier, I'm not sure that _it shouldn't be a part of it_ - it just needs better documentation, and very possibly, an implementation.

Talking briefly with @monfera earlier, it may be possible for us to modify the frag shader (or a wrapper around facecolor) to work using the z-position for coloring, but this will require someone a bit more knowledgable on our webgl front.

**Comment by mdtusz** [comment]
#643 has added a mock that uses mesh3d colorscale, but we could still improve upon the documentation so I will leave this open for the time being.

**Comment by etpinard** [comment]
Probably good enough after https://github.com/plotly/plotly.js/pull/1719/
