### ISSUE TITLE
License for code taken from https://bl.ocks.org/nolanlawson/0eac306e4dac2114c752

### ISSUE THREAD

**Issue by Bansems** [plotly/plotly.js#6364]
The code snippet taken from https://bl.ocks.org/nolanlawson/0eac306e4dac2114c752 and used in the file snapshot/helper.js does not has a license.

Is Plotly allowed to use this code under the MIT licence?

**Comment by alexcjohnson** [comment]
Thanks @Bansems - we probably should be more careful with attributions and licenses, though in this case it looks to me like a dead end: that block points - for the specific chunk we copied - to [this StackOverflow post](https://stackoverflow.com/questions/14967647/encode-decode-image-with-base64-breaks-image) which itself states that the solution came from [this defunct Evernote](https://www.evernote.com/shard/s18/sh/50ea8199-3f8c-4061-8c90-82e264380412/2c92f01382e0b35e1a48fd8e173ac8b2?noteKey=2c92f01382e0b35e1a48fd8e173ac8b2&noteGuid=50ea8199-3f8c-4061-8c90-82e264380412) and if I understand it correctly, it really should have been the license on that Evernote - if there was one - that governed this snippet of code. But now we can't even tell who the original author was. So ... ?

Anyway if it's relevant, that snippet is the obvious implementation of "convert the string into an ArrayBuffer," so the value here is simply recognizing that this is what you need as input to `window.Blob`.

**Comment by Bansems** [comment]
Thank you for the response @alexcjohnson.

I am asking because the License Compliance tool Black Duck has flagged it as a possible licence risk. Our security department has asked me to come with a solution.

Is it possible for you to change the code, so that it can be used under the MIT License without any problem?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
