### ISSUE TITLE
gd.data must be an array 

### ISSUE THREAD

**Issue by patson12** [plotly/plotly.js#6376]
hello,

i am working with plotly graph . i have one div container and this container will be changed with option select.. now when i choose chart , the chart is working fine.. but when i change the div container content , and then back to chart. it gives me error like..
"gd.data must be an array "

also when i console t.data it shows t.data undefined ..
i am working  with javascript .. PFA the screenshot of error
![Capture](https://user-images.githubusercontent.com/96180028/203471333-ff3bd222-e197-4a1b-bf63-bba39ede25e0.JPG)

Thanx and Regards,
harshad

**Comment by alexcjohnson** [comment]
@patson12 usage questions like this are better suited to https://community.plotly.com/c/plotly-js/6 - would you mind moving the question over there? Also, in order to help they're going to need more information about *how* you're changing the content - ie the specific code you're using.
