### ISSUE TITLE
Save Plot (camera icon) doesn't work in Chrome

### ISSUE THREAD

**Issue by mwho** [plotly/plotly.js#638]
This happened with the latest Chrome update - before that I didn't have any problems with Chrome. So far it looks like Firefox is okay.

Whenever I try to download a plot via the little camera icon in the upper right corner, I got the following error.

![image](https://cloud.githubusercontent.com/assets/1095711/16025806/98fea3dc-317e-11e6-82a9-71bf5b7df38e.png)

**Comment by etpinard** [comment]
Should be fixed by https://github.com/plotly/plotly.js/pull/604

Which is now part of version `1.13.0` and on our CDN. 

Can refresh your page a couple times and try again?

**Comment by mwho** [comment]
Great - I tried linking to 

<script src="https://cdn.plot.ly/plotly-1.13.0.min.js"></script>

which works.

As a side note, it looks like plotly-latest is still tied to 1.12.

**Comment by etpinard** [comment]
> As a side note, it looks like plotly-latest is still tied to 1.12.

Yeah. That might take a few minutes before the `latest` URL updates.

Closing.
