### ISSUE TITLE
Barmode 'relative' does not place leading bar in correct quadrant

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#639]
First reported by @programflex in https://github.com/plotly/plotly.js/issues/475#issuecomment-225803112

Reproducible example: http://codepen.io/etpinard/pen/bepzRm

May be related to https://github.com/plotly/plotly.js/issues/627

cc @keeganmccallum

**Comment by keeganmccallum** [comment]
Looking into, issue seems to be that -0 === 0, will make a pull request shortly

**Comment by etpinard** [comment]
@keeganmccallum You're the man!

**Comment by tonysunFlexsystem** [comment]
@etpinard I am facing the same problem too and I am kind of in a urgent need of using that.

Would you mind to make a pull request?

Thanks a lot

**Comment by keeganmccallum** [comment]
https://github.com/plotly/plotly.js/pull/687

**Comment by etpinard** [comment]
will be fixed in [`fix-bar-relative-first-bucket`](https://github.com/plotly/plotly.js/compare/fix-bar-relative-first-bucket).
