### ISSUE TITLE
Test dashboard fuzzy-search broken

### ISSUE THREAD

**Issue by mdtusz** [plotly/plotly.js#640]
It seems that _something_ has gone awry in the mocks fuzzy-search in the test-dashboard. Likely a quick fix (hello community!) but will make life simple again when trying to find mocks for a given trace type.

_Pro-tip for the readers: Use `Tabs.getMock('MOCK_NAME')` to bind the mock data and layout to the global `mock` object!_

**Comment by etpinard** [comment]
Yeah. I noticed that too. Not sure what's up.
