### ISSUE TITLE
Duplicated incorrect lines in html and svg output

### ISSUE THREAD

**Issue by vp-walter** [plotly/plotly.js#6404]
We noticed a big problem with svg rendering that happens on rare occasions.

Sometimes when writing a chart with many nan values to html, it will create phantom lines. They will be lines that exist in the chart but duplicated and placed in the wrong place. This doesn't happen if you .show() the chart in a jupyter notebook, only when you write to html (and I guess by extension also effects static chart export). 

I have attached two charts. One shows the phantom lines in the middle of the chart (the line being a duplicate of a line that is just to the left of it). The other shows the correct chart.

<img width="516" alt="image" src="https://user-images.githubusercontent.com/108830704/208004006-21586b5d-47d0-46a7-9f4f-5ea3ea7a28c9.png">

The correct one. The only difference between this chart and the one above is that this one uses Scattergl instead of Scatter, so likely a problem with how svg rendering works.

![AB Industrivärden (publ) Per Share Fundamentals](https://user-images.githubusercontent.com/108830704/208004138-2f156d02-6bd2-42ce-997f-920996cf10aa.png)

This is kind of a terrifying error because you never know when it might strike!

I am unable to give a min. reproducible example, except to say its a Scatter(mode='lines') with many np.nan values that seem to split the line into many svg line segments (which it somehow gets wrong). we 'fixed' it by using Scattergl (in case anyone else on here runs across it in the future).

**Comment by dbuezas** [comment]
This looks related to https://github.com/plotly/plotly.js/issues/6407 
I left a minimalistic way of reproducing it there.

**Comment by alexcjohnson** [comment]
@vp-walter does this problem go away if you downgrade to v2.14.0? If so it's probably indeed the same problem as #6407.

**Comment by alexcjohnson** [comment]
I'm going to assume https://github.com/plotly/plotly.js/pull/6429 fixes this one as well, if you're still seeing this problem with plotly.js v2.18 please reopen or make a new issue.
