### ISSUE TITLE
BUG: Ghost traces after zooming/panning when data has gaps (null)

### ISSUE THREAD

**Issue by dbuezas** [plotly/plotly.js#6407]
After zooming, a second trace appears and stays in the same spot independent of further panning. 

![plotly bug](https://user-images.githubusercontent.com/777196/208301643-8e0d8a57-362f-4561-9ea1-d9741503acda.gif)

Here's a minimal way of reproducing it:
```javascript
Plotly.newPlot('myDiv', [{
  x: [1, 2, 3, 4],
  y: [1,null,3,4],
}]);
```

https://codepen.io/davsbb/pen/WNKeVba

**Comment by alexcjohnson** [comment]
Thanks for the simplified example @dbuezas !

Seems this problem appeared between v2.14.0 and v2.15.0 - @archmoj the only thing I see in there that touched line drawing  is the `angleref` work https://github.com/plotly/plotly.js/pull/6297. Let's put this in line for immediately after the 2.17 feature work is complete.

Meantime, if you're hitting this problem please downgrade to v2.14.0
