### ISSUE TITLE
This contour trace has intersecting contour lines

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#641]
See http://codepen.io/etpinard/pen/wWGOJw

First reported on http://community.plot.ly/t/possible-bug-intersecting-contours/633

**Comment by etpinard** [comment]
cc @alexcjohnson

**Comment by alexcjohnson** [comment]
Oh interesting - thanks for pointing me to this. It's NOT the known issue with neighboring contour lines crossing when they have different topologies... looks like contours break with data to zero on a log axis. It works fine if I change the zeros to 0.1 for example.
