### ISSUE TITLE
Pie Chart show wrong with big value

### ISSUE THREAD

**Issue by Duc-Developer** [plotly/plotly.js#6419]
Hi Team,
I have an issue with Pie Chart. When my first value has a very large value compared to the rest, the chart will lose part or all of the image. 
![image](https://user-images.githubusercontent.com/66018863/209622474-34f38747-d38c-4c43-9056-abb452b09baf.png)

**jsfiddle**: https://jsfiddle.net/5u4zyoLd/
Here is my configuration.

var **data** =[
  {
    "type": "pie",
    "values": [
      "34000000000.00",
      "20.4716",
      "245.50"
    ],
    "labels": [
      "static 34,000,000,000: 34,000,000,000 ",
      "Data 1: 20.4716 ",
      "Data 2: 245.50 "
    ],
    "marker": {
      "colors": [
        "#f8fc94",
        "#769558",
        "#b0cb34"
      ]
    },
    "textinfo": "percent",
    "textfont": {
      "family": "Noto Sans",
      "size": 13
    },
    "text": [
      "<br>static 34,000,000,000: 34,000,000,000",
      "2022-12-27 (11:15:00.000)<br>Data 1: 20.4716 (t)",
      "2022-12-27 (11:15:00.000)<br>Data 2: 245.50 (°)"
    ],
    "hovertemplate": "%{text}<br>%{percent:.1%}<extra></extra>",
    "sort": false,
    "hoverlabel": {
      "align": "right",
      "font": {
        "family": "Noto Sans",
        "size": 13
      }
    },
    "outsidetextfont": {
      "color": "#d1d9e0"
    },
    "texttemplate": "%{percent:.1%}"
  }
];

var **layout** = {
  "title": "",
  "margin": {
    "t": 0,
    "b": 20,
    "l": 40
  },
  "legend": {
    "traceorder": "normal",
    "borderwidth": 0,
    "font": {
      "color": "#d1d9e0",
      "family": "Noto Sans",
      "size": 13
    }
  },
  "showlegend": true,
  "hovermode": "false",
  "width": 1000,
  "height": 400
};

**Comment by alexcjohnson** [comment]
Thanks @Duc-Developer - I see it too, looks like this gets below the precision of the SVG rendering engine, I can trace this down to the `path` attribute, and two paths that should give nearly the same result put the nearly-full circle in totally different places.

@archmoj maybe we can address this by breaking the arc into two pieces when it's >180 degrees? By the same token I wouldn't be surprised if there's a situation where a very small arc would decide to go the other way around and turn into almost the whole circle (or vice versa but breaking a large arc into two would fix that)... so if the arc is less than say a tenth of a degree maybe we should just turn it into a line?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
