### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined

### ISSUE THREAD

**Issue by klar-C** [plotly/plotly.js#6422]
Hi,

I'm running the below code in a Typescript/React project and am getting the error at the very bottom. I'm intentionally not using the plotly-react package because I want access to plotly.js directly. This code was working fine when not using Typescript. Has anyone come across this error? There are some discussions (e.g. https://stackoverflow.com/questions/39084438/how-to-import-plotly-js-into-typescript) but neither of the mentioned potential worked for me.

import React from 'react';
import './App.css';
// import Plotly from 'plotly.js/dist/plotly'; -> Does not work anymore in Typescript.
import Plotly from 'plotly.js';
function App() {
    const data: any = [
        {
            x: ['giraffes', 'orangutans', 'monkeys'],
            y: [20, 14, 23],
            type: 'bar'
        }
    ];
    Plotly.newPlot('test', data);
    return (
        <div id={"test"}/>
    );
}
export default App;

Here is the package.json file:

`{
  "name": "frontend_ts",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@emotion/react": "^11.10.5",
    "@emotion/styled": "^11.10.5",
    "@mui/icons-material": "^5.11.0",
    "@mui/material": "^5.11.1",
    "@react-hook/window-size": "^3.1.1",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.5.2",
    "@types/lodash": "^4.14.191",
    "@types/node": "^16.18.10",
    "@types/pako": "^2.0.0",
    "@types/plotly.js": "^2.12.11",
    "@types/react": "^18.0.26",
    "@types/react-dom": "^18.0.10",
    "@types/react-plotly.js": "^2.5.2",
    "@types/react-router-dom": "^5.3.3",
    "@types/react-splitter-layout": "^3.0.2",
    "@types/uuid": "^9.0.0",
    "assert": "^2.0.0",
    "axios": "^1.2.1",
    "buffer": "^6.0.3",
    "flexlayout-react": "^0.7.5",
    "lodash": "^4.17.21",
    "notistack": "^2.0.8",
    "numbro": "^2.3.6",
    "pako": "^2.1.0",
    "plotly.js": "^2.17.0",
    "probe-image-size": "^7.2.3",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-new-window": "^1.0.1",
    "react-plotly.js": "^2.6.0",
    "react-router-dom": "^6.6.1",
    "react-scripts": "5.0.1",
    "react-sparklines": "^1.7.0",
    "react-splitter-layout": "^4.0.0",
    "stream": "^0.0.2",
    "typescript": "^4.9.4",
    "uuid": "^9.0.0",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}`

![image](https://user-images.githubusercontent.com/51972811/210344909-521aebbc-92e3-4218-ab96-354dc3261cce.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
