### ISSUE TITLE
JavaScript Exception - Uncaught (in promise) Error after upgrading dash to 2.7.1 

### ISSUE THREAD

**Issue by kevalshah90** [plotly/plotly.js#6444]
My application renders a map and passes the `lat`, `long` values from a pandas dataframe for plotly's `scattermapbox` graph object.  

```
import dash
from dash import dcc
import pandas as pd
import mapbox
import plotly
import geojson
import ast
import dash
from dash.dependencies import Input, Output, State, ClientsideFunction
from dash import dcc
from dash import html, dash_table
import dash_bootstrap_components as dbc
import dash_daq as daq
import plotly as py
from plotly import graph_objs as go
from plotly.graph_objs import *

df = pd.DataFrame({
                   'x': [1, 2, 3],
                   'Lat': [37.774322, 37.777035, 37.773033],
                   'Long': [-122.489761, -122.485555, -122.491220]
                 }) 

layout = html.Div(
                   dcc.Graph(id="map"),
                   dcc.Input(id="inp")
                 )

@app.callback(
              Output('map','figure'),
              Input('inp','value')
             )
def fin(val):
    
    # do something

    data = []
    
    data.append({

                                 "type": "scattermapbox",
                                 "lat": df["Lat"],
                                 "lon": df["Long"],
                                 "name": "Location",
                                 "showlegend": False,
                                 "hoverinfo": "text",
                                 "mode": "markers",
                                 "clickmode": "event+select",
                                 "customdata": df.loc[:,cd_cols].values,
                                 "marker": {
                                            "symbol": "circle",
                                            "size": 8,
                                            "opacity": 0.7,
                                            "color": "black"
                                           }
                                 }
                   )

      layout = {

                     "autosize": True,
                     "hovermode": "closest",
                     "mapbox": {

                         "accesstoken": MAPBOX_KEY,
                         "bearing": 0,
                         "center": {
                             "lat": xxx,
                             "lon": xxx
                         },
                         "pitch": 0,
                         "zoom": zoom,
                         "style": "satellite-streets",

                     },

                    
        }

        return ({'data': data, 'layout': layout}) 
```

I upgraded the `dash` and `plotly` libraries to the latest version `2.7.1` and `5.13.0`. I am not able to render the points on the map. I do not see any errors in the application logs. The only exceptions I see are JS in console. 

```
Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received


Uncaught (in promise) Error: There is already a source with this ID

at r.addSource (async-plotlyjs.js:2:1020888)
    at i.addSource (async-plotlyjs.js:2:1219363)
    at l.addSource (async-plotlyjs.js:2:2988732)
    at async-plotlyjs.js:2:2989736
    at h (async-plotlyjs.js:2:2989770)
    at l.update (async-plotlyjs.js:2:2990100)
    at b.updateData (async-plotlyjs.js:2:2338377)
    at async-plotlyjs.js:2:2336961
```

**Comment by alexcjohnson** [comment]
Thanks @kevalshah90 - are you able to reduce this to a standalone app? I try to do that and it works with no error, but I had to comment out some of your missing variables

```py
from dash import Dash, dcc, html, Input, Output
import pandas as pd

MAPBOX_KEY = "<YOUR KEY>"

df = pd.DataFrame({
    'x': [1, 2, 3],
    'Lat': [37.774322, 37.777035, 37.773033],
    'Long': [-122.489761, -122.485555, -122.491220]
})

app = Dash(__name__)

app.layout = html.Div([dcc.Graph(id="map"), dcc.Input(id="inp")])

@app.callback(Output('map','figure'), Input('inp','value'))
def fin(val):
    data = [{
        "type": "scattermapbox",
        "lat": df["Lat"],
        "lon": df["Long"],
        "name": "Location",
        "showlegend": False,
        "hoverinfo": "text",
        "mode": "markers",
        "clickmode": "event+select",
        #  "customdata": df.loc[:,cd_cols].values,
        "marker": {
            "symbol": "circle",
            "size": 8,
            "opacity": 0.7,
            "color": "black"
        }
    }]

    layout = {
        "autosize": True,
        "hovermode": "closest",
        "mapbox": {
            "accesstoken": MAPBOX_KEY,
            "bearing": 0,
            #  "center": {
            #      "lat": xxx,
            #      "lon": xxx
            #  },
            #  "pitch": 0,
            #  "zoom": zoom,
            "style": "satellite-streets",
        }
    }

    return ({'data': data, 'layout': layout})

if __name__ == '__main__':
    app.run(debug=True)
```

**Comment by alexcjohnson** [comment]
The observation in https://github.com/plotly/dash/issues/2406 that this happens between Dash v2.6.1 and v2.7.1 narrows this down a bit - you could try adding a specific plotly.js version to your app, either by putting it in the `assets/` folder or with a CDN link in `external_scripts`. That Dash range upgraded plotly.js from 2.13.3 to 2.16.4, so perhaps we can figure out which precise plotly.js release broke this for you.

Of course that's still not the same as reproducing it, what we really need is a standalone app that triggers the bug. Perhaps you can augment my app above with more details from your app until the bug appears?

**Comment by kevalshah90** [comment]
@alexcjohnson which specific version of `plotly.js`? The current version that is bugfree is dash `2.6.2` and plotly `5.13.0`.

**Comment by alexcjohnson** [comment]
Right so I bet if you use the latest versions of dash and plotly.py but load plotly.js `2.13.3` it will work correctly. Then you can step forward from there to plotly.js `2.16.4` that won't work... the question is which intermediate version caused the bug? the full set of possibilities is `2.14.0`, `2.15.0`, `2.15.1`, `2.16.0`, `2.16.1`, `2.16.2`, `2.16.3`, `2.16.4`... most likely it's one of the minors, not one of the patches.

My guess is it'll be `2.16.0`, specifically https://github.com/plotly/plotly.js/pull/5827. That already caused one other bug that we've fixed: https://github.com/plotly/plotly.js/issues/6382 - but that apparently didn't fix your issue.

**Comment by alexcjohnson** [comment]
ooh the app @coding-with-adam posted in https://github.com/plotly/plotly.py/issues/3631#issuecomment-1408694360 shows the same JS error, and it's pretty simple. @archmoj is that enough to go off?

**Comment by kevalshah90** [comment]
ok, so the resolution for the time being is to go with `dash==2.6.2` and `plotly.js==2.13.3`? To confirm, I'll add it in `app.py` where I instantiate the `app` as external script and also update `requirements.txt` as `2.13.3`?

**Comment by ciskoh** [comment]
Hi all, 
I am having a problem with scatter_mapbox not updating upon callback and I do see the following error:

Uncaught (in promise) Error: Mapbox error.
    at i.r (plotly.v2_7_0m1667509735.min.js:37:1056684)
    at Et.fire (plotly.v2_7_0m1667509735.min.js:20:333027)
    at Et.fire (plotly.v2_7_0m1667509735.min.js:20:333170)
    at Et.fire (plotly.v2_7_0m1667509735.min.js:20:333170)
    at Et.fire (plotly.v2_7_0m1667509735.min.js:20:333170)
    at r._tileLoaded (plotly.v2_7_0m1667509735.min.js:20:768423)
    at plotly.v2_7_0m1667509735.min.js:20:725812
    at plotly.v2_7_0m1667509735.min.js:20:330966
    at plotly.v2_7_0m1667509735.min.js:20:328968


My stack: 
dash: 2.7.0
dash-core-components: 2.0.0
dash-html-components: 2.0.0

More details on my problem is here: https://community.plotly.com/t/mapbox-custom-raster-tiles-not-updating/71962

**Comment by ciskoh** [comment]
> ok, so the resolution for the time being is to go with `dash==2.6.2` and `plotly.js==2.13.3`? To confirm, I'll add it in `app.py` where I instantiate the `app` as external script and also update `requirements.txt` with version `2.13.3`?

How do you specify the plotly.js version in python? Having a similar problem with tiles and polygons not updating

**Comment by ciskoh** [comment]
Reporting afetr trying with dash version 2.6.2

I have tried running the dashboard with dash 2.6.2 and my problem (scattermapbox not displaying new raster tiles following callback) seems reduced but not disappeared. WIth version 2.7.0 the problem (tiles not refreshing) and the `Uncaught (in promise) Error: Mapbox error.` would appear at the second request. Now it takes between 5-10 subsequent request but the error comes back and my map is stuck again

**Comment by archmoj** [comment]
To replicate this issue on `plotly.js`
@kevalshah90 would you please fork [this codepen](https://codepen.io/MojtabaSamimi/pen/bGjOMvG?editors=0010) and make changes to data and layout (something similar to what is changing in your app) so that using `react step 0` then `react step 1` triggers the issue?

**Comment by kevalshah90** [comment]
@archmoj It is not clear what changes you'd like me to make. 

Do you want to me to wrap my callback return statement in `js` within the `.py` file? 

For reference, this what my return statement looks like: 

`return ({"data": datad, "layout": layout}, df.to_dict("records") })`

**Comment by archmoj** [comment]
@kevalshah90 Could you provide the minimal data and layout changes in the codepen that could trigger the bug when reacting between state 1 and state 2?
Without that I can't replicate the bug.
