### ISSUE TITLE
es-pe locale has incorrect number format specification

### ISSUE THREAD

**Issue by andresrcs** [plotly/plotly.js#6450]
The "es-pe" locale has incorrect number format specification, it should use these values:
```
decimal: "."
thousands: ","
grouping: [3]
currency: ["S/", ""]
```
But it uses the Spanish (es) number format with a dollar symbol ($) for currency.

If I use this tickformat in Plotly R
```
yaxis = list(title = 'Monto (S/)',
             zerolinecolor = '#ffff',
             zerolinewidth = 2,
             gridcolor = 'ffff',
             tickformat = '$,.0f',
             hoverformat = '$,.0f'),
```
I get this which is incorrect

![image](https://user-images.githubusercontent.com/14981085/215334988-3142bb93-0259-4836-b2ac-ac2aa9d1d967.png)

**Comment by alexcjohnson** [comment]
Thanks @andresrcs - would you be able to make a PR to update https://github.com/plotly/plotly.js/blob/master/lib/locales/es-pe.js with the correct entries, and ask one other Peruvian to review and approve?

**Comment by andresrcs** [comment]
Thanks, I have made the PR #6451 
I'll look into getting another Peruvian to review
