### ISSUE TITLE
Unable to create tandem hover events with violin and heatmap

### ISSUE THREAD

**Issue by connoranderson-synthego** [plotly/plotly.js#6456]
I am trying to make a plot with a violin plot and heatmap on it to visualize some data. I am trying to make it so that when I hover over one point on one of the graphs, the corresponding point on the other is highlighted/indicated in some way. You can see the work I am trying to do in this example https://codepen.io/wonderwally/pen/zYLjqVW 1. I am using Plotly.js v1.58.5 (by adding https://cdn.plot.ly/plotly-latest.min.js as a source to my script).

The gist of my code is that I generate the 2D array for the heatmap and also include the `pointNumber` of the corresponding violin’s 1D array under the heatmap’s `customdata` property.

The violin plot receives a similar treatment. The violin plot is made with a 1D array and includes the `pointNumber` of the corresponding heatmap’s 2D array under the violin plot’s `customdata` property.

As an example, if the heatmap 2D array is
```
[
   [0.43, 0.50, 0.58], 
   [0.73, 0.18, 0.14]
]
```
and the violin plot’s 1D array is
```
[0.43, 0.50, 0.58, 0.73, 0.18, 0.14]
```
the heatmap will have a customdata feature of
```
[
    [0, 1, 2], 
    [3, 4, 5]
]
```
and the violin plot will have a customdata feature of
```
[[0, 0], [0, 1], [0, 2], [1, 0], [1, 1], [1,2]]
```
This is the section of code I am using to try and achieve the tandem hover event:
```
PLOTLY_GRAPHS.on('plotly_hover', function(eventdata) {
    let violin_pointNumber, heatmap_pointNumber, violin_curveNumber, heatmap_curveNumber;
    if (eventdata.points[0].data.type === 'heatmap') {
        heatmap_pointNumber = eventdata.points[0].pointNumber;
        violin_pointNumber = eventdata.points[0].customdata;
        heatmap_curveNumber = eventdata.points[0].curveNumber;
        violin_curveNumber = (heatmap_curveNumber === 1) ? 0 : 1;
    } else {
        violin_pointNumber = eventdata.points[0].pointNumber;
        heatmap_pointNumber = eventdata.points[0].customdata;
        violin_curveNumber = eventdata.points[0].curveNumber;
        heatmap_curveNumber = (violin_curveNumber === 1) ? 0 : 1;
    }
    
    Plotly.Fx.hover(
        PLOTLY_GRAPHS,
        [
            {curveNumber: violin_curveNumber, pointNumber: violin_pointNumber},
            {curveNumber: heatmap_curveNumber, pointNumber: heatmap_pointNumber},
        ],
        [
            'xy',
            'x2y2',
        ]
    );
});
```
As you can see in the example https://codepen.io/wonderwally/pen/zYLjqVW 1, if you hover over a point in the violin plot, the corresponding heatmap point is indicated, but there isn’t any hovertext over that same, hovered-over violin plot point. However, when you hover over the heatmap, the corresponding violin plot point isn’t shown.

**Comment by connoranderson-synthego** [comment]
https://user-images.githubusercontent.com/72104682/215905631-85bc3a38-ecc9-4cf8-95de-a8b2f40b0fae.mov

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
