### ISSUE TITLE
Should not set Promise to global

### ISSUE THREAD

**Issue by ryanlin1986** [plotly/plotly.js#646]
I'm having a promise library instead of built-in es6-promise lib, Is there any way to not include es6-promise in plotly?

**Comment by etpinard** [comment]
I'm not sure I understand your situation.

You are currently using another Promise library and you want to use that library in plotly.js?

Or is our `es6-promise` polyfill messing up the rest of your app?

**Comment by ryanlin1986** [comment]
My scenario:
I have a customized es6 promise polyfill library, I want to use this library instead of es6-shim library built into plotly.
Since plotly is bundled with es6-shim, loading plotly would replace my custom es6 promise libray by set window.Promise.
Why does it matter?
check out following simplified code:
var promise=new Promise(function(){});
require('plotly',function(){
if( promise isntanceof Promise)//which returns false I never expected.
{
}
});

I fixed it by:
var promise=Promise;
require(['plotly'],function(){
window.Promise=promise;
});

Since I'm having a workaround, I'm OK with it now, what I'm complainning is I did not realized plotly bundled with es6-shim, which having myself several hours to fix problem.

**Comment by etpinard** [comment]
@ryanlin1986 No problem. Thanks for bringing this up. I'll admit it, the fact that plotly.js impacts the global scope by polyfilling `Promise` isn't great. We should reconsider this approach for `v2.0.0`.

I'm thinking about removing that `es6-promise` poylfill entirely from plotly.js and have users that care about IE support add their own polyfill.

**Comment by ryanlin1986** [comment]
Really great to hear, as angular 2 also has this approach.
