### ISSUE TITLE
The custom-bundle command generates empty file since v2.17.0

### ISSUE THREAD

**Issue by ssashir06** [plotly/plotly.js#6465]
Hello. Recently I'm trying to use the `custom-bundle` command by referencing the `CUSTOM_BUNDLE.md` document.
However, somehow I am getting incorrect output because a generated file of the `dist` directory has only the first 6 lines which describes a license.

plotly-myScatters.js:
```js
/**
* plotly.js (myScatters) v2.17.0
* Copyright 2012-2023, Plotly, Inc.
* All rights reserved.
* Licensed under the MIT license
*/

```

And also, I noticed that this issue is happening since v2.17.0, and it seems like it's ok if I select the version v2.16.5.
I appreciate if I could get some information as a workaround for it.

Environment I am testing:
- in a docker container
    - debian:bullseye
- installation of libraries or etc:
    - `apt install libpango1.0-dev node-gyp npm pkg-config libpixman-1-dev libcairo2-dev`
    - `npm i -g run-series prepend-file`
- command I tried: 
    - `npm i && npm run custom-bundle -- --unminified --out myScatters --traces scatter,scattergl,scatter3d --transforms none`

Thank you.

**Comment by archmoj** [comment]
`npm run custom-bundle -- --unminified --out myScatters --traces scatter,scattergl,scatter3d --transforms none` works for me.

Which version of `node` and `npm` you are on?

**Comment by ssashir06** [comment]
@archmoj Thank you for your advice!
After I install the LTS version by `nvm install --lts`, now everything works well.
I was forgetting to check the versions inside my working container.

The versions I was using:
- node: v12.22.12
- npm: 7.5.2

The versions I tried by this advice:
- node: v18.14.0
- npm: 9.3.1
