### ISSUE TITLE
uirevision doesn't works on dist version

### ISSUE THREAD

**Issue by MeterKishor** [plotly/plotly.js#6473]
I'm trying to build Plotly chart where it shouldn't reset chart when dynamically adding data. I'm using buddy.works as deploy engine and i have limited ram so had to use " plotly.js-basic-dist-min" this is what I'm trying to achieve https://codepen.io/plotly/pen/ebMJEW .

but I'm facing problem while using dist-min version. as uirevision works fine on
`import Plot from 'react-plotly.js';`

but it doesn't work for

```js
import createPlotlyComponent from "react-plotly.js/factory";
var Plotly = require('plotly.js-basic-dist-min')
```

do i need to pass any other options? or is there any mistakes in my code?

here's full code

```js
        import React, { useEffect, useState } from 'react';
        import './App.css';
        import createPlotlyComponent from "react-plotly.js/factory";
        var Plotly = require('plotly.js-basic-dist-min')


        function App() {
          const Plot = createPlotlyComponent(Plotly);
          const [data, setData] = useState<any>({
            x:[],
            y:[],
            type:'scatter'
          })
          useEffect(()=>{
            let x:any=[]
            let y:any=[]
            let i=1;
            let inval = setInterval(()=>{
              x= [...x, i]
              y= [...y, Math.floor(Math.random() * 10) + 1]
              setData({
                x:x,
                y:y,
                type:'scatter'
              })
              i++
            }, 5000)
            return ()=>{
              clearInterval(inval);
            }

          },[])
          return (
            <div className="App">
              <Plot
                  data={[data]}
                  config={{ scrollZoom: false, responsive: true, displaylogo: false}}
                  useResizeHandler={true}
                  style={{ width: "100%", height: "100%" }} 
                  
                  layout={{
                    title: 'User Zoom Persists<br>When uirevision Unchanged',
                    uirevision:'true',
                    xaxis: {autorange: true},
                    yaxis: {autorange: true}
                  }}
                  
                />
            </div>
          );
        }

        export default App;
```

**Comment by archmoj** [comment]
@MeterKishor please note that the `latest` bundles are only available for version 1.
To load the latest v2 plotly.js e.g. in your codepen, please try https://cdn.plot.ly/plotly-basic-2.18.1.min.js

**Comment by MeterKishor** [comment]
@archmoj thanks!, I tried "plotly.js-dist-min": "^2.18.1", too but same result. uirevision  still doesn't works.

**Comment by archmoj** [comment]
@alexcjohnson Could it be related to a bug in [`react-plotly.js`](https://www.npmjs.com/package/react-plotly.js)?

**Comment by alexcjohnson** [comment]
Hmm, the only thing that jumps out to me is that `const Plot = createPlotlyComponent(Plotly);` is inside the `App` component - perhaps doing it that way means React doesn't know that it's the same component each time so it recreates the DOM element rather than reusing it? So does it work if you move that statement to the outer scope?

**Comment by MeterKishor** [comment]
Good catch @alexcjohnson . That solved my problem. Thank you!

**Comment by nicolaskruchten** [comment]
Wow, eagle-eyes @alexcjohnson ... nice one! 🦅 👁️ 🎯
