### ISSUE TITLE
Plotly tries very hard to convert Strings to integers.

### ISSUE THREAD

**Issue by willhuang1997** [plotly/plotly.js#6475]
Hi I am a software engineer at Snowflake working on Streamlit! Someone was trying to render a plotly chart while using category_orders and it doesn't seem to work! issue where the python code can be found here: https://github.com/streamlit/streamlit/issues/6081
It doesn't seem like plotly.js is respecting the category_orders here for some reason but if I have "-" added into each string of category_orders , the category orders works.
Here is a code pen that demonstrates the bug: https://codepen.io/willhuang1997/pen/jOpooGg
Here is a code pen that demonstrates it working with the "-":  https://codepen.io/willhuang1997/pen/gOjJJEq

let me know if anyone needs anything from me. Happy to help out to the best of my ability.

**Comment by alexcjohnson** [comment]
Thanks @willhuang1997 - both of your codepens appear to have the "-" now, and when I remove it (I got lazy and only did the first 4 traces) it seems to work fine: https://codepen.io/alexcjohnson/pen/BaPegza?editors=0010

Happy to look into it if you can find us a complete (hopefully simplified 😉 ) reproduction!

**Comment by willhuang1997** [comment]
Ah... Sorry.
I'll look at this more closely tomorrow and give you a more simplified version that removes the streamlit theme 😅
