### ISSUE TITLE
Since 2.17.0, window.d3 is exported with internal 3.8.0 version preventing loading of external d3 library

### ISSUE THREAD

**Issue by lucasnetau** [plotly/plotly.js#6483]
Versions 2.17.0 to 2.18.1 (since change to webpack), window.d3 is defined to the Plotly packaged D3 3.8.0 version. This prevents loading a newer version of D3.

A newer version is needed since Plotly 2.0.0 to access d3.csv/json and also d3 colours (eg d3.schemeCategory10)

* Result with version 2.16.5 and prior https://jsfiddle.net/ga9rskdj/1/
* Failure with version 2.17.0 and later https://jsfiddle.net/f15jursm/

Workaround is to set window.d3 = undefined after loading Plotly.js and then including external D3

**Comment by archmoj** [comment]
Thanks for the report.

**Comment by archmoj** [comment]
Among all the keys on window, `d3` is the only module somehow exported!
This suggests we should fix the problem at [`@plotly/d3`](https://www.npmjs.com/package/@plotly/d3) level.
