### ISSUE TITLE
Does it support quick plotData switching such as pie to bar?

### ISSUE THREAD

**Issue by whbing** [plotly/plotly.js#6484]
I'm not familiar with `plotly.js`. In our product, the data is displayed in a fixed `pie chart`. I wonder if I can configure it to quickly switch to another type, such as a `bar chart`.

Thanks!

**Comment by alexcjohnson** [comment]
Yes, you can just provide a new figure, ideally via `Plotly.react`.
This kind of question is best asked on our community forum: https://community.plotly.com/
