### ISSUE TITLE
Can't make custom bundle with strict scattergl trace

### ISSUE THREAD

**Issue by CallumNZ** [plotly/plotly.js#6496]
I want to make a custom bundle that just includes the `scattergl` graph from the `strict `bundle. I tried the following:

```
npm i plotly.js
cd node_modules/plotly.js
npm i
npm run custom-bundle -- --traces scatter,scattergl-strict --transforms none
```

Error: `scattergl-strict is not a valid trace!`

I saw the name `scattergl-strict` [here](https://github.com/plotly/plotly.js/pull/6083), so thought it might work.
Not sure if it's the wrong command, a bug, or not a feature.
Thanks.

**Comment by alexcjohnson** [comment]
@archmoj is there a way to use the strict gl traces in custom bundles?

**Comment by archmoj** [comment]
I don't see such an option in https://github.com/plotly/plotly.js/blob/master/tasks/custom_bundle.js 
But that's something we could add.

**Comment by CallumNZ** [comment]
Thanks @archmoj, I will give it a go!

**Comment by CallumNZ** [comment]
Done
