### ISSUE TITLE
`barmode: relative` not working correctly when the x values are strings

### ISSUE THREAD

**Issue by yankev** [plotly/plotly.js#650]
When the x-values are strings (unwanted behaviour): https://jsfiddle.net/kevinyan/ajvr73Lr/0/
Correct behaviour: https://jsfiddle.net/kevinyan/ajvr73Lr/1/

**Comment by etpinard** [comment]
Ha. A quick trial and error showed that this is a similar but separate issue to https://github.com/plotly/plotly.js/issues/639

**Comment by etpinard** [comment]
After some investigation. This is a duplicate of #639.

Will be fixed in the next release.
