### ISSUE TITLE
 How to get all subgraph data for a specified coordinate

### ISSUE THREAD

**Issue by wanghe199512** [plotly/plotly.js#6500]
I built multiple subgraphs, using click or hover on one subgraph, and how to use this coordinate to get data from other subgraphs（Click or use hover on a subgraph to get all the data for the other subgraphs at that coordinates）

myplot. On (' plotly' , function (eventdata){
    // currently eventdata has only one subgraph data
 }

example ：https://codepen.io/wanghe199512/pen/XWPNbxJ

![image](https://user-images.githubusercontent.com/38382084/221411073-3bc8740c-a2d1-4b06-820f-e3d7ded4f038.png)

thanks

**Comment by gvwilson** [comment]
Hi - we are tidying up issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. For tech support and "how-to" questions, please post in our community forum https://community.plotly.com/. Thank you - @gvwilson
