### ISSUE TITLE
heatmap: colorbar.showticklabels cannot be set to false (nothing is rendered)

### ISSUE THREAD

**Issue by Nauss** [plotly/plotly.js#6507]
This [pen](https://codepen.io/Nauss/pen/bGxWYjK) is simply the [basic heatmap example](https://plotly.com/javascript/heatmaps/#basic-heatmap) with the `showticklabels` option set to false.
``` javascript
colorbar: {
  showticklabels: false
}
```
If I comment the option or set it to true it works correctly.

Looks like a bug or am I missing something ?

**Comment by alexcjohnson** [comment]
Thanks @Nauss - very clearly a bug, it's throwing a JS error.

**Comment by subhajit20** [comment]
@alexcjohnson  will that showticklabels attribute set to true value ?

**Comment by Nauss** [comment]
Nice, great (and fast) job, thanks !
