### ISSUE TITLE
I can't zoom where shapes cover the plot area

### ISSUE THREAD

**Issue by carmelocassisi** [plotly/plotly.js#6510]
### I describe the problem with a dummy example.

**Let `thresholds `an array like:**
```
[
  {
    "to_t": 10,
    "color": "#62f48e",
    "label": "A0",
    "from_t": null,
    "status": 0
  },
  {
    "to_t": 20,
    "color": "#c8d94a",
    "label": "A1",
    "from_t": 10,
    "status": 1
  },
  {
    "to_t": 30,
    "color": "#ee722f",
    "label": "A2",
    "from_t": 20,
    "status": 2
  },
  {
    "to_t": null,
    "color": "#ff0000",
    "label": "A3",
    "from_t": 30,
    "status": 3
  }
]
```
indicating several thresholds areas.

**Let `range `be a structure like:**
```
{
    "x": [
        "2022-10-25T11:15:00.000+00:00",
        "2022-11-01T11:15:00.000+00:00"
    ],
    "y": [
        0,
        99.87
    ]
}
```
indicating the min/max values for x and y axes.

**Let be `chart `the var containng my plotly chart:**
```
if (thresholds && Array.isArray(thresholds)) {
                for (let i = 0; i < thresholds.length; i++) {
                    if (thresholds[i].from_t) {
                        chart.layout.shapes.push({
                            type: 'line',
                            x0: range.x[0],
                            y0: thresholds[i].from_t,
                            x1: range.x[1],
                            y1: thresholds[i].from_t,
                            line: {
                                width: 0,
                            },
                            layer: 'below',
                            editable: false
                        });
                    }
                    if (thresholds[i].from_t && thresholds[i].to_t) {
                        chart.layout.shapes.push({
                            type: 'rect',
                            x0: range.x[0],
                            y0: thresholds[i].from_t,
                            x1: range.x[1],
                            y1: thresholds[i].to_t,
                            fillcolor: thresholds[i].color,
                            opacity: 0.2,
                            line: {
                                width: 0
                            },
                            layer: 'below',
                            editable: false
                        });
                    }
                    if (!thresholds[i].from_t && thresholds[i].to_t) {
                        chart.layout.shapes.push({
                            type: 'rect',
                            x0: range.x[0],
                            y0: range.y[0],
                            x1: range.x[1],
                            y1: thresholds[i].to_t,
                            fillcolor: thresholds[i].color,
                            opacity: 0.2,
                            line: {
                                width: 0
                            },
                            layer: 'below',
                            editable: false
                        });
                    }
                    if (thresholds[i].from_t && !thresholds[i].to_t) {
                        chart.layout.shapes.push({
                            type: 'rect',
                            x0: range.x[0],
                            y0: thresholds[i].from_t,
                            x1: range.x[1],
                            y1: range.y[1],
                            fillcolor: thresholds[i].color,
                            opacity: 0.2,
                            line: {
                                width: 0
                            },
                            layer: 'below',
                            editable: false
                        });
                    }
                }
            }
```
After obtaining the following plot:
<img width="532" alt="Cattura" src="https://user-images.githubusercontent.com/43577958/222798680-9acfd634-772c-4146-a1c5-304a2feff744.PNG">
I can't zoom on time series because the cursor only lets me to drag shapes
<img width="569" alt="Immagine" src="https://user-images.githubusercontent.com/43577958/222799529-df1f6c33-106b-4c15-be3b-75ee71883cbd.png">
... and then it lets me to zoom only into the "blank" part of the plot area.
I see this behavior **not** only on the latest version.
It is a bug or I miss something  on shapes/plot configuration?
If yes, should you give me a working example?
Thanks in advance

**Comment by carmelocassisi** [comment]
In addition to this (https://github.com/plotly/plotly.js/issues/6510#issue-1609090253), when using shapes, setting chart.layout['yaxis'].type = 'log' stalls the plot.

**Comment by alexcjohnson** [comment]
Thanks @carmelocassisi - can you create a codepen that shows the problems you're encountering? I'm not able to reproduce, if I put our original shapes test image into a codepen I can zoom & pan on top of the shapes, and they appear to work correctly on log axes. https://codepen.io/alexcjohnson/pen/QWVqNZj?editors=1000 (note the subplot with the pink rectangle and the smily face has linear and log axes, and the subplot to its right has category and date axes) (also: you can fork my codepen and just change the figure to your own)

I see your shapes have `editable: false` - have you enabled other editable features?

**Comment by carmelocassisi** [comment]
Yes, I enabled the `editable: true` in **config** parameters of `Plotly.newPlot(graphDiv, data, layout, config)`.
This configuration made _shapes_ editable. 
With `editable: false` this behavior does not happen.
I reproduced the example here: [https://codepen.io/Cassisi/pen/XWPzzPE?editors=1010](https://codepen.io/Cassisi/pen/XWPzzPE?editors=1010).
About stalling with `log `type chart, I'm investigating on my project code, because I didn't find any problem in the above reported [example](https://codepen.io/Cassisi/pen/XWPzzPE?editors=1010).
I'm sorry, if I will find the cause I will update this comment. For now, I temporarily close this issue.

**Comment by alexcjohnson** [comment]
OK great - let us know if you find how to reproduce the log axis problem.

BTW you may find `xref='paper'` useful for these stripes, so they align with the y axis but keep full x axis coverage even as you pan or zoom: https://codepen.io/alexcjohnson/pen/bGxYMBR?editors=1010
