### ISSUE TITLE
on click on an empty graph is not returning X-axis value

### ISSUE THREAD

**Issue by chaitu2chowdary** [plotly/plotly.js#653]
Is it possible to return  x or y value on click on an empty graph? 
please help me

**Comment by mdtusz** [comment]
Could you elaborate on what behaviour you are looking for?

Do you mean on a click on any location on a graph that has no traces plotted?

**Comment by etpinard** [comment]
@chaitu2chowdary no need to open an issue and forum post. 

Closing in favour of: http://community.plot.ly/t/on-click-get-x-axis-value-on-an-empty-graph/1314

**Comment by chaitu2chowdary** [comment]
graph may have traces,but mouse on click where traces are not there should return exact coordinates.
Please help!!
