### ISSUE TITLE
Box Selection behaves weirdly with overlay = "y". 

### ISSUE THREAD

**Issue by aymondebroglie** [plotly/plotly.js#6530]
I have a scatter plot graph with two series, two y axis and an overlay = 'y'. 

The box selections seems not to behave correctly, when I do a first selection it selects correctly the points but if I extend the selection, the points are not  selected anymore. (see gif attachedl .

**You can find a reproducing example here : https://stackblitz.com/edit/web-platform-7oxvtx?file=index.html** 

![plotly](https://user-images.githubusercontent.com/10114614/225881804-1adb12a6-6401-4bdf-8e8c-e043e196c6eb.gif)

**Comment by Coding-with-Adam** [comment]
@aymondebroglie emailed to let me know that they are currently running version 2.11.1.

**Comment by archmoj** [comment]
Thanks for the report.
We are investigating a fix for this bug.

**Comment by aymondebroglie** [comment]
@archmoj  any update on this bug ?
