### ISSUE TITLE
mesh coloring: intensity doesn't clear

### ISSUE THREAD

**Issue by VeraZab** [plotly/plotly.js#654]
intensity persists even if set to null and not present in _fullData.
http://codepen.io/veraz/pen/LZZJjv

**Comment by mdtusz** [comment]
You just need to wrap the `[null]` in another set of square brackets to clear the values.

If my suspicion is correct, the `null` is ignored as if there is no restyle for that trace index - this allows for multiple traces to be updated at once, while still leaving some untouched. E.g.

```
Plotly.restyle('chart', {intensity: [null, [0, 1, 2, 3], [null]]} , 0 );
```

**Comment by VeraZab** [comment]
You're right, it works with `[[null]]`
But many of the other restyle properties are clearable with just null, should we be using `[[null]] ` everywhere?

**Comment by etpinard** [comment]
@VeraZab that's because `intensity` is itself an array attribute.

Very confusingly, the outer arrays in `restyle` correspond to the traces to update, while the inner arrays correspond to the update values.

In more details: see https://github.com/plotly/plotly.js/issues/167#issuecomment-169720617
