### ISSUE TITLE
Unable to make the canvas/div containing a sunburst chart fit the width of the actual chart content (so there is no excess left and right margins)

### ISSUE THREAD

**Issue by mrxiaohe** [plotly/plotly.js#6546]
I have a sunburst chart embedded in a HTML page in a div set to `display:flow`. The chart itself is essentially a circle, so the height and the width are the same. I want the chart content to fill the container div's height, and I also want it to resize automatically based on the browser size and zoom level. 

While I am able to accomplish these, I have not been able to make the background canvas/div of the chart fit to the **width** of the content. As a result. the canvas/div is a lot wider than the content (see the screenshot on the bottom), hence taking up a lot of space. I tried setting the `width` of the div, and also tried `justify-content`, to no avail, I wonder what can be done to get rid of the excess left and right margins of the chart. My code is below, and a runnable snippet is [here](https://codepen.io/BigHungryBelly/pen/ZEMNXZM). Thanks!

**HTML**
```
<head>
  <!-- Load plotly.js into the DOM -->
  <script src='https://cdn.plot.ly/plotly-latest.min.js'></script>
</head>

<body>
  <div class='container'>
    <div id='sunBurst'><!-- Plotly chart will be drawn inside this DIV --></div>
    <div id="rightbox"> </div>
  </div>
</body>
```

**CSS**
```
.container {
  display: flex;
  width: auto;
  height: 100%;
  background-color: gray;
  display: flex;
}

#sunBurst {
  display: ;
  background: pink;  
  resize: both;
}

#rightbox {
}
```

**JS**
```
var data = [{
  type: "sunburst",
  labels: ["Skills", "Machine learning", "Optimization", "Organizational",
           "Python", "Cplex", "AWS", "Team work", "Git"],
  parents: ["", "Skills", "Skills", "Skills", "Machine learning", "Optimization", "Machine learning", "Organizational", "Machine learning" ],
  values:  [1, 1, 1, 1, 1, 1, 1, 1, 1],
  outsidetextfont: {size: 20, color: "#377eb8"},
  leaf: {opacity: 0.4},
  marker: {line: {width: 2}},
}];

var layout = {
  margin: {l: 0, r: 0, b: 0, t: 0},
  paper_bgcolor:"rgba(0,0,0,0)",
 plot_bgcolor:"rgba(0,0,0,0)",
  
};

var config = {responsive: false};

Plotly.newPlot('sunBurst', data, layout, config);


```
![image](https://user-images.githubusercontent.com/3064882/228912101-a5a8e5d5-3d62-454a-801e-ca88d2f1cc21.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
