### ISSUE TITLE
scattermapbox plots are not registred as subplots

### ISSUE THREAD

**Issue by kornerc** [plotly/plotly.js#6548]
When using `scattermapbox` the plot is not registered as a subplot and 

```js
Object.keys(myDiv._fullLayout._plots)
```
returns a empty list.

Here is a [minimal example](https://codepen.io/kornerc/pen/poOmmeP).

When I hover over a point I see in the developer tools that no subplots are registered and thus, plotly compains that it cannot find the subplot with the name `xy`:

![grafik](https://user-images.githubusercontent.com/1033108/229116727-fb31b107-4f7b-42cd-971b-7d7398b43097.png)

In comparison, when using a "normal", non `scattermapbox` plot, the plot is registered as a a subplot.

Here is a [minimal example](https://codepen.io/kornerc/pen/eYLaaEy).

Here `xy` is registered as subplot:

![grafik](https://user-images.githubusercontent.com/1033108/229117691-696847c1-6f8a-451d-9ddc-ea296bc637e6.png)

Due to that, I was not able to customize the hover behavior when using `scattermapbox`

**Comment by archmoj** [comment]
@alexcjohnson I'm not if this is a bug?
Also the underscore keys on the `fullLayout` object are internal.

**Comment by kornerc** [comment]
@archmoj thank you for your reply.

Due to this issue I cannot write an equivalent of [Hover Events in JavaScript / Coupled Hover Events](https://plotly.com/javascript/hover-events/#coupled-hover-events) for `scattermapbox` as demonstrated in [this example](https://codepen.io/kornerc/pen/wvYGKej).

I just used the underscore keys for the debugging of the problem.
But thanks for the heads up!

**Comment by alexcjohnson** [comment]
Right, non-cartesian subplots don't belong in `_plots`, but that's just an implementation detail. The real point is you want to be able to use `Plotly.Fx.hover` on other trace types like mapbox, and the fact that this doesn't work does seem to me to be a bug.

**Comment by archmoj** [comment]
Noting that the third argument to the `Plotly.Fx.hover` is the subplot.
For mapbox traces you need to pass the subplot id such as `mapbox`, `mapbox2`, etc.
Closing.
