### ISSUE TITLE
Firefox still breaks LaTeX rendering

### ISSUE THREAD

**Issue by moble** [plotly/plotly.js#6553]
Using Firefox 111.0.1 — the most recent as of this writing — LaTeX rendering still fails to set the box size correctly.  (I first tried this through the Julia interface, then Python, and now Javascript since that's the (descending) order in which I know those languages; the issue is the same in all.)

There seems to have been an attempted fix in [this PR](https://github.com/plotly/plotly.js/pull/5993), but I guess it doesn't work now.  In fact, that PR appears to have been incorporated into plotly-2.6.0, but even if I load that version it doesn't seem to work.  That PR suggested that it would be a workaround for #5374.

[Here is a codepen test](https://codepen.io/moble/pen/XWxWZdb) of the (correctly escaped) [example from the documentation](https://plotly.com/javascript/LaTeX/), along with what the relevant part looks like in Chrome

<img width="351" alt="ChromeRendering" src="https://user-images.githubusercontent.com/1470769/230431242-32b1eeb0-adbd-4d71-9a1b-c5c92422fe7f.png">

and what it looks like in Firefox

<img width="313" alt="FirefoxRendering" src="https://user-images.githubusercontent.com/1470769/230431279-767b13e0-e65c-4a4e-844f-da37722423f9.png">

Note that the legend entries get cut off in Firefox.  Looking at the source in Developer Tools, the full expressions are in there.  In fact, I can extract the `svg` elements, add an `xmlns`, and view the expressions on their own, and they render properly in Firefox.  So it evidently is a problem with the `g` containing the `svg`.

Is there at least a workaround?  I tried adjusting `layout.legend.entrywidth`, but that didn't seem to have any effect.

**Comment by bmaranville** [comment]
element.getBoundingClientRect() is returning bad values in Firefox, for the outer group.  It seems like there have been issues over the years with getBoundingClientRect - see e.g. https://bugzilla.mozilla.org/show_bug.cgi?id=1350755

It seems like element.getBBox returns reasonable values in both Firefox and Chrome, though it seems like there is a preference to use getBoundingClientRect in the plotly codebase.

**Comment by moble** [comment]
This appears to have been resolved.
