### ISSUE TITLE
In JavaScript, subplots don't have rowHeight attributes?

### ISSUE THREAD

**Issue by wanghe199512** [plotly/plotly.js#6561]
Hello, in JavaScript, there is no rowHeight property in subplots, I want to set a fixed height for each subplot, can someone help me！！

**Comment by alexcjohnson** [comment]
Yes, Python adds an extra layer on top of this but in Javascript this is controlled by the [`axis.domain`](https://plotly.com/javascript/reference/layout/yaxis/#layout-yaxis-domain) attribute, a length-2 array of numbers from 0 to 1. If you want to know the exact height of each, you must give the plot a fixed `layout.height` and `layout.margins` and disable any `automargin` properties because the domain refers to the height minus all margins.

**Comment by wanghe199512** [comment]
> Yes, Python adds an extra layer on top of this but in Javascript this is controlled by the [`axis.domain`](https://plotly.com/javascript/reference/layout/yaxis/#layout-yaxis-domain) attribute, a length-2 array of numbers from 0 to 1. If you want to know the exact height of each, you must give the plot a fixed `layout.height` and `layout.margins` and disable any `automargin` properties because the domain refers to the height minus all margins.

Excuse me, is there sample code? I want to set a fixed height for each subgraph

**Comment by wanghe199512** [comment]
Excuse me, is there sample code? I want to set a fixed height for each subgraph

**Comment by wanghe199512** [comment]
Excuse me, is there sample code? I want to set a fixed height for each subgraph

**Comment by wanghe199512** [comment]
> If you want `nRows`, with `rowHeight` each, `grout` between rows (for axis labels between subplots), and at the edges `marginTop` and `marginBottom` it would look something like:
> 
> ```js
> function findDomains(nRows, rowHeight, grout, marginTop, marginBottom) {
>     const innerHeight = nRows * rowHeight + (nRows - 1) * grout;
>     const height = innerHeight + marginTop + marginBottom;
>     const domains = [];
>     const domainDelta = rowHeight / innerHeight;
>     const domainStep = (rowHeight + grout) / innerHeight;
>     for(let i = 0; i < nRows; i++) {
>         domains.push([domainStep * i, domainStep * i + domainDelta]);
>     }
>     return {height, domains};
> }
> ```
> 
> Then you'd insert these into your `layout`, starting with `{height, margin: {b: marginBottom, t: marginTop}}`, then `domains[0]` going to the bottom `yaxis`, `domains[1]` to the one above it, and so on.

Thanks for the reply, I don't understand how to insert into the layout, 
 **Then you'd insert these into your `layout`, starting with `{height, margin: {b: marginBottom, t: marginTop}}`, then `domains[0]` going to the bottom `yaxis`, `domains[1]` to the one above it, and so on.**

can subplot be used like this? I remember domain is an array

**Comment by wanghe199512** [comment]
> > If you want `nRows`, with `rowHeight` each, `grout` between rows (for axis labels between subplots), and at the edges `marginTop` and `marginBottom` it would look something like:
> > ```js
> > function findDomains(nRows, rowHeight, grout, marginTop, marginBottom) {
> >     const innerHeight = nRows * rowHeight + (nRows - 1) * grout;
> >     const height = innerHeight + marginTop + marginBottom;
> >     const domains = [];
> >     const domainDelta = rowHeight / innerHeight;
> >     const domainStep = (rowHeight + grout) / innerHeight;
> >     for(let i = 0; i < nRows; i++) {
> >         domains.push([domainStep * i, domainStep * i + domainDelta]);
> >     }
> >     return {height, domains};
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then you'd insert these into your `layout`, starting with `{height, margin: {b: marginBottom, t: marginTop}}`, then `domains[0]` going to the bottom `yaxis`, `domains[1]` to the one above it, and so on.
> 
> Thanks for the reply, I don't understand how to insert into the layout, **Then you'd insert these into your `layout`, starting with `{height, margin: {b: marginBottom, t: marginTop}}`, then `domains[0]` going to the bottom `yaxis`, `domains[1]` to the one above it, and so on.**
> 
> can subplot be used like this? I remember domain is an array

Do you mean that the JSON returned by calling the findDomains method continues to append other layout code?

**Comment by alexcjohnson** [comment]
@wanghe199512 can you repost this on https://community.plotly.com/? That's a much better forum for "how to" questions, so we can keep GitHub more focused on features and bugs. Thanks!
