### ISSUE TITLE
Improve Heatmap rendering performance when zsmooth is false

### ISSUE THREAD

**Issue by lvlte** [plotly/plotly.js#6573]
The idea is to use the zsmooth="fast" rendering method, which is currently faster than without smoothing (imageData pixel array vs fillRect), whenever possible, and tell the browser to *not* interpolate when zsmooth is false.

The condition is that all bricks should be uniform (ie. linear axes, linear scales, no gaps), so the proposition doesn't come as a replacement for the fillRect loop. 

Here is a [codepen](https://codepen.io/lvlte/pen/BaqLawR) that illustrates what I mean. 

The performance gain becomes significant when used with sliders, as discussed [here](https://stackoverflow.com/q/75719733/2529954), and [here](https://github.com/plotly/plotly.js/issues/6521).

**Comment by alexcjohnson** [comment]
Thanks @lvlte - this is a great idea, the main constraint here is we need to detect whether the browser supports [`image-rendering: pixelated`](https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering) - all current browsers do seem to support this, but we generally aim to support at least 7-year-old browsers and some of them only got this 2-3 years ago.

**Comment by lvlte** [comment]
I'm about to submit a PR but yes I should have started with this (the browser support detection is not part of the PR yet - and I hope the detection is feasible without all of this ending too hackish).

Do you know if there is a browser feature detection utility used somewhere in the project, something that i could reuse ? Or is the idea already too hackish ?
