### ISSUE TITLE
document the structure of trace modules

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#66]
Motivated by #63 ... we should describe this structure somewhere in the contributor's guide. What's generally supposed to be the role of `attributes`, `supplyDefaults`, `supplyLayoutDefaults`, `calc`, `setPositions`, `plot`, and `style` (anything else?), how to tell the difference, and when each of them gets called. Without that it's pretty hard for new people to make any meaningful contributions to the drawing code. The non-trace modules (axes, annotations, etc...) may still be too ad-hoc for this kind of doc to be useful, but I think the traces are fairly uniform by now.

Of course if this leads us to the desperately needed refactor & modularization of `restyle` and `relayout` I wouldn't complain, but that shouldn't stop us from documenting what we have.

**Comment by etpinard** [comment]
the gl trace module need a `convert` step too at the moment.

**Comment by etpinard** [comment]
I'll try to make a PR for this ticket before I go.

@archmoj is there anything in particular regarding the trace module structure that you'd like me to write on?

**Comment by archmoj** [comment]
It would be helpful to know "when each of them gets called".

**Comment by etpinard** [comment]
TODO:

- (not really related this to, but something I should write about) how to debugger in jasmine test window to write interaction tests faster.

**Comment by etpinard** [comment]
![Peek 2020-03-11 10-45](https://user-images.githubusercontent.com/6675409/76438118-f2502300-6390-11ea-88d2-17a553c3b4e8.gif)

:arrow_up: gif I'll add to the `CONTRIBUTING.md` doc.
