### ISSUE TITLE
`image` traces with negative `dx` or `dy`

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#6600]
You can invert an `image` trace in either or both directions by inverting the axis ranges:
```js
Plotly.relayout(gd,{'xaxis.autorange':'reversed','xaxis.range':null,'yaxis.autorange':true,'yaxis.range':null})
```
(note that setting `range:null` is necessary when trying to un-invert an axis that previously had `autorange:'reversed'`. It's not necessary when inverting a previously normal axis, but for symmetry we could consider creating an option `autorange:'normal'` so you don't need the `range:null`... but that's a minor point)

But if you try to invert the image using `dx<0`, the image is drawn in the correct place but not correctly flipped, while the hover data is correct for the pixel that should have been drawn - for example here I'm hovering on what should have been the black of the helmet, mirrored left-to-right:
<img width="527" alt="Screenshot 2023-05-12 at 09 59 37" src="https://github.com/plotly/plotly.js/assets/2678795/5a17db48-0fa6-4524-9ece-f57f9d7a6c94">
If I use `dy<0` it's weirder: similar to `dx<0` the image is drawn in the correct place but not correctly flipped. However the hover is even more broken. Here I've panned so there's space below the image. My mouse was about where I drew the green arrow, but the hover showed up the same distance below the bottom edge of the image, with no data (`z: [0,0,0,0]` at all locations):
<img width="423" alt="Screenshot 2023-05-12 at 10 07 39" src="https://github.com/plotly/plotly.js/assets/2678795/d198e8b2-4823-4661-9d4f-91f7d1b64239">

I don't know if there's a use case for this... we could either fix it or just force `dx` and `dy` to be positive.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
