### ISSUE TITLE
Axis layout settings are ignored when using scatter3d

### ISSUE THREAD

**Issue by danielsamuels** [plotly/plotly.js#663]
When using a scatter3d type, it seems that the `xaxis`, `yaxis` and `zaxis` layout options are all ignored.

[This is a file using `scatter3d`](http://codepen.io/danielsamuels/pen/jrMYOq)
[This is the same file, but using `scatter`](http://codepen.io/danielsamuels/pen/dXpJPg)

As you can see, the 2d scatter takes the axis settings into account, but the 3d scatter doesn't.

**Comment by cldougl** [comment]
To use those options with scatter3d charts you can wrap them in the `scene` object.
Here's your codepen example edited: http://codepen.io/plotly/pen/qNapRJ
Here's the `scene` reference: https://plot.ly/javascript/reference/#layout-scene

(We'll add some additional examples to: https://plot.ly/javascript/#layout-options)

**Comment by danielsamuels** [comment]
Oh, that's perfect - thank you!

**Comment by cldougl** [comment]
No problem. That point is not currently exhibited clearly in our js docs (https://github.com/plotly/documentation/issues/439), thanks for pointing that out!
