### ISSUE TITLE
toggling visibility of most legend groups fails in editable charts as of plotly 2.22.0

### ISSUE THREAD

**Issue by michaelbabyn** [plotly/plotly.js#6638]
It looks like plotly 2.22.0 introduced a regression in the click behaviour of legend groups in editable charts. Specifically, only the first one seems to toggle the visibility properly. Clicking on other groups causes this error in the browser console:

  ```
Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at k (plotly-2.22.0.min.js:8:155632)
    at Object.clickFn (plotly-2.22.0.min.js:8:155432)
    at HTMLDocument.T (plotly-2.22.0.min.js:8:65592)
```

codepens: clicking on the second legend group to make those traces invisible [fails with Plotly>=2.22.0](https://codepen.io/michaelbabyn/pen/abQzMpP) but [works with plotly <2.22.0](https://codepen.io/michaelbabyn/pen/RwqNdVP)

**Comment by archmoj** [comment]
Thanks @michaelbabyn for the report and codepens too!
