### ISSUE TITLE
Click annotations stay when trace is hidden, and can't be removed without restoring trace.

### ISSUE THREAD

**Issue by abalter** [plotly/plotly.js#664]
You can see the effect in these examples:

https://plot.ly/javascript/text-and-annotations/

It makes sense that when you hide a trace, the annotations should hide as well. A prime example is one I'm doing right now where my popup click annotations cover a trace behind it. I should be able to hide the trace with the annotations briefly to look at the data behind, and then restore the trace with the pickets still there.

**Comment by etpinard** [comment]
Thanks for the feedback.

I agree, in this particular example the legend should toggle both traces and annotations. In more technical terms, each annotation is linked to a trace. Unfortunately, there is not the case in general and exposing an API to link components to traces isn't in our short-term plans.

In the meantime, here's a hacky solution: http://codepen.io/etpinard/pen/ZWdjNy

**Comment by etpinard** [comment]
related to https://github.com/plotly/plotly.js/issues/65

**Comment by abalter** [comment]
Hmmm. Trying to use this for professional presentations. I think a better hacky solution would be to capture the hide event, store the annotation data somewhere, then capture the show event and restore it.

Say, I think I saw somewhere that you are collecting feedback for 2.0. Can you direct me to that?
