### ISSUE TITLE
Right after drawing a new shape it is not set on the fullLayout when there is a shape in template 

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#6647]
I noticed this on `text_on_shapes_reversed_axes` mock.

**Comment by nickmelnikov82** [comment]
I tried to reproduce it like this -> 
```javascript
gd.layout.shapes[0].label.text = 'changed_shape0_text'; //change text for shape in layout
gd.layout.template.layout.shapes[0].label.text = 'changed_template_shape0_text' //change text for shape in template of layout
Plotly.update(gd, null, gd.layout); //update
console.log(gd._fullLayout.shapes[0].label.text); //'changed_shape0_text'
console.log(gd._fullLayout.template.layout.shapes[0].label.text); //'label' - original
```
I have checked the related code part and did not find any background relatively updating template object.
Currently only shapes are getting updated:
https://github.com/plotly/plotly.js/blob/ac2ce6619180a231233e0e38cf7a0de80d1df2de/src/components/shapes/defaults.js#LL11C43-L11C43

Do we need to make update for template in `fullLayout`?

**Comment by archmoj** [comment]
> Do we need to make update for template in `fullLayout`?

@nickmelnikov82 No we shouldn't touch the template in fullLayout.
I noticed this update problem also exists for other attributes e.g. `line.color`, etc. when there is a shape in `layout.template.layout.shapes`, then `layout.newshapes` values are not applied until the second new shape added.
Investigating...
