### ISSUE TITLE
403: Forbidden Error - Plotly unavailable now for download/use?

### ISSUE THREAD

**Issue by shaedmorgan** [plotly/plotly.js#6648]
Whenever I try to use/access Plotly, whether by CDN, NPM, or direct download from their site, it shows up as a 403 ERR_ABORTED code. Is Fastly or other resource down that we should be aware of?

**Comment by bgrgndzz** [comment]
Same issue!

**Comment by arda-bulut** [comment]
Same. All of a sudden, I'm getting Access Denied.

**Comment by shaedmorgan** [comment]
Edit: NPM install works - used to download a hard copy to deploy and read in via script locally instead of using CDN - but would still appreciate follow-up on what's going on!

**Comment by lucasnetau** [comment]
Same here. https://cdn.plot.ly/ is giving Access Denied for 

```xml
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>ZNEE2ZPGZG8R8ZFJ</RequestId>
<HostId>cEHu/w6jp0kidjR4ejIEQ6awUXzfVr4q9XVbQFIdIo+AUf9RBwzTvDD+m2T5/Iu2CzFtvV0e6E4=</HostId>
</Error>
```

**Comment by nomadiq** [comment]
Same problem here. Alternative location: https://cdnjs.cloudflare.com/ajax/libs/plotly.js/2.24.2/plotly.min.js

**Comment by imdex-brett-debeer** [comment]
We're using [angular-plotly.js](https://github.com/plotly/angular-plotly.js) and have the same problem.

**Comment by zidlier** [comment]
I used the file in the dist folder and should still be working
https://raw.githubusercontent.com/plotly/plotly.js/master/dist/plotly.min.js

**Comment by MuriloChianfa** [comment]
im having the same problem here.

**Comment by xta** [comment]
Other CDN assets are also currently unavailable

GET https://cdn.plot.ly/usa_110m.json also is 403 status

**Comment by kkoomen** [comment]
When will this be fixed? Would be nice if someone from the team could answer the current status and when this might be fixed.

**Comment by aliiakaay** [comment]
I have same issue, I can not also see the plots on plotly webpage https://plotly.com/python/line-and-scatter/

**Comment by pepijntje02** [comment]
I had the same issue. A workaround for me was to use the offline file from @zidlier and add that script in the HTML file.

**Comment by gigouni** [comment]
A (temp) fix has been found by targeting another CDN: https://cdnjs.com/libraries/plotly.js

Tried with the first and it worked back!

**Comment by alimanfoo** [comment]
For anyone hitting this from the plotly python space and trying to figure out how to configure plotly python to use a different CDN, here what I managed to hack (please say if there is a better way):

```python
import plotly
import plotly.io
import plotly.io._utils
from plotly.offline import get_plotlyjs_version


def plotly_cdn_url_hacked(cdn_ver=get_plotlyjs_version()):
    """Return a valid plotly CDN url."""
    # Hack to use a CDN that works.
    # See also https://github.com/plotly/plotly.js/issues/6648
    return "[https://cdnjs.cloudflare.com/ajax/libs/plotly.js/{cdn_ver}/plotly.min.js](https://cdnjs.cloudflare.com/ajax/libs/plotly.js/%7Bcdn_ver%7D/plotly.min.js)".format(
        cdn_ver=cdn_ver,
    )


setattr(plotly.io._utils, "plotly_cdn_url", plotly_cdn_url_hacked)
```

**Comment by Lucas-BLP** [comment]
Plotly choropleth is also down today due to access denied to https://cdn.plot.ly/world_110m.json

**Comment by arif98741** [comment]
facing same issue. alternatively we are using cdnsjs for support as temporary

**Comment by KarthikaRavindran** [comment]
This could be used as an alternative,

[Alternative cdnjs for plotly](https://cdnjs.cloudflare.com/ajax/libs/plotly.js/2.24.2/plotly.min.js)

**Comment by arif98741** [comment]
> This could be used as an alternative,
> 
> [Alternative cdnjs for plotly](https://cdnjs.cloudflare.com/ajax/libs/plotly.js/2.24.2/plotly.min.js)

yes. it works also

**Comment by Lucas-BLP** [comment]
You could use the wayback machine for static files, the url to https://cdn.plot.ly/world_110m.json is also affected.
https://web.archive.org/web/20230620005513/https://cdn.plot.ly/world_110m.json

**Comment by alexcjohnson** [comment]
Thanks all - we're working on it.

**Comment by alexcjohnson** [comment]
Please try again, should be working now. Sorry for the inconvenience!

**Comment by arif98741** [comment]
> Please try again, should be working now. Sorry for the inconvenience!

Its working. Thanks for quick support

**Comment by DanNeidle** [comment]
thank you!
