### ISSUE TITLE
npm run citest-jasmine fails locally

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#666]
Looks like `npm run citest-jasmine` is calibrated for CircleCI only.

Off 3c85d9e

![image](https://cloud.githubusercontent.com/assets/6675409/16200600/00c468c8-36dc-11e6-85ff-b017380b29e0.png)

I suspect that these issues are related to the browser window size. The failing tests should go away once we add a `window-size` flag in the `karma.ciconf.js` file like we currently do in the (local) [`karma.conf.js`](https://github.com/plotly/plotly.js/blob/3c85d9eb47ce08177d951065fd66a7d9f9671e57/test/jasmine/karma.conf.js#L79).

Moreover, perhaps we should merge the two karma conf files into one and use the CirlcleCI environment [variable](https://circleci.com/docs/environment-variables/#basics) to set up CI specific flags.

**Comment by alexcjohnson** [comment]
Locally I see a default body margin of 8px. I'd rather just set this to 0, then the pixel positions we have to use for mouse events will make more sense anyway. I'll try to address this in my working branch.

**Comment by etpinard** [comment]
@rreusser off `1.14.0`:

```
Firefox 42.0.0 (Mac OS X 10.11.0) mapbox plots should be able to relayout FAILED
    Expected 80,100,904,270 to be close to 80,100,908,270.
```

and

```
Firefox 42.0.0 (Mac OS X 10.11.0) hover on fill should always show one label in the right place FAILED
    Expected 254.27499999999998 to be close to 249.175, -1, 'trace 2:x'.
    assertLabelsCorrect/</<@/var/folders/5s/mm8_jrls0zd34zkb1z71xb940000gp/T/3e5f6eaff748734ec0be007b7921fd04.browserify:152118:17 <- tests/hover_label_test.js:673:0
```

**Comment by rreusser** [comment]
First test: `tests/hover_label_test.js:673:0`
Commit: `b6fc59d`
