### ISSUE TITLE
No way to center legend title in horizontal mode when x is set to a value between 0 and 1

### ISSUE THREAD

**Issue by GeorgeFlorian** [plotly/plotly.js#6668]
I am trying to center a legend title with the legend being in horizontal mode, but there is no way of doing it.
The only prop that modifies the legend's title positioning is `side`, which does not center it.

The current behavior is that the legend title is always positioned at the beginning of the legend area.

https://codepen.io/bleah1/pen/bGQYvbm?editors=1010

![image](https://github.com/plotly/plotly.js/assets/39895513/ff7490e0-0de6-4128-b588-697a78d04071)

**Comment by 28raining** [comment]
Created PR
https://github.com/plotly/plotly.js/pull/6711

**Comment by GeorgeFlorian** [comment]
> Created PR #6711

Doesn't seem to work:
https://codepen.io/bleah1/pen/bGQYvbm?editors=1010

There is no difference between `side: "top center"`, `side: "top"` or side: "top right".

Am I doing something wrong ?

**Comment by archmoj** [comment]
@GeorgeFlorian thanks for the report.
It is working when `x` is set to 0 or 1 : [codepen](https://codepen.io/MojtabaSamimi/pen/gOZgxoa?editors=1010)
Otherwise it looks like a bug.

**Comment by 28raining** [comment]
Created https://github.com/plotly/plotly.js/pull/6725
