### ISSUE TITLE
locale pt-BR

### ISSUE THREAD

**Issue by moisesbites** [plotly/plotly.js#6676]
Hello Guys!

In format of locale pt-BR, in Brazil, we use:

```js
locale = {

  format: {

    decimal: ',',
    thousands: '.'
  }
};
```

I appreciate if you can make this improvement in the file https://github.com/plotly/plotly.js/blob/master/dist/plotly-locale-pt-br.js.

Thank you!

**Comment by archmoj** [comment]
Instead of the file in the dist folder, this file should be modified:
https://github.com/plotly/plotly.js/blob/master/lib/locales/pt-br.js

Here is the instruction if you are interested to submit a PR.
https://github.com/plotly/plotly.js/blob/master/.github/PULL_REQUEST_TEMPLATE.md#translations
