### ISSUE TITLE
Hide Plotly's Hover Box When Mouse Is Hovered Over Plot

### ISSUE THREAD

**Issue by kennyxiegao** [plotly/plotly.js#668]
I know this probably isn't supported by the API, but when I hover over a plot, I want only the text to show up and not the text box. Anyone have any ideas on how to do this? Thanks.

**Comment by etpinard** [comment]
In other words, you want to _style_ the hover text box?

In that case, you may want to look at http://community.plot.ly/t/to-change-hover-text-properties/1170

We are planning on adding some sort of hover-label style attribute to our API at some. We might want to subscribe to https://github.com/plotly/plotly.js/issues/102 to get the latest development info.
