### ISSUE TITLE
Use of named colours in scatterGL is not case-insenstive

### ISSUE THREAD

**Issue by dsmmcken** [plotly/plotly.js#6685]
When using CSS colour names for a marker color, they should be case insensitive. I expected `LemonChiffon` to works as it is valid CSS3 colour, and works in svg, however a scatterGL trace renders it as black. 

> As usual for CSS-defined idents, all of these [color] keywords are ASCII [case-insensitive](https://drafts.csswg.org/css-color/#named-colors).

A simple fix would be to apply a lowercase before setting colours in the scattergl code, though I am not entirely sure why this isn't working currently.

Codepen:
https://codepen.io/dsmmcken/pen/JjeambK

![image](https://github.com/plotly/plotly.js/assets/1576283/477e2d32-83b7-4744-897b-005dc030ab32)

**Comment by 28raining** [comment]
The issue is inside this package:
https://www.npmjs.com/package/color-parse

which utilizes this package:
https://www.npmjs.com/package/color-name

where we can see all the string -> color code translation is in lower case

Created this issue -> https://github.com/colorjs/color-parse/issues/5

**Comment by 28raining** [comment]
@archmoj looks like you're a maintainer of that repo. If you agree with this analysis, let's create a new version

**Comment by 28raining** [comment]
note that the package dependency path is

ScatterGl -> plot.js -> regl-line2d -> color-normalize -> color-rgba -> color-parse

**Comment by archmoj** [comment]
> @archmoj looks like you're a maintainer of that repo. If you agree with this analysis, let's create a new version

@28raining Yes please feel free to submit a PR. Thank you!

**Comment by 28raining** [comment]
Added to PR https://github.com/plotly/plotly.js/pull/6725
