### ISSUE TITLE
Providing a negative number as the only range value reversed the axis

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#6693]
In this [codepen](https://codepen.io/MojtabaSamimi/pen/RwqEzYM?editors=0010) using `[-1, null]` as range reversed the axis.
@alexcjohnson is this the expected behavior?

**Comment by gvwilson** [comment]
ping @alexcjohnson

**Comment by alexcjohnson** [comment]
No, not the expected behavior... but if I update the plotly.js version in that codepen to the latest 2.34.0 it seems like this was fixed at some point.
