### ISSUE TITLE
Box plot to draw based on mean+-std deviation 

### ISSUE THREAD

**Issue by 28raining** [plotly/plotly.js#6697]
We'd like box plots to have the ability to draw the box based on standard deviation instead of quartiles.
This allows us to identify which data points need more attention.

This is something Tableau can do, the tool we use currently.

We're using PlotlyExpress which is why it's so hard to set q1,q2,q3 manually, because PlotlyExpress creates many 2-D datasets from the single dataFrame we give it. (because we separate plots by color, row, column)

![image](https://github.com/plotly/plotly.js/assets/18679628/0277b4af-1668-487f-af39-0ea3c0362bcc)

**Comment by 28raining** [comment]
Created pull request

https://github.com/plotly/plotly.js/pull/6698

**Comment by alexcjohnson** [comment]
closed by #6698 🎉
