### ISSUE TITLE
Something is up with relayout while adding/removing layout images

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#670]
See http://codepen.io/etpinard/pen/qNagLZ

Compare to the behavior for shapes: http://codepen.io/etpinard/pen/xVPoYG

**Comment by EvertS3** [comment]
@etpinard Multiple images can now be added but it seems there might still be a bug here, when trying to remove the images, only the latest one gets removed. The rest stay on the plot? See your code example: http://codepen.io/etpinard/pen/qNagLZ

**Comment by etpinard** [comment]
@EvertS3 here's a working version: http://codepen.io/etpinard/pen/qNagLZ
