### ISSUE TITLE
Stacked Funnel Chart

### ISSUE THREAD

**Issue by thao-io** [plotly/plotly.js#6713]
Is it possible to show conversions when grouped say step to see the conversion rate to the overall?

For example, I want to see the conversion rate for page A vs page B compared to the initial step. While, I can create a stacked funnel chart. The conversion rates are separated and not relative to the overall the initial step. 

1. Users created
2. Users clicked A / Users clicked B
3. Users clicked A conversion to overall users created / Users clicked B conversion to overall users created

**Comment by gvwilson** [comment]
Hi - we are tidying up issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. For tech support and "how-to" questions, please post in our community forum https://community.plotly.com/. Thank you - @gvwilson
