### ISSUE TITLE
Get click coordinate after a click with touch device

### ISSUE THREAD

**Issue by josephernest** [plotly/plotly.js#6721]
Let's say we have the `select` tool active on a heatmap. Live demo [here](https://gget.it/5ur5/test.html), see the JS console.

We successfully get the coordinates:
* when **drag-and-drop**: `plotly_selected` event => we have the coordinates in `event.selections`
* when **click**: `plotly_click` event => we have the coordinates in `event.points`

When using a **touchscreen**, we also successfully get the coordinates when drag-and-drop: the `plotly_selected` event is fired and we have the coordinates in `event.selections`. **But when clicking (=tap), we only get:**

* `plotly_selected undefined`, and no coordinate.

**Question: I know that Plotly.js touch support is limited for now, but is there a way to get `plotly_click` event when we do a tap on a heatmap (with `select` tool), and have the coordinates in `event.points`?**

PS: Even if I used an event listener with touch events (such as `touchstart`, `touchend`), I wouldn't get the coordinates in Plotly plot coordinate system.

@lvlte Maybe you have an idea? (I know you have experience in these topics!)

**Comment by josephernest** [comment]
With touch (see here simulated with Dev Console), we only get coordinates when drag-and-drop, but **not when single click/tap**:

https://github.com/plotly/plotly.js/assets/6168083/0fd6384f-7001-441c-99e2-448c60f8d2d2

Is there a workaround for this?

With mouse, we get coordinates in both cases (drag-and-drop, and single pixel click):

https://github.com/plotly/plotly.js/assets/6168083/a4620643-361d-49bc-8ece-b78ba894f4f7

**Comment by lvlte** [comment]
Hi @josephernest, I did some tests and realized that with `dragmode: "zoom"` (default), `plotly_click` events are properly fired on touchscreen devices, whereas with `dragmode: "select"` they are not, even though the click is detected. This helped me find the involved code and I think I have found a fix, but I have to do some tests to be sure it won't break anything.

**Comment by josephernest** [comment]
Thanks @lvlte, that's great! Feel free to send me the lines involved, I can try if it fixes it by just manually patching it. Thanks again!

**Comment by lvlte** [comment]
@josephernest see the unique commit in the linked PR.

**Comment by archmoj** [comment]
Fixed by #6724.
