### ISSUE TITLE
The violin plot very weird 

### ISSUE THREAD

**Issue by honghh2018** [plotly/plotly.js#6730]
Hi, i want to plot the gene expression using the violin plot of plotly.js，but the plot showing weird lying below

![image](https://github.com/plotly/plotly.js/assets/41668708/d56efaeb-d23a-410b-87c3-9739418d5e1a)

the data had very lot of zero value, and had the max value, it can not showing the normal middle value in my data using violin plot

the normal plot of the  test day lying below:
![image](https://github.com/plotly/plotly.js/assets/41668708/00143c83-9bc1-45c5-b48c-8aad0c3fa246)

So how can i fix  this issue? any advices would be appreciated
best,
hanhuihong

**Comment by alexcjohnson** [comment]
Sounds like the violin plot itself is doing the right thing given the data it received, so I'll close this issue. My guess is if the zeros are not meaningful data to you, they should be filtered out in a preprocessing step (maybe leaving one of them so you still see that there are zeros, but not so many that they swamp the real data) but if you want to discuss this further the right place to post is https://community.plotly.com/
