### ISSUE TITLE
Image Trace Not Displayed

### ISSUE THREAD

**Issue by ebel-magnin** [plotly/plotly.js#6732]
![script_js](https://github.com/plotly/plotly.js/assets/78963822/d8dee2bf-ec53-4620-8f26-fc3cc125aba5)
![index_html](https://github.com/plotly/plotly.js/assets/78963822/00303c6a-34b3-4948-b8a2-2e1bc780cd6b)
Thanks for your interest in plotly.js!

The attached code does not render the image. I use Ubuntu 22.04

**Comment by 28raining** [comment]
You can find examples of how to use images here
https://plotly.com/javascript/images/

Please provide an example from Codepen if you have more issues.
Keep an eye on your web console for errors

**Comment by ebel-magnin** [comment]
I am aware of these examples, but what a need is to display a mammogram as the main image trace. In Plotly for Python the function imshow() is used for this purpose. I need the equivalent of this function in Plotly JS. I have developed a breast cancer detection model in Tensorflow JS, which displays the mammogram. If the probability is 70% or more, I want to draw a box around the area where the model suspects cancer cells. With the Plotly zoom function the radiologist can zoom in on that area. This allows him or her to record the coordinates of area and then advice further screening that area with ultrasound or biopsy.

 

Looking forward to your answer.

 

Best regards,

Ebel Magnin

**Comment by alexcjohnson** [comment]
That page describes `layout.images`, which is meant for displaying non-data images like logos. You're trying to use the `image` trace type, which is https://plotly.com/javascript/reference/image/#image-source - and in particular this doesn't support display from a URL, it wants either a `data:image` URI or an MxNx(3 or 4) array. We don't have a reference page for doing this in JS, but in Python the lower-level interface looks like this: https://plotly.com/python/imshow/#passing-image-data-as-a-binary-string-to-goimage or https://plotly.com/python/imshow/#display-multichannel-image-data-with-goimage respectively.
