### ISSUE TITLE
Changing x axis tick mark labels to a larger font fails to change the font size

### ISSUE THREAD

**Issue by quantillaproject** [plotly/plotly.js#6748]
Here is a snippet of my code in which I set a number of parameters for Plotly's Layout object to change font size, family, and color. But, when run, the size never changes - yet all the other changes work:

```
const layout: Partial<Layout> = {
        dragmode: "pan", // make plot draggable by default
        showlegend: false,
        autosize: true,
        useResizeHandler: true,
        height: undefined,
        width: undefined,
        title: "Estimated wealth over time",
        yaxis: { tickfont: {size: 24, color: 'red', family: 'Arial, sans-serif' },
                 title: "Wealth ($M)", showgrid: true,
               },
        xaxis: {tickfont: {size: 36, color: 'blue'},
                 title: "Age", showgrid: false, autorange: true, type: "category",
                 dtick: 5,
           },   };
```

Just to be clear I am doing what the documentation says. Here is a CodePen I ran across which sets the font size for the X axis that does work.  But my code does not.

This problem, BTW, is cpu-dependent but not browser-specifi.  In other words, it fails to work on my computer but the same code (synchronized via GitHub) is being used; on an associate's laptop it is OK.  I have explored the objects in the graph that does come up, and font size is always set at 24.

Here is a codePen with the bare minimum amount of code to reproduce.  In fact, this works fine - but the code in my app does not.  

 ```
var layout = {
  autosize: false,
  width: 500,
  height: 500,
  xaxis: {tickfont: {size: 36, color: "blue"}},
  margin: {
    l: 50,
    r: 50,
    b: 100,
    t: 100,
    pad: 4,
  },
  paper_bgcolor: '#7f7f7f',
  plot_bgcolor: '#c7c7c7'
};
Plotly.newPlot('myDiv', data, layout, {showSendToCloud: true});


Which gives this (correctly):
```
![image](https://github.com/plotly/plotly.js/assets/33078648/0aebb55f-acf3-4b99-bfa4-f53498844aa7)

**Comment by alexcjohnson** [comment]
Looks like #6749 has more info so I'll close this one
