### ISSUE TITLE
changing Layout.xaxis.tickfont.size and Layout.yaxis.tickfont.size fails to work to make the axis tick labels a bigger font.

### ISSUE THREAD

**Issue by quantillaproject** [plotly/plotly.js#6749]
Here is a snippet of my code in which I set a number of parameters for Plotly's Layout object to change font size, family, and color. But, when run, the size never changes - yet all the other changes work:

```
const layout: Partial<Layout> = {
        dragmode: "pan", // make plot draggable by default
        showlegend: false,
        autosize: true,
        useResizeHandler: true,
        height: undefined,
        width: undefined,
        title: "Estimated wealth over time",
        yaxis: { tickfont: {size: 24, color: 'red', family: 'Arial, sans-serif' },
                 title: "Wealth ($M)", showgrid: true,
               },
        xaxis: {tickfont: {size: 36, color: 'blue'},
                 title: "Age", showgrid: false, autorange: true, type: "category",
                 dtick: 5,
           },   };
```
here is a sample of the output, with a much smaller font than 36:
![image](https://github.com/plotly/plotly.js/assets/33078648/d128f50c-68a4-4a59-9a86-11bb2f0a5d11)

Just to be clear I am doing what the documentation says; I am setting Layout.xaxis.tickfont.size.   Below is a CodePen I ran across which sets the font size for the X axis that _does_ work.  But my code does not, with the same parameters.

This problem, BTW, is cpu-dependent but not browser-specific.  In other words, it fails to work on _any_ browser on my computer when the same code (synchronized via GitHub) is being used; on an associate's laptop it is OK on _all_ browsers.  I have explored the objects in the graph that does come up, and here is what I see.  This comes from Plotly generated code (see the 4th line from the bottom):

Here is what you see when you inspect the x axis tick elements on Chrome:
![image](https://github.com/plotly/plotly.js/assets/33078648/a247e0b0-a18a-4f11-bede-c95e9aa6618e)
![image](https://github.com/plotly/plotly.js/assets/33078648/b72bd380-814b-49ec-bc20-1776a1cb3562)
![image](https://github.com/plotly/plotly.js/assets/33078648/8f1ab91f-02c9-435a-8f94-048e2664fa2c)

Here is a codePen with the bare minimum amount of code to reproduce.  In fact, this does _work_ fine -  but the code in my app on my CPU does not, leading to quite a mystery.

 ```
var layout = {
  autosize: false,
  width: 500,
  height: 500,
  xaxis: {tickfont: {size: 36, color: "blue"}},
  margin: {
    l: 50,
    r: 50,
    b: 100,
    t: 100,
    pad: 4,
  },
  paper_bgcolor: '#7f7f7f',
  plot_bgcolor: '#c7c7c7'
};
Plotly.newPlot('myDiv', data, layout, {showSendToCloud: true});


Which gives this (correctly):
```
![image](https://github.com/plotly/plotly.js/assets/33078648/0aebb55f-acf3-4b99-bfa4-f53498844aa7)

**Comment by alexcjohnson** [comment]
What version of plotly.js do you have in your app, and how are you getting it?

The next thing to look at is `gd._fullLayout` where `gd` is the `<div>` in which you created the plot. It should contain all the layout info you specified, plus the defaults for anything you didn't specify. However given that the `__data__` for the `g.xtick` element contains `fontSize: 36` I suspect we're doing what we can to set the `font-size` style attribute but it's getting overridden by something in your CSS. Try `document.querySelector('g.xtick text')` and then (if you're in Chrome) right-click the result -> "Reveal in Elements panel". If I do that in https://codepen.io/alexcjohnson/pen/wvQYwvy I see:
<img width="866" alt="Screenshot 2023-10-17 at 22 22 31" src="https://github.com/plotly/plotly.js/assets/2678795/9964ca8c-2f7a-4d8e-a3c2-eb69e317d993">
where `font-size: 36px;` is visible on the right side. Either that's not there in your plot, or it's there and crossed out, meaning it was overridden and farther down you should be able to see what's overriding it.

**Comment by quantillaproject** [comment]
I am using Plotly 2.20.0, but I have tested it with 2.26.2 as well and same problem.   I’ll try your ideas.  Yes, it looks like an override is making the trouble, but curiously it doesn’t do the same thing on another computer.

**Comment by quantillaproject** [comment]
To be clear, when I do what you did the element being inspected shows 12px as the font size:
￼

**Comment by alexcjohnson** [comment]
I don't see an image but if `element.style` shows `font-size: 12px` rather than the size you specified, it's not extra CSS overriding this, could really be a bug in the library. It's going to be very hard for us to track it down though unless we can find the conditions to reproduce it ourselves.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
