### ISSUE TITLE
Feature Request: Pie Charts Variable Inner Radius

### ISSUE THREAD

**Issue by barrymichaeldoyle** [plotly/plotly.js#6768]
<img width="304" alt="Screenshot 2023-11-02 at 14 10 01" src="https://github.com/plotly/plotly.js/assets/4674486/5e3090ab-254f-47bb-9035-c27705674163">

It would be epic if there was a way to make a Pie Chart have slices with variable inner radii, currently the donut pie chart has the `hole` properties which will set the radii for every slice instead of individual slices.

**Comment by archmoj** [comment]
If you are interested to submit a PR, then you need to add `arrayOk: true,` to `hole` attribute here: https://github.com/plotly/plotly.js/blob/a539c887c2a8fd7cacc8e2fe4af62ffb29fbc56a/src/traces/pie/attributes.js#L241-L251

Then inside [`pie/plot.js`](https://github.com/plotly/plotly.js/blob/master/src/traces/pie/plot.js`), you should revisit places `.pole` is used to read the value. E.g. you could see how this is handled for the `pull` attribute which is already `arrayOk`.

Please visit [`CONTRIBUTING.md`](https://github.com/plotly/plotly.js/blob/master/CONTRIBUTING.md) for more information.

**Comment by barrymichaeldoyle** [comment]
@archmoj thank you so much! I've pushed changes to the PR. I think I've covered all `.hole` scenarios. Hopefully correctly :)

**Comment by archmoj** [comment]
I don't see a use case for this feature at this moment.
Closing.
