### ISSUE TITLE
scattergl trace with marker angle array does not draw marker in legend

### ISSUE THREAD

**Issue by curtisratzlaff** [plotly/plotly.js#6770]
Code pen: [(https://codepen.io/curtisratzlaff/pen/GRzjMyK)](https://codepen.io/curtisratzlaff/pen/GRzjMyK)

The marker is missing from the legend:
![image](https://github.com/plotly/plotly.js/assets/26006732/5cb1793a-886a-4a5a-a3dd-ccdb122610ca)

The console outputs this error:
![image](https://github.com/plotly/plotly.js/assets/26006732/19268498-85a6-4c73-8612-0bb8c8180459)

Searching the the html for nan I find this:
![image](https://github.com/plotly/plotly.js/assets/26006732/faaa5b30-2089-4f52-93d7-66b88418ea9d)

A couple of things that will make this problem go away.
- If you remove the marker.angle array from the trace definition.
- If you only provide a single value in the array.
- If you specify "circle" in the marker.symbol.
- If you change the trace type to scatter.

Let me know if I can provide any more information.

**Comment by archmoj** [comment]
Thanks for the report.
@curtisratzlaff Are you interested to submit a PR to help fix this bug?

**Comment by curtisratzlaff** [comment]
I'm not sure what the fix is. I found this issue while working on a project this week and wanted to report it.
