### ISSUE TITLE
Hoverinfo doesn't show for some traces if legendgroup on same row as others

### ISSUE THREAD

**Issue by Braintelligence** [plotly/plotly.js#6777]
I'm currently in a hurry so sadly not able to create a reproducible code example, but I found a bug.

I use `x+y+name` for `hoverinfo` and `y unified` for hovermode.

I have a graph with horizontal bars and horizontal scatterplots each in their respective offsetgroup. The bars are in their own legendgroup, then some scatterplots have their own legendgroup and then there's a third legendgroup with some scatterplots.

If the third legendgroup is not in its own row, the hoverinfo is incomplete for many traces. It works, though, if the legendgrouptitles get long enough so that the third legendgroup has to go into the next row of the legend . It doesn't matter if the legendgrouptitles of the first two legendgroups or the third legendgrouptitle gets long enough to achieve this; as soon as the third legendgroup is in the same row as the rest, hoverinfo doesn't work for it and some other traces. If it goes down into its own row it works.

See these screenshots:

Third legendgroup in its own row, hoverinfo works:
![image](https://github.com/plotly/plotly.js/assets/6761196/ff7a7227-50fd-40ac-b43d-d3e7a4c76e84)

Third legendgroup due to shorter legendgrouptitle (only thing I changed) in same row, hoverinfo doesn't work for it:
![image](https://github.com/plotly/plotly.js/assets/6761196/67a4772d-5f35-422f-8a0d-fbafbf61bfc8)

As soon as I have more time I might try to create a reproducible example. For now I just wanted to "put this on record", because from the screenshots only this just has to clearly be a bug.

One thing that came to mind is that the trace `name`s for the first and third legendgroup are identical. But changing the names of the first legendgroup traces didn't change the outcome.

EDIT: As a workaround for now I just spam `&nbsp;` into the third legendgrouptitle to force it into its own row...

**Comment by gvwilson** [comment]
hi @Braintelligence - were you able to create a small reproducible example to share with us? If so, I'll reopen this issue and add it to our backlog. Thanks - @gvwilson
