### ISSUE TITLE
plotly-latest is stuck at v1.58.5

### ISSUE THREAD

**Issue by lswainemoore** [plotly/plotly.js#6786]
Hi--flagging that https://cdn.plot.ly/plotly-latest.js does not actually contain the latest plotly, and is stuck on v1.58.5. I can see from some internal slack communication in my organization that this has been true for at least a year-ish. I don't see any conversation about this--is it intentional?

**Comment by archmoj** [comment]
This is intentional (See https://github.com/plotly/plotly.js/releases/tag/v2.0.0#Removed). 
We now recommend our users to use specific versions and upgrade to `v2`.

**Comment by lswainemoore** [comment]
Gotcha--thanks.
