### ISSUE TITLE
wrong bar height if y values contains negative number, but the sum is postive

### ISSUE THREAD

**Issue by thinkerelwin** [plotly/plotly.js#6809]
I experienced a weird bug on a bar chart, multiple y values with the same label on the x value are accumulated, but if it contains negative values and the accumulated sum is positive, it's not starting from zero.

I've checked on different barmode options, but none helps.

Below is the attached codepen page to demonstrate this error:

https://codepen.io/thinkerElwin/pen/poGGmJJ

Current result:

giraffes: start from -6, and end at 25
orangutans: start from -15, and end at 14

Expected result:

giraffes: start from 0, and end at 19
orangutans: start from 0, and end at -1

**Comment by alexcjohnson** [comment]
I wouldn't consider this a bug, but it's certainly not helpful for your use case.

(Also: please don't use `plotly-latest` from the CDN anymore, it's stuck at the end of v1.x. Use exact versions ie `plotly-2.27.1.min.js` in version 2.)

Plotly bar charts don't natively do any aggregation. We try to display all the data you give us, so if you ask for bars of size 20, -6, and 5 we'll draw bars with heights 20, -6, and 5. This is all well and good when all of these heights are positive, but it gets ambiguous when some are negative. Here's a fork of your codepen with v2.27.1 and making the individual bars semitransparent so you can see them when they overlap: https://codepen.io/alexcjohnson/pen/ZEwPPVR?editors=0010 Here's what the different barmodes do:
- `overlay` - starts each bar separately from the origin, draws them all on top of each other
- `relative` - positive bars stack above the origin, negative bars stack below
- `group` - for one trace, same as `relative`; for multiple traces, sets traces side-by-side
- `stack` - each bar starts where the previous left off, so the stack will end at the overall total, but there's no guarantee that you didn't at some point go outside the range from 0 to the final sum (in fact in your examples it's unavoidable, regardless of the order you provide the data)

If you want aggregation, use a `histogram` trace with `histfunc: 'sum'` (the default is `histfunc: 'count'` which ignores the `y` data)

**Comment by thinkerelwin** [comment]
I really appreciate such a detailed explanation!

I've tried the histogram chart with histfunc: 'sum', it looks like a bar chart and has the aggregation I needed.
