### ISSUE TITLE
axis max length?

### ISSUE THREAD

**Issue by gbayarri** [plotly/plotly.js#6847]
Hi,

I'm trying to draw a heatmap plot with a yaxis length of 20 and a xaxis length of 500.000. This results in a blank plot where the z values are not drawn but present, because as you can see in the image, the hover shows the correct values:

![Captura de pantalla 2024-01-15 a les 16 38 07](https://github.com/plotly/plotly.js/assets/19928100/9d84b816-12a0-44a1-8a82-8ea8715435b7)

Is it a problem of memory? After doing some tests, I realized that the maximum xaxis lenght for drawing the plot properly is ~65k which is suspiciously close to 2^16.

I've done tests with more values than these 10M of my case, and they work, so I assume that the problem must be related with some kind of limitation of the axis length or the maximum amount of values for a single axis (z in this case, as it is a heatmap).

Any help will be welcomed.

**Comment by gvwilson** [comment]
Hi @gbayarri - I'm trying to tidy up issues that have been sitting in this repo for a while. If you can add a small reproducible example to help us with debugging this, I'd be happy to reopen it and add it to our backlog. Thanks - @gvwilson
