### ISSUE TITLE
rug plot trace not drawn at certain heights

### ISSUE THREAD

**Issue by joshua-gould** [plotly/plotly.js#685]
see http://codepen.io/anon/pen/MebMgL. Change layout.height to 200 and it will work fine.

**Comment by etpinard** [comment]
You mean on _very small heights_ ?

Not sure what the desired behaviour should be. The subplot element is very small for a plot height of `180px`.

I can only recommend setting the all margins to 0. Looks like that's enough room to display your trace: http://codepen.io/etpinard/pen/PzbrbQ

**Comment by joshua-gould** [comment]
When I make the height smaller, (e.g. 160) the plot is drawn-http://codepen.io/anon/pen/MebMgL.
