### ISSUE TITLE
Support simple subtitle parameter (like title)

### ISSUE THREAD

**Issue by mjainGH** [plotly/plotly.js#6856]
Image from Figma mock by @TonyBurbs :

![Screen Shot 2024-05-15 at 11 57 46 AM](https://github.com/plotly/plotly.js/assets/4672118/3977d756-25cd-4fa8-8b84-5af2230a72c0)

**Comment by emilykl** [comment]
**API for subtitle**

- Same API as `title`
- Add a `subtitle` property directly under `layout` with the same properties as `title`

-----

- `layout`
  - `subtitle`
    - `text`: str
    - `font`: standard font options

**Comment by archmoj** [comment]
I think it should go inside `layout.title` object instead of `layout`.
It reminds of when we added `minor` ticks in #6166.

That would also allow adding multiple titles and subtitles later on.

**Comment by archmoj** [comment]
Also it would be nice (and possibly easy) to have the subtitle option available on the cartesian axes and other places too.

**Comment by archmoj** [comment]
For a quick prototype, perhaps you could add the subtitle text to the end of title.text with a `<br>` and style it differently.

**Comment by alexcjohnson** [comment]
> I think it should go inside `layout.title` object instead of `layout`. It reminds of when we added `minor` ticks in #6166.
> 
> That would also allow adding multiple titles and subtitles later on.

I think that’s right. Also makes it clear that it inherits positioning from the title (presumably with optional overrides to at least the spacing relative to the main title) and it can inherit the main title font (but smaller, and remove bold if you bolder the main font?)

**Comment by emilykl** [comment]
@archmoj @alexcjohnson Makes sense -- do you mean something like the below?

-`layout`
  - `title`
    - `subtitle`
      - `text`
      - `font`

**Comment by archmoj** [comment]
> @archmoj @alexcjohnson Makes sense -- do you mean something like the below?
> 
> -`layout`
> 
> * `title`
>   
>   * `subtitle`
>     
>     * `text`
>     * `font`

Yes. Let's start with just that. Perhaps we rename `subtitle` to `sub` later.

**Comment by emilykl** [comment]
As suggested by @archmoj : A simple working prototype which uses HTML tags to simulate a subtitle:

https://codepen.io/emilykl-code/pen/MWdKYmr
