### ISSUE TITLE
Annotations referenced to the y-axis are in the wrong place, for log-scales

### ISSUE THREAD

**Issue by RichardNeill** [plotly/plotly.js#6880]
If I have: 
* a point at value y=3 
* an annotation at value y=3, with yref=y
then the annotation is attached to the point, as expected.

But If I then make the y-axis have type=log, then the annotation comes adrift from the point.
https://codepen.io/RichardNeill/pen/dyreyMG

What's happening is that the annotation is being drawn in linear units - it isn't truly referenced to the yaxis, because if you read across, the y-value for the annotation is 10E3, not 3.

This might be a problem to fix, given that it would be backward-incompatible - see #420.
If so, please at least consider warning about this issue at: https://plotly.com/javascript/text-and-annotations/
A suitable message might be:

 Note, for backward compatibility, annotations are drawn in linear units. So if your axis-type is log, remember to use:
 yref:y, y:Math.log10(your_y_value)

Thanks :-)

**Comment by alexcjohnson** [comment]
You're exactly right @RichardNeill - an unfortunate decision very early in the history of plotly.js 😅 

@LiamConnors thoughts on how best to warn people about this? We do already mention this in the description for x and y, but you'll only see that if you look carefully at the reference for these attributes:

https://github.com/plotly/plotly.js/blob/5272c3824170583f6e899225ba2246b68327819c/src/components/annotations/attributes.js#L366-L367

**Comment by LiamConnors** [comment]
Yeah, we could add an example to the annotations page of what that would look like with a log axis. Will add it in.

**Comment by LiamConnors** [comment]
Examples are live now at https://plotly.com/javascript/text-and-annotations/#annotations-with-log-axes
https://plotly.com/python/text-and-annotations/#text-annotations-with-log-axes
