### ISSUE TITLE
Mismatch between legend and line colors when using uppercase css colors

### ISSUE THREAD

**Issue by Coding-with-Adam** [plotly/plotly.js#6883]
Bug originally [reported on the forum](https://community.plotly.com/t/setting-line-color-with-seversl-dropdowns/82000/2?u=adamschroeder). 
When using css colors with the first letter capitalized, a line chart will show all lines as black, although the legend will adhere to the correct css colors.  

[Codepen JS code](https://codepen.io/charmingdata/pen/MWxGjqe)

![image](https://github.com/plotly/plotly.js/assets/32049495/6237c875-fe85-4df1-b822-92297585df5a)

Plotly.py code:
```
import plotly.express as px

css_colors = ['AntiqueWhite', 'Aqua', 'Aquamarine', 'Black', 'Red']
# css_colors = [color.lower() for color in css_colors]

df = px.data.gapminder()
print(df['continent'].unique())
color_discrete_map = {subject: css_colors[i] for i, subject in enumerate(sorted(df['continent'].unique()))}
fig = px.line(df, x="year", y="lifeExp", color='continent', color_discrete_map=color_discrete_map)
fig.show()
```

**Comment by depperm** [comment]
already an issue: #6685
