### ISSUE TITLE
In certain cases, a `scatter3d` trace line disappears

### ISSUE THREAD

**Issue by monfera** [plotly/plotly.js#691]
The connecting line on `scatter3d` may thin away to even zero width, depending on the angle of view. In this example, the trace has no gaps but a gap looks to be present:
![image](https://cloud.githubusercontent.com/assets/1548516/16356770/619da9f0-3ae4-11e6-9ca0-f9130fc89d9e.png)
Possible reason is this: the rendering seems to represent a line with a flat band (thin, long 2D rectangle). The WebGL renderer attempts to always transform this rectangle such that its cross-section is perpendicular to the line of sight, giving the approximate appearance of a cylindrical line. In specific angles, numerical issues may cause this transform to not work properly; maybe the 'gymbal lock' issue. In this case, a solution may be to pick another reference vector, or switch to a quaternion based rotation which is free of the gymbal lock issue. Will need to look into it to confirm.

Loosely related issue in `scatter3d`: if there's a gap in the data, but `connectgaps` is set to true, then the rotation seems to not be in effect for the point with the `null` value - the line vanishes over its length.
![image](https://cloud.githubusercontent.com/assets/1548516/16357268/0077f334-3af2-11e6-8652-2b9eb7e72862.png)

**Comment by etpinard** [comment]
Fixed in https://github.com/plotly/plotly.js/pull/3163

-------

cc @archmoj make sure to close corresponding issue(s) after merging your PRs. Note you can also use 

https://help.github.com/articles/closing-issues-using-keywords/

to tell Github to close issue automatically.
