### ISSUE TITLE
`scattergl` line plots no longer working after upgrading to 2.29.1

### ISSUE THREAD

**Issue by mofojed** [plotly/plotly.js#6911]
It seems plotly.js 2.29.1 has an incorrect dependency in regl-line2d 3.1.2, causing GL shaders to not work in custom bundles.
v2.29.1 of plotly.js depends on "^3.1.2" of regl-line2d: https://github.com/plotly/plotly.js/blob/3c922716626ca33636d6569b2422d5f4986d1b6e/package.json#L113 However, there are changes made after 3.1.2 to inline shaders: https://github.com/gl-vis/regl-line2d/commit/c3fefe2268b8d24fa4bb90cb374af90791ecf943 v2.29.1 expects these inline shaders, and should in fact depend on ^3.1.3. instead.

With `regl-line2d@3.1.2` installed, which happens if you're upgrading an existing application or you explicitly set it in your `package.json`, GL line plots will not render, only the points will:
![image](https://github.com/plotly/plotly.js/assets/4505624/dca69614-b4b8-49e3-b1b9-33c5c6a8f79b)

The following warnings appear in the browser logs:
```
WebGL: INVALID_OPERATION: drawArraysInstancedANGLE: no valid shader program in use
draw @ VM1313:344
REGLCommand @ plotly__js_lib_scattergl__js.js?v=eff02af6:16527
(anonymous) @ plotly__js_lib_scattergl__js.js?v=eff02af6:7083
Line2D.draw @ plotly__js_lib_scattergl__js.js?v=eff02af6:7067
draw @ plotly__js_lib_scattergl__js.js?v=eff02af6:3090
exports.redrawReglTraces @ chunk-IDUVTGCQ.js?v=eff02af6:5809
exports.drawData @ chunk-IDUVTGCQ.js?v=eff02af6:5775
lib.syncOrAsync @ chunk-O3K2MKXY.js?v=eff02af6:17324
_doPlot @ plotly__js_lib_core__js.js?v=eff02af6:1521
newPlot @ plotly__js_lib_core__js.js?v=eff02af6:1648
(anonymous) @ main.js:29
Show 9 more frames
Show less
WebGL: INVALID_OPERATION: useProgram: program not valid
```

This is already fixed with https://github.com/plotly/plotly.js/commit/a809b80caf3c1eeeda6dadd37722e5453a4cdc11, but that version isn't released yet, and others may still run into this issue when upgrading to v2.29.1. Wanted to log the issue in case others run into the same problem after an upgrade. In retrospect, regl-line2d should have published 3.1.3 first, then plotly.js should have updated package.json to require `regl-line2d@^3.1.3` before releasing plotly.js v2.29.1.

To resolve the issue, you can do an `npm uninstall plotly.js` and then `npm install plotly.js`.

I've created an example repo demonstrating the issue: https://github.com/mofojed/my-plotly-app

**Comment by archmoj** [comment]
Thanks for the report. 
I was not able to replicate the problem.

By the way I'm planning to release a minor plotly.js version today which I hope that would help fix this issue on your side.
Sounds good?

**Comment by mofojed** [comment]
Yes, a minor plotly.js version will resolve the issue, thanks!

**Comment by archmoj** [comment]
This should be fixed after https://github.com/plotly/plotly.js/releases/tag/v2.30.0.
