### ISSUE TITLE
Support for making multiple selections using Box selector or Lasso selector tools in Plotly.js

### ISSUE THREAD

**Issue by juni-green** [plotly/plotly.js#698]
Hi,
Is there any way to handle multiple selections simultaneously i.e. without cancelling the previous selection? Currently, when the Box select cursor is selected (from the modebar) and box selection is applied, the previously selected part of the graph gets deselected and the box re-appears for the newly selected part. I was just wondering if we can select new data points on the graph without deselecting the previous ones.

Any help will be appreciated. 
Thanks!

**Comment by etpinard** [comment]
> Is there any way to handle multiple selections simultaneously i.e. without cancelling the previous selection

Not at the moment. 

This is a limitation of the current implementation. See PR https://github.com/plotly/plotly.js/pull/154 for more information.

That said, what you describe would be a great addition to the library.

**Comment by toothlessdragon** [comment]
This would be awesome!

A great thing to do would be to enable pressing shift+selection to add to the current selection (keeping selection without pressing the shift key working as-is).

**Comment by drcrook1** [comment]
I could really use this functionality as well.  We use plotly for annotating various charts and many need multiple annotations.

**Comment by etpinard** [comment]
cc @dfcreative @chriddyp @jackwluo

**Comment by etpinard** [comment]
@dfcreative

**Comment by etpinard** [comment]
@dfcreative

**Comment by dfcreative** [comment]
[Here](https://github.com/dfcreative/plotly.js/tree/multiselect) is work in progress:

![screen](https://user-images.githubusercontent.com/300067/27558844-7a646cda-5a8c-11e7-8c16-b287bb28c081.gif)

Things to do:

* [ ] merge polygons
* [ ] make proper shift interaction
* [ ] cover scattergl case
* [ ] add multibox selection

**Comment by etpinard** [comment]
Awesome @dfcreative :tada: 

We should also discuss what should happen to the `plotly_selected` event data during multiple selections.

I'd vote for emit a `plotly_selected` event after every selection stroke is completed and making the `points` array include points for all selected currently visible.

Thoughts?

**Comment by dfcreative** [comment]
Progress so far

![multisel](https://user-images.githubusercontent.com/300067/27838388-5b61d43a-60b8-11e7-8cea-62b3acc61450.gif)

**Comment by etpinard** [comment]
Done via @dfcreative 's https://github.com/plotly/plotly.js/pull/2140
