### ISSUE TITLE
Plotly-basic.js + table 

### ISSUE THREAD

**Issue by slang-will** [plotly/plotly.js#6986]
Hi,

We're trying to work with Plotly.js on our Salesforce org. For some security reason, full version of plotly or plotly.min is loadable as static resource but newPlot() is blocked in a lightning web component.
But, I found out that Plotly-basic.js is successful and we're now able to build scatter/pie/bar charts in LWC. The only thing that we're missing to date is the ability to build tables with plotly. Would you be kind enough to consider adding table to plotly-basic ?

Thanks for your consideration,
Best regards,
Steve

**Comment by archmoj** [comment]
Hi,
Thanks for using plotly.
Have you tried making a custom bundle?
Please see https://github.com/plotly/plotly.js/blob/master/CUSTOM_BUNDLE.md

**Comment by slang-will** [comment]
Spectacular, that's exactly what I was looking for !
Thanks a lot
