### ISSUE TITLE
Download plot as a png not working in IE from 1.13.0

### ISSUE THREAD

**Issue by fixxxr** [plotly/plotly.js#699]
From release 1.13.0 the snapshot in IE (svg) seems broken. 
tested with `type: 'surface'` and `type: 'contour'` and for the first it produces a blank svg while for the second, the snapshot seems to stop before the saving of the svg file. 

From 1.12.0 and below the snapshot for `type: 'contour'` has the same behavior as described above.

**Comment by etpinard** [comment]
Thanks for the report.

We did make some changes to our to-image code in `1.13.0` (See PR https://github.com/plotly/plotly.js/pull/604). 

Can you confirm or infirm the following:

Donwload plot with

- `type: 'surface'` does not work in IE11 with plotly.js `1.13.0` ?
- `type: 'surface'` works in IE11 with plotly.js `1.12.0` ?
- `type: 'surface'` works in IE11 with plotly.js `1.11.0` ?
- `type: 'contour'` does not work in IE11 with plotly.js `1.13.0` ?
- `type: 'contour'` does not work in IE11 with plotly.js `1.12.0` ?
- `type: 'contour'` does not work in IE11 with plotly.js `1.11.0` ?

To-image support for IE11 was introduced in 1.11.0 (see PR https://github.com/plotly/plotly.js/pull/446), so there no chance of it working in versions < `1.11.0`.

cc @timelyportfolio

**Comment by fixxxr** [comment]
in order:

1. Yes
2. Yes
3. Yes
4. Yes
5. Yes
6. Yes

Below 1.12.0 is for down to 1.11.0

Thanks

**Comment by timelyportfolio** [comment]
@fixxxr, I'll check.  Could you provide the code you are using to make your `png`?  Sorry for the troubles.

**Comment by fixxxr** [comment]
I am using the snapshot button.
Also I tested the aforementioned releases with the example posted here: [plotly.surface](https://plot.ly/javascript/3d-surface-plots/#topographical-3d-surface-plot), just to be sure that it wasn't related only to my case. I confirm that the issue is reproducible with the code posted on Plotly's page.

**Comment by timelyportfolio** [comment]
Looking into this, and I think I see the issue. I'll keep working on it and hopefully by tomorrow I will have it fixed.

**Comment by fixxxr** [comment]
@timelyportfolio, thank you very much

**Comment by fixxxr** [comment]
hi there, 
any news on this issue?

**Comment by etpinard** [comment]
From @vsabeti :

PNG toImage for IE Edge works if img.crossOrigin is set to 'Anonymous'. The tainted canvas is fixed for the Edge browser (and works with this one change), but apparently will not be fixed for IE11. https://connect.microsoft.com/IE/feedback/details/828416/cavas-todataurl-method-doesnt-work-after-draw-svg-file-to-canvas
It would be great if in a future plotlyjs release, toImage png format is allowed for Edge while still restricting IE11 and below to be svg format only.

**Comment by ravidixit** [comment]
@etpinard so does this mean that we cannot use the `toImage` method in IE 11, but will work in IE Edge for windows 10 with `crossOrigin`, please let me know if I have understood it correct. 
Also if `toImage `method is not supported for IE11 then what are the alternatives for the same.
As suggested I have tried the `toImage `method with `svg `format and it fails to render in IE 11
In my above query #1103 I have added a JSfiddle which makes use of canvas but its working in chrome and Firefox but fails in IE 11.

**Comment by alexcjohnson** [comment]
superseded by #2077 for clarity
