### ISSUE TITLE
API Documentation improvements / reorganization

### ISSUE THREAD

**Issue by brian428** [plotly/plotly.js#700]
As a developer (and occasional OSS contributor), I know that no one wants to work on documentation. It's not fun. However, having said that, I really think the Plotly.js docs need some attention. Here is some feedback to consider. (Please don't take any of this personally, I really am just trying to help here.)

- Search!: It's **really** hard to find anything in the Plotly site or the API docs.
- Better top-level and sub-level navigation: Often, I'll Google for something related to Plotly.js, get a hit on the Plotly site, go look at it, and wonder "how on earth would I have gotten here without Google, using only the navigation and links on the Plotly site?" And even if you find some useful page that way, the site/page navigation gives very little indication of where you actually are in the information space.
- Break things up: many of the really important pages take **way** too long to load (like https://plot.ly/javascript/, or worse, https://plot.ly/javascript/reference/). Having everything on one page makes going through the docs _really_ slow and painful. Consider a more standard API docs format (perhaps [JSDoc 3](https://github.com/jsdoc3/jsdoc)?), possibly using frames, so the navigation and the content can be used separately.
- In addition to site search, consider searching in the API docs themselves. Right now, I'm basically stuck using Control-F to locate anything with the current "single-monster-page" format being used.
- Finally, I really have no idea where to go to ask for help. Is there a forum or Google Group for Plotly/Plotly.js? If not, there really should be. And if so, please add a "Support" or "Forum" link in the top-level navigation.

You folks have done a pretty amazing job with Plotly.js. But the current docs make it quite difficult to understand and get a handle on the great work you've done.

**Comment by etpinard** [comment]
Thanks for feedback @brian428 :beers: 

I move the items related to our documentaion [repo](https://github.com/plotly/documentation) in https://github.com/plotly/documentation/issues/455

>  Consider a more standard API docs format (perhaps JSDoc 3?), possibly using frames, so the navigation and the content can be used separately.

That's a good idea. Most new functions have JSDoc already. I'd vote :+1: for enforcing JSDoc on all public methods. Perhaps we could run JSDoc on every deploy to plot.ly and serve it output on some plot.ly endpoint which the documentation pages could use.

> I really have no idea where to go to ask for help. Is there a forum or Google Group for Plotly/Plotly.js? If not, there really should be. And if so, please add a "Support" or "Forum" link in the top-level navigation.

You're right. It's pretty ridiculous that https://plot.ly/javascript/ has no visible link to our forum pages. I made note of that in https://github.com/plotly/documentation/issues/455 Thanks for the headsup.

Anyway, here it is: http://community.plot.ly/
