### ISSUE TITLE
how to replace the color chunk in top heatmap 

### ISSUE THREAD

**Issue by honghh2018** [plotly/plotly.js#7000]
Thanks to develop the great tools,
    I want to plot the heatmap with color bar top in heatmap like below,picture
![image](https://github.com/plotly/plotly.js/assets/41668708/10f9faee-0a66-4d46-995e-b1c14618ae67)

but i get the below picture
![image](https://github.com/plotly/plotly.js/assets/41668708/4fc356b9-9dc6-421c-b2fa-6080b4ccc75f)

even thought i relpace the  element the trace in array, it color bar like below picture 
![image](https://github.com/plotly/plotly.js/assets/41668708/52a1fc31-cd8b-4734-82c7-79538a87c781)
It distance from the body heatmap
    
    
    var z_data = [];
       for (var i = 0; i < 15; i++) { // 15行基因
           var temp_row = [];
           for (var j = 0; j < 100; j++) { // 每行100个细胞
               temp_row.push(Math.random());
           }
           z_data.push(temp_row);
       }
       var genes = Array.from({length: 15}, (_, i) => `Gene${i + 1}`);
       var cells = Array.from({length: 100}, (_, i) => `Cell${i + 1}`);

       // 分群信息，分组不均匀
       var groupAssignments = [20, 15, 25, 10, 30]; // 各组的细胞数
       var clusterColorBar = [];
       var groupColors = ['red', 'green', 'blue', 'yellow', 'purple']; // 分组颜色

       groupAssignments.forEach((count, index) => {
           clusterColorBar = clusterColorBar.concat(Array(count).fill(index + 1));
       });

       var trace = [

           {
               x: cells,
               y: ['Cluster'],
               z: [clusterColorBar.map(value => value)], // 使用实际数值
               type: 'heatmap',
               colorscale: groupColors.map((color, index) => [index / (groupColors.length), color]),
               showscale: false,
               hoverinfo: 'skip', // 禁用悬停信息
               domain: {
                   x: [0.5, 1],
                   y: [0, .5]
               },
           },
           {
               z: z_data,
               x: cells,
               y: genes,
               type: 'heatmap',
               colorscale: 'Viridis',
               // hoverinfo: 'all' // 默认显示所有信息
               domain: {
                   x: [0.5, 1],
                   y: [0, .5]
               }

           }

       ]

       // 绘制图表
       // Plotly.newPlot('heatmap', [clusterTrace,heatmapTrace], layout);
       // Plotly.newPlot('heatmap', [clusterTrace,heatmapTrace], layout);
       Plotly.newPlot('heatmap', trace);
       trace[1].domain.x=[0,1]
       trace[1].domain.y=[0,1]

any advice would be appreciated,
Best,
hanhuihong

**Comment by gvwilson** [comment]
hi @honghh2018 - can you please post this in the community forum? You're more likely to get timely tech support there. Thanks - @gvwilson

**Comment by honghh2018** [comment]
您好！已经收到邮件，祝好！                                    洪汉辉
