### ISSUE TITLE
Plotly modebar buttons malformed

### ISSUE THREAD

**Issue by brjewell** [plotly/plotly.js#703]
Hi,

I have a web application where I open a new window using JS, 

    window.open (myUrl, '_blank');

to display a plotly graph.

When the graph is rendered, the modebar buttons are skewed (the buttons are large and are rendered across the entire page), as if the CSS for the modebar is not being read.

Note that this is happening in Google Chrome, and when I press F12 to display the Chrome developer Tools, and then hit F12 a second time, the modebar buttons are shown correctly.

Since F12 in Google Chrome will redraw the page, the workaround for this issue seems to be to programmatically force a redraw such that the modebar CSS takes over. However, I have not been able to get this to work. 

Note that the action of hitting F12 twice will always fix the issue and the modebar buttons are then rendered correctly.

Any ideas of how to get around this problem? I think it is likely related to the fact that I am displaying the plotly graph in a new window.

I should also mention this problem does not occur with FireFox.

I have enclosed a screenshot.

Thank you for your help.

[plotly-buttons-screenshot.docx](https://github.com/plotly/plotly.js/files/338384/plotly-buttons-screenshot.docx)

**Comment by etpinard** [comment]
Thanks for the report

Here's the screenshot in question:

![image](https://cloud.githubusercontent.com/assets/6675409/16455072/1740b9c4-3de1-11e6-910c-87ee0e58c51c.png)

This may be related to https://github.com/plotly/plotly.js/issues/702

**Comment by etpinard** [comment]
I wonder if this issue has to something to do with the way we inject style sheets into the DOM using js with [`Lib.addStyleRule`](https://github.com/plotly/plotly.js/blob/master/src/lib/index.js#L395-L412).

**Comment by brjewell** [comment]
Thank you for responding. 

 

It’s possible that there is a connection between and Issue #703. 

 

Any thoughts on how it might be resolved are appreciated.

 

==Brian Jewell

**Comment by brjewell** [comment]
I did look at the link provided.

 

I’ve not used “insertRule” or “addRule” myself. But, the code is properly checking to see if the browser environment supports them, unless for some reason they simply don’t work in Chrome(?)

 

Thanks for the information.

 

==Brian Jewell

**Comment by etpinard** [comment]
merged with https://github.com/plotly/plotly.js/issues/702
