### ISSUE TITLE
scatter3d: suppressing connecting lines causes WebGL warning

### ISSUE THREAD

**Issue by scottwittenburg** [plotly/plotly.js#704]
I am using plotly.js version 1.12.0.  In my browser console, I do:

``` javascript
container = document.querySelector('.plotly-container')
Plotly.newPlot(container, [{x: [1, 2, 3], y: [3, 2, 1], z: [2, 3, 1], type: 'scatter3d'}])
```

and everything is fine.  If I don't want the lines between the points, I do:

``` javascript
Plotly.newPlot(container, [{x: [1, 2, 3], y: [3, 2, 1], z: [2, 3, 1], type: 'scatter3d', mode:'markers+text'}])
```

and then, while I no longer see the lines between the points, I get many of this warning:

```
[.CommandBufferContext.Offscreen-MainThread-0x3969ca4b4a00]RENDER WARNING: Render count or primcount is 0.
```

I'm using Ubuntu 14.04 and the above warnings only seem to appear in Chrome (for me, Version 51.0.2704.106 (64-bit)).  When in Firefox, I do not see the warnings.

Thank you!

**Comment by etpinard** [comment]
Thanks for report. I can confirm this issue on Chrome 51 and Ubuntu 16.04. 

The plot still renders fine to my eyes. @scottwittenburg can you confirm?

**Comment by scottwittenburg** [comment]
That is correct.  The plot renders fine, and the only issue is the console warnings.

**Comment by etpinard** [comment]
cc @dfcreative

**Comment by etpinard** [comment]
Oh actually, I was able to replicate the same warning message with:

```js
Plotly.newPlot(gd, [{
  type: 'scatter3d',
  mode: 'text',
  x: [1,2,3],
  y: [2,1,2],
  z: [2,1,3]
}])
```

I'm thinking this has to do with setting `mode: 'text'` when `text` is empty.

**Comment by etpinard** [comment]
Fixed in https://github.com/plotly/plotly.js/pull/3171
