### ISSUE TITLE
Scattergl slower than scatter with many points

### ISSUE THREAD

**Issue by pdsatter** [plotly/plotly.js#7065]
Scattergl is having bad performance and interactivity with 100,000 points. However when using type "scatter" it works perfectly fine. It seems like this issue only happens when one line has more than 100,000 points. If multiple lines have about 85,000 points then it still works fine.

Here is an online sandbox showing the bug.
https://stackblitz.com/edit/react-ts-eb5bgt?file=index.tsx

**Comment by archmoj** [comment]
Addressed in #7301.
