### ISSUE TITLE
`zorder` on overlayed subplots case of multiple traces in each subplot

### ISSUE THREAD

**Issue by stephprobst** [plotly/plotly.js#7070]
The in plotly.js 2.34.0 introduced zorder property does not work as expected. The following chart demonstrates the issue:

https://codepen.io/Djeramon/pen/VwJPXGr

![image](https://github.com/user-attachments/assets/9d1cf9c4-2267-4d82-9aff-b705e46abb5b)

The orange line is drawn on top, but it should be drawn behind the green and red line.

The issue seems to be related to the traces being linked to different y-axes. Once the axes are being linked to the same y-axis, the bug disappears.

**Comment by archmoj** [comment]
Thanks for the report. This is a bug.

**Comment by archmoj** [comment]
@stephprobst in your codepen the third trace has a name saying the zorder is 3; but its zorder is actually is set to 2.
Since this is confusing, I thought you may want to adjust that?

**Comment by stephprobst** [comment]
@archmoj : You're right. Thanks. I corrected it.

**Comment by archmoj** [comment]
Thanks @stephprobst.
It looks like if you drop `barmode: 'stack'` or use `barmode: 'overlay' or `barmode: 'group'`; the issue is still present.
Please confirm.

**Comment by stephprobst** [comment]
@archmoj : Yes, I can confirm. The problem doesn't seem to be related to the used barmode.

**Comment by stephprobst** [comment]
@archmoj : The problem sits with the assignment of the bars to the y-axes. If you remove all assignment information, the bug appears. In your current codepen version:

```
  {
   "type": "bar",
   "x": ["A", "B", "C", "D"],
   "y": [1, 2, 3, 4],
   "zorder": 1
  },
  {
   "type": "bar",
   "width": 0.6,
   "x": ["A", "B", "C", "D"],
   "y": [2, 3, 4, 1],
   "zorder": 2
  },
```

**Comment by stephprobst** [comment]
@archmoj : Yes, I can confirm, that the bug is present in the given codepen and that the root cause seems to be related to the assignment to the y-axes.

**Comment by archmoj** [comment]
Thanks @stephprobst.
Now please update the issue title and description to better describe it.

**Comment by stephprobst** [comment]
@archmoj : Done.

**Comment by archmoj** [comment]
@stephprobst I edited the title.
 Also FYI [this codepen](https://codepen.io/MojtabaSamimi/pen/rNEoNpw) with two traces in each overlayed subplot renders as expected. Please confirm.
 
BTW it appears in the original issue the bug appears when lower subplot has more traces in it.
That could likely be related to the way the z index is added to declare subplot on one another.
Investigating...

**Comment by stephprobst** [comment]
@archmoj Yes, I confirm, that the linked codepen works as expected.

Thanks for your work on this.
