### ISSUE TITLE
Attributions display twice on `mapbox` 

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#7075]
![Screenshot from 2024-08-08 10-58-56](https://github.com/user-attachments/assets/53f9b87b-1e5d-48b4-8b1b-b4f3f70af634)

The image tests are failing on master after merging #7060:  https://app.circleci.com/pipelines/github/plotly/plotly.js/10950/workflows/2c1cc796-b8cd-47b9-adcc-328d0ae4a9f2/jobs/242299/parallel-runs/0/steps/0-102

This is not related to #7060 itself since if I checkout `v2.34.0`
```sh
git checkout tags/v2.34.0 && npm ci && npm start
```
then
```sh
npm run baseline mapbox_0
```
Gives me the baseline with duplicate source attribution!

I suspect this was related to the order of rendering on CI but somehow wasn't noticed before.

**Comment by archmoj** [comment]
Re-running CircleCi tests on the same commit also confirms that something is changed on the `mapbox` side in the past two weeks that caused these tests to start failing.

![Screenshot from 2024-08-08 12-30-40](https://github.com/user-attachments/assets/92f3404c-53f8-4d17-be16-491b34262e2d)

**Comment by archmoj** [comment]
Strangely enough if I call 
```sh
python3 test/image/make_baseline.py mapbox_0
``` 
It works just fine.
But  
```sh
npm run baseline mapbox_0
```
fails although it calls the same python script using node.js!

:exploding_head:

**Comment by archmoj** [comment]
@birkskyum this issue doesn't seem related to your PR; although it start showing up after we merged the `maplibre` PR.

Anyway I was not able to figure out what causes this.
Please note that in addition to the image test, there is one jasmine test is failing which might be easier for debugging.

**Comment by birkskyum** [comment]
The mapbox_scattercluster also appear to have issues with the little attribution icon in the lower right

<img width="477" alt="Screenshot 2024-08-09 at 12 40 53" src="https://github.com/user-attachments/assets/d3ba8945-0da6-470f-bd5e-f700206a139d">

<img width="500" alt="Screenshot 2024-08-09 at 12 42 06" src="https://github.com/user-attachments/assets/fd1db286-41ac-41af-b5cf-b372ccd4bb6c">


compared to maplibre
<img width="79" alt="Screenshot 2024-08-09 at 12 41 59" src="https://github.com/user-attachments/assets/82ca56e0-4ee8-4cd2-a16f-f963a08c9c68">
<img width="530" alt="Screenshot 2024-08-09 at 12 42 33" src="https://github.com/user-attachments/assets/a339980b-d2e0-491a-8ee3-b900cad74e22">

**Comment by archmoj** [comment]
> Re-running CircleCi tests on the same commit also confirms that something is changed on the `mapbox` side in the past two weeks that caused these tests to start failing.
> 
> ![Screenshot from 2024-08-08 12-30-40](https://private-user-images.githubusercontent.com/33888540/356305380-92f3404c-53f8-4d17-be16-491b34262e2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMDUzNjgsIm5iZiI6MTcyMzIwNTA2OCwicGF0aCI6Ii8zMzg4ODU0MC8zNTYzMDUzODAtOTJmMzQwNGMtNTNmOC00ZDE3LWJlMTYtNDkxYjM0MjYyZTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDEyMDQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyNjVhZTA4YTA2MmMzNDg3YjYyN2NmODUzYzE0ZDI5OGMzMmE5OTJhNzJmYzA1YTVkMTVmZjhjZTI1MzE2N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yoOWVClZS4j0x3oe1M5Fu41SmelHpRpiyRDrS6bEsOw)

@birkskyum Yes the same commit before merging maplibre PR passed the tests. 
But then few days later it start failing!!

**Comment by birkskyum** [comment]
The issues also persist in the existing builds, like the examples: https://plotly.com/python/mapbox-layers/

**Comment by archmoj** [comment]
> The issues are also present in the existing builds, like the examples: https://plotly.com/python/mapbox-layers/

Could you send a screenshot?
I don't see duplicates there.

**Comment by birkskyum** [comment]
<img width="261" alt="Screenshot 2024-08-09 at 16 04 26" src="https://github.com/user-attachments/assets/829f12f5-ac92-4e86-9255-0a5db534ae89">
<img width="98" alt="Screenshot 2024-08-09 at 16 04 24" src="https://github.com/user-attachments/assets/a249931d-b3af-4bc6-bb98-710e9b52b3c0">
<img width="998" alt="Screenshot 2024-08-09 at 16 04 41" src="https://github.com/user-attachments/assets/e488d2de-e459-4f07-bf04-4a45a3c66c46">

**Comment by archmoj** [comment]
@birkskyum That looks like a different bug. No?

**Comment by birkskyum** [comment]
@archmoj , yes, likely separate. I made a ticket for that [here](https://github.com/plotly/plotly.js/issues/7082)
