### ISSUE TITLE
maplibre attributions are expanded by default

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#7076]
When comparing attributions displayed on a `scattermap` with a `scattermapbox` on an interactive graph, the `maplibre` versions display "expanded" attributions by default.

**Comment by birkskyum** [comment]
@archmoj PR here:
- https://github.com/maplibre/maplibre-gl-js/pull/4526

**Comment by birkskyum** [comment]
I'm getting the impression that it's safest legally to have the attribution open initially, and have it go away either by clicking the toggle or interacting with the map. Whether or not it is allowed to collapsed the attribution by default depend on the license of the style in question, which would require of a plotly.js user to inspect the license of a certain style and then opt-out of the hide-by-default behaviour suggested in this ticket.

**Comment by archmoj** [comment]
@ndrezn Could we close this ticket?

**Comment by ndrezn** [comment]
Yes, let's close this ticket. Happy to leave behaviour as-is!
