### ISSUE TITLE
Plotting bars: 'bargap: 0' removes first bar

### ISSUE THREAD

**Issue by elv1s42** [plotly/plotly.js#708]
When using layout option 'bargap: 0' first bar disappears.
Please take a look at this example: https://jsfiddle.net/57b7stne/1/
I am plotting the same trace with two different layouts, first one works fine ('bargap: 0.01'), the second one works wrong ('bargap: 0', first bar disappears)

**Comment by elv1s42** [comment]
With 'histogram' trace type everithing works fine

**Comment by etpinard** [comment]
Thanks very much for the report.

This bug is in fact a regression from `v1.2.0`. 

- working version with `v1.2.0` : https://jsfiddle.net/57b7stne/3/
- git compare: https://github.com/plotly/plotly.js/compare/v1.2.0...v1.3.0

**Comment by etpinard** [comment]
Ok. `bargap: 0` actually spits out an error:

![image](https://cloud.githubusercontent.com/assets/6675409/16492611/63bfdd82-3eb0-11e6-9f44-17172c9eaa9f.png)

On it,
