### ISSUE TITLE
如何禁止右键缩放事件（How do I disable right-click zooming events）

### ISSUE THREAD

**Issue by MYangGit** [plotly/plotly.js#7084]
大家好，请问如何禁用右键缩放事件
问题：在绘制折线后，右键点击区域会居中放大显示，这和我自定义的右键菜单冲突，目前网上没有找到解决方案，这好像是一个底层问题。

Hello everyone, how do I disable right-click zooming events
Problem: After drawing the polyline, the right click area will be centered and enlarged, which conflicts with my custom right click menu, no solution has been found online, which seems to be a low-level problem.

你可以随便找一个示例右键点击复现
You can find an example and right-click it again

例如
example
https://plotly.com/javascript/error-bars/

**Comment by gvwilson** [comment]
Hi - we are tidying up issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. For tech support and "how-to" questions, please post in our community forum https://community.plotly.com/. Thank you - @gvwilson
