### ISSUE TITLE
Problem saving png when `map.style` is set to 'satellite-streets'

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#7091]
I noticed when setting `map.style` to *'satellite-streets'* [here](https://github.com/plotly/plotly.js/blob/34568d53ef1f2276bd75acbb2328b04bc43e77d1/test/image/mocks/map_predefined-styles2.json#L151) the PNG download is not working.

@birkskyum This is blocking the RC release; wondering if you could possibly help fix it?

**Comment by birkskyum** [comment]
When i run the `npm run start` its alright, as shown. When do you experience the issue? When executing the render test?

Which png are we talking about?

<img width="923" alt="Screenshot 2024-08-13 at 10 09 42" src="https://github.com/user-attachments/assets/3c7c8f09-58bc-430a-b755-fe699d013a72">

**Comment by archmoj** [comment]
Yes if you submit a PR with the change you made to that test by replacing the white background you will notice it.
Also if you hover over the modebar which is located on top right of the graph you get an error in the console.

**Comment by birkskyum** [comment]
I'm aware the baseline should be updated, but when I try to push the commit I get a:

```sh
➜ git push
Enumerating objects: 11, done.
Counting objects: 100% (11/11), done.
Delta compression using up to 10 threads
Compressing objects: 100% (6/6), done.
error: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400
send-pack: unexpected disconnect while reading sideband packet
Writing objects: 100% (6/6), 2.44 MiB | 6.14 MiB/s, done.
Total 6 (delta 4), reused 0 (delta 0), pack-reused 0
fatal: the remote end hung up unexpectedly
Everything up-to-date
```

**Comment by birkskyum** [comment]
Fantastic, so the RC is unblocked for now again 🎉 Let me know if anything else comes up
