### ISSUE TITLE
Some WebGL `jasmine` tests start failing with Chrome 128 on `master` and other branches

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#7126]
That's the source of problem we (cc: @birkskyum) noticed in https://github.com/plotly/plotly.js/pull/6909#issuecomment-2302947669.

Success yesterday:
https://app.circleci.com/pipelines/github/plotly/plotly.js/11164/workflows/627584e0-5d94-4566-acd6-79a85c7f66cf/jobs/246982

Fail today:
https://app.circleci.com/pipelines/github/plotly/plotly.js/11164/workflows/4411cbea-a676-48f4-a4e4-7fe4a388659a/jobs/247723

We should possibly pin down the version of Chrome in jasmine tests to have more robust/isolated testing environment.

**Comment by birkskyum** [comment]
I quick local repro of this is to run `npm run regl-codegen` because it touches those areas of the code.
