### ISSUE TITLE
Plotly tries to access maplibre-gl.css

### ISSUE THREAD

**Issue by secretwpn** [plotly/plotly.js#7139]
Hi!

It looks like starting from `2.35.0 ` Plotly tries to access `maplibre-gl.css` - in my case - via `https://unpkg.com/maplibre-gl@4.6.0/dist/maplibre-gl.css`

I am not using any `map` traces in my app - just `scattergl` - so I did not expect to be affected by migration to maplibre. To make matters worse my app is running in offline environment and thus requests to `upkg.com` are failing, leaving console in red.

Should I add some maplibre related stylesheets or bits of configuration to my app manually, or will this be ironed out in future versions?

Thanks!

**Comment by archmoj** [comment]
@birkskyum Would you please address this issue in a PR?

**Comment by rbell517** [comment]
I am also getting console errors from our CSP policy with the `strict` dist from this maplibre CSS file. I set `style-src: 'self' 'unsafe-inline'` in my CSP header. It looks like the associated PR #7140 will address this if anyone else has the same problem.
