### ISSUE TITLE
Is there a way to vary the thickness of a layer in sunburst diagram in plotly

### ISSUE THREAD

**Issue by mmszhezhi** [plotly/plotly.js#7168]
[Is there a way to vary the thickness of a layer in sunburst diagram ?

**Comment by gvwilson** [comment]
Hi - we are tidying up issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. For tech support and "how-to" questions, please post in our community forum https://community.plotly.com/. Thank you - @gvwilson
