### ISSUE TITLE
Test dashboard search doesn't work

### ISSUE THREAD

**Issue by marthacryan** [plotly/plotly.js#7172]
Steps to reproduce:
* clone plotly.js repo (if you already have it cloned, do a git clean)
* `npm i`
* `npm start`
* The mock search doesn't work

This is due to the esbuild changes - #6909. That PR removed the generation of the `build/test_dashboard-bundle.js` file, which is essential to using the test dashboard. 

This wasn't caught when testing that PR (or as we've been continuing development) because the file remained locally, but if you clone the repo, the test dashboard doesn't work anymore.

**Comment by emilykl** [comment]
Thanks for opening this issue Martha! I ran into this but hadn't gotten around to investigating yet.

The individual mocks can be accessed by typing in the URL directly, but the search is broken.
