### ISSUE TITLE
fixedrange with zoom and pan

### ISSUE THREAD

**Issue by cherkashinda** [plotly/plotly.js#7173]
Can I set a fixed date range without being able to drag the graph beyond that range, but still have zoom and pan work? For example Amcharts5 allows this behavior.

**Comment by gvwilson** [comment]
Hi - we are tidying up issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. For tech support and "how-to" questions, please post in our community forum https://community.plotly.com/. Thank you - @gvwilson
