### ISSUE TITLE
Custom geo scope

### ISSUE THREAD

**Issue by Mike3010** [plotly/plotly.js#719]
In the API there are just a handful of available scopes which include 
- world, usa, europe, asia, africa, north america
(https://plot.ly/javascript/reference/#layout-geo-scope)

My main issue is, that I need a map of Europe with Turkey included, which is missing in the Europe scope.

I also would like to have a map of all of America, not just North America.

Are there any ways to achieve this? 
And if you develop the thought further, are there any ways to define own - custom - scopes for the maps?

I would appreciate your help!

**Comment by etpinard** [comment]
Adding more geo scopes isn't in our short term plans.

> My main issue is, that I need a map of Europe with Turkey included, which is missing in the Europe scope.

To do so, I'd recommend using the world (the default) combined with custom `lonaxis` and `lataxis` ranges. See example here: http://codepen.io/etpinard/pen/XKamdk

**Comment by etpinard** [comment]
Subsequent discussion(s) on this topic should be done on http://community.plot.ly/

**Comment by Mike3010** [comment]
Ok, thank you for the information.

I just got one more question. Can you tell me where the scopes are originally defined? Do they come from d3?

**Comment by etpinard** [comment]
@Mike3010 

plotly.js uses the scoped topojson files made in [`sane-topojson`](https://github.com/etpinard/sane-topojson) and the per-scope defaults are set [here](https://github.com/plotly/plotly.js/blob/46bbbaebfd70ed28196df9c4993a1ded5292bebf/src/plots/geo/constants.js#L62-L106). I hope this helps.

**Comment by spideep** [comment]
Is it possible to use a custom *topojson* from a custom location?

**Comment by spideep** [comment]
How can I include PRI inside USA map and place it in bottom right (similar to Alaska )?
