### ISSUE TITLE
drop deprecated opacity attribute of errorbars in v3

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#7197]
https://github.com/plotly/plotly.js/blob/206d117e01a79ff63b5a8f5f76d97e2b095e8ac5/src/components/errorbars/attributes.js#L125-L134

**Comment by RohitMangale** [comment]
I’d like to take on the deprecation of the opacity attribute in error bars. I’m still learning and may need some assistance, but I’ll do my best. Could you please assign this issue to me?

**Comment by emilykl** [comment]
Hi @RohitMangale , thanks for your interest in Plotly.js!

We're assigning this issue internally as we're moving quickly towards the next release, but we would welcome your contribution to another open issue. Feel free to take a look at [the issues tagged "good first issue"](https://github.com/plotly/plotly.js/labels/good%20first%20issue) as a starting place!
