### ISSUE TITLE
Change the thickness of the spike line to -2 to remove the shadow:

### ISSUE THREAD

**Issue by Fanerk1ken** [plotly/plotly.js#7220]
Hi everyone, how can I then increase the width of this spike? Or is it already possible to remove the white border from the spike?

_Originally posted by @dmfst in https://github.com/plotly/plotly.js/issues/3042#issuecomment-944863538_

**Comment by gvwilson** [comment]
Hi - we are tidying up issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. For tech support and "how-to" questions, please post in our community forum https://community.plotly.com/. Thank you - @gvwilson
