### ISSUE TITLE
Boxplot points not drawn when data has no whiskers and jitter is not 0

### ISSUE THREAD

**Issue by imre-v** [plotly/plotly.js#725]
When the data to be plotted has such a distribution that there are no whiskers to be drawn, plotly fails to draw boxpoints if jitter is set to anything but 0. I.e. if jitter is 0, the points are drawn, but they overlap. Example at:

http://codepen.io/anon/pen/OXjgNP

**Comment by etpinard** [comment]
Thanks for the report.

This may be related to https://github.com/plotly/plotly.js/issues/574

**Comment by etpinard** [comment]
I'm not exactly how to fix this bug, but I found the problem. 

On this [line](https://github.com/plotly/plotly.js/blob/926bfd5cae9ab8bbeac1de8f9443f51cd326d697/src/traces/box/plot.js#L164), `maxJitterFactor` is zero whenever there are no whiskers and a `jitter: 0`.

**Comment by etpinard** [comment]
@alexcjohnson do you have an opinion on this one?

**Comment by alexcjohnson** [comment]
Oh man, that's pathological... but should be a quick fix.
