### ISSUE TITLE
HTML/Svg Content over treemap boxes

### ISSUE THREAD

**Issue by HolyOne** [plotly/plotly.js#7267]
Hello, I am trying to add responsive html/svg contents to treemap boxes. Like a background picture and a title+link

It does not seem possible with plotly. so I tried css approach but there is no way to select the  .slice.cursor-pointer  or the underlying surface because they dont have the data-id s associated with the underlying data.

Can you add some functionality to add id's to them so we can style with css?
Or can you provide a way to add html content on them?

**Comment by HolyOne** [comment]
I also tried to add some customdata, it either dont work or the documentation is missing on how to grab those custom data. I mean I expected customdata to add data-something to the html tags of boxes

**Comment by gvwilson** [comment]
Hi - we are tidying up issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. For tech support and "how-to" questions, please post in our community forum https://community.plotly.com/. Thank you - @gvwilson
