### ISSUE TITLE
How to dynamically configure coordinates x and y for a multi pie chart?

### ISSUE THREAD

**Issue by ccworld1000** [plotly/plotly.js#7284]
How to dynamically configure coordinates x and y for a multi pie chart?

How to dynamically configure coordinates x and y for multiple pie chart lists instead of manually configuring them.
As shown in the figure below, multiple puzzle texts are re pasted together.
![Image](https://github.com/user-attachments/assets/541dc9bd-f370-4226-a6a0-396b567842ae)

Since the number of pie charts here is dynamically changing and cannot be manually set, I expect automatic dynamic configuration based on each pie chart.

**Comment by gvwilson** [comment]
Hi - we are tidying up issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. For tech support and "how-to" questions, please post in our community forum https://community.plotly.com/. Thank you - @gvwilson
