### ISSUE TITLE
node label links not working html

### ISSUE THREAD

**Issue by humtn** [plotly/plotly.js#7321]
Hi all,

I am doing a sankey plot and I'd like each of my nodes to have a label that can be clickable and redirects to some link.

```
fig = go.Figure( 
        data=[
            go.Sankey(
                arrangement='fixed',
                node=dict(label=labels, color=label_colors),
                link=dict(
                    source=links["source"],
                    target=links["target"],
                    value=links["value"],
                    color=links["link_c"],
                ),
            )
        ]
    )
```

However, when exporting the plotly file to html, the link tag appears but the href doesnt, but when further inspecting it appears in "data-unformatted" part of the code below: 

```<text class="node-label" style="cursor: default; font-family: Helvetica; font-size: 12px; fill: rgb(42, 63, 95); fill-opacity: 1; white-space: pre; pointer-events: all; text-shadow: white 1px 1px 1px, white -1px -1px 1px, white 1px -1px 1px, white -1px 1px 1px;" data-notex="1" data-unformatted="<a href='google.com'>test</a>" data-math="N" x="0" y="0" text-anchor="start" transform="translate(23.25,4.449999999999999)"><a style="cursor:pointer">test</a></text>``` 

Is there any way I can get this to work (I'd want `<a href='google.com'>test</a>` instead of the `<a style="cursor:pointer">test</a>`)

Thanks!

**Comment by gvwilson** [comment]
closed in favor of https://github.com/plotly/plotly.py/issues/4947
