### ISSUE TITLE
Is there an example on how to update the points in a linechart for ticking data?

### ISSUE THREAD

**Issue by darthninja1** [plotly/plotly.js#734]
If I update the json data object, is there a way to add the new points on a chart without redrawing the entire chart/series?

Something along the lines of ... http://www.highcharts.com/stock/demo/dynamic-update

**Comment by etpinard** [comment]
You might want to try `Plotly.extendTraces`. Here's an example: http://codepen.io/etpinard/pen/qZzyXp

Moreover, I'd recommend taking a look at [forums](http://community.plot.ly/) for questions of likes in the future. Thanks.
