### ISSUE TITLE
Custom Icons Not Rendering in Modebar

### ISSUE THREAD

**Issue by mcneela** [plotly/plotly.js#739]
I'm trying to create my own icons for use with my Plotly project, but the SVG does not appear to render in the mode bar. After running the following code, a button is indeed generated as there is a blank location in the mode bar which I can click on to activate the button's "onclick" method. That said, there is no actual icon present. I think this might have to do with the way in which the SVG path argument is formatted.

```
Icons = {
	'display': {
        'width': 512,
        'path': 'M45.297,21.946l9.656-5.517L27.477,0.825L0,16.429l9.656,5.517L0,27.429l9.656,5.517L0,38.429l27.477,15.698l27.476-15.698  l-9.656-5.483l9.656-5.517L45.297,21.946z M27.477,3.125l23.435,13.309l-23.435,13.39L4.041,16.434L27.477,3.125z M11.675,23.099  l15.802,9.028l15.802-9.028l7.633,4.335l-23.435,13.39L4.041,27.434L11.675,23.099z M50.912,38.434l-23.435,13.39L4.041,38.434  l7.634-4.335l15.802,9.028l15.802-9.028L50.912,38.434z',
	 	'ascent': 850,
        'descent': -150,
    }
};

displayButton = {
	name: 'Toggle Display',
	title: 'Toggle the display of the currently selected items',
	icon: Icons.display,
	click: function() {
		myLayer.toggleDisplay();
	}
};

Plotly.newPlot(graph, [plotTrace], {title: "Is this button here?"}, {modeBarButtonsToAdd: [displayButton]});
```

For reference, here is a screenshot of the output

![missingbutton](https://cloud.githubusercontent.com/assets/10649764/16773569/45108286-480d-11e6-81f3-1e91bb2ae72f.png)

**Comment by etpinard** [comment]
Thanks for writing in.

I'm not sure where the `Icons` object in your snippet comes from.

You may want to look at https://gist.github.com/etpinard/a282e5baff0ea19924def83e338aceda first.

**Comment by mcneela** [comment]
Hi @etpinard 

The width and path attributes of the icons object comes from an SVG image that I downloaded. I copied the ascent and descent attributes as well as the overall object description from here: [](https://github.com/plotly/plotly.js/blob/master/build/ploticon.js)

so as to be conformant with the proto.createIcon function in this file: [](https://github.com/plotly/plotly.js/blob/e03e9e0bd7ea3a6bed3b32bd784276e8e9eb70f1/src/components/modebar/index.js )

**Comment by mcneela** [comment]
In your gist, it looks like the SVG file has to be included with the Plotly source. Is this correct? I'm trying to avoid this as I'm distributing my code as part of a library and would like to avoid bundling a forked version of Plotly along with it. I am also not using NodeJS.

**Comment by etpinard** [comment]
> In your gist, it looks like the SVG file has to be included with the Plotly source. Is this correct?

No, you're right, You don't have to include the icon in Plotly source. Here's a working example: http://codepen.io/etpinard/pen/YWEdpo

----

Looks like there's an issue with the icon `path` you're using. Replacing the icon definition of the codepen referenced :arrow_double_up: with yours in http://codepen.io/etpinard/pen/RRjEpw I'm getting:

![image](https://cloud.githubusercontent.com/assets/6675409/16808390/5535409c-48ea-11e6-82d6-341ba51ea96f.png)

explaining why your icon does not show up on your graph.

I'd recommend using our community [forums](http://community.plot.ly/) if you any other questions while trying to debug your icon path.

**Comment by mcneela** [comment]
Thanks for your help!
