### ISSUE TITLE
Click event on "scattergl" doesn't work

### ISSUE THREAD

**Issue by ifll** [plotly/plotly.js#743]
The "plotly_click" event does not trigger when I click a point on a "scattergl" plot.

Does anyone know if it is due to a bug or if it will be implemented soon? I really need this feature as I am plotting a lot of points (over 50k) and I can't use the "scatter" type as it is quite laggy and reduces the performance of the whole page...

Thanks a lot!

**Comment by etpinard** [comment]
Part of the known gl2d limitations https://github.com/plotly/plotly.js/issues/130

Please review that list before opening new issues. Thanks :beers:

**Comment by ifll** [comment]
Any idea when the click option will be available?

Thank you very much!

**Comment by etpinard** [comment]
Maybe @dfcreative would be interested in this issue?

**Comment by etpinard** [comment]
for reference PR https://github.com/plotly/plotly.js/pull/240 added `plotly_click` and `plotly_hover` to gl3d plots.

**Comment by etpinard** [comment]
done in https://github.com/plotly/plotly.js/pull/994
