### ISSUE TITLE
Malformed hovertext in IE11

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#746]
I don't have IE11, but this was reported in https://github.com/ropensci/plotly/issues/636

http://codepen.io/cpsievert/pen/wWpzzr

In IE11:

![image](https://camo.githubusercontent.com/c038af84e05619da3f01ed5c3600a76ef200ac81/687474703a2f2f692e737461636b2e696d6775722e636f6d2f57493669462e706e67)

**Comment by rreusser** [comment]
Everyone is probably good on the IE-debugging front, but just FYI, useful resources:

- [free IE virtual machines from MS](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/)
- http://browserstack.com
