### ISSUE TITLE
Plotly restyle doesnt work properly!

### ISSUE THREAD

**Issue by Rudresh-Ajgaonkar** [plotly/plotly.js#748]
hey i think this is a probable issue.

When i try to restyle the plot, the plot legend shows only 1 color

Here is the codepen. 
http://codepen.io/rudi8292/pen/RRxBAQ

if i click on "Click here for update", the data points get a white colored circle around them. 

Thanks!

**Comment by rreusser** [comment]
Can you clarify what you expect? The syntax you've used assigns the array `[1, 2, 3, 4, 5]` to *each trace*. If you wanted to assign a point to each trace respectively, then you could use:

```javascript
  var update = {
          x : [[1],[2],[3],[4],[5]],
          y : [[1],[2],[3],[4],[5]],
          z : [[1],[2],[3],[4],[5]],
          size :[[12],[13],[14],[15],[16]],
          'marker.color' : [["#001"],["#005"],["#0f0"],["#f00"],["#00f"]],
           text : "size"
      }
       Plotly.restyle('myDiv', update, [0,1,2,3,4]);
```

**Comment by Rudresh-Ajgaonkar** [comment]
Extremely Sorry for raising this as issue ! It works as it should. Yes, i wanted to send data to respective traces.
Really sorry for the false alarm

**Comment by rreusser** [comment]
No prob! I did exactly the same thing a few different ways before getting the update pattern figured out. 👍🏼
