### ISSUE TITLE
Pie charts don't always seem to fit labels to a constrained space

### ISSUE THREAD

**Issue by tlrdstd** [plotly/plotly.js#75]
Maybe it's just me, but I keep ending up with pie chart labels that look like this: http://codepen.io/tlrdstd/pen/QyWybK

![image](https://cloud.githubusercontent.com/assets/194300/11580670/9a700422-9a07-11e5-8927-3f24562b0d32.png)

It happens when I assign a fixed size to the pie chart, either by passing it in the `layout` hash, or in `style` attributes on the div. The pie chart always grows to fit the space, regardless of whether there is room to fit the labels. With a 300x300 square in this example, both the title and the text are cut off. If I increase to a 500x500 square, the title fits, but the text is still cut off because the pie chart grows to match.

Converting the square to a rectangle solves the problem, but that doesn't fit my design space.

I haven't dug into this in the code yet...after trying to solve variations on the same problem in other libraries (flot, d3pie, and uvcharts come to mind), I'm just assuming it ain't easy. d3pie does the best job of plotting labels of anything I've seen, though it too forgets to check the edges of the box.

**Comment by alexcjohnson** [comment]
We certainly could check for labels going off the edge of the plot, and shrink them to fit, that probably wouldn't be very hard.

The problem gets worse if you have several pies, their respective labels do nothing to avoid each other. That seems like a harder one to fix...

**Comment by mosteele** [comment]
This is not just you! Mine are getting cut off when embedded.
![image](https://cloud.githubusercontent.com/assets/2314995/22720022/3d7b332c-ed5d-11e6-8479-2a3cd0ce3c7a.png)

**Comment by mosteele** [comment]
FYI - I as able to fix this by adding margins, but to do it I had to give up the go.Pie() approach. What about adding margins as a parameter of the go.Pie method?

Thanks! LOVE PLOTLY! <3

**Comment by lucky6qi** [comment]
Any workaround solution for pit chart auto margin?

**Comment by phanigokaraj** [comment]
guys, any workaround for this?

**Comment by nicolaskruchten** [comment]
Related #3607

**Comment by etpinard** [comment]
Merging into (updated) https://github.com/plotly/plotly.js/issues/4223
