### ISSUE TITLE
Plotly toImage and snapshot not working for scatter3D plot

### ISSUE THREAD

**Issue by mcneela** [plotly/plotly.js#750]
I'm working with the example here: http://codepen.io/plotly/pen/PzmNXP

Running `Plotly.toImage(graph, {format: 'png', width: 200, height: 150})` gives

`[[PromiseValue]]:
TypeError: Cannot set property 'cmin' of undefined at e.exports (https://cdn.plot.ly/plotly-latest.min.js:29:1601) at e.exports (https://cdn.plot.ly/plotly-latest.min.js:43:14111) at Object.e.exports [as calc] (https://cdn.plot.ly/plotly-latest.min.js:43:28774) at h (https://cdn.plot.ly/plotly-latest.min.js:33:3912) at Object.P.plot (https://cdn.plot.ly/plotly-latest.min.js:33:18628) at https://cdn.plot.ly/plotly-latest.min.js:34:7453 at Object.n [as toImage] (https://cdn.plot.ly/plotly-latest.min.js:34:6706) at <anonymous>:1:8`

Similarly, clicking the "Download plot as png" icon in the hoverbar gives a status that says:

"Sorry, there was a problem downloading your snapshot!"

**Comment by etpinard** [comment]
Thanks for the report!

Something is up with `line.color` container.

The fix will be part of the new release.
