### ISSUE TITLE
Upgrade to mapbox-gl 0.21.0

### ISSUE THREAD

**Issue by mithrandi** [plotly/plotly.js#756]
Currently, the dependency is on `mapbox-gl^0.18.0`; unfortunately, there are some problematic transitive dependencies of this version, resulting in a `UNMET PEER DEPENDENCY browserify@>= 5` problem (which causes `npm shrinkwrap` to fail) as well as a deprecation warning from `mapbox-gl-js-supported` which has been renamed to `mapbox-gl-supported`.

Would it be possible to update the mapbox-gl version?

**Comment by etpinard** [comment]
Thanks for the headsup!

I tried bumping the `mapbox-gl` version but it made one our image [test](https://github.com/plotly/plotly.js/blob/master/test/image/baselines/mapbox_fill.png) fail. Not sure if it's a new bug in `mapbox-gl` or a wrong implementation of their API on our part.

Further investigation is needed. Hopefully for before releasing plotly.js `v1.16.0`.

**Comment by etpinard** [comment]
Quick update: upgrading `mapbox-gl` will be a little trickier than I thought. The latest version removed `mapboxgl.GeoJSONSource()` and a few more methods that we're currently using. I'm still hoping to have `mapbox-gl` `0.22.x` in plotly.js `1.17.0`

**Comment by etpinard** [comment]
Progress on the [`bump-mapbox`](https://github.com/plotly/plotly.js/compare/bump-mapbox) branch.

Waiting for a response to https://github.com/mapbox/mapbox-gl-js/issues/3032 before continuing.
