### ISSUE TITLE
Plotly.js Showgrid:false not working for 3d Scatter Plot.

### ISSUE THREAD

**Issue by Rudresh-Ajgaonkar** [plotly/plotly.js#759]
http://community.plot.ly/t/plotly-js-showgrid-false-not-working/1598

This is the issue i have opened up in the community.

I tried to follow the codepen( http://codepen.io/plotly/pen/KpLVzv) given in the example in the documentation but wasn't able to reproduce similar results when dealing with a 3D scatter Plot. 
 
I am trying for something like this : 
 http://codepen.io/plotly/pen/KpLVzv

**Comment by etpinard** [comment]
3D axis attributes need to be wrapped inside a `scene` container. 

See example here: http://codepen.io/etpinard/pen/LkdbWo

In the future please note: there's no need to open a community post **and** a Github issue for the same topic. Cross-referencing the two is pretty annoying. Thanks.
