### ISSUE TITLE
Horizontal legend items not visible when many legend items

### ISSUE THREAD

**Issue by psalmody** [plotly/plotly.js#769]
Was pointed out in #766 that scrolling not intended for `layout.legend.orientation = 'h'`.  Example workaround is to use [legend groups](https://github.com/plotly/plotly.js/blob/master/test/image/mocks/legend_horizontal_groups.json). 

This is not a great solution, however, as it means clicking the legend group hides/shows ALL traces in the group (see [jsfiddle](https://jsfiddle.net/psalmody/c9x3xzg9/)).

Proposing that plotly.js implement something similar to ggplot2 which automatically wraps additional legend items on horizontal legend orientation. Especially on mobile portrait orientation, this allows the graph data to take up the entire width of the screen and push the legend below the graph which is much preferable in my view.
![kpi-2-raceretention](https://cloud.githubusercontent.com/assets/12420157/17063488/047552ae-4fe4-11e6-9094-c91257b01b8b.png)

**Comment by etpinard** [comment]
Thanks.

**Comment by psalmody** [comment]
@etpinard Can you review this PR on my fork? I think it should resolves this issue. https://github.com/psalmody/plotly.js/pull/1

**Comment by etpinard** [comment]
@psalmody I think that should do it.

One possible imperfection I see here:

![image](https://cloud.githubusercontent.com/assets/6675409/17069023/5276bd42-5022-11e6-817b-6efb0f327dc6.png)

is that the items on the second line don't line up with the items above them - unlike in the ggplot example you posted. Was that on purpose?

**Comment by psalmody** [comment]
I did notice that but decided it's probably more complicated than it's worth. Personally, I don't have any problems with the items not appearing in columns and I think that the (legend groups)[https://github.com/plotly/plotly.js/blob/master/test/image/mocks/legend_horizontal_groups.json] workaround would still be possible if a user really wanted the lined-up columns.

**Comment by etpinard** [comment]
> I did notice that but decided it's probably more complicated than it's worth

Yeah. I agree. Your solution sounds like a solid fallback for extra-wide legends. If ever some users want a more fine-grained legend layout, we could always add support for something like:

```js
layout.legend = {
  type: 'grid',
  grid: [ [ 'trace 0', 'trace 1', 'trace 2'], ['trace 4', 'trace 3'] ]
};
```

down the road.

@n-riesco what do you think?

**Comment by n-riesco** [comment]
I'm unable to test this until Monday.

Does toggling traces work in this PR?

**Comment by psalmody** [comment]
If by toggle you mean hide/show the trace by clicking the legend item, yes.

**Comment by n-riesco** [comment]
@etpinard , @mdtusz I think this PR is ready for review.

---

This PR is an improvement over the current behaviour. I think there is a low hanging fruit that could be implemented in another PR. With this PR, a multiline horizontal legend would look like this:

![](https://cloud.githubusercontent.com/assets/12420157/17119043/0abcec38-5270-11e6-993b-43fa61dae2ff.png)

One easy way to align the traces in a grid would be to iterate over all the traces to compute the maximum width, and use this width for all the traces.

**Comment by psalmody** [comment]
@etpinard I've made a change to the pull request per @n-riesco suggestions about aligning traces in a grid. I agree that it looks much better and it was simpler to do than I originally thought.

![image of plotly with grid legend](https://cloud.githubusercontent.com/assets/12420157/17149251/f4dbd0c6-5316-11e6-9600-65a0e3eac18e.png)

**Comment by psalmody** [comment]
Sorry but new to this process. @etpinard or @mdtusz should I send a PR back to plotly/plotly.js from my fork?

**Comment by mdtusz** [comment]
Yep! Open a PR with your fork and we'll take a look at it!

**Comment by psalmody** [comment]
@yniknafs It's a great idea. Not sure I personally have the time to modify the code though... :(

**Comment by viggotw** [comment]
> > I did notice that but decided it's probably more complicated than it's worth
> 
> Yeah. I agree. Your solution sounds like a solid fallback for extra-wide legends. If ever some users want a more fine-grained legend layout, we could always add support for something like:
> 
> ```js
> layout.legend = {
>   type: 'grid',
>   grid: [ [ 'trace 0', 'trace 1', 'trace 2'], ['trace 4', 'trace 3'] ]
> };
> ```
> 
> down the road.
> 
> @n-riesco what do you think?

I realize I am pretty late for this conversation, but that suggestion sounds fantastic. The problem with using legend groups to align/group the legends is that this also makes them visible/invisible together when you toggle-click the trace name in the legend. More than ones, I have wanted to group similar legends together, though be able to make them invisible seperatly.

**Comment by ad4437** [comment]
Any updates on this?
