### ISSUE TITLE
Documentation - no title on title example

### ISSUE THREAD

**Issue by lp-jonathan** [plotly/plotly.js#772]
This page:
https://plot.ly/javascript/figure-labels/
Shows that the chart title should be "plot title", but there is no such title on the chart (it's missing from the actual JS).
This would usually be trivial, but as this is meant to be an example of setting the chart title...

(Other components of the actual-JS and the documentation-JS don't align in that example either.)

**Comment by cldougl** [comment]
All fixed - thanks for pointing that out @lp-jonathan!
