### ISSUE TITLE
documentation - layout points to the wrong place

### ISSUE THREAD

**Issue by lp-jonathan** [plotly/plotly.js#773]
On https://plot.ly/javascript/reference/ - if I click on the left bar "Layout", the link is actually to https://plot.ly/javascript/reference/#layout-margin - which is at the very very very very bottom of the page (and the bottom of the layout section), and not at the top of the "layout" section as would be expected.

Some other left-links seem to do that too (geo-axes), but I've not tested them all.

**Comment by cldougl** [comment]
Hey @lp-jonathan I'm moving this issue into our documentation repo: https://github.com/plotly/documentation/issues/486
Feel free to post any doc issues you run into there.
Thanks for reporting!
