### ISSUE TITLE
allow images restyle without source key

### ISSUE THREAD

**Issue by VeraZab** [plotly/plotly.js#774]
it appears that the sources key is necessary in order to successfully call a restyle on `layout.images`.
http://codepen.io/veraz/pen/wWjPZp?editors=1010

Would it be possible to remove this condition as it would allow greater flexibility to create UI elements that create defaults for those other keys and are created before the user uploads an image?

**Comment by etpinard** [comment]
That's a correct. 

Images with no `source` field are considered invalid for plotly.js as per this [line](https://github.com/plotly/plotly.js/blob/bc917acc7c0936ca2f31a9535c0f7fbec23954f6/src/components/images/defaults.js#L28) from PR https://github.com/plotly/plotly.js/pull/525.

A way around this problem would be to have a default image `source` in store somewhere (e.g. in the workspace) that would fill in the `source` field when a user omits it.
