### ISSUE TITLE
cannot remove rangeselector buttons with a relayout call

### ISSUE THREAD

**Issue by VeraZab** [plotly/plotly.js#777]
here's a codepen
http://codepen.io/veraz/pen/zBjVAZ

So instead of removing the button, it appears that the default plotly.js button is appearing instead.

**Comment by etpinard** [comment]
Confirmed.

`Plotly.relayout(gd, 'xaxis.rangeselector.buttons[i]', null);` appears to work. 

But yeah, `'remove'` just work also.
