### ISSUE TITLE
Hover info does not always display for bar traces with many values

### ISSUE THREAD

**Issue by caseyross** [plotly/plotly.js#779]
Bar traces with many values can sometimes have areas where hover info does not appear at all.

See [here](https://jsfiddle.net/vn2dphyp/4/) for an example. By moving your mouse left and right along the plot, you should be able to find areas where hovers do not appear, even though there is data in those areas.

**Comment by rreusser** [comment]
It looks like a aliasing due to the very large number of bars. In other words, the bars are less than one pixel wide so that, although the browser renders a sliver of blue, it's not actually possible to place the mouse on top of some of the bars.

At risk of sidestepping the issue, is it possible that a filled scatter would be a better fit?

**Comment by caseyross** [comment]
Ideally, I'd like to preserve the bar structure for when the plot is zoomed-in. But a filled scatter definitely seems like a good workaround when there are this many bars.

**Comment by etpinard** [comment]
Confirming the described behavior. As @rreusser points out, I'm not sure how to _fix_ this though.

**Comment by rreusser** [comment]
Relevant code is [traces/box/hover.js](https://github.com/plotly/plotly.js/blob/master/src/traces/box/hover.js) and [plots/cartesian/graph_interact.js#inbox](https://github.com/plotly/plotly.js/blob/master/src/plots/cartesian/graph_interact.js#L1340-L1345). Perhaps a tweak is necessary for sub-pixel bar widths, but it would require digging in and dissecting the logic a bit more.

**Comment by rreusser** [comment]
See also: #780

**Comment by alexcjohnson** [comment]
closed, probably by #2218
