### ISSUE TITLE
Bar trace hover text not shown when using bar and scatter with large data set

### ISSUE THREAD

**Issue by caseyross** [plotly/plotly.js#780]
[Example here](https://jsfiddle.net/0sgj3dzb/1/). With the 'compare data' option selected, only the hover text for the scatter trace is shown. Either reducing the number of data points or removing one of the traces appears to eliminate the issue.

**Comment by etpinard** [comment]
Thanks for writing in.

>  Either reducing the number of data points

Do you have example of this?

**Comment by caseyross** [comment]
[Here is the above example reduced](https://jsfiddle.net/59qo2v88/2/) to half the number of points. It appears to correctly display hover text for both traces.

**Comment by etpinard** [comment]
@caseyross thanks very much.

**Comment by vadonibabu** [comment]
Any update on this issue?
