### ISSUE TITLE
Heatmap crashes with d3 errors when the x and y axis label arrays only contain a single string

### ISSUE THREAD

**Issue by wobenshain** [plotly/plotly.js#782]
http://codepen.io/wobenshain/pen/XKYmGA

This appears to be an unintended consequence of the fix for Issue #605 which causes v0 to be set to a string instead of V0In or 0.

Relevant commit: b913a5bd44cda9f28b4cea5a076cd24820b6d3df

**Comment by etpinard** [comment]
fixed via https://github.com/plotly/plotly.js/pull/783
