### ISSUE TITLE
Expose original event

### ISSUE THREAD

**Issue by paneyi** [plotly/plotly.js#788]
It would be great to expose the original event along with the data in Plotly events.
One practical example would be to know if the user was pressing any special keys when clicking and act accordingly, like add to a selection.

`var acummulate = originalEvent.altKey || originalEvent.ctrlKey || originalEvent.shiftKey || originalEvent.metaKey`

Thanks!

**Comment by etpinard** [comment]
@paneyi thanks for writing in. Merging your ticket with https://github.com/plotly/plotly.js/issues/145
