### ISSUE TITLE
Make range selector active button color settable

### ISSUE THREAD

**Issue by VeraZab** [plotly/plotly.js#790]
It appears that I cannot change the background color of the 'all' rangeslider button.
Is this the intended behavior?
http://codepen.io/veraz/pen/XKYLoQ?editors=0010#anon-login

**Comment by etpinard** [comment]
confirmed.

**Comment by etpinard** [comment]
Oops. In fact, yes, the _active_ button colour cannot be modified at the moment. See [here](https://github.com/plotly/plotly.js/blob/85c2e2050f9aa8c7ec9abb854095992b3a99cd5f/src/components/rangeselector/draw.js#L145) it is always set via a constant.

Changing this to `type: feature`. But, this will still part of `1.16.0`.

**Comment by etpinard** [comment]
@VeraZab  do you have a preference for the attribute name? Should it be: 

- `rangeselector.activebgcolor` or 
- `rangeselector.bgcoloractive`  or 
- `rangeselector.activecolor` 

??

(cc @cldougl @chriddyp )

**Comment by cldougl** [comment]
I think I like `rangeselector.activebgcolor` the best

**Comment by mmehrle** [comment]
Five years later this answer actually helped me in python ;-)
