### ISSUE TITLE
Plot sizing problems

### ISSUE THREAD

**Issue by paneyi** [plotly/plotly.js#797]
Hi! I'm trying to build a dashboard using [angular-gridster](https://github.com/ManifestWebDesign/angular-gridster) and realized that whenever I do a resize on each gridster-item and replicate it resizing the Plotly graphs (`Plotly.Plots.resize(graph)` with the graph having `autosize: true`), the width changes correctly and fills the parent `div` but the height is always stuck at 450px.
Where does this magic number come from? I couldn't find it in the source.
I've also came accross this [post](http://community.plot.ly/t/plot-sizing-problems/1620) which seems to be related.
Any ideas what might be happening?

**Comment by etpinard** [comment]
Can you share a reproducible example to help us debug? Thanks.

**Comment by etpinard** [comment]
Closing until reproducible example is shared.
