### ISSUE TITLE
Rangemode tozero has odd behavior with only negative points in scatter plot

### ISSUE THREAD

**Issue by mboorstin** [plotly/plotly.js#798]
Repro cases: http://codepen.io/anon/pen/QEBOzQ

I've encountered two odd behaviors when a scatter plot with an axis set to `rangemode: 'tozero'` has only negative data points.  If there is only a single data point, the axis direction will be reversed and the inital range won't go all the way to the point (it looks like it's 1 unit away from the point; you can scroll to find the point at the correct coordinates).  If there are multiple data points, the axis direction will be correct and both points will be within the initial range, but the initial range won't go to zero.  I've included examples of these as the first and second graphs in the Codepen.  I've also included examples of bar charts as the third and fourth graphs to show what I think is the correct behavior.

If this is indeed a bug I'm happy to work on a patch to fix it.

**Comment by etpinard** [comment]
Thanks very much for this very detailed report.

The autorange code is pretty old and not that well tested so I'm not sure what exactly `rangemode: 'tozero'` _should do_ for scatter traces with negative values.

Generalising non-default `rangemode` to negative values would be great addition to the library. But we should first solidify our testing suites. 

Here are the (only) two image test we have for non-default `rangemode` at the moment:

- `axes_range_mode` - [mock](https://github.com/plotly/plotly.js/blob/master/test/image/mocks/axes_range_mode.json)  | [img](https://github.com/plotly/plotly.js/blob/master/test/image/baselines/axes_range_mode.png)
- `autorange-tozero-rangemode` - [mock](https://github.com/plotly/plotly.js/blob/master/test/image/mocks/autorange-tozero-rangemode.json) | [img](https://github.com/plotly/plotly.js/blob/master/test/image/baselines/autorange-tozero-rangemode.png)

The autorange computations are made in [`Axes.getAutoRange`](https://github.com/plotly/plotly.js/blob/a992b5985fa9890ef7317c99836fda861d58285c/src/plots/cartesian/axes.js#L133-L215) and rely on [`Axes.expand`](https://github.com/plotly/plotly.js/blob/a992b5985fa9890ef7317c99836fda861d58285c/src/plots/cartesian/axes.js#L278-L385) which is called from the trace modules (e.g. [here](https://github.com/plotly/plotly.js/blob/a992b5985fa9890ef7317c99836fda861d58285c/src/traces/bar/set_positions.js#L215) for bar traces). Both these routine aren't tested in isolation yet (in [`axes_test.js`](https://github.com/plotly/plotly.js/blob/master/test/jasmine/tests/axes_test.js)). We should do this before moving on this fixing the issue you're pointed here.

**Comment by mboorstin** [comment]
OK.  I'll take a crack at adding some Jasmine tests in `axes_test.js` with what I think is reasonable behavior.

**Comment by mboorstin** [comment]
@etpinard can you take a look at https://github.com/plotly/plotly.js/pull/813?  Thanks!

**Comment by etpinard** [comment]
fixed by https://github.com/plotly/plotly.js/pull/813
