### ISSUE TITLE
Space in x-value causes combined bar/scatter trace hover text misalignment with large data set

### ISSUE THREAD

**Issue by caseyross** [plotly/plotly.js#803]
See here: http://jsfiddle.net/cpanmc8m/
When hovering over the chart, the x-value identified by the hover text differs between the two traces, even though the traces have the same x-values. For example, the scatter trace may show that the hovered x-value is 40, while the bar trace shows hover text for value 39.

[Increasing the amount of data relative to the chart width](http://jsfiddle.net/n17sxmcc/) appears to exacerbate how far apart (numerically) these hover text values are. On the other hand, [reducing the amount of data](http://jsfiddle.net/2oh1sev6/) seems to make the hover text work as expected.

The immediate culprit seems to be the space character in each x-value. [Replacing the space character with a letter](http://jsfiddle.net/m0zrLczq/) or [with a tab character](http://jsfiddle.net/bppLxqt8/) does not cause the same issue. Instead, this causes a reversion to the behavior described in #780 (bar trace hover text is not shown).

**Comment by etpinard** [comment]
Thanks.

**Comment by alexcjohnson** [comment]
fixed, probably by #2218
