### ISSUE TITLE
Assigned range does not work when Autorange been set as "reversed"

### ISSUE THREAD

**Issue by BELIEVEWSW** [plotly/plotly.js#809]
I tried to assigned a specific value for the range but it's not work when the autorange was set as reversed.
It's even not work in the example on the plotly website.[here is it](http://codepen.io/plotly/pen/oxbzyO)

**Comment by etpinard** [comment]
That's the intended behaviour.

Whenever an axis `autorange` is set to `true` or `'reversed'` the `range` setting is ignored.

To set a reversed range, simply set the axis `range` such that `range[0] > range[1]` like in http://codepen.io/etpinard/pen/AXPwAr
