### ISSUE TITLE
Default date ticks are drawn for each day at time: 01:00:00 rather than 00:00:00 

### ISSUE THREAD

**Issue by cldougl** [plotly/plotly.js#811]
Example: http://codepen.io/plotly/pen/grdEaN?editors=1010

It would be more correct to have the default tick for a day be drawn at time: 00:00:00 rather than the first hour.

**Comment by etpinard** [comment]
pinging @alexcjohnson (again)

**Comment by alexcjohnson** [comment]
I'm pretty sure this is the daylight saving time bug, will go away when we switch to UTC internally, which is part 2 of my cleanup plan, once nothing user-facing involves epoch milliseconds. Thanks for pointing me to this @etpinard

**Comment by alexcjohnson** [comment]
closed by #1194
