### ISSUE TITLE
can plot.ly graph multiple surfaces using the javascript (not python) api?

### ISSUE THREAD

**Issue by mewalig** [plotly/plotly.js#82]
Can plot.ly do a multiple-surface chart (and if so, how)-- such as the bottom one shown at https://plot.ly/python/3d-surface-plots/, but using the javascript api instead of the python one?

**Comment by etpinard** [comment]
Bug reports must be accompanied with a reproducible example. We recommend using
[codepen](http://codepen.io/), [jsfiddle](https://jsfiddle.net/) or
[jsbin](https://jsbin.com) to share your example.

https://github.com/plotly/plotly.js/blob/master/CONTRIBUTING.md#opening-issues

**Comment by mewalig** [comment]
This is not a bug report, it is a question of whether the js library has a feature already which I just can't seem to find.

**Comment by mewalig** [comment]
If I'm posing this question in the wrong forum pls let me know.

**Comment by etpinard** [comment]
answer here: http://stackoverflow.com/a/34137105/4068492

**Comment by mewalig** [comment]
Thank you
