### ISSUE TITLE
Plotly returns undefined for axis

### ISSUE THREAD

**Issue by camper9** [plotly/plotly.js#820]
Plotly JS returns undefined value if series x array is set string values array. Please find below sample

Plotly.plot(gd, [{
  y: [2,1,2],
  x: ["Q1","Q2","Q3"]
}]);

gd.on('plotly_hover', function(eventData) {
  var xaxis = eventData.points[0].xaxis,
      yaxis = eventData.points[0].yaxis;
  
  eventData.points.forEach(function(p) {
    console.log('pixel position', xaxis.l2p(p.x), yaxis.l2p(p.y))
  });
})

It would be good to have data return clicked x and y coordinate in plotly_click event function

**Comment by etpinard** [comment]
> Plotly JS returns undefined value if series x array

This is by [design](https://github.com/plotly/plotly.js/blob/1992b57743fbeb9aeb42c46c6bc9029b3216c97c/src/plots/cartesian/set_convert.js#L126) for categorical axes. Try using `d2c` instead as in http://codepen.io/etpinard/pen/EydWVG

**Comment by camper9** [comment]
But still d2c is not solving the purpose. There should be direct method to return clicked point x & y.
