### ISSUE TITLE
Uncaught HierarchyRequestError: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to insert the rule.

### ISSUE THREAD

**Issue by Gerarddp** [plotly/plotly.js#822]
With the last version of plotly.js (v1.16.0) I get the following error

<img width="762" alt="screen shot 2016-08-04 at 23 14 01" src="https://cloud.githubusercontent.com/assets/285647/17418515/36fb647e-5a99-11e6-9034-2c4b2a4e72ab.png">

![image](https://cloud.githubusercontent.com/assets/285647/17418577/831aa432-5a99-11e6-8f8c-b3a3a5ead6ab.png)

**Comment by etpinard** [comment]
Thanks for reporting. What browser are you using?

**Comment by Gerarddp** [comment]
With:
 - Chrome Mac (Version 52.0.2743.82 (64-bit))
 - Chrome Mac (Version 52.0.2743.116 (64-bit))
 - Safari Technological Preview Mac (Release 10 (Safari 9.1.2, WebKit 11603.1.1)) with _different_ error
    `HierarchyRequestError (DOM Exception 3): The operation would yield an incorrect node tree`

Don't have any other browser right now to try

**Comment by etpinard** [comment]
OK. Strange. All good from my end on Chrome 51.

Can you share a reproducible example in codepen / jsFiddle / jsBin ?

**Comment by Gerarddp** [comment]
I tried reproducing the bug with one of this online editors with no success. So I'll be making a repo to reproduce it, hopefully I have time soon to do it.

**Comment by etpinard** [comment]
I just updated to `Chrome 52.0.2743.116`, and everything appears to work in vanilla-ish environments.

**Comment by etpinard** [comment]
Ok. I just released a hot fix [`1.16.1`](https://github.com/plotly/plotly.js/releases/tag/v1.16.1), would you mind trying it out?

**Comment by Gerarddp** [comment]
Yes, that fixes the problem 😄
