### ISSUE TITLE
Firefox SecurityError: The operation is insecure

### ISSUE THREAD

**Issue by seanpringle** [plotly/plotly.js#826]
Using Firefox v47 on Ubuntu, Plotly.js v1.16.0 sometimes returns a "SecurityError: The operation is insecure."

The test case is https://plot.ly/javascript/ where three of the example charts fail, starting with the top-most one mapping GDP to Life expectancy.

Console says:

```
SecurityError: The operation is insecure.

[573]</r.getAllRuleSelectors()
 plotly-latest.min.js:45
[573]</r.injectStyles()
 plotly-latest.min.js:45
[583]</C.plot()
 plotly-latest.min.js:46
plotLifeExpectancy()
 javascript:3942
plotAll/<()
 javascript:3975
forEach()
 self-hosted:232
plotAll()
 javascript:3968
<anonymous>
 javascript:4006
```

On an intranet web app I see the same error. Rolling that back to v1.15.0 works fine.

**Comment by etpinard** [comment]
Confirmed. Thanks for the report. 

Maybe related to https://github.com/plotly/plotly.js/issues/822
