### ISSUE TITLE
Snapshot routines should allow users to specify image width/height

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#83]
Motivated by https://github.com/plotly/plotly.js/issues/42#issuecomment-162520017

At the moment, the `Snapshot.toImage` has [hard-coded `width` and `height` parameters](https://github.com/plotly/plotly.js/blob/master/src/snapshot/toimage.js#L50-L51).

Something like:

```js
Plotly.Snapshot.toImage(gd, {format: 'png', width: 1000, height: 800});
```

Moreover, maybe the on-success handler used by the [modebar `toImage` button](https://github.com/plotly/plotly.js/blob/master/src/components/modebar/buttons.js#L73-L83) could be used as the default on-success handler to `Snapshot.toImage`

**Comment by spencerlyon2** [comment]
Ping, any update on this?

**Comment by etpinard** [comment]
We're still doing experiments with potential APIs. No serious work has gone into this to date. 

That said, once we figure out how to expose things to the users, this should be a 2-day project.

**Comment by etpinard** [comment]
Once we're comfortable with the API, we should expose the `toImage` on the `Plotly` directly.

Moreover, we'll need `toImage` to return a promise, like the other `Plotly` async methods.

**Comment by gramster** [comment]
Is there a way to get raw PNG data from a plot snapshot? We would like to do this so that we can generate a PNG output in an IPython notebook so that when viewing the .ipynb file in Github or elsewhere where Javascript is not executed there is a static fallback version that gets displayed.

**Comment by spencerlyon2** [comment]
You should be able to do `Plotly.Snapshot.toImage(gd, {"format": "png"})`

**Comment by gramster** [comment]
Thanks. I don't see docs on Plotly promises. I tried this:

    var idata;
    Plotly.Snapshot.toImage(model.dom.id, {"format": "png"}).then(function(d) { idata=d; })

but I get:

    Plotly.Snapshot.toImage(...).then is not a function(…)

`toImage()` is returning an EventEmitter. 

What am I missing?

**Comment by gramster** [comment]
Ah, I see. I need to use `...toImage(...).once('success', function(url) { ...})`

**Comment by ifll** [comment]
I think that for the user it would be really interesting to be able to choose the image size. But also it could be too much features on the plot and reduce simplicity...

I would suggest that the coder who is buiding the plot could choose if the users (the ones who will be watching the plot) are capable to change or not the PNG image from the plot.

To do so I would suggest to add inside the layout variable an option which involves the modebar, and where it could be such a variable like "snapshotsize" which could admit a vector including a fixed size: `snapshotsize = [1000 1000]` or either the auto option `snapshotsize = "auto"`

Regarding the `"auto"` functionality I would suggest that a dialog box appears on the plot allowing to choose the dimension of it. Somehow similar to the message box which appears when you click the snapshot button and it tells you that `Taking snapshot - this may take a few seconds`

With this implementation the current way that snapshots are being done right now can be kept (as the coder can decide the output size) but also the new feature of being able to choose the plot size can be implemented.

**Comment by etpinard** [comment]
Unfortunately other obligations came up for the plotly.js team members and this issue will remain on hold until at least April 1.

Our apologies.

**Comment by jackparmer** [comment]
Related discussion: http://community.plot.ly/t/use-plotly-offline-to-save-chart-as-image-file/408/8

**Comment by spencerlyon2** [comment]
For what it is worth, in [PlotlyJS.jl](https://github.com/spencerlyon2/PlotlyJS.jl) I can get true vector image pdf/eps/svg export as well as configurable png/jpeg exporting by getting the svg data from plotly, using librsvg to load that into cairo, and using cairo to render to the desired file type.

**Comment by etpinard** [comment]
@timelyportfolio have you made any progress on this one?

**Comment by timelyportfolio** [comment]
Yes, I just started working through this.  Here is the very preliminary set of [thoughts](https://github.com/timelyportfolio/plotly.js/blob/feature/snapshot/snapshot.md).  By the end of the week, I hope to have a full plan to address this.  Is that ok?

**Comment by timelyportfolio** [comment]
https://github.com/timelyportfolio/plotly.js/pull/1#issue-146731840 is my first attempt, and it seems we now have both 2) promises and 3) resize.  I would appreciate any thoughts.

**Comment by etpinard** [comment]
done in https://github.com/plotly/plotly.js/pull/446
