### ISSUE TITLE
Incorrect behaviour with Plotly.extendTraces when maxPoints > initial

### ISSUE THREAD

**Issue by mdtusz** [plotly/plotly.js#84]
When Plotly.extendTraces is called with a `maxPoints` value greater than the initial number of points when `Plotly.plot` is called, the maximum number of points shown does not change, i.e. if we extend a trace containing 3 points so that it will have 4, and set `maxPoints` to any value greater than 3, only 3 points will be shown on the plot.

Example:

``` javascript
Plotly.plot('plotDiv', [{ x: [1,2,3], y: [5,4,3] }], {})
    .then(function(gd){
        Plotly,extendTraces(gd, { y: [[4]] }, [0], 10)
    });
```

In this scenario, only 3 points will continue to be displayed, despite setting `maxPoints` to 10 in `Plotly.extendTraces`.

**Comment by mdtusz** [comment]
Upon further investigation, this isn't *really* a bug. 

To increase the number of points shown on the graph, you must also add a new x values - in situations where your x values are named strings, plotly.js cannot infer what an appended value should be. 

[Codepen here](http://codepen.io/plotly/pen/LGEyyY?editors=001).

**Comment by buremba** [comment]
@mdtusz What's the recommended way to deal with streaming data?

**Comment by mdtusz** [comment]
Sorry, upon a closer look (and more time in plotly.js code!) I see I was wrong!

In the codepen example, the last argument to `extendTraces` is 10 - this means that we truncate the data itself to 10 elements, *not just the display of data*.

In a typical streaming situation however, you would likely want to persist the incoming data to a database or logfile or something as well, but that can be managed separately from plotly.js code.

Sorry for any confusion - hope that helps!

**Comment by buremba** [comment]
Got it. Thanks @mdtusz!
