### ISSUE TITLE
showLink option does not have any effect. Link is always shown.

### ISSUE THREAD

**Issue by jnehlmeier** [plotly/plotly.js#854]
Regardless of the value of `showLink` option the link to open a plot in the cloud is always visible. Documentation/code states `showLink: false` is the default, so I would expect it to be hidden.

https://jsfiddle.net/6wwmfpLc/

Tried it with 1.16.1 and 1.16.2.

**Comment by etpinard** [comment]
Please have a look at: https://github.com/plotly/plotly.js/issues/603#issuecomment-231840090

**Comment by jnehlmeier** [comment]
So what is `showLink` good for then?

**Comment by etpinard** [comment]
It adds an _Edit chart_ link at the bottom right of graph (which essentially does the same of the `sendToCloud` mode bar button). 

See http://codepen.io/etpinard/pen/GqZqKE

**Comment by jnehlmeier** [comment]
Oh, I see. Thanks for the info.
