### ISSUE TITLE
Provide proper i18n support

### ISSUE THREAD

**Issue by jnehlmeier** [plotly/plotly.js#856]
Currently Plotly has poor i18n support.
- You can not change d3 locale (issue #380)
- Adjustment of rendered precision on date axis does not work when applying custom `axis.tickformat` if dates need to be rendered differently because of locale. If you want to keep that feature you have to patch hardcoded format strings: https://github.com/plotly/plotly.js/blob/ad88139911d09b52cfafecc2bc7e72fc267b3a7f/src/plots/cartesian/axes.js#L879
- Error messages, notifier messages, hover texts for default mode bar buttons are hardcoded in english https://github.com/plotly/plotly.js/issues/288

Currently I have to manually patch plotly for each release, which is pretty annoying.

**Comment by etpinard** [comment]
Thanks for writing in. 

It shouldn't be too hard to pass these locale options in the plot [config](https://github.com/plotly/plotly.js/blob/master/src/plot_api/plot_config.js) and have the axes code look up `gd._context` for their values.

I added a link to a past issue discussing mode bar internationalisation and I marked #380, #288 as duplicate.

**Comment by fhurta** [comment]
I'm voting for this feature!

**Comment by sclausen** [comment]
:+1: The only thing that keeps us from moving from Highcharts to plotly.js

**Comment by etpinard** [comment]
@sclausen 

> us

Who would that be?

**Comment by florianleger** [comment]
Hi there,
I've made a fork of Plotly.js to handle french translations and d3 locales for my company:
https://github.com/florianleger/plotly.js
([diff](https://github.com/plotly/plotly.js/compare/master...florianleger:master))
I explain in the README how it works and how to add new languages, I thought that it might be helpful to others until a patch came out.

**Comment by alexcjohnson** [comment]
I believe that between #2195 and #2207 this issue on i18n can be closed - but before I do so, I'd love some 👍 /👎  on the framework from folks who've weighed in here.

I'd also ❤️  if folks who need localization for their own purposes would be willing to PR those back into the main repo - filling in the translations, verifying the date formats, and adding `decimal`/`thousands` to the files in [lib/locales](https://github.com/plotly/plotly.js/tree/master/lib/locales). The full list of strings we need to translate is in [dist/translation_keys.txt](https://github.com/plotly/plotly.js/blob/master/dist/translation-keys.txt). The locale files we have currently are auto-generated from [world-calendars](https://github.com/alexcjohnson/world-calendars/tree/master/dist/regional) which is itself a descendant of https://github.com/kbwood/calendars - but we're certainly happy to accept any other locales you might want to contribute!

@florianleger thanks for pointing out your fork - I did some things the same way, other things differently, but it was very helpful to see what you had done. Does the current master branch of plotly.js work for your purposes now?

**Comment by florianleger** [comment]
@alexcjohnson My fork does not work with the last release `1.13.2`, there is a lot of conflicts and I've not the time to resolve them now...

**Comment by alexcjohnson** [comment]
@florianleger sorry, what I meant was, can you use plotly.js as of the current `master` branch - which has not yet been published to npm - WITHOUT forking it? I just want to know if the changes in #2195 and #2207 satisfy your needs (and replace your fork) or if there is anything else we need to consider before publishing this.

**Comment by JonasGutermuth** [comment]
Thanks for your work! 

I tried to translate it to German, but I'm not sure how to best translate everything. Please feel free do criticize the translation. Do you think we need an issue to discuss the translations for every language?

https://github.com/JonasGutermuth/plotly.js/blob/master/lib/locales/de.js

**Comment by alexcjohnson** [comment]
@JonasGutermuth great!

I think we should handle each translation as a separate PR directly to the main repo:
- Give the PR the label `type: translation` (that I just created 😉 )
- Please @ mention a few other speakers of this language who can help review your translations. If Plotly staff can't review this language we will wait for comments and approval from someone who can.
- If you've omitted any keys from [dist/translation_keys.txt](https://github.com/plotly/plotly.js/blob/master/dist/translation-keys.txt) - which means they will fall back on the US English text - just make a short comment about why in the PR description: the English text works fine in your language, or you would like someone else to help translating those, or whatever the reason.
- And just to be clear, you need only update the files in `lib/locales/`, not the ones in `dist` - those will be automatically updated when we build and publish.

**Comment by jdugge** [comment]
@JonasGutermuth That looks great! I'd be happy to review the translations once they've been turned into a pull request (there's a couple of typos "Standart" instead of "Standard" or "Componente" instead of "Komponente").

**Comment by florianleger** [comment]
@alexcjohnson It's fine with the current master, thanks for your work!

**Comment by etpinard** [comment]
Closing. The "to add a translation" instructions are now part of our [PR template](https://github.com/plotly/plotly.js/blob/master/.github/PULL_REQUEST_TEMPLATE.md#translations).
