### ISSUE TITLE
Crossfilter support

### ISSUE THREAD

**Issue by rolandjitsu** [plotly/plotly.js#857]
Are there any plans for crossfilter support? So some kind of lasso selection but similar to what Google Chrome Dev Tools has when looking at Timeline.

Or can the zoom be controlled so that it does not scale, it just selects?

**Comment by rolandjitsu** [comment]
Oops, by bad, it looks like [range-slider/](https://plot.ly/javascript/range-slider) is somewhat what I just described.

Or are there other ways for achieving the same result?

**Comment by etpinard** [comment]
Our lasso and rectangular selection are probably exactly what you're asking for. See docs at -> https://plot.ly/javascript/lasso-selection/

That said, lasso and rectangular selections only work for markers and text points at the moment 

You might want to read up on the current open items in https://github.com/plotly/plotly.js/issues/698 and https://github.com/plotly/plotly.js/issues/170 before starting to build something too serious. 

If you have any other questions about lasso and rectangular selections, please ask them on our community forums at http://community.plot.ly/
