### ISSUE TITLE
Stop Zoom Event Bubbling in Line graph

### ISSUE THREAD

**Issue by agarwalhitesh83** [plotly/plotly.js#861]
Hi All,
I want to redraw the whole plotly line graph(by making ajax call) with the new x-axis values received when 'plotly_relayout' event gets fired. Currently it is always firing the default behaviour of scale zoom.

Is it possible to load dynamic data when we try to zoom in plot.ly line graph.

Thanks,
Hitesh

**Comment by etpinard** [comment]
It would be best to ask your question on http://community.plot.ly/

Thanks.
