### ISSUE TITLE
Duplicate x-axis label with 'category ascending'

### ISSUE THREAD

**Issue by john-soklaski** [plotly/plotly.js#862]
Repro at:
https://codepen.io/john-soklaski/pen/QEoJAz

When the xaxis in this example has `categoryorder: 'category ascending'` set, there is a duplicate '1' on the xaxis, if it is not set, the duplicate label no longer appears.

**Comment by john-soklaski** [comment]
I think this is due to an off by one error in `flattenUniqueSort`. Fix at https://github.com/plotly/plotly.js/compare/master...john-soklaski:category_ascending_bug

**Comment by etpinard** [comment]
Thanks for the report. Confirmed.

At first glance your fix looks appropriate. Categorical ordering is tested [here](https://github.com/plotly/plotly.js/blob/92e73feb73b7f02f09cd733eecabf32971f2e47d/test/jasmine/tests/calcdata_test.js#L33). Would you mind testing that suite by running:

```bash
npm run test-jasmine -- tests/calcdata_test.js
```

and see that it doesn't break anything?

If the tests pass, PR away :rocket:
