### ISSUE TITLE
Color of border pad

### ISSUE THREAD

**Issue by Tmv3v** [plotly/plotly.js#864]
http://stackoverflow.com/questions/38986899/r-plotly-how-to-change-the-color-of-the-outer-border

This issue appeared when I tried to create a plot with grey background., and I am unable to find a way to change the color of the border pad

**Comment by etpinard** [comment]
Hmm. Of the

```html
<body style="margin: 5px; padding: 0px; overflow: hidden; width: 100%; height: 100%; background-color: white;">
<div id="htmlwidget_container" style="position: absolute; top: 5px; right: 5px; bottom: 5px; left: 5px;">
<div id="htmlwidget-3128" class="plotly html-widget html-widget-static-bound js-plotly-plot" style="width: 100%; height: 100%;">

<div class="plot-container plotly"><div class="svg-container" style="position: relative; width: 1270px; height: 403px;">
```

plotly.js only generates the

```js
<div class="svg-container" style="position: relative; width: 1270px; height: 403px;">
```

part. So the solution won't be part of this repo unfortunately. 

I believe the best place to post this issue would be here: https://github.com/ropensci/plotly/issues/new
