### ISSUE TITLE
Hover label elements are misplaced on small viewports

### ISSUE THREAD

**Issue by eagor** [plotly/plotly.js#865]
text itself seems to be aligned properly, but the background rects are overlapping.

![image](https://cloud.githubusercontent.com/assets/2478452/17800390/776f0e18-65eb-11e6-98c4-3117b1b7e6bf.png)

Demo:
http://codepen.io/eagor/pen/RROKKK

**Comment by eagor** [comment]
did some more testing. Looks like it's not long text to be the issue:

http://codepen.io/eagor/pen/dXLNzX

**Comment by etpinard** [comment]
Looks like the issue is with small `width` / `height` viewports in general. 

Thanks for posting!
