### ISSUE TITLE
Place labels inside chart

### ISSUE THREAD

**Issue by CalvinFernandez** [plotly/plotly.js#877]
![image](https://cloud.githubusercontent.com/assets/2644420/17911512/e45f41aa-695b-11e6-9f1f-5e73e5dd0c99.png)

Is it possible to place labels inside chart the way they appear on the Y axis above? It seems like axis labels could support an 'inside' and 'outside' designation the same way they're implemented with ticks.

**Comment by etpinard** [comment]
That's not possible at the moment unfortunately. 

@CalvinFernandez I can turn this issue into a feature request if you like.

**Comment by CalvinFernandez** [comment]
@etpinard is this the correct place for feature requests? I wasn't sure -- If you would like I can submit a PR for this

**Comment by etpinard** [comment]
> is this the correct place for feature requests? 

Yes. Absolutely. 

> If you would like I can submit a PR for this

that would be amazing.

**Comment by doersino** [comment]
This feature would enable full-width/edge-to-edge charts on mobile, which would under certain circumstances look better that what's currently possible.

**Comment by shannonlubetichsc** [comment]
👍  I just spent quite some time trying to do this (not realizing it wasn't possible)

**Comment by jayfresh** [comment]
:+1: for this feature

**Comment by edwardbetan** [comment]
+1

**Comment by nkmechanics** [comment]
+1

**Comment by romallemann** [comment]
+1

**Comment by etpinard** [comment]
deleting all +1s.

**Comment by healzer** [comment]
This an old post, but I'm wondering whether this is already possible in 2018?

**Comment by ricazhang** [comment]
@etpinard 

First, hi, I'm new to contributing so I wanted to run this idea by you if that's ok. I've created a basic implementation for this locally by adding a field in yaxis called ticklabelalignment which can be set to "inside" or "outside". If it is "inside" then you need to make some changes in [axes.js](https://github.com/plotly/plotly.js/blob/master/src/plots/cartesian/axes.js#L1740) (see image below). 

This is similar to what you suggested in #883 for the tickanchor. It would not cover positioning the label above or below the tick though (#1882), its only for the horizontal alignment but we could do something similar for the vertical alignment. This seems to work well with left or right y-axis and subplots. 

<img width="580" alt="screen shot 2018-06-12 at 9 57 21 pm" src="https://user-images.githubusercontent.com/7819877/41331079-f751cdd2-6e8b-11e8-9015-7e77bf06c0b9.png">

**Comment by rms95** [comment]
As I understand these changes aren't in the current version? (I'm working with 1.40, using `yaxis: { ticklabelalignment: 'inside' }`)

As this is a much needed change for mobile (maximizing screen real estate utilization), I'd very much like to see this feature. Many apps use this:
https://www.designyourway.net/diverse/6/uicharts/1997994.jpg
https://cdn.dribbble.com/users/4620/screenshots/2576470/linegraphdashmobile_1x.png
Or Google Image search for "mobile graph"

@etpinard There seems to be a solution (or at least partially, for horizontal alignment, which is the most important one in most use cases), which from the looks of it does not pose a high risk for conflicts, can this please be verified and merged to the master branch?

**Comment by ricazhang** [comment]
@rms95 Yes they aren’t in the current version. I haven’t merged my change to master. You’re welcome to try out my version of it with that alignment flag though!

**Comment by rms95** [comment]
I looked at the /dist/plotly.min.js file in your latest commit files, though that doesn't seem to include the new code.
I haven't compiled projects like this before, if you have the fully build file ready to grab, would mind sending it as attachment here?

**Comment by alexcjohnson** [comment]
Closed by #5275
