### ISSUE TITLE
line chart with single trace, leneged won't visible when visible:"legendonly" property

### ISSUE THREAD

**Issue by dineshu07** [plotly/plotly.js#879]
legend is not visible When data is single trace with visible property to set to legenedonly.
here is my jsfiddle. https://jsfiddle.net/dineshu07/w7gjfpkr/
legend visible when more than 1 trace

**Comment by etpinard** [comment]
That's the intended behavior.

Single-trace graphs don't get a legend unless `layout.showlegend` is set to `true` regardless of the value of the trace `showlegend` attribute. See logic [here](https://github.com/plotly/plotly.js/blob/0daa5d6ea0eec6e55ec300a7904d278ec1b805b8/src/components/legend/defaults.js#L56-L57).

**Comment by dineshu07** [comment]
Thank you. i got it.
