### ISSUE TITLE
JSPM: mapbox-gl error processing package

### ISSUE THREAD

**Issue by DevJazz** [plotly/plotly.js#880]
Hi, I am currently using JSPM as my choice of package manager for my current project, and one of the major dependencies I want to be using is Plotly.js. When I am installing (through JSPM) the plotly.js package, it returns this error.

'err  Error processing package config for npm:mapbox-gl.'

This is happening on what I have tested so far, versions 1.16.0, 1.16.1 and 1.16.2. I noticed in your release log for 1.16.3 that you've bumped up mapbox-gl to a newer version. It looks like mapbox-gl is failing on a further dependency down the line. 

Does this contain the potential fix for the error? If so the package is currently not retrievable on NPM at this time of writing so I cannot test if the error can be resolved.

Apologies if this turns out to be a JSPM issue rather than a Plotly.js, thankyou!

Edit: more detail

**Comment by etpinard** [comment]
Oh interesting. I didn't even know that plotly.js was working with jspm. Maybe this issue https://github.com/plotly/plotly.js/issues/22 is obsolete? 

> I noticed in your release log for 1.16.3 

Can you please try that?

**Comment by DevJazz** [comment]
Okay so I managed to grab 1.16.3 from npm now but the process is still failing. However, reverting to 1.15.0 managed to fix the JSPM build process!

I do remember running JSPM with a targeted version of 1.16.1 a week or two ago and it use to build absolutely fine so it's interesting it's failing now. I had a look into the issue you linked me, so will attempt some of those fixes in there to see if it works. So far I haven't had to do any special implementations and its generally worked straight out of the box with a JSPM install.

Will leave any comments in here if I find anything further.

**Comment by etpinard** [comment]
OK. Thanks for the info.Let us know if you find more 

Due to other time constrains, no plotly.js team member will spend time resolving this issue (hence the `type: community` tag)

**Comment by DevJazz** [comment]
No problem! Thank you for taking the time to look at the issue!

**Comment by etpinard** [comment]
> However, reverting to 1.15.0 managed to fix the JSPM build process!

Interesting. `1.16.0` added the `scattermapbox` trace type the the main bundle (ref [here](https://github.com/plotly/plotly.js/releases/tag/v1.16.0)), so maybe `mapbox-gl` is causing this issue.

Have you tried installing [`mapbox-gl`](https://github.com/mapbox/mapbox-gl-js) with JSPM?

**Comment by DevJazz** [comment]
Yeah tried an install with mapbox-gl and it instantly threw a parsing error on the package.json file. Doing a few searches on Google looks like mapbox-gl does not preferably support for SystemJS/JSPM due to the way browserify is heavily integrated/used in their development process.

Might try setting a shim/path on the JSPM package to use the 'dist' version of Plotly as noted in the earlier linked issue.

**Comment by etpinard** [comment]
I suspect this issue will be resolved in https://github.com/plotly/plotly.js/pull/2361 or is resolved already.

Closing. Subscribers are invited to open a new issue if ever this problems persist once `v1.35.0` is released.
