### ISSUE TITLE
Inconsistent spacing between legend marker and legend title

### ISSUE THREAD

**Issue by CalvinFernandez** [plotly/plotly.js#881]
![image](https://cloud.githubusercontent.com/assets/2644420/17979311/e96f90b0-6ac7-11e6-8215-23adc5b99d50.png)

![image](https://cloud.githubusercontent.com/assets/2644420/17979349/26087f8c-6ac8-11e6-9d0f-0d2f5b5ec5ac.png)

Would it be possible to make spacing between legend and marker consistent based on marker size?

**Comment by etpinard** [comment]
Thanks for the suggestion.

I'm not sure exactly what you mean by _marker consistent based on marker size_? You mean the Central Park Zoo and Bronx Zoo text in the above screenshot should be placed closer to the marker items? 

But, consider this legend 

![image](https://cloud.githubusercontent.com/assets/6675409/18182259/357974d6-705d-11e6-9335-76e056ba9a98.png)

by moving _trace 3_ closer to the square marker, _trace 3_ would be misaligned with the items above it.

**Comment by CalvinFernandez** [comment]
@etpinard yes this is a good point, perhaps we could apply spacing such that the legend text is aligned and the minimum is always consistent?

**Comment by etpinard** [comment]
> perhaps we could apply spacing such that the legend text is aligned and the minimum is always consistent?

Maybe a below solution would be to add a set of attribute determining the legend item text position offset (in pixels). For example,

```js
var layout = {
  legend: {
     xtextoffset: -1, // for all items OR [0,0,-1, /* .. */] to offset each item independently 
     ytestoffset: 0   // similarly
  }
}

```

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
