### ISSUE TITLE
Bar Chart - No data

### ISSUE THREAD

**Issue by allochi** [plotly/plotly.js#885]
Hi, I'm sorry if this is a repeated question, I did try and searched the issues but couldn't find something.

Currently in the bar charts, if the data is null, it's drawn as zero, is there a way to tell the bar chart do draw something like these instead?

http://i.stack.imgur.com/rwGy4.png
http://i.stack.imgur.com/Jyap7.jpg

if not, is it planned?

Thanks!

**Comment by etpinard** [comment]
> is there a way to tell the bar chart do draw something like these instead?

No, there's no way to do at the moment.

Adding a fallback isn't really in our plans. I'd recommend using layout shapes for this task.
