### ISSUE TITLE
addTraces() not working for scattergl

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#886]
Couldn't find this listed in #130 

http://codepen.io/cpsievert/pen/kXOPgq

**Comment by etpinard** [comment]
Ah I see. 

`scatter` and `scattergl` can't be mixed at the moment (the trace being added by `addTraces` is a `scatter`). 

See working version: http://codepen.io/etpinard/pen/bwGpPJ

More generally, as listed in #130, cartesian subplots can't mixed with gl2d subplots.
