### ISSUE TITLE
Plotly.js requires gl in Electron contexts

### ISSUE THREAD

**Issue by rgbkrk** [plotly/plotly.js#891]
When using plotly.js in an Electron app, it requires `gl`. I'm guessing this is because Plotly.js determines that it's running in a node context, even though there is a `window` and a full browsing environment available. Installed `gl` for now, figured I'd post an issue. I'll link to the relevant PR on the nteract side shortly.

**Comment by rgbkrk** [comment]
Related support for Plotly in nteract: https://github.com/nteract/nteract/pull/662

Possibly related gl error:

<img width="1109" alt="screen shot 2016-08-30 at 8 03 14 pm" src="https://cloud.githubusercontent.com/assets/836375/18114557/d14c9a36-6eec-11e6-8664-c57768b25084.png">

**Comment by etpinard** [comment]
Requiring plotly.js as `require('plotly.js/dist/plotly.js')` should make this issue disappear.

Is there an `electron` field we could add to the package.json to tell Electron to use the dist bundle instead of resolving all the `src/` requires?

> I'm guessing this is because Plotly.js determines that it's running in a node context

The only reason that happens is because of our `mapbox-gl` dependency. I think this issue should be moved to https://github.com/mapbox/mapbox-gl-js/issues unless there's a way to Electron to use the `dist/` bundle.

**Comment by rgbkrk** [comment]
> Is there an electron field we could add to the package.json to tell Electron to use the dist bundle instead of resolving all the src/ requires?

Sadly, no.

I'll try the dist path, sounds like an awesome option.

**Comment by spencerlyon2** [comment]
@rgbkrk how do you tell that gl isn't working inside electron.

I my Julia package (PlotlyJS.jl) that uses Electron as a display window I am able to make a `scattergl` trace, for example

**Comment by etpinard** [comment]
@spencerlyon2 the `gl` issue (see -> https://github.com/stackgl/headless-gl ) can be seen by `require('plotly.js`)` of version `1.16.0` and up which include `mapbox-gl` (to generate `scattermapbox` traces) which itself requires the `gl` module.

Our `gl2d` and `gl3d` trace types don't require `gl`.

**Comment by rgbkrk** [comment]
Ok great, that dist bundle works perfect for displaying the plot above.

**Comment by spencerlyon2** [comment]
@etpinard thanks for the explanation. 

I must be getting around it without knowing because I'm running plotly.js 0.16.2  inside electron without any problems -- that works for me!

**Comment by rgbkrk** [comment]
I'll have something nice for you soon @spencerlyon2 that you can use to send the plotly JSON spec over to this same component in nteract: https://github.com/nteract/nteract/pull/662

**Comment by spencerlyon2** [comment]
That's great. I really need to take a closer look at nteract. 

I've been very happy with the combination of Electron + plotly.js for my Julia package -- it let's me to some really cool streaming things.

**Comment by etpinard** [comment]
@rgbkrk @spencerlyon2 Ok if I close this issue?

**Comment by spencerlyon2** [comment]
Yep, good for me

**Comment by rgbkrk** [comment]
My second comment in this thread is fixed, not the core bit. We're still stuck with a native dependency on `gl` because of the `npm install`.

**Comment by etpinard** [comment]
> We're still stuck with a native dependency on gl because of the npm install

... in a node.js context - which we don't support (at least until https://github.com/tmpvar/jsdom/issues/1368 is done - as plotly.js makes use of `XMLSerializer`).

**Comment by rgbkrk** [comment]
I may end up creating a separate package specifically for electron uses that cuts a version based on plotly.js, though I'd rather not manage that and let it get out of sync.

**Comment by etpinard** [comment]
Yeah good point about the maintenance burden.

We might end up publishing another package specifically from node contexts (`plotly.js-node` anyone??) again once `jsdom` support all the browser things plotly.js uses. But, that said, the _main_ `plotly.js` package will remain a browser-only package in the foreseeable future.

**Comment by rgbkrk** [comment]
Yup, browser only is fine for me (browserifiable/webpackable that is).

**Comment by rgbkrk** [comment]
Ok we just tried to switch our build setup to not have any compilers, etc. available and the fact that `npm install` will try to bring in `gl` fails on us:

https://github.com/nteract/nteract/pull/687

**Comment by rgbkrk** [comment]
What if `gl` is a dev dependency and if someone is really using this from `node`, they have to install `gl` themselves?

**Comment by etpinard** [comment]
> What if gl is a dev dependency and if someone is really using this from node, they have to install gl themselves?

I'd vote :-1: on that, plotly.js is a browser-only app at the moment (and for the foreseeable future). 

I don't see why we should add a dev dependency to make sure that `require('plotly.js')` works in a node context, even though `Plotly.plot()` won't work.

**Comment by rgbkrk** [comment]
I think something is lost in translation here. I want a browser only app too and `gl` is not used in the browser version - it is in the node version.

**Comment by rgbkrk** [comment]
Welp, I'm a jerk. It was a peer dependency of a downstream dependency that has been resolved since upgrading. No `gl` necessary.

Sorry to waste your time @etpinard, thank you for the lovely JS.

**Comment by FrantisekGazo** [comment]
I got the `Uncaught Error: Cannot find module 'gl'` when trying the `plotly.js` in Electron app.

I installed version `1.18.1` via `npm install plotly.js`

**Comment by etpinard** [comment]
@FrantisekGazo 

please read https://github.com/plotly/plotly.js/issues/891#issuecomment-244088863

**Comment by rgbkrk** [comment]
I've updated the issue description to include the `require` into dist so people who end up at this issue see the way to handle it upfront.

**Comment by rgbkrk** [comment]
Since our overall bundled electron app was rather big (especially for Hydrogen), @lgeiger made [minimal-plotly](https://github.com/nteract/minimal-plotly) with only the `.min.js` build. It would be good for us to use the source distribution as much as possible (to allow for flattened npm dependencies and tree shaking), this is our first pass for now though.
