### ISSUE TITLE
Highlight Background Bars

### ISSUE THREAD

**Issue by Venerons** [plotly/plotly.js#892]
I have not found this feature neither an alternative way to accomplish this, so I'd like to submit a feature request if possible.

What I'd like to have is the feature to specify some regions to highlight on the chart, so between the given ranges (on the example based on X axis, but would be cool if also available on Y axis) the background is of a different, specified, color.

What I mean is something similar to the orange and darkgrey zones in the following example:

![highlights](https://cloud.githubusercontent.com/assets/1484847/18126176/3e82be0e-6f7a-11e6-8945-af1a5e73ca7f.png)

**Comment by spencerlyon2** [comment]
Does the `temperature` example [here](http://spencerlyon.com/PlotlyJS.jl/examples/shapes/) do what you want?  Note that you can change the color of those sections if you would like

**Comment by Venerons** [comment]
Wow, yes, seems exactly what I was searching for, thanks!
I should use [this configuration](https://plot.ly/javascript/reference/#layout-shapes) while using the Javascript version right?

**Comment by spencerlyon2** [comment]
The json for the layout in that example is:

```son
  "layout": {
    "width": 500,
    "shapes": [
      {
        "opacity": 0.2,
        "x0": "2015-02-04",
        "x1": "2015-02-06",
        "y0": 0,
        "type": "rect",
        "y1": 1,
        "fillcolor": "#d3d3d3",
        "line": {
          "width": 0
        },
        "xref": "x",
        "yref": "paper"
      },
      {
        "opacity": 0.2,
        "x0": "2015-02-20",
        "x1": "2015-02-22",
        "y0": 0,
        "type": "rect",
        "y1": 1,
        "fillcolor": "#d3d3d3",
        "line": {
          "width": 0
        },
        "xref": "x",
        "yref": "paper"
      }
    ],
    "height": 500
  }
```

**Comment by spencerlyon2** [comment]
link here: https://plot.ly/~sglyon/105/temperature/#code

**Comment by Venerons** [comment]
It's exaclty what I was searching for, thanks, sorry for bothering you! :)

**Comment by spencerlyon2** [comment]
No problem -- happy to help
