### ISSUE TITLE
restyle makes it harder to hover on trace legend

### ISSUE THREAD

**Issue by colinfang** [plotly/plotly.js#893]
This is very weird, and it seems to only occur when legends is inside the main plot.

Without `restyle`, the cursor changes immediately when over on the legends.

http://codepen.io/anon/pen/LRPrgV

However with `restyle`, it requires a bit of luck to get cursor correctly hover on the legends.

     Plotly.restyle(graphDiv, {visible: [false, false, true, true]});
     Plotly.restyle(graphDiv, {showlegend: [false, false, true, true]});

http://codepen.io/anon/pen/JRPwaj

I am using Chrome

**Comment by etpinard** [comment]
Thanks for reporting

**Comment by etpinard** [comment]
This bug was introduced in `1.11.0`
