### ISSUE TITLE
error message in IE 11 - chart does not plot

### ISSUE THREAD

**Issue by TanyaShen-BEA** [plotly/plotly.js#895]
Please see the attached screenshot of chart that doesn't render.  It works in Chrome, Firefox but not in IE 11.
![plotlylibraryerror](https://cloud.githubusercontent.com/assets/17254834/18181427/183f90a2-7059-11e6-9f26-2e935eee6cf9.PNG)

This is the error message:
SCRIPT5009: 'Uint8ClampedArray' is undefined.  
File: plotly-latest.min.js, Line: 32, Column: 22068

**Comment by etpinard** [comment]
Yikes.

What trace type are you trying to plot? Would you mind sharing a reproducible example?

**Comment by rreusser** [comment]
Looks like the only place it occurs in the plotly source comes from es6-promise. See: https://github.com/stefanpenner/es6-promise/blob/9fef04c77d94b1d1ff2e65180fad96c3d806db72/lib/es6-promise/asap.js#L35

**Comment by etpinard** [comment]
Thanks for the info @rreusser !

Interesting. We've been using that `es6-promise` polyfill ever since the `1.0.0` release and this is the first report we get.

Maybe `es6-promise` conflicts with something else on @TanyaShen-BEA 's page.

**Comment by rreusser** [comment]
Can't reference dist files since too big, so I'm looking at this from `plotly-basic.js`. It looks exactly the same in `v1.0.0`:

```javascript
10193 (function (process,global){
10194 /*!
10195  * @overview es6-promise - a tiny implementation of Promises/A+.
10196  * @copyright Copyright (c) 2014 Yehuda Katz, Tom Dale, Stefan Penner and contributors (Conversion to ES6 API by Jake Archibald)
10197  * @license   Licensed under MIT license
10198  *            See https://raw.githubusercontent.com/jakearchibald/es6-promise/master/LICENSE
10199  * @version   3.1.2
10200  */
10201 
10202 (function() {
10203     "use strict";
10204     function lib$es6$promise$utils$$objectOrFunction(x) {
10205       return typeof x === 'function' || (typeof x === 'object' && x !== null);
10206     }
10207 
...
10259     // test for web worker but not in IE10
10260     var lib$es6$promise$asap$$isWorker = typeof Uint8ClampedArray !== 'undefined' &&
10261       typeof importScripts !== 'undefined' &&
10262       typeof MessageChannel !== 'undefined';
```

**Comment by rreusser** [comment]
Hmm… `Uint8ClampedArray` supported [since KB2929437](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray), which was a security update released 04/08/2014. @TanyaShen-BEA is it possible that you're using a very old version of IE11?

**Comment by krellsebastian** [comment]
I've got the same behavior. 
Reproducible with the [public accessible VMs of Microsoft](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/). I've wanted to test my plots with IE10, bit seems the Win-Version is too old then?

**Comment by vikasmanze** [comment]
I am also geeting below error on trying to draw basic graph

File: plotly-latest.min.js, Line: 7, Column: 31139

Please suggest!

**Comment by rreusser** [comment]
@vikasmanze Sometimes very similar looking errors can have very difficult causes. Which version of plotly are you using? Which version of IE? Can you use `plotly-latest.js` instead of `plotly-latest.min.js` and paste the source of the error? (an error in a minified file is not very informative!) Thanks!

**Comment by warrenspe** [comment]
I am getting a similar error as well, emulating IE 10 via IE 11 (11.1480.14393.0).  Error below:

This browser lacks typed array (Uint8Array) support which is required by `buffer` v5.x. Use `buffer` v4.x if you require old browser support.

'Uint8ClampedArray' is undefined
plotly.js (73594,1)

According to [caniuse|http://caniuse.com/#feat=typedarrays], Uint8ClampedArrays are not supported by IE 10

**Comment by aaron5555** [comment]
This happens on all versions of IE I tested, and all version of Plotly.

Here is my inelegant workaround. It is working so far with relatively simple charts, but may cause side effects on more complex ones if Plotly actually tries to use a clamped array.

//ugly IE workaround
	if (typeof Uint8ClampedArray == 'undefined'){
		//just define it as a regular array
		Uint8ClampedArray = function(){return []};
	}
	$.getScript('plotly-latest.min.js', showChart);

**Comment by JewelsJLF** [comment]
I'm still getting this issue in v1.38.3 ...... are there any plans to fix this?

**Comment by kgrpti** [comment]
Look at https://community.plot.ly/t/error-loading-dependencies-in-ie-and-older-chrome-51/9426/15

**Comment by yemling** [comment]
Hi folks. Weirdly this looks like it's working in IE11 now, but not the older versions. Is this expected?

**Comment by AniWar** [comment]
I'm facing the same issue on IE-11 . I'm using trace type "scatter3d" .

**Comment by jackparmer** [comment]
This issue has been tagged with `NEEDS SPON$OR`

A [community PR](https://github.com/plotly/plotly.js/pulls?q=is%3Apr+is%3Aopen+label%3A%22type%3A+community%22) for this feature would certainly be welcome, but our experience is deeper features like this are difficult to complete without the Plotly maintainers leading the effort.

**Sponsorship range: $5k-$10k**

What Sponsorship includes:
- Completion of this feature to the Sponsor's satisfaction, in a manner coherent with the rest of the Plotly.js library and API
- Tests for this feature
- Long-term support (continued support of this feature in the latest version of Plotly.js)
- Documentation at [plotly.com/javascript](https://plotly.com/javascript/)
- Possibility of integrating this feature with Plotly Graphing Libraries (Python, R, F#, Julia, MATLAB, etc)
- Possibility of integrating this feature with Dash
- Feature announcement on [community.plotly.com](https://community.plotly.com/tag/announcements) with shout out to Sponsor (or can remain anonymous)
- Gratification of advancing the world's most downloaded, interactive scientific graphing libraries (>50M downloads across supported languages)

Please include the link to this issue when [contacting us](https://plotly.com/get-pricing/) to discuss.
