### ISSUE TITLE
Fix Michigan

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#899]
Choropleths of US states - like https://plot.ly/~Dreamshot/8177/gun-control-google-search-volume-by-us-state-since-2004/ - draw states with their borders out in the great lakes. Which *is* where their jurisdictional borders are, but this is not so useful or meaningful to viewers.

![screen shot 2016-09-02 at 12 01 58 pm](https://cloud.githubusercontent.com/assets/2678795/18210902/c9b34f86-7108-11e6-846e-687299c416ff.png)

This looks OK at the national level (gives a seamless border between US and Canada) but not at the state level. We should use the land outlines. This will affect all the great lakes states a little bit (MN, WI, IL, IN, OH, PA, NY) but Michigan has a totally different shape and size if you include the lakes.

The [docs](https://plot.ly/python/choropleth-maps/#united-states-choropleth-map) show a workaround using `showlakes` but this shouldn't be necessary, and still doesn't look exactly as you'd want - for this type of map you shouldn't see the border lines out in the water, and there should be lines at the water's edge:

![screen shot 2016-09-02 at 12 34 37 pm](https://cloud.githubusercontent.com/assets/2678795/18211071/b0ee5544-7109-11e6-9d4b-8f69be05fb41.png)

Globally I only see one other place we could consider doing this: Lake Victoria (Uganda, Tanzania, Kenya) but it's still not as big a change to the countries involved, and searches for eg "Tanzania Outline" and "Africa Choropleth" show that people don't seem to care too much one way or the other (but I will defer to locals, if any would like to chime in)

**Comment by etpinard** [comment]
@alexcjohnson I think fixed the problem in [`sane-topojson`](https://github.com/etpinard/sane-topojson).

Here's the USA scope at `resolution: 110` with `showcountries: true` and `showlakes: false` (i.e. the default look):

![image](https://cloud.githubusercontent.com/assets/6675409/19401691/bc4f5dc4-922a-11e6-97d3-963be71cf554.png)

with `showcountries: false` and `showlakes: false`:

![image](https://cloud.githubusercontent.com/assets/6675409/19401733/f210784e-922a-11e6-89ec-07cd32f058b2.png)


with `showcountries: false` and `showlakes: true`:

![image](https://cloud.githubusercontent.com/assets/6675409/19401761/14f80e94-922b-11e6-8a74-2163513e6d77.png)


with `showcountries: true` and `showlakes: true`:

![image](https://cloud.githubusercontent.com/assets/6675409/19401766/227db000-922b-11e6-89f1-dd7e28b6c07f.png)


:+1:  / :-1:  :question:

**Comment by alexcjohnson** [comment]
Huge improvement - love it!

Can we set `showcountries: false` by default when the scope is just the USA? This would extend to any other single-country scope we might add in the future too...
