### ISSUE TITLE
qgrid - plotly conflict

### ISSUE THREAD

**Issue by djchou** [plotly/plotly.js#90]
I'm using plotly offline in a jupyter notebook.  I'm coming across an error that i can't seem to debug.  

Here is my code:

import qgrid
import Quandl
import plotly
from plotly.offline import download_plotlyjs, init_notebook_mode, iplot

aapl = Quandl.get('yahoo/aapl')
qgrid.nbinstall(overwrite=True)

#works ok
qgrid.show_grid(aapl)

init_notebook_mode()
#no longer works ok
qgrid.show_grid(aapl)

The error message is
"
Javascript error adding output!
TypeError: Cannot read property 's' of undefined
See your browser Javascript console for more details.
"

**Comment by etpinard** [comment]
Looks like

Unfortunately, [qgrid](https://github.com/quantopian/qgrid/blob/master/qgrid/qgridjs/qgrid.js) uses the  RequireJS module syntax whereas plotly.js uses CommonJS. The two are incompatible out of the box (more info [here](http://stackoverflow.com/questions/16521471/relation-between-commonjs-amd-and-requirejs)).

Here are some solutions:

- https://github.com/rse/browserify-derequire
- https://github.com/calvinmetcalf/derequire

Thanks for reporting this issue. That said, no plotly.js team member will devote time to fixing this issue in the short term.

**Comment by djchou** [comment]
Thats too bad.  The combination of qgrid and plotly offline is powerful

**Comment by aggFTW** [comment]
This scenario would be fantastic @etpinard :(

**Comment by etpinard** [comment]
@djchou @aggFTW It would be great to fix this issue, I'm not saying we shouldn't. 

But, plotly.js only has 3 full-time devs at the moment, so we have to make decision based on the amount of users affected. I doubt that many people use plotly.js together with qgrid. Please, prove me wrong if you have data saying otherwise.

Sorry for the inconvenience.

**Comment by akansal1** [comment]
@etpinard Even custom widgets in Jupyter Notebook use Requirejs, as I received similar error using date widgets example provided in the ipywidgets examples with plotly in notebook...

**Comment by etpinard** [comment]
After the experiment in #232, we conclude that the best to solve this issue is within [plotly.py](https://github.com/plotly/plotly.py/issues/373).
