### ISSUE TITLE
Custom hover event for pie chart fail when hoverinfo set to 'none'

### ISSUE THREAD

**Issue by yongjun21** [plotly/plotly.js#902]
https://github.com/plotly/plotly.js/blob/master/src/traces/pie/plot.js#L99
https://github.com/plotly/plotly.js/blob/master/src/traces/pie/plot.js#L129

handleMouseOver exit early if hoverinfo set to 'none' skipping Fx.hover which triggers the custom hover event

**Comment by etpinard** [comment]
related to https://github.com/plotly/plotly.js/pull/851
