### ISSUE TITLE
Barmode relative breaks when combining with scatterplot and using orientation 'h'

### ISSUE THREAD

**Issue by fabiangehring** [plotly/plotly.js#905]
When combining a plot with barmode = 'relative' with a scatterplot and using orientation 'h', the barmode seems to be set back to 'group'. 
A reproducible example can be found in the link below. This issue is forwarded from https://github.com/ropensci/plotly/issues/667

**Comment by etpinard** [comment]
Can you share a reproducible example?

**Comment by fabiangehring** [comment]
Unfortunatley I only use plotly within R. I have never used it with "plain" javascript, therefore don't know how to create one. But in the link above there can be found a minimal R-Example.

**Comment by etpinard** [comment]
I'm not I understand this report. Maybe @cpsievert can help.

In plotly.js, there's no such thing as a scatter trace with `orientation: 'h'`. Moreover, the layout `barmode` attribute only affect bar traces, so a graph with one bar and one scatter looks exactly the same with `barmode: 'relative'` or `barmode: 'group'`.

**Comment by cpsievert** [comment]
https://github.com/ropensci/plotly/issues/667#issuecomment-245054440
