### ISSUE TITLE
Markers disapear when using subplots combining barmode 'relative' with scatterplot plots

### ISSUE THREAD

**Issue by fabiangehring** [plotly/plotly.js#906]
I have two plots that combine a barmode 'relative' and a scatterplot. When I combine them themselves with subplot markers disappear. Reproducible example in the following post where it was referenced to here: https://github.com/ropensci/plotly/issues/667

**Comment by etpinard** [comment]
sound like a duplicate of https://github.com/plotly/plotly.js/issues/905

**Comment by etpinard** [comment]
Calling this a duplicate of the closed #905 until further info from the issue author.
