### ISSUE TITLE
Invalid Date format in Hover data when full hour (0 mins)

### ISSUE THREAD

**Issue by fhurta** [plotly/plotly.js#911]
If the time is full hour (0 minutes), e.g. 12:00, the minutes part is stripped from `points[index].x` in `plotly_hover` event.

For x value of '2001-06-11 12:00', the points[0].x value is '2001-06-11 12' - the missing minutes part makes it invalid Date when used in `new Date(points[0].x)`.

See this [codepen](http://codepen.io/exavier/pen/wzagRb?editors=0010)

**Comment by etpinard** [comment]
pinging @alexcjohnson - who's been working on our date handlers lately.

**Comment by alexcjohnson** [comment]
Ah interesting... true, every other truncation of the full date format is common except this one. I'll make sure we keep minutes unless hours are going away too.
