### ISSUE TITLE
Changing className on container breaks subsequent redraws

### ISSUE THREAD

**Issue by benjeffery** [plotly/plotly.js#916]
Hi,
Had a quick search and can't see any mention of this. 
See fiddle here: https://jsfiddle.net/b1jLzqs1/2/
The plot should redraw three times - but only does so twice.
If one removes the line that modifies the container's className between redraws, then the redraw is successful.
Initial report: https://github.com/benjeffery/react-plotlyjs/issues/10
Thanks!

**Comment by etpinard** [comment]
plotly.js pre-`1.17.0` failed silently on `redraw` when the input graph div classes didn't include `js-plotly-plot` - see [`Lib.isPlotDiv`](https://github.com/plotly/plotly.js/blob/0676a21c0eadc1771bd51a5ea0464c584db24f4c/src/lib/index.js#L386-L389)

If you're looking for a better handling of this situation, I think this is now _fixed_ via https://github.com/plotly/plotly.js/pull/907 which is part of the `1.17.0` release - where `Plotly.redraw` now throws an [error](https://github.com/plotly/plotly.js/blob/0676a21c0eadc1771bd51a5ea0464c584db24f4c/src/plot_api/plot_api.js#L473) when `Lib.isPlotDiv(gd)` is false.

Can I ask why you would want to change the `contaienr.className` before a redraw?

**Comment by benjeffery** [comment]
>Can I ask why you would want to change the `container.className` before a redraw?

The original reporter wanted to style the div when loading data, this can easily be done with an enclosing div, so I don't think there are any critical use cases for this. 

I'm happy enough for this to be an error - so it's great that `1.17.0` includes this. I will add code to react-plotlyjs to detect class changes and give a friendly error also.

Many thanks for the response, feel free to close if you agree.

**Comment by etpinard** [comment]
> I'm happy enough for this to be an error

Great. I'll close this issue.

But, I'm open to suggestions about making plotly.js a little less intrusive (e.g. with `className`) if you have any.
