### ISSUE TITLE
Suggestion: Percent axis type

### ISSUE THREAD

**Issue by WorldMaker** [plotly/plotly.js#918]
Low priority feature request: I've got several line and bar charts where the data is stored as float percents (range 0.0 to 1.0) and it would be nice to have an axis type that worked like linear in autorange and tick determination but output to the display tick counts like "20%" instead of "0.2".

Obvious workaround for now is that I can multiply all my data myself before feeding it to Plotly and get what close to what I'm looking for here (but without "%" in the tick labels of course), but it might be nice to have an explicit support for percentages directly in plotly, somewhat like the difference between the category and date axis types.

**Comment by etpinard** [comment]
You might to look at http://community.plot.ly/t/normalizing-data-to-percentages/1923 and more specifically http://codepen.io/etpinard/pen/ZONwNA?editors=0010

**Comment by WorldMaker** [comment]
Ah, `tickformat` was something that hadn't turned up in some of my other searches. That does seem to help.

**Comment by etpinard** [comment]
No problem. IT

**Comment by WorldMaker** [comment]
Yup, lots of documentation and options makes it easy to overlook some of the little things. Thanks.
