### ISSUE TITLE
Alternating background colors in bar charts

### ISSUE THREAD

**Issue by Mike3010** [plotly/plotly.js#922]
It would be nice to have a possibility for alternating background colors in bar charts.

So for example when displaying data from 1 year it should be possible to have an alternating background for different quarters for better visualization.

suggestions would be to have _color1_, _color2_, _start of color1_ and _span between alternations_ as parameters.

**Comment by etpinard** [comment]
I'm not sure what you mean by _background colors_. Do you refer to the fill color of the bars?

For example here: http://codepen.io/etpinard/pen/bwVEBb where the `marker.color` is set to an array where its items correspond to each bar.

**Comment by Mike3010** [comment]
Hi, 

thanks for your answer. I'm referring to the background color of the plot (plot_bgcolor in layout settings)

**Comment by etpinard** [comment]
Are you referring the the background color of multiple subplots? Or, making the background of a given subplot be of multiple colors?

If the latter, I'd recommand using `layout.shapes`.

**Comment by etpinard** [comment]
If you can find a screenshot of what you're looking, that would help us a lot. Thanks.

**Comment by Mike3010** [comment]
I'm looking for something like this:
http://codepen.io/MikeLogan/pen/EgPYOr

The solution with shapes works, as you can see in the codepen, but I would like to set a starting point and an intervall for the different background colors, so that I don't have to compute every shape on my own when the data of the plot changes.

**Comment by etpinard** [comment]
I see. But, I doubt this use case alone justifies modifying the `plot_bgcolor` functionality.

**Comment by Mike3010** [comment]
Ok, too bad.

But thanks for your time anyways!
