### ISSUE TITLE
z-Index for shapes

### ISSUE THREAD

**Issue by Mike3010** [plotly/plotly.js#923]
Looking at issue #892 with highlighting background bars, implemented with layout shapes

These highlighting shapes are actually in the foreground. Is it possible to introduce a z-Index for shapes, so they can be moved to the background, behind the charts?

**Comment by etpinard** [comment]
I think PR https://github.com/plotly/plotly.js/pull/439 added exactly what you described.

See example: http://codepen.io/etpinard/pen/wzKrrL

**Comment by etpinard** [comment]
@Mike3010 does the `layer` attribute for shapes resolve your issue?

**Comment by Mike3010** [comment]
Yes, this was exactly what I was searching for, thanks!
