### ISSUE TITLE
Range slider not responsive

### ISSUE THREAD

**Issue by camper9** [plotly/plotly.js#927]
Plotly chart is responsive and can be resized using "Plotly.Plots.resize". But the range slider never resizes.

Any fixes for this issue?

**Comment by camper9** [comment]
Plotly chart is responsive and can be resized using "Plotly.Plots.resize". But the range slider never resizes.

Any fixes for this issue?

**Comment by etpinard** [comment]
duplicate of https://github.com/plotly/plotly.js/issues/686
