### ISSUE TITLE
background color not showing in 3DMesh Plots

### ISSUE THREAD

**Issue by Kully** [plotly/plotly.js#929]
@etpinard 
I noticed that the background colors for [Trisurfs](https://plot.ly/python/trisurf/) in Python were not their usual grey. I found a similar issue in the [JS tutorial for 3D Axes](https://plot.ly/javascript/3d-axes/#axes-background-color) and recreated the same problem in [Codepen](http://codepen.io/plotly/pen/Xjmrbp) by forcing a background color of `rgb(255,0,0)` for illustrative purposes.

**Comment by etpinard** [comment]
Thanks. This has been broken since the `1.17.0` release.

**Comment by etpinard** [comment]
Oh. This is really unfortunate.

Looks like https://github.com/stackgl/gl-shader/pull/16 is causing this issue.

Reverting back to `gl-shader@4.2.0` fixes the issue. I also noticed the some tick labels aren't showing on 3D graphs on `1.17.x`, reverting to `gl-shader@4.2.0` also fixes that.

The worse part is that `npm run test-image -- gl3d_*` fails locally on `master` but CiricleCI fail to catch the problem - most likely it didn't properly update `gl-shader` to `4.2.1` during https://github.com/plotly/plotly.js/pull/850.

cc @monfera

**Comment by etpinard** [comment]
... maybe we should start committing an `npm-shrinkwrap.json` file to ensure that CircleCi run `npm i` when updating nested dependencies.

**Comment by etpinard** [comment]
I'm going to make a patch release after https://github.com/plotly/plotly.js/pull/931 is merged. 

@Kully this issue should be fixed in  `v1.17.2`

**Comment by Kully** [comment]
> @Kully this issue will be fixed in v1.17.2

👍

**Comment by etpinard** [comment]
Fixed: http://codepen.io/etpinard/pen/GjokrJ
