### ISSUE TITLE
Relayout with scatter3d (and other 3d traces, probably?)

### ISSUE THREAD

**Issue by rreusser** [plotly/plotly.js#934]
**Expected behavior**: scene layout properties for 3D plots can be modified with `Plotly.relayout` (and similar API methods that work through `Plots.supplyLayoutModuleDefaults`).

**Observed behavior**: The call appears valid, but no change occurs. It's possible I have a simple error, but it appears not to do anything. [This example](http://codepen.io/etpinard/pen/WxrRoG) appears to work through getters and setters, but that seemed to be finicky. Specifically, object identity made a big difference. Any similar examples without the same scene/camera object identities led to a blank white screen.

**Version**: `plotly-1.17.2.min.js` 

**Possible fix**: Without understanding the cause, it seems that if GL just doesn't work this way that plotly.js should be doing the footwork to make it appear as if it does, i.e. sending the input through getters and setters for you.

**Example**: http://codepen.io/rsreusser/pen/ALEaNR?editors=0010

**Further small nitpick**: I could produce a more simple example, but just to float the issue out there, [this pen](http://codepen.io/rsreusser/pen/EgPgZw) attempts to update the data and layout as simultaneously as it can, but the scene/camera getters/setters appear to all get queued behind any other updates, making for kind of an unpleasant effect. It would be nice if the scene updates were somehow synchronous-ish.

cc: @etpinard @monfera, who both know way more than I do about the GL interface.

**Comment by monfera** [comment]
@rreusser is it the same behavior with `plotly-1.16.0` ?

**Comment by rreusser** [comment]
Yes. Confirmed all the way back to `1.0.0`. Behavior is also the same if I use the `{camera: {scene: {eye: {x: ..., y: ...}}}}` format instead.

**Comment by monfera** [comment]
@rreusser I bumped into the same thing when I wanted to animate something in GL (IIRC programmatically rotating the brain) and it didn't work the usual way, I got the info that it was not implemented. As an example workaround, I forked this from @etpinard : http://codepen.io/monfera/pen/KMmPPV and there was a fairly smoothly rotating Snowden head as well (just speeding up Étienne's original Snowden head rotation) but haven't found it now.

**Comment by rreusser** [comment]
For reference, here's what the laggy effect looks like. As discussed with @monfera, I'm making a reasonable attempt to avoid lots of input events from queueing or something else problematic on my end, so I think this might be legitimately odd.

![lorenz-3d](https://cloud.githubusercontent.com/assets/572717/18484845/5f601b76-79a7-11e6-9bf0-134837d042d3.gif)

**Comment by NateZimmer** [comment]
For any who might be reading this, yeah i've had a huge amount of trouble doing what monfera did. I tried relayout ...ect to try to change the graphs rotation but no luck. Side note, if you modify monferas code from Math.atan(xyz.y/xyz.x) to Math.atan2(xyz.y , xyz.x) you get a full rotation as opposed to a 180deg rotation.
