### ISSUE TITLE
Long yaxis values crop into label

### ISSUE THREAD

**Issue by dbauszus** [plotly/plotly.js#938]
In the case of the yaxis value labels being 4 digits long, the value labels overlap with the yaxis title.

![image](https://cloud.githubusercontent.com/assets/6732788/18513424/59eb54c4-7a85-11e6-85af-128dfd1be68e.png)

Here is a jsfiddle to show the problem.

https://jsfiddle.net/goldrydigital/t49y6gf1/

**Comment by etpinard** [comment]
I can't reproduce this.

This what I'm seeing in your fiddle:

![image](https://cloud.githubusercontent.com/assets/6675409/18513658/67ce8bc0-7a5c-11e6-8381-0e55c94bf02e.png)


Would you mind sharing any other info?

**Comment by dbauszus** [comment]
Which browser are you using? I have tested IE, EDGE, Chrome, FireFox. I don't have access to Safari. Perhaps it is working in Safari.

Is there any way to force a distance between the title and the graph?

**Comment by etpinard** [comment]
> Which browser are you using?

I'm using `Google Chrome 53.0.2785.101` on Ubuntu 16.04.

> Is there any way to force a distance between the title and the graph?

Here's a (hacky) solution using `yaxis.tickprefix` (don't forget to increase `margin.l`): https://jsfiddle.net/t49y6gf1/4/

**Comment by dbauszus** [comment]
Perfect... That's exactly what I was looking for. Thanks.

**Comment by hiteshsahu** [comment]
You need to add <br> with the title text

Add <br\> as prefix if you want to add space on top of the title. Add <br\> with a &nbsp; if you want to add space after the title.

```
  yaxis2: {
          showgrid: false,
          title: 'Condensing Temperature (°F)<br\> <br\><br\><br\>',
          titlefont: {color: '#ff7f0e'},
          tickfont: {color: '#ff7f0e'},
          anchor: 'free',
          overlaying: 'y',
          ticksuffix: ' °F ',
          side: 'left',
          position: -20.,
          fixedrange:true,
          range: [60, 150],
          titlefont: {
             size: 12,
             color: '#7f7f7f'
           },

```
