### ISSUE TITLE
No text hover info on polar plots

### ISSUE THREAD

**Issue by djkashtan** [plotly/plotly.js#94]
If I set my plot to use x and y and text, it works just fine. If I set it to use r and t (radius and theta), the r and t show up when I hover over the marker, but I cannot get text to show up. Is this a known bug or do I have to do something special? I did not find anything in the api :(

Here is a jsfiddle:

http://jsfiddle.net/kb3gN/13150/

**Comment by etpinard** [comment]
From v1.0.0 release [notes](https://github.com/plotly/plotly.js/releases/tag/v1.0.0): 

> Polar charts are under-developed.

**Comment by emackey** [comment]
+1, would like to have option to customize text hovers like on other chart types.

**Comment by jlamato** [comment]
I'll +1 this too. Having a on_hover/on_click event would be very useful.

**Comment by etpinard** [comment]
> Having a on_hover/on_click event would be very useful

> would like to have option to customize text hovers like on other cha

Both suggestions are in the plans. Stay tuned for updates.

**Comment by suh786** [comment]
+1, ability to customise tooltip will be great.

**Comment by waegen** [comment]
+1 
Any updates on this 18month old issue?

**Comment by FabienDaniel** [comment]
Hi, I try to set up a radar chart and can't make the text to appear on hover.
Any update (or plan) with this ?

**Comment by etpinard** [comment]
No updates. We mostly stopped maintaining polar charts in their current form. Polar needs a full rewrite which should take at least one month if not two.

Projects of that scale usually require some financial support. Please take a look at https://plot.ly/products/consulting-and-oem/ if any of you are interested.

**Comment by ColasDroin** [comment]
+1
Still no update on this issue?

**Comment by etpinard** [comment]
here's an _update_: https://github.com/plotly/plotly.js/pull/2200

**Comment by etpinard** [comment]
fixed in `scatterpolar` after #2200
