### ISSUE TITLE
Invisible traces in 1.17.0+ when using Plotly.redraw

### ISSUE THREAD

**Issue by tim-hutchinson** [plotly/plotly.js#942]
In my use of Plotly, I frequently end up with an empty placeholder created while data is retrieved, then update it with new data using Plotly.redraw(). After 1.17, only one trace is drawn in a scatter plot when following this method. The legend and tooltips are created as expected, but the actual trace is missing from the chart. A quick check indicates this is also true if calling through Plotly.update()
[CodePen](http://codepen.io/timhutchinson/pen/gwAGKb)

![image](https://cloud.githubusercontent.com/assets/14815358/18536464/82c5591c-7acb-11e6-8a3a-399d55fcf70d.png)

I've checked past versions and it looks like it's working as of 1.16.3, but not from 1.17.0 - 1.17.2
[CodePen working in 1.16.3](http://codepen.io/timhutchinson/pen/pEyWpZ)

**Comment by arikfr** [comment]
I experienced the same thing. I just didn't know how to describe it... Thanks @tim-hutchinson !

**Comment by etpinard** [comment]
Thanks very much for the report!

We made numerous changes to the update paths during the animate PR (https://github.com/plotly/plotly.js/pull/802 - release in `1.17.0`), so problems like this one don't come as a surprise.

In the meantime, I suggest replacing your `Plotly.redraw` with (the more robust) `Plotly.addTraces` as in http://codepen.io/etpinard/pen/VKaVmY 

Now that we added a `Plotly.update` method (that can update both `data` and `layout` simultaneously https://github.com/plotly/plotly.js/pull/875, I'm thinking about deprecating `Plotly.redraw` in [`v2.0.0`](https://github.com/plotly/plotly.js/issues/420). Can I ask what do you find convenient about `Plotly.redraw`?

**Comment by tim-hutchinson** [comment]
With `Plotly.redraw`, I only need to know that the data for the chart changed, not how it changed, which makes it easy to use Plotly with data binding (we're wrapping it into a Polymer component). With methods like `addTraces`/`deleteTraces`, I need to know to manage the state to know that I added a new trace, or track which one I'm deleting. Or if I add data to an existing trace, I need to handle that case too. It's all doable, and probably higher performance, just additional overhead of working out what changed.

Are there differences between `Plotly.redraw` and `Plotly.update` as they exist today? From the docs, they read like they do the same thing. I'd actually discovered this by updating to 1.17 with the intent of moving to `Plotly.update`
