### ISSUE TITLE
Store data in binary format in html export

### ISSUE THREAD

**Issue by fcollonval** [plotly/plotly.js#943]
Hello,

First thank you for your amazing work!

I'm using a lot Jupyter Notebook and I face a challenge when in need to share static form keeping the graphics interactivity. Indeed, I tend to have large amount of data. Therefore when saving the notebook in HTML, its size is huge. As far as I know all interactive visualization javascript library like Plotly or D3js store the data in ascii format in the HTML. **Would it be possible to store the data as binary (like for the images)?**

I have some experience with that [opensource software](http://www.openfoam.com/documentation/user-guide/basic-file-format.php#x6-80002.2.3) in which it is possible to specify if the numbers must be stored as ascii or binary; the binary format taking notably less size.

Cheers

**Comment by etpinard** [comment]
This ticket would probably be best for https://github.com/plotly/plotly.py/issues

plotly.js can already generate `png` images for example:

```js
Plotly.plot('graph', [{ y: [2,1,2] }]).then(function(graph) {
   return Plotly.toImage(gd, { format: 'png' });
})
.then(function(imgData) {
   /* imgData is the image data URL */
});
```

Maybe we could add an `export_static=True` option to the plotly.py `plotly.offline` module that would remove the `plotly.js` bundle (which is taking ~ `1MB` by itself) and leave only static png graphs.

**Comment by etpinard** [comment]
Alternatively, you might want to look at https://plot.ly/python/static-image-export/
