### ISSUE TITLE
Issue with 3D surface graph width. 

### ISSUE THREAD

**Issue by goralpl** [plotly/plotly.js#951]
Hello,

I'm trying to adjust the width of a 3d surface graph. I know that you can specify a width and height using the layout object. 

`var layout = {
							title : "Tim Lahey",
							autosize : false,
							width : 1000,
							height : 1000
						};`

However, this only works to a certain extent. The graph does not adjust the width past a certain point and the only thing that happens is that a space is created between the graph legend on the right and the actual graph on the left. Does anyone know how to adjust the width of the graph?

Thanks

**Comment by etpinard** [comment]
See http://codepen.io/etpinard/pen/dppqRr

 And more generally, have a look at our community [forums](http://community.plot.ly/) if you have any other implementation questions in the future.
