### ISSUE TITLE
image export doesn't include CSS modifications

### ISSUE THREAD

**Issue by hellochar** [plotly/plotly.js#954]
Hey Plotly team,

It seems that the image export feature currently doesn't take into account CSS properties -- see http://codepen.io/hellochar/pen/zKowEB and notice how the image export doesn't have the dashed line or text shadow. Is that something we can workaround/are there plans to support this in the future?

Thanks for your time!
Xiaohan Zhang

**Comment by etpinard** [comment]
That's the desired behavior unfortunately.

plotly.js graphs are meant to be edited using our JSON-serializable data / layout API.

The reason why the CSS properties don't appear on image exports is that our [snapshot](https://github.com/plotly/plotly.js/tree/master/src/snapshot) routine clones the graph's `data` / `layout` into a orphan `<div>` that isn't not attached to the DOM.

By looking at our snapshot code, I'd recommend writing your own to-image function as plotly.js will look in `data` / `layout` for its **only** source of truth for the foreseeable future.

**Comment by hellochar** [comment]
Gotcha, I'll look into maybe rolling my own then. Appreciate the quick and thorough response :)
