### ISSUE TITLE
incompatible with Angular 2

### ISSUE THREAD

**Issue by rolandjitsu** [plotly/plotly.js#955]
There seems to be some kind of conflict when using Angular 2 and Plotly. The same issue is somewhat described in [#7218](https://github.com/angular/angular/issues/7218).

For now, the only fix is including plotly before angular's zone.js dependency.

Could there be something done from within this lib?

**Comment by etpinard** [comment]
We'll remove the `es6-promise` polyfill entirely from plotly.js in `v2.0.0` (see complete list of planned modifications [here](https://github.com/plotly/plotly.js/issues/420)).

That said,pPerhaps we could already (in the `v1.x` series) distribute a plotly.js bundle w/o the `es6-promise`? I'd vote :+1: on that if this issue gets more backers.

In the meantime, I'd recommend:

- cloning the repo
- cd into it then `npm i`, 
- removing this [line](https://github.com/plotly/plotly.js/blob/de6a183ca5d40e597bf224a4a0f7a069adf3f44a/src/core.js#L21)
- running `npm run build` and
- then use the resulting `dist/plotly.js` bundle.

I hope this helps.

**Comment by rolandjitsu** [comment]
Thanks for the quick response, looks like a lot of work on the next version. It may make sense to have a patch with the promise polyfill removed already.

[Promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) are widely supported (IE not) and it always makes sense to let the user decide on which polyfill to use.

I prefer using npm to mange my dependencies, so rolling a build of my own is not something I would do. For now, I just include before angular deps, which still allows me to be up to date with the newer versions.

I think that a simple doc on including the promise polyfill for those that use browsers which don't support it yet, should be enough. I'm not sure though how much work would be required in order to remove the polyfill, but if it's just a [line](https://github.com/plotly/plotly.js/blob/de6a183ca5d40e597bf224a4a0f7a069adf3f44a/src/core.js#L21), I think it's worth doing it.

Thanks again 👍

**Comment by brian428** [comment]
Was this ever addressed? Trying to add plotly to an Angular 2 project and it is hanging the browser, probably because of the Promise conflict.

**Comment by amellnik** [comment]
Including it from the CDN in `index.html` and using `declare var Plotly: any;` in the controller is pretty hacky, but works fine for me in a few angular-cli apps.

**Comment by sn0wcat** [comment]
it seems to still be broken in angular/cli apps. The hack from amllnik works though.

**Comment by prateek0103** [comment]
@damienbod It would be helpful to publish the angular2 component to npm, open source community could then pick it up. Thanks for the tutorial.

**Comment by etpinard** [comment]
@arlowhite what tool are you using to bundle your app? plotly.js works best with browserify. Here's how to make it [work](https://github.com/plotly/plotly.js#webpack-usage-with-modules) with webpack.

**Comment by arlowhite** [comment]
@etpinard Thanks, but unfortunately, angular-cli hides webpack.config.json from you.

I updated my previous comment to describe how I got plotly.js working with angular-cli.

**Comment by prateek0103** [comment]
@arlowhite I have been down the same road. Projects built using Angular CLI don't offer any method to use custom loader which is required by `glslify` to work. Check out this [issue on angular-cli repo](https://github.com/angular/angular-cli/issues/1656) for more details. If you are using [basic charts](https://plot.ly/javascript/basic-charts/) and **_don't require_** GLSL, then you can go for `plotly-basic.js` which can be found in `node_modules/plotly.js/dist`.

**Comment by arlowhite** [comment]
@prateek0103 Ok, thanks. `dist/plotly.js` does load and renders the getting started plot. You think it will break if I use a plotly.js API that requires GLSL?

**Comment by yugi03** [comment]
@arlowhite : In response to your reply to @etpinard, now angular is exposing webpack.config.json. You can see it [here](https://github.com/angular/angular-cli/wiki/eject)

**Comment by szechyjs** [comment]
The following worked for me with angular-cli.

```sh
yarn add plotly.js
yarn add @types/plotly.js --dev
```

Add the following to `src/tsconfig.app.json`:
```json
{
  "compilerOptions": {
    ...
    "paths": {
      "plotly.js": [
        "../node_modules/plotly.js/dist/plotly.js"
      ]
    },
    ...
}
```

I haven't fully tested the use of `dist/plotly.js` it may break if GLSL plots are used, you can also use `dist/plotly-basic.js`, which should have no problems.

You can then utilize fully typed Plotly in your components:

```ts
import * as Plotly from 'plotly.js';
import {Config, Data, Layout} from 'plotly.js';
```

**Comment by rolandjitsu** [comment]
One addition to @szechyjs 's comment: do not use `{ ... "strict": true ... }` compiler option as it will not work.

**Comment by nikhilkalyankar** [comment]
I spent a whole day with  "browserify tranform glslify" issue associated with plotly.js and angular 2: 

> Uncaught Error: It appears that you're using glslify in browserify without its transform applied. Make sure that you've set up glslify as a source transform" 

 and finally this worked for me

`npm install plotly.js
`

Then include 
```
import * as Plotly from 'plotly.js/dist/plotly.js';
import { ScatterData } from 'plotly.js/dist/plotly.js';
...
const data = [ {
              x: ['giraffes', 'orangutans', 'monkeys'],
              y: [20, 14, 23],
              type: 'bar'
} as ScatterData];
Plotly.newPlot('myDiv', data);
...
```

https://github.com/plotly/plotly.js/blob/master/dist/README.md
> All plotly.js dist bundles inject an object Plotly into the global scope.

Additional helpful resource: 
https://stackoverflow.com/questions/39084438/how-to-import-plotly-js-into-typescript
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/plotly.js/test/index-tests.ts

**Comment by avbentem** [comment]
Just a heads up: using `plotly.js/dist/plotly-basic.js` rather than `plotly.js/dist/plotly.js` in the solutions above will get one a much smaller bundle. Of course, this limits the support to basic graphs only.

(Despite --an attempt of?-- tree shaking using Angular CLI's `--prod` flag, this still adds about 700 KB to my application, but the full one would add 2.32 MB for me.)

**Comment by cicinelli** [comment]
The following worked without any update to the tsconfig after importing plotly.js and types. Passing the nativeElement from the ViewChild reference allows me to mark-up multiple instances of the component on a single view.

`
import { Component, Input, OnInit, ViewChild } from "@angular/core";
import * as Plotly from "plotly.js/dist/plotly-basic.js";
import { Config, Data, Layout } from "plotly.js/dist/plotly-basic.js";

@Component({
  selector: "plotly-chart",
  template: `
    <div #plotly></div>
  `,
  styleUrls: ["./zeno-plotly-chart.component.scss"]
})
export class PlotlyChartComponent implements OnInit {
  @Input() data: any;
  @Input() layout: any;
  @Input() options: any;
  @ViewChild("plotly") plotly;

  constructor() {}

  ngOnInit() {
    Plotly.newPlot(
      this.plotly.nativeElement,
      this.data,
      this.layout,
      this.options
    );
  }
}
`

**Comment by saaniaki** [comment]
I'm using Angular 6 at the moment and I have problem with @type files (i.e. index.d.ts). The project complies fine and and everything is working but my IDE, which is Intellij WebStorm is not fully functioning.

I did what @szechyjs said but WebStorm is only suggesting the name of the functions and not providing any details. For example, for newPlot() function it only shows:
`newPlot(tsconfig$roots) . . . . main.newPlot`
in the popup menu.

In addition, I checked and I can not simply "ctrl + click" on the name of function or other imports like "Data" or "Layout" to go to the index.d.ts file.

What I did was to play with tsconfig.app.jason file and I changed the "paths" variable from:
`
    "paths": {
      "plotly.js": [
        "../node_modules/plotly.js/dist/plotly.js"
      ]
    }
`
to
`
    "paths": {
      "Plotly": [
        "../node_modules/plotly.js/dist/plotly.js"
      ]
    }
`
and suddenly WebStorm started to work! However, as you can guess, the project couldn't be compiled successfully anymore :(

Any suggestion to make Angular 6 to work with the new typing files?
