### ISSUE TITLE
Broken tutorial

### ISSUE THREAD

**Issue by djkashtan** [plotly/plotly.js#96]
I am on Ubuntu with Firefox 42 and Chrome Version 47.0.2526.80 (64-bit), but I cannot get an alert to fire when I click on a marker. I am not sure if the tutorial is broken or if plotly.js is broken...

**Comment by etpinard** [comment]
which tutorial?

**Comment by djkashtan** [comment]
The first one at: https://plot.ly/javascript/click-events/

My mistake for forgetting the link :/

**Comment by etpinard** [comment]
https://github.com/plotly/documentation/issues/243
