### ISSUE TITLE
[bug] Incorrect interpretation of SVG paths

### ISSUE THREAD

**Issue by pdziak** [plotly/plotly.js#961]
When I try to draw a shape using layout.shapes data array SVH path is not readed properly. For example: 
path M -2,2 Q 0,5 2,2 with control point value x1 = 0, y1 = 5,  y1 is placed on 3,5 when x1 value is OK. 

Tested on Firefox 48.0.2

![plotly](https://cloud.githubusercontent.com/assets/2017268/18726162/73d723c2-8043-11e6-8a63-2c20478fa31a.PNG)

**Comment by etpinard** [comment]
Can you share a reproducible example using codepen / jsFiddle / jsBin. Thanks.

**Comment by pdziak** [comment]
Yes, please.
Look at 0,5 control point.
https://jsfiddle.net/6ktmxmbs/5/

**Comment by rreusser** [comment]
@pdziak After checking with the [MDN SVG docs](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths#Curve_commands), the result looks to me like what I'd expect.

From what understand, you're asking for a path that:
- starts at -2, 2
- has a *control point* at 0, 5 (which defines the curve but which the path is *not* expected to pass through)
- ends at 2, 2

Unless I'm wrong, this is what it's drawing, right?

**Comment by pdziak** [comment]
@rreusser yes, indeed.

**Comment by rreusser** [comment]
All good. Thanks for the clear example! Is it alright to close this? In the future [http://community.plot.ly/](http://community.plot.ly/) is a great place to ask questions or get a second opinion before confirming the presence of a bug.
