### ISSUE TITLE
Stacked/Clustered bar charts 'plotly_click' should return which series was clicked

### ISSUE THREAD

**Issue by DevJazz** [plotly/plotly.js#965]
Hi, I am not sure whether this is a bug but I cannot find any resource about it online or in your bug list.

When subscribing to the 'plotly_onclick' listener on a stacked or clustered bar chart, the event currently returned is all the series within a category. However there is no property within the points to indicate which series in particular was clicked, only the category.

Is there a potential workaround for it at this time or could this eventually be implemented as a small tweak?

Thank you!

**Comment by etpinard** [comment]
Yeah. That would be great.

Someone has asked for it before in http://community.plot.ly/t/add-functionality/971/19

I can't think of an easy workaround unfortunately.

**Comment by DevJazz** [comment]
Ah okay that would be an excellent feature either way. Thank you for commenting back!

**Comment by eagor** [comment]
maybe, it's possible to capture click position, and use axis scales and traces data to calculate, which one would be positioned where click happend?

**Comment by etpinard** [comment]
Here's an UBER hacky solution: http://codepen.io/etpinard/pen/ZWwqoy

**Comment by DevJazz** [comment]
With Plotly version 1.21.2 (this could of also existed in earlier releases without realising), this is now possible, see the following codepen example:
[http://codepen.io/DeveloperJazz/pen/gwPWKA]

You can see that by setting the hovermode to 'closest' gives you the accuracy. Hope this helps! :)

**Comment by morgangraphics** [comment]
For those of you who are coming here looking for a solution to isolating what series you clicked on in a stacked bar chart and perhaps associating a key with that click and finding @DevJazz Code Pen missing.  I've added an example highlighting the `hovermode: 'closest'` functionality that is not well documented.  [https://codepen.io/DM00000](https://codepen.io/DM00000)

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
