### ISSUE TITLE
MathJax makes the legend scroll unnecessarily

### ISSUE THREAD

**Issue by rreusser** [plotly/plotly.js#966]
http://codepen.io/rsreusser/pen/mARpJd?editors=1010

<img width="198" alt="2016-09-22 10 48 51" src="https://cloud.githubusercontent.com/assets/572717/18753106/6269cf12-80b2-11e6-8ba2-31b54ff73461.png">

I get a scrollbar when my legend includes mathjax. In this case it's not catastrophic, but in [another example](http://demos.rickyreusser.com/elastodynamics/complex.html), I just had to drop the mathjax altogether because the legend names ended up blank if they included any mathjax.

**Comment by etpinard** [comment]
Oh MathJax

**Comment by rreusser** [comment]
Yeah, I'm assuming that it's because of asynchronous measuring/rendering passes. I mainly raise this because I feel like it's an argument in favor of KaTeX if the support ever becomes viable.

**Comment by etpinard** [comment]
Yeah. We've been wanting to switch over to KaTeX for about two years now.

I wonder how hard that would be?

**Comment by etpinard** [comment]
Most likely fixed as part of https://github.com/plotly/plotly.js/pull/2426
