### ISSUE TITLE
Show/Hide all traces as a single event

### ISSUE THREAD

**Issue by mdramos** [plotly/plotly.js#968]
**Feature request here**

It does not seem possible that all traces can be shown/hidden with one event. In the case where there are many traces and I want to compare small portions, hiding all and then selecting only the ones I want is a much simpler workflow than what is currently possible (deselecting all the ones I don't want).

The legend seems like the most obvious choice to put the event creator, but I wouldn't be opposed to having it in the toolbar as well.

**Comment by etpinard** [comment]
Can you clarify what you mean by _event_? 

- An event as in a user click / double-click interaction? or
- an event like the `plotly_` series the graph `<div>` emits?

**Comment by mdramos** [comment]
this: An event as in a user click / double-click interaction

**Comment by etpinard** [comment]
Here's two ways to do this: http://codepen.io/etpinard/pen/BLpVrG

I doubt that a _native_ hide / show all trace buttons would benefit a lot of users. Could you elaborate on the possible use cases?

**Comment by etpinard** [comment]
Would something like what's discussed in https://github.com/plotly/plotly.js/issues/674 satisfy your request?

**Comment by mdramos** [comment]
Thanks, the codepen example is close and seems like something I can build a custom solution with. The functionality I would like would be to only unselect them in the legend and remove from plot/chart, not an actually hiding of the legend (my mistake for any confusion).

I'm not sure about others, but my particular use case is when many country data points are plotted, and the user would like to easy compare only a few if those at a time without having to create new charting, and without having to manually unselect/hide all the unwanted traces.

#647, yes that would, as it is another option to easily hide all but wanted traces.

**Comment by etpinard** [comment]
Here's another example that keeps the legend: http://codepen.io/etpinard/pen/YGNjwL

I like the idea of adding multiple legend _modes_ to fine tuned legend click (or even double click) iterations. The exact details of the implementation aren't 100% clear to me and need to be worked out.

Would it be ok if I merge your issue with #674 ?

**Comment by mdramos** [comment]
Yes thats fine, thanks for the help!

**Comment by etpinard** [comment]
merged with #674
