### ISSUE TITLE
linear axis heatmaps show confusing data

### ISSUE THREAD

**Issue by hellochar** [plotly/plotly.js#969]
Hey Plotly,

It looks like heatmaps do non-obvious computation on heatmaps with linear scales. See http://codepen.io/hellochar/pen/BLpxmp which has:

```javascript
var data = [
  {
    x: [1,2,7],
    z: [[1, 20, 30], [20, 1, 60], [30, 60, 1]],
    type: 'heatmap'
  }
];

Plotly.plot('myDiv', data);
```

And outputs 
![image](https://cloud.githubusercontent.com/assets/1079495/18759737/d8b8b106-80cb-11e6-91ff-cdfa0e6baada.png)

The rendered chart is broken in the following ways: 
* the middle "x" value is shown as 3, when I put it at 2
* the third x value spans from 4.5 to 9.5 -- these numbers are made up! An arbitrary algorithm is computing widths based on neighboring data, but that's not at all what I asked for.

I think my expectation is that the axes are always categorical for heatmaps. What's the use case for heatmaps with linear axes? 

Thanks,
Xiaohan Zhang

**Comment by etpinard** [comment]
That is the intended behavior.

The relevant code block is [here](https://github.com/plotly/plotly.js/blob/48459784fe7ae5a6de7e7b2c757199b2aa1e4869/src/traces/heatmap/calc.js#L186-L214).

Heatmap traces that an `x.length` less or equal to the max row length of `z` are plotted using computed bricks in which the width of each brick is equal to the difference between each `x` value.

To control exactly where the bricks end up, try supplying one more `x` item as in http://codepen.io/etpinard/pen/ozByxL where now the `x` values correspond to the start and end of each brick. I hope this helps.

**Comment by hellochar** [comment]
Hmm, okay I see. Could you tell me the benefits of this behavior? I'm leaning towards always using `type: category`, but feel like I'm missing the point of this code

**Comment by etpinard** [comment]
> Could you tell me the benefits of this behavior?

Good question. I believe using the `x` values to find the brick widths makes the problem less susceptible to edge cases and interpretations then using `x` as the brick middle points, but I'm not the person who wrote this part.

**Comment by etpinard** [comment]
If you're looking for more implement Q&As, please have a look at our community forums at http://community.plot.ly/
