### ISSUE TITLE
colorbar draws outside the bounds

### ISSUE THREAD

**Issue by hellochar** [plotly/plotly.js#970]
Hey Plotly team,

Small bug - sometimes, depending on the layout's height/vertical margins, one of the colorbar's `.cbfill` will get drawn outside the outline (see http://codepen.io/hellochar/pen/JREjyv):
![image](https://cloud.githubusercontent.com/assets/1079495/18761582/81d98fba-80d3-11e6-8e20-93bdbf37e359.png)

Looks like it's only off by 1 pixel:

![image](https://cloud.githubusercontent.com/assets/1079495/18761654/d42c56e4-80d3-11e6-9c06-0eb6433521af.png)

It is a noticeable artifact that sometimes appears in our charts. Any ideas what's going on here? Happy to submit a PR as well if someone could help me understand the code at 
https://github.com/plotly/plotly.js/blob/master/src/components/colorbar/draw.js#L348

Thanks,
Xiaohan

**Comment by etpinard** [comment]
Thanks for the report.

**Comment by andi1984** [comment]
When `yanchor: 'bottom'` is used it is off by far more pixels also overlapping with mode bar. So this mode is pretty much not usable at the moment. It should simply set `y=0` on this mode.

**Comment by alexcjohnson** [comment]
@etpinard pointed out this issue when I mentioned a related one during #1906, so I might as well combine them and tackle them simultaneously:

> we're not doing crisp rendering of colorbars - particularly the outlines, but line levels should probably be crisp too

**Comment by alexcjohnson** [comment]
Looks like the original issue is masked in v1.29.0 - I suspect the tweaks in #1854 result in the outline covering the out-of-place bar - but there's still a `y="-1"` bar sometimes so I suspect it could become visible in certain cases. Frankly the whole concept of constructing our colorbars from 256 overlapping bars (regardless of how many pixels tall the bar is) seems a bit silly, I'm going to try to replace it with a simple gradient fill.

**Comment by rreusser** [comment]
@alexcjohnson This page: http://rickyreusser.com/plotly-mock-viewer/#contour_heatmap_coloring
Shows this:

<img width="348" alt="screen shot 2017-07-24 at 11 56 53" src="https://user-images.githubusercontent.com/572717/28539622-39b4d9f4-7067-11e7-8c48-1212880fdf78.png">

What do you see?

**Comment by alexcjohnson** [comment]
![screen shot 2017-07-24 at 3 16 26 pm](https://user-images.githubusercontent.com/2678795/28540376-1ffce26a-7083-11e7-8d12-8083fa0c8522.png)
@rreusser Yep, I see the missing lines there too.

**Comment by rreusser** [comment]
Good to know. Just wanted to be 100% sure we were all looking at identically the same code. I have a non-retina screen back at home that I can check out tonight. Anyone else able to confirm?

**Comment by rreusser** [comment]
<img width="686" alt="screen shot 2017-07-24 at 12 19 46" src="https://user-images.githubusercontent.com/572717/28540475-673edc6e-706a-11e7-9c02-301f4141c680.png">

**Comment by alexcjohnson** [comment]
possibly - `crispEdges` is what I was going to do to fix the other part of this anyway - just worried that this will lead to other instances where the line gets completely deleted too - typically that's even *easier* to do crisp than non-crisp.

**Comment by alexcjohnson** [comment]
My chrome just updated from v59 to v60 and these artifacts (along with a bunch of related antialiasing failures I've noticed) seem to have been fixed. So the `y="-1"` issue and crisp rendering change are still open but unless other people report these missing lines and other failures I think this is no longer urgent.

**Comment by etpinard** [comment]
Accidently automatically close by #2891 

![image](https://user-images.githubusercontent.com/6675409/44171233-bca96200-a0a7-11e8-8c98-44131738f191.png)

Github isn't smart enough yet to know that _would probably make it easier to finally close_ isn't equivalent to _close_.

**Comment by alexcjohnson** [comment]
Hah, maybe I should take that as a sign and just do ^^

**Comment by alexcjohnson** [comment]
@andi1984 I haven't been able to reproduce the `yanchor: 'bottom'` issue you mentioned. Maybe it was solved somewhere else, or maybe I just haven't found the other pieces required to exhibit it... if you still see this please open a new issue with a reproducible example.
