### ISSUE TITLE
histogram2d / heatmap with z: separate color for empty bins

### ISSUE THREAD

**Issue by ajrouvoet** [plotly/plotly.js#975]
2d histograms with `histfunc = avg|sum` are useful for plotting measurements on irregular 2D grids. 
The downside of this approach is that the representation of zero measurements collapses with e.g. n times a measurement of zero.

For these applications it would be useful if there was some way of either treating empty bins separately, or having the ability of setting a custom histfunc.

**Comment by etpinard** [comment]
That would be really nice to allow for a special _no-data_ color - even heatmap traces could benefit from it.

In the meantime, here's a workaround: http://codepen.io/etpinard/pen/xVoJoj?

**Comment by ElessarWebb** [comment]
If I were to implement this feature and submit a PR (assuming it wouldn't be too hard), what would be the timeline for it to end up in a release?

**Comment by etpinard** [comment]
> If I were to implement this feature and submit a PR [...] timeline for it to end up in a release

The next minor release ([`v1.18.0`](https://github.com/plotly/plotly.js/milestone/11)) should be out in about 7 to 10 days. We usually make minor release (i.e. release that add features) every two weeks or so.

>  (assuming it wouldn't be too hard)

Adding this feature will be similar to and have to touch the same files as PR https://github.com/plotly/plotly.js/pull/868

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
