### ISSUE TITLE
BarChart Color Grouping Issues

### ISSUE THREAD

**Issue by pgensler** [plotly/plotly.js#976]
Recently I was trying to create a barchart with ploty, and I think I may have came across a bug with regards to spacing of the bars using ggplotly, and the grouping command in conjunction with color causes some issues. Here is the stackoverflow thread outlining the issue in more detail:
http://stackoverflow.com/questions/39183203/grouped-bar-chart-with-grouping-in-plotly

**Comment by etpinard** [comment]
plotly.js bar traces don't have a `group` attribute at the moment. This appears to be an abstraction coming from the R library. Here's how to color bar _per-group_ in plotly.js http://codepen.io/etpinard/pen/JRNRbk

Reading through the SO post, i'm sure exactly what _spacing bug_ you're referring to. I suspect it is similar to what https://github.com/plotly/plotly.js/issues/930 is discussing. Can you confirm.

**Comment by etpinard** [comment]
Closing until further information

**Comment by sourcecode369** [comment]
Please fix this issue.
