### ISSUE TITLE
Dividers between subplots

### ISSUE THREAD

**Issue by Chris7** [plotly/plotly.js#977]
It is currently not possible (or at least documented) on how to add borders to subplots. 

When using plotly js to make facet plots with shared axes, they are far too difficult to use (even with a simple 2x2 data matrix) because the users cannot distinguish between plots.

If subplots could have borders, this would greatly increase the usability of js facet plots.

**Comment by etpinard** [comment]
Could you clarify what you mean by _border_ on subplots? If you could share a few screenshot, that would be very helpful. Thanks.

**Comment by etpinard** [comment]
@Chris7 can you help us out a little?

**Comment by Chris7** [comment]
Sorry about this -- got caught up with things. Here's a fiddle example:

https://jsfiddle.net/f2nt55dy/2/

The idea is to have a cross divider between the lines to distinguish between subplots. Some data configurations make it very difficult to distinguish between plots (especially when it goes to a 3x3 or 4x4 matrix!)

**Comment by etpinard** [comment]
You mean something like https://jsfiddle.net/f2nt55dy/3/ ?

**Comment by Chris7** [comment]
Ooo, clever. I like it. 

I know there are a ton of feature requests, but having something that specified that plot options like borders apply at a 'per subplot' level as well as a 'per entire plot' level (similar to how you can segment legends into tracegroups) would be nice. Feel free to close this or if you want to add a note for a feature request keep it open.

Thanks @etpinard !

**Comment by etpinard** [comment]
I'll leave it open. Thanks for taking the time to write us. 

One thing that makes this issue a little harder to implement is that plotly.js doesn't currently expose the notion of a cartesian subplot. plotly.js subplots are simply pairs of x/y axes.

So, we can't just add a `layout.subplot[0].border: true` attribute.

But at some point, we are planning on adding some subplot generating transform. Maybe subplot borders could be set as an option there.

**Comment by lgervich** [comment]
Are there any updates related to this issue?

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
