### ISSUE TITLE
R: error when data contains only 1 datapoint and color argument is passed

### ISSUE THREAD

**Issue by shosaco** [plotly/plotly.js#987]
See http://stackoverflow.com/questions/39752432/colors-in-plotly-4-x-for-r

This bug is visible in generation subplot or plots when a subplot or plot has only one datapoint.

Prerequisites:

1. the data has only one row,
2. and a color = argument is passed to plot_ly or add_trace.
3. and the column used for color has factor levels that are not present

     plot_ly(head(iris, 1), 
        x = ~Sepal.Length, y = ~Sepal.Width, color=~Species, colors = setNames("#FF5748", "setosa"),
        type = "scatter", mode = "markers")

      Error in if (has_attr(x$type, "colorscale")) x[["z"]] else NULL : argument is of length zero

The following workaround works fine:
     plot_ly(pdata, x = ~Sepal.Length, y = ~Sepal.Width, 
              color = factor(pdata$Species), colors = setNames("#FF5748", "setosa"), type = "scatter", mode = "markers")

**Comment by etpinard** [comment]
Can share a reproducible JavaScript example? Thanks.

cc @cpsievert

**Comment by shosaco** [comment]
Sorry, the R code snipped above is all I can offer... The markdown didn't work, sorry for that (why?).

**Comment by cpsievert** [comment]
This is an R issue, please report the issue here -- https://github.com/ropensci/plotly/issues/new
