### ISSUE TITLE
`on_hover`: pass MouseEvent to the user

### ISSUE THREAD

**Issue by CalvinFernandez** [plotly/plotly.js#988]
Currently, Plotly doesn't pass the raw MouseEvent to the user. I'd like to use clientX and clientY to determine the location of the user's cursor at the time the hover event was fired to render a custom tooltip. 

would like to augment the hover event, something like `on_hover: (data, event)`

**Comment by rreusser** [comment]
@etpinard we've been discussing object containers for data so that we can bundle more information along with event callbacks. I don't know precisely what this means for backwards compatibility (i.e. which fraction do this already), but perhaps this is a use-case.

**Comment by etpinard** [comment]
Yeah, that would be nice.

I'll referenced https://github.com/plotly/plotly.js/issues/168 and https://github.com/plotly/plotly.js/issues/145 but this request deserves a ticker of its own. Thanks @CalvinFernandez 

I would prefer that our `plotly_` events pass one lone object as event data, so maybe the signature could be:

```js
gd.on('plotly_hover', (eventData) => {
   eventData.event // => original Mouse Event object
});
```

Implementing for cartesian plots should be easy. Doing the same for our `gl3d` plots will be a bit of a headache though.

**Comment by rreusser** [comment]
Does this require a major version bump?

**Comment by etpinard** [comment]
> Does this require a major version bump?

Not if we link the event object to the existing `eventData` object.

**Comment by etpinard** [comment]
cc @n-riesco

**Comment by etpinard** [comment]
Done in https://github.com/plotly/plotly.js/pull/1505
