### ISSUE TITLE
Unify component `pad` logic

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#997]
PR https://github.com/plotly/plotly.js/pull/989 added `pad` to update menus, and PR https://github.com/plotly/plotly.js/pull/986 with to do same for sliders.

At the moment, colorbars are using `xpad` and `ypad` to determine their horizontal padding :arrow_right: we should switch them to `pad.l` + `pad.r` (++ add a backward-compatible `cleanLayout` step) and add support for `pad.t`  and `pad.b` while at it.

We should also allow legends, range selector and range sliders to set their own `pad` options.

**Comment by etpinard** [comment]
cc @rreusser

**Comment by rreusser** [comment]
Copying checklist from #985. :)

Update: Seems like a good idea. Checklist:

- [x] sliders
- [ ] colorbar
- [ ] rangeslider
- [ ] updatemenus
- [ ] review code for others?

**Comment by rreusser** [comment]
For reference, the procedure is pretty simple:

1. When computing its size, a component should, as a *final* step, add padding in each direction.
2. It sends this size to automargins
3. it must shift the content it draws (presumably by `pad.l` and `pad.t`)

**Comment by jensb** [comment]
Would this enable users to configure legend *entry* padding as well? (Not just the whole legend)
IMHO, the legend entries have too much padding around them especially when using smaller fonts. I would like to be able to configure this.

**Comment by etpinard** [comment]
@jensb you mean like in https://github.com/plotly/plotly.js/issues/881 ?

**Comment by jensb** [comment]
No, I meant the vertical padding. When using smaller font sizes, the padding between legend rows is (IMHO) too large. I think it's hardcoded as 5 pixels in both direction. I would like to be able customize this padding, e.g. using a configuration variable.

**Comment by jensb** [comment]
Can somebody please have a look at this and maybe give me a hint how to make legend entry padding configurable? I'm not afraid of hacking by myself and creating a pull request, but I need some startup assistance. Thank you!

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
